### ISSUE TITLE
Docker-machine env command takes ~150ms to run

### ISSUE THREAD

**Issue by lox** [docker/machine#1007]
After putting `docker-machine env` in my `.profile`, I'm seeing around 150ms of shell boot up time.

Should this really be taking that long to run?

```bash
 ~/  › time docker-machine env
export DOCKER_TLS_VERIFY=yes
export DOCKER_CERT_PATH=xxx
export DOCKER_HOST=xxx
docker-machine env  0.04s user 0.03s system 43% cpu 0.173 total
```

**Comment by nathanleclaire** [comment]
I'm not 100% positive, but I think that a majority of that time is the driver doing its thing to get access to the IP address for `DOCKER_HOST`.

For instance, consider the following sequence of events:

1. `docker-machine start foo`
2. The IP address has changed (this happens with VBox, Amazon, and other drivers)
3. `eval $(docker-machine env foo)` has to call out to figure out what the new IP is, or else it won't work

So, I think it might be unavoidable, but never say never.  What's the driver you're using here?
