### ISSUE TITLE
DigitalOcean bugs

### ISSUE THREAD

**Issue by jerng** [docker/machine#102]
1. (machine ls) goes out of sync with the machines listed at DO's web GUI. Specifically, (machine) assumes droplets are dead when they are still alive. How hard is it to hit the API properly?
2. No obvious way to affect DO host's configuration - hosts are set up without SSH access (though you can reboot from web GUI to set a root password). First thing that became an issue was that DO's default "no swap" configuration on the host seemed to cause MySQLd to fail upon startup inside a container when it tried to mmap 128MB of InnoDB buffer, on a 512MB host.
3. Random failures of communication between (machine) and DO, but this happens on Tugboat too. No surprises there.

This was all done on the SG region. I'm in MY.

**Comment by ehazlett** [comment]
Closing as there do not appear to be issues.  Please re-open if you have them again.  Thanks
