### ISSUE TITLE
vmwarefusion driver errors with 'fail to create'

### ISSUE THREAD

**Issue by jayed** [docker/machine#1021]
Creating a vmwarefusion machine errs out with "fail to create" while actually creating the machine.

Jays-MacBook-Air-2:Downloads jayed$ docker-machine -D create -d vmwarefusion localvm
INFO[0000] Creating SSH key...                          
DEBU[0000] executing: /usr/local/bin/ssh-keygen ssh-keygen -t rsa -N  -f /Users/jayed/.docker/machine/machines/localvm/id_rsa
 
Generating public/private rsa key pair.
Your identification has been saved in /Users/jayed/.docker/machine/machines/localvm/id_rsa.
Your public key has been saved in /Users/jayed/.docker/machine/machines/localvm/id_rsa.pub.
The key fingerprint is:
6e:85:e3:83:cc:b6:f2:b6:79:92:5c:bc:35:8b:73:d0 jayed@Jays-MacBook-Air-2.local
The key's randomart image is:
+---[RSA 2048]----+
|                 |
|                 |
|                 |
|         .       |
|       .S..      |
|     o ++oE      |
|     .=o== o     |
|    ..=+=.o      |
|     +=+ o       |
+-----------------+
INFO[0000] Creating VM...                               
VixDiskLib: Invalid configuration file parameter. Failed to read configuration file.
Creating disk '/Users/jayed/.docker/machine/machines/localvm/localvm.vmdk'
Virtual disk creation successful.
DEBU[0000] executing: /Applications/VMware Fusion.app/Contents/Library/vmrun start /Users/jayed/.docker/machine/machines/localvm/localvm.vmx nogui 
INFO[0000] Waiting for VM to come online...             
DEBU[0000] MAC address in VMX: 00:0c:29:0c:bb:30        
DEBU[0000] IP found in DHCP lease table: 172.16.164.135 
DEBU[0000] Got an ip: 172.16.164.135                    
ERRO[0020] Error creating machine: dial tcp 172.16.164.135:22: connection refused 
WARN[0020] You will want to check the provider to make sure the machine and associated resources were properly removed. 
FATA[0020] Error creating machine                       
Jays-MacBook-Air-2:Downloads jayed$ docker-machine ls
NAME      ACTIVE   DRIVER         STATE     URL                         SWARM
local              virtualbox     Running   tcp://192.168.99.100:2376   
localvm   *        vmwarefusion   Running   tcp://172.16.164.135:2376

**Comment by jayed** [comment]
The SSH connection is refused because the boot2docker instance isn't doing key authentication; it wants a password. 

Jays-MacBook-Air-2:Downloads jayed$ docker-machine ssh
docker@172.16.164.135's password: 
docker@172.16.164.135's password: 
docker@172.16.164.135's password: 
FATA[0004] exit status 255

**Comment by jayed** [comment]
The docker user does not have an authorized_keys file.

docker@boot2docker:~/.ssh$ pwd
/home/docker/.ssh
docker@boot2docker:~/.ssh$ ls -al
total 4
drwx--S---    2 docker   staff           60 Apr 17 01:37 ./
drwxr-sr-x    5 docker   staff          180 Apr 17 01:37 ../
-rw-r--r--    1 docker   staff          171 Apr 17 01:37 known_hosts

**Comment by jayed** [comment]
I've got about a 40% success rate. It seems to occur randomly. Here's another failure. The machine is created in VMWare and boots up just fine. 

Jays-MacBook-Air-2:localvm jayed$ docker-machine -D create -d vmwarefusion localvm3
INFO[0000] Creating SSH key...                          
DEBU[0000] executing: /usr/local/bin/ssh-keygen ssh-keygen -t rsa -N  -f /Users/jayed/.docker/machine/machines/localvm3/id_rsa
 
Generating public/private rsa key pair.
Your identification has been saved in /Users/jayed/.docker/machine/machines/localvm3/id_rsa.
Your public key has been saved in /Users/jayed/.docker/machine/machines/localvm3/id_rsa.pub.
The key fingerprint is:
93:d8:8a:09:50:1e:ae:8a:e6:55:ee:e6:96:77:36:22 jayed@Jays-MacBook-Air-2.local
The key's randomart image is:
+---[RSA 2048]----+
|  o              |
| + .             |
|. o              |
| o     o .       |
|. .  .. S        |
|o  .oo . .       |
|o. .o.o          |
|o . .E o +       |
| .  +oo + .      |
+-----------------+
INFO[0000] Creating VM...                               
VixDiskLib: Invalid configuration file parameter. Failed to read configuration file.
Creating disk '/Users/jayed/.docker/machine/machines/localvm3/localvm3.vmdk'
Virtual disk creation successful.
DEBU[0000] executing: /Applications/VMware Fusion.app/Contents/Library/vmrun start /Users/jayed/.docker/machine/machines/localvm3/localvm3.vmx nogui 
INFO[0000] Waiting for VM to come online...             
DEBU[0000] MAC address in VMX: 00:0c:29:3d:75:c8        
DEBU[0000] Not there yet 1/60, error: IP not found for MAC 00:0c:29:3d:75:c8 in DHCP leases 
DEBU[0002] MAC address in VMX: 00:0c:29:3d:75:c8        
DEBU[0002] Not there yet 2/60, error: IP not found for MAC 00:0c:29:3d:75:c8 in DHCP leases 
DEBU[0004] MAC address in VMX: 00:0c:29:3d:75:c8        
DEBU[0004] Not there yet 3/60, error: IP not found for MAC 00:0c:29:3d:75:c8 in DHCP leases 
DEBU[0006] MAC address in VMX: 00:0c:29:3d:75:c8        
DEBU[0006] Not there yet 4/60, error: IP not found for MAC 00:0c:29:3d:75:c8 in DHCP leases 
DEBU[0008] MAC address in VMX: 00:0c:29:3d:75:c8        
DEBU[0008] Not there yet 5/60, error: IP not found for MAC 00:0c:29:3d:75:c8 in DHCP leases 
DEBU[0010] MAC address in VMX: 00:0c:29:3d:75:c8        
DEBU[0010] Not there yet 6/60, error: IP not found for MAC 00:0c:29:3d:75:c8 in DHCP leases 
DEBU[0012] MAC address in VMX: 00:0c:29:3d:75:c8        
DEBU[0012] Not there yet 7/60, error: IP not found for MAC 00:0c:29:3d:75:c8 in DHCP leases 
DEBU[0014] MAC address in VMX: 00:0c:29:3d:75:c8        
DEBU[0014] Not there yet 8/60, error: IP not found for MAC 00:0c:29:3d:75:c8 in DHCP leases 
DEBU[0016] MAC address in VMX: 00:0c:29:3d:75:c8        
DEBU[0016] Not there yet 9/60, error: IP not found for MAC 00:0c:29:3d:75:c8 in DHCP leases 
DEBU[0018] MAC address in VMX: 00:0c:29:3d:75:c8        
DEBU[0018] Not there yet 10/60, error: IP not found for MAC 00:0c:29:3d:75:c8 in DHCP leases 
DEBU[0020] MAC address in VMX: 00:0c:29:3d:75:c8        
DEBU[0020] IP found in DHCP lease table: 172.16.164.137 
DEBU[0020] Got an ip: 172.16.164.137                    
ERRO[0020] Error creating machine: dial tcp 172.16.164.137:22: connection refused 
WARN[0020] You will want to check the provider to make sure the machine and associated resources were properly removed. 
FATA[0020] Error creating machine

**Comment by frapposelli** [comment]
Can't reproduce right now, @jayed what version of Fusion are you using?

**Comment by jayed** [comment]
@frapposelli I'm using 7.1. I rolled a custom version of docker-machine that puts a 5 second sleep after "Got an IP" and can't repro it. The original version still spits out the error periodically.

**Comment by frapposelli** [comment]
Will work on this over the weekend, thanks for reporting

**Comment by frapposelli** [comment]
This PR should fix it https://github.com/docker/machine/pull/1034
