### ISSUE TITLE
Broken download link for windows Installation Guide

### ISSUE THREAD

**Issue by weifengbao** [docker/machine#1026]
In the Windows section, it listed install the Docker Machine binary:

curl https://github.com/docker/machine/releases/docker-machine_windows-amd64.exe

However, the link appears is broken.  Returns: {"error":"Not Found"}

The following command works:

curl -L https://github.com/docker/machine/releases/download/v0.2.0/docker-machine_windows-amd64.exe > /bin/docker-machine

**Comment by nathanleclaire** [comment]
Dang, it should be this.  I will make a PR to correct it
