### ISSUE TITLE
Issues with restarting the docker daemon and /var/run/docker.sock

### ISSUE THREAD

**Issue by far-blue** [docker/machine#1027]
I'm seeing a problem with restarting the docker daemon when there are auto-starting containers that link to the /var/run/docker.sock socket, the jwilder/nginx-proxy being one example. The result is that docker is unable to create the socket after restart.

To create the situation:
1) create a new virtualbox-backed docker-machine
2) create and start a container from the jwilder/nginx-proxy image with a restart policy of always
3) ssh into the vm
4) restart the docker daemon using the init.d script

This results in:
1) /var/run/docker.sock is created as a directory
2) docker is unable to create the socket
3) the proxy container can no longer talk to the daemon

Furthermore, because a directory is created, all future restarts will fail until the directory is manually removed.

The commands I used for the above would be:
`docker-machine create --driver=virtualbox dev`
`docker run -d -p 80:80 --restart=always -v /var/run/docker.sock:/tmp/docker.sock jwilder/nginx-proxy`
`docker-machine ssh`
`sudo /etc/init.d/docker restart`

This has been tested using docker-machine 0.2.0 and the 1.6.0 boot2docker image from 16th April 2015

**Comment by errordeveloper** [comment]
May be related to boot2docker/boot2docker#844.

**Comment by nathanleclaire** [comment]
This seems more like a docker/docker issue than a Docker Machine issue.  I'm not sure what we could do to help with this, but please feel free to open a new issue if you have ideas.
