### ISSUE TITLE
docker server certificate -- requires exact ip match?

### ISSUE THREAD

**Issue by jamshid** [docker/machine#1030]
Let's say I have two machines: my desktop machine running docker in Virtual Box, and my laptop where I want to run the docker client.

I created a Virtual Box docker server named "docker" on my desktop with:
```
docker-machine create --driver=virtualbox --virtualbox-memory=9000 --virtualbox-disk-size=50000 docker
```
I'm trying to access that docker server from my laptop (OSX).

I'm running this ssh tunnel between my laptop and my desktop, exposing the docker server port on my laptop's localhost port 12376. This requires me to be able to ssh from my laptop to my desktop, but seems secure.

`ssh -nNT -L 12376:192.168.99.100:2376 MYDESKTOP`

I already copied the docker server's certs, i.e. copied /var/lib/boot2docker/tls ca.pem cert.pem key.pem to my laptop's ~/.docker-tls.

But docker only wants to talk to a specific ip:

```
$ export DOCKER_CERT_PATH=~/.docker-tls
$ export DOCKER_TLS_VERIFY=1
$ export DOCKER_HOST=tcp://localhost:12376
$ docker ps
FATA[0000] An error occurred trying to connect: Get https://127.0.0.1:12376/v1.17/containers/json: x509: certificate is valid for 192.168.99.100, not 127.0.0.1 
```

Is there any way to tell docker client to trust the certificate and ignore its hostname/ip? Or is there a better way to tunnel a docker server port?

**Comment by jamshid** [comment]
I see `certs.go` `newCertificate()` sets the Subject Name "Organization" to the docker-machine name. 
https://github.com/docker/machine/blob/344c7d771afd681322d543891df948db8749cb7b/utils/certs.go
```
func newCertificate(org string) (*x509.Certificate, error) {
...
	return &x509.Certificate{
		SerialNumber: serialNumber,
		Subject: pkix.Name{
			Organization: []string{org},
		},
```
Maybe it should set the "Common Name" to that too too? Then as long as I access the server by that hostname (eg. add "127.0.0.1 docker" to my `/etc/hosts` and set `DOCKER_HOST=tcp://docker:12376`), the docker client would validate the cert.

Or, allow a series of alternative hostnames or ip's to be passed down, currently the array only contains a single ip:

https://github.com/docker/machine/blob/339267198840eefa6508c1de509b13af3c77884f/libmachine/provision/utils.go
```
func ConfigureAuth(p Provisioner, authOptions auth.AuthOptions) error {
...
        err = utils.GenerateCert(
		[]string{ip},
```

**Comment by jamshid** [comment]
Yup, setting "CommonName" allows `docker` client on my laptop to validate the cert, even through an ssh tunnel to the docker server running in a Virtual Box on my desktop. Code diff below.

Had some trouble figuring out which cert files I needed on my laptop. I assumed all the .pem files I need are in /var/lib/boot2docker/tls, but `./docker-machine_darwin-amd64 regenerate-certs docker` did not seem to update that directory, and `cert.pem` isn't even in the file system.

Got it working by copying some of the .pem's from my desktop:
```
ssh MYDESTOP tar -cf - -C .docker/machine/machines/docker/ ca.pem cert.pem key.pem | tar -xvf - -C ~/.docker-tls
ssh -nNT -L 12376:192.168.99.100:2376 MYDESKTOP  # tunnel to docker on docker vm
ssh -nNT -L 12022:localhost:57040 MYDESKTOP   # tunnel to ssh on docker vm
export DOCKER_CERT_PATH=~/.docker-tls
export DOCKER_TLS_VERIFY=1
export DOCKER_HOST=tcp://docker:12376  # my /etc/hosts has "127.0.0.1  docker"
docker ps   # yay, able to securely use by desktop's virtual box docker-machine
```

diff --git a/utils/certs.go b/utils/certs.go
index 84361f7..4341a21 100644
--- a/utils/certs.go
+++ b/utils/certs.go
@@ -51,6 +51,7 @@ func newCertificate(org string) (*x509.Certificate, error) {
                SerialNumber: serialNumber,
                Subject: pkix.Name{
                        Organization: []string{org},
+                       CommonName: org,
                },
                NotBefore: notBefore,
                NotAfter:  notAfter,
```

**Comment by themasterchef** [comment]
I get almost exactly the same error when using Kitematic (which bundles docker-machine) + a hostname (also defined in /etc/hosts) for the active docker machine instead of an IP address.

As previously found, this is most likely happening because CN is not being set yet. This would need to be fixed before this setup can actually work.

------

Result of using DOCKER_HOST with IP address:

```
$ env DOCKER_HOST=tcp://192.168.99.100:2376 docker info
Containers: 52
...[it works]...
```

Result of using it with the active docker-machine name:

```
$ env DOCKER_HOST=tcp://dev:2376 docker info                  
FATA[0000] An error occurred trying to connect: Get https://dev:2376/v1.18/info: x509: certificate is valid for , not dev
```

Content of /etc/hosts file:

```
##
# Host Database
#
# localhost is used to configure the loopback interface
# when the system is booting.  Do not change this entry.
##
127.0.0.1	localhost
255.255.255.255	broadcasthost
::1             localhost 

# Docker host
192.168.99.100  dev
```

System:
* OS X 10.10.3
* Docker version 1.6.2, build 7c8fca2
* docker-machine version 0.2.0 (8b9eaf2)

**Comment by ehazlett** [comment]
Correct.  This is how the TLS config works.  It currently uses the IP SAN for communication.  There is a PR open to allow more SANs during creation (#1228).

**Comment by nathanleclaire** [comment]
@jamshid Maybe you could make some specific propsals for features, including how they would be integrated with the Machine CLI, to follow up on this?  There's a couple different threads in this issue.

**Comment by jamshid** [comment]
I think being able to specify multiple `--tls-san` when creating machine or regenerating certs covers my use case, so I think https://github.com/docker/machine/pull/1228 resolves this.
