### ISSUE TITLE
Cannot build 'env' output from 'inspect' output

### ISSUE THREAD

**Issue by hamiltont** [docker/machine#1041]
I'm trying to interface with `docker-machine` from an external program using `inspect`. Some information seems to be missing. Using the digitalocean driver, I see 

```
$ docker-machine env
export DOCKER_TLS_VERIFY=1
export DOCKER_CERT_PATH="/Users/hamiltont/.docker/machine/machines/staging"
export DOCKER_HOST=tcp://104.236.9.119:2376
```

When I run `inspect`, I don't find the `2376` anywhere in the output, and the value of `TlsVerify` seems to disagree with `DOCKER_TLS_VERIFY` above. I know that [2376 is the recommended port](https://github.com/docker/docker/blob/master/docs/sources/articles/https.md), but without it being output from `inspect` I'm hard-coding an implementation detail of `docker-machine` if I assume it's always 2376. 

```
$ docker-machine inspect
{
    "DriverName": "digitalocean",
    "Driver": {
        "AccessToken": "<snip>",
        "DropletID": <snip>,
        "DropletName": "",
        "Image": "ubuntu-14-04-x64",
        "MachineName": "staging",
        "IPAddress": "104.236.9.119",
        "Region": "nyc3",
        "SSHKeyID": 773910,
        "SSHUser": "root",
        "SSHPort": 22,
        "Size": "512mb",
        "IPv6": false,
        "Backups": false,
        "PrivateNetworking": false,
        "CaCertPath": "/Users/hamiltont/.docker/machine/certs/ca.pem",
        "PrivateKeyPath": "/Users/hamiltont/.docker/machine/certs/ca-key.pem",
        "DriverKeyPath": "",
        "SwarmMaster": false,
        "SwarmHost": "tcp://0.0.0.0:3376",
        "SwarmDiscovery": ""
    },
    "StorePath": "/Users/hamiltont/.docker/machine/machines/staging",
    "HostOptions": {
        "Driver": "",
        "Memory": 0,
        "Disk": 0,
        "EngineOptions": {
            "Dns": null,
            "GraphDir": "",
            "Ipv6": false,
            "Labels": null,
            "LogLevel": "",
            "StorageDriver": "",
            "SelinuxEnabled": false,
            "TlsCaCert": "",
            "TlsCert": "",
            "TlsKey": "",
            "TlsVerify": false,
            "RegistryMirror": null
        },
        "SwarmOptions": {
            "IsSwarm": false,
            "Address": "",
            "Discovery": "",
            "Master": false,
            "Host": "tcp://0.0.0.0:3376",
            "Strategy": "",
            "Heartbeat": 0,
            "Overcommit": 0,
            "TlsCaCert": "",
            "TlsCert": "",
            "TlsKey": "",
            "TlsVerify": false
        },
        "AuthOptions": {
            "StorePath": "/Users/hamiltont/.docker/machine/machines/staging",
            "CaCertPath": "/Users/hamiltont/.docker/machine/certs/ca.pem",
            "CaCertRemotePath": "",
            "ServerCertPath": "/Users/hamiltont/.docker/machine/certs/server.pem",
            "ServerKeyPath": "/Users/hamiltont/.docker/machine/certs/server-key.pem",
            "ClientKeyPath": "/Users/hamiltont/.docker/machine/certs/key.pem",
            "ServerCertRemotePath": "",
            "ServerKeyRemotePath": "",
            "PrivateKeyPath": "/Users/hamiltont/.docker/machine/certs/ca-key.pem",
            "ClientCertPath": "/Users/hamiltont/.docker/machine/certs/cert.pem"
        }
    },
    "SwarmHost": "",
    "SwarmMaster": false,
    "SwarmDiscovery": "",
    "CaCertPath": "",
    "PrivateKeyPath": "",
    "ServerCertPath": "",
    "ServerKeyPath": "",
    "ClientCertPath": "",
    "ClientKeyPath": ""
}
```

Using the `virtualbox` driver, I don't see the the `IPAddress` field, even though `docker-machine ip` returns the correct IP address.

**Comment by hairyhenderson** [comment]
:+1: I ran into this while working on #921. 

There are two separate issues here, really:
1. not all drivers expose an IP Address, and to make matters worse, those that do sometimes spell `IPAddress` differently.
2. the Docker port is hard-coded in a bunch of places to 2376. For now, you can assume it'll always be 2376... We _could_ add it in the `inspect` output too - the place that makes the most sense to me is `HostOptions.EngineOptions`.

I'll see if I can hack up some fixes for these...

Ideally, it'd be cool if you could do something like: `docker-machine inspect -f 'tcp://{{ .Driver.IPAddress }}:{{ .HostOptions.EngineOptions.Port }}'` to get a string equivalent to `DOCKER_HOST`.

**Comment by hamiltont** [comment]
1 - Perhaps you re-use the code path for `docker-machine ip` - if that returns a result, then ensure it's exposed using a common key like `IPAddress` (even if that means you'd occasionally see stuff like `IPaddress` and `IPAddress`, IMO it's ok to duplicate the data so the user of inspect can rely on that key being set if there is an ip address available)
2 - Hardcoded it for now, and either approach sounds fine to me. Thanks for looking

**Comment by ehazlett** [comment]
I agree this would be beneficial.  I would also like to remove the hard coded port throughout machine as well.

**Comment by nathanleclaire** [comment]
Heh... it's the `EngineOptions.TlsVerify` which has the wrong value here, not the env var... we simply set an empty struct so it defaults to false.  I'll make sure to include setting that correctly in the engine options PR.

**Comment by ehazlett** [comment]
@nathanleclaire :+1:

**Comment by hairyhenderson** [comment]
@nathanleclaire - lol, apparently I totally mis-read the issue... My comments were heavily influenced by an IRC chat with @hamiltont, so I was focused on the IP address and port issues. :)

**Comment by hairyhenderson** [comment]
@hamiltont - is this closable yet? @nathanleclaire's engine options PR got merged recently so in theory that part is fixed.

**Comment by nathanleclaire** [comment]
@hairyhenderson I think we still need to actually set the option in the struct (should be a ~1 line change unless I'm mis-remembering).

**Comment by nathanleclaire** [comment]
So I think this is close-able, and modifying the exposed port should be something we take care of in the future.
