### ISSUE TITLE
'inspect' should include VM status for virtualbox driver

### ISSUE THREAD

**Issue by hamiltont** [docker/machine#1042]
When using `virtualbox` driver, I noticed that running `env` will fail if you have not run `start`. However, as far as I can see there is no output in `inspect` that tells me if the machine is started or not. It would be nice to have this info included under the `Driver` section

```
$ docker-machine inspect
{
    "DriverName": "virtualbox",
    "Driver": {
        "CPU": -1,
        "MachineName": "webjuice",
        "SSHUser": "docker",
        "SSHPort": 60009,
        "Memory": 1024,
        "DiskSize": 20000,
        "Boot2DockerURL": "",
        "CaCertPath": "/Users/hamiltont/.docker/machine/certs/ca.pem",
        "PrivateKeyPath": "/Users/hamiltont/.docker/machine/certs/ca-key.pem",
        "SwarmMaster": false,
        "SwarmHost": "tcp://0.0.0.0:3376",
        "SwarmDiscovery": ""
    },
<snip>
$ docker-machine start webjuice
INFO[0003] Waiting for VM to start...
$ docker-machine inspect
{
    "DriverName": "virtualbox",
    "Driver": {
        "CPU": -1,
        "MachineName": "webjuice",
        "SSHUser": "docker",
        "SSHPort": 60009,
        "Memory": 1024,
        "DiskSize": 20000,
        "Boot2DockerURL": "",
        "CaCertPath": "/Users/hamiltont/.docker/machine/certs/ca.pem",
        "PrivateKeyPath": "/Users/hamiltont/.docker/machine/certs/ca-key.pem",
        "SwarmMaster": false,
        "SwarmHost": "tcp://0.0.0.0:3376",
        "SwarmDiscovery": ""
    },
<snip>
```

**Comment by ehazlett** [comment]
Thanks for the feedback.  I think we could add the result from `GetState` to inspect.

**Comment by hamiltont** [comment]
Great, thanks for looking!

**Comment by ehazlett** [comment]
@hairyhenderson thoughts on this one?  it would be similar to the `GetIP` I would imagine right?

**Comment by hairyhenderson** [comment]
Hrm... I've always just used `machine ls` to figure out whether a machine is up or not :)

Right now, the `inspect` command just takes the current state of the `Host` and turns it into a map. We don't actually call `GetIP` to get the IP address, we just let the current state of `Driver.IPAddress` show up (where present - *cough* #1043 *cough*).

For something like the result from `GetState` though, it really would be best to have `inspect` report the current state, and not risk the cache being out of date. It feels a little odd, but we could inject the state into the map during the `inspect` command...

**Comment by ehazlett** [comment]
@hairyhenderson yeah that's kind of what i was thinking (inject state into map) although I agree it feels a bit odd.  

@nathanleclaire thoughts?

**Comment by nathanleclaire** [comment]
Yes, I've always used `ls` to check machine status although I don't think it is a very machine-readable approach.  To that extent maybe we could add a `machine status foo` command if there is demand for it.

My original goal for `inspect` was just to have a very quick way of querying the json file on disk which describes the saved machine properties, so if we aren't saving it in there, I don't really expect to get it back.  (That said, in the future I would like to have a way to actually query all of the "real time" properties of the instance in case something changed).

**Comment by hairyhenderson** [comment]
@nathanleclaire - I think that's a good goal for `inspect`. Maybe the best of both worlds could be to add some sort of `--update` flag to `inspect` to explicitly tell it "make sure you're getting the latest information, and I don't care if it takes a few seconds to query a bunch of stuff first."

I do like the idea of having a `State` value somewhere in the `inspect` output, even if it's (potentially) stale. Maybe some sort of `UpdateState` method could be added to the `Driver` interface, then these sorts of properties could be updated in that method, and the driver could call that at the end of `Create`, `Start`, `Stop`, `Restart`, etc... to make sure the state is more-or-less up to date.

**Comment by hamiltont** [comment]
As a total newbie to the project, I thought `inspect` would always return fresh output that could then be fed into external programs. Using a flag for this "update everything before returning to me" seems quite reasonable to me

**Comment by hairyhenderson** [comment]
Given that `docker inspect` _always_ returns fresh output, it's actually a pretty natural assumption that `docker-machine inspect`'s output would be fresh...

Maybe we should handle this in the usage message, and mention something like `...provides reasonably recent information about a machine...` (I don't like that wording, but...)?

The problem with altering `inspect` to be consistent with reality is that performance suffers considerably. `docker inspect` is hitting a single (and often local) REST API, whereas `docker-machine inspect` would hit a bunch of different APIs often on faraway hosts. But maybe that's OK.

**Comment by hamiltont** [comment]
perhaps `docker-machine inspect --no-cache` would suffice?

**Comment by hairyhenderson** [comment]
So, with a few days of mulling this about in my head, I think I like more and more the idea of changing the way `inspect` is designed to be more consistent with reality (i.e. query the provider for the up-to-date state first, then return it to the user). It's a slower model, but I think that's acceptable.

With that model, we'd preserve the current behaviour with something like `docker-machine inspect --cached`.

We could even be extra-clever and hit the cache if it's been updated within the past 5mins or so, so that I can run multiple `inspect -f ...` commands without taking dog's age each time. 

@ehazlett, @nathanleclaire - any thoughts on this?

**Comment by nathanleclaire** [comment]
Don't you feel that this will be _extremely_ difficult and time-consuming to get correct?  Trying to provide true consistency for every single field you can get back from `inspect` has a lot of surface area to consider.  What happens if the user goes and changes the daemon options that they originally created the instance with?  Do we support tracking that too?  What about re-sizing an existing instance to have more memory?  That will also have to be tracked if we're trying to provide consistency guarantees.  I don't know, it strikes me as really fraught with peril.

**Comment by hairyhenderson** [comment]
@nathanleclaire - ok, you're absolutely right. I hadn't thought about this quite that deeply ;)

So... that brings us back to what to do about having the VM state in the `inspect` output. Should we start caching the VM's state, updating it at opportune times like during `Driver.Start` and `Driver.Stop`? I think this would be reasonably simple and not too misleading...

**Comment by hamiltont** [comment]
Isn't one main point of the docker machine project to deal with that wide
surface area?

Re 5-minute cache, I think that would only be useful if a --no-cache flag
was provided to disable it. Otherwise external programs(or impatient users
;-) ) could not poll inspect

**Comment by hamiltont** [comment]
To clarify: I definitely don't think you should standardize the entire set
of returned keys, but choosing a small set that is always correct seems
very beneficial

**Comment by ehazlett** [comment]
I think perhaps doing it on start/stop as @hairyhenderson is a good compromise.  I agree with @nathanleclaire that it would be very time consuming and a great potential for failure if we tried every field.  However, I think updating common fields that we perhaps get each start/stop would be better than what we have.

**Comment by hamiltont** [comment]
Works for me! You guys know way more about how in/feasible it is to
implement any of this, my main concern as a user is to get an interface
that's consistent enough for an external program to rely on :-)​

**Comment by nathanleclaire** [comment]
I would much rather have a `docker-machine status` command -- So I'm going to file an issue for that.
