### ISSUE TITLE
Add docs for b2d migration

### ISSUE THREAD

**Issue by nathanleclaire** [docker/machine#1047]
When https://github.com/docker/machine/pull/979 it will need docs to assist users in the migration from boot2docker to machine (this usage is self-evident to us, but not clear to new users). Let's add them!  cc @ehazlett @SvenDowideit @tianon

**Comment by ehazlett** [comment]
@nathanleclaire thanks!  You beat me to the issue :)

**Comment by ehazlett** [comment]
Closing this -- we can continue the review in #1051
