### ISSUE TITLE
Start Swarm cluster using docker-machine

### ISSUE THREAD

**Issue by arun-gupta** [docker/machine#1052]
`docker-machine start --help` shows:

```
~> docker-machine start --help
NAME:
   start - Start a machine

USAGE:
   command start [arguments...]

DESCRIPTION:
   Argument(s) are one or more machine names. Will use the active machine if none is provided.
```

An option should be added that will allow to start the complete cluster. This could be something like:

`docker-machine start --swarm swarm-master`

`swarm-master` is the master, and this should start the other nodes as well.

Without this command, multiple commands need to be given:

```
docker-machine start swarm-master
docker-machine start swarm-node-01
docker-machine start swarm-node-02
```

**Comment by nathanleclaire** [comment]
@arun-gupta I think `docker-machine start nodeA nodeB nodeC` should do it for you, does it not work?

**Comment by arun-gupta** [comment]
@nathanleclaire The command does work but this would require the knowledge of all machines in the cluster. The command should either take the discovery token or master node, find out all the machines in the cluster, and then start them.

**Comment by nathanleclaire** [comment]
@arun-gupta I'm wondering if a slightly more flexible solution for your use case might be some kind of `--filter` flag on `docker-machine ls`.  Then, you could do `docker-machine start $(docker-machine ls -q --filter swarm=swarm-master` similar to how you would, say, remove all containers in docker today.  What do you think?

**Comment by arun-gupta** [comment]
@nathanleclaire that's the Docker way, and seems appropriate to me.

**Comment by nathanleclaire** [comment]
Filters have been implemented so commands similar to the above work now
