### ISSUE TITLE
Remove multiple machines with a single command

### ISSUE THREAD

**Issue by arun-gupta** [docker/machine#1053]
```
~> docker-machine rm swarm-master swarm-node-01 swarm-node-02
INFO[0000] The machine was successfully removed. 
```
removed only a single machine.

The command should be updated to remove multiple machines. It would be better if it can take a regular expression, this can be very useful for (re)deployment of a cluster.

**Comment by nathanleclaire** [comment]
Hi @arun-gupta, thanks for the report (and for the articles as well btw).  This command _should_ actually work to remove the machines specified (it does for me) but I the text is quite misleading as it references only one machine.  Do you think maybe we should spit back the machine names instead like how `docker rm` works?  cc @ehazlett for thoughts

**Comment by arun-gupta** [comment]
@nathanleclaire thanks, hope the articles would benefit others too!

+1, the command does work and the output is misleading. Spitting out machine names would be useful. Also include a command to delete entire cluster by specifying the master or discovery token.

**Comment by ehazlett** [comment]
I agree -- we should tell what machines were removed -- whether it is a single or multiple.  As far as the swarm cluster, we could inspect the swarm-agent-master container to get the token and delete automatically.

**Comment by hairyhenderson** [comment]
I've got a pretty simple solution in the referenced PR... It'll just report success on each machine removal. That way if there's a failure, you know that some machines were removed.

**Comment by nathanleclaire** [comment]
> I agree -- we should tell what machines were removed -- whether it is a single or multiple. As far as the swarm cluster, we could inspect the swarm-agent-master container to get the token and delete automatically.

Just to riff on this a bit- I think I would actually prefer to implement filters for `ls` so that instead user could do:

```
$ docker-machine rm $(docker-machine ls --filter swarm=mainswarm -q)
```

It would be simpler.  And we could definitely use filters for other things too, like getting back just a subset of machines if some are hanging on returning their state.

**Comment by hairyhenderson** [comment]
@nathanleclaire - +1

If you open an issue for filters on `ls`, I can hack at a PR :)

**Comment by ehazlett** [comment]
+1 for filters too

**Comment by nathanleclaire** [comment]
I filed a proposal for filters here: https://github.com/docker/machine/issues/1076

**Comment by avindra** [comment]
`docker-machine ls | cut -f 1 -d ' ' | tail -n +2 | xargs docker-machine rm -y`

If you want to nuke all your machines in one go

**Comment by nathanleclaire** [comment]
@avindra this should do to remove all:

```
$ docker-machine rm -y $(docker-machine ls -q)
```

**Comment by denzuko** [comment]
another more unix like way would be, `dmclean() { awk -v filter=$1 'BEGIN { inventory=system("docker-machine ls -q") }; inventory ~ filter { system("docker-machine rm -y "$1) }'; }`

What this does is creates an command in bash that one can remove machines based on regex with `.*` being for all machines or a matching pattern.

Usage:
`dmclean <regex|.*>`

**Comment by dotjsNet** [comment]
Run this command

`chmod +x /usr/local/bin/docker-compose`

Then check

**Comment by denzuko** [comment]
> Run this command
> 
> `chmod +x /usr/local/bin/docker-compose`
> 
> Then check

Had to downvote since the above is off topic. For reference; `docker-compose` manages services, networks, volumes, etc.. which are objects that live inside the Virtual Machine. While `docker-machine` manages the library of Virtual Machine itself. OP is asking for ways to teardown an existing Virtual Machine with `docker-machine`.
