### ISSUE TITLE
Unable to change StorageDriver in virtualbox driver

### ISSUE THREAD

**Issue by gregaumann** [docker/machine#1055]
I need to change the storage driver in the virtualbox driver to use devicemapper rather than aufs. This is because aufs doesn't support setcap and devicemapper does. When using boot2docker without docker-machine this can be done as per these instructions: echo 'EXTRA_ARGS="--storage-driver=devicemapper"' > /var/lib/boot2docker/profile && sudo /etc/init.d/docker restart. I have found a StorageDriver option in the config.json but when I put devicemapper in there and restart the dev vm it still reports it is using aufs.

Is there a way to change the storage driver to device mapper in docker-machine?

**Comment by nathanleclaire** [comment]
Hi @gregaumann - I'm not sure that suggestion will work with docker-machine as we already set EXTRA_ARGS in that file, but this exact feature will be supported by https://github.com/docker/machine/pull/1040 which will hopefully be making its way into master soon.

**Comment by gregaumann** [comment]
Yes the solution for boot2docker without machine doesn't work with machine. Can you suggest a work around that will work or do I need to build from source with your pull request?

**Comment by nathanleclaire** [comment]
@gregaumann For now, if you edit the `EXTRA_ARGS` variable in `/var/lib/boot2docker/profile` (perhaps with a command like `docker-machine ssh machinename vi /var/lib/boot2docker/profile` to include the storage driver flag you want, and restart the daemon, it will work.

**Comment by gregaumann** [comment]
Your instructions above are working for me. 

thanks so much you're a legend
Greg

**Comment by nathanleclaire** [comment]
Ha!  Thanks!  Glad it's working for you!

**Comment by menzow** [comment]
Hello @gregaumann ,

I know this issue is old, but it still popped up on google when searching for this issue. From my findings, the boot2docker base os does not support the devicemapper storage driver anymore. 

I wrote a article on how to resolve this issue on medium. Everyone can check it out here:
https://medium.com/@menzo/using-the-device-mapper-storage-driver-on-mac-osx-6327dbee3250

**Comment by zrml** [comment]
@gregaumann thank you for sharing that!
