### ISSUE TITLE
VirtualBox machine hostname not added to /etc/hosts on the first boot

### ISSUE THREAD

**Issue by dwilson6** [docker/machine#1057]
After creating a new VirtualBox machine the /etc/hosts file still has boot2docker as the hostname instead of the machine name. If I do a docker-machine restart then the machine name is in the hosts file. 

After a little investigation, it looks like the set hostname function in the boot2docker provisioner doesn't call the binary which actually updates the hosts file (but that binary is called in the boot2docker init script). The first time the boot2docker init script runs, the hostname hasn't been set yet.

**Comment by nathanleclaire** [comment]
Very interesting - which script is it?

**Comment by dwilson6** [comment]
The script is https://github.com/boot2docker/boot2docker/blob/master/rootfs/rootfs/etc/rc.d/hostname

That script is called by https://github.com/boot2docker/boot2docker/blob/master/rootfs/rootfs/bootscript.sh

**Comment by dwilson6** [comment]
In the docker-machine [boot2docker provisioner](https://github.com/docker/machine/blob/master/libmachine/provision/boot2docker.go), the SetHostname method should run "sudo /usr/bin/sethostname %s && echo %q | sudo tee /var/lib/boot2docker/etc/hostname" instead of "sudo hostname %s && echo %q | sudo tee /var/lib/boot2docker/etc/hostname"

**Comment by nathanleclaire** [comment]
Nice - I will make a PR to do so

**Comment by dwilson6** [comment]
Thanks!

**Comment by jkrukoff** [comment]
Just ran into this, as it was causing a marathon container to fail to boot. Appears to also affect vmware based hosts.

Temporarily resolved by only running a single machine named "boot2docker" so that there's no mismatch, though it'd be nice to be able to run more than one.
