### ISSUE TITLE
vmwarevsphere boot2docker running docker 1.6.0 and docker-machine version 0.2.0

### ISSUE THREAD

**Issue by FlxPeters** [docker/machine#1060]
Hi,

i think this is related to #1020 issue. When i create a new docker-machine on a vSphere 5.5 I can not make any command to this machine. 

```
$ docker ps
FATA[0000] Error response from daemon: client and server don't have same version (client : 1.18, server: 1.17)
```
Lokal versions:
```
$ docker -v
Docker version 1.6.0, build 4749651
$ docker-machine -v
docker-machine version 0.2.0 (8b9eaf2)
```

```
$ docker-machine ssh
                        ##        .
                  ## ## ##       ==
               ## ## ## ##      ===
           /""""""""""""""""\___/ ===
      ~~~ {~~ ~~~~ ~~~ ~~~~ ~~ ~ /  ===- ~~~
           \______ o          __/
             \    \        __/
              \____\______/
 _                 _   ____     _            _
| |__   ___   ___ | |_|___ \ __| | ___   ___| | _____ _ __
| '_ \ / _ \ / _ \| __| __) / _` |/ _ \ / __| |/ / _ \ '__|
| |_) | (_) | (_) | |_ / __/ (_| | (_) | (__|   <  __/ |
|_.__/ \___/ \___/ \__|_____\__,_|\___/ \___|_|\_\___|_|
Boot2Docker version 1.5.0, build vmware-support : e883254 - Fri Feb 27 18:00:02 UTC 2015
Docker version 1.5.0, build a8a31ef
```

**Comment by FlxPeters** [comment]
I found a dirty workaround. Just Download the the Image from #1034 and rename it to `/User/xxx/.docker/machine/cache/boot2docker-1.5.0-GH747.iso` and remove all caches.

**Comment by lesaux** [comment]
thanks for this! helps me until next release

**Comment by victorock** [comment]
Just need to provide the correct URL where the ISO must be downloaded from.
Follow example adopting vmwarefusion driver:

docker-machine create -d vmwarefusion \
--vmwarefusion-boot2docker-url https://github.com/cloudnativeapps/boot2docker/releases/download/v1.6.0-vmw/boot2docker-1.6.0-vmw.iso \
local-fusion
