### ISSUE TITLE
Default to a single CPU core

### ISSUE THREAD

**Issue by SvenDowideit** [docker/machine#1062]
reported as https://github.com/boot2docker/boot2docker/issues/769 by @lmakarov

I'm getting considerably better results with a single core on both Mac and Windows.
The application uses two containers: a web (nginx+php-fpm) and a db (mysql).
I'm seeing a 40% (!!!) performance gain from switching from 8 cores (default and recommended max by VirtualBox) to a single core.

Apparently virtualizing multiple cores for a VM is more overhead than benefit for VirtualBox in most cases. You may achieve better results if the guest stack/application is optimized for a multi-core environment. However, the primary use case for boot2docker is non-production use/local development, so it may make sense to default to a single core for better performance in most cases.

**System information**
```
Boot2Docker-cli version: v1.5.0
Client version: 1.5.0
Client API version: 1.17
Go version (client): go1.4.1
Git commit (client): a8a31ef
OS/Arch (client): darwin/amd64
Server version: 1.5.0
Server API version: 1.17
Go version (server): go1.4.1
Git commit (server): a8a31ef
```

**Related discussions**
- https://forums.virtualbox.org/viewtopic.php?f=2&t=56730
- http://superuser.com/questions/297697/are-there-any-real-advantages-to-assigning-more-cores-to-virtualbox
- #702

**Comment by znmeb** [comment]
+1 ... in fact, on my hyperthreaded Core i5 Windows 8.1 machine, it defaults to four "CPUs" and VirtualBox flags that as non-optimal - recommends dropping it to the two physical cores.

**Comment by ehazlett** [comment]
@SvenDowideit wow -- nice.  we'll get this in to see.  thanks!

**Comment by znmeb** [comment]
Incidentally, I haven't run any tests recently but a year or so ago on Windows 8 I ran a Linux VM with the Redis built-in benchmark with Client Hyper-V, VMware Workstation and VirtualBox and VirtualBox was just horrible - IIRC half the throughput of Client Hyper-V. VMware Workstation was close to what Client Hyper-V got (but it costs money).

Oracle is claiming they've made some performance improvements in VirtualBox 5 but I'm running Client Hyper-V now.

**Comment by UserTaken** [comment]
With my desktop i3 running Siege against the default Nginx container in Boot2Docker build a66bce5 in Virtualbox 4.3.26-3 under Arch Linux, I get

```
(trans/sec)

1 CPU
3242.00
3188.01
3184.37

2 CPU
2962.78
2856.34
3023.13

4 CPU
2156.02
2102.68
2287.49
```

I wonder if this also the case with AMD CPUs.

**Comment by nathanleclaire** [comment]
Sounds good to me.

**Comment by ehazlett** [comment]
@frapposelli should we do this for fusion as well?

**Comment by frapposelli** [comment]
Yes we should, It was actually the default on fusion a while back, then changed it to align with virtualbox.

**Comment by frapposelli** [comment]
Honestly, Fusion should scale decently, I think we should do something like `totalcores/2` by default

**Comment by ehazlett** [comment]
@frapposelli yes i remember asking you to switch to match :)  I want to do what works best for each hypervisor.  If fusion works well with multiple then lets do that.  sorry for the motion around it :)

I'll do a PR for this.  @frapposelli i will leave fusion as is since it should scale fine -- feel free to switch to `total/2` if you want.  Thanks!

**Comment by strarsis** [comment]
I configured the docker-machine-created VM in VirtualBox to max CPU cores manually.
