### ISSUE TITLE
eval "$(docker-machine env xxx)" does not work in ZSH

### ISSUE THREAD

**Issue by yograterol** [docker/machine#1070]
Hi, today I'm trying Docker Machine and I saw that does not work in ZSH, in BASH work without problem but in ZSH when I run `eval "$(docker-machine env xxx)"` (xxx is the my machine name) not set the settings for Docker.

**Comment by leyyinad** [comment]
Same here, running `$(docker-machine env)` gives `export: not valid in this context: shell:`.

**Comment by UserTaken** [comment]
`eval "$(docker-machine env xxx)" ` with ZSH works for me.

[![Alt Text](http://chunk.io/f/1699da4d8a1f4c21be2f70e18cd77098)](http://chunk.io/f/678a3f9c840d4729a76e69512663839a)

**Comment by zchee** [comment]
I'm works too.

- OSX darwin
- `docker-machine` HEAD version (self build after git clone)
- `zsh 5.0.7 (x86_64-apple-darwin14.0.0)`

I think the cause of the your zsh config or zsh version.

If there is influence, it might `typeset -gU cdpath fpath mailpath path PATH` ?
This config is [Ensure path arrays do not contain duplicates](https://github.com/sorin-ionescu/prezto/blob/master/runcoms/zprofile#L36-L37).

**Comment by leyyinad** [comment]
It used to work this way some time ago. But prepending `eval` did it for me.

**Comment by zchee** [comment]
@yograterol 
@leyyinad 
Can you write a configuration file of your zsh the gist in the permissible range?

**Comment by yograterol** [comment]
@zchee this is my ZSH config https://gist.github.com/yograterol/0abb556c201525b571e8

My Docker's version                                                                                                        
Docker version 1.6.0, build 3eac457/1.6.0

My Docker Machine version:
docker-machine version 0.2.0 (8b9eaf2)

**Comment by zchee** [comment]
@yograterol
I'll try in the your environment. 
BTW, What your os distribution?

**Comment by yograterol** [comment]
@zchee thank u, my OS distribution is Fedora 21

**Comment by zchee** [comment]
Ok, I'm try now....

**Comment by zchee** [comment]
@yograterol 
I create fedora container in docker.
https://registry.hub.docker.com/_/fedora/

In root user,

```sh
yum install zsh git docker-io
chsh -s /usr/bin/zsh
curl -L https://gist.githubusercontent.com/yograterol/0abb556c201525b571e8/raw/376d134b421d33b16fa8b401b11fbc7203c55ccc/zsh > ~/.zshrc
curl -L https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh | sh
zsh # launch zsh
curl -L https://github.com/docker/machine/releases/download/v0.2.0/docker-machine_linux-amd64 > /usr/bin/docker-machine
chmod +x /usr/bin/docker-machine
env # confirmed not set DOCKER_***
docker-machine create test --driver amazonec2 ...........
eval "$(docker-machine env test)"
env # find DOCKER_***
```

I works now. Why? :(
Do you are not set environment in this state?

**Comment by yograterol** [comment]
hmmm, I will try again with a clean ZSH.

**Comment by ehazlett** [comment]
@tianon this should work for zsh right?

**Comment by tianon** [comment]
Hmm, good question.  I'm not actually sure on the semantics of ZSH specifically, but it _should_ work given that it's standard POSIX shell.

**Comment by nathanleclaire** [comment]
I am a daily `zsh` user and it works for me.  There may be something in your shell configuration which is interfering with it.  Could you please post the output of running just `docker-machine env name`?  Thanks.

**Comment by zchee** [comment]
@yograterol FYI, I pushed docker image.
Try it.
`docker run -it --rm zchee/yograterol`
INFO https://registry.hub.docker.com/u/zchee/yograterol/

**Comment by vincentbernat** [comment]
@tianon zsh is a POSIX shell only when invoked as `sh`. For example, word splitting is not done after variable expansion while it should be done in a POSIX shell. But stuff as basic as setting the environment, it should work as expected. I am also using zsh and never had a problem with `docker-machine env name`. I don't see what would fail unless the certificate path contains characters like `"` or `$` (quite unlikely as the machine name is checked to only have regular characters)

**Comment by nathanleclaire** [comment]
`zsh` works fine on my end and I use it every day

**Comment by chrissound** [comment]
Doesn't work for me either.
