### ISSUE TITLE
Proposal: Filters for "docker-machine ls"

### ISSUE THREAD

**Issue by nathanleclaire** [docker/machine#1076]
## Abstract

Right now it is not possible to query only a subset of machines for their state using `docker-machine ls`.  For a variety of reasons, including the ability to integrate nicely with other commands such as `rm` that accept multiple machine names as arguments, I propose that we support a `docker-machine ls --filter` flag which will only query a subset of those machines.  It is similar to how `docker images` has a `--filter dangling=true` option.

Then we can do things like:

```console
$ # Stop the "foobar" swarm with one command!
$ docker-machine stop $(docker-machine ls --filter swarm=foobar)
```

## Implementation

If you look in `commands/ls.go` you can see that we have a little block like this:

```go
        hostList, err := mcn.List()
        if err != nil {
                log.Fatal(err)
        }
```

Right after this block is where the filtering should take place.  `List` will return all of the hosts that we have a reference to locally.  The approach I would take is to add a `FilterOptions` struct to this file, which contains the settings that we might want to filter by (`--filter` should be a `StringSlice` flag, so we will have to add one or two functions to parse this into the struct as well).

We can start simple with just "SwarmName" and "DriverName" parameters and expand from there if we want more, so let's not get too elaborate on the first go:

```go
type FilterOptions struct {
    SwarmName string
    DriverName string
}
```

Add a function, maybe named `filterHosts`, which accepts a `[]*Host` and `FilterOptions` and returns a `[]*Host` with the ones that we don't want removed.  Then everything in the rest of the function will work the same as it ever has since we will just be modifying the value of what `hostList` is today.

cc @hairyhenderson @sthulb @ehazlett

**Comment by hairyhenderson** [comment]
:+1: 

#dibs if nobody else wants this ;)

**Comment by sthulb** [comment]
Perhaps counter to this, I'd like to see us filter from things in inspect with go templates.

**Comment by nathanleclaire** [comment]
@sthulb Do you mean like `docker-machine inspect -f '{{.SwarmMaster}}' overlay`?  If so, that feature snuck in when you weren't looking :wink:
