### ISSUE TITLE
Handling of tilda in path as cli argument

### ISSUE THREAD

**Issue by ahmetalpbalkan** [docker/machine#1077]
I realized 

    $ machine create --azure-subscription-cert=~/junk/mycert.pem [...]

fails with error saying 

    stat: ~/junk/mycert.pem no such file or directory

apparently ~ is not getting expanded. We should probably support that somehow. I don't know why the shell doesn't expand that already before passing to `machine`. (I'm using zsh on osx.)

**Comment by hairyhenderson** [comment]
@ahmetalpbalkan it should work fine if instead you do:

```sh
$ machine create --azure-subscription-cert ~/junk/mycert.pem [...]
```

This is because the form with a `=` is treated as a whole word and your shell has no idea it needs to do any expansion.

See also http://stackoverflow.com/questions/17609732/expand-tilde-to-home-directory/30027501#30027501

**Comment by ahmetalpbalkan** [comment]
Ah, makes sense @hairyhenderson. Closing this one.
