### ISSUE TITLE
Better message for shellinit after create

### ISSUE THREAD

**Issue by ahmetalpbalkan** [docker/machine#1078]
Whenever I watch people using docker-machine to create a VM

![image](https://cloud.githubusercontent.com/assets/159209/7408835/f49dc2fa-eed5-11e4-9ecb-9ca94825747d.png)

they just copy/paste the part **inside quotes** and forgot the `eval` all time. 

I think we can do something like `.... shell:\n\t\teval $(...` for better readability.

**Comment by UserTaken** [comment]
What about highlighting the eval part?

![Image](http://oi58.tinypic.com/5vdc3t.jpg)

**Comment by ehazlett** [comment]
@ahmetalpbalkan does this look better? https://github.com/docker/machine/pull/1083/files#diff-d979e9548d0d641ce071ee98608da5faR99

**Comment by ahmetalpbalkan** [comment]
I think we should keep "eval", that's useful. it's just since eval is not inside quotes, or starts in a separate new line, people forget copying eval.

**Comment by ehazlett** [comment]
well `eval` isn't relevant in the powershell/cmd.exe context.  as we add more shells in the future, i think it's easier to defer to each `env` command -- that's where the details are.  thoughts?

**Comment by ahmetalpbalkan** [comment]
@ehazlett by looking at your diff link I can't see why the eval went away. This is not related to the issue. What I'm saying is it makes more sense to turn this:

```
INFO[0053] To point your Docker client at it, run this in your shell: eval "$(docker-machine env dev)"
```

into this:
```
INFO[0053] To point your Docker client at it, run this in your shell:
    eval "$(docker-machine env dev)"
```

or this on windows (powershell):
```
INFO[0053] To point your Docker client at it, run this in your shell:
    docker-machine env dev --powershell | Invoke-Expression
```

**Comment by ehazlett** [comment]
@ahmetalpbalkan ah sorry -- i read the question wrong.  noted -- i agree it would be better for usability.

thanks!
