### ISSUE TITLE
Fusion Driver: ssh keys not being copied

### ISSUE THREAD

**Issue by victorock** [docker/machine#1079]
When i try to use docker-machine with VMware Fusion driver with the latest boot2docker:

victor$ docker-machine rm local-fusion #create -d vmwarefusion local-fusion
INFO[0000] Forcibly halting local-fusion...             
INFO[0002] Deleting local-fusion...                     
INFO[0002] The machine was successfully removed.        
vicdacosta:dacosta victor$ docker-machine -D create -d vmwarefusion --vmwarefusion-boot2docker-url https://github.com/boot2docker/boot2docker/releases/download/v1.6.0/boot2docker.iso local-fusion
INFO[0000] Downloading boot2docker.iso from https://github.com/boot2docker/boot2docker/releases/download/v1.6.0/boot2docker.iso... 
INFO[0003] Creating SSH key...                          
DEBU[0003] executing: /usr/bin/ssh-keygen ssh-keygen -t rsa -N  -f /Users/victor/.docker/machine/machines/local-fusion/id_rsa
 
Generating public/private rsa key pair.
Your identification has been saved in /Users/victor/.docker/machine/machines/local-fusion/id_rsa.
Your public key has been saved in /Users/victor/.docker/machine/machines/local-fusion/id_rsa.pub.
The key fingerprint is:
8d:d4:fc:3e:0c:80:40:e6:6f:d6:b8:33:d1:4c:16:b4 victor@vicdacosta
The key's randomart image is:
+--[ RSA 2048]----+
|   .+  .o        |
|   o . . =       |
|    . . E o      |
|     . O + .     |
|      * S o .    |
|     o o   +     |
|      +     +    |
|       o     .   |
|                 |
+-----------------+
INFO[0004] Creating VM...                               
VixDiskLib: Invalid configuration file parameter.  Failed to read configuration file.
Creating disk '/Users/victor/.docker/machine/machines/local-fusion/local-fusion.vmdk'
Virtual disk creation successful.
INFO[0004] Starting local-fusion...                     
DEBU[0004] executing: /Applications/VMware Fusion.app/Contents/Library/vmrun start /Users/victor/.docker/machine/machines/local-fusion/local-fusion.vmx nogui 
INFO[0005] Waiting for VM to come online...             
DEBU[0005] MAC address in VMX: 00:0c:29:da:83:87        
DEBU[0005] IP found in DHCP lease table: 172.16.32.249  
DEBU[0005] Got an ip: 172.16.32.249                     
DEBU[0005] Creating Tar key bundle...                   
DEBU[0005] executing: /Applications/VMware Fusion.app/Contents/Library/vmrun -gu docker -gp tcuser directoryExistsInGuest /Users/victor/.docker/machine/machines/local-fusion/local-fusion.vmx /var/lib/boot2docker 
DEBU[0305] executing: /Applications/VMware Fusion.app/Contents/Library/vmrun -gu docker -gp tcuser CopyFileFromHostToGuest /Users/victor/.docker/machine/machines/local-fusion/local-fusion.vmx /Users/victor/.docker/machine/machines/local-fusion/userdata.tar /home/docker/userdata.tar 
DEBU[0606] executing: /Applications/VMware Fusion.app/Contents/Library/vmrun -gu docker -gp tcuser runScriptInGuest /Users/victor/.docker/machine/machines/local-fusion/local-fusion.vmx /bin/sh sudo /bin/mv /home/docker/userdata.tar /var/lib/boot2docker/userdata.tar && sudo tar xf /var/lib/boot2docker/userdata.tar -C /home/docker/ > /var/log/userdata.log 2>&1 && sudo chown -R docker:staff /home/docker 

DEBU[0906] Getting to WaitForSSH function...            
DEBU[0906] MAC address in VMX: 00:0c:29:da:83:87        
DEBU[0906] IP found in DHCP lease table: 172.16.32.249  
DEBU[0906] MAC address in VMX: 00:0c:29:da:83:87        
DEBU[0906] IP found in DHCP lease table: 172.16.32.249  
DEBU[0906] executing: ssh -o IdentitiesOnly=yes -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ConnectionAttempts=30 -o LogLevel=quiet -p 22 -i /Users/victor/.docker/machine/machines/local-fusion/id_rsa docker@172.16.32.249 exit 0 
docker@172.16.32.249's password: 

* If i enter the password tcuser multiple times the machine is created successfully.

**Comment by ehazlett** [comment]
this will be updated in 0.3.0.  for the time being you can either use a master build or use this URL https://github.com/cloudnativeapps/boot2docker/releases/download/v1.6.0-vmw/boot2docker-1.6.0-vmw.iso

**Comment by frapposelli** [comment]
Yes, you should use the ISO that @ehazlett has linked, or just compile HEAD and do not specify `--vmwarefusion-boot2docker-url`, this will pull the right iso down.
