### ISSUE TITLE
Refactor to remove log.*ln method usage

### ISSUE THREAD

**Issue by nathanleclaire** [docker/machine#1081]
Users should do either `log.Warn` (same as `log.Warnln` for our purposes) or `log.Warnf` style, but not both.  `logrus` allowed this but we will not with the new logging interface. https://github.com/docker/machine/pull/1008 does not address this directly but it should be done in a followup PR to remove these methods from the interface as well as change where the are used.

**Comment by nathanleclaire** [comment]
Looks like `Errorln` and `Infoln` are the only ones that need to go.

**Comment by dgageot** [comment]
Closing. This is fixed
