### ISSUE TITLE
Add docs for docker-machine inspect -f

### ISSUE THREAD

**Issue by nathanleclaire** [docker/machine#1084]
The `docker-machine inspect -f` is a pretty cool feature.  We should cover it in the `inspect` section in the docs.  cc @hairyhenderson

**Comment by hairyhenderson** [comment]
Yes, yes we should :+1: :)

Might even be possible to steal most of this from https://github.com/docker/docker/blob/master/docs/sources/reference/commandline/cli.md#L1452

**Comment by nathanleclaire** [comment]
Yeah, it doesn't need to be anything elaborate, I just want to make sure that we at least mention it's a feature, include an example, and maybe link to that saying "it works very similarly to this".
