### ISSUE TITLE
Proposal: Abstract SSH "backends"

### ISSUE THREAD

**Issue by nathanleclaire** [docker/machine#1091]
The recent SSH changes are great for users who we cannot count on having the `ssh` binary around for (mostly Windows users), but for Mac and Linux users I'd argue that we should default to shelling out to `ssh` instead of the new stuff for two main reasons:

1. `ssh` binary has been around much, much, longer.  It is battle tested and includes many provisions for things that we would otherwise be rolling on our own, e.g. timeout and retry logic.
2.  Debugability.  I've been noticing that it's much harder to get a grasp on what is happening with the native code `ssh` stuff and fix it.

For these reasons I don't think we should drop shelling out to `ssh` entirely like we have in current master.  We should provide a common interface, check for the `ssh` binary (`exec.LookPath`) and if it's there use it, otherwise default to the native code implementation.

Similarly, we _badly_ need `scp` type functionality and it'd be much easier to get by just shelling out than by re-writing scp ourselves (none of us have time for that, really, and I'd rather just send an error saying "scp is not supported" if it is not available until we can get it together with native code).

cc @ehazlett @sthulb @ehazlett

**Comment by sthulb** [comment]
Whilst I agree that the ssh term we have isn't great, I think we should stick with it.

**Comment by hairyhenderson** [comment]
I'm not _totally_ against, this, but I worry that it would add extra maintenance, and it would also mean trying to maintain parity between two different SSH backends...

**Comment by ehazlett** [comment]
So I think we should do the following:

Implement the default to the ssh binary if it's present -- mainly for the following:  we are noticing some quirks (timeouts, retries, handshake errors, etc).  I'm fearful of what else may come and us not being able to fix it fast enough causing stability issues in the release.  We rely heavily on SSH and need it to be solid.  This would allow us an "interim" phase to test out our `crypto/ssh` implementation and get it solid and then switch to it when it's stable.

@hairyhenderson I don't there will be much maintenance as we had it pretty solid and didn't require much maintenance in the recent weeks.  I think we should do the light maintenance in favor of stability with the end goal being a single portable ssh.

Thoughts?

**Comment by nathanleclaire** [comment]
> Implement the default to the ssh binary if it's present -- mainly for the following: we are noticing some quirks (timeouts, retries, handshake errors, etc). I'm fearful of what else may come and us not being able to fix it fast enough causing stability issues in the release. We rely heavily on SSH and need it to be solid. This would allow us an "interim" phase to test out our crypto/ssh implementation and get it solid and then switch to it when it's stable.

Yes, I am in favor of always shelling out to `ssh` when available.  This will allow us to get the best of both worlds.  `ssh` has been around for a very long time and is rock-solid.

**Comment by sthulb** [comment]
We should definitely feature flag it... we could use the behaviour of:
1. Check for SSH env var (Something like MACHINE_SSH_BINARY)
1. Check for SSH Binary
1. If MACHINE_SSH_BINARY is falsey, use crypto/ssh otherwise, use ssh binary.

**Comment by ehazlett** [comment]
+1 for the flag.

**Comment by hairyhenderson** [comment]
Ok, given all the issues lately I think this is worthwhile :)

Also, +1 on the feature flag.

**Comment by nathanleclaire** [comment]
![image](https://cloud.githubusercontent.com/assets/1476820/7755180/30bc4176-ffa7-11e4-8770-131119d9826b.png)
