### ISSUE TITLE
Bump version to 0.3.0

### ISSUE THREAD

**Issue by chanwit** [docker/machine#1093]
Version 0.2.0 has been released since several days ago, but the `version.go` file still contains 0.2.0. 
I think it's a good practice to increase version number after the current one is tagged.

Could you please update it to 0.3.0 or 0.3.0 snapshot, so at least the version display while development will show 0.3.0 (HEAD).

**Comment by thaJeztah** [comment]
Just for reference, since Docker 1.6, docker also bumps the version directly after a release; after 1.6 was released, the version was bumped to `1.7.0-dev`

**Comment by nathanleclaire** [comment]
I'm sure we can and I'm happy to

**Comment by ehazlett** [comment]
@nathanleclaire #1104  :)
