### ISSUE TITLE
[VMWare] Why auto set Processors to 8 core?

### ISSUE THREAD

**Issue by zchee** [docker/machine#1095]
I created docker machine use VMWare Fusion.

I was specify set to
```
--driver vmwarefusion
--vmwarefusion-disk-size "1000000"
--vmwarefusion-memory-size "4098"
```

There is no set of cpu in it.

I check setting after launch vmware, 8 core is specified.
It gives all of the number of CPU, I think that is go too far.

/cc @ehazlett, @frapposelli 

ps, My mac spec

```
  Model Name:	MacBook Pro
  Model Identifier:	MacBookPro11,3
  Processor Name:	Intel Core i7
  Processor Speed:	2.3 GHz
  Number of Processors:	1
  Total Number of Cores:	4
  L2 Cache (per Core):	256 KB
  L3 Cache:	6 MB
  Memory:	16 GB
```

**Comment by zchee** [comment]
Well, I'm not in trouble, I think I trouble to be a low spec.

**Comment by ehazlett** [comment]
This was a request from me to match the Vbox driver (default to use all available CPUs).  According to @frapposelli this should be fine on Fusion.

@frapposelli can you confirm this?

**Comment by frapposelli** [comment]
It should be fine, maybe we can throttle this down to the number of physical cores which would be more accurate.

**Comment by zchee** [comment]
Might some people do not want to assign all of the CPU.
So that, I think that is better that the user can specify be something more user friendly.

Vagrant(or etc...) can be specified.
But, If a recommendation of @frapposelli, I will follow it :)

**Comment by frapposelli** [comment]
@zchee I will submit a PR for that soon, just realized I didn't embed a config option for CPUs....

**Comment by zchee** [comment]
@frapposelli Thanks :)

**Comment by zchee** [comment]
close https://github.com/docker/machine/pull/1110
