### ISSUE TITLE
Use of the "--amazonec2-ssh-user" option throws an "incorrect Usage" error.

### ISSUE THREAD

**Issue by RusDavies** [docker/machine#1102]
I'm working with a custom Ubuntu-based AMI on Amazon EC2.  For compliance reasons, the image is configured without the "ubuntu" user.  Instead, cloud-init initializes the SSH key onto a custom username, which more adequately meets a compliance requirement. 

So, my use case is that I want to be able to configure the ssh-user used by docker-machine, when using the Amazon EC2 driver. 

I see there's a "--amazonec2-ssh-user" flag in the amazonec2 driver code (see [here](https://github.com/docker/machine/blob/master/drivers/amazonec2/amazonec2.go#L154), and [here](https://github.com/docker/machine/blob/master/drivers/amazonec2/amazonec2.go#L227) ).  That kind of sounds like what I want. 

However, it's not documented.  Further, if I do the following, the result is an "incorrect usage" error:
```bash
docker-machine -D create --driver amazonec2 \
        --amazonec2-ssh-user "mycompliantusername" \
        --amazonec2-access-key "xxxxxxxxxxxxx" \
         --amazonec2-secret-key "xxxxxxxxxxxxx" \
         --amazonec2-ami  "xxxxxxxxxxxxx" \
         --amazonec2-vpc-id "xxxxxxxxxxxxx"   example01
```
If I take out the --amazonec2-ssh-user flag, then it happily creates the machine, but, of course, can't then open a SSH connection.  

Am I missing something?  Or this a bug, and/or the --amazonec2-ssh-user flag unsupported?  Is there any way to use a ssh-user other than the default 'ubuntu'? 

Thanks

**Comment by zchee** [comment]
It's a bug :(

I fix now...

**Comment by RusDavies** [comment]
Hey, thanks for the fast reply :)

It's interesting that you didn't exit with the "incorrect usage" error.  Are you on the master branch?

I should have said, I'm using the 0.2 release.

**Comment by zchee** [comment]
@RusDavies 
Yes, I using HEAD branch.
It seems that does not work Either way.

I do not check the 02, but I'm trying to fix in the HEAD.

**Comment by ehazlett** [comment]
this appears to be working.  closing -- if you still experience this please re-open.  thanks!

**Comment by RusDavies** [comment]
@ehazlett, it seems to work in 0.3-dev, but is broken in the 0.2 release.   However, I'll consider 0.2 as an unsupported release, and therefore I'll not reopen.  Thanks.

**Comment by ehazlett** [comment]
@RusDavies thanks for the update!
