### ISSUE TITLE
Bug on docker-machine upgrade (boot2docker) on Windows

### ISSUE THREAD

**Issue by nathanleclaire** [docker/machine#1112]
When I try a `docker-machine upgrade dev` on Windows, it seems to go OK until we actually try to copy the new ISO in place of the old one.  I get an error:

```
rename [path to tmp ISO] [path to boot2docker.iso]: Cannot create a file when that file already exists.
```

I seem to recall a little bit about this in the b2d upgrade code, so I will start fishing there for hints - looks like we just need to actually remove the old boot2docker.iso before renaming the new ISO downloaded to `boot2docker.iso`.

cc @SvenDowideit @tianon @ehazlett WDYT

**Comment by ehazlett** [comment]
that would make sense but I defer to @SvenDowideit as he probably knows from the b2d side.

**Comment by tianon** [comment]
Yeah, that bug was fun.  Windows is picky about replacing files if they're
in use, IIRC.  Basically, I'd recommend you steal whatever hanky
delete-copy logic boot2docker has here, even if it's just for Windows. :+1:

**Comment by nathanleclaire** [comment]
I have a fix for this in the pipe.

**Comment by nathanleclaire** [comment]
This is the b2d code: https://github.com/boot2docker/boot2docker-cli/blob/0a3a250f0d3e3b7362fbb7eafecb0891dbf7befc/util.go#L91

@tianon Do you know the motivation of the extra `.bak` file?  I'm having a hard time trying to figure out the failure case here.  If the download succeeded, the window of failure seems small if we just go ahead and remove the ISO, then rename the downloaded file.

**Comment by tianon** [comment]
Not sure, especially since Windows won't be any more happy about renaming
if the file is use than it is about overwriting.

**Comment by tianon** [comment]
https://github.com/boot2docker/boot2docker-cli/commit/5a65dfe687ef9dc57d402eff93162019e994f6ce

**Comment by tianon** [comment]
ie, https://github.com/boot2docker/boot2docker-cli/pull/86

**Comment by tianon** [comment]
So, I don't see anything specific about why it has to be renamed and not just removed.  It might work. :+1:

**Comment by nathanleclaire** [comment]
Yeah, that's what I'm inclined towards.  I'll fix it up if we discover an issue with that method.

**Comment by SvenDowideit** [comment]
you can rename a file thats open on windows (iirc), but you can't delete it.

also - I like backups, that way i can compare what i had to what i have, and roll back.

tbh, I was planning on making the b2d-cli code replace this mess with filenames with versions - which machine, with its multiple vm's would benefit from more.

**Comment by nathanleclaire** [comment]
Would love to hear a proposal from you on the subject (versioning) @SvenDowideit
