### ISSUE TITLE
docker-machine upgrade for vbox will not work if machine is powered off when command is invoked

### ISSUE THREAD

**Issue by nathanleclaire** [docker/machine#1113]
This one is funny to me.  If the machine is powered off, we cannot actually call over SSH to get `/etc/os-release`, so we cannot actually run the upgrade because this hangs forever.  Guess we need to either power the machine on first (hack, as it will then immediately get turned off) or start storing OS information locally / in the Driver so that we can access it later.  I think we should do (1) for the short term, and consider the latter for the future.  cc @ehazlett

**Comment by ehazlett** [comment]
I agree -- option 1 to start.  Option 2 brings an entirely different set of potential issues.  I think it's OK to start it then upgrade.

**Comment by nathanleclaire** [comment]
SGTM -- I will put in a PR for this today

**Comment by ehazlett** [comment]
awesome thx!
