### ISSUE TITLE
No Driver Utility

### ISSUE THREAD

**Issue by UserTaken** [docker/machine#1123]
I have several servers running Docker that was created without any driver. Docker-machine allows hosts to be added just by the URL but that does not have any function. Running `docker-machine env` and `config` prints an error about missing cert instead of `DOCKER_HOST=IP:port` and even running `docker-machine ip` prints out nothing. Beyond that, improvements to the functionality that will significantly increase Machine's utility include being able to specify custom ca.pem, cert.pem, key.pem and SSH certs for a host. Something like

```
$ docker-machine create -d none --url 50.134.234.20:2376 \
	--tlscacert /User/owner/.docker/ca.pem \
	--tlscert /User/owner/.docker/cert.pem \
	--tlskey /User/owner/.docker/key.pem \
	--sshkey /User/owner/.docker/id_rsa \
	--sshuser docker custombox
```

The official docs show

```
$ docker-machine create --url=tcp://50.134.234.20:2376 custombox
$ docker-machine ls
NAME        ACTIVE   DRIVER    STATE     URL
custombox   *        none      Running   tcp://50.134.234.20:2376
```

But I don't see anything under `STATE` so perhaps a ping could be used to determine if a host is running or not since doing a port scan is probably wishing too much.

**Comment by nathanleclaire** [comment]
I think the recently merged `--generic` driver might be more akin to what you're after.

**Comment by UserTaken** [comment]
The `generic` driver will certainly help with future machines but this is about managing existing machines.

**Comment by hairyhenderson** [comment]
@UserTaken - I've used the `none` driver in the past to do this (without the errors you're talking about), but frankly it was a massive pain to set up. If I were to do this again today, I'd use `generic`.

Can you try out `generic` on a machine with Docker already-installed and let us know specifically what aspects of the driver don't work for you?

**Comment by UserTaken** [comment]
@hairyhenderson According to #406, the `generic` driver only supports Ubuntu while my servers consist of CentOS, Fedora and Arch Linux.

**Comment by hairyhenderson** [comment]
@UserTaken - the driver is OS-agnostic, though the only provisioner currently available is for Ubuntu. That'll change soon, though - there is a RHEL/CentOS provisioner coming in #1090, and RancherOS support will come in #1096.

I'd imagine Fedora and Arch support would be pretty straightforward to bring in afterward :)

If your main issue is lack of OS support - can you open issues specifically to support Fedora and Arch?

**Comment by nathanleclaire** [comment]
+1 to what @hairyhenderson said -- if the issues are specific to OSes, please open issues for that.
