### ISSUE TITLE
Azure Driver - add (optional) cli flag for azure hostname

### ISSUE THREAD

**Issue by jayfk** [docker/machine#1126]
The azure driver uses the machine name as a hostname during creation. 

This leads to problems because hostnames on azure have to be globally unique, so the same applies for our machine name.

**Comment by hairyhenderson** [comment]
Thanks for the suggestion, @jayfk!

So if I understand this correctly, you're looking for something like:
```sh
$ docker-machine create -d azure --azure-hostname foo bar
```
Where `foo` would be a globally-unique hostname (that you've somehow determined to be unique beforehand), and `bar` is a locally-unique machine name?

This seems a bit redundant to me, since if you can pick a name that's globally-unique, why not simply use that for the machine name? Or is there something more involved I'm not aware of? :)

Now, this sort of option _does_ have a precedent in the SoftLayer driver (`--softlayer-hostname`), but I don't really see the point and I kind of want to remove it. However, if there's a decent use case for this, then maybe it would make sense to put this in all drivers...

/cc @ehazlett

**Comment by ehazlett** [comment]
I think the reasoning behind this is the fact that Azure only allows the single level domain naming scheme and machine names must be very unique (i.e. `app00` will almost always be taken).

However, that being said, I'm not sure we should add that in.  If you want to customize the VM past what Machine does, I don't think it's a far stretch to `machine ssh` and change.

thoughts @nathanleclaire

**Comment by jayfk** [comment]
> This seems a bit redundant to me, since if you can pick a name that's globally-unique, why not simply use that for the machine name? Or is there something more involved I'm not aware of? :)

I'd like to keep the names of my machines simple. I was playing around with a mixed environment on aws, digitalocean and azure with something like "prod-XXX" as machine names. This failed on azure because the hostname was already taken. I ended up with a trailing "azure" for all machines hosted at microsoft.

That's maybe just a small thing, but, In my opinion, docker-machine should not be limited by what subdomains microsoft has available.

Adding an (optional) hostname parameter seemed like the easiest solution for this. 

Another solution would be to add a function to the driver that ensures that unique hostnames are created (e.g by appending characters etc). I'd be happy to submit a PR for this in the next weeks, if this is something you would consider.

> However, that being said, I'm not sure we should add that in. If you want to customize the VM past what Machine does, I don't think it's a far stretch to machine ssh and change.

I totally agree with you, machine should not be used to configure the VM, but that's not possible with the current implementation. If you can't create the machine, how would you ssh into it?

**Comment by ehazlett** [comment]
> Another solution would be to add a function to the driver that ensures that unique hostnames are created (e.g by appending characters etc). I'd be happy to submit a PR for this in the next weeks, if this is something you would consider.

This is how it used to be and then we were requested to make it match for consistency :)

> I totally agree with you, machine should not be used to configure the VM, but that's not possible with the current implementation. If you can't create the machine, how would you ssh into it?

You could create it with the unique name, then `ssh` and change it.

**Comment by hairyhenderson** [comment]
> I think the reasoning behind this is the fact that Azure only allows the single level domain naming scheme and machine names must be very unique (i.e. `app00` will almost always be taken).

Ah. I was missing this fact.

> > I totally agree with you, machine should not be used to configure the VM, but that's not possible with the current implementation. If you can't create the machine, how would you ssh into it?

> You could create it with the unique name, then ssh and change it.

I think @jayfk is thinking the other way around - he wants the Machine name to be non-unique, but the hostname to be unique.

This is kind of a tough one. Given Azure's restrictions on naming, adding an `--azure-hostname` flag might be the only way around it. I _don't_ like appending random characters to the hostname - that just seems unexpected. I'd rather the driver fail if the machine name is taken, and if the user _really_ wants to assign _that_ machine name, `--azure-hostname` is IMO the only way to accomplish it.

So, I'm +0.25 on this at the moment... A few more days and I might be +1 :stuck_out_tongue_winking_eye:

**Comment by nathanleclaire** [comment]
For now at least, the Machine name and hostname are always expected to correspond exactly, and to deviate from that pattern would introduce frustrating inconsistency.  I am supportive of allowing skipping some or all of provisioning, which includes the host name, but unfortunately if Microsoft has opted to have only one global namespace I don't think I can get behind Machine being responsible for working around it.
