### ISSUE TITLE
azure-size flag seems to be ignored, size "Small", A1 is always used

### ISSUE THREAD

**Issue by thauburger** [docker/machine#1128]
Passing a string like "Standard_D2" to `--azure-size` seems to result in an a "Small" or A1 host being created on Azure.

**Comment by nathanleclaire** [comment]
cc @ahmetalpbalkan

**Comment by ahmetalpbalkan** [comment]
I can't repro this. I was able to create Standard_D1 and Standard_D2 VM sizes just fine with the following command:

    docker-machine create -d azure --azure-subscription-id=...  --azure-subscription-cert=... --azure-size=Standard_D1 $hostname

**Comment by thauburger** [comment]
@ahmetalpbalkan and I talked about this. Was a dumb syntax error on my side (wrong position of the flag). Closing as not an issue. Thanks.
