### ISSUE TITLE
Cleanup failed machines

### ISSUE THREAD

**Issue by tobegit3hub** [docker/machine#1141]
There're some useless machines when errors occur during `machine create`. We should cleanup them if it fails to initialize the environment :smiley:

**Comment by nathanleclaire** [comment]
It cannot be done reliably, see for instance here: https://github.com/docker/machine/issues/972#issuecomment-93651103 for an explanation.

**Comment by tobegit3hub** [comment]
Thanks @nathanleclaire . It seems the same issue.
