### ISSUE TITLE
FATA[0000] host is not running on OSX

### ISSUE THREAD

**Issue by arun-gupta** [docker/machine#1149]
Several Docker machines were created a few days ago and the current state is:
```
wildfly> docker-machine ls
NAME            ACTIVE   DRIVER       STATE     URL                         SWARM
mydocker                 virtualbox   Running   tcp://192.168.99.100:2376   
swarm-master             virtualbox   Stopped                               swarm-master (master)
swarm-node-01            virtualbox   Stopped                               swarm-master
swarm-node-02   *        virtualbox   Stopped                               swarm-master
```

Docker client is configured to connect to the host as `eval $(docker-machine env mydocker)`. But `docker-machine ip` gives the error `FATA[0000] host is not running`.

Tried to start the machine as `docker-machine start mydocker` and got the error `INFO[0000] VM not in restartable state`.

Created a new machine as `docker-machine create --driver virtualbox mydocker2`and then `docker-machine ip` can be found correct (after `eval $(docker-machine env mydocker2)`.

**Comment by marioidival** [comment]
up

**Comment by ehazlett** [comment]
@arun-gupta could you try `docker-machine kill swarm-master`?

**Comment by nathanleclaire** [comment]
@arun-gupta Can you confirm this is still happening with 0.3.0?

**Comment by arun-gupta** [comment]
@nathanleclaire @ehazlett heading back home tomorrow and will respond back later this week.

**Comment by dgageot** [comment]
Hi @arun-gupta Can I close this ticket?

**Comment by arun-gupta** [comment]
@dgageot cannot reproduce, so closing is fine. Will file if it happens again.
