### ISSUE TITLE
Separate pkgaction into "pkgaction" and "serviceaction"

### ISSUE THREAD

**Issue by nathanleclaire** [docker/machine#1150]
Right now the two are conflated because I keep forgetting to separate them.  They should be two separate modules with separate "enums".  One for `pkgaction` e.g. `install`, `update`, etc. and one for `serviceaction` e.g. `stop`, `start`, `restart` cc @sthulb @ehazlett

**Comment by xiaohui** [comment]
I will do this if no one else is working on it
