### ISSUE TITLE
support agent forwarding via `docker-machine ssh`

### ISSUE THREAD

**Issue by gerad** [docker/machine#1154]
We'd like to use ssh agent forwarding so our development builds can access private github repos; as described in https://gist.github.com/d11wtq/8699521#comment-1424725

Unfortunately, `docker-machine ssh` does not seem to support the `-A` flag (ala `ssh -A` or `boot2docker ssh -A`)

**Comment by nathanleclaire** [comment]
+1 cc @ehazlett FYI

**Comment by ehazlett** [comment]
+1

**Comment by hairyhenderson** [comment]
whoa yeah, +1

**Comment by saada** [comment]
:+1:

**Comment by davidpenn** [comment]
👍

**Comment by joshuagoodson-wf** [comment]
+1

**Comment by nathanleclaire** [comment]
Just to give everyone a feel for where my head is at with this:  I am thinking about adding some sort of `--extra-args` flag to `ssh` which would append the extra args specified to the generated SSH command, e.g.:

```console
$ docker-machine ssh --extra-args '-A' foo
```

Thoughts?

**Comment by joshuagoodson-wf** [comment]
that seems reasonable to me.

**Comment by saada** [comment]
I like

**Comment by kudos** [comment]
I've just ran into this problem today, trying to use SSH remote forwarding (not local). In the mean time, I'm trying to figure out a programmatic way of getting the machine's ssh port so I can craft an ssh command. One that doesn't involve parsing JSON from my shell, so `docker-machine inspect` is a non-starter.

**Comment by nathanleclaire** [comment]
> One that doesn't involve parsing JSON from my shell, so docker-machine inspect is a non-starter.

It's definitely kind of a hack for this use case but FYI there is a `-f` option to `docker inspect` for "format" which would allow you to do things like `docker-machine inspect -f '{{.Driver.SSHPort}}' mcn`.

**Comment by adbl** [comment]
Adding this to `~/.ssh/config` worked for me:
```
Host localhost
  ForwardAgent yes
```

Getting `docker run ...` on the host to use the ssh agent on the other hand...

**Comment by nathanleclaire** [comment]
FYI everyone, `-A` support will be added when : https://github.com/docker/machine/pull/1791 is merged

**Comment by nathanleclaire** [comment]
Closing as #1791 is merged
