### ISSUE TITLE
Error regenerating certs: Error copying ca.pem to machine dir

### ISSUE THREAD

**Issue by nathanleclaire** [docker/machine#1159]
Not sure what's going on here, but the regenerating certs action is failing because of an issue in `libmachine/provision/utils.go`:

```console
$ docker-machine regenerate-certs overlay
Regenerate TLS machine certs?  Warning: this is irreversible. (y/n): y
Regenerating TLS certificates
Error copying ca.pem to machine dir: open : no such file or directory
```

cc @ehazlett Seen anything like this before?  It's rendering my machine unusable.

**Comment by nathanleclaire** [comment]
I know what's behind this now: in the recent changes to `ConfigureAuth`, I moved away from passing in `AuthOptions`, due to the fact that they are passed in when you invoke `Provision`.  So, the struct is blank, since with regenerating the certs we do not actually call `Provision` first.  The obvious/hacky way to fix is to create a method `SetAuthOptions` which allows you to do this directly... I am not sure how to handle it elegantly.  If we had an idempotent `Provision` method (we are not really too far off), it might be OK to just call it directly, but as of right now we don't.  I might end up removing the append to config file code we have now and just call `Provision` directly.  It will be a little more overhead but not too bad.

**Comment by nathanleclaire** [comment]
OK, I'm going to go ahead and fix the newline invalidating hashes issue with the certs while I'm at it.

**Comment by ehazlett** [comment]
Ah makes sense.  Thanks!
