### ISSUE TITLE
`docker-machine env` hangs when stopped

### ISSUE THREAD

**Issue by miketheman** [docker/machine#1168]
```shellsession
$ docker-machine --version
docker-machine version 0.2.0 (8b9eaf2)
$ docker-machine stop dev
INFO[0000] Gracefully shutting down dev...
$ docker-machine env dev
<hangs forever>
```

Inspecting the hung process:
```shellsession
$ pgrep -fl docker
6695 docker-machine env dev
6698 ssh -o IdentitiesOnly=yes -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ConnectionAttempts=30 -o LogLevel=quiet -p 22 -i /Users/miketheman/.docker/machine/machines/dev/id_rsa docker@192.168.157.131 cat /etc/os-release
```

Sooo... I can't help but wonder if the first step of `env` subcommand should be to determine `STATE` of the machine, and bail with some error message?

I tried to figure out how to insert that state into the env.go - but my go-fu ain't up to spec yet.

**Comment by nathanleclaire** [comment]
Yeah, if this is happening, it definitely shouldn't - we should try to detect whether the machine's running and error if it's not.

**Comment by ehazlett** [comment]
Thanks for the report.  Can you tell what driver you are using?

**Comment by miketheman** [comment]
Sure - I was using the `vmwarefusion` driver. I could likely test the behavior against the `virtualbox` driver if that would help.

**Comment by ehazlett** [comment]
@miketheman yeah that would help us narrow it down.  thanks!

**Comment by miketheman** [comment]
Well, I was inspired once I ran the virtualbox driver and everything worked the way I thought it would, so I went down the rabbit hole to figure it out, and I think found some other things along the way.
I opened a PR #1206 with my changeset - please review and let me know if I went completely crazy, the wrong way, or if it makes sense.
Thanks!

**Comment by docteurklein** [comment]
The same problems appears on (only) one of my aws instance as well.
The thing is that `docker-machine ssh` works well tho.

**Comment by miketheman** [comment]
@docteurklein This is a driver-specific implementation responsibility, so should be addressed in a separate issue. 

Could you possible open another issue with information, and debug details, similar to the initial report? 
Having versions of all the pieces is useful - especially if you'e saying it happens to only one of your AWS instances.
