### ISSUE TITLE
msysgit workflow on windows doesn't work at all with current master

### ISSUE THREAD

**Issue by nathanleclaire** [docker/machine#1170]
The msysgit workflow on Windows doesn't work at all right now, with `env` we just bail and tell the user that it's not supported Windows without the `--shell` flag.  This chucks out users of Cygwin as well, which is unfortunate as I've seen at least one instance of someone using `docker-machine` on Cygwin in the wild.  Do we want to deprecate using msysgit entirely?  I think it might be kind of over-ambitious for the time being as all of our docs use it, and personally I would like to keep using msysgit for a while just because I like the UNIX tools etc.  So, maybe allow the standard `env` with a warning line if they're on Windows, or at least add a `--shell sh` type of option?

cc @ehazlett @ahmetalpbalkan @hairyhenderson WDYT

**Comment by ahmetalpbalkan** [comment]
Oh I think we forgot to handle the cygwin case ($SHELL is set) on windows (runtime.GOOS=="windows") in @ehazlett's last PR about this.

IMO, if $SHELL is set (would be the case only on msys/cygwin) `--shell` shouldn't be mandatory (or shouldn't even work –b/c for instance we don't generate fish output in bash).

**Comment by ehazlett** [comment]
We do check for SHELL: https://github.com/docker/machine/blob/master/commands/commands.go#L624

We can't deprecate msysgit as that is the only way to get shared folders since we encourage users to mount volumes via the shared folder.  Let's fix it before just throwing our hands up and dumping it.

How would the warning work?  We can't set anything as it varies depending on powershell vs. cmd.exe.  We error because the command doesn't work.

I'll do some more testing to see if I can find a solution.

**Comment by znmeb** [comment]
@ehazlett There's an option when you install msysgit to adjust the Windows path: 
![msysgit](https://cloud.githubusercontent.com/assets/4938/7644014/c520e884-fa53-11e4-9a95-5b83c048e088.png)

I noticed that Boot2Docker installs msysgit with the default (top radio button selected). When I install msysgit I check the bottom one, which gives me a decent shell.

**Comment by ahmetalpbalkan** [comment]
@znmeb not sure how that's relevant.

@nathanleclaire based on @ehazlett's comment, `machine env` should not require `--shell` on msys bash. (Does it?)

**Comment by nathanleclaire** [comment]
It seemed to be resisting last time I tried master on a Windows computer (last week-ish), but I'll check again.

**Comment by ehazlett** [comment]
msysgit with master:

![2015-05-15-101037_1048x531_scrot](https://cloud.githubusercontent.com/assets/260642/7654375/acb4b7b6-faea-11e4-8991-058aee87cecd.png)

**Comment by ehazlett** [comment]
update:

with `eval` and `docker`

![2015-05-15-101150_999x480_scrot](https://cloud.githubusercontent.com/assets/260642/7654405/d6bf2b68-faea-11e4-9c86-ea6ceaceb25f.png)

**Comment by nathanleclaire** [comment]
Yeah, I'm not sure what was going on or maybe I was just using an old version, but it seems to work on Windows 7 and Windows 8.1 with master when I tried last night.  Going to close this.
