### ISSUE TITLE
cloud-init support?

### ISSUE THREAD

**Issue by MNT-Mantas** [docker/machine#1185]
I've read many issues and pull requests here, but I couldn't get clear information whether cloud-init support is comming. I'm interested in cloud-init support for DO driver with CoreOS.

**Comment by ehazlett** [comment]
@MNT-Mantas there are plans but not all providers support cloudinit nor do they support all features needed for cloud-config.  We want to get there eventually, but with the various providers it's more complex than initially thought.  We want it but not sure when it will get in.
