### ISSUE TITLE
Machines are in a broken state when creation fails

### ISSUE THREAD

**Issue by nathanleclaire** [docker/machine#119]
Consider this example:

```console
$ machine ls
NAME   ACTIVE   DRIVER   STATE   URL

$ machine create -d amazonec2 --amazonec2-access-key foo --amazonec2-secret-key bar --amazonec2-subnet-id quux spam
INFO[0000] Launching instance...
FATA[0000] Problem with AWS API call: Non-200 API response: code=401 message=AWS was not able to validate the provided access credentials

$ machine ls
ERRO[0000] error getting state for host spam: Problem with AWS API call: Non-200 API response: code=401 message=AWS was not able to validate the provided access credentials

ERRO[0000] error getting URL for host spam: Problem with AWS API call: Non-200 API response: code=401 message=AWS was not able to validate the provided access credentials

NAME   ACTIVE   DRIVER      STATE   URL
spam            amazonec2   Error

$ machine rm spam
ERRO[0000] Error removing machine spam: unabme to terminate instance: unknown instance
FATA[0000] There was an error removing a machine. To force remove it, pass the -f option. Warning: this might leave it running on the provider.

$ machine ls
ERRO[0000] error getting state for host spam: Problem with AWS API call: Non-200 API response: code=401 message=AWS was not able to validate the provided access credentials

ERRO[0000] error getting URL for host spam: Problem with AWS API call: Non-200 API response: code=401 message=AWS was not able to validate the provided access credentials

NAME   ACTIVE   DRIVER      STATE   URL
spam            amazonec2   Error

$ machine rm -f spam
ERRO[0000] Error removing host, force removing anyway: unabme to terminate instance: unknown instance

$ machine ls
NAME   ACTIVE   DRIVER   STATE   URL
```

User should not have to `machine rm -f` at all.  If there is _any_ error with `machine create`, machine should clean up the failed host create.

**Comment by ehazlett** [comment]
What if we do the following:

If DEBUG is enabled, we do not automatically cleanup the reference nor attempt to remove the provisioned instance.

If not, we show the error and then remove the reference and attempt to remove the possibly provisioned instance.  We also show a warning that states all resources may not have been removed.

Thoughts?

**Comment by bfirsh** [comment]
If a machine might have been created, we definitely want to keep around the local reference. Otherwise the user might not know they have created an instance and they'll be charged money for it.

Perhaps along with an error, we explain that your machine might be in a broken state, and give you instructions on how to remove it.

**Comment by ehazlett** [comment]
@bfirsh ok makes sense 

So perhaps this:  if DEBUG, things basically perform as they do today and leave it in whatever state along with a message stating something went wrong and general instructions for cleanup.

By default, it would report and error and attempt to do the remove / cleanup but still report the instructions "just in case".

Thoughts?

/cc @nathanleclaire @sthulb

**Comment by sthulb** [comment]
My thinking is, "normal" mode should clean up, if we're in a state we know we can clean up from. 

Debug mode should act as we do now, leave things in place with a note telling people the resources are there still.

**Comment by ehazlett** [comment]
@sthulb cool -- thanks

**Comment by ehazlett** [comment]
@bfirsh @nathanleclaire @sthulb could you take a look at #234 and see if it makes sense?  Thanks!

**Comment by ehazlett** [comment]
Closing as #234 is merged.

**Comment by ehazlett** [comment]
Re-opening.  If you happen to try to create a machine with the same name as an existing machine, this will remove the old one.

**Comment by nathanleclaire** [comment]
Yes.  As mentioned in IRC but I actually have changed my mind on the PR that was submitted to address this due to discussion with @bfirsh and @SvenDowideit.  Auto-remove seems to be causing too many problems, I was wrong.  If you CTRL+C in the middle of a `create`, for instance, the reference will not get cleaned up.

I think leaving the machines around in an error state is fine.  However, I don't really like the extra "ERROR" logs that pop up when you run `machine ls` or something if the state of the machine is `Error`.

**Comment by ehazlett** [comment]
Ok thx.  I agree with the extra logging.  I would like to clean up logging
in general as each driver seems to do its own thing.

**Comment by ehazlett** [comment]
I think I will close this as we've reverted the auto-cleanup and fixed some of the logging.  We are looking to standardize the way we handle common tasks (create, remove, etc) and I think the error reporting can be a part of this.  We can use #392 to track that.

**Comment by oleggen** [comment]
I've managed to remove it by removing the right folder from here ~/.docker/machine/machines/
Origin: https://www.digitalocean.com/community/questions/can-t-remove-a-docker-machine

Sorry for commenting on an old thread but I googled it and thought it might help others. 

A thought: maybe the rm -f should be able to remove even if there's no connection.

**Comment by jlsjonas** [comment]
>A thought: maybe the rm -f should be able to remove even if there's no connection.

Especially if the error is that the instance doesn't exist (anymore) 😅
