### ISSUE TITLE
vSphere Incorrect Usage

### ISSUE THREAD

**Issue by kojiromike** [docker/machine#1194]
I've tried several iterations to run docker-machine with vSphere. The only output I get is 'Incorrect Usage', so I'm not sure what I'm doing wrong.

- I'm using `0.2.0`.
- I have `govc` installed and on my PATH.
- This is all on OS X Yosemite.

At my last attempt I tried the following invocation:

```
docker-machine create \
               --drive vmwarevsphere \
               --vmwarevsphere-compute-ip 10.48.177.24 \
               --vmwarevsphere-cpu-count 2 \
               --vmwarevsphere-datacenter 'Las Vegas' \
               --vmwarevsphere-datastore local_lvsprdhv11701 \
               --vmwarevsphere-disk-size 20000 \
               --vmwarevsphere-memory-size 2048 \
               --vmwarevsphere-network 'VLAN 2006' \
               --vmwarevsphere-password ***** \
               --vmwarevsphere-username *****
```

I've also tried using environment variables instead of `--flag` options, various ways of ordering the options, and different values for various options, but it's very difficult to tell what the problem is.

I realize Machine is pre-release software. If anyone knows what I am not understanding from `docker-machine help create`, or if there is soon going to be a patch to improve the error reporting, that would greatly help me.

**Comment by UserTaken** [comment]
```
docker-machine create \
               --drive vmwarevsphere \
               --vmwarevsphere-compute-ip 10.48.177.24 \
               --vmwarevsphere-cpu-count 2 \
               --vmwarevsphere-datacenter 'Las Vegas' \
               --vmwarevsphere-datastore local_lvsprdhv11701 \
               --vmwarevsphere-disk-size 20000 \
               --vmwarevsphere-memory-size 2048 \
               --vmwarevsphere-network 'VLAN 2006' \
               --vmwarevsphere-password ***** \
               --vmwarevsphere-username *****
```

does not look like you specified a machine name.

**Comment by kojiromike** [comment]
Derp! Thanks.

In my defense, neither `docker-machine help` nor `docker-machine help create` actually say anything about naming the machine. It may seem obvious now, but I had assumed the name would be set automatically in a docker-like fashion.

But yeah, that was it.

**Comment by UserTaken** [comment]
At the bottom it says

```
$ docker-machine create

...

--swarm-discovery 							Discovery service to use with Swarm
--swarm-host "tcp://0.0.0.0:3376"			ip/socket to listen on for Swarm master
--swarm-addr 								addr to advertise for Swarm (default: detect and use the machine IP)
You must specify a machine name
```

but at the the top it would probably help to specify 
```
$ docker-machine create

Usage: docker-machine create [OPTIONS] [arg...] NAME
```

**Comment by kojiromike** [comment]
I just checked again, and your output is different from mine:

```
09:37 ~ $ docker-machine --version
docker-machine version 0.2.0 (HEAD)
09:38 ~ $ docker-machine help create 2>&1 | grep specify
09:38 ~ $ docker-machine create --help 2>&1 | grep specify
09:39 ~ $ docker-machine help create 2>&1 | grep -iF usage # sanity check
USAGE:
```

**Comment by UserTaken** [comment]
```
$ docker-machine -v
docker-machine version 0.3.0-dev (15e0222)
```

**Comment by kojiromike** [comment]
OK, so it's fixed in git. Good enough for me!
