### ISSUE TITLE
drivers: add joyent triton driver

### ISSUE THREAD

**Issue by twhiteman** [docker/machine#1196]
Add Joyent Triton cloud platform which implements the docker remote API.

## Configuration
*--triton-region* - the SDC to use (e.g. us-east-3b)
*--triton-account* - user login name
*--triton-key* - SSH key used for the account

## Supported commands
* create
* env
* inspect
* ip
* ls
* rm

## Unsupported commands
These commands are not useful for the SDC platform:
* kill
* restart
* ssh, scp
* start
* stop
* upgrade

## Notes

Triton provides a dynamic and flexible docker cloud environment, and the provisioning of individual machines isn't required for Triton.

Triton (SDC) is open-source: https://github.com/joyent/sdc
SDC-docker is the open-source docker remote API endpoint for SDC: https://github.com/joyent/sdc-docker

**Comment by ehazlett** [comment]
Did you mean to open a pull request?

**Comment by dgageot** [comment]
@docker/machine-maintainers With the introduction of driver plugins, we should close this ticket, shouldn't we?

**Comment by nathanleclaire** [comment]
Yes, @twhiteman please take a look at the new plugin model!
