### ISSUE TITLE
Creation of Hyper-V machine hangs on 'Got IP, waiting for SSH' in Windows 10

### ISSUE THREAD

**Issue by alek-sys** [docker/machine#1203]
Hi,
I understand that Windows 10 is preview only but I believe that is not a Windows issue but something I'm missing. Here is what I do from *elevated* command prompt:
`> docker-machine --version`
docker-machine version 0.2.0 (8b9eaf2)
`> docker-machine --debug create -d hyper-v dev`
_(tons of output from machine - https://gist.github.com/alek-sys/067b15158a6fd04ba792)_
**INFO[0063] Got IP, waiting for SSH**
DEBU[0063] [executing ==>] : C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe (( Get-VM -Name dev ).networkadapters[0]).ipaddresses[0]

**DEBU[0067] [stdout =====>] : fe80::215:5dff:fe00:603**

(*DEBU[0067] [stderr =====>] :**

And that is it. It hangs for a while, then I stop it with Ctrl+C. When I go to Hyper-V manager - dev machine is there, I can connect to it and everything seems fine.

My guess is ipv6 - Hyper-V assigns fe80::215:5dff:fe00:603 to new create machine, I cannot do ssh -6 fe80::215:5dff:fe00:603 so this might be the reason?

OS Name:                   Microsoft Windows 10 Pro Insider Preview
OS Version:                10.0.10074 N/A Build 10074

**Comment by nathanleclaire** [comment]
cc @ahmetalpbalkan

**Comment by ahmetalpbalkan** [comment]
I have no idea about hyperv driver. @jhowardmsft

**Comment by jhowardmsft** [comment]
I have no idea either, or anything about docker-machine. What it looks like is something is trying to connect to SSH in a Hyper-V VM called 'dev'. Are you sure there is an SSH daemon running inside the Hyper-V VM? Is this specific to Windows 10 and something that worked on 8.1?

**Comment by alek-sys** [comment]
SSHD daemon is running
`> ps -a | grep sshd`
1266 root /usr/local/sbin/sshd

However I cannot connect to the host from command line
`> ssh -6 fe80::215:5dff:fe00:604`
ssh: fe80::215:5dff:fe00:604: no address associated with name

Cannot test in Win 8.1 but believe it works fine. So it probably something specific to my Windows / Hyper-V and I'm trying to understand the direction where to look. Is that ok there is no ssh command output in log? `ssh` is available in PATH, of course. 

Forgot to mention, there is no any antivirus or firewall running.

**Comment by alek-sys** [comment]
Ah, ok, it was my ignorance. 
So as I thought the issue seems to be related to the network set up. I've been using Virtual Switch with type 'Internal network' and this type of switch only assign IPv6 addresses to containers and do not allow to access them externally. So I've changed the switch from 'Internal' to 'External', VM got a proper IPv4 address and machine was successfully created.
