### ISSUE TITLE
Document that changing the image, e.g. AMI, also usually entails changing the SSH user

### ISSUE THREAD

**Issue by nathanleclaire** [docker/machine#1204]
This one caught me off guard, it will probably bite others as well.  @ehazlett and I agree that it is perfectly fine to expect users to change the SSH user if they are changing the base image, however it should probably be documented and have a "NOTE" or something which warns that this should be the case.

**Comment by nathanleclaire** [comment]
This is done now!

**Comment by ehazlett** [comment]
:+1:
