### ISSUE TITLE
Update Swarm node address arg to --advertise

### ISSUE THREAD

**Issue by ehazlett** [docker/machine#1205]
The `--addr` option is changing in Swarm to `--advertise`.

`--addr` is staying for compatibility in 0.3.  We will update this for 0.4.

Refs https://github.com/docker/swarm/issues/817

**Comment by aluzzardi** [comment]
We finally ended up using `--advertise` (docker/swarm#858).

Merged in master but we **kept backward compatibility** (`--addr` will continue working)

**Comment by ehazlett** [comment]
@aluzzardi perfect!  thanks for the heads up -- we will get it updated :)

**Comment by thaJeztah** [comment]
Can you update the title and description of this issue? It's a bit confusing now :smile:

**Comment by nathanleclaire** [comment]
Hm, @ehazlett let's make sure not to forget about this before the release.
