### ISSUE TITLE
virtualbox: Unable to use VBoxManage to set Port Forwarding after machine is created

### ISSUE THREAD

**Issue by dave-tucker** [docker/machine#1209]
Attempting to do this from  the CLI fails, but you can do it from the GUI (Settings > Network > Port Forwarding)

``` 
$ VBoxManage modifyvm "registry" --natpf1 "registryv2,tcp,127.0.0.1,5000,,5000"
VBoxManage: error: The machine 'registry' is already locked for a session (or being unlocked)
VBoxManage: error: Details: code VBOX_E_INVALID_OBJECT_STATE (0x80bb0007), component Machine, interface IMachine, callee nsISupports
VBoxManage: error: Context: "LockMachine(a->session, LockType_Write)" at line 471 of file VBoxManageModifyVM.cpp
```

and the process which I assume has the lock:

```
$ ps ax | grep -i virtualbox
 37861   ??  U      0:36.58 /Applications/VirtualBox.app/Contents/MacOS/VBoxHeadless --comment registry --startvm a9fe4a13-5dff-4157-9b5a-027eca1c79ed --vrde config
```

Hopefully, somebody with more Virtualbox-jitsu might be able to make this work!

**Comment by UserTaken** [comment]
Use `vboxmanage controlvm` for running machines.

**Comment by ehazlett** [comment]
@dave-tucker does the above work for you?

**Comment by dave-tucker** [comment]
@UserTaken you rock - have a cookie :cookie:!
@ehazlett yes that fixed it... if you can point me to a place in the docs where I could write this up, i'll happily write a PR

**Comment by ehazlett** [comment]
@dave-tucker probably a hint here https://github.com/docker/machine/blob/master/docs/index.md#oracle-virtualbox would be best.  thanks!
