### ISSUE TITLE
--engine-insecure-registry

### ISSUE THREAD

**Issue by dmlond** [docker/machine#1210]
I was looking at the [Documentation](https://github.com/docker/machine/blob/309afd11129a88baa81f21803f5b83fcfd680d04/docs/index.md) and it mentions the use of the --engine-insecure-registry URL option to docker-machine create.  I am using:

```bash
docker-machine -v
docker-machine version 0.2.0 (8b9eaf2)
```

and I do not see these options.  I was hoping to play around with deploying a registry on one docker-machine without a tls cert, and run another docker-machine with this flag to push/pull registries from the insecure registry.

Is there a better way to configure a docker machine to allow insecure registries?

**Comment by ehazlett** [comment]
The docs for the current release are at http://docs.docker.com/machine/.  The docs you are referring to are for master.  If you would like to test the current build you can get the latest master builds from https://docker-machine-builds.evanhazlett.com/latest/.

Thanks!

**Comment by dmlond** [comment]
Hi,
Thanks so much. I didnt realize that link took me to master.  I appreciate
it.
I may try out the master build

**Comment by ehazlett** [comment]
You are welcome!
