### ISSUE TITLE
docker machine 0.2.0 amazonec2 driver cannot run in AWS China(cn-north-1)

### ISSUE THREAD

**Issue by xiaoluffy** [docker/machine#1224]
is there something wrong with cn-north-1 region URL?
hi. I execute the command and return an error:

docker-machine create --driver amazonec2 --amazonec2-region=cn-north-1 --amazonec2-root-size=5 --amazonec2-vpc-id=vpcxxxx --amazonec2-subnet-id=subnetxxxxx --amazonec2-access-key=<key> --amazonec2-secret-key=<key> --amazonec2-ami=ami-fe7ae8c7 --amazonec2-zone=a --amazonec2-security-group=docker-machine --swarm --swarm-master --swarm-discovery token://d270bd78882e04e1ee987de3f7270db6 swarm master

client encountered error while doing the request: Get https://ec2.cn-north-1.amazonaws.com/?Action=DescribeKeyPairs&Version=2014-06-15: dial tcp: lookup ec2.cn-north-1.amazonaws.com: no such hostERRO[0000] Error creating machine: Problem with AWS API call: client encountered error while doing the request: Get https://ec2.cn-north-1.amazonaws.com/?Action=DescribeKeyPairs&Version=2014-06-15: dial tcp: lookup ec2.cn-north-1.amazonaws.com: no such host 
WARN[0000] You will want to check the provider to make sure the machine and associated resources were properly removed. 
FATA[0000] Error creating machine

Thanks.

**Comment by ehazlett** [comment]
That doesn't look like a valid endpoint.  http://docs.aws.amazon.com/general/latest/gr/rande.html#ec2_region

Please re-open if this isn't correct.  Thanks!

**Comment by xiaoluffy** [comment]
Hi, BOSS~
cn-north-1 (a or b) is a Isolated Region, so URL may be different. 
http://docs.aws.amazon.com/general/latest/gr/isolated_regions.html

Thanks.

**Comment by dr-impossible** [comment]
The correct endpoint is ec2.cn-north-1.amazonaws.com.cn

Reference: http://docs.amazonaws.cn/en_us/general/latest/gr/rande.html#cnnorth_region
