### ISSUE TITLE
Proposal: Language Bindings (Python)

### ISSUE THREAD

**Issue by prologic** [docker/machine#1226]
Out of curiosity; would anyone be interested in this?

On a technical note (*not really having developed in Go yet*) what would it take to create language bindings for say Python (*CPython*)?

If anyone else is interested in this (*besides me*) I'd definitely want to have a go and submit a PR against this issue!

**Comment by nathanleclaire** [comment]
I would definitely like to see this kind of thing, most likely in the short-term the way to make this happen would be to use the proposed `libmachine` (https://github.com/docker/machine/issues/1211) to create a binary which is easy to interact with from Python (e.g. it expects input from STDIN as JSON, and spits out JSON as a result).  I'm not sure about natively bridging the code, it looks a little tricky.

**Comment by nathanleclaire** [comment]
I think this is out of scope for the main Machine repo, but have at it if you are interested!!  I would really like to have you involved with all discussion around `libmachine` and any kind of declarative configuration if we end up implementing that as well.

**Comment by prologic** [comment]
@nathanleclaire Yeah no worries at all; right now I haven't had much time to *think* about how other language bindings *could* be acheived at this point. However I did come up with [factory](https://github.com/prologic/factory) -- Is this what you meant by declarative machines?

**Comment by nathanleclaire** [comment]
Yep, it's similar.  I saw that and that's why I thought you might be interested :D

**Comment by prologic** [comment]
Most definitely :)

**Comment by jakirkham** [comment]
Sounds like a really cool idea.
