### ISSUE TITLE
Server-side certs are too restrictive, need ability to add extra SANs

### ISSUE THREAD

**Issue by samalba** [docker/machine#1227]
Right now, each generated server-side certificate (both for the Swarm master and the docker daemon) contain only one SAN (Subject Alt Name) which points to the Host IP (usually localhost).

This makes it too restrictive, it's not possible to connect to my Swarm API from my internal network...

I propose a global option `--tls-san' which allows to specify extra SANs.

**Comment by tyrken** [comment]
My (one-sided) discussion in #1233 is about the driver=none case, but if docker-machine were to be production-ized as a "VM appliance producer" then I'd want to be able to pass in custom server certs made by my own CA, at which point I can pre-add my own SANs in the external CSR.  Custom client-certs/client-auth-CA-at-server also.
