### ISSUE TITLE
Proposal: (re-)Add Upgrade() to Driver interface

### ISSUE THREAD

**Issue by frapposelli** [docker/machine#1230]
The `vmwarevsphere` driver uploads the boot2docker iso to a remote ESXi host, upgrading that iso without a direct way to trigger an upgrade function in the driver is extremely cumbersome.

I would ideally trigger the Upgrade from the boot2docker upgrade functions, once the new iso has been copied to the local machine folder.

There is still an Upgrade() stub left in the driver, as I recall it used to be part of the interface, can we reinstate that? I'm sure there are other use cases that would mandate for that.

**Comment by ehazlett** [comment]
This looks like a left-over artifact.  I don't believe `Upgrade` is valid anymore (https://github.com/docker/machine/blob/master/drivers/drivers.go) we should remove that.

As far as the upgrade process, we would have to take a look for vsphere's case.  I think it's unique as openstack uses an ubuntu image.  Perhaps that's an alternative?

**Comment by frapposelli** [comment]
From a very quick look at the openstack driver code seems like you need to provide your own image, I'd rather stick with b2d as it's a much better UX.

**Comment by dgageot** [comment]
@frapposelli Thanks for sharing this idea. This is not something we plan to do. Upgrade process clearly needs some improvement but we have no plan delegating this process to the plugins.
