### ISSUE TITLE
Give arguments like -e to machine for swarm containers (proxy environment)

### ISSUE THREAD

**Issue by pacaletx** [docker/machine#1241]
Hi,

I didn't find an issue about that, and it's my first post, sorry if it's already exists or if the issue is not "right".

Problem: 

My problem is I start VM's using docker-machine in proxy environment, so my containers need some http_proxy to work.
When i start my containers, i put these variables, but if I want to use docker-machine --swarm, my swarm containers won't have these variables, so for example I can't use the token discovery system (cause they won't have internet).

Solution:

For example it could exist an option for docker-machine to specify swarm containers options: docker-machine create ... --swarm --swarm-parameters -e http_proxy=myproxy

Will start swarm agent with the -e variable.

Thanks for helping/advices.

**Comment by pacaletx** [comment]
Is it what engine-opt does ?

**Comment by ehazlett** [comment]
You are asking for preset environment variables to be passed to each container upon launch?  Machine doesn't do that currently nor do I think it should.  That is a container launch time setting.

`--engine-opt` allows setting Docker Engine options -- i.e. storage backend, graph directory, etc.

**Comment by pacaletx** [comment]
So i should not use --swarm when i create my machine and start my swarm containers by myself ?

**Comment by ehazlett** [comment]
Even if you run swarm by itself it still will not pass a default environment variable for every container.  That would be in the system that launches containers.  I'm not sure I'm fully understanding your question.  Are you trying to set a host level environment variable or just pass a set of default variables to each container?

**Comment by pacaletx** [comment]
I don't want that docker-machine does it for every containers, just for the swarm containers when i use --swarm.
I understand what you understood, i want my variable for the swarm containers themselves, not for the containers that i start in the cluster (for that as you said i do it myself).

The variables are just for my swarm agents & swarm managers containers.

If I start my swarm containers by myself on my machines, i can give my variables to the docker deamon, if I use --swarm, I can't right ? Cuase docker-machine does the "docker run swarm" for me.

**Comment by ehazlett** [comment]
Ah I see.  So just allowing to pass environment variables to the Swarm containers.  I don't see huge objections to this.

/cc @nathanleclaire thoughts?

**Comment by nathanleclaire** [comment]
So just to be clear, you want to set `HTTP_PROXY` for _only_ the Swarm containers, not every container? Why not every container, out of curiosity?

**Comment by pacaletx** [comment]
Yup my need is for only the Swarm containers.

Actually I may need it for every container, but for the containers I start myself I can do it by myself, the problem is I can't use the --swarm option (with token discovery method) if I can't tell to docker-machine this variable, I have to start my swarm containers by myself, and I suppose it's a little bit sad to do something manually when docker-machine is also able to do ^^

**Comment by nathanleclaire** [comment]
I think this falls into the general class of issues where specifying `HTTP_PROXY` for the daemon is needed.  Do you agree @pacaletx @ehazlett ?

**Comment by pacaletx** [comment]
It's in the same area yes.

**Comment by phathocker** [comment]
I would like to configure it for all containers.  Is that easier to do?

**Comment by nathanleclaire** [comment]
> I would like to configure it for all containers. Is that easier to do?

If you're going to be using such a wide-ranging proxy, why not set it at the firewall level?

**Comment by phathocker** [comment]
I don't have control of the firewalls but I do of the servers.  I agree with your statement that the specify HTTP_PROXY for daemon is needed

**Comment by danmerino** [comment]
I also would like to be able to give swarm environmental variables.

For example: https://github.com/gliderlabs/logspout allows ignoring logging from individual containers based on environmental variables. I do not want the swarm logs to pushed up.

**Comment by nathanleclaire** [comment]
We now have a PR merged into master for this.  All engine environment variables `--engine-env`, will be propagated to the Swarm containers as well.
