### ISSUE TITLE
Allow custom image for gce

### ISSUE THREAD

**Issue by mberhault** [docker/machine#1243]
The vm image for GCE is currently hard-coded.
It would be nice to be able to specify this on the command-line (either full resource URL, or project-name/image-name).

Setting up docker on GCE with ubuntu images requires installing linux-image-extra-*-generic for aufs support. This installs a few things and reconfigures many more, and ends up spending a lot of time in update-initramfs calls.

Anyway, with all that, just creating a docker machine on GCE from scratch takes ~15 minutes.
I'd like to cut down on this by creating my own image from an existing one, then re-use it.
However, without a custom --google-image flag, this is a bit tricky.

Would it be possible to add such a flag? Many of the other drivers allow custom images.

**Comment by aperepel** [comment]
Hi, a duplicate issue #617 was filed back in Feb '15, and had a discussion about cloudinint superseding all those options, but from recent discussions here it sounds like cloudinit might not be a solid solution for every provider out there, and might not be the way forward.

Where does it leave this feature? We don't have cloudinit, and we don't have a way to change GCE image (I need to work with CentOS, not Ubuntu).

Any feedback is greatly appreciated :)

**Comment by nathanleclaire** [comment]
We're happy to accept such a feature, however @ehazlett and I have not had time to work on it.  cc @jeffmendoza @proppy perhaps you guys could contribute it as you know the code.

**Comment by aperepel** [comment]
Who knows, maybe I'll contribute a PR, it didn't look like a very difficult part of a codebase. I know you guys are busy with all kinds of other cool features.

It all depends on how those wheels are greased with my first patch. It's sitting green and ready to go, according tobTravus CI :)

**Comment by jeffmendoza** [comment]
Would machine work with CentOS? I thought it assumes Ubuntu and does apt-get, etc.

**Comment by nathanleclaire** [comment]
@jeffmendoza Yep, support for CentOS, though experimental, was recently added: https://github.com/docker/machine/blob/master/libmachine/provision/centos.go

**Comment by jeffmendoza** [comment]
Ah cool.

**Comment by aperepel** [comment]
So far had no issues with CentOS, as long as you go with CentOS 7.x (6.x has an older kernel and isn't very stable for Docker needs)

**Comment by aperepel** [comment]
Hey guys, I've sent a PR https://github.com/docker/machine/pull/1350 - things work well for me. I've updated the machine docs in this PR as well, take a look.

**Comment by ehazlett** [comment]
@aperepel thanks i'll take a look!
