### ISSUE TITLE
New status command

### ISSUE THREAD

**Issue by robwithhair** [docker/machine#1249]
There should be a way to find out if the machine is running without having to parse the output from `ls` command.  Ideally I'd suggest a status command which you can pass the machine name to and it will output something like running or stopped.  Also would be handy to have status optionally added to inspect command json output.

**Comment by ehazlett** [comment]
I think this would be ok.  You can already filter based on state.  Perhaps a filter based upon name?  /cc @hairyhenderson

**Comment by hairyhenderson** [comment]
@robwithhair - does this do what you want?

```sh
$ docker-machine ls                       
NAME             ACTIVE   DRIVER         STATE     URL                        SWARM
dev                       vmwarefusion   Stopped                              
hairyhenderson            digitalocean   Running   tcp://1.2.3.4:2376
$ docker-machine ls --filter state=Running
NAME             ACTIVE   DRIVER         STATE     URL                        SWARM
hairyhenderson            digitalocean   Running   tcp://1.2.3.4:2376
```

**Comment by robwithhair** [comment]
Hey, didn't know you could do that. Filter would be ideal yes. Particularly if you could use the -q option with it. 

Sent from my iPhone

> On 27 May 2015, at 18:26, Evan Hazlett <notifications@github.com> wrote:
> 
> I think this would be ok. You can already filter based on state. Perhaps a filter based upon name? /cc @hairyhenderson
> 
> —
> Reply to this email directly or view it on GitHub.
> 

--

**Comment by hairyhenderson** [comment]
Also, I think adding current state to `inspect` would be useful, however there's been some discussions about `inspect`'s role, and it's unclear how state would fit in. 

/cc @nathanleclaire

**Comment by robwithhair** [comment]
The use case for me would be to test if a container is running or not. Filter will allow me to do this which is great, however it is not as simple as perhaps it might be. Either documentation or an alias command maybe useful for others trying a similar thing.

Sent from my iPhone

> On 27 May 2015, at 18:26, Evan Hazlett <notifications@github.com> wrote:
> 
> I think this would be ok. You can already filter based on state. Perhaps a filter based upon name? /cc @hairyhenderson
> 
> —
> Reply to this email directly or view it on GitHub.
> 

--

**Comment by robwithhair** [comment]
Whether inspect is used or not, I feel there ought to be a better way to start a machine if it is stopped or stop a running machine if there are no running docker containers on that machine. This was the original problem I was facing. I think now I know about the filter option this will be a lot easier. 

Sent from my iPhone

> On 27 May 2015, at 18:35, Dave Henderson <notifications@github.com> wrote:
> 
> Also, I think adding current state to inspect would be useful, however there's been some discussions about inspect's role, and it's unclear how state would fit in.
> 
> /cc @nathanleclaire
> 
> —
> Reply to this email directly or view it on GitHub.
> 

--

**Comment by hairyhenderson** [comment]
The docs are here: https://github.com/docker/machine/blob/master/docs/index.md#ls

This will be a new feature in 0.3.0 though, so the released docs (at http://docs.docker.com/) aren't yet up-to-date :)

**Comment by hairyhenderson** [comment]
@robwithhair it sounds like `ls --filter` is good enough for your use case - can this issue get closed, or is there anything outstanding?

**Comment by robwithhair** [comment]
Sure
