### ISSUE TITLE
invalid spdelta 0 -1/runtime: unexpected return pc for  called from 0xb5581000/fatal error: unknown caller pc

### ISSUE THREAD

**Issue by stefan-jones** [docker/machine#1260]
Brand new to docker-machine. installed it on a Linux VM; it is being used, together with swarm, for an application install.

[root@XXX ~]#  uname -a
Linux XXX.XXXX.XXX 3.10.0-229.4.2.el7.x86_64 #1 SMP Wed May 13 10:06:09 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

[root@XXX ~]# docker version
Client version: 1.6.0
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): 8aae715/1.6.0
OS/Arch (client): linux/amd64
Server version: 1.6.0
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server): 8aae715/1.6.0
OS/Arch (server): linux/amd64

[root@XXX ~]# service docker status
Redirecting to /bin/systemctl status  docker.service
docker.service - Docker Application Container Engine
   Loaded: loaded (/etc/systemd/system/docker.service; enabled)
   Active: active (running) since Thu 2015-05-28 09:32:53 PDT; 14min ago
     Docs: http://docs.docker.com
 Main PID: 12316 (docker)
   CGroup: /system.slice/docker.service
           └─12316 /usr/bin/docker -d -H fd://

Downloaded docker-machine linux binary from: https://github.com/docker/machine/releases/download/v0.2.0/docker-machine_linux-amd64.

Placed in path, with run permissions:
-rwxr-xr-x. 1 root root 11961936 May 28 08:55 /usr/bin/docker-machine

[root@XXX ~]# docker-machine version
invalid spdelta 0 -1
runtime: unexpected return pc for  called from 0xb5581000
fatal error: unknown caller pc

runtime stack:
runtime.throw(0x106de31)
        /usr/src/go/src/pkg/runtime/panic.c:520 +0x69
runtime.gentraceback(0x57ff30, 0x7facb8c4e190, 0x0, 0xc208002120, 0x0, 0x0, 0x7fac7fffffff, 0x427b00, 0x7ffffa341158, 0x427700)
        /usr/src/go/src/pkg/runtime/traceback_x86.c:180 +0xba9
copyabletopsegment(0xc208002120)
        /usr/src/go/src/pkg/runtime/stack.c:333 +0xad
runtime.newstack()
        /usr/src/go/src/pkg/runtime/stack.c:759 +0x3f2
runtime.morestack()
        /usr/src/go/src/pkg/runtime/asm_amd64.s:228 +0x61

goroutine 16 [stack growth]:
regexp.func·004(0x7fac0000000e, 0xc208024de0, 0x0)
        /usr/src/go/src/pkg/regexp/onepass.go:334 fp=0x7facb8c4e198 sp=0x7facb8c4e190
regexp.func·004(0x7fac0000000d, 0xc208024de0, 0x1)
        /usr/src/go/src/pkg/regexp/onepass.go:389 +0xc5b fp=0x7facb8c4e360 sp=0x7facb8c4e198
regexp.func·004(0x7fac0000000c, 0xc208024de0, 0x7facb8c4e501)
        /usr/src/go/src/pkg/regexp/onepass.go:389 +0xc5b fp=0x7facb8c4e528 sp=0x7facb8c4e360
regexp.func·004(0x7fac0000000b, 0xc208024de0, 0x1)
        /usr/src/go/src/pkg/regexp/onepass.go:389 +0xc5b fp=0x7facb8c4e6f0 sp=0x7facb8c4e528
regexp.func·004(0x7fac0000000a, 0xc208024de0, 0x1)
        /usr/src/go/src/pkg/regexp/onepass.go:389 +0xc5b fp=0x7facb8c4e8b8 sp=0x7facb8c4e6f0
regexp.func·004(0x7fac00000009, 0xc208024de0, 0xffffffffffffff01)
        /usr/src/go/src/pkg/regexp/onepass.go:389 +0xc5b fp=0x7facb8c4ea80 sp=0x7facb8c4e8b8
regexp.func·004(0x7fac00000008, 0xc208024de0, 0x7facb8c4ec01)
        /usr/src/go/src/pkg/regexp/onepass.go:389 +0xc5b fp=0x7facb8c4ec48 sp=0x7facb8c4ea80
regexp.func·004(0x7fac00000007, 0xc208024de0, 0x7facb8c4ee01)
        /usr/src/go/src/pkg/regexp/onepass.go:389 +0xc5b fp=0x7facb8c4ee10 sp=0x7facb8c4ec48
regexp.func·004(0x7fac00000006, 0xc208024de0, 0x7facb8c4f001)
        /usr/src/go/src/pkg/regexp/onepass.go:389 +0xc5b fp=0x7facb8c4efd8 sp=0x7facb8c4ee10
regexp.func·004(0x7fac00000005, 0xc208024de0, 0x7facb8c4f101)
        /usr/src/go/src/pkg/regexp/onepass.go:389 +0xc5b fp=0x7facb8c4f1a0 sp=0x7facb8c4efd8
regexp.func·004(0x7fac00000004, 0xc208024de0, 0x41af01)
        /usr/src/go/src/pkg/regexp/onepass.go:389 +0xc5b fp=0x7facb8c4f368 sp=0x7facb8c4f1a0
regexp.func·004(0x7fac00000003, 0xc208024de0, 0xa01)
        /usr/src/go/src/pkg/regexp/onepass.go:389 +0xc5b fp=0x7facb8c4f530 sp=0x7facb8c4f368
regexp.func·004(0x7fac00000002, 0xc208024de0, 0xc20801a001)
        /usr/src/go/src/pkg/regexp/onepass.go:369 +0x3e0 fp=0x7facb8c4f6f8 sp=0x7facb8c4f530
regexp.func·004(0x1, 0xc208024de0, 0xc208024d01)
        /usr/src/go/src/pkg/regexp/onepass.go:378 +0x7e3 fp=0x7facb8c4f8c0 sp=0x7facb8c4f6f8
regexp.makeOnePass(0xc208024db0, 0xc208024db0)
        /usr/src/go/src/pkg/regexp/onepass.go:470 +0x42e fp=0x7facb8c4fa90 sp=0x7facb8c4f8c0
regexp.compileOnePass(0xc208024d50, 0xc208024d50)
        /usr/src/go/src/pkg/regexp/onepass.go:576 +0x1b5 fp=0x7facb8c4fb28 sp=0x7facb8c4fa90
regexp.compile(0xb55810, 0x10, 0xd4, 0xc208038de0, 0x0, 0x0)
        /usr/src/go/src/pkg/regexp/regexp.go:168 +0x15f fp=0x7facb8c4fbc0 sp=0x7facb8c4fb28
regexp.Compile(0xb55810, 0x10, 0xc51d60, 0x0, 0x0)
        /usr/src/go/src/pkg/regexp/regexp.go:118 +0x4f fp=0x7facb8c4fbf8 sp=0x7facb8c4fbc0
regexp.MustCompile(0xb55810, 0x10, 0x0)
        /usr/src/go/src/pkg/regexp/regexp.go:219 +0x3f fp=0x7facb8c4fc90 sp=0x7facb8c4fbf8
invalid spdelta 0 -1
runtime: unexpected return pc for  called from 0xb5581000
()
        ?:0 +0x5d7aaa fp=0x7facb8c4fc97 sp=0x7facb8c4fc90
created by _rt0_go
        /usr/src/go/src/pkg/runtime/asm_amd64.s:97 +0x120

goroutine 17 [runnable]:
runtime.MHeap_Scavenger()
        /usr/src/go/src/pkg/runtime/mheap.c:507
runtime.goexit()
        /usr/src/go/src/pkg/runtime/proc.c:1445

goroutine 18 [runnable]:
bgsweep()
        /usr/src/go/src/pkg/runtime/mgc0.c:1976
runtime.goexit()
        /usr/src/go/src/pkg/runtime/proc.c:1445

goroutine 19 [runnable]:
runfinq()
        /usr/src/go/src/pkg/runtime/mgc0.c:2606
runtime.goexit()
        /usr/src/go/src/pkg/runtime/proc.c:1445

goroutine 20 [runnable]:
os/signal.loop()
        /usr/src/go/src/pkg/os/signal/signal_unix.go:19
created by os/signal.init·1
        /usr/src/go/src/pkg/os/signal/signal_unix.go:27 +0x32

**Comment by stefan-jones** [comment]
I used the alternate installation instructions (download using curl, https://docs.docker.com/machine/#osx-and-linux) and this time got a binary that work.

Leaving this issue open, because there's something up with that other binary, clearly labeled for 64 bit linux.

**Comment by ehazlett** [comment]
@stefan-jones thanks for the report.  if you happen to have the old binary i would be curious what the md5 or sha sum is of the binary.

**Comment by stefan-jones** [comment]
[root@x ~]# sha1sum /usr/bin/docker-machine
72fdbcf3b6d3d96f5b04a215c3b1f5316d5aeebd  /usr/bin/docker-machine

[root@x ~]# md5sum  /usr/bin/docker-machine
6794951335d05fb687746f8b945249c3  /usr/bin/docker-machine
[root@x ~]# file  /usr/bin/docker-machine
/usr/bin/docker-machine: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked (uses shared libs), for GNU/Linux 2.6.32, BuildID[sha1]=0xcf83094f8acf5011c84199c4e20f9a2c1a73f42a, not stripped

[root@x ~]# 
[root@x ~]# ls -ltr  /usr/bin/docker-machine
-rwxr-xr-x. 1 root root 12426792 May 28 11:46 /usr/bin/docker-machine

**Comment by ehazlett** [comment]
Is that the current one or the old?

**Comment by stefan-jones** [comment]
I’m sorry. In looking over the command history, I copied over the new (working) binary over the old. I don’t have the old binary to get a checksum from.

Stefan Jones
ARRIS

o: +1 (503) 495-9458
c: -

**Comment by ehazlett** [comment]
Ok.  I'm going to close this for now.  Please re-open if you experience again.  Thanks!
