### ISSUE TITLE
Digital ocean connection issue 

### ISSUE THREAD

**Issue by pix-art** [docker/machine#1265]
So i'm trying out docker-machine it's going nicely but i'm stuck with an annoying issue let me elaborate. It could also be that i'm doing something wrong but I don't see what.
```
docker-machine create --driver digitalocean --digitalocean-region ams2 --digitalocean-access-token secret jmeter-server
INFO[0000] Creating SSH key...                          
INFO[0001] Creating Digital Ocean droplet...            
INFO[0133] "jmeter" has been created and is now the active machine. 
INFO[0133] To point your Docker client at it, run this in your shell: eval "$(docker-machine env jmeter)" 
docker-machine active jmeter-server
eval "$(docker-machine env jmeter-server)"
docker-machine ls
NAME            ACTIVE   DRIVER         STATE     URL                          SWARM
jmeter-server   *        digitalocean   Running   tcp://xxx.xxx.xxx.xxx:2376 
```
So far so good, I see my machine, and it's running and I've selected it. 

But now when I try to do anything on the machine for example:
```
docker info
FATA[0032] An error occurred trying to connect: Get https://xxx.xxx.xxx.xxx:2376/v1.18/info: dial tcp xxx.xxx.xxx.xxx:2376: i/o timeout 
```

All I can see so far is that to create the machine I need a API 2.0 key to create my machine, but to do actions on the machine it's trying to use API 1.18. 

Any idea?

**Comment by pix-art** [comment]
Extra info: This is all executed in a boot2docker environment on a Macbook Pro. Trying this now on a linux environment to see if this is the issue.

**Comment by pix-art** [comment]
This issue is none existent when running on linux. So this seems to be related to boot2Docker

**Comment by ehazlett** [comment]
Yeah looks like a connection issue to the DO API.   Are you able to do other operations such as `ping` or `curl` to a host outside of the VM?

**Comment by nathanleclaire** [comment]
Hi @pix-art !

> All I can see so far is that to create the machine I need a API 2.0 key to create my machine, but to do actions on the machine it's trying to use API 1.18.

So, to clarify, Machine uses the DigitalOcean v2.0 API, but that API 1.18 version you're seeing is the _Docker_ API, which is being served from the created server.  This seems to be an issue connecting to the Docker daemon running on the server.

> This issue is none existent when running on linux. So this seems to be related to boot2Docker

I don't quite understand.  Does this mean you are running the docker-machine command inside of a boot2docker VM when you use it on Mac, or do you use the Darwin binary?

What does the command `docker-machine ssh jmeter-server docker info` print?

**Comment by pix-art** [comment]
Hi @ehazlett,
Pinging works when i run it in b2d

Hi @nathanleclaire,
I just ran your test and this is rather remarkable. When I run "docker info" after  "eval "$(docker-machine env jmeter-server)"" I get 

```
FATA[0014] An error occurred trying to connect: Get https://xxx.xxx.xxx.xxx:2376/v1.18/info: dial tcp xxx.xxx.xxx.xxx:2376: operation timed out
```

but when I run "docker-machine ssh jmeter-server docker info" I get:

```
Containers: 0
Images: 0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 0
 Dirperm1 Supported: false
Execution Driver: native-0.2
Kernel Version: 3.13.0-52-generic
Operating System: Ubuntu 14.04.2 LTS
CPUs: 1
Total Memory: 490 MiB
Name: jmeter-server
ID: my-id
Labels:
 provider=digitalocean
WARNING: No swap limit support
```

So it seems to be an issue with docker inside a boot2docker instance

**Comment by hairyhenderson** [comment]
@pix-art - any reason why you're running docker and/or docker-machine inside a boot2docker instance?

Both docker-machine and docker have native OS X binaries available, so when you're connecting to DigitalOcean, boot2docker is unnecessary.

**Comment by pix-art** [comment]
I think i've just made a pretty big mess up. This was my first experience with Docker and actually thought that I had to run this from within b2d in order to be able to use docker/docker-machine. Thanks for clearing that up. Still not an explanation why it would not work but now I know I was using it wrong :+1:

**Comment by ehazlett** [comment]
@pix-art the networking in vbox is pretty scary.  I would recommend running the Machine binary for the most stability.  Closing for now.  Thanks!
