### ISSUE TITLE
Output from SSH command that fails should be printed

### ISSUE THREAD

**Issue by bfirsh** [docker/machine#1266]
```
$ docker-machine create ...
Creating SSH key...
Creating Digital Ocean droplet...
Error creating machine: exit status 255
You will want to check the provider to make sure the machine and associated resources were properly removed.
```

This isn't particularly helpful. It should probably be something like this:

```
$ docker-machine create ...
Creating SSH key...
Creating Digital Ocean droplet...
Error running command "sudo -E apt-get update" on the Machine. Here is the output:

---------------------------------
... error ...
---------------------------------

You will want to check the provider to make sure the machine and associated resources were properly removed.
```

**Comment by prologic** [comment]
+1

**Comment by nathanleclaire** [comment]
I'm all for storing / showing more information in the case of an error, although I think we need to think about the approach a bit.  Generally where I'm headed is towards having a `docker-machine logs` command which stores anything which gets logged by Machine in flight (including all debug output) to a log file on disk (just like `docker logs`), and that is something which can be queried later by the user, or by us if we want to selectively show things like above.

Bear in mind that there are many cases in Machine where things like SSH commands could fail and it is perfectly fine and normal (e.g. the SSH command timed out so we want to re-try it), so implementing this kind of thing without also spewing "undesirable"/scary error messages at the user is a little trickier than it may look at first glance.

**Comment by nathanleclaire** [comment]
Update:  I may have been a bit hasty.  I think that the "good" SSH failures (testing if SSH is up / working) are largely exit code 255, so perhaps the proposed solution in my PR might work OK for now.
