### ISSUE TITLE
docker-machine  command is Blocked on " Waiting for the SSH server to be started..."

### ISSUE THREAD

**Issue by fifiant** [docker/machine#1267]
I have tried to create a VM on openstack with this comman:

 docker-machine -D create \
 --driver openstack \
 --openstack-auth-url http://xxxx/v2.0\
 --openstack-flavor-id 2 \
 --openstack-image-id ff0dd534-ea07-4144-b4d2-ec1e1f445d7c \
 --openstack-floatingip-pool public \
 --openstack-ssh-user ubuntu \
 --openstack-sec-groups default\
 --openstack-username username \
 --openstack-password xxxxx \
 --openstack-insecure \
 --openstack-tenant-id 6b9b324525774862bf00c0886b89d0d7 \
 --openstack-tenant-name OCCIWARE \
 my-occiware-host

```
username@host-xxx-xxx-xx-xxx:~/xxx$ 

 DEBU[0000] Instantiating OpenStack driver...             caCert=/Users/occiware/.docker/machine/certs/ca.pem machineName=occiware-docker privateKey=/Users/occiware/.docker/machine/certs/ca-key.pem storePath=/Users/occiware/.docker/machine/machines/occiware-docker
DEBU[0000] Authenticating...                             AuthUrl=http://ow2-04.xsalto.net:5000/v2.0 Insecure=false TenantID=6b9b324525774862bf00c0886b89d0d7 TenantName=OCCIWARE Username=username
DEBU[0001] Found floating IP pool id using its name      ID=d68ab5e6-d515-4582-a1f4-58b460f15ab2 Name=public
DEBU[0001] Creating Key Pair...                          Name=occiware-docker-d1158c71391342c839b489bd9b8dc7dfa7a9aba58aeb715648d2a0897c137c97
DEBU[0001] executing: /usr/bin/ssh-keygen ssh-keygen -t rsa -N  -f /Users/occiware/.docker/machine/machines/occiware-docker/id_rsa
 
Generating public/private rsa key pair.
Your identification has been saved in /Users/occiware/.docker/machine/machines/occiware-docker/id_rsa.
Your public key has been saved in /Users/occiware/.docker/machine/machines/occiware-docker/id_rsa.pub.
The key fingerprint is:
b4:ce:f8:1b:fe:97:19:c4:36:14:10:a8:23:eb:ab:b9 occiware@193-51-236-221.lille.inria.fr
The key's randomart image is:
+--[ RSA 2048]----+
|         .oo..   |
|        .   .    |
|       ..  o     |
|    . o. .  =    |
|     o .S  o .   |
|    .  +    .    |
|   .  . +    +   |
|   ..  o .  +    |
|  Eo..  +o..     |
+-----------------+
DEBU[0002] Creating OpenStack instance...                FlavorId=2 ImageId=3956d754-664a-432f-a0b0-da64fe2382a6
INFO[0002] Creating machine...                          
DEBU[0002] Waiting for the OpenStack instance to be ACTIVE...  MachineId=a299517f-a18b-4843-9006-5de979764b66
DEBU[0007] Looking for an available floating IP          MachineId=a299517f-a18b-4843-9006-5de979764b66 Pool=public
DEBU[0007] Available floating IP found                   IP=XX.XX.XX.XX MachineId=a299517f-a18b-4843-9006-5de979764b66
DEBU[0007] Assigning floating IP to the instance         MachineId=a299517f-a18b-4843-9006-5de979764b66
DEBU[0007] IP address found                              IP=XX.XX.XX.XX MachineId=a299517f-a18b-4843-9006-5de979764b66
DEBU[0007] Waiting for the SSH server to be started...   IP=XX.XX.XX.XX MachineId=a299517f-a18b-4843-9006-5de979764b66
```
The problem is that docker-machine  command is still Blocked on " Waiting for the SSH server to be started..." for many minutes without success.

Do you have an idea of what is not going well?

Thanks.

**Comment by ggiamarchi** [comment]
A few questions :
* On the last line of your log, does the IP address match the real floating IP of the newly created instance ?
* Do you manage to SSH into the machine using the `ssh` command from where you launched `docker-machine create` ? If not, are you sure your security group `default` allows SSH ?

**Comment by fifiant** [comment]
> Le 29 mai 2015 à 18:07, Guillaume Giamarchi <notifications@github.com> a écrit :
> 
> A few questions :
> 
> On the last line of your log, does the IP address match the real floating IP of the newly created instance ?
Yes.
> Do you manage to SSH into the machine using the ssh command from where you launched docker-machine create ?
Yes.
> If not, are you sure your security group default allows SSH ?
However my security group default allows SSH.

**Comment by fifiant** [comment]
Thanks ggiamarchi,

My network firewall has blocked the port 22.

All is right now.
