### ISSUE TITLE
In case of Nova error, docker-machine doesn't exit

### ISSUE THREAD

**Issue by fsoppelsa** [docker/machine#1269]
When an instance spawning fails, docker-machine doesn't handle the error and stays hanging for an undefined time. I'd expect it exits in presence of a nova error.

    [root@node-1 ~]# docker-machine -v
    docker-machine version 0.2.0 (8b9eaf2)
    [root@node-1 ~]# docker-machine create --driver openstack --openstack-flavor-name m1.small \
    --openstack-image-name atomic --openstack-net-name net04 --openstack-tenant-name admin a2
    INFO[0001] Creating machine...
    ^C
    [root@node-1 ~]# nova list
    +--------------------------------------+------+--------+------------+-------------+----------+
    | ID                                   | Name | Status | Task State | Power State | Networks |
    +--------------------------------------+------+--------+------------+-------------+----------+
    | 30b088cb-e809-4bcd-8be5-f719a8cad477 | a2   | ERROR  | -          | NOSTATE     |          |
    +--------------------------------------+------+--------+------------+-------------+----------+

**Comment by ggiamarchi** [comment]
You're right. [It waits for 200 seconds](https://github.com/docker/machine/blob/v0.2.0/drivers/openstack/openstack.go#L667) even if the VM status become `ERROR`.  That's a bug.
