### ISSUE TITLE
ap-northeast-1 default AMI is no longer available on AWS

### ISSUE THREAD

**Issue by deniseschannon** [docker/machine#1272]
Tried to launch a docker machine using the default AMI for the ap-northeast-1 and was returned with an error.

`Error creating machine: Error launching instance: Problem with AWS API call: Non-200 API response: code=400 message=The image id '[ami-44f1e245]' does not exist\\n\`

The AMI ID that was attempted to be used is in the docs, but no longer in the public repository for the Tokyo Region.

**Comment by hairyhenderson** [comment]
@ehazlett - would this be fixed by #1222?

**Comment by zchee** [comment]
@hairyhenderson Yes, but current latest each AMI timestamp is 20155028.
I'll fix, and re-pull request later :)

**Comment by ehazlett** [comment]
@hairyhenderson yeah i would think so.  I also didn't think AWS unpublished AMIs.  Maybe they do.  Seems a bad thing to me -- at least the last few versions.

**Comment by ehazlett** [comment]
Closing as #1222 is merged.  Thanks!
