### ISSUE TITLE
Very peculiar behavior with VMware Fusion Shared Folders (1.7 / docker-machine-rc1)

### ISSUE THREAD

**Issue by nathanleclaire** [docker/machine#1275]
I was delighted to find that shared folders with this command seemed to work out of the box with the Docker Machine 0.3.0RC1:

```console
$ docker-machine create -d vmwarefusion --vmwarefusion-boot2docker-url https://github.com/tianon/boot2docker/releases/download/v1.7.0-rc1/boot2docker.iso 1.7rc1
...
$ docker-machine ssh 1.7rc1 ls /Users
Shared
nathanleclaire
```

Woot!  This is exactly what we want, to switch to using the standard b2d ISO for `vmwarefusion`.

Reading from this file seems fine, and everything I'd expect to be able to peek at is there and I can `cat` it, etc.   But there seems to be some very odd behavior, I'm wondering if anyone can dupe or has insight.

Anything I try to write to the share creates a file, but with no content.

e.g.

```
$ docker-machine ssh 1.7rc1
                        ##         .
                  ## ## ##        ==
               ## ## ## ## ##    ===
           /"""""""""""""""""\___/ ===
      ~~~ {~~ ~~~~ ~~~ ~~~~ ~~~ ~ /  ===- ~~~
           \______ o           __/
             \    \         __/
              \____\_______/
 _                 _   ____     _            _
| |__   ___   ___ | |_|___ \ __| | ___   ___| | _____ _ __
| '_ \ / _ \ / _ \| __| __) / _` |/ _ \ / __| |/ / _ \ '__|
| |_) | (_) | (_) | |_ / __/ (_| | (_) | (__|   <  __/ |
|_.__/ \___/ \___/ \__|_____\__,_|\___/ \___|_|\_\___|_|

  WARNING: this is a test.docker.com build, not a release.

Boot2Docker version 1.7.0-rc1, build master : c347ab0 - Thu May 28 05:31:26 UTC 2015
Docker version 1.7.0-rc1, build 395cced
docker@1:~$ echo "This is useless junk" > /Users/nathanleclaire/junk.tmp
docker@1:~$ cat /Users/nathanleclaire/junk.tmp
docker@1.:~$ # Nothing there!!
```

The hostname seems off too due to the `.` - @sthulb maybe I could persuade you to take a look ? - but that seems a separate issue.

cc @ehazlett @SvenDowideit @frapposelli @tianon

**Comment by frapposelli** [comment]
I'm taking a look at that, I remember testing a @SvenDowideit RC image that worked fine.

**Comment by frapposelli** [comment]
Seems like it's something with Kernel 4.x, my iso that's still on 3.18 works correctly:

```shell
~ ⟩ docker-machine ssh svenrc "uname -a && echo 'test test test' > /Users/frapposelli/svenrc-junk.tmp && cat /Users/frapposelli/svenrc-junk.tmp"
Linux svenrc 4.0.2-boot2docker #1 SMP Thu May 14 11:50:18 UTC 2015 x86_64 GNU/Linux
~ ⟩ docker-machine ssh 1.7rc1 "uname -a && echo 'test test test' > /Users/frapposelli/1.7rc1-junk.tmp && cat /Users/frapposelli/1.7rc1-junk.tmp"
Linux 1.7rc1 4.0.4-boot2docker #1 SMP Tue May 26 18:59:42 UTC 2015 x86_64 GNU/Linux
~ ⟩ docker-machine ssh buildbox-fusion "uname -a && echo 'test test test' > /Users/frapposelli/kernel3-junk.tmp && cat /Users/frapposelli/kernel3-junk.tmp"
Linux buildbox-fusion 3.18.11-tinycore64 #1 SMP Sun Apr 19 15:35:01 UTC 2015 x86_64 GNU/Linux
test test test
```

I'll loop these findings internally to see if there are any known incompatibilities, we're in the process of moving the shared folders feature to a FUSE module that will keep all these problems at bay.

**Comment by nathanleclaire** [comment]
@frapposelli Any update on this?  It's getting pretty urgent for the release.

**Comment by frapposelli** [comment]
Right now I don't have an ETA on the fix, unfortunately it's out of my control, the only way to make this work right now is to go back to a pre-4.0 kernel.

**Comment by frapposelli** [comment]
I'm going to find a way to make it work, I'll circle back asap.

**Comment by adambiggs** [comment]
Thanks @frapposelli, this is the only thing holding us back from switching to Docker Machine.

**Comment by frapposelli** [comment]
That was easier than anticipated... see boot2docker/boot2docker#925

```shell
machine · fix-vmhgfs-on-lk4 ⟩ ./docker-machine_darwin-amd64 ssh test-kernel4 "uname -a && echo 'test test test' > /Users/frapposelli/kernel4-junk.tmp && cat /Users/frapposelli/kernel4-junk.tmp"
Linux test-kernel4 4.0.5-boot2docker #1 SMP Wed Jun 10 21:32:03 UTC 2015 x86_64 GNU/Linux
test test test
```

Ping @nathanleclaire @ehazlett @tianon @SvenDowideit

**Comment by nathanleclaire** [comment]
I've verified this as fixed by https://github.com/boot2docker/boot2docker/pull/925#issuecomment-110959938

If anyone wants to test I've published an unofficial 1.7rc2 / fixed Fusion shared folders ISO:

```console
$ dm create -d vmwarefusion --vmwarefusion-boot2docker-url https://s3-us-west-1.amazonaws.com/b2diso/boot2docker-vmhgfs-lk4.iso rc2
```

**Comment by kc8viq** [comment]
Briefly tested with the URL @nathanleclaire provided. Seems to be working for me. Thanks all!

**Comment by ehazlett** [comment]
yay!! :+1:

**Comment by vovimayhem** [comment]
+1!

**Comment by FabienD** [comment]
It works ! Thx
