### ISSUE TITLE
Cannot push to registry

### ISSUE THREAD

**Issue by jehrhardt** [docker/machine#1278]
I have created a vm in VirtualBox with `docker-machine` and want to push to a registry different than Docker hub:

```sh
docker push registry.giantswarm.io/jehrhardt/derjan
```

This results in the following error:

```
FATA[0000] Error response from daemon: v1 ping attempt failed with error: Get https://registry.giantswarm.io/v1/_ping: dial tcp: lookup registry.giantswarm.io on 10.0.2.3:53: too many redirects. If this private registry supports only HTTP or HTTPS with an unknown CA certificate, please add `--insecure-registry registry.giantswarm.io` to the daemon's arguments. In the case of HTTPS, if you have access to the registry's CA certificate, no need for the flag; simply place the CA certificate at /etc/docker/certs.d/registry.giantswarm.io/ca.crt
```

When I create a vm with the boot2docker cli everything works, although the vm image should be the same. The registry and the credentials have also been added to my `$HOME/.dockercfg` file.

Any idea what could be the problem?

**Comment by ehazlett** [comment]
@jehrhardt thanks for the feedback.  Starting in 0.3.0 you can specify engine options.  See https://github.com/docker/machine/blob/master/docs/index.md#specifying-configuration-options-for-the-created-docker-engine

Thanks!
