### ISSUE TITLE
VirtualBox: re-create hostonly interface on Machine start

### ISSUE THREAD

**Issue by ehazlett** [docker/machine#1290]
If you are troubleshooting vbox machines, it can be useful to remove existing host only interfaces and have them re-created.  The only way Machine creates the interface is on `create`.  It would be beneficial to have them checked and re-created on `start` as well.

h/t to @fxdgear for the trouble working through this ;)

**Comment by nathanleclaire** [comment]
Mmmmmm, this is exactly what I'd hoped to address through some kind of "Uniform Resource Model" like mentioned in the roadmap.  We'd have a uniform way to query that thing for existing, and bring the state of the system to where it's meant to be, right now we don't have a formal "schema" for desired state and just kind of wing it :)

**Comment by ehazlett** [comment]
I agree.  However, I think it's beneficial to have for those that have issues with vbox atm.  Thoughts?

**Comment by nathanleclaire** [comment]
Ah, I see, I missed the proposal because I was pushing my own agenda.  So if I understand correctly, this will:

1. Check to see if needed hostonlyif exists on VirtualBox start and create it if not
2. Add the machine to this created hostonlyif on start

?

**Comment by ehazlett** [comment]
@nathanleclaire precisely.  see https://github.com/docker/machine/pull/1292
