### ISSUE TITLE
Generic driver should use identities offered by ssh-agent when not specified

### ISSUE THREAD

**Issue by hairyhenderson** [docker/machine#1291]
When using the `generic` driver, you're forced to pass in an SSH key. IMO that should be optional, and in the absence of an explicit identity, the SSH client (external at least, if not native) should be able to look at identities registered to my ssh-agent.

This would allow the use of passphrase-protected SSH keys, perhaps avoiding problems such as https://github.com/docker/machine/issues/1229#issuecomment-106790757

I _think_ this is simply a case of making the flag optional in the generic driver and modifying the external SSH client support to skip the `ssh -i` flag if `--generic-ssh-key` wasn't set.

Thoughts? @ehazlett @nathanleclaire @sthulb

**Comment by sthulb** [comment]
-1, if you have too many keys in the agent, SSH fails to connect, iirc the client is only willing to send the first 5 or so, and if you server's key is 6th in the list, you won't connect.

**Comment by hairyhenderson** [comment]
@sthulb - I've never run into that, but don't think I've ever had more than 5 or 6 identities in my agent. Regardless, that's probably an `ssh-agent` bug and I don't see how it precludes the usefulness of this feature...

IMO, it's the only way to securely support SSH keys with passphrases.

**Comment by sthulb** [comment]
@hairyhenderson it's not the agent, it's somewhere between the client and server

**Comment by hairyhenderson** [comment]
@sthulb well, ok, but same point... IMO having more than a few identities in the agent isn't a super-common case. At most, it's something to warn users about in documentation...

**Comment by hairyhenderson** [comment]
...also, they'd have that problem regardless of whether they were using docker-machine :)

**Comment by sthulb** [comment]
Sure, but if we have 10 hosts in machine, we'll run into it :)

**Comment by hairyhenderson** [comment]
@sthulb - oh, I'm not suggesting putting every machine-created identity in the agent. I think by default we should behave as we do now. What I'm suggesting is simply not forcing an identity to be configured, and allowing `ssh` to look up keys in the agent.

**Comment by hairyhenderson** [comment]
Edited the title to hopefully make my intent a little more clear :)

**Comment by chantra** [comment]
+1 on using the agent.

Using a non passphrase protected ssh key is not best practice. In my use case (which I would assume is many people's case but I may be wrong), either .ssh/config is going to take care of setting the right key or I use a common key for the machine I own/have access to.

One could still override the agent by providing the key file name on the command line.

**Comment by mickours** [comment]
The use of the ssh-agent is also mandatory if your key to access the nodes is not present locally but only in the ssh-agent: It happen if you use your local key with the ``ForwardAgent yes`` option to access the device where docker-machine is running and then connect to the nodes.

**Comment by EnigmaCurry** [comment]
@sthulb @hairyhenderson regarding the ssh connection failure if you have too many keys in your agent (MaxAuthTries defaults to 6 in sshd_config) : as long as you specify the key file with 'ssh -i' it doesn't matter how many keys you have in your agent, it will try the one you specify first, and it will still pull the unlocked key from the agent. This doesn't work if you don't locally have the keyfile, but hopefully if you're using ForwardAgent you don't have that many keys in your agent anyway and I would also argue that's not the normal use case for this. 

+1 on this feature. It's real inconvenient to type in my password each time, and having a passwordless key is terribly insecure.

**Comment by prologic** [comment]
+1 for me too; I want to be able to create generic machines with passphrased protected ssh keys.

**Comment by bachi76** [comment]
+1 for what it's worth - need ssh-agent supported, can't use non-pw-protected keys.

**Comment by robbertkl** [comment]
+1 on this from me, another passphrased ssh key user.

**Comment by berghaus** [comment]
+1 from me also, for reasons stated above.
