### ISSUE TITLE
Password Support

### ISSUE THREAD

**Issue by UserTaken** [docker/machine#1294]
In addition to https://github.com/docker/machine/issues/1291, current `generic` driver provisioning requires no password SSH keyfile as well as nopasswd sudo which a big limitation. Machine is analogous to Ansible in that they both are able to create cloud instances and provision over SSH. So taking a page from Ansible, Machine should have the ability to SSH in using password in addition to a keyfile and sudo using a password (same as SSH password by default). Taking this further would be a playbook like file for defining multiple servers similar to [machinery](https://github.com/efrecon/machinery).

**Comment by hairyhenderson** [comment]
+1 on support for SSH keys with passphrases, but -1 on password login support.

**Comment by UserTaken** [comment]
@hairyhenderson If you're worried about security then the password input should be a prompt like Ansible has instead of an argument so there would be no history.

**Comment by hairyhenderson** [comment]
@UserTaken yeah ok, good point. In general I want to encourage better security, and IMO there shouldn't be any situation where you can't provision a host with an SSH key

**Comment by UserTaken** [comment]
@hairyhenderson What about my second point about not requiring nopasswd sudo?

**Comment by hairyhenderson** [comment]
@UserTaken well, most images on most providers that I've run into are configured by default to either log in as root directly, or with passwordless sudo. So this would be a rare case.

I just don't think supporting a sudo password is within the scope of what we want to do with docker-machine right now.

**Comment by UserTaken** [comment]
@hairyhenderson I'm specifically referring to the `generic` driver for provisioning servers not created by cloud providers.

**Comment by ehazlett** [comment]
As @hairyhenderson said, all of the current providers give passwordless sudo.  I'm not saying it's the best but it's the current de facto standard.  As for password sudo, right now that would be a terrible user experience.  We have dozens of SSH calls and most use sudo so a user would be entering a password several times.

As for a passphrase on the locally generated key, I'm +1 to supporting that.

We have no plans to support a playbook style format with multiple machines.

**Comment by nathanleclaire** [comment]
Yeah +1 to what @ehazlett said.  I'm going to close this issue and file a new one for password protected SSH keys.
