### ISSUE TITLE
Feature request - allow to pass in instance tags when creating machines

### ISSUE THREAD

**Issue by aperepel** [docker/machine#1297]
This is for GCE, but I see some basic code in AWS driver, too. We need to allow passing in instance tags for created machines. Internally, machine has a couple hard-coded ones it uses to set up basic firewall rules, but this needs to be opened up to allow more tags from a user.

Use case - I want to quickly open the swarm master machine port (3376), currently machine only sets up 2376 access. Ideally, this should be addressed via #948 , but I see how it will be useful beyond that. Having a tag makes firewall setup less brittle.

```
gcloud compute instances add-tags gce1 --tags docker-swarm-master --zone us-central1-f
gcloud compute firewall-rules create docker-swarm-master --allow tcp:3376 --target-tags docker-swarm-master
```

I noticed that machine terminates the instance in GCE when issued a `stop` command. On subsequent start the tag is lost, however. It is critical that machine saves these tags in instance metadata and re-applies them on `docker-machine start`, as cloud provider doesn't preserve them.

**Comment by ehazlett** [comment]
Thanks for the feedback!  I'm not sure what the issue with Swarm is.  We'll check that.  I'm not a GCE expert but I'll add tag support to the backlog.  Thanks!

**Comment by aperepel** [comment]
It's a generic theme across all drivers. When standing up clusters with `--swarm`, there is an additional `3376` port to be open for docker->swarm master communication. However, drivers don't do it today (1 or 2 tries to, but it's inconsistent.).

Here are some more examples on where tags come in very useful. Imagine that we're deploying many nodes, and use Swarm constraints (node, affinity, etc) heavily to lay down services into group of nodes. Being able to provide additional tags to those machines is critical, supporting next steps like firewall, internal load balancing, etc (can be done without using IP addresses by using logical tags only).

**Comment by ehazlett** [comment]
If there are several drivers that do not adjust firewalls, we should fix.  Please report those issues.

Only a few providers support tagging otherwise we would use them across the board.
