### ISSUE TITLE
Restart command doesn't re-export DOCKER_HOST, breaks Swarm

### ISSUE THREAD

**Issue by aperepel** [docker/machine#1298]
`docker-machine version 0.3.0-dev (fec8b4a)`

Testing with GCE. Restarting a machine in the cloud changes its IP address. `docker-machine restart xxx` command doesn't update the DOCKER_HOST env variable, causing swarm connections to break. Note in the session below how `docker-machine env` correctly lists the updated IP, while DOCKER_HOST is still pointing to the (now) non-existent IP from before the restart.

(I have a firewall rule to allow swarm-master traffic to a machine tagged `docker-swarm-master`, used to illustrate it's not a firewall issue).

```
09:39:40::docker-964 ♨ >  docker-machine ls
NAME           ACTIVE   DRIVER       STATE     URL                         SWARM
gce1                    google       Running   tcp://104.154.84.165:2376   gce1 (master)
gce7                    google       Running   tcp://130.211.126.35:2376   gce1
09:40:07::docker-964 ♨ >  docker-machine restart gce1
Deleting instance.
Waiting for instance to delete.
Creating instance.
Waiting for Instance...
Uploading SSH Key
Waiting for SSH Key
09:41:37::docker-964 ♨ >  docker-machine ls
NAME           ACTIVE   DRIVER       STATE     URL                         SWARM
gce1                    google       Running   tcp://104.154.82.233:2376   gce1 (master)
gce7                    google       Running   tcp://130.211.126.35:2376   gce1
09:42:55::docker-964 ♨ >  gcloud compute instances add-tags gce1 --tags docker-swarm-master --zone us-central1-f
Updated [https://www.googleapis.com/compute/v1/projects/docker-964/zones/us-central1-f/instances/gce1].
09:43:35::docker-964 ♨ >  docker info
FATA[0032] An error occurred trying to connect: Get https://104.154.84.165:3376/v1.18/info: dial tcp 104.154.84.165:3376: i/o timeout

###
### NOTE THE INCORRECT IP, IT NO LONGER EXISTS
###

09:44:12::docker-964 ♨ >  echo $DOCKER_HOST
tcp://104.154.84.165:3376

09:44:38::docker-964 ♨ >  docker-machine env --swarm gce1
export DOCKER_TLS_VERIFY="1"
export DOCKER_HOST="tcp://104.154.82.233:3376"
export DOCKER_CERT_PATH="xxx"
export DOCKER_MACHINE_NAME="gce1"
# Run this command to configure your shell:
# eval "$(docker-machine env gce1)"
09:45:58::docker-964 ♨ >  docker-machine -v
docker-machine version 0.3.0-dev (fec8b4a)

###
### And now let's prove it works if configured properly
###

09:48:45::docker-964 ♨ >  eval $(docker-machine env --swarm gce1)
09:54:22::docker-964 ♨ >  docker info
Containers: 1
Strategy: spread
Filters: affinity, health, constraint, port, dependency
Nodes: 1
 gce7: 130.211.126.35:2376
  └ Containers: 1
  └ Reserved CPUs: 0 / 2
  └ Reserved Memory: 0 B / 7.671 GiB
09:54:24::docker-964 ♨ >
```

P.S.: looks like there's a potential issue here with the number of machines too (it lists 1 node, gce7, but gce1 is omitted) - will keep an eye on it and file an issue once I understand what's going on.

**Comment by hairyhenderson** [comment]
@aperepel - the `docker-machine` binary can't (re-)export variables to your shell, so the only way to do this is to re-run `eval "$(docker-machine env --swarm gce1)"`.

Probably the fix for this is for the `restart` command to ask the user to re-run the `docker-machine env` command.

**Comment by aperepel** [comment]
I see, fixing the suggested `eval` command to run to account for swarm/no swarm scenarios is something to look out for.

Just throwing ideas out - can the binary invoke the `eval` as an external process?

**Comment by ehazlett** [comment]
+1 for @hairyhenderson suggestion.  we should add a note like we do for `create`

**Comment by ehazlett** [comment]
@aperepel I'm not a fan of altering the users environment automatically.  I think we should cue them to do so themselves.

**Comment by hairyhenderson** [comment]
@aperepel - a process can't affect its parent's (i.e. the shell's) environment, so it's impossible for docker-machine to set the appropriate variables itself.
