### ISSUE TITLE
Add homebrew formulas

### ISSUE THREAD

**Issue by jkp** [docker/machine#130]
I knocked up a quick [Formula](https://github.com/Homebrew/homebrew/pull/35272) to install machine already.  Perhaps you can link to that somewhere in your docs for people running OS X.

**Comment by DanLipsitt** [comment]
I took another crack at this in Homebrew/homebrew#35676. My version also installs the official binary (because v0.0.2 doesn't compile easily with homebrew), but it also has a --HEAD version that compiles from the latest git revision.

**Comment by ehazlett** [comment]
cool -- thanks.  we will get this in the docs

**Comment by ehazlett** [comment]
I think we want to figure out how we distribute machine.  Eventually we want to have them bundled but I'm not sure if we want to have a single binary from brew.

@bfirsh thoughts?

**Comment by dmp42** [comment]
FWIW: machine is now available in brew cask - it does depend on the cask boot2docker install, which messes things up.

**Comment by bfirsh** [comment]
I don't think Homebrew should be the recommended install path, but I don't think there's any harm having a brew available.

That said, it sucks it depends on boot2docker, so we should probably have that fixed.

**Comment by tchak** [comment]
There is a version in brew now (0.1.0) which have known issues. Would be nice if brew would be up to date.

@bfirsh why brew is not the recommended path? It is the "normal" way now days people install stuff on mac...

**Comment by ehazlett** [comment]
@tchak this is why -- we do not maintain that and don't have a way to update it.  we will have installers with update functionality in the future.  

perhaps @jkp could update the current formula when 0.2.0 is released?

**Comment by rsmitty** [comment]
I asked some questions around this in the IRC channel this evening. I agree that this makes sense for a sane way to install and keep docker-machine up to date. I'm trying to learn how to push updates into homebrew now so that we may be able to keep docker-machine up to date in there.

**Comment by tchak** [comment]
I just want you to think about the fact that homebrew is the default way most developers on mac install software... I would newer use an installer unless I have to and I think lots of developers out there are in the same set of mind.

> don't have a way to update it
How every other pice of software out there doing it? If it's the matter of not owning the formula in homebrew, would be nice if you could talk to the guy who owns it and sort it out :)

Just to be clear, I am aware that for now `docker-machine` and `docker-compose` are considered not stable, so not pushing you or something. I can understand if you have other concerns right now.
But I also feel that at some point both projects needs to be in homebrew and up to date.

@rsmitty thanks !

**Comment by ehazlett** [comment]
@tchak thanks!  we are working on how to get the "getting started with machine" experience happens.  for instance, it's not just a simple update the brew formula and go.  anyone on OS X will need a hypervisor so we also have to account for that.  Also, machine provides multiple hypervisor options so I also do not think it would be a good idea to forcibly install VirtualBox if the user is using Fusion, etc.  We want it to be solid all around.  I could see homebrew in the future we just want to make sure we get everything aligned before.

Thanks!

**Comment by tchak** [comment]
@ehazlett :+1:

**Comment by rsmitty** [comment]
FYI all - looks like this was already updated before I got back around to it. 

https://github.com/Homebrew/homebrew/pull/38851
https://github.com/Homebrew/homebrew/commit/d7c140a21c5ef0ae459d7e5dfaad82154e5b8bae

**Comment by ehazlett** [comment]
@rsmitty thanks!  :+1:

**Comment by ehazlett** [comment]
I'm going to close this.  We can add new issues for future updates.
