### ISSUE TITLE
Various DNS issues due to chained CNAMEs for registry

### ISSUE THREAD

**Issue by discordianfish** [docker/machine#1302]
Hi,

apparently there is some issue with Docker running in virtualbox at not being able to resolve the registry DNS name if it has chained CNAMEs. Similar to https://github.com/hashicorp/consul/issues/321

I saw following reports before reverting the changes:

```
`FATA[0003] Get https://registry-1.docker.io/v1/repositories/kunickiaj/elasticsearch-head/tags : dial tcp: lookup http://registry-1.docker.io on 10.0.2.3:53: too many redirects` as well
```

And:
```
FATA[0025] Get https://index.docker.io/v1/repositories/library/alpine/images : dial tcp: lookup http://index.docker.io on 192.168.1.1:53: read udp 192.168.1.1:53: i/o timeout
```

@nathanleclaire Can you make sure this is indeed fixed in master and somehow make sure people upgrade? We need to introduce the change back soon which will break everyone not upgraded.

**Comment by ehazlett** [comment]
We've already added fixes for this I believe.  https://github.com/docker/machine/pull/1075

If that doesn't fix the issue please re-open.  Thanks.

**Comment by discordianfish** [comment]
@ehazlett Is this released? If so, we will cutover again breaking all 0.2.0 clients effectively. If that doesn't work for you, propose an alternative.

**Comment by nathanleclaire** [comment]
It should be in the RC, but it is not in an official release yet.

**Comment by ehazlett** [comment]
@discordianfish correct -- this will be in 0.3 release.  My suggestion would be to hold off on any infrastructure changes until 0.3 if possible.  It is set for Jun.16.
