### ISSUE TITLE
Regression for VirtualBox driver - create hangs forever

### ISSUE THREAD

**Issue by aperepel** [docker/machine#1306]
docker-machine: `docker-machine version 0.3.0-dev (fec8b4a)`
VirtualBox: `Version 4.3.28 r100309 '4.3.28'`

Something is wrong with the VBox driver, I can no longer create local virtualbox machines:
```
09:29:26::~ ♨ >  docker-machine create --driver virtualbox dev1
Creating VirtualBox VM...
Creating SSH key...
Starting VirtualBox VM...
Starting VM...
^C10:01:14::~ ♨ >
```

In 30 minutes it didn't manage to do anything.

Nothing unusual in vbox log:
```
00:00:16.246310 Guest Log: vboxguest: misc device minor 56, IRQ 20, I/O port d020, MMIO at 00000000f0400000 (size 0x400000)
00:00:21.243943 NAT: link up
00:00:30.118921 NAT: DHCP offered IP address 10.0.2.15
00:00:30.119202 NAT: DHCP offered IP address 10.0.2.15
00:00:30.943524 NAT: IPv6 not supported
```

The machine is actually running, but not provisioned with ssh:

```
10:02:49::~ ♨ >  docker-machine ssh dev1
Bad port '0'
exit status 255
```

If I manually boot the vbox machine - everything looks good, and docker is running there, but docker-machine script didn't do the usual init.

This was working ok with `v0.2.0`. Note, also, provisioning to e.g. azure works well, it's the local virtualbox which got broken now.

**Comment by aperepel** [comment]
I've been debugging the create step and found the error I think:

```
STDERR:
executing: /usr/bin/VBoxManage modifyvm dev1 --natpf1 delete ssh
STDOUT:
STDERR: VBoxManage: error: Code NS_ERROR_INVALID_ARG (0x80070057) - Invalid argument value (extended info not available)
VBoxManage: error: Context: "RemoveRedirect(Bstr(ValueUnion.psz).raw())" at line 1717 of file VBoxManageModifyVM.cpp

executing: /usr/bin/VBoxManage modifyvm dev1 --natpf1 ssh,tcp,127.0.0.1,56337,,22
STDOUT:
STDERR:
executing: /usr/bin/VBoxManage startvm dev1 --type headless
STDOUT: Waiting for VM "dev1" to power on...
VM "dev1" has been successfully started.

STDERR:
Starting VM...
Getting to WaitForSSH function...
Testing TCP connection to: localhost:56337
Testing TCP connection to: localhost:56337
Testing TCP connection to: localhost:56337
```

It goes into a spin loop waiting for SSH forever from here, but note the error above.

**Comment by nathanleclaire** [comment]
Hm, generally I think that error there is not unexpected due to the way our little NAT-SSH-port forwarding dance works.  On VBox machine start we delete and re-create the SSH port forwarding rule in case the host has used the port in the interim.  I _do_ get a slightly different one (this was on a successful machine create):

```console
STDERR:
executing: /usr/bin/VBoxManage modifyvm foobar --natpf1 delete ssh
STDOUT:
STDERR: VBoxManage: error: This machine does not have any snapshots
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component SessionMachine, interface IMachine, callee nsISupports
VBoxManage: error: Context: "RemoveRedirect(Bstr(ValueUnion.psz).raw())" at line 1717 of file VBoxManageModifyVM.cpp
```

So, I'm not sure that is the issue.

**Comment by aperepel** [comment]
Hi @nathanleclaire , I did see that message too sometimes, but then it goes into a spin loop. Do you run the same VBox version?

**Comment by ehazlett** [comment]
@aperepel i've been troubleshooting this for a few days.  The bad port 0 is misleading.  It does get a port.  The problem appears to be that VirtualBox is not giving an IP to the second network interface (hostonly) thus causing machine to hang waiting and not persisting that port to the config.  I cannot personally get this re-created but have been able to troubleshoot other issues with the same behavior.  Some have reported success when removing all hostonly interfaces but it doesn't always work.

**Comment by adamjgray** [comment]
There's been quite a bit of discssion over at #1031 similar to this as well.

**Comment by aperepel** [comment]
I've found a solution, maybe it's worth a FAQ entry? Too many people run into it with boot2docker. The root cause was that somehow the `/etc/hosts` file got the `localhost` entry mangled. Review it and ensure there is a `127.0.0.1 localhost` entry present. Then

```
# note this will delete all docker data from this vm
boot2docker delete
boot2docker init
boot2docker up
```

**Comment by ehazlett** [comment]
@aperepel interesting -- thanks for the feedback -- i will take a look.

**Comment by aaronbwcollins** [comment]
It seems to get stuck at the Starting VM stage. Once using --debug we find that its waiting to make a connection with the machine via ssh. Our temporary workaround was to add ```unset SSH_AUTH_SOCK ```to our bashrc and retry ``` docker-machine create ```. We are using openssh via brew version OpenSSH_6.9p1. Once we unset the ssh variable the setup worked as expected. You can replicate this by using ssh -v elsewhere, If it hangs during the ``` debug1: SSH2_MSG_SERVICE_ACCEPT received ```then unsetting the **SSH_AUTH_SOCK** variable should do the trick.

**Comment by saxxi** [comment]
Unfortunately I have the same issue. Unsetting the `SSH_AUTH_SOCK` doesn't seem to help.

```
docker-machine --debug create --driver virtualbox default

STDERR:
executing: /usr/local/bin/VBoxManage modifyvm default --nic2 hostonly --nictype2 82540EM --hostonlyadapter2 vboxnet1 --cableconnected2 on
STDOUT:
STDERR:
executing: /usr/local/bin/VBoxManage modifyvm default --natpf1 delete ssh
STDOUT:
STDERR: VBoxManage: error: Code NS_ERROR_INVALID_ARG (0x80070057) - Invalid argument value (extended info not available)
VBoxManage: error: Context: "RemoveRedirect(Bstr(ValueUnion.psz).raw())" at line 1766 of file VBoxManageModifyVM.cpp

executing: /usr/local/bin/VBoxManage modifyvm default --natpf1 ssh,tcp,127.0.0.1,51847,,22
STDOUT:
STDERR:
executing: /usr/local/bin/VBoxManage startvm default --type headless
STDOUT: Waiting for VM "default" to power on...
VM "default" has been successfully started.

STDERR:
Error creating machine: exit status 1
```
Other infos:
```
# /etc/hosts
255.255.255.255	broadcasthost
::1             localhost
127.0.0.1 localhost
```
docker-machine: version 0.4.1 (e2c88d6) # I manually removed boot2docker
VirtualBox: 5.0.2 r102096
OS: Yosemite 10.10.5 on macbook pro
I reinstalled everything and restarted a couple of times

Thank you, apart from this small issue I love the project! :)

**Comment by petercoles** [comment]
Near identical setup to @saxxi (except Yosemite 10.10.4), identical problem.

Have tried sudoing "/usr/local/bin/VBoxManage modifyvm default --natpf1 delete ssh" from the command line (as that's where the error seems to sneak in) and get the following:

VBoxManage: error: Could not find a registered machine named 'default'
VBoxManage: error: Details: code VBOX_E_OBJECT_NOT_FOUND (0x80bb0001), component VirtualBoxWrap, interface IVirtualBox, callee nsISupports
VBoxManage: error: Context: "FindMachine(Bstr(a->argv[0]).raw(), machine.asOutParam())" at line 485 of file VBoxManageModifyVM.cpp

Have setting up a variety of differently-named VMS using "docker-machine --debug create --driver virtualbox <box-name>", but all fail to create in the same way leaving unlaunchable box in VirtualBox and manifest the same issue locating the registered machine if I execute manually what looks to me to be the stocking point in the docker box creation process.

**Comment by renaudguerin** [comment]
Exact same problem as @saxxi here, same versions except OS: 10.11 PB5

**Comment by mohamedattahri** [comment]
Same problem here. OSX 10.11.

**Comment by tomleese** [comment]
I get the same error message as @saxxi on OS X 10.11.

**Comment by petercoles** [comment]
This appears to be local to version 5.0.2 of VirtualBox and I was able to get past it by installing the current test build for 5.0.3 (available at https://www.virtualbox.org/wiki/Testbuilds). Not something I'd normally want to do, but it looks robust and I've not had any problems with it to date.

**Comment by lyndaoleary** [comment]
Same problem here with latest version of Docker Toolbox 1.8.1b and VirtualBox 5.0.2.

**Comment by tejksat** [comment]
I had the same problem with error messages as @saxxi posted. Docker Toolbox 1.8.1b and VirtualBox 5.0.2 on Windows 7.
Update to VirtualBox 5.0.3 testbuild fixed the problem! Thank you @petercoles!

**Comment by jeffcharles** [comment]
Using docker-machine version 0.4.1 (e2c88d6) and Virtualbox 5.0.3 I get:

```
Daemon not responding yet: dial tcp 192.168.99.101:2376: operation timed out
Daemon not responding yet: dial tcp 192.168.99.101:2376: operation timed out
Daemon not responding yet: dial tcp 192.168.99.101:2376: operation timed out
```

after running `ip addr show dev eth1` over ssh.

**Comment by jeffcharles** [comment]
Actually, disabling my vpn seems to have cleared up the issue

**Comment by ZGeomantic** [comment]
I had the same issue, and I had solve this by add one line in my /etc/hosts file:
127.0.0.1 localhost
I think the reason for the log like: Testing TCP connection to: localhost:56337 repeat is the machine can't parse the localhost to 127.0.0.1, just add this to /etc/hosts may fix it.

**Comment by bean5** [comment]
I was running into this. I removed all my VirtualBox vms, uninstalled VBox, then reinstalled VBox. Now docker works again. I don't have any of my built containers anymore, but that is easy to fix.

**Comment by petercoles** [comment]
@bean5, That's overkill. The problem was with VirtualBox 5.0.2, but the current version is 5.0.4, so merely upgrading should now be enough to fix this, without the need to trash your containers.

**Comment by bean5** [comment]
Yeah, perhaps. I was hitting some issues that may have been more
docker-specific than VBox specific. They seem to have cleared up. So maybe
I hit two birds with one stone. Thanks for the letting me know, though.

**Comment by aleksandr-vin** [comment]
> I removed all my VirtualBox vms, uninstalled VBox, then installed the latest VBox. Now docker works again.

Plus I've removed all the vm networks in VirtualBox > Preferences

**Comment by bean5** [comment]
I eventually got the same problem again within hours, but resolved it the same way. Seems like a non-robust way to fix. I should try removing VM networks. Thanks for the idea @aleksandr-vin.
