### ISSUE TITLE
Add shell completion for commands and flags

### ISSUE THREAD

**Issue by booyaa** [docker/machine#1308]
I noticed that codegangsta's cli package is being used to parse command line flags and arguments. This package has shell completion (bash/zsh) and can be enabled with a single line.

I think this would be a handy feature to enable given the number of options you can have to create, configure and manage a machine. 

[docker](https://github.com/docker/docker/tree/master/contrib/completion) and [compose](https://github.com/docker/compose/tree/master/contrib/completion) have completion scripts.

**Comment by jeanlaurent** [comment]
AFAIK this is done. Feel free to re-open if needed.
