### ISSUE TITLE
Option to specify Swarm version

### ISSUE THREAD

**Issue by chanwit** [docker/machine#1318]
We have a problem when to provision machines with a specific version of `swarm` as the current implementation fixes version to `swarm:latest`. This prevents us to test `docker-machine` with the development versions of `swarm`.

Could you please add `--swarm-version` or `--swarm-tag` to allow this?
To be the backward compatible, the default value of `--swarm-version` would be `latest`.

/cc @vieux @aluzzardi @abronan

**Comment by hairyhenderson** [comment]
@chanwit - you should be able to accomplish this with the `--swarm-image` flag that was recently added. Try out a master build (or 0.3.0-rc2 when it gets released soon).

**Comment by chanwit** [comment]
@hairyhenderson I see. Thank you for pointing out.
