### ISSUE TITLE
Re-provision host without needing a re-create

### ISSUE THREAD

**Issue by ehazlett** [docker/machine#1330]
It would be nice to "recover" from initial provisioning failures by re-running the provisioning step instead of needing to re-create the entire instance.

**Comment by nathanleclaire** [comment]
:+1:

**Comment by nathanleclaire** [comment]
`docker-machine provision` ?  It would also allow to bootstrap swarm based on the settings for that machine after a restart and so on.

**Comment by dgageot** [comment]
This was fixed with https://github.com/docker/machine/pull/2121
