### ISSUE TITLE
Provisioning stability

### ISSUE THREAD

**Issue by ehazlett** [docker/machine#1331]
The creation process varies greatly from provider to provider. Issues like network partitions, provider API hiccups, etc can cause issues. Currently, Machine does not handle those very well. Errors are not always reported well and the user must remove whatever has been created and start over. This affects users using Machine directly as well as indirectly (i.e. Kitematic, Rancher, Machinery). We should improve the provision process to handle various types of failure and better report them when they occur.

Related:

- [x] https://github.com/docker/machine/issues/1266
- [x] https://github.com/docker/machine/issues/721
- [x] https://github.com/docker/machine/issues/1028
- [x] https://github.com/docker/machine/issues/950
- [x] https://github.com/docker/machine/issues/1031
- [ ] https://github.com/docker/machine/issues/1330
- [x] https://github.com/docker/machine/issues/1319

**Comment by dgageot** [comment]
Closing. Since only #1330 is still opened
