### ISSUE TITLE
Local Provider Improvements

### ISSUE THREAD

**Issue by ehazlett** [docker/machine#1332]
In 0.3.0 we added several improvements for the VirtualBox provider however, the user experience is still a bit lacking for the other "local" providers. Machine 0.3.0 also added support for VMware shared directories however not all features for local drivers match. For example, VirtualBox on Linux does not map shared directories. Hyper-V does not have shared directories at all. We should work to get the local drivers as stable and feature complete as possible.

Related:

- [x] https://github.com/docker/machine/issues/820
- [x] https://github.com/docker/machine/issues/1275
- [x] https://github.com/docker/machine/issues/1285
- [x] https://github.com/docker/machine/issues/1219
- [x] https://github.com/docker/machine/issues/1193
- [x] https://github.com/docker/machine/issues/639
- [x] https://github.com/docker/machine/issues/512
- [x] https://github.com/docker/machine/issues/1433

**Comment by dgageot** [comment]
All related tickets are closed
