### ISSUE TITLE
[v0.3.0-rc2] VMware Fusion shared folders do not work

### ISSUE THREAD

**Issue by chouclee** [docker/machine#1344]
I created the machine with standard iso. 
i.e. $ docker-machine create --driver vmwarefusion dev

Inside boot2docker, I could see the shared directories. But all contents inside the directories are empty.

I'm using VMware Fusion Pro v7.1.1

BTW, is it normal that I could't see my machine in Virtual Machine Library?

Edit: I re-created the machine, now the shared folders are gone. If I run a new container which uses -v flag, the shared folders would appear without all contents.

**Comment by nathanleclaire** [comment]
@chouclee Are you using the most recent release candidate?

**Comment by chouclee** [comment]
@nathanleclaire  I built the v0.3.0-rc source code my self. Probably I should use the binary package directly?

**Comment by nathanleclaire** [comment]
Are you seeing issues like : https://github.com/docker/machine/issues/1275 ?

**Comment by chouclee** [comment]
@nathanleclaire  Mine is more weird. I couldn't see any content even for read only. And I tested the issue #1275, I have the same result.

**Comment by nathanleclaire** [comment]
cc @frapposelli for input.  @chouclee, please stay tuned and I will hopefully be able to provide you with a command with a new ISO to try.

**Comment by frapposelli** [comment]
Here you go: https://github.com/frapposelli/boot2docker/releases/tag/lk4

https://github.com/frapposelli/boot2docker/releases/download/lk4/boot2docker-lk4-vmhgfs-fix.iso

**Comment by chouclee** [comment]
@frapposelli @nathanleclaire  I just tried it. The issues are gone. It works perfect!

**Comment by chouclee** [comment]
@frapposelli  BTW,  is it normal that I couldn't see this machine in Fusion's Virtual Machine Library?

**Comment by frapposelli** [comment]
@chouclee yes, that's the expected behavior.

**Comment by nathanleclaire** [comment]
The fix is merged into b2d so I'm closing --- thanks @chouclee for reporting and thanks a _lot_ @frapposelli for the fix!
