### ISSUE TITLE
No IP address found on machine start

### ISSUE THREAD

**Issue by nathanleclaire** [docker/machine#1346]
When running `docker-machine start`, with a high enough probability to be considered worrisome, I see this:

```console
$ dm stop dev; dm start dev
Starting VM...
No IP address found 4: eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 08:00:27:38:96:36 brd ff:ff:ff:ff:ff:ff
    inet6 fe80::a00:27ff:fe38:9636/64 scope link
       valid_lft forever preferred_lft forever
```

Everything seems to work after that, so the error message is slightly misleading (I suspect a race or, surprise, funny business in the network setup) -- BUT, it's still important to fix this, especially as it's affecting downstream -- see https://github.com/kitematic/kitematic/issues/615

IMO this _must_ be fixed by the release, so help debugging or reproducing is appreciated.

cc @ehazlett @jeffdm @mchiang @elesant

**Comment by ehazlett** [comment]
Perhaps it's a race in bringing up the second interface (hostonly).  We currently only wait for SSH which is on the NAT with a port forward (https://github.com/docker/machine/blob/master/drivers/virtualbox/virtualbox.go#L400).  I wonder if it's attempting to `GetIP` before the hostonly is ready?

**Comment by ehazlett** [comment]
This appears to be from the legacy configs in VirtualBox and doesn't appear to be happening with new machines.  I think we need a config migration.

**Comment by ehazlett** [comment]
Closing as #1349 was merged
