### ISSUE TITLE
VirtualBox Cannot create machine

### ISSUE THREAD

**Issue by chouclee** [docker/machine#1354]
Using cmd: "docker-machine -D create -d virtualbox dev"

error:
...
SSH cmd err, output: exit status 255: 
Error getting ssh command 'exit 0' : exit status 255
...
SSH returned: 4: eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP qlen 1000
    link/ether 08:00:27:e2:f5:bf brd ff:ff:ff:ff:ff:ff
    inet 192.168.99.103/24 brd 192.168.99.255 scope global eth1
       valid_lft forever preferred_lft forever
    inet6 fe80::a00:27ff:fee2:f5bf/64 scope link 
       valid_lft forever preferred_lft forever

END SSH

Daemon not responding yet: dial tcp 192.168.99.103:2376: operation timed out

**Comment by nathanleclaire** [comment]
So what exactly is the issue you are seeing?

**Comment by chouclee** [comment]
It never finish creating.

**Comment by chouclee** [comment]
My mac is totally a mess now... Too much problems...
I could crete a machine using vmware fusion driver. But I encountered error message like " Failured to generate cert: crypto/tls: private key does not match public key"
So I cannot use private registry anymore.

**Comment by duynguyenvan** [comment]
Same issue here. Any solution for this please?

**Comment by dgageot** [comment]
Hi @chouclee, can you try with docker-machine 0.5.0rc4 and tell us is the problem is fixed. Otherwise can you gist the output of this command `docker-machine -D create -d virtualbox dev`.

**Comment by cteyton** [comment]
Hi there, 
With docker-toolbox-1.9.0-rc3 / windows 8.1, i got a similar issue when running : 
```
docker-machine -D create --driver virtualbox dev
```

```
 STDERR:
(dev) DBG | {
(dev) DBG | }
(dev) DBG | Using SSH client type: external
(dev) DBG | About to run SSH command:
(dev) DBG | ip addr show dev eth1
(dev) DBG | SSH cmd err, output: <nil>: 4: eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
(dev) DBG |     link/ether 08:00:27:87:60:c4 brd ff:ff:ff:ff:ff:ff
(dev) DBG |     inet6 fe80::a00:27ff:fe87:60c4/64 scope link
(dev) DBG |        valid_lft forever preferred_lft forever
(dev) DBG |
(dev) DBG | SSH returned: 4: eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
(dev) DBG |     link/ether 08:00:27:87:60:c4 brd ff:ff:ff:ff:ff:ff
(dev) DBG |     inet6 fe80::a00:27ff:fe87:60c4/64 scope link
(dev) DBG |        valid_lft forever preferred_lft forever
(dev) DBG |
(dev) DBG | END SSH
(dev) DBG |
(dev) DBG | ERROR getting IP: No IP address found 4: eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
(dev) DBG |     link/ether 08:00:27:87:60:c4 brd ff:ff:ff:ff:ff:ff
(dev) DBG |     inet6 fe80::a00:27ff:fe87:60c4/64 scope link
(dev) DBG |        valid_lft forever preferred_lft forever
```

I then got this 
```
$ eval "$(docker-machine env dev)"
Error running connection boilerplate: Error getting driver URL: Something went wrong running an SSH command!
command : ip addr show dev eth1
err     : exit status 255
output  :
```

I also tried a suggestion found in similar threads, i.e. :
 ```
$ eval "$(docker-machine --native-ssh env dev)"
 ```
and got the same issue. 
Hope this can help !

**Comment by nathanleclaire** [comment]
@chouclee Please try the latest and open a new issue with more information if the problem persists.
