### ISSUE TITLE
'generic' driver should document that it changes the Os name, force yum update, etc

### ISSUE THREAD

**Issue by djsly** [docker/machine#1362]
version: Docker Machine 0.3.0rc2

When trying the 'generic' driver on a machine running centOS 7 with docker already installed using EPEL, and with the configured FS to be BTRFS.

docker-machine, changed my original hostname, forced a yum update (we are controlling the rpm version we wan't to use in production) and tried to installed a version of Docker that doesn't match our need. 

I was first looking at using the 'none' driver to add existing machines to my clusters of machines, but after ready some more on the subject, people were referring the 'generic' driver as being THE driver to use instead of 'none'

Still insterested in adding a machine with docker already installed to it, to an existing list of machines managed by docker-machine.

**Comment by nathanleclaire** [comment]
I agree that the behavior should be described better in the documentation.  I think the `url` driver is more akin to what you have in mind, but it requires you to setup and manage certs for yourself, and is a little hard to use IMO.

**Comment by djsly** [comment]
Correct. This is what brought me here. After trying the URL method. 

Sent from Outlook on iPhone 

    _____________________________

**Comment by mickours** [comment]
I have the same use case, with an already installed docker on cluster that just need configuration and not install. Maybe the generic plugin should just make some checks before trying to update and install anything, don't you think?

Or just add an option for this like ``--only-configure``.

What do you think?

**Comment by metasim** [comment]
@mickours +1 on this idea. 

I've just upgraded to 0.5.0, and the `--driver=none` no longer works for me (running `env` gives me a `Error running connection boilerplate: [host] is not running` error). 

I like the simplicity of the `--driver=generic` approach, where it handles the credentials headache, but leaves the installation and configuration of docker daemon to me.

**Comment by dgageot** [comment]
See https://github.com/docker/machine/pull/3085

**Comment by dgageot** [comment]
Documentation added with https://github.com/docker/machine/pull/3085
