### ISSUE TITLE
Setting active machine broken in 0.3.0-rc3

### ISSUE THREAD

**Issue by ilkka** [docker/machine#1367]
Docker-machine doesn't accept any arguments for the "active" command:

```console
$ docker-machine create -d virtualbox --virtualbox-cpu-count 2 virtualbox
Creating CA: /Users/ilau/.docker/machine/certs/ca.pem
Creating client certificate: /Users/ilau/.docker/machine/certs/cert.pem
Image cache does not exist, creating it at /Users/ilau/.docker/machine/cache...
No default boot2docker iso found locally, downloading the latest release...
Downloading https://github.com/boot2docker/boot2docker/releases/download/v1.6.2/boot2docker.iso to /Users/ilau/.docker/machine/cache/boot2docker.iso...
Creating VirtualBox VM...
Creating SSH key...
Starting VirtualBox VM...
Starting VM...
To see how to connect Docker to this machine, run: docker-machine env virtualbox
$ docker-machine create -d virtualbox vbox2
Creating VirtualBox VM...
Creating SSH key...
Starting VirtualBox VM...
Starting VM...
To see how to connect Docker to this machine, run: docker-machine env vbox2
$ docker-machine ls
NAME         ACTIVE   DRIVER       STATE     URL                         SWARM
vbox2                 virtualbox   Running   tcp://192.168.99.101:2376
virtualbox   *        virtualbox   Running   tcp://192.168.99.100:2376
$ docker-machine active vbox2
Error: Too many arguments given.
$ docker-machine --version
docker-machine version 0.3.0-rc3 (a5fd8cf)
```

**Comment by ilkka** [comment]
Oh okay, reading e.g. #616, #443 and #777 it seems like the whole active machine concept might be going away. A further clue is that commands like "ip" no longer seem to use the active machine by default.

The reason this would've been nice for me is that I had a bit of automation that got the IP of the active docker host by just running

```sh
IP=$(docker-machine ip)
```

and that would work no matter what the active machine happened to be, and also work with minimal fuss with boot2docker by just changing "docker-machine" to "boot2docker". I guess I can do

```sh
IP=$(docker-machine ip $(docker-machine active))
```

but it does seem a bit complex...

**Comment by ehazlett** [comment]
@ilkka yes this behavior has changed (see https://github.com/docker/machine/blob/master/docs/machine-overview.md#active).  I see your point.  I was wondering if we could add a `active` key to the ls `filter` but I don't think that would get you any better than your last workaround.

**Comment by nathanleclaire** [comment]
Hey @ilkka, sorry to hear that you ran into some trouble around this.  Perhaps we could communicate it better in the release notes.

**Comment by mojodna** [comment]
@nathanleclaire the included help should also be updated (it's currently misleading given `[arg...]`), assuming that `active` isn't going away completely:

```bash
$ docker-machine help active
Usage: docker-machine active [arg...]

Print which machine is active
```

**Comment by nathanleclaire** [comment]
Good point @mojodna -- I think it's added automatically by codegangsta/cli but we'll see what we can do.

**Comment by anentropic** [comment]
how does a machine get set "active"?

```
$ docker-machine create --driver virtualbox default
...
$ docker-machine ls
NAME      ACTIVE   DRIVER       STATE     URL                         SWARM
default            virtualbox   Running   tcp://192.168.56.101:2376
$ docker-machine active
Error getting active host: Active host not found
```

is this something I do by manually exporting `DOCKER_HOST` ?

in that case I can't really see any use for it

**Comment by anentropic** [comment]
I'd love to be able to set a particular machine as the 'default' to avoid having to type the machine name on every command

I realise docker-machine has more powers and uses, but most of the time I'm using it locally as a replacement for boot2docker and will only have a single machine

**Comment by anentropic** [comment]
ok, for the first part you have to do the `eval "$(docker-machine env default)"`

**Comment by jedwards1211** [comment]
@ehazlett that link is now broken, I'm a bit confused about how to start any docker containers on my mac now?

**Comment by jedwards1211** [comment]
Ah, okay, the documentation isn't very clear for me as a first-time user.  It says:

> Connect your shell to the new machine.
> `$ eval "$(docker-machine env default)"`

I had no idea that "Connect your shell to the new machine" means "mark the machine as active".

Also, `docker-machine start default` output this:
> Started machines may have new IP addresses. You may need to re-run the `docker-machine env` command.

It would have saved me some confusion if it had just said "You may need to run `eval "$(docker-machine env default)"` to mark this machine active"

**Comment by nathanleclaire** [comment]
> Is there any reason starting the only machine shouldn't set it active automatically?

It's not possible to "set a machine as active" without having the user set environment variables today (a child process, e.g. `docker-machine`, cannot modify the environment of its parent process, e.g. `bash`).

Configuring a local Docker client to talk to a remote Docker daemon requires setting `DOCKER_HOST` and other environment variables.

**Comment by jedwards1211** [comment]
Okay, that makes sense.
