### ISSUE TITLE
Azure: update Go lib to current

### ISSUE THREAD

**Issue by ehazlett** [docker/machine#1368]
The Azure Go lib is quite a bit behind.  When trying to update it appears to have changed drastically.  We should get this up to date.

**Comment by ehazlett** [comment]
I started on it and found that things like `CreateAzureVMConfiguration` and `ImportPublishSettingsFile` no longer exist.  Looks like the driver will need significant refactoring.

**Comment by ahmetalpbalkan** [comment]
Yep it will require a big refactoring, leave this task to me :-) I guess there's no hurry?

**Comment by ehazlett** [comment]
@ahmetalpbalkan i wasn't meaning to assign you :)  No rush.

**Comment by ahmetalpbalkan** [comment]
Yeah the version you got is stable enough, we pretty much rewrote everything in the meanwhile.

I recently re-vendored the SDK into docker/distribution, I will do for machine as well when I can find time. We still have no versioning yet as things are really moving fast, too.

**Comment by kikov79** [comment]
When doing the refactor, I think it could be great supporting the Azure cloud service name to be able to construct clusters within the same service in different machines. At the moment, each vm go to a different cloud service (so escalation it's not possible).

**Comment by ahmetalpbalkan** [comment]
@kikov79 that probably would require using our new upcoming REST API set called ARM (azure resource manager) and ARM templates. Currently the REST API used (service management api) does not allow parallel-deployments within the same affinity group / virtual network.

In the long run, we'll be switching to the new API set and making it possible (I imagine at some point we'd  allow creating swarm clusters using docker-machine and the creation will be all parallelized and atomic within a “resource group” –a new concept introduced in ARM model).

**Comment by prbond** [comment]
In drivers/azure/azure.go the library :
azure "github.com/MSOpenTech/azure-sdk-for-go"
"github.com/MSOpenTech/azure-sdk-for-go/clients/vmClient"

didn't exist it is remplaced by :
"github.com/Azure/azure-sdk-for-go/management"

**Comment by ahmetalpbalkan** [comment]
This will happen in the new Azure driver :bomb: !
