### ISSUE TITLE
Do we need to support multiple ssh commands within one ssh connection?

### ISSUE THREAD

**Issue by chouclee** [docker/machine#1372]
Currently I can execute multiple ssh commands by repeatedly calling `docker-machine ssh name 'command'`.

I think it is very easy to let client support commands like `docker-machine ssh name 'cmd1' 'cmd2'...`
or even `docker-machine ssh name 'script'`

**Comment by nathanleclaire** [comment]
> docker-machine ssh name 'cmd1' 'cmd2'...

This would break our current ability to do things like `docker-machine ssh dev -- sh -c 'echo foo'` which I'm a big fan of.  I'm -1 on this, but I do wonder what the best approach is since I've seen a lot of "machine ssh sleds" in scripts.

**Comment by chouclee** [comment]
well, if it's well handled,  `docker-machine ssh dev -- "sh -c 'echo foo'" "sh -c 'echo bar'"` or `docker-machine ssh dev -- "sh -c 'echo foo'; sh -c 'echo bar'"` could be a proper way.

**Comment by nathanleclaire** [comment]
@chouclee Why not do it like so:

```console
$ docker-machine ssh dev '
echo foo;
echo bar;
echo baz;'
foo
bar
baz
```

This will work out of the box today.

**Comment by chouclee** [comment]
@nathanleclaire  Oh, I didn't realize we already could do that.
