### ISSUE TITLE
Different Default SSH Users among providers (VirtualBox and Digital Ocean)

### ISSUE THREAD

**Issue by nireak** [docker/machine#1386]
I have noticed that the default SSH User (and I don't know how to change it) is "docker" at VirtualBox and "root" at Digital Ocean. I think that could be a problem IMHO if your use, for instance, VBOX for developing and DO for staging/production and you want to be sure that both environments and the scripts used to configure them are exactly the same.

Is there an easy way to configure DockerMachine for these environments, like using "--Virtualbox-ssh-username" ?

Thank you

**Comment by nathanleclaire** [comment]
@nireak If the provider supports it, there's a `*-ssh-user` flag:

```console
$ dm create | grep ssh-user
   --amazonec2-ssh-user "ubuntu"											set the name of the ssh user [$AWS_SSH_USER]
   --generic-ssh-user "root"												SSH user
   --openstack-ssh-user "root"												OpenStack SSH user
   --rackspace-ssh-user "root"												SSH user for the newly booted machine. Set to root by default
```

Perhaps we should allow a `--virtualbox-ssh-user` flag, or simply a generic flag that works for all providers.

**Comment by nireak** [comment]
@nathanleclaire thank you for your answer. 

I think the best option would be a generic flag that works for all providers. The default ssh-user should be the same (root, perhaps) for all providers. If not, portability would be problematic.
