### ISSUE TITLE
Virtualbox 5.0.0.RC1 - parameter SynthCPU no longer supported

### ISSUE THREAD

**Issue by hendrikstier** [docker/machine#1387]
Running

> $ docker-machine create --driver virtualbox dev -D

leads to failure in VM creation/modification using VBoxManage:

> VBoxManage: error: Unknown option: --synthcpu

I tried my best to figure out where the command options are set. I found https://github.com/docker/machine/blob/master/drivers/virtualbox/virtualbox.go#L273 and removed the line after forking the repository. Afterwards I installed using a modified homebrew formula pointing to the forked github repository. Still the option is set and the command failed.

Where should I continue my hunt for the option-setting?

**Comment by hendrikstier** [comment]
I did some changes in my form. Are those helpful to you?


1. Removal of synthcpu-flag: https://github.com/hendrikstier/machine/commit/436497fde460c9d042ee72ee446f7031d067646c
2. Explicit logrus dependency in godeps: https://github.com/hendrikstier/machine/commit/36c28569928b6726ca53d4fd7054ddb76d845dc2

**Comment by methane** [comment]
VirtualBox 5.0 is released.

**Comment by c3c** [comment]
Also experiencing this problem with the latest docker release.

**Comment by nathanleclaire** [comment]
Hey all, I've submitted a fix here: https://github.com/docker/machine/pull/1496 Sorry for any inconvenience in the meantime.
