### ISSUE TITLE
Allow specifying DigitalOcean existing SSH Key ID

### ISSUE THREAD

**Issue by jpadilla** [docker/machine#1390]
It'd be great If if we could skip createSSHKey and instead pass via a flag the ID of an existing SSH Key already in DigitalOcean.

**Comment by bhurlow** [comment]
is this a dup of: https://github.com/docker/machine/pull/1438 ?

**Comment by bhurlow** [comment]
also: https://github.com/docker/machine/issues/1445 and https://github.com/rancher/rancher/issues/1352

**Comment by STRML** [comment]
This can be closed, merged in https://github.com/docker/machine/pull/3144.
