### ISSUE TITLE
Unable to connect docker from inside guest, or UNIX socket

### ISSUE THREAD

**Issue by jmmills** [docker/machine#1392]
I've been trying to troubleshoot why my logspout container wasn't able to connect to docker via UNIX socket and found this behavior. It seems that I can't use the docker client from inside the provided boot2docker guest, nor can I share the unix socket from a volume mount. Either expected behavior has changed, and I'm unaware, or something is amiss. 

If this is actually an an issue with something boot2docker is doing, close this out and I will take this issue to them.

    $ uname -a
    Darwin charlie.local 14.3.0 Darwin Kernel Version 14.3.0: Mon Mar 23 11:59:05 PDT 2015; root:xnu-2782.20.48~5/RELEASE_X86_64 x86_64 i386 MacBookPro11,3 Darwin
    $ machine --version
    machine version 0.1.0
    $ docker --version
    Docker version 1.7.0, build 0baf609
    $ machine create -d virtualbox test
    INFO[0000] Creating SSH key...
    INFO[0000] Creating VirtualBox VM...
    INFO[0006] Starting VirtualBox VM...
    INFO[0006] Waiting for VM to start...
    INFO[0038] "test" has been created and is now the active machine.
    INFO[0038] To point your Docker client at it, run this in your shell: $(machine env test)
    $ $(machine env test)
    $ machine ssh
                            ##         .
                      ## ## ##        ==
                   ## ## ## ## ##    ===
               /"""""""""""""""""\___/ ===
          ~~~ {~~ ~~~~ ~~~ ~~~~ ~~~ ~ /  ===- ~~~
               \______ o           __/
                 \    \         __/
                  \____\_______/
     _                 _   ____     _            _
    | |__   ___   ___ | |_|___ \ __| | ___   ___| | _____ _ __
    | '_ \ / _ \ / _ \| __| __) / _` |/ _ \ / __| |/ / _ \ '__|
    | |_) | (_) | (_) | |_ / __/ (_| | (_) | (__|   <  __/ |
    |_.__/ \___/ \___/ \__|_____\__,_|\___/ \___|_|\_\___|_|
    Boot2Docker version 1.7.0, build master : 7960f90 - Thu Jun 18 18:31:45 UTC 2015
    Docker version 1.7.0, build 0baf609
    docker@test:~$ docker images
    Cannot connect to the Docker daemon. Is 'docker -d' running on this host?
    docker@test:~$ docker -H unix:///var/run/docker.sock images
    Cannot connect to the Docker daemon. Is 'docker -d' running on this host?
    docker@test:~$ exit
    FATA[0031] exit status 1
    $ docker run -it --rm -v /var/run/docker.sock:/tmp/docker.sock ubuntu /bin/bash -l
    Unable to find image 'ubuntu:latest' locally
    latest: Pulling from ubuntu
    ####
    Status: Downloaded newer image for ubuntu:latest
    root@778fcd441e32:/# ls -l /tmp/docker.sock
    srw-rw---- 1 root users 0 Jun 19 22:51 /tmp/docker.sock
    root@778fcd441e32:/# apt-get update
    ####
    Fetched 20.9 MB in 11s (1840 kB/s)
    Reading package lists... Done
    root@778fcd441e32:/# apt-get install -y socat
    ####
    root@778fcd441e32:/# socat UNIX:/tmp/docker.sock STDOUT
    2015/06/19 22:53:52 socat[99] E connect(3, AF=1 "/tmp/docker.sock", 18): Connection refused
    root@778fcd441e32:/# logout
    $

**Comment by nathanleclaire** [comment]
It looks like the daemon is not up.  If the daemon is not up, normal Docker commands will not work and naturally mounting the socket will not work either as nobody's listening on it.

What is the output of `tail /var/log/docker.log` in the VM?  It might give you a clue why the daemon did not come up.

Also, that version of Machine is really old, so please try `rm -rf ~/.docker` and creating a new VM with the latest (0.3.0) to see if that fixes the issue.

**Comment by jmmills** [comment]
If the daemon wasn't up then I wouldn't have been able to do a docker run from outside the guest. I will attempt this with the updated docker-machine to see if that makes a difference.

**Comment by nathanleclaire** [comment]
> If the daemon wasn't up then I wouldn't have been able to do a docker run from outside the guest. I will attempt this with the updated docker-machine to see if that makes a difference.

OK, you hadn't mentioned that in your bug report -- please make 100% certain that you are actually hitting the created / faulty machine e.g. by running the command using `docker $(docker-machine config dev) ps`, and let us know how the create with a new version goes.

**Comment by jmmills** [comment]
Just tried it with machine v0.3.0 and it seems to be working, it's on a different machine so it would lead me to believe that if it's still an issue it's something to do with my environment.
