### ISSUE TITLE
docker-machine create no longer works on 3.0?

### ISSUE THREAD

**Issue by riddopic** [docker/machine#1393]
Hello,

I have been using docker-machine for months without any trouble but most today when I updated to 3.0 I have not been able to get my machine going again. I am on OS X Yosemite, I downloaded docker-machine and docker today and removed my old .docker directory. When I try and create a machine using the VMware driver it just hangs indefinitely.

Running in debug mode I see the following:

```
$ docker-machine -v
docker-machine version 0.3.0 (0a251fe)
$ docker -v
Docker version 1.7.0, build 0baf609

$ docker-machine -D create -d vmwarefusion dev
Creating CA: /Users/sharding/.docker/machine/certs/ca.pem
Creating client certificate: /Users/sharding/.docker/machine/certs/cert.pem
Image cache does not exist, creating it at /Users/sharding/.docker/machine/cache...
No default boot2docker iso found locally, downloading the latest release...
Downloading https://github.com/boot2docker/boot2docker/releases/download/v1.7.0/boot2docker.iso to /Users/sharding/.docker/machine/cache/boot2docker.iso...
Creating SSH key...
Creating VM...
VixDiskLib: Invalid configuration file parameter. Failed to read configuration file.
Creating disk '/Users/sharding/.docker/machine/machines/dev/dev.vmdk'
Virtual disk creation successful.
Starting dev...
executing: /Applications/VMware Fusion.app/Contents/Library/vmrun start /Users/sharding/.docker/machine/machines/dev/dev.vmx nogui
Waiting for VM to come online...
MAC address in VMX: 00:0c:29:62:6a:2f
IP found in DHCP lease table: 172.16.91.128
Got an ip: 172.16.91.128
Creating Tar key bundle...
executing: /Applications/VMware Fusion.app/Contents/Library/vmrun -gu docker -gp tcuser directoryExistsInGuest /Users/sharding/.docker/machine/machines/dev/dev.vmx /var/lib/boot2docker
executing: /Applications/VMware Fusion.app/Contents/Library/vmrun -gu docker -gp tcuser CopyFileFromHostToGuest /Users/sharding/.docker/machine/machines/dev/dev.vmx /Users/sharding/.docker/machine/machines/dev/userdata.tar /home/docker/userdata.tar
executing: /Applications/VMware Fusion.app/Contents/Library/vmrun -gu docker -gp tcuser runScriptInGuest /Users/sharding/.docker/machine/machines/dev/dev.vmx /bin/sh sudo /bin/mv /home/docker/userdata.tar /var/lib/boot2docker/userdata.tar && sudo tar xf /var/lib/boot2docker/userdata.tar -C /home/docker/ > /var/log/userdata.log 2>&1 && sudo chown -R docker:staff /home/docker
executing: /Applications/VMware Fusion.app/Contents/Library/vmrun -gu docker -gp tcuser enableSharedFolders /Users/sharding/.docker/machine/machines/dev/dev.vmx
executing: /Applications/VMware Fusion.app/Contents/Library/vmrun -gu docker -gp tcuser addSharedFolder /Users/sharding/.docker/machine/machines/dev/dev.vmx Users /Users
executing: /Applications/VMware Fusion.app/Contents/Library/vmrun -gu docker -gp tcuser runScriptInGuest /Users/sharding/.docker/machine/machines/dev/dev.vmx /bin/sh sudo mkdir /Users && sudo mount -t vmhgfs .host:/Users /Users
executing: /Applications/VMware Fusion.app/Contents/Library/vmrun list
Getting to WaitForSSH function...
executing: /Applications/VMware Fusion.app/Contents/Library/vmrun list
MAC address in VMX: 00:0c:29:62:6a:2f
IP found in DHCP lease table: 172.16.91.128
Testing TCP connection to: 172.16.91.128:22
executing: /Applications/VMware Fusion.app/Contents/Library/vmrun list
MAC address in VMX: 00:0c:29:62:6a:2f
IP found in DHCP lease table: 172.16.91.128
Using SSH client type: external
About to run SSH command:
exit 0
&{/usr/bin/ssh [/usr/bin/ssh -o PasswordAuthentication=no -o IdentitiesOnly=yes -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=quiet -o ConnectionAttempts=3 -o ConnectTimeout=10 -i /Users/sharding/.docker/machine/machines/dev/id_rsa -p 22 docker@172.16.91.128 exit 0] []  <nil> <nil> <nil> [] <nil> <nil> <nil> ?reflect.Value? false [] [] [] [] <nil>}
```

In another window I am able to see the machine is up with an IP and I can even connect to it via docker-ssh:

```
docker-machine ls
NAME   ACTIVE   DRIVER         STATE     URL                        SWARM
dev    *        vmwarefusion   Running   tcp://172.16.91.128:2376
```

When I try to load my shell with the `docker-machine env` I get the error:

```
$ docker-machine env dev
open /Users/sharding/.docker/machine/machines/dev/ca.pem: no such file or directory
```

I do not see any certs in ```~/.docker/machine/machines/dev/``` and only see the following certs in my `.docker/machine/certs/` dir:

```
ls -al .docker/machine/machines/dev/
total 2258544
drwx------  4 sharding  staff   544B Jun 19 18:25 .
drwx------  3 sharding  staff   102B Jun 19 18:24 ..
-rw-------  1 sharding  staff   1.0G Jun 19 18:25 564d3b9c-854a-bd52-6ad5-811580626a2f.vmem
drwxrwxrwx  2 sharding  staff   102B Jun 19 18:25 564d3b9c-854a-bd52-6ad5-811580626a2f.vmem.lck
-rw-------  1 sharding  staff    26M Jun 19 18:25 boot2docker.iso
-rw-------  1 sharding  staff   1.7K Jun 19 18:25 config.json
-rw-------  1 sharding  staff    25M Jun 19 18:35 dev.vmdk
drwxrwxrwx  2 sharding  staff   102B Jun 19 18:25 dev.vmdk.lck
-rw-r--r--  1 sharding  staff     0B Jun 19 18:25 dev.vmsd
-rw-r--r--  1 sharding  staff   2.5K Jun 19 18:25 dev.vmx
-rw-r--r--  1 sharding  staff   258B Jun 19 18:25 dev.vmxf
-rw-------  1 sharding  staff   1.6K Jun 19 18:25 id_rsa
-rw-------  1 sharding  staff   381B Jun 19 18:25 id_rsa.pub
-rw-------  1 sharding  staff   8.5K Jun 19 18:30 nvram
-rw-r--r--  1 sharding  staff   4.5K Jun 19 18:25 userdata.tar
-rw-r--r--  1 sharding  staff   269K Jun 19 18:26 vmware.log

ls -al .docker/machine/certs/
total 32
drwx------  2 sharding  staff   204B Jun 19 18:24 .
drwx------  5 sharding  staff   170B Jun 19 18:24 ..
-rw-------  1 sharding  staff   1.6K Jun 19 18:24 ca-key.pem
-rw-r--r--  1 sharding  staff   1.0K Jun 19 18:24 ca.pem
-rw-r--r--  1 sharding  staff   1.0K Jun 19 18:24 cert.pem
-rw-------  1 sharding  staff   1.6K Jun 19 18:24 key.pem
```

**Comment by mojodna** [comment]
I managed to get it working by passing the `--native-ssh`

**Comment by erwin16** [comment]
Thanks for the tip, I had the same issue today... w 3.0, is it documented somewhere ? ( how did you find this tip ?)

**Comment by mojodna** [comment]
Not that I've seen.  I saw the option in the `docker-machine` args and figured I'd try it, since the SSH connection was the thing hanging...

**Comment by erwin16** [comment]
thanks will give it a try ... I'm reinstalling ... enjoy your day

**Comment by jconlon** [comment]
I am seeing something similar but with a host that does not have a driver:
`$ docker-machine create --url=tcp:192.168.0.133:2376 shamu`
`To see how to connect Docker to this machine, run: docker-machine env shamu`
`$ docker-machine env shamu`
`open /home/jconlon/.docker/machine/machines/shamu/ca.pem: no such file or directory`
`$ docker-machine ls`
`NAME             ACTIVE   DRIVER      STATE     URL                      SWARM`
`shamu                     none                  tcp:192.168.0.133:2376   `
`test-instance1            amazonec2   Stopped  `

**Comment by jconlon** [comment]
Regarding the previous noted problem.  

Since I am on a local dev lan, I really did not need tls, so  I was able to get a connection to the remote host running docker by adding this line:
DOCKER_OPTS="-H tcp://0.0.0.0:2375 -H unix:///var/run/docker.sock"
to the target host docker configuration (in /etc/default/docker) which causes docker to startup like:
/usr/bin/docker -d -H tcp://0.0.0.0:2375 -H unix:///var/run/docker.sock

Then on the source host where I am running my docker-machine I simply copied the needed *.pem files from the ~/.docker/machine/certs folder to the ~.docker/machine/machines/shamu folder.

**Comment by easel** [comment]
Still seeing this with 0.4 and vmware fusion. --native-ssh works for me as well.

**Comment by DanielSmedegaardBuus** [comment]
I'm have a similar problem, though mine hangs at the `vmrun list` command. Or rather, it tries 60 times, then fails.

Running `vmrun list` myself, I got `Total running VMs: 0`, so I tried running the VM with the same command docker-machine did, sans the `nogui` part:

`/Applications/VMware\ Fusion.app/Contents/Library/vmrun start /Users/daniel/.docker/machine/machines/fusion/fusion.vmx`

This opens up the GUI, and I'm immediately requested to upgrade the machine (strange, I thought docker-machine used Fusion itself to created the vmx?). I do, so and the machine appears to be starting up (greyed out play button in the machine window). After a handful of seconds, it seems to fail though, and the play button turns white again.

Every time I try to start the VM, Console fills with errors like `21/08/15 14:31:20,179 com.apple.xpc.launchd[1]: (com.apple.xpc.launchd.domain.pid.vmware-vmx.6239) Attempt to re-bootstrap service from different path, will use existing: service = com.apple.desktopservices.KeynoteConverterXPCService32, existing = /System/Library/PrivateFrameworks/DesktopServicesPriv.framework/Versions/A_/XPCServices/com.apple.desktopservices.KeynoteConverterXPCService32.xpc, conflicting = /System/Library/PrivateFrameworks/DesktopServicesPriv.framework/Versions/A/XPCServices/com.apple.desktopservices.KeynoteConverterXPCService32.xpc`

Might be a Capitan issue, though :-1:

**Comment by nathanleclaire** [comment]
This issue is slightly old now.  Please re-try with 0.5.0.  If someone continues to encounter similar ones please open a new one at https://github.com/docker/machine/issues/new with detailed information including:

- Which OS you are on
- Anything atypical in networking configuration (VPN, proxy, SSH configuration settings, etc.),
- Output of the misbehaving commands with the `--debug` flag
- the VirtualBox logs from `~/.docker/machine/machines/name/name`.  

Thanks!

- N
