### ISSUE TITLE
docker-machine create --driver digitalocean not working, no error message

### ISSUE THREAD

**Issue by dperetti** [docker/machine#1397]
Just trying to create a digitalocean machine for the first time using a token that I just created in DO console :
```docker-machine create --driver digitalocean --digitalocean-access-token 1239080....12123eafad prod```
... and nothing is happening. It's just hanging without any message. Nothing in the console.

docker-machine version 0.3.0 (0a251fe). Yosemite 10.10.3.

**Comment by dperetti** [comment]
My bad... firewall issue.

**Comment by Oliboy50** [comment]
@dperetti Just something to know about Docker Machine: there is a "debug mode" if you add a `-D` flag (i.e. `docker-machine create -D`)

**Comment by dperetti** [comment]
Thanks, next time I'll think about either the firewall or debug mode trick ! :-)
