### ISSUE TITLE
No need to start machine for upgrade

### ISSUE THREAD

**Issue by arun-gupta** [docker/machine#1399]
Upgrading a machine requires the machine to be started otherwise the following error is reported:

```
Error: machine must be running to upgrade.
```

Upgrading the machine, after stopping the machine, shows the following steps:

```
Stopping machine to do the upgrade...
Upgrading machine microservices...
Downloading https://github.com/boot2docker/boot2docker/releases/download/v1.7.0/boot2docker.iso to /Users/arungupta/.docker/machine/cache/boot2docker.iso...
Starting machine back up...
Starting VM...
```

If the machine needs to stop anyway, the requirement to start the machine to upgrade seems superfluous.

**Comment by nathanleclaire** [comment]
For now, our provisioning system requires the machine to be running in order to detect the OS.  Maybe eventually we can move to storing that information after detecting it once.

**Comment by arun-gupta** [comment]
Yes, that would be useful.

**Comment by dgageot** [comment]
Hi @arun-gupta, I was also surprised with this behaviour. We do need the machine to be started. https://github.com/docker/machine/pull/2168 adds a log that explains what is done before stopping the machine.

-1 on storing information that can be found on the machine.

**Comment by dgageot** [comment]
A log was added in 1f0de8f. It makes it clearer that the machine has to be started before it's stopped
