### ISSUE TITLE
Please include versions in artifact filenames

### ISSUE THREAD

**Issue by mbailey** [docker/machine#1400]
I've spent the past 30 minutes trying to get docker working again after upgrading to docker-1.7 on OSX.

Debugging and maintenance would be easier if a convention of including versions in filenames for artifacts was adopted.

While versions of downloaded files can be obtained by running then with --version, this is not possible with boot2docker.iso.

```
$ md5 ~/.docker/machine/cache/boot2docker.iso
MD5 (/Users/mike.bailey/.docker/machine/cache/boot2docker.iso) = 7d8c43f57d04a250696129221c23cc18
```

**Comment by nathanleclaire** [comment]
Does `file` work for this use case?

```console
$ file ~/.docker/images/boot2docker.iso
/Users/nathanleclaire/.docker/images/boot2docker.iso: ISO 9660 CD-ROM filesystem data 'Boot2Docker-v1.5.0             ' (bootable)
```
