### ISSUE TITLE
[generic driver] OSX adds extra output to SSH command, causing error on create

### ISSUE THREAD

**Issue by samwierema** [docker/machine#1402]
I just upgraded to 0.3.0 with Homebrew and facing an issue with the generic driver when running the following command:

```
docker-machine -D create -d generic --generic-ip-address "172.x.x.x" machine-name
```
The command prompts me for the id_rsa password for each command (see #1374), and **is able to successfully connect** to the server using SSH. The issue occurs due to the output of the SSH command on OSX, where it adds one or two lines on top of the output. 

```
$ usr/bin/ssh -o PasswordAuthentication=no -o IdentitiesOnly=yes -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=quiet -o ConnectionAttempts=3 -o ConnectTimeout=10 -i /path/to/machine/id_rsa -p 22 root@172.x.x.x cat /etc/os-release

Saving password to keychain failed
Identity added: /path/to/machine/id_rsa (/path/to/machine/id_rsa)
NAME="Ubuntu"
VERSION="14.04.2 LTS, Trusty Tahr"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 14.04.2 LTS"
VERSION_ID="14.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
```
This causes the parsing of the ```os-release``` file to fail and throw the following error: 
```
Error creating machine: Error parsing /etc/os-release file: Expected Saving password to keychain failed to split by '=' char into two strings, instead got 1 strings
```
The issue originates here: https://github.com/docker/machine/blob/master/libmachine/provision/os_release.go#L59

I've tried the adding the ```-y``` and ```-q``` flag to the SSH command to see if that would remove the extra output, but to no avail. And when you say to "Save the password in Keychain" on the password prompt, the first line ("Failed to...") is removed, but the second line ("Identity added...") will still exist, triggering the error.

This might be an issue with SSH on OSX and not with machine itself, but I thought I'd report it anyway. I'm running OSX 10.10.3, ```OpenSSH_6.2p2, OSSLShim 0.9.8r 8 Dec 2011``` and docker-machine version 0.3.0.

**Comment by gsfr** [comment]
I encountered the same problem, but was able to temporarily work around it by using a passphrase-less ssh key. Not ideal by any means.

**Comment by nathanleclaire** [comment]
Mmmmm yeah that's no fun.  I wonder if differentiating the STDOUT and STDERR of the command would help.

**Comment by endersonmaia** [comment]
Same problem here.

**Comment by mtscout6** [comment]
Are there any known workarounds to this problem? When I try `docker-machine env es01` I get the output:

```
➜  ~  docker-machine env es01
open /Users/smithm/.docker/machine/machines/es01/ca.pem: no such file or directory
```

I can run `docker-machine ssh es01` and I can successfully connect.

**Comment by nathanleclaire** [comment]
@mtscout6 For that problem, try `docker-machine regenerate-certs -f es01`

**Comment by mtscout6** [comment]
Still a no go:

```
➜  docker-metrics git:(master) ✗ dm regenerate-certs -f es01
Regenerating TLS certificates
Error getting SSH command: exit status 255
```

**Comment by jh12z** [comment]
For some reason it seems Mac OS keeps prompting for the passphrase when there is no corresponding `id_rsa.pub` or `id_dsa.pub` beside the private key on the same directory.

You can generate the file using command:

```
ssh-keygen -y -f ~/.docker/machine/machines/machine-name/id_rsa > ~/.docker/machine/machines/machine-name/id_rsa.pub
```

I run the command on another terminal window  the first time I get asked for the passphrase as the directory doesn't exist until `docker-machine create` command creates it.

I suppose the fix would be to include the `.pub` file.

Credits to Constantine Sapuntzakis' answer: http://apple.stackexchange.com/a/26252/17690.

**Comment by smithkyle** [comment]
+1 to the above. This has been a pain in my side after my initial excitement at being able to use machine to manage already-existing docker machines.

**Comment by sheerun** [comment]
Please also add .pub file. It's really annoying that keychain asks for password each time, especially it happens 20+ times during `docker-machine create`.

**Comment by dgageot** [comment]
Hi everybody, dealing with existing hosts can be simple if you rely on ssh-agent. Here's what the `generic` driver says:

```
Interaction with SSH Agents

When an SSH identity is not provided (with the --generic-ssh-key flag), the SSH agent (if running) will be consulted. This makes it possible to easily use password-protected SSH keys.

Note that this usage is only supported if you're using the external SSH client, which is the default behaviour when the ssh binary is available. If you're using the native client (with --native-ssh), using the SSH agent is not yet supported.
```

Can you have a look?

**Comment by dgageot** [comment]
Closing the issue. The official way of supporting password protected keys with the generic driver is to use an ssh-agent.
