### ISSUE TITLE
i/o timeout when upgrading vm

### ISSUE THREAD

**Issue by sarvagnan** [docker/machine#1413]
When running docker-machine upgrade for a vm, the upgrade operation timesout. I'm running machine on OS X 10.10.3
The output is as follows:
Stopping machine to do the upgrade...
Upgrading machine devdocker...
Downloading https://github.com/boot2docker/boot2docker/releases/download/v1.7.0/boot2docker.iso to /Users/sarvagnan/.docker/machine/cache/boot2docker.iso...
Get https://github.com/boot2docker/boot2docker/releases/download/v1.7.0/boot2docker.iso: dial tcp: i/o timeout

How do I fix this?
Thanks!

**Comment by dnozay** [comment]
In my case (as commented in bug #1274), I had to re-order nameservers in my `/etc/resolv.conf` to pick up a different nameserver. Check with `nslookup` if you can resolve the server's address.

**Comment by sarvagnan** [comment]
This is my resolv.conf

#
# Mac OS X Notice
#
# This file is not used by the host name and address resolution
# or the DNS query routing mechanisms used by most processes on
# this Mac OS X system.
#
# This file is automatically generated.
#
nameserver 192.168.1.1

As to nslookup, github.com is resolved, but https://github.com, github.com/boot2docker/boot2docker, https://github.com/boot2docker/boot2docker/releases/download/v1.7.0/boot2docker.iso, and github.com/boot2docker/boot2docker/releases/download/v1.7.0/boot2docker.iso are not. Should I add something to my resolv.conf for this to work?

**Comment by dnozay** [comment]
you can open your network preferences > advanced > DNS and add some DNS servers explicitly.

**Comment by sarvagnan** [comment]
That worked. Thanks!
