### ISSUE TITLE
Docker Machine Cleanup when Resources are not created 

### ISSUE THREAD

**Issue by kgrvamsi** [docker/machine#1414]
Problem

With the new flag for aws in requesting spot instances i have tried creating the instance and seems like the requests halts in waiting for the spot instance to create but it creates the keypair with the machine name .

Is it possible that when the user does a CTRL+^C then the resources which are created for this request will be cleaned so that the user can request for a new resource with the same name.

this may help us not to change the machine name or any other attributes more aws cleaning efforts will be reduced when we are creating machines through CLI

**Comment by nathanleclaire** [comment]
Hi @kgrvamsi thanks for the report and while we'd love such a feature, it cannot really be done reliably.  See https://github.com/docker/machine/issues/972#issuecomment-93651103 for explanation.
