### ISSUE TITLE
Catalog of changes to machine target

### ISSUE THREAD

**Issue by stephanbuys** [docker/machine#1415]
Hi, is there a way to see (or perhaps a doc?) that catalogues the changes made by machine on a target host? 

I'm mostly interested in determining if machine will eventually take care of all of the hardening, customisation, etc required to 'run docker right' or if another provisioner (such as saltstack) should be used to harden systems.

Thanks!

**Comment by nathanleclaire** [comment]
There is not such a thing today (other than the code, of course), but I do really like this idea.  Especially as it would allow operators a quick chance to look at, critique and make suggestions.

**Comment by stephanbuys** [comment]
Agreed, the docker-machine model allows an operator to really treat the machine in a hands-off fashion via a secure port, so if we get all the right hardening, etc, bits in there it might solve a lot of use cases (CIS, etc). Other option is to include a `script` option that will be run in conjunction to the creation commands that already exist allowing an operator to customise, lock things down.
