### ISSUE TITLE
Support config file over "eval"

### ISSUE THREAD

**Issue by parabuzzle** [docker/machine#1416]
I would like to be able to do intelligent machine switching per project (like the way rvm uses `.ruby-version` & `.gemset` to automatically change over to the correct ruby and gemset when switching into the directory)

Instead of the `eval "$(docker-machine env foo)"` configuration should be handled by a config file in the directory.

The problem I'm attempting to solve here is, at the minimum, I would like to be able to run a script that can set up my docker machine and load it as my docker host, etc. The problem here is that I can't embed the `eval "$(docker-machine env foo)"` statement into a bash script because the export statements are lost because the bash script can't modify the parents env (without some dirty gdb based hacking). 

If docker/docker-machine could configure this via a config file or some other config injection, it would allow more scripting and handling of this in an abstract way.

**Comment by nathanleclaire** [comment]
As you mentioned, there's nothing that Machine can do in terms of environment.  In order to get `docker` client to "automatically" point at a machine, without environment variables, one would have to get upstream Docker to honor the config file.

However, you could use a shell script workaround such as:

```bash
function mcndocker() {
    docker $(docker-machine config $1) ${*:2}
}

# Will run "docker ps" on host "dev"
mcndocker dev ps

# Will run "docker run busybox echo hello" on host "staging"
mcndocker staging run busybox echo hello  
```
