### ISSUE TITLE
I got an error when trying to run docker run hello-world

### ISSUE THREAD

**Issue by evanyetter** [docker/machine#1419]
As you can probably tell by the title, I am extremely new to docker, so I am just attempting to get it set up.  After I completed the installation and running the start script, I ran the test line "docker run hello-world" to make sure everything was alright, but got the following error:

An error occurred trying to connect: Post https://192.168.56.101:2376/v1.19/cont
ainers/create: x509: certificate is valid for 127.0.0.1, 10.0.2.15, not 192.168.
56.101

I read a little bit about these types of errors on other threads of the repository, but I can't find anything about this happening right off the bat from the hello-world command, and I also don't think I could have performed some of the complicated "fixes" without step by step guidance.

Any help would be appreciated, thanks!

**Comment by wenlock** [comment]
@evanyetter i was trying to follow the same steps, im new to machine as well.. can you tell me what docker-machine -v is for you?

**Comment by nathanleclaire** [comment]
@evanyetter Is it still an issue?  

Please make sure you upgrade to 0.3.0 and try: 

- `docker-machine restart name`
- (if that doesn't work) `docker-machine regenerate-certs name`

Then the usual `eval $(docker-machine env name)` and see if it works.

**Comment by thaJeztah** [comment]
think this can be closed?

**Comment by nathanleclaire** [comment]
Thanks for calling that out @thaJeztah
