### ISSUE TITLE
Machine hangs indefinitely if unable to access machine via SSH

### ISSUE THREAD

**Issue by ekristen** [docker/machine#1424]
It appears that machine hangs indefinitely and chews up a good percentage of CPU when it is unable to access the machine it is spinning up via SSH. Perhaps there should be a timeout and an subsequent error?

**Comment by labianchin** [comment]
Same problem.
Running on OSX, openstack driver with ubuntu 14.04 as flavor when running *docker-machine -D create" it hangs here:

```
About to run SSH command:
exit 0
&{/usr/bin/ssh [/usr/bin/ssh -o PasswordAuthentication=no -o IdentitiesOnly=yes -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=quiet -o ConnectionAttempts=3 -o ConnectTimeout=10 -i /Users/user/.docker/machine/machines/my-machine/id_rsa -p 22 ubuntu@10.1.2.3 exit 0] []  <nil> <nil> <nil> [] <nil> <nil> <nil> <nil> false [] [] [] [] <nil>}
```

This only happens on machine v0.3.

**Comment by kung-fu-tzu** [comment]
+1, but without CPU consumption.

**Comment by ggiamarchi** [comment]
@labianchin docker-machine tries to contact your OpenStack machine on `10.1.2.3` which is a private IP (i guess this is an IP on your OpenStack private network). Are you sure you run docker-machine from somewhere you can join this IP ? If not, maybe you forgot to add a floating IP on the `create` command or maybe your machine should be directly connected on a public network (it depends your OpenStack installation)

If this don't help, please provide your `create`  command and the whole debug log.

**Comment by labianchin** [comment]
@ggiamarchi. That was in a private VPN, but I was connected.
A few days later I did not have this issue anymore.

**Comment by nathanleclaire** [comment]
There is a timeout.  If Machine can't reach machine via SSH but should be able to, that should be filed as a new bug.  Otherwise SSH won't work for other reasons.
