### ISSUE TITLE
[vsphere driver] Esxi free license ( Not 60 days trial )

### ISSUE THREAD

**Issue by cdosso** [docker/machine#1427]
Hello,

Could you add in your documentation that vsphere driver isn't working for ESXi free license?  

It's related to govc but enjoyed by your documentation I've been really frustraded while trying it and getting this error on machine creation : 
> Error: ServerFaultCode: Current license or ESXi version prohibits execution of the requested operation.

Cheers

**Comment by nathanleclaire** [comment]
Nice point - want to win some Machine Points and make a pull request to do so ?   :)

**Comment by nathanleclaire** [comment]
The fix this is now merged!  Thanks !
