### ISSUE TITLE
docker-machine create hangs when using ``--digitalocean-image ubuntu-15-04-x64``

### ISSUE THREAD

**Issue by rogaha** [docker/machine#1431]
The machine is created, but further commands from ``docker-machine`` that needs to talk to the daemon as ``docker-machine env`` also hangs for those VMs. It hangs because the daemon is not reachable.

**Comment by rogaha** [comment]
``ubuntu 15.04`` doesn't use upstart it uses systemd, it might be related to this issue.

**Comment by jgkamat** [comment]
Right now DOCKER_OPTS isn't appended to the docker daemon on debian 8/ubuntu 15.04. See [this pull](https://github.com/docker/docker/pull/13923) for a discussion. Docker machine uses that file to specify options, so probably they aren't getting applied to the daemon.

**Comment by nathanleclaire** [comment]
Yes, I think it's because we expect the "old school" init, and 15.04 switches to use systemd.  We will have to do some kind of funny systemd / non-systemd split with the provisioners methinks.

**Comment by ntfrnzn** [comment]
It seems that this is still a live issue, I've run into it because docker networking as of v1.9 requires kernel >= 3.16. Upgrading the Digital Ocean image to Ubuntu 15 looks like the easy way to get there, except ...

**Comment by nathanleclaire** [comment]
@ntfrnzn Yes, it's quite high on the priority list.

**Comment by bhurlow** [comment]
@ntfrnzn progress on this here: https://github.com/docker/machine/pull/2311#issuecomment-157925045 I also need ubuntu 15 for multihost networking

**Comment by dgageot** [comment]
Fixed with https://github.com/docker/machine/pull/2311
