### ISSUE TITLE
The Google driver creates a firewall rule for docker (2376) but not swarm (3376)

### ISSUE THREAD

**Issue by DazWilkin** [docker/machine#1432]
After learning about machine and swarm this week at DockerCon was excited to explore them using [Google] Compute Engine (GCE).

One problem that may confuse those unfamiliar with GCE is that the docker-machine driver for Google creates the needed firewall rule for port 2376 but -- somewhat understandably -- does not open 3376 which is needed once one decides to go "whole-hog" and play with swarm too.

This is easily resolved either by navigating to the firewall rules in the Developers Console and creating a firewall rule "tcp:3376" and preferably reusing the "docker-machine" tag:

https://console.developers.google.com/project/_/compute/networksDetail/global/networks/default

Or through the command-line:

    gcloud compute firewall-rules create swarm-machines --allow tcp:3376 --source-ranges 0.0.0.0/0 --target-tags docker-machine --project [[google-project]]

[[google-project]] == the Google project ID and the same value used in docker-machine commands that use the Google driver, e.g.

    docker-machine create --driver google --google-project [[google-project]] [[my-docker-machine]]

Full disclosure: I'm a Google employee in cloud but not a developer

**Comment by nathanleclaire** [comment]
@abronan ran into this just yesterday.  It should definitely be fixed.  cc @jeffmendoza

**Comment by abronan** [comment]
Yes, I can confirm I had the same issue :+1:

Also I remember this working as intended with `0.3.0-rcX`, so not sure on when the regression was introduced.

**Comment by dgageot** [comment]
Hi @DazWilkin, do you think it's ok if we always open both ports? Or should we do it only when a swarm host is created?

**Comment by DazWilkin** [comment]
My personal opinion, is to open both (or flag?) when provisioning with docker-machine since this is the interaction point with compute engine and is more convenient.

From a security, do-only-what's-needed perspective, it would be preferable to only augment the firewall when the user explicitly needs swarm but that may make your flow more complex.

Apologies for the delayed reply.

**Comment by dgageot** [comment]
I just checked and the driver already opens both ports if a swarm master is created. The problem is that the firewall rule is not updated if it already existed before a swarm master is created.
I'll see if this can be fixed
