### ISSUE TITLE
docker-machine hangs after creation with virtualbox

### ISSUE THREAD

**Issue by stevvooe** [docker/machine#1433]
The following command hangs nearly forever:

```
docker-machine -D create prod --engine-storage-driver overlay -d virtualbox --virtualbox-disk-size 40000 --virtualbox-memory 2048
```

I can ssh in and it looks like the daemon is running:

```
time="2015-06-26T23:34:28.862838098Z" level=debug msg="Using 0x7d6e80 as native.cgroupdriver"
time="2015-06-26T23:34:28.863139059Z" level=info msg="Daemon has completed initialization"
time="2015-06-26T23:34:28.863158533Z" level=info msg="Docker daemon" commit=0baf609 execdriver=native-0.2 graphdriver=aufs version=1.7.0
```

However, if I use eval, I get an error message:

```console
$ eval $(docker-machine env prod)
open /Users/sday/.docker/machine/machines/prod/ca.pem: no such file or directory
```

Here is the debug output: https://gist.github.com/stevvooe/b89bb209b0ee38608bc4

I cannot use docker at all on my machine, at this point.

```console
$ docker-machine --version
docker-machine version 0.3.0 (0a251fe)
```

**Comment by garystafford** [comment]
gstafford@gstafford-X555LA$ docker-machine --version
docker-machine version 0.3.0 (0a251fe)

Seeing identical issues/results, repeatedly, with basic docker-machine command with VirtualBox
Created gist of most of output: https://gist.github.com/8d244fe478e59dd4d131.git
It worked for first two days, then started this behavior...

gstafford@gstafford-X555LA$ docker-machine create --driver virtualbox test
Creating VirtualBox VM...
Creating SSH key...
Starting VirtualBox VM...
Starting VM...

Error creating machine: Maximum number of retries (60) exceeded
You will want to check the provider to make sure the machine and associated resources were properly removed.
gstafford@gstafford-X555LA$ docker-machine ls
NAME   ACTIVE   DRIVER       STATE     URL                         SWARM
test            virtualbox   Running   tcp://192.168.99.100:2376   

gstafford@gstafford-X555LA$ $ eval $(docker-machine env test)
open /home/gstafford/.docker/machine/machines/test/ca.pem: no such file or directory
$: command not found

**Comment by veggiemonk** [comment]
+1  Same here

```
▶ docker-machine create --driver virtualbox dev
Creating CA: /home/veggiemonk/.docker/machine/certs/ca.pem
Creating client certificate: /home/veggiemonk/.docker/machine/certs/cert.pem
Image cache does not exist, creating it at /home/veggiemonk/.docker/machine/cache...
No default boot2docker iso found locally, downloading the latest release...
Downloading https://github.com/boot2docker/boot2docker/releases/download/v1.7.0/boot2docker.iso to /home/veggiemonk/.docker/machine/cache/boot2docker.iso...
Creating VirtualBox VM...
Creating SSH key...
Starting VirtualBox VM...
Starting VM...
Error creating machine: Too many retries.  Last error: Maximum number of retries (60) exceeded
You will want to check the provider to make sure the machine and associated resources were properly removed.
```
It differs a little bit here
```
▶ docker-machine ls    
error getting URL for host dev: exit status 255
NAME   ACTIVE   DRIVER       STATE     URL   SWARM
dev    *        virtualbox   Running         
[~]                                                                                                                                                                                         
▶ eval $(docker-machine env dev)
Unexpected error getting machine url: exit status 255
```
Maybe that version has problem
```
▶ docker-machine --version      
docker-machine version 0.3.0 (0a251fe)
```

**Comment by liudonghua123** [comment]
I also got the similar problem.
```
ldh@ldh-HVM-domU:~$ docker-machine create -d virtualbox local
Creating VirtualBox VM...
Creating SSH key...
Starting VirtualBox VM...
Starting VM...
Error creating machine: Too many retries.  Last error: Maximum number of retries (60) exceeded
You will want to check the provider to make sure the machine and associated resources were properly removed.
ldh@ldh-HVM-domU:~$
```

and I noticed some failures when installing virtualbox, is the installation not successful?
```
ldh@ldh-HVM-domU:~$ sudo apt-get install virtualbox
[sudo] password for ldh: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages were automatically installed and are no longer required:
  diffstat gettext intltool-debian libapt-pkg-perl libarchive-zip-perl
  libasprintf-dev libauthen-sasl-perl libautodie-perl libclass-accessor-perl
  libclone-perl libdigest-hmac-perl libdpkg-perl libemail-valid-perl
  libfile-fcntllock-perl libgettextpo-dev libgettextpo0 libio-pty-perl
  libio-socket-inet6-perl libio-socket-ssl-perl libio-string-perl
  libipc-run-perl libipc-system-simple-perl liblist-moreutils-perl
  libmailtools-perl libnet-dns-perl libnet-domain-tld-perl libnet-ip-perl
  libnet-libidn-perl libnet-smtp-ssl-perl libnet-ssleay-perl
  libparse-debianchangelog-perl libperlio-gzip-perl libsocket6-perl
  libsub-identify-perl libsub-name-perl libtext-levenshtein-perl
  libtimedate-perl liburi-perl patchutils t1utils
Use 'apt-get autoremove' to remove them.
The following extra packages will be installed:
  virtualbox-dkms virtualbox-qt
Suggested packages:
  virtualbox-guest-additions-iso vde2
The following NEW packages will be installed:
  virtualbox virtualbox-dkms virtualbox-qt
0 upgraded, 3 newly installed, 0 to remove and 316 not upgraded.
Need to get 0 B/20.6 MB of archives.
After this operation, 84.1 MB of additional disk space will be used.
Do you want to continue? [Y/n] y
Selecting previously unselected package virtualbox.
(Reading database ... 173957 files and directories currently installed.)
Preparing to unpack .../virtualbox_4.3.10-dfsg-1ubuntu5_amd64.deb ...
Unpacking virtualbox (4.3.10-dfsg-1ubuntu5) ...
Selecting previously unselected package virtualbox-dkms.
Preparing to unpack .../virtualbox-dkms_4.3.10-dfsg-1ubuntu5_all.deb ...
Unpacking virtualbox-dkms (4.3.10-dfsg-1ubuntu5) ...
Selecting previously unselected package virtualbox-qt.
Preparing to unpack .../virtualbox-qt_4.3.10-dfsg-1ubuntu5_amd64.deb ...
Unpacking virtualbox-qt (4.3.10-dfsg-1ubuntu5) ...
Processing triggers for ureadahead (0.100.0-16) ...
ureadahead will be reprofiled on next reboot
Processing triggers for man-db (2.6.7.1-1ubuntu1) ...
Processing triggers for shared-mime-info (1.2-0ubuntu3) ...
Processing triggers for gnome-menus (3.10.1-0ubuntu2) ...
Processing triggers for desktop-file-utils (0.22-1ubuntu1) ...
Processing triggers for bamfdaemon (0.5.1+14.04.20140409-0ubuntu1) ...
Rebuilding /usr/share/applications/bamf-2.index...
Processing triggers for mime-support (3.54ubuntu1.1) ...
Processing triggers for hicolor-icon-theme (0.13-1) ...
Setting up virtualbox (4.3.10-dfsg-1ubuntu5) ...
 * Stopping VirtualBox kernel modules                                                                                 [ OK ] 
 * Starting VirtualBox kernel modules                                                                                         * No suitable module for running kernel found
                                                                                                                      [fail]
invoke-rc.d: initscript virtualbox, action "restart" failed.
Setting up virtualbox-dkms (4.3.10-dfsg-1ubuntu5) ...
Loading new virtualbox-4.3.10 DKMS files...
First Installation: checking all kernels...
Building only for 3.16.0-30-generic
Building initial module for 3.16.0-30-generic
Done.

vboxdrv:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/3.16.0-30-generic/updates/dkms/

vboxnetadp.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/3.16.0-30-generic/updates/dkms/

vboxnetflt.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/3.16.0-30-generic/updates/dkms/

vboxpci.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/3.16.0-30-generic/updates/dkms/

depmod...........

DKMS: install completed.
 * Stopping VirtualBox kernel modules                                                                                 [ OK ] 
 * Starting VirtualBox kernel modules                                                                                 [ OK ] 
Setting up virtualbox-qt (4.3.10-dfsg-1ubuntu5) ...
ldh@ldh-HVM-domU:~$ 
ldh@ldh-HVM-domU:~$ 
ldh@ldh-HVM-domU:~$ 
ldh@ldh-HVM-domU:~$ service virtualbox status
VirtualBox kernel modules are loaded.
ldh@ldh-HVM-domU:~$
ldh@ldh-HVM-domU:~$ apt-cache show virtualbox
Package: virtualbox
Priority: optional
Section: multiverse/misc
Installed-Size: 57189
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Original-Maintainer: Debian Virtualbox Team <pkg-virtualbox-devel@lists.alioth.debian.org>
Architecture: amd64
Version: 4.3.10-dfsg-1ubuntu5
Depends: libc6 (>= 2.15), libcurl3 (>= 7.16.2), libgcc1 (>= 1:4.1.1), libgsoap4, libpng12-0 (>= 1.2.13-4), libpython2.7 (>= 2.7), libsdl1.2debian (>= 1.2.11), libssl1.0.0 (>= 1.0.0), libstdc++6 (>= 4.6), libvncserver0, libvpx1 (>= 1.0.0), libx11-6, libxcursor1 (>> 1.1.2), libxext6, libxml2 (>= 2.7.4), libxmu6, libxt6, zlib1g (>= 1:1.1.4), python (>= 2.7), python (<< 2.8), python:any (>= 2.7.1-0ubuntu2), python2.7, adduser
Pre-Depends: dpkg (>= 1.15.6~)
Recommends: virtualbox-dkms (= 4.3.10-dfsg-1ubuntu5) | virtualbox-source (= 4.3.10-dfsg-1ubuntu5), virtualbox-qt (= 4.3.10-dfsg-1ubuntu5), libgl1-mesa-glx | libgl1, libqt4-opengl (>= 4:4.5.3), libqtcore4 (>= 4:4.5.3), libqtgui4 (>= 4:4.5.3)
Suggests: virtualbox-guest-additions-iso, vde2
Conflicts: virtualbox-2.0, virtualbox-2.1, virtualbox-2.2, virtualbox-3.0, virtualbox-4.2
Filename: pool/multiverse/v/virtualbox/virtualbox_4.3.10-dfsg-1ubuntu5_amd64.deb
Size: 15462556
MD5sum: 7f9d1580006728446bb8c0fd715b0b7c
SHA1: 2f27091cd05c6c17167aae1c20d1aae636f93f9e
SHA256: 8dbf9d77a4f48051765ca14ad4df8a4a49ec6d840469eaf3ba6def8e02bc34ee
Description-en: x86 virtualization solution - base binaries
 VirtualBox is a free x86 virtualization solution allowing a wide range
 of x86 operating systems such as Windows, DOS, BSD or Linux to run on a
 Linux system.
 .
 This package provides the binaries for VirtualBox. Either the virtualbox-dkms
 or the virtualbox-source package is also required in order to compile the
 kernel modules needed for virtualbox. A graphical user interface for
 VirtualBox is provided by the package virtualbox-qt.
Description-md5: 30f96d22c1a6ca04db16bdc1e79ad965
Homepage: http://www.virtualbox.org/
Bugs: https://bugs.launchpad.net/ubuntu/+filebug
Origin: Ubuntu

Package: virtualbox
Priority: optional
Section: multiverse/misc
Installed-Size: 57210
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Original-Maintainer: Debian Virtualbox Team <pkg-virtualbox-devel@lists.alioth.debian.org>
Architecture: amd64
Version: 4.3.10-dfsg-1
Depends: libc6 (>= 2.15), libcurl3 (>= 7.16.2), libgcc1 (>= 1:4.1.1), libgsoap4, libpng12-0 (>= 1.2.13-4), libpython2.7 (>= 2.7), libsdl1.2debian (>= 1.2.11), libssl1.0.0 (>= 1.0.0), libstdc++6 (>= 4.6), libvncserver0, libvpx1 (>= 1.0.0), libx11-6, libxcursor1 (>> 1.1.2), libxext6, libxml2 (>= 2.7.4), libxmu6, libxt6, zlib1g (>= 1:1.1.4), python (>= 2.7), python (<< 2.8), python:any (>= 2.7.1-0ubuntu2), python2.7, adduser
Pre-Depends: dpkg (>= 1.15.6~)
Recommends: virtualbox-dkms (= 4.3.10-dfsg-1) | virtualbox-source (= 4.3.10-dfsg-1), virtualbox-qt (= 4.3.10-dfsg-1), libgl1-mesa-glx | libgl1, libqt4-opengl (>= 4:4.5.3), libqtcore4 (>= 4:4.5.3), libqtgui4 (>= 4:4.5.3)
Suggests: virtualbox-guest-additions-iso, vde2
Conflicts: virtualbox-2.0, virtualbox-2.1, virtualbox-2.2, virtualbox-3.0, virtualbox-4.2
Filename: pool/multiverse/v/virtualbox/virtualbox_4.3.10-dfsg-1_amd64.deb
Size: 15513912
MD5sum: 94abe68c331d26a086ba36c97c86d05f
SHA1: 7d75b3aa319377613bf0ade1e55e4d81c906af1c
SHA256: d42c80fc72522c46d5375389ddf2370f406433ba3b5a8f19fc414e6c4d143fcd
Description-en: x86 virtualization solution - base binaries
 VirtualBox is a free x86 virtualization solution allowing a wide range
 of x86 operating systems such as Windows, DOS, BSD or Linux to run on a
 Linux system.
 .
 This package provides the binaries for VirtualBox. Either the virtualbox-dkms
 or the virtualbox-source package is also required in order to compile the
 kernel modules needed for virtualbox. A graphical user interface for
 VirtualBox is provided by the package virtualbox-qt.
Description-md5: 30f96d22c1a6ca04db16bdc1e79ad965
Homepage: http://www.virtualbox.org/
Bugs: https://bugs.launchpad.net/ubuntu/+filebug
Origin: Ubuntu

ldh@ldh-HVM-domU:~$ 
ldh@ldh-HVM-domU:~$ 
ldh@ldh-HVM-domU:~$ 
ldh@ldh-HVM-domU:~$ 
ldh@ldh-HVM-domU:~$ clear
ldh@ldh-HVM-domU:~$ 
ldh@ldh-HVM-domU:~$ 
ldh@ldh-HVM-domU:~$ 
ldh@ldh-HVM-domU:~$ ll .docker/
config.json  machine/     
ldh@ldh-HVM-domU:~$ ll .docker/machine/
cache/    certs/    machines/ 
ldh@ldh-HVM-domU:~$ ll .docker/machine/machines/
total 8
drwx------ 2 ldh ldh 4096  6月 28 08:34 ./
drwx------ 5 ldh ldh 4096  6月 27 22:17 ../
ldh@ldh-HVM-domU:~$ 
ldh@ldh-HVM-domU:~$ 
ldh@ldh-HVM-domU:~$ docker-machine create -d virtualbox local
Creating VirtualBox VM...
Creating SSH key...
Starting VirtualBox VM...
Starting VM...
Error creating machine: Too many retries.  Last error: Maximum number of retries (60) exceeded
You will want to check the provider to make sure the machine and associated resources were properly removed.
ldh@ldh-HVM-domU:~$
```

**Comment by liudonghua123** [comment]
I think it might be a VT-x problem.
I checked whether the VT-x of my computer(actually it's a virtual machine) is enabled or not by executing `sudo kvm-ok` according [how-to-determine-if-cpu-vt-extensions-enabled-in-bios](http://askubuntu.com/questions/103965/how-to-determine-if-cpu-vt-extensions-enabled-in-bios)

```
ldh@ldh-HVM-domU:~$ sudo kvm-ok
INFO: Your CPU does not support KVM extensions
KVM acceleration can NOT be used
ldh@ldh-HVM-domU:~$
```

I will consult the administrator about changing VT-x settings and try again.

**Comment by liudonghua123** [comment]
I have the similar problem when I run on Windows, I have VT-x enabled.
```
Liu.D.H@WORKING-PC ~
$ docker-machine create --driver virtualbox dev
No default boot2docker iso found locally, downloading the latest release...
Downloading https://github.com/boot2docker/boot2docker/releases/download/v1.7.0/boot2docker.iso to C:\Users\Liu.D.H\.docker\machine\cache\boot2docker.iso...
Creating VirtualBox VM...
Creating SSH key...
Starting VirtualBox VM...
Starting VM...
Error creating machine: Maximum number of retries (60) exceeded
You will want to check the provider to make sure the machine and associated resources were properly removed.

Liu.D.H@WORKING-PC ~
```

**Comment by ehazlett** [comment]
@stevvooe i've seen this too.  as @garystafford mentioned, a `eval $(docker-machine env -u)` fixes it for me.  i need to dig further into what the root cause is.

**Comment by ehazlett** [comment]
@veggiemonk i'm not sure you can run a 64 bit OS on 32 bit host.  Starting with b2d 1.7, I believe it's 64 bit now.  that could be part of it.

**Comment by stevvooe** [comment]
@ehazlett I did a full restart to address the issue. There may have been a few things going on that were fixed with the restart (the env issue, being one of them). I was also getting problems where the daemon would not start because it would not bind to the interface. My guess is that there is a bug related to env setup and a networking problem with VirtualBox. I'm sorry I don't have better information here.

**Comment by garystafford** [comment]
@ehazlett the unset command you/I mentioned works for me occasionally, but most often I am also rebooting to clear whatever state Docker Machine is in, and then deleting the existing, mis-configured VM. I hit the problem pretty often. I have the latest release version of Docker, Compose, and Machine, running on Ubuntu 14.10.

**Comment by tavisto** [comment]
I was not having this issue until I did a 
```console
$docker-machine upgrade dev
```
Where dev was my docker host on virtualbox that had previously worked just fine. 

OSX 10.10.3 with virtaulbox 4.3.26, docker-machine 0.3.0

I updated my virtualbox to v4.3.28 as well as the Extension pack. 
According to the boot2docker release it included the VirtualBox Guest Additions v4.3.28. 

Once I updated everything it all worked again. I am theorizing that the boot2docker image contains some helpers that might be causing this issue on other platforms as well.

**Comment by nathanleclaire** [comment]
@stevvooe Looks like your flags aren't getting parsed quite correctly as well, which definitely means we need to fix that issue.

**Comment by nathanleclaire** [comment]
Really peculiar issue.  Looks like the daemon starts fine but Machine fails to detect it.  @stevvooe do you have some non-vanilla stuff in terms on networking on the box where you've run this?  Perhaps VPN, changes to your DNS resolution, etc.?  Does the Machine get an IP from the Virtualbox host only network?

**Comment by GoNZooo** [comment]
I hesitate to say that this is exactly the same issue, but I just now got past this. When I tried to create a new machine using 'docker-machine create -d virtualbox' I ended up halting at "Starting VM...".

I had all but given up when I checked out some VirtualBox documentation on the Arch wiki and saw that it requires the package ['net-tools'](https://www.archlinux.org/packages/core/x86_64/net-tools/) (this includes ifconfig and the like and since this package is actually deprecated on Arch it's not installed). I installed it and instantly got past "Starting VM..." on the first try, despite having previously tried reboots, '--native-ssh' and the like before without any success.

If anything, this might be of help to anyone having the same issues for the same reason I did, even if it's probably not the core reason for the issues of previous posters here.

**Comment by stevvooe** [comment]
@nathanleclaire I don't have anything special setup, except the for a standard VPN, which does inject routes. Inspection of those routes showed nothing peculiar. As far as I could tell, the machine got an IP assigned but the traffic was being black-holed.

I issued a restart and the issue went away, so take what I say above with a grain of salt.

**Comment by mgasner** [comment]
unset command seems to work for this on OS X as well

**Comment by nathanleclaire** [comment]
> unset command seems to work for this on OS X as well

Could you elaborate on what you mean by this please @mgasner ?

**Comment by jmonmane** [comment]
I was getting the "Unexpected error getting machine url: exit status 255" and fixed it by adding this line to the top of my hosts file:
127.0.0.1 localhost

**Comment by nathanleclaire** [comment]
> I was getting the "Unexpected error getting machine url: exit status 255" and fixed it by adding this line > to the top of my hosts file:
> 127.0.0.1 localhost

Hm, odd.  Maybe we should dial `127.0.0.1` directly, although I don't know how common it is to lack the `localhost` entry in a hosts file.

**Comment by jmonmane** [comment]
Ya maybe not, looks like I've edited my hosts file several times. Somebody had put a machine named localhost on our domain, which was why I went looking at my hosts file.

**Comment by polinom** [comment]
Had the same problem

```
(djangopeople)igor:~$ docker-machine active                                                           
error getting URL for host dbandredis: exit status 255                                                
error getting URL for host dbandredis: exit status 255                                                
error determining if host is active for host dbandredis: exit status 255                            
dev
```

Rebooting would not help. Had to remove vm and create it again.

**Comment by saada** [comment]
+1

**Comment by chromerobv** [comment]
i have yet to get this to work. i have uninstalled everything blew away every directory to do with virtualbox and or docker and i still can't connect to this. the docker vm is running in virtualbox and looks fine. 



Creating Machine default...
Creating VirtualBox VM...
Creating SSH key...
Starting VirtualBox VM...
Starting VM...
Error creating machine: Too many retries.  Last error: Maximum number of retries (60) exceeded
You will want to check the provider to make sure the machine and associated resources were properly removed.
Starting machine default...
Started machines may have new IP addresses. You may need to re-run the `docker-machine env` command.
Setting environment variables for machine default...


                        ##         .
                  ## ## ##        ==
               ## ## ## ## ##    ===
           /"""""""""""""""""\___/ ===
      ~~~ {~~ ~~~~ ~~~ ~~~~ ~~~ ~ /  ===- ~~~
           \______ o           __/
             \    \         __/
              \____\_______/


exit status 255
docker is configured to use the default machine with IP
For help getting started, check out the docs at https://docs.docker.com

Unexpected error getting machine url: exit status 255
bash: chef: command not found
[~]: docker-machine active
error getting URL for host default: exit status 255
error getting URL for host default: exit status 255
error determining if host is active for host default: exit status 255
Error getting active host: Active host not found
[~]: docker-machine ls
error getting URL for host default: exit status 255
error getting URL for host default: exit status 255
error determining if host is active for host default: exit status 255
NAME      ACTIVE   DRIVER       STATE     URL   SWARM
default            virtualbox   Running

**Comment by chrisleck** [comment]
Also seeing this

**Comment by miguelqvd** [comment]
I've found the issue!

you just need to do:
chmod 600 id_rsa

where id_rsa is the private key for your specific virtual machine

**Comment by LongYC** [comment]
> Hm, odd. Maybe we should dial 127.0.0.1 directly, although I don't know how common it is to lack the localhost entry in a hosts file.
I had an extra name, e.g. `127.0.0.1 localhost myextraname` which gives me this issue, having exactly `127.0.0.1 localhost` seems to solve the issue although I don't really understand why.

**Comment by miguelqvd** [comment]
Sorry I didn't explain why **chmod 600 ~/.docker/machine/machines/default/id_rsa** fixed the issue for me.

If you execute docker-machine using --debug you will see that it calls ssh internally. If you copy the whole ssh command and add -v for verbose you will see that ssh warns you about low security in ~/.docker/machine/machines/default/id_rsa because it should be only rw for the user owner of the file. I guess that this "extra" warning doesn't is not properly parsed by docker-machine and it causes the issue:

error getting URL for host dbandredis: exit status 255                                                
error getting URL for host dbandredis: exit status 255                                                
error determining if host is active for host dbandredis: exit status 255  

In my case that was the cause

**Comment by chrisleck** [comment]
That didn't work for me, though your pointers helped me dig in.  Thanks!

In my case, the private key I had did not match the key in the VM.  Looks like there's a race somewhere with key generation/propagation.

**Comment by rygood** [comment]
In order to correct this problem. I had to:
- ensure my etc/hosts had a 127.0.0.1 localhost entry
- open Virtualbox and shutdown then remove my VM, including all files
- run docker-machine rm dev & docker-machine rm default
- close my terminal (cmd+Q)
- then run the Docker Quickstart Terminal (using DockerToolbox-1.8.3)

**Comment by JoeCoATL** [comment]
Yes, yours was the right answer @rygood . Worked for me.

**Comment by sidlinux22** [comment]
@rygood  +1 .Worked for me.

**Comment by ragavendra** [comment]
I had corrupt ~/.ssh/config . Once I corrected it, I was able to create machine like before. One way to check this is trying to ssh to some other server and see if it works to make sure the docker-machine isn't failing due to ssh.

**Comment by nathanleclaire** [comment]
This issue is very long and contains a lot of digressions.  If someone continues to encounter similar ones please open a new one at https://github.com/docker/machine/issues/new with detailed information including:

- Which OS you are on
- Anything atypical in networking configuration (VPN, proxy, SSH configuration settings, etc.),
- Output of the misbehaving commands with the `--debug` flag
- the VirtualBox logs from `~/.docker/machine/machines/name/name`.  

Thanks!

- N

**Comment by skji** [comment]
Thank u, @rygood. However, I commented the localhost settings, then it worked.
