### ISSUE TITLE
docker-machine on Windows / msysgit bash cannot generate env keys (v1.3)

### ISSUE THREAD

**Issue by jstclair** [docker/machine#1441]
Tried the normal `eval "$(docker-machine env dev)"`, but that resulted in an error that I should pass `--shell` with either `cmd` or `powershell`. 

I tried to pass `bash` (and `powershell`), but both attempts hung. I did get the output when I passed `cmd` and could manually set the values (via `export`).

**Comment by jstclair** [comment]
Sorry, it worked when I used `--shell sh` -- d'oh!
But you might want to tweak the message (as long as msysgit is still the recommended way to run docker-machine)

**Comment by Oliboy50** [comment]
I'm using `msysgit` and `--shell cmd` just work fine for me.

**Comment by yeyan** [comment]
I can't get it work on windows as well.  I have tried with and without --shell
```
MINGW64 ~
$ VBoxmanage -v
4.3.28r100309

MINGW64 ~
$ docker-machine -v
<msys-home>\msys64\usr\bin\docker-machine version 0.3.0 (0a251fe)

MINGW64 ~
$ docker-machine env dev
On Windows, please specify either 'cmd' or 'powershell' with the --shell flag.


Error: Unknown shell

MINGW64 ~
$ docker-machine env dev --shell cmd
open <user-home>\.docker\machine\machines\dev\ca.pem: The system cannot find the file specified.

MINGW64 ~
$ docker-machine env dev --shell powershell
open <user-home>\.docker\machine\machines\dev\ca.pem: The system cannot find the file specified.

```

**Comment by nathanleclaire** [comment]
I could have sworn that this worked with msysgit, but maybe we overlooked it.

**Comment by nathanleclaire** [comment]
cc @ahmetalpbalkan please try this out when you get a chance.

**Comment by ahmetalpbalkan** [comment]
I don't have a windows machine with me atm. Can you please read the code if the code is checking for $SHELL first and then `runtime.GOOS=="windows"` @nathanleclaire?

**Comment by ahmetalpbalkan** [comment]
... it doesn't: https://github.com/docker/machine/blame/6d26992101db6bc10872d75c72239ca88290d5e7/commands/commands.go#L654-L672

If there's $SHELL present (even though it's windows) it should be used as computing the return value. After that the `if runtime.GOOS == "windows" ...` check should happen.

**Comment by nathanleclaire** [comment]
Hm, I thought msysgit set `SHELL` as `cygwin`.  I remember talking to @ehazlett about this.

**Comment by ahmetalpbalkan** [comment]
I don't know why there's a `os.Getenv("TERM") != "cygwin"` case in the `if GOOS==windows` stmt I linked above...

It should be like:

```
if os.Getenv("SHELL") != "" {
  return filepath.Base(os.Getenv("SHELL")) // even on windows
}

if runtime.GOOS=="windows" {
   // fail b/c --shell not specified
}

**Comment by jstclair** [comment]
@yeyan Note I did get it to work with `--shell sh`

**Comment by jessy1092** [comment]
+1 on Windows7 with Mintty

The `Docker Quickstart Terminal` run the `start.sh` but the script is `eval "$($DOCKER_MACHINE env $VM)"`

I should modify into `eval "$($DOCKER_MACHINE env $VM --shell sh)"` to workaround.

Error:
![ps0014](https://cloud.githubusercontent.com/assets/4408071/9439530/86a9d1fa-4a9a-11e5-88d4-e4aedecb1439.jpg)

Relative https://github.com/docker/toolbox/issues/95
