### ISSUE TITLE
Digital Ocean Driver creates a new ssh key everytime.

### ISSUE THREAD

**Issue by usmanismail** [docker/machine#1445]
Currently there is no way to tell the digital ocean driver use a preexisting ssh key. This leads to a lot of cruft with new keys for every instance launch

**Comment by nathanleclaire** [comment]
Yeah I would be OK with adding this.

**Comment by usmanismail** [comment]
@nathanleclaire Cool, is there an ETA for when you can review the PR.

**Comment by michaelkrog** [comment]
I am having issues using this feature.

I create a machine like this:
```bash
docker-machine --debug create --driver digitalocean --digitalocean-access-token xxxxx --digitalocean-size 1gb --digitalocean-region ams2 --digitalocean-image 2321312 --digitalocean-ssh-user devops --digitalocean-ssh-key-fingerprint "04:1e:b1:c4:96:40:14:26:cf:cb:13:df:68:f2:af:13" docker-test
```

It creates the machine, but fails when it comes to establishing the SSH connection. Full debug output:

> Docker Machine Version:  0.7.0-rc1, build 0fb68ca
> Found binary path at /usr/local/bin/docker-machine
> Launching plugin server for driver digitalocean
> Plugin server listening at address 127.0.0.1:33228
> () Calling .GetVersion
> Using API Version  1
> () Calling .SetConfigRaw
> () Calling .GetMachineName
> (flag-lookup) Calling .GetMachineName
> (flag-lookup) Calling .DriverName
> (flag-lookup) Calling .GetCreateFlags
> Found binary path at /usr/local/bin/docker-machine
> Launching plugin server for driver digitalocean
> Plugin server listening at address 127.0.0.1:36842
> () Calling .GetVersion
> Using API Version  1
> () Calling .SetConfigRaw
> () Calling .GetMachineName
> (previsto-test) Calling .GetMachineName
> (previsto-test) Calling .DriverName
> (previsto-test) Calling .GetCreateFlags
> (previsto-test) Calling .SetConfigFromFlags
> Running pre-create checks...
> (previsto-test) Calling .PreCreateCheck
> (previsto-test) Calling .GetConfigRaw
> Creating machine...
> (previsto-test) Calling .Create
> (previsto-test) Creating SSH key...
> (previsto-test) Creating Digital Ocean droplet...
> (previsto-test) Waiting for IP address to be assigned to the Droplet...
> (previsto-test) Calling .GetConfigRaw
> (previsto-test) DBG | Created droplet ID 12642079, IP address 82.196.14.245
> (previsto-test) Calling .DriverName
> (previsto-test) Calling .DriverName
> Waiting for machine to be running, this may take a few minutes...
> (previsto-test) Calling .GetState
> (previsto-test) Calling .GetState
> (previsto-test) Calling .GetState
> (previsto-test) Calling .GetState
> (previsto-test) Calling .GetState
> (previsto-test) Calling .GetState
> (previsto-test) Calling .GetState
> (previsto-test) Calling .GetState
> (previsto-test) Calling .GetState
> (previsto-test) Calling .GetState
> (previsto-test) Calling .GetState
> (previsto-test) Calling .GetState
> Detecting operating system of created instance...
> Waiting for SSH to be available...
> Getting to WaitForSSH function...
> (previsto-test) Calling .GetSSHHostname
> (previsto-test) Calling .GetSSHPort
> (previsto-test) Calling .GetSSHKeyPath
> (previsto-test) Calling .GetSSHKeyPath
> (previsto-test) Calling .GetSSHUsername
> Using SSH client type: external
> &{[-o BatchMode=yes -o PasswordAuthentication=no -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=quiet -o ConnectionAttempts=3 -o ConnectTimeout=10 -o ControlMaster=no -o ControlPath=none devops@82.196.14.245 -o IdentitiesOnly=yes -i /var/lib/jenkins/.docker/machine/machines/docker-test/id_rsa -p 22] /usr/bin/ssh <nil>}
> About to run SSH command:
> exit 0
> SSH cmd err, output: exit status 255: Warning: Identity file /var/lib/jenkins/.docker/machine/machines/docker-test/id_rsa not accessible: No such file or directory.
> 
> Error getting ssh command 'exit 0' : Something went wrong running an SSH command!
> command : exit 0
> err     : exit status 255
> output  : Warning: Identity file /var/lib/jenkins/.docker/machine/machines/docker-test/id_rsa not accessible: No such file or directory.
>
