### ISSUE TITLE
docker-machine fails with digital ocean provider

### ISSUE THREAD

**Issue by mklatsky** [docker/machine#1447]
When running the following command (from https://github.com/docker/docker/blob/master/experimental/compose_swarm_networking.md):

**docker-machine --debug create -d digitalocean --digitalocean-image="ubuntu-14-10-x64" --engine-install-url="https://experimental.docker.com" --engine-opt="default-network=overlay:multihost" --engine-opt="kv-store=consul:$(docker-machine ip consul):8500" --engine-label="com.docker.network.driver.overlay.bind_interface=eth0" swarm-0**

The system is launched, but ends in the following error:

Daemon not responding yet: dial tcp 45.55.89.22:2376: connection refused
Error creating machine: Maximum number of retries (60) exceeded
You will want to check the provider to make sure the machine and associated resources were properly removed.

When I login to the new server via 'docker-machine ssh swarm-0' I find that docker has not started, with
an error stating that the daemon is spawning too fast.

If change the **--digitalocean-image** to 'ubuntu-15-04-x64', the same message regarding the daemon not responding is received, but in this case, docker is actually running on the new server.

**Comment by kitotik** [comment]
I am seeing the same results on:

Docker version 1.8.0-dev, build 71f8ca3, experimental
docker-machine version 0.4.0-dev (HEAD)
docker-compose version: 1.4.0dev

**Comment by dgageot** [comment]
Hi @mklatsky, have you tried docker-machine 0.5.0rc4? Can you tell us if it fixes the issue? Otherwise, please gist the output of your command.

**Comment by hcguersoy** [comment]
Hi,

I've observed the same problems with the Ubuntu images.
Switching to latest Debian (Jessie) solved this for me on Digital Ocean.
The reason is that in 14.04.3 the kernel is too old and the network driver runs into an error then it tries to set up the vxlan. You can observe this then you do the steps manually in Ubuntu.

**Comment by dgageot** [comment]
@mklatsky I'm going to close this issue. Ubuntu 14 does not support overlay network. You should create the machine with a Debian Jessie or Ubuntu 15.
Default images will soon be updated in as many drivers as possible. See https://github.com/docker/machine/issues/2361
