### ISSUE TITLE
Add support for VMWare AppCatalyst

### ISSUE THREAD

**Issue by cwandrews** [docker/machine#1452]
Add a driver type for [VMWare AppCatalyst](https://communities.vmware.com/community/vmtn/devops/vmware-appcatalyst). Not sure what this effort would look like, but I just tried AppCatalyst out and I think it is a good candidate for having a docker-machine driver.

**Comment by StefanScherer** [comment]
Have a look at #1401, it is on its way.

**Comment by nathanleclaire** [comment]
Since I'm going to treat the PR as the "proposal" for including that driver, I'm going to close this lest I forget.  Thanks @cwandrews @StefanScherer
