### ISSUE TITLE
Sporadically stoping with Processing signal 'terminated'

### ISSUE THREAD

**Issue by peter-leonov** [docker/machine#1458]
No matter what I do, after a few hours a find docker daemon stopped with all the containers. At times, the daemon is up but few of the `--restart=always` containers I find stopped with exit status 128.

All the containers and the app itself is just a dockerized version of an app running for a year on Ubuntu 14.04.

The box is a fresh DigitalOcean droplet created with:
```
docker-machine create --driver=digitalocean --digitalocean-size=2gb  --digitalocean-region=ams3 --digitalocean-backups
```
Then I enabled swap with:
```
touch /var/swap.img
chmod 600 /var/swap.img
dd if=/dev/zero of=/var/swap.img bs=1MB count=4000
mkswap /var/swap.img
swapon /var/swap.img
echo "/var/swap.img    none    swap    sw    0    0" >>/etc/fstab
```
as DO recommends in [the tutorial](https://www.digitalocean.com/community/tutorials/how-to-configure-virtual-memory-swap-file-on-a-vps). Disabling swap didn't help.

All the rest setup took place through docker or docker-machine CLI.

[docker-machine ssh food 'cat /var/log/upstart/docker.log'](https://gist.github.com/kung-fu-tzu/073b161622e539c62956)

### $ docker-machine --version
```
docker-machine version 0.3.0 (HEAD)
```

### docker version
```
Client version: 1.7.0
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 0baf609
OS/Arch (client): linux/amd64
Server version: 1.7.0
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 0baf609
OS/Arch (server): linux/amd64
```

### docker info
```
Containers: 6
Images: 96
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 108
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.13.0-52-generic
Operating System: Ubuntu 14.04.2 LTS
CPUs: 2
Total Memory: 1.955 GiB
Name: food
ID: R4NP:MRHJ:WC7A:ZICR:6VLW:UQXS:I27Z:AJL5:BXKV:4PHY:X4AL:H5U6
WARNING: No swap limit support
Labels:
 provider=digitalocean
```

### uname -a
```
Linux food 3.13.0-52-generic #85-Ubuntu SMP Wed Apr 29 16:44:17 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by nathanleclaire** [comment]
Hmmmm tricky tricky.  Looks like a Docker daemon issue.

**Comment by kung-fu-tzu** [comment]
Maybe, but the exactly same setup works fine on VirtualBox machine provisioned the same way (RAM, CPU count, drive size) with `docker-machine` and `docker-compose`.

**Comment by dgageot** [comment]
Hi @peter-leonov has you experienced similar issues with a more recent Docker Machine?

**Comment by peter-leonov** [comment]
Hi @dgageot, I really do not remember how this issue has gone. Additional memory? Re-provisioning till it worked? Daemon update? Can't remember.

These days we just use the machines provided last summer without any issues. Docker daemon is a pretty stable piece of software, I should add :)

**Comment by dgageot** [comment]
@peter-edge Do you think we can close the issue?

**Comment by peter-edge** [comment]
@peter-leonov (not me :) )

**Comment by dgageot** [comment]
Sorry wrong Peter!!

**Comment by peter-leonov** [comment]
Sure you can. I guess.

**Comment by naphthalene** [comment]
I am having this issue sadly. I've tried Ubuntu 15.10 and Ubuntu 14.04 LTS.
More info:

```
<scrubbed>:28:32 systemd[1]: Starting Cleanup of Temporary Directories...
<scrubbed>:28:32 systemd-tmpfiles[23770]: [/usr/lib/tmpfiles.d/var.conf:14] Duplicate line for path "/var/log", ignoring.
<scrubbed>:28:32 systemd[1]: Started Cleanup of Temporary Directories.
<scrubbed>:33:56 systemd[1]: Reloading.
<scrubbed>:34:32 systemd[1]: message repeated 7 times: [ Reloading.]
<scrubbed>:34:32 docker[12334]: time="<scrubbed>:34:32.202986403Z" level=info msg="Processing signal 'terminated'"
<scrubbed>:34:32 systemd[1]: Stopping Docker Application Container Engine...
```

```
Server Version: 1.10.0
Storage Driver: devicemapper
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: ext4
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 11.73 GB
 Data Space Total: 107.4 GB
 Data Space Available: 95.65 GB
 Metadata Space Used: 13.56 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.134 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Library Version: 1.02.99 (2015-06-20)
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 4.2.0-34-generic
Operating System: Ubuntu 15.10
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 14.69 GiB
```

**Comment by sqybi** [comment]
@naphthalene I got a similar issue recently and found this ticket by Google. I am using Ubuntu 16.04.
Fortunately, I found some evidence that `dpkg.log` said it updated `containerd` at the same time as the log `Processing signal 'terminated'`.
Hope it could help you (although it was more than 4 year ago :P) or other guys who find this page.

**Comment by dhruvx24** [comment]
> @naphthalene I got a similar issue recently and found this ticket by Google. I am using Ubuntu 16.04.
> Fortunately, I found some evidence that `dpkg.log` said it updated `containerd` at the same time as the log `Processing signal 'terminated'`.
> Hope it could help you (although it was more than 4 year ago :P) or other guys who find this page.

Same here.. just found out that all my containers were stopped automatically when Azure VM updated containerd automatically

![image](https://user-images.githubusercontent.com/3754225/100842575-0dbf0900-349f-11eb-8ea6-8390e93794d0.png)

This same time my docker got killed and didnt restart until manually started again. 
To Solve:

Edit /etc/apt/apt.conf.d/20auto-upgrades to disable automatic updates from the command line:
`$ sudo nano /etc/apt/apt.conf.d/20auto-upgrades`
Once you have the file opened, switch off the Update-Package-Lists directive from 1 to 0 as shown below on Line 1:

APT::Periodic::Update-Package-Lists "0";
APT::Periodic::Unattended-Upgrade "1";
