### ISSUE TITLE
Better UX for `docker-machine create -h`

### ISSUE THREAD

**Issue by ahmetalpbalkan** [docker/machine#1469]
Currently `docker-machine create -h` prints hundreds of lines (probably more than 50 cli options) for all machine drivers.

If we can have something like:

    docker-machine create -d virtualbox -h

that only shows me virtualbox, that'd be very tractable.

**Comment by robertjustjones** [comment]
Try this
```
docker-machine create -d virtualbox
```

**Comment by ahmetalpbalkan** [comment]
@robertjustjones that does the job (just prints vbox arguments) but I think adding `-h` to this command should not print the entire `create` subcmd usage. It's confusing.

**Comment by nathanleclaire** [comment]
Argh, I'm afraid that might be a `codegangsta/cli` thing which we have to workaround.

**Comment by dgageot** [comment]
Closing. This is fixed in 0.5.0
