### ISSUE TITLE
docker-machine status command

### ISSUE THREAD

**Issue by nathanleclaire** [docker/machine#1471]
To easily get the status of one particular machine, we should support:

```console
$ docker-machine status dev
Running
```

That would provide issues like https://github.com/docker/machine/issues/1042 what they are after, and prevent awk hacking of the `ls` output, etc.

**Comment by hairyhenderson** [comment]
:+1:

**Comment by sergiobuj** [comment]
I was just looking for a way to easily get the status of a machine. I can help with this.

**Comment by socketwiz** [comment]
boot2docker status command used to set $? to 1 when the status was stopped in addition to printing out stopped.  docker-machine status seems to only print out stopped.  Would it be possible to have it also set $? accordingly? It would make it easier for scripting.

**Comment by hairyhenderson** [comment]
@socketwiz - If you're using it in scripts you could do something like:

```sh
if [ "$(docker-machine status foo)" == "Stopped" ]; then
  docker-machine start foo
fi
```

No _real_ need for `$?` in that sort of situation. IMO, a non-zero exit code means that something went wrong with the command's execution. A machine being stopped isn't an error state - it's perfectly reasonable to expect a machine to be stopped sometimes...

**Comment by nathanleclaire** [comment]
I'd say I agree with @hairyhenderson on this one.  If the program is successfully reporting a "stopped" state, and given the ability to get the state through other means, I'd say returning 0 is reasonable.

**Comment by socketwiz** [comment]
Thanks guys, that works for me :)
