### ISSUE TITLE
Add support for password-protected SSH keys

### ISSUE THREAD

**Issue by nathanleclaire** [docker/machine#1473]
Right now Machine has no such support for this.  It would be great for security to enable SSH keys protected by passwords for the users who want it.

**Comment by hairyhenderson** [comment]
@nathanleclaire - #1299 is a partial solution to this issue, from what I can tell

**Comment by tpires** [comment]
I think this is a duplicated of #1357.

**Comment by dgageot** [comment]
Closing since it's solved with #1299
