### ISSUE TITLE
error creating digitalocean machine when on ko_KR.UTF-8 locale

### ISSUE THREAD

**Issue by difro** [docker/machine#1481]
I was trying to create digitalocean machine on a ubuntu machine which has ko_KR.UTF-8 locale.

Following error occurred.
```
Creating CA: /home/jihoonc/.docker/machine/certs/ca.pem
Creating client certificate: /home/jihoonc/.docker/machine/certs/cert.pem
Creating SSH key...
Creating Digital Ocean droplet...
Error creating machine: Error parsing /etc/os-release file: Expected bash: warning: setlocale: LC_ALL: cannot change locale (ko_KR.UTF-8) to split by '=' char into two strings, instead got 1 strings
You will want to check the provider to make sure the machine and associated resources were properly removed
```

**Comment by difro** [comment]
same error happens on google-cloud driver.
```
...
Saving token in /home/jihoonc/.docker/machine/machines/gobox/gce_token
Creating host...
Generating SSH Key
Creating instance.
Creating firewall rule.
Waiting for Instance...
Uploading SSH Key
Waiting for SSH Key
Error creating machine: Error parsing /etc/os-release file: Expected bash: warning: setlocale: LC_ALL: cannot change locale (ko_KR.UTF-8) to split by '=' char into two strings, instead got 1 strings
```

**Comment by difro** [comment]
prepending ```LC_ALL=C``` seems to fix the issue.
```LC_ALL=C docker-machine create --driver digitalocean ....```

I believe the culprit is this line in my host's ```/etc/ssh/ssh_config```.
```    SendEnv LANG LC_* ```

**Comment by pandrew** [comment]
yeah, got this issue on latest 0.4.0-rc1 on osx. Commented the line in /etc/ssh_config and the issue disappeared.

**Comment by legal90** [comment]
@tianon Is not it an issue of boot2docker NG? 
I got the similar warning after `docker-machine ssh <vm_name>` on OS X host:
```
$ docker-machine ssh b2d-prl-test

Docker version 1.7.1, build 786b29d

Last login: Wed Jul 29 16:13:32 2015 from 10.211.55.2
-bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
-bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
-bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)


docker@docker:~$ locale
locale: Cannot set LC_CTYPE to default locale: No such file or directory
locale: Cannot set LC_MESSAGES to default locale: No such file or directory
locale: Cannot set LC_ALL to default locale: No such file or directory
LANG=C.UTF-8
LANGUAGE=
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=en_US.UTF-8
```

**Comment by tianon** [comment]
Is `LC_ALL` set on your host?  (`env | grep ^LC_`)

**Comment by legal90** [comment]
Yes, it is:
```
$ env | grep ^LC_
LC_ALL=en_US.UTF-8
LC_CTYPE=UTF-8

$ env | grep ^LANG
LANG=en_US.UTF-8
```
I also have this option in `/etc/ssh_config` (This is a default setting on OS X hosts):
```
 Host *
   SendEnv LANG LC_*
```

**Comment by tianon** [comment]
Was that set by your OS automatically, or is that something you configured?  Setting `LC_ALL` anywhere but in scripts is very strongly discouraged because it forcefully overrides ALL the locale-related environment variables by design, so I'm really hesitant to consider "fixing" this at the boot2docker OS level just by setting `LC_ALL` instead of `LANG`.  The behavior and warnings we're seeing here are exactly how these things are supposed to interact if used together in this way.

**Comment by legal90** [comment]
Ah, sorry, that was my bad. I had this in my `~/.bash_profile`, which **is wrong**:
```
export LANG="en_US.UTF-8"
export LC_ALL="en_US.UTF-8"
```

I found the here: https://gist.github.com/eriksencosta/3850157#gistcomment-1316962
`SendEnv` in `/etc/ssh_config` should be kept unchanged, but lines above should be replaced with:
```
export LANG="en_US"
export LC_ALL=$LANG.UTF-8
```
cc:\ @difro, @pandrew, @moxiegirl 

P.s. @tianon Sorry for disturbing. No need to change on the boot2docker OS side.

**Comment by tianon** [comment]
No worries!  Glad we figured out the issue. :+1:
