### ISSUE TITLE
Is there a way to create a machine but NOT start it?

### ISSUE THREAD

**Issue by fgimian** [docker/machine#1492]
Hey there guys, great work on docker machine :smile: 

Forgive me if this is totally obvious and I've missed it, but is there any way at all to create a machine but not start it automatically?

The reason I wish to do this is because I've automated the creation of my machine via Ansible but don't want the VM started, just created for later use.

Thanks
Fotis

**Comment by ehazlett** [comment]
Hey thanks!  Right now machine requires the host to be running to provision.

**Comment by fgimian** [comment]
Aah, gotcha.  Thanks for the quick reply :smile:
