### ISSUE TITLE
machine是什么？它能为数据中心带来哪些便利

### ISSUE THREAD

**Issue by heidsoft** [docker/machine#1505]

**Comment by thaJeztah** [comment]
Using google translate;
> What machine is it? What it will bring convenience for the data center?

I think the best point to start is the documentation here; https://docs.docker.com/machine/

(please note that the GitHub issue tracker is for tracking bugs and feature requests, not for general questions)

**Comment by ehazlett** [comment]
@thaJeztah thx

@heidsoft as said, this is for tracking issues and feature requests.  you can find project information at the link above.

thanks!
