### ISSUE TITLE
Heroku driver

### ISSUE THREAD

**Issue by jingweno** [docker/machine#1514]
Would it make sense to add a Heroku driver as part of `docker-machine`? I could contribute if it's desirable :smile_cat:

**Comment by hairyhenderson** [comment]
@jingweno - does Heroku expose a Docker engine API? I wasn't aware of this :)

**Comment by jingweno** [comment]
Does `docker-machine` require a Docker engine running? I'm wondering we could bridge the command to the [Heroku platform API](https://devcenter.heroku.com/categories/platform-api)?

**Comment by nathanleclaire** [comment]
As far as I know Heroku is just a PaaS provider and does not expose the underlying machine layer, which is what Docker Machine is interested in, so I'm not sure how this could work.
