### ISSUE TITLE
Fail on creating dev virtualbox machine on ubuntu

### ISSUE THREAD

**Issue by gi4nks** [docker/machine#1524]
Hi all,
I am trying to create a new dev machine in ubuntu but i am getting an error.

Environment
Ubuntu: 15.04
VirtualBox:  Oracle VM VirtualBox Command Line Management Interface Version 5.0.0

Running command:
```$ docker-machine -D create -d virtualbox dev```

I am getting following error:

```
...
                            [--videocapmaxsize <MB>]
                            [--videocapopts <key=value> [<key=value> ...]]
                            [--defaultfrontend default|<name>]

VBoxManage: error: Unknown option: --synthcpu

Error creating machine: exit status 1
You will want to check the provider to make sure the machine and associated resources were properly removed.
```

Thanks

**Comment by linhmtran168** [comment]
I encountered the same error with VirtualBox 5.0.0. Switched back to VirtualBox 4.3.0 and problem disappeared.

**Comment by nathanleclaire** [comment]
This should be fixed in master; please try the builds at https://docker-machine-builds.evanhazlett.com/latest/ and let us know if you have any more issues.
