### ISSUE TITLE
"/etc/init.d/docker restart" fails to start service

### ISSUE THREAD

**Issue by jamshid** [docker/machine#1529]
Just did a `brew update && brew upgrade` to docker 1.7.1 / docker-machine 0.3.0, created a machine with `docker-machine create --driver virtualbox test`. I then `docker-machine ssh test` and try to `restart` the docker service but it outputs message about needing certs and the `docker` client no longer works ("Cannot connect to the Docker daemon").

I can restart fine with `docker-machine restart test`, but shouldn't restarting the docker service work too?

```
Boot2Docker version 1.7.1, build master : c202798 - Wed Jul 15 00:16:02 UTC 2015
Docker version 1.7.1, build 786b29d
docker@test:~$ docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
docker@test:~$ sudo /etc/init.d/docker restart
hostname: test: Unknown host      <=== don't always get this line
Need TLS certs for test,,10.0.2.15,192.168.99.102
-------------------
docker@test:~$ docker ps
Cannot connect to the Docker daemon. Is 'docker -d' running on this host?
```
Also, can't seem to stop the service:
```
docker@test:~$ sudo /etc/init.d/docker stop
cat: can't open '/var/run/docker.pid': No such file or directory
sh: you need to specify whom to kill
```

**Comment by ehazlett** [comment]
Can you post the version of machine you are using?  (`docker-machine -v`)

**Comment by nathanleclaire** [comment]
Hi @jamshid, also please try : `docker-machine upgrade test`

**Comment by nathanleclaire** [comment]
Ah, also, please post the output of:

```console
$ tail /var/log/docker.log
```

So we can see why the daemon is failing.

As for `sudo /etc/init.d/docker stop` not working, the daemon has to be running for you to be able to stop it ;D

**Comment by jamshid** [comment]
I'm running the latest docker-machine from homebrew.sh:
```
$ docker-machine -v
docker-machine version 0.3.0 (HEAD)
```
I'll try a recent docker-machine RC mentioned in another issue.

Sorry @nathanleclaire I should have mentioned that I still see docker process running at the time `/etc/init.d/docker stop` fails. It is the same pid as before restart, so `/etc/init.d/docker restart` is failing to stop the service.

```
$ ps aux  | grep docker
root       993  1.1  2.0 191876 20440 ?        Sl   05:38   0:00 /usr/local/bin/docker -d -D -g /var/lib/docker -H unix:// -H tcp://0.0.0.0:2376 --label provider=virtualbox --tlsverify --tlscacert=/var/lib/boot2docker/ca.pem --tlscert=/var/lib/boot2docker/server.pem --tlskey=/var/lib/boot2docker/server-key.pem -s aufs
```

Logs confirm that restart is failing because the original docker service is listening on port 2376:

```
time="2015-07-19T05:34:40.393436170Z" level=debug msg="Registering OPTIONS, " 
time="2015-07-19T05:34:40.394476588Z" level=debug msg="[graphdriver] trying provided driver \"aufs\"" 
time="2015-07-19T05:34:40.396035940Z" level=debug msg="docker group found. gid: 100" 
time="2015-07-19T05:34:40.396036023Z" level=info msg="Listening for HTTP on unix (/var/run/docker.sock)" 
time="2015-07-19T05:34:40.396036051Z" level=error msg="ServeAPI error: listen tcp 0.0.0.0:2376: bind: address already in use" 
time="2015-07-19T05:34:40.399845272Z" level=debug msg="Using graph driver aufs" 
...
time="2015-07-19T05:34:40.434904748Z" level=info msg="Docker daemon" commit=786b29d execdriver=native-0.2 graphdriver=aufs version=1.7.1 
time="2015-07-19T05:34:40.434968779Z" level=debug msg="starting clean shutdown of all containers..." 
time="2015-07-19T05:34:40.435309172Z" level=debug msg="Clean shutdown succeded" 
time="2015-07-19T05:34:40.435336998Z" level=fatal msg="Shutting down due to ServeAPI error: listen tcp 0.0.0.0:2376: bind: address already in use" 
```

**Comment by nathanleclaire** [comment]
Ah, I've seen this issue before sporadically.  I usually just `sudo killall -9 docker` and then re-run the init script.  I'm not sure what Machine could do to help with this as it seems like a github.com/boot2docker/boot2docker issue.

**Comment by dgageot** [comment]
@jamshid this seems to impact a very old version of docker-machine. Can you try with the latest version and let us know if you still have the problem? Thanks a lot for your time.

**Comment by dgageot** [comment]
@jamshid I'm going to close this issue since it impacts a very old version. Thank you for taking the time to fill an issue and of course fill free to reopen this ticket or fill a new one if the problem still occurs
