### ISSUE TITLE
FYI 1.7.1 seems buggy with old machines

### ISSUE THREAD

**Issue by jamshid** [docker/machine#1530]
I just had a heck of a time getting my 1.7.1 upgraded machine working (originally created under docker 1.6 or probably earlier). The `docker` client when ssh'd into the machine wasn't working, complained `Cannot connect to the Docker daemon. Is 'docker -d' running on this host?`. I could see the service running as:
```root       834  0.5  0.8 1779296 42768 ?       Sl   16:13   0:16 /usr/local/bin/docker -d -D -g /var/lib/docker -H unix:// -H tcp://0.0.0.0:2375 --dns 172.17.42.1 --dns-search=. --tlsverify --tlscacert=/var/lib/boot2docker/ca.pem --tlskey=/var/lib/boot2docker/server-key.pem --tlscert=/var/lib/boot2docker/server.pem --label=provider=virtualbox -H tcp://0.0.0.0:2376 --insecure-registry=http://192.168.99.100:5000```

I had this /var/lib/boot2docker/profile (last line is my only custom change afaik, I think I tried setting DOCKER_TLS=yes too):
```
EXTRA_ARGS='--tlsverify --tlscacert=/var/lib/boot2docker/ca.pem --tlskey=/var/lib/boot2docker/server-key.pem --tlscert=/var/lib/boot2docker/server.pem --label=provider=virtualbox -H tcp://0.0.0.0:2376'
CACERT=/var/lib/boot2docker/ca.pem
SERVERCERT=/var/lib/boot2docker/server-key.pem
SERVERKEY=/var/lib/boot2docker/server.pem
DOCKER_TLS=no
EXTRA_ARGS="--dns 172.17.42.1 --dns-search=. ${EXTRA_ARGS} --insecure-registry=http://192.168.99.100:5000"
```
Seems the paths for certs and the tls directory changed a lot in 1.7.1. Also, it's expecting tls/hostnames instead of etc/hostname. Maybe the docker startup script or machine upgrade tries to handle old settings, but I think there's some bugs there (of course, it could just be me).

Anyway, finally got things working by copying a newly created machine's /var/lib/boot2docker/profile and moving around cert files and editing tls/hostnames.

PS: I'm using docker-machine from brew:
```
$ docker-machine -v
docker-machine version 0.3.0 (HEAD)
$ ls -l /usr/local/bin/dock*
lrwxr-xr-x  1 jamshid  admin       33 Jul 15 11:30 /usr/local/bin/docker -> ../Cellar/docker/1.7.1/bin/docker
-rwxr-xr-x  1 jamshid  wheel  5123521 Jul  6 08:01 /usr/local/bin/docker-compose
lrwxr-xr-x  1 jamshid  admin       49 Jun 20 19:01 /usr/local/bin/docker-machine -> ../Cellar/docker-machine/0.3.0/bin/docker-machine
```
which is hopefully the same build as the official download which reports as `docker-machine version 0.3.0 (0a251fe)`.

**Comment by ehazlett** [comment]
It's hard to say which version the homebrew is using.  Would you mind trying v0.3.1-rc1 with the latest b2d?  You can get it https://github.com/docker/machine/releases/tag/v0.3.1-rc1

**Comment by dgageot** [comment]
Closing this since it's related to a "very old" version
