### ISSUE TITLE
failed to start boot2docker

### ISSUE THREAD

**Issue by kl2848** [docker/machine#1531]
I have tried to download boot2docker v1.7.1. I stry to start boot2docker and i get an error that I failed to connect with 192.30.252.136. How are the proxy connections configured for IE. 

Thanks

**Comment by ehazlett** [comment]
Can you provide some more detail on the error?  Are you using machine upgrade or just trying to download from your browser?

**Comment by nathanleclaire** [comment]
Hi @kl2848, please file issues with boot2docker-cli over at https://github.com/boot2docker/boot2docker-cli .   Thanks!

**Comment by kl2848** [comment]
So the boot2docker folks sent me to you. Can you answer whether or not I need to install the docker machine or just the boot2docker will be fine. Thanks

**Comment by nathanleclaire** [comment]
@kl2848 boot2docker-cli support will continue through the next release in about 3-4 weeks, at which point users of boot2docker-cli will be expected to switch to docker-machine.
