### ISSUE TITLE
VBoxManage.exe: error: Unknown option: --synthcpu

### ISSUE THREAD

**Issue by nsandalov** [docker/machine#1534]
Hello,

I am on Win8.1 with VirtualBox 5.0 and Docker 1.7.1 trying to create VM with:
 docker-machine -D create -d virtualbox dev

output is:

VBoxManage.exe: error: Unknown option: --synthcpu

Error creating machine: exit status 1
You will want to check the provider to make sure the machine and associated resources were properly removed.

There are no logs in the .docker\machine\machines\dev\dev and around.
VT-x is enabled in Bios and for created dev VM in the VirtualBox. 

Could you please advice?

**Comment by ehazlett** [comment]
Thanks for submitting.  This has been fixed in master and is available in the [v0.3.1-rc1](https://github.com/docker/machine/releases/tag/v0.3.1-rc1) release.
