### ISSUE TITLE
Support for vagrant boxes

### ISSUE THREAD

**Issue by chantra** [docker/machine#1538]
`docker-machine` currently come with a virtualbox and vmware driver. As far as I can see, those are mainly focused at provisioning boot2docker.

It would be handy to be able to provision any vagrant boxes, this would allow to provision from vagrant boxes like the ones created by chef's bento project: https://atlas.hashicorp.com/chef making it easier to test/create provisioners.

It looks like the virtualbox and vmwarefusion drivers could be modified to handle those boxes.

@nathanleclaire @ehazlett any thoughts?

**Comment by r4j4h** [comment]
I think this overlaps with #1541

**Comment by nathanleclaire** [comment]
Yes, @chantra I'm going to consolidate this one into #1541 - please post there with any questions or discussion.  A Vagrant box is mostly a VMDK with some metadata IIRC, so maybe we can keep that in mind in designing.
