### ISSUE TITLE
[VirtualBox] Machine (or VirtualBox) somehow deactivated host DNS resolution

### ISSUE THREAD

**Issue by Oliboy50** [docker/machine#1540]
I don't even know how this happened in my case, all I know is that my `dev` virtualbox machine (created 3 or 4 months ago) suddently stopped to use my host DNS...

So I ended having DNS issues in my containers... I don't know if this issue could happen to someone else but here is what I did to solve this particular problem:

```
VBoxManage modifyvm dev --natdnshostresolver1 on
```

BTW, I'm working on Windows 8.1

**Comment by pfultz2** [comment]
I see the same issue on the mac as well. Using `VBoxManage modifyvm dev --natdnshostresolver1 on` did fix it.

**Comment by Oliboy50** [comment]
Closing while it looks like a pretty random issue, and it seems that we have a workaround for Windows and OS X
