### ISSUE TITLE
Default AMI kernel needs to be upgraded to 3.15 or above

### ISSUE THREAD

**Issue by alvinr** [docker/machine#1542]
# Problem
When using the EC2 Driver, the AMI used to create the instance is based on a 3.13 kernel. However, a libnetworking issues means that (for now) 3.15 kernel is the minimum supported version, see

https://github.com/docker/libnetwork/issues/329

# Solution
Base the AMI that machine launches for EC2 on a 3.15 or greater kernel.

# Environment

```
$ uname -a
Linux swarm-1 3.13.0-57-generic #95-Ubuntu SMP Fri Jun 19 09:28:15 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

```
$ docker --version
Docker version 1.8.0-dev, build 8c7cd78, experimental
```

**Comment by nathanleclaire** [comment]
I wonder if there are any of the Canonical AMIs which do this, since I think that is what we are relying on today.

**Comment by ehazlett** [comment]
@alvinr also we use the LTS version for stability which defaults to 3.13 I believe.  FYI you can use custom AMIs with machine using the `--amazonec-ami` flag.

**Comment by alvinr** [comment]
saw the ```--amazonec2-ami`` flag and under desire to pick an LTS. Just a heads up that libnetwork may require a higher kernel version.

**Comment by schmunk42** [comment]
I am looking for an AMI which is compatible with `docker-machine`, AWS and has a `kernel >= 3.15`. I tried Ubuntu Ubuntu 15.04 (Vivid Vervet), from http://cloud-images.ubuntu.com/releases/15.04/release/ - but without success yet.

Does anyone know about a working AMI for trying out the very latest docker-compose 1.5 features (--x-networking)?

**Comment by nathanleclaire** [comment]
We just merged support for Ubuntu >=15.04 (first systemd version), and I've filed https://github.com/docker/machine/issues/2361 to bump our default AMIs / cloud images.

**Comment by schmunk42** [comment]
Cool, looking forward to the new AMIs. 

If some needs to try a kernel upgrade now...

    docker-machine ssh node1 \
      "sudo DEBIAN_FRONTEND=noninteractive apt-get -o Dpkg::Options::="--force-confnew" --force-yes -fuy install linux-generic-lts-vivid"
    docker-machine restart node1
    docker-machine regenerate-certs node1

Note: Use at your own risk.

**Comment by BretFisher** [comment]
So as a sort of compatibility matrix of having 3.16+ kernel **and** AMI's that are a `docker-machine` supported distro, I pulled out these latest hvm ebs AMI's, but all are Community AMI's at this point:

- **debian 8.1** ami-8b9a63e0 (debian-jessie-amd64-hvm-2015-06-07-12-27-ebs-39d3917e-ff4e-4597-848e-4d0fdf8529e6-ami-116d857a.2)
- **Ubuntu 15.10** ami-305d115a (ubuntu/images/hvm-ssd/ubuntu-wily-15.10-amd64-server-20151203)
- **Fedora-Cloud-Base-23** ami-dceaa2b6 (20151212.x86_64-us-east-1-HVM-gp2-0) 
- **RancherOS v0.4.1** ami-11740e7b (rancheros-v0.4.1-hvm-0)

Sadly, from what I can tell, everything I checked in AWS GUI for Quick Start or AMI Marketplace (free) are missing one of those two requirements.

**Comment by thaJeztah** [comment]
Note that there's now an open pull request in docker that adds support for overlay networks on kernel 3.10 and above; https://github.com/docker/docker/pull/18775, this should probably land in docker 1.10

**Comment by nathanleclaire** [comment]
I think also AMI is bumped to Ubuntu 15.10 now.

**Comment by jeanlaurent** [comment]
AMI have been updated to 15.10 this leads to 
```
$ uname -a
Linux aws 4.2.0-18-generic #22-Ubuntu SMP Fri Nov 6 18:25:50 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

Closing this, re-open if I missed something.
