### ISSUE TITLE
Error response from daemon: client and server don't have same version (client : 1.19, server: 1.18)

### ISSUE THREAD

**Issue by CristianCantoro** [docker/machine#1545]
Software versions:
* OS: Ubuntu 15.04 (3.19.0-22-generic #22-Ubuntu x86_64)
* Docker: Docker version 1.7.1, build 786b29d
* Machine: docker-machine version 0.3.0 (0a251fe)
* VirtualBox: Oracle VM VirtualBox Manager 4.3.28 r100309

Steps to reproduce:
1. `docker-machine create -d virtualbox test `
2. `eval "$(docker-machine env test)"`
3. `docker ps`
```
Error response from daemon: client and server don't have same version (client : 1.19, server: 1.18)
```

The `Boot2Docker` version that gets installed in the virtual machine is:
```
Boot2Docker version 1.6.2, build master : 4534e65 - Wed May 13 21:24:28 UTC 2015
Docker version 1.6.2, build 7c8fca2
$ uname -a
Linux test 4.0.3-boot2docker #1 SMP Wed May 13 20:54:49 UTC 2015 x86_64 GNU/Linux
```

**Comment by windweller** [comment]
I have the same problem. It seems like Docker updated itself before all its components (Boot2Docker, Docker-machine) get a chance to upgrade.

**Comment by nathanleclaire** [comment]
Can you please try `docker-machine upgrade test` to see if it fixes your issue?

**Comment by CristianCantoro** [comment]
@nathanleclaire that fixed it!
```
$ docker-machine upgrade test
Stopping machine to do the upgrade...
Upgrading machine test...
Downloading https://github.com/boot2docker/boot2docker/releases/download/v1.7.1/boot2docker.iso to /home/cristian/.docker/machine/cache/boot2docker.iso...
Starting machine back up...
Starting VM...

$ docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
```
(I am quite sure I have searched/tried hot to upgrade the machine before posting this issue... but, well...)

**Comment by windweller** [comment]
Hmmm, I didn't get the same thing 
```
$ docker-machine upgrade test
FATA[0000] Host "test" does not exist
```

Do I need to create a docker-machine named `test` first and then upgrade it?? Does this mean I have to upgrade every single time???

**Comment by CristianCantoro** [comment]
@windweller, you should use your machine name in place of `test`. In my example above I used the name `test` so @nathanleclaire used that name in his answer.

**Comment by windweller** [comment]
Got that! Thank you!

**Comment by nathanleclaire** [comment]
Going to close this issue.  Glad that things worked out for you all!

**Comment by rgbkrk** [comment]
In case you want to not hot swap a docker machine, @smashwilson and I put together [Docker Version Manager](https://github.com/rgbkrk/dvm) to let you work between versions. It would be nice if docker machine's env also spat out the `DOCKER_VERSION` (as, e.g. `'1.8.2'`).
