### ISSUE TITLE
docker-machine cannot reach Azure China with Azure driver

### ISSUE THREAD

**Issue by NoamB** [docker/machine#1547]
docker-machine version 0.4.0-dev (2c36635)

I assume all docker-machine commands with Azure driver use the main Azure API.
However, there is a another Azure API, operated by a separate company in China, due to Chinese government regulations:

https://manage.windowsazure.cn

Trying to state "China East" as a region, and giving the Azure china subscription ID does not seem to work.

**Comment by NoamB** [comment]
Same for EC2 in China, see #1513

**Comment by ahmetalpbalkan** [comment]
@NoamB please see my comment at https://github.com/docker/machine/issues/2639#issuecomment-173083965 We're hoping to fix this soon.

**Comment by dgageot** [comment]
Closing. Duplicate of https://github.com/docker/machine/issues/2639
