### ISSUE TITLE
Cannot create VM in specific inventory folder using vmwarevsphere driver

### ISSUE THREAD

**Issue by doxxx** [docker/machine#1556]
The vSphere environment that I use is very locked down and my user only has permissions for creating VMs in a specific directory. However, it appears that there's no way to control what directory the vmwarevsphere driver uses. Judging from the error it's trying to create a directory with the same name as the docker machine I'm creating.

It would be useful if this worked like the Vagrant vsphere driver where I can specify the "vm_base_path" which is used in combination with the actual name of the VM to construct the path at which the VM is created.

**Comment by doxxx** [comment]
So this was apparently the datastore folder that it was trying to create, into which it uploads the ISO. I had no permissions to create folders in the datastore. I have subsequently been granted those permissions, so I am able to create the folder and upload the ISO.

I had thought it was the inventory folder under the datacenter, which it is not possible to specify either so my issue still stands.

**Comment by dakhbc** [comment]
You have create the VM, by default you will see it at the root folder. After the VM is created you can move it to any folder you want(in vphere) and then you only need to change the config.json for "MachineName": "folder/VM".

**Comment by doxxx** [comment]
@dakhbc, no it hasn't create the VM because *I don't have permissions for the folder in which it is trying to create the VM*.

**Comment by jonrsawyer** [comment]
Support for inventory folders would be useful for me too. There are policies around here about what folders my VMs need to reside in, otherwise they are at risk of deletion by the IT Powers That Be.  

Editing the config.json file works, but is a hack.

Could we get a VSPHERE_INVENTORY_FOLDER or VSPHERE_INVENTORY_PATH variable and corresponding command line parameter?

**Comment by mjiderhamn** [comment]
I'm running into this issue as well. During creating, I'm getting the exception below. After having been in contact with the vCenter admins it turned out VMs were in fact created in the root folder (not visible to me in the vSphere Client), but due to the exception below they were uninitialized (`Operating System not found`) and - I assume - unusable.

```
...
(name-of-new-vm) Uploading Boot2docker ISO ...
Error creating machine: Error in driver during machine creation: Panic in the driver: interface conversion: interface is nil, not types.ManagedObjectReference
goroutine 83 [running]:
runtime/debug.Stack(0x0, 0x0, 0x0)
        /usr/local/go/src/runtime/debug/stack.go:24 +0x87
github.com/docker/machine/libmachine/drivers/rpc.(*StandardStack).Stack(0x26e9198, 0x0, 0x0, 0x0)
        /go/src/github.com/docker/machine/libmachine/drivers/rpc/server_driver.go:23 +0x30
github.com/docker/machine/libmachine/drivers/rpc.trapPanic(0xc0826059f8)
        /go/src/github.com/docker/machine/libmachine/drivers/rpc/server_driver.go:129 +0x9d
panic(0x167cdc0, 0xc082624140)
        /usr/local/go/src/runtime/panic.go:426 +0x4f7
github.com/docker/machine/drivers/vmwarevsphere.(*Driver).Create(0xc082158380, 0x0, 0x0)
        /go/src/github.com/docker/machine/drivers/vmwarevsphere/vsphere.go:444 +0x10b8
github.com/docker/machine/libmachine/drivers/rpc.(*RPCServerDriver).Create(0xc0820b9c20, 0x26e9198, 0x26e9198, 0x0, 0x0)
        /go/src/github.com/docker/machine/libmachine/drivers/rpc/server_driver.go:140 +0x83
reflect.Value.call(0x14beac0, 0x1954bc8, 0x13, 0x1997a18, 0x4, 0xc082605ea8, 0x3, 0x3, 0x0, 0x0, ...)
        /usr/local/go/src/reflect/value.go:435 +0x1214
reflect.Value.Call(0x14beac0, 0x1954bc8, 0x13, 0xc082605ea8, 0x3, 0x3, 0x0, 0x0, 0x0)
        /usr/local/go/src/reflect/value.go:303 +0xb8
net/rpc.(*service).call(0xc0821559c0, 0xc08200bf40, 0xc082145368, 0xc082151600, 0xc08210e580, 0x11b2ba0, 0x26e9198, 0x16, 0x11b2ba0, 0x26e9198, ...)
        /usr/local/go/src/net/rpc/server.go:383 +0x1c9
created by net/rpc.(*Server).ServeCodec
        /usr/local/go/src/net/rpc/server.go:477 +0x4a4
```

**Comment by RealKanashii** [comment]
Same here. 
Once the VM is moved to a Datacenter folder (after creating the VM on the root path) the docker-machine doesn't find the VM. You have to manually modify the machine conf on your local machine configuration (config.json) and add "_folder_/_machine_name_" on the **machine name property** to be able to connect to it again (it works again). So seems the machine name works once the machine is already moved. I tried to create the machine changing the machine name as "_folder_/_machine_name_" but then the creation fails: "invalid chars on machine name".
Probably it's only needed to allow "machine name" on creation time to have "/" on it and consider left chars as folder, right ones the machine name...

**Comment by kevin-wang-cy** [comment]
OK I have this issue either, is there any plan to add this feature?
