### ISSUE TITLE
Default value for "docker-machine ip"

### ISSUE THREAD

**Issue by arun-gupta** [docker/machine#1558]
`docker-machine ip` command gives the following error:

```
docker-machine ip
Error: Expected to get one or more machine names as arguments.
```

If no arguments are specified, then it should display IP address of the currently selected machine.

**Comment by nathanleclaire** [comment]
Hi @arun-gupta.  This is a chicken and egg problem.  We check which host is active based on the value returned for the IP address.  Therefore, with the current implementation, it would be impossible to query the IP of the "active" machine, since you need to know the IP address to know which machine is active.

**Comment by arun-gupta** [comment]
@nathanleclaire `docker-machine ls` shows the output as:

```
NAME            ACTIVE   DRIVER       STATE     URL                         SWARM
lab                      virtualbox   Running   tcp://192.168.99.103:2376   
summit2015      *        virtualbox   Running   tcp://192.168.99.104:2376   
swarm-master             virtualbox   Stopped                               swarm-master (master)
swarm-node-01            virtualbox   Stopped                               swarm-master
swarm-node-02            virtualbox   Stopped                               swarm-master
```

And so this command knows the currently active machine and its IP address as well. Without going into implementation details, I think it'll be a convenient update to the command where it show the IP address of the currently active machine.

**Comment by kohver** [comment]
+1, that is so intuitive

**Comment by nathanleclaire** [comment]
Please take discussion of this issue to the proposal at: https://github.com/docker/machine/issues/1783

Thanks!
