### ISSUE TITLE
EC2: docker-machine restart does not perform a reboot

### ISSUE THREAD

**Issue by alvinr** [docker/machine#1571]
# Problem
`docker-machine restart` appears to do a shutdown and restart of the EC2 instance, causing the EC2 instance to get a new external IP address. This can cause issues with other containers that reply on the IP address, since the external IP address is used as the default hostname.

<img width="804" alt="screen shot 2015-07-22 at 10 25 55 pm" src="https://cloud.githubusercontent.com/assets/336450/8843700/cbf2583e-30c0-11e5-903c-2f5f8e02ed1a.png">

Machine running
```
$ docker-machine ls
NAME           ACTIVE   DRIVER         STATE     URL                         SWARM
foobar                  amazonec2      Running   tcp://52.2.125.236:2376     
```

Restart called
`$ docker-machine restart foobar`

After complete, it can be seen the IP address has changed
```
$ docker-machine ls
NAME           ACTIVE   DRIVER         STATE     URL                         SWARM
foobar                  amazonec2      Running   tcp://52.5.78.200:2376      
```

# Solution
Rebooting the EC2 retains the IP address / hostname

`$ docker-machine ssh foobar "sudo reboot"`

IP retained through the reboot
```
NAME           ACTIVE   DRIVER         STATE     URL                         SWARM
foobar                  amazonec2      Running   tcp://52.5.78.200:2376      
```

# Workaround
Use the following
`docker-machine ssh foobar "sudo reboot"`

# Environment

```
$ uname -a
Linux foobar 3.13.0-58-generic #97-Ubuntu SMP Wed Jul 8 02:56:15 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

```
$ docker-machine --version
docker-machine version 0.3.0 (0a251fe)
```

**Comment by jeanlaurent** [comment]
this is fixed by #2684
