### ISSUE TITLE
create doesn't work when ssh session multiplexing is enabled

### ISSUE THREAD

**Issue by jitakirin** [docker/machine#1572]
So when SSH config contains e.g. ``ControlMaster auto``, ``ControlPath ...``, ``ControlPersist yes`` so that when ssh command is run it spawns a process in the background which maintains the network connection and allows multiple sessions to be run over the same connection which improves performance as connection is only established once.

With that configuration docker-machine runs an ssh command and appears to hang when the command finishes:

```
$ docker-machine --debug create --driver=digitalocean ...
Creating SSH key...
Creating Digital Ocean droplet...
Created droplet ID ..., IP address x.x.x.x
Getting to WaitForSSH function...
Testing TCP connection to: x.x.x.x:22
...
Using SSH client type: external
About to run SSH command:
exit 0
&{/usr/bin/ssh [/usr/bin/ssh -o PasswordAuthentication=no -o IdentitiesOnly=yes -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=quiet -o ConnectionAttempts=3 -o ConnectTimeout=10 -i /.../.docker/machine/machines/test/id_rsa -p 22 root@x.x.x.x exit 0] []  <nil> <nil> <nil> [] <nil> <nil> <nil> <nil> false [] [] [] [] <nil>}
```

hangs here.

I've confirmed that if I close the master with ``ssh -S /path/to/socket -O exit none``, docker-machine continues to run, at least up until the next ssh command is run (which establishes a new master and docker-machine hangs again).

Looks like this is because while the the ssh master process is run in the background, it leaves fd 2 (stderr) open for outputting error messages.  I'll have a look if there's a way to make ssh close stderr, but do you think there's something that can be done in docker-machine to handle that?

**Comment by myfear** [comment]
Looks like I have the same problem on Windows 7: docker-machine version 0.3.1 (40ee236)
on VirtualBox 4.3.18

docker-machine -D create --driver virtualbox dev2

```
STDERR:
Using SSH client type: external
About to run SSH command:
ip addr show dev eth1
&{D:\Program Files (x86)\Git\bin\ssh.exe [D:\Program Files (x86)\Git\bin\ssh.exe -o PasswordAuthentication=no -o IdentitiesOnly=yes -o
StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=quiet -o ConnectionAttempts=3 -o ConnectTimeout=10 -i C:\Users\myf
ear\.docker\machine\machines\dev2\id_rsa -p 54361 docker@localhost ip addr show dev eth1] []  <nil> <nil> <nil> [] <nil> <nil> <nil> <n
il> false [] [] [] [] <nil>}
SSH cmd err, output: <nil>: 4: eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 08:00:27:60:0e:6a brd ff:ff:ff:ff:ff:ff
    inet 192.168.56.104/24 brd 192.168.56.255 scope global eth1
       valid_lft forever preferred_lft forever
    inet6 fe80::a00:27ff:fe60:e6a/64 scope link
       valid_lft forever preferred_lft forever

SSH returned: 4: eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 08:00:27:60:0e:6a brd ff:ff:ff:ff:ff:ff
    inet 192.168.56.104/24 brd 192.168.56.255 scope global eth1
       valid_lft forever preferred_lft forever
    inet6 fe80::a00:27ff:fe60:e6a/64 scope link
       valid_lft forever preferred_lft forever

END SSH
```

The machine is up and running and I can ssh into it.
No certificates are generated. Regenerating with regenerate-certificates hangs at the same ssh command.

docker-machine env --shell cmd dev
open C:\Users\myfear\.docker\machine\machines\dev\ca.pem: The system cannot find the file specified.

**Comment by jitakirin** [comment]
[bug report against OpenSSH](https://bugzilla.mindrot.org/show_bug.cgi?id=1988)

**Comment by jitakirin** [comment]
@myfear you seem to be getting response from SSH, are you sure this is the same issue?

**Comment by mdub** [comment]
Would adding `-o ControlMaster=no` to the ssh options fix it?

**Comment by jitakirin** [comment]
@mdub if you mean if docker-machine used an option to disable multiplexing explicitly then yes (could even use ``-S none``); however I'd actually be more interested in having docker-machine play well with multiplexing; I know it can be done (e.g. ansible uses multiplexing internally and also reads stderr from commands it runs), just not sure how yet :-)

**Comment by myfear** [comment]
@jitakirin after you pointed it out, I'm no longer sure. What would be your
suggestion?
Happens with both the mysysgit ssh client and the native go version.

**Comment by alex-leonhardt** [comment]
```docker-machine --debug --native-ssh create -d virtualbox default```

and then

```docker-machine --native-ssh start default```

has worked now twice in a row :)

**Comment by alex-leonhardt** [comment]
the disk image still seems to be inconsistently mounted, though that's a different issue I guess

**Comment by saada** [comment]
+1

**Comment by pearofducks** [comment]
+1

Mine was hanging on 'About to run SSH command', I use these options in `~/.ssh/config`

```
host *
  Protocol 2
  Compression yes
  CompressionLevel 6
  ServerAliveInterval 15
  ServerAliveCountMax 3
  ControlPersist 1h
  ControlMaster auto
  ControlPath ~/.ssh/master-%r@%h:%p
  AddressFamily inet
```

**Comment by nathanleclaire** [comment]
This should work fine now due to the new added SSH options.
