### ISSUE TITLE
Running docker-compose with docker-machine

### ISSUE THREAD

**Issue by AlexZeitler** [docker/machine#1577]
I created a machine using 

````bash
docker-machine create \
--driver digitalocean \ 
--digitalocean-access-token <token> fs
````

I connect to the machine:

````bash
eval "$(docker-machine env fs)"
````

I created a small node.js application:

`app.js`
````js
var express = require('express');
var app = express();

app.get('/', function(req,res) { res.send('hello world')});
console.log('listening on localhost:3000');
app.listen(3000);
````

I created a `Dockerfile`

````Dockerfile
FROM node
EXPOSE 3000
WORKDIR /app

CMD ["node /app/app.js"]
````

I created a `docker-compose.yml`

````yml
app:
        build: ./
        command:  node app.js
        ports:
         - "3000:3000"
         - "5858:5858"
        volumes:
         - ./:/app
````

When I run `docker-compose up`, I get this result:

````bash
Building app...
Step 0 : FROM node
 ---> c03077d1e6a0
Step 1 : EXPOSE 3000
 ---> Using cache
 ---> c4a82f27d349
Step 2 : WORKDIR /app
 ---> Using cache
 ---> 0b3aa79e1ec1
Step 3 : CMD node /app/app.js
 ---> Using cache
 ---> cd7b9465b18d
Successfully built cd7b9465b18d
Creating dockermachinenode_app_1...
Attaching to dockermachinenode_app_1
app_1 | module.js:338
app_1 |     throw err;
app_1 |           ^
app_1 | Error: Cannot find module '/app/app.js'
app_1 |     at Function.Module._resolveFilename (module.js:336:15)
app_1 |     at Function.Module._load (module.js:278:25)
app_1 |     at Function.Module.runMain (module.js:501:10)
app_1 |     at startup (node.js:129:16)
app_1 |     at node.js:814:3
````

When I run `docker-compose up` against my local Docker host, everything works fine:

````bash
Building app...
Step 0 : FROM node
 ---> c03077d1e6a0
Step 1 : EXPOSE 3000
 ---> Using cache
 ---> 1484a1cebd00
Step 2 : WORKDIR /app
 ---> Using cache
 ---> aa6d06d4411c
Step 3 : CMD node /app/app.js
 ---> Using cache
 ---> 306fed3b81c6
Successfully built 306fed3b81c6
Creating dockermachinenode_app_1...
Attaching to dockermachinenode_app_1
app_1 | listening on localhost:3000
````

````bash
curl localhost:3000
hello world
````

What am I doing wrong when combining `docker-machine` with `docker-compose`?

Should I create an image first, push it to Docker Hub and refer to it in my `docker-compose.yml`?

**Comment by AlexZeitler** [comment]
After I ran `docker-machine scp -r . fs:` followed by `docker-compose build` and `docker-compose up`, I got this log:

````bash
listening on localhost:3000
````

But I have not been able to `curl http://<machineip>:3000`
Connection has been refused.

When I did a `docker inspect dockermachinenode_app_1 | grep "IPAddress"`, it was empty.

**Comment by nathanleclaire** [comment]
Hi @AlexZeitler,

Where did you `docker-machine scp` the files to on the remote machine?

In your `docker-compose.yml`, you have this section:

```
        volumes:
         - ./:/app
```

Which will transform into a Docker API request to the remote daemon that says, "bind mount the path at `.` on my client into the container at directory `/app`", and transforms them into absolute paths appropriately.  If your client is a Mac, `.` will be wherever the `docker-compose.yml` is, so the request will say the path should be something like `/Users/Alex/webapp`, which naturally probably doesn't exist on your remote Linux server.  So, you have to either drop the volumes section, or somehow make sure the files exist at that path on your remote server (you could also change the `.` to an absolute path on the remote).

**Comment by AlexZeitler** [comment]
Hi @nathanleclaire, I did `docker-machine scp` from my local machine in the folder where the code and the `docker-compose.yml` resides.

I'm running on Ubuntu.

**Comment by nathanleclaire** [comment]
@AlexZeitler So, just to be clear, if you are in the repo where the `docker-compose.yml` is on the command line, what is the output of the following commands:

```console
$ pwd
$ docker-machine ssh fs ls $(pwd)
```

**Comment by AlexZeitler** [comment]
```bash
~/src/dockermachinenode$ pwd
/home/alex/src/dockermachinenode
~/src/dockermachinenode$ docker-machine ssh fs ls $(pwd)
~/src/dockermachinenode$
````

**Comment by nathanleclaire** [comment]
Ah, yes.  So, the files have not been copied to your remote host as you would like.  As you see, the remote directory is empty.  Probably because you are user `root` on the remote and there is no user `alex` there, so there is no `/home/alex/src/dockermachinenode` on the server.

Consider trying something like:

```console
$ docker-machine ssh fs -- mkdir -p /home/alex/src/dockermachinenode
$ docker-machine scp -r . fs:/home/alex/src/dockermachinenode
```

That's a bit hacky, but it should work.  The files will be where your requests to the Docker API expect them to be.

Does that help?  And does it make sense?

**Comment by AlexZeitler** [comment]
~/src/dockermachinenode$ docker-compose up
Recreating dockermachinenode_app_1...
Attaching to dockermachinenode_app_1
app_1 | listening on localhost:3000

After your explanation it totally makes sence.
My expectations were just wrong.

Thanks! :+1:

**Comment by nathanleclaire** [comment]
:+1:

**Comment by M0on75e1l** [comment]
Just got the same issue. In the example above I noticed that 

`~/src/dockermachinenode$ docker-machine ssh fs ls $(pwd)`

showed you nothing instead of:

`ls: /home/alex/src/dockermachinenode: No such file or directory`

which means that directory **exists** on the server, and @AlexZeitler mentioned that:
> Hi @nathanleclaire, I did docker-machine scp from my local machine in the folder where the code and the docker-compose.yml resides.

So directory was created on the server automatically but **files** inside of local directory just didn't copied to server. So I assume this is not actually the case:

> Probably because you are user root on the remote and there is no user alex there, so there is no /home/alex/src/dockermachinenode on the server.

I see here from @nathanleclaire comment that solution may be too copy files manually with

`docker-machine scp -r . fs:/home/alex/src/dockermachinenode`

But should they sync from that point? Or if I made some changes to that files from my local machine, should I `scp` them every time to the server?

**Comment by M0on75e1l** [comment]
I got a similar issue.

I am running `docker-compose up -d` at path `/home/roman.burkovsky/barnak`.
My `/home/roman.burkovsky/barnak/docker-compose.yml`:
```yml
nginx:
    build: ./nginx
    ports:
        - 80:80
    links:
        - php
    volumes:
        - .:/var/www/html
php:
    image: php:7.0-fpm
    expose:
        - 9000
    volumes:
        - .:/var/www/html
```
On my local machine I created a file `/home/roman.burkovsky/barnak/index.php`.
I am trying to access it from browser with docker-machine's IP, but getting 403 error. 

Nginx log:
`2016/05/17 13:02:23 [error] 5#5: *1 directory index of "/var/www/html/" is forbidden, client: 192.168.99.101, server: , request: "GET / HTTP/1.1", host: "192.168.99.100`

On the server directory `/home/roman.burkovsky/barnak` exists, but it is empty. It was created automatically, I didn't `scp` anything. However, files are not there. 

So I wonder if I must manually `scp` files to server every time I will make changes to them on local machine? I was following that [guide](http://blog.osteel.me/posts/2015/12/18/from-vagrant-to-docker-how-to-use-docker-for-local-web-development.html) and author haven't mentioned anything about the need to use `scp`. Shouldn't they be in sync?

**Comment by AlexZeitler** [comment]
You could use rsync as I described here: https://alexanderzeitler.com/articles/docker-machine-and-docker-compose-developer-workflows/

Also read the comments as there was some suggestion how to do it without rsync/scp.

**Comment by M0on75e1l** [comment]
I saw your article, but that all makes docker-machine useless for me. 

At least I figured out what was the problem.

Thanks.

**Comment by ozolinsartis** [comment]
@m0onspell Mind sharing what was the issue? Still stuck on this, can't figure out why the folder is not being mounted. It gets created but it's empty.

**Comment by nathanleclaire** [comment]
> @m0onspell Mind sharing what was the issue? Still stuck on this, can't figure out why the folder is not being mounted. It gets created but it's empty.

Are you trying to talk to a remote server this way?  Folder sharing between host and VM only occurs in local drivers, e.g., virtualbox and vmwarefusion.  Otherwise you are referencing paths on the remote computer which do not exist

**Comment by m0onspell** [comment]
@ozolinsartis I can't remember exactly, I just made a conclusion that there are no easy way to use docker-machine, at least on my linux environment, and that's something rather for windows/mac use. I spent a lot of time, playing with different configs, updating different parts of software, but with no luck. I ended up using docker directly without machine.

**Comment by ozolinsartis** [comment]
@m0onspell Thanks a lot for your response. Most likely I'll end up doing the same.  I tried several configurations and virtual box versions but to no avail.
I'll post here if I happen to discover anything.
