### ISSUE TITLE
boot2docker NG issue rodeo

### ISSUE THREAD

**Issue by nathanleclaire** [docker/machine#1579]
There are a few issues with the NG code which need to be rectified before release:

- [x] As noted in https://github.com/docker/machine/pull/1552#issuecomment-124263400, we need to fix the Debian provisioner to conditionally download new ISOs based on which driver it is dealing with.  Some will want `apt-get upgrade`, others will want new ISOs.
- [x] VMware Shared folders are not working out of the box with created Fusion VMs.  cc @frapposelli PTAL

**Comment by ehazlett** [comment]
Upgrade has been fixed and is on the `b2d-next` branch.

**Comment by ehazlett** [comment]
I'm still debugging the vmware shared folders with @tianon.

**Comment by frapposelli** [comment]
I haven't had the time to test this yet, but if you're sourcing `open-vm-tools` from debian you're most likely missing the `vmhgfs` kernel module.

**Comment by frapposelli** [comment]
btw, I'm working with the VMtools team to get a tech preview of open-vm-tools 10 out very soon so we can move to the FUSE-based shared folders platform.

**Comment by tianon** [comment]
:metal:

**Comment by ehazlett** [comment]
Fusion shared folders working again in https://github.com/ehazlett/machine/commit/5f972ad759f63c0c8c45021ead4d3d30f65e8f71

**Comment by ehazlett** [comment]
I think we can close this one.

**Comment by tianon** [comment]
Thanks for the hint @frapposelli, that was exactly it! (needed `open-vm-tools-dkms`) :heart:

**Comment by nathanleclaire** [comment]
:+1:
