### ISSUE TITLE
Where to put bootlocal.sh after installing 0.4.0-rc1 (f6ea2c1)

### ISSUE THREAD

**Issue by WebAppNut** [docker/machine#1587]
Just installed v0.4.0-rc1and created new virtualbox vm. Looking to run bootlocal.sh from persistent disk, but /var/lib/boot2docker symlink does not exist.

Tried $ sudo mkdir /mnt/data/var/lib/boot2docker && sudo ln -s /mnt/data/var/lib/boot2docker /var/lib/boot2docker. Symlink will not survive vm restart, but source directory does. Creating an executable bootlocal.sh inside does not appear to be loading.

Has the default location for bootlocal.sh changed with 0.4.0-rc1? 

Purpose of script is to swap out default /Users share with NFS. Worked great on v0.3.1.

![screen shot 2015-07-25 at 11 49 56 am](https://cloud.githubusercontent.com/assets/2280741/8890595/771a78fa-32c3-11e5-8e0d-ec67b98a6f5d.png)

**Comment by WebAppFlow** [comment]
Just to confirm... downgrading to v0.3.1 and recreating virtualbox vm results in boot2docker symlink.
![screen shot 2015-07-25 at 3 15 32 pm](https://cloud.githubusercontent.com/assets/2280741/8891297/068ae034-32e1-11e5-8ac1-e918e5bdcdac.png)

**Comment by WebAppFlow** [comment]
I'm guessing this is not a bug now, as it appears the nfs functional was removed from the latest boot2docker-virtualbox.iso. Any sudo mount -t nfs fails with "unknown filesystem type". Does this mean a better (faster) folder sharing method is in the works, or will there be a different way to get nfs mounts working?

Guess I'll just stick with v0.3.1, as it works great with my nfs mount script. Maybe a blurb under https://github.com/docker/machine/releases to save someone else some time.

Btw, thx for docker, machine & compose... really amazing stuff!

**Comment by WebAppFlow** [comment]
For what it's worth, here is the script I use to populate bootlocal.sh: https://gist.github.com/WebAppFlow/16426261bc053d9a878d/3b806d1a97b1226ff8fcd2282315af3fd5f46577#file-nfs_machine-sh

**Comment by nathanleclaire** [comment]
> Does this mean a better (faster) folder sharing method is in the works

Unfortunately not for the time being.

> will there be a different way to get nfs mounts working?

Hopefully, but it still remains to be seen for this release.  In the worst case scenario, you could "bake" your own boot2docker ISO which has the relevant features and use that.

So, to explain a little further what you are actually running into here:

In Machine 0.4.0 / b2d 1.8 we are migrating to a new boot2docker which is based on Debian instead of TinyCore Linux.  There are going to be some issues with backwards compatibility such as this, but I am trying hard to try and accommodate existing workflows where possible.  I think there's a fair argument in favor of `bootlocal.sh` and including NFS, so I'll start a conversation with the "boot2docker OS upstream" and see if / how we will integrate those.

**Comment by nathanleclaire** [comment]
cc @tianon

**Comment by tianon** [comment]
Breaking NFS completely was definitely not intentional!  We do also need to figure out where `bootlocal.sh` fits in.  We don't really have a good answer for this just yet, but we definitely plan to have something as soon as we figure out exactly where it should live!

**Comment by tianon** [comment]
NFS is back: https://github.com/boot2docker/boot2docker/commit/242d7b70f12b434048f241408dcfd6f6a3db7d9a

Now to figure out where to put boot hooks.

**Comment by tianon** [comment]
https://github.com/docker/boot2docker/commit/24cbf748594f57cbc1be83b14721d59d98626b13 and now we have persistent `before-docker.d` and `after-docker.d` on-boot scripts directories :+1: (although only lightly tested at this point)

Put `something.sh` files in either `/etc/boot2docker/hooks/before-docker.d` or  `/etc/boot2docker/hooks/after-docker.d`. :metal:

**Comment by tianon** [comment]
Doh, uh, and https://github.com/docker/boot2docker/commit/602d5b6bc016b31231f9e55e2d47b21dfbab4c59. :innocent:

**Comment by WebAppFlow** [comment]
Thx @nathanleclaire & @tianon, that was quick!

How would I go about testing these new commits?

Should I build a custom iso using instructions at https://github.com/boot2docker/boot2docker/blob/master/doc/BUILD.md. How would I modify to account for new debian-based b2d?

Should I just wait till there is a release posted to https://github.com/docker/boot2docker?

**Comment by tianon** [comment]
@WebAppFlow I think @ehazlett was planning on building updated ISOs soon, but we'll also have an official RC release as soon as Docker 0.8.0-rc2 is out (rc1 was a bust thanks to missing systemd service files).

**Comment by n1koo** [comment]
I just tried this out. Seems like the `nfs` module isn't compatible with the kernel.

```
modprobe: ERROR: ../libkmod/libkmod-module.c:186 kmod_module_parse_depline() ctx=0x7f2630a16010 path=/lib/modules/3.16.0-4-amd64/kernel/net/sunrpc/sunrpc.ko error=No such file or directory
modprobe: ERROR: ../libkmod/libkmod-module.c:186 kmod_module_parse_depline() ctx=0x7f2630a16010 path=/lib/modules/3.16.0-4-amd64/kernel/net/sunrpc/sunrpc.ko error=No such file or directory
modprobe: ERROR: could not insert 'nfs': Unknown symbol in module, or unknown parameter (see dmesg)
root@boot2docker:/etc/boot2docker/hooks/before-docker.d# uname -a
Linux boot2docker 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt11-1+deb8u2 (2015-07-17) x86_64 GNU/Linux
```

`dmesg` full of this kinda stuff.

```
[  891.588920] nfs: Unknown symbol __fscache_disable_cookie (err 0)
[  891.588930] nfs: Unknown symbol __fscache_acquire_cookie (err 0)
```

Compiled the current HEAD in `docker/boot2docker`. `nfs-common` seems to be present.

**Comment by acaire** [comment]
> How would I go about testing these new commits?

I'd also be interested in testing this - I'm Building [docker/boot2docker master](https://circleci.com/gh/cotdsa/boot2docker/tree/cgws) and [docker/machine master](https://circleci.com/gh/cotdsa/machine/tree/cgws) (have tried @ehazlett's fork too), but it doesn't seem like it's injecting [.ssh/authorized_keys] (https://github.com/docker/machine/blob/af08468f00f3109961d279b83c538633459c434d/drivers/virtualbox/virtualbox.go#L558:L561) (or anything for that matter into the home dir) but it looks like you guys are using it fine?

@tianon any chance of a 30 second run down on which branches to use for each project?

**Comment by nathanleclaire** [comment]
Just FYI everyone - we have decided to delay the OS transition for another release so all of the boto2docker idioms which you may be familiar with (e.g. where to put `bootlocal.sh`) will stay the same for this upcoming release.

**Comment by sebflipper** [comment]
I've been using `/var/lib/boot2docker/bootlocal.sh` to automatically add our internal Docker Registry self signed certificate to the boot2docker machine.

However since updating to `docker-machine` this no longer works.
```bash
#!/bin/sh
# /var/lib/boot2docker/bootlocal.sh
curl http://www.example.com/my-docker-registry-public-key.crt >> /etc/ssl/certs/ca-certificates.crt
```
This used to preserve our Docker Registry self signed certificate between reboots.

So to work around this I'm currently wrapping the startup script like so:
```bash
#!/bin/bash
# ~/bin/boot2docker/bootlocal.sh
. '/Applications/Docker/Docker Quickstart Terminal.app/Contents/Resources/Scripts/start.sh'
docker-machine ssh default 'sudo mkdir -p /etc/docker/certs.d/example.com:5000 && sudo sh -c "curl http://www.example.com/my-docker-registry-public-key.crt > /etc/docker/certs.d/example.com:5000/ca.crt"'
```

If anyone knows a better way of adding Docker Registry self signed certificates to `docker-machine` let me know!

**Comment by nathanleclaire** [comment]
@tianon -- @sebflipper's issue is not something I would expect to happen given that we haven't transitioned OSes yet.  Do you have any idea what might be going on?  Perhaps we should transition to a boot2docker/boot2docker issue?

**Comment by dgageot** [comment]
@WebAppFlow @nathanleclaire is this issue something we can do about? Looks like it's not in docker-machine's garden

**Comment by dangreen** [comment]
@sebflipper https://github.com/boot2docker/boot2docker#installing-secure-registry-certificates
@WebAppNut https://github.com/boot2docker/boot2docker/blob/master/doc/FAQ.md#local-customisation-with-persistent-partition

**Comment by nathanleclaire** [comment]
`bootlocal.sh` should work as far as I'm aware.  Please open an issue on https://github.com/boot2docker/boot2docker if not (with steps to reproduce).  Thanks!
