### ISSUE TITLE
docker-machine start vm failed

### ISSUE THREAD

**Issue by myfear** [docker/machine#1588]
Testing latest  0.4.0rc1 with Windows 7 and 
C:\Users\myfear>vboxmanage --version
4.3.30r101610

It hangs, but, I can actually login:

C:\Users\myfear>docker-machine ssh dev
Docker version 1.7.1, build 786b29d
Last login: Sun Jul 26 07:20:08 2015
docker@dev:~$ pwd
/home/docker

C:\Users\myfear>docker-machine ls
NAME   ACTIVE   DRIVER       STATE     URL                         SWARM
dev             virtualbox   Running   tcp://192.168.99.101:2376

```
Using SSH client type: external
About to run SSH command:
sudo systemctl daemon-reload
&{D:\Program Files (x86)\Git\bin\ssh.exe [D:\Program Files (x86)\Git\bin\ssh.exe -o PasswordAuthentication=no -o IdentitiesOnly=yes -o
StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=quiet -o ConnectionAttempts=3 -o ConnectTimeout=10 -i C:\Users\myf
ear\.docker\machine\machines\dev\id_rsa -p 50887 docker@localhost sudo systemctl daemon-reload] []  <nil> <nil> <nil> [] <nil> <nil> <n
il> <nil> false [] [] [] [] <nil>}
SSH cmd err, output: <nil>:
Using SSH client type: external
About to run SSH command:
sudo systemctl start docker
&{D:\Program Files (x86)\Git\bin\ssh.exe [D:\Program Files (x86)\Git\bin\ssh.exe -o PasswordAuthentication=no -o IdentitiesOnly=yes -o
StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=quiet -o ConnectionAttempts=3 -o ConnectTimeout=10 -i C:\Users\myf
ear\.docker\machine\machines\dev\id_rsa -p 50887 docker@localhost sudo systemctl start docker] []  <nil> <nil> <nil> [] <nil> <nil> <ni
l> <nil> false [] [] [] [] <nil>}
SSH cmd err, output: <nil>:
Daemon not responding yet: dial tcp 192.168.99.101:2376: ConnectEx tcp: A connection attempt failed because the connected party did not
 properly respond after a period of time, or established connection failed because connected host has failed to respond.
Daemon not responding yet: dial tcp 192.168.99.101:2376: ConnectEx tcp: A connection attempt failed because the connected party did not
 properly respond after a period of time, or established connection failed because connected host has failed to respond.
Daemon not responding yet: dial tcp 192.168.99.101:2376: ConnectEx tcp: A connection attempt failed because the connected party did not
 properly respond after a period of time, or established connection failed because connected host has failed to respond.
Daemon not responding yet: dial tcp 192.168.99.101:2376: ConnectEx tcp: A connection attempt failed because the connected party did not
 properly respond after a period of time, or established connection failed because connected host has failed to respond.
```

The full output for docker-machine create
https://gist.github.com/myfear/c3c15d025726a697cc8b

@nathanleclaire give me a ping, when there's something I can do to debug this further. Happy to help!

**Comment by tknerr** [comment]
In my case the virtualbox installation was the culprit. After reinstalling everything was fine again.

**Comment by nathanleclaire** [comment]
Nice to hear @tknerr !

**Comment by FrenchBen** [comment]
@myfear Can you verify that the IP originally used to setup the VM is the `192.168.99.101`?
`docker-machine ssh dev`
then:
`sudo cat /var/lib/boot2docker/tls/hostnames`

**Comment by Crashthatch** [comment]
I was getting this error after installing docker-toolbox upgraded virtualbox to 5.0.2. Uninstalling Virtualbox and reinstalling from Oracle's website fixed the problem.

**Comment by Crashthatch** [comment]
Restarting host seems to have fixed. Suspect Virtualbox is at fault, not docker-machine.

**Comment by FrenchBen** [comment]
@Crashthatch glad your issue was resolved - I've seen a few good results with the [test builds of Virtualbox](https://www.virtualbox.org/wiki/Testbuilds) if it happens in the future

**Comment by dgageot** [comment]
Closing this issue since it seems that it's fixed. Feel free to reopen!

**Comment by Crashthatch** [comment]
It kept recurring and test builds did not fix. Restarting the host did fix it, but is a very annoying workaround to do after each sleep. Either way, I think it's a Virtualbox bug, not Docker-machine.

I've switched to using ubuntu (natively, rather than in a VM) for all docker things partly because of this issue.
