### ISSUE TITLE
Version 0.4.0-dev panics on 'ls' and other commands

### ISSUE THREAD

**Issue by benvolioT** [docker/machine#1589]
Installed docker-machine using homebrew, pointing to HEAD in order to get VirtualBox 5.0 compatibility:
$ brew install --HEAD docker-machine

$ docker-machine -v
docker-machine version 0.4.0-dev (HEAD)

$ docker-machine ls
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x16a0a1]

goroutine 1 [running]:
github.com/docker/machine/libmachine.(*Host).LoadConfig(0xc20802f220, 0x0, 0x0)
	/private/tmp/docker-machine20150726-36626-ohf8e9/src/github.com/docker/machine/libmachine/host.go:287 +0x3d1
github.com/docker/machine/libmachine.Filestore.loadHost(0xc20806a4c0, 0x1e, 0xc20803d8f0, 0x2b, 0xc20803dbc0, 0x2f, 0xc20802ea28, 0x1c, 0x55b1e0, 0x0, ...)
	/private/tmp/docker-machine20150726-36626-ohf8e9/src/github.com/docker/machine/libmachine/filestore.go:34 +0x287
github.com/docker/machine/libmachine.Filestore.Get(0xc20806a4c0, 0x1e, 0xc20803d8f0, 0x2b, 0xc20803dbc0, 0x2f, 0xc20802ea28, 0x1c, 0x0, 0x0, ...)
	/private/tmp/docker-machine20150726-36626-ohf8e9/src/github.com/docker/machine/libmachine/filestore.go:112 +0x65
github.com/docker/machine/libmachine.Filestore.List(0xc20806a4c0, 0x1e, 0xc20803d8f0, 0x2b, 0xc20803dbc0, 0x2f, 0x0, 0x0, 0x0, 0x0, ...)
	/private/tmp/docker-machine20150726-36626-ohf8e9/src/github.com/docker/machine/libmachine/filestore.go:88 +0x2c6
github.com/docker/machine/libmachine.(*Filestore).List(0xc20808a060, 0x0, 0x0, 0x0, 0x0, 0x0)
	<autogenerated>:8 +0xd3
github.com/docker/machine/libmachine.(*Provider).List(0xc2080b6a20, 0x0, 0x0, 0x0, 0x0, 0x0)
	/private/tmp/docker-machine20150726-36626-ohf8e9/src/github.com/docker/machine/libmachine/provider.go:75 +0x6d
github.com/docker/machine/commands.cmdLs(0xc2080420c0)
	/private/tmp/docker-machine20150726-36626-ohf8e9/src/github.com/docker/machine/commands/ls.go:30 +0x1d7
github.com/codegangsta/cli.Command.Run(0x778890, 0x2, 0x0, 0x0, 0x78ea70, 0xd, 0x0, 0x0, 0x0, 0x0, ...)
	/private/tmp/docker-machine20150726-36626-ohf8e9/Godeps/_workspace/src/github.com/codegangsta/cli/command.go:113 +0x1038
github.com/codegangsta/cli.(*App).Run(0xc20801e4e0, 0xc20800a000, 0x2, 0x2, 0x0, 0x0)
	/private/tmp/docker-machine20150726-36626-ohf8e9/Godeps/_workspace/src/github.com/codegangsta/cli/app.go:156 +0xcf7
main.main()
	/private/tmp/docker-machine20150726-36626-ohf8e9/main.go:114 +0x9bc

goroutine 5 [runnable]:
os/signal.loop()
	/usr/local/Cellar/go/1.4.2/libexec/src/os/signal/signal_unix.go:19
created by os/signal.init·1
	/usr/local/Cellar/go/1.4.2/libexec/src/os/signal/signal_unix.go:27 +0x35

**Comment by benvolioT** [comment]
This is most likely a duplicate of #1537

**Comment by nathanleclaire** [comment]
@benvolioT Yep, it certainly seems to be -- thanks for the report, I'm going to close this issue as the other one is tracking it, and I have some migration code in the works.
