### ISSUE TITLE
virtualbox: Disable User share

### ISSUE THREAD

**Issue by rawkode** [docker/machine#1593]
I've flicked through other issues and browsed the code, but I am unable to see a way to disable the automatic mounting of my User folder (I wish to manage this myself with rsync, for performance)

Can somebody please advise me of something I'm missing?

**Comment by clnperez** [comment]
Nope, you're not missing anything. It looks like VirtualBox auto-mounts your $HOME.

**Comment by nathanleclaire** [comment]
I definitely would like at least a `--virtualbox-no-share` option or equivalent, just haven't written it.

**Comment by ehazlett** [comment]
+1 for the flag.

**Comment by rawkode** [comment]
Attempted to add this myself #1622

**Comment by Multiply** [comment]
:+1: for this. Wouldn't it be nice to also have the option to override the shared folders, somehow? It's highly needed for a project of mine.

**Comment by rawkode** [comment]
#1622 merged

**Comment by mikzalais** [comment]
Does this work?
All I get is this, with docker-machine version 0.4.1 (e2c88d6):

-> % docker-machine create --driver=virtualbox --virtualbox-no-share default        
Incorrect Usage.

**Comment by nathanleclaire** [comment]
@mikzalais It is not out yet -- it will be out in 0.5.0

**Comment by wcandillon** [comment]
Very cool!
