### ISSUE TITLE
Virtualbox and VMware Fusion have different permissions on /Users share

### ISSUE THREAD

**Issue by rouge8** [docker/machine#1594]
After creating a VM with `docker-machine create --driver=DRIVER NAME` on OS X, the user's home directory is mounted as `/Users`. When using the VMware fusion driver, `/Users` is mounted with the uid and gid of the host user. In Virtualbox, `/Users` is mounted with the uid and gid of the boot2docker user. Personally, I prefer the VMware configuration, because we use `docker run -u $(id -u)` a lot, and with VMware fusion, it just works.

### VMware fusion:

```console
docker@dev:~$ ls -l /Users | grep rouge8
drwxr-xr-x    1 502      20            4862 Jul 27 15:44 rouge8/
```

```console
$ docker -D info
Containers: 90
Images: 196
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 376
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.0.5-boot2docker
Operating System: Boot2Docker 1.7.0 (TCL 6.3); master : 7960f90 - Thu Jun 18 18:31:45 UTC 2015
CPUs: 1
Total Memory: 996.2 MiB
Name: dev
ID: J2UV:75A4:AKB6:TLCK:I3NP:P4Z7:FSLX:PPIV:E7LA:XYL3:R6L7:VLXJ
Debug mode (server): true
File Descriptors: 11
Goroutines: 17
System Time: 2015-07-27T15:55:23.731825016Z
EventsListeners: 0
Init SHA1:
Init Path: /usr/local/bin/docker
Docker Root Dir: /mnt/sda1/var/lib/docker
Labels:
 provider=vmwarefusion
```

### Virtualbox:

```console
docker@vbox:~$ ls -l /Users | grep rouge8
drwxr-xr-x    1 docker   staff         4862 Jul 27 15:44 rouge8/
```

```console
$ docker -D info
Containers: 2
Images: 10
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 14
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.0.5-boot2docker
Operating System: Boot2Docker 1.7.0 (TCL 6.3); master : 7960f90 - Thu Jun 18 18:31:45 UTC 2015
CPUs: 1
Total Memory: 996.2 MiB
Name: vbox
ID: O7EP:NYT7:ONSR:CH3J:JJVW:5JOO:LQIQ:UMAW:Z6AJ:TKRC:B4CR:YK7P
Debug mode (server): true
File Descriptors: 9
Goroutines: 17
System Time: 2015-07-27T16:00:24.676426506Z
EventsListeners: 0
Init SHA1:
Init Path: /usr/local/bin/docker
Docker Root Dir: /mnt/sda1/var/lib/docker
Labels:
 provider=virtualbox
```

**Comment by timfallmk** [comment]
@rouge8 This stems from differences in share creation between Virtual Box and VMWare Fusion. `machine` relies on the automounting method built into both (for better or worse) to do the mounting inside the vm. In virtualbox this uses the default auto mount method for linux, which defaults to the current user in the vm. You can see what I mean here: https://github.com/docker/machine/blob/master/drivers/virtualbox/virtualbox.go#L295

I agree with you that it's an annoyance (and I prefer the way Fusion does it), but without a major refactor of how mounting is handled, it would be difficult to change.

A good workaround might be to remount share with the permission you want, ala:
`sudo mount -o remount -t vboxsf -o umask=0022,gid=33,uid=33 <mount> <mountpoint>`

**Comment by rouge8** [comment]
> A good workaround might be to remount share with the permission you want, ala:
> `sudo mount -o remount -t vboxsf -o umask=0022,gid=33,uid=33 <mount> <mountpoint>`

The `-o remount` doesn't seem to work, but `sudo umount <mountpoint> && sudo mount ...` does. It's annoying, but it's a decent workaround, especially with `docker-machine ssh`. Thanks.

**Comment by timfallmk** [comment]
No problem @rouge8 . Glad to hear that worked for you. Unfortunately it's mostly due to Virtual Box, so there's not a lot that can be done about it at the moment.

**Comment by ehazlett** [comment]
Thanks @timfallmk -- as mentioned this is due to the way the shares are setup.  In the future, we are planning to have more control over the share process and control from within machine to workaround things like this.
