### ISSUE TITLE
Creating .docker from scratch results in a permissions error

### ISSUE THREAD

**Issue by moxiegirl** [docker/machine#1595]
```
docker-machine create --driver virtualbox docker-vm
Error creating machine config dir: mkdir /Users/mary/.docker/machine/certs: permission denied
```

**Comment by moxiegirl** [comment]
On further investigation, it looks like the `~/.docker/machine` directory gets created as being owned by user `root`, which prevents Machine from adding additional sub-directories.  We suspect this might be a Toolbox issue.  cc @jeffdm @ehazlett @nathanleclaire

**Comment by moxiegirl** [comment]
@nathanleclaire confirmed.  After installing the Toolbox without running `docker-machine` I have this:

```
$ tree .docker
.docker
└── machine
    └── cache
        └── boot2docker-virtualbox.iso
```

**Comment by timfallmk** [comment]
Confirmed. Ownership appears to be `root:root`

**Comment by ehazlett** [comment]
Ideally the toolbox should let machine handle the directory creation since it could change in the future, etc. IMO

**Comment by moxiegirl** [comment]
@jeffdm do you want to move this to Toolbox?

**Comment by nathanleclaire** [comment]
Closing as this is a Toolbox issue.

**Comment by ericandrewlewis** [comment]
@nathanleclaire can you link to the Toolbox issue? Thanks!
