### ISSUE TITLE
Better Error Message On 'docker-machine active' When No Hosts Found

### ISSUE THREAD

**Issue by tehmaspc** [docker/machine#1599]
I believe we need a better error message and error code if there are no active hosts found with 'docker-machine active'.

e.g. I see this when I have no active hosts:

    % docker-machine active
    Error getting active host: Active host not found
    % echo $?
    1

**Comment by nathanleclaire** [comment]
That seems fairly clear to me, but I'm biased  Do you have any suggestions?

**Comment by tehmaspc** [comment]
Didn't realize there is no more than 1 active host at a time. I was thinking there could be more than one and thus thought this error message was off. Apologies. Closing.

**Comment by nathanleclaire** [comment]
No problem - there actually _can_ be more than one "active" host in a sense, just not more than one per shell - this is because the active host is dictated by the environment variable `DOCKER_HOST` and others, which can change per-shell.
