### ISSUE TITLE
Machine should configure Docker to automatically control the active machine

### ISSUE THREAD

**Issue by bfirsh** [docker/machine#16]
We should configure the Docker host and authentication method so this works seamlessly:

    $ machine create -d virtualbox dev
    $ docker run ...

The best way to do this is probably to create a configuration file that sets these options (`~/.docker/config`?). This will require modification to Docker – I'll put together a proposal on the Docker repository.

An alternative method could be to set environment variables. For example, there could be a `machine config` command which output:

```
export DOCKER_HOST=$(machine url) DOCKER_AUTH=identity`
```

You could then just run `$(machine config)` and your shell would be set up to talk to the active machine.

**Comment by bfirsh** [comment]
Here's a comment on that proposal explaining the requirements for Machine: https://github.com/docker/docker/issues/7232#issuecomment-68545474

**Comment by bfirsh** [comment]
cc @ehazlett

**Comment by ehazlett** [comment]
I think integration into Docker Engine would be best.  However, I think to create a better user experience we should do the env vars config for the interim.   This has bit me multiple times :)

**Comment by sthulb** [comment]
+1 for the env vars via `machine config` for now.

**Comment by sthulb** [comment]
However, it would perhaps be more advantageous for people to have this instead:

Zsh:
```sh
_machine_env_hook() {
  export DOCKER_HOST=$(machine url) DOCKER_AUTH=identity`
}
typeset -ag precmd_functions
if [[ -z $precmd_functions[(r)_machine_env_hook] ]]; then
  precmd_functions+=_machine_env_hook;
fi
``` 

Bash:
```sh
_machine_env_hook() {
  export DOCKER_HOST=$(machine url) DOCKER_AUTH=identity`
}
if ! [[ "$PROMPT_COMMAND" =~ _machine_env_hook ]]; then
  PROMPT_COMMAND="_machine_env_hook;$PROMPT_COMMAND";
fi
```

**Comment by bfirsh** [comment]
If we're going to do `machine config` then:

1) it needs a better name that makes it clear that it's outputting a shell script
2) it should just output `export DOCKER_HOST=tcp://x.x.x.x:2376 DOCKER_AUTH=identity`

**Comment by sthulb** [comment]
@bfirsh Firstly, perhaps `config-shell`

Secondly, if it just outputs an export, one would have to restart their shell for it to pick it up, creating the workflow of:
1. machine create ...
1. exit shell
1. reopen shell
1. docker run ...

**Comment by bfirsh** [comment]
True.

I think we should aim to get Machine to automatically configure Docker. This is a hack which can use as a last resort.

**Comment by sthulb** [comment]
For that, we need docker to be changed to allow for your proposal from docker/docker#7232

**Comment by SvenDowideit** [comment]
I'd propose `$(machine shellinit)` _only_ because thats what `boot2docker` has had, so many users are used to it.

**Comment by ehazlett** [comment]
For now, we are using the `machine config` command (not shell init as it just passes args to the Docker CLI and nothing in the environment) and swarm is doing the same.  The long term solution is support in the engine.

**Comment by parabuzzle** [comment]
+1

Also, I may have created a duplicate (or augmentation) to this issue yesterday: https://github.com/docker/machine/issues/1416

**Comment by nathanleclaire** [comment]
I am closing this issue as I think it's "as good as it's going to get" in Machine right now and further solutions would mandate support in Docker itself.
