### ISSUE TITLE
Proposal: Commands with "token://" should error out if "//" is omitted

### ISSUE THREAD

**Issue by dockermikeg** [docker/machine#1604]
The "--swarm-discovery token://" option should terminate with an error message if the user does not specify "//".

I have watched two people complete the Swarm "Getting Started" guide, and both specified "token:flkajdkasdl" instead of "token://flkajdkasdl".

For both cases, the individuals were confused by the documentation, and thought the '//' meant that the token value was a comment. They didn't realize that // is required.

To avoid confusion, the command should terminate with an error when 'token://' does not include the double-slashes.

**Comment by hairyhenderson** [comment]
Indeed, the `--swarm-discovery` argument needs to begin with an URL-ish scheme prefix - swarm requires it. We should probably check this as soon as possible when `create` starts.

**Comment by nathanleclaire** [comment]
Yep, I'm always for more validation when we can get it.  Probably we could introduce at least a little validation via regex.

**Comment by hairyhenderson** [comment]
_PR incoming..._
