### ISSUE TITLE
Debian provision. systemd managing

### ISSUE THREAD

**Issue by akolpakov** [docker/machine#1607]
I have a Debian 7 instance in my VPS which was not created with ``docker-machine``.
I'm trying to import this instance with:
```bash
docker-machine create -d generic [connection params]
```
But I'm getting the error:
```bash
configuring auth
...
Using SSH client type: external
About to run SSH command:
sudo systemctl daemon-reload
...
SSH cmd err, output: exit status 1: sudo: systemctl: command not found
```

After some investigation I realised that ``create`` script is trying to install package ``docker-engine``. This package depends on ``init-system-helpers (>= 1.18~)``. Installing of package ``init-system-helpers`` REMOVES package ``systemd`` from the system, that's why ``systemctl: command not found``

Package ``init-system-helpers`` provides some wrapper around ``systemctl``. I'm new in docker, but maybe ``docker-engine`` used to ``systemd`` directly, but now it uses ``init-system-helpers``. I think ``docker-machine`` needs to be reviewed according this changes.

**Comment by FrenchBen** [comment]
This may not be the *exact* solution you were looking for, but it's fairly easy to add an existing VPS if docker is configured on it:
https://docs.docker.com/machine/#adding-a-host-without-a-driver

**Comment by ehazlett** [comment]
This is probably due to the OS version.  Debian 8+ is needed (http://docs.docker.com/machine/#specify-a-base-operating-systems).

**Comment by nathanleclaire** [comment]
Yes, unfortunately we don't have any support for Debian <8 today.  Please feel free to open a separate ticket for that with some details on how you feel we might be able to accomplish that in the repo.
