### ISSUE TITLE
libmachine: what does host.Name != host.Name mean in filestore_test.go?

### ISSUE THREAD

**Issue by skatsuta** [docker/machine#1614]
In https://github.com/docker/machine/blob/master/libmachine/filestore_test.go#L231-L233 what does the test below mean?

```go
if host.Name != host.Name {
    t.Fatalf("Active host is not 'test', got %s", host.Name)
}
```

I don't understand why the condition is this way.

**Comment by nathanleclaire** [comment]
Probably search and replace error

**Comment by nathanleclaire** [comment]
It's safe to say that taking that out would probably get merged right away

**Comment by skatsuta** [comment]
@nathanleclaire Thanks! I see.
I think it's better to modify one of `host.Name`s to `hostTestName` instead of to remove it. I'll create a PR.
