### ISSUE TITLE
Move `goauth2/oauth` dependency to `golang.org/x/oauth2`

### ISSUE THREAD

**Issue by timfallmk** [docker/machine#1628]
https://code.google.com/p/goauth2/ is depreciated (along with all of code.google.com), and is being moved to read-only mode on August 25 in preparation for removal. We need to move this dependency to https://godoc.org/golang.org/x/oauth2, the suggested alternative.

**Comment by dgageot** [comment]
This was done on the google driver.
Digital ocean driver is still using it though.
