### ISSUE TITLE
Creating openstack machine leads to maximum number of retries exceeded (it worked with 0.2)

### ISSUE THREAD

**Issue by AxelVoitier** [docker/machine#1632]
Hi guys,

Using docker-machine-0.3.0 I can not create anymore openstack machines. It fails on some kind of timeout.
```
$ ./docker-machine_linux-amd64-0.3 create -d openstack --openstack-flavor-name="m1.small" --openstack-image-name="Ubuntu-14.04.2" --openstack-ssh-user=ubuntu cvl-iceda-everware01
Creating machine...
Error creating machine: Maximum number of retries (50) exceeded
You will want to check the provider to make sure the machine and associated resources were properly removed.
```
But then the machine actually appears created in my openstack dashboard.

I still had the 0.2 binaries around and I tried with it, and it worked:
```
$ ./docker-machine_linux-amd64-0.2 create -d openstack --openstack-flavor-name="m1.small" --openstack-image-name="Ubuntu-14.04.2" --openstack-ssh-user=ubuntu cvl-iceda-everware
INFO[0009] Creating machine...                          
INFO[0747] "cvl-iceda-everware" has been created and is now the active machine. 
INFO[0747] To point your Docker client at it, run this in your shell: eval "$(docker-machine env cvl-iceda-everware)" 
```

And by the way, it took quite a lot of time (10-20 minutes, it is slow in our openstack installation because of network/DNS registration) to successfully create this machine with 0.2.
While with 0.3 I got the error rather quickly.

Seems to me the timeout is not letting enough time to the openstack driver to create the machine. And there does not seem to be a flag to actually increase the number of retries.

Cheers,
Axel

**Comment by ddaze** [comment]
Hey,
If PR  #1642 gets accepted you can use `--openstack-connection-retries`.
The waiting time between retries is 5 seconds.
