### ISSUE TITLE
docker-machine network stack not working with a fixed host-only network adapter

### ISSUE THREAD

**Issue by mrumpf** [docker/machine#1635]
In the corporate environment, security regulations are very strict. I cannot create arbirary "Host-Only Network" adapters because this is not allowed by the security settings. The VPN client pops-up, terminating all network connections until I deactivate the new "Host-Only Network" adapter. 
The only chance I have is to install, via the company software distribution tool, a fixed host-only network 169.254.0.20/24.

I configured the Host-Only Network adapter to assign IP addresses via DHCP in the range from 169.254.0.100 to 169.254.0.200. That means that all the generated VMs have an IP address in this range.

That means all my docker-machine vms need to use the same host-only network adapter and must not try to create its own one. As far as I understand the docs, this can be achieved with the parameter --virtualbox-hostonly-cdr

     docker-machine create dev --driver virtualbox --virtualbox-hostonly-cidr "169.254.0.20/24"

This seems to work basically as docker-machine does not try to create its own Host-Only Network, instead it gets the one, I mentioned above.

When I access the VM afterwards via 

    docker-machine ssh dev

the network does not work as expected: 

    docker@dev:~$ nslookup google.de 
    Server:    10.xx.yy.zz
    Address 1: 10.xx.yy.zz <hostname>
    nslookup: can't resolve 'google.de'

I'm a little bit stuck here, is the parameter "--virtualbox-hostonly-cidr" known to have some issues or should this work out of the box?
The consequence is that docker cannot download any images so that the docker host is currently useless.

**Comment by ehazlett** [comment]
If the lookup is failing this seems to be a DNS issue.  Can you lookup any addresses from within the machine VM?

**Comment by mrumpf** [comment]
This is really strange! I started the docker-machine image again to test your suggestion and now the DNS resolving works...

   ping www.google.de
   PING www.google.de (216.58.209.163): 56 data bytes
   ^C--- www.google.de ping statistics ---
   2 packets transmitted, 0 packets received, 100% packet loss

And nslokup works as well

    nslookup google.de
    Server:    10.33.255.29
    Address 1: 10.33.255.29 xxx.yyy.company.com

    Name:      google.de
    Address 1: 173.194.113.183 ham02s12-in-f23.1e100.net
    Address 2: 173.194.113.184 ham02s12-in-f24.1e100.net
    Address 3: 173.194.113.191 ham02s12-in-f31.1e100.net
    Address 4: 173.194.113.175 ham02s12-in-f15.1e100.net
    Address 5: 2a00:1450:4005:800::100f ham02s13-in-x0f.1e100.net

And  wget works as well. The only thing remaining seems to be the proxy configuration.
Sorry for wasting your time.
