### ISSUE TITLE
"Too many retries" message should be more specific

### ISSUE THREAD

**Issue by rvesse** [docker/machine#1636]
During a `docker-machine create` the create fails with the following output:

```
> docker-machine create -d generic --generic-ip-address 10.0.1.101 node01
Importing SSH key...
Error creating machine: Too many retries.  Last error: Maximum number of retries (60) exceeded
You will want to check the provider to make sure the machine and associated resources were properly removed.
```

This error message is unhelpful because it doesn't tell me anything useful about what failed e.g. what was Machine trying to do when it ran out of retries?

If I then run `docker-machine ls` the machine is listed:

```
NAME         ACTIVE   DRIVER    STATE     URL                     SWARM
node01            generic   Running   tcp://10.0.1.101:2376   
```

But it does not have a working configuration as `docker-machine env` fails:

```
docker-machine env urika-xa01
open /home/users/rvesse/.docker/machine/machines/node01/ca.pem: no such file or directory
```

**Comment by carlosamartins** [comment]
It happened the same error with me. I am using vagrant on windows machine and the vagrant relative path is "/vagrant".

```docker-machine create -d generic \```
 ```--generic-ssh-user vagrant \```
 ```--generic-ssh-key /vagrant/.vagrant.d/insecure_private_key \```
 ```--generic-ip-address 192.168.226.37 \```
 ```--engine-install-url "https://test.docker.com" \```
 ```vmtest```

Importing SSH key...
Error creating machine: Too many retries.  Last error: Maximum number of retries (60) exceeded
You will want to check the provider to make sure the machine and associated resources were properly removed.
vagrant@vagrant-ubuntu-trusty-64:~$ docker-machine ls
NAME      ACTIVE   DRIVER       STATE     URL                                      SWARM
vmtest    generic  Running                tcp://192.168.226.37:2376
vagrant@vagrant-ubuntu-trusty-64:~$ docker-machine env vmtest
open /home/vagrant/.docker/machine/machines/vmtest/ca.pem: no such file or directory

**Comment by jeanlaurent** [comment]
Closing this, since error message display has been emhanced especially during create.

Feel free to re-open if this still does not work with a recent 0.5.6+ version of `docker-machine`
