### ISSUE TITLE
Boot2Docker URLs should allow file:/// URI syntax

### ISSUE THREAD

**Issue by huslage** [docker/machine#1638]
`docker-machine create -d vmwarefusion --vmwarefusion-cpu-count "2" --vmwarefusion-memory-size "2048" --vmwarefusion-boot2docker-url "file:///Users/huslage/Downloads/boo2docker-vmware.iso" localdev ` does not work as I would expect:

```
Downloading boot2docker-vmware.iso from file:///Users/huslage/Downloads/boo2docker-vmware.iso...
Error creating machine: open /Users/huslage/Downloads/boo2docker-vmware.iso: no such file or directory
You will want to check the provider to make sure the machine and associated resources were properly removed.
➜  ~  ls /Users/huslage/Downloads/boot2docker-vmware.iso 
/Users/huslage/Downloads/boot2docker-vmware.iso
```

**Comment by nathanleclaire** [comment]
It should work fine, so this seems to be bug to me.

**Comment by ehazlett** [comment]
This should work.  I've used it.  Can you try without the quotes?  That might be causing an issue.

**Comment by ehazlett** [comment]
@huslage this is working for me with the 0.4.0-rc2.  Can you try again with the latest RC2?

**Comment by huslage** [comment]
Looks ok now.

On Thu, Aug 6, 2015 at 9:15 PM, Evan Hazlett <notifications@github.com>
wrote:

> @huslage <https://github.com/huslage> this is working for me with the
> 0.4.0-rc2. Can you try again with the latest RC2?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/docker/machine/issues/1638#issuecomment-128554285>.
>



-- 
Aaron Huslage
Solution Architect - Docker, Inc.
+1-919-600-1712

**Comment by nathanleclaire** [comment]
![](http://assets.sbnation.com/assets/2182797/lbjallstar2.gif)
