### ISSUE TITLE
"active" and "ls" use different checks for active machine

### ISSUE THREAD

**Issue by ilkka** [docker/machine#1651]
Just noticed when commenting on brikis98/docker-osx-dev#77 that the "active" and "ls" commands use different methods for determining if a machine is active or not. Don't know if this is intentional, but for "active" using Filestore, only the value of DOCKER_HOST is checked against the host's URL. For "ls", `attemptGetHostState` in libmachine/host checks both the URL and also that the machine is not in state "Stopped". When DOCKER_HOST is set but e.g. the VM it points to is stopped, the commands now report slightly confusing results.

**Comment by nathanleclaire** [comment]
Good catch.  They should definitely use the same, shared method.

**Comment by mattjmcnaughton** [comment]
:+1: 

I'd love to call #dibs on this if that's cool (idk if machine uses #dibs like docker) - been looking to get involved with this project for a while and this seems like a good first issue.

**Comment by nathanleclaire** [comment]
If you're interested, go for it @mattjmcnaughton !  I've been treating the "help-wanted" tag as kind of a "Hey, these issues are relatively non-controversial and might be worth looking into for someone wanting to contribute to Machine".
