### ISSUE TITLE
DockerMachine boot2docker issue

### ISSUE THREAD

**Issue by mkscala** [docker/machine#1654]
I have installed DOCKER HOST with docker-machine virutalbox and then when i use docker-py client to create a container getting the below error
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', BadStatusLine('\x15\x03\x01\x00\x02\x02\n',)

**Comment by ehazlett** [comment]
You need to make sure you configure it for TLS.  See here https://docker-py.readthedocs.org/en/latest/tls/
