### ISSUE TITLE
SSH proxy support for `create` and `upgrade`

### ISSUE THREAD

**Issue by brint** [docker/machine#1665]
I'm hoping that a "No TCP SSH check" flag could be added to allow for SSH proxy support with `docker-machine create`. Example `~/.ssh/config`:

```
Host * !192.168.* !10.*
    ProxyCommand ssh -aY bastion 'nc %h %p'
```

I don't have any experience with go to write this myself.

#### Skipping the TCP SSH check
For users in different environments, the only way they can access devices may be through a bastion of some kind leveraging a SSH or SOCKS5 proxy. Currently machine leverages a [WaitForTCP check](https://github.com/docker/machine/blob/226dc8d15ac04a5c488b06aeca7b5169a67ef685/drivers/utils.go#L73) that calls [ssh.go](https://github.com/docker/machine/blob/226dc8d15ac04a5c488b06aeca7b5169a67ef685/ssh/ssh.go#L13) to run the TCP checks, and it will not move forward with provisioning until this test passes. Being able to skip this would allow for users on networks with policies that more strictly restrict outbound SSH traffic to access nodes. 

Note: I have verified that the nodes being spun are accessible via SSH when accessed via the proxy using the `~/.docker/machine/machines/<SERVER NAME>/id_rsa` key.

Here's what it looks like today with the `-D` flag:
```
$ docker-machine -D --native-ssh create --driver rackspace \
                      --rackspace-api-key $OS_API_KEY \
                      --rackspace-username $OS_USERNAME \
                      --rackspace-region $OS_REGION_NAME \
                      --swarm \
                      --swarm-master \
                      --swarm-discovery token://$TOKEN \
                      swarm-master
Instantiating Rackspace driver.		 caCert=/Users/brint/.docker/machine/certs/ca.pem machineName=swarm-master privateKey=/Users/brint/.docker/machine/certs/ca-key.pem storePath=/Users/brint/.docker/machine/machines/swarm-master
Creating Key Pair...		 Name=swarm-master-9f895aa148c950e46cd3f74bee2055721163fe79a2476896d5d35b9d01002f39
Authenticating to Rackspace.		 Username=<USERNAME>
Creating OpenStack instance...		 FlavorId=general1-1 ImageId=598a4282-f14b-4e50-af4c-b3e52749d9f9
Creating machine...
Waiting for the OpenStack instance to be ACTIVE...		 MachineId=33d231d9-e1f9-4289-8a0e-79edf538174b
Looking for the IP address...		 MachineId=33d231d9-e1f9-4289-8a0e-79edf538174b
IP address found		 IP=23.253.230.169 MachineId=33d231d9-e1f9-4289-8a0e-79edf538174b
Get status for OpenStack instance...		 MachineId=33d231d9-e1f9-4289-8a0e-79edf538174b
State for OpenStack instance		 MachineId=33d231d9-e1f9-4289-8a0e-79edf538174b State=ACTIVE
Getting to WaitForSSH function...
Testing TCP connection to: 23.253.230.169:22
Testing TCP connection to: 23.253.230.169:22
Testing TCP connection to: 23.253.230.169:22
Testing TCP connection to: 23.253.230.169:22
Testing TCP connection to: 23.253.230.169:22
Testing TCP connection to: 23.253.230.169:22
Testing TCP connection to: 23.253.230.169:22
Testing TCP connection to: 23.253.230.169:22
```

The `Testing TCP connection to: 23.253.230.169:22` seems to go on forever. I ctrl+c'd out of it after 5+ minutes.

I have tried using `docker-machine upgrade` as a temporary workaround, but it fails as well while proxying the SSH connection.

Both `docker-machine ssh` and `docker-machine scp` work once a machine is up.

`docker-machine` version:
```
$ docker-machine --version
docker-machine version 0.3.1 (HEAD)
```

**Comment by ehazlett** [comment]
I'm curious how Machine would continue to provision if it cannot reach the instance on port 22?

**Comment by brint** [comment]
Thanks for the response! This is definitely a TL;DR issue :)

In this case, I can only talk to things via SSH if I jump through a bastion/jump box. I cannot SSH to things directly due to network policies. This is why the direct TCP connection from my workstation to port 22 is failing.

If we are able to skip the TCP connection check, and the provisioning follows my client SSH config to connect to the box for provisioning, Machine will succeed. Case and point: When I use `docker-machine create`, I can actually login via `docker-machine ssh` once the VM becomes active. However, provisioning fails since it's running trying to make a direct TCP connection from my workstation to the VM. Does that make sense?

**Comment by nathanleclaire** [comment]
So if I understand correctly, you can SSH into a bastion box, but direct connection to other hosts is choked out by a firewall?

**Comment by brint** [comment]
@nathanleclaire: That's right! Direct connections to to port 22 for anything other than the jump host/bastion are explicitly blocked by the corporate firewall. Our SSH traffic has to go through a bastion. This article is probably the best description of what we have to do so we can proxy through the jump hosts: 

https://en.wikibooks.org/wiki/OpenSSH/Cookbook/Proxies_and_Jump_Hosts#Passing_through_a_gateway_using_netcat_mode

If we have an option to skip the TCP check to port 22 within Machine (since that won't abide by our `~/.ssh/config`), I think it will allow us to provision nodes using docker-machine. An example of an SSH config is included in the first comment. `docker-machine ssh` does work on VM's created using `create`, even though the actual docker provisioning is never completes due to the TCP check of 22 failing.

Here's another project where we had to implement the same thing:

https://github.com/test-kitchen/kitchen-rackspace#usage

You'll see the `no_ssh_tcp_check` option. That's something that we had to add to get around this problem in corporate network environments where egress traffic is more strictly controlled. 

What this looks like from our shell:

Telnet to port 22 rejected by firewall:
```
$ telnet 1.2.3.4 22
Trying 1.2.3.4...
telnet: connect to address 1.2.3.4: Connection refused
telnet: Unable to connect to remote host
```
SSH connections hops through a bastion/jump box based on our SSH client config and connects successfully:
```
$ ssh 1.2.3.4
Warning: Permanently added 'bastion' (RSA) to the list of known hosts.
Warning: Permanently added '1.2.3.4' (RSA) to the list of known hosts.
Last login: Tue Aug 11 22:50:47 2015 from bastion
brint@host:~$
```

We :heart: running things locally. I'd be happy to do jump on a hangout to go into more detail if it would help.

**Comment by prologic** [comment]
I'd like to see a feature to facilitate this too. In our production AWS environment I cannot use ``--private-address-only`` as the ``WaitForSSH()`` function never succeeds.

**Comment by nathanleclaire** [comment]
@prologic @brint Would https://github.com/docker/machine/pull/1685 solve it for you?  It uses only SSH to check daemon availability without dialing the IP:port directly.

**Comment by brint** [comment]
Hi @nathanleclaire - I might be wrong on this one, but it doesn't look like it would be a fix for this SSH issue. It looks like #1685 fixes instances where machine is waiting for the docker daemon to show up as responsive on a port.

In reading through the branch, it looks like SSH connections will still try the TCP check of port 22 prior to SSH'ing. Here was the path I followed to jump to this conclusion:

https://github.com/nathanleclaire/machine/blob/daemon_wait_over_ssh/libmachine%2Fhost.go#L125

https://github.com/nathanleclaire/machine/blob/daemon_wait_over_ssh/drivers%2Futils.go#L79-L80

https://github.com/nathanleclaire/machine/blob/daemon_wait_over_ssh/drivers%2Futils.go#L66-L69

https://github.com/nathanleclaire/machine/blob/daemon_wait_over_ssh/ssh/ssh.go#L13

**Comment by nathanleclaire** [comment]
Ah, yes, sorry, I had confused that issue with a general direction of removing non-SSH dialing.  I think I would definitely like to remove the TCP check.

**Comment by nathanleclaire** [comment]
This should now be fixed on master (no more lone TCP dial)
