### ISSUE TITLE
Machine should have --ssh-user flag common to all drivers

### ISSUE THREAD

**Issue by nathanleclaire** [docker/machine#1672]
There are many driver flags which are on the order of `--amazonec2-ssh-user`, `--digitalocean-ssh-user`, etc.  They all seem to do mostly the same thing so this should probably be a "global" create flag like `--swarm` is, for instance.

**Comment by ehazlett** [comment]
:+1:

**Comment by dalanmiller** [comment]
Also agree here.

**Comment by dgageot** [comment]
Duplicate of https://github.com/docker/machine/issues/489
