### ISSUE TITLE
VirtualBox DHCPServer always uses x.x.x.1, despite getRandomIPinSubnet()

### ISSUE THREAD

**Issue by csakoda** [docker/machine#1673]
I observed this on Windows when using the virtualbox driver.  The host-only adapter would default come up on 192.168.99.1, but then also set the DHCP Server in VBox to use 192.168.99.1 as its address.  This causes Windows to detect the adapter as having a dupe IP on the network, which then causes it to re-negotiate to less-than-useful 169.254.x.x ip.  

Shouldn't this line (https://github.com/docker/machine/blob/master/drivers/virtualbox/virtualbox.go#L747) be
```
			dhcpAddr = net.IPv4(nAddr[0], nAddr[1], nAddr[2], byte(n))
```

The use of `n` seems spurious otherwise?  I can submit a patch for this if it's correct.

**Comment by nathanleclaire** [comment]
cc @ehazlett WDYT

**Comment by ehazlett** [comment]
Yes, @csakoda I believe that is correct.  I'll add this to the 0.5 milestone.  Thanks!

**Comment by dgageot** [comment]
@ehazlett was this issue closed by [this PR](https://github.com/docker/machine/pull/1674)?

**Comment by nathanleclaire** [comment]
@dgageot Yep nice catch
