### ISSUE TITLE
Pull fails when switching networks

### ISSUE THREAD

**Issue by saada** [docker/machine#1675]
When switching networks, I have to restart my virtualbox docker-machine.

Here's someone else experiencing the same issue
http://stackoverflow.com/questions/24390329/cant-pull-docker-image-no-route-to-host

Here's the error message
```
Get https://index.docker.io/v1/repositories/library/mysql/images: dial tcp: lookup index.docker.io on 192.168.6.6:53: read udp 192.168.6.6:53: i/o timeout
```

After running
```
docker-machine restart dev
```

Running `docker pull` starts working again

**Comment by ehazlett** [comment]
Sorry for the issue.  Unfortunately, this is related to VirtualBox and it's resolution lookup and not much we can do I think.  What you did is the fix.  Thanks for reporting.
