### ISSUE TITLE
"docker-machine env" not generating NO_PROXY

### ISSUE THREAD

**Issue by vehovmar** [docker/machine#1676]
Bug report
docker-machine version 0.4.0 (9d0dc7a)
Windows

    boot2docker shellinit
was generating export for NO_PROXY with IP of the VM

    docker-machine env
does not do the same.

Result is that unless I do it manually I'm not able to connect to the docker daemon:

    An error occurred trying to connect: Get https://192.168.99.100:2376/v1.20/info: Proxy Error ( The specified Secure Sockets Layer (SSL) port is not allowed. Forefront TMG is not configured to allow SSL requests from this port. Most Web browsers use port 443 for SSL requests.  )

**Comment by goelvijay** [comment]
I am also having same issue, while installing in windows....please suggest work around?

**Comment by vehovmar** [comment]
For now I solved it by adding following to my .bash_profile

    export NO_PROXY="$(docker-machine ip <your_machine_name>)"

**Comment by nathanleclaire** [comment]
This is fixed by the `--no-proxy` flag for `docker-machine env`
