### ISSUE TITLE
docker-machine ls/inspect command to show boot2docker version

### ISSUE THREAD

**Issue by arun-gupta** [docker/machine#1677]
It would be useful to show the `boot2docker.iso` version being used by each docker machine. This could be an enhancement to `docker-machine ls` command.

This will allow to see the existing versions and then upgrade them as necessary.

It could also be optionally shown via `docker-machine inspect` command.

**Comment by nathanleclaire** [comment]
Why not something like `docker-machine ssh rc2 -- cat /etc/os-release`?

**Comment by arun-gupta** [comment]
OK, that's helpful. Can this information be exposed in `inspect`?

**Comment by dgageot** [comment]
Fixed in `ls` in https://github.com/docker/machine/pull/2442
