### ISSUE TITLE
How to portforward in VBoxManage?

### ISSUE THREAD

**Issue by DanielHKim** [docker/machine#1679]
I used to be able to do this with boot2docker on Mac OS X:

`VBoxManage modifyvm "boot2docker-vm" --natpf1 "tcp-port8000,tcp,,8000,,8000"`

I run Django in a docker container via docker-compose, and I use the above command whenever I need to do a clean initial setup of my project so that instead of having to always go to the VM's IP at port 8000, I can just go to localhost:8000. However, when trying to do the same sort of thing using docker-machine, I get errors. Let's say I do:

```
docker-machine create --driver virtualbox dev
VBoxManage modifyvm "dev" --natpf1 "tcp-port8000,tcp,,8000,,8000"
```

Then I get this error:

```
VBoxManage: error: The machine 'dev' is already locked for a session (or being unlocked)
VBoxManage: error: Details: code VBOX_E_INVALID_OBJECT_STATE (0x80bb0007), component MachineWrap, interface IMachine, callee nsISupports`
VBoxManage: error: Context: "LockMachine(a->session, LockType_Write)" at line 492 of file VBoxManageModifyVM.cpp
```

What's the proper way to do what I used to be able to do with the boot2docker-vm?

**Comment by UserTaken** [comment]
`VBoxManage modifyvm` is for when the VM is off. Use `VBoxManage controlvm` when it is running.

`vboxmanage controlvm dev natpf1 "django,tcp,127.0.0.1,8000,,8000"`

**Comment by DanielHKim** [comment]
Yeah, that's what I also just found out. I'm not sure of all the differences between boot2docker and docker-machine but apparently the create command has the VM running already, whereas the old boot2docker init command apparently didn't.
