### ISSUE TITLE
No clear way to install Docker Machine

### ISSUE THREAD

**Issue by nathanleclaire** [docker/machine#1680]
This must have gotten lost in the release kerfluffle, but there is no clear way to install machine at https://docs.docker.com/machine (which is where the README for Machine points).  We should link users to the Toolbox at the top of that page, and continue to include the information about how to install the binaries manually as well.

cc @ehazlett @moxiegirl

**Comment by moxiegirl** [comment]
Isn't this it?

![image](https://cloud.githubusercontent.com/assets/1347209/9241291/623f8742-4126-11e5-97af-29fa276a0841.png)

**Comment by thaJeztah** [comment]
I think the point is that, when you open the https://docs.docker.com/machine page, the menu is opened like this (and there's no "install" instructions in the menu or on the page);

![screen shot 2015-08-14 at 00 34 08](https://cloud.githubusercontent.com/assets/1804568/9263315/519e86f8-421c-11e5-91cc-e20ae67089cd.png)

**Comment by moxiegirl** [comment]
So, I don't think it is necessary to add an Install title.  The docs.docker.com splash page Links to all the install points for Machine. According to Google Analytics only 10% of the people who reach the actual install page got there from `/machine` or `machine/get-started`  --- major feeders are the root `/` at 20% and the `/kitematic` page at `19%`

**Comment by nathanleclaire** [comment]
I would still be more comfortable if we had an explicit link to the install instructions on the landing page, so I think I'm going to make a PR to add one.

**Comment by stain** [comment]
Here's the user experience from Linux:

* Used and installed Docker.. happy.
* Hear about Docker Machine
* https://www.docker.com/ -> Products -> https://www.docker.com/products/overview
* Docker Machine -> https://www.docker.com/docker-machine
* Get Machine (at bottom of page) -> https://docs.docker.com/machine/
* Well, nothing there on how to install.. s
* In menu on the left: Get Started with Docker Machine and a Local VM -> https://docs.docker.com/machine/get-started/
* It tells me to install VirtualBox, and then run `docker-machine`
* But I don't have docker-machine. How do I get it? 

On OS X and Windows the installers now bundle `docker-machine` -- however this only happened in the latest version, so people with older versions of Docker will have exactly the same baffling question as me.

**Comment by moxiegirl** [comment]
@stain Thank you for the feedback.  The overview now includes a link to the installation page.   https://github.com/docker/machine/pull/1830
