### ISSUE TITLE
"Active" star in ls output breaks UNIX-ness of program

### ISSUE THREAD

**Issue by nathanleclaire** [docker/machine#1682]
Notice that if you have an active machine something like this will return unreliable results:

```console
$ docker-machine ls | awk '{ print $3; }'
DRIVER
Running
Running
Stopped
Running
virtualbox
```

:frowning: 

`awk` delimits by whitespace so I think we should have a character to indicate non-active as well, or come up with another solution to make the output a bit more UNIX-ey.  Even though it's meant to be just for humans, I know of at least two or three examples of people parsing this output mechanically.

cc @ehazlett

**Comment by ehazlett** [comment]
Hmm.  Perhaps we leave off the asterisk and just rely on the `active` command instead?

**Comment by nathanleclaire** [comment]
Hm, it's hard to say what the right thing is.  I definitely like having a visual reference to indicate which machine is active, although on my computer I just put that information directly into $PS1

**Comment by mattjmcnaughton** [comment]
Just my opinion but I agree with @nathanleclaire about liking a visual indicator.

I personally think having a character to indicate non-active sounds like a good idea (maybe a - or an x) but thats just personal preference.

Once the desired behavior is decided I'd be happy to make a pr unless someone else wants to! Seems like a good issue for someone just beginning with machine contributing like myself haha

**Comment by thaJeztah** [comment]
Yup, I like *something* to indicate the active machine as well :-)

**Comment by skatsuta** [comment]
+1 for @nathanleclaire and @mattjmcnaughton 

What mark is easiest to recognize?

##### `-`

```
NAME            ACTIVE   DRIVER       STATE     URL                         SWARM
dev             *        virtualbox   Running   tcp://192.168.99.100:2376
swarm-master    -        virtualbox   Stopped                               swarm-master (master)
swarm-node-00   -        virtualbox   Stopped                               swarm-master
```

##### `x`

```
NAME            ACTIVE   DRIVER       STATE     URL                         SWARM
dev             *        virtualbox   Running   tcp://192.168.99.100:2376
swarm-master    x        virtualbox   Stopped                               swarm-master (master)
swarm-node-00   x        virtualbox   Stopped                               swarm-master
```

##### `.`

```
NAME            ACTIVE   DRIVER       STATE     URL                         SWARM
dev             *        virtualbox   Running   tcp://192.168.99.100:2376
swarm-master    .        virtualbox   Stopped                               swarm-master (master)
swarm-node-00   .        virtualbox   Stopped                               swarm-master
```

Hmm... I'd prefer `-` but I don't think it's best...

**Comment by thaJeztah** [comment]
I think I like `-` best too (at a quick glance)

**Comment by nathanleclaire** [comment]
Nice @skatsuta.  I definitely think I prefer `-` of the options discussed so far.
