### ISSUE TITLE
Can't check for machine status because of missing config.json

### ISSUE THREAD

**Issue by frapontillo** [docker/machine#1688]
Description of problem: Can't check for machine status because of missing `~/.docker/machine/machines/config.json`.

`docker version`:
```
Client:
 Version:      1.8.0
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   0d03096
 Built:        Tue Aug 11 17:17:40 UTC 2015
 OS/Arch:      darwin/amd64

Server:
 Version:      1.8.0
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   0d03096
 Built:        Tue Aug 11 17:17:40 UTC 2015
 OS/Arch:      linux/amd64
```

`docker info`:
```
Containers: 6
Images: 220
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 232
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.0.9-boot2docker
Operating System: Boot2Docker 1.8.0 (TCL 6.3); master : 7f12e95 - Tue Aug 11 17:55:16 UTC 2015
CPUs: 4
Total Memory: 995.9 MiB
Name: default
ID: EVTJ:P5MB:TPSK:YLMW:4QFH:DULF:AXWD:TJCC:7CPQ:KUNM:WBME:PMM4
Debug mode (server): true
File Descriptors: 10
Goroutines: 16
System Time: 2015-08-13T07:21:24.578789115Z
EventsListeners: 0
Init SHA1: 
Init Path: /usr/local/bin/docker
Docker Root Dir: /mnt/sda1/var/lib/docker
Labels:
 provider=virtualbox
```

`uname -a`:
```
Darwin Batmans-MacBook-Pro.local 14.4.0 Darwin Kernel Version 14.4.0: Thu May 28 11:35:04 PDT 2015; root:xnu-2782.30.5~1/RELEASE_X86_64 x86_64
```

Environment details (AWS, VirtualBox, physical, etc.):
VirtualBox on a MacBook Pro.

Steps to Reproduce:
1. `docker-machine status`

Actual Results: the following is printed: `unable to load host: open /Users/fra/.docker/machine/machines/config.json: no such file or directory`

Expected Results: `docker-machine` should retrieve the status of the machine.

Additional info: I just upgraded from Docker 1.7, `docker` can boot and stop containers, everything looks like it's working if I start the Docker Quickstart Terminal, BUT the `docker-machine` (which should still be available outside of the quickstart terminal, right?).

**Comment by rvdmei** [comment]
I ran into the same problem and it is a bug, but not the bug you are reporting. `docker-machine status` is for retrieving the status of a single machine, so `docker-machine status dev` does work. When you omit the machine name, it should throw an error / help message. Use `docker-machine ls` for getting status of all machines.

**Comment by frapontillo** [comment]
Thank you @rvdmei, that solved the misunderstanding! :+1:
