### ISSUE TITLE
Machine creation fails with existing Virtualbox Interface

### ISSUE THREAD

**Issue by tinchou** [docker/machine#1691]
Sorry for the very vague report:
- I'm running Windows 8.1
- I was using Boot2docker to run Docker in my machine
- I downloaded docker-toolbox
- I tried creating the machine several times (from both Kitematic and Docker Quickstart terminal) but it failed
- I noticed it wasn't able to find the Virtualbox Interface # 14, so I went and deleted the Host-Only Ethernet Adapter from Virtualbox preferences
- I was able to create my machine at this point

**Comment by ehazlett** [comment]
Thanks for the feedback.  Unfortunately, this is common in VirtualBox with several host only adapters.  We are working to get more stability on the networking in VirtualBox.  I'm going to close this but thanks for reporting so others can try if needed.
