### ISSUE TITLE
Docker Toolbox Quickstart Terminal error parsing "128"

### ISSUE THREAD

**Issue by yoshutch** [docker/machine#1692]
I just tried installing Dockertoolbox and ran the Docker Quickstart Terminal which created a VM in virtual box but ran into an error that I recall was very similar when I attempted to use Boot2Docker about a year ago:

STDERR:
Error creating machine: strconv.ParseUint: parsing "128": value out of range
You will want to check the provider to make sure the machine and associated resources were properly removed.

I'm running Virtual Box version 5.0.0 on Windows 8.1 Enterprise (Intel Core i7, 16 GB RAM, 64-bit processor). If I remember correctly I had to edit some file saying that we can parse 128. But I don't know where or how.

![image](https://cloud.githubusercontent.com/assets/6410743/9255852/3cae502a-41a9-11e5-8ca8-e3b79fda5d6e.png)

**Comment by blitzd** [comment]
Also having this same error on Windows 10 using the Kitematic initial setup.

**Comment by EliSnow** [comment]
I experience the same problem with VirtualBox 4.3.30 under Windows 7. Perhaps related: the installer also encountered an error trying to migrate by Boot2Docker VM.

**Comment by blitzd** [comment]
Still an issue on 1.8.2 toolbox.

**Comment by fernandoigual** [comment]
Hi! I've the same problem with Windows 10. Nobody can help us?

**Comment by marx-freedom** [comment]
windows 10, virtualbox 5.0.2, toolbox 1.8.2a - same problem

**Comment by NicholasGW** [comment]
On Windows 7 with VBox 5, disabling IPv6 lets me at least get a boot2docker machine up.

**Comment by gmacario** [comment]
Fix via https://github.com/docker/machine/commit/b01442c6bbbb4210221954ecd513c76c1fa8c170

**Comment by scotty6435** [comment]
Why oh why oh why hasn't this been merged into a release yet? As far as I can see any Windows machine will fail because of this error!

**Comment by gmacario** [comment]
The fix is included in v0.5.0-rc3 so that should land on v0.5.0 when it is released
