### ISSUE TITLE
docker-machine ls timeout should be configurable.

### ISSUE THREAD

**Issue by nathanleclaire** [docker/machine#1696]
The current timeout for machines reporting state is 3 seconds.  This is intended to promote a relatively snappy UX.  However, this should be configurable in case the user has far away machines they want to include, e.g.:

```console
$ docker-machine ls --timeout=10
```

**Comment by mattjmcnaughton** [comment]
I'd love to tackle this if no one else is - working on a pr now!

**Comment by nathanleclaire** [comment]
Nice @mattjmcnaughton

**Comment by ehazlett** [comment]
@mattjmcnaughton thanks!

**Comment by mrumpf** [comment]
Under Windows 7 (VirtualBox) it seems that the timeout is too low. When I run the command ```docker-machine ls``` frequently I see that the virtual machine is running. When I wait 30 seconds and run the ls command again, I get a timeout for the same machine. Running the command again shows active again.

**Comment by chigix** [comment]
Same situation encountered as @mrumpf  said in windows 10. And with `docker-machine --native-ssh ls`, every thing works very well.

Thanks, @mrumpf , your suggestion provided is of great helpful.

**Comment by dgageot** [comment]
Fixed in https://github.com/docker/machine/commit/02c235b8b91e093fc185713e965fd17d7c462873
