### ISSUE TITLE
Add --ip argument to docker so `docker port` returns usable data

### ISSUE THREAD

**Issue by maximkulkin** [docker/machine#1697]
Currently if you have a docker machine running somewhere, when you run a container on that machine which exposes some port and then do `docker port <container ID> <port>` it will return something like "0.0.0.0:{port}" which is not very useful as you need to substitute "0.0.0.0" with real IP address of that docker machine. This can be fixed if you specify "--ip {address}" argument to `docker` where "address" is address of user facing interface. Then `docker port` will return proper IP+port combination.

So, the task is to modify docker startup scripts on docker machine image to add that "--ip" argument with proper IP address.

**Comment by ehazlett** [comment]
You can already do this with the `--engine-option` flag.  When creating, try `--engine-option ip=x.x.x.x`.  That should get what you need.

**Comment by maximkulkin** [comment]
Why this is not an automatic default behavior?
