### ISSUE TITLE
Error creating CentOS 7 Image with v0.4.0 on AWS

### ISSUE THREAD

**Issue by kacole2** [docker/machine#1698]
I'm using version 0.4.0. I've tried creating a CentOS Machine in both AWS and Digital Ocean. For some reason, it continually fails on AWS.

It's failing at `sudo systemctl restart docker`. Entire output is on this gist. https://gist.github.com/kacole2/378aac80a671ed8b76e5

However, it works fine on Digital Ocean. 

I just changed the Docker-Machine binary to v 0.3.1 and the deployment worked fine with CentOS 7 to AWS

**Comment by ehazlett** [comment]
This looks related to #1705.  We will need to handle certain distros that enable vs. ones that don't.

**Comment by EvanMcClure** [comment]
I attempted the workaround described by @kacole2, but it failed, too. I'm not sure if it's the same error because I never logged into the machine.

First, I downgraded docker-machine to 0.3.1:
```
$ docker-machine -v
docker-machine version 0.3.1 (40ee236)
```

Then, I attempted to create my machine:
```
$ docker-machine create -d amazonec2 --amazonec2-access-key 'MY_ACCESS_KEY' --amazonec2-secret-key 'MY_SECRET_KEY' --amazonec2-vpc-id MY_VPC_ID --amazonec2-region "us-west-2" --engine-storage-driver devicemapper --amazonec2-ami 'ami-c7d092f7' centos-machine-1
```

And I received the following error after:
```
Error creating machine: Too many retries.  Last error: Maximum number of retries (60) exceeded
You will want to check the provider to make sure the machine and associated resources were properly removed.
```

The machine exists in the list, which is good so that I can remove it:
```
$ docker-machine ls
NAME               ACTIVE   DRIVER       STATE     URL                         SWARM
centos-machine-1            amazonec2    Running   tcp://54.148.131.27:2376    
dev                *        virtualbox   Running   tcp://192.168.99.100:2376   
```

But, I can't SSH to it:
```
$ docker-machine ssh centos-machine-1
exit status 255
```

**Comment by dgageot** [comment]
Hi @kacole2, have you tried version 0.5.1?

**Comment by kacole2** [comment]
@dgageot sorry i have not yet. will attempt it at some point in the next week

**Comment by jeanlaurent** [comment]
in 0.5.6 the AWS driver has been significantly rewritten.

Sounds like this is working.

Please re-open if I missed something
