### ISSUE TITLE
Mac OS X Yosemite + VirtualBox + Docker Machine 0.4.0: `docker-machine create dev -d virtualbox` causing "No IP address found 4" error.

### ISSUE THREAD

**Issue by cjroth** [docker/machine#1699]
I am am getting the error `No IP address found 4` when I run `docker-machine -D create dev -d virtualbox`. If I go into the Virtual Box GUI I can see the box running successfully, so it seems to be a matter of connection or getting the IP address or port.

mac os x yosemite, fully up to date:
```
➜  ~ git:(master) ✗ sw_vers                                   
ProductName:	Mac OS X
ProductVersion:	10.10.5
BuildVersion:	14F27
````

docker-machine:
```
➜  ~ git:(master) ✗ docker-machine -v
docker-machine version 0.4.0 (9d0dc7a)
```

docker:
```
➜  ~ git:(master) ✗ docker -v
Docker version 1.8.1, build d12ea79
```

virtualbox: `4.3.30` (also tried with `5.0.2`)

`docker-machine -D create dev -d virtualbox` full output: https://gist.github.com/cjroth/26bb2e1261a3099c4f51

just the error:
```
STDERR: 
Using SSH client type: external
About to run SSH command:
ip addr show dev eth1
&{/usr/bin/ssh [/usr/bin/ssh -o PasswordAuthentication=no -o IdentitiesOnly=yes -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=quiet -o ConnectionAttempts=3 -o ConnectTimeout=10 -i /Users/chris/.docker/machine/machines/dev/id_rsa -p 50135 docker@localhost ip addr show dev eth1] []  <nil> <nil> <nil> [] <nil> <nil> <nil> <nil> false [] [] [] [] <nil>}
SSH cmd err, output: <nil>: 4: eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 08:00:27:72:fc:35 brd ff:ff:ff:ff:ff:ff
    inet6 fe80::a00:27ff:fe72:fc35/64 scope link 
       valid_lft forever preferred_lft forever

SSH returned: 4: eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 08:00:27:72:fc:35 brd ff:ff:ff:ff:ff:ff
    inet6 fe80::a00:27ff:fe72:fc35/64 scope link 
       valid_lft forever preferred_lft forever

END SSH

ERROR getting IP: %sNo IP address found 4: eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 08:00:27:72:fc:35 brd ff:ff:ff:ff:ff:ff
    inet6 fe80::a00:27ff:fe72:fc35/64 scope link 
       valid_lft forever preferred_lft forever

Error creating machine: Maximum number of retries (5) exceeded
You will want to check the provider to make sure the machine and associated resources were properly removed.
```

And here are the network settings in Virtual Box:

![screen shot 2015-08-13 at 17 02 07](https://cloud.githubusercontent.com/assets/582130/9261620/20d1acd8-41dd-11e5-9610-2c32e9444e65.png)

![screen shot 2015-08-13 at 17 02 14](https://cloud.githubusercontent.com/assets/582130/9261623/247857ce-41dd-11e5-8ee1-64640c638c35.png)

![screen shot 2015-08-13 at 17 03 41](https://cloud.githubusercontent.com/assets/582130/9261640/457bfa52-41dd-11e5-976e-b72c8c54d162.png)

docker-machine ls:
```
➜  ~ git:(master) ✗ docker-machine ls                         
error getting URL for host dev: exit status 255
NAME      ACTIVE   DRIVER       STATE     URL   SWARM
default            virtualbox   Stopped         
dev                virtualbox   Timeout      
```

docker-machine ssh:
```
STDERR: 
Using SSH client type: external
&{/usr/bin/ssh [/usr/bin/ssh -o PasswordAuthentication=no -o IdentitiesOnly=yes -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=quiet -o ConnectionAttempts=3 -o ConnectTimeout=10 -i /Users/chris/.docker/machine/machines/dev/id_rsa -p 22 docker@localhost] []  <nil> <nil> <nil> [] <nil> <nil> <nil> <nil> false [] [] [] [] <nil>}
exit status 255
```

**Comment by cjroth** [comment]
I was able to resolve this by removing all of the existing host-only networks in VirtualBox so that docker-machine created a new one from. To do this, go into VirtualBox and select Preferences -> Network -> Host-only Networks and delete them all. It will prompt you with a warning, just click Remove. Once they are all gone, destroy any docker instances and recreate them from scratch.

**Comment by buddhafinger** [comment]
Thanks dude, this helped me out.

**Comment by seregasheypak** [comment]
https://github.com/docker/toolbox/issues/273#issuecomment-157805699
Had pretty the same, solution above helped.

**Comment by Ninir** [comment]
@cjroth solution helped. :+1:

**Comment by iver3on** [comment]
@cjroth  solution can't help me . windows10   same info.

**Comment by iver3on** [comment]
`Running pre-create checks...
Creating machine...
(default) Copying C:\Users\31639\.docker\machine\cache\boot2docker.iso to C:\Users\31639\.docker\machine\machines\defaul
t\boot2docker.iso...
(default) Creating VirtualBox VM...
(default) Creating SSH key...
(default) Starting the VM...
(default) Check network to re-create if needed...
(default) Windows might ask for the permission to create a network adapter. Sometimes, such confirmation window is minim
ized in the taskbar.
(default) Found a new host-only adapter: "VirtualBox Host-Only Ethernet Adapter"
(default) Windows might ask for the permission to configure a network adapter. Sometimes, such confirmation window is mi
nimized in the taskbar.
(default) Windows might ask for the permission to configure a dhcp server. Sometimes, such confirmation window is minimi
zed in the taskbar.
(default) Waiting for an IP...`

**Comment by iver3on** [comment]
Waiting for an IP.  always!!!!!!!!!!!!!!!!!!!!!
