### ISSUE TITLE
Add --virtualbox-hostonly-name option

### ISSUE THREAD

**Issue by arabold** [docker/machine#1706]
This is a real tricky issue I have on my Windows 10 PC. For some odd reason I cannot create a default host-only network adapter in VirtualBox but it is always renamed "VirtualBox Host-Only Ethernet Adapter #4" (and # 5, # 6, etc.). If I try to create a new docker VM through docker-machine, this error kicks in which prevents the VM to be setup correctly. Instead an error message is shown:
"Error Renaming Connection - Cannot rename this connection. A connection with the name you specified already exists. Specify a different name."

I suggest to add a new option "`--virtualbox-hostonly-name`" through which we can control the name of the network interface adapter created. E.g. `docker-machine create --driver virtualbox --virtualbox-hostonly-name "VirtualBox Host-Only Ethernet Adapter #5" default`.By providing an explicit network adapter name the issue above can be worked around and we have also more flexibility in the creation of our virtual boxes. If I remember correctly Vagrant also has such an option as well.

**Comment by hqinnus** [comment]
I am encountering exactly the same problem. 
Attach image for the error, the popup window for the error is from VirtualBox, and after this, I will see new Host-only adapter on my windows 10 machine. 
I'm on DockerToolbox-1.8.2, using default VirtualBox comes with toolbox.

![error_renaming_connection](https://cloud.githubusercontent.com/assets/692001/9868103/8ac28b74-5ba7-11e5-8c90-5a3bdf1b0832.PNG)

**Comment by hqinnus** [comment]
Any walkaround for this issue? I cannot create any container after this, also Kitematic will have problem. I think all start from this issue

**Comment by shuaqiu** [comment]
I have this problem too, What can I do for next?

**Comment by juharris** [comment]
Here's how I got around this:
I had an old VirtualBox installed.  I uninstalled and deleted `%USERPROFILE%\.VirtualBox` (might not be necessary but I didn't need my old stuff).
I re-installed Docker Toolbox but I still had issues but Kitematic helped me.  This stackoverflow post might be helpful: http://stackoverflow.com/a/32597724/1226799
Basically if Kitematic runs into an error do the remove and retry option.

**Comment by urish** [comment]
+1

**Comment by ericmcdaniel** [comment]
I am also having this issue.

**Comment by pierophp** [comment]
+1

**Comment by nathanleclaire** [comment]
Hi all, aware of a few different issues around host only interfaces in Windows 10 and working on it.

**Comment by AlmogCohen** [comment]
+1

**Comment by mrsheepuk** [comment]
A few observations that might help:

* I find that this occurs after suspending and resuming my laptop
* Removing the docker-machine and removing all host-only interfaces in virtualbox then creating a new docker-machine seems to resolve the issue. 
* If I remember to stop the docker-machine before suspending the laptop then start it again when turning it back on, it seems to stay working.

This is using the very latest release of Virtualbox (v5.0.6).

**Comment by graphnode** [comment]
Deleted docker-machine and host-only interfaces in virtualbox and then created the docker-machine again getting this error: `Cannot rename this connection. The requested operation was made in the context of a transaction that is no longer active.`

**Comment by sjrocks** [comment]
Please share the workaround if any. I am facing similar issue with Docker Toolbox 1.9.0b.

Lost almost a day on doing this but with no positive results

**Comment by mrsheepuk** [comment]
@sjrocks I've found that, on Windows 10 at least, ensuring that I always run docker-machine in an administrator command prompt or powershell session, and if it doesn't work after resuming or rebooting my machine, I do `docker-machine start dev` to ensure it's running, then `docker-machine ssh dev` to SSH onto the machine, then `sudo shutdown -r now` on the resulting SSH session to restart the docker machine. When it comes back up, it then invariably seems to work.

Good luck!

**Comment by sjrocks** [comment]
Thanks @mrsheepuk !!!

**Comment by TomHart** [comment]
I had this issue after upgrading from Windows 8 to 10. A combination of the above methods worked.
I removed the `docker/certs` folder, removed VirtualBox, removed the `.VirtualBox` folder, and reinstalled VirtualBox.  Then, next time Kitematic loaded, it added the VM again and it all worked.

**Comment by dgageot** [comment]
With latest version of Docker Machine, this should really not be an issue anymore. Can you give it a shot?

**Comment by dgageot** [comment]
This is fixed in https://github.com/docker/machine/pull/2797
