### ISSUE TITLE
generateUsageHint feature

### ISSUE THREAD

**Issue by brint** [docker/machine#1708]
It would be nice if `generateUsageHint` would be aware of the flags used to generate the environment variables and include them in the [generateUsageHint](https://github.com/docker/machine/blob/b101c290114f35e94689d133f1365f10f2638f39/commands/env.go#L191-L217).

Example of current functionality:
```
$ docker-machine env --swarm swarm-master
export DOCKER_TLS_VERIFY="1"
export DOCKER_HOST="tcp://192.168.99.101:3376"
export DOCKER_CERT_PATH="/Users/brint/.docker/machine/machines/swarm-master"
export DOCKER_MACHINE_NAME="swarm-master"
# Run this command to configure your shell: 
# eval "$(docker-machine env swarm-master)"
```
The desired outcome would be to have the eval line reflect the command we ran:
```
# eval "$(docker-machine env --swarm swarm-master)"
```
This is a "nice to have".

**Comment by dgageot** [comment]
Fixed by https://github.com/docker/machine/pull/2084
