### ISSUE TITLE
Docker Toolkit:  All machines except VirtualBox say "Timeout"

### ISSUE THREAD

**Issue by davidcittadini** [docker/machine#1711]
docker-machine etc were working perfectly; I had one machine pointing to VirtualBox and two others to external services (DigitalOcean and Google Compute Engine).  I updated to Docker Toolbox on Mac OS X and now the VirtualBox machine says "Stopped" and the two external services say "Timeout".  I can get VirtualBox to run OK but the two external service are no longer working.  I have deleted them and reinstalled them and they still just say "Timeout".  The env command works and the "Timeout" machines all point to the correct IP Address etc..  So, how does one fix the Timeout issue with the new Docker Toolkit?

**Comment by nathanleclaire** [comment]
Hey @davidcittadini, sorry about this.  We introduced a timeout feature for Docker Machine state queries to keep non-responsive machines from hanging the UI, but the timeout duration seems quite aggressive (it is 3 seconds).  We want to make the timeout configurable (e.g. https://github.com/docker/machine/pull/1700), and figure out what the right thing to do by default is.  cc @ehazlett how do you think we should handle this?

**Comment by davidcittadini** [comment]
Thanks @nathanleclaire.  At the moment I am accessing all the Docker services via WiFi in hotels in Europe...and so being able to achieve a connection within 3 seconds is an absolute impossibility here :)  Look forward to something soon..thanks..

**Comment by serbrech** [comment]
I run on windows, in powershell, and mostly use the hyper-v drivers. All hyper-v machines have State timeout when running docker-machine ls, although I they are running and I can interact with them properly

**Comment by nathanleclaire** [comment]
Just FYI I think I will kick the timeout up higher in the next release and also potentially include an option to disable it.

**Comment by davidcittadini** [comment]
That would be great :)

**Comment by mbentley** [comment]
I've noticed a few mentions of the timeout being an annoyance; I also ran into this while being on wifi in Europe.  I would think that at least 10 or 15 seconds would be an acceptable default timeout as I would rather wait 10-15 seconds for proper information than have to try my same command again with the timeout parameter on a more regular basis when a few of my instances don't respond quite as quickly.

**Comment by nathanleclaire** [comment]
Yeah, I think I will kick the timeout up to 10-15 seconds.

**Comment by nathanleclaire** [comment]
It's 10 seconds now (will be included in next release): https://github.com/docker/machine/blob/master/commands/ls.go#L24

It's not configurable yet, but maybe we can file an issue for that specifically.

**Comment by serbrech** [comment]
I am a bit torn here. Just giving my feedback for considerations.

Although I want the proper information, if my console locks when this is
happening, it becomes quite annoying too.
I often run ls just to figure out the names of the machines I have. I don't
always need to know if it's up or not, if it times out or responds.

On Friday, 23 October 2015, Nathan LeClaire <notifications@github.com>
wrote:

> It's 10 seconds now (will be included in next release):
> https://github.com/docker/machine/blob/master/commands/ls.go#L24
>
> It's not configurable yet, but maybe we can file an issue for that
> specifically.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/docker/machine/issues/1711#issuecomment-150652918>.
>


-- 

Stéphane Erbrech

**Comment by nathanleclaire** [comment]
@serbrech Not a perfect solution, but if all you want to know is the names of the machines, `docker-machine ls -q` is the "quiet" mode which will just list their names without query status etc.
