### ISSUE TITLE
Proposal: Adding remote Hyper-V Server support

### ISSUE THREAD

**Issue by agup006** [docker/machine#1713]
Currently Docker Machine assumes that Hyper-V is on the same host that runs the docker-machine command. In a large enterprise environment deploying docker-machine to every Hyper-V host becomes unsustainable. As docker-machine is using mainly PowerShell commands to create and configure the Boot2Docker Virtual Machine a potential solution can involve using PowerShell remoting command before any other invoke. Additionally, there might be room for invoking [PowerShell DSC for Hyper-V](https://gallery.technet.microsoft.com/scriptcenter/xHyperV-Module-PowerShell-a646ad1a)?

Curious what others opinions are, might try some options in the following weeks.

**Comment by tomsowerby** [comment]
I've just run into this problem. Connecting to a remote Hyper-V host would be very useful.

**Comment by dgageot** [comment]
Duplicate https://github.com/docker/machine/issues/2985
