### ISSUE TITLE
Docker-Machine : "Error creating machine: exit status 1"

### ISSUE THREAD

**Issue by CaptainFeng** [docker/machine#1716]
Hello,

I am a new-comer. I am trying to use Docker.But I have some problem. 
When I click 'Quick Start Terminal', here is the error I am getting:

```
Starting machine default...
exit status 1
Started machines may have new IP addresses. You may need to re-run the `docker-machine env` command.
```
And I re-run the 'docker-machine env default, here is what i am getting:

```
default is not running. Please start this with docker-machine start default.
```

And I cat the log in ~/.docker/machine/machines/default/default/Logs/VBox.log:

```
VirtualBox VM 5.0.2 r102096 darwin.amd64 (Aug 13 2015 18:38:03) release log
00:00:00.022523 Log opened 2015-08-17T13:58:50.429529000Z
00:00:00.022524 Build Type: release
00:00:00.022537 OS Product: Darwin
00:00:00.022543 OS Release: 14.4.0
00:00:00.022548 OS Version: Darwin Kernel Version 14.4.0: Thu May 28 11:35:04 PDT 2015; root:xnu-2782.30.5~1/RELEASE_X86_64
00:00:00.022643 DMI Product Name: MacBookPro12,1
00:00:00.022696 DMI Product Version: 1.0
00:00:00.022704 Host RAM: 8192MB total, 3446MB available
00:00:00.022705 Executable: /Applications/VirtualBox.app/Contents/MacOS/VBoxHeadless
00:00:00.022705 Process ID: 7403
00:00:00.022706 Package type: DARWIN_64BITS_GENERIC
00:00:00.024332 Installed Extension Packs:
00:00:00.024343   None installed!
00:00:00.025363 Console: Machine state changed to 'Starting'
00:00:00.052800 SUP: Loading failed for VMMR0.r0 (/Applications/VirtualBox.app/Contents/MacOS/VMMR0.r0) rc=VERR_VMM_SMAP_BUT_AC_CLEAR
00:00:00.052936 PDMLdr: pdmR3LoadR0U: pszName="VMMR0.r0" rc=VERR_VMM_SMAP_BUT_AC_CLEAR szErr="SUPR3LoadModule: supLoadModule returned VERR_VMM_SMAP_BUT_AC_CLEAR"
00:00:00.052960 VMSetError: /Users/vbox/tinderbox/mac-rel/src/VBox/VMM/VMMR3/VM.cpp(595) int vmR3CreateU(UVM*, uint32_t, int (*)(UVM*, VM*, void*), void*); rc=VERR_VMM_SMAP_BUT_AC_CLEAR
00:00:00.052974 VMSetError: Failed to load VMMR0.r0
00:00:00.053155 ERROR [COM]: aRC=NS_ERROR_FAILURE (0x80004005) aIID={872da645-4a9b-1727-bee2-5585105b9eed} aComponent={ConsoleWrap} aText={Failed to load VMMR0.r0 (VERR_VMM_SMAP_BUT_AC_CLEAR)}, preserve=false aResultDetail=0
00:00:00.053286 Console: Machine state changed to 'PoweredOff'
00:00:00.055651 Power up failed (vrc=VERR_VMM_SMAP_BUT_AC_CLEAR, rc=NS_ERROR_FAILURE (0X80004005))
```

I am using macbook pro with yosemite.
Docker verison is 1.8.1, build d12ea79.
And I use Docker Toolbox.

Please help me to figure this out.
Thanks.

**Comment by vanrysss** [comment]
+1

**Comment by CaptainFeng** [comment]
@vanrysss I have tried reinstalling virtualbox and Docker Toolbox. But nothing changed.

**Comment by yanke-guo** [comment]
I believe VirtualBox 5 is incompatible with docker-machine. I solve this issue by installing old version VirtualBox 4.3

https://www.virtualbox.org/wiki/Download_Old_Builds_4_3

**Comment by CaptainFeng** [comment]
You are right. I tried VirtualBox 4.3. It works right.
It should be a problem of virtualbox 5.
Thanks.

**Comment by phildav** [comment]
This is an issue with virtualbox which is solved in test builds.
https://www.virtualbox.org/ticket/14412

I have just installed virtualbox from https://www.virtualbox.org/wiki/Testbuilds and it solved the issue.

**Comment by CaptainFeng** [comment]
@phildav Thank u. I will tried it.

**Comment by hrbu** [comment]
This is an issue for VirtualBox-5.0.2 on Windows-8.1 too. Upgrading to the current VirtualBox-Testbuild (5.0.3) solved the issue too. Thank you for that hint!!!

**Comment by gegere** [comment]
+1 Works!

**Comment by kanasite** [comment]
:+1:  thanks!

**Comment by hopsoft** [comment]
Virtualbox test builds as recommended by @phildav worked for me on OSX 10.10.4

**Comment by duynguyenvan** [comment]
I keep getting the problem on OSX 10.10.4
docker-machine version 0.4.1 (e2c88d6)
Docker version 1.8.1, build d12ea79
VBoxManage -v 
5.0.3r102220
Command:
$ docker-machine -D create -d virtualbox --virtualbox-disk-size 2000 dev
It hangs at here forever:
Daemon not responding yet: dial tcp 192.168.99.100:2376: operation timed out
Daemon not responding yet: dial tcp 192.168.99.100:2376: operation timed out
Daemon not responding yet: dial tcp 192.168.99.100:2376: operation timed out

**Comment by duynguyenvan** [comment]
It works after rebooting my machine. Thanks @phildav and all.

**Comment by thalesfsp** [comment]
Still not working. It's so frustrating..

**Comment by dirkhainc3** [comment]
Having the same issue on OSX 10.10.4 with VB 4.3.30.

**Comment by CaptainFeng** [comment]
@dirkhainc3 Did you reboot your mac?

**Comment by calebhaye** [comment]
I had the same problem, and resolved it by starting the virtualbox gui and removing all the VMs, many of which were inaccessible.  There were several duplicates, probably artifacts of my repeated install attempts.

**Comment by wangyuelucky** [comment]
@phildav Thank you, save my life

**Comment by step1profit** [comment]
works for me:
- OS X 10.10.5 14F27
- https://www.virtualbox.org/wiki/Download_Old_Builds_5_0
- removing all VMs

**Comment by dirkhainc3** [comment]
@CaptainFeng Yes I did.  In fact I didn't get a choice b/c when using VB 4.2.12 it would reproducibly crash my system. I ended up getting further with using the VB test build @phildav pointed out but ended up with contains that did not have a network connection.  Right now I completely wiped Docker and VB of my system (for VB this script is really helpful: http://www.virtualbox.org/svn/vbox/trunk/src/VBox/Installer/darwin/DiskImage/VirtualBox_Uninstall.tool ) I will try a clean install of docker-machine and VB 5.0.2. #102096 which has worked for a colleague.  If that does not work I will try @step1profit 's suggestion.

**Comment by sanecito** [comment]
I got the same error after installing Docker toolbar yesterday on Windows 8.1 x64. However, I re-ran just to see what happened and it opened up just fine, so I'd recommend running Docker twice and seeing what happens.

**Comment by dirkhainc3** [comment]
@step1profit 's suggestion seems to be the only way to get it to work with 10.10.5 (14F27).  Thanks for posting!

**Comment by sanecito** [comment]
Just kidding, I'm new to Docker and didn't realize I had to start the VM from VB before starting the Docker QuickTerminal. I couldn't start the default image docker creates with VB 5.x on WIndows 8.1 x64 and had to downgrade to VB 4.3.3 to get a startable default image, and even then I'm running into more issues (Docker QuickTerminal giving an exit code 255 and a "ConnectEx tcp: No connection could be made because the target machine actively refused it error")

**Comment by eduandrade** [comment]
Installing the latest test build solved the problem for me!
https://www.virtualbox.org/wiki/Testbuilds

Thanks everyone!

**Comment by poshUp** [comment]
For everyone who are struggling with this on Max OS X Yosemite (10.10.5)
In my case the *permissions* weren't configured correctly so I ran the **Disk Utility -> Repair Disk Permission** which fixed the issue.

**Comment by ggupta2008** [comment]
try

docker-machine stop default
docker-machine start default

**Comment by vanstriker** [comment]
I have this problem on EL Capitan. It seems network setting of the *default* docker-machine is not correct. I removed the installed *default* VM in virtualbox, and ran Quick Start Terminal again. It works.

**Comment by gotcha** [comment]
I upgraded to VB 5.0.8. I started to see the same issue. I tried 5.0.4 and 5.0.10 and it still fails.
I downgraded to VB 4.3.34 and docker-machine works properly.

I think this issue should be kept opened.

**Comment by aboutvale** [comment]
I had the same problem with the following sys conf:
Max OS X Yosemite (10.10.5), 
Docker Toolbox 1.9
VB 5.0.10

**Here how I fixed:**
Disk Utility -> Repair Disk Permission (thanks a lot @poshUp )
Delete all VMs
Unistalled and Installed VB
Installed Docker Toolbox and the default VM

**Comment by bhalothia** [comment]
:+1:

**Comment by gotcha** [comment]
@aboutvale Deleting all VMs can be a costly workaround as it implies downloading all images again.

**Comment by aboutvale** [comment]
@gotcha I completely agree with you. I accepted the drawback in this case, may be this step can be skipped without affecting the final result.

**Comment by pari125** [comment]
Downgrading to the lower virtual machine (4.3) also solved my problem! Thnx

**Comment by dimroc** [comment]
To any future readers, the post below about `/Applications` not being owned by root solved my problems.

https://forums.virtualbox.org/viewtopic.php?f=7&t=39179

For whatever reason, the machine didn't correctly have `root` as the owner. `chown root /Applications` and doing a reinstall (running the uninstall script provided with the .dmg and then reinstalling) solves the issue.

**Comment by slooker** [comment]
I also had the problem with /Applications not owned as root for some reason, and `chown root /Applications' also fixed my problem.

**Comment by lookfirst** [comment]
I've installed docker-machine with brew and had to run 'brew link docker-machine --overwrite'

**Comment by korsmakolnikov** [comment]
I've still this problem on Captain osx. I've try all of solutions of yours and none work. 
/Application is own by root
docker-machine can't work with vbox 4 anymore, so I try to install lastest after remove old one, install 4, try, install lastestes, try... Everytimes repairing disc permissions.

**Comment by trinitronx** [comment]
Ran into this problem on OSX `10.9.5`, using `VirtualBox 5.0.14 r105127`.  Solved problem by upgrading `docker-machine` via HomeBrew, then repairing disk permissions [to avoid this issue][1].

    brew update
    brew upgrade docker-machine
    brew link docker-machine --overwrite

Open Disk Utility app, select Mac OSX root FS partition, then "`Repair Disk Permissions`".

Solved the error:

    Starting "test-machine"...
    (test-machine) Check network to re-create if needed...
    Unable to start the VM: exit status 1
    Details: 00:00:00.042269 Power up failed (vrc=VERR_SUPLIB_OWNER_NOT_ROOT, rc=NS_ERROR_FAILURE (0X80004005))

[1]: http://www.benhepworth.com/blog/2012/06/22/virtualbox-failed-to-load-vmmr0-r0/

**Comment by SuriyaaKudoIsc** [comment]
See https://github.com/docker/kitematic/issues/1564!

**Comment by Boulboulouboule** [comment]
Reinstalling virtualbox worked for me ! Thanks :)

**Comment by tkvinfolio** [comment]
Try to use this link:

**docker-machine start default**
Starting "default"...
(default) Waiting for an IP...
Machine "default" was started.
Waiting for SSH to be available...
Detecting the provisioner...
Started machines may have new IP addresses. You may need to re-run the `docker-machine env` command.
Set up environment as instructed
**$ eval $(docker-machine env default)**
Now we can load the hello-world image into a container and run it
