### ISSUE TITLE
How to connect to private registry via SSL?

### ISSUE THREAD

**Issue by christianhuening** [docker/machine#1717]
Since Boot2Docker is now deprecated and you are encouraged to use docker-machine instead, I ask myself how to add a certificate from my private docker registry. My usual way of doing it was to add the cert to /etc/certs.d/<nameofhost>/ca.crt and exit, boot2docker save , down and up. 

Since boot2docker save is no more: How is this meant to be accomplished now?

Cheers,
Christian

**Comment by nathanleclaire** [comment]
cc @tianon @SvenDowideit @ehazlett for discussion and recommendations

**Comment by JacsonPaz** [comment]
+1 waiting for a solution or a workaround..

**Comment by ceagan** [comment]
Here is a hack to make it work until a better solution arrives. Note that the cert should be base64 encoded.

```sh
docker-machine.exe scp ca.crt default:.
docker-machine.exe ssh default
sudo mkdir -p /etc/docker/certs.d/<fully-qualified-host-name>
sudo mv ca.crt /etc/docker/certs.d/<fully-qualified-host-name>/ca.crt
```

**Comment by tianon** [comment]
Isn't `/var/lib/boot2docker/certs` set up in the VM on the persistent storage specifically for this right now?  ie, https://github.com/boot2docker/boot2docker/blob/30800b21799f3aedba2150c729aeafc13baad8d9/rootfs/rootfs/etc/rc.d/install-ca-certs, which runs at boot

**Comment by SvenDowideit** [comment]
yup.

**Comment by christianhuening** [comment]
@tianon Sorry, don't get you?

**Comment by nathanleclaire** [comment]
Note to self: Add this to docs.

**Comment by shepmaster** [comment]
@christianhuening specifically, something like this seemed to work for me:

```
host$ docker-machine scp my-private-ca.pem my-machine-name:/tmp
host$ docker-machine ssh my-machine-name

docker$ sudo mkdir /var/lib/boot2docker/certs
docker$ sudo cp /tmp/my-private-ca.pem /var/lib/boot2docker/certs 
docker$ exit

host$ docker-machine restart my-machine-name
```

**Comment by christianhuening** [comment]
@shepmaster Thanks! much appreciated!

**Comment by shepmaster** [comment]
@nathanleclaire maybe this issue could be repurposed as a note to add the info to the docs as appropriate?

**Comment by nathanleclaire** [comment]
Yeah, I think I will add one.
