### ISSUE TITLE
driver request: bhyve and xhyve support

### ISSUE THREAD

**Issue by lloeki** [docker/machine#1724]
[bhyve](http://www.bhyve.org) is analogous to KVM but native to FreeBSD, while [xhyve](https://github.com/mist64/xhyve) is a port of bhyve to OS X using the native [Hypervisor.framework](http://www.pagetable.com/?p=764)

They would make great additions along with [KVM](https://github.com/docker/machine/issues/659) on Linux.

**Comment by mschygulla** [comment]
Here was a PR https://github.com/docker/machine/pull/1358 for xhyve

**Comment by lloeki** [comment]
Oh, whoopsie. I suppose it's waiting on #1626 then.

**Comment by ashleysommer** [comment]
So https://github.com/docker/machine/pull/1902 landed in 2015, and https://github.com/docker/machine/issues/1626 was closed as completed after that.
It appears that the xhyve driver turned into a plugin and was finished not long after.
Was there ever any progress on a bhyve plugin?
