### ISSUE TITLE
docker-machine create fails (OS X 10.10.4, 13" retina MBP 2015)

### ISSUE THREAD

**Issue by elnygren** [docker/machine#1725]
Kitematic (rm and retry)

```
/Applications/Docker/Kitematic (Beta).app/Contents/Resources/resources/docker-machine -D create -d virtualbox --virtualbox-memory 2048 default returned non zero exit code. Stderr: Converting from raw image file="stdin" to file="/Users/<redacted>/.docker/machine/machines/default/disk.vmdk"... Creating dynamic image with size 20971520000 bytes (20000MB)... Error creating machine: exit status 1 You will want to check the provider to make sure the machine and associated resources were properly removed.
```

CLI

```
> docker-machine create --driver virtualbox default
Creating VirtualBox VM...
Creating SSH key...
Starting VirtualBox VM...
Error creating machine: exit status 1
You will want to check the provider to make sure the machine and associated resources were properly removed.
```

Downloaded Docker today from https://www.docker.com/toolbox

**Comment by dpresling** [comment]
Same problem. Same machine specs.

**Comment by petercoles** [comment]
Same here, upgraded to test build of VirtualBox 5.0.3, available from https://www.virtualbox.org/wiki/Testbuilds and all was good again.

**Comment by dweinstein** [comment]
FWIW there isn't enough error information to really say what went wrong here. I stumbled into this one only to really be looking for this patch  in docker-machine: https://github.com/docker/machine/issues/1725 

in case anyone else ends up here :-)

**Comment by dgageot** [comment]
Let's assume it's a VirtualBox bug. Closing this issue. Feel free to reopen if you feel like it.
