### ISSUE TITLE
Docker Toolbox Migration of Boot2Docker VM failed on Windows 7, Git not found

### ISSUE THREAD

**Issue by pthorson** [docker/machine#1727]
Per the installer instructions (and because I did not see another instance of this one), logging a new issue. 
![image](https://cloud.githubusercontent.com/assets/2442268/9341571/b4935ba2-45c4-11e5-8c47-cea8af2fefda.png)

It appears the path to Git is hard coded somewhere in the install script. Here is toolbox-migration-logs.txt:

    C:\Program Files\Docker Toolbox>cd C:\Program Files\Docker Toolbox\ 

    C:\Program Files\Docker Toolbox>"C:\Program Files (x86)\Git\bin\sh.exe" --login -i migrate.sh 
    The system cannot find the path specified.

My Git is installed in a separate folder.

Subsequently running `>docker-machine create -d virtualbox --virtualbox-import-boot2docker-vm boot2docker-vm dev` worked just fine so not a critical defect but something to investigate.

**Comment by nathanleclaire** [comment]
Hi @pthorson, could I please get you to file an issue over at https://github.com/docker/toolbox?  If not, perhaps @mchiang @jeffdm could carry this.

**Comment by pthorson** [comment]
Opened new issue at https://github.com/docker/toolbox/issues/112

Closing this one.

**Comment by nathanleclaire** [comment]
Thanks!
