### ISSUE TITLE
--url is totally broken

### ISSUE THREAD

**Issue by nathanleclaire** [docker/machine#1728]
Even if you specify the location of the CA cert and other secrets, it goes off and creates them, and on commands like `env` Machine expects to read them from the Machine directory (not where they were originally referenced as being), so you see the familiar "could not find ca.pem" type error messages. The certs never get copied since that runs as part of provisioning, which gets skipped for the `none` driver.

I've seen a few other issues around referencing this fact, I'll add them to this thread as I dig them up.  Ultimately we have to decide if this is a feature we're going to keep supporting and fix this, or deprecate it.  I'm leaning more towards the former (maybe with a good reconsideration of how the workflow fits for that sort of thing), but it will take some time and effort to get this into shape again.

cc @ehazlett

**Comment by perj** [comment]
#1233 is basically this

**Comment by nathanleclaire** [comment]
Going to close and move discussion to: https://github.com/docker/machine/issues/1728

**Comment by dnephin** [comment]
*move discussion to #2270 ?

**Comment by nathanleclaire** [comment]
@dnephin Yep I mistyped.  Nice catch.
