### ISSUE TITLE
Consider removing coverage check in Travis

### ISSUE THREAD

**Issue by nathanleclaire** [docker/machine#1730]
Yup, I'm the one who introduced it and now I'm thinking about removing it.  Originally I hoped it would serve as a "shame, shame, shame" function for those who added modules without unit tests, but over time it's just served as a nuisance and we're all just hacking around it anyway.  Besides, some modules don't even _need_ unit tests, `pkgaction` being one example.

WDYT @ehazlett ?

**Comment by dmp42** [comment]
Would #1834 somewhat enhance the situation and make it usable again?

**Comment by nathanleclaire** [comment]
Yes, I'd still really like to get rid of the check in Travis entirely and get rid of all our empty fake test files, but I'm in favor of a percentage-based check.

**Comment by dmp42** [comment]
Coverage/report has been rehauled significantly, to the point it should no longer be a PITA. I think we can close this.
