### ISSUE TITLE
Ability to provision Windows hosts via VirtualBox

### ISSUE THREAD

**Issue by michaelsbradleyjr** [docker/machine#1734]
I use a Mac laptop as my principal dev environment, and `docker-machine` makes it so very convenient to provision Docker-Linux hosts locally, using VirtualBox.

I would like to request a feature whereby Docker-Windows hosts can likewise be provisioned locally, i.e. on my Mac laptop, using VirtualBox.

**Comment by dgageot** [comment]
Duplicate of https://github.com/docker/machine/issues/2907
