### ISSUE TITLE
create docker failure due to different oracle virtualbox installation path.

### ISSUE THREAD

**Issue by larrycai** [docker/machine#1737]
I can't install docker-vm successfully due to the different oracle virtualbox installation path in windows

The original path is `C:\Program Files\Oracle VM VirtualBox`, so when I do virtualbox upgrade, it will use this without change. `boot2docker` can handle this.

If it is the new installation, it will be `C:\\Program Files\\Oracle\\VirtualBox`

Now it is hard-coded in https://github.com/docker/machine/blob/master/drivers/virtualbox/vbm.go for new installation path, it looks someone already have the comment to use registry `HKEY_LOCAL_MACHINE\SOFTWARE\Oracle\VirtualBox\InstallDir`

It impacts the new installation of docker-vm and migration from boot2docker both.

**Comment by petercoles** [comment]
I've also had problems with paths, albeit in OSX so maybe different to yours. the issues came back to the current version of VirtualBox, 5.0.2 but resolved them by upgrading to the test build of 5.0.3 (https://www.virtualbox.org/wiki/Testbuilds).

**Comment by tomwaits** [comment]
Thx peter, that was definitely the issue.  Upgraded and all is good again with the world.  So not a docker issue.

**Comment by larrycai** [comment]
@tomwaits I still think it is a docker issue, upgrade virtualbox will not solve the issue.

Since from oracle (or other SW) point of view, it is up to end-user to select the installation path, they just need to have registry for it as record.

docker should not hard-code to take the default path as granted.

**Comment by tomwaits** [comment]
@larrycai if you look at code https://github.com/docker/machine/blob/master/drivers/virtualbox/vbm.go#L39 it seems to me that the docker first checks the env to see if path exists and the hard coded path is just a fall back in case path of vm is not set.  and by the way both petercoles and I are using OSX hence I would still think it was a virtual box issue where path was no properly set by vb for env to discover.

**Comment by larrycai** [comment]
I just noticed those environment checking. thx.

But at least for old 5.0.x release, 4.x.x release, this environment can't
be found after upgrade. Or it happens only for new installation.

Maybe in later release (5.0.3+) , virtualbox app will create those variable
environment during upgrade.

And also in windows, registry is more nature to be used to find the
installation path, this is what line
https://github.com/docker/machine/blob/master/drivers/virtualbox/vbm.go#L50
indicated, but it is little strange why it is not implemented.

In short: current upgrading virtualbox app doesn't solve this problem. we
need force user to install new, this is not friendly.

Using registry is more safe to achieve this.

Will be good if someone report this case to virtualbox dev forum to see
their view.








On Thu, Aug 27, 2015 at 11:14 PM, tomwaits <notifications@github.com> wrote:

> @larrycai <https://github.com/larrycai> if you look at code
> https://github.com/docker/machine/blob/master/drivers/virtualbox/vbm.go#L39
> it seems to me that the docker first checks the env to see if path exists
> and the hard coded path is just a fall back in case path of vm is not set.
> and by the way both petercoles and I are using OSX hence I would still
> think it was a virtual box issue where path was no properly set by vb for
> env to discover.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/docker/machine/issues/1737#issuecomment-135465232>.
>



-- 
True software development embraces consistent inconsistency.
blog: http://larrycaiyu.com/blog (en), http://larrycaiyu.com (chinese)
