### ISSUE TITLE
HyperV module detection in `docker-machine create` command

### ISSUE THREAD

**Issue by colindembovsky** [docker/machine#1746]
I was struggling to successfully create a docker-machine using Hyper-V provider. The command would fail with "PowerShell module not found". (Similar to some of the issues in [512](https://github.com/docker/machine/issues/512).

I think there's a bug somewhere in the code that detects the Hyper-V module. 

When running with `-D` I could see that `docker-machine` was executing `@(Get-Command Get-VM).ModuleName`. However, instead of returning the expected "Hyper-V", the command was outputting:
```
Warning: ssh-agent not found
Hyper-V
```

I then just added the Git\bin folder to my path (so that the ssh-agent warning wasn't splashed) and the `docker-machine create` command then started working.

**Comment by ehazlett** [comment]
Thanks for the report.  The recommended way to use docker machine on Windows is to install MSYSGIT.  I believe that sets up the paths for you.  Thanks for the feedback in case anyone wants to set it up manually.  Closing.  Thanks!

**Comment by colindembovsky** [comment]
Ok - but I did try from the bash prompt of Git (which uses MSYSGit as far as I know) and got the same error.
