### ISSUE TITLE
Need to open port 3376 when creating with --swarm flag

### ISSUE THREAD

**Issue by rgardler** [docker/machine#1748]
docker-machine create -d azure ... --swarm --swarm-master --swarm-discovery token://$sid  rgswarm-master

Creates the machine on Azure just fine, but only port 2376 is open, swarm needs port 3376.

I have not tested with other drivers.

**Comment by ehazlett** [comment]
Hmm this should work I believe.  Unless there are multiple config sets -- I'm not very familiar with the Azure config.  https://github.com/docker/machine/blob/master/drivers/azure/azure.go#L397

**Comment by rgardler** [comment]
OK, let me do some investigation. It didn't work with the last master I stood up. I'll update this issue when I've taken a look.

**Comment by rgardler** [comment]
Updating to docker-machine 0.4 resolved the issue. Thanks.
