### ISSUE TITLE
create docker host failed when used generic drivers

### ISSUE THREAD

**Issue by dayiguizhen** [docker/machine#1751]
The error message:

    root@n14:~/.ssh# docker-machine create -d generic --generic-ssh-user yzxu --generic-ssh-key id_rsa --generic-ip-address 10.0.5.137 ubuntu
    Importing SSH key...
    SSH cmd error!
    command: sudo hostname ubuntu && echo "ubuntu" | sudo tee /etc/hostname
    err    : exit status 1
    output : sudo: no tty present and no askpass program specified
    Sorry, try again.
    sudo: no tty present and no askpass program specified
    Sorry, try again.
    sudo: no tty present and no askpass program specified
    Sorry, try again.
    sudo: 3 incorrect password attempts

**Comment by ehazlett** [comment]
Does your ssh key require a password?

**Comment by dayiguizhen** [comment]
@ehazlett No,it doesn't.

    yzxu@n14:~/.ssh$ ls
    authorized_keys  config.bk  id_rsa  id_rsa.pub  known_hosts
    yzxu@n14:~/.ssh$ ssh -i id_rsa yzxu@10.0.5.137
    Welcome to Ubuntu 12.04.5 LTS (GNU/Linux 3.8.0-29-generic x86_64)

    * Documentation:  https://help.ubuntu.com/
    New release '14.04.1 LTS' available.
    Run 'do-release-upgrade' to upgrade to it.
    
    Last login: Tue Aug 25 10:16:25 2015 from 10.1.0.91
    yzxu@ubuntu:~$

**Comment by mnencia** [comment]
Are you on OSX?

**Comment by marlonpp** [comment]
+1

Running on OSX and Linux.
But in my case, I'm trying to specify a ".pem" key.

**Comment by dgageot** [comment]
@dayiguizhen @marlonpp Did you get a chance to test a more recent version?

**Comment by tedyoung** [comment]
@dayiguizhen -- is this the same as #1569? Not sure if @marlonpp is different, though.

**Comment by dayiguizhen** [comment]
@dgageot I'm give up create that docker host.And I create another docker host,it was will.So I will close this issue.
