### ISSUE TITLE
Migration of boot2docker VM failed with GIT 64 bits installed

### ISSUE THREAD

**Issue by Akhena** [docker/machine#1753]
It seems that the migration commands being executed are :
```
cd C:\Program Files\Docker Toolbox\ 
"C:\Program Files (x86)\Git\bin\sh.exe" --login -i migrate.sh 
```
The migration log was:
```
'"C:\Program Files (x86)\Git\bin\sh.exe"' is not recognized as an internal or external command,
operable program or batch file.
```

GIT is now available in a 64bits version, and so the hardcoded (as it seems) path to the x86 ProgramFiles folder fails when trying to execute sh.exe .

I was able to launch the vm migration by typing manually the fixed commands:
```
cd C:\Program Files\Docker Toolbox\ 
C:\Program Files\Docker Toolbox>"C:\Program Files\Git\bin\sh.exe" --login -i migrate.sh
```

The migration stopped on the following step:
Daemon not responding yet: dial tcp 192.168.99.100:2376: ConnectEx tcp: No conne
ction could be made because the target machine actively refused it.

**Comment by FrenchBen** [comment]
@Akhena for the command to work, verify that boot2docker/VM is up and running first.

**Comment by Akhena** [comment]
Unfortunately I did not have time to search more for the root cause of this issue. Maybe the old git (x86) path still existed, and that tricked the installer into thinking Git x86 was still installed.

Anyway, I ended uninstalling everything (boot2docker + toolbox + git), and reinstalling from scratch. Almost everything is perfect now, except for the fact that I am behind a corporate proxy that does MITM with a self signed certificate, and I still have not found where to add it when using docker-toolbox (it apparently doesn't work the same way than boot2docker)

I don't know for you, but for me, this (non-?)issue can be closed.

**Comment by FrenchBen** [comment]
@Akhena Thanks for the feedback - Although not perfect, you can look at the following wiki which highlights how some users have modified their VM to work with their proxy:
https://github.com/kitematic/kitematic/wiki/Common-Issues-and-Fixes#proxy-issues

**Comment by Akhena** [comment]
@FrenchBen Thanks for the link. It will help me having the proxy supported by Kitematic. 
For the vm itself, I managed quite easily to add the proxy, but it's the self signed certificated used for https that I still have trouble with.
