### ISSUE TITLE
Schedule for Monthly Community Meetings

### ISSUE THREAD

**Issue by ehazlett** [docker/machine#1757]
The first community meeting (https://bluejeans.com/s/8vFc) was a tremendous success!  In the last meeting we decided to start an issue to get a majority vote on the date / time moving forward.

I will throw out an initial day to start and then we can iterate on the time.  How does the 4th Thurs. of each month sound?

Let's give times in UTC.

**Comment by miqui** [comment]
thanks....  i am flexible., but sure 4th Thur @ 3pm (EST) ==> 7pm (UTC)

**Comment by wenlock** [comment]
+1 works for me too

**Comment by miqui** [comment]
@ehazlett , hi Evan, are we set then?

**Comment by miqui** [comment]
@ehazlett any updates on this?  any news on the docker-machine<-->shim<--->mypluggin?

**Comment by ehazlett** [comment]
Schedule will be here: https://github.com/docker/machine/wiki
