### ISSUE TITLE
Docker client docs need to be clarified

### ISSUE THREAD

**Issue by arun-gupta** [docker/machine#1760]
https://docs.docker.com/machine/  says:

"configures the docker client to talk to them"

Machine does not configure the Client to talk to them. It shows the commands that need to be executed for a client to be configured, but they are different things.

Docs need to be updated.

**Comment by moxiegirl** [comment]
My understanding is that when I use `docker-machine env machine-name` I am using Docker Machine to direct the client to interact with a particular machine instance.  That is configuration for the client's interaction.  Happy to discuss alternative wording...

**Comment by arun-gupta** [comment]
`docker-machine env default` on my Mac shows:

```
~> docker-machine env default
export DOCKER_TLS_VERIFY="1"
export DOCKER_HOST="tcp://192.168.99.101:2376"
export DOCKER_CERT_PATH="/Users/arungupta/.docker/machine/machines/default"
export DOCKER_MACHINE_NAME="default"
# Run this command to configure your shell: 
# eval "$(docker-machine env default)"
```

It shows the command that needs to be explicitly executed (using last line from the output) in order to configure the client to talk to this host. Can `docker-machine` be used directly to execute that command?

**Comment by moxiegirl** [comment]
The last line is a convenience command from Docker Machine. It automatically configures all the settings the shell needs from Docker Machine so that the Docker Client can connect with the correct host.  I can configure different values by subing out the default value.

**Comment by arun-gupta** [comment]
I've seen a different behavior on my Mac OS X.

Before running `docker-machine env default` ...

```
> docker ps
Get http:///var/run/docker.sock/v1.20/containers/json: dial unix /var/run/docker.sock: no such file or directory.
* Are you trying to connect to a TLS-enabled daemon without TLS?
* Is your docker daemon up and running?
```

Now running the command ...

```
> docker-machine env default
export DOCKER_TLS_VERIFY="1"
export DOCKER_HOST="tcp://192.168.99.101:2376"
export DOCKER_CERT_PATH="/Users/arungupta/.docker/machine/machines/default"
export DOCKER_MACHINE_NAME="default"
# Run this command to configure your shell: 
# eval "$(docker-machine env default)"
```

Still the same output ...

```
> docker ps
Get http:///var/run/docker.sock/v1.20/containers/json: dial unix /var/run/docker.sock: no such file or directory.
* Are you trying to connect to a TLS-enabled daemon without TLS?
* Is your docker daemon up and running?
```

If its only convenience command then "Run this command" is misleading and needs to be reworded. Everything works correctly if I run the command though.

**Comment by moxiegirl** [comment]
The user must run  `eval "$(docker-machine env default)"` on the command line. Then, the client returns properly.

```
$ docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
```

**Comment by arun-gupta** [comment]
See the original comment.

It does not configure the client, only shows the command that need to be run to configure the client.

**Comment by bill2004158** [comment]
@moxiegirl , I got this error:
$ eval "$(docker-machine env default)"
open C:\Users\Bill\.docker\machine\machines\default\ca.pem: The system cannot find the file specified.

**Comment by ehazlett** [comment]
@bill2004158 do you have a machine named "default"?

**Comment by ehazlett** [comment]
@arun-gupta we cannot run a subshell from that output.  You must run the `eval` manually.

**Comment by mattjmcnaughton** [comment]
The more specific docker-machine documentation for the `env` says
`The docker-machine env <machine-name> subcommand outputs the configuration command you should use. ` so it seems pretty clear - but maybe there's room for a broader clarification of what docker-machine can do.

 @arun-gupta and @moxiegirl what would you think about the documentation saying something like 
```
It automatically creates hosts, installs Docker on them, then outputs configuration for making the `docker` client talk to them. 
```

instead of 

```
It automatically creates hosts, installs Docker on them, then configures the `docker` client to talk to them.
```

**Comment by arun-gupta** [comment]
@mattjmcnaughton the proposed wording is the current behavior and seems accurate.

**Comment by arun-gupta** [comment]
@ehazlett "default" machine is created by Docker Quickstart Terminal.

**Comment by bill2004158** [comment]
@ehazlett , yes, a machine named "default" is crated and running (I can see it in virtualbox).
however, docker env config fail.

1. i tried upgrade virtualbox to latest version (nightly build one)
2. and re-generated the cert.  then it generated cert file in .docker\machine\machines\default\
3. then I try to re-config the env, 
4. finally it works, and I can use the docker client in windows 10 directly.

**Comment by jeanlaurent** [comment]
This sounds like resolved to me and an "old story". Feel free to disagree by re-opening if you think the wording is faulty.
