### ISSUE TITLE
Docker searching for server.pem file

### ISSUE THREAD

**Issue by chwade** [docker/machine#1761]
I am trying to install Docker on a MacBook Pro, using the Docker Toolbox 1.8.1.  I receive the following error when I start the Docker Quickstart Terminal.  I am new to Docker and not quite sure how to solve this.

open /Users/charliewade/.docker/machine/machines/default/server.pem: no such file or directory

**Comment by bill2004158** [comment]
similar error:
$ eval "$(docker-machine env default)"
open C:\Users\Bill\.docker\machine\machines\default\ca.pem: The system cannot find the file specified.

**Comment by chwade** [comment]
@bill2004158 Look in the .docker\machine\certs folder for the ca.pem file. I had the same issue and found the ca.pem file there

**Comment by ehazlett** [comment]
This usually occurs from a provisioning issue.  Can you try to remove and re-create the machine?

**Comment by chwade** [comment]
@ehazlett Worked! Thanks
