### ISSUE TITLE
Boot2Docker driver certificate file names are inconvenient

### ISSUE THREAD

**Issue by ahmetalpbalkan** [docker/machine#1767]
(first of all: not sure if a machine driver issue or boot2docker issue)

Normally when you run `docker --help` it shows this:

```
  --tlscacert=~/.docker/ca.pem    Trust certs signed only by this CA
  --tlscert=~/.docker/cert.pem    Path to TLS certificate file
  --tlskey=~/.docker/key.pem      Path to TLS key file
```

and if you set your `$DOCKER_CERT_PATH`, and just run `docker --tls ps` docker will automatically pick up `ca.pem` , `key.pem`, `cert.pem`.

However if I do a:

```
$ docker-machine create -d virtualbox --swarm \
    -d virtualbox \
    --swarm \
    --swarm-master \
    --swarm-discovery token://<guid> \
    swarm-m
...
$ docker-machine ssh swarm-m
# docker inspect swarm swarm-agent-master
```

I see this output:

```json
    "Args": [
        "manage",
        "--tlsverify",
        "--tlscacert=/var/lib/boot2docker/ca.pem",
        "--tlscert=/var/lib/boot2docker/server.pem",
        "--tlskey=/var/lib/boot2docker/server-key.pem",
        "-H", ...
```

OK, so at this point:

| standard | swarm as set up by docker-machine |
|-----|-----------|
|ca.pem|ca.pem|
|cert.pem|server.pem|
|key.pem|server-key.pem|

**This is super confusing!** Now I have to do all the symlinks before mounting `/var/lib/boot2docker` to another directory that understands the standard Docker CLI language (ca/cert/key.pem)...

I think this should be fixed before it lays eggs or spreads any further.

**Comment by SvenDowideit** [comment]
That's really confusing, and not totally correct.

You're not supposed to use the _server_ keys on the client __ever__.

You're supposed to create a set of client keys for your client, signed by the same `ca.key`

and if you look in `/var/lib/boot2docker/tls`, you see we make a set by default:

```
root@boot2docker:/mnt/sda1/var/lib/boot2docker/tls# ls -al
total 36
drwx------    2 root     root          4096 Aug 15 20:22 .
drwxr-xr-x    6 root     root          4096 Aug 25 03:59 ..
-rw-r--r--    1 root     root          1042 Aug 15 20:21 ca.pem
-rw-------    1 root     root          1679 Aug 15 20:21 cakey.pem
-rw-r--r--    1 root     root          1070 Aug 15 20:22 cert.pem
-rw-r--r--    1 root     root            53 Aug 15 20:22 hostnames
-rw-------    1 root     root          1679 Aug 15 20:22 key.pem
-rw-r--r--    1 root     root          1099 Aug 15 20:22 server.pem
-rw-------    1 root     root          1679 Aug 15 20:22 serverkey.pem
```

iirc, `boot2docker-cli` copied over the client certs.

however, docker-machine generates its own certs and uploads them to the vm, so that could also be totally different.

so _i think this is not a b2d issue_

**Comment by ahmetalpbalkan** [comment]
> That's really confusing, and not totally correct.

@SvenDowideit I'm aware of that but I believe what `docker-machine` does is when you create a VM as illustrated below, it uses the same certs to provide authentication on Swarm manager, as well as to the communication between manager<-->nodes.

Here's how I create my cluster:

```sh
#!/bin/bash
set -ex

docker-machine create \
    -d virtualbox \
    --swarm \
    --swarm-master \
    --swarm-discovery token://<paste-token-here> \
    swarm-m && \
  for i in {0..2}; do
    docker-machine create \
      -d virtualbox \
      --swarm \
      --swarm-discovery token://<paste-token-here> \
      swarm-$i
  done
```

What I understand from the `docker inspect swarm-agent-master` output is docker-machine's Swarm integration is using the same certs to do two things. cc'ing @chanwit as he may have an idea here.

**Comment by SvenDowideit** [comment]
Y, mostly I replied to suggest that its not boot2docker, which has separate certificates for server and client side - I presume your table should really be `standard` vs `swarm`, or even `swarm as set up by docker-machine` ?

**Comment by ahmetalpbalkan** [comment]
fair point

**Comment by ahmetalpbalkan** [comment]
I'm not even sure this is valid anymore. Closing.
