### ISSUE TITLE
`docker-machine env default` consumes STDIN

### ISSUE THREAD

**Issue by pstengel** [docker/machine#1774]
I have placed the following line in my `.bash_profile` to initialize my environment:

    eval "$(docker-machine env default)"

It appears that when `docker-machine` connects to the VM via SSH to obtain needed information, it is consuming STDIN:

    pstengel@HAL-9000 ~ $ echo "echo Hello world" | bash -l
    pstengel@HAL-9000 ~ $

With the docker-machine line in my Bash profile commented out:

    pstengel@HAL-9000 ~ $ echo "echo Hello world" | bash -l
    Hello world

This is unexpected behavior.

**Comment by pstengel** [comment]
In case anyone else is encountering this, a temporary workaround is to change the eval line to:

    eval "$(docker-machine env default </dev/null)"

**Comment by adambiggs** [comment]
+1

This causes problems when used as a pre-window command with Tmuxinator/Tmuxp. Any following pane commands are swallowed up, resulting in a bunch of empty panes on launch.

Thanks for that workaround @pstengel, nice to have things working as they should again!

**Comment by nickfyson** [comment]
+1

For anyone suffering the same problem as me, this workaround fixed my iTerm2 'Send text at start' option, as well as tmuxstart sessions. 

Cheers for the solution!

**Comment by wilmoore** [comment]
:+1: - I can also confirm that this resolves issues where having `eval "$(docker-machine env default)"` in my shell profile caused my tmux scripts to seemingly fail. Sending keys would seem to send the commands to the background so my tmux panes would end up sitting in a default state.

Changing it to:

```
eval "$(docker-machine env default </dev/null)"
```

Solves the problem. Thanks @pstengel

**Comment by jeanlaurent** [comment]
Closing since this is now fixed since [v0.5.4](https://github.com/docker/machine/releases/tag/v0.5.4)
