### ISSUE TITLE
"Getting started" documentation still links and uses depreacted boot2docker

### ISSUE THREAD

**Issue by Zanadar** [docker/machine#1775]
The documentation linked to in [Docker Toolbox](https://docs.docker.com/mac/started/) still references and links to boot2docker installation and assumes the use of that utility.  

I understand, now, that this has been deprecated in favor of Docker Machine, but I wasted my morning down rabbitholes, trying to resolve certificate issues with boot2docker-cli, etc. etc. only to find I should be using Docker Machine anyway.  That would have been nice to know before I started...

Docs should be updated (especially since they're supposedly written for the layman who's not even assumed to know how to use the command line).

**Comment by clnperez** [comment]
Maybe the docs could point to https://docs.docker.com/machine/get-started/ instead. Since these docs live in the docker project, I think this issue might need to be opened in docker's github instead, though.

**Comment by Zanadar** [comment]
Or [Toolbox's](https://github.com/docker/toolbox)? as that was where the fault link was...good call @clnperez.

**Comment by clnperez** [comment]
Since I don't see any explicit mention of boot2docker's tool in the toolbox github page, I was thinking the very last part of the first link you listed (docker/ mac / started) would need updates.  Some more can be added to the last part, and also fix the link to point to the machine get-started page instead. And all that lives in docker's github.

**Comment by clnperez** [comment]
Oh, or just link to http://docs.docker.com/installation/mac/ instead of https://docs.docker.com/mac/started/

**Comment by Zanadar** [comment]
Yes I think that's the right call. Will close this issue and move over to docker's github.

**Comment by ehazlett** [comment]
good call @clnperez 

i'll get this updated

**Comment by nathanleclaire** [comment]
Is this issue still valid?  I don't see references to b2d anywhere.

**Comment by dgageot** [comment]
@dmp42 Can we close this one?
