### ISSUE TITLE
docker-machine create -d virtualbox dev hangs

### ISSUE THREAD

**Issue by stupendous-man** [docker/machine#1787]
Hello,

After installing the new Docker Toolbox I've tried running "docker-machine create" multiple times and keep running into the same issue, the process hangs indefinitely at "Starting VM..." 

bash-3.2$ docker-machine create -d virtualbox dev
Creating CA: /Users/username/.docker/machine/certs/ca.pem
Creating client certificate: /Users/username/.docker/machine/certs/cert.pem
Image cache does not exist, creating it at /Users/username/.docker/machine/cache...
No default boot2docker iso found locally, downloading the latest release...
Downloading https://github.com/boot2docker/boot2docker/releases/download/v1.8.1/boot2docker.iso to /Users/username/.docker/machine/cache/boot2docker.iso...
Creating VirtualBox VM...
Creating SSH key...
Starting VirtualBox VM...
Starting VM...

When I launch a new terminal window and run "docker-machine ls", the machine seems to be running:

bash-3.2$ docker-machine ls
NAME   ACTIVE   DRIVER       STATE     URL                         SWARM
dev             virtualbox   Running   tcp://192.168.99.105:2376   

However, when I run "docker-machine env dev" I keep getting the following error:

bash-3.2$ docker-machine env dev
open /Users/username/.docker/machine/machines/dev/ca.pem: no such file or directory

At this point I am out of ideas and any help would be greatly appreciated. Thanks.

**Comment by dnephin** [comment]
I had a similar problem on linux the first time I tried to create a virtualbox machine. I went to the virtualbox UI, right clicked on the vm, and clicked "show" (there's probably some way to do that with virtualbox admin commands, but I'm not that familiar with it).

That opened the vm console window, and revealed the error that was causing it to get stuck (in my case it was an issue with vt-x being disabled by the bios).  

You might be able to do the same to find the issue that is preventing the vm from booting correctly.

**Comment by F1-Engineer** [comment]
This ended up being a VPN issue. I found the solution here: https://github.com/boot2docker/boot2docker/issues/392

**Comment by xi2008wang** [comment]
is virtualbox 5.0.0 bug!
upgrade virtualbox 5.0.4 !
http://download.virtualbox.org/virtualbox/5.0.4/VirtualBox-5.0.4-102546-OSX.dmg

**Comment by srmadsen** [comment]
Apparently VirtualBox 5.0.4 does not solve the problem.  My context:

* Mac OS/X 10.10.5
* Docker Toolkit 1.8.2
* Virtual Box 5.0.4-102
* Docker Machine 0.4.1
* Cisco VPN installed but not active connected.

Executing "--debug create -d virtualbox --engine-insecure-registry docker-registry.vip.fsglobal.net default"  hangs forever.

**Comment by pierredup** [comment]
I also have the same issue, creating a local VM using docker-machine just hangs forever, I'm also using OSX 10.10.5 with VirtualBox 5.0.4-R102 and docker-machine 0.4.1 (using the command `docker-machine create -d virtualbox dev`)

**Comment by ShylockGou** [comment]
is this issue solved ?

**Comment by srmadsen** [comment]
Nope.  Currently unusable on MacOS.  Very frustrating!

Reid Madsen
Manager, Continuous Delivery Services
FamilySearch.org<http://FamilySearch.org>
Tel: 801.240.6009, Cell: 214.912.5152
reid.madsen@familysearch.org<mailto:reid.madsen@familysearch.org>

On Oct 4, 2015, at 12:38 AM, ShylockGou <notifications@github.com<mailto:notifications@github.com>> wrote:


is this issue solved ?

**Comment by ShylockGou** [comment]
@srmadsen maybe ssh client configure,i got fixed with close multiplexing  .tks @tehmaspc ,it speed   my two weeks .https://github.com/docker/machine/issues/1591

**Comment by damonmcminn** [comment]
I am also experiencing this issue.

**Comment by pierredup** [comment]
Disabling SSH multiplexing fixes the issues, check out https://github.com/docker/machine/issues/1591#issuecomment-126169020

**Comment by timhtheos** [comment]
Disabling ssh multiplexing works for me.  @tehmaspc https://github.com/docker/machine/issues/1591#issuecomment-126169020
