### ISSUE TITLE
Can't connect to VM after suspending

### ISSUE THREAD

**Issue by tinchou** [docker/machine#1788]
I'm in Windows 8.1 using docker-toolbox 1.8.1c. Everytime I suspend my computer I need to restart it in order to be able to connect to the VM again. VM shows up correctly in Virtualbox.

If I stop the machine before suspending, then I can start it again just fine. If I don't stop it, then even `docker-machine restart` it doesn't make it work.

Let me know if I can provide any kind of logs.

Thanks!

**Comment by dgageot** [comment]
Hi @tinchou, can you gist the output of `docker-machine -D start [machine]` just when it fails?

**Comment by tinchou** [comment]
@dgageot sure, please take a look: https://gist.github.com/tinchou/08aa3e7674b8f2d1375e

**Comment by dgageot** [comment]
Thanks a lot @tinchou. `docker-machine` 0.5.0 was released yesterday. Can you upgrade and try again?

**Comment by tinchou** [comment]
I tried updating to docker-toolbox 1.9, and everything just stopped
working. Reinstalling didn't work. I switched to my Linux dual-boot for
now, so I won't be able to test this anytime soon.

**Comment by dgageot** [comment]
Closing the issue. @tinchou please feel free to reopen if you get a chance to test again on windows.
