### ISSUE TITLE
docker-machine create does not update ISO when a new version is available

### ISSUE THREAD

**Issue by alvinr** [docker/machine#1790]
# Problem
`docker-machine` maintains a cache of ISO images, on OS-X this is stored at ~/.docker/machine/cache.

Right now, the Boot2Docker.iso is download on first usage of `docker-machine`. You are kept at this version until you run a `docker-machine upgrade {my machine}`. Creating new VMs from an out of date ISO seems bad, and in my case it fails the latest docker install script at https://get.docker.com

# Solution
It would seem to make sense to
- warn on `create` if this is an older ISO image. I had 1.6.2 locally which is way old.
- on `create` always check and download the latest ISO

# Environment

```
docker-machine -version
docker-machine version 0.4.1 (e2c88d6)
```

```
uname -a
Darwin vero.local 14.5.0 Darwin Kernel Version 14.5.0: Wed Jul 29 02:26:53 PDT 2015; root:xnu-2782.40.9~1/RELEASE_X86_64 x86_64
```

**Comment by nathanleclaire** [comment]
I do think that we should actually call out to Github and check the releases, then download the latest ISO if the cached version is out of date, if it is possible (Machine create shouldn't b0rk if the network is unavailable but a cached ISO is still around).

To that end, `boot2docker.iso` has some volume metadata set that allows querying of the version.  Here's a fun little Go example I've written to get that metadata:

```golang
package main

import (
        "bufio"
        "fmt"
        "log"
        "os"
)

// THANK YOU SO MUCH http://serverfault.com/questions/361474/is-there-a-way-to-change-a-iso-files-volume-id-from-the-command-line
const (
        isoVolumeIdOffset   = 0x8028
        fromBeginningOfFile = 0
        volumeIdLength      = 32
)

func main() {
        file, err := os.Open(os.Args[1])
        if err != nil {
                log.Fatal(err)
        }

        defer file.Close()

        if _, err := file.Seek(isoVolumeIdOffset, fromBeginningOfFile); err != nil {
                log.Fatal(err)
        }

        bufReader := bufio.NewReader(file)
        isoMetadata, err := bufReader.Peek(volumeIdLength)
        if err != nil {
                log.Fatal(err)
        }

        fmt.Println(string(isoMetadata))
}
```

This little string can then be parsed to get the version directly from the ISO file.

If anyone wants to help with this, go for it, and/or I can go implement it when I get some time.

**Comment by skatsuta** [comment]
I've also experienced this problem, and @nathanleclaire's sample code is interesting!
I may work on it...
