### ISSUE TITLE
Instead of probing machines via TCP, just try SSH-ing

### ISSUE THREAD

**Issue by PerilousApricot** [docker/machine#1794]
During startup, docker-machine tries opening the target SSH port before trying to connect with SSH. For machines only accessible via proxy, this Does The Wrong Thing, since it bypasses both ALL_PROXY and any ProxyCommand stanzas.

https://github.com/docker/machine/blob/89e6530528d4db67829fb82aa167b7aec835ab2a/drivers/utils.go#L73

Instead of looping until a TCP connection can be made, I'd suggest looping until an SSH connection can be made.

**Comment by nathanleclaire** [comment]
Good idea.  I'll look into this.

**Comment by prologic** [comment]
Related issue #1665 -- We need to address this; as many environments with private networks and Bashtion/Jump boxes makes using ``docker-machine`` **quite** hard :)

**Comment by PerilousApricot** [comment]
I fought quite unsuccessfully to get docker (the actual client) to work
through SSH's dynamicForwarding. Go's net library doesn't work with socks :(


-- 
Sent from Gmail Mobile

**Comment by prologic** [comment]
I thing the solution here is to use ``--native-ssh`` but for the code to respect this and **not** try to do port checks directly on a network it cannot access (*except via ssh'ing through a Bashtion/Jump host*).

**Comment by PerilousApricot** [comment]
That probably makes the most sense. I need to pull out the exact logs (away from my dev machine), but the other hitch I ran into is that (at least with the openstack plugin), docker-machine passes the ip name and not the hostname to ssh, which causes ```Host *.domain``` bits in ```.ssh/config``` to not work right. When I was kicking together my test, I got around it by manually adding the IP of the VM, but that's not ideal.

**Comment by nathanleclaire** [comment]
This is now fixed on master

**Comment by nathanleclaire** [comment]
@PerilousApricot Sounds like if there is a hostname available and an IP address is getting used instead, I'd consider that a bug with the Openstack driver but not the core SSH code.

**Comment by PerilousApricot** [comment]
@nathanleclaire I've had to take care of a different project in the ole priority queue, but when I come back around, i'll investigate that. Thanks!

**Comment by nathanleclaire** [comment]
:+1:
