### ISSUE TITLE
docker-machine restart overwites /var/lib/boot2docker/profile

### ISSUE THREAD

**Issue by oobles** [docker/machine#1798]
Just installed DockerToolbox 1.8.1c (docker-machine 0.4.1(e2c88d6) and boot2docker version 1.8.1 (build 7f12e95)) on OSX.  After making a change in /var/lib/boot2docker/profile and restarting the machine the changes in profile are overwritten. Creating a new file /var/lib/boot2docker/bootlocal.sh changes are not overwritten.

**Comment by oobles** [comment]
After a few more tests found that docker-machine env command overwrites profile and also updates certificates.

I'd like to update profile to add HTTP_PROXY and HTTPS_PROXY, but every time "Docker Quickstart Terminal" is started the profile settings are overwritten.  I'd also like to update the certificates used by docker.  Is there another way to configure docker daemon that will not be overwritten by "docker-machine env"?

**Comment by oobles** [comment]
After more investigation found that currently profile is updated by design by "docker-machine env".  The only way to update this is during "docker-machine create" using engine-env commands.  Using this it is possible to update HTTP_PROXY and HTTPS_PROXY.  eg.

docker-machine create -d virtualbox --engine-env HTTP_PROXY=http://<user>:<password>@<host>:<port> --engine-env HTTPS_PROXY=http://<user>:<password>@<host>:<port> default

I'm yet to find a way to use other certificates, but will open another issue for that.

**Comment by RickiWeb** [comment]
Hello, it's the first time that i work with docker and i don't have any idea where i find this path ? 
the root dierectry i mean :/ 
some help please !
