### ISSUE TITLE
Discover current b2d instances and add to store

### ISSUE THREAD

**Issue by ehazlett** [docker/machine#180]
Credit to shykes for this. This would allow for an easy transition from boot2docker to machine.

**Comment by ehazlett** [comment]
This will be part of a "b2d migration path" doc.  I will rebase this to get up to date with the latest vbox driver.

**Comment by teng-lin** [comment]
+1

**Comment by nathanleclaire** [comment]
This has largely been covered by the `--virtualbox-use-boot2docker-vm` flag IMO.
