### ISSUE TITLE
Error to detect powershell.exe

### ISSUE THREAD

**Issue by JonathanDaSilva** [docker/machine#1800]
Hi. The script as a little bit of trouble to detect my powershell.exe, this lead to fail when asking to create an hyper-v machine.

What happend is that in my path I have two path to Powershell Modules, witch mean that in both cases the path will look like *\WindowsPowerShell\Modules\*. This two one was pointing to the global powershell modules one and the personnal one into Documents.

Maybe the code should look to *\WindowsPowerShell\v.* instead of what he does for the moment.

I haven't add these path manualy, I'm in Windows 10 Pro.

If I'm not clear or something feel free to ask futher question.

Regards, Jonathan.
(I'm not a native english speaker so sorry to all mistake made :( )

**Comment by ehazlett** [comment]
Closing as duplicate to #639.  Thanks for reporting!
