### ISSUE TITLE
No certificate / key created when creating a new docker machine using the aws driver

### ISSUE THREAD

**Issue by bahaaldine** [docker/machine#1805]
Hi,

So I'm running docker-machine 0.4.1 and I'm basically trying to create a docker-machine on AWS.
The creation works, I can see my VM spinning up on AWS, but I can't switch my default machine on it, meaning the following command:

```bash
docker-machine env docker-machine-i1
```
returns:

```bash
open /Users/bahaaldine/.docker/machine/machines/docker-machine-i1/ca.pem: no such file or directory
```

A docker-machine ls gives:
```bash
NAME                ACTIVE   DRIVER       STATE     URL                         SWARM
default                      *        virtualbox   Running   tcp://192.168.99.100:2376   
docker-machine-i1            amazonec2    Running   tcp://XXX.XXX.XXX.XXX:2376 
```

This is how I've created the AWS machine:
```bash
docker-machine -D create \
    --driver amazonec2 \
    --amazonec2-access-key $AWS_ACCESS_KEY \
    --amazonec2-secret-key $AWS_SECRET_KEY \
    --amazonec2-vpc-id $AWS_VPC_ID \
    --amazonec2-zone b \
    docker-machine-i1
```

When I compare the content of 
```bash
/Users/bahaaldine/.docker/machine/machines/default
```
to 
```bash
/Users/bahaaldine/.docker/machine/machines/docker-machine-i1
```
Following files are missing:

```bash
ca.pem
cert.pem
server.pem
server-key.pem
```
My default environment variable are configured like following:
```bash
export DOCKER_HOST=tcp://192.168.99.100:2376
export DOCKER_CERT_PATH=/Users/bahaaldine/.docker/machine/machines/default
export DOCKER_MACHINE_NAME=default
export DOCKER_TLS_VERIFY=1
```

Still an :
```bash
eval "$(docker-machine env docker-machine-i1)"
```
gives:
```
open /Users/bahaaldine/.docker/machine/machines/docker-machine-i1/ca.pem: no such file or directory
```

Any thoughts?

Thanks,
Baha

**Comment by kurakin-oleksandr** [comment]
Same problem with digitalocean driver

**Comment by sameer-bridg** [comment]
+1

Experiencing the same issue on Amazon EC2.

**Comment by ehazlett** [comment]
You need to run `eval $(docker-machine env docker-machine-i1`.  You must use `eval` to load the config in your environment.

**Comment by n3at** [comment]
Had same issue, docker-machine 0.3.1.
Just regenerated certs, then it was ok:
`docker-machine regenerate-certs MACHINE_NAME`

**Comment by fourty7** [comment]
I'm unsure how running `eval "$(docker-machine env default --shell  bash)"` is a resolution to this issue. I'm having this same issue where it's not able to generate the certificates and the way that I go about figuring out that the certs haven't been generated is by running the above command:

`eval "$(docker-machine env default --shell bash)"
open C:\Users\{user}\.docker\machine\machines\default\ca.pem: The system cannot find the file specified.`

So far I have done pretty much everything I can think of to try to generate the certs and everything so far has failed. I've tried `regenerate-certs`, which results in the system just hanging and then doing nothing. I've tried fixing my proxy settings and restarting. I've tried recreating the vm several times.

I'm genuinely unsure as to what to do next in order to get this to work. As of right now my boot2docker VM can't access the outside world which makes it rather hard to do much of anything with it. The strange part is that I can `docker-machine ssh` into my vm.

**Comment by TrentBrown** [comment]
Having the same problem...  Am I supposed to go to my AWS console and generate a new keypair, and put that into my /Users/<me>/.docker/machine/machines/grafit-aws/ directory localy?

**Comment by montytorr** [comment]
I had exactly the same problem. turns out my AWS_SSH_USER was the wrong one. Could that be it ?

**Comment by edoardo-c** [comment]
As for me, the trick was to not send the docker-machine command to the background... go figure.

    $ docker-machine create -d digitalocean \
    >                         --digitalocean-access-token xxx \
    >                         --digitalocean-region fra1 \
    >                         --engine-label node=swarm-master \
    >                         --swarm \
    >                         --swarm-master \
    >                         --swarm-discovery="consul://$(docker-machine ip mh-keystore):8500" \
    >                         --engine-opt="cluster-store=consul://$(docker-machine ip mh-keystore):8500" \
    >                         --engine-opt="cluster-advertise=eth1:2376" \
    >                         mhs-demo0 &
    [1] 5506

    $ docker-machine create -d digitalocean \
    >                         --digitalocean-access-token xxx \
    >                         --digitalocean-region fra1 \
    >                         --engine-label node=swarm-node1 \
    >                         --swarm \
    >                         --swarm-discovery="consul://$(docker-machine ip mh-keystore):8500" \
    >                         --engine-opt="cluster-store=consul://$(docker-machine ip mh-keystore):8500" \
    >                         --engine-opt="cluster-advertise=eth1:2376" \
    >                         mhs-demo1 &
    [2] 5509

    $ cd ~/.docker/machine/machines/

    $ ls
    mh-keystore  mhs-demo0  mhs-demo1

    $ ls -lFA *
    mh-keystore:
    total 32
    -rw-rw-r--. 1 myuser myuser 1029 Nov 21 13:22 ca.pem
    -rw-rw-r--. 1 myuser myuser 1054 Nov 21 13:22 cert.pem
    -rw-------. 1 myuser myuser 1776 Nov 21 13:26 config.json
    -rw-------. 1 myuser myuser 1675 Nov 21 13:20 id_rsa
    -rw-------. 1 myuser myuser  381 Nov 21 13:20 id_rsa.pub
    -rw-------. 1 myuser myuser 1679 Nov 21 13:22 key.pem
    -rw-------. 1 myuser myuser 1679 Nov 21 13:23 server-key.pem
    -rw-rw-r--. 1 myuser myuser 1099 Nov 21 13:23 server.pem

    mhs-demo0:
    total 12
    -rw-------. 1 myuser myuser 1897 Nov 21 13:26 config.json
    -rw-------. 1 myuser myuser 1675 Nov 21 13:26 id_rsa
    -rw-------. 1 myuser myuser  381 Nov 21 13:26 id_rsa.pub

    mhs-demo1:
    total 12
    -rw-------. 1 myuser myuser 1898 Nov 21 13:26 config.json
    -rw-------. 1 myuser myuser 1679 Nov 21 13:26 id_rsa
    -rw-------. 1 myuser myuser  381 Nov 21 13:26 id_rsa.pub

I removed the machines and started again. If I now create them in the foreground using the same syntax as before I get:

    $ ls -lFa *
    mh-keystore:
    total 36
    drwx------. 2 myuser myuser 4096 Nov 21 13:23 ./
    drwx------. 5 myuser myuser   56 Nov 21 13:44 ../
    -rw-rw-r--. 1 myuser myuser 1029 Nov 21 13:22 ca.pem
    -rw-rw-r--. 1 myuser myuser 1054 Nov 21 13:22 cert.pem
    -rw-------. 1 myuser myuser 1776 Nov 21 13:44 config.json
    -rw-------. 1 myuser myuser 1675 Nov 21 13:20 id_rsa
    -rw-------. 1 myuser myuser  381 Nov 21 13:20 id_rsa.pub
    -rw-------. 1 myuser myuser 1679 Nov 21 13:22 key.pem
    -rw-------. 1 myuser myuser 1679 Nov 21 13:23 server-key.pem
    -rw-rw-r--. 1 myuser myuser 1099 Nov 21 13:23 server.pem

    mhs-demo0:
    total 36
    drwx------. 2 myuser myuser 4096 Nov 21 13:40 ./
    drwx------. 5 myuser myuser   56 Nov 21 13:44 ../
    -rw-rw-r--. 1 myuser myuser 1029 Nov 21 13:40 ca.pem
    -rw-rw-r--. 1 myuser myuser 1054 Nov 21 13:40 cert.pem
    -rw-------. 1 myuser myuser 1897 Nov 21 13:44 config.json
    -rw-------. 1 myuser myuser 1675 Nov 21 13:38 id_rsa
    -rw-------. 1 myuser myuser  381 Nov 21 13:38 id_rsa.pub
    -rw-------. 1 myuser myuser 1679 Nov 21 13:40 key.pem
    -rw-------. 1 myuser myuser 1675 Nov 21 13:40 server-key.pem
    -rw-rw-r--. 1 myuser myuser 1094 Nov 21 13:40 server.pem

    mhs-demo1:
    total 36
    drwx------. 2 myuser myuser 4096 Nov 21 13:47 ./
    drwx------. 5 myuser myuser   56 Nov 21 13:44 ../
    -rw-rw-r--. 1 myuser myuser 1029 Nov 21 13:47 ca.pem
    -rw-rw-r--. 1 myuser myuser 1054 Nov 21 13:47 cert.pem
    -rw-------. 1 myuser myuser 1898 Nov 21 13:44 config.json
    -rw-------. 1 myuser myuser 1675 Nov 21 13:44 id_rsa
    -rw-------. 1 myuser myuser  381 Nov 21 13:44 id_rsa.pub
    -rw-------. 1 myuser myuser 1679 Nov 21 13:47 key.pem
    -rw-------. 1 myuser myuser 1679 Nov 21 13:47 server-key.pem
    -rw-rw-r--. 1 myuser myuser 1094 Nov 21 13:47 server.pem

**Comment by Kuzmin** [comment]
FWIW, I'm experiencing the same issues as @edoardo-c above. I haven't been able to identify anything more useful than that removing the background run fixes the issue..

**Comment by desireB** [comment]
Hi,  I'm having the same issue as @TrentBrown.
Missing pem files in the Docker machine file. I open the ports in the SG, assigned a default subnet in the VPC group.  I'm not sending the creation commands to the background. 
This issue is not resolved, as it is still happening. What else do you suggest either to troubleshoot or to make it work? 
Thank you

**Comment by camposer** [comment]
In my case this did the trick:

`~/.docker/machine/machines/aws-sandbox$ ls -l
total 12
-rw------- 1 ubuntu ubuntu 3403 Aug  1 22:09 config.json
-rw------- 1 ubuntu ubuntu 1679 Aug  1 22:09 id_rsa
-rw------- 1 ubuntu ubuntu  381 Aug  1 22:09 id_rsa.pub
lrwxrwxrwx 1 ubuntu ubuntu   42 Aug  1 22:11 server-key.pem -> /home/ubuntu/.docker/machine/certs/key.pem
lrwxrwxrwx 1 ubuntu ubuntu   43 Aug  1 22:11 server.pem -> /home/ubuntu/.docker/machine/certs/cert.pem
`

After creation, I've just created symlinks to certificates in order directory. I think this also can be achieved changing config.json...

**Comment by drewcrawford** [comment]
Braindump from debugging this.

This error can be produced in the case that an SSH connection cannot be made to the remote machine, or that docker ultimately does not start up on the instance.

That can reflect, e.g. a provisioning issue.  It can also reflect an issue like #2898 where the instance does not start.  Further, it can reflect some configuration error, for example `ubuntu` is the default `amazonec2-ssh-user`, but for instances of some other OS, `ubuntu` is not a valid user and SSH will not succeed.
