### ISSUE TITLE
docker-compose does not truncate container logs

### ISSUE THREAD

**Issue by triptec** [docker/machine#1806]
I use docker-compose and it seems it outputs the accumulated logs every time i start it, so I use a alias like so:
`alias docker-logs-truncate="docker-machine ssh default -- 'sudo find /var/lib/docker/containers/ -iname \"*json.log\"|xargs -I{} sudo dd if=/dev/null of={}'"`

I'm wondering if there's a better way?

**Comment by nathanleclaire** [comment]
Hm, no way to do log rotation like this that I know of.  cc @aanand any ideas?

**Comment by aanand** [comment]
It's a bug, we're tracking it in https://github.com/docker/compose/issues/1946

**Comment by nathanleclaire** [comment]
Cool thanks @aanand .  @triptec please see that issue.
