### ISSUE TITLE
Dump VBox logs and daemon logs on machine error

### ISSUE THREAD

**Issue by nathanleclaire** [docker/machine#1807]

**Comment by dgageot** [comment]
Fixed with https://github.com/docker/machine/pull/2609

**Comment by nathanleclaire** [comment]
@dgageot I'd like the daemon logs (e.g. `/var/log/docker.log` file in boot2docker -- sometimes it's very helpful as libnetwork discovery etc. might fall over) as well so maybe we should open a new issue for that.
