### ISSUE TITLE
Make failures when setting options via `--engine-opt` more verbose

### ISSUE THREAD

**Issue by cel4** [docker/machine#1813]
I am currently trying to find out how to add a host entry to a docker-machine.

`docker-machine create tmp --driver virtualbox --engine-opt add-host=localhost:127.0.0.1`

will hang for a very long time in the `Starting VM` phase and ultimately fails:

```
Creating VirtualBox VM...
Creating SSH key...
Starting VirtualBox VM...
Starting VM...
Error creating machine: Maximum number of retries (60) exceeded
You will want to check the provider to make sure the machine and associated resources were properly removed.
```

Interestingly, I get the same behavior for `docker-machine create tmp1 --driver virtualbox --engine-opt foo=bar`, so I assume there is a bug in my syntax?

`docker-machine create tmp1 --driver virtualbox --engine-opt dns=127.0.0.1` seems to work.

Would it be possible to report the failure quicker and print a error message for debugging?

**Comment by booyaa** [comment]
[Syntax](https://github.com/docker/machine/blob/master/docs/reference/create.md) looks fine, `foo=bar` shouldn't work because it's not a docker engine [option](https://github.com/docker/docker/blob/master/docs/reference/run.md). What version of docker-machine and virtualbox are you using?

**Comment by cel4** [comment]
`docker-machine --version` -> docker-machine version 0.4.1 (HEAD)

`vboxmanage --version` -> 5.0.0r101573

debug log: https://gist.github.com/cel4/34dfe8d891a7666a8ec4

**Comment by cel4** [comment]
@ehazlett, the proposed enhancement is nice to have, but my primary goal is to find out why `add-host` does not play along with `--engine-opts` and see if this can be fixed.

**Comment by ehazlett** [comment]
@cel4 what version of docker are you using?  `add-host` does not appear to be a valid engine option in 1.8.1.

**Comment by cel4** [comment]
I am using `1.8.1` - I am not sure if I understood your comment. Is there a difference between optional docker command line arguments and engine options? `--add-host` is mentioned here. Did I miss anything? https://github.com/docker/docker/blob/master/docs/reference/run.md#managing-etchosts

**Comment by nathanleclaire** [comment]
@cel4 That documentation you link is for a `docker run` option. `--engine-flag` is for providing flags on the launched Docker daemon, e.g. `--bip` or `--storage-driver`.

**Comment by cel4** [comment]
@nathanleclaire, thanks for the clarification. I misunderstood the purpose of `--engine-opts`. I assumed it can be used to run every container with an additional `--add-host` flag. I guess I have to think about a different way to solve this problem.

**Comment by nathanleclaire** [comment]
Cool @cel4 , going to go ahead and close this one
