### ISSUE TITLE
[HELP] VirtualBox machine with local IP

### ISSUE THREAD

**Issue by oleynikd** [docker/machine#1825]
First of all - thank you guys for such a great tool!!!

I couldn't find solution so I'll ask here:
How can I start virtual box within my local network so other devices on the same network can access it?
When I manually select Network adapter to be "Bridged Adapter" in VirtualBox settings and the start VM from VirtualBox - everything works fine. Here's the screenshot:
![screenshot 2015-09-09 02 24 48](https://cloud.githubusercontent.com/assets/3976868/9749890/e29650e6-5699-11e5-9ff9-4916758a03d9.png)

But next time I do `docker-machine start` these settings are getting rewritten to default.

Thanks in advance.

**Comment by ehazlett** [comment]
Thanks!  You would need to add an additional network interface and set it for bridged.  Machine and B2D should ignore the extra adapter and let you access it directly.

**Comment by oleynikd** [comment]
This works. Thanks!
