### ISSUE TITLE
Error importing with generic driver on OS X

### ISSUE THREAD

**Issue by ahmetalpbalkan** [docker/machine#1833]
docker-machine version 0.4.1 (e2c88d6)

```
$ docker-machine create -d generic --generic-ip-address hellodocker.cloudapp.net --generic-ssh-user azureuser hellodocker
Importing SSH key...
Warning: got an invalid line error parsing /etc/os-release: %sExpected Saving password to keychain failed to split by '=' char into two strings, instead got 1 strings
Warning: got an invalid line error parsing /etc/os-release: %sExpected Saving password to keychain failed to split by '=' char into two strings, instead got 1 strings
Warning: got an invalid line error parsing /etc/os-release: %sExpected Identity added: /Users/alp/.docker/machine/machines/hellodocker/id_rsa ((null)) to split by '=' char into two strings, instead got 1 strings
```

I keep entering my cert password to the prompt, but no luck:

![image](https://cloud.githubusercontent.com/assets/159209/9802319/2c8d2622-57ce-11e5-9840-6f92c079782c.png)

it keeps asking over and over and prints the error above to the terminal in the meanwhile. Looks like there's also a Print vs Printf issue in the logs.

**Comment by nathanleclaire** [comment]
Argh.  Yes, we don't really support password-protected SSH keys right now, but we should.

**Comment by ahmetalpbalkan** [comment]
ah okay.

**Comment by ehazlett** [comment]
Yes, we want to add this but right now you would be prompted over and over for each ssh command that is sent.  Sorry!
