### ISSUE TITLE
Docker version drift

### ISSUE THREAD

**Issue by rgbkrk** [docker/machine#1839]
How do users deal with version drift across our running machines?

Let's say I deploy to a provider when I'm on Docker 1.6.1 then later deploy a server with version 1.7.0 Meanwhile, I've updated my local Docker client to 1.8.1. Along the way, we'll see

```
Error response from daemon: client and server don't have same version (client : 1.13, server: 1.12)
```

This only affects usage from the Docker CLI and won't affect e.g. docker-py, where you can specify the API version.

I'm half tempted to write a Docker Version Manager.

Related to #1702.

**Comment by ehazlett** [comment]
You can use the `docker-machine upgrade <name>` command.  That will update to the latest stable (or experimental version if you've specified that).

**Comment by rgbkrk** [comment]
If you do that, you'll have to migrate your containers too right?

**Comment by thaJeztah** [comment]
FYI, there's currently a PR in docker to allow overriding the API version that the client uses; https://github.com/docker/docker/pull/15964. It *is* considered a "power user" feature, because using a different API version could lead to unexpected behavior.

If I understand correctly, your use case would be to be able to "pin" machine to install a specific version of docker, I.e. install docker 1.7.x, even if docker 1.8 is available?

**Comment by rgbkrk** [comment]
My use case is a machine that was launched with an old version (that has running containers/services) yet I want to be able to do operations (possibly for the sake of migration to a newer version).

If specifying the API would be unstable, how would you feel about me writing a docker version manager, a la nvm, rvm, etc.? That would satisfy my needs.

**Comment by thaJeztah** [comment]
> My use case is a machine that was launched with an old version (that has running containers/services) yet I want to be able to do operations (possibly for the sake of migration to a newer version).

I think https://github.com/docker/docker/pull/15964 would be suitable for that situation, as long as you're not trying to go "too many versions" back. The reason for "warning" against it, is that, although the api is versioned, newer clients may not be fully backwards compatible with the older API.

If you (temporarily) need an older version of the docker client to work with an older daemon, you can still download all older binaries, using the instructions found at this page; https://docs.docker.com/installation/binaries/#get-the-docker-binary
