### ISSUE TITLE
azure driver import  packages which is not exist any more 

### ISSUE THREAD

**Issue by xiaohui** [docker/machine#1844]
azure's driver import an package `github.com/MSOpenTech/azure-sdk-for-go` which is not exist anymore. it will make ci/circleci check failed. 

>
go get -t -d -v ./...
github.com/MSOpenTech/azure-sdk-for-go (download)
package github.com/MSOpenTech/azure-sdk-for-go/clients/vmClient
	imports github.com/MSOpenTech/azure-sdk-for-go/clients/vmClient
	imports github.com/MSOpenTech/azure-sdk-for-go/clients/vmClient: cannot find package "github.com/MSOpenTech/azure-sdk-for-go/clients/vmClient" in any of:
	/usr/local/go/src/github.com/MSOpenTech/azure-sdk-for-go/clients/vmClient (from $GOROOT)
	/home/ubuntu/.go_workspace/src/github.com/MSOpenTech/azure-sdk-for-go/clients/vmClient (from $GOPATH)
	/usr/local/go_workspace/src/github.com/MSOpenTech/azure-sdk-for-go/clients/vmClient
go get -t -d -v ./... returned exit code 1
/home/ubuntu/.go_project/src/github.com/MSOpenTech/azure-sdk-for-go/clients/vmClient Action failed: go get

**Comment by ahmetalpbalkan** [comment]
You are not using godep. There's a vendored old version of azure-sdk-for-go here which works for machine.

**Comment by dmp42** [comment]
Thanks @ahmetalpbalkan 

Closing.

**Comment by xiaohui** [comment]
@ahmetalpbalkan @dmp42 It happened at ci/circleci tests, I don't know why not using godep for cirleci, but it actually effect  the PR's check, should we replace the `github.com/MSOpenTech/azure-sdk-for-go` package to the right one?

**Comment by ahmetalpbalkan** [comment]
@xiaohui nope not now, the new repo is entirely different than what we got here. I already have an open work item in this repo assigned to me to do that sometime. :)

**Comment by dmp42** [comment]
@xiaohui circleci tests are not ready. Please ignore circle for now. Sorry for the inconvenience.

**Comment by xiaohui** [comment]
👌thanks， @ahmetalpbalkan @dmp42
