### ISSUE TITLE
docker-machine 0.4.1 on Mac - confusing cmdline syntax

### ISSUE THREAD

**Issue by n0mer** [docker/machine#1854]
Hi,

here is the list of DO commands

```bash
$ docker-machine create --help | grep digitalocean
   --digitalocean-access-token 												Digital Ocean access token [$DIGITALOCEAN_ACCESS_TOKEN]
   --digitalocean-backups												enable backups for droplet [$DIGITALOCEAN_BACKUPS]
   --digitalocean-image "ubuntu-14-04-x64"										Digital Ocean Image [$DIGITALOCEAN_IMAGE]
   --digitalocean-ipv6													enable ipv6 for droplet [$DIGITALOCEAN_IPV6]
   --digitalocean-private-networking											enable private networking for droplet [$DIGITALOCEAN_PRIVATE_NETWORKING]
   --digitalocean-region "nyc3"												Digital Ocean region [$DIGITALOCEAN_REGION]
   --digitalocean-size "512mb"												Digital Ocean size [$DIGITALOCEAN_SIZE]
```

It is confusing.

## token arg
`--digitalocean-access-token` parameter should have the same argument example as `--digitalocean-image`, `--digitalocean-region` and `--digitalocean-size`. From `--help` it seems that this cmdline arg does not accept any argument

## true/false args
From this page https://docs.docker.com/machine/drivers/digital-ocean/ we can see that `--digitalocean-private-networking`, `--digitalocean-ipv6` and `--digitalocean-backups` all have default value of `false`. 

Does it mean that just `--digitalocean-private-networking` is `false` or `true`?
How should i say `true`? Here is my uneducated guess:
* `--digitalocean-private-networking`
* `--digitalocean-private-networking true`
* `--digitalocean-private-networking=true`

I am using `0.4.1` version of docker machine via this cask: https://github.com/caskroom/homebrew-cask/blob/d4cb55f195e638988a8905e6aea029e9d94f92f7/Casks/docker-machine.rb

**Comment by n0mer** [comment]
By the way - here are the quotes from Docker Support.

https://support.docker.com/hc/en-us/requests/6919

> Nick Hazlett September 08, 2015 18:27
Hi Nikolay,
The options --digitalocean-ipv6, --digitalocean-private-networking, and --digitalocean-backups don't have a value specified field, it's a boolean option. (if the option is specified, it's considered true) If you don't want private networking you don't pass the option, you can't pass true/false for it.

https://support.docker.com/hc/en-us/requests/6918

> the digitalocean-access-token option can be used with or without = and it should work fine

**Comment by nathanleclaire** [comment]
You don't have to specify the value, just the presence of those flags will indicate that you want to turn those options on:

```console
$ docker-machine create -d digitalocean --digitalocean-private-networking droplet
```

`false` is the default.
