### ISSUE TITLE
DNS settings in boot2docker become invalid over time or when switching networks

### ISSUE THREAD

**Issue by arun-gupta** [docker/machine#1857]
I've seen the following error when trying to pull Docker images at multiple events:

```
Pulling jenkins (arungupta/jenkins-docker-workflow:latest)...
Pulling repository docker.io/arungupta/jenkins-docker-workflow
Network timed out while trying to connect to https://index.docker.io/v1/repositories/arungupta/jenkins-docker-workflow/images. You may want to check your internet connection or if you are behind a proxy.
```

Typically restarting the Docker Machine solves the problem. This has worked for others as well as explained at:

http://stackoverflow.com/questions/31990757/network-timed-out-while-trying-to-connect-to-https-index-docker-io

This should not be required.

More details:

```
docker info
Containers: 2
Images: 53
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 57
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.0.9-boot2docker
Operating System: Boot2Docker 1.8.1 (TCL 6.3); master : 7f12e95 - Thu Aug 13 03:24:56 UTC 2015
CPUs: 1
Total Memory: 996.2 MiB
Name: pipeline
ID: S2GY:FA3E:7YDG:2LME:7NUW:R7LN:ON74:LPO5:4O6B:TJA6:AY5B:ENAY
Debug mode (server): true
File Descriptors: 16
Goroutines: 27
System Time: 2015-09-15T08:58:35.385599305Z
EventsListeners: 0
Init SHA1: 
Init Path: /usr/local/bin/docker
Docker Root Dir: /mnt/sda1/var/lib/docker
Username: arungupta
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
```

Docker Machine

```
docker-machine --version
docker-machine version 0.3.0 (0a251fe)
```

**Comment by arun-gupta** [comment]
Similar to https://github.com/docker/machine/issues/792

**Comment by nathanleclaire** [comment]
Just an idea (not sure if it will help), but restarting the daemon like `docker-machine ssh default sudo /etc/init.d/docker restart` might accomplish the same effect faster.

**Comment by nathanleclaire** [comment]
@arun-gupta Let me know if you're still experiencing this issue, please retry with 0.4.1 and re-open if you still see the issue.

**Comment by denmojo** [comment]
I am seeing this issue with 0.4.1.

**Comment by jpdesigndev** [comment]
Same issue here on 0.4.1:

`docker info`

```
Containers: 0
Images: 0
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 0
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.0.9-boot2docker
Operating System: Boot2Docker 1.8.2 (TCL 6.4); master : aba6192 - Thu Sep 10 20:58:17 UTC 2015
CPUs: 1
Total Memory: 996.2 MiB
Name: vb1
ID: M6TR:TYUC:5QLY:BFGA:73UT:SWI6:6YNX:F2UA:HW3T:TWWY:YMMZ:PGFC
Debug mode (server): true
File Descriptors: 10
Goroutines: 17
System Time: 2015-10-02T18:41:59.310630315Z
EventsListeners: 0
Init SHA1:
Init Path: /usr/local/bin/docker
Docker Root Dir: /mnt/sda1/var/lib/docker
Labels:
 provider=virtualbox
```

**Comment by benbc** [comment]
I see this with docker-machine 0.4.1.

**Comment by nathanleclaire** [comment]
I think it has to do with VirtualBox DNS resolution, right?  Does `docker-machine restart default` fix it?  Also, does updating `/etc/resolv.conf` to point to, say `8.8.8.8` fix it?

**Comment by patrickaroo** [comment]
Also having this on docker-machine version 0.4.1.

**Comment by cengizIO** [comment]
@nathanleclaire `docker-machine restart default` resolved the issue for now.

I don't know if it's going to happen again when I restart my host machine.

I'm on OSX El Capitan v10.11 by the way.

```
Containers: 4
Images: 41
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 49
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.0.9-boot2docker
Operating System: Boot2Docker 1.8.2 (TCL 6.4); master : aba6192 - Thu Sep 10 20:58:17 UTC 2015
CPUs: 1
Total Memory: 1.956 GiB
Name: default
ID: 22NK:XPSI:4WWV:VDLC:PUUO:VOPJ:FPY6:X6AQ:C7CY:ZHN4:NWR2:LMUS
Debug mode (server): true
File Descriptors: 21
Goroutines: 40
System Time: 2015-10-19T18:52:11.655474117Z
EventsListeners: 0
Init SHA1:
Init Path: /usr/local/bin/docker
Docker Root Dir: /mnt/sda1/var/lib/docker
Labels:
 provider=virtualbox
```

**Comment by ericandrewlewis** [comment]
Experience this regularly on `docker-machine version 0.4.1 (e2c88d6)`. Glad to be a guinea pig for questions / solutions.

> does updating /etc/resolv.conf in the VM to point to, say 8.8.8.8 fix it?

No.

> Does docker-machine restart default fix it? 

Yes.

**Comment by FreakTheMighty** [comment]
@nathanleclaire @ericandrewlewis @dancingshell the opposite was true for me.

>does updating /etc/resolv.conf in the VM to point to, say 8.8.8.8 fix it?
Yes.
>Does docker-machine restart default fix it?
No.

**Comment by nathanleclaire** [comment]
@ericandrewlewis @FreakTheMighty Can you make sure you try 0.5.0 to see if the problems persist?  Thanks.

**Comment by FreakTheMighty** [comment]
@nathanleclaire I just installed today and doubled checked the version. I'm on on 0.5.0.

**Comment by nathanleclaire** [comment]
Thanks @FreakTheMighty I will look into it.

**Comment by smerrill** [comment]
I am still getting this on a Mac with docker-machine 0.4.1 running 1.8.1 in a VM and it appears to be related to /etc/resolv.conf.

I started a docker-machine at home where my DNS gateway is 192.168.0.1. When I head into the office, that is no longer the proper DNS gateway, but /etc/resolv.conf in the VM still points to 192.168.0.1.

In my case, changing /etc/resolv.conf to point at 8.8.8.8 made `docker pull` commands start working immediately.

**Comment by dancingshell** [comment]
I had the same problem and changing /etc/resolv.conf to `8.8.8.8` works.

However, it seems that that file resets to default ip and then the machine can no longer connect to the internet. Any info on how this file gets set?

**Comment by nathanleclaire** [comment]
See https://github.com/docker/machine/pull/1069 for related discussion / dilemma

**Comment by nathanleclaire** [comment]
I'm not so sure if we can fix this one without introducing another set of new problems.  The alternative (use DNS pass-through to host) seems that it comes with a bag of issues which can't be remedied by a reset.  So, we might be stuck with recommending `restart`.

**Comment by nathanleclaire** [comment]
@docker/machine-maintainers ^^

**Comment by nathanleclaire** [comment]
We merged https://github.com/docker/machine/pull/2448 and https://github.com/docker/machine/pull/2467 so that users can change these default settings if they wish.  This is as close as we're going to get to a fix as we're relying on VirtualBox to do the right thing here.  In my experience it's been a "lesser of two evils" type situation where one needs to decide what is correct for their use case.

We do welcome additions to the troubleshooting which might explain how to deal with these issues if they come up.

**Comment by jakirkham** [comment]
@nathanleclaire, any clue how soon it will be until these additional settings land in a release?

**Comment by jeanlaurent** [comment]
@jakirkham we have a two weeks release cycle currently. Next release is scheduled for december 14th
