### ISSUE TITLE
Specifying another port than 2376 when machine checks docker daemon presence at creation time

### ISSUE THREAD

**Issue by efrecon** [docker/machine#1858]
I am looking for a way to specify another port than `2376` when docker machine waits for the presence of the docker daemon on the remote host, after it has installed the docker daemon and arrange for it to start.

My use case is that I am trying to support remote machines that are behind a NAT. I have setup a persistent [reverse ssh tunnel](https://raymii.org/s/tutorials/Autossh_persistent_tunnels.html) to be able to access them and am trying to use the generic driver from [machinery](https://github.com/efrecon/machinery). Using the tunnel I can provide `machine` with options like `--generic-ip-address 127.0.0.1 --generic-ssh-port 10000` (note the use of the `localhost` IP address and, thus, a local port, tunneled to the remote ssh port). I could setup a second tunnel to access port `2376` on the remote as locally on the server running machine/machinery, but this requires me to be able to pinpoint something else that `2376` and hand this port to docker machine. Any ideas?

**Comment by nathanleclaire** [comment]
Yeah, I've run into this writing a `dind` driver as a plugin with the new stuff as well.  I think that we need to move longer-term to not simply relying on `GetURL` to get the daemon URL for provisioning and so on, but need to define any new model carefully.

**Comment by efrecon** [comment]
Actually, I think that a fix for #1820 would perhaps be sufficient. Checking for proper presence and functioning of the docker daemon can be tricky if you wanted to cover all the corner cases and different distributions.

My current implementation in [machinery](https://github.com/efrecon/machinery) checks that there is a running process with a number matching the one announced in the file at `/var/run/docker.pid` Check the procedure called `DaemonPID` in [this file](https://github.com/efrecon/machinery/blob/master/lib/cluster/unix.tcl) for details. Machinery performs those checks solely through the ssh connection to the remote machine.

I deemed that this was sufficient, even though this does not check that it properly responds to the Docker API on port `2376`, and this might be wrong. Also, it takes a number of assumptions as to where the PID file is stored, etc.
