### ISSUE TITLE
Debugging errors on docker server

### ISSUE THREAD

**Issue by brucardoso2** [docker/machine#1861]
Hi,
I'm trying to use docker on windows and gave it a shot to docker-machine.
```
$ docker-machine.exe env default --shell cmd
set DOCKER_TLS_VERIFY=1
set DOCKER_HOST=tcp://192.168.56.102:2376
set DOCKER_CERT_PATH=C:\Users\ribeirob.AUTH\.docker\machine\machines\default
set DOCKER_MACHINE_NAME=default
# Run this command to configure your shell:
# copy and paste the above values into your command prompt
```
After setting this on my cmd, I tried to `docker ps`
```
C:\Users\ribeirob.AUTH>docker ps
An error occurred trying to connect: Get https://192.168.56.102:2376/v1.20/containers/json: Service Unavailable
```
Can you guys give me a hint on how to debug what's going on with my docker server?
I tried to ssh into the server, however it asks for a password which I don't have.

**Comment by nathanleclaire** [comment]
Is it `virtualbox` driver?

**Comment by brucardoso2** [comment]
@nathanleclaire yes

**Comment by nathanleclaire** [comment]
Does `docker-machine.exe ssh default docker version` work correctly?

**Comment by brucardoso2** [comment]
@nathanleclaire worked
```
$ docker-machine.exe ssh default docker version
Client:
 Version:      1.8.1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   d12ea79
 Built:        Thu Aug 13 02:49:29 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   d12ea79
 Built:        Thu Aug 13 02:49:29 UTC 2015
 OS/Arch:      linux/amd64
```
as other commands as well. Didn't known about `docker-machine ssh`.
So the question is, why it doesn't work with just `docker`?

**Comment by dgageot** [comment]
@brucardoso2 can you try again with `Virtualbox 5` and `docker-machine 0.5.1`?

**Comment by nathanleclaire** [comment]
@brucardoso2 It indicates that the route assigned by VirtualBox DHCP (the IP for the VM) is not reachable by the host.  There are a number of issues that might cause this.  As @dgageot mentioned, please try with Docker Machine 0.5.1 if you haven't already and maybe post the output of a `docker-machine --debug create -d virtualbox foo` as well if you're willing.

**Comment by dgageot** [comment]
Hi, @brucardoso2 did you get a chance to test a more recent version?

**Comment by dmp42** [comment]
Closing for bookkeeping. @brucardoso2 if you still have issues, let us know and we will reopen.
