### ISSUE TITLE
eval env command bugs when enable MACHINE_DEBUG flag

### ISSUE THREAD

**Issue by zchee** [docker/machine#1863]
When enable `MACHINE_DEBUG=1` flag, `docker-machine env ****` commnad is print the unnecessary outputs.

For example, vmware driver...

```bash
$ export MACHINE_DEBUG=1
$ docker-machine env vmware

# result...
shell: zsh
executing: /Applications/VMware Fusion.app/Contents/Library/vmrun list
MAC address in VMX: 00:0c:29:5d:09:3f
IP found in DHCP lease table: 192.168.***.**
export DOCKER_TLS_VERIFY="1"
export DOCKER_HOST="tcp:/192.168.***.**:2376"
export DOCKER_CERT_PATH="/Users/zchee/.docker/machine/machines/vmware"
export DOCKER_MACHINE_NAME="vmware"
# Run this command to configure your shell:
# eval "$(docker-machine env vmware)"
```
Ok. Fine.

but, when eval...
```bash
$ export MACHINE_DEBUG=1
$ eval $(docker-machine env vmvare)

# result...
zsh: command not found: shell:
zsh: command not found: executing:
zsh: command not found: MAC
zsh: command not found: IP
```
Executed `shell`,`executing`, `MAC`, `IP` command on zsh.

This problem caused by line https://github.com/docker/machine/blob/master/commands/commands.go#L665-L683 and https://github.com/docker/machine/blob/master/drivers/vmwarefusion/fusion_darwin.go#L463-L466 and more.

**This error will operate in almost all of the driver.**

amazonec2 driver...
```bash
$ export MACHINE_DEBUG=1
$ eval "$(docker-machine env amazonec2-docker)"

zsh: command not found: shell:
zsh: command not found: Making
zsh: command not found: Action:
zsh: command not found: DescribeInstances
zsh: command not found: ],
zsh: command not found: InstanceId.1:
zsh: command not found: i-cf73e06d
zsh: command not found: ],
zsh: command not found: Version:
zsh: command not found: 2014-06-15
zsh: command not found: ]
```

In a security point of view, I think it dangerous.

How do you think?

**Comment by zchee** [comment]
This problem is due to the prepared flag, always because the debug log is output.

Debug flag did not been adapted to eval until now.
but, it will be always enabled by the `export MACHINE_DEBUG = 1`

**Comment by zchee** [comment]
virtualbox's misery... :scream:

**Comment by nathanleclaire** [comment]
Debug logs should go to STDERR, not STDOUT.  I have a fix for this in the libmachine / plugins work, but I don't think it's made its way upstream yet, so if you are willing to hang tight for a little while it will get fixed.

**Comment by yonah-codefresh** [comment]
It seems that the debug output can also be triggered with a plain DEBUG env var, not necessarily MACHINE_DEBUG. It would be nice if this didn't happen IMO.

**Comment by nathanleclaire** [comment]
On master / RC all logs will go to STDERR so @zchee issue should be fixed.  Likewise using `MACHINE_DEBUG` over `DEBUG` seems to work.  Please re-open if the RC does not fix these issues.

**Comment by zchee** [comment]
@nathanleclaire I tried a little while ago.
It seems to solve the current master branch :)

Thanks for remember the this issue!
