### ISSUE TITLE
Wrote a little script to run  eval "$(docker-machine env dev)"

### ISSUE THREAD

**Issue by snehesht** [docker/machine#1868]
https://gist.github.com/snehesht/5cfa5885208a633e4826

**Comment by nathanleclaire** [comment]
Good times!  I have something similar for my shell, and it makes me wonder if we should potentially have a section in the Wiki or elsewhere that we track these types of things.

**Comment by snehesht** [comment]
yeah we definitely should, the eval function works perfectly on bash shell on windows but if you're using cmd (conemu)  then it's little difficult. so I wrote this.

**Comment by nathanleclaire** [comment]
I'm going to close this as there's no action item, however keep us in mind if/when we add a wiki with these types of tricks.
