### ISSUE TITLE
~/.ssh/config interferes with SSH calls

### ISSUE THREAD

**Issue by bfirsh** [docker/machine#1896]
threescoops on IRC reported an issue where machines were taking ages to boot up. It turned out to be _something_ in his ~/.ssh/config causing it to be slow - moving the file and running again fixed the issue.

Perhaps Machine should ignore ~/.ssh/config, or have its own location for configuring SSH?

**Comment by nathanleclaire** [comment]
We set some options manually in the `ssh` command with `-o`, but I actually hadn't thought of simply specifying an alternate config file- looks like the `-F` option for `ssh` will do it.  I'm for it, although I'm not sure what the best file to use would be.  `/dev/null` seems reasonable, I'm not sure how that works on Windows though (FWIW I think we're already doing it with `KnownHostsFile`, perhaps in error).

**Comment by nathanleclaire** [comment]
OTOH, looks like using the config file is actually the desired behavior for some users, e.g. https://github.com/docker/machine/issues/1665

It'd be really helpful to know which SSH configuration settings in particular were problematic.

**Comment by bfirsh** [comment]
Perhaps it could use `~/.docker/machine/ssh/config` or something like that.

**Comment by bazbremner** [comment]
@bfirsh Thanks for opening this bug. Apologies for not being able to give an details of the specific issue, I had quite a substantial ~/.ssh/config, although I'd guess that a ProxyCommand statement was the likely culprit, but haven't had the time to experiment.

**Comment by jitakirin** [comment]
Could it be SSH multiplexing (#1572)?

In any case I also think ignoring user's SSH config is undesired, it is usually there for a reason (reducing auth prompts, multi-hop connections, etc.).  I think it would be better to work out which option is causing issues and adjusting code to work with it.  E.g. for SSH multiplexing the most likely culprit is (as mentioned in #1572) that SSH has a bug where it leaves stderr open in the daemonized process, which could possibly be worked around.

**Comment by bazbremner** [comment]
@jitakirin I suspect so - I did have multiplexing in my previous SSH config. It probably makes sense to close this issue in favour of #1572.

**Comment by dgageot** [comment]
Closing in favour of https://github.com/docker/machine/issues/1572 that itself is fixed
