### ISSUE TITLE
Machine configuration file should have a version field

### ISSUE THREAD

**Issue by bfirsh** [docker/machine#190]
This will make updating the format of config.json less of a PITA in the future. We can have some kind of upgrade procedure that knows how to migrate config versions.

**Comment by ehazlett** [comment]
+1

**Comment by bfirsh** [comment]
At some point we should also separate out the internal representation of hosts from the configuration file format so we can change internals without worrying about breaking configuration files.

**Comment by nathanleclaire** [comment]
Been thinking about this exact thing lately.  +1 from my end.

**Comment by nathanleclaire** [comment]
> At some point we should also separate out the internal representation of hosts from the configuration file format so we can change internals without worrying about breaking configuration files.

Do you have some more thoughts on this @bfirsh ?

**Comment by nathanleclaire** [comment]
This has now been implemented for a wihle

**Comment by bfirsh** [comment]
Niccceee

**Comment by bfirsh** [comment]
@nathanleclaire About internal representation of hosts... This has bitten Engine where they just dump the internal struct for API calls and now it's a pain to refactor internals, etc. Just good practice to have explicit serialisation steps, I think.
