### ISSUE TITLE
Windows 10 - SSH Error When Setting Hostname (exit status 2: sh: syntax error: unterminated quoted string)

### ISSUE THREAD

**Issue by carolynvs** [docker/machine#1906]
I wanted to try out the fix from PR #1882 so I am using a local build of master (c4cd238) on Windows 10 with Virtualbox. It looks like a bug may have been introduced in 2a15d98.

When I run `docker-machine -D create default --driver virtualbox` or `docker-machine regenerate-certs default`, it fails when setting the host name with the error **unterminated quoted string**. Here's a link to the [full output from both commands](https://gist.github.com/carolynvs/457f67bbcc1fffe3e78a), the important part is below.

```
Using SSH client type: external
About to run SSH command:
sudo /usr/bin/sethostname default && echo "default" | sudo tee /var/lib/boot2docker/etc/hostname
&{C:\Program Files\Git\usr\bin\ssh.exe [C:\Program Files\Git\usr\bin\ssh.exe -o PasswordAuthentication=no -o IdentitiesOnly=yes -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=quiet -o ConnectionAttempts=3 -o ConnectTimeout=10 -o ControlMaster=no -o ControlPath=no docker@127.0.0.1 -i C:\Users\caro8994\.docker\machine\machines\default\id_rsa -p 49654 sudo /usr/bin/sethostname default && echo "default" | sudo tee /var/lib/boot2docker/etc/hostname] []  <nil> <nil> <nil> [] <nil> <nil> <nil> <nil> false [] [] [] [] <nil>}
SSH cmd err, output: exit status 2: sh: syntax error: unterminated quoted string
```

I edited `boot2docker.go` `SetHostname` to not quote the docker machine name in the echo command
which fixed the problem. I'd be happy to send a PR if this seems like an appropriate change (dropping the quotes).

```go
func (provisioner *Boot2DockerProvisioner) SetHostname(hostname string) error {
	if _, err := provisioner.SSHCommand(fmt.Sprintf(
		"sudo /usr/bin/sethostname %s && echo %s | sudo tee /var/lib/boot2docker/etc/hostname",
		hostname,
		hostname,
	)); err != nil {
		return err
	}

	return nil
}
```

**Comment by nathanleclaire** [comment]
Go ahead and send a PR, please. I'd like to review it.

**Comment by gmanfunky** [comment]
Could it be an escaping problem with the way we are executing ssh command and the arguments being sent? Perhaps the command pipe and/or double-quotes aren't properly escaped.

**Comment by nathanleclaire** [comment]
It's a problem with the way that SSH commands are being handled internally for the provisioning process.  It's something I accidentally broke in getting the SSH additional command arguments to work, e.g. `docker-machine ssh default -L 8080:localhost:8080`.  I'm working on a fix now and should have it PRed soon.
