### ISSUE TITLE
Swarm creation with docker machine

### ISSUE THREAD

**Issue by bergtwvd** [docker/machine#1911]
Followed the example for creating a swarm on https://docs.docker.com/swarm/install-w-machine.

Using Windows 7, Virtual Box 5.0.4 and Docker 1.8.2.

However. I am not able to create a swarm.
The VM is created in VB, but after waiting a long time, I get on Windows:

$ docker-machine create -d virtualbox --swarm --swarm-master --swarm-discovery token://07888a9864d382857ada80bba59a310b swarm-master
Creating VirtualBox VM...
Creating SSH key...
Starting VirtualBox VM...
Starting VM...
Error creating machine: Maximum number of retries (60) exceeded
You will want to check the provider to make sure the machine and associated resources were properly removed.

The VM is running in VB, and I can login to it. There are no images present (I expect there would be a swarm image, right?).

What should have been the end-result of the VM?
Any ideas?

**Comment by bergtwvd** [comment]
docker machine appears to hang.
At another try I get:
$ docker-machine create -d virtualbox --swarm --swarm-discovery token://07888a9864d382857ada80bba59a310b swarm-slave-1
Creating VirtualBox VM...
Creating SSH key...
Starting VirtualBox VM...
Starting VM...

Nothing happens here for a long time.
Is this the same as: #1787 (which is closed. And fixed?)

**Comment by dgageot** [comment]
Hi @bergtwvd, can you try again with version 0.5.0rc4? If it still fails, can you gist the output of the command?

**Comment by bergtwvd** [comment]
Sorry to take so long to get back.
In installed Docker 1.9.0 (Virtual Box on Windows), and upgrade docker-machine to 0.5.0 (Windows 7).

I do the following below and run into an issue (described at the end here under).

====================
C:\Users\bergtwvd\bin> .\docker-machine.exe create -d virtualbox --swarm --swarm-image="swarm" --swarm-master --swarm
-discovery="consul://$(docker-machine ip mh-keystore):8500" --engine-opt="cluster-store=consul://$(docker-machine ip mh-
keystore):8500" --engine-opt="cluster-advertise=eth1:2376" mhs-demo0
Running pre-create checks...
Creating machine...
Waiting for machine to be running, this may take a few minutes...
Machine is running, waiting for SSH to be available...
Detecting operating system of created instance...
Provisioning created instance...
Copying certs to the local machine directory...
Copying certs to the remote machine...
Setting Docker configuration on the remote daemon...
Configuring swarm...
WARNING >>>
This machine has been allocated an IP address, but Docker Machine could not
reach it successfully.

SSH for the machine should still work, but connecting to exposed ports, such as
the Docker daemon port (usually <ip>:2376), may not work properly.

You may need to add the route manually, or use another related workaround.

This could be due to a VPN, proxy, or host file configuration issue.

You also might want to clear any VirtualBox host only interfaces you are not using.
To see how to connect Docker to this machine, run: C:\Users\bergtwvd\bin\docker-machine.exe env mhs-demo0
PS C:\Users\bergtwvd\bin> .\docker-machine.exe env mhs-demo0
Error running connection boilerplate: Error checking and/or regenerating the certs: There was an error validating certif
icates for host "192.168.99.100:2376": dial tcp 192.168.99.100:2376: i/o timeout
You can attempt to regenerate them using 'docker-machine regenerate-certs name'.
Be advised that this will trigger a Docker daemon restart which will stop running containers.
============================

The issue I think is that the VB image gets a Host Only Adapter with some IP address, and that the internal eth1 address is different (this address is assigned by the VB DHCP server). This address (eth1) is unreachable from the outside, whence docker-machine cannot login in. Docker-machine should use the Host Only Adapter address instead. Right?

**Comment by nathanleclaire** [comment]
I think I have seen an issue like this and the problem was that there were duplicate host only interfaces as mentioned in https://github.com/docker/machine/issues/2231.  @bergtwvd when you get a chance can you please paste the (verbose) output of a Docker Machine create with the `docker-machine --debug` flag set?  In particular I'm interested to see which host only interfaces exist on your machine.

**Comment by bergtwvd** [comment]
Just to let you know that I have re-installed Docker-Toolbox 1.9.0b to have a clean baseline.
Before I get further on the above issue, I ran into another issue (seen before, but ignored it so far), I submit that as a new issue.

**Comment by bergtwvd** [comment]
The re-install cleaned up the issue somehow. Now there is only one Host Only Adapter created for all Docker VMs inside VB, with the proper IP addresses used by all. So, I can only close the issue ...

**Comment by nathanleclaire** [comment]
Nice, thanks for following up to close @bergtwvd
