### ISSUE TITLE
`create` silently ignores trailing options

### ISSUE THREAD

**Issue by willpriceb** [docker/machine#1914]
Hi,

I spent most of my day debugging a problem caused by specifying trailing options on `docker-machine create --driver virtualbox default <more options>`, it'd be nice to have some sort of warning message when there are extra arguments specified to alert the user that it will not perform the desired behaviour.

**Comment by jpetazzo** [comment]
Same here. I was trying to provision Swarm-enabled machines with:

```
docker-machine create -d amazonec2 node00 --swarm --swarm-master --swarm-discovery token://$TOKEN
```

And it didn't work (the machine would come up but no Swarm provisioning was done, and `--debug` was showing that the Swarm code was never executed).

After a few hours of debugging, I found out that the following would work, though:

```
docker-machine  create node00 -d amazonec2 --swarm --swarm-master --swarm-discovery token://$TOKEN
```

/cc @nathanleclaire

**Comment by dgageot** [comment]
Would you consider it ok to fail with a warning if there are more options than just the machine name?

**Comment by willpriceb** [comment]
That'd be better than silently failing IMO. I'm not sure if there is a more
desirable behaviour that could be achieved?

**Comment by dgageot** [comment]
We could imagine being able to consider trailing flags being valid flags.
It looks much more complicated than just failing though!

**Comment by willpriceb** [comment]
If it's possible then I think that would result in the best end user
experience, might be *fun* to implement though ;)

**Comment by dgageot** [comment]
I gave a shot to a PR. That's pretty simple. Can you take a look?
I'd like to add tests but would like to make sure it does the job first.
