### ISSUE TITLE
Can't "gcloud ssh" into docker-machine

### ISSUE THREAD

**Issue by DazWilkin** [docker/machine#1916]
Google Compute Engine (GCE) automates key generation for approved users of the project to which instances are scoped using Google Developers Console and the gcloud CLI. This permits any authenticated user of the project to access|manipulate instances. Unfortunately, it appears docker-machine breaks Google's mechanism:
```
docker-machine create [INSTANCE-NAME] \
--driver google \
--google-project [MY-PROJECT-ID] \
--google-zone [GOOGLE-ZONE]
```
Correctly permits:

    docker-machine ssh [INSTANCE-NAME]

However, a Google developer would expect to be able to:

    gcloud compute --project [MY-PROJECT-ID] ssh --zone [GOOGLE-ZONE] [INSTANCE-NAME]

This errors:
```
Warning: Permanently added 'XX.XX.XX.XX' (ECDSA) to the list of known hosts.
Permission denied (publickey).
ERROR: (gcloud.compute.ssh) [/usr/bin/ssh] exited with return code [255]. See https://cloud.google.com/compute/docs/troubleshooting#ssherrors for troubleshooting hints.
```

This is because, docker-machine has created an sshKeys entry in the instance's metadata for docker-user. The act of adding a single user manually, stops gcloud from managing user credentials. See here:

https://cloud.google.com/compute/docs/instances/managing-ssh-keys

To revert to gcloud management of user credentials (but break docker-machine's credential management), it's possible to delete the ssKeys entry for the instance:

    gcloud compute instances remove-metadata [INSTANCE-NAME] --keys sshKeys

Or, edit the keys in the console:

https://console.developers.google.com/project/[MY-PROJECT-ID]/compute/metadata/sshKeys

Once this is done, it's possible to ssh using gcloud ssh.

Alternatively, it should be possible to force gcloud to use the docker-machine generated credentials *but* I believe because of the incorrect format, this does not work. The docker-machine created credentials for docker-user appear to not be in this format and I was unable to get this to work:

https://cloud.google.com/compute/docs/instances/managing-ssh-keys#ssh_key_format
https://cloud.google.com/compute/docs/instances/connecting-to-instance#gcloudownkeys

Full disclosure: I'm a Google employee in cloud but not a developer

**Comment by dgageot** [comment]
@DazWilkin Have you tried with Docker Machine 0.6.0-rc? I don't think that anything was fixed but at least we would get a refresh.

**Comment by DazWilkin** [comment]
Will try it next week once back from vacation.

>

**Comment by DazWilkin** [comment]
The issue appears to be resolved but I don't understand why :-(

I'm able to  create a machine, docker-machine ssh and gcloud ssh into it without problem:

```
docker-machine.exe version 0.6.0-rc1, build 174e390
Docker version 1.10.0-rc2, build c1cdc6e
```

**Comment by dgageot** [comment]
Some would say magic?

**Comment by dgageot** [comment]
I changed the way ssh key metadata management is done. This might have an impact. I'll check further tomorrow to give you a better answer!

**Comment by dgageot** [comment]
@DazWilkin The only thing that changed is that with https://github.com/docker/machine/commit/b995a4d65a3e666b6cdec79036db0379b3d58b69, ssh metadata are better formed.
Anyways, happy to see everything is working ok
