### ISSUE TITLE
enable docker-machine to create remote virtualbox machines

### ISSUE THREAD

**Issue by iangkent** [docker/machine#1918]
Currently the virtualbox driver for docker-machine allows users to create local virtualbox machines.
It would be useful to be able to also create remote virtualbox machines. The driver would need to be able
to call virtualbox webservice to create machines on remote host. This is useful for the following scenarios:

- being able to create docker machines on remote headless virtualbox manager (poor mans micro cloud)
- being able to create docker machines on virtualbox host from python scripts running on docker container

**Comment by nathanleclaire** [comment]
Would probably make a good [driver plugin](https://github.com/docker/machine/pull/1902).  The current `virtualbox` driver is pretty focused on local machines.

**Comment by dgageot** [comment]
@docker/machine-maintainers With the introduction of driver plugins, we should close this ticket, shouldn't we?

**Comment by nathanleclaire** [comment]
Yep -- I don't see it being a high priority on our immediate roadmap
