### ISSUE TITLE
Doc for building docker-machine

### ISSUE THREAD

**Issue by jeffellin** [docker/machine#1919]
after much struggling I finally was able to get docker-machine built without the container.  My motivation for this was to be able to run the integration tests that currently will not run in the container.

Here is what I did that wasn't in the docks.  Being new to Go, most of this was groked from reading the Dockerfile.

git clone https://github.com/docker/machine.git /tmp/go/machine
mkdir -p /tmp/go/work/src/github.com/docker
cp -R /tmp/go/machine /tmp/go/work/src/github/com/docker
export GOROOT=/usr/local/go
export GOPATH=/tmp/go/work
cd /tmp/go/work/src/github/com/docker/machine
go get  github.com/mitchellh/gox
go get github.com/golang/lint/golint
go get github.com/mattn/goveralls
go get golang.org/x/tools/cover
go get  github.com/tools/godep
go get github.com/aktau/github-release
make build

if any steps here were not necessary I'd appreciate hearing them.  I'd be happy to update the doc if people feel that this information is a) correct and b) useful

**Comment by dmp42** [comment]
This is why the container solution is provided as a sane default (eg: to save the hassle setting-up a golang env).

Furthermore, I believe setting up a working golang env is out of scope.
Also, you don't need any extra dependency (go get) if you just want to build.

**Comment by jeffellin** [comment]
The container is great for what it can do,  but as far as I can tell it can't be used for the integration tests. 

Maybe it doesn't need to be as overly verbose but something as simple as saying that your code needs to be in GOPATH/src/github/com/docker/machine would have saved me a bunch of time.  The docs as is seem to imply that all I have to do is unset USE_CONTAINER and then run make build from the same location.

Anyway maybe this is all know information for those working with Go for a while,  but I am just learning and finally think I understand what is going on in regards to GOPATH.

**Comment by nathanleclaire** [comment]
Thanks for the feedback @jeffellin .  The recent shakeups to the build model have definitely made it less clear how to proceed and I think that historically having a clear path to start developing on the project has been very valuable to us.  I'll see what I can do to clarify and/or simplify the process.

**Comment by jeffellin** [comment]
I am guessing the go gets are in the Dockerfile to simply allow for caching,   although maybe it isn't useful since it appears that the container is removed in the makefile.

Anyway to simplify what I have above

```
export GOROOT=/usr/local/go
export GOPATH=/tmp/go/work
git clone https://github.com/docker/machine.git /tmp/go/machine
#copy the contents of the cloned repo to the correct package in your $GOPATH.
mkdir -p $GOPATH/src/github.com/docker
cp -R /tmp/go/machine $GOPATH/src/github/com/docker
cd $GOPATH/src/github/com/docker/machine
make build
```

Like I said what really got me was the assumption that I could run the make right from the directory where I cloned the repo from. Being used to maven/gradle  this was immediately apparent.

**Comment by dmp42** [comment]
@nathanleclaire there previously was no way to build natively, and never was any indication about how to setup a native go environment: https://github.com/docker/machine/blob/28831d1f65e6aa0215339a8209c3589d6db33f29/CONTRIBUTING.md

Can you elaborate on how "the build model have definitely made it less clear how to proceed"? I would be happy to fix it.

**Comment by jeffellin** [comment]
I guess a better question might be ,  is it possible to make integration tests run within in the container.  I am thinking it is possible for remote drivers like ec2 or gcp,  but may be tougher for local drivers like virtualbox or fusion.

**Comment by dgageot** [comment]
We could explain that go has to be properly installed (with GOROOT and GOPATH set).
Then building natively should be as easy as:

```
go get github.com/docker/machine
cd $GOPATH/src/github.com/docker/machine
make build
```

Am I missing something?

**Comment by dmp42** [comment]
@dgageot that would be enough indeed.
Doc has been massaged a bit over here: https://github.com/docker/machine/pull/1949

Specifically, I made integration testing more brainless and straight-forward.

Additional info about basic golang setup can go on top of this.

**Comment by dgageot** [comment]
Hi @jeffellin, the doc was updated since your report. Do you think it's ok now?

**Comment by jeffellin** [comment]
@dgageot While this is better I would still like to see a paragraph on where to clone the repository to.  Simply "Then clone the machine repository inside your gopath" is confusing to a new go user since it needs to be in a specific subdirectory.

I do like your idea of the following

```
go get github.com/docker/machine
cd $GOPATH/src/github.com/docker/machine
make
```

**Comment by blaggacao** [comment]
I tried out the new release candidate and it has an issue on hyperv.

This is a case where I have no access to the docker runtime and need to build go "traditionally".

I'm caged by not being able to build without containers.

**Comment by blaggacao** [comment]
I want to test a PR, so maybe the simplest thing would be to follow:
```
go get github.com/docker/machine
cd $GOPATH/src/github.com/docker/machine
make
git fetch origin pull/ID/head:BRANCHNAME
```
It doesn't work when I go get my fork, as I'm new to go, I can't judge, if this is expected to not to work ootb...

**Comment by nathanleclaire** [comment]
It's a silly issue with package naming that has now been fixed on master.  Will be following up with a rc2 shortly.
