### ISSUE TITLE
Valid hostname check #399 Better Messaging Required

### ISSUE THREAD

**Issue by alexmcroberts** [docker/machine#1922]
I've just been bitten by this - although partially address in #399. #383 shows the exact problem - including `_` underscores in a name. Perhaps a message suggesting valid characters would go a ways to improving error communication

**Comment by kacole2** [comment]
@alexmcroberts i added in a small nugget for better error messaging. #1957

**Comment by kacole2** [comment]
@alexmcroberts this can be closed

**Comment by alexmcroberts** [comment]
Excellent! Thanks for the fix!
