### ISSUE TITLE
docker-machine create using wrong username with CentOS7 AMI?

### ISSUE THREAD

**Issue by rhim** [docker/machine#1923]
I tried to use the CentOS7 AMI ami-6bcfc42e to create a docker-host VM in EC2. It failed to create after 60 ssh retries. Interestingly, I found it using the following command:

&{/usr/bin/ssh [/usr/bin/ssh -o PasswordAuthentication=no -o IdentitiesOnly=yes -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=quiet -o ConnectionAttempts=3 -o ConnectTimeout=10 -i /Users/rhim/.docker/machine/machines/centos7-test/id_rsa -p 22 ubuntu@54.215.130.108 exit 0] []  <nil> <nil> <nil> [] <nil> <nil> <nil> <nil> false [] [] [] [] <nil>}

Note the username in the command.

Any idea why this could have happened?

**Comment by kacole2** [comment]
@rhim you need to specify the centOS7 username. ubuntu is used by default. try using `--amazonec2-ssh-user centos`

**Comment by nathanleclaire** [comment]
@kacole2 Is correct, if changing AMI you must also change other parameters such as user.
