### ISSUE TITLE
docker-machine command not working

### ISSUE THREAD

**Issue by ramgovind** [docker/machine#1930]
docker-machine command is not working from docker quick start terminal with the windows version 1.8.2c.  This was working before with 1.8.2a version of docker windows.  

docker@default:/c$ docker-machine ls
-sh: docker-machine: not found

It appears docker-machine is not on the path.  But I could not add it to that path as C:/Program Files/Docker Toolbox is not visible in docker.  I can see only Users folder under C drive in docker terminal. 

docker@default:/c$ ls
Users/

Any ideas?

**Comment by adj7388** [comment]
I can confirm the same problem on Windows 7, Service Pack 1, running Docker Toolbox 1.8.2.c.

`docker@default:~$ docker-machine`
`-sh: docker-machine: not found`

`docker` command works fine

**Comment by nathanleclaire** [comment]
Looks like the quickstart terminal is actually SSHed into the VM based on the shell prompt?  cc @jeffdm @mchiang ?????

**Comment by nathanleclaire** [comment]
Going to move this over to be a Toolbox bug.

**Comment by nathanleclaire** [comment]
Please follow up in: https://github.com/docker/toolbox/issues/220 thanks
