### ISSUE TITLE
Gracefully handle full disk

### ISSUE THREAD

**Issue by fbender** [docker/machine#1931]
My MBA's SSD filled up while I was running a docker-machine/boot2docker Virtualbox VM. I figured I could recover some disk space by shutting down the VM (due to swapping). When trying to stop the VM, the command failed in an unrecoverable way (and did not shut down the VM). 

```
$ docker-machine stop default
Error saving config after migration was performed: write /Users/fbender/.docker/machine/machines/default/config.json: no space left on device
$ docker-machine stop default
Error getting migrated host: unexpected end of JSON input
$ docker-machine start default
Error getting migrated host: unexpected end of JSON input
```

The `config.json` became zero bytes when executing the first `stop` command, which rendered `docker-machine` incapable of handling or even recognizing the VM. I could only recover the VM by creating two new VMs, diffing their `config.json`, looking up some data in Virtualbox, and adapting one `config.json` for the broken default VM.

So I figured there are 3 things to consider: 

1. Why is the `config.json` written at all on shutdown? Can this be bypassed?
2. Do not write when disk is full. Either fail the command, or handle this gracefully, e.g. shutdown but do not update `config.json`.
3. Try to recover broken `config.json` files. Most metadata can be retrived by querying Virtualbox, the filesystem, and config templates. Think about storing more metadata within the VM, e.g. writing machine-readable metadata into the VM's description field.

No. 3 is desirable whether 1 and 2 are applicable or not. No. 1 may be helpful to reduce resource usage, i.e. only write to disk when really necessary. No. 2 is what's really needed here to prevent the core issue.
What do you think?

**Comment by 1905** [comment]
got this today. +1

**Comment by mcfiredrill** [comment]
ugh :sweat:

**Comment by immunda** [comment]
Came across this too. I had also run out of disc space.

**Comment by lvyaojia** [comment]
+ 1

**Comment by askb** [comment]
Hitting this issue here! I was looking into the code (`Filestore.save()`), it maybe be better to dump meta-data into a `config.json.tmp` (temp file) and replace it with the previous working `config.json` file on hitting `ENOSPC`. In that way when an `open()` or `write()` returns a `ENOSPC` still the config would remain intact.

**Comment by jeanlaurent** [comment]
This sounds like related to : #2285
