### ISSUE TITLE
Docker Machine Google Cloud Driver : stop <machine> command deletes instance

### ISSUE THREAD

**Issue by rominirani** [docker/machine#1935]
This issue is about the Google Cloud driver for Docker Machine. 

The "stop" command is supposed to just stop the instance from a RUNNING state to STOPPED. Currently, it ends up deleting the instance (however it retains the boot-disk for the instance).

What this means is that later on if you "rm" the machine, it is simply deleting the disk and removing the machine from the configured list of hosts.

Is this the expected behaviour. I would assume that the instance is not killed. Otherwise I am assuming that if the boot-disk is retained, then while starting the instance again, it is launching the instance from the boot-disk?

**Comment by nathanleclaire** [comment]
This should be fixed on master by bb45f83319bb26bff1382bd2d86293da26b43d5d .  Please try and report back if it's still an issue, thanks.
