### ISSUE TITLE
creating new docker machine hangs on mac

### ISSUE THREAD

**Issue by embrown30** [docker/machine#1945]
I am opening this issue because I cannot use docker-machine that was installed via docker toolbox that I downloaded.
The previous issue was here
https://github.com/docker/machine/issues/1838#issuecomment-146136427
...
StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=quiet -o ConnectionAttempts=3 -o ConnectTimeout=10 -i /Users/chriswan/.docker/machine/machines/dev/id_rsa -p 53051 docker@localhost ip addr show dev eth1] [] [] false [] [] [] [] }
SSH cmd err, output: : 4: eth1: mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
link/ether 08:00:27:88:e8:ee brd ff:ff:ff:ff:ff:ff
inet 192.168.99.101/24 brd 192.168.99.255 scope global eth1
valid_lft forever preferred_lft forever
inet6 fe80::a00:27ff:fe88:e8ee/64 scope link
valid_lft forever preferred_lft forever

SSH returned: 4: eth1: mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
link/ether 08:00:27:88:e8:ee brd ff:ff:ff:ff:ff:ff
inet 192.168.99.101/24 brd 192.168.99.255 scope global eth1
valid_lft forever preferred_lft forever
inet6 fe80::a00:27ff:fe88:e8ee/64 scope link
valid_lft forever preferred_lft forever

END SSH

open /Users/chriswan/.docker/machine/machines/dev/ca.pem: no such file or directory

And many people are asking if it will be reopened, but there was no response.

The only way I was able to get around this was to revert back to using boot2docker
Please advise.. thanks!

**Comment by gdm85** [comment]
For some reason it's getting stuck here as well. It does not correctly configure networking as far as I can see.

Furthermore, it waits forever and hangs on ``Starting VM...``

**Comment by kacole2** [comment]
@embrown30 @gdm85 can you try installing docker machine with:
```
$ curl -L https://github.com/docker/machine/releases/download/v0.4.1/docker-machine_linux-amd64 > /usr/local/bin/docker-machine
$ chmod +x /usr/local/bin/docker-machine
```

Please also test using AWS or GCE and then we can narrow down if it's a virtualbox issue.

@gdm85 make sure to use `-D` during provisioning to get the debug output

**Comment by damselem** [comment]
Not sure if it will help, but in my case the problem was caused by PF on Mac OS X. My machine was filtering certain packets and I only had to add a `pass` rule in one of my anchor files. For example:

```
pass quick proto tcp all
```

Note that this will allow all packets to go through, so I recommend you to customize it to a more specific rule like:

```
pass quick on vboxnetXX proto tcp from ... to ...
```

You can read more about these rules using `man pf.conf`. Remember to reload pf with:

```
sudo pfctl -ef /etc/pf.conf
```

If you want to make sure whether this is your problem, you can inspect the PF logs and see if any packets are blocked:

```
sudo tcpdump -n -e -ttt -i pflog1 on vboxnet0
```

**Comment by gdm85** [comment]
@kacole2 I can't easily access AWS/GCE, maybe later this week.

As of this morning I get a new error:
```
listen tcp4: lookup tcp4/-1: nodename nor servname provided, or not known
```

Re-creating the docker-machine helped.

**Comment by dgageot** [comment]
Hi @embrown30, can you share the output of those commands:

```
docker-machine -version
VBoxManage list hostonlyifs
VBoxManage list dhcpservers
docker-machine -debug regenerate-certs default
```

Please DO remove personal information like PRIVATE KEYs from the output

**Comment by embrown30** [comment]
docker-machine -version
docker-machine version 0.4.1 (e2c88d6)

Name:            vboxnet0
GUID:            786f6276-656e-4074-8000-0a0027000000
DHCP:            Disabled
IPAddress:       192.168.59.3
NetworkMask:     255.255.255.0
IPV6Address:     
IPV6NetworkMaskPrefixLength: 0
HardwareAddress: 0a:00:27:00:00:00
MediumType:      Ethernet
Status:          Down
VBoxNetworkName: HostInterfaceNetworking-vboxnet0

Name:            vboxnet1
GUID:            786f6276-656e-4174-8000-0a0027000001
DHCP:            Disabled
IPAddress:       192.168.99.1
NetworkMask:     255.255.255.0
IPV6Address:     
IPV6NetworkMaskPrefixLength: 0
HardwareAddress: 0a:00:27:00:00:01
MediumType:      Ethernet
Status:          Up
VBoxNetworkName: HostInterfaceNetworking-vboxnet1

Name:            vboxnet2
GUID:            786f6276-656e-4274-8000-0a0027000002
DHCP:            Disabled
IPAddress:       192.168.99.1
NetworkMask:     255.255.255.0
IPV6Address:     
IPV6NetworkMaskPrefixLength: 0
HardwareAddress: 0a:00:27:00:00:02
MediumType:      Ethernet
Status:          Down
VBoxNetworkName: HostInterfaceNetworking-vboxnet2

NetworkName:    HostInterfaceNetworking-vboxnet0
IP:             192.168.59.99
NetworkMask:    255.255.255.0
lowerIPAddress: 192.168.59.103
upperIPAddress: 192.168.59.254
Enabled:        Yes

NetworkName:    HostInterfaceNetworking-vboxnet1
IP:             192.168.99.1
NetworkMask:    255.255.255.0
lowerIPAddress: 192.168.99.100
upperIPAddress: 192.168.99.254
Enabled:        Yes

NetworkName:    HostInterfaceNetworking-vboxnet2
IP:             192.168.99.1
NetworkMask:    255.255.255.0
lowerIPAddress: 192.168.99.100
upperIPAddress: 192.168.99.254
Enabled:        Yes

NetworkName:    NatNetwork
IP:             10.0.2.3
NetworkMask:    255.255.255.0
lowerIPAddress: 10.0.2.4
upperIPAddress: 10.0.2.254
Enabled:        Yes

docker-machine -debug regenerate-certs default
Regenerate TLS machine certs?  Warning: this is irreversible. (y/n): y
Regenerating TLS certificates
command=configureAuth machine=default
Using SSH client type: external
About to run SSH command:
cat /etc/os-release
&{/usr/bin/ssh [/usr/bin/ssh -o PasswordAuthentication=no -o IdentitiesOnly=yes -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=quiet -o ConnectionAttempts=3 -o ConnectTimeout=10 -i /Users/user/.docker/machine/machines/default/id_rsa -p 63182 docker@localhost cat /etc/os-release] []  <nil> <nil> <nil> [] <nil> <nil> <nil> <nil> false [] [] [] [] <nil>}
SSH cmd err, output: exit status 255: 
Error getting SSH command: exit status 255

**Comment by dgageot** [comment]
Thank you very much @embrown30 for the feedback. Can you try docker-machine 0.5.0-rc4 and tell us if it fixes the problem?

**Comment by embrown30** [comment]
That version of docker-machine worked! Thank you!
