### ISSUE TITLE
Respect change to network adapter

### ISSUE THREAD

**Issue by kevinsimper** [docker/machine#1948]
Right now if I change the network adapter to be vboxnet2 (like it was with boot2docker) it changes it back to vboxnet7?

How can you prevent that? Or is there any way to use a custom network adapter?

![image](https://cloud.githubusercontent.com/assets/1126497/10351024/9e079d12-6d47-11e5-9476-5cd6beac217e.png)

**Comment by nathanleclaire** [comment]
Does it do this even if the VM is stopped?  VBox is not very communicative about why it's behaving in a certain way sometimes.

**Comment by kevinsimper** [comment]
@nathanleclaire Thank you for responding. You are only allowed to change the settings when the machine is stopped.

**Comment by nathanleclaire** [comment]
@kevinsimper Ah good, I was worried it might be some wacky bug or edge case.

**Comment by kevinsimper** [comment]
@nathanleclaire It is a bug, you can't change the adapter, it always changed back to vboxnet7 when you run `docker-machine up`

**Comment by nathanleclaire** [comment]
@kevinsimper You mean `docker-machine start`?

**Comment by nathanleclaire** [comment]
What's the reason you'd like to change the Network adapter?

**Comment by kevinsimper** [comment]
Yes, i mean `docker-machine start`.

I want to have my main machine to have another network adapter, which makes it possible to have a different dns server.

**Comment by nathanleclaire** [comment]
@kevinsimper Why not add it to "Adapter 3"?
