### ISSUE TITLE
Integrate DNS resolution for docker-machine instances

### ISSUE THREAD

**Issue by mrumpf** [docker/machine#1955]
It would be great if docker-machine would setup hostnames for each created docker machine instance.

```docker-machine create registry ... ```

would create a hostname on the host machine: registry.dockermachine or registry.dm for short.
That would simplify accessing services, started by Docker containers inside the docker-machine instance.

A simple solution would be the feature, provided by the Node.js tool hostile:
https://github.com/feross/hostile

**Comment by nathanleclaire** [comment]
We've thought about it -- my strong feeling is that it's quite out of scope for Machine in its current form (and trickier to get right than it looks).  Might be something that we visit if we implement any kind of plugin / "hook" model.
