### ISSUE TITLE
Support for Debian Wheezy

### ISSUE THREAD

**Issue by bjoern-jacobs** [docker/machine#1959]
I followed the installation steps at https://docs.docker.com/installation/debian/ for Debian Wheezy. However, I was unable to install the package docker-engine because of this error:

`The following packages have unmet dependencies:
 docker-engine : Depends: init-system-helpers (>= 1.18~) but it is not installable`

In issue https://github.com/docker/machine/issues/1607 I read that if support for Wheezy is requested, an issue should be openend - which I'm doing with this.

We have a large cluster currently running many Debian Wheezy machines. They won't be upgraded to Debian 8 in the foreseeable future, so support for Debian 7 would be highly appreciated.

**Comment by bjoern-jacobs** [comment]
Sorry, wrong sub-project.

**Comment by leonardlabuneti** [comment]
init-system-helpers (missing dependency) can be installed from backports repo.
Just add deb http://http.debian.net/debian wheezy-backports main at the end of /etc/apt/sources.list and run apt-get update && apt-get install init-system-helpers.
