### ISSUE TITLE
Building with docker generates a binary for linux regardless of the host

### ISSUE THREAD

**Issue by dmp42** [docker/machine#1962]
`USE_CONTAINER=true make` will generate a single binary for linux, even if you are running on OSX.

This is contrary to the user expectations.

We should make the makefile smarter to detect the *host* ARCH and OS (if TARGET_* are not explicitly specified by the user), in the case where we build with docker.

Assigning @dgageot and @jeanlaurent ;)

**Comment by dgageot** [comment]
dibs

**Comment by dgageot** [comment]
@dmp42 Let's close this one since it's not really a pain and there are bigger fish to fry :-)

**Comment by dmp42** [comment]
Agreed. Also, it's not simple to solve, since testing can happen inside the container.
