### ISSUE TITLE
Work with homebrew to get the formula updated

### ISSUE THREAD

**Issue by dmp42** [docker/machine#1964]
Coming up with the plugins system, the build will be quite different.

Currently they are using this: https://github.com/Homebrew/homebrew/blob/master/Library/Formula/docker-machine.rb

We need to discuss with them so that they either:

 * use the makefile and call `make build` (recommended)
 * adjust their `go build` call to build all plugins 

Alternatively, we may just do it ourselves land suggest a PR. 

@jeanlaurent @dgageot let me know if you want to take this when plugins will be ready.

**Comment by nathanleclaire** [comment]
Filed an issue on homebrew CCing the relevant maintainers in case we get lucky and one of them wants to take the initiative.

**Comment by thaJeztah** [comment]
I see the issue was closed, but a PR is still open here; https://github.com/Homebrew/homebrew/pull/45403

**Comment by nathanleclaire** [comment]
They're waiting for the actual 0.5.0 release as far as I'm aware. I'd say we've moved this far enough on our end that I feel safe closing it.  We can re-open if there's a hiccup in getting that PR out the door.
