### ISSUE TITLE
docker-machine ssh buffering issue, messes up tail -f

### ISSUE THREAD

**Issue by kbullaughey** [docker/machine#1970]
I am trying to upgrade from `boot2docker` to `docker-machine` using a mac. I used to be able to do this:

    boot2docker ssh "tail -f /somelogfile.log"

And I was assuming that this would work similarly with `docker-machine`, however the following doesn't show any output:

    docker-machine ssh default "tail -f /somelogfile.log"

If I don't follow and let the command complete, it returns output:

    docker-machine ssh default "tail /somelogfile.log"

So I know the file exists and there's stuff to see. It seems to be a buffering issue because if I do the following, I only see the output after the sleep:

    docker-machine ssh default "tail /somelogfile.log; sleep 5"

Is there a work-around for this? Am I using `docker-machine ssh` in an unintended way? This seemed like a natural behavior to me.

**Comment by nathanleclaire** [comment]
I think https://github.com/docker/machine/pull/1951 should fix this when merged.  We were not handling connecting to STDIN, STDOUT, and STDERR for that form of command properly.

**Comment by nathanleclaire** [comment]
This is fixed in the RC for 0.5.0.  :+1:
