### ISSUE TITLE
Makefile is broken

### ISSUE THREAD

**Issue by dgageot** [docker/machine#1974]
The Makefile is broken in multiple ways.

I've got multiple failures when trying to test machine on OSX.

+ out-of-container `make test` fails
+ in-container `make test` fails for a different reason
+ out-of-container `make clean` can't clean the binaries created by in-container `make build-x`

Here are the build outputs

```
$ make test
0 adds, 0 deletions; nothing to validate! :)
drivers/openstack/client.go:73: github.com/rackspace/gophercloud/openstack/compute/v2/extensions/keypairs.CreateOptsExt composite literal uses unkeyed fields
exit status 1
make: *** [vet] Error 1
```

```
$ USE_CONTAINER=true make test
Sending build context to Docker daemon 23.38 MB
Step 0 : FROM golang:1.5
 ---> e7bca7669626
Step 1 : RUN go get  github.com/golang/lint/golint             github.com/mattn/goveralls             golang.org/x/tools/cover             github.com/tools/godep             github.com/aktau/github-release
 ---> Using cache
 ---> 0bd0235b559a
Step 2 : WORKDIR /go/src/github.com/docker/machine
 ---> Using cache
 ---> e289a9ca79d0
Step 3 : ADD . /go/src/github.com/docker/machine
 ---> Using cache
 ---> 8b48f84971bc
Successfully built 8b48f84971bc
docker-machine-build-container
Sending build context to Docker daemon 23.38 MB
Step 0 : FROM golang:1.5
 ---> e7bca7669626
Step 1 : RUN go get  github.com/golang/lint/golint             github.com/mattn/goveralls             golang.org/x/tools/cover             github.com/tools/godep             github.com/aktau/github-release
 ---> Using cache
 ---> 0bd0235b559a
Step 2 : WORKDIR /go/src/github.com/docker/machine
 ---> Using cache
 ---> e289a9ca79d0
Step 3 : ADD . /go/src/github.com/docker/machine
 ---> Using cache
 ---> 8b48f84971bc
Successfully built 8b48f84971bc
docker-machine-build-container
0 adds, 0 deletions; nothing to validate! :)
?   	github.com/docker/machine	[no test files]
ok  	github.com/docker/machine/cmd	0.013s
ok  	github.com/docker/machine/commands	0.009s
ok  	github.com/docker/machine/commands/mcndirs	0.003s
ok  	github.com/docker/machine/drivers/amazonec2	0.003s
?   	github.com/docker/machine/drivers/amazonec2/amz	[no test files]
?   	github.com/docker/machine/drivers/azure	[no test files]
?   	github.com/docker/machine/drivers/digitalocean	[no test files]
?   	github.com/docker/machine/drivers/driverfactory	[no test files]
?   	github.com/docker/machine/drivers/exoscale	[no test files]
?   	github.com/docker/machine/drivers/fakedriver	[no test files]
?   	github.com/docker/machine/drivers/generic	[no test files]
?   	github.com/docker/machine/drivers/google	[no test files]
?   	github.com/docker/machine/drivers/hyperv	[no test files]
?   	github.com/docker/machine/drivers/none	[no test files]
?   	github.com/docker/machine/drivers/openstack	[no test files]
?   	github.com/docker/machine/drivers/rackspace	[no test files]
ok  	github.com/docker/machine/drivers/softlayer	0.003s
ok  	github.com/docker/machine/drivers/virtualbox	0.003s
?   	github.com/docker/machine/drivers/vmwarefusion	[no test files]
?   	github.com/docker/machine/drivers/vmwarevcloudair	[no test files]
?   	github.com/docker/machine/drivers/vmwarevsphere	[no test files]
?   	github.com/docker/machine/drivers/vmwarevsphere/errors	[no test files]
?   	github.com/docker/machine/libmachine	[no test files]
?   	github.com/docker/machine/libmachine/auth	[no test files]
ok  	github.com/docker/machine/libmachine/cert	0.624s
ok  	github.com/docker/machine/libmachine/drivers	0.003s
?   	github.com/docker/machine/libmachine/engine	[no test files]
?   	github.com/docker/machine/libmachine/examples	[no test files]
ok  	github.com/docker/machine/libmachine/host	0.004s
?   	github.com/docker/machine/libmachine/hosttest	[no test files]
ok  	github.com/docker/machine/libmachine/log	0.002s
?   	github.com/docker/machine/libmachine/mcnerror	[no test files]
--- FAIL: TestGetUsername (0.00s)
	utils_test.go:67: expected username ; received unknown
FAIL
FAIL	github.com/docker/machine/libmachine/mcnutils	0.005s
ok  	github.com/docker/machine/libmachine/persist	0.006s
?   	github.com/docker/machine/libmachine/persisttest	[no test files]
?   	github.com/docker/machine/libmachine/provider	[no test files]
ok  	github.com/docker/machine/libmachine/provision	0.004s
ok  	github.com/docker/machine/libmachine/provision/pkgaction	0.002s
ok  	github.com/docker/machine/libmachine/provision/serviceaction	0.002s
ok  	github.com/docker/machine/libmachine/ssh	0.433s
ok  	github.com/docker/machine/libmachine/state	0.002s
?   	github.com/docker/machine/libmachine/swarm	[no test files]
?   	github.com/docker/machine/libmachine/version	[no test files]
?   	github.com/docker/machine/version	[no test files]
mk/test.mk:3: recipe for target 'test-short' failed
make: *** [test-short] Error 1
make: *** [test] Error 2
```

```
$ USE_CONTAINER=true make build-x
Sending build context to Docker daemon 23.38 MB
Step 0 : FROM golang:1.5
 ---> e7bca7669626
Step 1 : RUN go get  github.com/golang/lint/golint             github.com/mattn/goveralls             golang.org/x/tools/cover             github.com/tools/godep             github.com/aktau/github-release
 ---> Using cache
 ---> 0bd0235b559a
Step 2 : WORKDIR /go/src/github.com/docker/machine
 ---> Using cache
 ---> e289a9ca79d0
Step 3 : ADD . /go/src/github.com/docker/machine
 ---> Using cache
 ---> 8b48f84971bc
Successfully built 8b48f84971bc
docker-machine-build-container

$make clean
rm: /Users/dgageot/go/src/github.com/docker/machine/bin/darwin-386: is a directory
rm: /Users/dgageot/go/src/github.com/docker/machine/bin/darwin-amd64: is a directory
rm: /Users/dgageot/go/src/github.com/docker/machine/bin/linux-386: is a directory
rm: /Users/dgageot/go/src/github.com/docker/machine/bin/linux-amd64: is a directory
rm: /Users/dgageot/go/src/github.com/docker/machine/bin/windows-386: is a directory
rm: /Users/dgageot/go/src/github.com/docker/machine/bin/windows-amd64: is a directory
make: *** [build-clean] Error 1
```

**Comment by jeanlaurent** [comment]
For what's is worth, (it doesn't make the build more reliable), but tests run, on a out of coutainer build (ie with golang), on a clean checkout at 6a5219b879db52698ccb2b7e0aafd516b34df839
'''
machine [master|✔] > git last
commit 6a5219b879db52698ccb2b7e0aafd516b34df839
Merge: caab273 7c8fc35
Author: Olivier Gambier <dmp42@users.noreply.github.com>
Date:   Fri Oct 9 15:44:14 2015 -0700

    Merge pull request #1961 from dmp42/12-targets-fix
    
    Fix building in docker
machine [master|✔] > go version
go version go1.5.1 darwin/amd64
machine [master|✔] > make test
0 adds, 0 deletions; nothing to validate! :)
?   	github.com/docker/machine	[no test files]
ok  	github.com/docker/machine/cmd	0.017s
ok  	github.com/docker/machine/commands	0.016s
ok  	github.com/docker/machine/commands/mcndirs	0.014s
ok  	github.com/docker/machine/drivers/amazonec2	0.018s
?   	github.com/docker/machine/drivers/amazonec2/amz	[no test files]
?   	github.com/docker/machine/drivers/azure	[no test files]
?   	github.com/docker/machine/drivers/digitalocean	[no test files]
?   	github.com/docker/machine/drivers/driverfactory	[no test files]
?   	github.com/docker/machine/drivers/exoscale	[no test files]
?   	github.com/docker/machine/drivers/fakedriver	[no test files]
?   	github.com/docker/machine/drivers/generic	[no test files]
?   	github.com/docker/machine/drivers/google	[no test files]
?   	github.com/docker/machine/drivers/hyperv	[no test files]
?   	github.com/docker/machine/drivers/none	[no test files]
?   	github.com/docker/machine/drivers/openstack	[no test files]
?   	github.com/docker/machine/drivers/rackspace	[no test files]
ok  	github.com/docker/machine/drivers/softlayer	0.016s
ok  	github.com/docker/machine/drivers/virtualbox	0.014s
?   	github.com/docker/machine/drivers/vmwarefusion	[no test files]
?   	github.com/docker/machine/drivers/vmwarevcloudair	[no test files]
?   	github.com/docker/machine/drivers/vmwarevsphere	[no test files]
?   	github.com/docker/machine/drivers/vmwarevsphere/errors	[no test files]
?   	github.com/docker/machine/libmachine	[no test files]
?   	github.com/docker/machine/libmachine/auth	[no test files]
ok  	github.com/docker/machine/libmachine/cert	3.201s
ok  	github.com/docker/machine/libmachine/drivers	0.015s
?   	github.com/docker/machine/libmachine/engine	[no test files]
?   	github.com/docker/machine/libmachine/examples	[no test files]
ok  	github.com/docker/machine/libmachine/host	0.016s
?   	github.com/docker/machine/libmachine/hosttest	[no test files]
ok  	github.com/docker/machine/libmachine/log	0.011s
?   	github.com/docker/machine/libmachine/mcnerror	[no test files]
ok  	github.com/docker/machine/libmachine/mcnutils	0.018s
ok  	github.com/docker/machine/libmachine/persist	0.020s
?   	github.com/docker/machine/libmachine/persisttest	[no test files]
?   	github.com/docker/machine/libmachine/provider	[no test files]
ok  	github.com/docker/machine/libmachine/provision	0.017s
ok  	github.com/docker/machine/libmachine/provision/pkgaction	0.011s
ok  	github.com/docker/machine/libmachine/provision/serviceaction	0.011s
ok  	github.com/docker/machine/libmachine/ssh	1.570s
ok  	github.com/docker/machine/libmachine/state	0.009s
?   	github.com/docker/machine/libmachine/swarm	[no test files]
?   	github.com/docker/machine/libmachine/version	[no test files]
?   	github.com/docker/machine/version	[no test files]
'''

**Comment by nathanleclaire** [comment]
cc @dmp42

**Comment by dmp42** [comment]
Fresh clone:

 * `make test` out of container: WFM - can you check the status of your tree? uncommited files? dirty branch?
 * `make test` inside container: WFM, but docker build cache might be an issue - worth looking into
 * fixing `make clean`, let's `-R`
```
build-clean:
	@rm -Rf $(PREFIX)/bin/*
```

@dgageot can you take the last one fix and investigate for the rest?

**Comment by dgageot** [comment]
+ `make test` out of container: no uncommited file, no dirty branch. I don't get where the problem comes from.
+ `make test` in container: Are you on linux or OSX? I'm on OSX. It fails on the Username. I'll investigate.
+ `make clean` I'll do it, thanks a lot.

**Comment by dmp42** [comment]
Use `VERBOSE=true make foo` to get go -v output (might help figure it out).
I'm on OSX otherwise.

**Comment by dgageot** [comment]
@dmp42 I don't understand how it can work for you. Here's the test that fails for me:

```
=== RUN   TestGetUsername
--- FAIL: TestGetUsername (0.00s)
	utils_test.go:67: expected username ; received unknown
```

The test tries to compare `GetUsername()` with `os.Getenv("USER")` but:
+ `GetUsername()` returns `unknown` because `USER` is not set in the `golang:1.5.1` image
+ `os.Getenv("USER")` returns `""` for the same reason

**Comment by dgageot** [comment]
Let's forget about `make test` out of container because it looks like it was caused by something that is not there anymore when I remove everything but machine from my `$GOPATH`

**Comment by dmp42** [comment]
@dgageot indeed, out of container fail with stuff in $GOPATH rings like golang import lookup oddities related to GOVENDOR. 

About in container: agreed that test cannot work - the test needs to be fixed and/or the code amended to deal with that case.

**Comment by nathanleclaire** [comment]
We used to set `USER` environment variable in our Dockerfile, but it was taken out in recent changes.  It should probably be added back in.

**Comment by dmp42** [comment]
@nathanleclaire indeed, my bad.

So, question: will machine work if there is no USER set?

**Comment by nathanleclaire** [comment]
> So, question: will machine work if there is no USER set?

I don't think so; we need it to set the user in the certificates.

**Comment by dmp42** [comment]
`GetUserName` will still return `unknown`, correct?

https://github.com/docker/machine/blob/fe5a72299da0407a6c8f122b8719f705ddd1b60d/libmachine/mcnutils/utils.go#L27

**Comment by dgageot** [comment]
I'm reopening the issue because not everything is fixed.

**Comment by dgageot** [comment]
Does somebody know why we don't use golang's `user.Current` Api to find the username?

The failing code was introduced with [this commit](https://github.com/docker/machine/commit/720c4edfd23d86b0ca5e226d07a933edeff741d7)

Hi @ehazlett, any idea on that subject?

**Comment by nathanleclaire** [comment]
@dgageot I think because it is a case, much like finding the user's home directory, where the Go library actually depends on cgo and therefore makes cross-compilation impossible.

**Comment by dgageot** [comment]
@nathanleclaire How can I check? Would it refuse to cross-compile or just fail at runtime?

**Comment by nathanleclaire** [comment]
@dgageot I could be mistaken, but I think cross-compilation will just fail.  Our current Makefile has `CGO_ENABLED=0` too which I think will play not so nicely.

**Comment by dgageot** [comment]
Cross compilation does not fail. So what now

**Comment by dmp42** [comment]
@dgageot this is probably this https://github.com/golang/go/issues/6376

**Comment by nathanleclaire** [comment]
@dgageot Sorry, if you see the comment on the other issue, I did a little research and the issues seem to not show up until runtime.
