### ISSUE TITLE
machine godoc contains an import statement

### ISSUE THREAD

**Issue by dgageot** [docker/machine#1975]
Documentation at https://godoc.org/github.com/docker/machine contains

```
package machine
import "github.com/docker/machine"

Machine defines interfaces to manage a variety of docker instances deployed on different backends (VMs, baremetal). The goal is to allow users get from zero to docker as fast as possible.

Index
```

I believe the `import "github.com/docker/machine"` line shouldn't be here

**Comment by dmp42** [comment]
It really depends what we want (this is governed by the presence of a top-level package, here doc.go).

Examples:

 * with a top level package: https://godoc.org/github.com/docker/distribution
 * withou: https://godoc.org/github.com/docker/swarm

**Comment by dgageot** [comment]
If we have a `main.go` that contains package `main` annotated with this documentation and we change `machine.go` package to either `cmd` or `machine`, I think it get rid of the `import "github.com/docker/machine"` line in the documentation. wdyt?

**Comment by dgageot** [comment]
@dmp42 I tried to implement what I was talking about. Does it make sense?
