### ISSUE TITLE
docker-machine configuration sharing with team

### ISSUE THREAD

**Issue by uptownhr** [docker/machine#1980]
What is the best way to share docker-machine configurations with the team?

I'm aware that you can share the machine directory with another person, and they can also get the machine details and be able to connect through docker machine. However, is this a necessary step? Is there a better way without having to transfer the docker machine directory?  For example, if we were to share the certs in .docker/machine/certs, does docker-machine know how to connect to other machines generated with these certs? And auto regenerate the target machine directory?

**Comment by thaJeztah** [comment]
Hi @uptownhr, I think this is a duplicate of https://github.com/docker/machine/issues/23, if you agree, can you close this issue?

**Comment by uptownhr** [comment]
yup the same :) thanks!

**Comment by thaJeztah** [comment]
Thanks for reporting!
