### ISSUE TITLE
Host needs VT-x/AMD-v enabled for docker-machine to work on virtualbox

### ISSUE THREAD

**Issue by dgageot** [docker/machine#1983]
If VT-x or AMD-v are not enabled on the host machine, the vm won't boot boot2docker properly and the whole creation process will hang forever.

To reproduce:

```
docker-machine create -d virtualbox default
```

, on a host without VT-x/AMD-v

We need to:
+ Detect that VT-x/AMD-v is not enabled and fail as early as possible
+ Understand why the `start` command hangs for what it looks forever

**Comment by dmp42** [comment]
Random googling :-)

http://stackoverflow.com/questions/21537769/programatically-detect-if-vt-x-or-amd-v-is-enabled-on-windows

https://www.virtualbox.org/ticket/10694

**Comment by thaJeztah** [comment]
Also see https://github.com/docker/toolbox/issues/166

**Comment by jeanlaurent** [comment]
Got this one which explain for windows and linux how to detect it.

http://stackoverflow.com/questions/840873/how-to-determine-if-hardware-virtualization-is-available-via-code-c-c

**Comment by nathanleclaire** [comment]
I think my main concern in the immediate future is to detect this case for Windows users (the most likely to have it disabled), so maybe we can focus on that.  I don't see any reliable way to find the information in the links referenced without assuming something like Powershell, though.  Maybe I'm overlooking something.

At any rate, can `VBoxManage` itself detect whether virtualization is enabled through the command line?  I know that it complains if you attempt to run it in Xen, so there might be something there we can try and parse.

**Comment by dgageot** [comment]
We should be able to detect that VT-x/AMD-v is enabled on windows with this command:

```
> wmic cpu get VirtualizationEnabled
VirtualizationEnabled
TRUE
```

If wmic is not available then we could create the vm anyway and then use `VBoxManage showvminfo` to see if it is enabled.

**Comment by dgageot** [comment]
The only way I found to detect afterwards is to look at the vm's log in `~/.docker/machine/machines/default/default/Logs/VBox.log`

When is works, it says:

```
00:00:00.121781 HM: HMR3Init: VT-x w/ nested paging and unrestricted guest execution hw support
```

Otherwise it says:

```
00:00:00.121781 HM: HMR3Init: Falling back to raw-mode: VT-x is disabled in the BIOS for both all CPU modes
```

**Comment by dgageot** [comment]
Closed by https://github.com/docker/machine/pull/1990

**Comment by serjN** [comment]
@dgageot, you can check if virtualization enabled on windows 7 by utility [Microsoft® Hardware-Assisted Virtualization Detection Tool](https://www.microsoft.com/en-us/download/details.aspx?id=592). It has console mode, but needs admin rights.

**Comment by xhchrn** [comment]
It seems a problem that the core isolation in Windows is enabled. See here:
https://stackoverflow.com/a/50403200/8585276
