### ISSUE TITLE
[feature request] Option to set AWS EC2 tags

### ISSUE THREAD

**Issue by azpekt** [docker/machine#1986]
Hello, due to requirements of my client, I need docker hosts in AWS to have an additional tags. I saw tags implemented for Machine name in docker-machine source code, but no option to add more tags.

Is this functionality is planned to be implemented?

Thanks!

**Comment by dgageot** [comment]
Hi @azpekt, no it is not planned. It shouldn't be too hard to implement though. Would you like to try?

**Comment by jeffellin** [comment]
I have spent a bit of time looking at this driver, it really isn't too hard to implement,  however in the meantime you can probably accomplish the same with the AWS cli and a shell script that does both operations.

**Comment by soleo** [comment]
Would adding an parameter ``--tags="key:k1,k2,value:v1,v2,"`` be okay for this? If it sounds good, I could help to get this done.

**Comment by azpekt** [comment]
Hi @dgageot , I`m absolute noob in Go, so I`d rather leave that to professionals :)

I believe, any format that is in line with current docker-machine guidelines is fine.

Thanks for replies, guys!

**Comment by jeffellin** [comment]
@soleo I think what you propose is fine.   I can also help with this if needed.

**Comment by tdensmore** [comment]
+1 for this feature. @jeffellin any idea if someone is looking into this?

**Comment by jeffellin** [comment]
No idea,   I have given up on the ec2 driver two other PRs I have worked on still haven't been merged.,  using a cloud formation driver I created https://github.com/jeffellin/machine-cloudformation  leaves me more in control since I can do just about anything I want with cloud formation.

**Comment by tdensmore** [comment]
Thanks @jeffellin . I use Ansible and other tools to wrangle my cloud. I feel your pain.

Unfortunately not having AWS tag support in the driver may limit my ability to use docker-machine in a production environment. Most of our automation relies on having properly tagged instances.

**Comment by jeffellin** [comment]
could probably create a driver that invokes ansible.

**Comment by jeffellin** [comment]
What I have been doing lately is using cloud formation then adding a docker-machine using the generic driver

**Comment by soleo** [comment]
Added support for extra tags. But I simplied the assigment to be just ``--amazon-tags "k1,v1,k2,v2"`` .  Refer to PR https://github.com/docker/machine/pull/2727

**Comment by soleo** [comment]
@dgageot  would you like to take a look at the PR? One of the test is not passed, and I don't know why.

**Comment by dgageot** [comment]
Hi @soleo I guess you found on your own. That's cool!

**Comment by dgageot** [comment]
Fixed with https://github.com/docker/machine/pull/2727
