### ISSUE TITLE
Machine IP accessible from terminal but not from browser

### ISSUE THREAD

**Issue by flenoir** [docker/machine#1988]
Hi, 

I am on OSX Yosemite
 i previously used docker-machine on my machine but now i have an issue and i can't figure out where is the problem/

 i can start docker-machine and run a container. 

 in the terminal, i can ping the IP of the docker-machine ( nginx) but i can't access my nginx in my browser

 any idea ? 

 thanks

**Comment by nathanleclaire** [comment]
Can you post the specific commands you're running please?

**Comment by CARocha** [comment]
Hello i have the same situation, i run docker-compose up and then find in the browser the ip
192.168.99.102:2376 for example i don't see any??
anyone have any idea??

**Comment by dmp42** [comment]
People: please provide at least the commands you have been running, and the configuration files you have used.

If you are using compose, then please ask on the compose support forums.

Thanks.

**Comment by nathanleclaire** [comment]
Closing -- please open a new issue with more specific details if you continue to experience issues all.
