### ISSUE TITLE
Machine IP could not be fetched. - MAC OS X El Capitan

### ISSUE THREAD

**Issue by sebastienhouzet** [docker/machine#1992]
Hello,

impossible to use docker mac os x since El Capitan.

With Kitematic:

<img width="304" alt="capture d ecran 2015-10-15 a 21 17 35" src="https://cloud.githubusercontent.com/assets/2550639/10524919/4ab6b77e-7382-11e5-9cc4-6a7a3cf4c781.png">

With Terminal:

xit status 255
docker is configured to use the default machine with IP 
For help getting started, check out the docs at https://docs.docker.com

Unexpected error getting machine url: exit status 255

**Comment by nathanleclaire** [comment]
@sebastienhouzet Can you create a machine successfully in a terminal using `docker-machine --debug create -d virtualbox default`?

**Comment by sebastienhouzet** [comment]
it doesnt work with this command :/

**Comment by dgageot** [comment]
@sebastienhouzet Can you gist the whole output of running `docker-machine --debug create -d virtualbox default`?

**Comment by sebastienhouzet** [comment]
Now if i re-launch command, it display : Error creating machine: Machine default already exists
You will want to check the provider to make sure the machine and associated resources were properly removed.

But the previous and first launch display :

TDERR: 
Using SSH client type: external
About to run SSH command:
ip addr show dev eth1
&{/usr/bin/ssh [/usr/bin/ssh -o PasswordAuthentication=no -o IdentitiesOnly=yes -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=quiet -o ConnectionAttempts=3 -o ConnectTimeout=10 -i /Users/sebastien/.docker/machine/machines/default/id_rsa -p 50492 docker@localhost ip addr show dev eth1] []  <nil> <nil> <nil> [] <nil> <nil> <nil> <nil> false [] [] [] [] <nil>}
SSH cmd err, output: <nil>: 4: eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 08:00:27:cc:e7:44 brd ff:ff:ff:ff:ff:ff
    inet 192.168.99.100/24 brd 192.168.99.255 scope global eth1
       valid_lft forever preferred_lft forever
    inet6 fe80::a00:27ff:fecc:e744/64 scope link 
       valid_lft forever preferred_lft forever

SSH returned: 4: eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 08:00:27:cc:e7:44 brd ff:ff:ff:ff:ff:ff
    inet 192.168.99.100/24 brd 192.168.99.255 scope global eth1
       valid_lft forever preferred_lft forever
    inet6 fe80::a00:27ff:fecc:e744/64 scope link 
       valid_lft forever preferred_lft forever

END SSH

Using SSH client type: external
About to run SSH command:
printf %s "
EXTRA_ARGS='
--label provider=virtualbox

'
CACERT=/var/lib/boot2docker/ca.pem
DOCKER_HOST='-H tcp://0.0.0.0:2376'
DOCKER_STORAGE=aufs
DOCKER_TLS=auto
SERVERKEY=/var/lib/boot2docker/server-key.pem
SERVERCERT=/var/lib/boot2docker/server.pem


" | sudo tee /var/lib/boot2docker/profile
&{/usr/bin/ssh [/usr/bin/ssh -o PasswordAuthentication=no -o IdentitiesOnly=yes -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=quiet -o ConnectionAttempts=3 -o ConnectTimeout=10 -i /Users/sebastien/.docker/machine/machines/default/id_rsa -p 50492 docker@localhost printf %s "
EXTRA_ARGS='
--label provider=virtualbox

'
CACERT=/var/lib/boot2docker/ca.pem
DOCKER_HOST='-H tcp://0.0.0.0:2376'
DOCKER_STORAGE=aufs
DOCKER_TLS=auto
SERVERKEY=/var/lib/boot2docker/server-key.pem
SERVERCERT=/var/lib/boot2docker/server.pem


" | sudo tee /var/lib/boot2docker/profile] []  <nil> <nil> <nil> [] <nil> <nil> <nil> <nil> false [] [] [] [] <nil>}
SSH cmd err, output: <nil>: 
EXTRA_ARGS='
--label provider=virtualbox

'
CACERT=/var/lib/boot2docker/ca.pem
DOCKER_HOST='-H tcp://0.0.0.0:2376'
DOCKER_STORAGE=aufs
DOCKER_TLS=auto
SERVERKEY=/var/lib/boot2docker/server-key.pem
SERVERCERT=/var/lib/boot2docker/server.pem



Using SSH client type: external
About to run SSH command:
sudo /etc/init.d/docker start
&{/usr/bin/ssh [/usr/bin/ssh -o PasswordAuthentication=no -o IdentitiesOnly=yes -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=quiet -o ConnectionAttempts=3 -o ConnectTimeout=10 -i /Users/sebastien/.docker/machine/machines/default/id_rsa -p 50492 docker@localhost sudo /etc/init.d/docker start] []  <nil> <nil> <nil> [] <nil> <nil> <nil> <nil> false [] [] [] [] <nil>}
SSH cmd err, output: <nil>: Need TLS certs for default,127.0.0.1,10.0.2.15,192.168.99.100
-------------------

Daemon not responding yet: dial tcp 192.168.99.100:2376: connection refused
To see how to connect Docker to this machine, run: docker-machine env default

**Comment by dgageot** [comment]
@sebastienhouzet
Which version of machine are you using?
Can you try the latest release candidate for Toolbox/machine? https://github.com/docker/toolbox/releases

**Comment by sebastienhouzet** [comment]
@dgageot Perfect with your new version !! Nice :+1: 

Seb
