### ISSUE TITLE
"machine" command name conflict

### ISSUE THREAD

**Issue by tlrobinson** [docker/machine#2]
OS X (and I assume other BSD variants) already has a "machine" command line tool: https://developer.apple.com/library/mac/documentation/Darwin/Reference/ManPages/man1/machine.1.html

Probably best not to conflict with it.

**Comment by sthulb** [comment]
Can we just rename to docker-machine now? :)

**Comment by ehazlett** [comment]
@sthulb yes, `docker-machine` is it for now :)

**Comment by ehazlett** [comment]
Closing as #2 is complete :)  Thx everyone!

**Comment by leifhanack** [comment]
What about my comment?

> It might be a solution to do it like git did. You have separated commands e.g. docker-machine, docker-swarm and the docker command will delegate to them, so that it will be possible to call either docker machine .. or docker-machine ..

Should this be a new ticket?

**Comment by ndeloof** [comment]
see https://github.com/docker/docker/issues/10299

**Comment by sthulb** [comment]
@leifhanack I think that's for the parent project, thankfully, @ndeloof created his issue :)

**Comment by leifhanack** [comment]
cool. thanks!
