### ISSUE TITLE
v0.5.0-rc1: Driver "hyper-v" not found. Do you have the plugin binary accessible in your PATH?

### ISSUE THREAD

**Issue by factormystic** [docker/machine#2001]
```
> docker-machine --debug ls
Docker Machine Version: 0.5.0-rc1 (43543d1)
Launching plugin server for driver hyper-v
Driver "hyper-v" not found. Do you have the plugin binary accessible in your PATH?

> docker-machine-driver-hyperv.exe
This is a Docker Machine plugin binary.
Plugin binaries are not intended to be invoked directly.
Please use this plugin through the main 'docker-machine' binary.
```

I downloaded `docker-machine_windows-amd64.zip` for the v0.5.0-rc1 release, then added the folder to my PATH. `docker-machine-driver-hyperv.exe` is right there in the folder next to `docker-machine.exe`. I do not have any other copies of docker-machine installed. Not sure what's going on.

**Comment by blaggacao** [comment]
Same problem here, was about to report it.

On Cygwin:

```
$ ls -a /usr/bin/ | grep "docker"
docker.exe*
docker-machine.exe*
docker-machine-driver-amazonec2.exe*
docker-machine-driver-azure.exe*
docker-machine-driver-digitalocean.exe*
docker-machine-driver-exoscale.exe*
docker-machine-driver-generic.exe*
docker-machine-driver-google.exe*
docker-machine-driver-hyperv.exe*
docker-machine-driver-none.exe*
docker-machine-driver-openstack.exe*
docker-machine-driver-rackspace.exe*
docker-machine-driver-softlayer.exe*
docker-machine-driver-virtualbox.exe*
docker-machine-driver-vmwarefusion.exe*
docker-machine-driver-vmwarevcloudair.exe*
docker-machine-driver-vmwarevsphere.exe*
```

**Comment by blaggacao** [comment]
ok, got it:
https://github.com/docker/machine/blob/8aa1572e0dcd75762a7627e1056ef104317f44b9/libmachine/drivers/plugin/localbinary/plugin.go#L91

lookpath looks for `docker-machine-driver-hyper-v.exe`
though we have only `docker-machine-driver-hyperv.exe` as can be seen above.

The culprit is either the filename itself or https://github.com/docker/machine/blob/8aa1572e0dcd75762a7627e1056ef104317f44b9/drivers/hyperv/hyperv.go#L100

**Comment by dgageot** [comment]
@blaggacao Would you like to create a PR for your fix?

**Comment by dgageot** [comment]
@blaggacao Forget what I said! You did create a PR

**Comment by udif** [comment]
I have an old host (I installed docker-machine many months ago) with this problem which I cant remove .
Today I reinstalled docker-machine and successfully created a host using hyperv, but I cant kill the old one.
How do I clean this up? rebooting doesn't help.
