### ISSUE TITLE
Powershell: Error running connection boilerplate: XXX is not running. Please start it in order to use the connection settings..

### ISSUE THREAD

**Issue by blaggacao** [docker/machine#2004]
This is an issue for reference only:

Powershell:
```
PS C:\Program Files\Oracle\VirtualBox> .\VBoxManage showvminfo dev --machinereadable | grep "VMState"
VMState="poweroff"
VMStateChangeTime="2015-10-18T17:23:38.000000000"
```

Cygwin:
```
David@DAR-Laptop /cygdrive/c/Program Files/Oracle/VirtualBox
$ ./VBoxManage.exe showvminfo dev --machinereadable | grep "VMState"
VMState="running"
VMStateChangeTime="2015-10-18T17:29:19.734000000"
```

This seems to be a VirtualBox issue. But please note, that this breakes the docker-machine command with the following error massage:

```
Error running connection boilerplate: XXX is not running. Please start it in order to use the connection settings.
```

**Comment by blaggacao** [comment]
Here is the entire output of `$ ./VBoxManage.exe showvminfo dev --machinereadable`: https://gist.github.com/blaggacao/e966d0be4f538f913162

Here is the entire output of `PS .\VBoxManage showvminfo dev --machinereadable`: https://gist.github.com/blaggacao/73c3a618b1e2321c5aaf

**Comment by blaggacao** [comment]
I'm quite confued, because trying to start the virtualbox in powershell, yields running state in powershell and poweroff state in cygwin AND VirtualBox UI...

**Comment by dgageot** [comment]
Sorry @blaggacao is this ticket related to docker-machine?

**Comment by dgageot** [comment]
@blaggacao Closing the ticket. Feel free to reopen it if it's related to machine.
