### ISSUE TITLE
v0.5.0-rc1 Error: "error attempting to invoke binary for plugin: unexpected end of JSON input"

### ISSUE THREAD

**Issue by jeffdm** [docker/machine#2005]
When building & testing out the 1.9 Toolbox I run into the following errors with machine:

```
~/workspace/toolbox$ docker-machine -D ls
Docker Machine Version: 0.5.0-rc1 (43543d1)
Launching plugin server for driver virtualbox
Found binary path at /usr/local/bin/docker-machine-driver-virtualbox
Plugin server listening at address 127.0.0.1:58937
() Got msg {ServiceMethod:RpcServerDriver.GetVersion Args:{} Reply:0xc82013e080}
Using API Version 1
() Got msg {ServiceMethod:RpcServerDriver.SetConfigRaw Args:[] Reply:<nil>}
Error attempting to invoke binary for plugin: unexpected end of JSON input
```

Here's where the binaries are:
```
~/workspace/toolbox$ ls -al /usr/local/bin/
-rwxr-xr-x    1 jmorgan  admin   9192272 Oct 18 16:29 docker
-rwxr-xr-x    1 jmorgan  admin   5222505 Oct 18 16:32 docker-compose
-rwxr-xr-x    1 jmorgan  admin   8791024 Oct 16 18:21 docker-machine
-rwxr-xr-x    1 jmorgan  admin   8607488 Oct 16 18:07 docker-machine-driver-amazonec2
-rwxr-xr-x    1 jmorgan  admin   9333104 Oct 16 18:08 docker-machine-driver-azure
-rwxr-xr-x    1 jmorgan  admin   8423120 Oct 16 18:09 docker-machine-driver-digitalocean
-rwxr-xr-x    1 jmorgan  admin   8262016 Oct 16 18:10 docker-machine-driver-exoscale
-rwxr-xr-x    1 jmorgan  admin   8109584 Oct 16 18:11 docker-machine-driver-generic
-rwxr-xr-x    1 jmorgan  admin   9699888 Oct 16 18:12 docker-machine-driver-google
-rwxr-xr-x    1 jmorgan  admin   8191856 Oct 16 18:13 docker-machine-driver-hyperv
-rwxr-xr-x    1 jmorgan  admin   8100672 Oct 16 18:14 docker-machine-driver-none
-rwxr-xr-x    1 jmorgan  admin   8836192 Oct 16 18:15 docker-machine-driver-openstack
-rwxr-xr-x    1 jmorgan  admin   8875936 Oct 16 18:15 docker-machine-driver-rackspace
-rwxr-xr-x    1 jmorgan  admin   8206000 Oct 16 18:16 docker-machine-driver-softlayer
-rwxr-xr-x    1 jmorgan  admin   8257952 Oct 16 18:17 docker-machine-driver-virtualbox
-rwxr-xr-x    1 jmorgan  admin   8217616 Oct 16 18:18 docker-machine-driver-vmwarefusion
-rwxr-xr-x    1 jmorgan  admin   8739824 Oct 16 18:19 docker-machine-driver-vmwarevcloudair
-rwxr-xr-x    1 jmorgan  admin   8278752 Oct 16 18:20 docker-machine-driver-vmwarevsphere
```

**Comment by dgageot** [comment]
Hi @jeffdm can you check your `/etc/hosts` file and tell me if there's a line with `127.0.0.1 localhost`?

**Comment by nathanleclaire** [comment]
We discussed this in person and I think it is related to using an older version of Docker Machine after using the new, plugin-based binary.  Consequently, the `RawDriver` field is left out of the config but the new plugin does not know to migrate because the config version has been moved forward already.

I'm not 100% sure what to do, but might look into seeing if I can hack around by generating `RawDriver` in the case where it is `nil` for Machine 0.5.0.

**Comment by gmanfunky** [comment]
I ran into this when having multiple docker machines generated with docker-machine 0.4.1. 

I somehow got into a state where my default machine was updated to include the new ```RawDriver``` field, but another one of my non-default machines made with docker-machine 0.4.1 was not updated.

**Comment by nathanleclaire** [comment]
> Granted, i was trying to troubleshoot another issue that DID have me bouncing back and forth between docker machine versions.

Yup, there's your issue.  Wonder if we can somehow make this safer.

**Comment by nathanleclaire** [comment]
> I somehow got into a state where my default machine was updated to include the new RawDriver field, but another one of my non-default machines made with docker-machine 0.4.1 was not updated.

Did you invoke some operations on the `default` machine but not on the other?  IIRC just `docker-machine ls` should automatically migrate all of the hosts.

**Comment by gmanfunky** [comment]
I figured out what is up. It is pretty much what you expected @nathanleclaire 

```docker-machine-0.5.0rc1.exe ls``` will convert all the config.json files to ```"ConfigVersion":3```

If you then run ```docker-machine-0.4.1 ls```, it will do a back-convert to something like the old ```"ConfigVersion":1```, but keeps ```"ConfigVersion":3``` value while not writing out the new ```"RawDriver":"...."``` element. 

Then, i suspect ```docker-machine-0.5.0rc1.exe ls``` Kinda tries to convert it again. But it sees version 3, so doesn't do any fixing up and just prints out the config with the new prettyJson printer? 

Maybe old docker-machines don't anticipate new top-level elements like this?

**Comment by gmanfunky** [comment]
> Did you invoke some operations on the default machine but not on the other?

Yes, i likely did a ```docker-machine env default```

**Comment by nathanleclaire** [comment]
> it will do a back-convert to something like the old "ConfigVersion":1

Yeah, but not intentionally.  I'm going to include some code in the next RC to re-migrate configs that oopsied back into an old version like that.

**Comment by jurosh** [comment]
Seems like it's still issue in recently released DockerToolbox 1.9.0 and Win10.
``docker-machine ls`` also throws error: panic: runtime error: invalid memory address or nil pointer...

**Comment by dmp42** [comment]
@nathanleclaire wdyt?

**Comment by nathanleclaire** [comment]
@jurosh Issue sounds different than the OP issue.  @jurosh can you please file a new issue and include a link to a https://gist.github.com of the output of `docker-machine --debug ls`?  Thanks

**Comment by jurosh** [comment]
@nathanleclaire after removal of docker defualt machine and running kitematic it ends with:
https://gist.github.com/jurosh/59e01e1fd1e269e6aa06#file-docker-1-9-0-kitematic-no-vm-before

Then running: `docker-machine --debug ls` ends with:
```
(default) DBG | SSH binary not found, using native Go implementation
(default) DBG | About to run SSH command:
(default) DBG | ip addr show dev eth1
(default) DBG | Error dialing TCP: dial tcp 127.0.0.1:22: connectex: No connection could be made because the target machine actively refused it.
```

After adding GIT ssh.exe to path it shows something different:
```
error getting URL for host default: Something went wrong running an SSH command!
command : ip addr show dev eth1
err     : exit status 255
output  :

(default) Calling RpcServerDriver.DriverName
(default) DBG | SSH cmd err, output: exit status 255:
NAME      ACTIVE   DRIVER       STATE     URL   SWARM
default   *        virtualbox   Running 
```
Full output: https://gist.github.com/jurosh/9cc05432fa1d9addd005#file-docker-docker-machine-debug-ls

After that kitematic cannot start (only shows loading).

**Comment by jurosh** [comment]
Seems like it was issue with Network Interfaces in virtualbox - created by docker before. It was blocking new instance to be created properly - I found this advice in this thread https://github.com/docker/machine/issues/1031.
This probably should be in Documentation of Docker as seems like it's pretty common issue happening to peaple using Windows and also Mac.
