### ISSUE TITLE
Problem with kitematic as VM is not started

### ISSUE THREAD

**Issue by tkrsumanth** [docker/machine#2007]
when i start the kitematic latest version it is showing that "MACHINE IP COULDN'T BE FETCHED"

and the detailed message is as follows:-

"Machine IP could not be fetched. Please retry the setup. If this fails please file a ticket on our GitHub repo."

**Comment by dgageot** [comment]
Hi @tkrsumanth, thank you very much for filing a ticket.
Can you provide more details on the context?
You can take a look at this [documentation](https://github.com/docker/machine/blob/master/README.md#troubleshooting) for information on how to troubleshoot/report issues.

**Comment by dgageot** [comment]
Not enough information. Closing the issue.
@tkrsumanth Feel free to reopen!
