### ISSUE TITLE
Host File System not Syncing Properly with VMWare VMs

### ISSUE THREAD

**Issue by jeffpereira** [docker/machine#2009]
I am creating a dev VM with docker-machine using the following command.  "docker-machine create --driver vmwarefusion --vmwarefusion-memory-size 2048 --vmwarefusion-disk-size 50000 dev"

I am running into a problem where I make changes locally on whatever repo I am working on, and sometimes only some or none of the changes are there.  It seems as though the replication of data between the Host and the VM lags at certain points with no reason at all.  I was forced to switch to VMWare after going to hosted gems on a Rails project caused any VM I had built with Virtualbox to bring up a Rails console insanely slow (like 5+ minutes).

**Comment by dgageot** [comment]
@frapposelli any idea?

**Comment by jeffpereira** [comment]
Also as an FYI this was happening in virtual box as well.

**Comment by frapposelli** [comment]
@jeffpereira is this still a problem?

**Comment by jeffpereira** [comment]
As far as I know it is still happening. I had to switch to using docker directly in an Ubuntu VM because it was hindering my work. Also another problem I noticed that has been aparent with many of my teammates is that even if you are removing your images and containers it seems that the docker machine VMs always run out of space inevitably.
