### ISSUE TITLE
Commands should not need machine name if only one machine

### ISSUE THREAD

**Issue by anentropic** [docker/machine#2010]
Most of the time I will only have one machine (essentially I'm using DM just as replacement for boot2docker on my laptop)

It's annoying always to have to include the machine name `default` with every docker-machine command

I suggest, if you only have one machine installed, commands should just use that machine without having to name it every time

**Comment by nathanleclaire** [comment]
Want to fix this with https://github.com/docker/machine/issues/1783

Please take discussion there
