### ISSUE TITLE
v0.5.0-rc2: Driver "hyper-v" not found. Do you have the plugin binary accessible in your PATH?

### ISSUE THREAD

**Issue by factormystic** [docker/machine#2016]
#2001 is still alive in rc2, looks like:

```
>docker-machine --debug ls
Docker Machine Version: 0.5.0-rc2 (6cac8cc)
Launching plugin server for driver hyper-v
Driver "hyper-v" not found. Do you have the plugin binary accessible in your PATH?
```

```
>docker-machine-driver-hyperv.exe
This is a Docker Machine plugin binary.
Plugin binaries are not intended to be invoked directly.
Please use this plugin through the main 'docker-machine' binary.
```

**Comment by factormystic** [comment]
Renaming `docker-machine-driver-hyperv.exe` to `docker-machine-driver-hyper-v.exe` seems to work.

**Comment by nathanleclaire** [comment]
Ah, you have existing machines created with `hyper-v` driver it looks like.  If you remove them and recreate with `--driver hyperv`, it should work.

**Comment by factormystic** [comment]
Ok, that particular issue seems to be resolved I guess

**Comment by QGB** [comment]
Driver "Hyper-V" not found. Do you have the plugin binary "docker-machine-driver-Hyper-V" accessible in your PATH?

**Comment by tariq-sketch** [comment]
This is a Docker Machine plugin binary.
Plugin binaries are not intended to be invoked directly.
Please use this plugin through the main 'docker-machine' binary.
(API version: 1)
