### ISSUE TITLE
[generic] eval $(docker-machine env myhost) fails

### ISSUE THREAD

**Issue by rahal** [docker/machine#2017]
Hello, 
On random occasions, I have the following error while using : eval $(docker-machine env myhost )  , myhost is a generic host, and when it happens, the containers are stopped. I have several hosts and it happens at least once or twice a day with one of them. I have debians. Is there any way I can know what's happening exactly? Thank you.

```
SSH cmd error!
command: sudo systemctl enable docker
err    : exit status 1
output : Synchronizing state for docker.service with sysvinit using update-rc.d...
Executing /usr/sbin/update-rc.d docker defaults
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
	LANGUAGE = (unset),
	LC_ALL = (unset),
	LC_CTYPE = "UTF-8",
	LANG = "en_US.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to a fallback locale ("en_US.UTF-8").
Executing /usr/sbin/update-rc.d docker enable
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
	LANGUAGE = (unset),
	LC_ALL = (unset),
	LC_CTYPE = "UTF-8",
	LANG = "en_US.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to a fallback locale ("en_US.UTF-8").
Failed to execute operation: File exists
```

**Comment by nathanleclaire** [comment]
cc @ehazlett

**Comment by dgageot** [comment]
Hi @rahal Can you tell us which version you are using. Also can you try with docker-machine 0.5.0-rc4 please?

**Comment by rahal** [comment]
Hi, I'm using docker-machine version 0.4.1 (e2c88d6) .
I Will test with 0.5.0-rc4 and I'll get back to you. 
Thank you

**Comment by dmp42** [comment]
@rahal 0.5.0 has been released. You can test with that instead of the RC.

**Comment by rahal** [comment]
Hi, I'm using docker-machine version 0.5.0 (04cfa58)  and it seems to be working good so far.
I'll keep testing this week and I'll update this issue.
Thank you.

**Comment by dgageot** [comment]
Hi @rahal, can we close the issue?

**Comment by nathanleclaire** [comment]
Going to go ahead and close this... @rahal please follow up and re-open if the issue persists, thanks!

**Comment by rahal** [comment]
Yeah Thank you, it’s good now.
