### ISSUE TITLE
docker-machine env --swarm wrong message?

### ISSUE THREAD

**Issue by Ozzyboshi** [docker/machine#2019]
I set up a swarm using docker machine with a virtualbox driver on my ubuntu 14.04 LTS.

docker-machine create -d virtualbox --swarm --swarm-master --swarm-discovery token://$TOKEN swarm_master

Then i added 2 more nodes... at the end i ask docker-machine to print the env to talk to the infrastructure with:

    root@ozzy-desktop:~# docker-machine env --swarm swarmmaster
    export DOCKER_TLS_VERIFY="1"
    export DOCKER_HOST="tcp://192.168.99.100:3376"
    export DOCKER_CERT_PATH="/home/ozzy/.docker/machine/machines/swarmmaster"
    export DOCKER_MACHINE_NAME="swarmmaster"
    # Run this command to configure your shell: 
    # eval "$(docker-machine env swarmmaster)"

In my opinion the last line is wrong, # eval "$(docker-machine env --swarm swarmmaster)" should be printed instead of 
    # eval "$(docker-machine env swarmmaster)"

I usually copy - paste and execute the last line so I end up talking to the swarm master virtual machine.

**Comment by rafabene** [comment]
+1
