### ISSUE TITLE
Unable to access /var/run/docker.sock using amazonec2 driver

### ISSUE THREAD

**Issue by david-richer-adsk** [docker/machine#202]
When I try to launch the following container on a machine using amazonec2 driver I got the following errors:

docker run --rm -v /var/run/docker.sock:/tmp/docker.sock jwilder/nginx-proxy
dockergen.1 | 2015/01/01 23:43:14 error listing containers: dial unix /tmp/docker.sock: connection refused
 
It's working properly when I used the virtualbox driver. I am using the latest version of the master branch.

Thanks,
David

**Comment by ehazlett** [comment]
@david-richer-adsk this is fixed in master.  thanks for the feedback!

**Comment by david-richer-adsk** [comment]
It works. Thanks!
