### ISSUE TITLE
0.5-rc2 Error creating machine: Error with pre-create check: VBoxManage not found

### ISSUE THREAD

**Issue by swan-go** [docker/machine#2020]
on ubuntu,  why ?   thanks
$ sudo docker-machine -v
docker-machine version 0.5.0-rc2 (6cac8cc)
$ sudo docker-machine create --driver virtualbox linux
Running pre-create checks...
Error creating machine: Error with pre-create check: VBoxManage not found

**Comment by dgageot** [comment]
Hi @swan-go You need to have [VirtualBox](https://www.virtualbox.org/) installed for the virtualbox driver to work. Is it?
If it is, can you tell me the path to `VBoxManage`?

**Comment by swan-go** [comment]
Ok, I see, thanks

**Comment by dmp42** [comment]
Admittedly the error message could be enhanced.

**Comment by dgageot** [comment]
@dmp42 I improved the error message. ptal
