### ISSUE TITLE
Google driver is broken since 0.5.0-rc1

### ISSUE THREAD

**Issue by dgageot** [docker/machine#2023]
The authentication mechanism is broken for Google Driver is broken since 0.5.0-rc1.
The driver process fails just after opening a browser for the authentication oauth.

```
$ /bin/docker-machine create -d google --google-project my-project machine

Running pre-create checks...
Creating machine...
Error creating machine: Error in driver during machine creation: unexpected EOF
```

**Comment by dmp42** [comment]
This one is critical.
It's also worth looking into other drivers to see if there are similar patterns.

**Comment by dgageot** [comment]
Hi @jeffmendoza, would you or a colleague be willing to work on that issue?

**Comment by jeffmendoza** [comment]
I'll take a look on Monday

**Comment by dmp42** [comment]
Thanks @jeffmendoza ! 
cc @nathanleclaire

**Comment by nathanleclaire** [comment]
Have my eye on it.

My general thinking is that we should modify the driver to run without needing input from the user mid-flight, i.e. it asks for the required secrets etc. as flags instead.

**Comment by dgageot** [comment]
#1061already asked for a non-interactive way of creating a machine

**Comment by dgageot** [comment]
@nathanleclaire @jeffmendoza I've got an experimental version here: https://github.com/dgageot/machine/tree/gce-default-auth

It uses default auth to create a vm. That means that if docker-machine is run from GCE, no auth is necessary. If it is run from elsewhere, the user has to run `gcloud auth login` once before calling `docker-machine` any time needed.

It looks very good except I now have SSH problems when trying to create a machine... I'm going to investigate.
