### ISSUE TITLE
Drivers which don't use `--engine-install-url` should at least warn if the option is used

### ISSUE THREAD

**Issue by jpetazzo** [docker/machine#2029]
If someone wants to install a RC or experimental version, they can do something like:

```
docker-machine create -d amazonec2 --engine-install-url test.docker.com mytestbox
```

However, if they try to do that with a local VM (`-d virtualbox`) the option is silently ignored (since the `virtualbox` driver uses boot2docker images rather than the SSH-based provisioning system).

Instead, the `--virtualbox-boot2docker-url` has to be used.

It would be nice if Machine could display a warning when the `--engine-install-url` (and potentially other options) are used with a driver that doesn't use them.

Also: I couldn't find much info in the docs about this; but maybe I didn't look hard enough (I figured it out with the command-line help, mostly).

/cc @ManoMarks

**Comment by nathanleclaire** [comment]
That's fair -- right now I think we imply that it will work everywhere, but it's OS-dependent.

**Comment by mfischer-zd** [comment]
Why have a separate option argument name in the first place?   Is there some reason why the virtualbox driver can't use the `--engine-install-url` option?

**Comment by jpetazzo** [comment]
Because the virtualbox driver is using boot2docker, which comes as a small,
optimized disk image with Docker pre-installed on it.
The other drivers assume that the host will come clean, and that they have
to SSH into the host to install Docker using the get.docker.com script.


On Mon, Oct 26, 2015 at 11:27 AM, Michael S. Fischer <
notifications@github.com> wrote:

> Why have a separate option argument name in the first place? Is there some
> reason why the virtualbox driver can't use the --engine-install-url
> option?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/docker/machine/issues/2029#issuecomment-151238225>.
>



-- 
@jpetazzo <https://twitter.com/jpetazzo>
http://jpetazzo.github.io/

**Comment by mfischer-zd** [comment]
@jpetazzo see above :)

**Comment by mfischer-zd** [comment]
Also, right now, as a consequence of this operational inconsistency, I can't figure out how to get boot2docker to run a prerelease version of docker: the latest published ISO has 1.8.3 on it and doesn't seem to want to be easily upgraded.

**Comment by ppadala** [comment]
I ran into the same problem. Found this blog post http://sirile.github.io/2015/07/02/using-docker-18-experimental-with-docker-machine-and-virtualbox-driver-boot2docker.html to help with this.

You could build your own boot2docker image with pre-release version as mentioned in the link above as well.

**Comment by nathanleclaire** [comment]
@mfischer-zd 

You can try out different versions of boot2docker using the `--virtualbox-boot2docker-url` flag, e.g.:

```
$ docker-machine create -d virtualbox \
    --virtualbox-boot2docker-url https://github.com/tianon/boot2docker-legacy/releases/download/v1.9.0-rc2/boot2docker.iso \
    1.9rc2
```

**Comment by mfischer-zd** [comment]
Thanks @ppadala @nathanleclaire !

**Comment by jpetazzo** [comment]
You can install an experimental build like this:

```
docker-machine create -d virtualbox --virtualbox-boot2docker-url https://github.com/tianon/boot2docker-legacy/releases/download/v1.9.0-rc1/boot2docker.iso
 blah
```

I totally understand your concern (i.e. discrepancy between the virtualbox driver and other drivers). There are a few possible solutions, but they all require some extra work; e.g.:
- changing the virtualbox driver to use a basic ubuntu image (great for consistency, but means a much bigger download for the VM image, since boot2docker has been extremely optimized for size; it's like 30 MB instead of 300!)
- changing the get.docker.com install script so that it recognizes that it's in boot2docker and does "the right thing" (i.e. install/upgrade Docker when needed)

**Comment by dgageot** [comment]
@jpetazzo Do you think we could at least print a warning to the user saying that `--engine-install-url` should not be used with `virtualbox` driver. We could point to using `--virtualbox-boot2docker-url` instead. The other solutions seem very expensive.

**Comment by jpetazzo** [comment]
Printing a warning would be sufficient (and, in my opinion, necessary :-))

The other solutions were just listed out of completeness.

On Mon, Nov 2, 2015 at 6:40 AM, David Gageot <notifications@github.com>
wrote:

> @jpetazzo <https://github.com/jpetazzo> Do you think we could at least
> print a warning to the user saying that --engine-install-url should not
> be used with virtualbox driver. We could point to using
> --virtualbox-boot2docker-url instead. The other solutions seem very
> expensive.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/docker/machine/issues/2029#issuecomment-153034336>.
>



-- 
@jpetazzo <https://twitter.com/jpetazzo>
http://jpetazzo.github.io/

**Comment by dgageot** [comment]
Thanks @jpetazzo we are aligned ten!

**Comment by lox** [comment]
Seems like this option isn't supported by `generic` either.

**Comment by nathanleclaire** [comment]
@lox It should work fine with `generic` driver.  Depends on the OS.  Which OS are you using?

**Comment by lox** [comment]
I believe I was actually seeing https://github.com/docker/docker/issues/19620 and I assumed it was a docker-machine related issue. I'll check if it's resolved.

**Comment by anentropic** [comment]
need a solution for Digital Ocean driver too, see above
