### ISSUE TITLE
0.5.0 rc2 machine names with hyphen

### ISSUE THREAD

**Issue by atomi** [docker/machine#2030]
Testing 0.5.0 rc2 I created a machine

```docker-machine create -d virtualbox CI-SERVER```

Running ```machine ls``` or ```machine rm CI-SERVER``` gives the following error:

```Driver "" not found. Do you have the plugin binary accessible in your PATH?```

**Comment by dgageot** [comment]
Hi @atomi, I can't reproduce this issue. Can you provide more context? OS? Are there other machines already created? Can you triple check your path?...

Looks like a duplicate of #2040

**Comment by atomi** [comment]
Yeah. Apologies for such little context. 
I'm testing on a Windows 10 rig using Babun/mintty. 

I think the reason for this error.

**Comment by atomi** [comment]
I just tested this again with docker-machine in the system wide user path and with the path set using only cygwin and am unable to reproduce the error again. Closing this for now.

**Comment by nathanleclaire** [comment]
Thanks for reporting and for following up to close @atomi!
