### ISSUE TITLE
docker-machine create fails

### ISSUE THREAD

**Issue by hadley** [docker/machine#2041]
After a fresh install of docker toolbox on OS X 10.10.5, I get:

```
docker-machine create --driver virtualbox default
Creating CA: /Users/hadley/.docker/machine/certs/ca.pem
Creating client certificate: /Users/hadley/.docker/machine/certs/cert.pem
Creating VirtualBox VM...
Creating SSH key...
Error creating machine: exit status 1
You will want to check the provider to make sure the machine and associated resources were properly removed.
```

**Comment by dgageot** [comment]
Hi @hadley, thank you fir the bug report. Can you provide more information on the context? Please read https://github.com/docker/machine/blob/master/README.md#troubleshooting for information on what you can try and what information you can report.

**Comment by hadley** [comment]
Sure:

* There is no log file (or Logs directory) in the corresponding machine directory
* Deleting that directory and then rerunning `docker-machine create --driver virtualbox default --debug` yields https://gist.github.com/hadley/c2e697f71b31db19c496

The relevant bit seems to be:

```
executing: /usr/local/bin/VBoxManage modifyvm default --firmware bios --bioslogofadein off --bioslogofadeout off --bioslogodisplaytime 0 --biosbootmenu disabled --ostype Linux26_64 --cpus 1 --memory 1024 --acpi on --ioapic on --rtcuseutc on --natdnshostresolver1 off --natdnsproxy1 off --cpuhotplug off --pae on --hpet on --hwvirtex on --nestedpaging on --largepages on --vtxvpid on --accelerate3d off --boot1 dvd
STDOUT: 
STDERR: VBoxManage: error: The machine 'default' is already locked for a session (or being unlocked)
VBoxManage: error: Details: code VBOX_E_INVALID_OBJECT_STATE (0x80bb0007), component MachineWrap, interface IMachine, callee nsISupports
VBoxManage: error: Context: "LockMachine(a->session, LockType_Write)" at line 493 of file VBoxManageModifyVM.cpp
```

**Comment by dgageot** [comment]
Can you try to create a fresh machine with a new name and provide the logs?

```
docker-machine create --driver virtualbox newname --debug
```

**Comment by hadley** [comment]
Killing, rm'ing, then re-creating the image seems to fix the problem.

**Comment by hadley** [comment]
I think I probably got in this state because I upgraded from boot2docker - `docker-machine env default` failed so I tried to `docker-machine rm default`. That was still running after 15 minutes, so I killed the process, and manually deleted the `machine` directory.

**Comment by hadley** [comment]
Thanks for the help!
