### ISSUE TITLE
vsphere driver cant find boot2docker.iso

### ISSUE THREAD

**Issue by pandrew** [docker/machine#2060]
The vspheredriver looks for boot2docker.iso in ~/.docker/machine/ by default. Creating machine without iso already downloaded gives an error about the iso is missing. It seems to complete the download to the cache folder. Copying the iso from ~/.docker/machine/cache/ to ../machine/ solves this temporarily.

**Comment by nathanleclaire** [comment]
cc @frapposelli

**Comment by frapposelli** [comment]
The current plugin is being rewritten from scratch (see #1522) once that is merged this will be fixed.

**Comment by szechyjs** [comment]
:+1:

**Comment by dgageot** [comment]
Fixed in https://github.com/docker/machine/pull/2487
