### ISSUE TITLE
Colons in SCP filepaths aren't supported

### ISSUE THREAD

**Issue by joeduffy** [docker/machine#2064]
On Windows, it's easy to get into a situation where you need a colon in filepaths, due to drive specifications.  For example, `docker-machine scp c:\some\file.txt default:/some/file.txt`.

This is currently unsupported, though it took a little spelunking.  See https://github.com/docker/machine/blob/master/commands/scp.go#L45.

My initial attempt to solve this was to specify localhost as the hostname, as in `docker-machine scp localhost:c:\some\file.txt default:/some/file.txt`, but alas, no luck.  It seems like a reasonable solution -- the syntax is clearly ambiguous otherwise -- and probably what would come to mind for many folks.

It's also a reasonable stance that docker-machine only support UNIX-style absolute filepaths, but everything else works so nicely in DOS cmd shells, it'd be a shame if Windows users had to drop back to Cygwin/MSYS/MinGW/etc. just do perform copying operations, IMHO.

**Comment by joeduffy** [comment]
It occurs to me maybe `localhost` is problematic.  I mean, what if you named one of your Docker Machines "localhost"?  Maybe there are alternative specification formats to consider, like `.:c:\some\file.txt` or `:c:\some\file.txt`.  Just a thought.

**Comment by dgageot** [comment]
@nathanleclaire wdyt?

**Comment by nathanleclaire** [comment]
Let's look at this after the release, I'm swamped with other more pressing issues.
