### ISSUE TITLE
docker-machine create -d virtualbox needs longmode

### ISSUE THREAD

**Issue by rhendric** [docker/machine#2071]
OS X 10.6.8, VirtualBox 4.3.32 (the latest version of VB available for pre-Mountain Lion)

I know that the new Docker Toolbox installer only supports Mountain Lion and higher, but I'm still able to use docker and docker-machine by building them myself. The one problem I've run into is that the vbox files created by docker-machine have longmode set to false in them (maybe this is a default in VB 4.3 that has changed in more recent VB?). This causes the VM to hang at boot with `kernel requires an x86_64 cpu, but only detected an i686 cpu` printed on the VM console.

I added a `"--longmode", "on"` line to the list of modifyvm flags in [drivers/virtualbox/virtualbox.go](https://github.com/docker/machine/blob/master/drivers/virtualbox/virtualbox.go), which solved the problem; however, I also found [this old bug](https://github.com/boot2docker/osx-installer/issues/82) which implies that `--longmode` was removed for a reason, which is why this isn't just a PR.

Thoughts?

**Comment by nathanleclaire** [comment]
In general (and somewhat unfortunately), we support only the latest versions of VirtualBox, and treatment of which flags we pass in to `VBoxManage` etc. is handled accordingly.  I'd be willing to discuss proposals to handle different versions more robustly (and indeed we're starting to take steps in the right direction there with some of the recent work we've done on testing that driver), but for now it's considered that the latest versions of VirtualBox are expected to be the only supported ones.

**Comment by rhendric** [comment]
So, since I'm not running VirtualBox 5 I can't test this myself, but the [current manual](http://www.virtualbox.org/manual/ch08.html#idp45859073204832) does mention `--longmode` as a valid option for `modifyvm`; maybe it's that 4.3 has it `off` by default in VMs created via command line and 5 has it `on` by default (I'm only assuming the latter because I don't see how the VirtualBox driver would ever work otherwise)? If that's the case (I assume a maintainer can quickly check their `VBoxManage` for `--longmode` support), would you reconsider adding the flag explicitly?

**Comment by nathanleclaire** [comment]
Yup, looks like 5.0.6 has the flag.  I'd consider adding it.
