### ISSUE TITLE
docker-machine ls fails if a driver is not found

### ISSUE THREAD

**Issue by dmp42** [docker/machine#2077]
Reproduce:
 * have machines created created by driver `foo`
 * make sure driver `foo` is not available
 * docker-machine ls (and probably other commands)

Result: 

`Driver "foo" not found. Do you have the plugin binary accessible in your PATH?`

Expected result:

List my valid machines and work with that.

The current behavior is a problem since we changed the vsphere driver name, and also, since removing a single plugin breaks all machines for the user.

**Comment by nathanleclaire** [comment]
Side note: For us to have changed any driver name, `hyper-v` etc., strikes me now as a very bad idea.  We shouldn't have done that.

As for the issue of `ls` failing when a driver is not found, I agree it shouldn't lock up completely in this case.  I'll look into some potential workarounds for this release.
