### ISSUE TITLE
docker-machine rm -f not working (0.4)

### ISSUE THREAD

**Issue by dmp42** [docker/machine#2078]
```
docker-machine rm -f sometest
Error removing machine sometest: Error getting migrated host: hosts: Unknown driver "mydriver"
There was an error removing a machine. To force remove it, pass the -f option. Warning: this might leave it running on the provider.
```

@nathanleclaire wdyt? was this fixed on master? (I can't test because I'm in a catch 22 situation where I miss the driver that created these machines)

**Comment by nathanleclaire** [comment]
It should be fixed.  Let me know if `docker-machine rm -f` does not remove the machine's local directory for you on master.

**Comment by dmp42** [comment]
@nathanleclaire it does not work on master because of #2077 - but maybe we can consider this aspect of it as a duplicate?

**Comment by nathanleclaire** [comment]
@dmp42 Yeah, I'd argue that #2077 is the real issue here:  the code around force removing in general should be sound.
