### ISSUE TITLE
-d flag undocumented

### ISSUE THREAD

**Issue by zenfish** [docker/machine#2080]
The -d flag doesn't appear to be documented... at least, it isn't listed in the default output (e.g. "$ docker-machine") or in any git pages I could find (it may be in there somewhere), but the flag is used extensively in the various examples, including the very first one on the git homepage.

**Comment by dmp42** [comment]
`-d` is the same as `--driver`

I believe this is documented. See for example: https://github.com/docker/machine/blob/master/docs/reference/create.md#filtering-create-flags-by-driver-in-the-help-text
this is also in the output of `docker-machine create`

Nevertheless, documentation can be improved, so, if you feel something can be made better, please open a PR.

Hope that helps.

**Comment by zenfish** [comment]
If you think that not explaining what the only argument means in the first use case (and three on your splash page on git) you talk about in your documentation is sufficient, who am I to argue. Dismiss away, surely users will figure it out, dox are overrated anyway.

**Comment by dmp42** [comment]
@zenfish 

From your initial report:

> at least, it isn't listed in the default output (e.g. "$ docker-machine")

This is not accurate.

It is listed in the default output, where it makes sense (`docker-machine create`).

Furthermore, this issue title:

> -d flag undocumented

Is also not accurate, like pointed out in my first comment

> If you think that not explaining what the only argument means in the first use case (and three on your splash page on git) you talk about in your documentation is sufficient, who am I to argue

Thanks for the feedback.

Like I said, if something can be improved, it should definitely be.

If you are willing to contribute, please go for it, the community will happily review your contribution.

If you are not, then you are still welcome to report what you feel is not optimal - conversely, maintainers are entitled to close issues that they think are not accurate / not helping (for the reasons why I closed this one, see my first comment).

Nevertheless, if you still think this one should be reopened, please retitle it and re-describe it.
If you don't want to do that, fine, the documentation will still be improved at a later point.

Thanks again.
