### ISSUE TITLE
How can I do to Disable Transparent Huge Pages?

### ISSUE THREAD

**Issue by sebicas** [docker/machine#2081]
I am getting some warnings on a few containers ( Redis & Mongo )

```
** WARNING: /sys/kernel/mm/transparent_hugepage/enabled is 'always'.
**        We suggest setting it to 'never'

** WARNING: /sys/kernel/mm/transparent_hugepage/defrag is 'always'.
**        We suggest setting it to 'never'
```

And as far as can I read on https://github.com/docker-library/redis/issues/20#issuecomment-76066090 is a host ( boot2docker on VirtualBox ) issue.

How can I do to set this kernel flags as 'never' as suggested?

```
docker-machine version 0.4.1 (e2c88d6)
Boot2Docker version 1.8.2, build master : aba6192 - Thu Sep 10 20:58:17 UTC 2015
Docker version 1.8.2, build 0a8c2e3
```

**Comment by thaJeztah** [comment]
Hm, perhaps this should be opened in the Boot2Docker issue tracker; https://github.com/boot2docker/boot2docker/issues

/cc @tianon @SvenDowideit

**Comment by pcssi** [comment]
:+1:

**Comment by tianon** [comment]
This is probably a good use case for `bootlocal.sh`/`bootsync.sh` inside the VM (see https://github.com/boot2docker/boot2docker/blob/master/doc/FAQ.md#local-customisation-with-persistent-partition).

**Comment by nathanleclaire** [comment]
Yup, the answer lies within boot2docker the OS.  Please open an issue there if you continue to experience problems.  Thanks!

**Comment by sebicas** [comment]
Issue has been resolved at boot2docker, here is the link to the issue for reference: https://github.com/boot2docker/boot2docker/issues/1083

**Comment by pcssi** [comment]
@sebicas thank you. :+1:

**Comment by nathanleclaire** [comment]
Thanks @sebicas for following up
