### ISSUE TITLE
[amazonec2] Only us-east-1a region / AZ works

### ISSUE THREAD

**Issue by kundeng** [docker/machine#2082]
I tried the docker machine for amazonec2 today and I encountered several issues:

1.  only the default region us-east-1 a  works.  Can't specify other region or zone in the command.  Otherwise,  for strange reasons:  the subnet will be appended by 2 extra spaces! 

2.  not automatically removing the key pair  when failure of creation occurs.  Had to go into amazon to remove it 

3.  ssh error. 
Using SSH client type: external
About to run SSH command:
if grep -xq 127.0.1.1.* /etc/hosts; then sudo sed -i 's/^127.0.1.1.*/127.0.1.1 aws-bandit/g' /etc/hosts; else echo '127.0.1.1 aws-bandit' | sudo tee -a /etc/hosts; fi
&{/usr/bin/ssh [/usr/bin/ssh -o PasswordAuthentication=no -o IdentitiesOnly=yes -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=quiet -o ConnectionAttempts=3 -o ConnectTimeout=10 -i /Users/kundeng/.docker/machine/machines/aws-bandit/id_rsa -p 22 ubuntu@52.91.104.135 if grep -xq 127.0.1.1.* /etc/hosts; then sudo sed -i 's/^127.0.1.1.*/127.0.1.1 aws-bandit/g' /etc/hosts; else echo '127.0.1.1 aws-bandit' | sudo tee -a /etc/hosts; fi] []  <nil> <nil> <nil> [] <nil> <nil> <nil> <nil> false [] [] [] [] <nil>}
SSH cmd err, output: <nil>: 127.0.1.1 aws-bandit
sudo: unable to resolve host awe-bandit

More errors after that...

**Comment by dmp42** [comment]
Hi @kundeng 

Is this from master or a released version of machine?

**Comment by kundeng** [comment]
Released version.  

Sent from Outlook




On Sun, Oct 25, 2015 at 10:43 PM -0700, "Olivier Gambier" <notifications@github.com> wrote:












Hi @kundeng 



Is this from master or a released version of machine?

**Comment by dmp42** [comment]
@kundeng any chance you can test the latest 0.5 release candidates?

https://github.com/docker/machine/releases/tag/v0.5.0-rc3

**Comment by nathanleclaire** [comment]
@kundeng Please paste the `create` commands used (minus any secrets such as IAM credentials) and the full debug output when you get a chance.

**Comment by jeanlaurent** [comment]
Driver has been completely rewrote since then, and many tests reported this working on different zone and regions.

Feel free to re-open with fresh information if needed.
