### ISSUE TITLE
Maximum number of retries (60) exceeded

### ISSUE THREAD

**Issue by midito** [docker/machine#2085]
Hi,
I'm having some troubles with Docker in Mac. Every time I restart I have a different problem and is really frustrating. Now, I'm getting the next error after upgraded docker & virtualbox because i was having other kind of problems taht didn't allow me to start my machine.

I can't start my dev machine and i get some error when I try to list the machines. Also, the docker-vm shows an error state.

Any ideas?

mycomputer:backend-admin myuser$ docker-machine env dev
Maximum number of retries (60) exceeded
export DOCKER_TLS_VERIFY="1"
export DOCKER_HOST="tcp://10.99.171.244:2376"
export DOCKER_CERT_PATH="/Users/myuser/.docker/machine/machines/dev"
export DOCKER_MACHINE_NAME="dev"
# Run this command to configure your shell: 
# eval "$(docker-machine env dev)"
mycomputer:backend:backend-admin myuser$ docker-machine ls
error getting state for host docker-vm: machine does not exist
error getting URL for host docker-vm: machine does not exist
error getting state for host docker-vm: machine does not exist
error determining if host is active for host docker-vm: machine does not exist
NAME        ACTIVE   DRIVER       STATE     URL                         SWARM
default     *        virtualbox   Running   tcp://192.168.99.100:2376   
dev                  virtualbox   Running   tcp://10.99.171.244:2376    
docker-vm            virtualbox   Error

**Comment by dgageot** [comment]
Hi @midito, it looks like two machines are working ok: `default` and `dev`. A third machine, `docker-vm`, is not found even if its description exists in your `~/.docker/machine/machines/` folder.

Can you try `docker-machine rm -f docker-vm` and see if it fixes the problem.

**Comment by midito** [comment]
After I shut down my computer ( I restarted it sometimes before ) and doing this, now everything works fine. I don't know if it was because deleting the "docker-vm" machine or the magic "turn it of and on again". Thanks for your help. Everything is working as expected now.

**Comment by dgageot** [comment]
Thank you for the feedback!
