### ISSUE TITLE
Improve the output of `docker-machine ls` in case of an error

### ISSUE THREAD

**Issue by dgageot** [docker/machine#2086]
`docker-machine ls` prints something like this in case one of the machines is not well configured. 

```
$ docker-machine ls

error getting URL for host other: machine does not exist
error getting state for host other: machine does not exist
NAME      ACTIVE   DRIVER       STATE     URL                         SWARM
default   -        virtualbox   Running   tcp://192.168.99.100:2376
other     -        virtualbox   Error
```

The problem occurs for example when a machine is manually deleted.

It would be nicer for the user either swallow the error or move the message to an additional column, like this:

```
$ docker-machine ls

NAME      ACTIVE   DRIVER       STATE     URL                         SWARM ERRORS
default   -        virtualbox   Running   tcp://192.168.99.100:2376
other     -        virtualbox   Error                                       machine does not exist
```

**Comment by nathanleclaire** [comment]
Huge +1 from my end on this, it's been a pet peeve for a long time.

How I would like to do this is to move over to per-driver loggers (consequently things logged within the driver would be query-able later using [docker-machine logs](https://github.com/docker/machine/issues/1821)) which can also be accessed externally using a `driver.Log` method.  Unfortunately, though, we can't write code that depends on that once we start distributing plugins everywhere (very soon) which don't have it (without a version bump to the plugin API, at least).

Maybe we can instead aggregate the external errors (notice that the kind you list above come from outside the driver, not inside) and display them in an error column like you mention.

**Comment by dgageot** [comment]
@nathanleclaire Let's start with the aggregation. Ok ?

**Comment by nathanleclaire** [comment]
Yeah that SGTM
