### ISSUE TITLE
docker-machine creates a virtualbox with an old API version

### ISSUE THREAD

**Issue by funkytaco** [docker/machine#2089]
Referencing #2046 as it seems to be related.

docker-machine spins up a 1.19 machine....my client docker API is 1.20 .... I've tried `docker-machine upgrade` as well, to no avail.

`docker-machine create -d virtualbox --virtualbox-memory "4096" --virtualbox-disk-size "32000" nyc`

    Creating VirtualBox VM...
    Creating SSH key...
    Starting VirtualBox VM...
    Starting VM...
    To see how to connect Docker to this machine, run: docker-machine env nyc

    $ dm_env nyc

    $ docker images
    Error response from daemon: client and server don't have same version (client API version: 1.20, server API version: 1.19)

**Comment by funkytaco** [comment]
To work around this, I used @sirile's 1.9 iso:
`docker-machine create -d virtualbox --virtualbox-boot2docker-url=http://sirile.github.io/files/boot2docker-1.9.iso nyc` which uses API version 1.21

**Comment by nathanleclaire** [comment]
1.9 is not out yet.  When it is out, `upgrade` will work.

**Comment by funkytaco** [comment]
The `docker-machine` I used came from https://github.com/docker/toolbox/releases/download/v1.8.3/DockerToolbox-1.8.3.pkg

Toolbox has a `docker-machine` which created a VirtualBox with an API that's older than the one it uses, so it renders the `create` command useless for Virtualbox, does it not? Or maybe I caused the problem (no idea how)?

Docker Toolbox comes with: Docker Engine 1.8.3, "Virtualbox" (no version mentioned, but I did check for updates manually), Docker Machine 0.4.1

**Comment by nathanleclaire** [comment]
@funkytaco For `upgrade` at least, Docker Machine version does not matter; it will check with GitHub to see the most recently released boot2docker, and get that.  It's still 1.8.3 today until Docker 1.9 comes out.
