### ISSUE TITLE
Machine should detect and/or remove unused host only interfaces as part of the creation process

### ISSUE THREAD

**Issue by nathanleclaire** [docker/machine#2091]
cc @docker/machine-maintainers 

Normally I'm against automatically removing resources, but we've had _so_ many issues around extraneous host-only networks, that I'm beginning to think we should add code to the `virtualbox` driver to go through existing host-only networks and DHCP servers and clear out any that are not in use by VMs.  Or, at least, to try and detect the invalid states when they come up.

**Comment by drbitslayer** [comment]
Agreed, I am spinning up many times and with docker-machine "hanging" when removing docker machines it's not removing the adapaters.  I end up with many of them.

**Comment by dgageot** [comment]
@nathanleclaire Do you know what creates those networks in the first place? I've tried to push vb into doing it. I failed.

**Comment by nathanleclaire** [comment]
They're created through `VBoxManage`, and usually the invoker is either:

1. Faulty logic in Machine (whether it's older versions, experimental branches, etc.) or
2. Other tools such as boot2docker and Vagrant that do this kind of creation and may or may not have cleaned up

My thinking is, our best bet to start resolving these kinds of issues, is take a look at the output of commands from users with faulty configurations, and start writing some tests around handling and/or detecting them.

**Comment by dgageot** [comment]
Closed with https://github.com/docker/machine/pull/2625

**Comment by hiteshjoshi1** [comment]
I am on Windows 8.1 Pro. I am using Docker toolbox which I installed recently. I am facing this issue even now. I suppose that your fix should be released by now. But I still get multiple host only networks which bring my internet down. This is stopping me from doing any serious work.

**Comment by Milanoss** [comment]
Same issue for me. After Docker toolbox installation I lost connection because of "VirtualBox Host-Only Network". "Docker Quickstart Terminal" cannot finish without error.

**Comment by farhadab** [comment]
Same issue for me Windows 10. Every time my computer sleeps and restarts, I lose internet/wireless network adapter access.
