### ISSUE TITLE
Checking if hardware virtualization is enabled prints extraneous error messages

### ISSUE THREAD

**Issue by nathanleclaire** [docker/machine#2092]
cc @docker/machine-maintainers @dgageot 

![screen shot 2015-10-26 at 2 05 54 pm](https://cloud.githubusercontent.com/assets/1476820/10742511/d5767708-7bea-11e5-9d35-3cc264f6831b.png)

We need to use `os.Stat` to check if the log file exists first.

**Comment by dgageot** [comment]
@nathanleclaire The real question is "Why is this file not found?" Are we trying to read it too early?

**Comment by dgageot** [comment]
@nathanleclaire I think the problem is not related to hardware virtualization check. The path `machines/default/default/Logs/VBox.log` is wrong. It looks like the `StorePath` is empty which is another problem.
Closing this issue.

**Comment by nathanleclaire** [comment]
Yeah good call.  It makes sense and I happen to know that something is wonky in the migration on this particular computer / DM combination.
