### ISSUE TITLE
"This computer doesn't have VT-X/AMD-v enabled" (Bootcamp running Windows)

### ISSUE THREAD

**Issue by dracan** [docker/machine#2093]
Whilst this is technically a Bootcamp issue, the recent change where Docker Machine checks if virtualization is enabled fails when running on a Macbook Pro using Windows. The virtualization flag is set to false when you boot straight into Windows for some unknown reason. A google suggests that there's no way around this other than first booting into OSX, then doing a soft boot into Windows each time :-/

Docker Machine was working fine for me until I updated to RC3 where it's now unusable, as it just throws the following error:

"This computer doesn't have VT-X/AMD-v enabled."

Is there any way this check can be bypassed? Perhaps with an explicit command line argument?

**Comment by nathanleclaire** [comment]
cc @dgageot

**Comment by nathanleclaire** [comment]
Having seen a couple of these issues now, I'd suggest we move towards using `log.Warn` or something instead of banning attempted create completely

**Comment by dgageot** [comment]
@nathanleclaire How do we print a warning from a driver? `log.Warn` is only visible on debug mode.

**Comment by dgageot** [comment]
OK, I'm going to just log a warning (which unfortunately is not visible unless running in debug mode).
Anyway, the vm is checked for actual VT-X support after creation.
If the first check can be improved to being bulletproof, then we can restore the failure before the vm is created.

**Comment by mlgiter** [comment]
Error starting Docker Quickstart:

>Welcome to msysGit


Run 'git help git' to display the help index.
Run 'git help <command>' to display help for specific commands.
Run '/share/msysGit/add-shortcut.tcl' to add a shortcut to msysGit.
Machine default already exists in VirtualBox.
Starting machine default...
(default) Starting VM...
This computer doesn't have VT-X/AMD-v enabled. Enabling it in the BIOS is mandat
ory
Looks like something went wrong... Press any key to continue...

But VirtualBox can be started any time at my PC.(AMD x6 CPU), as i do Android development, too..

**Comment by tekintian** [comment]
I got this error

**Comment by aaron72** [comment]
Error reappeared even though VT-X us enabled on host system.
