### ISSUE TITLE
Call `eval "$(docker-machine env default)"` automatically

### ISSUE THREAD

**Issue by iBobik** [docker/machine#2094]
Is i able to make commands like restart and start to call `eval "$(docker-machine env default)"` automatically, so user don't run it manually?

**Comment by nathanleclaire** [comment]
We can't do it directly from the Machine binary (child process can't alter the environment of their parent), but you could make a shell alias for it.  There's one such shell alias included in our bash autocompletion scripts, so take a look at those if you're curious.
