### ISSUE TITLE
Dockerfile to run Machine

### ISSUE THREAD

**Issue by defermat** [docker/machine#21]
Hi, I see there is already a Dockerfile for building Machine, but I created a Dockerfile to run Machine inside a container using docker-in-docker.  Wasn't sure if there was a place for it in this repo, or if I should just keep it as a separate repo and perhaps reference it in the docs for those interested?  I'm also fine if this issue is closed and the runtime Dockerfile doesn't belong here, but thought I'd throw it out there if there's interest.

On the hub:
https://registry.hub.docker.com/u/defermat/machine/

On Github:
https://github.com/defermat/machine

I'm happy to make a PR if there's a particular direction that makes sense.

**Comment by ehazlett** [comment]
Closing this.  We are getting more local drivers that rely on applications that do not offer APIs.  While I am in favor of using containers for everything, this would give an odd user experience by recommending an image for some providers and the binary for local.
