### ISSUE TITLE
Support for PEM in addition to JSON cert files?

### ISSUE THREAD

**Issue by alankent** [docker/machine#210]
I grabbed the prebuilt version of 'machine' for Windows and gave it a try. It failed to find public-key.json. The Windows native Docker.exe (client only) I built runs successfully (talking to my local VirtualBox instance), but uses PEM files. Looking in utils.go it appears to be hard coded to use public-key.json (no way to ask it to use cert.pem), even though the lower level code seems to be able to read both JSON and PEM certificate files.

Is it worth making 'machine' also support PEM files?  (Or is it Docker in the future will use JSON files and not support PEM files any more for identity?)

**Comment by ehazlett** [comment]
As of now, the only auth that machine supports in identity.  I am working to get multiple builds for the major platforms (linux, mac, windows) for Docker with Identity and Machine for easier testing.

**Comment by alankent** [comment]
Thanks. I am no expert, but my reading was 'identity' is supposed to support both PEM and JSON files for holding identity. "These public keys will be stored as JSON Web Keys and can be distributed as a JSON file, *or as a standard PEM file*" - https://github.com/docker/docker/issues/7667.

The lower level code seems to be able to read PEM files - its just 'machine' seems to have a bit of hard coded code in the middle to only use the JSON files (as I originally mentioned), rather than trying both JSON and PEM files based on whichever was available.

**Comment by ehazlett** [comment]
Ah ok I think I understand what you are saying now.  At this time we don't
have any plan to support the .pem version but PRs welcome :)

**Comment by alankent** [comment]
In case anyone else is interested, I came across https://github.com/docker/docker/blob/999d4117f6544aeefaba3c40aef678042c71aa7a/vendor/src/github.com/docker/libtrust/tlsdemo/README.md which talks about a program to convert public-key.json etc files into PEM files.

**Comment by jaigouk** [comment]
something like this? https://github.com/jaigouk/convert_pem_to_json/blob/master/convert_pem_to_json.go

**Comment by ehazlett** [comment]
We are switching from identity auth to standard TLS (
https://github.com/docker/machine/issues/254).  This should fix this issue.
