### ISSUE TITLE
Gracefully fallback if building out of a git clone 

### ISSUE THREAD

**Issue by dmp42** [docker/machine#2102]
See https://github.com/Homebrew/homebrew/issues/45352

**Comment by nathanleclaire** [comment]
What do you think about https://github.com/docker/machine/pull/2103 ?

It should clean up the error messages and will simply have the git tag be empty string in the resulting binaries, which seems reasonable result to me.

**Comment by dmp42** [comment]
Yes, works well. Thanks @nathanleclaire
