### ISSUE TITLE
Switching env missing .pem after creating machine on ec2

### ISSUE THREAD

**Issue by thomassnielsen** [docker/machine#2114]
I've just created a machine on ec2, but I can't switch to it. There were some errors during setup that might have contributed to this. Steps:

1. Created the machine
```
docker-machine -D create \
--driver amazonec2 \
--amazonec2-access-key <access-key> \
--amazonec2-secret-key <secret-key> \
--amazonec2-vpc-id <vpc-id> \
--amazonec2-subnet-id <subnet-id> \
--amazonec2-region eu-west-1 \
--amazonec2-zone b \
<name>
```

Errors during creation:

```
SSH cmd error!
command: sudo apt-get update
err    : exit status 100
output : Ign http://archive.ubuntu.com trusty InRelease
Get:1 http://archive.ubuntu.com trusty-updates InRelease [64.4 kB]
Get:2 http://security.ubuntu.com trusty-security InRelease [64.4 kB]
Hit http://archive.ubuntu.com trusty Release.gpg
Hit http://archive.ubuntu.com trusty Release
Get:3 http://archive.ubuntu.com trusty-updates/main amd64 Packages [638 kB]
E: can not open /var/lib/apt/lists/archive.ubuntu.com_ubuntu_dists_trusty_Release - fopen (2: No such file or directory)
```

There is a bug in the ec2 repos that might have contributed to this. Anyway, after logging in to the server and connecting to the upstream repos instead, I'm able to run `sudo apt-get update` just fine.

## The actual problem

```sh
> eval $(docker-machine env <name>);
open /Users/thomas/.docker/machine/machines/<name>/ca.pem: no such file or directory
```

I'm not sure if there is something that didn't run properly during setup, or if this is unrelated. In any case, I'm unable to run containers on my machine by using docker-machine, since I can't switch to it. There is no .pem files at all in that folder, just the `config.json`, `id_rsa` and `id_rsa.pub`.

Any help appreciated.

**Comment by nathanleclaire** [comment]
Yes, this is one of many reasons I'd like to introduce `docker-machine provision` command -- to redo provisioning if a step temporarily fails.

**Comment by thomassnielsen** [comment]
Are there any decent workarounds at this time? Can I regenerate the .pem file in some way?

**Comment by nathanleclaire** [comment]
You could try `docker-machine regenerate-certs mcnanme`.  That might work.  The most reliable, though, is to just create a new machine.

**Comment by thomassnielsen** [comment]
Thanks, that worked. I'm afraid I might have missed some other steps as well, as I'm having other problems too (still investigating). 

It seems pretty volatile that any error like this can cancel the whole process, especially now that EC2 presumably will cause this error every single time until they fix their Ubuntu repos and/or VM image. (if I'm understanding what's happening correctly)

Would `docker-machine provision` (#2121 :+1:) solve this by running all actions that are supposed to run after server setup? I'm thinking that being able to run the steps in smaller batches (create server, configure certs, install docker, configure docker, etc) would solve most of these kinds of problems, allowing users to intervene between each step if necessary.

**Comment by nathanleclaire** [comment]
> Would docker-machine provision (#2121 :+1:) solve this by running all actions that are supposed to run after server setup? I'm thinking that being able to run the steps in smaller batches (create server, configure certs, install docker, configure docker, etc) would solve most of these kinds of problems, allowing users to intervene between each step if necessary.

Yeah, exactly -- "configure certs, install docker, configure docker" are all one step in `provision`, but it would be the start of such granularity.

**Comment by dgageot** [comment]
Closing the issue since `docker-machine regenerate-certs mcnname` did the job.
#2121 will address this issue in a broader way.
@thomassnielsen Feel free to reopen.
