### ISSUE TITLE
After upgrade to v0.5.0-rc4, Docker machine breaks on Windows 7

### ISSUE THREAD

**Issue by kunalkushwaha** [docker/machine#2123]
I upgraded to ``v0.5.0-rc4`` on windows7 with VirtualBox.

When I launch ``docker-quickstart-terminal`` or try to do any operation with ``docker-machine`` it results into following Warning.

```
WARNING >>> Error attempting heartbeat call to plugin server: rpc: can't find method RpcServerDriver.Heartbeat

```

Did I missed anything while upgrade?

**Comment by kunalkushwaha** [comment]
I think problem was old docker-virtualbox-driver loaded in memory.
After manually stopping task from task-bar, Now it works file.

**Comment by nathanleclaire** [comment]
Excellent thanks for following up @kunalkushwaha !
