### ISSUE TITLE
`docker-machine scp` to copy files from local folder to machine

### ISSUE THREAD

**Issue by gfarrell** [docker/machine#2126]
I'm trying to copy over some certificates from my computer to a `docker-machine` provisioned DigitalOcean droplet.

    docker-machine scp /local/path/to/certs/* machine-name:/etc/secure/

This gives me an error `Improper number of arguments`. Given that the usage doc says:

    Arguments are [machine:][path] [machine:][path]

Is this a bug?

(ref http://stackoverflow.com/questions/33437742/docker-machine-scp-from-local-directory-to-machine)

**Comment by dgageot** [comment]
Hello @gfarrell What you are trying to do is copy multiple files at once right? This is not possible. I think the `*` wildcard will be replaced by the shell with all the files in `/local/path/to/certs`. So `docker-machine scp` receives more than 2 arguments hence the error.
Does it make sense?

**Comment by dgageot** [comment]
I guess you should use the `-r` flag to copy the content of one folder to another folder.

**Comment by gfarrell** [comment]
yes, got it, thanks!
