### ISSUE TITLE
Driver name missing on upgrade from docker-machine 0.3.1 to 0.5.0-rc4

### ISSUE THREAD

**Issue by ljrittle** [docker/machine#2129]
`$ docker-machine ls`
Driver "" not found. Do you have the plugin binary accessible in your PATH?

I placed all drivers in /usr/local/bin per the release notes.  Confirmed they are seen on PATH.

Here is what docker-machine 0.5.0-rc4 did when it translated the `config.json` file:

`$ more ~/.docker/machine/machines/dev/config.json.bak`
{"DriverName":"virtualbox","Driver":{"IPAddress":"192.168.99.100","SSHUser":"docker","SSHPort":53507,"MachineName":"dev","CaCertPath":"/Users/ljrittle/.docker/machine/certs/ca.pem","PrivateKeyPath":"/Users/ljrittle/.docker/machine/certs/ca-key.pem","SwarmMaster":false,"SwarmHost":"tcp://0.0.0.0:3376","SwarmDiscovery":"","CPU":-1,"Memory":1024,"DiskSize":20000,"Boot2DockerURL":"","Boot2DockerImportVM":"","HostOnlyCIDR":""},"StorePath":"/Users/ljrittle/.docker/machine/machines/dev","HostOptions":{"Driver":"","Memory":0,"Disk":0,"EngineOptions":{"ArbitraryFlags":null,"Dns":null,"GraphDir":"","Ipv6":false,"InsecureRegistry":null,"Labels":null,"LogLevel":"","StorageDriver":"","SelinuxEnabled":false,"TlsCaCert":"","TlsCert":"","TlsKey":"","TlsVerify":false,"RegistryMirror":null,"InstallURL":""},"SwarmOptions":{"IsSwarm":false,"Address":"","Discovery":"","Master":false,"Host":"tcp://0.0.0.0:3376","Image":"","Strategy":"","Heartbeat":0,"Overcommit":0,"TlsCaCert":"","TlsCert":"","TlsKey":"","TlsVerify":false,"ArbitraryFlags":null},"AuthOptions":{"StorePath":"/Users/ljrittle/.docker/machine/machines/dev","CaCertPath":"/Users/ljrittle/.docker/machine/certs/ca.pem","CaCertRemotePath":"","ServerCertPath":"/Users/ljrittle/.docker/machine/certs/server.pem","ServerKeyPath":"/Users/ljrittle/.docker/machine/certs/server-key.pem","ClientKeyPath":"/Users/ljrittle/.docker/machine/certs/key.pem","ServerCertRemotePath":"","ServerKeyRemotePath":"","PrivateKeyPath":"/Users/ljrittle/.docker/machine/certs/ca-key.pem","ClientCertPath":"/Users/ljrittle/.docker/machine/certs/cert.pem"}}}

`$ more ~/.docker/machine/machines/dev/config.json`
{
    "ConfigVersion": 3,
    "Driver": {
        "IPAddress": "192.168.99.100",
        "SSHUser": "docker",
        "SSHPort": 53507,
        "MachineName": "dev",
        "SwarmMaster": false,
        "SwarmHost": "tcp://0.0.0.0:3376",
        "SwarmDiscovery": "",
        "StorePath": "/Users/ljrittle/.docker/machine",
        "URL": ""
    },
    "DriverName": "",
[...]

I see the manual fix but did I miss a release note about skipping from 0.3.1 to 0.5.0?

**Comment by nathanleclaire** [comment]
It's intended to work seamlessly but I mostly tested 0.4.1 => 0.5.0, so I missed this. Sorry about that, we're working on a fix.

**Comment by fmontada** [comment]
Hi I having the same problem, I just install "Docker Toolbox" https://docs.docker.com/engine/installation/mac/

And I want to create a EC2 with the amazonec2 driver but I am getting this error 
Driver "amazonec2\u00a0" not found. Do you have the plugin binary accessible in your PATH?

I using "docker-machine version 0.6.0, build e27fb87"

Can someone help us ? 

Thanks 
Francisco

**Comment by nathanleclaire** [comment]
@fmontada Looks like whichever command you are attempting to run (`docker-machine create -d amazonec2 ...`) has some hidden "garbage" characters in the driver arg that are throwing off the CLI.

**Comment by nathanleclaire** [comment]
Are you copy pasting?  Might want to try typing manually if so.

**Comment by fmontada** [comment]
Hi @nathanleclaire thanks for the reply, yes I had a "space" on one of the parameter
Thanks a lot 
Francisco

**Comment by nathanleclaire** [comment]
:+1:
