### ISSUE TITLE
The help-text for the `create` command is infuriatingly wide

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [docker/machine#2132]
This is unreadable:

![](http://ell.io/i14LwN+)

It seems to be because of the `--google-scopes` and `--exoscale-security-group` flags. :P

![](http://ell.io/i16mBg+)

**Comment by ELLIOTTCABLE** [comment]
Actually, further, it'd be a lot less confusing for a newcomer if that list were broken down. I'm assuming it's automatically generated, but it'd be really nice if the *inspecific* flags were listed first, and then the individual flags for each “driver” (took me a few minutes to even find out that there *was* a `--driver` flag, in all that mess!) were listed separately / below.

**Comment by ELLIOTTCABLE** [comment]
… and further yet, if I run it according to that help-text,

    Usage: docker-machine create [OPTIONS] [arg...]

    Create a machine

    > docker-machine create --driver vmwarefusion \
         --vmwarefusion-cpu-count 2 --vmwarefusion-disk-size 10000 --vmwarefusion-memory-size 4096
    <legions of help-text>
    “You must specify a machine name.”

Nowhere in all of the output help-text is there any description of how to specify a “machine name.” I tried the rather obvious, and simply appended ‘uhh’ to the end of that string … and now I successfully have a VMware `docker-machine` named “uhh.” That should really be mentioned in the `Usage:`-string, though.

**Comment by nathanleclaire** [comment]
Please try the 0.5.0-rc4.  Now driver-specific flags only appear if you specify the driver with the `--driver` flag.

**Comment by ELLIOTTCABLE** [comment]
@nathanleclaire excellent! Always great to report a problem, only to hear it's already been fixed in HEAD. <3

**Comment by nathanleclaire** [comment]
> Does this also fix the Usage-string omission?

I think you mean the specification of "name" as an argument?  If so, then no, but that issue is slightly more problematic.  Our cli library AFAIK doesn't allow specification of named args in the example in the help text, but I'd consider a pull request that adds it to the small summary (e.g. add `Accepts a machine name as an argument`).
