### ISSUE TITLE
[Feature Request] docker-machine tree command.

### ISSUE THREAD

**Issue by kunalkushwaha** [docker/machine#2139]
A ``docker-machine tree``  command, which prints list of docker containers from each machine.
This may be useful, to visualize the docker containers, without switching to each machine.

```
$ docker-machine tree [--filters]
|-swarm-agent-01( virtualbox ) - Running 
|  |_ stoic_perlman - swarm - "/swarm manage -H 192"
|  |_suspicious_jones - busybox  "sh"
|-swarm-agent-02( digitalocean) - Stopped
|-swarm-master ( virtualbox ) - Running *
   |_ swarm-agent - swarm:latest -  "/swarm join --advert"
   |_swarm-agent-master - swarm:latest -  "/swarm manage --tlsv" 

```

**Comment by dgageot** [comment]
Maybe we should support additional commands "a la" git. If a `docker-machine-tree` binary is available in the path then `docker-machine tree` will use it.

**Comment by nathanleclaire** [comment]
Yes, I think it's far out of the scope of main Machine binary, but would make an interesting plugin (if we were to implement such a model as @dgageot mentions) or shell script.
