### ISSUE TITLE
Driver plugins cannot write to the terminal from within the driver

### ISSUE THREAD

**Issue by wenlock** [docker/machine#2145]
When writing to the new plugin architecture, and we use the libmachine log package for logging, we don't get output for normal docker-machine commands from the plugin to show up on the console.

Expected output is that stdout will receive messages from the plugin driver when the driver uses log.Info and log.Infof.    We do appear to be getting log.Error messages.

**Comment by nathanleclaire** [comment]
I've been thinking about this and I'd consider it a bug -- would be nice to expose STDOUT at least.  Generally error communication I would expect to happen through a returned `error` though.  cc @docker/machine-maintainers

**Comment by dgageot** [comment]
+1 on both.
Drivers should be able to log information/warnings.
Errors should be returned `error`s

**Comment by NeilW** [comment]
I'd add to this a general lack of a debug mechanism within driver. The debug setting in the main program isn't passed through to the plugin. 

I had to hack 'log.go' and set IsDebug to true to get a trace. That's fine for me, but not much use when I want a customer to trace the driver. 

Additionally you're using two methods of setting debug in the code: `libmachine.SetDebug(x)` and `log.IsDebug = x`. It'd be useful to settle on one or the other.

**Comment by nathanleclaire** [comment]
Hm, @NeilW plugins should show `Debug` calls by default.  Does it not work for you? Could you provide a simple example to reproduce?

> Additionally you're using two methods of setting debug in the code: libmachine.SetDebug(x) and log.IsDebug = x. It'd be useful to settle on one or the other.

Yeah, I agree it's ugly as we've been moving aggressively on shipping it -- the actual answer, I think, it that _neither_ should be used, but rather "ShowDebug" will be a configurable property on the eventual `libmachine` client struct that we move to.

**Comment by NeilW** [comment]
I've done a complete rebuild from the latest HEAD and the debug statements are coming through loud and clear now with the new debug flag on the cli. 

I'm also getting the 'Info' level log messages from the plugin.

```
(example) OUT | Creating Brightbox Server...
```
but only if the debug flag is on.

**Comment by nathanleclaire** [comment]
@NeilW Yeah, that's expected behavior with the current release, this issue is requesting that some can be viewed without `--debug`.  Stay tuned, thanks.

**Comment by wenlock** [comment]
@nathanleclaire right, --debug works like a champ, and so do error messages.   It's the log.Info and Infof messages that don't get bubbled up to docker-machine to display.

BTW, as a side-effect, today i was testing with --debug, and ran into an issue where a Debug message that was too large , caused the driver to hang, wondering if thats another issue we should track... don't have a good reproducible use case yet for it.

**Comment by nathanleclaire** [comment]
@wenlock Definitely sounds like an issue I'd like to track if you can reproduce effectively.  I do recall thinking about long lines of output as an edge case to keep an eye on.

**Comment by wenlock** [comment]
@nathanleclaire woot, thanks for getting this coded & merged so quickly, looks great!

**Comment by nathanleclaire** [comment]
@wenlock :+1:
