### ISSUE TITLE
Eliminate RawDriver from Host struct / config.json

### ISSUE THREAD

**Issue by nathanleclaire** [docker/machine#2155]
Unfortunately, I realized a bit too late that there are a couple of issues with this method. Originally it was intended to be the "preserved" state of the Driver between Machine runs, since the client side (which handles persistence to disk) doesn't know which interface is being used on the server side.

But now I have two main concerns with it having used and distributed it a while:

1. Users may not realize that the `[]byte` is only a very thin layer of obfuscation and still contains trivially decodable secrets, so I worry that they'll post `docker-machine inspect `output that contains secrets without realizing it.
2. Some users (including myself) are accustomed to being able to change the values in the `Driver` JSON object, and have them affect the result of the run program.  This is not possible with 0.5.0 today and makes things like manually rotating AWS keys in the JSON (which, while not advised, is being done) difficult to impossible.

cc @docker/machine-maintainers

**Comment by charlesg3** [comment]
Out of curiosity -- are the AWS credentials being stored in this blob?

**Comment by nathanleclaire** [comment]
@charlesg3 Yes -- it's the reason why editing the config manually to update the credentials no longer works.

**Comment by charlesg3** [comment]
Ah, bummer. Can you describe any workflow that would allow updating the creds?

**Comment by nathanleclaire** [comment]
Hm, I know this is a terrible hack (and really we should fix this since I think manually editing configs is a valid use case), but until we roll out a solution you might be able to paste your desired driver JSON into the JSON literal in this Go program (probably as a Go file running locally): http://play.golang.org/p/JTzFal8zfJ and run the code to see the what you should put in the `RawDriver` field.  That might help until we can get a proper fix.  Does it make sense?

(There's probably a more elegant way to do this in Go, but this closely mimics what's actually going on in the actual Machine code).

**Comment by nathanleclaire** [comment]
Really sorry about this, and the issue is slated to be worked on for 0.5.1, which is scheduled to be released in about two weeks' time.

**Comment by charlesg3** [comment]
I'm willing to give that a shot for now. Happy to help try to work around these issues as things progress. There's huge potential for docker-machine to help our workflow but I think we have a particular usage pattern that may not be the usual.

**Comment by nathanleclaire** [comment]
Seems not too unusual to me so I'm happy to help.  In fact in the future I'd like to make the type of secret management you're doing by hand today a little more easy to do automatically.

**Comment by charlesg3** [comment]
Yeah that'd be awesome. Basically we realized how awesome `docker-machine` is but then realized we needed an ability to pass around the environments to different machines. Since we had vault setup we rely on the security model of that to pass things around (and patch up the directories / access keys and the like). It's sort of like a "machine repository" for us.

**Comment by charlesg3** [comment]
In that go function -- I simply provide the machine name and aws secret key in that program?

**Comment by charlesg3** [comment]
(It only has the key and not the access id, I would expect it to require both)

**Comment by nathanleclaire** [comment]
@charlesg3 You should paste the whole of the `Driver` JSON that you want to convert.

**Comment by charlesg3** [comment]
This seems to be working (for now) to renew the credentials. I will keep updated of anything else that pops up.

Note that I am receiving the following errors:
```
WARNING >>> It looks like you have used an older Docker Machine binary to interact with hosts after using a 0.5.0 binary.
WARNING >>> Please be advised that doing so can result in erratic behavior due to migrated configuration settings.
```

Not sure how that is determined but things seem to be working.

**Comment by nathanleclaire** [comment]
@charlesg3 Yes due to the weird behavior the error falsely believes you have reverted to an older config schema.  It should be fine to ignore it and let us know if you run into any issues.

**Comment by bhurlow** [comment]
Hi @nathanleclaire :+1: for this. I was attempting to write some import/export tooling for docker machines and got tripped up by this RawDriver struct. Why base64 encode that at all?

**Comment by nathanleclaire** [comment]
@bhurlow It's just how `[]byte` gets `json.Marshal`ed by Golang.  It's kind of an implementation detail of the plugins' first iteration that, as mentioned, I'd like to get rid now that it's apparent it's not really needed.

**Comment by bhurlow** [comment]
ah! that makes sense thanks

**Comment by miguelpuyol** [comment]
Here is a snippet of how we did it in Python within a Docker Machine helper class:

```python
    def inspect_machine(self, node):
        command = ["docker-machine", "inspect", node]
        info = json.loads(subprocess.check_output(command))
        return info
    def list_nodes(self):
        command = ["docker-machine", "ls", "-q"]
        nodes = subprocess.check_output(command).strip().split('\n')
        return nodes
    def update_aws_keys(self, new_token=None, new_access_key=None, new_secret_access_key=None):
        for node in self.list_nodes():
            info = self.inspect_machine(node)

            if new_token and new_access_key and new_secret_access_key and info['DriverName'] == 'amazonec2':
                info['Driver']['SessionToken'] = new_token
                info['Driver']['AccessKey'] = new_access_key
                info['Driver']['SecretKey'] = new_secret_access_key
                info['RawDriver'] = base64.b64encode(json.dumps(info['Driver']))
                path = info['HostOptions']['AuthOptions']['StorePath']
                self.__dump_config(path, info)
```

**Comment by nathanleclaire** [comment]
Yeah, hopefully we can tackle this in time for 0.5.2 (a couple of weeks from now).  Pretty high in importance IMO.

**Comment by dgageot** [comment]
@nathanleclaire I gave it a shot and got lost!! I'm going to assign you

**Comment by charlesg3** [comment]
@miguelpuyol -- we've added a similar snippet to what's above to our own flow and it works for us. :+1:
