### ISSUE TITLE
Cleanup deps

### ISSUE THREAD

**Issue by dmp42** [docker/machine#2160]
* [x] remove unused dependencies
 * [x] update some dependencies
 * [x] make sure godep works again

**Comment by dgageot** [comment]
@dmp42 Is it fixed?

**Comment by dmp42** [comment]
We may want to update some of our deps.
Wdyt?

**Comment by dmp42** [comment]
@dgageot specifically worth investigating this `warning: code.google.com is shutting down; import path code.google.com/p/goauth2/compute/serviceaccount will stop working`

**Comment by dgageot** [comment]
Closed with https://github.com/docker/machine/pull/2391, https://github.com/docker/machine/pull/2394 and https://github.com/docker/machine/pull/2399
