### ISSUE TITLE
azure driver question  - Docker Machine 0.5

### ISSUE THREAD

**Issue by hsingh23** [docker/machine#2161]
![image](https://cloud.githubusercontent.com/assets/1136514/10929354/79d0504e-8280-11e5-935d-b6cefa0d57b4.png)
I noticed that a vm and a cloud service, storage account, and directory were provisioned. I only want a vm, I don't need the cloud service. Is there a way to do this?

**Comment by hsingh23** [comment]
I wonder why azure can't be like digital ocean. I want to create a vm with an image that has docker pre installed. I want to be able to control the azure instance type - and i want to see the estimated pricing per hour,day,month for that instance. I don't need cloud services, I don't need a storage account - the vm I have will do just fine. I also want to have my ssh key copied, and I want to be able to destroy the vm on a whim. 

In the current situation I'm billed for the cloud service, vm, and storage account, yea?

**Comment by squillace** [comment]
@hsingh23 Go ahead and use CoreOS or Ubuntu images, or any one of the other images that have docker preinstalled. Pricing for Cloud Services are located [here](https://azure.microsoft.com/en-us/pricing/details/cloud-services/). "Cloud Services" are the basic networking infrastructure to host your VM (storage, networking, subdomain, lb if you want more VMs inside it) and that's it. Everyone gives you one of these, but people don't call it a "thing". I'm not clear why there's no entry for your ssh key; that's a strange thing to overlook in the driver. You can destroy the VM whenever you wish, it's a VM. You could also stop it and restart it again when you wish. It's a VM.

You are paying for the compute time down to the minute, egress, and VM storage footprint, and that's it. The last two are extremely small, depending upon what you're downloading. The rule of thumb is that you're always mostly paying for compute. Hope that helps. 

I do not understand what this has to do with docker-machine, however.... What am I missing?

**Comment by ahmetalpbalkan** [comment]
@hsingh23 Hello, to answer your question, cloud service only provides a DNS name for your VM (*.cloudapp.net) and you can place multiple VMs behind that (something you can't do on DigitalOcean). Also cloud services allow you to define specific firewall and load balancing rules. You're not charged for a cloud service, it's free.

The storage account however is used to store your operating system disk. You pay by the GB space you are using. When you delete the VM, the OS disk of the VM will be deleted as well and you will not be paying for it anymore. Also, an empty storage account is free as well.

I hope this answers your questions. We're in process of creating a new Azure driver for docker-machine, it will have a lot more resources (IP addresses, NICs, virtual networks, storage accounts, availability sets, networks security groups, virtual machines, ...) and I just want you to know that we' will be doing our best to clean up billable resources after your docker-machine is deleted.

**Comment by jeanlaurent** [comment]
Closing since, I believe @ahmetalpbalkan answer the question.

Please re-open, if this is not the case.
