### ISSUE TITLE
boot2docker image cache should be indexed by version

### ISSUE THREAD

**Issue by bfirsh** [docker/machine#217]
When boot2docker is updated, `.docker/images/boot2docker.iso` won't get updated.

I also think we should put them in a path that is machine-specific, so as to avoid polluting the ~/.docker namespace. `~/.docker/machine/something`?

**Comment by nathanleclaire** [comment]
> When boot2docker is updated, .docker/images/boot2docker.iso won't get updated.

We could probably introduce a check to the GH API (releases) on `machine create -d virtualbox`.  `boot2docker-cli` has some similar code for `upgrade` that we could probably cop (https://github.com/boot2docker/boot2docker-cli/blob/master/util.go#L105).

> I also think we should put them in a path that is machine-specific, so as to avoid polluting the `~/.docker` namespace. `~/.docker/machine/something`?

SGTM.  Should be just a few lines change.

**Comment by SvenDowideit** [comment]
The b2d iso's also contain the version string as one of the iso labels

**Comment by ehazlett** [comment]
This is going to be even more important now that fusion support is merged.  We could get into a potential issue where a fusion machine is created and then the virtualbox driver uses the fusion b2d iso.  We should probably also include the driver as part of the versioning.

**Comment by ehazlett** [comment]
Removing from the milestone as we are using standard TLS now so this is not as urgent.

**Comment by bfirsh** [comment]
@ehazlett Why is this less urgent because of TLS? I encountered this bug today where Machine was creating 1.4.1 Machines, even though 1.5 has been released.

There is also the more urgent issue that Machine is polluting ~/.docker. We can't reverse that! #580

**Comment by ehazlett** [comment]
@bfirsh because before we were using the same ISO for both vmware and b2d.  I agree now that we have varying b2d ISOs in use we need to do this.

Yes, I'm aware of #580.  That will be fixed before release.

**Comment by sthulb** [comment]
Can we define the behaviour?

I propose the following:
 1. ISOs are stored in `~/.docker/machine/images`
 1.  stored as <version>-<driver>.iso (this is because VMware's custom ISO).
 1. The latest version is symlinked as: latest-<driver>.iso
 1. We check for a new release every time we create a local machine.
   1. Download if required.
   1. Update latest iso symlink

**Comment by sthulb** [comment]
@ehazlett @bfirsh ^

**Comment by ehazlett** [comment]
@sthulb i think the markdown parsing is eating your vars

**Comment by sthulb** [comment]
Better :)

**Comment by ehazlett** [comment]
@sthulb what happens when the machine is created?  I think we should also prefix them with `b2d` or something in case we change the mini OS in the future.

**Comment by sthulb** [comment]
We resolve the symlink and use the "real" path in the driver store.

**Comment by ehazlett** [comment]
@sthulb can you add a step 5 with that?  I want to make sure we don't stomp on any existing machine.

**Comment by sthulb** [comment]
Done!

**Comment by ehazlett** [comment]
@sthulb sounds good to me -- thx!

**Comment by SvenDowideit** [comment]
+1 to full versioning of the iso files - though checking every time i make a vm may be annoying when I'm offline, it will likely solve a tonne of support pain that we still have in b2d.

**Comment by CWSpear** [comment]
Is there any progress on this? I have a client using an version of Artifactory that doesn't work with Docker `1.8` (and IT is refusing to update for all sorts of Enterprise reasons) and so I'd *like* to create two Docker Machines, one with Docker `1.7.1` and one with the latest for other clients and personal projects, but since they both share the same `boot2docker.iso`, I'm not sure it's currently possible.

Perhaps a separate issue, but it'd be nice to specify a version of `boot2docker` (and thus Docker itself) for these sorts of cases (see https://github.com/docker/docker/issues/15538 for more about such a case).

**Comment by nathanleclaire** [comment]
@CWSpear If I'm not mistaken, the `--virtualbox-boot2docker-url` flag for `create` should cover your use case?  You could do a create like this:

```
$ docker-machine create -d virtualbox \
    --virtualbox-boot2docker-url https://github.com/boot2docker/boot2docker/releases/download/v1.7.1/boot2docker.iso \
    oldermcn
...
```

And keep that VM sitting side by side with a "latest" VM that you upgrade regularly.  Naturally you shouldn't `upgrade` the `oldermcn` VM.

**Comment by CWSpear** [comment]
@nathanleclaire you are not mistaken! That does help, thank you. 

Less critical, but it'd be nice if the docker version was displayed like in the `docker-machine ls` or something. I can always just put it in the name, so it's not a big deal (i.e., in my case, `vbox-[client]` to remind me its their box with the old version of `docker`, etc).

Anyway, thanks for the very helpful reply =)

**Comment by nathanleclaire** [comment]
> Less critical, but it'd be nice if the docker version was displayed like in the docker-machine ls or something.

Ah yeah, I think we definitely have a need for a more verbose `ls` or something which would display information like this.

**Comment by bfirsh** [comment]
Just heard that @alvinr tripped up on this issue, then realised I was tripping up on it on too.

When I do `docker-machine create`, I kinda expect it to fetch the latest version of Boot2Docker. I got stuck on 1.8.0 without really realising it because of the cache.

**Comment by nathanleclaire** [comment]
I'm going to move the discussion on this to: https://github.com/docker/machine/issues/1790 which is a bit more focused / up to date.
