### ISSUE TITLE
make validate fail with missing dependency

### ISSUE THREAD

**Issue by jeanlaurent** [docker/machine#2170]
```
> make validate
0 adds, 0 deletions; nothing to validate! :)
mk/validate.mk:21: *** Please install golint: go get -u github.com/golang/lint/golint.  Stop.
```

**Comment by dgageot** [comment]
@jeanlaurent Then you should install golint ;-)

**Comment by jeanlaurent** [comment]
@dgageot couldn't find this myself :smile: , I quickly noted this not to forget about it.

This has to be handled automagically or noted in the CONTRIBUTING.md

**Comment by nathanleclaire** [comment]
> This has to be handled automagically

No

> noted in the CONTRIBUTING.md

Yes
