### ISSUE TITLE
EC2 issue with version .5 amazonec2-private-address-only

### ISSUE THREAD

**Issue by jeffellin** [docker/machine#2171]
I am having an issue with the new version of docker machine.

Running the following command

docker-machine --debug create --driver amazonec2 --amazonec2-subnet-id subnet-24abec0f --amazonec2-zone b --amazonec2-private-address-only swarm-demo2

the result is 
Error: No machine name specified

If I remove amazonec2-private-address-only option, it works, but I can't connect to it since the machine isn't accessible using the public ip.

Running in debug shows this

(swarm-demo2) Calling RpcServerDriver.GetSSHPort
(swarm-demo2) Calling RpcServerDriver.GetSSHKeyPath
(swarm-demo2) Calling RpcServerDriver.GetSSHUsername
Using SSH client type: external
About to run SSH command:
exit 0
SSH cmd err, output: exit status 255: 
Error getting ssh command 'exit 0' : Something went wrong running an SSH command!
command : exit 0
err     : exit status 255
output  :

**Comment by aidanbon** [comment]
Encountered the same problem with 0.5.0 release. Specified with --amazonec2-private-address-only=true but the debug output shows "Using SSH client type: external"  and therefore failed with SSH cmd err.

In the AWS EC2 panel. noticed the corresponding EC2 instance did successfully created, but with a public IP which it should not.

A previous version (forgot the version #) of docker-machine works correctly with this flag.

**Comment by jeffellin** [comment]
Glad to know it isn't just me.  I might try and dive into the source and see if I can figure it out.

**Comment by jeffellin** [comment]
The AWS command to create the instance is sending

    "NetworkInterface.0.AssociatePublicIpAddress": [
    (test3) DBG |         "1"
    (test3) DBG |     ],

Not sure why the command line isn't being parsed properly.

**Comment by jeffellin** [comment]
Some further info,   Seeing the folliowing in the logs.
      
    OUT | WARNING >>> Type assertion did not go smoothly to bool for key amazonec2-private-address-only

Looking at the code, it seems that the flag amazonec2-private-address-only is a string, and it should probably be a bool.  I am building the latest release now with this change to see if that fixes the problem.

**Comment by jeffellin** [comment]
I can confirm that the following fixes the issue.  I can do a PR,  this really should have an integration test which I can certainly do but I won't be able to get to it for a few days.   

    --- a/drivers/amazonec2/amazonec2.go
    +++ b/drivers/amazonec2/amazonec2.go
    @@ -150,7 +150,7 @@ func (d *Driver) GetCreateFlags() []mcnflag.Flag {
    			Usage: "AWS spot instance bid price (in dollar)",
    			Value: defaultSpotPrice,
    		},
       -		mcnflag.StringFlag{
       +		mcnflag.BoolFlag{
     			Name:  "amazonec2-private-address-only",
 	    		Usage: "Only use a private IP address",
 	    	},
    --

**Comment by dgageot** [comment]
@jeffellin Thanks a lot for the investigation!
I'm going to shoot a PR with fix and test

**Comment by dgageot** [comment]
@docker/machine-maintainers PTAL

**Comment by jeffellin** [comment]
Thanks @dgageot for the quick fix.  Any idea when .5.1 will be ?

**Comment by nathanleclaire** [comment]
@jeffellin About a week and a half

**Comment by jeffellin** [comment]
Should this be in docker-toolbox 1.90d?  The release notes says its now at docker-machine .51 but It still seems to be at .50

docker-machine version 0.5.0 (04cfa58)

**Comment by jeanlaurent** [comment]
@jeffellin This is a [glitch](https://github.com/docker/toolbox/issues/307 ) with toolbox release note 1.9.0d.

You'll have to install docker-machine 0.5.1 by hand from the [release](https://github.com/docker/machine/releases/tag/v0.5.1) page for now on.

sorry about that.
