### ISSUE TITLE
Error creating machine: Error in driver during machine creation: Unable to upload on datastore Datacenter due to Error

### ISSUE THREAD

**Issue by ThatsNinja** [docker/machine#2176]
Full error text:
```
Error creating machine: Error in driver during machine creation: Unable to upload on datastore <vmwarevsphere-datacenter> due to Error: Put https://<host>/folder/<machine_name>/boot2docker.iso?dcPath=ha-datacenter&dsName=<vmwarevsphere-datastore>: dial tcp <host_ip>:443: getsockopt: connection refused
```
This the result of this command:
```
docker-machine create \
  --driver vmwarevsphere \
  --vmwarevsphere-cpu-count 8 \
  --vmwarevsphere-memory-size 16384 \
  --vmwarevsphere-vcenter <vcenter_ip> \
  --vmwarevsphere-datacenter <vmwarevsphere-datacenter> \
  --vmwarevsphere-disk-size 40960 \
  --vmwarevsphere-username <user> \
  --vmwarevsphere-password "<password>" \
  --vmwarevsphere-network <vmwarevsphere-network> \
  --vmwarevsphere-datastore <vmwarevsphere-datastore> \
  --vmwarevsphere-pool <vmwarevsphere-pool> \
  <machine_name>
```
There are two issues in the above error output:
1. `[...] Unable to upload on datastore <vmwarevsphere-datacenter> due to Error [...]`: Here, the name specified for `--vmwarevsphere-datacenter` is being returned as the datastore name;
2. `[...] Put https://<host>/folder/<machine_name>/boot2docker.iso?dcPath=ha-datacenter&dsName=<vmwarevsphere-datastore> [...]`: In the URL parameters being printed here, the specified `--vmwarevsphere-datacenter` has been replaced by `ha-datacenter`.

I can't imagine that this is simply broken for everyone who's attempted this, or there would be open issues. In short, are these merely typos, and I need to get up with my VMWare folks, or is this an issue with the vmwarevsphere driver?

**Comment by nathanleclaire** [comment]
cc @frapposelli

**Comment by frapposelli** [comment]
@ThatsNinja seems like you don't have access to your vCenter server, you get `connection refused` when attempting to connect to it.

**Comment by ThatsNinja** [comment]
@frapposelli Thanks for your reply! I'd suspected as much. I've got a ticket open with my VMWare support team to check things on their end. I'll update this issue with the final disposition if the problem is resolved on my end.

**Comment by frapposelli** [comment]
@ThatsNinja did you sort this out?

**Comment by ThatsNinja** [comment]
@frapposelli Somewhat, yes. Put simply, the error being reported was correct inasmuch as our DNS configuration was bad, and I was being directed to the wrong IP.

Still, I initially thought this might be a driver issue because the output in the error didn't match my input parameters. Fixing the error output to properly display could help prevent confusion for others in the future.

**Comment by frapposelli** [comment]
@ThatsNinja well, `connection refused` is a pretty straightforward message, also the error message is being rewritten in a more succinct way with the driver rewrite.

**Comment by ThatsNinja** [comment]
Yes, the `connection refused` error was correct. As for the output I was referring to, please see:

> There are two issues in the above error output:
> 1. [...] Unable to upload on datastore <vmwarevsphere-datacenter> due to Error [...]: Here, the name specified for --vmwarevsphere-datacenter is being returned as the datastore name;
> 2. [...] Put https://<host>/folder/<machine_name>/boot2docker.iso?dcPath=ha-datacenter&dsName=<vmwarevsphere-datastore> [...]: In the URL parameters being printed here, the specified --vmwarevsphere-datacenter has been replaced by ha-datacenter.

**Comment by frapposelli** [comment]
yes, the error you see is what `govc` reports, in the vsphere driver rewrite we're using govmomi directly so we can manipulate the message in a better way.

**Comment by ThatsNinja** [comment]
Cheers! Thanks, @frapposelli!
