### ISSUE TITLE
machine does not exist error

### ISSUE THREAD

**Issue by peco8** [docker/machine#2182]
Whenever I hit `docker-macihne active`, following errors come out.

<img width="553" alt="screen shot 2015-11-05 at 17 24 20" src="https://cloud.githubusercontent.com/assets/4458427/10963252/417f3cb0-83e2-11e5-9477-914bddddbd61.png">

Can anyone please suggest what might be wrong? Has anyone run into this before?

**Comment by dgageot** [comment]
Hi @peco8, thanks for the report. Can you tell which version of `docker-machine` you are using. If it's not the latest 0.5.0, can you upgrade and test?
Can you provide the output of `docker-machine ls`?
Can you provide the output of `ls ~/.docker/machine/machines`?

**Comment by peco8** [comment]
hi @dgageot, sorry for the late reply.

I use `docker-machine` : version 0.4.1(e2c88d6) 

The output of `docker-machine ls` is
<img width="596" alt="screen shot 2015-11-06 at 09 36 18" src="https://cloud.githubusercontent.com/assets/4458427/10986057/f10c5f00-8469-11e5-97a5-98472f2c5a46.png">

The output of `ls ~/.docker/machine/machines` outputs
<img width="532" alt="screen shot 2015-11-06 at 09 39 24" src="https://cloud.githubusercontent.com/assets/4458427/10986090/4ab00b92-846a-11e5-91e7-d282beefdd7e.png">

Thanks,

**Comment by nathanleclaire** [comment]
Please try with 0.5.0 and let us know if the problem persists.  Please ensure that `default` is a machine existing in the VirtualBox GUI.  If it isn't, trying `docker-machine rm`ing it and re-creating it.
