### ISSUE TITLE
Can not connect to the docker machine without driver

### ISSUE THREAD

**Issue by eyakcn** [docker/machine#2183]
I created a docker machine by running:

$ docker-machine create --url tcp://xxx.xxxx:2376 serve

It was created before I upgrade docker-machine to 0.5.0.

But after I update to 0.5.0, it shows error message when I try to connect to it by:

$ eval "$(docker-machine env serve)"

Error message is following:

Error running connection boilerplate: serve is not running. Please start it in order to use the connection settings.

But actually you can not start a docker machine without driver... WTF...

$ docker-machine start serve
hosts without a driver cannot be started

**Comment by melnikk** [comment]
+1
I've got same issue after upgrading to docker-machine v0.5.0.

**Comment by dmp42** [comment]
@nathanleclaire wdyt?

**Comment by nathanleclaire** [comment]
I think it's generally presumed that instances created with `none` are guaranteed to be running, so maybe `GetState` for that driver should return `state.Running`.

**Comment by nathanleclaire** [comment]
I'll submit a PR for that.

**Comment by eyakcn** [comment]
@nathanleclaire Great! Thank you!

**Comment by nathanleclaire** [comment]
@eyakcn Please try master if you can and make sure to verify that it solves your issues.  Thanks!

**Comment by eyakcn** [comment]
@nathanleclaire I tried the master branch, the commit hash is 93376828af9aa9bc7734fcf0440e2baedf3aca4f

And then I tried to build the binary by:

$ export USE_CONTAINER=true
$ TARGET_OS=darwin TARGET_ARCH="amd64" make cross

But the binary built in this way still cannot connect to the machine created without a driver.

**Comment by nathanleclaire** [comment]
@eyakcn Did you copy the compiled binaries to your `PATH`?  Does `docker-machine ls` report `none` machine state as `Running` after creating e.g. `docker-machine create --driver none --url foo.bar foobar`?  If that is true and it still isn't working, please let us know your latest symptoms.

**Comment by eyakcn** [comment]
@nathanleclaire It's really strange, after I updated the master branch, and run 

$ TARGET_OS=darwin TARGET_ARCH="amd64" make cross

I can not find the build output of bin/

**Comment by dmp42** [comment]
@eyakcn I believe Monsieur @dgageot broke the build here :) https://github.com/docker/machine/pull/2239/files#diff-47b96c240fe19eb8a0c14dc47e9f4c38R33

**Comment by eyakcn** [comment]
@dmp42 Thank you :) 
I will try again after it's fixed
