### ISSUE TITLE
Docker volumes

### ISSUE THREAD

**Issue by MartinsThiago** [docker/machine#2188]
Since boot2docker we're having some problems for sharing folders between virtual machine and host

To be honest I'am really looking forward `docker-compose`, it's already doing really well cross-platform once I can run `docker-compose up` even on Windows, and sure... it does what we expect, but setting up shared folder manually is such a pain

*The same occurs with docker client it self... it's doing really well, but we can't expect to get volumes working if we are on Windows/Mac*

What's the way to go for providing the same usability cross-platforms? Actually I thought about forking `docker-compose` to implement some logic on Windows for managing shared folders in virtual box

previous link https://github.com/docker/compose/issues/2328#issuecomment-154139341

**Comment by nathanleclaire** [comment]
Currently `C:\Users\You` or `/Users` gets auto-mounted into the VM at `/c/users` and  `/Users` respectively.  I agree the workflow is not perfect, moving forward my preference would be to introduce some sort of `docker-machine share` command (https://github.com/docker/machine/issues/179) or first-class share/volume object which is created and manipulated by Docker Compose.
