### ISSUE TITLE
Driver integration tests always exit with 1

### ISSUE THREAD

**Issue by legal90** [docker/machine#2190]
I've reproduced this with built-in `virtualbox` driver:

```
$ DRIVER=virtualbox test/integration/run-bats.sh test/integration/drivers/virtualbox/bad-create-iso.bats
=> test/integration/drivers/virtualbox/bad-create-iso.bats
 ✓ virtualbox: Should not allow machine creation with bad ISO

1 test, 0 failures

$ echo $?
1
```

## Details
It is caused by this block in `run-bats.sh`: https://github.com/docker/machine/blob/d07d443466e2d4a00cbffa438335fc647f2e2d74/test/integration/run-bats.sh#L82-L87

Seems like it is expected that all `docker-machine*` processes will be terminated _before_ reaching this block. Otherwise, they will be killed by `pkill` and global EXIT_STATUS will be set to 1.

But in the example displayed above, `docker-machine-driver-virtualbox` processes are always running, when this block is reached. 

## Debug
You can make sure by adding a "ps" print:
```bash
# ...
set +e
ps ax | grep [d]ocker-machine
pkill docker-machine
if [[ $? -eq 0 ]]; then
    EXIT_STATUS=1
fi
set -e
# ...
```

Result:
```
$ DRIVER=virtualbox test/integration/run-bats.sh test/integration/drivers/virtualbox/bad-create-iso.bats
=> test/integration/drivers/virtualbox/bad-create-iso.bats
 ✓ virtualbox: Should not allow machine creation with bad ISO

1 test, 0 failures

85867 s000  S+     0:00.01 /Users/legal/go/src/github.com/docker/machine/test/integration/../../bin/docker-machine-driver-virtualbox
85870 s000  S+     0:00.01 /Users/legal/go/src/github.com/docker/machine/test/integration/../../bin/docker-machine-driver-virtualbox
85872 s000  S+     0:00.01 /Users/legal/go/src/github.com/docker/machine/test/integration/../../bin/docker-machine-driver-virtualbox
```

P.s. I've also noticed that if we remove this block, then driver processes will be terminated automatically in ~1 second after the `run-bats.sh` script run.

cc: @nathanleclaire

**Comment by nathanleclaire** [comment]
Really we should probably just take that block out.  It was a decent effort, but I think our current cleanup model (self-destruct if a server hasn't heard from clients past a given heartbeat interval) is pretty safe.  That said, I'm open to ideas on how to test to make sure we don't accidentally start leaking processes at some point in the future.

**Comment by nathanleclaire** [comment]
We've removed it.  Thanks for the diligence @legal90.

**Comment by legal90** [comment]
@nathanleclaire You're welcome :) 
I've also removed it in `docker-machine-parallels`
