### ISSUE TITLE
`docker-machine ssh` won't exit if ports are forwarded and accessed

### ISSUE THREAD

**Issue by skalfyfan** [docker/machine#2194]
Not quite sure if this an issue as I just upgraded to docker-machine 0.5.0 and I'm happy to see that ssh port-forwarding is working now through:

```bash
docker-machine ssh <machine> -L 8080:localhost:80
```
One thing I've noticed though is that when I *exit* out it is taking an incredibly long amount of time to exit my ssh connection to the vm machine. Is this an issue or am I missing something? 

<img width="603" alt="docker-machine050-port-forward-exit" src="https://cloud.githubusercontent.com/assets/4172830/10984735/8dacbc6e-83e9-11e5-9bc7-112b8cc9ba9a.png">

I've noticed that if I ssh and forward ports, and then *exit* right away (without opening my browser to http://localhost:8080), then my ssh connection closes immediately. If I access my browser at http://localhost:8080 a couple times first - then I get this issue of an incredibly long amount of time closing.

Again, not sure if it's an issue, but if not then an explanation would be fantastic!

Thanks!

**Comment by nathanleclaire** [comment]
Looks like it's normal behavior of `ssh` binary: http://serverfault.com/questions/20713/why-does-logging-out-of-an-ssh-session-hang-when-using-port-forwarding

That issue indicates you need to terminate connections forwarded over SSH before the SSH process will exit.  I'll usually just hit CTRL+C though.

**Comment by skalfyfan** [comment]
@nathanleclaire thanks for the direct explanation link. I suspected it had something to do with existing ports being accessed and still being open.
