### ISSUE TITLE
Add a vmwarefusion driver flag to disable the mounting of the /Users directory

### ISSUE THREAD

**Issue by jviide** [docker/machine#2196]
It would be great to be able to disable the automatic mounting of the /Users directory inside the VMWare Fusion VM.

Maybe this could be done along the lines of pull request #1622 that adds the flag --virtualbox-no-share. The Parallels driver also has a similar --parallels-no-share (see https://github.com/Parallels/docker-machine-parallels/pull/1). Therefore it would make sense to name the flag --vmwarefusion-no-share.

**Comment by jviide** [comment]
Opened pull request #2197 to have a go at implementing this.

**Comment by dgageot** [comment]
Closed with https://github.com/docker/machine/pull/2197
