### ISSUE TITLE
docker-machine 0.5.0 env -u fails

### ISSUE THREAD

**Issue by jonaskello** [docker/machine#2204]
I get this when I try to unset the selected machine:

$ docker-machine -D env -u
Docker Machine Version: 0.5.0 (04cfa58)
Error trying to get host "": Loading host from store failed: open    /home/xxx/.docker/machine/machines/config.json: no such file or directory

Tried to create an empty config.json file at that location but that does not work either. Is there a work around for this problem?

**Comment by dgageot** [comment]
@jonaskello That's a bug! And I don't think there's a workaround.
Shceduling the fix for 0.5.1

**Comment by dgageot** [comment]
`docker-machine env -u` fails and it shouldn't
`docker-machine env -u machine_name` should fail and it isn't

**Comment by dgageot** [comment]
@jeanlaurent I let you take a look. There should really be at least an integration test on this one

**Comment by Ducatel** [comment]
I can also reproduce this issue. [I have created a thread about it in the docker forum](https://forums.docker.com/t/impossible-to-go-back-on-local-host/4259)

**Comment by pdalpra** [comment]
Actually, there is a workaround: I managed to get it work by adding the `--shell` option.

**Comment by nathanleclaire** [comment]
The fix has been merged to master so it should be out in the 0.5.1 release next week.  Thanks everyone!

**Comment by pdalpra** [comment]
@nathanleclaire sure thing, I mentioned it in case anybody really need to unset env vars in the coming days :P

**Comment by jonaskello** [comment]
@pdalpra Could you give the exact command-line you used? I could not use this:

```
docker-machine --version
docker-machine version 0.5.0 (04cfa58)
$ docker-machine env -u --shell bash
Error trying to get host "": Loading host from store failed: open /Users/JonKel/.docker/machine/machines/config.json: no such file or directory
```

**Comment by pdalpra** [comment]
@jonaskello I used `docker-machine env --shell -u <sandbox_name>`.
Didn't try to unset the currently selected machine though.
