### ISSUE TITLE
Use samalba/dockerclient instead of templating docker run commands for Swarm

### ISSUE THREAD

**Issue by nathanleclaire** [docker/machine#2209]
See: https://github.com/docker/machine/pull/2202#issuecomment-154512024

We used a template which was pretty effective for getting started to run Swarm containers but, as noted in the linked issue, it is not compiler-safe and also is slightly hacky.  Using Sam's Docker client library would be preferable.

**Comment by dgageot** [comment]
closed with https://github.com/docker/machine/pull/2521
