### ISSUE TITLE
Machine creation hangs

### ISSUE THREAD

**Issue by ain** [docker/machine#2211]
```
$ docker-machine create ruby --driver=virtualbox
Running pre-create checks...
Creating machine...
```
hangs indefinitely.

```
$ docker-machine --version
docker-machine version 0.5.0 (04cfa58)
$ docker version
Client:
 Version:      1.9.0
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   76d6bc9
 Built:        Tue Nov  3 19:20:09 UTC 2015
 OS/Arch:      darwin/amd64
```

**Comment by ain** [comment]
`docker-machine create -d virtualbox ruby` works, but takes way longer than in `1.8.3` for instance.

**Comment by nathanleclaire** [comment]
@ain Feel free to post the `docker-machine --debug create` logs so we can take a look at what might be causing the slowness.

**Comment by ain** [comment]
Right now it feels like a broadband problem. Will retry on office connection on Monday.

**Comment by nathanleclaire** [comment]
The boot2docker ISO, most likely.
