### ISSUE TITLE
Node discovery for Docker Machine

### ISSUE THREAD

**Issue by arun-gupta** [docker/machine#2218]
`docker daemon --help | grep cluster` allows host to set the cluster store information for Docker daemon to Consul or something else.

In order to achieve similar behavior using Docker Machine, do I need to use the following command?

`docker-machine create -d=virtualbox --engine-opt --cluster-advertise=value --engine-opt --cluster-store=value test`

Is that the correct behavior or there is a better way?

**Comment by nathanleclaire** [comment]
That's pretty close.  Don't need hyphens on the `--cluster-advertise` key-val opt though (and I think it will throw off flag parsing):

```console
$ docker-machine create -d virtualbox \
    --engine-opt cluster-advertise=value \
    --engine-opt cluster-store=value \
    test
```

Indeed, something like `--engine-opt cluster-advertise="eth0:2376"` is being used for multihost networking demos all over the place now.
