### ISSUE TITLE
OS X Outgoing Networking from Containers

### ISSUE THREAD

**Issue by Crispy1975** [docker/machine#2226]
This is something of a sporadic issue over different laptops and machines. We can run Docker Machine on one laptop and have it run our multi-container environment no problem, then on another there is no outgoing network connectivity from containers at all. The OS is the same (El Capitan) and as are versions of Docker Machine and Virtualbox. We have tried removing unused ethernet interfaces, killing off the Virtualbox daemon to make sure everything is started from fresh, but no luck on some systems, yet others work perfectly.

Is this possibly related to a number of other OS X networking issues or are we missing something simple?

This is running the latest `v1.90b` of the Docker Toolbox. Any help appreciated.

**Comment by dmp42** [comment]
cc @docker/machine-maintainers

**Comment by nathanleclaire** [comment]
Hm very odd behavior.  Please post the output of `docker-machine --debug create -d virtualbox foo` and the VirtualBox logs from that instance when you get a chance.  Is it all network connectivity or just things that go through DNS?  Does restarting the VM fix it?

**Comment by Crispy1975** [comment]
Will post logs tomorrow as it's late here now...

The VM has full external connectivity, can ping hosts, download Docker images no problem. But when building an image that requires a download - apt-get for example - the operation fails on certain machines.

**Comment by nathanleclaire** [comment]
So it's just containers which lack network connectivity, eh?  Please make sure to include the daemon logs (`/var/log/docker.log` in the VM) and configuration `/var/lib/boot2docker/profile`).

Please also check if `ping` works inside containers and when pointed directly at an IP, e.g.:

```console
docker@default:~$ docker run busybox ping 8.8.8.8
PING 8.8.8.8 (8.8.8.8): 56 data bytes
64 bytes from 8.8.8.8: seq=0 ttl=61 time=7.014 ms
64 bytes from 8.8.8.8: seq=1 ttl=61 time=7.439 ms
64 bytes from 8.8.8.8: seq=2 ttl=61 time=7.013 ms
^C
--- 8.8.8.8 ping statistics ---
3 packets transmitted, 3 packets received, 0% packet loss
round-trip min/avg/max = 7.013/7.155/7.439 ms
```

If hitting IP addresses directly works, I suspect our old friend DNS resolution.  In that case, try changing `/etc/resolv.conf` to point to `8.8.8.8` (or your company's whitelisted DNS servers) and see if a container can properly resolve names in that case.

**Comment by iammerrick** [comment]
Yup seeing this same thing. Only way to fix for me is to docker-machine rm and docker-machine create and do the exact same build

**Comment by iammerrick** [comment]
What's odd is it'll work after the first build or docker-compose up but it breaks with subsequent builds or ups...

**Comment by iammerrick** [comment]
For me it seems to be a DNS resolution problem.

**Comment by Crispy1975** [comment]
We are still running some tests locally, hoping the identify the issue and then report back...

**Comment by iammerrick** [comment]
It appears this happens after doing a `docker run container <command>` after doing a `docker-compose up`

**Comment by Crispy1975** [comment]
Ok, tentatively I believe our issues was in fact due to the Docker bridge interface (docker0) being assigned an IP different from the most common `172.16.42.1`. We're using SkyDock and SkyDNS containers to have service discovery between the containers using DNS, then using `8.8.8.8` for any lookups that do not match locally set containers. We have no altered our set-up to dynamically detect the `docker0` interface IP and everything seems to work ok on one machine that was having issues.

I can only surmise that the machines that worked were down to luck in having the correct `docker0` interface IP address assigned. We will run our updates on the other machines affected and report back to make sure all is well. :)

**Comment by nathanleclaire** [comment]
Thanks for the update @Crispy1975

**Comment by Crispy1975** [comment]
@nathanleclaire I am happy to close this issue as we now have everything working. I suspect that it might be similar for @iammerrick also? But will leave him to respond on that.

**Comment by dgageot** [comment]
@iammerrick I'm going to close the issue. Feel free to reopen if you still face this issue
