### ISSUE TITLE
Windows + Bash: Issue with `docker-machine env --shell bash xxx`

### ISSUE THREAD

**Issue by dsifford** [docker/machine#2230]
I apologize if this issue has already been created (I looked briefly for it).

### My setup
- Windows 10 Pro, Beta (fast build)
- Docker Toolbox (latest)
- Shell: bash

### Here's what's happening:

```bash
docker-machine env --shell bash dev
export DOCKER_TLS_VERIFY="1"
export DOCKER_HOST="tcp://111.111.11.111:1111"
export DOCKER_CERT_PATH="C:\Users\dsifford\.docker\machine\machines\dev"
export DOCKER_MACHINE_NAME="dev"
# Run this command to configure your shell:
# eval "$(C:\Program Files\Docker Toolbox\docker-machine.exe env --shell bash dev)"
```

### The issue
Running `eval` on a filename containing spaces will not work unless properly formatted.

```bash
eval "$(C:/Program Files/Docker Toolbox/docker-machine.exe env --shell bash dev)"
bash: C:/Program: No such file or directory
```

### The solution
Format the above bash `eval` script like this...

```bash
eval "$(C:/Program\ Files/Docker\ Toolbox/docker-machine.exe env --shell bash dev)"
```
1. Convert the backslashes into forward slashes
2. Use backslashes before every space in the file path

Cheers!

**Comment by jeanlaurent** [comment]
@dsifford 

Through which environment you're using to run bash ?
Cygwin, MINGW, MSYS ?

**Comment by dsifford** [comment]
@jeanlaurent I believe at that time I was running MSYS? Not totally sure because I ran through all three of those until finally settling upon cygwin.

**Comment by dgageot** [comment]
@dsifford Can the ticket be closed?

**Comment by dsifford** [comment]
Yes. I'm no longer on Windows.

**Comment by franzbecker** [comment]
I tried this with Cygwin just now and got the following:
```
$ docker-machine env --shell bash --no-proxy dev
export DOCKER_TLS_VERIFY="1"
export DOCKER_HOST="tcp://192.168.99.100:2376"
export DOCKER_CERT_PATH="C:\Users\xxx\.docker\machine\machines\dev"
export DOCKER_MACHINE_NAME="dev"
export NO_PROXY="192.168.99.100"
# Run this command to configure your shell:
# eval $("C:\Program Files\Docker Toolbox\docker-machine.exe" env --shell bash --no-proxy dev)
```

```
$ eval $("C:\Program Files\Docker Toolbox\docker-machine.exe" env --shell bash --no-proxy dev)
-bash: C:\Program Files\Docker Toolbox\docker-machine.exe: Command not found.
```

With the above solution of dsifford it worked fine.

**Comment by albert616** [comment]
eval $("/cygdrive/c/Program Files/Docker Toolbox/docker-machine.exe" env universal)
