### ISSUE TITLE
Azure Driver: cannot create vm; fails with isavailable internal error (yosemite/ubuntu 14.04 LTS)

### ISSUE THREAD

**Issue by squillace** [docker/machine#2236]
I've tried to figure this out, but I've had bad luck on two machines now, so filing the issue to make sure I'm doing something incorrectly.

On mac, Docker Tools installation fresh. d-m verison 0.5.0 (04cfa58) on both machines.
- `docker-machine create --driver virtualbox` works perfectly. 
- `docker-machine create --driver azure` fails with an internal error on both the mac and the ubuntu. 

Mac:

>
☁  .docker  docker-machine -D create -d azure --azure-subscription-id=f7f09258-xxxx-xxxx-xxxx-xxxxxxxxxxxx --azure-subscription-cert=cert.pem --azure-location="Central US" --azure-image=2b171e93f07c4903bcad35bda10acf22__CoreOS-Stable-766.5.0  yodocker
Docker Machine Version: 0.5.0 (04cfa58)
Found binary path at /usr/local/bin/docker-machine-driver-azure
Launching plugin server for driver azure
Plugin server listening at address 127.0.0.1:56600
() Calling RpcServerDriver.GetVersion
Using API Version 1
() Calling RpcServerDriver.SetConfigRaw
() Calling RpcServerDriver.GetMachineName
(flag-lookup) Calling RpcServerDriver.GetCreateFlags
Making call to close connection to plugin binary
Making call to close driver server
(flag-lookup) Calling RpcServerDriver.Close
Successfully made call to close driver server
Found binary path at /usr/local/bin/docker-machine-driver-azure
Launching plugin server for driver azure
Plugin server listening at address 127.0.0.1:56605
() Calling RpcServerDriver.GetVersion
Using API Version 1
() Calling RpcServerDriver.SetConfigRaw
() Calling RpcServerDriver.GetMachineName
(yodocker) Calling RpcServerDriver.GetMachineName
(yodocker) Calling RpcServerDriver.DriverName
(yodocker) Calling RpcServerDriver.GetCreateFlags
(yodocker) Calling RpcServerDriver.SetConfigFromFlags
Running pre-create checks...
(yodocker) Calling RpcServerDriver.PreCreateCheck
Error creating machine: Error with pre-create check: Get https://management.core.windows.net/f7f09258-xxxx-xxxx-xxxx-xxxxxxxxx/services/hostedservices/operations/isavailable/yodocker: local error: internal error
>

And the ubuntu is identical:

>
ralph@local:~ 
 $ docker-machine -D create \                                                                                                           1
-d azure \
--azure-subscription-id="f7f09258-xxxx-xxxx-xxxx-xxxxxxxxxxxxx" \
--azure-subscription-cert="/home/ralph/.ssh/myCert.pem" \
yodocker
Docker Machine Version: 0.5.0 (04cfa58)
Found binary path at /usr/local/bin/docker-machine-driver-azure
Launching plugin server for driver azure
Plugin server listening at address 127.0.0.1:41644
() Calling RpcServerDriver.GetVersion
Using API Version 1
() Calling RpcServerDriver.SetConfigRaw
() Calling RpcServerDriver.GetMachineName
(flag-lookup) Calling RpcServerDriver.GetCreateFlags
Making call to close connection to plugin binary
Making call to close driver server
(flag-lookup) Calling RpcServerDriver.Close
Successfully made call to close driver server
Found binary path at /usr/local/bin/docker-machine-driver-azure
Launching plugin server for driver azure
Plugin server listening at address 127.0.0.1:46952
() Calling RpcServerDriver.GetVersion
Using API Version 1
() Calling RpcServerDriver.SetConfigRaw
() Calling RpcServerDriver.GetMachineName
(yodocker) Calling RpcServerDriver.GetMachineName
(yodocker) Calling RpcServerDriver.DriverName
(yodocker) Calling RpcServerDriver.GetCreateFlags
(yodocker) Calling RpcServerDriver.SetConfigFromFlags
Running pre-create checks...
(yodocker) Calling RpcServerDriver.PreCreateCheck
Error creating machine: Error with pre-create check: Get https://management.core.windows.net/-xxx-xxxx-xxx-/services/hostedservices/operations/isavailable/yodocker: local error: internal error

>

**Comment by squillace** [comment]
@ahmetalpbalkan I'm wondering whether the first call fails due to some auth issue, but I've imported the publishsettings file and uploaded the .cer file, so... not clear how. in any case, if that's the issue, we aren't getting any error message help here.

**Comment by squillace** [comment]
Update: if I get rid of the certs and simply pass the publishsettings file, directly (not using the environment variables) it works. Go figure.

**Comment by ahmetalpbalkan** [comment]
Sounds a lot like #2180 (azure driver and environment variables)...

**Comment by squillace** [comment]
Yeah,  except that Monsieur @pchanezon didn't post the error trace. If it said "internal error" I'd be convinced.  :-)

That said,  at very least I'd love it if the error message could do a bit better... :-)
