### ISSUE TITLE
Option --store-path doesn't work properly

### ISSUE THREAD

**Issue by nguymin4** [docker/machine#2243]
I create a machine with `--storage-path` option. There is no error warnings but `docker-machine ls` shows no machines. 
![with-s](https://cloud.githubusercontent.com/assets/6953273/11072341/0ca5e452-87ee-11e5-8f6b-264bfb842aef.png)
I try the machine name with other docker-machine commands but only error message: `Host "dev" does not exist`.
But when I open Virtualbox then there is a machine up and running.

If I remove the `--storage-path` option and keeps the rests arguments then it just works as expected.
`docker-machine ls` show new created machine and I can work with that machine.
![without-s](https://cloud.githubusercontent.com/assets/6953273/11072324/004b36da-87ee-11e5-9310-c436f3671164.png)

OS: Windows 10
Docker-machine version: 0.5.0
Virtualbox: 5.0.8

**Comment by nathanleclaire** [comment]
If it's custom, you have to specify the `--storage-path` option for every `docker-machine` invocation.  So, `docker-machine --storage-path /custompath ls` should work.  You can set also the `MACHINE_STORAGE_PATH` environment variable to avoid typing the flag each time.

**Comment by nguymin4** [comment]
Ah I see. Thanks
