### ISSUE TITLE
make fails if you clone using https instead of ssh(i.e. git)

### ISSUE THREAD

**Issue by miqui** [docker/machine#2244]
make fails if you clone using https instead of ssh(i.e. git)
Looking at Makefile.inc, 

# Github infos
GITHUB_INFO := $(shell git config --get remote.origin.url | sed -e 's/.*:\(.*\).git/\1/')

assumes cloning with ssh.. is worth fixing/changing for both https and git?

**Comment by jeanlaurent** [comment]
Thx @miqui to point this out.

Current code link is : https://github.com/docker/machine/blob/master/Makefile.inc#L4

As a side note, the build can't work offline.

**Comment by dmp42** [comment]
That part is only used for release management.
Let's just `2>&1 > /dev/null` it and be happy.

**Comment by dmp42** [comment]
The same thing has been done here: https://github.com/docker/machine/blob/34f818527debef02f5a3102f198e44fb911433ae/mk/main.mk#L2

**Comment by nathanleclaire** [comment]
Why are we even doing that parsing at all?  As noted here, it seems to be brittle.  Why not just hardcode `docker` and `machine` for the repo information?

**Comment by dmp42** [comment]
@nathanleclaire portability, and ability to test on a fork more easily come to mind.
Doesn't look like the fix is specially complex (and it does only matter for publication).

**Comment by nathanleclaire** [comment]
@dmp42 What kind of portability are you referring to?  As for ability to test on a fork, editing two variables by hand seems a pretty reasonable tradeoff to me to get our Makefile simpler.

**Comment by dmp42** [comment]
Portability of the makefile.

About "simplification", it's doubtful that replacing these by consts is going to make the makefile significantly simpler (what would make it simpler is extracting the in-container build, but that would come at a price too).

Nevertheless, we certainly have more important stuff to fix right now :)

**Comment by jeanlaurent** [comment]
This is super tiny, it does not change the world, this is only affecting release management BUT it prevent some user from easily building docker-machine and thus probably affect the # of contribution we could get.

Note that, I did this with @dgageot in pairing and that we couldn't fully run the `make release` since it does a `git tag` + `git push`on master and we couldn't spot a "dryRun" flag or something alike.

I suggest moving forward with this, for the sole reason of helping our contributor a bit.

**Comment by dmp42** [comment]
Agreed about fixing this :)

**Comment by nathanleclaire** [comment]
As far as portability of the Makefile goes, we're already shelling out on lines like https://github.com/docker/machine/blob/master/Makefile#L15 (invoking a script directly), https://github.com/docker/machine/blob/master/mk/main.mk#L13 (using `$(shell ...)`), and elsewhere, so I don't see how our current Makefile is portable.  You _have_ to have a compatible shell already for our Makefile to be usable.

**Comment by dgageot** [comment]
Closed with https://github.com/docker/machine/pull/2245
