### ISSUE TITLE
docker-machine upgrade downgraded my vm

### ISSUE THREAD

**Issue by guiantunes** [docker/machine#2248]
Hi, Just upgraded to version 1.9.0b was using 1.8.0 before, but my mac still had files from older boot2docker and Kitematic. Everything was working fine but when I upgrade to 1.9 I needed to upgrade the VM. I ran docker-machine upgrade dev and it took an old version of a boot2docker.iso from this path:
/Applications/Kitematic (Beta).app/Contents/Resources/resources/boot2docker.iso which was version 1.7.1 why that happened? Can't figure out which environment configuration is telling docker-machine to look under this folder, tried to delete this file in order to see if it could try to download a newer one but unsuccessfuly. Can anybody help me?

    bash-3.2$ docker-machine upgrade dev
    Stopping machine to do the upgrade...
    Upgrading machine dev...
    Downloading boot2docker.iso from /Applications/Kitematic (Beta).app/Contents/Resources/resources/boot2docker.iso...
    open /Applications/Kitematic (Beta).app/Contents/Resources/resources/boot2docker.iso: no such file or directory

bash-3.2$ env
MANPATH=/Users/guilhermeantunes/.nvm/versions/v4.1.2/share/man:/Users/guilhermeantunes/.nvm/versions/v4.1.2/share/man:/Users/guilhermeantunes/.nvm/versions/v4.1.2/share/man:/usr/local/share/man:/usr/share/man:/opt/X11/share/man:/Applications/Xcode.app/Contents/Developer/usr/share/man:/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/share/man
rvm_bin_path=/Users/guilhermeantunes/.rvm/bin
TERM_PROGRAM=iTerm.app
GEM_HOME=/Users/guilhermeantunes/.rvm/gems/ruby-2.2.3
TERM=xterm-256color
SHELL=/bin/bash
IRBRC=/Users/guilhermeantunes/.rvm/rubies/ruby-2.2.3/.irbrc
TMPDIR=/var/folders/b5/cf9q7xj52_q7nvwqw_ywpx280000gn/T/
NVM_PATH=/Users/guilhermeantunes/.nvm/versions/v4.1.2/lib/node
Apple_PubSub_Socket_Render=/private/tmp/com.apple.launchd.9Ef5SrLfPD/Render
DOCKER_HOST=tcp://192.168.99.100:2376
MY_RUBY_HOME=/Users/guilhermeantunes/.rvm/rubies/ruby-2.2.3
NVM_DIR=/Users/guilhermeantunes/.nvm
USER=guilhermeantunes
_system_type=Darwin
rvm_path=/Users/guilhermeantunes/.rvm
SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.k7xtUrpqBt/Listeners
__CF_USER_TEXT_ENCODING=0x1F5:0x0:0x0
DOCKER_TLS_VERIFY=1
rvm_prefix=/Users/guilhermeantunes
PATH=/Users/guilhermeantunes/.rvm/gems/ruby-2.2.3/bin:/Users/guilhermeantunes/.rvm/gems/ruby-2.2.3@global/bin:/Users/guilhermeantunes/.rvm/rubies/ruby-2.2.3/bin:/Users/guilhermeantunes/google-cloud-sdk/bin:/Users/guilhermeantunes/.nvm/versions/v4.1.2/bin:/Users/guilhermeantunes/.nvm/versions/v4.1.2/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Users/guilhermeantunes/.rvm/bin
NVM_NODEJS_ORG_MIRROR=https://nodejs.org/dist
PWD=/Users/guilhermeantunes
LANG=pt_BR.UTF-8
ITERM_PROFILE=Default
NODE_PATH=/Users/guilhermeantunes/.nvm/versions/v4.1.2/lib/node_modules:/Users/guilhermeantunes/.nvm/versions/v4.1.2/lib/node_modules
_system_arch=x86_64
XPC_FLAGS=0x0
_system_version=10.11
XPC_SERVICE_NAME=0
rvm_version=1.26.11 (latest)
SHLVL=3
COLORFGBG=7;0
HOME=/Users/guilhermeantunes
DOCKER_CERT_PATH=/Users/guilhermeantunes/.docker/machine/machines/default
ITERM_SESSION_ID=w0t1p0
LOGNAME=guilhermeantunes
GEM_PATH=/Users/guilhermeantunes/.rvm/gems/ruby-2.2.3:/Users/guilhermeantunes/.rvm/gems/ruby-2.2.3@global
NVM_BIN=/Users/guilhermeantunes/.nvm/versions/v4.1.2/bin
DISPLAY=/private/tmp/com.apple.launchd.hC5gWQjNoR/org.macosforge.xquartz:0
RUBY_VERSION=ruby-2.2.3
_system_name=OSX
_=/usr/bin/env

**Comment by nathanleclaire** [comment]
@jeffdm @mchiang This is a good example of why bundling the `boot2docker.iso` alongside the rest of the Toolbox is potentially problematic.

**Comment by jeffdm** [comment]
We don't bundle boot2docker.iso with Kitematic anymore

The Toolbox includes boot2docker.iso and puts it in `~/.docker/machine/cache/boot2docker.iso`.

This shouldn't cause downgrading. `docker-machine upgrade` always checks GitHub, unless I'm mistaking

**Comment by guiantunes** [comment]
The problem is that docker-machine is always checking this path 

    /Applications/Kitematic (Beta).app/Contents/Resources/resources/

I don't understand why.

**Comment by jeffdm** [comment]
That's strange - which version of machine?

**Comment by jeffdm** [comment]
Also: thanks for letting us know :smiley:

**Comment by nathanleclaire** [comment]
One possible explanation: If it's a machine that was created before the change of not bundling the ISO anymore, it will still have the same property of where it looks for the `boot2docker.iso`. `upgrade` will therefore always check the `file:///` URI.  It could potentially be fixed by deleting and re-creating the instance with latest versions.

**Comment by guiantunes** [comment]
Guys, what I ended up doing was running the boot2docker uninstaller before updating the VM. I was using that comes when you download the latest toolbox just after docker 1.9.0 was released.

**Comment by nathanleclaire** [comment]
Please try latest Toolbox and re-open if this is not fixed.  Thanks
