### ISSUE TITLE
[EC2 driver] Support for spot instances

### ISSUE THREAD

**Issue by sylvinus** [docker/machine#226]
Spot instances are one of the features that make EC2 stand out for some workloads:
http://aws.amazon.com/ec2/purchasing-options/spot-instances/

Would be great to have support for them in Machine! I don't think it would be a huge undertaking.

Thanks!!

**Comment by ogrisel** [comment]
+1, it would be ideal to deploy batch data processing / compute workloads.

**Comment by sthulb** [comment]
I'm not against the idea, we need to decide which params to expose to a user.

**Comment by ogrisel** [comment]
In addition to the existing EC2 params I would just add the bid price and a boolean flag to use spot instance pricing instead of the default pricing.

Maybe also a specific timeout in case the bid is never satisfied (bid price is too low compared to the current market).

**Comment by ehazlett** [comment]
I don't think we will implement this at this time.  This could cause inconsistent states if the spot instance is terminated as machine expects them to be long running.

**Comment by ogrisel** [comment]
>  This could cause inconsistent states if the spot instance is terminated as machine expects them to be long running.

Spot instances are long running if you bid high enoough on an under-used datacenter. I don't see why this should be treated differently from a hardware or network failure.

**Comment by sylvinus** [comment]
+1 to @ogrisel. If machine makes such assumptions about the uptime of the instances, it doesn't sound very reliable... Regular EC2 instances may be terminated by Amazon, disconnected from the network, have a kernel panic, so in this respect they are not different from Spot instances at all.

**Comment by ogrisel** [comment]
Or terminated by a Chaos Monkey intentionally deployed on the cluster to make sure that the deployed services can all deal with frequent failures :)

**Comment by sthulb** [comment]
I actually like this feature

**Comment by ehazlett** [comment]
Ok.  What would we need to support spot instances?  The bid?

**Comment by sylvinus** [comment]
Thanks @ehazlett, very appreciated. 

From http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/spot-requests.html, the main additional parameters seem to be Bid, Request valid From/To and Persistent request.

In the context of machine, I guess you could set `request valid to` = now + 2 minutes or so, at which point the command could fail. Persistent requests are also probably out of scope, so IMHO the only parameter that would make sense is indeed the bid.

After submitting the bid you have to use a different API to wait for it to be fulfilled or not and that should be it!

Thanks a lot. Happy to provide testing on this.

**Comment by ehazlett** [comment]
@sylvinus ok thanks for the feedback!

**Comment by smolix** [comment]
+1 Yes, spot instance support would be great. Persistence is probably one of the key issues that might cause headaches since this will affect whether the number of available machines can ever go back up again.

**Comment by ranman** [comment]
We recently added a feature to Spot Instances that will give you a two minute warning before termination.
https://aws.amazon.com/blogs/aws/new-ec2-spot-instance-termination-notices/

The termination notice is accessible by `curl http://169.254.169.254/latest/meta-data/spot/termination-time`  it will contain the time when the shutdown signal will be sent to the instance's operating system.

We recommend that interested applications poll for the termination notice at five-second intervals.

**Comment by ehazlett** [comment]
@ranman nice!  thanks for the heads up.

**Comment by ogrisel** [comment]
Thanks @qicongchen  and @ehazlett!

**Comment by ehazlett** [comment]
@ogrisel yw!

**Comment by joshuacalloway** [comment]
has anyone used the spot instance type feature.  I got it up, but then how do you remove a machine?

$ docker-machine rm testspot
Provider error removing machine "testspot": unable to terminate instance: unknown instance

**Comment by richtong** [comment]
`docker-machine rm -f` seems to take care of instance which have vanished.

**Comment by jingpengwu** [comment]
this is a great feature, I have not found the specification of number of instances though. is that possible to launch a bunch of spot instances? Or I should have a for loop to create them?
