### ISSUE TITLE
Is `--driver=none` deprecated?

### ISSUE THREAD

**Issue by metasim** [docker/machine#2260]
It's not clear whether the `none` driver is still supported. It's disappeared from the docs, and functionality that worked in 0.3.x no longer works in 0.5.0, yet it still exists. I see comments about `--driver=generic` replacing `none`, but it doesn't quite fulfill all the "just add it to the inventory" nature of `none`.

Clarification on driver status would be helpful.

**Comment by nathanleclaire** [comment]
It's still supported, just broken.  If you post an issue with the symptoms you are seeing, we can help fix it.

**Comment by metasim** [comment]
I'll open two new issues: 

1) Add a documentation page on the `none` driver
2) Functionality that broke in the 0.5.0 release.

**Comment by nathanleclaire** [comment]
Sounds great thanks @metasim

**Comment by metasim** [comment]
Replaced with issues #2270 #2269
