### ISSUE TITLE
CI should build for all targets

### ISSUE THREAD

**Issue by dgageot** [docker/machine#2262]
The CI that runs on Travis currently builds and tests only the linux version of `docker-machine`. When a target specific file fails to compile, the build is still green. Cf https://github.com/docker/machine/pull/2261

We should really be building and testing for all platforms on TravisCI

**Comment by jeanlaurent** [comment]
If we find a way to build *quickly* for each OSes. This will enable per-OS unit/integration tests as hinted in  #2237

**Comment by dgageot** [comment]
Fixed with https://github.com/docker/machine/pull/2265
