### ISSUE TITLE
create --swarm-opt(s) only used for master, not for nodes

### ISSUE THREAD

**Issue by schmunk42** [docker/machine#2266]
I create swarm nodes with the following command

```
docker-machine --debug create \
    -d amazonec2 --swarm  \
    --swarm-opt ttl=121s --swarm-opt heartbeat=7s \
    --swarm-image="swarm:1.0.0" --swarm-discovery "token://$TOKEN" \
   $ROJ_SWARM_NAME-1
```

I'd expect see this container and command running on my node

    swarm join --heartbeat 7s --ttl 121s --advertise IP:2376 token://TOKEN

But the options are not applied:

    swarm join --advertise IP:2376 token://TOKEN

AFAIK the master can use heartbeat as an option as described in the docs.

**Comment by nathanleclaire** [comment]
It should work with the master.  That's where you set the heartbeat AFAIK as well.  As an option on `swarm manage`.  So, I don't think this is a bug, but expected behavior.

**Comment by schmunk42** [comment]
IMHO, setting the swarm opts on the worker is at least as important as on the master, below is the help output of the swarm join command:

```
$ docker run swarm join -h
Usage: swarm join [OPTIONS] <discovery>

join a docker cluster

Arguments: 
   <discovery>    discovery service to use [$SWARM_DISCOVERY]
                   * token://<token>
                   * consul://<ip>/<path>
                   * etcd://<ip1>,<ip2>/<path>
                   * file://path/to/file
                   * zk://<ip1>,<ip2>/<path>
                   * [nodes://]<ip1>,<ip2>

Options:
   --advertise, --addr 							Address of the Docker Engine joining the cluster. Swarm manager(s) MUST be able to reach the Docker Engine at this address. [$SWARM_ADVERTISE]
   --heartbeat "20s"							period between each heartbeat
   --ttl "60s"								sets the expiration of an ephemeral node
   --discovery-opt [--discovery-opt option --discovery-opt option]	discovery options
```

And `docker-machine create -h` says:

```
--swarm-opt [--swarm-opt option --swarm-opt option]							Define arbitrary flags for swarm
```

So the current behavior is at least unexpected since it does not explicitly state, that the options are only used for master. 

As said above, setting the swarm params on the node is very important, see related issue: https://github.com/docker/swarm/issues/1405

**Comment by nathanleclaire** [comment]
I'm going to transition this issue into a "Feature Request" to do so.  Sound good?

**Comment by nathanleclaire** [comment]
Adding "help-wanted" tag since this might be a good area for a contributor to pick up.  Just need to add a bit to an existing template.

**Comment by schmunk42** [comment]
@nathanleclaire Thank you. Sounds good.
