### ISSUE TITLE
GCE driver should name the instance after the machine name

### ISSUE THREAD

**Issue by proppy** [docker/machine#227]
It would be nice if machine created with the GCE driver (and others) would be named (or even prefixed) after the machine name by default if no flag value for `--google-instance-name` is specified.

The current behavior is a bit confusing as `machine` will create multiple machine with the same underlying VM, if you don't specific `--google-instance-name`.

```
proppy@noir:~$ machine create --driver google --google-project proppy-stuff foo
proppy@noir:~$ machine create --driver google --google-project proppy-stuff bar
FATA[0004] Instance docker-machine already exists.
proppy@noir:~$ machine ls
NAME             ACTIVE   DRIVER   STATE     URL
bar              google   Running   tcp://130.211.144.5:2376
foo     *        google   Running   tcp://130.211.144.5:2376
```

Possibly related to #59 #219 
/cc @dlorenc

**Comment by sthulb** [comment]
All machines will take the name from the command as the VM name in whatever account/hypervisor

**Comment by proppy** [comment]
@sthulb that doesn't seems to be the case right now, at least for GCE:
https://github.com/docker/machine/blob/master/drivers/google/google.go#L96

**Comment by sthulb** [comment]
Not right now. It's something I'm working on for #59

**Comment by ehazlett** [comment]
Closing as #59 will handle this (as @sthulb mentioned).
