### ISSUE TITLE
Still provide docker-machine with a GOARCH=386 for Linux & Darwin ?

### ISSUE THREAD

**Issue by jeanlaurent** [docker/machine#2271]
We actually provide 6 binaries : `darwin`, `window` & `linux` each of them for two architectures `amd64` & `386`.

Two questions, open for discussion
* It sounds like docker engine project does [not provide](https://github.com/docker/docker/releases/tag/v1.9.0) `386` `linux` binaries, so why should we ? 
* Its sounds like the last mac running a 32bits processor has been out in [2005](http://apple.stackexchange.com/questions/99640/how-old-are-macs-that-cannot-run-64-bit-applications/99644#99644), why should still provide theses ? (Although the docker engine project still provide them, we should ask them)

If we have users on these, fair enough, let's keep them, if we don't maybe it's time to simplify this a bit. The main advantage is to speed up the cross-os projects, simplify the build and tests.

**Comment by dmp42** [comment]
> It sounds like docker engine project does not provide 386 linux binaries, so why should we ?

On "what" docker is installed is different from on "what" machine is ran to install docker somewhere else. See the point?

Agreed though that the 386 arch is probably not that interesting...
Not building them would indeed speed-up the cross target - not so much for simplifying build & tests though I'm afraid.

**Comment by nathanleclaire** [comment]
I would not really be too averse to dropping support for the 32 bit executables, but we should check our download numbers for those binaries first to make sure the tradeoff is acceptable.  If <5% of our downloads are on 32bit, for instance, I'm more keen than if 30% of our downloads are for 32bit.

**Comment by nathanleclaire** [comment]
Wow, just ran the numbers on 0.5.0 so far (source: https://api.github.com/repos/docker/machine/releases), the amount of users on 32 bit is really pretty tiny, with the exception of Windows at least.

```
Darwin:  9 / 1141   total downloads  == 0.78%
Linux:   19 / 3862  total downloads  == 0.49%
Windows: 28.0 / 561 total downloads  == 5%
```

So, I'd say I'm in favor.  We might want to keep them around for Windows though, or at least provide a pointer to "Hey, if you want 32 bit, here's how to compile it yourself".

**Comment by jeanlaurent** [comment]
I believe some users are mislead by the arch name also. A few of those 386 downloads are probably people who downloaded the wrong version.

+1 to remove linux and darwin 386 and keep windows for now...

**Comment by dgageot** [comment]
Let's remove them is 0.5.2!

**Comment by nathanleclaire** [comment]
Sure, I'm in favor of removing the Darwin and Linux packages for 0.5.2.
