### ISSUE TITLE
VMWareVSphere driver expects boot2docker.iso in different location

### ISSUE THREAD

**Issue by donaldquixote** [docker/machine#2279]
When running docker-machine create -d vmwarevsphere ...

"Error creating machine: Error in driver during machine creation: Incomplete vSphere information: missing C:\Users\redacto\.docker\machine\boot2docker.iso."

boot2.docker.iso is found in C:\Users\redacto\.docker\machine\cache on my setup. Copying the file to the location specified in the error message resolved the issue.

**Comment by nathanleclaire** [comment]
cc @frapposelli

**Comment by nathanleclaire** [comment]
I may have messed this (previously working) code up in some refactoring changes, so I'm sorry if that's the cause.

**Comment by donaldquixote** [comment]
No worries. I appreciate the quick response and look forward to seeing these tools continue to grow.

**Comment by kel0o** [comment]
Can confirm this on Mac OS X 10.11.1

**Comment by kleptog** [comment]
Also on my Debian Jessie amd64 machine:

    Error creating machine: Error in driver during machine creation: Incomplete vSphere information: missing /home/kleptog/.docker/machine/boot2docker.iso

**Comment by manei** [comment]
The workaround so far is to put the iso where it expects to be. Unfortunately I have not had time to test the whole plugin on our vmware environment, yet.

**Comment by r0bnet** [comment]
We encountered the same issue (Ubuntu 14.04, docker-machine v0.5.1). The workaround that @manei mentioned is working for us but it's not a nice solution. We maybe found the problematic code at machine/drivers/vmwarevsphere/vsphere.go line 175.
There the path is probably incorrect. A solution could be:
d.ISO = filepath.Join(d.StorePath, "machines", d.MachineName, isoFilename)

I hope you can fix this soon.

**Comment by frapposelli** [comment]
Just sent #2487 for a quick interim fix while we decide on the future of the vSphere driver rewrite.

**Comment by rossedman** [comment]
Wondering what the status of this was? I know @frapposelli is a busy man, but interested to know if there is any progress. :100:
