### ISSUE TITLE
Service Unavailable error on MacOSX

### ISSUE THREAD

**Issue by valentin69** [docker/machine#2282]
Unable to connect from the MacOSX host.
Using DockerToolbox-1.9.0c
Every command fails with a Service Unavailable error.

$ docker-machine --version
docker-machine version 0.5.0 (04cfa58)
$ docker images
An error occurred trying to connect: Get https://192.168.99.100:2376/v1.21/images/json: Service Unavailable
$ docker-machine ls
NAME                     ACTIVE   DRIVER       STATE     URL                         SWARM
machine1                 *        virtualbox   Running   tcp://192.168.99.100:2376   

I can ssh in the machine : Docker is ok.

docker-machine ssh machine1
                        ##         .
                  ## ## ##        ==
               ## ## ## ## ##    ===
           /"""""""""""""""""\___/ ===
      ~~~ {~~ ~~~~ ~~~ ~~~~ ~~~ ~ /  ===- ~~~
           \______ o           __/
             \    \         __/
              \____\_______/
 _                 _   ____     _            _
| |__   ___   ___ | |_|___ \ __| | ___   ___| | _____ _ __
| '_ \ / _ \ / _ \| __| __) / _` |/ _ \ / __| |/ / _ \ '__|
| |_) | (_) | (_) | |_ / __/ (_| | (_) | (__|   <  __/ |
|_.__/ \___/ \___/ \__|_____\__,_|\___/ \___|_|\_\___|_|
Boot2Docker version 1.9.0, build master : 16e4a2a - Tue Nov  3 19:49:22 UTC 2015
Docker version 1.9.0, build 76d6bc9
docker@homebyme:~$ docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
hello-world         latest              0a6ba66e537a        4 weeks ago         960 B

**Comment by jeanlaurent** [comment]
Thx @valentin69 for your feedback.

did you run `eval $(docker-machine env machine1)`  from the MacOSX Host ?

**Comment by valentin69** [comment]
Absolutely :
$ env | grep DOCKER
DOCKER_HOST=tcp://192.168.99.101:2376
DOCKER_MACHINE_NAME=machine1
DOCKER_TLS_VERIFY=1
DOCKER_CERT_PATH=/Users/valentin/.docker/machine/machines/machine1

**Comment by jeanlaurent** [comment]
From your 1st message it sounds like machine1 ip is `192.168.99.100` and from your 2nd message your `DOCKER_HOST` is `192.168.99.101`. I don't have all the details of what you did but it sounds like your need to refresh you env and/or recreate your machine.

**Comment by valentin69** [comment]
That is just because I destroyed the machine and recreated a new one (in my attempts to find what's going wrong...).
machine1                 *        virtualbox   Running   tcp://192.168.99.101:2376 
DOCKER_HOST=tcp://192.168.99.101:2376

**Comment by jeanlaurent** [comment]
This is really weird.

Sounds like the machine is setup but maybe the docker daemon may not run.

can you check if the daemon is running by `docker-machine ssh default` and type in `ps aux | grep 'docker daemon` and report here the result ?

Although if it was the case, the `docker-machine env default` should report the problem beforehand.

What's your docker version ?

Nice to have seen each other in f2f @ dockercon

**Comment by valentin69** [comment]
Hi Jean Laurent,
Yes it was very nice seeing you at the Dockercon EU 15.
I ended up destroying the machines, cleanind ~/.docker/machine and installing the next version of the toolbox that was released just before Dockercon and it is working now.
Cleaning up the cache probably did the trick.
Valentin

**Comment by ghusta** [comment]
I had a similar problem on Windows (Docker Toolbox 1.10.3), but it was due to my proxy configuration.
I solved my problem with this : https://docs.docker.com/machine/reference/env/#excluding-the-created-machine-from-proxies
(adding NO_PROXY env variable).
