### ISSUE TITLE
[DigitalOcean/Azure driver] Intermittent tls Handshake errors on create

### ISSUE THREAD

**Issue by nathanleclaire** [docker/machine#229]
A few times now I've gotten DigitalOcean errors on `create`:

```console
$ machine create -d digitalocean --digitalocean-access-token token foo
INFO[0000] Creating SSH key...
INFO[0001] Creating Digital Ocean droplet...
INFO[0003] Waiting for SSH...
FATA[0094] tls Handshake error: dial tcp 104.236.111.172:2376: connection refused
```

If I set that host to active and run docker commands against it it works as expected... it's just the `create` output that's blowing up.

Anyone else run into this?

**Comment by ehazlett** [comment]
I've been seeing some odd behavior today as well - like SSH never making it, droplets saying they weren't created etc.  Will investigate more.

**Comment by nathanleclaire** [comment]
Added "Azure" to the tag in title.

**Comment by ehazlett** [comment]
@ahmetalpbalkan thanks for the report -- I'm digging to see if I can find what might be causing this for Azure as well.

**Comment by ahmetalpbalkan** [comment]
@ehazlett one thing I noticed with Azure is, if you set --azure-port something other than default 2376, it still keeps using 2376.

The failure above doesn't prevent installation to complete (I guess docker is installed and started by the time we get that failure). However using the wrong port causes bad port mapping on Azure VM and you can't reach Docker daemon using the port you specified at --azure-port. I think [this](https://github.com/docker/machine/blob/ee9e4843b304b84e5ceb13319b91e45c28ee3bba/drivers/azure/azure.go#L22) hardcoding causes that. 

Not sure if these issues are related, though.

**Comment by ehazlett** [comment]
@ahmetalpbalkan ok could you open a separate issue for that?  I'm getting some odd behavior with Azure itself as well (A hosted service with the specified name already exists. with no services).

/cc @jeffmendoza any ideas on that one?

DigitalOcean has been fine for me today.

**Comment by sthulb** [comment]
I've had this on virtual box today.

**Comment by ehazlett** [comment]
Ok this is starting to sound like a possible race issue perhaps.

**Comment by jeffmendoza** [comment]
hosted service names are used for DNS and must be globally unique.

**Comment by ehazlett** [comment]
@jeffmendoza i had no services provisioned.  this issue went away for azure yesterday.  not sure what happened.

**Comment by ehazlett** [comment]
@jeffmendoza thanks for explaining :)

**Comment by andyshinn** [comment]
I'm seeing this same issue in VirtualBox as well. The create errors. But if I run with `--debug` to keep the machine around, after it is created, I can use the Docker client against the TCP socket just fine. Here is the end of the create debug output for both Digital Ocean and VirtualBox showing the issue:

* Digital Ocean: https://gist.github.com/andyshinn/cfb0ffd350cee35b3d92
* VirtualBox: https://gist.github.com/andyshinn/4b91d344cdeb52e4959d

**Comment by ehazlett** [comment]
@andyshinn @sthulb @ahmetalpbalkan could you test the fix in #266?  I haven't had this issue anymore after that fix.

**Comment by andyshinn** [comment]
I can't reproduce this particular issue. But am having a bunch of other failures which seem to be slowness inside the DO network (failing sometimes on docker stop, curling the binary with identity, etc.).

**Comment by ehazlett** [comment]
Yeah I was having a bunch of issues on DO today as well :(

**Comment by ahmetalpbalkan** [comment]
@ehazlett just had a chance to try with #266. It works for Azure –unless I specify the `--azure-port` parameter. There's some hard coding in the code for port 2376 and this disallows custom ports from being used. Nonetheless, it doesn't give the TLS handshake error anymore.

**Comment by ehazlett** [comment]
Thanks.  Yeah we should open a separate issue for that.  We have a couple
of drivers that hard code some things.

On Wed, Jan 14, 2015 at 12:04 PM, Ahmet Alp Balkan <notifications@github.com
