### ISSUE TITLE
Possibility to create master with manager, but without agent

### ISSUE THREAD

**Issue by nazar-pc** [docker/machine#2302]
Originally reported as https://github.com/docker/swarm/issues/771, but seems to be Machine-related.
I'd like to also have master with just `swarm-agent-master` without `swarm-agent` on it.
I'm wondering that this is not possible:(
Especially having such message in docs:
> The master is running both the swarm manager and a swarm agent container. This isn’t recommended in a production environment because it can cause problems with agent failover. However, it is perfectly fine to do this in a learning environment like this one.

It would be helpful to run only manager, while currently it doesn't seem to be possible to do out of the box - we need to dig into machine and remove agent manually.

**Comment by nathanleclaire** [comment]
Maybe we should have the existing `--swarm` flag imply the creation of a `join` container, and leave that container out if it's absent.  That way, `--swarm-master` would be usable outside of `--swarm`, which isn't the case today, and would preserve backwards compat while allowing this use case.  cc @docker/machine-maintainers WDYT

**Comment by abronan** [comment]
Missed that one but sounds like a good idea :+1:

This separates the concepts of `Manager` and `Agents` which would allow us to run a standalone `Manager`. Also it's not documented at all yet but `swarm join` is not necessary anymore (on `swarm:master` at least), you can now have a single Manager pointing to nodes registering on the docker discovery (that are using `--cluster-store` and `--cluster-advertise`).

`--swarm-master` being usable outside of using `--swarm` is necessary as this will be made optional in the future anyway.

**Comment by fiunchinho** [comment]
I was just asking the same question on IRC channel. It's needed to be able to create a manager that does not contain agents. Typically, you wouldn't want app containers running in your managers.

**Comment by BretFisher** [comment]
GHIssue gold right here. Went down rabbit holes of why `--swarm-master` acted like it was working without `--swarm` (no errors). That one line in documentation saying to create dedicated masters had me assuming that `--swarm` is to only install agent, and `--swarm-master` is to only install master. Even more misleading: after the fact, `machine` lists it as a swarm master when you put in everything but `--swarm`, but it's not running the swarm container nor listening on 3376.

Example: `docker-machine create -d virtualbox --swarm-master --swarm-discovery token://<token-id> swarm-master`

That will create the VM, with no errors that I could see, and show up in `docker-machine` as:

`swarm-master            -        virtualbox   Running   tcp://192.168.99.106:2376   swarm-master (master)`

But swarm isn't to be found. Only hint would be during `create` output you don't see anything mentioning swarm. `--help` doesn't give any tips either.

**Comment by batmat** [comment]
+1 exact same issue encountered as @BretFisher : I spent a few minutes making sure I hadn't miss something when I decided to _not_ put the `--swarm` switch but only the `--swarm-master` one. 
At least in the very short term, I think this might be very useful that `docker-machine` just stops and issues an error when `--swarm-master` is used without `--swarm`.
Thanks again for that great tool, provisioning machines has never been so simple, congrats again.

**Comment by batmat** [comment]
Note: a possible workaround is to create the swarm master using the "standard" command with both `--swarm` and `--swarm-master`, and then just stop the swarm-agent container on that node (and leave the swarm-agent-master/manager container running, obviously).

**Comment by awishformore** [comment]
This was something that really bothered me as well when setting up our swarm.

**Comment by dgageot** [comment]
@nathanleclaire +1 to be able to use `--swarm-master` flag alone

**Comment by awishformore** [comment]
I would actually suggest --swarm-manager and --swarm-agent.

It seems to me that "master" implies that it's a normal node with extra authoritative powers, while "manager" implies it just manages, but doesn't accomplish normal agent duties. We could still leave --swarm-master to initialize a node that does both for dev environment, while you would use --swarm-agent and --swarm-manager for production deployments.

**Comment by NoamB** [comment]
+1 on manager without agent
