### ISSUE TITLE
Generate CMD.exe compatible code in 'env' command

### ISSUE THREAD

**Issue by jonnyzzz** [docker/machine#2304]
Currently it generates 
```
Eugene.Petrenko@MUNIT-131 C:\Users\Eugene.Petrenko
> docker-machine env default
export DOCKER_TLS_VERIFY="1"
export DOCKER_HOST="tcp://192.168.99.100:2376"
export DOCKER_CERT_PATH="C:\Users\Eugene.Petrenko\.docker\machine\machines\default"
export DOCKER_MACHINE_NAME="default"
# Run this command to configure your shell:
# eval "$(docker-machine env default)"
```

But for CMD.exe it's required to 
* replace `export` with `set` 
* remove quotes from values 
* replace `#` with `rem `

Currently I cannot copy-paste it to have it working. The only case is to get it line-by-line and remove quotes from arguments.

**Comment by jeanlaurent** [comment]
`docker-machine env --shell cmd default` should do exactly that for you.

Can you try & report here if it works for you ?

**Comment by nathanleclaire** [comment]
It should be covered by `--shell cmd`.

**Comment by jonnyzzz** [comment]
Works correctly. But why is not it set as default for Windows builds?

**Comment by nathanleclaire** [comment]
@jonnyzzz Because `cmd.exe` is actually not the "default" shell for Windows.  In the Toolbox we bundle git bash and expect users to mostly use that, but do provide support for other shells in case they want to switch.

**Comment by jonnyzzz** [comment]
I believe one can detect current shell. I can expect powershell, cmd and git-bash to be used under windows. I do not use git-bash in most cases. Most time I use cmd.exe under ConEmu64

**Comment by nathanleclaire** [comment]
We do try to detect the shell through `SHELL` environment variable and other tricks but doing it robustly for every shell and combination of possible environments is difficult.  Feel free to submit a PR to more robustly detect `cmd.exe` if our current method can be improved upon.

**Comment by abejenaru** [comment]
I wish some default options could be changed; like being able to set the implicit shell to cmd, use --no-proxy, etc. much like the powerful git commands aliases.
