### ISSUE TITLE
Alias "machine ps" to "machine ls"

### ISSUE THREAD

**Issue by bfirsh** [docker/machine#231]
"machine ps" doesn't make sense because they're not processes, but lots of people are going to type it by mistake. We should probably alias "machine ps" to "machine ls" or at least say "You're looking for machine ls."

**Comment by thaJeztah** [comment]
If there's any chance that a `machine ps` will exist in the future, I'd go for the latter, and not encourage people to get used to it. Just my 0.02c

**Comment by ehazlett** [comment]
@thaJeztah thanks for that link.  Perhaps we follow suit and report "machine --help"?

**Comment by thaJeztah** [comment]
I think it would be good to be consistent between docker projects yes

**Comment by nathanleclaire** [comment]
Yes, I am +1 on just displaying "That's not a command, run `machine --help`."  Aliasing `machine ps` to `machine ls` would encourage bad habits and confuse users IMO.

**Comment by sthulb** [comment]
I wouldn't alias it. Just do as others have mentioned.

**Comment by bfirsh** [comment]
Alright. Doing nothing is my favourite solution.
