### ISSUE TITLE
[Feature Request] Support filtering by Engine label in `ls`

### ISSUE THREAD

**Issue by schmunk42** [docker/machine#2310]
Although the syntax might be a bit quirky, it would be nice if we could do something like:

    docker-machine ls --filter "label:app=1"

For such a machine, i.e.

```
 tim-a1: 1.2.3.4:2376
  └ Containers: 73
  └ Reserved CPUs: 0 / 1
  └ Reserved Memory: 0 B / 2.051 GiB
  └ Labels: app=1, executiondriver=native-0.2, kernelversion=3.13.0-53-generic, operatingsystem=Ubuntu 14.04.2 LTS, provider=amazonec2, storagedriver=aufs
```

See also https://docs.docker.com/machine/reference/ls/

**Comment by ksasi** [comment]
+kind/feature

**Comment by askb** [comment]
For filtering machines with label's: (docker-machine "--engine-label foo=bar") this information gets stored on the persistent filestore (config.json), which can already be retrieved with `docker-machine inspect <name>` (even when the machine is not in running state) OR through "docker info" (cli API), which requires that the machine is in `STATE=running` for reading these values, and would also require every driver to have there own implement. Which would be a better approach ? I would like give this a go. :). thanks

**Comment by dgageot** [comment]
fixed with https://github.com/docker/machine/pull/2464
