### ISSUE TITLE
Exit status 255 from SSH on OSX

### ISSUE THREAD

**Issue by SalemAmeen** [docker/machine#2312]
Machine default already exists in VirtualBox.
Setting environment variables for machine default...

                        ##         .
                  ## ## ##        ==
               ## ## ## ## ##    ===
           /"""""""""""""""""\___/ ===
      ~~~ {~~ ~~~~ ~~~ ~~~~ ~~~ ~ /  ===- ~~~
           \______ o           __/
             \    \         __/
              \____\_______/


Error getting IP address: Something went wrong running an SSH command!
command : ip addr show dev eth1
err     : exit status 255
output  :
docker is configured to use the default machine with IP 
For help getting started, check out the docs at https://docs.docker.com

Error running connection boilerplate: Error getting driver URL: Something went wrong running an SSH command!
command : ip addr show dev eth1
err     : exit status 255
output  :

**Comment by nathanleclaire** [comment]
Please print the output of `docker-machine --debug start default`.  This looks a lot like a duplicate issue to several we have already, though, so I'm inclined towards closing it.

**Comment by nathanleclaire** [comment]
Please re-open when you have some more infos.

**Comment by samartioli** [comment]
I have a friend seeing the same issue. @SalemAmeen did you figure out what it was?

**Comment by SalemAmeen** [comment]
unfortunately no

**Comment by dalyleya** [comment]
docker-machine --debug start default
Docker Machine Version:  0.5.4, build 6643d0e
Found binary path at /usr/local/bin/docker-machine
Launching plugin server for driver virtualbox
Plugin server listening at address 127.0.0.1:52128
() Calling .GetVersion
Using API Version  1
() Calling .SetConfigRaw
() Calling .GetMachineName
command=start machine=default
(default) Calling .GetState
(default) DBG | COMMAND: /usr/local/bin/VBoxManage showvminfo default --machinereadable
(default) DBG | STDOUT:
(default) DBG | {
(default) DBG | name="default"
(default) DBG | groups="/"
(default) DBG | ostype="Linux 2.6 / 3.x / 4.x (64-bit)"
(default) DBG | UUID="96aefd27-4cb4-429d-b6f2-b3fbf3ea592c"
(default) DBG | CfgFile="/Users/daria/.docker/machine/machines/default/default/default.vbox"
(default) DBG | SnapFldr="/Users/daria/.docker/machine/machines/default/default/Snapshots"
(default) DBG | LogFldr="/Users/daria/.docker/machine/machines/default/default/Logs"
(default) DBG | hardwareuuid="96aefd27-4cb4-429d-b6f2-b3fbf3ea592c"
(default) DBG | memory=2048
(default) DBG | pagefusion="off"
(default) DBG | vram=8
(default) DBG | cpuexecutioncap=100
(default) DBG | hpet="on"
(default) DBG | chipset="piix3"
(default) DBG | firmware="BIOS"
(default) DBG | cpus=1
(default) DBG | pae="on"
(default) DBG | longmode="on"
(default) DBG | cpuid-portability-level=0
(default) DBG | bootmenu="disabled"
(default) DBG | boot1="dvd"
(default) DBG | boot2="dvd"
(default) DBG | boot3="disk"
(default) DBG | boot4="none"
(default) DBG | acpi="on"
(default) DBG | ioapic="on"
(default) DBG | biossystemtimeoffset=0
(default) DBG | rtcuseutc="on"
(default) DBG | hwvirtex="on"
(default) DBG | nestedpaging="on"
(default) DBG | largepages="on"
(default) DBG | vtxvpid="on"
(default) DBG | vtxux="on"
(default) DBG | paravirtprovider="default"
(default) DBG | VMState="running"
(default) DBG | VMStateChangeTime="2016-01-04T13:20:54.841000000"
(default) DBG | monitorcount=1
(default) DBG | accelerate3d="off"
(default) DBG | accelerate2dvideo="off"
(default) DBG | teleporterenabled="off"
(default) DBG | teleporterport=0
(default) DBG | teleporteraddress=""
(default) DBG | teleporterpassword=""
(default) DBG | tracing-enabled="off"
(default) DBG | tracing-allow-vm-access="off"
(default) DBG | tracing-config=""
Machine "default" is already running.
(default) DBG | autostart-enabled="off"
(default) DBG | autostart-delay=0

**Comment by dalyleya** [comment]
The same issue 
There is output of 
docker-machine --debug start default

Docker Machine Version:  0.5.4, build 6643d0e
Found binary path at /usr/local/bin/docker-machine
Launching plugin server for driver virtualbox
Plugin server listening at address 127.0.0.1:52128
() Calling .GetVersion
Using API Version  1
() Calling .SetConfigRaw
() Calling .GetMachineName
command=start machine=default
(default) Calling .GetState
(default) DBG | COMMAND: /usr/local/bin/VBoxManage showvminfo default --machinereadable
(default) DBG | STDOUT:
(default) DBG | {
(default) DBG | name="default"
(default) DBG | groups="/"
(default) DBG | ostype="Linux 2.6 / 3.x / 4.x (64-bit)"
(default) DBG | UUID="96aefd27-4cb4-429d-b6f2-b3fbf3ea592c"
(default) DBG | CfgFile="/Users/daria/.docker/machine/machines/default/default/default.vbox"
(default) DBG | SnapFldr="/Users/daria/.docker/machine/machines/default/default/Snapshots"
(default) DBG | LogFldr="/Users/daria/.docker/machine/machines/default/default/Logs"
(default) DBG | hardwareuuid="96aefd27-4cb4-429d-b6f2-b3fbf3ea592c"
(default) DBG | memory=2048
(default) DBG | pagefusion="off"
(default) DBG | vram=8
(default) DBG | cpuexecutioncap=100
(default) DBG | hpet="on"
(default) DBG | chipset="piix3"
(default) DBG | firmware="BIOS"
(default) DBG | cpus=1
(default) DBG | pae="on"
(default) DBG | longmode="on"
(default) DBG | cpuid-portability-level=0
(default) DBG | bootmenu="disabled"
(default) DBG | boot1="dvd"
(default) DBG | boot2="dvd"
(default) DBG | boot3="disk"
(default) DBG | boot4="none"
(default) DBG | acpi="on"
(default) DBG | ioapic="on"
(default) DBG | biossystemtimeoffset=0
(default) DBG | rtcuseutc="on"
(default) DBG | hwvirtex="on"
(default) DBG | nestedpaging="on"
(default) DBG | largepages="on"
(default) DBG | vtxvpid="on"
(default) DBG | vtxux="on"
(default) DBG | paravirtprovider="default"
(default) DBG | VMState="running"
(default) DBG | VMStateChangeTime="2016-01-04T13:20:54.841000000"
(default) DBG | monitorcount=1
(default) DBG | accelerate3d="off"
(default) DBG | accelerate2dvideo="off"
(default) DBG | teleporterenabled="off"
(default) DBG | teleporterport=0
(default) DBG | teleporteraddress=""
(default) DBG | teleporterpassword=""
(default) DBG | tracing-enabled="off"
(default) DBG | tracing-allow-vm-access="off"
(default) DBG | tracing-config=""
Machine "default" is already running.
(default) DBG | autostart-enabled="off"
(default) DBG | autostart-delay=0

**Comment by TimoSolo** [comment]
Did the `docker-machine rm default` thing a couple times, but takes ages to download image.

Found a simpler solution though! Open VirtualBox, turn off the "default" machine. Run Docker Quickstart and it starts up the VM and connects fine!
