### ISSUE TITLE
Rackspace Driver is not working in v0.5.0

### ISSUE THREAD

**Issue by wlan0** [docker/machine#2314]
It seems like the rackspace driver for docker-machine-v0.5.0 does not work. I understand that the rackspace driver is not maintained by docker anymore, but I figured a github issue documenting this would let the community know about this issue and let them track it. 

The openstack driver for rackspace tries to authenticate using an uninitialized/partially initialized object in this line https://github.com/docker/machine/blob/master/drivers/openstack/client.go#L515

I added log lines to examine the arguments passed down to the call, and these were its contents 

Authentication Provider  (arg1) - 
```
[&{IdentityBase:/ IdentityEndpoint: TokenID: EndpointLocator:<nil> HTTPClient:{Transport:<nil> CheckRedirect:<nil> Jar:<nil> Timeout:0} UserAgent:{prepend:[docker-machine/v1]} ReauthFunc:<nil>}]
```

opts (gophercloud.AuthOptions) (arg2) -
```
[{IdentityEndpoint: Username:${USERNAME} UserID: Password: APIKey: DomainID: DomainName: TenantID: TenantName: AllowReauth:true}]
```

Note that all fields except `Username` are empty

These are the commands that can be used to reproduce.

1. Create a rackspace host with valid credentials, using this command -

```
docker-machine create --driver rackspace --rackspace-region $REGION --rackspace-username $USERNAME --rackspace-api-key $API_KEY $MACHINE_KEY 
```

The following error message will be produced
```
Error creating machine: Error in driver during machine creation: Get /: unsupported protocol scheme ""
```

**Comment by nathanleclaire** [comment]
Please try 0.5.1 and re-open if it does not work.  It contains a fix meant to address this.

**Comment by wlan0** [comment]
@nathanleclaire Thanks for the update. v0.5.1 fixes the issue

**Comment by nathanleclaire** [comment]
Nice thanks for confirming it's fixed.
