### ISSUE TITLE
Docker Machine v0.5.1 breaks compatibility with v0.5.0 drivers

### ISSUE THREAD

**Issue by janeczku** [docker/machine#2325]
This particularly affects use of drivers not distributed with the machine binary.

For simplicity this is demonstrated with the `virtualbox` driver.

#### Steps to reproduce

1. `$ git clone https://github.com/docker/machine.git`
2. `$ cd machine && git checkout v0.5.0`
4. `$ go build -a -o /usr/local/bin/docker-machine-driver-virtualbox cmd/machine-driver-virtualbox.go`
5. `$ git checkout v0.5.1`
6. `$ go build -a -o /usr/local/bin/docker-machine cmd/machine.go`
7. `$ docker-machine create -d virtualbox`

#### Expected result

Machine continuous to work

#### Actual result

Error occurs and Machine exits

```text
WARNING >>> Error attempting heartbeat call to plugin server: rpc: can't find service RPCServerDriver.Heartbeat
Error attempting to invoke binary for plugin 'virtualbox': rpc: can't find service RPCServerDriver.GetVersion

```

This is probably caused by commit 89d9854 which changed the RPC API interface breaking compatibility with all drivers compiled against v0.5.0 or earlier.

Reference PR #2321
/cc @nathanleclaire @dmp42

**Comment by nathanleclaire** [comment]
Ah, of course, the linting changes.  Thanks for the report @janeczku.

I'm pretty upset about this (and I really am profusely sorry) as it wasn't intended to break compatibility but I think the linting changes are over (new PRs are being run through `golint`) and there is nothing we can do about it now unfortunately.  In the future we will be more disciplined about not breaking the API.

**Comment by dgageot** [comment]
Yes, that's bad. We had to do it. We should have done it before 0.5.0 and didn't have time.

**Comment by legal90** [comment]
That's really sad that these backward & forward incompatible stuff was done in the scope of patch level release. May be, it is reasonable to bump a minor version at least? (0.6.0)

**Comment by allingeek** [comment]
You can still fix this AND keep the linting change. There is no reason to tie the API service and method names to Go types. Please consider reopening, making the change, and restoring the API.

Should I send a PR?

**Comment by nathanleclaire** [comment]
@allingeek Interesting, I had not considered that as an alternative.  Would love to see such a PR.

**Comment by allingeek** [comment]
I've verified that a docker-machine binary with this patch will work with both plugin generations.

**Comment by janeczku** [comment]
@allingeek you rock! :clap: :mega:

**Comment by allingeek** [comment]
Can this be closed after the patch?

**Comment by nathanleclaire** [comment]
Yes I think so!
