### ISSUE TITLE
Problem volume mounting on Windows Docker Machine

### ISSUE THREAD

**Issue by donaldquixote** [docker/machine#2341]
When I run:

docker run ... -v /var/consul/data:/data ... 

I get:

"invalid value "C:\\Program Files\\Git\\var\\consul\\data;C:\\Program Files\\Git\\data;rw" for flag -v: bad mode specified: \Program Files\Git\data;rw"

It appears the docker CLI for windows is translating the paths to windows paths and then the colons following drive letters are interpreted as delimiters for the -v parameter.

**Comment by nathanleclaire** [comment]
Yes, git bash does some munging of the paths to ensure compatibility with UNIX programs, so it doesn't get literally translated.  If you truly want `/var/consul/data` in the VM to be mounted into the container, you could just run the `docker` command in question while `docker-machine ssh`ed into your VM.

**Comment by donaldquixote** [comment]
I did exactly that as a workaround, then later discovered that I could quote my paths and start with a double slash (e.g. "//var/consule/data") to prevent the translation.

It might be worth adding some notes somewhere in doc about caveats to running docker-machine on windows for those like myself that are less-experienced with git bash and such.

**Comment by nathanleclaire** [comment]
Oh, that's a nice trick.  I hadn't thought of that.  I do think a document with suggestions for Windows / the general setup is a good idea.
