### ISSUE TITLE
docker-machine rm should ask for confirmation

### ISSUE THREAD

**Issue by schmunk42** [docker/machine#2349]
I think that `docker-machine` should ask the user to confirm the operation before removing a machine, unless `-f` is specified. Basically same as `docker-compose rm`.

Current output:

    $ docker-machine rm dev1
    Successfully removed dev

Expected output:

    $ docker-machine rm dev1
    Do you really want to remove dev? [y/N] <enter>
    Operation aborted.

Version: `docker-machine version 0.5.0 (04cfa58)`

**Comment by jeanlaurent** [comment]
I understand we may need a some sort  of confirmation.
The `-f` flag though has another meaning for now : it means, destroy locally the information on the remote host even in the case I can't reach it.

But I think this is a good idea with another flag name for instance: `-y` to bypass the confirmation.

What the other @docker/machine-maintainers think ?

**Comment by nathanleclaire** [comment]
Similar to https://github.com/docker/machine/issues/1179 and yes, I think a prompt would solve the issue.

**Comment by askb** [comment]
#dibs if no one else is working on this issue.

**Comment by jeanlaurent** [comment]
@askb go ahead.

If you need review and/or direction, feel free to ping @docker/machine-maintainers

**Comment by askb** [comment]
@jeanlaurent thanks.
Please review and provide comments.
//cc @docker/machine-maintainers
