### ISSUE TITLE
Renaming machines

### ISSUE THREAD

**Issue by rawtaz** [docker/machine#2354]
It would be handy to have the ability to rename machines, but it seems that's not possible currently. Has there been any work done on this, or thoughts on it?

Looking at a VMware Fusion backed VM it seem there's a bunch of places/references that would need to be changed from the old to the new name, and I realize there's probably a lot more to it when it comes to other drivers too.

**Comment by nathanleclaire** [comment]
Long story short, I think it's very difficult, especially to do across all drivers.  How would you expect Machine to behave in the case that a rename is requested for a cloud server?  In the case where configs are shared across machines?

**Comment by rawtaz** [comment]
Yes, that's pretty much the summary. Quite a lot of work and things to figure out, so probably not worth it overall.

The answer to your questions are "it depends on what the cloud service supports" and "whatever is needed, as long as it's possible of course".

Was just curious. Feel free to close the issue.


20 nov 2015 kl. 00:33 skrev Nathan LeClaire <notifications@github.com>:

**Comment by nathanleclaire** [comment]
Will close -- Thanks for the contribution @rawtaz
