### ISSUE TITLE
VMWareVSphere driver confuses Datastore with Datacenter

### ISSUE THREAD

**Issue by manei** [docker/machine#2358]
While using docker-machine with vsphere driver to deploy docker swarm into a VCenter Server it throws:

Error creating machine: Error in driver during machine creation: Unable to upload on datastore <datacenter-name> due to Error: ServerFaultCode: Permission to perform this operation was denied.

I double checked and I did no mistake while building the command.

**Comment by kel0o** [comment]
And the issue is in vc_conn.go line 85:

return errors.NewDatastoreError(conn.driver.Datacenter, "upload", stderr)

So actually I really don't have Permissions? Weird. I'll look more into it.

**Comment by frapposelli** [comment]
The error you get means you don't have sufficient privileges to upload an ISO on a datastore.

**Comment by dgageot** [comment]
@manei @frapposelli Is there something we can improve or shall we just close the ticket?

**Comment by frapposelli** [comment]
@dgageot this is a permission problem, no way to improve around it.

**Comment by manei** [comment]
It can be closed, I think the code was rewritten, I cannot find the problem anymore. The problem was not about the permission was about the actual error it shows: was showing that I did not have permissions to upload on datastore where in fact I hadn't permissions on Datacenter. Which was a little misleading.
