### ISSUE TITLE
Upgrade from v0.3.1 to v0.5.1 breaks configs

### ISSUE THREAD

**Issue by gimoh** [docker/machine#2360]
After upgrading directly from v0.3.1 to v.0.5.1 I was getting an error when trying to run any docker-machine command (e.g. env):

    $  docker-machine --version
    docker-machine version 0.5.1 (7e8e38e)
    $
    $ docker-machine --debug env pdock02
    Docker Machine Version: 0.5.1 (7e8e38e)
    Migrating to config v0
    Migrating to config v1
    Migrating to config v2
    Found binary path at /usr/local/bin/docker-machine-driver-generic
    Launching plugin server for driver generic
    Plugin server listening at address 127.0.0.1:33208
    () Calling RPCServerDriver.GetVersion
    Using API Version 1
    () Calling RPCServerDriver.SetConfigRaw
    () Calling RPCServerDriver.GetMachineName
    (pdock02) Calling RPCServerDriver.GetState
    (pdock02) Calling RPCServerDriver.GetURL
    Reading CA certificate from 
    Error running connection boilerplate: Error checking and/or regenerating the certs: There was an error validating certificates for host "10.0.0.161:2376": open : no such file or directory
    You can attempt to regenerate them using 'docker-machine regenerate-certs name'.
    Be advised that this will trigger a Docker daemon restart which will stop running containers.

Turned out after the migration values for many settings including paths to keys and certificates disappeared, i.e. the config.json now looks like this:

    {
        "ConfigVersion": 3,
        "Driver": {
            "IPAddress": "10.0.0.161",
            "MachineName": "pdock02",
            "SSHUser": "user",
            "SSHPort": 22,
            "SSHKeyPath": "",
            "StorePath": "/opt/app/.docker/machine",
            "SwarmMaster": false,
            "SwarmHost": "",
            "SwarmDiscovery": "",
            "URL": ""
        },
        "DriverName": "generic",
        "HostOptions": {
            "Driver": "",
            "Memory": 0,
            "Disk": 0,
            "EngineOptions": {
                "ArbitraryFlags": null,
                "Dns": null,
                "GraphDir": "",
                "Env": null,
                "Ipv6": false,
                "InsecureRegistry": null,
                "Labels": null,
                "LogLevel": "",
                "StorageDriver": "",
                "SelinuxEnabled": false,
                "TlsVerify": true,
                "RegistryMirror": null,
                "InstallURL": "https://get.docker.com"
            },
            "SwarmOptions": {
                "IsSwarm": false,
                "Address": "",
                "Discovery": "",
                "Master": false,
                "Host": "",
                "Image": "",
                "Strategy": "",
                "Heartbeat": 0,
                "Overcommit": 0,
                "ArbitraryFlags": null,
                "Env": null
            },
            "AuthOptions": {
                "CertDir": "certs",
                "CaCertPath": "",
                "CaPrivateKeyPath": "",
                "CaCertRemotePath": "",
                "ServerCertPath": "",
                "ServerKeyPath": "",
                "ClientKeyPath": "",
                "ServerCertRemotePath": "",
                "ServerKeyRemotePath": "",
                "ClientCertPath": "",
                "StorePath": "."
            }
        },
        "Name": "pdock02",
        "RawDriver": "OMITTED"
    }

If I upgrade to v0.4.1 first and then to v0.5.1 the values are preserved and everything works OK.

**Comment by nathanleclaire** [comment]
If I recall correctly, we actually made a mistake by having a breaking change not covered by a migration in the 0.4.0 => 0.4.1 transition without realizing it.  So, sad to say, due to errors in the past, I think this is not fixable.  I'm really sorry about it.  We've not had an official backwards compatibility policy and try our best to preserve compatibility from version to version but migrating bigger jumps like this is trickier.

**Comment by nathanleclaire** [comment]
Thanks for the report though!  Hope you are enjoying Machine.

**Comment by gimoh** [comment]
No worries, fortunately I had everything under VCS control so it was simple enough to revert and play around to figure out what's going on.

Wondering if a line in release notes would be helpful to others?

**Comment by nathanleclaire** [comment]
@gimoh What kind of line did you have in mind?

**Comment by gimoh** [comment]
Something along the lines of "If upgrading from versions < 0.4 make sure to install 0.4.1 first, run `docker-machien ls` and then install latest.  This will ensure your configuration files are properly migrated without errors."
