### ISSUE TITLE
Update base images for core drivers to use Ubuntu 15.10

### ISSUE THREAD

**Issue by nathanleclaire** [docker/machine#2361]
Now that we have support for it in the main Machine binary, I'd suggest that we update our core drivers to default to Ubuntu 15.04 instead of Ubuntu 14.04.

cc @docker/machine-maintainers

**Comment by dgageot** [comment]
I'm all for it. However, I tested the google driver with a 15.04 and the time to create a VM goes from less than 2 minutes to more than 5 minutes. I will investigate tomorrow

**Comment by nathanleclaire** [comment]
Cool, yes, that would indeed be annoying.  If the fault is on our end, we can fix it, and if the fault lies with the Docker project install script, we'll file an issue.

**Comment by dgageot** [comment]
I confirm that with google driver, using the `15.04` image is much longer than with `14.04` image. Mainly because `aufs` support is already installed in the `14.04` image.

**Comment by nathanleclaire** [comment]
Hm, that's really unfortunate.  I wonder how things look for the other drivers.  I'll give DigitalOcean and AWS a whirl and get back to you.

**Comment by trecloux** [comment]
With exoscale driver :
* 14.04 : 2m11s
* 15.04 : 2m30s
* 15.10 : 2m22s
I tested only once each version, not sure the if differences are caused by the provisioner .

**Comment by trecloux** [comment]
With AWS driver :
* 14.04 : 10m44s / 8m53s / 5m41s
* 15.04 : 5m5s / 4m54s / 4m38s

**Comment by dgageot** [comment]
Thanks @trecloux! Do you mind submitting PRs to update the default images in those drivers?

**Comment by trecloux** [comment]
Ok, yes I will.
Could we directly jump to 15.10 ?

**Comment by dgageot** [comment]
@trecloux I guess we could. @nathanleclaire wdyt?

**Comment by nathanleclaire** [comment]
Jumping to 15.10 as a new default seems reasonable to me.

**Comment by trecloux** [comment]
Do you know how to find AWS EC2 image Ids for zones us-gov-west-1 and cn-north-1 ?

**Comment by nathanleclaire** [comment]
@trecloux I think both should show up using https://cloud-images.ubuntu.com/locator/ec2/

**Comment by trecloux** [comment]
I've branches with changes needed for amazon, exoscale, azure, rackspace and digital ocean.
 @dgageot are you taking care of google ?
Do you want me to submit one pull request per driver or a grouped one ?
Could you also please rename the issue ?

**Comment by jeanlaurent** [comment]
@trecloux Grouped one will do, since they are all the same purpose.

**Comment by dgageot** [comment]
@trecloux Please take care of Google :-)

**Comment by trecloux** [comment]
Ok, will update the PR
