### ISSUE TITLE
[VirtualBox] Kill + Start = Hang + Crash

### ISSUE THREAD

**Issue by jeanlaurent** [docker/machine#2371]
Sounds like a "killed" machine can't reliably start afterwards.

@dgageot reports that if you CTRL-C during the hang while trying to start and launch the start command again it may succeed to start

```
> docker-machine create -d virtualbox tobekilled
../...

> docker-machine kill tobekilled

> docker-machine start tobekilled
(tobekilled) Starting VM...
Too many retries waiting for SSH to be available.  Last error: Maximum number of retries (60) exceeded

> docker-machine ls
error getting URL for host tobekilled: Something went wrong running an SSH command!
command : ip addr show dev eth1
err     : exit status 255
output  :

NAME         ACTIVE   DRIVER       STATE     URL                         SWARM
default      *        virtualbox   Running   tcp://192.168.99.100:2376   
fromhome     -        virtualbox   Running   tcp://192.168.99.127:2376   
tobekilled   -        virtualbox   Running
```

**Comment by dgageot** [comment]
I've run more tests and in fact **no** I couldn't find a way to make it work.

**Comment by dgageot** [comment]
This scenario seems to be working very well with `VirtualBox 4.3.34`...

**Comment by dgageot** [comment]
It is hanging on `VirtualBox 5.0.8` and `VirtualBox 5.0.10`

**Comment by nathanleclaire** [comment]
Sounds like we may want to file or +1 a bug upstream with Oracle on this sequence of commands.

**Comment by jeanlaurent** [comment]
While trying to gather some data on this issue we found out that we couldn't reproduce error again with the new codebase on VirtualBox `5.0.8` as well with `5.0.10`

Closing for now. Feel free to re-open if you can reproduce it.
