### ISSUE TITLE
Same IP of HostOnly Controller after restart

### ISSUE THREAD

**Issue by stemau98** [docker/machine#2378]
Docker Toolbox 1.9d
Docker version 1.9.0, build 76d6bc9
docker-machine.exe version 0.5.1 (7e8e38e)
Windows 8.1 64bit

I followed exactly the tutorial to get a multi host network: https://docs.docker.com/engine/userguide/networking/get-started-overlay/

First time everything worked fine, but after I stopped and started all there machines again every machine created a new host-only controller and all get the same IP.

docker-machine ls
NAME         ACTIVE   DRIVER       STATE     URL                                    SWARM
demo-master    -        virtualbox   Running   tcp://192.168.99.100:2376   demo-master (master)
demo-node01   -        virtualbox   Running   tcp://192.168.99.100:2376   demo-master
keystore            -        virtualbox   Running   tcp://192.168.99.100:2376

I think this is a bug! Maybe anyone else could test this

update: I maybe have a explanation why this happens. I have multiple HostOnly Adapters and the machines where first time started with HostOnly#5. At restart the machines don't use this Adapter they created a new for every single machine.  

And I get this error:
Error running connection boilerplate: Error checking and/or regenerating the certs: There was an error validating certificates for host "192.168.99.100:3376": dial tcp 192.168.99.100:3376: i/o timeout
You can attempt to regenerate them using 'docker-machine regenerate-certs name'.
Be advised that this will trigger a Docker daemon restart which will stop running containers.

**Comment by dgageot** [comment]
Fixed in https://github.com/docker/machine/pull/2797
