### ISSUE TITLE
docker push returns "invalid argument"

### ISSUE THREAD

**Issue by Leland-Takamine** [docker/machine#239]
I've followed the instructions [here](https://github.com/docker/machine) and most of the functionality is working, but I run into the following issue when I try to push an image.

**docker push**
```
$ docker push leland/helloserver
The push refers to a repository [leland/helloserver] (len: 1)
Sending image list
Pushing repository leland/helloserver (1 tags)
511136ea3c5a: Image already pushed, skipping
16386e29a1f4: Image already pushed, skipping
835c4d274060: Image already pushed, skipping
22c23ce0a90c: Image already pushed, skipping
3f1e6432f26e: Image already pushed, skipping
7982826b1e59: Image already pushed, skipping
1dafbd563f5a: Image already pushed, skipping
7a94d87545e8: Image already pushed, skipping
e2d60f7b3d07: Image already pushed, skipping
4f23222e2f74: Image already pushed, skipping
258b590ccdee: Image already pushed, skipping
986643313a7b: Image already pushed, skipping
1ea210e0e1f6: Image already pushed, skipping
cd960d5841ca: Pushing 5.632 kB/5.632 kB
FATA[0026] invalid argument
```

**machine ls**
```
$ machine ls
NAME   ACTIVE   DRIVER         STATE     URL
dev    *        virtualbox     Running   tcp://192.168.99.100:2376
```

**docker version**
```
$ docker version
Client API version: 1.16
Go version (client): go1.3.3
OS/Arch (client): darwin/amd64
Server version: 1.3.1-dev
Server API version: 1.16
Go version (server): go1.3.3
Git commit (server): 0876d6b
```

**docker info**
```
$ docker info
Containers: 11
Images: 55
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Dirs: 77
Execution Driver: native-0.2
Kernel Version: 3.13.0-40-generic
Operating System: Ubuntu 14.04.1 LTS
CPUs: 1
Total Memory: 490 MiB
Name: docker
ID: JGGE:HM25:MM2R:6OV3:P6HR:ZI6V:3F4I:4DHZ:N7B4:CPGS:GHQO:WLC2
Username: leland
Registry: [https://index.docker.io/v1/]
```

**Additional Information**
OS: Mac OS X Version 10.9.5
client: https://ejhazlett.s3.amazonaws.com/public/docker/darwin/docker-1.4.1-136b351e-identity

**Comment by ankushagarwal** [comment]
Is it reproducible (after a restart of the VM)?
ᐧ

On Wed, Jan 7, 2015 at 11:29 PM, Leland-Takamine <notifications@github.com>
wrote:

> I've followed the instructions here <https://github.com/docker/machine>
> and most of the functionality is working, but I run into the following
> issue when I try to push an image.
>
> *docker push*
>
> $ docker push leland/helloserver
> The push refers to a repository [leland/helloserver] (len: 1)
> Sending image list
> Pushing repository leland/helloserver (1 tags)
> 511136ea3c5a: Image already pushed, skipping
> 16386e29a1f4: Image already pushed, skipping
> 835c4d274060: Image already pushed, skipping
> 22c23ce0a90c: Image already pushed, skipping
> 3f1e6432f26e: Image already pushed, skipping
> 7982826b1e59: Image already pushed, skipping
> 1dafbd563f5a: Image already pushed, skipping
> 7a94d87545e8: Image already pushed, skipping
> e2d60f7b3d07: Image already pushed, skipping
> 4f23222e2f74: Image already pushed, skipping
> 258b590ccdee: Image already pushed, skipping
> 986643313a7b: Image already pushed, skipping
> 1ea210e0e1f6: Image already pushed, skipping
> cd960d5841ca: Pushing 5.632 kB/5.632 kB
> FATA[0026] invalid argument
>
> *machine ls*
>
> $ machine ls
> NAME   ACTIVE   DRIVER         STATE     URL
> dev    *        virtualbox     Running   tcp://192.168.99.100:2376
>
> *docker version*
>
> $ docker version
> Client API version: 1.16
> Go version (client): go1.3.3
> OS/Arch (client): darwin/amd64
> Server version: 1.3.1-dev
> Server API version: 1.16
> Go version (server): go1.3.3
> Git commit (server): 0876d6b
>
> *docker info*
>
> $ docker info
> Containers: 11
> Images: 55
> Storage Driver: aufs
>  Root Dir: /var/lib/docker/aufs
>  Dirs: 77
> Execution Driver: native-0.2
> Kernel Version: 3.13.0-40-generic
> Operating System: Ubuntu 14.04.1 LTS
> CPUs: 1
> Total Memory: 490 MiB
> Name: docker
> ID: JGGE:HM25:MM2R:6OV3:P6HR:ZI6V:3F4I:4DHZ:N7B4:CPGS:GHQO:WLC2
> Username: leland
> Registry: [https://index.docker.io/v1/]
>
> *Additional Information*
> OS: Mac OS X Version 10.9.5
> client:
> https://ejhazlett.s3.amazonaws.com/public/docker/darwin/docker-1.4.1-136b351e-identity
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/docker/machine/issues/239>.
>



-- 
Ankush Agarwal
http://ankush.io
@ankushio <https://twitter.com/ankushio>

*There are 10 types of people in this world. Those who understand binary
and those who don't.*

**Comment by Leland-Takamine** [comment]
Yes - I restarted the VM and am still getting the same error.
```
$ machine restart dev
INFO[0005] Waiting for VM to start...
$ docker push leland/helloserver
The push refers to a repository [leland/helloserver] (len: 1)
Sending image list
Pushing repository leland/helloserver (1 tags)
511136ea3c5a: Image already pushed, skipping
16386e29a1f4: Image already pushed, skipping
835c4d274060: Image already pushed, skipping
22c23ce0a90c: Image already pushed, skipping
3f1e6432f26e: Image already pushed, skipping
7982826b1e59: Image already pushed, skipping
1dafbd563f5a: Image already pushed, skipping
7a94d87545e8: Image already pushed, skipping
e2d60f7b3d07: Image already pushed, skipping
4f23222e2f74: Image already pushed, skipping
258b590ccdee: Image already pushed, skipping
986643313a7b: Image already pushed, skipping
1ea210e0e1f6: Image already pushed, skipping
cd960d5841ca: Pushing 5.632 kB/5.632 kB
FATA[0025] invalid argument
```
I'm also able to reproduce consistently on my Digital Ocean host.
```
$ machine active do1
$ docker push leland/helloserver
The push refers to a repository [leland/helloserver] (len: 1)
Sending image list
Pushing repository leland/helloserver (1 tags)
511136ea3c5a: Image already pushed, skipping
16386e29a1f4: Image already pushed, skipping
835c4d274060: Image already pushed, skipping
22c23ce0a90c: Image already pushed, skipping
3f1e6432f26e: Image already pushed, skipping
7982826b1e59: Image already pushed, skipping
1dafbd563f5a: Image already pushed, skipping
7a94d87545e8: Image already pushed, skipping
e2d60f7b3d07: Image already pushed, skipping
4f23222e2f74: Image already pushed, skipping
258b590ccdee: Image already pushed, skipping
986643313a7b: Image already pushed, skipping
1ea210e0e1f6: Image already pushed, skipping
cd960d5841ca: Pushing 5.632 kB/5.632 kB
FATA[0024] invalid argument
```

**Comment by Leland-Takamine** [comment]
Reported by another user here also: docker/docker#9691

**Comment by ehazlett** [comment]
Hmm that looks like a Docker issue.  Can you try another image to see if it does the same?

**Comment by Leland-Takamine** [comment]
Trying to push a different image. Still seeing the error when using machine.

**machine**
```
$ machine ls
NAME   ACTIVE   DRIVER         STATE     URL
dev    *        virtualbox     Running   tcp://192.168.99.100:2376

$ docker run --name test ubuntu

$ docker commit test leland/pushtest
ea07445bea316c8cca50b288194751e84cb747ea21328f60ff39f5cdf087d609

$ docker push leland/pushtest
The push refers to a repository [leland/pushtest] (len: 1)
Sending image list
Pushing repository leland/pushtest (1 tags)
511136ea3c5a: Image already pushed, skipping
3b363fd9d7da: Image already pushed, skipping
607c5d1cca71: Image already pushed, skipping
f62feddc05dc: Image already pushed, skipping
8eaa4ff06b53: Image already pushed, skipping
ea07445bea31: Pushing 1.024 kB/1.024 kB
FATA[0030] invalid argument
```

I can push successfully with Boot2Docker:

Standard **Boot2Docker**
```
$ docker version
Client version: 1.4.1
Client API version: 1.16
Go version (client): go1.3.3
Git commit (client): 5bc2ff8
OS/Arch (client): darwin/amd64
Server version: 1.4.1
Server API version: 1.16
Go version (server): go1.3.3
Git commit (server): 5bc2ff8

$ docker info
Containers: 119
Images: 505
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Dirs: 744
Execution Driver: native-0.2
Kernel Version: 3.16.7-tinycore64
Operating System: Boot2Docker 1.4.1 (TCL 5.4); master : 86f7ec8 - Tue Dec 16 23:11:29 UTC 2014
CPUs: 8
Total Memory: 1.961 GiB
Name: boot2docker
ID: LHKW:43TA:UKCV:ZP4E:66HD:4IHX:FL52:SGLY:FYLT:RQBC:5KLA:YNKZ
Debug mode (server): true
Debug mode (client): false
Fds: 11
Goroutines: 13
EventsListeners: 0
Init Path: /usr/local/bin/docker
Docker Root Dir: /mnt/sda1/var/lib/docker
Username: leland
Registry: [https://index.docker.io/v1/]

$ docker run --name test ubuntu

$ docker commit test leland/pushtest
8163e77d5e644f1789bdc7f377019cea30b7f653df92cf00d713906620cb0a66

$ docker push leland/pushtest
The push refers to a repository [leland/pushtest] (len: 1)
Sending image list
Pushing repository leland/pushtest (1 tags)
511136ea3c5a: Image already pushed, skipping
fe95bf7d5f50: Image already pushed, skipping
9a4594fe74ea: Image already pushed, skipping
8c4b1edcceea: Image already pushed, skipping
ed5a78b7b42b: Image already pushed, skipping
8163e77d5e64: Image successfully pushed
Pushing tag for rev [8163e77d5e64] on {https://cdn-registry-1.docker.io/v1/repositories/leland/pushtest/tags/latest}
```

**Comment by ehazlett** [comment]
Ok perhaps this was an older bug that is in the custom Docker build.  I'm
guessing that's it.  We are refactoring to support TLS so this should be
fixed soon.

**Comment by Leland-Takamine** [comment]
Awesome, thanks for the quick responses! Do you have a estimated timeline for the next release?

**Comment by Leland-Takamine** [comment]
For the record, I've tested with a build from #255 and it seems to fix this issue.

**Comment by ehazlett** [comment]
awesome.  looks like that was it.  i will leave this open until we merge
#255.

thanks!
