### ISSUE TITLE
Openstack change password.. need to update docker-machine openstack password ??

### ISSUE THREAD

**Issue by sebmoule** [docker/machine#2395]
Hi guys,

I have changed my Openstack password, and then my account has been blocked in openstack.

I have made a docker-machine ls which has also blocked my password in Openstack so I will need to change it again..
```
"component": "IAM","message": "Password is locked","additionalInfo": "You or someone tried to connect too with wrong credentials several time. You can unlock it by reseting your password"}
```

Is there another way to use a token instead of password for calling openstack ?

If I change my password in openstack, it seams that docker-machine continue to uses the old one and make a lock again on my openstack account ==> is there a way to update my openstack password within docker-machine ?

thanks

sébastien

**Comment by nathanleclaire** [comment]
cc @ggiamarchi

**Comment by fsoppelsa** [comment]
@sebmoule changing credentials in ~/.docker/machine/machines/<machine>/config.json doesn't help?
I'm not totally sure this trick could work, but you can try.

**Comment by sebmoule** [comment]
Yes I thinks it would be a palliatif, but i'm not satisfied with this

**Comment by fsoppelsa** [comment]
Can you elaborate a bit your expectation here? What I can think about is some `update` command, but still, DM hasn't such.

**Comment by fsoppelsa** [comment]
@sebmoule did the trick work? Just for curiosity

**Comment by sebmoule** [comment]
Hi @fsoppelsa Thanks a lot it works now like a charm !!

**Comment by nathanleclaire** [comment]
Sounds like this issue is closed!  Thanks @fsoppelsa @sebmoule
