### ISSUE TITLE
vmwarevsphere requires datacenter to be set

### ISSUE THREAD

**Issue by pandrew** [docker/machine#240]
I cant connect directly to the esxi without machine requiring --vmwarevsphere-datacenter to be set. In debug mode when using the govc command and removeing the option for datacenter it works.

**Comment by frapposelli** [comment]
Sorry, forgot to include that in the doc, when connecting to a single ESXi host Datacenter should be set to: ha-datacenter

Will send a PR tomorrow for that.

**Comment by ehazlett** [comment]
@frapposelli thx!

**Comment by pandrew** [comment]
Seems to work.
