### ISSUE TITLE
Different certs between localhost and created machine

### ISSUE THREAD

**Issue by lucj** [docker/machine#2405]
Hi,
I have created a swarm on virtualbox (with machine) and encounter this error message when using Interlock.
        
    "Get https://192.168.99.114:2376/v1.15/events: remote error: bad certificate"

My swarm is composed of:
- consul kv
- swarm master n0
- swarm agent n1

On my local folder, in ~/.docker/machine/machines/n0 I have some *.pem that are not the same as in /home/docker/.docker within n0

    # On Localhost
    luc ~/.docker/machine/machines/n0 [] $ ls -lrt
    total 3854272
    -rw-------  1 luc  staff         381 24 nov 20:37 id_rsa.pub
    -rw-------  1 luc  staff        1679 24 nov 20:37 id_rsa
    -rw-------  1 luc  staff    31457280 24 nov 20:37 boot2docker.iso  
    drwx------  5 luc  staff         170 24 nov 20:37 n0
    -rw-r--r--  1 luc  staff        1107 24 nov 20:38 server.pem
    -rw-------  1 luc  staff        1675 24 nov 20:38 server-key.pem
    -rw-------  1 luc  staff        1675 24 nov 20:38 key.pem  // not the same
    -rw-r--r--  1 luc  staff        1046 24 nov 20:38 cert.pem // not the same
    -rw-r--r--  1 luc  staff        1021 24 nov 20:38 ca.pem  // Same on localhost and on machine created
    -rw-------  1 luc  staff        3269 24 nov 20:39 config.json
    -rw-------  1 luc  staff  1941897216 24 nov 21:03 disk.vmdk

    # On the swarm master
    docker@n0:~/.docker$ ls -lrt
    total 12
    -rw-------    1 docker   staff         1679 Nov 24 19:38 key.pem
    -rw-r--r--    1 docker   staff         1070 Nov 24 19:38 cert.pem
    -rw-r--r--    1 docker   staff         1021 Nov 24 19:38 ca.pem
    docker@n0:~/.docker$

Only ca.pem is the same but key.pem and cert.pem are not the same.
Any idea of why the certs are not the same ?

**Comment by lucj** [comment]
would you have a workaround for this problem ? Seems like deleting the machines and recreating them do not solve the thing.

**Comment by nathanleclaire** [comment]
The cert files used should be in `/var/lib/boot2docker`.  The ones in `~/.docker` are a relic of the way that `boot2docker-cli` used to do cert generation.

**Comment by nathanleclaire** [comment]
Can you provide more steps to reproduce, e.g. `create` commands and `docker run` commands for interlock, etc. please?

**Comment by lucj** [comment]
@nathanleclaire, no problem, I use those files to build the swarm and run the app:

docker-compose.yml

    interlock:
      image: ehazlett/interlock
      ports:
        - "80:80"
      volumes:
        - /home/docker/.docker:/etc/docker
      command: "--swarm-url tcp://SWARM_MASTER_IP:2376 --swarm-tls-ca-cert=/etc/docker/ca.pem --swarm-tls-cert=/etc/docker/cert.pem --swarm-tls-key=/etc/docker/key.pem --plugin haproxy start"
    db:
      image: mongo:3.0
      command: "--storageEngine wiredTiger"
      environment:
        - "constraint:node==n0"
    api:
      image: lucj/message-app:v5
      environment:
        - MONGO_URL=mongodb://virtualbox_db_1:27017/messageApp
        - INTERLOCK_DATA={"hostname":"api","domain":"message-app.com"}

init.sh

    # KV Store  
    docker-machine create -d virtualbox consul  
    eval "$(docker-machine env consul)"
    docker run -d -p "8500:8500" -h "consul" progrium/consul -server -bootstrap
    
    # Swarm master
    docker-machine create \
    -d virtualbox \
    --swarm \
    --swarm-master \
    --swarm-discovery="consul://$(docker-machine ip consul):8500" \
    --engine-opt="cluster-store=consul://$(docker-machine ip consul):8500" \
    --engine-opt="cluster-advertise=eth1:2376" \
    n0
    
    # Swarm node
    docker-machine create -d virtualbox \
    --swarm \
    --swarm-discovery="consul://$(docker-machine ip consul):8500" \
    --engine-opt="cluster-store=consul://$(docker-machine ip consul):8500" \
    --engine-opt="cluster-advertise=eth1:2376" \
    n1
    
    echo
    echo "modify docker-compose.yml with correct SWARM_MASTER_ID $(docker-machine ip n0) and run the following commands"
    echo
    echo 'eval $(docker-machine env --swarm n0)'
    echo 'docker-compose --x-networking --x-network-driver=overlay up'
    echo

**Comment by nathanleclaire** [comment]
If you change this in your Compose does it work:

```diff
interlock:
  image: ehazlett/interlock
  ports:
    - "80:80"
  volumes:
+    - /home/docker/.docker:/etc/docker
-    - /var/lib/boot2docker:/etc/docker
  command: "--swarm-url tcp://SWARM_MASTER_IP:2376 --swarm-tls-ca-cert=/etc/docker/ca.pem --swarm-tls-cert=/etc/docker/cert.pem --swarm-tls-key=/etc/docker/key.pem --plugin haproxy start"
db:
  image: mongo:3.0
  command: "--storageEngine wiredTiger"
  environment:
    - "constraint:node==n0"
api:
  image: lucj/message-app:v5
  environment:
    - MONGO_URL=mongodb://virtualbox_db_1:27017/messageApp
    - INTERLOCK_DATA={"hostname":"api","domain":"message-app.com"}
```

**Comment by lucj** [comment]
@nathanleclaire 

Using the modified volume and changing the name of the key (server-key.pem instead of the previous key.pem, the one used in /home/docker/.docker) fixed the thing:

    interlock:
      image: ehazlett/interlock
      ports:
        - "80:80"
      volumes:
        - /var/lib/boot2docker:/etc/docker
      command: "--swarm-url tcp://192.168.99.101:2376 --swarm-tls-ca-cert=/etc/docker/ca.pem --swarm-tls-cert=/etc/docker/server.pem --swarm-tls-key=/etc/docker/server-key.pem --plugin haproxy start"
    db:
      image: mongo:3.0
      command: "--storageEngine wiredTiger"
      environment:
        - "constraint:node==n0" 
    api:
      image: lucj/message-app:v5
      environment:
        - MONGO_URL=mongodb://virtualbox_db_1:27017/messageApp
        - INTERLOCK_DATA={"hostname":"api","domain":"message-app.com"}

Thanks a lot

**Comment by nathanleclaire** [comment]
Glad to hear it worked out for you @lucj
