### ISSUE TITLE
docker ps failed in a new "machine"

### ISSUE THREAD

**Issue by klaus1982** [docker/machine#2407]
Docker Version:

    docker --version
    Docker version 1.9.1, build a34a1d5

Docker Machine Version:

    docker-machine version 0.5.1 (7e8e38e)

Virtualbox Driver:

    Oracle VM VirtualBox Manager 4.3.10_Ubuntu

Output of `docker ps`

```
klaus@klaus-OptiPlex-780:~/Workspace/daas$ docker-machine env devenv
export DOCKER_TLS_VERIFY="1"
export DOCKER_HOST="tcp://192.168.99.100:2376"
export DOCKER_CERT_PATH="/home/klaus/.docker/machine/machines/devenv"
export DOCKER_MACHINE_NAME="devenv"
# Run this command to configure your shell: 
# eval "$(docker-machine env devenv)"
klaus@klaus-OptiPlex-780:~/Workspace/daas$ eval(docker-machine env devenv)
-bash: syntax error near unexpected token `docker-machine'
klaus@klaus-OptiPlex-780:~/Workspace/daas$ eval $(docker-machine env devenv)
klaus@klaus-OptiPlex-780:~/Workspace/daas$ docker ps
An error occurred trying to connect: Get https://192.168.99.100:2376/v1.21/containers/json: EOF
```

**Comment by dgageot** [comment]
Hi @klaus1982 can you tell us which driver you used to create the machine? Thank you.

**Comment by klaus1982** [comment]
@dgageot the driver is virtualbox, the version is `4.3.10_Ubuntu`. I also update those info in description.

**Comment by klaus1982** [comment]
Any input?

**Comment by dgageot** [comment]
Hi @klaus1982 You should try docker-machine 0.6.0. It fixes a lot of issues with virtualbox. Also, upgrading Virtualbox to 5.0.14 could help

**Comment by klaus1982** [comment]
It works now, I think we can close this issue now.
