### ISSUE TITLE
generic driver: since aufs is not supported on btrfs, the default storage driver should be btrfs on such a system

### ISSUE THREAD

**Issue by robvanmieghem** [docker/machine#2411]
When creating a docker machine using the generic driver and you do not pass the storage driver explicitly, aufs is set in the docker daemon configuration.

For example, on an ubuntu-systemd target system, the docker.service contains:
```
[Service]
ExecStart=/usr/bin/docker -d -H tcp://0.0.0.0:2376 -H unix:///var/run/docker.sock --stor
age-driver aufs --tlsverify --tlscacert /etc/docker/ca.pem --tlscert /etc/docker/server.
pem --tlskey /etc/docker/server-key.pem --label provider=generic
```

This errors out since aufs on btrfs is a non supported setup:
```
docker[2969]: time="2015-11-25T16:49:49.636299049+01:00" level=fatal msg="Error starting daemon: error initializing graphdriver: backing file system is unsupported for this graph driver"
```

So instead of configuring the daemon to use aufs, it would be better to detect the btrfs and use that driver when creating a docker machine without having to explicitly set the storage driver to btrfs on the docker-machine commandline.

Version: master branch, released versions (tested with 0.5.0 and 0.5.1) do not work on systemd-ubuntu 15.10

**Comment by nathanleclaire** [comment]
How to detect that such a machine is using `btrfs` already?

**Comment by robvanmieghem** [comment]
The way the aufs graphdriver in the docker daemon detects it is running on an incompatible filesystem:
https://github.com/docker/docker/blob/master/daemon/graphdriver/aufs/aufs.go#L92

So the actual filesystem detection: https://github.com/docker/docker/blob/master/daemon/graphdriver/driver_linux.go

I'll see if I have time to create a patch this evening or tomorrow.
