### ISSUE TITLE
On fish shell docker-machine config does not work

### ISSUE THREAD

**Issue by jake-low** [docker/machine#2415]
When running `docker-machine config <name>`, the output usually looks like:

```
--tlsverify --tlscacert="/Users/jake/.docker/machine/certs/ca.pem" --tlscert="/Users/jake/.docker/machine/certs/cert.pem" --tlskey="/Users/jake/.docker/machine/certs/key.pem" -H=tcp://192.168.99.100:2376
```

The primary use case for this feature is to use it in a command substitution, like this:

```
docker $(docker-machine config <name>) run ...
```

The trouble with space-separating is that not all shells perform word splitting on spaces by default. While `sh`, `bash`, and `zsh` split on all whitespace (`\s`, `\t`, or `\n`) by default, `fish` splits only on newlines. This is a design decision to help reduce script bugs caused by filenames containing spaces.

Since most common shells will split arguments on newlines (to my knowledge `ksh` and even `csh`/`tcsh` do this also), I think it's more portable to have `docker-machine config` output each argument separated by a newline instead of a space.

As a bonus, this makes grepping the output easier.

**Comment by jeanlaurent** [comment]
Did I understand correctly if I say that `docker $(docker-machine config <name>) run ...` does not work in fish but potentially everywhere else ?

**Comment by jake-low** [comment]
Correct. The command syntax in fish actually drops the `$`, but the idea's the same.

```
$ docker (docker-machine config default) run centos:6 ls
flag provided but not defined: --tlsverify --tlscacert
```

`docker` receives a single argument `--tlsverify --tlscacert=...` when it should get four args, `--tlsverify`, `--tlscacert="/Users/..."`, etc. This is because fish doesn't tokenize the output of subcommands on spaces, only on newlines.

**Comment by tuxknight** [comment]
My docker-machine on Mac OS X  support fish.
The output of docker-machine env default:
```
 ><((("> Eason@iDocker: ~ => docker-machine env default                                          ~
set -x DOCKER_TLS_VERIFY "1";
set -x DOCKER_HOST "tcp://192.168.99.100:2376";
set -x DOCKER_CERT_PATH "/Users/Eason/.docker/machine/machines/default";
set -x DOCKER_MACHINE_NAME "default";
# Run this command to configure your shell: 
# eval (docker-machine env default)
```
docker-machine version 0.5.0 (04cfa58)   Mac OS X
Hope this will help.

**Comment by jeanlaurent** [comment]
@jake-low was talking about `docker-machine config` command. I believe `docker-machine env` and `docker-machine env -u` works correctly for the fish shell.

**Comment by jake-low** [comment]
@jeanlaurent: thanks for the fix!
