### ISSUE TITLE
docker-machine proxy settings

### ISSUE THREAD

**Issue by muthukn** [docker/machine#2418]
Hello,

I have set the docker proxy while creating the docker VM using the below command. 

$ docker-machine create -d virtualbox \
    --engine-env HTTP_PROXY=http://username:pwd@proxyhost:proxyport \
    --engine-env HTTPS_PROXY=https://username:pwd@proxyhost:proxyport \
    --engine-env NO_PROXY=dockerhostip \
    defaultVM

This works fine. But i could not find any option to reset this proxy user credentials in docker-machine. Is there a way to update the proxy details once the VM is created? Please assist.

Thanks

**Comment by nathanleclaire** [comment]
Not automatically, but for the time being you can edit the file generated at `/var/lib/boot2docker/profile` in the VM and `sudo /etc/init.d/docker restart` to restart the daemon.

**Comment by nathanleclaire** [comment]
e.g. 
```console
$ docker-machine ssh default -t sudo vi /var/lib/boot2docker/profile
$ docker-machine ssh default sudo /etc/init.d/docker restart
```

**Comment by nathanleclaire** [comment]
Going to close this -- some day I want a command to update this in place but I have other issues for that.

**Comment by muthukn** [comment]
Thanks. It helped me reset the proxy details and working fine.

**Comment by nathanleclaire** [comment]
@muthukn :+1:

**Comment by jp052** [comment]
Works now by changing the variables directly in config.json at:
`$HOME\.docker\machine\machines\myMachineName\config.json`
And after that running:
`docker provision myMachineName` 
or if default machine:
`docker provision`

**Comment by nathanleclaire** [comment]
@jp052 Nitpick: I think you mean `docker-machine provision`, not `docker provision`

**Comment by saites** [comment]
Further point of interest: I was consistently getting
`Error response from daemon: Get https://registry-1.docker.io/v2/: proxyconnect tcp: EOF.`
after reinstalling Docker Toolbox. There were various suggestions online about how to fix it, but I was not having any luck. 

The `config.json` file referenced above had my proxies already, in this format:
```json
        "EngineOptions": {
            "ArbitraryFlags": [],
            "Dns": null,
            "GraphDir": "",
            "Env": [
                "HTTP_PROXY=http://proxy.mycorp.com:XXX",
                "HTTPS_PROXY=https://proxy.mycorp.com:XXX",
                "NO_PROXY=localhost,127.0.0.1"
            ],

```

I removed the `http://` and `https://` prefixes from the variable values and ran `docker-machine provision`; it's now working again. 

I am not sure if this also made a difference, but in my attempts to get things working, I changed `Dns` to `["8.8.8.8"]`, restarted, then later removed it and restarted -- this was based on comments people had said fixed it for them, but this alone did not fix things for me.
