### ISSUE TITLE
machine creation failures on MacOS

### ISSUE THREAD

**Issue by DanLipsitt** [docker/machine#242]
## Description of problem
`machine` fails to create new virtualbox appliances.

## Environment
These are hard to collect because the identity build of docker isn't working for me (see #245). However, this bug seems to be in machine itself because the failure occurs during virtualbox creation.

`machine` commit is 5a251c5d. Version 0.0.2 fails as well. I've named my `machine` binary `docker-machine` because of #2.

### `docker version`:
```
Client API version: 1.16
Go version (client): go1.3.3
OS/Arch (client): darwin/amd64
FATA[0000] Get http://192.168.59.103:2376/v1.16/version: malformed HTTP response "\x15\x03\x01\x00\x02\x02". Are you trying to connect to a TLS-enabled daemon without TLS? 
```
(Using docker-1.4.1-136b351e-identity from the machine README)

### `docker info`:
```
FATA[0000] Get http://192.168.59.103:2376/v1.16/info: malformed HTTP response "\x15\x03\x01\x00\x02\x02". Are you trying to connect to a TLS-enabled daemon without TLS? 
```
### `uname -a`:
```
Darwin me.local 12.5.0 Darwin Kernel Version 12.5.0: Sun Sep 29 13:33:47 PDT 2013; root:xnu-2050.48.12~1/RELEASE_X86_64 x86_64
```
(MacOS 10.8.5)

## Steps to Reproduce
1. Download https://ejhazlett.s3.amazonaws.com/public/docker/darwin/docker-1.4.1-136b351e-identity
2.  `cp docker-1.4.1-136b351e-identity /usr/local/bin/docker`
4. `docker-machine create -d virtualbox dev`

### machine 0.0.2
```
$ docker-machine create -d virtualbox dev
INFO[0000] Downloading boot2docker... 
INFO[0029] Creating SSH key...                          
INFO[0029] Creating VirtualBox VM...                    
FATA[0037] VBoxManage hostonlyif ipconfig dyld: DYLD_ environment variables being ignored because main executable (/Applications/VirtualBox.app/Contents/MacOS/VBoxNetAdp --ip 192.168.99.1 --netmask 255.255.255.0 failed: exit status 2 
```
### machine 5a251c5d
```
$ docker-machine create -d virtualbox dev --debug
[...]
DEBU[0006] executing: VBoxManage hostonlyif ipconfig dyld: DYLD_ environment variables being ignored because main executable (/Applications/VirtualBox.app/Contents/MacOS/VBoxNetAdp --ip 192.168.99.1 --netmask 255.255.255.0 
VBoxManage: error: The host network interface with the given name could not be found
VBoxManage: error: Details: code NS_ERROR_INVALID_ARG (0x80070057), component Host, interface IHost, callee nsISupports
VBoxManage: error: Context: "FindHostNetworkInterfaceByName(name.raw(), hif.asOutParam())" at line 218 of file VBoxManageHostonly.cpp
VBoxManage: error: Could not find interface 'dyld: DYLD_ environment variables being ignored because main executable (/Applications/VirtualBox.app/Contents/MacOS/VBoxNetAdp'
ERRO[0006] Error creating host: VBoxManage hostonlyif ipconfig dyld: DYLD_ environment variables being ignored because main executable (/Applications/VirtualBox.app/Contents/MacOS/VBoxNetAdp --ip 192.168.99.1 --netmask 255.255.255.0 failed: exit status 2 
WARN[0006] Removing created machine. You can run machine with the --debug flag to avoid this. 
DEBU[0006] executing: VBoxManage showvminfo  --machinereadable 
WARN[0006] You will want to check the provider to make sure the machine and associated resources were properly removed. 
FATA[0006] Error creating machine                       
```

**Comment by SvenDowideit** [comment]
mmm, `DYLD_` env vars are a horror.

if you can unset both `DYLD_LIBRARY_PATH` and `LD_LIBRARY_PATH` in the shell you're running `machine` from it should work - in boot2docker, we have some code that tries, but we also manually unset it in the OSX script-applet.

```
virtualbox/vbm.go:              // remove DYLD_LIBRARY_PATH and LD_LIBRARY_PATH as they break VBoxManage on OSX
virtualbox/vbm.go:              os.Setenv("DYLD_LIBRARY_PATH", "")
```

this probably should be done in `machine` too - and I would do it for all drivers, cos its a pain to reproduce

**Comment by DanLipsitt** [comment]
I don't have either of those variables set in my shell:
```
$ env | grep -c LD
0
```

**Comment by DanLipsitt** [comment]
But just for good measure I tried
```
export DYLD_LIBRARY_PATH=""
export LD_LIBRARY_PATH=""
```
before running `docker-machine create -d virtualbox dev`. It didn't help.

**Comment by ehazlett** [comment]
@DanLipsitt could you try with a build from master to see if you still have this issue?  thx

**Comment by DanLipsitt** [comment]
Still fails with revision `0.0.2-158-gc2f1fea` (`docker-machine --version` lies and says just `0.0.2`):

```
DEBU[0007] executing: VBoxManage hostonlyif create      
0%...10%...20%...30%...40%...50%...60%...70%...80%...90%...100%
DEBU[0007] executing: VBoxManage hostonlyif ipconfig dyld: DYLD_ environment variables being ignored because main executable (/Applications/VirtualBox.app/Contents/MacOS/VBoxNetAdp --ip 192.168.99.1 --netmask 255.255.255.0 
VBoxManage: error: The host network interface with the given name could not be found
VBoxManage: error: Details: code NS_ERROR_INVALID_ARG (0x80070057), component Host, interface IHost, callee nsISupports
VBoxManage: error: Context: "FindHostNetworkInterfaceByName(name.raw(), hif.asOutParam())" at line 218 of file VBoxManageHostonly.cpp
VBoxManage: error: Could not find interface 'dyld: DYLD_ environment variables being ignored because main executable (/Applications/VirtualBox.app/Contents/MacOS/VBoxNetAdp'
ERRO[0007] Error creating host: VBoxManage hostonlyif ipconfig dyld: DYLD_ environment variables being ignored because main executable (/Applications/VirtualBox.app/Contents/MacOS/VBoxNetAdp --ip 192.168.99.1 --netmask 255.255.255.0 failed: exit status 2 
```

This is after setting the `LIBRARY_PATH` variables as above.

**Comment by DanLipsitt** [comment]
It also looks like those error messages are getting munged.

**Comment by ehazlett** [comment]
@DanLipsitt could you try this with the latest RC or master?  I'm thinking it won't because it looks VirtualBox related, but just to rule it out.  Thanks.

**Comment by DanLipsitt** [comment]
With v0.1.0-rc2:

```
$ docker-machine create -d virtualbox dev
INFO[0000] Creating SSH key...                          
INFO[0000] Creating VirtualBox VM...                    
ERRO[0006] Error creating machine: VBoxManage hostonlyif ipconfig dyld: DYLD_ environment variables being ignored because main executable (/Applications/VirtualBox.app/Contents/MacOS/VBoxNetAdp --ip 192.168.99.1 --netmask 255.255.255.0 failed: exit status 2 
WARN[0006] You will want to check the provider to make sure the machine and associated resources were properly removed. 
FATA[0006] Error creating machine
```

With master:
```
$ docker-machine create -d virtualbox dev
ERRO[0000] Error creating machine: hosts: Unknown driver "" 
WARN[0000] You will want to check the provider to make sure the machine and associated resources were properly removed. 
FATA[0000] Error creating machine 
```

**Comment by ehazlett** [comment]
Are you using any shell aliases?  What shell?  I'm not sure why that would
not see the driver name.

**Comment by Vrakfall** [comment]
I've got the same kind of issue after I installed `docker` and `boot2docker` with `Homebrew`. The installation went ok (after I fixed some directory ownership troubles because I messed it up once, I installed both homebrew and docker with sudo permissions which I shouldn't).

But then, when I type the command `docker version`, I get the same result :
```
$ docker version
Client version: 1.4.1
Client API version: 1.16
Go version (client): go1.4
Git commit (client): 5bc2ff8
OS/Arch (client): darwin/amd64
FATA[0000] Get http://192.168.59.103:2376/v1.16/version: malformed HTTP response "\x15\x03\x01\x00\x02\x02". Are you trying to connect to a TLS-enabled daemon without TLS?
```

I'm still trying to figure out what's happening and why.

**Comment by sthulb** [comment]
@ehazlett Can you check against master too? I remember bug in @codegansta/cli when Before was used on commands, it could interfere with that action. Perhaps this is a result of my last PR & an old version of @codegansta/cli being used

**Comment by ehazlett** [comment]
@Vrakfall this is almost always due to access the Docker host without the TLS settings.  Try using the `$(boot2docker shellinit)` also detailed here https://github.com/boot2docker/boot2docker/blob/master/README.md#tls-support.

Hope this helps!

**Comment by Vrakfall** [comment]
Yep, this helped a lot. It fixed my problem and even simplified my future work (I won't have to check the ip and the port of the new machine to fix the environment variable because it does it for me =D).

Thanks a lot !
(PS: I'm keeping your project in mind for later, I might need it in a close future.)

**Comment by ehazlett** [comment]
@Vrakfall awesome!  thanks for reporting back!

**Comment by DanLipsitt** [comment]
@ehazlett:
> Are you using any shell aliases?  What shell?

No aliases.

```
$ bash --version
GNU bash, version 3.2.53(1)-release (x86_64-apple-darwin12)
```

**Comment by ehazlett** [comment]
@DanLipsitt have you tried with a recent build from master?  I can provide pre-built if you just want to test.

**Comment by DanLipsitt** [comment]
Just tried with 4a81c4b17. No more "unknown driver" error, but I'm back to this:

```
ERRO[0009] Error creating machine: VBoxManage hostonlyif ipconfig dyld: DYLD_ environment variables being ignored because main executable (/Applications/VirtualBox.app/Contents/MacOS/VBoxNetAdp --ip 192.168.99.1 --netmask 255.255.255.0 failed: exit status 2 
```

I'm using this homebrew config:
Homebrew/homebrew-devel-only#11

**Comment by DanLipsitt** [comment]
I don't think it's the source of your error, but it looks like Godeps.json was [updated today](https://github.com/docker/machine/commit/cdd891ce7c0ef9474c7c60269414af317683bf67). I don't understand how we're supposed to keep `go_resources` up to speed. Seems like a losing battle. Is it okay to use `godep` directly since it already freezes dependencies?

**Comment by DanLipsitt** [comment]
Oops, please ignore previous comment, it was meant for the homebrew build script repo!

**Comment by ehazlett** [comment]
@DanLipsitt could you try the latest release (0.1.0) and see if a fresh machine still has the issue.  Thanks

**Comment by DanLipsitt** [comment]
Didn't work until I upgraded VirtualBox to the latest (4.3.22). It could have been just restarting VirtualBox that fixed it, but I'm not about to downgrade to find out.

**Comment by DanLipsitt** [comment]
Pull request for new homebrew package: https://github.com/Homebrew/homebrew-devel-only/pull/14

**Comment by ehazlett** [comment]
Cool -- yeah no way I would downgrade either ;)  Thx for the heads up -- I'll keep an eye out.

Thanks for the homebrew bump too!
