### ISSUE TITLE
Register existing docker host.

### ISSUE THREAD

**Issue by jeanlaurent** [docker/machine#2436]
We should allow users to easily register existing docker host/machine into a local docker-machine. This could probably be not too difficult if we follow the way the `generic` driver works. ie.: Give me ssh credentials and I setup a docker host.

This could be done with something like `docker-machine register polka --ip-address xx.xx.xx.xx` 
Or with the various option used by the generic driver : 
```
--generic-ip-address 										IP Address of machine
--generic-ssh-key "/Users/jlm/.ssh/id_rsa"					SSH private key path
--generic-ssh-port "22"										SSH port
--generic-ssh-user "root"									SSH user
  ```

btw, if you use the generic driver on an existing host, it will succesfully register the machine in docker-machine but at the expense of re-installing docker on the host.

This leads us to an interesting question : should we hack into the generic driver to allow not to re-install docker if it found it is already there, and just setup the certificates and register the docker host. Or should we have a dedicated command to this like the register one hinted above.

( the none diver as been in a distant path of some help on this, but the current code is broken in a way that it can't properly register existing host )

**Comment by jeanlaurent** [comment]
Closing as not relevant.

**Comment by yellowiscool** [comment]
Can you explain why it is not relevant? I would be interested by such a feature, to manipulate a Swarm cluster in an easy way from different computers. Today I connect to SSH to a "controller" having docker-machine instead of using docker-machine directly.
