### ISSUE TITLE
Proposal: Alter configuration of created machine

### ISSUE THREAD

**Issue by abejenaru** [docker/machine#2440]
In my opinion, it will be handy to be able to alter the config of an existing machine; I'm thinking especially of VM engine parameters like allocated memory or CPUs, and environment variables (proxies, etc.)

**Comment by jeanlaurent** [comment]
It's not exactly as the closed proposal for renaming docker machine #2354, but close.

Today, with most cloud provider altering the configuration ( cpus, memory) will involve restarting/recreating the machine. You can do this today by removing & recreating the machine with the proper configuration. We will *not* support this in the near future.

Your proposal seems valid for environment variables, though. Being able to add them afterwards without crashing the whole instance sounds like useful in a couple of scenarios.

**Comment by kunalkushwaha** [comment]
Maybe this can be handled with Issue https://github.com/docker/machine/issues/773,
A draft PR https://github.com/docker/machine/pull/2422 is in progress. 

Machine configuration with multiple version is also one point in this discussion.
And this issue can be solved with that.

**Comment by abejenaru** [comment]
The draft PR sound good! Looking forward!
