### ISSUE TITLE
Command scp being called twice

### ISSUE THREAD

**Issue by klmcwhirter** [docker/machine#2444]
I believe 8a452a9629969b5368aace64df8e296a506c5156 introduced a regression where the files are copied twice.

Being called like this:
docker-machine scp -r www machine-name:/www

These are the lines introduced. This looks like a merged copy from the previous commit and earlier commits. Note that runCmdWithStdio is run twice if there is no err.

73	if err := runCmdWithStdIo(*cmd); err != nil {
74			return err
75		}
76	
77		return runCmdWithStdIo(*cmd)

**Comment by dgageot** [comment]
Oh yes you are right! I'll fix that

**Comment by jeanlaurent** [comment]
This has been fixed with PR #2452
