### ISSUE TITLE
identity-enabled docker can't connect

### ISSUE THREAD

**Issue by DanLipsitt** [docker/machine#245]
## Description of problem
 `docker-1.4.1-136b351e-identity` from the machine README fails to connect to my existing running boot2docker instance. Since this binary seems to be created specifically for use with `machine` I'm filing the but here instead of at docker/docker. Apologies if this is the wrong place.

### `docker version`:
```
Client API version: 1.16
Go version (client): go1.3.3
OS/Arch (client): darwin/amd64
FATA[0000] Get http://192.168.59.103:2376/v1.16/version: malformed HTTP response "\x15\x03\x01\x00\x02\x02". Are you trying to connect to a TLS-enabled daemon without TLS? 
```

### `docker info`:
```
FATA[0000] Get http://192.168.59.103:2376/v1.16/info: malformed HTTP response "\x15\x03\x01\x00\x02\x02". Are you trying to connect to a TLS-enabled daemon without TLS? 
```

### `uname -a`:
```
Darwin me.local 12.5.0 Darwin Kernel Version 12.5.0: Sun Sep 29 13:33:47 PDT 2013; root:xnu-2050.48.12~1/RELEASE_X86_64 x86_64
```
(MacOS 10.8.5)

## Steps to Reproduce
1. Download https://ejhazlett.s3.amazonaws.com/public/docker/darwin/docker-1.4.1-136b351e-identity
2.  `cp docker-1.4.1-136b351e-identity /usr/local/bin/docker`
3.  `docker run --rm hello-world`

## Results
```
$ docker run --rm hello-world
FATA[0000] Post http://192.168.59.103:2376/v1.16/containers/create: malformed HTTP response "\x15\x03\x01\x00\x02\x02\x16". Are you trying to connect to a TLS-enabled daemon without TLS?
```

My regular docker 1.4.1 (both the one from Homebrew and the one that comes with boot2docker) run this command fine.

**Comment by ehazlett** [comment]
@DanLipsitt are you making sure to set the `DOCKER_HOST` and `DOCKER_AUTH` environment variables after creation from machine?

**Comment by DanLipsitt** [comment]
Well, I'm not actually able to create VMs with machine yet (see #242). But the identity build should work with VMs created by ordinary boot2docker as well, right? I just tried setting DOCKER_AUTH as well as trying some other things, but it didn't help:

```
$(boot2docker shellinit)
Writing /Users/dan/.boot2docker/certs/boot2docker-vm/ca.pem
Writing /Users/dan/.boot2docker/certs/boot2docker-vm/cert.pem
Writing /Users/dan/.boot2docker/certs/boot2docker-vm/key.pem
$ export DOCKER_AUTH=identity
$ env | grep DOCKER
DOCKER_HOST=tcp://192.168.59.103:2376
DOCKER_AUTH=identity
DOCKER_TLS_VERIFY=1
DOCKER_CERT_PATH=/Users/dan/.boot2docker/certs/boot2docker-vm
$ ~/Downloads/docker-1.4.1-136b351e-identity run --rm hello-world
FATA[0000] TLS Handshake error: remote error: bad certificate 
$ DOCKER_TLS_VERIFY=0
$ ~/Downloads/docker-1.4.1-136b351e-identity run --rm hello-world
FATA[0000] TLS Handshake error: remote error: bad certificate 
$ unset DOCKER_TLS_VERIFY
$ ~/Downloads/docker-1.4.1-136b351e-identity run --rm hello-world
FATA[0000] TLS Handshake error: remote error: bad certificate 
```

**Comment by ehazlett** [comment]
No, existing b2d instances will not work as they have different certs.  I
have a PR open that will allow for importing existing instances but it's
not yet merged.

**Comment by ehazlett** [comment]
@DanLipsitt could you try with a build from master to see if you still have this issue?  Thanks!

**Comment by bfirsh** [comment]
@ehazlett can this be closed now we no longer do identity auth/

**Comment by ehazlett** [comment]
Yes

**Comment by kamaljeetrathi** [comment]
String caCrtFile = "/$PATH/ca.pem";
String certCrtFile = "/$PATH/cert.pem";
String keyCrtFile = "/$PATH/key.pem";

HttpClientOptions httpClientOptions = new HttpClientOptions();
httpClientOptions.setSsl(true).setPemKeyCertOptions(new PemKeyCertOptions().setKeyPath(keyCrtFile).setCertPath(certCrtFile).setCertPath(caCrtFile))
httpClientOptions.setDefaultHost("$HOST").setDefaultPort(2376);
HttpClient Client = vertx.createHttpClient(httpClientOptions);
	Client.getNow("/images/json?all=0",new Handler<HttpClientResponse>() {
			
			@Override
			public void handle(HttpClientResponse response) {
				// TODO Auto-generated method stub
				System.out.println();
				 System.out.println("--"+response.statusCode());
				 System.out.println("--"+response.headers());
				 System.out.println("--"+response.bodyHandler(new Handler<Buffer>() {
					
					@Override
					public void handle(Buffer event) {
						// TODO Auto-generated method stub
						System.out.println(event.getString(0,event.length()));
					}
				}));
				
				
			}
		});


I am requesting to docker deamon running on my local machine from vertx 3 get request and certificate but it is giving me error  TLS handshake error:unknown certificate while requesting.

I have my docker deamon running with same certificate 
sudo docker daemon --tlsverify --tlscacert=/$PATH/ca.pem --tlscert=/$PATH/server-cert.pem --tlskey=/$PATH/server-key.pem -H=$HOST:2376

But when I request this deamon from command line it serves my request and gives me output.
 sudo docker --tlsverify --tlscacert=/$PATH/ca.pem --tlscert=/$PATH/cert.pem --tlskey=/$PATH/key.pem -H=$HOST:2376 images


Also it serves my request from curl also with same certificates 
 curl https://$HOST:2376/images/json \
>   --cert /$PATH/cert.pem \
>   --key /$PATH/key.pem \
>   --cacert /$PATH/ca.pem
