### ISSUE TITLE
Support edition of InsecureRegistry entries

### ISSUE THREAD

**Issue by akram** [docker/machine#2455]
As far as I know, docker-machine cannot edit insecure-registry option for an existing machine.

That would be great to be able to edit this option.
It seems that in docker-machine 0.4, one can edit this by editing $HOME/.docker/machine/mymachine/config.json and setting the InsecureRegistry array into the appropriate value as described here: http://akrambenaissi.com/2015/11/17/addingediting-insecure-registry-to-docker-machine-afterwards/

But, that would be great if we could use docker-machine directly instead.

**Comment by jeanlaurent** [comment]
You can use the `--engine-insecure-registry` flag at VM creation time.

`docker-machine` does not support vm modification atm.

**Comment by akram** [comment]
thank you @jeanlaurent
do you know if machines modification is planned ?

**Comment by bacongobbler** [comment]
I found a way to do this for the virtualbox driver by just SSH'ing into the machine. You can run the following to reconfigure your docker engine flags. I was motivated to figure this out so I didn't have to re-provision a new box and re-pull/rebuild every image back onto the box every time I wanted to switch around the engine's flags.

```
$ docker-machine ssh <box>
$ vi /var/lib/boot2docker/profile # edit the EXTRA_ARGS envvar to add any additional engine flags you like
$ sudo /etc/init.d/docker restart
```

I imagine that something similar can be done with the rest of the drivers as [they use the default provisioning process](https://github.com/docker/machine/blob/aa36205174b7aa8728db3b80d87300bc7933e0e7/libmachine/provision/debian.go#L71) which will end up using systemd or w/e the default is for that specific box. You probably just need to figure out what distro of linux the machine is running, what's the underlying process manager and follow the respective "default" documentation on configuring [that OS's docker daemon](http://docs.docker.com/engine/articles/configuring/) using that process manager.

Hope this helps, @akram.

**Comment by nathanleclaire** [comment]
You can do it in place, and doing this kind of modification is also why I'd like to support some type of declarative config and `docker-machine apply` type command.

**Comment by jeanlaurent** [comment]
Machine modification is not planned atm.
But the future of this is more headed towards #2422

Closing this. 
If you feel like I missed something, please re-open.
