### ISSUE TITLE
docker-machine --hyperv-cpu-count switch?

### ISSUE THREAD

**Issue by dubrowgn** [docker/machine#2457]
I noticed there is a switch for the virtualbox driver to set the number of VM cpus (`--virtualbox-cpu-count`). Are there plans to introduce a similar switch for the hyperv driver?

**Comment by jeanlaurent** [comment]
The hyperv driver is quite old. It needs a significant rewrite to be usable.

You're request is still valid, just that probably not that high in the chain.

**Comment by dubrowgn** [comment]
It doesn't look like this would be too difficult to implement, after looking through the driver code a bit. It seems the powershell command to change the cpu count setting looks like: `SET-VMProcessor –VMName <vm name here> –count <cpu count here>`. Unforntuately, I won't have time for a while to mess around getting a go compiler up and running as we have much higher priorities at the moment.
