### ISSUE TITLE
Windows 10 - Failed to create the host-only adapter

### ISSUE THREAD

**Issue by myfear** [docker/machine#2465]
C:\Users\me>docker-machine --version
docker-machine version 0.5.1 (7e8e38e)

C:\Users\m>docker-machine -D create dev2 -d virtualbox  
Docker Machine Version: 0.5.1 (7e8e38e)
Found binary path at D:\Program Files\Docker Toolbox\docker-machine-driver-virtualbox.exe
Launching plugin server for driver virtualbox
Plugin server listening at address 127.0.0.1:56008
() Calling RPCServerDriver.GetVersion
Using API Version 1
() Calling RPCServerDriver.SetConfigRaw
() Calling RPCServerDriver.GetMachineName
(flag-lookup) Calling RPCServerDriver.GetCreateFlags
Making call to close connection to plugin binary
Making call to close driver server
(flag-lookup) Calling RPCServerDriver.Close
Successfully made call to close driver server
Found binary path at D:\Program Files\Docker Toolbox\docker-machine-driver-virtualbox.exe
Launching plugin server for driver virtualbox
Plugin server listening at address 127.0.0.1:56012
() Calling RPCServerDriver.GetVersion
Using API Version 1
() Calling RPCServerDriver.SetConfigRaw
() Calling RPCServerDriver.GetMachineName
(dev2) Calling RPCServerDriver.GetMachineName
(dev2) Calling RPCServerDriver.DriverName
(dev2) Calling RPCServerDriver.GetCreateFlags
(dev2) Calling RPCServerDriver.SetConfigFromFlags
(dev2) Calling RPCServerDriver.PreCreateCheck
(dev2) DBG | COMMAND: D:\Program Files\Oracle\VirtualBox\VBoxManage.exe
(dev2) Calling RPCServerDriver.GetConfigRaw
(dev2) Calling RPCServerDriver.GetConfigRaw
(dev2) Calling RPCServerDriver.Create
(dev2) DBG | COMMAND: wmic cpu get VirtualizationFirmwareEnabled
(dev2) DBG | STDOUT:
(dev2) DBG | {
(dev2) DBG | VirtualizationFirmwareEnabled
(dev2) DBG | TRUE
(dev2) DBG |
(dev2) DBG | }
(dev2) DBG | Creating disk image...
(dev2) DBG | Creating 20000 MB hard disk image...
(dev2) DBG | COMMAND: D:\Program Files\Oracle\VirtualBox\VBoxManage.exe createvm --basefolder C:\Users\me\.docker\machine\machines\dev2 --name dev2 --register
(dev2) DBG | STDOUT:
(dev2) DBG | {
(dev2) DBG | Virtual machine 'dev2' is created and registered.
(dev2) DBG | UUID: dbf23385-d0b4-4df7-9e4f-d3626a3617d4
(dev2) DBG | Settings file: 'C:\Users\me\.docker\machine\machines\dev2\dev2\dev2.vbox'
(dev2) DBG | }
(dev2) DBG | STDERR:
(dev2) DBG | {
(dev2) DBG | }
(dev2) DBG | VM CPUS: 1
(dev2) DBG | VM Memory: 1024
(dev2) DBG | COMMAND: D:\Program Files\Oracle\VirtualBox\VBoxManage.exe modifyvm dev2 --firmware bios --bioslogofadein off --bioslogofadeout off --bioslogodisplaytime 0 --biosbootmenu disabled --ostype Linux26_64 --cpus 1 --memory 1024 --acpi on --ioapic on --rtcuseutc on --natdnshostresolver1 off --natdnsproxy1 off --cpuhotplug off --pae on --hpet on --hwvirtex on --nestedpaging on --largepages on --vtxvpid on --accelerate3d off --boot1 dvd
(dev2) DBG | STDOUT:
(dev2) DBG | {
(dev2) DBG | }
(dev2) DBG | STDERR:
(dev2) DBG | {
(dev2) DBG | }
(dev2) DBG | COMMAND: D:\Program Files\Oracle\VirtualBox\VBoxManage.exe modifyvm dev2 --nic1 nat --nictype1 82540EM --cableconnected1 on
(dev2) DBG | STDOUT:
(dev2) DBG | {
(dev2) DBG | }
(dev2) DBG | STDERR:
(dev2) DBG | {
(dev2) DBG | }
(dev2) DBG | using 192.168.99.6 for dhcp address
(dev2) DBG | COMMAND: D:\Program Files\Oracle\VirtualBox\VBoxManage.exe list hostonlyifs
(dev2) DBG | STDOUT:
(dev2) DBG | {
(dev2) DBG | }
(dev2) DBG | STDERR:
(dev2) DBG | {
(dev2) DBG | }
(dev2) DBG | COMMAND: D:\Program Files\Oracle\VirtualBox\VBoxManage.exe hostonlyif create
(dev2) DBG | STDOUT:
(dev2) DBG | {
(dev2) DBG | }
(dev2) DBG | STDERR:
(dev2) DBG | {
(dev2) DBG | 0%...
(dev2) DBG | Progress state: E_FAIL
(dev2) DBG | VBoxManage.exe: error: Failed to create the host-only adapter
(dev2) DBG | VBoxManage.exe: error: Querying NetCfgInstanceId failed (0x00000000)
(dev2) DBG | VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component HostNetworkInterfaceWrap, interface IHostNetworkInterface
Error creating machine: Error in driver during machine creation: D:\Program Files\Oracle\VirtualBox\VBoxManage.exe hostonlyif create failed:
0%...
Progress state: E_FAIL
VBoxManage.exe: error: Failed to create the host-only adapter
VBoxManage.exe: error: Querying NetCfgInstanceId failed (0x00000000)
VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component HostNetworkInterfaceWrap, interface IHostNetworkInterface
VBoxManage.exe: error: Context: "enum RTEXITCODE __cdecl handleCreate(struct HandlerArg *)" at line 71 of file VBoxManageHostonly.cpp

**Comment by jeanlaurent** [comment]
Sounds like Virtualbox going kaboom.

What is your `vboxmanage --version` ?

Did it work on this machine once or is it new ?

**Comment by myfear** [comment]
D:\Program Files\Oracle\VirtualBox>vboxmanage --version
5.0.10r104061

It worked on Win7 before the upgrade. I re-installed VirtulBox completeley.

**Comment by kirstin** [comment]
I have the same error. 
I have installed the latest test build of virtualbox, because I thought maybe something would be better in that version. It is not - unfortunately.

PS C:\Program Files\Oracle\VirtualBox> .\vboxmanage --version
5.0.11r104456

**Comment by DeyV** [comment]
On windows 10 x64   with virtualbox beta version 5.0.11r104602  - it's start works

**Comment by kirstin** [comment]
I have installed the test version 5.0.11r104602 and tried again.

I still get the same error.

docker-machine -D create -d virtualbox test
Docker Machine Version: 0.5.2 ( 0456b9f )
Found binary path at C:\Program Files\Docker Toolbox\docker-machine-driver-virtualbox.exe
Launching plugin server for driver virtualbox
Plugin server listening at address 127.0.0.1:58199
() Calling .GetVersion
Using API Version 1
() Calling .SetConfigRaw
() Calling .GetMachineName
(flag-lookup) Calling .GetCreateFlags
Making call to close connection to plugin binary
Making call to close driver server
(flag-lookup) Calling .Close
Successfully made call to close driver server
Found binary path at C:\Program Files\Docker Toolbox\docker-machine-driver-virtualbox.exe
Launching plugin server for driver virtualbox
Plugin server listening at address 127.0.0.1:58203
() Calling .GetVersion
Using API Version 1
() Calling .SetConfigRaw
() Calling .GetMachineName
(test) Calling .GetMachineName
(test) Calling .DriverName
(test) Calling .GetCreateFlags
(test) Calling .SetConfigFromFlags
Running pre-create checks...
(test) Calling .PreCreateCheck
(test) DBG | COMMAND: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe --version
(test) DBG | STDOUT:
(test) DBG | {
(test) DBG | 5.0.11r104602
(test) DBG | }
(test) DBG | STDERR:
(test) DBG | {
(test) DBG | }
(test) DBG | COMMAND: wmic cpu get VirtualizationFirmwareEnabled
(test) DBG | STDOUT:
(test) DBG | {
(test) DBG | VirtualizationFirmwareEnabled
(test) DBG | TRUE
(test) DBG |
(test) DBG | }
(test) Calling .GetConfigRaw
Creating machine...
(test) Calling .Create
(test) Creating VirtualBox VM...
(test) Creating SSH key...
(test) DBG | Creating disk image...
(test) DBG | Creating 20000 MB hard disk image...
(test) DBG | COMMAND: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe createvm --basefolder C:\Users\Menthol\.docker\m
achine\machines\test --name test --register
(test) DBG | STDOUT:
(test) DBG | {
(test) DBG | Virtual machine 'test' is created and registered.
(test) DBG | UUID: 9c732a95-0904-4190-9b38-7d77aceb2350
(test) DBG | Settings file: 'C:\Users\Menthol\.docker\machine\machines\test\test\test.vbox'
(test) DBG | }
(test) DBG | STDERR:
(test) DBG | {
(test) DBG | }
(test) DBG | VM CPUS: 1
(test) DBG | VM Memory: 1024
(test) DBG | COMMAND: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe modifyvm test --firmware bios --bioslogofadein o
ff --bioslogofadeout off --bioslogodisplaytime 0 --biosbootmenu disabled --ostype Linux26_64 --cpus 1 --memory 1024 --ac
pi on --ioapic on --rtcuseutc on --natdnshostresolver1 off --natdnsproxy1 off --cpuhotplug off --pae on --hpet on --hwvi
rtex on --nestedpaging on --largepages on --vtxvpid on --accelerate3d off --boot1 dvd
(test) DBG | STDOUT:
(test) DBG | {
(test) DBG | }
(test) DBG | STDERR:
(test) DBG | {
(test) DBG | }
(test) DBG | COMMAND: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe modifyvm test --nic1 nat --nictype1 82540EM --ca
bleconnected1 on
(test) DBG | STDOUT:
(test) DBG | {
(test) DBG | }
(test) DBG | STDERR:
(test) DBG | {
(test) DBG | }
(test) DBG | using 192.168.99.6 for dhcp address
(test) DBG | COMMAND: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe list hostonlyifs
(test) DBG | STDOUT:
(test) DBG | {
(test) DBG | }
(test) DBG | STDERR:
(test) DBG | {
(test) DBG | }
(test) DBG | COMMAND: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe hostonlyif create
(test) DBG | STDOUT:
(test) DBG | {
(test) DBG | }
(test) DBG | STDERR:
(test) DBG | {
(test) DBG | 0%...
(test) DBG | Progress state: E_FAIL
(test) DBG | VBoxManage.exe: error: Failed to create the host-only adapter
(test) DBG | VBoxManage.exe: error: Querying NetCfgInstanceId failed (0x00000000)
(test) DBG | VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component HostNetworkInterfaceWrap, interface IHo
stNetworkInterface
Error creating machine: Error in driver during machine creation: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe hosto
nlyif create failed:
0%...
Progress state: E_FAIL
VBoxManage.exe: error: Failed to create the host-only adapter
VBoxManage.exe: error: Querying NetCfgInstanceId failed (0x00000000)
VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component HostNetworkInterfaceWrap, interface IHostNetworkInte
rface
VBoxManage.exe: error: Context: "enum RTEXITCODE __cdecl handleCreate(struct HandlerArg *)" at line 71 of file VBoxManag
eHostonly.cpp

**Comment by kirstin** [comment]
**UPDATE**:
I have resolved my issue by 
- remove all host-only network adapters in GUI
- uninstall virtualbox
- reboot
- install virtualbox

I then had different errors. Namely this one:  #1754 
The suggested fix of activating the NDIS6 Driver for the adapter worked for me.

**Comment by dgageot** [comment]
This is worked around in https://github.com/docker/machine/pull/2797

**Comment by wbmedia** [comment]
Hi, @kirstin your recomendation works ! thanks

**Comment by ghostthrone** [comment]
@kirstin Thank you very much, it works for me as well.

**Comment by Prem-Patel** [comment]
I had the same issue. I got two solution for it.

Uninstall check point endpoint security application OR
added below line in vagrantfile
config.vm.network "public_network", ip: "{ip}" along with config.vm.network "private_network", ip: "{ip}"

**Comment by Deepikabawa** [comment]
@Prem-Patel Thanks for the solution. It worked for me.

**Comment by wjrmffldrhrl** [comment]
thank you!
