### ISSUE TITLE
docker commands fail after removing the machine instance

### ISSUE THREAD

**Issue by AlexOugh** [docker/machine#2469]
I'm getting this error after removing an machine instance, 'aws01'.

$ docker ps
Could not read CA certificate "/home/ec2-user/.docker/machine/machines/aws01/ca.pem": open /home/ec2-user/.docker/machine/machines/aws01/ca.pem: no such file or directory

I manually created that file and tried again, but the command just hung.
Any way or workaround to make the docker commands work?

**Comment by nathanleclaire** [comment]
Did the `docker-machine create` fail?  That's usually what this is symptomatic of.  If the create fails, there's no way to recover at the moment.

**Comment by AlexOugh** [comment]
Yes, it failed. But the failure seemed to make no 'docker' commands available. So I stopped the docker and restarted and after a while, the docker commands started to work normal.

It is ok that there is no way to recover the failed instances, but it shouldn't cause the docker commands failed, though.

**Comment by nathanleclaire** [comment]
@AlexOugh But if provisioning fails the certs won't get copied over, so connection won't work properly.  That's the issue you're seeing here.  How would you expect Machine to behave if provisioning fails and an "unhealthy" instance is left?

**Comment by AlexOugh** [comment]
I think the failed instances should be terminated unless any retries are available from the point where it failed, which doesn't seem to be the case.

**Comment by nathanleclaire** [comment]
But how can one remove the generated resources safely if provisioning has failed?  Consider, for instance, that the network drops in the middle of provisioning a cloud server.  `rm` would fail as well.

**Comment by AlexOugh** [comment]
I think it is your decision whether to ask users to remove the instance manually with explanation or to retry it if you can maintain the point whether it fails.

**Comment by nathanleclaire** [comment]
We've tried automatic cleanup before and had quite a few issues with it.  As for re-trying failed provisions, we are considering a `docker-machine provision` command for that.
