### ISSUE TITLE
machine ssh name -c ls -al fails

### ISSUE THREAD

**Issue by SvenDowideit** [docker/machine#247]
in b2d we had to detect where the b2d flags ended and force it not to parse past that.

```
mini:machine sven$ ./machine ssh vmtest -c ls -al
Incorrect Usage.

NAME:
   ssh - Log into or run a command on a machine with SSH

USAGE:
   command ssh [command options] [arguments...]

OPTIONS:
   --command, -c        SSH Command
   
```

**Comment by SvenDowideit** [comment]
personally, I was also surprised that the `-c` was needed at all

we made `boot2docker ssh ls -al` work, that way is was similar to `ssh host ls -la`

**Comment by sthulb** [comment]
the machine name can be specified in the ssh command `machine ssh [name] [-c command]` 

If we don't care about the name and always have it perform on the active machine, we can drop the -c

**Comment by ehazlett** [comment]
If we want to remove the name from ssh we should look at the other commands as some can take the machine name as well.  This could get confusing.

**Comment by sthulb** [comment]
I like the option of specifying the name.

**Comment by ehazlett** [comment]
I personally like specifying the name as well.

@bfirsh thoughts?

**Comment by SvenDowideit** [comment]
or, if you always have to specify a name, then the cmds follow - prettymuch the main risk point is if a machine's name is the same as a command someone uses..

**Comment by nathanleclaire** [comment]
I think this brings up a somewhat larger underlying issue about consistency of the commands with respect to specifying the name.  I'm starting to think that I favor _always_ specifying the machine name explicitly.  It would make shell scripts easier to read and, although I like the convenience of `machine stop` and `machine start`, they invoke implicit arguments that would probably be better off explicit.  We're having a bit of a hard time keeping it consistent already, I think- for instance, `machine rm` without args does not seem to work against the active host (and _should_ it?).

**Comment by ehazlett** [comment]
I actually love that as well.  I always specify the name simply because I
tend to favor explicit over implicit.  I like the consistency facet as
well.  Keeping everything the same instead of some commands using different
ways.

**Comment by bfirsh** [comment]
I wonder if SSH could be an exception which takes the name with a `-n` option.

`machine ssh df -h` is much better than a `-c` option. I think that's how it worked originally... when did we lose that?

**Comment by bfirsh** [comment]
---> #434. Thanks sven!
