### ISSUE TITLE
Document creating a machine with more disk space than default

### ISSUE THREAD

**Issue by moxiegirl** [docker/machine#2470]
This question came up in the IRC cloud.  We should cover the topic in the docs --- it is maybe an article "machine features and how to control them" or maybe it is part of a FAQ which we could also use.

cc /@londoncalling

**Comment by toli** [comment]
Running `docker-machine create -d virtualbox  --virtualbox-disk-size "20000" default` will create a machine called `default` with the size of `20G`

**Comment by nathanleclaire** [comment]
Yup, @toli has it right, I've changed the issue to be phrased as a request to document this feature.

**Comment by londoncalling** [comment]
Currently, top level Docker Machine docs are mainly:
* an install (on Mac or Windows) 
* An overview: http://docs.docker.com/machine/
* A getting started, one for Virutal Box (http://docs.docker.com/machine/get-started/) and one for hosting on cloud providers (http://docs.docker.com/machine/get-started-cloud/)

Much of the detail about configuration is buried in the `create`  subcommand (http://docs.docker.com/machine/reference/create/). 

@nathanleclaire, @moxiegirl, and I chatted about this today, and my plan is to surface information in the `create` command reference to one of the existing intro topics or create a new one (e.g., Configuring Docker Machine, or something like that). I"ll work with Nathan on other useful information to highlight at create time. The create subcommand topic will retain the examples and command description, flags and syntax detail, but the explanations will move up into the getting started topics. 

Finally, I'll make sure we have x-refs between the relevant subcommands and getting started task docs, which we don't have right now.
