### ISSUE TITLE
Warn on virtualbox version

### ISSUE THREAD

**Issue by dmp42** [docker/machine#2479]
1. decide of a minimal 5.X version that we officially support
 1. if the version does not match the criteria, issue a warning on the command-line: "Your virtualbox version is outdated. Things might not work. Please upgrade."
 1. if people report issues with "warned" versions, we don't spend time on it and ask them to upgrade

**Comment by nathanleclaire** [comment]
I'm still not convinced this is a good idea.  As noted before, newer versions of VirtualBox are frequently _less_ stable than their older counterpoints, and we're not doing anything special to support the older versions, so we might actually be doing users a disservice by encouraging them to upgrade.

**Comment by nathanleclaire** [comment]
e.g.: https://github.com/docker/machine/issues/1716#issuecomment-161369319

**Comment by dmp42** [comment]
We don't have the bandwidth to support many versions (even reproduce / test).
Pretending we do is disingenuous to the users.
Fixing / workarounding issues with a restricted set of virtualbox versions is what we can (and should) reasonably do.
Other versions *might work*, but we should make these facts ^ clear.

Put otherwise: machine *must* work well with a given version of VirtualBox. Then we can discuss advertising "more" versions as "supported".

**Comment by dgageot** [comment]
I've added a simple warning inviting users to upgrade if they encounter an issue.
