### ISSUE TITLE
Unable to provision with generic driver (exit status 127)

### ISSUE THREAD

**Issue by johnjelinek** [docker/machine#2480]
example:
```
$ docker-machine create --driver generic --generic-ip-address 123.45.67.89 --generic-ssh-port 2222 my-machine
Running pre-create checks...
Creating machine...
Waiting for machine to be running, this may take a few minutes...
(my-machine) Importing SSH key...
Machine is running, waiting for SSH to be available...
Detecting operating system of created instance...
Detecting the provisioner...
Provisioning with centos...
Copying certs to the local machine directory...
Copying certs to the remote machine...
Setting Docker configuration on the remote daemon...
WARNING >>> Error running SSH command: exit status 127
WARNING >>> Error running SSH command: exit status 127
WARNING >>> Error running SSH command: exit status 127
WARNING >>> Error running SSH command: exit status 127
WARNING >>> Error running SSH command: exit status 127
Error creating machine: Error running provisioning: Unable to verify the Docker daemon is listening: Maximum number of retries (5) exceeded
```

```
$ docker-machine version
docker-machine version 0.5.2 ( 0456b9f )
```

**Comment by johnjelinek** [comment]
With `-D`, I see:
```
(knifeparty) Calling .GetSSHHostname
(knifeparty) Calling .GetSSHPort
(knifeparty) Calling .GetSSHKeyPath
(knifeparty) Calling .GetSSHUsername
Using SSH client type: external
WARNING >>> Error running SSH command: exit status 127
```

with `--native-ssh`, I see:
```
(knifeparty) Calling .GetSSHHostname
(knifeparty) Calling .GetSSHPort
(knifeparty) Calling .GetSSHKeyPath
(knifeparty) Calling .GetSSHUsername
Using SSH client type: native
WARNING >>> Error running SSH command: exit status 127
```

**Comment by nathanleclaire** [comment]
Guess you probably don't have `netstat` installed on the OS you're provisioning?  We're using it to detect if the daemon is up.

**Comment by johnjelinek** [comment]
Ahh, you should check if that dependency exists :)



—

**Comment by johnjelinek** [comment]
installing netstat made everything all better :) Thanks!

**Comment by nathanleclaire** [comment]
NP yes I agree that we should check for `netstat`, usually it's a pretty safe bet to expect to be around but obviously (as this issue illustrates) not in all cases.

**Comment by johnjelinek** [comment]
Do I need to open another issue to report checking for netstat?



—

**Comment by nathanleclaire** [comment]
@johnjelinek Yes please, that would be great for us.

**Comment by psychok7** [comment]
in my case i did `docker-machine regenerate-certs dev` on Ubuntu 14.04 Lts and when i created a new machine the error didn't appear anymore

**Comment by rakotomandimby** [comment]
Please note that `netstat` has been deprecated on several Linux distributions in favour of `ss`.
- https://bugzilla.redhat.com/show_bug.cgi?id=1119297 for RHEL and CEntOS v 7
- https://www.archlinux.org/news/deprecation-of-net-tools/ for Archlinux
- https://wiki.debian.org/NetToolsDeprecation still an intention on Debian

That is the culprit of https://github.com/docker/machine/issues/3171

**Comment by alexanderilyin** [comment]
@johnjelinek thank for suggestion, after `yum install -y net-tools` it was able to provision.
BTW how I could find that problem was with missing `netstat`? I did find anything in logs.
