### ISSUE TITLE
#1716 should be reopened. 

### ISSUE THREAD

**Issue by gotcha** [docker/machine#2484]
#1716 should be reopened

Some people still cannot use docker-machine with VB 5.0.10

See my comment or https://github.com/docker/machine/issues/1716#issuecomment-161369319

**Comment by nathanleclaire** [comment]
Please comment there, be sure to include `--debug` output and as much information as possible.  Thanks!

**Comment by gotcha** [comment]
@nathanleclaire Would you reopen #1716  ?

**Comment by nathanleclaire** [comment]
@gotcha Mind opening a new issue with the symptoms that you're seeing?  Usually threads like that tend to be long-winded and digress from the original issue quite a bit.
