### ISSUE TITLE
In generic driver, if a permanent IP address and hostname has alread in /etc/hosts, docker-machine will insert a line "127.0.1.1 hostname" into /etc/hosts

### ISSUE THREAD

**Issue by dongmx** [docker/machine#2485]
I saw the source code, and find this comment in it. 
// ubuntu/debian use 127.0.1.1 for non "localhost" loopback hostnames: https://www.debian.org/doc/manuals/debian-reference/ch05.en.html#_the_hostname_resolution

As the document says "For a system with a permanent IP address, that permanent IP address should be used here instead of 127.0.1.1." . But if there is already a permanent IP address and hostname in /etc/hosts, docker-machine with insert a line "127.0.1.1 hostname" into /etc/hosts which cause one hostname multi address.

I have fixed this issue and I will pull my code later.

**Comment by dongmx** [comment]
I saw the source code, and find this comment in it. 
// ubuntu/debian use 127.0.1.1 for non "localhost" loopback hostnames: https://www.debian.org/doc/manuals/debian-reference/ch05.en.html#_the_hostname_resolution

As the document says "For a system with a permanent IP address, that permanent IP address should be used here instead of 127.0.1.1." . But if there is already a permanent IP address and hostname in /etc/hosts, docker-machine with insert a line "127.0.1.1 hostname" into /etc/hosts which cause one hostname multi address. 

I have fixed this issue and I will pull my code later.

**Comment by nathanleclaire** [comment]
Yeah, this line is somewhat problematic for a variety of reasons, and I've considered just removing it, but I'm curious to see what you're working on.

**Comment by dongmx** [comment]
My pr is here https://github.com/docker/machine/pull/2486 :)

**Comment by dongmx** [comment]
@nathanleclaire Thanks for your feedback. I have already create a pull request for this issue. And nobody comment this pull request, should I just wait or ping someone?

**Comment by nathanleclaire** [comment]
@dongmx It's merged now ;D
