### ISSUE TITLE
Integration tests take too much time

### ISSUE THREAD

**Issue by dgageot** [docker/machine#2490]
The integration tests on VirtualBox take more than 20min on my machine.

Would you be ok if I changed the integration tests so that a single machine is shared across multiple tests files?
Of course some of the tests would still have to start a new distinct machine.

cc @docker/machine-maintainers

**Comment by nathanleclaire** [comment]
I do really think it's a bit risky to start mixing results from different tests intertwined, but I understand the appeal.

How about this:

- We create a function in `helpers.bash`, something like `mcn_create`, which:
    - Creates the test machine if it doesn't exist already.
    - Skips creating the test machine if it _does_ exist already.

Then, we replace invocations of `machine create -d $DRIVER $NAME` with this function, but not anything which requires custom `create` flags.  Those will always run their own independent create.

And, it also includes support, to opt out of sharing machines by running with `NO_SHARE_MACHINES` environment or equivalent enabled.  That way, before releases and stuff, we can run it a few times that way to make sure the tests aren't depending on each other for their results.  Looks like these are the tests for which we could use such an approach:

```
test/integration/core/core-commands.bats
test/integration/core/env_shell.bats
test/integration/core/inspect_format.bats
test/integration/core/regenerate-certs.bats
test/integration/core/scp.bats
test/integration/core/ssh-backends.bats
test/integration/virtualbox/certs-checksum.bats
test/integration/virtualbox/pause-save-start.bats
```

How does that sound?

Also, how do you envision this working in tandem with the way that we uniquely tag the `NAME` using timestamp today?
