### ISSUE TITLE
Update exoscale (and openstack?) drivers to Ubuntu 15.10

### ISSUE THREAD

**Issue by nathanleclaire** [docker/machine#2496]
Continuation of: https://github.com/docker/machine/issues/2361

Would be great to get your input / help on this @ggiamarchi @vincentbernat  Ubuntu 15.10 is now becoming our base Ubuntu version due to needing a kernel bump for overlay networking.

**Comment by nathanleclaire** [comment]
@trecloux Told me this is done already :+1:

**Comment by vincentbernat** [comment]
Oh, great! I'll test as soon as possible.

**Comment by nathanleclaire** [comment]
Thanks!

**Comment by vincentbernat** [comment]
I just tested and it works without much trouble.

I have a failure for "machine should show stopped after stop". It shows "Timeout" instead. I'll try to investigate shortly.
