### ISSUE TITLE
Document changes in release process given non-external drivers

### ISSUE THREAD

**Issue by nathanleclaire** [docker/machine#2499]
Following up on: https://github.com/docker/machine/pull/2453#issuecomment-161487141

Now that the installation process and release process is changed somewhat by this PR, we should document the changes so that the release document and installation guide are congruent.

cc @docker/machine-maintainers 

cc @londoncalling -- I don't think we'll need you to actively work on this one, but it would be great for you to follow to start to get a feel for our documentation structure and process.

**Comment by jeanlaurent** [comment]
I believe this is done. Feel free to re-open it if I missed something.
