### ISSUE TITLE
Error creating machine: Error in driver during machine creation: This computer doesn't have VT-X/AMD-v enabled. Enabling it in the BIOS is mandatory

### ISSUE THREAD

**Issue by Viiderstorm** [docker/machine#2502]
I'm pretty sure this issue has come up before however I can't seem to find a fix for it.

I'm trying to run docker on my AMD FX-8350 Windows 10 machine with the most recent BIOS. AMD-V is enabled in the BIOS, I made sure of that.

I've also checked for Virtualization being enabled with the 

    wmic cpu get VirtualizationFirmwareEnabled

Here's a screenshot of my cpu details and the messages I got. ![screenshot](http://i.imgur.com/fAIfm04.png)

**Comment by dgageot** [comment]
Hi @Viiderstorm, can you gist the content of the `~/.docker/machine/machines/default/default/Logs/VBox.log` file please?

Also, which version of VBox are you using?

**Comment by Viiderstorm** [comment]
https://gist.github.com/Viiderstorm/16c560979587358d9188

**Comment by Viiderstorm** [comment]
And I'm using VirtualBox Version 5.0.10 R104061.

It got installed with docker.

**Comment by nathanleclaire** [comment]
@dgageot Did `aece926d13eec3aeb07840ff6ac6b6bf334355eb` fix this or was that another issue?

**Comment by nathanleclaire** [comment]
Is the Windows version 32-bit?

**Comment by waleedsamy** [comment]
```
OS: Fedora 21
docker : v1.9
docker-machine: v0.5.4
```
may be this happen because your underline machine has `vt-x` disabled so reboot and enable it.
this feature is called `intel intermediate visualization` in my BIOS

**Comment by Adilsh4uk** [comment]
Try to remove Hyper-V in Control Panel -> Programs -> Turn Windows features on or off.

**Comment by dgageot** [comment]
Version 0.5.5 of docker-machine shows a clear error message when an installed hyper-v prevents vbox from working.

**Comment by Adilsh4uk** [comment]
I had the same issue few days ago with the latest VirtualBox and Docker ToolBox.
VT-d in the BIOS was turned on, but VirtualBox couldn't work with x64 images.
Uninstalling Hyper-V has solved this issue and i was able to run docker.

**Comment by dgageot** [comment]
Improved with https://github.com/docker/machine/pull/2695. Nothing else we can do, so I'm going to close this ticket. Feel free to reopen if you think we could do better.
