### ISSUE TITLE
Unable to create/start/stop/remove machine on Windows.

### ISSUE THREAD

**Issue by kunalkushwaha** [docker/machine#2504]
With patch https://github.com/docker/machine/commit/1a3c3898c12d4a3d315d8460bb48617e8ef59c2c

A bug of windows is introduced, which restricts any creation/start/stop on machine.

```
$ docker-machine start swl-consul
(swl-consul) Starting VM...
Error saving host to store: rename C:\Users\kunal\.docker\machine\machines\swl-consul\config.json.tmp162410963 C:\Users\kunal\.docker\machine\machines\swl-consul\config.json: The process cannot access the file because it is being used by another process.
```

While debugging issue I found, [``os.Remove``](https://github.com/docker/machine/blob/master/libmachine/persist/filestore.go#L49) successfully removes the config.json

Not sure, How to fix this bug as code seems correct. Issue is with ``os.Rename`` function.

**Comment by kunalkushwaha** [comment]
Reverting patch https://github.com/docker/machine/commit/1a3c3898c12d4a3d315d8460bb48617e8ef59c2c works fine.

**Comment by dgageot** [comment]
Closed with https://github.com/docker/machine/pull/2505
