### ISSUE TITLE
Machine should be able to register a generic host by DNS name

### ISSUE THREAD

**Issue by dgageot** [docker/machine#2510]
I'm trying to register a machine using the `generic` driver. It fails after a timeout because I used the machine dns name, not the IP address to register the machine.

When I run the `create` command in debug mode, I get the root cause:

```
$ ./bin/docker-machine -D create -d generic --generic-ip-address foo.42craft.com --generic-ssh-user root --generic-ssh-key ~/.ssh/id_rsa foo
...
Machine is running, waiting for SSH to be available...
Getting to WaitForSSH function...
(foo) Calling .GetSSHHostname
Error getting ssh command 'exit 0' : IP address is invalid: foo.42craft.com
Getting to WaitForSSH function...
(foo) Calling .GetSSHHostname
Error getting ssh command 'exit 0' : IP address is invalid: foo.42craft.com
```

Should we fix the code to accept a host name or is there a reason to accept only IPs?
In any case, the address should be checked in `PreCreateCheck` to avoid creating a non-functional machine.

**Comment by jeanlaurent** [comment]
From a user point of view I would like to do it. Most of the time I `dig` my dns name right before using create... which is kind of lame.

**Comment by dgageot** [comment]
ping @docker/machine-maintainers

**Comment by nathanleclaire** [comment]
Yes, I think this should work.

**Comment by nathanleclaire** [comment]
I'm updating the issue title to be phrased more like a feature request, since I think we're in agreement that this should work.

**Comment by hans-d** [comment]
I was initially able to register a machine using its hostname, it installed the software and was able to perform some actions.
After upgrading docker toolbox (i needed the latest docker-compose), `docker-machine ls` now reports `IP address is invalid: <hostname>` - but also reporting that machine to be running.

Running on MacOS, docker installed via toolbox. Current docker-machine version 0.5.2. Current toolbox 1.9.1c, previous 1.9.0d.

Being able to use hostname: +1

**Comment by narqo** [comment]
:+1: for the issue

**Comment by dgageot** [comment]
Closed with https://github.com/docker/machine/pull/2523
