### ISSUE TITLE
Spawn docker-machine instance to private subnet on aws?

### ISSUE THREAD

**Issue by riadbahri** [docker/machine#2512]
Probably a novice question, but how would i go about deploying a container via docker-machine into a private subnet on aws?

I guess docker-machine needs to connect to the instance via a specific port open. Should i tunnel this port into the private subnet? Is there anyway doing this with VPN? Should i first deploy to a public instance and then move the instance into the private subnet?

Any pointers would be appreciated greatly!!

**Comment by Telemakhos** [comment]
Check [this](http://networkstatic.net/docker-machine-provisioning-on-aws/) out
