### ISSUE TITLE
`machine create` with `--driver  <none>` could avoid `ERRORS` column

### ISSUE THREAD

**Issue by askb** [docker/machine#2518]
Do we need to query the docker version and lengthy display errors with `machine create` with `--driver  <none>` option ?

```
$ PATH="$PWD/bin:$PATH" bin/docker-machine --version 
docker-machine version 0.5.3-dev ( a86ae3c )
```

```
$ PATH="$PWD/bin:$PATH" bin/docker-machine ls 
NAME        ACTIVE   DRIVER       STATE     URL    SWARM   DOCKER    ERRORS
dev           -        virtualbox   Stopped                  Unknown   
stage        -        virtualbox   Stopped                  Unknown   
labapp      -        none         Running   none           Unknown   Unable to query docker version: Unable to read TLS config: open /home/user/.docker/machine/machines/labapp/server.pem: no such file or directory
labfoo      -        none         Running   none           Unknown   Unable to query docker version: Unable to read TLS config: open /home/user/.docker/machine/machines/labfoo/server.pem: no such file or directory
labfooapp   -        none         Running   none           Unknown   Unable to query docker version: Unable to read TLS config: open /home/user/.docker/machine/machines/labfooapp/server.pem: no such file or directory
testappengine   -        virtualbox   Error                    Unknown   machine does not exist
```

**Comment by dgageot** [comment]
@askb The `none` driver is currently not working at all. When/if it is fixed, then it will support only hosts that have a proper docker daemon up and running. So the `DOCKER` column will contain the docker daemon version and the `ERRORS` column will hopefully be empty.

I think we could close this one. @askb I let you decide.

**Comment by askb** [comment]
@dgageot thanks, it makes sense. closing this now.

**Comment by s1rc0** [comment]
So, how best practice to add local server as docker-mashine?
I have installed docket-engine , laster i install docker-mashine, and when i trying create docker-mashine via
docker-machine create -d "none" --url=tcp://127.0.0.1:2376 h4
i getting
# docker-machine ls
NAME   ACTIVE   DRIVER   STATE     URL                    SWARM   DOCKER    ERRORS
h4     -        none     Running   tcp://127.0.0.1:2376           Unknown   Unable to query docker version: Unable to read TLS config: open /root/.docker/machine/machines/h4/server.pem: no such file or directory

**Comment by dkirrane** [comment]
Same issue with Generic driver. 
Is there an open bug that tracks the **Unable to query docker version: Unable to read TLS config** issue?
Is there a open feature request open to handle registering existing docker hosts with machine?
