### ISSUE TITLE
Machine should save to config file as soon as possible when creating hosts

### ISSUE THREAD

**Issue by bfirsh** [docker/machine#253]
Machine doesn't save the config file until the Machine has booted up and the Docker daemon is running. This means if you ctrl-c when Machine says "Waiting for SSH...", then the machine will always be broken.

Machine instead should save to the config file as soon as the machine has been created. This might mean a change to the driver API. This might also be easier when we're using cloudinit, because the logic for waiting for the Docker daemon to start up can be pulled out of the driver and into the `Host`, where config files are saved.

**Comment by sthulb** [comment]
I think we should save config in /tmp until we're sure it's ok. This might mitigate #249

**Comment by ehazlett** [comment]
I think I would rather save it to the regular store as soon as possible and then remove if it's not OK.  I'm not a big fan of saving it somewhere else in the filesystem.

**Comment by Tebro** [comment]
+1. And I would also rather see it removed than have it in /tmp.

**Comment by nathanleclaire** [comment]
I think we're in a pretty happy place as far as saving the config file goes nowadays... I agree SIGINT handling could be better, but that ties into a broader discussion about enabling re-provisioning.
