### ISSUE TITLE
"Error running provisioning" using ami for latest Ubuntu 15.10

### ISSUE THREAD

**Issue by fiunchinho** [docker/machine#2530]
I wanted to create a swarm cluster on AWS, but I couldn't use the overlay multi-host networking feature since the default docker-machine ami uses Ubuntu 14.04, which has a kernel version < 3.16. I tried to create the swarm manager using the latest ami from AWS but the command fails provisioning the machine.

This works:

    [jose.armesto:~/dev/swarm]$ docker-machine create -d amazonec2 --amazonec2-access-key ** --amazonec2-secret-key ** --amazonec2-region eu-west-1 --amazonec2-vpc-id ** --swarm --swarm-master --swarm-discovery="consul://$(docker-machine ip consul01):8500" --engine-opt="cluster-store=consul://$(docker-machine ip consul01):8500" --swarm-opt="replication=true" --engine-opt="cluster-advertise=eth0:2376" --swarm-opt="advertise=eth0:3376" swarm-master-aws-01
    Running pre-create checks...
    Creating machine...
    (swarm-master-aws-01) OUT | Launching instance...
    Waiting for machine to be running, this may take a few minutes...
    Machine is running, waiting for SSH to be available...
    Detecting operating system of created instance...
    Detecting the provisioner...
    Provisioning created instance...
    Copying certs to the local machine directory...
    Copying certs to the remote machine...
    Setting Docker configuration on the remote daemon...
    Configuring swarm...
    To see how to connect Docker to this machine, run: docker-machine env swarm-master-aws-01
    [jose.armesto:~/dev/swarm]$ eval "$(docker-machine env --swarm swarm-master-aws-01)"
    [jose.armesto:~/dev/swarm]$ docker info
    Containers: 2
    Images: 1
    Role: primary
    Strategy: spread
    Filters: health, port, dependency, affinity, constraint
    Nodes: 1
     swarm-master-aws-01: 54.194.***.***:2376
      └ Containers: 2
      └ Reserved CPUs: 0 / 1
      └ Reserved Memory: 0 B / 1.018 GiB
      └ Labels: executiondriver=native-0.2, kernelversion=3.13.0-53-generic, operatingsystem=Ubuntu 14.04.2 LTS, provider=amazonec2, storagedriver=aufs
    CPUs: 1
    Total Memory: 1.018 GiB
    Name: 5ab686cc6d7f

This *does not*:

    [jose.armesto:~/dev/swarm]$ docker-machine create -d amazonec2 --amazonec2-access-key ** --amazonec2-secret-key ** --amazonec2-region eu-west-1 --amazonec2-ami ami-8618bff5 --amazonec2-vpc-id ** --swarm --swarm-master --swarm-discovery="consul://$(docker-machine ip consul01):8500" --engine-opt="cluster-store=consul://$(docker-machine ip consul01):8500" --swarm-opt="replication=true" --engine-opt="cluster-advertise=eth0:2376" --swarm-opt="advertise=eth0:3376" swarm-master-aws-01
    Running pre-create checks...
    Creating machine...
    (swarm-master-aws-01) OUT | Launching instance...
    Waiting for machine to be running, this may take a few minutes...
    Machine is running, waiting for SSH to be available...
    Detecting operating system of created instance...
    Detecting the provisioner...
    Provisioning created instance...
    Copying certs to the local machine directory...
    Copying certs to the remote machine...
    Setting Docker configuration on the remote daemon...
    Error creating machine: Error running provisioning: Unable to verify the Docker daemon is listening: Maximum number of retries (5) exceeded

The only difference is the parameter specifying the AMI to use. I've tried several times just in case it was a problem updating package repositories. But I always get the same error. Same thing trying Ubuntu 14.10. 
Any ideas?

**Comment by nathanleclaire** [comment]
Can you please https://gist.github.com the output of the Docker daemon logs from the instance which fails?

If it's Ubuntu 15.04, I think the command to get them is `sudo journalctl -u docker.service`.

**Comment by fiunchinho** [comment]
Sure. Also, additional info:
- The AMI Im trying here is Ubuntu 15.04 on eu-west-1. I tried 15.10 with same results.
- Docker Machine version: 0.5.1 (HEAD)
- Docker version: 1.9.1

This time I got a different error than yesterday:

```bash
[jose.armesto:~/dev]$ docker-machine create -d amazonec2 --amazonec2-access-key ** --amazonec2-secret-key ** --amazonec2-region eu-west-1 --amazonec2-ami ami-8618bff5 --amazonec2-vpc-id vpc-** --swarm --swarm-master --swarm-discovery="consul://$(docker-machine ip consul01):8500" --engine-opt="cluster-store=consul://$(docker-machine ip consul01):8500" --swarm-opt="replication=true" --engine-opt="cluster-advertise=eth0:2376" --swarm-opt="advertise=eth0:3376" swarm-master-aws-01
Running pre-create checks...
Creating machine...
(swarm-master-aws-01) OUT | Launching instance...
Waiting for machine to be running, this may take a few minutes...
Machine is running, waiting for SSH to be available...
Detecting operating system of created instance...
Detecting the provisioner...
Provisioning created instance...
WARNING >>> Error attempting heartbeat call to plugin server: connection is shut down
WARNING >>> Error getting SSH command to check if the daemon is up: connection is shut down
WARNING >>> Error getting SSH command to check if the daemon is up: connection is shut down
WARNING >>> Error getting SSH command to check if the daemon is up: connection is shut down
.
..
...
WARNING >>> Error getting SSH command to check if the daemon is up: connection is shut down
Error creating machine: Error running provisioning: Maximum number of retries (60) exceeded

[jose.armesto:~/dev]$ docker-machine ssh swarm-master-aws-01
Welcome to Ubuntu 15.04 (GNU/Linux 3.19.0-37-generic x86_64)

  System information as of Wed Dec  9 07:57:58 UTC 2015

  System load:  0.0               Processes:              75
  Usage of /:   9.8% of 15.61GB   Users logged in:        0
  Memory usage: 16%               IP address for eth0:    192.168.97.11
  Swap usage:   0%                IP address for docker0: 172.17.0.1

ubuntu@swarm-master-aws-01:~$ sudo journalctl -u docker.service
-- Logs begin at Wed 2015-12-09 07:26:33 UTC, end at Wed 2015-12-09 07:58:13 UTC. --
Dec 09 07:34:12 swarm-master-aws-01 systemd[1]: Starting Docker Application Container Engine...
Dec 09 07:34:12 swarm-master-aws-01 docker[29249]: time="2015-12-09T07:34:12.779856150Z" level=info msg="API listen on /var/run/docker.sock"
Dec 09 07:34:12 swarm-master-aws-01 docker[29249]: time="2015-12-09T07:34:12.809922150Z" level=info msg="Firewalld running: false"
Dec 09 07:34:12 swarm-master-aws-01 docker[29249]: time="2015-12-09T07:34:12.843689064Z" level=info msg="Default bridge (docker0) is assigned with an IP address 172.17.0.0/16. Daemon option --bip can be used to set a preferred IP address"
Dec 09 07:34:12 swarm-master-aws-01 docker[29249]: time="2015-12-09T07:34:12.948554318Z" level=warning msg="Your kernel does not support swap memory limit."
Dec 09 07:34:13 swarm-master-aws-01 docker[29249]: time="2015-12-09T07:34:13.091244435Z" level=info msg="Loading containers: start."
Dec 09 07:34:13 swarm-master-aws-01 docker[29249]: time="2015-12-09T07:34:13.091641161Z" level=info msg="Loading containers: done."
Dec 09 07:34:13 swarm-master-aws-01 docker[29249]: time="2015-12-09T07:34:13.091869783Z" level=info msg="Daemon has completed initialization"
Dec 09 07:34:13 swarm-master-aws-01 docker[29249]: time="2015-12-09T07:34:13.092047971Z" level=info msg="Docker daemon" commit=a34a1d5 execdriver=native-0.2 graphdriver=aufs version=1.9.1
Dec 09 07:34:13 swarm-master-aws-01 systemd[1]: Started Docker Application Container Engine.
Dec 09 07:34:13 swarm-master-aws-01 docker[29249]: time="2015-12-09T07:34:13.607746543Z" level=info msg="GET /v1.21/version"

ubuntu@swarm-master-aws-01:~$ sudo service docker status
● docker.service - Docker Application Container Engine
   Loaded: loaded (/lib/systemd/system/docker.service; enabled; vendor preset: enabled)
   Active: active (running) since Wed 2015-12-09 07:34:13 UTC; 29min ago
```

Thank you

**Comment by nathanleclaire** [comment]
@fiunchinho Those heartbeat errors indicate that something is wrong with Machine communicating from client binary => plugin, so it will not work if that is the case.  Can you try installing Docker Machine 0.5.2 and try again?

**Comment by nathanleclaire** [comment]
Normal create looks OK for me in `us-west-1` on master, but Swarm introduces some additional complications -- I'll try that and report back.

**Comment by fiunchinho** [comment]
I've updated to Docker Machine 0.5.2, and it seems to work fine now. Not sure why. Maybe v0.5.1 doesn't know how to provision Ubuntu 15.04 which uses Systemd?

If you want more information just ask me. Otherwise, I guess we can close the issue. Thank you for your help.

**Comment by nathanleclaire** [comment]
Thanks @fiunchinho .  We did recently release support for Ubuntu >=15.04 (I think in 0.5.2 like you mention), so that may well be the culprit.
