### ISSUE TITLE
Unable to kill a machine after being rejected by AWS api

### ISSUE THREAD

**Issue by voltecrus** [docker/machine#2531]
I tried creating a VM on AWS following this https://docs.docker.com/machine/drivers/aws/ but wasn't successful since it tries to create a security group and I don't have permissions to do so.

Now I'm unable to rm/kill that vm.

Here's the error that I'm given:

    Problem with AWS API call: Non-200 API response: code=400 message=Invalid id: "" (expecting "i-...")

Here's output of my docker-machine ls:
 
    NAME           ACTIVE   DRIVER       STATE     URL                         SWARM   ERRORS
    default        -        virtualbox   Running   tcp://192.168.99.100:2376           
    spark-docker   -        amazonec2    Error                                         Problem with AWS API call: Non-200        API response: code=400 message=The request must contain the parameter InstanceId

**Comment by voltecrus** [comment]
I imagine that it creates the local entry before it confirms the successful convergence of a node in the cloud. It's unable then to delete it since it can't find the node.

**Comment by nathanleclaire** [comment]
Yes, it's telling you that it can't find any created instance.  You can remove the local reference using `docker-machine rm -f spark-docker`.

**Comment by voltecrus** [comment]
Ah! I was trying to find it under the ```kill```, wasn't sure what the difference was, thanks!
