### ISSUE TITLE
Use "standard" TLS instead of identity auth

### ISSUE THREAD

**Issue by ehazlett** [docker/machine#254]
We have found that the identity auth branch is a bit invasive on the Docker Engine and will not be merged soon.  I am working on using the regular TLS mechanism for auth in machine.  This is the placeholder issue.  A PR will be coming soon.

**Comment by sthulb** [comment]
+1 It would be nice to use a mainstream docker binary.

**Comment by ehazlett** [comment]
@sthulb +1 -- and the regular b2d iso as well.

**Comment by sthulb** [comment]
Are you working on the PR? If not, I can start it since I'm done with #219 and #241

**Comment by ehazlett** [comment]
@sthulb coming momentarily

**Comment by ehazlett** [comment]
Closing as #255 is merged.
