### ISSUE TITLE
Some provisioners do not honor --engine-install-url

### ISSUE THREAD

**Issue by dweomer** [docker/machine#2540]
Please notice the `"curl -sSL https://get.docker.com | sh"` below. Is this intentional?

```
✔ 15:43 (jlebc@JLEBC) ~/Projects/docker-machine [master|✔] $ date
Wed Dec  9 15:43:55 MST 2015
✔ 15:43 (jlebc@JLEBC) ~/Projects/docker-machine [master|✔] $ git log -1
commit a1275f6f1117c84e6bb6fca18dca1ab70e74b4c4
Merge: c2ed9e3 75b2d5f
Author: Jean-Laurent de Morlhon <jeanlaurent@morlhon.net>
Date:   Wed Dec 9 16:30:01 2015 +0100

    Merge pull request #2537 from Godin/patch-1
    
    Fix link
✔ 15:43 (jlebc@JLEBC) ~/Projects/docker-machine [master|✔] $ find . -type f -name "*.go" -exec grep -Hi 'get[.]docker[.]com' {} \;
./commands/create.go:			Value:  "https://get.docker.com",
./libmachine/host/migrate_v0_v1.go:		InstallURL: "https://get.docker.com",
./libmachine/host/migrate_v0_v1_test.go:			InstallURL: "https://get.docker.com",
./libmachine/host/migrate_v1_v2_test.go:            "InstallURL": "https://get.docker.com"
./libmachine/libmachine.go:			InstallURL:    "https://get.docker.com",
./libmachine/provision/debian.go:		// also re-run the get.docker.com script to properly setup
./libmachine/provision/debian.go:			"curl -sSL https://get.docker.com | sh",
./libmachine/provision/ubuntu_systemd.go:		// also re-run the get.docker.com script to properly setup
./libmachine/provision/ubuntu_systemd.go:			"curl -sSL https://get.docker.com | sh",
./libmachine/provision/ubuntu_upstart.go:		// also re-run the get.docker.com script to properly setup
./libmachine/provision/ubuntu_upstart.go:			"curl -sSL https://get.docker.com | sh",
```

**Comment by nathanleclaire** [comment]
It is intentional.  The script from `get.docker.com` is always considered the canonical way to install Docker.  In most cases it will patch your kernel to support AUFS if available, and then install Docker using the distro's package manager.

Long-term, we want to move what the script does today, into direct Go code / SSH commands within the Machine provisioners, so that reliance on this script can be removed.

**Comment by dweomer** [comment]
@nathanleclaire that doesn't quite answer what I was trying to ask and that is because of a poor choice of words on my part.

What I was trying to point out is that these three implementations are not honoring the `InstallURL` from the `EngineOptions` attached to the `provisioner` that is in scope.

**Comment by nathanleclaire** [comment]
@dweomer I see.  It is not intentional.  Provisioners should honor `--engine-install-url`.  I've updated the title to reflect this and transition this to "issue report".
