### ISSUE TITLE
docker-machine hangs, boot2docker doesn't

### ISSUE THREAD

**Issue by tmornini** [docker/machine#2542]
On my machine (MacBook Air, Core i7, 8GB, OS X 10.11.1), running `./build_common` from `https://github.com/tmornini/docker-machine-bug-report` will quickly hang a container in a weird state.

Both docker-machine and boot2docker machines were configured with default values except memory size was bumped to 4096 MB on both. The virtualbox driver was used with docker-machine.

docker-toolbox [1.9.1c](https://github.com/docker/toolbox/releases/download/v1.9.1c/DockerToolbox-1.9.1c.pkg)

and brew installed:

docker-machine version: `0.5.1 (HEAD)`

The only way to disconnect from the run command is to run `docker-machine stop machine` from another terminal window...

The behavior is non-deterministic but is more prone to hang than not. Sometimes it'll execute properly once, sometimes it'll hang the first time. I've never seen it run successfully twice in a row, but I suspect it's just statistically unlikely. :-)

Running against boot2docker works just fine, infinitely looping until ctrl-c though it's a bit tricky to catch it at the right moment. Running natively on an AWS EC2 instance using the current Amazon Linux AMI with Docker upgraded as discussed [here](http://stackoverflow.com/questions/32639553/upgrading-docker-on-amazon-linux-ami) works perfectly as well.

```
$ sudo service docker stop
$ sudo cp /usr/bin/docker /usr/bin/docker.old
$ sudo curl -o /usr/bin/docker https://get.docker.com/builds/Linux/x86_64/docker-1.9.1
$ sudo service docker start
```

Docker client version: `1.9.1, build a34a1d5`

**Comment by nathanleclaire** [comment]
I have this uncanny feeling you're running into our old pal https://github.com/docker/docker/issues/18180.  Might want to try on a 1.9.0 VM (using `--virtualbox-boot2docker-url`) to see if the behavior still persists.

**Comment by tmornini** [comment]
@nathanleclaire You're feeling is, indeed, uncanny. :-)

**Comment by thaJeztah** [comment]
@tmornini are both using the `aufs` graphdriver?

**Comment by nathanleclaire** [comment]
Are you adding more memory to that VM by default with `boot2docker`?  If so, that might also explain the discrepancy.

**Comment by tmornini** [comment]
@nathanleclaire Yes

> Both docker-machine and boot2docker machines were configured with default values except memory size was bumped to 4096 MB on both

**Comment by tmornini** [comment]
@thaJeztah I'm not 100% certain, but I think so.

Neither `docker-machine inspect` not `cat ~/.boot2docker/profile` mention aufs, which I believe means it will use the default, which I believe to be aufs. :-)

**Comment by tmornini** [comment]
I think this turns out to be a difference between tight memory conditions.

Yesterday I saw this condition get resolved by increasing the size of the docker-machine memory size.

**Comment by nathanleclaire** [comment]
Odd, I'm not sure why that would be something DM would hang at when b2d wouldn't, other than maybe the extra plugin processes spawned..  Shall we close this issue then?

**Comment by tmornini** [comment]
Yes. I'll reopen if required.
