### ISSUE TITLE
Include instruction to cleanup core driver plugin binaries which are no longer used

### ISSUE THREAD

**Issue by nathanleclaire** [docker/machine#2563]
In 0.5.3 release we no longer need external core binaries, but upgrading users might have them around.  In the release notes we should include a suggestion to remove them such as:

    $ rm /usr/local/bin/docker-machine-driver-{amazonec2,azure,digitalocean,exoscale,generic,google,hyperv,none,openstack,rackspace,softlayer,virtualbox,vmwarefusion,vmwarevcloudair,vmwarevsphere}

@dgageot @jeanlaurent

**Comment by jeanlaurent** [comment]
I believe this is done.

Re-open if I missed something.

**Comment by nathanleclaire** [comment]
:+1:
