### ISSUE TITLE
Docker-machine can't ssh into new machine if --amazonec2-ssh-user is set

### ISSUE THREAD

**Issue by ignasi35** [docker/machine#2567]
I'm creating a docker-machine using driver  amazonec2 and setting an ssh user with the driver's option:

```
docker-machine create \
  --driver amazonec2 \
  --amazonec2-access-key $AWS_ACCESS_KEY \
  --amazonec2-secret-key $AWS_SECRET_KEY \
  --amazonec2-vpc-id vpc-asdf \
  —amazonec2-subnet-id subnet-asdf  \
  --amazonec2-region eu-west-1 \ 
  --amazonec2-zone b \
  --amazonec2-root-size 20 \
  --amazonec2-ssh-user myuser \
  --amazonec2-monitoring true \
  aws01
```
This seems to be stuck when trying to SSH into the newly created machine:

````
Running pre-create checks...
Creating machine...
Waiting for machine to be running, this may take a few minutes...
Machine is running, waiting for SSH to be available...
Error creating machine: Error waiting for SSH: Too many retries waiting for SSH to be available.  Last error: Maximum number of retries (60) exceeded
````

After some test-and-fail (I even tried https://github.com/docker/machine/issues/964#issuecomment-162987333 with several certs) I removed the option ``` --amazonec2-ssh-user myuser ``` and the command succeeded.

**Comment by asciifaceman** [comment]
I am having the same problem, in my case the ec2 machine initializes, is "running" for about half a minute, then stops itself

**Comment by galenp** [comment]
+1

**Comment by galenp** [comment]
I think non issue, see: #1954 for details.

AWS Subnet needs to have Route Table associated from the VPC that you set up previously before running docker-machine create. Referenced issue has the details.

Configure AWS properly, re-run creation and things worked for me.

**Comment by jeanlaurent** [comment]
@ignasi35 while looking at your cli it sounds like you don't use a custom AMI.
What do you want to achieve with a custom SSH username ?

**Comment by ignasi35** [comment]
I assumed the parameter would allow to to create an EC2 machine where only the provided username would have access. Something in the form of: "create instance with default user, useradd 'abc', delete default user".

I got a bit carried away.

PS: I don't have much experience in AWS and some well-known practices when dealing with new machines still go over my head.

**Comment by jeanlaurent** [comment]
I thought the same at first, the documentation was scarse, but has been updated since. 

I'm going to close this.

Please re-open if I missed something.
