### ISSUE TITLE
ssh timeout is not configurable

### ISSUE THREAD

**Issue by jeffellin** [docker/machine#2581]
I am working on a custom driver that builds a stack using cloud formation,   and as such that driver does not require a ssh identity file as we are using a third party ssh authentication mechanism.  Unfortunately, the first time I connect to the host the ssh prompt takes a bit of time since some data needs to be retrieved from our identity server.  This can take more than the hard coded 10seconds for ssh timeout.  

Would it make sense to either a) increase the timeout or b) make it customizable via a config switch? I'd be willing to commit the change if I thought that there was a chance that the PR would be merged in. 

from client.go

    var (
	baseSSHArgs = []string{
		"-o", "PasswordAuthentication=no",
		"-o", "IdentitiesOnly=yes",
		"-o", "StrictHostKeyChecking=no",
		"-o", "UserKnownHostsFile=/dev/null",
		"-o", "LogLevel=quiet", // suppress "Warning: Permanently added '[localhost]:2022' (ECDSA) to the list of known hosts."
		"-o", "ConnectionAttempts=3", // retry 3 times if SSH connection fails
		"-o", "ConnectTimeout=10", // timeout after 10 seconds
		"-o", "ControlMaster=no", // disable ssh multiplexing
		"-o", "ControlPath=no",
	}
	defaultClientType = External
    )

**Comment by jeanlaurent** [comment]
I'm wondering what is the best case to handle those cases.

Increasing the timeout is not a great idea. It is a not a "one size fits all" thing.
Adding the `ConnectTimeout` flag is a way of doing it, but this will add yet another flag. And what about `ControlPath` or `StrictHostKeyChecking` etc...

I believe we should investigate a solution where we should add a `ssh-arg` and pass them to the `ssh` command, overriding default if needed.

**Comment by jeffellin** [comment]
Agree with providing option to override entire ssh options.  Default would use existing settings if flag not provided. Or perhaps delegate to the driver.

**Comment by nathanleclaire** [comment]
Just to make sure, are you 100% positive that the `-o ConnectTimeout=no` is the issue?  Do you have some `ssh -vvv` logs from doing so manually that I could take a look at?  Seems like a really long time for one SSH command to be waiting.

**Comment by jeffellin** [comment]
Yes we are sure. Our ssh daemon is doing some magic behind the scenes the
first time a user logs in. Sets up user account etc. I have a ticket open
with those people to see if there is something they can fix but subsequent
log ins are normal.

**Comment by fsoppelsa** [comment]
It doesn't connect even at second or third attempt?

**Comment by jeffellin** [comment]
Actually it seems that the issue is that after I hand the Create call back the instance still isn't "ready" as its installing the conjur ssh key management piece via cloud formation.  The real issue is that the default number of retries 60 isn't sufficient. 

A possible work around,  although It seems ugly to me is to poll ssh within the driver before handing back control to docker machine.

**Comment by nathanleclaire** [comment]
> A possible work around, although It seems ugly to me is to poll ssh within the driver before handing back control to docker machine.

Although I usually explicitly discourage this type of behavior in drivers (we're converging on a model where they should be as uninvolved with provisioning as possible), in this case it might be unavoidable.

**Comment by jeffellin** [comment]
I am going to go ahead and close this for now since I have a viable work around.

**Comment by nathanleclaire** [comment]
Thanks for following up to close @jeffellin .  What was the workaround?

**Comment by jeffellin** [comment]
Cloud formation has a script that you can execute during init on the host to delay completion of the stack.  By this time connection succeeds.
