### ISSUE TITLE
Docker-machine 0.5.3 outputs status to STDERR instead of STDOUT

### ISSUE THREAD

**Issue by generalov** [docker/machine#2587]
I've installed https://github.com/docker/machine/releases/download/v0.5.3/docker-machine_linux-amd64 to try a [PyCharm](http://blog.jetbrains.com/pycharm/2015/10/announcing-pycharm-5-eap-143-165-docker-integration/) interation with Docker. But on the Python interpreter configuration streen I got an error: 

    Docker Machine returned empty status string for 'localhost'

Internally PyCharm executes commands:
    
    docker-machine ls --quiet  
    docker-machine status localhost

and reads results of the both commands from STDOUT.  

But `docker-machine status` surpriselly outputs the status to STDERR.

```
$ { { docker-machine ls; } 2>&3 | sed 's/^/STDOUT: /'; } 3>&1 1>&2 | sed 's/^/STDERR: /'
STDOUT: NAME        ACTIVE   DRIVER    STATE     URL                    SWARM              DOCKER   ERRORS
STDOUT: localhost   -        generic   Running   tcp://127.0.0.1:2376   Smaster            v1.9.1   
```
```
$ { { docker-machine status localhost; } 2>&3 | sed 's/^/STDOUT: /'; } 3>&1 1>&2 | sed 's/^/STDERR: /'
STDERR: Running
```

**Comment by jeanlaurent** [comment]
We have changed lots of the internal of the outputs in this release, we probably did a mistake.

To investigate.

**Comment by nathanleclaire** [comment]
`log.Info` is printing to STDERR instead of STDOUT as intended.  It's happening with `create` and in a lot of other places as well.

**Comment by generalov** [comment]
Thanks!
