### ISSUE TITLE
Creating Docker Machine

### ISSUE THREAD

**Issue by NathanGRomano** [docker/machine#2590]
Just installed Docker Toolkit on OS X 10.11.1. I had a machine up and running.  After connecting to VPN and then disconnecting from VPN I noticed issues with docker-compose build and docker-compose up.  I disabled the firewall, destroyed the machine and now getting this issue consistently.

```
docker-machine create --driver virtualbox dev
Running pre-create checks...
Creating machine...
(dev) Creating VirtualBox VM...
(dev) Creating SSH key...
(dev) Starting VM...
Waiting for machine to be running, this may take a few minutes...
Machine is running, waiting for SSH to be available...
Detecting operating system of created instance...
Detecting the provisioner...
Provisioning with boot2docker...
Copying certs to the local machine directory...
Copying certs to the remote machine...
Setting Docker configuration on the remote daemon...

This machine has been allocated an IP address, but Docker Machine could not
reach it successfully.

SSH for the machine should still work, but connecting to exposed ports, such as
the Docker daemon port (usually <ip>:2376), may not work properly.

You may need to add the route manually, or use another related workaround.

This could be due to a VPN, proxy, or host file configuration issue.

You also might want to clear any VirtualBox host only interfaces you are not using.
Checking connection to Docker...
Error creating machine: Error checking the host: Error checking and/or regenerating the certs: There was an error validating certificates for host "192.168.99.100:2376": dial tcp 192.168.99.100:2376: i/o timeout
You can attempt to regenerate them using 'docker-machine regenerate-certs [name]'.
Be advised that this will trigger a Docker daemon restart which will stop running containers.
```

**Comment by dgageot** [comment]
Hi @NathanGRomano, can you try again with latest version of docker-machine (0.5.5) and VirtualBox (5.0.12)? Thank you

**Comment by dgageot** [comment]
Hi @NathanGRomano Any update on this? Because of all the fixes on Virtualbox driver lately, we might consider closing this ticket if you don't encounter the error with more recent versions. Thanks for your time!

**Comment by NathanGRomano** [comment]
I think we are food.  Issue resolved I apologize for not updating

**Comment by ehernandez-xk** [comment]
Can you guys can help me with this?

**docker-machine version 0.7.0, build a650a40**
VirtualBox **5.0.24r108355**
**Debian GNU/Linux 8**

`docker-machine create --driver=virtualbox --virtualbox-boot2docker-url=file://`pwd`/boot2docker.iso my-machine`

```
(my-machine) Creating VirtualBox VM...
(my-machine) Creating SSH key...
(my-machine) Starting the VM...
(my-machine) Check network to re-create if needed...
(my-machine) Waiting for an IP...
Waiting for machine to be running, this may take a few minutes...
Detecting operating system of created instance...
Waiting for SSH to be available...
Detecting the provisioner...
Provisioning with boot2docker...
Copying certs to the local machine directory...
Copying certs to the remote machine...
Setting Docker configuration on the remote daemon...

This machine has been allocated an IP address, but Docker Machine could not
reach it successfully.

SSH for the machine should still work, but connecting to exposed ports, such as
the Docker daemon port (usually <ip>:2376), may not work properly.

You may need to add the route manually, or use another related workaround.

This could be due to a VPN, proxy, or host file configuration issue.

You also might want to clear any VirtualBox host only interfaces you are not using.
Checking connection to Docker...
Error creating machine: Error checking the host: Error checking and/or regenerating the certs: There was an error validating certificates for host "192.168.99.101:2376": dial tcp 192.168.99.101:2376: i/o timeout
You can attempt to regenerate them using 'docker-machine regenerate-certs [name]'.
Be advised that this will trigger a Docker daemon restart which will stop running containers.
```

I'm using a local server with Debian 8, all configuration must be done using ssh (command line).

Do you have any idea of this?

**Comment by ehernandez-xk** [comment]
I found that removing the host-only adapter **vboxnet0** the error is removed, If I want to run `docker-machine create` again, the error appears again. How can I fix that?


`VBoxManage hostonlyif remove vboxnet0`
`docker-machine create --driver=virtualbox --virtualbox-boot2docker-url=file://`pwd`/boot2docker.iso my-machine`

`VBoxManage hostonlyif remove vboxnet0`
`docker-machine create --driver=virtualbox --virtualbox-boot2docker-url=file://`pwd`/boot2docker.iso my-machine`

I don't want to remove the host-only adapter in every creation.

**Comment by ovidiub13** [comment]
I still experience this. Removing the host-only adapter solves nothing. It just gets recreated when the VM is created.

docker-machine version 0.12.0, build 45c69ad
Docker version 17.05.0-ce, build 89658be
VirtualBox Version 5.1.22 r115126 (Qt5.7.1)
Host: Kubuntu 17.04
