### ISSUE TITLE
Don't include mock & stubs file in final binaries

### ISSUE THREAD

**Issue by jeanlaurent** [docker/machine#2606]
make file should exclude from the final binary :
- All files ending with _test.go
- All directories ending with test and all files within whatever their name.

**Comment by dgageot** [comment]
What makes you think it is included?

**Comment by jeanlaurent** [comment]
Because we discussed it ?

But's it's more a todo/check than anything else.

**Comment by dgageot** [comment]
I checked with `nm bin/docker-machine` and I don't see test files. Do you?

**Comment by jeanlaurent** [comment]
No, thanks to the linker
