### ISSUE TITLE
Error creating machine: Error with pre-create check: VBoxManage not found. Make sure VirtualBox is installed and VBoxManage is in the path

### ISSUE THREAD

**Issue by Dreampie** [docker/machine#2608]
centos  use overlay muti-host networking.
```
docker-machine create -d virtualbox mh-keystore
Running pre-create checks...
Error creating machine: Error with pre-create check: VBoxManage not found. Make sure VirtualBox is installed and VBoxManage is in the path
```

**Comment by dgageot** [comment]
Hi @Dreampie you have to install Virtualbox before you use the virtualbox driver.
Can you run `which VBoxManage`?

**Comment by Dreampie** [comment]
I use centos，and must create virtualbox？If already have a virtual machine, and how do create virtualbox？

**Comment by dgageot** [comment]
Centos supports native Docker but then you don't need docker-machine.
If you still want to use docker-machine, for eg. to create multiple virtual hosts on your laptop, then you should install VirtualBox, otherwise docker-machine won't work with virtualbox driver.

**Comment by Dreampie** [comment]
if machine already is virtualbox,how to do?

**Comment by Dreampie** [comment]
https://docs.docker.com/engine/userguide/networking/get-started-overlay/  this only for VirtualBox Docker not for native Docker OS？Centos supports native Docker，so it not need to use docker-machine to impl overlay networking？

**Comment by dgageot** [comment]
@Dreampie `docker-machine create -d virtualbox mh-keystore` can only be run on a machine that has VirtualBox installed. This message tells you VirtualBox is not installed. Please install it and try again.

**Comment by dgageot** [comment]
Closing. Not a bug

**Comment by Aaqib041** [comment]
For me same error , I have installed Virtual box but still error exist. Please help

**Comment by saadaouad** [comment]
@Dreampie, @Aaqib041 you have to install VirtualBox : 

```bash
sudo apt-get install virtualbox
```

Then create a machine:
 
```bash
docker-machine create --driver virtualbox default
```

**Comment by Nitinkumar-Gove** [comment]
@saadaouad Thank you for your inputs.

**Comment by saadaouad** [comment]
@Nitinkumar-Gove No problem :+1:

**Comment by smalot** [comment]
Hi All,
Virtualbox is correctly (I Hope) installed on my computer, but I'm encountering this issue.

````
VBoxManage not found. Make sure VirtualBox is installed and VBoxManage is in the path
````

````
~# docker-machine --version
docker-machine version 0.7.0, build a650a40
````

Many thanks

**Comment by gameguyr** [comment]
I just downloaded VirtualBox for mac osx and it started working fine
https://www.virtualbox.org/wiki/Downloads

**Comment by BillioJeverson** [comment]
Hello DreamPie have u manage to solve the problem ? I am having the same problem now . I tried @saadaouad solution but it came up with apt-get not found. please help me out here

**Comment by runstrider** [comment]
same error

**Comment by thibmo** [comment]
That is because apt is only for Debian-like distributions, like Debian (Duh), Ubuntu, Mint, etc... OSx does NOT have apt......

**Comment by omidbabaeigithub** [comment]
I just export PATH=$PATH:$(which vboxmanage) before executing docker-machine create ...

**Comment by etrim** [comment]
Install the newest version of docker-machine from github.
https://github.com/docker/machine

**Comment by salimfadhley** [comment]
I'm stuck on this as well. VirtualBox is installed and VBoxManage is in my path:

```
sal@gruntyman:~/PycharmProjects/exoduspoint_homework$ docker-machine create --driver virtualbox dev
Running pre-create checks...
Error with pre-create check: "VBoxManage not found. Make sure VirtualBox is installed and VBoxManage is in the path"
sal@gruntyman:~/PycharmProjects/exoduspoint_homework$ which VBoxManage 
/usr/bin/VBoxManage
```
Any idea what might be going wrong here?

**Comment by albertzubkowicz** [comment]
same here. fresh install (according to https://docs.docker.com/install/linux/docker-ce/ubuntu/#install-using-the-repository), path added to ~/.bashrc, but the error persists.

**Comment by wapmorgan** [comment]
I think it's important to note:
1. **Remove docker, installed via snap**.
2. Install docker-machine with **official instructions**: https://docs.docker.com/machine/install-machine/

**Comment by gasparyanyur** [comment]
```
$ docker-machine create --driver virtualbox default
Running pre-create checks...
Error with pre-create check: "VBoxManage not found. Make sure VirtualBox is installed and VBoxManage is in the path"
```
OS: Ubuntu - 18.04

```
$ which virtualbox 
/usr/bin/virtualbox
$ which VBoxManage 
/usr/bin/VBoxManage

```

Can not solve this problem!

**Comment by chovy** [comment]
I'm still having same issue on 18.04 LTS

**Comment by albertzubkowicz** [comment]
I've managed to resolve it by adding user to docker group and restarting system.

**Comment by SundeepPidugu** [comment]
@albertzubkowicz  how do i do that ? and i still have the same issue

**Comment by albertzubkowicz** [comment]
@SundeepPidugu https://docs.docker.com/install/linux/linux-postinstall/

**Comment by SundeepPidugu** [comment]
@albertzubkowicz Can you please post a set of required instructions that i can follow for the same.

**Comment by albertzubkowicz** [comment]
@SundeepPidugu just install docker with official instructions and do post-install from above link.

**Comment by sytae** [comment]
> I just export PATH=$PATH:$(which vboxmanage) before executing docker-machine create ...

This solved my issue. Thanks!

**Comment by KacperBiedka** [comment]
In my case one of the most random fixes happened. After running docker run hello-world it got fixed automatically O.o

**Comment by sakthivelj** [comment]
> export PATH=$PATH:$(which vboxmanage)

```
tyrebot@tyrebot-PhotoGAUGE:~$ docker-machine create --driver virtualbox default
Running pre-create checks...
Error with pre-create check: "VBoxManage not found. Make sure VirtualBox is installed and VBoxManage is in the path"
```
