### ISSUE TITLE
Test suite leaks into user's data store.

### ISSUE THREAD

**Issue by sthulb** [docker/machine#261]
Running `go test` leaves a 'test' machine after the tests run.

Ideally, we should create a test store in `/tmp` or in the current dir and clean up afterwards.

**Comment by ehazlett** [comment]
Well ideally you use the `script/test` which runs them in a container.  Perhaps we need more clarification in the readme?

**Comment by sthulb** [comment]
As per @ehazlett's comment, the desired path is inside a container.
