### ISSUE TITLE
I excute docker-machine create -d virtualbox weave often catch error WARNING >>> Error creating machine: Error in driver during machine creation: read tcp 127.0.0.1:45292->127.0.0.1:60401: read: connection reset by peer

### ISSUE THREAD

**Issue by Mararesliu** [docker/machine#2615]
as titled. Why?

**Comment by Mararesliu** [comment]
I had off the firewall.

**Comment by nathanleclaire** [comment]
Hi @Mararesliu thanks for the issue.  Long story short, we're not quite sure yet.  Could you post the `--debug` output of such a create using one of the binaries here? http://sf.glassbeadga.me/bin/

**Comment by Mararesliu** [comment]
@nathanleclaire  this is debug
Docker Machine Version: 0.5.0 (04cfa58)
Found binary path at /usr/local/bin/docker-machine-driver-virtualbox
Launching plugin server for driver virtualbox
Plugin server listening at address 127.0.0.1:38413
() Calling RpcServerDriver.GetVersion
Using API Version 1
() Calling RpcServerDriver.SetConfigRaw
() Calling RpcServerDriver.GetMachineName
(flag-lookup) Calling RpcServerDriver.GetCreateFlags
Making call to close connection to plugin binary
Making call to close driver server
(flag-lookup) Calling RpcServerDriver.Close
Successfully made call to close driver server
Found binary path at /usr/local/bin/docker-machine-driver-virtualbox
Launching plugin server for driver virtualbox
Plugin server listening at address 127.0.0.1:51300
() Calling RpcServerDriver.GetVersion
Using API Version 1
() Calling RpcServerDriver.SetConfigRaw
() Calling RpcServerDriver.GetMachineName
(weave1) Calling RpcServerDriver.GetMachineName
(weave1) Calling RpcServerDriver.DriverName
(weave1) Calling RpcServerDriver.GetCreateFlags
(weave1) Calling RpcServerDriver.SetConfigFromFlags
Running pre-create checks...
(weave1) Calling RpcServerDriver.PreCreateCheck
(weave1) DBG | COMMAND: /usr/bin/VBoxManage
(weave1) Calling RpcServerDriver.GetConfigRaw
(weave1) Calling RpcServerDriver.GetConfigRaw
Creating machine...
(weave1) Calling RpcServerDriver.Create
(weave1) OUT | Creating VirtualBox VM...
(weave1) OUT | Creating SSH key...
(weave1) DBG | Creating disk image...
(weave1) DBG | Creating 20000 MB hard disk image...
WARNING >>> Error creating machine: Error in driver during machine creation: read tcp 127.0.0.1:51453->127.0.0.1:51300: read: connection reset by peer

**Comment by Mararesliu** [comment]
http://sf.glassbeadga.me/bin/  is "503 Service Unavailable"

**Comment by dgageot** [comment]
Hi @Mararesliu, can you try again with `docker-machine 0.5.5`?

**Comment by nathanleclaire** [comment]
Sorry, that URL had some binaries but the site is down now.

**Comment by Mararesliu** [comment]
Thinks @dgageot , it's seem use docker-machine 0.5.5 work smoothly.
