### ISSUE TITLE
Unable to provision with generic driver (exit status 1)

### ISSUE THREAD

**Issue by festum** [docker/machine#2616]
I have a CentOS 7 with net-tools installed on local VMware Workstation

```
C:\Users\Festum> docker-machine create -d generic --generic-ip-address 192.168.13.129 --generic-ssh-user festum cent
Running pre-create checks...
Creating machine...
(cent) Importing SSH key...
Waiting for machine to be running, this may take a few minutes...
Machine is running, waiting for SSH to be available...
Detecting operating system of created instance...
Detecting the provisioner...
Provisioning with centos...
Error creating machine: Error running provisioning: exit status 1
```

**Comment by oliamb** [comment]
Can you re-run with -D command to see the log details:

```shell
docker-machine -D create -d generic --generic-ip-address 192.168.13.129 --generic-ssh-user festum cent
```

**Comment by Festum** [comment]
Sure

```
λ docker-machine -D create -d generic --generic-ip-address 192.168.13.129 --generic-ssh-user festu m cent
Docker Machine Version: 0.5.2 ( 0456b9f )
Found binary path at C:\Program Files\Docker Toolbox\docker-machine-driver-generic.exe
Launching plugin server for driver generic
Plugin server listening at address 127.0.0.1:60154
() Calling .GetVersion
Using API Version 1
() Calling .SetConfigRaw
() Calling .GetMachineName
(flag-lookup) Calling .GetCreateFlags
Making call to close connection to plugin binary
Making call to close driver server
(flag-lookup) Calling .Close
Successfully made call to close driver server
Found binary path at C:\Program Files\Docker Toolbox\docker-machine-driver-generic.exe
Launching plugin server for driver generic
Plugin server listening at address 127.0.0.1:60158
() Calling .GetVersion
Using API Version 1
() Calling .SetConfigRaw
() Calling .GetMachineName
(cent) Calling .GetMachineName
(cent) Calling .DriverName
(cent) Calling .GetCreateFlags
(cent) Calling .SetConfigFromFlags
Creating CA: C:\Users\Festum\.docker\machine\certs\ca.pem
Creating client certificate: C:\Users\Festum\.docker\machine\certs\cert.pem
Running pre-create checks...
(cent) Calling .PreCreateCheck
(cent) Calling .GetConfigRaw
Creating machine...
(cent) Calling .Create
(cent) Importing SSH key...
(cent) Calling .GetConfigRaw
(cent) DBG | IP: 192.168.13.129
(cent) Calling .DriverName
Waiting for machine to be running, this may take a few minutes...
(cent) Calling .GetState
Machine is running, waiting for SSH to be available...
Getting to WaitForSSH function...
(cent) Calling .GetSSHHostname
(cent) Calling .GetSSHPort
(cent) Calling .GetSSHKeyPath
(cent) Calling .GetSSHUsername
Using SSH client type: external
About to run SSH command:
exit 0
SSH cmd err, output: <nil>:
Detecting operating system of created instance...
Detecting the provisioner...
(cent) Calling .GetSSHHostname
(cent) Calling .GetSSHPort
(cent) Calling .GetSSHKeyPath
(cent) Calling .GetSSHUsername
Using SSH client type: external
About to run SSH command:
cat /etc/os-release
SSH cmd err, output: <nil>: NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"


Couldn't set key CPE_NAME, no corresponding struct field found
Couldn't set key , no corresponding struct field found
Couldn't set key CENTOS_MANTISBT_PROJECT, no corresponding struct field found
Couldn't set key CENTOS_MANTISBT_PROJECT_VERSION, no corresponding struct field found
Couldn't set key REDHAT_SUPPORT_PRODUCT, no corresponding struct field found
Couldn't set key REDHAT_SUPPORT_PRODUCT_VERSION, no corresponding struct field found
Couldn't set key , no corresponding struct field found
found compatible host: centos
Provisioning with centos...
(cent) Calling .GetMachineName
(cent) Calling .GetSSHHostname
(cent) Calling .GetSSHPort
(cent) Calling .GetSSHKeyPath
(cent) Calling .GetSSHUsername
Using SSH client type: external
Error creating machine: Error running provisioning: exit status 1
```

**Comment by kumar2000s** [comment]
i am also facing the same issue , any suggestion ?

**Comment by dgageot** [comment]
@Festum @kumar2000s Can you gist the content of `cat /etc/os-release`?

**Comment by kumar2000s** [comment]
here is the output:
[root@~]# cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

**Comment by kumar2000s** [comment]
[root@no1010042193248 ~]#  docker-machine -D  --native-ssh create --driver generic --generic-ip-address xx.xx.xx.xx --generic-ssh-user root   node1
Docker Machine Version:  0.5.4, build 6643d0e
Found binary path at /usr/local/bin/docker-machine
Launching plugin server for driver generic
Plugin server listening at address 127.0.0.1:59801
() Calling .GetVersion
Using API Version  1
() Calling .SetConfigRaw
() Calling .GetMachineName
(flag-lookup) Calling .GetCreateFlags
Making call to close connection to plugin binary
Making call to close driver server
(flag-lookup) Calling .Close
Successfully made call to close driver server
Found binary path at /usr/local/bin/docker-machine
Launching plugin server for driver generic
Plugin server listening at address 127.0.0.1:42189
() Calling .GetVersion
Using API Version  1
() Calling .SetConfigRaw
() Calling .GetMachineName
(node1) Calling .GetMachineName
(node1) Calling .DriverName
(node1) Calling .GetCreateFlags
(node1) Calling .SetConfigFromFlags
Running pre-create checks...
(node1) Calling .PreCreateCheck
(node1) Calling .GetConfigRaw
Creating machine...
(node1) Calling .Create
(node1) No SSH key specified. Connecting to this machine now and in the future will require the ssh agent to contain the appropriate key.
(node1) Calling .GetConfigRaw
(node1) DBG | IP: xx.xx.xx.xx
(node1) Calling .DriverName
Waiting for machine to be running, this may take a few minutes...
(node1) Calling .GetState
Machine is running, waiting for SSH to be available...
Getting to WaitForSSH function...
(node1) Calling .GetSSHHostname
(node1) Calling .GetSSHPort
(node1) Calling .GetSSHKeyPath
(node1) Calling .GetSSHUsername
Using SSH client type: native
About to run SSH command:
exit 0
Error dialing TCP: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none], no supported methods remain
Error dialing TCP: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none], no supported methods remain
Error dialing TCP: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none], no supported methods remain
Error dialing TCP: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none], no supported methods remain
Error dialing TCP: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none], no supported methods remain

**Comment by Festum** [comment]
➜  ~  cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

**Comment by EtienneK** [comment]
Getting the same issue:

# cat /etc/os-release
NAME="Red Hat Enterprise Linux Server"
VERSION="7.2 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="7.2"
PRETTY_NAME=RHEV
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.2:GA:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.2
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.2"

**Comment by gartcimore** [comment]
I have something similar when trying to use the generic driver with an existing host, (it failed when using the hostname or an ip address) : 

docker-machine -D create  --driver=generic --generic-ip-address bskerrigan --generic-ssh-user=genesys --generic-ssh-key /home/vagrant/.ssh/id_dsa --swarm     --swarm-master     --swarm-discovery token://e424d938f87c5d1b5529ac2f1d1b4773 kerrigan-swarm-master
Docker Machine Version: 0.5.3, build 4d39a66
Found binary path at /usr/local/bin/docker-machine
Launching plugin server for driver generic
Plugin server listening at address 127.0.0.1:59011
() Calling .GetVersion
Using API Version 1
() Calling .SetConfigRaw
() Calling .GetMachineName
(flag-lookup) Calling .GetCreateFlags
Making call to close connection to plugin binary
Making call to close driver server
(flag-lookup) Calling .Close
Successfully made call to close driver server
Found binary path at /usr/local/bin/docker-machine
Launching plugin server for driver generic
Plugin server listening at address 127.0.0.1:52899
() Calling .GetVersion
Using API Version 1
() Calling .SetConfigRaw
() Calling .GetMachineName
(kerrigan-swarm-master) Calling .GetMachineName
(kerrigan-swarm-master) Calling .DriverName
(kerrigan-swarm-master) Calling .GetCreateFlags
(kerrigan-swarm-master) Calling .SetConfigFromFlags
Running pre-create checks...
(kerrigan-swarm-master) Calling .PreCreateCheck
(kerrigan-swarm-master) Calling .GetConfigRaw
Creating machine...
(kerrigan-swarm-master) Calling .Create
(kerrigan-swarm-master) Importing SSH key...
(kerrigan-swarm-master) DBG | IP: bskerrigan
(kerrigan-swarm-master) Calling .GetConfigRaw
(kerrigan-swarm-master) Calling .DriverName
Waiting for machine to be running, this may take a few minutes...
(kerrigan-swarm-master) Calling .GetState
Machine is running, waiting for SSH to be available...
Getting to WaitForSSH function...
(kerrigan-swarm-master) Calling .GetSSHHostname
(kerrigan-swarm-master) Calling .GetSSHPort
(kerrigan-swarm-master) Calling .GetSSHKeyPath
(kerrigan-swarm-master) Calling .GetSSHKeyPath
(kerrigan-swarm-master) Calling .GetSSHUsername
Using SSH client type: external
About to run SSH command:
exit 0
SSH cmd err, output: <nil>: 
Detecting operating system of created instance...
Detecting the provisioner...
(kerrigan-swarm-master) Calling .GetSSHHostname
(kerrigan-swarm-master) Calling .GetSSHPort
(kerrigan-swarm-master) Calling .GetSSHKeyPath
(kerrigan-swarm-master) Calling .GetSSHKeyPath
(kerrigan-swarm-master) Calling .GetSSHUsername
Using SSH client type: external
About to run SSH command:
cat /etc/os-release
SSH cmd err, output: <nil>: NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"


Couldn't set key CPE_NAME, no corresponding struct field found
Couldn't set key , no corresponding struct field found
Couldn't set key CENTOS_MANTISBT_PROJECT, no corresponding struct field found
Couldn't set key CENTOS_MANTISBT_PROJECT_VERSION, no corresponding struct field found
Couldn't set key REDHAT_SUPPORT_PRODUCT, no corresponding struct field found
Couldn't set key REDHAT_SUPPORT_PRODUCT_VERSION, no corresponding struct field found
Couldn't set key , no corresponding struct field found
found compatible host: centos
Provisioning with centos...
(kerrigan-swarm-master) Calling .GetMachineName
(kerrigan-swarm-master) Calling .GetSSHHostname
(kerrigan-swarm-master) Calling .GetSSHPort
(kerrigan-swarm-master) Calling .GetSSHKeyPath
(kerrigan-swarm-master) Calling .GetSSHKeyPath
(kerrigan-swarm-master) Calling .GetSSHUsername
Using SSH client type: external
notifying bugsnag: [Error running provisioning: exit status 1]
Error creating machine: Error running provisioning: exit status 1

**Comment by jstoner** [comment]
I am seeing the same issue with a freshly downloaded CentOS 7 image. Downloaded it, gave it a static IP, made my user sudo and set up the ssh key, and kablooey.

[ jstoner@erzulie:~ ]
2s $> docker-machine -D create --driver generic --generic-ip-address=192.168.80.252 --generic-ssh-user jstoner default
Docker Machine Version:  0.6.0, build e27fb87
Found binary path at /usr/local/bin/docker-machine
Launching plugin server for driver generic
Plugin server listening at address 127.0.0.1:61681
() Calling .GetVersion
Using API Version  1
() Calling .SetConfigRaw
() Calling .GetMachineName
(flag-lookup) Calling .GetMachineName
(flag-lookup) Calling .DriverName
(flag-lookup) Calling .GetCreateFlags
Found binary path at /usr/local/bin/docker-machine
Launching plugin server for driver generic
Plugin server listening at address 127.0.0.1:61685
() Calling .GetVersion
Using API Version  1
() Calling .SetConfigRaw
() Calling .GetMachineName
(default) Calling .GetMachineName
(default) Calling .DriverName
(default) Calling .GetCreateFlags
(default) Calling .SetConfigFromFlags
Running pre-create checks...
(default) Calling .PreCreateCheck
(default) Calling .GetConfigRaw
Creating machine...
(default) Calling .Create
(default) No SSH key specified. Connecting to this machine now and in the future will require the ssh agent to contain the appropriate key.
(default) DBG | IP: 192.168.80.252
(default) Calling .GetConfigRaw
(default) Calling .DriverName
(default) Calling .DriverName
Waiting for machine to be running, this may take a few minutes...
(default) Calling .GetState
Detecting operating system of created instance...
Waiting for SSH to be available...
Getting to WaitForSSH function...
(default) Calling .GetSSHHostname
(default) Calling .GetSSHPort
(default) Calling .GetSSHKeyPath
(default) Calling .GetSSHUsername
Using SSH client type: external
{[-o BatchMode=yes -o PasswordAuthentication=no -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=quiet -o ConnectionAttempts=3 -o ConnectTimeout=10 -o ControlMaster=no -o ControlPath=none jstoner@192.168.80.252 -p 22] /usr/bin/ssh}
About to run SSH command:
exit 0
SSH cmd err, output: <nil>:
Detecting the provisioner...
(default) Calling .GetSSHHostname
(default) Calling .GetSSHPort
(default) Calling .GetSSHKeyPath
(default) Calling .GetSSHUsername
Using SSH client type: external
{[-o BatchMode=yes -o PasswordAuthentication=no -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=quiet -o ConnectionAttempts=3 -o ConnectTimeout=10 -o ControlMaster=no -o ControlPath=none jstoner@192.168.80.252 -p 22] /usr/bin/ssh}
About to run SSH command:
cat /etc/os-release
SSH cmd err, output: <nil>: NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"


Couldn't set key CPE_NAME, no corresponding struct field found
Couldn't set key , no corresponding struct field found
Couldn't set key CENTOS_MANTISBT_PROJECT, no corresponding struct field found
Couldn't set key CENTOS_MANTISBT_PROJECT_VERSION, no corresponding struct field found
Couldn't set key REDHAT_SUPPORT_PRODUCT, no corresponding struct field found
Couldn't set key REDHAT_SUPPORT_PRODUCT_VERSION, no corresponding struct field found
Couldn't set key , no corresponding struct field found
found compatible host: centos
Provisioning with centos...
No storagedriver specified, using devicemapper

(default) Calling .GetMachineName
(default) Calling .GetSSHHostname
(default) Calling .GetSSHPort
(default) Calling .GetSSHKeyPath
(default) Calling .GetSSHUsername
Using SSH client type: external
{[-o BatchMode=yes -o PasswordAuthentication=no -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=quiet -o ConnectionAttempts=3 -o ConnectTimeout=10 -o ControlMaster=no -o ControlPath=none jstoner@192.168.80.252 -p 22] /usr/bin/ssh}
(default) Calling .GetSSHHostname
(default) Calling .GetSSHPort
(default) Calling .GetSSHKeyPath
(default) Calling .GetSSHUsername
Using SSH client type: external
{[-o BatchMode=yes -o PasswordAuthentication=no -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=quiet -o ConnectionAttempts=3 -o ConnectTimeout=10 -o ControlMaster=no -o ControlPath=none jstoner@192.168.80.252 -p 22] /usr/bin/ssh}
installing base package: name=curl
(default) Calling .GetSSHHostname
(default) Calling .GetSSHPort
(default) Calling .GetSSHKeyPath
(default) Calling .GetSSHUsername
Using SSH client type: external
{[-o BatchMode=yes -o PasswordAuthentication=no -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=quiet -o ConnectionAttempts=3 -o ConnectTimeout=10 -o ControlMaster=no -o ControlPath=none jstoner@192.168.80.252 -p 22] /usr/bin/ssh}
Error creating machine: Error running provisioning: exit status 1
Opting out of crash reporting.
[ jstoner@erzulie:~ ]
4s $> ssh 192.168.80.252
Last login: Thu Feb 18 14:00:15 2016 from 192.168.80.28
[jstoner@default ~]$ cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

**Comment by foleymic** [comment]
I had the same problem and was able to resolve it by granting password-less sudo privileges to the ssh-user.  I found this out by reading here: [https://github.com/docker/machine/blob/master/docs/drivers/generic.md#interaction-with-ssh-agents](https://github.com/docker/machine/blob/master/docs/drivers/generic.md#interaction-with-ssh-agents)

**Comment by sebadiaz** [comment]
Same issue with openstack provisionning

+1

docker-machine --debug create -d openstack --openstack-flavor-name m1.medium --openstack-image-name centos7 --openstack-ssh-user centos --openstack-sec-groups toall   --openstack-nova-network=true --openstack-floatingip-pool public centos
Docker Machine Version: 0.5.0 (04cfa58)
Found binary path at /usr/local/bin/docker-machine-driver-openstack
Launching plugin server for driver openstack
Plugin server listening at address 127.0.0.1:37381
() Calling RpcServerDriver.GetVersion
Using API Version 1
() Calling RpcServerDriver.SetConfigRaw
() Calling RpcServerDriver.GetMachineName
(flag-lookup) Calling RpcServerDriver.GetCreateFlags
Making call to close connection to plugin binary
Making call to close driver server
(flag-lookup) Calling RpcServerDriver.Close
Successfully made call to close driver server
Found binary path at /usr/local/bin/docker-machine-driver-openstack
Launching plugin server for driver openstack
Plugin server listening at address 127.0.0.1:42341
() Calling RpcServerDriver.GetVersion
Using API Version 1
() Calling RpcServerDriver.SetConfigRaw
() Calling RpcServerDriver.GetMachineName
(centos) Calling RpcServerDriver.GetMachineName
(centos) Calling RpcServerDriver.DriverName
(centos) Calling RpcServerDriver.GetCreateFlags
(centos) Calling RpcServerDriver.SetConfigFromFlags
Running pre-create checks...
(centos) Calling RpcServerDriver.PreCreateCheck
(centos) Calling RpcServerDriver.GetConfigRaw
(centos) Calling RpcServerDriver.GetConfigRaw
Creating machine...
(centos) Calling RpcServerDriver.Create
(centos) DBG | Authenticating...		 AuthUrl=http://fr1pslcmf01:5000/v2.0 DomainID= DomainName= Insecure=false TenantID= TenantName=alt_demo Username=alt_demo
(centos) DBG | Found flavor id using its name		 ID=3 Name=m1.medium
(centos) DBG | Found image id using its name		 ID=f722310a-ab85-4d51-9808-1dd74139c8f0 Name=centos7
(centos) DBG | Creating Key Pair...		 Name=centos-eb6edc83fabe2b38731bfcd217ddeac91c2b8bbf22551ee2f9eeec4da8af146b
(centos) OUT | Creating machine...
(centos) DBG | Creating OpenStack instance...		 FlavorId=3 ImageId=f722310a-ab85-4d51-9808-1dd74139c8f0
(centos) DBG | Waiting for the OpenStack instance to be ACTIVE...		 MachineId=88cf6841-ee4d-43ba-a325-f4796105ed07
(centos) DBG | Looking for an available floating IP		 MachineId=88cf6841-ee4d-43ba-a325-f4796105ed07 Pool=public
(centos) DBG | Available floating IP found		 IP=10.21.22.4 MachineId=88cf6841-ee4d-43ba-a325-f4796105ed07
(centos) DBG | Assigning floating IP to the instance		 MachineId=88cf6841-ee4d-43ba-a325-f4796105ed07
(centos) Calling RpcServerDriver.GetConfigRaw
(centos) DBG | IP address found		 IP=10.21.22.4 MachineId=88cf6841-ee4d-43ba-a325-f4796105ed07
(centos) Calling RpcServerDriver.GetConfigRaw
(centos) Calling RpcServerDriver.DriverName
Waiting for machine to be running, this may take a few minutes...
(centos) Calling RpcServerDriver.GetState
(centos) DBG | Get status for OpenStack instance...		 MachineId=88cf6841-ee4d-43ba-a325-f4796105ed07
Machine is running, waiting for SSH to be available...
Getting to WaitForSSH function...
(centos) Calling RpcServerDriver.GetSSHHostname
(centos) DBG | State for OpenStack instance		 MachineId=88cf6841-ee4d-43ba-a325-f4796105ed07 State=ACTIVE
(centos) Calling RpcServerDriver.GetSSHPort
(centos) Calling RpcServerDriver.GetSSHKeyPath
(centos) Calling RpcServerDriver.GetSSHUsername
Using SSH client type: external
About to run SSH command:
exit 0
SSH cmd err, output: exit status 255: 
Error getting ssh command 'exit 0' : Something went wrong running an SSH command!
command : exit 0
err     : exit status 255
output  : 

Getting to WaitForSSH function...
(centos) Calling RpcServerDriver.GetSSHHostname
(centos) Calling RpcServerDriver.GetSSHPort
(centos) Calling RpcServerDriver.GetSSHKeyPath
(centos) Calling RpcServerDriver.GetSSHUsername
Using SSH client type: external
About to run SSH command:
exit 0
SSH cmd err, output: <nil>: 
Detecting operating system of created instance...
(centos) Calling RpcServerDriver.GetSSHHostname
(centos) Calling RpcServerDriver.GetSSHPort
(centos) Calling RpcServerDriver.GetSSHKeyPath
(centos) Calling RpcServerDriver.GetSSHUsername
Using SSH client type: external
About to run SSH command:
cat /etc/os-release
SSH cmd err, output: <nil>: NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"


Couldn't set key CPE_NAME, no corresponding struct field found
Couldn't set key , no corresponding struct field found
Couldn't set key CENTOS_MANTISBT_PROJECT, no corresponding struct field found
Couldn't set key CENTOS_MANTISBT_PROJECT_VERSION, no corresponding struct field found
Couldn't set key REDHAT_SUPPORT_PRODUCT, no corresponding struct field found
Couldn't set key REDHAT_SUPPORT_PRODUCT_VERSION, no corresponding struct field found
Couldn't set key , no corresponding struct field found
found compatible host: centos
Provisioning created instance...
(centos) Calling RpcServerDriver.GetMachineName
(centos) Calling RpcServerDriver.GetSSHHostname
(centos) Calling RpcServerDriver.GetSSHPort
(centos) Calling RpcServerDriver.GetSSHKeyPath
(centos) Calling RpcServerDriver.GetSSHUsername
Using SSH client type: external
(centos) Calling RpcServerDriver.GetSSHHostname
(centos) Calling RpcServerDriver.GetSSHPort
(centos) Calling RpcServerDriver.GetSSHKeyPath
(centos) Calling RpcServerDriver.GetSSHUsername
Using SSH client type: external
(centos) Calling RpcServerDriver.GetSSHHostname
(centos) Calling RpcServerDriver.GetSSHPort
(centos) Calling RpcServerDriver.GetSSHKeyPath
(centos) Calling RpcServerDriver.GetSSHUsername
Using SSH client type: external
installing docker
(centos) Calling RpcServerDriver.GetSSHHostname
(centos) Calling RpcServerDriver.GetSSHPort
(centos) Calling RpcServerDriver.GetSSHKeyPath
(centos) Calling RpcServerDriver.GetSSHUsername
Using SSH client type: external
(centos) Calling RpcServerDriver.GetSSHHostname
(centos) Calling RpcServerDriver.GetSSHPort
(centos) Calling RpcServerDriver.GetSSHKeyPath
(centos) Calling RpcServerDriver.GetSSHUsername
Using SSH client type: external
(centos) Calling RpcServerDriver.GetSSHHostname
(centos) Calling RpcServerDriver.GetSSHPort
(centos) Calling RpcServerDriver.GetSSHKeyPath
(centos) Calling RpcServerDriver.GetSSHUsername
Using SSH client type: external
(centos) Calling RpcServerDriver.GetSSHHostname
(centos) Calling RpcServerDriver.GetSSHPort
(centos) Calling RpcServerDriver.GetSSHKeyPath
(centos) Calling RpcServerDriver.GetSSHUsername
Using SSH client type: external
(centos) Calling RpcServerDriver.GetSSHHostname
(centos) Calling RpcServerDriver.GetSSHPort
(centos) Calling RpcServerDriver.GetSSHKeyPath
(centos) Calling RpcServerDriver.GetSSHUsername
Using SSH client type: external
(centos) Calling RpcServerDriver.GetSSHHostname
(centos) Calling RpcServerDriver.GetSSHPort
(centos) Calling RpcServerDriver.GetSSHKeyPath
(centos) Calling RpcServerDriver.GetSSHUsername
Using SSH client type: external
(centos) Calling RpcServerDriver.GetSSHHostname
(centos) Calling RpcServerDriver.GetSSHPort
(centos) Calling RpcServerDriver.GetSSHKeyPath
(centos) Calling RpcServerDriver.GetSSHUsername
Using SSH client type: external
(centos) Calling RpcServerDriver.GetMachineName
(centos) Calling RpcServerDriver.GetIP
Copying certs to the local machine directory...
generating server cert: /home/misys/.docker/machine/machines/centos/server.pem ca-key=/home/misys/.docker/machine/certs/ca.pem private-key=/home/misys/.docker/machine/certs/ca-key.pem org=misys.centos
(centos) Calling RpcServerDriver.GetSSHHostname
(centos) Calling RpcServerDriver.GetSSHPort
(centos) Calling RpcServerDriver.GetSSHKeyPath
(centos) Calling RpcServerDriver.GetSSHUsername
Using SSH client type: external
Copying certs to the remote machine...
(centos) Calling RpcServerDriver.GetSSHHostname
(centos) Calling RpcServerDriver.GetSSHPort
(centos) Calling RpcServerDriver.GetSSHKeyPath
(centos) Calling RpcServerDriver.GetSSHUsername
Using SSH client type: external
(centos) Calling RpcServerDriver.GetSSHHostname
(centos) Calling RpcServerDriver.GetSSHPort
(centos) Calling RpcServerDriver.GetSSHKeyPath
(centos) Calling RpcServerDriver.GetSSHUsername
Using SSH client type: external
(centos) Calling RpcServerDriver.GetSSHHostname
(centos) Calling RpcServerDriver.GetSSHPort
(centos) Calling RpcServerDriver.GetSSHKeyPath
(centos) Calling RpcServerDriver.GetSSHUsername
Using SSH client type: external
(centos) Calling RpcServerDriver.GetURL
(centos) Calling RpcServerDriver.DriverName
Setting Docker configuration on the remote daemon...
(centos) Calling RpcServerDriver.GetSSHHostname
(centos) Calling RpcServerDriver.GetSSHPort
(centos) Calling RpcServerDriver.GetSSHKeyPath
(centos) Calling RpcServerDriver.GetSSHUsername
Using SSH client type: external
(centos) Calling RpcServerDriver.GetSSHHostname
(centos) Calling RpcServerDriver.GetSSHPort
(centos) Calling RpcServerDriver.GetSSHKeyPath
(centos) Calling RpcServerDriver.GetSSHUsername
Using SSH client type: external
(centos) Calling RpcServerDriver.GetSSHHostname
(centos) Calling RpcServerDriver.GetSSHPort
(centos) Calling RpcServerDriver.GetSSHKeyPath
(centos) Calling RpcServerDriver.GetSSHUsername
Using SSH client type: external
(centos) Calling RpcServerDriver.GetSSHHostname
(centos) Calling RpcServerDriver.GetSSHPort
(centos) Calling RpcServerDriver.GetSSHKeyPath
(centos) Calling RpcServerDriver.GetSSHUsername
Using SSH client type: external
(centos) Calling RpcServerDriver.GetSSHHostname
(centos) Calling RpcServerDriver.GetSSHPort
(centos) Calling RpcServerDriver.GetSSHKeyPath
(centos) Calling RpcServerDriver.GetSSHUsername
Using SSH client type: external
(centos) Calling RpcServerDriver.GetSSHHostname
(centos) Calling RpcServerDriver.GetSSHPort
(centos) Calling RpcServerDriver.GetSSHKeyPath
(centos) Calling RpcServerDriver.GetSSHUsername
Using SSH client type: external
(centos) Calling RpcServerDriver.GetSSHHostname
(centos) Calling RpcServerDriver.GetSSHPort
(centos) Calling RpcServerDriver.GetSSHKeyPath
(centos) Calling RpcServerDriver.GetSSHUsername
Using SSH client type: external
(centos) Calling RpcServerDriver.GetSSHHostname
(centos) Calling RpcServerDriver.GetSSHPort
(centos) Calling RpcServerDriver.GetSSHKeyPath
(centos) Calling RpcServerDriver.GetSSHUsername
Using SSH client type: external
Error creating machine: Error running provisioning: Unable to verify the Docker daemon is listening: Maximum number of retries (5) exceeded

**Comment by blaggacao** [comment]
Here is the answer, it is not supported yet for native ssh client:

https://github.com/docker/machine/blob/master/docs/drivers/generic.md#password-protected-ssh-keys

**Comment by chrisfelix82** [comment]
Any progress on this?  I am having issues as well on RHEL 7

**Comment by ltzMaxwell** [comment]
same issue on centos7 ,any progress ?

**Comment by gintsgints** [comment]
Please check target machine logs. Many issues is related on host ability to execute remote commands.

**Comment by gintsgints** [comment]
I got process hanging on 
```
{[-o BatchMode=yes -o PasswordAuthentication=no -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=quiet -o ConnectionAttempts=3 -o ConnectTimeout=10 -o ControlMaster=no -o ControlPath=none gpolis@10.15.4.129 -o IdentitiesOnly=yes -i /home/gpolis/.docker/machine/machines/laimdota-dc1/id_rsa -p 22] /usr/bin/ssh}
```
And on host, list of the processes shows:
```
bash -c sudo hostname laimdota-dc1 && echo "laimdota-dc1" | sudo tee /etc/hostname
```

So imho it hangs on trying to set hostname or right after this.

**Comment by festum** [comment]
Close due to outdated.
