### ISSUE TITLE
Add existing host or reconfig name/ip for an existing machine

### ISSUE THREAD

**Issue by krasi-georgiev** [docker/machine#2621]
Often I need to add an already configured machine 
docker-machine add ip 

or simply reconfigure an existing machine in the list.
docker-machine config rename oldName newName
docker-machine config ip oldIp newIp

Is this in the future roadmap ?

**Comment by nathanleclaire** [comment]
We might support some limited modification of already created VMs in the future, but implementing a rename across all drivers (remember, the name also dictates names of created resources and hostnames, etc. as well as being a logical name) is an intimidatingly large change.

**Comment by vipconsult** [comment]
we need to think about this and the multi client access to existing machine as well.
