### ISSUE TITLE
The output from the drivers is truncated when a create fails

### ISSUE THREAD

**Issue by dgageot** [docker/machine#2622]
When a Create fails, the end of the driver's output is not captured. This means that:
 + The user sometimes can't see what caused the creation failure
 + The bugsnag reports miss the most important part

**Comment by nathanleclaire** [comment]
Dupe of: https://github.com/docker/machine/issues/2217

I have what seems to be a fix for this in the pipe.

**Comment by dgageot** [comment]
Closing. Duplicate of @22217
