### ISSUE TITLE
Local VM hypervisors should save state

### ISSUE THREAD

**Issue by sthulb** [docker/machine#263]
Instead of using stop/start, we should save state of the machine. 

We could implement this in two ways: we can either:
1. Introduce pause & unpause commands
2. Make stop & start save machine state and restore it via a flag

This would stop machines losing state when they don't have to be around any longer. This would be helpful on B2D machines.

**Comment by sthulb** [comment]
Apparently already fixed using another method...

**Comment by Tebro** [comment]
At least my boot2docker machines seem to get reset, I use VMWare Fusion:

machine stop dev
machine start dev
docker ps
FATA[0011] TLS Handshake error: dial tcp 192.168.102.137:2376: connection refused 

But IRC claims an update is coming, so just leaving this here as documentation.
