### ISSUE TITLE
Pasting commands to terminal doesn't work

### ISSUE THREAD

**Issue by kolodny** [docker/machine#2631]
see docker/docker#18772

For example if I paste the following in the terminal:

```
docker-machine ssh default 'echo test1'
echo test2
echo test3
```

I'll only get `test1` printed:

```
$ docker-machine ssh default echo test1
echo test2
echo test3
test1
$
```

consider the expected behavior:

```
sleep 4
echo test1
echo test2
```

result:

```
$ sleep 4
echo test1
echo test2
$ echo test1
test1
$ echo test2
test2
$
```

Some info:

```
$ docker version
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   a34a1d5
 Built:        Fri Nov 20 17:56:04 UTC 2015
 OS/Arch:      darwin/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   a34a1d5
 Built:        Fri Nov 20 17:56:04 UTC 2015
 OS/Arch:      linux/amd64

$ docker info
Containers: 4
Images: 318
Server Version: 1.9.1
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 326
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.1.13-boot2docker
Operating System: Boot2Docker 1.9.1 (TCL 6.4.1); master : cef800b - Fri Nov 20 19:33:59 UTC 2015
CPUs: 4
Total Memory: 7.79 GiB
Name: default
ID: RRUD:3SUW:WC3U:TMC5:S32S:QPZW:JIGJ:2KWF:PSUZ:ZEZI:7TMV:6ZSP
Debug mode (server): true
 File Descriptors: 34
 Goroutines: 61
 System Time: 2015-12-18T19:13:15.423353104Z
 EventsListeners: 0
 Init SHA1: 
 Init Path: /usr/local/bin/docker
 Docker Root Dir: /mnt/sda1/var/lib/docker
Username: kolodny
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox

$ uname -a
Darwin Moshes-MacBook-Pro.local 14.4.0 Darwin Kernel Version 14.4.0: Thu May 28 11:35:04 PDT 2015; root:xnu-2782.30.5~1/RELEASE_X86_64 x86_64

```

**Comment by fsoppelsa** [comment]
```
$ docker-machine ssh v1 'echo test1; echo test2; echo test3'
test1
test2
test3
```

**Comment by nathanleclaire** [comment]
Hi @kolodny, thanks for the report.

@fsoppelsa has the right idea.  We can't really cover every possibly semantic desired of `ssh`, so usually it's asked that you wrap such multi-line invocations in quotes.  I think it seems like a pretty fair ask.

**Comment by kolodny** [comment]
@fsoppelsa @nathanleclaire I think you're misunderstanding the issue. I'm trying to write a script that someone can paste into the terminal. Some of those commands do stuff over docker. The expected behavior is for the commands to wait for the previous command to finish, copy this into your terminal to see what I mean:

```
echo pinging googles dns
ping -c 5 8.8.8.8
echo done

```

The same mechanism doesn't work for docker-machine

**Comment by fsoppelsa** [comment]
This is not a dm issue.

I can suggest to look into your shell manpage for `&&`, `\`, and maybe `expect`.

**Comment by nathanleclaire** [comment]
@kolodny, why not this:

```console
$ docker-machine ssh default 'echo pinging googles dns
ping -c 5 8.8.8.8
echo done'
```

?

**Comment by alcalyn** [comment]
Put all commands in one exec works in this case, but I get the same issue, and I can't use this workaround because I need to `exec` commands on multiple containers:

``` bash
docker exec -ti php /bin/bash -c "composer update"
docker exec -ti database /bin/bash -c "mysql -u root -proot -e 'create database somedatabase;'"
docker exec -ti php /bin/bash -c "bin/console orm:schema-tool:create"
```

I expect all these commands run, but only the first one is run.

I tried adding `sleep 1` between commands, not working.
I tried adding `; \` to the end of each lines, it works, but if I add empty line to add comments, like:

``` bash
docker exec -ti php /bin/bash -c "composer update"; \
docker exec -ti database /bin/bash -c "mysql -u root -proot -e 'create database somedatabase;'"; \

# Comment
docker exec -ti php /bin/bash -c "bin/console orm:schema-tool:create"; \
```

Only the two first commands are run, so I consider this is still not a good workaround as it is not the expected behaviour, and counter intuitive.
