### ISSUE TITLE
Dose not work on Windows Azure Chinese version. 

### ISSUE THREAD

**Issue by hunter-xue** [docker/machine#2639]
get error below: 
Error creating machine: Error with pre-create check: Code: ForbiddenError, Message: The server failed to authenticate the request. Verify that the certificate is valid and is associated with this subscription.

**Comment by ahmetalpbalkan** [comment]
@hunter-xue This is good feedback. I think the current Azure driver is written in a way that it only supports AzurePublic environment and not AzureChina. I am rewriting the Azure driver and I will make sure we make this configurable.

**Comment by ahmetalpbalkan** [comment]
Also this is a dupe of #1547.

**Comment by ahmetalpbalkan** [comment]
@hunter-xue I added China support for the new Azure driver that's upcoming, however apparently our new Azure Resource Manager stack is not fully deployed to AzureChina yet, once it does I believe you'll be able to use it.

**Comment by hunter-xue** [comment]
@ahmetalpbalkan Very cool. Yes, Resource Manager mode cannot working well on Azure China right now. 
BTW: I am Azure solution architect and I can help you to do some test on Azure China if you need.

**Comment by ahmetalpbalkan** [comment]
@hunter-xue I believe Core RPs will be deployed to China in the next week or so, please a keep an eye on that. The new azure driver is currently being reviewed (#3159) and you can download it here http://cl.ly/fLkb until it is merged or build it from source yourself.

All you need to do while creating the machine is to say:

    docker-machine create -d azure --azure-environment AzureChinaCloud [...]

or set environment variable `AZURE_ENVIRONMENT` to `AzureChinaCloud` in your shell before creating the machine(s) and it should work just fine.

I only had a chance to test the authentication but I got failure calling the deployment APIs as the Core RPs are not yet deployed. Feel free to close the issue once you have a chance to verify.

**Comment by ahmetalpbalkan** [comment]
@hunter-xue I should also note that, from my experience being the author of [azure-docker-extension](https://github.com/Azure/azure-docker-extension) (which does a very similar job as docker machine), you will have a lot of trouble using this driver in China.

Half of the time docker installation (`curl get.docker.com | sh `) will fail because of the GFW and your VM creation will therefore fail in the middle of the process. Just giving an heads-up notice that it'll not be as successful as running this in public cloud in non-China regions.

**Comment by ahmetalpbalkan** [comment]
@hunter-xue This now works:

```
$ docker-machine create -d azure --azure-location chinaeast foo

Running pre-create checks...
(foo2) Registering subscription to resource provider.  ns="Microsoft.Network" subs="92178e8c-69a2-497b-821a-f4fa0a9a539d"
(foo2) Completed machine pre-create checks.
Creating machine...
(foo2) Querying existing resource group.  name="docker-machine"
(foo2) Creating resource group.  name="docker-machine" location="chinaeast"
(foo2) Configuring availability set.  name="docker-machine"
(foo2) Configuring network security group.  name="foo2-firewall" location="chinaeast"
(foo2) Querying if virtual network already exists.  name="docker-machine-vnet" location="chinaeast"
(foo2) Configuring subnet.  name="docker-machine" vnet="docker-machine-vnet" cidr="192.168.0.0/16"
(foo2) Creating public IP address.  name="foo2-ip" static=false
(foo2) Creating network interface.  name="foo2-nic"
(foo2) Creating storage account.  name="vhds3t2gu47sbso0ry1om1hi" location="chinaeast"
(foo2) Creating virtual machine.  name="foo2" location="chinaeast" size="Standard_A2" username="docker-user" osImage="canonical:UbuntuServer:15.10:latest"
Waiting for machine to be running, this may take a few minutes...
Detecting operating system of created instance...
Waiting for SSH to be available...
Detecting the provisioner...
Provisioning with ubuntu(systemd)...
Installing Docker...
Copying certs to the local machine directory...
Copying certs to the remote machine...
Setting Docker configuration on the remote daemon...
Checking connection to Docker...
Docker is up and running!
```

Please try it out and consider closing the issue.

**Comment by hunter-xue** [comment]
@ahmetalpbalkan Many thanks for your information. Really good news for Azure China users.
