### ISSUE TITLE
Docker Machine listing need to clearly identify machine or cluster

### ISSUE THREAD

**Issue by arun-gupta** [docker/machine#2653]
Three Docker Machines are created to participate in Docker Swarm. `docker-machine ls` shows the output as:

```
swarm-master       *        virtualbox   Running   tcp://192.168.99.107:2376   swarm-master (master)
swarm-node-01      -        virtualbox   Running   tcp://192.168.99.108:2376   swarm-master
swarm-node-02      -        virtualbox   Running   tcp://192.168.99.109:2376   swarm-master
```

This output does not convey any information whether the environment is configured for `swarm-master` machine or the cluster.

**Comment by dgageot** [comment]
Hi @arun-gupta is it something like https://github.com/docker/machine/pull/1253 that you'd expect?

**Comment by arun-gupta** [comment]
@dgageot yes, that's what I'm looking for.

**Comment by dgageot** [comment]
ping @nathanleclaire now you know what you have to do :-)
