### ISSUE TITLE
Make setting envvars easier

### ISSUE THREAD

**Issue by ericandrewlewis** [docker/machine#2665]
Every time I want to interact with Docker, I run `eval "$(docker-machine env default)"` in my shell.

Can we make this process easier? Is it possible to make a command that sets env for you, rather than having to remember to run the output of `docker-machine env` in a subshell? e.g. `docker-machine setenv default`?

**Comment by dgageot** [comment]
Hi @ericandrewlewis, sorry it's not something that's possible with bash. A command cannot set env variables on the parent shell. If I recall correctly, fish can do it though.
To solve this issue, we would have to use a different mechanism than env variables. Creating a config file that would be known to docker cli. But that's another story!

**Comment by ericandrewlewis** [comment]
Ah that makes sense. Thanks for indulging my naiveté of how computers work :smile:
