### ISSUE TITLE
Single confirmation of exclusion for multiple hosts

### ISSUE THREAD

**Issue by rafabene** [docker/machine#2671]
I ran the following command: docker-machine rm mh-keystore swarm-master swarm-node-01 swarm-node-02

But it asked to confirm the exclusion for each machine: 

```
Do you really want to remove "mh-keystore"? (y/n): y
(mh-keystore) Stopping VM...
Successfully removed mh-keystore
Do you really want to remove "swarm-master"? (y/n): y
(swarm-master) Stopping VM...
Successfully removed swarm-master
Do you really want to remove "swarm-node-01"? (y/n): y
(swarm-node-01) Stopping VM...
Successfully removed swarm-node-01
Do you really want to remove "swarm-node-02"? (y/n): y
(swarm-node-02) Stopping VM...
Successfully removed swarm-node-02
```

For standard purpose it should act as docker-compose: docker-compose rm

```
Going to remove swarm_wildfly_1, db, modcluster
Are you sure? [yN] y
Removing swarm_wildfly_1 ... done
Removing db ... done
Removing modcluster ... done
```

**Comment by dgageot** [comment]
Hi @rafabene, yes, I think you are right. Would you like to contribute?

**Comment by rafabene** [comment]
I would love it but I'm still learning Golang to be a more active contributor.

**Comment by dgageot** [comment]
That fix is a good opportunity to practice you know!

**Comment by rafabene** [comment]
Exactly! :+1: 

So challenge accepted :D (and since it's not a priority bug fix) 

I'll be fully busy until March 2016 but after then I would love to contribute. 


Thanks @dgageot
