### ISSUE TITLE
Setting up Swarm: "Error checking and/or regenerating the certs"

### ISSUE THREAD

**Issue by lionpants** [docker/machine#2677]
I've been following the documentation found here https://docs.docker.com/swarm/install-w-machine/ to get a new Docker Swarm with Consul setup. Everything works fine until I try and run the following command.

`docker-machine env --swarm swarm-master`

I then receive the following error.

`Error checking TLS connection: Error checking and/or regenerating the certs: There was an error validating certificates for host "192.168.99.104:3376": dial tcp 192.168.99.104:3376: getsockopt: connection refused`

I've tried destroying all VMs and starting from scratch. I've also tried regenerating all certs for the 3 swarm machines. Same problem. What am I missing?

**Details**

`docker-machine ls` output

consul-master      -        virtualbox   Running   tcp://192.168.99.100:2376                           v1.9.1
consul-server-01   -        virtualbox   Running   tcp://192.168.99.101:2376                           v1.9.1
consul-server-02   -        virtualbox   Running   tcp://192.168.99.102:2376                           v1.9.1
swarm-master       *        virtualbox   Running   tcp://192.168.99.104:2376   swarm-master (master)   v1.9.1
swarm-node-01      -        virtualbox   Running   tcp://192.168.99.105:2376   swarm-master            v1.9.1
swarm-node-02      -        virtualbox   Running   tcp://192.168.99.106:2376   swarm-master    v1.9.1

Browsing to http://192.168.99.100:8500/ui shows that Consul is working properly.

Please see attached for the work in progress shell script I am using to generate this environment.

[setup-env.sh.zip](https://github.com/docker/machine/files/71242/setup-env.sh.zip)

**Comment by dgageot** [comment]
Hi @lionpants Can you check that swarm didn't fail to start on the master?

```
$ docker-machine ssh swarm-master docker inspect -f "{{.State.Running}}" "swarm-agent-master"
true
$ docker-machine ssh swarm-master docker logs swarm-agent-master
```

**Comment by lionpants** [comment]
After running the first command...

`Error: No such image or container: swarm-agent-master`

The second...

`Error response from daemon: no such id: swarm-agent-master`

docker@swarm-master:~$ docker ps -a
CONTAINER ID        IMAGE                           COMMAND                  CREATED             STATUS              PORTS                                                                                                                                                                                          NAMES
90e9e24f7814        gliderlabs/registrator:latest   "/bin/registrator con"   7 minutes ago       Up 7 minutes                                                                                                                                                                                                       registrator-swarm-master
a7a6be64351e        progrium/consul                 "/bin/start -advertis"   8 minutes ago       Up 8 minutes        192.168.99.104:8300-8302->8300-8302/tcp, 192.168.99.104:8400->8400/tcp, 192.168.99.104:8500->8500/tcp, 192.168.99.104:8301-8302->8301-8302/udp, 172.17.0.1:53->53/tcp, 172.17.0.1:53->53/udp   consul

**Comment by lionpants** [comment]
Bah, I just realized the problem...

After I create each machine I kill all containers (just in case the script was run a second time and the containers already exist). I didn't realize that Swarm creates its own containers, thus my container kill script wipes them out. :(

All seems to be working now.

Thanks, happy holidays!

**Comment by dgageot** [comment]
Same for you!
