### ISSUE TITLE
docker-machine bash auto-complete error

### ISSUE THREAD

**Issue by ajayrathore** [docker/machine#2689]
Using docker on mac os, just downloaded the scripts from here https://github.com/docker/machine/tree/master/contrib/completion/bash

trying to auto-complete and getting this error
[ajay@ajaymbp /Users/ajay$ ~]$ docker-machine -bash: _get_comp_words_by_ref: command not found
-bash: ((: i < : syntax error: operand expected (error token is " ")

**Comment by thaJeztah** [comment]
ping @albers is this something similar to https://github.com/docker/docker/pull/16492?

**Comment by albers** [comment]
@ajayrathore The `_get_comp_words_by_ref` function mentioned in your error message is provided by the _bash completion_ package. I assume that you either do not have this package installed or are not working in a login shell, see https://github.com/docker/docker/issues/18140#issuecomment-166611858.
@thaJeztah It's a different thing. https://github.com/docker/docker/pull/16492 is about using an unsupported command in bash completion, this one looks like a configuration issue.

**Comment by thaJeztah** [comment]
@albers thanks!

/me crawls back to the bash completions n00b corner

**Comment by ajayrathore** [comment]
ok thanks, I will check my configuration

**Comment by hholst80** [comment]
I think this was a pretty solid bug report. Think about it: If one person went the mile to bug report this to you guys how many people will run into this problem world-wide? 

@ajayrathore consider a reopen?

The bugfix MVP at Stackoverflow: http://stackoverflow.com/questions/85880/determine-if-a-function-exists-in-bash. 

If the extension is not found - return the same thing as if the script had not been loaded.

**Comment by HerveNivon** [comment]
I'm late, but none on the previous comment actually solved my problem.

The solution has been found here: http://izeye.blogspot.fr/2016/09/bash-getcompwordsbyref-command-not-found.html

`bash-completion` was not correctly installed on my `mac`.

Adding the following lines to my `.bash_profile` made it work:
```bash
And add the following to '.bash_profile':

if [ -f $(brew --prefix)/etc/bash_completion ]; then
  . $(brew --prefix)/etc/bash_completion
fi
```
