### ISSUE TITLE
Can't run your example libmachine/examples/vbox_create.go

### ISSUE THREAD

**Issue by blacktop** [docker/machine#2690]
When I run https://github.com/docker/machine/blob/master/libmachine/examples/vbox_create.go I get:
```bash
$ go run vbox_create.go                                                                                                          

Found binary path at /var/folders/cc/rtlqvl2x3gs2bljhbk60nrp40000gn/T/go-build000574690/command-line-arguments/_obj/exe/example
Launching plugin server for driver virtualbox
Plugin server listening at address
dial tcp: missing address
exit status 1
```

**Comment by nathanleclaire** [comment]
Yeah, it's outdated (and from when `libmachine` was working as a module independent of the plugins system) and arguably should be removed entirely.

**Comment by blacktop** [comment]
@nathanleclaire I would love to see a working example of how to get this working remotely from other go code. pretty please! :smile:

**Comment by mssola** [comment]
I think that this has been solved with commits 00eee7db1d409e14a4d1e8f3dbc64d45e07a8ffd, 263f8c5cddaef930427a1b1b1a5829b842a08620 and 85405468de1d92ef2c5e38d34741a702ec8909fe; no ? At least I can run this example (I had to upgrade to 0.5.6)

**Comment by dgageot** [comment]
@blacktop @mssola yes, this should work now

**Comment by blacktop** [comment]
@mssola @dgageot it works great now MUCH thanks! :heart:
