### ISSUE TITLE
Error in libmachine/mcndockerclient/docker_client.go

### ISSUE THREAD

**Issue by blacktop** [docker/machine#2703]
### github.com/docker/machine/libmachine/mcndockerclient
../../docker/machine/libmachine/mcndockerclient/docker_client.go:35: not enough arguments in call to docker.CreateContainer

**Comment by blacktop** [comment]
This might actually be due to a package name collision in my program.

**Comment by blacktop** [comment]
Nope, you are missing the **AuthConfig**

func (client *DockerClient) CreateContainer(config *ContainerConfig, name string, auth *AuthConfig) (string, error)

**Comment by sandywater** [comment]
:+1:

**Comment by dgageot** [comment]
Hello @blacktop you shouldn't have this problem. We vendor a version of dockerclient that is not the latest and in which `CreateContainer` takes only two parameters.
That said, I'm going to update our version of dockerclient because it seems outdated.

**Comment by blacktop** [comment]
@dgageot much thanks! I now see if I would have done a godep restore or used the vendor experiment I would have had the right older version of the code.  I was just doing a `go get -u`

Thanks again.  You guys are awesome! :+1:
