### ISSUE TITLE
swarm provisioning: 'Always' is not a valid restart policy

### ISSUE THREAD

**Issue by dweomer** [docker/machine#2715]
I believe the recent refactoring of swarm provisioning that makes use of the docker client instead of go templates has broken swarm containers that are provisioned by docker-machine from properly restarting when the docker daemon is restarted because of an improperly capitalized restart policy of `Always` that should instead be `always`.

```
✘-1 19:08 (jacob@JLEBC-LWS) ~ $ docker run -itd --restart Always nginx
docker: invalid restart policy Always.
See 'docker run --help'.
```

**Comment by dgageot** [comment]
Fixed with https://github.com/docker/machine/pull/2716
