### ISSUE TITLE
binaries at the 'unofficial pre-compiled master binaries' link in README are from 2015/10/15

### ISSUE THREAD

**Issue by dweomer** [docker/machine#2718]
I just noticed this link in the [troubleshooting section of the README](https://github.com/docker/machine#troubleshooting). The binaries that live there are out of date and therefore seem to me to be not nearly as useful as advertised.

**Comment by thaJeztah** [comment]
Good catch!

ping @ehazlett were you planning on updating those again, or should that reference be removed?

**Comment by nathanleclaire** [comment]
I think this was taken care of, no?
