### ISSUE TITLE
Volume Mounting issue on OSX

### ISSUE THREAD

**Issue by digitaldavenyc** [docker/machine#2736]
Trying to mount my source files to a directory in docker located outside of my /Users directory. If you try to move the /Users directory in Virtualbox, Docker Volume mounting doesn't work anymore, even if you try to revert back to the /Users directory.  The only way to fix the issue is to delete the Docker machine and recreate it.

Docker version is **1.9.1** and running on **OSX 10.10.5**

Steps to reproduce:

1. Install docker 1.9.1
2. `docker-machine create --driver virtualbox dev`
3. Change shared folder location to outside /Users directory in **Virtualbox**
4. `docker-machine restart dev`
5. `eval "$(docker-machine env dev)"`
6. `docker build -t davesrepo/dynamo -f ./Dockerfile .`
7. `docker run -v $(pwd):/var/dynamo -d -t -p 8001:8001 --env-file ./dynamo.env --name dynamo davesrepo/dynamo`
8. `docker exec -it dynamo /bin/bash`

    root@235196b7fcd6:/var/dynamo# ls
    root@235196b7fcd6:/var/dynamo#

I tried to move the share folder outside of the /Users directory, that didn't work. So let's try to revert it back to the /Users directory

1. `docker stop dynamo`
2. `docker rm dynamo`
3. Revert shared folder to /Users/dave directory
4. `docker-machine restart dev`
5. `eval "$(docker-machine env dev)"`
6. `docker build -t davesrepo/dynamo -f ./Dockerfile .`
7. `docker run -v $(pwd):/var/dynamo -d -t -p 8001:8001 --env-file ./dynamo.env --name dynamo davesrepo/dynamo`
8. `docker exec -it dynamo /bin/bash`

`root@235196b7fcd6:/var/dynamo# ls`
`root@235196b7fcd6:/var/dynamo#`

No files after reverting to /Users folder.

Running `docker inspect dynamo` shows the directory mounted properly

    [
    {
        "Id": "7d3d338891aae32e001a3bb31d6be17802d238526830396472b011599a97212a",
        "Created": "2015-12-29T03:37:01.416445958Z",
        "Path": "python3",
        "Args": [],
        "State": {
            "Status": "running",
            "Running": true,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 1314,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2015-12-29T03:37:01.516253705Z",
            "FinishedAt": "0001-01-01T00:00:00Z"
        },
        "Image": "19697c9b5c7561b113d817821280971f063ea0187c82343c0832348fb6863c9a",
        "ResolvConfPath": "/mnt/sda1/var/lib/docker/containers/7d3d338891aae32e001a3bb31d6be17802d238526830396472b011599a97212a/resolv.conf",
        "HostnamePath": "/mnt/sda1/var/lib/docker/containers/7d3d338891aae32e001a3bb31d6be17802d238526830396472b011599a97212a/hostname",
        "HostsPath": "/mnt/sda1/var/lib/docker/containers/7d3d338891aae32e001a3bb31d6be17802d238526830396472b011599a97212a/hosts",
        "LogPath": "/mnt/sda1/var/lib/docker/containers/7d3d338891aae32e001a3bb31d6be17802d238526830396472b011599a97212a/7d3d338891aae32e001a3bb31d6be17802d238526830396472b011599a97212a-json.log",
        "Name": "/dynamo",
        "RestartCount": 0,
        "Driver": "aufs",
        "ExecDriver": "native-0.2",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "",
        "ExecIDs": null,
        "HostConfig": {
            "Binds": [
                "/Users/dave/Sites/davesrepo/dynamo:/var/dynamo"
            ],
            "ContainerIDFile": "",
            "LxcConf": [],
            "Memory": 0,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "KernelMemory": 0,
            "CpuShares": 0,
            "CpuPeriod": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "CpuQuota": 0,
            "BlkioWeight": 0,
            "OomKillDisable": false,
            "MemorySwappiness": -1,
            "Privileged": false,
            "PortBindings": {
                "8001/tcp": [
                    {
                        "HostIp": "",
                        "HostPort": "8001"
                    }
                ]
            },
            "Links": null,
            "PublishAllPorts": false,
            "Dns": [],
            "DnsOptions": [],
            "DnsSearch": [],
            "ExtraHosts": null,
            "VolumesFrom": null,
            "Devices": [],
            "NetworkMode": "default",
            "IpcMode": "",
            "PidMode": "",
            "UTSMode": "",
            "CapAdd": null,
            "CapDrop": null,
            "GroupAdd": null,
            "RestartPolicy": {
                "Name": "no",
                "MaximumRetryCount": 0
            },
            "SecurityOpt": null,
            "ReadonlyRootfs": false,
            "Ulimits": null,
            "LogConfig": {
                "Type": "json-file",
                "Config": {}
            },
            "CgroupParent": "",
            "ConsoleSize": [
                0,
                0
            ],
            "VolumeDriver": ""
        },
        "GraphDriver": {
            "Name": "aufs",
            "Data": null
        },
        "Mounts": [
            {
                "Source": "/Users/dave/Sites/davesrepo/dynamo",
                "Destination": "/var/dynamo",
                "Mode": "",
                "RW": true
            }
        ],
        "Config": {
            "Hostname": "7d3d338891aa",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "8001/tcp": {}
            },
            "Tty": true,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "APP_ENV=development",
                "PYTHONPATH=$PYTHONPATH:/var/dynamo",
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "LANG=C.UTF-8",
                "PYTHON_VERSION=3.5.1",
                "PYTHON_PIP_VERSION=7.1.2"
            ],
            "Cmd": [
                "python3"
            ],
            "Image": "davesrepo/dynamo",
            "Volumes": null,
            "WorkingDir": "/var/dynamo",
            "Entrypoint": null,
            "OnBuild": null,
            "Labels": {},
            "StopSignal": "SIGTERM"
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "71d99a7d11908a9d1c0156fd33eb3f0ff5ef9f6697bb77103fe2caa1cf488530",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {
                "8001/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "8001"
                    }
                ]
            },
            "SandboxKey": "/var/run/docker/netns/71d99a7d1190",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "1cc99b0de89700368f31b43248c90ea45cec756712a2bd2ba2dc57293a5d0a72",
            "Gateway": "172.17.0.1",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "172.17.0.2",
            "IPPrefixLen": 16,
            "IPv6Gateway": "",
            "MacAddress": "02:42:ac:11:00:02",
            "Networks": {
                "bridge": {
                    "EndpointID": "1cc99b0de89700368f31b43248c90ea45cec756712a2bd2ba2dc57293a5d0a72",
                    "Gateway": "172.17.0.1",
                    "IPAddress": "172.17.0.2",
                    "IPPrefixLen": 16,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "02:42:ac:11:00:02"
                }
            }
        }
    }
    ]

Docker info and version

    Daves-MacBook-Pro:dynamo dave$ docker version
    Client:
     Version:      1.9.1
     API version:  1.21
     Go version:   go1.4.3
     Git commit:   a34a1d5
     Built:        Fri Nov 20 17:56:04 UTC 2015
     OS/Arch:      darwin/amd64
    
    Server:
     Version:      1.9.1
     API version:  1.21
     Go version:   go1.4.3
     Git commit:   a34a1d5
     Built:        Fri Nov 20 17:56:04 UTC 2015
     OS/Arch:      linux/amd64

 

    Daves-MacBook-Pro:dynamo dave$ docker info
    Containers: 1
    Images: 17
    Server Version: 1.9.1
    Storage Driver: aufs
     Root Dir: /mnt/sda1/var/lib/docker/aufs
     Backing Filesystem: extfs
     Dirs: 19
     Dirperm1 Supported: true
    Execution Driver: native-0.2
    Logging Driver: json-file
    Kernel Version: 4.1.13-boot2docker
    Operating System: Boot2Docker 1.9.1 (TCL 6.4.1); master : cef800b - Fri Nov 20 19:33:59 UTC 2015
    CPUs: 1
    Total Memory: 996.2 MiB
    Name: dev
    ID: Z32E:B2D3:HS74:KDSU:CQ5V:7Q5U:ZMUW:LHY7:KUJ7:S2XK:HHEZ:KZS2
    Debug mode (server): true
     File Descriptors: 15
     Goroutines: 28
     System Time: 2015-12-31T03:15:06.906277246Z
     EventsListeners: 0
     Init SHA1:
     Init Path: /usr/local/bin/docker
     Docker Root Dir: /mnt/sda1/var/lib/docker
    Labels:
     provider=virtualbox

**Comment by nathanleclaire** [comment]
Hi @digitaldavenyc, thanks for the issue.

It's not recommended to try and modify the existing `/Users` share through the VirtualBox GUI.  boot2docker has some existing init scripts to set up the mount that expect the share to be present there and will generally balk if that's not the case.  If you want to mount something outside of `/Users` my recommendation is to add it to VirtualBox GUI and run `mount` yourself inside of the VM over SSH.  Thanks.

**Comment by digitaldavenyc** [comment]
@nathanleclaire Ok I have a couple of follow up comments / questions.

1. I think it would be helpful to add a warning somewhere when the share folder is changed in VirtualBox. I am an existing VirtualBox user and always have changed the /Users share folder location. The fact that this broke something in Docker was not obvious until someone from the community let me know that this is not recommended. 

2. When you say to mount inside the VM over SSH, would that be inside the machine VM or the docker container?

**Comment by nathanleclaire** [comment]
> I think it would be helpful to add a warning somewhere when the share folder is changed in VirtualBox. I am an existing VirtualBox user and always have changed the /Users share folder location. The fact that this broke something in Docker was not obvious until someone from the community let me know that this is not recommended.

Yes, I think our documentation could definitely be improved in this area.

> When you say to mount inside the VM over SSH, would that be inside the machine VM or the docker container?

Machine VM.  In the VM's shell you need to run some type of `mount -o vboxsf` command to actually mount your shared folder in the VM.

**Comment by digitaldavenyc** [comment]
I was thinking it would be most help for docker itself to notify of mounting issue, but a documentation update would certainly help as well.
