### ISSUE TITLE
swarm containers does not start automatically, after docker host reboot.

### ISSUE THREAD

**Issue by kunalkushwaha** [docker/machine#2751]
Ideally, containers which are default to node like, swarm containers should auto start after host is rebooted. If a host with swarm is created, rejoining cluster on reboot is desired behaviour.

- Though, currently there is no particular way to understand, if swarm containers are created while host creation, current reserved names "swarm-agent" & "swarm-agent-master" can be used for identifying the containers.

**Comment by dweomer** [comment]
I submitted a PR to fix this that was recently merged into master,  https://github.com/docker/machine/pull/2716. Currently I do not see it as included in the [next release/milestone](https://github.com/docker/machine/milestones/0.6.0).

**Comment by dweomer** [comment]
@nathanleclaire @dgageot @ehazlett (forgive me if I am not associated the correct users): this would seem like an important fix to get into the next milestone, no?

**Comment by dgageot** [comment]
Don't worry, @dweomer, it was merged so it will be in version 0.6.0

**Comment by dweomer** [comment]
Of course it will, I blame a lack of caffeine for this derp

**Comment by dgageot** [comment]
Here it is :coffee:

**Comment by dgageot** [comment]
Fixed with https://github.com/docker/machine/pull/2716

**Comment by kunalkushwaha** [comment]
Thanks :)
