### ISSUE TITLE
create --swarm doesn't have a way to specify options on the swarm agent

### ISSUE THREAD

**Issue by gittycat** [docker/machine#2761]
The `--swarm-opt` options are only used to create the swarm master container. There is currently no way to specify startup options for the swarm-agent container (see [configure-swarm.go](https://github.com/docker/machine/blob/61fed5c11bef5e8b48af02020f0475fcfdeeab10/libmachine/provision/configure_swarm.go)).

I may be missing something here but how can the swarm-agent be automatically restarted when its host is rebooted since swarm-agent isn't created using an option like `--restart=always`?

**Comment by dweomer** [comment]
@ehazlett @nathanleclaire @dgageot  This speaks to the need for injecting compositions at the tail end of the provisioning process (or possibly post-provisioning), no? See https://github.com/docker/machine/issues/1663#issuecomment-131260348

**Comment by gittycat** [comment]
@dweomer Ok so this means that there is currently no way to create a High Availability swarm cluster using `docker-machine create`.

**Comment by nathanleclaire** [comment]
We _do_ start it with `--restart always` (although in the switch to `samalba/dockerclient` this seems to have regressed, it is now fixed on master): https://github.com/docker/machine/blob/276e7e48b675290dd933f9ffe1861ec1c2438511/libmachine/provision/configure_swarm.go#L92

Was there something else you had in mind @gittycat ?

**Comment by gittycat** [comment]
Thanks @nathanleclaire, the latest code from master works for me.

There still isn't a mechanism to specify other startup options (swarmOptions.ArbitraryFlags) to the swarm-agent but I personally don't have a need for it now that the swarm agents/master restart automatically. I'll let others re-open if they have a need for it.
