### ISSUE TITLE
Support for multi-master HA swarm 

### ISSUE THREAD

**Issue by kunalkushwaha** [docker/machine#2771]
Swarm supports [HA configuration](https://docs.docker.com/swarm/multi-manager-setup/) for Master with ``--replication`` flag. But machine provisioning code doesn't have support for same.  

while machine creation, ``--replication`` flag can be passed, which can configure ``swarm-agent-master`` container with ``--replication`` flag.

**Comment by nathanleclaire** [comment]
Maybe a `--swarm-replication` flag for `create` which instructs a created master to also be a replica?  At the same time, we have some fundamental assumptions about what it means to be a master which will need to be changed first.  Currently our model is only one-master-per-swarm.

**Comment by kunalkushwaha** [comment]
Currently, if we try to create more then one swarm masters with same KV store, it is permitted.
Also, all becomes part of same cluster, But they manage scheduling independently i.e. none of master shares information with others, I think this is not expected behaviour.

Will it be not correct to support ``--replication`` by default. In this case, if multiple masters are created with same KV store, it will created as replica instead of independent masters?

**Comment by kunalkushwaha** [comment]
Since this issue gets fixed with PR #2833, Closing the issue.

**Comment by nathanleclaire** [comment]
Thanks for following up to close the issue @kunalkushwaha
