### ISSUE TITLE
Stopping machine results in error

### ISSUE THREAD

**Issue by tdensmore** [docker/machine#2772]
**Docker version 1.9.1, build a34a1d5**
**docker-machine version 0.5.5, build 02c4254**
installed on a Mac using:  **DockerToolbox-1.9.1g.pkg**

Trying to stop a machine after it was created results in error:

❯❯❯ docker-machine ls

NAME       ACTIVE   DRIVER       STATE     URL                         SWARM   DOCKER   ERRORS
default    *        virtualbox   Running   tcp://192.168.99.100:2376           v1.9.1
registry   -        virtualbox   Running   tcp://192.168.99.102:2376           v1.9.1

❯❯❯ docker-machine stop registry
/usr/local/bin/VBoxManage showvminfo registry --machinereadable failed:
VBoxManage: error: The object is not ready
VBoxManage: error: Details: code E_ACCESSDENIED (0x80070005), component ConsoleWrap, interface IConsole, callee nsISupports
VBoxManage: error: Context: "COMGETTER(VRDEServerInfo)(vrdeServerInfo.asOutParam())" at line 2340 of file VBoxManageInfo.cpp

**Comment by dgageot** [comment]
Fixed with https://github.com/docker/machine/pull/2763
