### ISSUE TITLE
Error attempting heartbeat call to plugin server: connection is shut down

### ISSUE THREAD

**Issue by rkazak** [docker/machine#2773]
docker version:
Client:
Version: 1.9.1
API version: 1.21
Go version: go1.4.3
Git commit: a34a1d5
Built: Fri Nov 20 17:56:04 UTC 2015
OS/Arch: darwin/amd64
Cannot connect to the Docker daemon. Is the docker daemon running on this host?

docker info:
Cannot connect to the Docker daemon. Is the docker daemon running on this host?

uname -a:
Darwin kazak.local 15.2.0 Darwin Kernel Version 15.2.0: Fri Nov 13 19:56:56 PST 2015; root:xnu-3248.20.55~2/RELEASE_X86_64 x86_64

Provide additional environment details (AWS, VirtualBox, physical, etc.):
VirtualBox is my provider.

List the steps to reproduce the issue:
1. I had to reinstall everything, VBox, DockerToolBox after I had upgraded from 1.8 to 1.9 and this did not work.
2. When I finally got my default machine going I ssh'ed into it from two sessions
3. I left my terms running and now see the following message repeatedly.

'Error attempting heartbeat call to plugin server: connection is shut down'

I disconnected the ssh session from one term and reconnected and the message has stopped.
The other is still reporting the error.

Describe the results you received:
The above error message reported repeatedly.

Describe the results you expected:
No error messages.

Provide additional info you think is important:
This may need to be a seperate report, however, I just now also created a second machine 'dev'
and this worked partially I get the following;

docker-machine create -d virtualbox dev
Running pre-create checks...
Creating machine...
(dev) Copying /Users/rkazak/.docker/machine/cache/boot2docker.iso to /Users/rkazak/.docker/machine/machines/dev/boot2docker.iso...
(dev) Creating VirtualBox VM...
(dev) Creating SSH key...
(dev) Starting VM...
Waiting for machine to be running, this may take a few minutes...
Machine is running, waiting for SSH to be available...
Detecting operating system of created instance...
Detecting the provisioner...
Provisioning with boot2docker...
Copying certs to the local machine directory...
Copying certs to the remote machine...
Setting Docker configuration on the remote daemon...

This machine has been allocated an IP address, but Docker Machine could not
reach it successfully.

SSH for the machine should still work, but connecting to exposed ports, such as
the Docker daemon port (usually :2376), may not work properly.

You may need to add the route manually, or use another related workaround.

This could be due to a VPN, proxy, or host file configuration issue.

You also might want to clear any VirtualBox host only interfaces you are not using.
Checking connection to Docker...

Error creating machine: Error checking the host: Error checking and/or regenerating the certs: There was an error validating certificates for host "192.168.99.101:2376": dial tcp 192.168.99.101:2376: i/o timeout

You can attempt to regenerate them using 'docker-machine regenerate-certs [name]'.
Be advised that this will trigger a Docker daemon restart which will stop running containers.

Also docker-machine ls shows;
NAME ACTIVE DRIVER STATE URL SWARM DOCKER ERRORS
default - virtual box Timeout
dev - virtual box Timeout

**Comment by rkazak** [comment]
From 'within' the machine I see
docker@default:~$ w
04:51:13 up 12:20, 3 users, load average: 0.00, 0.01, 0.05
USER TTY LOGIN@ IDLE JCPU PCPU WHAT
root tty1 Tue10 18:47m 0.00s 0.00s -sh
docker pts/0 Tue10 11:02 0.00s 0.00s -sh
docker pts/1 04:38 0.00s 0.00s 0.00s w
docker@default:~$ 
docker@default:~$ docker info
Containers: 0
Images: 0
Server Version: 1.9.1
Storage Driver: aufs
Root Dir: /mnt/sda1/var/lib/docker/aufs
Backing Filesystem: extfs
Dirs: 0
Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.1.13-boot2docker
Operating System: Boot2Docker 1.9.1 (TCL 6.4.1); master : cef800b - Fri Nov 20 19:33:59 UTC 2015
CPUs: 1
Total Memory: 1.956 GiB
Name: default
ID: DQCO:BX2H:JAJH:EOQM:TVJM:4CUH:LKMJ:INF3:5T2N:RWFE:MEMB:KKRK
Debug mode (server): true
File Descriptors: 12
Goroutines: 18
System Time: 2016-01-06T05:16:59.555061439Z
EventsListeners: 0
Init SHA1: 
Init Path: /usr/local/bin/docker
Docker Root Dir: /mnt/sda1/var/lib/docker
Labels:
provider=virtualbox

**Comment by rkazak** [comment]
A couple more things I see;
I had VirtualBox 5.0.12  installed ( via kitematic ) but the guest addition baked into boot2Docker is 5.0.10?
When I start my docker-machine in the I am sure there is a core dump / segv but I don't see that in the vbox.log - however I do see;

08:06:33.682510 VMMDev: Guest Log: VBoxService 5.0.10 r104061 (verbosity: 0) linux.amd64 (Nov 10 2015 17:56:08) release log
08:06:33.682522 VMMDev: Guest Log: 00:00:00.000047 main     Log opened 2016-01-06T16:35:10.437287000Z
08:06:33.683583 VMMDev: Guest Log: 00:00:00.001133 main     OS Product: Linux
08:06:33.683602 VMMDev: Guest Log: 00:00:00.001153 main     OS Release: 4.1.13-boot2docker
08:06:33.683615 VMMDev: Guest Log: 00:00:00.001168 main     OS Version: #1 SMP Fri Nov 20 19:05:50 UTC 2015
08:06:33.683629 VMMDev: Guest Log: 00:00:00.001181 main     Executable: /sbin/VBoxService
08:06:33.683632 VMMDev: Guest Log: 00:00:00.001181 main     Process ID: 830
08:06:33.683633 VMMDev: Guest Log: 00:00:00.001182 main     Package type: LINUX_64BITS_GENERIC
08:06:33.686964 VMMDev: Guest Log: 00:00:00.004513 main     5.0.10 r104061 started. Verbose level = 0
08:06:33.690773 VMMDev: Guest Log: 00:00:00.008309 vminfo   rtldrNativeLoad: dlopen('libdbus-1.so.3', RTLD_NOW | RTLD_LOCAL) failed: libdbus-1.so.3: cannot open shared object file: No such file or directory
08:06:33.690848 VMMDev: Guest Log: 00:00:00.008381 vminfo   Error: Unable to connect to system D-Bus (1/3): D-Bus not installed
08:06:34.199116 NAT: DHCP offered IP address 10.0.2.15
08:06:34.199276 NAT: DHCP offered IP address 10.0.2.15
08:06:38.691646 VMMDev: Guest Log: 00:00:05.009177 vminfo   Error: Unable to connect to system D-Bus (2/3): D-Bus not installed
08:06:43.693794 VMMDev: Guest Log: 00:00:10.011323 vminfo   Error: Unable to connect to system D-Bus (3/3): D-Bus not installed
08:16:54.350007 Display::handleDisplayResize: uScreenId=0 pvVRAM=0000000000000000 w=720 h=400 bpp=0 cbLine=0x0 flags=0x1
08:16:54.380114 VMMDev: SetVideoModeHint: Got a video mode hint (800x600x0)@(0x0),(1;0) at 0

Is it work trying to build a Boot2Docker.iso with the correct/matching guest addition?

**Comment by jeremymills** [comment]
Been receiving the same thing recently, I didn't see this issue here but posted in [StackOverFlow](http://stackoverflow.com/questions/34679916/docker-machine-error-attempting-heartbeat-call-to-plugin-server-connection-is) a day after you, will update if I get anything

**Comment by rkazak** [comment]
Hi, I believe that this will also shed some more light on the [issue.](https://github.com/boot2docker/boot2docker/issues/628) I found this after reading something else which help my google search. ( docker-machine cisco network vpn ).

**Comment by gnanasundar** [comment]
Hi, I'm also facing the same issue. It doesn't happen when I start the "default" machine using docker quickstart. I'm seeing this when I created my own machine "dev", started it and then did a ssh into it.
```
docker-machine create --driver virtualbox --virtualbox-memory 2048 --virtualbox-disk-size 204800 --virtualbox-hostonly-cidr "10.0.0.1/24" --engine-insecure-registry localreg:5000 dev
```

**Comment by alanwill** [comment]
FWIW, I was getting this error all of a sudden, but it didn't go away until I restarted the virtualbox instance
`docker-machine restart default`

Note: My default is not the OOB default but one that I manually created and called default so I expect this may work for others with any named vm

**Comment by MaerF0x0** [comment]
I got this when i am connected to an AWS instance and my wifi hiccups.  The ssh stays alive but the complaints come roughly every 5 seconds.

**Comment by vsDizzy** [comment]
Have Windows 10 + Hyper-V enabled and Virtual Switch to Wi-Fi
Installed Docker Toolbox.

```
C:\Windows\system32>docker-machine create --driver hyperv vm
Running pre-create checks...
Error attempting heartbeat call to plugin server: connection is shut down
Error with pre-create check: "read tcp 127.0.0.1:51413->127.0.0.1:51412: wsarecv: An existing connection was forcibly closed by the remote host."
Error attempting heartbeat call to plugin server: connection is shut down
```

**Comment by ssteinerx** [comment]
I am having this on the latest Docker installed May 8, 2016.

Error attempting heartbeat call to plugin server: unexpected EOF
Followed by:
Error attempting heartbeat call to plugin server: connection is shut down
every five seconds.

**Comment by rogaha** [comment]
Same issue here:

<pre>
docker@node1:~$ docker version
Client:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Wed Apr 27 00:34:20 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Wed Apr 27 00:34:20 2016
 OS/Arch:      linux/amd64

docker@node1:~$ Error attempting heartbeat call to plugin server: connection is shut down
                                                                                         Error attempting heartbeat call to plugin server: connection is shut down
                                                                                                                                                                  Error attempting heartbeat call to plugin server: connection is shut down
                                                      Error attempting heartbeat call to plugin server: connection is shut down
</pre>

**Comment by nathanleclaire** [comment]
Probably should just make the program exit after getting heartbeat errors some set number of times, e.g. after 3 retries.

**Comment by lucj** [comment]
Just create a swarm cluster using docker-machine + swarmkit on my laptop.
When the laptop wakes up from the sleep, I got the same error on the 4 nodes.

**Comment by venkatesh03** [comment]
(swarm-agent-00) Creating VirtualBox VM...
(swarm-agent-00) Creating SSH key...
(swarm-agent-00) Starting the VM...
(swarm-agent-00) Check network to re-create if needed...
(swarm-agent-00) Waiting for an IP...
Error attempting heartbeat call to plugin server: unexpected EOF
Error attempting heartbeat call to plugin server: unexpected EOF
Error creating machine: Error in driver during machine creation: unexpected EOF
Error attempting heartbeat call to plugin server: connection is shut down
Error attempting heartbeat call to plugin server: connection is shut down
Error attempting heartbeat call to plugin server: connection is shut down
Error attempting heartbeat call to plugin server: connection is shut down


i am facing the same issue in ubuntu 14.04
