### ISSUE TITLE
documentation for ports open under docker-machine aws security-group?

### ISSUE THREAD

**Issue by cboettig** [docker/machine#2776]
Hi,

I see that `docker-machine create --driver amazonec2` creates a machine with security group `docker-machine` by default (if no value is given in env var or arguments to `docker-machine`).  What ports does this open inbound by default?  Just SSH and Docker?  Or is it just a default security group (with no inbound ports open) until the user edits it in their web console?

Can these by customized by `docker-machine` command or must the security group first be created and configured in the EC2 web console?  If not, are there plans to do so in the future?  (Looking to simplify the workflow as much as possible when teaching to new users)

p.s. Love the new command-line documentation where `-h` options are specific to `--driver` instead of flooding the screen with all possible drivers!

**Comment by jeanlaurent** [comment]
The `amazonec2` driver is opening the ssh, docker and swarm port on the default security group (docker-machine) which it creates or on the security group you pass to the CLI with the `--amazonec2-security-group` flag.

You can look at the [security group configuration code](https://github.com/docker/machine/blob/master/drivers/amazonec2/amazonec2.go#L853-L900) and the [security group creation code](https://github.com/docker/machine/blob/master/drivers/amazonec2/amazonec2.go#L785-L851).

You can't specify more ports to be openned by docker-machine. What we suggest is that you create a security group beforehand and attach your host to it with the  `--amazonec2-security-group`.
The `gcloud` and `digitalfusion` share the same behaviour.

**Comment by jeanlaurent** [comment]
Added the missing doc in #2784

**Comment by cboettig** [comment]
Thanks for the links, and the new docs looks great to me.  Feel free to close this when you're ready / merged or whatnot.
