### ISSUE TITLE
Issue with docker-machine with rackspace driver

### ISSUE THREAD

**Issue by stushurik** [docker/machine#2781]
Recenlty, I have found these docs: 
https://docs.docker.com/machine/drivers/rackspace/ 
https://developer.rackspace.com/blog/using-docker-machine-to-deploy-your-docker-containers-on-rackspace/

I followed all steps from that instruction and get the next error:

olexandr@E5-551G:~/vboxes/autumn-docker-compose-files$ docker-machine create --driver rackspace test-host 
Running pre-create checks... 
Creating machine... 
Error creating machine: Error in driver during machine creation: Unable to find tenant named

Also if I list all machines:

olexandr@E5-551G:~/vboxes/autumn-docker-compose-files$ docker-machine ls 
NAME ACTIVE DRIVER STATE URL SWARM DOCKER ERRORS 
test-host - rackspace Error Unknown Expected HTTP response code [200 203] when accessing [GET https://lon.servers.api.rackspacecloud.com/v2/10045552/servers/], but got 404 instead

**UPD**. I use docker-machine v. 0.5.5

**Comment by stushurik** [comment]
According to this (https://github.com/docker/machine/issues/2314) issue`s solution, I have downgrade docker-machine to 0.5.1 and it works

**Comment by nathanleclaire** [comment]
I think it should be fixed with 0.7.0
