### ISSUE TITLE
Creating default machine on virtualbox takes a LONG time!!! ~50 min

### ISSUE THREAD

**Issue by IanEdington** [docker/machine#2788]
I am trying to create the default-machine in the quickstart start.sh file. I've tracked it to this line, but it hangs at `Creating SSH key...`. I have uninstalled everything and reinstalled the toolbox, and searched everywhere I can think of for a solution. If this isn't the appropriate place to ask about this feel free to tell me ;).

edit: I'm on Mac OSX 10.11.2

```
❯ docker-machine create -d virtualbox --virtualbox-memory 2048 --virtualbox-disk-size 204800 default
Running pre-create checks...
Creating machine...
(default) Copying /Users/ian/.docker/machine/cache/boot2docker.iso to /Users/ian/.docker/machine/machines/default/boot2docker.iso...
(default) Creating VirtualBox VM...
(default) Creating SSH key...
^C%
>>> elapsed time 3m18s
```
Does the same with `docker-machine create -d virtualbox test`

with --debug
Does the same with `docker-machine --debug create -d virtualbox test`
```
❯ docker-machine --debug create -d virtualbox --virtualbox-memory 2048 --virtualbox-disk-size 204800 default       [10:39:11]
Docker Machine Version:  0.5.5, build
Found binary path at /usr/local/bin/docker-machine
Launching plugin server for driver virtualbox
Plugin server listening at address 127.0.0.1:59530
() Calling .GetVersion
Using API Version  1
() Calling .SetConfigRaw
() Calling .GetMachineName
(flag-lookup) Calling .GetCreateFlags
Found binary path at /usr/local/bin/docker-machine
Launching plugin server for driver virtualbox
Plugin server listening at address 127.0.0.1:59534
() Calling .GetVersion
Using API Version  1
() Calling .SetConfigRaw
() Calling .GetMachineName
(default) Calling .GetMachineName
(default) Calling .DriverName
(default) Calling .GetCreateFlags
(default) Calling .SetConfigFromFlags
Running pre-create checks...
(default) Calling .PreCreateCheck
(default) DBG | COMMAND: /usr/local/bin/VBoxManage --version
(default) DBG | STDOUT:
(default) DBG | {
(default) DBG | 5.0.12r104815
(default) DBG | }
(default) DBG | STDERR:
(default) DBG | {
(default) DBG | }
(default) DBG | local Boot2Docker ISO version:  v1.9.1
(default) DBG | COMMAND: /usr/local/bin/VBoxManage list hostonlyifs
(default) DBG | STDOUT:
(default) DBG | {
(default) DBG | Name:            vboxnet0
(default) DBG | GUID:            786f6276-656e-4074-8000-0a0027000000
(default) DBG | DHCP:            Disabled
(default) DBG | IPAddress:       192.168.99.1
(default) DBG | NetworkMask:     255.255.255.0
(default) DBG | IPV6Address:
(default) DBG | IPV6NetworkMaskPrefixLength: 0
(default) DBG | HardwareAddress: 0a:00:27:00:00:00
(default) DBG | MediumType:      Ethernet
(default) DBG | Status:          Down
(default) DBG | VBoxNetworkName: HostInterfaceNetworking-vboxnet0
(default) DBG |
(default) DBG | Name:            vboxnet1
(default) DBG | GUID:            786f6276-656e-4174-8000-0a0027000001
(default) DBG | DHCP:            Disabled
(default) DBG | IPAddress:       192.168.50.1
(default) DBG | NetworkMask:     255.255.255.0
(default) DBG | IPV6Address:
(default) DBG | IPV6NetworkMaskPrefixLength: 0
(default) DBG | HardwareAddress: 0a:00:27:00:00:01
(default) DBG | MediumType:      Ethernet
(default) DBG | Status:          Down
(default) DBG | VBoxNetworkName: HostInterfaceNetworking-vboxnet1
(default) DBG |
(default) DBG | }
(default) DBG | STDERR:
(default) DBG | {
(default) DBG | }
(default) Calling .GetConfigRaw
Creating machine...
(default) Calling .Create
(default) DBG | local Boot2Docker ISO version:  v1.9.1
(default) Copying /Users/ian/.docker/machine/cache/boot2docker.iso to /Users/ian/.docker/machine/machines/default/boot2docker.iso...
(default) Creating VirtualBox VM...
(default) Creating SSH key...
(default) DBG | Creating disk image...
(default) DBG | Creating 204800 MB hard disk image...
(default) DBG | Writing magic tar header
(default) DBG | Writing SSH key tar header
(default) DBG | Calling inner createDiskImage
(default) DBG | &{/usr/local/bin/VBoxManage [/usr/local/bin/VBoxManage convertfromraw stdin /Users/ian/.docker/machine/machines/default/disk.vmdk 214748364800 --format VMDK] []  <nil> <nil> <nil> [] <nil> <nil> <nil> <nil> false [] [] [] [] <nil>}
(default) DBG | Starting command
(default) DBG | Copying to stdin
(default) DBG | Converting from raw image file="stdin" to file="/Users/ian/.docker/machine/machines/default/disk.vmdk"...
(default) DBG | Creating dynamic image with size 214748364800 bytes (204800MB)...
(default) DBG | Filling zeroes
^C%
>>> elapsed time 10m46s
```

**Comment by hcguersoy** [comment]
Hi Ian,

I observe the same, but it continues after several minutes.
During this time, `VBoxManage` occupies one of the CPU cores up to 99%.
Overall, the creation of a simple machine lasts about 5 minutes.

I'm running it on a MacBook Pro 13'' with a SSD, VirtualBox 5.0.10 r104061, Docker Machine 0.5.6.
I didn't observed this with Machine 0.5.0.

**Comment by IanEdington** [comment]
Ran it again. It took 50min 19sec. I'm pretty sure when I did this with an older version of docker it did not take this much time to initialize.

MacBook Pro (Retina, 13-inch, Late 2013)
Processor 2.4 GHz Intel Core i5
Ram 8 GB 1600 MHz DDR3
With SSD

**Comment by hcguersoy** [comment]
OK, I've some new informations and I would say the problem is VirtualBox not Docker Machine.

Initially, everything has worked fine after an restart of my MacBook (normally I don't do that but for flights I shut it down).
After that, everything was fine and machines / VMs got created in several seconds. But some days later I've again the same problem.
So I searched for all VirtualBox related processes in the Activity Monitor (all starting with 'VBox') and shut them down. After that, the problems are gone ... for some days. So I've repeated that and everything was fine again.

Hint: you should suspend or stop all machines/VMs before you kill the VirtualBox processes.

**Comment by nathanleclaire** [comment]
VBox issue

**Comment by adoyle** [comment]
I'm getting similar problems. I notice that the setting for the disk size is 200+ GB.  I noticed there was discussion about this in https://github.com/docker/machine/pull/2069 where it was bumped from 20GB. 

The size is not so much an issue as is the fact that the create routine fills the new disk with zeroes. This is what's taking the time at nearly 100% CPU.  I think this is happening at https://github.com/docker/machine/blob/master/drivers/virtualbox/disk.go#L80

**Comment by adoyle** [comment]
Oddly enough, it takes less time to build a 200GB default machine on my MacBook Air than it does to create a 20GB one on my Mac mini. Both have SSDs and the Air has 1/2 the RAM.
