### ISSUE TITLE
alternative notes for windows install w/ powershell

### ISSUE THREAD

**Issue by factormystic** [docker/machine#2791]
Currently the release notes only suggest git bash, but there's an even simpler option to get a release with powershell: use Invoke-WebRequest, which is aliased as `iwr` by default. Plus the `bin` dir creation gives us:

```
md -f $home\bin; iwr -outfile $home\bin\docker-machine.exe https://github.com/docker/machine/releases/download/v0.5.5/docker-machine_windows-amd64.exe
```

**Comment by nathanleclaire** [comment]
Even though we provide some limited support for Powershell etc., our recommended path is to use git bash (preferably through the Quickstart/Toolbox)

**Comment by factormystic** [comment]
Well, I doubt people using toolbox are following github release notes for updates (or, is something scraping github releases and the notes being posted elsewhere?). Also weird that powershell would be supported but not actually used, when it is the preferable shell on windows. Obviously the OS X/Linux directions don't need to change.
