### ISSUE TITLE
stdout from driver

### ISSUE THREAD

**Issue by jeffellin** [docker/machine#2794]
the ec2 driver now uses the amazon ec2 go library.  As a side affect to this I am no longer able to monitor the aws calls in debug mode.  I am assuming that this is due to the new driver model not displaying stdout. Is my assumption correct?  Is there any way around this.  I see the ec2 library allows the implementation of a custom logger,  is using the libmachine/log with a customer logger my only option?

**Comment by nathanleclaire** [comment]
The driver system should display anything that the plugins logs to STDOUT by default, and include anything printed to STDERR if `--debug` is set.  Perhaps adding a custom logger would be a good thing to do in our usage of the Go AWS package.

**Comment by jeffellin** [comment]
I am not seeing anything from the basic aws go logger,  I will try and spin
up a standalone test outside of docker to see if I am even setting the
flags right.

**Comment by jeffellin** [comment]
@nathanleclaire I am assuming there is nothing right now to alert the driver to the fact that debug is enabled?  Java you can usually do something like logger.isDebugEnabled but I don't see anything like that in the go logger.  I suppose I can expose the state via the docker logger.  I see you have a setDebug but not a getDebug.

**Comment by nathanleclaire** [comment]
@jeffellin, the drivers should display STDOUT just fine, and have `log.IsDebug` set to true automatically (https://github.com/docker/machine/blob/master/libmachine/drivers/plugin/register_driver.go#L32).

Most likely the debugging output you are looking for was in https://github.com/docker/machine/blob/v0.5.4/drivers/amazonec2/amz/ec2.go#L154, which was removed when we moved to the new lib.

**Comment by jeffellin** [comment]
@nathanleclaire Why are you setting debug explicitly on drivers, shouldn't it follow the --debug?

What I am looking to do is programmatically set the aws debug when setting up the client.

svc := ec2.New(sess,aws.NewConfig().WithLogLevel(aws.LogDebugWithHTTPBody))

**Comment by nathanleclaire** [comment]
@jeffellin You could just check `log.IsDebug`.

> Why are you setting debug explicitly on drivers, shouldn't it follow the --debug?

Maybe, but the way it currently works today is that we ask the driver to dump all output (debug output always goes to STDERR) and then we do the display filtering at the client level.

**Comment by jeffellin** [comment]
So you are making an assumption that debug is always stderr,   I can't guarantee that a third party library would use stderr if I want to enable debug mode on it.

**Comment by nathanleclaire** [comment]
> So you are making an assumption that debug is always stderr, I can't guarantee that a third party library would use stderr if I want to enable debug mode on it.

I'm not 100% sure what you mean -- yes, we assume output intended to be only shown when `--debug` is used to be the same as output which the driver sends to STDERR, and output sent to STDOUT "leaks" to the client binary exec by default.

It's true that one cannot guarantee 3rd party libraries will log debug output to STDERR, but sending debug output to STDERR is a very common convention.  `ssh`, for instance, sends the additional information it prints when invoked with `-vvv` to STDERR.

**Comment by jeffellin** [comment]
@nathanleclaire Looking at the aws code a bit more.  Then use a logging abstraction, unfortunately they only have one method log()  when debug is enabled via 
```
 svc := ec2.New(sess,aws.NewConfig().WithLogLevel(aws.LogDebugWithHTTPBody))
```

So even if I implement my own logger I can only log stderr or stdout.

It will check in the code and then continue to dump the message to the same log method. In other words it will simply send more data to the logger if log is enabled, rather than use the more conventional log.debug or log.info.  Even if I had a way to determine if debug mode was on for machine I wouldn't be able to tell what was an informational vs a debug message.  

https://github.com/aws/aws-sdk-go/blob/master/aws/client/client.go  (line 76)

BTW,  this has come about because I have noticed an issue that when you have more than one security group called docker-machine aws can return the wrong one leading to some strange errors.  The only way to figure out what was going on was to get the request/response logging and determine that I need to supply the vpc-id as driver does not determine the correct vpc from the subnet-id. (it probably should but thats a discussion for another day)

**Comment by nathanleclaire** [comment]
My first approach (there might be a better one) would just be to set the log level as high as we can and direct the output to STDERR (so it's only shown with `--debug`), then pepper the driver code with `log.Info` calls for what we want to send to STDOUT without `--debug`.  Most drivers aren't very chatty without `--debug` so I don't feel like we'd lose much.

> BTW, this has come about because I have noticed an issue that when you have more than one security group called docker-machine aws can return the wrong one leading to some strange errors. The only way to figure out what was going on was to get the request/response logging and determine that I need to supply the vpc-id as driver does not determine the correct vpc from the subnet-id. (it probably should but thats a discussion for another day)

Can you please file an issue for that specifically?

Thanks!

**Comment by jeffellin** [comment]
I guess my hangup is that I can’t determine if machine is in debug mode to
generate extra information, since the logger is always set to debug for the
driver.

**Comment by jeffellin** [comment]
@nathanleclaire you are probably right,   I can direct all aws messages to stderr,  I think by default it logs nothing anyway.

**Comment by jeffellin** [comment]
@nathanleclaire  Thoughts on this as a possible solution?

https://github.com/jeffellin/machine/commit/b2b8bf794c7187358a7b6a974e28ca63466f3214

Basically its a implementation of the aws logger interface that prints all messages to stderr.  The driver out of the box prints very little to stdout unless debug is turned on so we won't really be losing anything by dropping it down to debug level.

**Comment by nathanleclaire** [comment]
@jeffellin Seems like a good solution to me.

**Comment by jeffellin** [comment]
thanks I need to clean up the commit a bit then I will do a PR.
