### ISSUE TITLE
docker-machine installs broken systemd unit file during provisioning

### ISSUE THREAD

**Issue by DanielDent** [docker/machine#2795]
I ran into an issue (see weaveworks/weave/issues/1607) where a machine which docker-machine had provisioned using the generic provider was not booting properly.

It looks like docker-machine installs a systemd unit file in /etc/systemd/system. This file uses deprecated docker startup parameters, and also does not properly specify dependencies. The systemd unit file installed in /lib does properly specify dependencies.

This causes a machine which has had docker-machine's magic done to it to no longer resolve systemd dependencies correctly, causing software such as weave to not work.

**Comment by nathanleclaire** [comment]
Hi @DanielDent, thanks for the report.  Will you please post OS (of the provisioned system), the contents of the failing systemd unit file, and the contents of the proper one>

**Comment by DanielDent** [comment]
Debian Jessie:
Failing systemd unit file (was located in /etc/systemd/system):

    [Service]
    ExecStart=/usr/bin/docker -d -H tcp://0.0.0.0:2376 -H unix:///var/run/docker.sock --storage-driver aufs --tlsverify --tlscacert /etc/docker/ca.pem --tlscert /etc/docker/server.pem --tlskey /etc/docker/server-key.pem --label provider=generic 
    MountFlags=slave
    LimitNOFILE=1048576
    LimitNPROC=1048576
    LimitCORE=infinity
    Environment=
    
    [Install]
    WantedBy=multi-user.target

Working systemd file:

    [Unit]
    Description=Docker Application Container Engine
    Documentation=https://docs.docker.com
    After=network.target docker.socket
    Requires=docker.socket
    
    [Service]
    Type=notify
    ExecStart=/usr/bin/docker daemon -H fd://
    MountFlags=slave
    LimitNOFILE=1048576
    LimitNPROC=1048576
    LimitCORE=infinity
    
    [Install]
    WantedBy=multi-user.target

**Comment by nathanleclaire** [comment]
Thanks, will take note and work on fixing.

**Comment by nathanleclaire** [comment]
Looks like on my fresh install of 1.10.1 on Debian Jessie the default service file gets dropped into `/lib/systemd/system/docker.service`.  I'm not sure what location the latest versions of Ubuntu use but we should probably follow upstream Docker's lead and modify our default location.

**Comment by DanielDent** [comment]
See https://www.freedesktop.org/wiki/Software/systemd/FrequentlyAskedQuestions/

The TL;DR: /etc is intended for unit files which have been locally modified, and take precedence over files in /lib. Files included in a package should typically go in /lib. In this case, where docker-machine is reaching out and provisioning a system, if it's modifying unit files /etc is probably the right place to put them.

**Comment by nathanleclaire** [comment]
Ah, good call -- thanks for pointing that out @DanielDent

**Comment by hdost** [comment]
This happens with docker-machine regenerate-certs with the generic driver also

**Comment by nathanleclaire** [comment]
@hdost Can you be more specific?  Machine version, expected vs. desired behavior etc.  I think with 0.6.0 it should at least use `daemon` correctly although a few of the desired `After=` type parameters are missing.

**Comment by hdost** [comment]
@nathanleclaire updated

**Comment by nathanleclaire** [comment]
Thanks -- it shouldn't create service file with `-d`, maybe it's a bug.

**Comment by sergef** [comment]
`Requires=docker.socket` option is breaking docker daemon startup since version 1.12

**Comment by djleeam** [comment]
Hi, when I remove "Requires=docker.socket" from /etc/systemd/system/docker.service leaving...

```
[Unit]
Description=Docker Application Container Engine
After=network.target docker.socket

[Service]
ExecStart=/usr/bin/docker daemon -H tcp://0.0.0.0:2376 -H unix:///var/run/docker.sock --storage-driver devicemapper --tlsverify --tlscacert /etc/docker/ca.pem --tlscert /etc/docker/server.pem --tlskey /etc/docker/server-key.pem --label provider=generic
MountFlags=slave
LimitNOFILE=1048576
LimitNPROC=1048576
LimitCORE=infinity
Environment=
```
the docker service (v1.12.0) starts up fine again. But as soon as I run docker-machine (v0.8.0) regenerate-certs or create against this Centos 7 host, "Requires=docker.socket" gets added back to docker.service and the service no longer start properly...

```
Using SSH client type: external
&{[-F /dev/null -o PasswordAuthentication=no -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=quiet -o ConnectionAttempts=3 -o ConnectTimeout=10 -o ControlMaster=no -o ControlPath=none me@dev -p 22] /usr/bin/ssh <nil>}
About to run SSH command:
printf %s "[Unit]
Description=Docker Application Container Engine
After=network.target docker.socket
Requires=docker.socket

[Service]
ExecStart=/usr/bin/docker daemon -H tcp://0.0.0.0:2376 -H unix:///var/run/docker.sock --storage-driver devicemapper --tlsverify --tlscacert /etc/docker/ca.pem --tlscert /etc/docker/server.pem --tlskey /etc/docker/server-key.pem --label provider=generic 
MountFlags=slave
LimitNOFILE=1048576
LimitNPROC=1048576
LimitCORE=infinity
Environment=
" | sudo tee /etc/systemd/system/docker.service
SSH cmd err, output: <nil>: [Unit]
Description=Docker Application Container Engine
After=network.target docker.socket
Requires=docker.socket

[Service]
ExecStart=/usr/bin/docker daemon -H tcp://0.0.0.0:2376 -H unix:///var/run/docker.sock --storage-driver devicemapper --tlsverify --tlscacert /etc/docker/ca.pem --tlscert /etc/docker/server.pem --tlskey /etc/docker/server-key.pem --label provider=generic 
MountFlags=slave
LimitNOFILE=1048576
LimitNPROC=1048576
LimitCORE=infinity
Environment=
```

**Comment by nathanleclaire** [comment]
Made a change to move the file closer to the upstream including this fix, testing it now.

**Comment by djleeam** [comment]
awesome, thanks!

**Comment by nathanleclaire** [comment]
https://github.com/docker/machine/pull/3624 seems to work fine for me
