### ISSUE TITLE
Error validating certificates rackspace driver

### ISSUE THREAD

**Issue by andyau** [docker/machine#2798]
We are currently running in to this issue time we try and deploy a new docker instance

olexandr@E5-551G:~/vboxes/autumn-docker-compose-files$ docker-machine env dev-autumnapp
Error running connection boilerplate: Error checking and/or regenerating the certs: There was an error validating certificates for host "162.13.190.166:2376": dial tcp 162.13.190.166:2376: i/o timeout
You can attempt to regenerate them using 'docker-machine regenerate-certs name'.
Be advised that this will trigger a Docker daemon restart which will stop running containers.

**Comment by snelis** [comment]
Same on digitalocean:

`docker-machine env snelis`
```
Error checking TLS connection: Error checking and/or regenerating the certs: There was an error validating certificates for host "XXX.XXX.XXX.XXX:2376": tls: DialWithDialer timed out
You can attempt to regenerate them using 'docker-machine regenerate-certs [name]'.
Be advised that this will trigger a Docker daemon restart which will stop running containers.
```

`docker-machine regenerate-certs snelis`
```
Regenerate TLS machine certs?  Warning: this is irreversible. (y/n): y
Regenerating TLS certificates
Detecting the provisioner...
Installing Docker...
Copying certs to the local machine directory...
Copying certs to the remote machine...
Setting Docker configuration on the remote daemon...
```

`docker-machine env snelis`
```
Error checking TLS connection: Error checking and/or regenerating the certs: There was an error validating certificates for host "XXX.XXX.XXX.XXX:2376": tls: DialWithDialer timed out
You can attempt to regenerate them using 'docker-machine regenerate-certs [name]'.
Be advised that this will trigger a Docker daemon restart which will stop running containers.
```

**Comment by smashwilson** [comment]
While I was trying to repro this I hit #2781. Looks like the Rackspace driver needs a little attention in general. I have some bandwidth today, so I'll see what I can do :smile:

**Comment by jrperritt** [comment]
Possibly related issues and some fixes for them:
https://github.com/docker/toolbox/issues/275
https://github.com/docker/machine/issues/2320

**Comment by smashwilson** [comment]
I've been investigating this and I can't reproduce it myself, even using a 0.5.1 binary.

Can you `docker-machine ssh` in to your hosts? If so, can you verify that the docker daemon is running and correctly bound to port 2376? Failing that, I'd verify that there's nothing odd going on with your networking; port blocking from a VPN, for example.

It is strange to me that it doesn't fail during provisioning rather than connection. Looking through the source, though, it looks like (during `create`) machine doesn't wait for connectivity on the Docker port, just SSH, so it would be possible for `create` to succeed and `env` to fail if 2376 is inaccessible.

**Comment by andyau** [comment]
docker-machine -D env dev-autumnapp out is:

olexandr@E5-551G:~/vboxes/autumn-docker-compose-files$ docker-machine -D env dev-autumnapp
Docker Machine Version: 0.5.1 (7e8e38e)
Found binary path at /usr/local/bin/docker-machine-driver-rackspace
Launching plugin server for driver rackspace
Plugin server listening at address 127.0.0.1:59892
() Calling RPCServerDriver.GetVersion
Using API Version 1
() Calling RPCServerDriver.SetConfigRaw
() Calling RPCServerDriver.GetMachineName
(dev-autumnapp) Calling RPCServerDriver.GetState
(dev-autumnapp) DBG | Get status for OpenStack instance...		 MachineId=520d7509-4441-467a-9843-c0aac4f76ffa
(dev-autumnapp) DBG | Authenticating to Rackspace.		 Username=Olexandr.Poplavskyi
(dev-autumnapp) DBG | State for OpenStack instance		 MachineId=520d7509-4441-467a-9843-c0aac4f76ffa State=ACTIVE
(dev-autumnapp) Calling RPCServerDriver.GetURL
Reading CA certificate from /home/olexandr/.docker/machine/certs/ca.pem
Reading server certificate from /home/olexandr/.docker/machine/machines/dev-autumnapp/server.pem
Reading server key from /home/olexandr/.docker/machine/machines/dev-autumnapp/server-key.pem
Error running connection boilerplate: Error checking and/or regenerating the certs: There was an error validating certificates for host "162.13.190.166:2376": dial tcp 162.13.190.166:2376: i/o timeout
You can attempt to regenerate them using 'docker-machine regenerate-certs name'.
Be advised that this will trigger a Docker daemon restart which will stop running containers.

**Comment by andyau** [comment]
Port 2376 verification:

root@dev-autumnapp:~# netstat -tulpn | grep :2376
tcp6       0      0 :::2376                 :::*                    LISTEN      11066/docker    
root@dev-autumnapp:~# sudo service docker status 
docker start/running, process 11066
root@dev-autumnapp:~#

**Comment by smashwilson** [comment]
Alright, thanks. From the trace, we can see that it's failing [in this section,](https://github.com/docker/machine/blob/7e8e38e/libmachine/cert/cert.go#L236-L243) which (according to my tracing) is indeed the first time that docker-machine attempts to open a connection to the host on 2376. You've verified that the docker daemon is up and listening, so the problem must be in the connection between your host and the launched host.

I find it interesting that there's a hardcoded timeout of 2 seconds on that connection attempt. What region are you creating hosts in? Is it possible that your connection latency to that host exceeds two seconds?

Let's take Docker out of the picture and try to get a connection to the host manually. It's [difficult to connect to the Docker remote API with curl](https://github.com/docker/docker/issues/16107), at least if you're on a Mac, but wget seems to work okay. Give this a shot and see if it connects:

```bash
wget \
  --ca-certificate=/home/olexandr/.docker/machine/machines/dev-autumnapp/ca.pem \
  --certificate=/home/olexandr/.docker/machine/machines/dev-autumnapp/cert.pem \
  --private-key=/home/olexandr/.docker/machine/machines/dev-autumnapp/key.pem \
  https://162.13.190.166:2376/version -O -
```

(You might need to adjust the hostname and the machine name if you've been creating and destroying machines; I based this on the output from your `env -D` command.)

**Comment by andyau** [comment]
We tried that code and it didn't connect at all. The servers are in the London region.

**Comment by smashwilson** [comment]
Alright. Are you behind any kind of proxy, firewall, or VPN?

The host _shouldn't_ be blocking traffic, but it's worth a check. `docker-machine ssh` in and run `iptables -L -n -v` to see if there's anything weird going on there.

**Comment by stushurik** [comment]
We have disabled ufw on the host and it seems everything is working now. Thank you!

**Comment by smashwilson** [comment]
Huh! Well that shouldn't have happened. Did you enable it yourself, by any chance?

If not, it might be enabled by default on that image, now, which means that `docker-machine create` would need to turn it off (or, better, configure it to permit external connections to the Docker daemon and not interfere with Docker's networking shenanigans).

**Comment by stushurik** [comment]
No we didn`t enable it. Actually, we run only docker-machine create.

**Comment by smashwilson** [comment]
Okay, I suspected so. No explicit `--rackspace-image-id` argument either? It's odd to me that my machines don't seem to launch with ufw enabled but yours did.

I'll see if I can deal with that during provisioning somehow.

**Comment by stushurik** [comment]
We defined 3 env variables: 
$OS_API_KEY
$OS_REGION_NAME
$OS_USERNAME 

and launch docker-machine create

**Comment by snelis** [comment]
The same issue was the problem for me, but then on digitalocean.

```
Welcome to Ubuntu 15.10 (GNU/Linux 4.2.0-16-generic x86_64)

 * Documentation:  https://help.ubuntu.com/
Last login: Tue Jan 12 06:15:26 2016 from xxx
root@snelis:~# service ufw status
● ufw.service - Uncomplicated firewall
   Loaded: loaded (/lib/systemd/system/ufw.service; enabled; vendor preset: enabled)
   Active: active (exited) since Tue 2016-01-12 06:13:30 EST; 6h ago
 Main PID: 210 (code=exited, status=0/SUCCESS)
   CGroup: /system.slice/ufw.service

Warning: Journal has been rotated since unit was started. Log output is incomplete or unavailable.
```

disabling this fixed it

**Comment by snelis** [comment]
Good call on the proxy for my case it turns out a corp. proxy is causing the timeout here.
Tried the wget, but it will just hang on on `Connecting to x.x.x.x:2376... connected.`
If i try another proxy i get `Unable to establish SSL connection.`
When jumping outside of this network everything works perfect.

tnx for the time and effort

**Comment by nathanleclaire** [comment]
Seems to be a proxy issue... Please re-open if problems persist
