### ISSUE TITLE
Provisioner plugins?

### ISSUE THREAD

**Issue by StefanScherer** [docker/machine#2822]
Are there plans to allow provisioner plugins or at least to allow a driver plugin to bring its own provisioner with it?

Background is the discussion in https://github.com/hypriot/docker-machine-hypriot/issues/1 to fully implement the Hypriot driver plugin to connect eg. to a Raspberry Pi and provision Docker on ARM there.
The hard part seems to be adding the little different provision steps. I could send a PR to this repo, but I've seen eg. the photon provisioner which is needed for eg. the vmwareappcatalyst driver plugin. But adding more and more provisioners lead to the same situation as with the drivers some months ago, I think.

So what I was thinking off is the possibility to either 
1.) allow provisioner plugins (the user then needs probably two plugins, one for the driver, one for the provisioner) or
2.) allow a driver plugin to also register a provisioner that is needed only for this driver. (the user then only needs docker-machine + 1 binary with the driver plugin)

**Comment by kunalkushwaha** [comment]
+1 for need of additional/external provisioning support.

On different use case, I am working on machine to build docker host for production environment. Usually in production, docker host requires more then just docker and swarm. 
e.g. Volume managers like [Flocker](https://github.com/ClusterHQ/flocker) or [Openstorage](https://github.com/libopenstorage/openstorage)
- Creating OS image with such third party software's are not clean way to do it.

**Comment by benediktarnold** [comment]
+1 for pluggable provisioners
