### ISSUE TITLE
IPv6 & ssh "Too many colons"

### ISSUE THREAD

**Issue by blaggacao** [docker/machine#2824]
```
docker-machine --native-ssh ssh dev
dial tcp: too many colons in address fe80::215:5dff:fe5f:100:22
```
```
docker-machine version
docker-machine.exe version 0.5.6, build 61388e9
```

I've heard the IPv6 must be handeled in `[fe80::215:5dff:fe5f:100]:22` format

**Comment by blaggacao** [comment]
ref: #1616

**Comment by nathanleclaire** [comment]
Can you provide a few more details about how you've created the machine?  driver, etc.

It's been pretty implicit in `GetIP` so far that it means IPv4, although I'm not crazy about that.

**Comment by blaggacao** [comment]
Of course, I'm using the hyper-v driver on windows 10.

For some reasons I cannot make an external network switch working. I guess it's for incompatibilities of my router, without knowing if this is a reasonable suspect.

Therefore I work with the "internal" switch and network sharing, which is adviced at some place in the internet.

The so called "internal" switch however does not provide dhcp and seems to rely on the 169. address equivalent in ipv6 (fe80:).

I can work around by installing a dhcp server on the host and enabling it for the virtual interface.

However, this is a multiple error situation, people might encounter when working with hyper-v, so if docker machine would work, or even give a hint about that, this would get docker-machine out of the line.

**Comment by blaggacao** [comment]
I can't right now find the docker commit, that includes ipv6 support for the `docker -H` option. But it exists and will make it into 1.10...

**Comment by blaggacao** [comment]
I think this can be burried on behalf of mobylinux and docker windows support
