### ISSUE TITLE
Intermittent SSL key/certificate generation issues

### ISSUE THREAD

**Issue by dherben** [docker/machine#2837]
I've been encountering intermittent failures trying to set up a docker VM under VirtualBox on Mac OS X using Docker Toolbox 1.9.1 (tried 1.9.1h and every one before that). All seem to be related to ssh in one way or another, but the exact symptoms vary. I've encountered any of the following:

* docker-machine create hanging on 'Starting VM'
* docker-machine restart complaining that certificates need to be regenerated
* docker-machine restart failing after 60 tries to connect to ssh

Most of the time, when restart times out trying to connect via ssh, I see in the VM that the SSL certs/keys in /var/lib/boot2docker/ssh and /var/lib/boot2docker/tls are empty files:

* [failure-docker-machine-restart-certs.txt](https://github.com/docker/machine/files/89979/failure-docker-machine-restart-certs.txt)

I've attempted a remove-clean-create-restart cycle numerous times, and can't find a pattern in when it succeeds or fails. I _think_ it occurs more often when I run the restart immediately after running the create, and docker-machine restart also _seems_ to be worse than the combination of docker-machine stop; docker-machine start. I suspect a kind of race condition somewhere, but have no clue on how to solve.

This issue seems to be related to #986, #2175, and possibly #908, but I've tried a few of the workarounds there without success.

Things I've excluded:
* ::1 localhost is commented out in /etc/hosts
* no ControlMaster or the like in ssh
* vboxnet* interfaces are removed from VirtualBox before each attempt
* ~/.docker is cleared before each attempt
* virtualbox VM is removed before each attempt 

My environment:

$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.11.2
BuildVersion:	15C50
$ docker-machine --version
docker-machine version 0.5.5, build 02c4254
$ docker --version
Docker version 1.9.1, build a34a1d5
$ VBoxManage --version
5.0.12r104815

Log files of a successful create-restart cycle:
* [success-docker-machine-create.txt](https://github.com/docker/machine/files/89981/success-docker-machine-create.txt)
* [success-docker-machine-create-boot2docker.txt](https://github.com/docker/machine/files/89983/success-docker-machine-create-boot2docker.txt)
* [success-docker-machine-restart.txt](https://github.com/docker/machine/files/89986/success-docker-machine-restart.txt) 
* [success-docker-machine-restart-boot2docker.txt](https://github.com/docker/machine/files/89985/success-docker-machine-restart-boot2docker.txt)

Log files of a failed create-restart cycle (unfortunately, I seem to be missing the create boot2docker log):
* [failure-docker-machine-create.txt](https://github.com/docker/machine/files/89984/failure-docker-machine-create.txt)
* [failure-docker-machine-restart.txt](https://github.com/docker/machine/files/89982/failure-docker-machine-restart.txt)
* [failure-docker-machine-restart-boot2docker.txt](https://github.com/docker/machine/files/89980/failure-docker-machine-restart-boot2docker.txt)

**Comment by nathanleclaire** [comment]
Please try 0.7.0 and open a new ticket if you experience issues.  Thanks
