### ISSUE TITLE
 certs are valid. Maybe swarm is not started?

### ISSUE THREAD

**Issue by navinSing** [docker/machine#2840]
create a docker machines with generic
they were not provisioned.
so pasted the certs manually.. 
now the docker-machines are created .. 

These machines were created with --swarm flags, with one of them as master. Able to execute commands on machines but not in swarm. The consul was running outside the swarm cluster. 

$ docker-machine config --swarm v36
Error running connection boilerplate: Connection to Swarm cannot be checked but the certs are valid. Maybe swarm is not started

**Comment by nathanleclaire** [comment]
Can you please paste the `--debug` results of the `create` as well as the `config` call?  Thanks!

**Comment by dgageot** [comment]
@navinSing can you take a look at swarm logs? I guess swarm is either not running or has a configuration issue.

```
docker-machien ssh v36
docker logs swarm-agent-master
```

**Comment by navinSing** [comment]
@dgageot , yes swarm-agent-master is not started, yet docker-machine is showing that. NOTE : i started consul outside the docker-machine list(on my laptop, even the consul is not showing swarm) .. should it be part of the docker-machine list. 

docker-machine ls 
NAME   ACTIVE   URL       STATE     URL                       SWARM          DOCKER   ERRORS
v34    -        generic   Running   tcp://192.168.1.34:2376   v36            v1.9.1   
v35    -        generic   Running   tcp://192.168.1.35:2376   v36            v1.9.1   
v36    -        generic   Running   tcp://192.168.1.36:2376   v36 (master)   v1.9.1   
v37    -        generic   Running   tcp://192.168.1.37:2376   v36            v1.9.1   


=============

docker-machien ssh v36
$ docker logs swarm-agent-master
Error response from daemon: no such id: swarm-agent-master
$ docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
==



@nathanleclaire 


export MAC_NAME="v38"
export MAC_ETH="eth0"
export MAC_IP="192.168.1.38"
kowo@gomo:/mo/jo/deploy/jj$ export CONSUL_IP=19.168.1.33 &&  docker-machine --debug  create -d generic --generic-ip-address $MAC_IP --generic-ssh-key /mo/keysOfServers/vvwCommon/id_rsa --generic-ssh-user vvw --swarm --swarm-image="swarm:latest" --swarm-discovery="consul://$CONSUL_IP:8500" --engine-opt="cluster-store=consul://$CONSUL_IP:8500" --engine-opt="cluster-advertise=$MAC_ETH:2376" $MAC_NAME
Docker Machine Version:  0.5.6, build 61388e9
Found binary path at /usr/local/bin/docker-machine
Launching plugin server for driver generic
Plugin server listening at address 127.0.0.1:32962
() Calling .GetVersion
Using API Version  1
() Calling .SetConfigRaw
() Calling .GetMachineName
(flag-lookup) Calling .GetMachineName
(flag-lookup) Calling .DriverName
(flag-lookup) Calling .GetCreateFlags
Found binary path at /usr/local/bin/docker-machine
Launching plugin server for driver generic
Plugin server listening at address 127.0.0.1:41509
() Calling .GetVersion
Using API Version  1
() Calling .SetConfigRaw
() Calling .GetMachineName
(v38) Calling .GetMachineName
(v38) Calling .DriverName
(v38) Calling .GetCreateFlags
(v38) Calling .SetConfigFromFlags
Running pre-create checks...
(v38) Calling .PreCreateCheck
(v38) Calling .GetConfigRaw
Creating machine...
(v38) Calling .Create
(v38) Importing SSH key...
(v38) DBG | IP: 192.168.1.38
(v38) Calling .GetConfigRaw
(v38) Calling .DriverName
(v38) Calling .DriverName
Waiting for machine to be running, this may take a few minutes...
(v38) Calling .GetState
Machine is running, waiting for SSH to be available...
Getting to WaitForSSH function...
(v38) Calling .GetSSHHostname
(v38) Calling .GetSSHPort
(v38) Calling .GetSSHKeyPath
(v38) Calling .GetSSHKeyPath
(v38) Calling .GetSSHUsername
Using SSH client type: external
{[-o BatchMode=yes -o PasswordAuthentication=no -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=quiet -o ConnectionAttempts=3 -o ConnectTimeout=10 -o ControlMaster=no -o ControlPath=none vvw@192.168.1.38 -o IdentitiesOnly=yes -i /home/kowo/.docker/machine/machines/v38/id_rsa -p 22] /usr/bin/ssh}
About to run SSH command:
exit 0
SSH cmd err, output: <nil>:
Detecting operating system of created instance...
Detecting the provisioner...
(v38) Calling .GetSSHHostname
(v38) Calling .GetSSHPort
(v38) Calling .GetSSHKeyPath
(v38) Calling .GetSSHKeyPath
(v38) Calling .GetSSHUsername
Using SSH client type: external
{[-o BatchMode=yes -o PasswordAuthentication=no -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=quiet -o ConnectionAttempts=3 -o ConnectTimeout=10 -o ControlMaster=no -o ControlPath=none vvw@192.168.1.38 -o IdentitiesOnly=yes -i /home/kowo/.docker/machine/machines/v38/id_rsa -p 22] /usr/bin/ssh}
About to run SSH command:
cat /etc/os-release
SSH cmd err, output: <nil>: NAME="Ubuntu"
VERSION="14.04.3 LTS, Trusty Tahr"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 14.04.3 LTS"
VERSION_ID="14.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"

found compatible host: ubuntu
Provisioning with ubuntu(upstart)...
(v38) Calling .GetMachineName
(v38) Calling .GetSSHHostname
(v38) Calling .GetSSHPort
(v38) Calling .GetSSHKeyPath
(v38) Calling .GetSSHKeyPath
(v38) Calling .GetSSHUsername
Using SSH client type: external
{[-o BatchMode=yes -o PasswordAuthentication=no -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=quiet -o ConnectionAttempts=3 -o ConnectTimeout=10 -o ControlMaster=no -o ControlPath=none vvw@192.168.1.38 -o IdentitiesOnly=yes -i /home/kowo/.docker/machine/machines/v38/id_rsa -p 22] /usr/bin/ssh}
About to run SSH command:
sudo hostname v38 && echo "v38" | sudo tee /etc/hostname
SSH cmd err, output: exit status 1: sudo: no tty present and no askpass program specified

Error creating machine: Error running provisioning: Something went wrong running an SSH command!
command : sudo hostname v38 && echo "v38" | sudo tee /etc/hostname
err     : exit status 1
output  : sudo: no tty present and no askpass program specified








kowo@gomo:/mo/jo/deploy/jj$ docker-machine ls
NAME   ACTIVE   URL       STATE     URL                       SWARM          DOCKER    ERRORS
v34    -        generic   Running   tcp://192.168.1.34:2376   v36            v1.9.1
v35    -        generic   Running   tcp://192.168.1.35:2376   v36            v1.9.1
v36    -        generic   Running   tcp://192.168.1.36:2376   v36 (master)   v1.9.1
v37    -        generic   Running   tcp://192.168.1.37:2376   v36            v1.9.1
v38    -        generic   Running   tcp://192.168.1.38:2376                  Unknown   Unable to query docker version: Unable to read TLS config: open /home/kowo/.docker/machine/machines/v38/server.pem: no such file or directory





############## copy .pem files


#### ls
$ docker-machine ls
NAME   ACTIVE   URL       STATE     URL                       SWARM          DOCKER   ERRORS
v34    -        generic   Running   tcp://192.168.1.34:2376   v36            v1.9.1
v35    -        generic   Running   tcp://192.168.1.35:2376   v36            v1.9.1
v36    -        generic   Running   tcp://192.168.1.36:2376   v36 (master)   v1.9.1
v37    -        generic   Running   tcp://192.168.1.37:2376   v36            v1.9.1
v38    -        generic   Running   tcp://192.168.1.38:2376                  v1.9.1








$  docker-machine --debug config --swarm v36
Docker Machine Version:  0.5.6, build 61388e9
Found binary path at /usr/local/bin/docker-machine
Launching plugin server for driver generic
Plugin server listening at address 127.0.0.1:40970
() Calling .GetVersion
Using API Version  1
() Calling .SetConfigRaw
() Calling .GetMachineName
(v36) Calling .GetURL
Reading CA certificate from /home/kowo/.docker/machine/certs/ca.pem
Reading server certificate from /home/kowo/.docker/machine/machines/v36/server.pem
Reading server key from /home/kowo/.docker/machine/machines/v36/server-key.pem
(v36) Calling .GetURL
Reading CA certificate from /home/kowo/.docker/machine/certs/ca.pem
Reading server certificate from /home/kowo/.docker/machine/machines/v36/server.pem
Reading server key from /home/kowo/.docker/machine/machines/v36/server-key.pem
Error running connection boilerplate: Connection to Swarm cannot be checked but the certs are valid. Maybe swarm is not started

**Comment by nathanleclaire** [comment]
Hm. If the create fails Swarm is not guaranteed to be working.  Maybe that's the issue here?

**Comment by navinSing** [comment]
Actually the certs files were not there, hence docker-machine cannot ssh at that time.. have to manually copy it.
Can we have a default cert file path to pick this up or probably a command line args to pick up these certs .. so that the machine could be ssh'ed into and swarm master would then be created at creation time.(with create command.)

**Comment by navinSing** [comment]
@nathanleclaire  @dgageot 
Any luck on the bug.

**Comment by navinSing** [comment]
Actually the certs files were not there, hence docker-machine cannot ssh at that time.. have to manually copy it... hence the swarm-master was not created; but docker-machine shows that ... any other way to restart or manually create the swarm-master in the docker cluster.. Pls help, thanks.

**Comment by navinSing** [comment]
Ah ! got it closed by mistake ..

**Comment by nathanleclaire** [comment]
I'm running into this issue (or a similar one) as well on the RC1.  Looks like the created Swarm containers don't have any ports forwarded.

```console
docker@swarmmaster:~$ docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS                         PORTS               NAMES
14b31947dffe        swarm:latest        "/swarm join --advert"   8 minutes ago       Up 8 minutes                                       swarm-agent
28c103f6e0d3        swarm:latest        "/swarm manage --tlsv"   8 minutes ago       Restarting (1) 2 minutes ago                       swarm-agent-master
```
