### ISSUE TITLE
Docker machine inject USB device

### ISSUE THREAD

**Issue by cedricve** [docker/machine#2841]
I'm currently creating my own docker image, and I'm trying to inject a USB camera device into my docker container. After searching/finding a lot of different answers, I've managed to do this.

```
docker run -p 80:80 -v /dev/usb/bus:/dev/bus/usb -t kerberosio
```

As I work on OSX, and thus using docker-machine, I forwarded the USB device into my VM, installed usbutils and there it is: my USB devices are visible to the docker image.

```
# lsusb -t
/:  Bus 01.Port 1: Dev 1, Class=root_hub, Driver=ohci-pci/12p, 12M
|__ Port 1: Dev 2, If 0, Class=Video, Driver=, 12M
|__ Port 1: Dev 2, If 1, Class=Video, Driver=, 12M
|__ Port 1: Dev 2, If 2, Class=Vendor Specific Class, Driver=, 12M
|__ Port 2: Dev 3, If 0, Class=Video, Driver=, 12M
|__ Port 2: Dev 3, If 1, Class=Video, Driver=, 12M
|__ Port 2: Dev 3, If 2, Class=Audio, Driver=, 12M
|__ Port 2: Dev 3, If 3, Class=Audio, Driver=, 12M
```

My next step is to actually use the USB camera (on Port 1 and/or Port 2). However when trying to open these devices with e.g. fswebcam. I get an error:

```
# fswebcam -d /dev/bus/usb/001/002
--- Opening /dev/bus/usb/001/002...
Trying source module v4l2...
/dev/bus/usb/001/002 opened.
/dev/bus/usb/001/002: Not a V4L2 device?
Trying source module v4l1...
/dev/bus/usb/001/002 opened.
/dev/bus/usb/001/002: Not a V4L device?
VIDIOCGCAP: Inappropriate ioctl for device
/dev/bus/usb/001/002 closed.
Unable to find a source module that can read /dev/bus/usb/001/002.
```

So fswebcam found the device but doesn't know how to handle it. After doing some more research I've found out that the drivers are not found (see output above lsusb -t).

I'm wondering if someone can help me and tell me how to tackle this problem. Do I need to install the drivers myself, if yes, how should I do it? I'm pretty sure this has something to do with a docker-machine configuration.

My setup:

OSX 10.10.3
Docker version 1.9.1

Thanks in advance!

**Comment by nathanleclaire** [comment]
Hm, I'm not really sure.  Everything seems to be getting set up properly on the VM and container side, no?  It's possible you're missing some kind of dependency that is assumed to be around in normal systems.  Might want to run `fswebcam` with `--verbose` to see if that yields any useful info.

**Comment by cedricve** [comment]
Thanks for your comment; verbose doesn't gives me any other information.

```
# fswebcam --verbose -d /dev/bus/usb/001/002
--- Opening /dev/bus/usb/001/002...
Trying source module v4l2...
/dev/bus/usb/001/002 opened.
/dev/bus/usb/001/002: Not a V4L2 device?
Trying source module v4l1...
/dev/bus/usb/001/002 opened.
/dev/bus/usb/001/002: Not a V4L device?
VIDIOCGCAP: Inappropriate ioctl for device
/dev/bus/usb/001/002 closed.
Unable to find a source module that can read /dev/bus/usb/001/002
```

Indeed some dependencies are missing, it looks like the drivers are missing for the attached USB devices. Don't know if I need to forward another directory in the container?

**Comment by nathanleclaire** [comment]
I would guess there may be libraries and/or kernel modules missing that you need to `apt-get install` (or equivalent, e.g. patch), but I admit this is definitely not my area of expertise.

@SvenDowideit @tianon Any ideas for a tough problem? :D 

@jfrazelle You're the resident master of containerizing all the things, so if you have any ideas, would be great to have you chime in.

**Comment by cedricve** [comment]
I've installed the Oracle Virtual Box extension pack, so USB 2.0 and USB 3.0 devices can be used. But that didn't helped either.

**Comment by cedricve** [comment]
Does anyone can help on this?

**Comment by cedricve** [comment]
Any update on this ticket guys?

**Comment by nathanleclaire** [comment]
No update on our end, but let us know if you figure anything else out.

**Comment by nathanleclaire** [comment]
I think it's probably too hard to make supporting this a priority, but we're happy to accept PRs.  Thanks!

**Comment by cedricve** [comment]
@nathanleclaire it's been a while, is there any update on this ticket you're aware of?
