### ISSUE TITLE
[AmazonEC2 driver] Takes forever to finish creating the machine

### ISSUE THREAD

**Issue by ahmetalpbalkan** [docker/machine#285]
I was playing with amazonec2 driver to create a machine on EC2. It took so long (~30 mins) and I just killed it. It got stuck at `Waiting for SSH`, however when I go to the management console, the instance is there. (although I did not ssh into the instance, where can I find the .pem for the security group anyway?)

```sh
$ time bin/machine create -d amazonec2 --amazonec2-vpc-id=vpc-cdbdd0a8 --amazonec2-access-key=AK[.....]GP3A  --amazonec2-secret-key=daby[...]ciUi myamazonec2
INFO[0000] Launching instance...
INFO[0029] Waiting for SSH...
^C
real	1678.35s
user	0.36s
sys	0.08s
```

**Comment by sthulb** [comment]
The SSH key will be in $HOME/.docker/machines/name

**Comment by sthulb** [comment]
I've had the same issue.

**Comment by ehazlett** [comment]
What region/zone are you using?  I've been creating them tonight with no
issues.

**Comment by ahmetalpbalkan** [comment]
@ehazlett Whatever is the default, I use that. I used the command above.

**Comment by ehazlett** [comment]
It depends on your account.  You will be able to find your default in the
AWS console.

**Comment by ahmetalpbalkan** [comment]
@ehazlett alright, I've been using us-east-1a. For some reason it didn't work back then but it is working fine now.

**Comment by ehazlett** [comment]
Thanks for the follow-up!
