### ISSUE TITLE
"docker-machine start" ends before child processes finished

### ISSUE THREAD

**Issue by cjerdonek** [docker/machine#2851]
I noticed that `docker-machine start` (and `restart`) finish before all of its child processes are finished.  In particular, `/usr/local/bin/docker-machine-driver-virtualbox` runs for a half-second or so after start or restart is complete.  This is with version 0.5.1 (7e8e38e).

`docker-machine` should wait for its descendant processes to complete before exiting.

To reproduce, create the following script with name "machine-test.sh":

    #!/bin/bash

    pgid=$(ps xao pgid,pid,command | grep "[m]achine-test" | awk '{print $1}')
    echo "pgid: $pgid"
    docker-machine start default

    while [ 1 ]
    do
        echo "running ps:"
        ps xao pgid,pid,command | grep -E "^$pgid"
        sleep .25
    done

Then run it:

    $ ./machine-test.sh 
    pgid: 43885
    43885
    (shotwell) OUT | Starting VM...
    Started machines may have new IP addresses. You may need to re-run the `docker-machine env` command.
    running ps:
    43885 43885 /bin/bash ./machine-test.sh
    43885 43891 /usr/local/bin/docker-machine-driver-virtualbox
    43885 43929 ps xao pgid,pid,command
    43885 43930 grep -E ^43885^J43885
    running ps:
    43885 43885 /bin/bash ./machine-test.sh
    43885 43891 /usr/local/bin/docker-machine-driver-virtualbox
    43885 43932 ps xao pgid,pid,command
    43885 43933 grep -E ^43885^J43885
    running ps:
    43885 43885 /bin/bash ./machine-test.sh
    43885 43935 ps xao pgid,pid,command
    43885 43936 grep -E ^43885^J43885
    ^C

Observe the extra child process "/usr/local/bin/docker-machine-driver-virtualbox" with the same process group ID.

I believe this may be contributing to issue #2175 as I said in my comment on that issue [here](https://github.com/docker/machine/issues/2175#issuecomment-168533573) and [here](https://github.com/docker/machine/issues/2175#issuecomment-168792110).

**Comment by dgageot** [comment]
Hi @cjerdonek Can you check with version 0.5.6?

**Comment by cjerdonek** [comment]
@dgageot, I'm not seeing this issue with version 0.5.6, build 61388e9.  However, I'm still seeing issue #2175.

**Comment by dgageot** [comment]
Thanks for the feedback @cjerdonek. Can we close this ticket then?

**Comment by cjerdonek** [comment]
Sure, I'll close it. Thanks for your attention!
