### ISSUE TITLE
docker-machine create on amazonec2 driver fails on ssh cmd err and doesnt write the server.pem

### ISSUE THREAD

**Issue by steveinatorx** [docker/machine#2854]
OSX 
docker-machine version 0.5.6, build 61388e9
(i also tried several other previous versions of DM all the way down to pre-driver <5)
I know my AWS settings are good because i had created instances up to last week on the same VPC/subnet/region. 
Tried a new VPC in us-east-1, us-west-1, and us-west-2.
So the machines are actually created - they just fail to write the server.pem so the configs are corrupted.
i can delete them via docker-machine rm. 
Im not using ssh multiplexing - and i tried native-ssh and also switching out to the newest brew openssh - still keeps dying on this command:

```
Using SSH client type: external
{[-o BatchMode=yes -o PasswordAuthentication=no -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=quiet -o ConnectionAttempts=3 -o ConnectTimeout=10 -o ControlMaster=no -o ControlPath=none ubuntu@myip -o IdentitiesOnly=yes -i /Users/me/.docker/machine/machines/mysandbox3/id_rsa -p 22] /usr/bin/ssh}
About to run SSH command:
exit 0
SSH cmd err, output: exit status 255: 
Error getting ssh command 'exit 0' : Something went wrong running an SSH command!
command : exit 0
err     : exit status 255
output  : 
```

* i can successfully create a local instance using virtualbox

**Comment by steveinatorx** [comment]
workaround for anyone that lands on this: run docker-create -D in debug mode and just kill the process when it hangs on 
```exit 0
SSH cmd err, output: exit status 255: 
Error getting ssh command 'exit 0' : Something went wrong running an SSH command!
command : exit 0
err     : exit status 255
output  : 
```

i got the server.pem to create and the instance to reconfig correctly by regenerating the certs:
```
docker-machine regenerate-certs *machine-name*

**Comment by jeanlaurent** [comment]
thx @steveinatorx, I stumbled on this one, the other day while working on something else.

Did not pinpoint it precisely just yet.
Sounds from your 1st comment you tried a bunch of ssh connection.
Did the issue occurs when you were using the defaults ?

**Comment by steveinatorx** [comment]
@jeanlaurent  hi and thanks for responding,
So here was the forensics of what i did if i can remember this correctly - i had a previously installed version of docker toolkit that i upgraded to latest (OSX). This destroyed my existing amazonec2 driver based machine configs. My local virtualbox based machine configs were fine and worked normally with the upgrade.

At that point i couldnt run a docker-create amazonec2 without getting the ssh hang - the process would create the instance on ec2 but i couldnt get an env handle on it or connect to it - and it wouldnt build the server.pem key in the config. 

Today i ended up wiping out docker completely from my mac and reinstalling docker-machine and docker from brew

```
brew install docker
brew install docker-machine
```
Now its working as expected. 

Im going to close this issue but i strongly suspect that there is a bug (possibly a permissions problem) in the docker toolkit install/upgrade package for mac. I will leave it up to you folks to figure that out but this particular issue for me was solved per above by uninstalling and using brew.

**Comment by steveinatorx** [comment]
i had occasionally seen this same error intermittently until updating to docker-machine 0.6.0 and now havnt seen it since.

**Comment by liyaka** [comment]
Have the same problem with docker-machine 0.6.0 and 0.7.0 on Ubuntu.
The weird thing is that running the same commands in another VPC works without problems..
