### ISSUE TITLE
Docker Machine Login Launchd

### ISSUE THREAD

**Issue by caiofbpa** [docker/machine#2857]
I currently use this [gist](https://gist.github.com/awmichel/baf4337463b326b6d253) to start a local machine when my Mac boots. I would like to request a similar feature built into docker-machine, starting local machines by hand is cumbersome.

**Comment by dgageot** [comment]
Hello @caiofbpa I'm sorry it seems a little out of scope for Docker Machine.
Your gist seems to work well.
We'd welcome a PR to add this gist to the documentation somewhere.

**Comment by caiofbpa** [comment]
The problem with the gist is that we have the machine name (in this case `default`) hardcoded into the property list. I wondered if there could be a startup command like `docker-machine startup` that the launchd could call and then the set of machines to be started could be configured somewhere more accessible (config file or via docker-machine CLI itself). What do you think?

P.S.: I'll be working on that PR to update the documentation anyway. :smile:

**Comment by dgageot** [comment]
@caiofbpa any update of this or are you ok to close the ticket?

**Comment by caiofbpa** [comment]
I've opened #3047 to add this to the documentations. I'll fix the sign your work issue and hope we can move the conversation there.
