### ISSUE TITLE
Problem running docker-machine env on windows 7

### ISSUE THREAD

**Issue by davidkarlsen** [docker/machine#2858]
Please see enclosed screen-dump.
Some users have a problem running docker-machine on windows 7.
(I have no problems and am running on Windows10 - there might however be other environmental differences than this obvious one).
The issue seem to be related to the fact that there is a whitespace in the "Program Files" folder from the error message - however strange that this happens for some users and not all, as we follow the same installation instructions.
This is based on docker toolbox 1.9.1i

![env_cmd](https://cloud.githubusercontent.com/assets/18299/12393244/c5b38e2c-bdf4-11e5-884a-757fe1eec5a9.png)

**Comment by dgageot** [comment]
Hi @davidkarlsen, can you try with 0.6.0-rc1 that supports automatic shell detection?

**Comment by davidkarlsen** [comment]
Actually the problem was at one of my coworkers machine - and he resolved it by making sure ssh was in a path w/o whitespace. Everything works for me now except our psychotic VPN software which highjacks the ip routes to the machine and attempts to route that over vpn - which I fix by adding some delete route commands.
