### ISSUE TITLE
Invalid command line. Found extra arguments

### ISSUE THREAD

**Issue by mateeyow** [docker/machine#2859]
Hi! There seems to be an error when adding the ` --digitalocean-private-networking yes` parameter. This is my complete command.
```bash
docker-machine create --driver digitalocean --digitalocean-access-token $VERSUS_DO --digitalocean-region sgp1 --digitalocean-image coreos-stable --digitalocean-private-networking yes staging
```
Docker machine version: `docker-machine version 0.5.3`

**Comment by bamarni** [comment]
`--digitalocean-private-networking` looks like a flag, does it work without yes?

**Comment by mateeyow** [comment]
Let me test it out.

**Comment by mateeyow** [comment]
Yes it works. Sorry about that. Didn't know you can just place it without yes. Thank you!
