### ISSUE TITLE
add option to enable experimental swarm features

### ISSUE THREAD

**Issue by schmunk42** [docker/machine#2861]
Like described here https://github.com/docker/swarm/tree/master/experimental

As far as I understand the `-experimental` flag has to be passed before the actual `manage` or `join` command - I couldn't figure out a way to do so with currently available options.

*hacking the source now...* :)

**Comment by schmunk42** [comment]
That's what I'd need https://github.com/schmunk42/machine/commit/b741f603c70c306b068cbf1591b5436f5718e588

But I am unsure about the best way how to implement the option.

**Comment by schmunk42** [comment]
Some more feedback...

I tried to use it via `docker-compose`

```
appcli:
  environment:
    - 'reschedule:on-node-failure'
```

But got the error:

```
ERROR: invalid reschedule policy: on-node-failure=
```

I also tried

```
appcli:
  labels:
    - 'com.docker.swarm.reschedule-policy=["on-node-failure"]'
```

What basically works is:

```
appcli:
  labels:
    com.docker.swarm.reschedule-policy: "on-node-failure"
```

I couldn't see rescheduling yet, because I ran into

```
time="2016-01-18T22:53:30Z" level=error msg="HTTP error: Engine no longer exists" status=500 
```

I just stopped and started the engine, don't know why this happens (yet)?!

**Comment by jeanlaurent** [comment]
The main workaround is to install a standard machine ie withtout the `--swarm` flags and start a swarm container within it atm.

I'm not sure we would want to add such a global flag for this, but this is open for discussion. cc @docker/machine-maintainers
