### ISSUE TITLE
docker-machine can not create VBox VMs with less than 300MB RAM

### ISSUE THREAD

**Issue by marsmensch** [docker/machine#2870]
Might be OS X related, but i don't think so.

**Environment**
* OS X 10.10.5 (14F27)
* VirtualBox 5.0.12r104815
* docker-machine version 0.5.5, build 02c4254
* Docker version 1.9.1, build a34a1d5

**Steps to reproduce**
```$ docker-machine -D create -d virtualbox --virtualbox-memory 256 testerle```

**Effects**
* Machine hangs on WaitForSSH forever (see attached log)
* VM is created, but hangs with a kernel panic in VBox background (see attached screenshots)

**Should be**
If there is an arbitrary limit imposed by machine or VirtualBox for some reason, machine should
log and display a message to the user and exit gracefully.

**Gist**
https://gist.github.com/marsmensch/b8980dbc4b851dbfb11a

<img width="762" alt="screen shot 2016-01-19 at 08 43 41" src="https://cloud.githubusercontent.com/assets/82906/12412959/83cdc72e-be8b-11e5-8d69-508ee65c9c3e.png">
<img width="733" alt="screen shot 2016-01-19 at 08 26 40" src="https://cloud.githubusercontent.com/assets/82906/12412960/83cfa206-be8b-11e5-8328-c6d37e96fd54.png">

**Comment by marsmensch** [comment]
Forgot to mention that i do also have a (manually created) VBox VM that is running fine with 128M.

**Comment by jeanlaurent** [comment]
I can reproduce the issue. (OSX 10.11.2, docker-machine on master, same version of vbox)

On virtualbox, docker-machine provision the host with boot2docker. It runs completely from RAM so maybe it is the guilty one, I don't know minimum memory requirements for it. Sounds like from the error message it couldn't load the filesystem.

From a virtualbox point of view the machine is started and runs fine, so as the host does not start, there isn't much we can do to detect this.

I'm thinking putting a minimum value to the `--virtualbox-memory` flag.

**Comment by jeanlaurent** [comment]
While experimenting I stumbled on vbox memory limit 
`VBoxManage: error: Invalid RAM size: 1 MB (must be in range [4, 2097152] MB)`
Not helping much on boot2docker but this gives info on vbox

**Comment by marsmensch** [comment]
@jeanlaurent 
I think your fix is good enough and works for me, thanks for the investigation!
