### ISSUE TITLE
Docker client reporting bad certificate after new virtualbox VM created using machine

### ISSUE THREAD

**Issue by ivstas** [docker/machine#2871]
The original issue was created in docker toolbox repository:
https://github.com/docker/toolbox/issues/255

However, it was advised to raise the issue here as it is more likely to be connected with **docker-machine** rather than **toolbox**.

1. Create a new vm: `docker-machine create dev --driver virtualbox`
2. Setup docker client to work with the vm: `eval "$(docker-machine env dev)"`
3. Run hello-world example: `docker run hello-world`

**As result:**
`The server probably has client authentication (--tlsverify) enabled. Please check your TLS client certification settings: Post https://192.168.99.102:2376/v1.21/containers/create: remote error: bad certificate`

**Workaround:**
4. `export DOCKER_OPTS="-H $DOCKER_HOST --tls --tlskey $DOCKER_CERT_PATH/server-key.pem    --tlscert $DOCKER_CERT_PATH/server.pem --tlsverify --tlscacert $DOCKER_CERT_PATH/ca.pem "`
5. `alias docker="docker $DOCKER_OPTS"`

**After this hello-world works fine.**

- I installed docker and docker-machine using docker toolbox (version 1.9.1)
- docker-machine version 0.5.1
- docker version 1.9.1, build a34a1d5.
- the problem occurred only on Mac OS X (I use El Capitan, some people in original issue reported this problem with Yosemite), don't face this problem on Windows 10.

**Comment by nathanleclaire** [comment]
Hi @ivstas thanks for the issue.

Does the `eval $(docker-machine env dev)` line echo anything to the terminal when you run it?

Can you print the output of `docker-machine config dev` please (your alias, is largely what this is intended to spit out)?

How about versions?  Docker Machine 0.5.6 and Docker 1.9.1?

**Comment by ivstas** [comment]
> Does the eval $(docker-machine env dev) line echo anything to the terminal when you run it?

No. Nothing.
> How about the output of env | grep DOCKER after running that command?

```
DOCKER_HOST=tcp://192.168.99.101:2376
DOCKER_MACHINE_NAME=dev
DOCKER_TLS_VERIFY=1
DOCKER_CERT_PATH=/Users/stiv/.docker/machine/machines/dev
```

> Can you print the output of `docker-machine config dev` please ?

```
--tlsverify --tlscacert="/Users/stiv/.docker/machine/certs/ca.pem" --tlscert="/Users/stiv/.docker/machine/certs/cert.pem" --tlskey="/Users/stiv/.docker/machine/certs/key.pem" -H=tcp://192.168.99.100:2376
```

>  Your alias is largely what this is intended to spit out

Actually, that also confuses me a lot.

**Comment by nathanleclaire** [comment]
I'm seeing different IP addresses in `config` and `env` -- wonder if it's related or incidental.  Can you paste the output of `docker-machine env default` (no subshell) followed immediately by the output of `docker-machine config default`?

**Comment by nathanleclaire** [comment]
> I'm gonna update to latest docker and docker-machine. Btw, what is correct way to do that? Just reinstall the latest toolbox?

Yes, that's probably easiest.

**Comment by ivstas** [comment]
@nathanleclaire it's accidental, my fault. I just recreated dev machine several times - that was output from different attempts.

I updated to latest docker-machine & docker.

```
docker-machine version 0.5.6, build 61388e9
Docker version 1.9.1, build a34a1d5
```

Same issue.

Repeat from the start: 
 `docker-machine create dev --driver virtualbox`

```
Running pre-create checks...
Creating machine...
(dev) Copying /Users/stiv/.docker/machine/cache/boot2docker.iso to /Users/stiv/.docker/machine/machines/dev/boot2docker.iso...
(dev) Creating VirtualBox VM...
(dev) Creating SSH key...
(dev) Starting the VM...
(dev) Waiting for an IP...
Waiting for machine to be running, this may take a few minutes...
Machine is running, waiting for SSH to be available...
Detecting operating system of created instance...
Detecting the provisioner...
Provisioning with boot2docker...
Copying certs to the local machine directory...
Copying certs to the remote machine...
Setting Docker configuration on the remote daemon...
Checking connection to Docker...
Docker is up and running!
To see how to connect Docker to this machine, run: docker-machine env dev
```

`docker-machine env dev`
```
export DOCKER_TLS_VERIFY="1"
export DOCKER_HOST="tcp://192.168.99.102:2376"
export DOCKER_CERT_PATH="/Users/stiv/.docker/machine/machines/dev"
export DOCKER_MACHINE_NAME="dev"
# Run this command to configure your shell: 
# eval $(docker-machine env dev)
```

`eval $(docker-machine env dev)`
`docker run hello-world`
```
The server probably has client authentication (--tlsverify) enabled. Please check your TLS client certification settings: Post https://192.168.99.102:2376/v1.21/containers/create: remote error: bad certificate
```

`docker-machine config dev`
```
--tlsverify
--tlscacert="/Users/stiv/.docker/machine/certs/ca.pem"
--tlscert="/Users/stiv/.docker/machine/certs/cert.pem"
--tlskey="/Users/stiv/.docker/machine/certs/key.pem"
-H=tcp://192.168.99.102:2376
```

Btw, `docker-machine config dev` shows the certificates are obtained from `~/.docker/machine/certs` rather than `~/.docker/machine/machines/dev`. **Probably that is the reason?**

**Comment by nathanleclaire** [comment]
> @nathanleclaire, docker-machine config dev shows that certificates are obtained from ~/.docker/machine/certs rather than ~/.docker/machine/machines/dev. Probably it is the reason?

It's definitely possible.  I know there were some mistakes in the `libmachine` refactoring work that I did which resulted in this issue (inconsistent use of `certs` vs. VM dir), and it has been fixed in `env` but clearly `config` needs an update as well.

**Comment by ivstas** [comment]
@dgageot @nathanleclaire issue no longer appears on `docker-machine version 0.6.0, build e27fb87` (docker-toolbox 1.10.3)

**Comment by jeriko** [comment]
@ivstas I'm having exactly the same problem with a fresh install using `build e27fb87`, which you mentioned should be fixed?

**Comment by jeriko** [comment]
The `DOCKER_OPTS` / `alias` workaround fixes it for me, but `docker-compose` throws `SSL error: [SSL: SSLV3_ALERT_BAD_CERTIFICATE] sslv3 alert bad certificate`

**Comment by ligerzero459** [comment]
@ivstas It does still seem to be an issue. Fresh install, OS X El Capitan, Fish shell and Bash, with both the Virtualbox and VMWareFusion drivers

`docker-machine --version`
```
docker-machine version 0.6.0, build e27fb87
```

`docker-machine create --driver vmwarefusion --vmwarefusion-memory-size 10240 --vmwarefusion-disk-size "20480" default`

```
Running pre-create checks...
Creating machine...
(default) Copying /Users/ligerzero459/.docker/machine/cache/boot2docker.iso to /Users/ligerzero459/.docker/machine/machines/default/boot2docker.iso...
(default) Creating SSH key...
(default) Creating VM...
(default) Creating disk '/Users/ligerzero459/.docker/machine/machines/default/default.vmdk'
(default) Virtual disk creation successful.
(default) Starting default...
(default) Waiting for VM to come online...
Waiting for machine to be running, this may take a few minutes...
Detecting operating system of created instance...
Waiting for SSH to be available...
Detecting the provisioner...
Provisioning with boot2docker...
Copying certs to the local machine directory...
Copying certs to the remote machine...
Setting Docker configuration on the remote daemon...
Checking connection to Docker...
Docker is up and running!
To see how to connect your Docker Client to the Docker Engine running on this virtual machine, run: docker-machine env default
```

`docker-machine env default`

```
set -gx DOCKER_TLS_VERIFY "1";
set -gx DOCKER_HOST "tcp://192.168.106.128:2376";
set -gx DOCKER_CERT_PATH "/Users/ryanmottley/.docker/machine/machines/default";
set -gx DOCKER_MACHINE_NAME "default";
# Run this command to configure your shell: 
# eval (docker-machine env default)
```

`docker run hello-world`

```
docker: The server probably has client authentication (--tlsverify) enabled. Please check your TLS client certification settings: Post https://192.168.106.128:2376/v1.22/containers/create: remote error: bad certificate.
See 'docker run --help'.
```

Creating an alias with the the DOCKER_OPTS does seem to solve it, but is just a workaround

**Comment by jeriko** [comment]
I originally had the same issue with `e27fb87`, but upon uninstalling and reinstalling Docker Toolbox it was rectified.

**Comment by ligerzero459** [comment]
Tried a full uninstall and reinstall with both Docker Toolbox and Homebrew. Unfortunately, no effect :disappointed: I'll give it another shot

**Comment by nathanleclaire** [comment]
> Creating an alias with the the DOCKER_OPTS does seem to solve it, but is just a workaround

What do you mean specifically by this?

**Comment by jeriko** [comment]
@ligerzero459 Not sure what your issue is, but I also needed to remove the `.docker` folder (containing broken certs) which remained after uninstalling Docker Toolbox.

**Comment by jeriko** [comment]
@nathanleclaire see https://github.com/docker/machine/issues/2871#issue-127422705 titled "Workaround"

**Comment by nathanleclaire** [comment]
@jeriko Just to be clear, I see above you're using `fish`, you are running the command to set the environment variables as `eval (docker-machine env default)`, right?

**Comment by ligerzero459** [comment]
@nathanleclaire Correct, running it using `fish` syntax.

@jeriko I might have failed to remove my `.docker` folder before I reinstalled. I'll give that a shot and report back

**Comment by ligerzero459** [comment]
Not sure what caused it initially, but reinstalling once more after removing `.docker` did clear up the authentication error. Thanks, @jeriko

**Comment by jeriko** [comment]
Cool @ligerzero459 I think my error was because I launched both Kitematic and the Quickstart Terminal simultaneously once Toolbox was installed, and they each started their own machine setup processes which trod on each other.

**Comment by nathanleclaire** [comment]
@jeriko Mm, yeah, that's likely to cause problems.  There should probably be some kind of "locking" between these two entrypoints.

**Comment by ligerzero459** [comment]
@jeriko That's probably it. I did the exact same thing when I finished installing Toolbox the first time.
