### ISSUE TITLE
Use $DOCKER_MACHINE_NAME as default machine

### ISSUE THREAD

**Issue by robbertkl** [docker/machine#2877]
Love the default machine #2843 option in v0.6.0-rc1, but the first thing I wondered was: why use a hardcoded name "default". None of my machines are actually named default.

Usually when I interact with one of my docker machines, I have the `docker-machine env` variables set in my shell, so docker commands work. Wouldn't it make more sense if `$DOCKER_MACHINE_NAME` is used instead?

Just came across #1783, where @hairyhenderson actually suggest just this! Unfortunately, I don't see any discussion/acknowledgement around his proposal.

Since #2843 is now merged and #1783 closed, I'm starting this new issue to propose changing the default machine behaviour to use the value of `$DOCKER_MACHINE_NAME` instead of "default", unless `$DOCKER_MACHINE_NAME` is unset, in which case "default" can still be used as a fallback. This way, the environment variable can be seen as an override for `defaultMachineName`.

**Comment by robbertkl** [comment]
For those interested, I'm working on a PR for this proposal. Expect it today or tomorrow.

**Comment by dgageot** [comment]
Closing as won't do. See https://github.com/docker/machine/pull/2897
