### ISSUE TITLE
Driver "hyper-v" not found. Do you have the plugin binary accessible in your PATH?

### ISSUE THREAD

**Issue by Petoj87** [docker/machine#2878]
I installed docker toolbox, but when i try to use -drive hyper-v, i get the following error:
Driver "hyper-v" not found. Do you have the plugin binary accessible in your PATH?
What am i missing?
where is the binary located so i can add it to my path?

**Comment by jeanlaurent** [comment]
You're probably running an old `docker-machine` version, I suggest you move to the latest release atm v0.5.6

**Comment by Petoj87** [comment]
I'm using `0.5.5, build 02c4254`, has there been any bugfixes in 0.5.6 that would resolve this issue?
But ill try to upgrade when I get home, also it would be nice if you allowed me to unselect Virtual Box, currently I have to use Command line argument to remove it..

**Comment by jeanlaurent** [comment]
Nothing specific on this, I thought, you would have an older version than that. We rewrote the hyper-v driver in 0.5.5.

What is the exact command line you typed-in ? ( in your !st comment you typedin `hyper-v` where the real driver name is `hyperv`

What is your windows version ?

**Comment by Petoj87** [comment]
I have tried both `-d hyper-v` and `-d hyperv` I'm running windows 10.
If I understand it correctly the drivers are separate exe files?
If I'm correct where are they installed by default? (that way I can check if they are even there)

**Comment by Petoj87** [comment]
Nvm, I tried again now it works,, I must have written something wrong when I tried last time..
Sorry to have wasted your time!

**Comment by jeanlaurent** [comment]
> If I understand it correctly the drivers are separate exe files
There was a time where this was the case for v0.5 to ~ v0.5.2. It's not the case anymore. There could be cases where you have old binaries in your path which mess up with this, but that's not your case.

**Comment by jeanlaurent** [comment]
>I tried again now it works

:+1:
