### ISSUE TITLE
Unable to specify custom DO memory size

### ISSUE THREAD

**Issue by srid** [docker/machine#288]
I'm following the README here:

```
$ machine create -d digitalocean --digitalocean-access-token $MYDOTOKEN --digitalocean-size 1024mb docker0
INFO[0000] Creating SSH key...                          
INFO[0000] Creating Digital Ocean droplet...            
FATA[0001] POST https://api.digitalocean.com/v2/droplets: 422 You specified an invalid size for Droplet creation. 
```

Workaround: drop the `--digitalocean-size` argument and live with the 0.5G VM.

**Comment by ehazlett** [comment]
You need to specify a size DO expects (see https://developers.digitalocean.com/v1/sizes/ for the list).  In your case you can use `1gb` instead of `1024mb` and it will work.
