### ISSUE TITLE
Allow nonstandard docker daemon ports for --generic driver

### ISSUE THREAD

**Issue by CWSpear** [docker/machine#2882]
I have had success using `--generic` to bring remote docker instances into `docker-machine` in the past, but I've hit a snag on the latest:

My docker daemon is running on a port other than `2376`, specifically, it was started with:

```
docker daemon -H tcp://0.0.0.0:4243 -H unix:///var/run/docker.sock
```

Creating a Docker Machine instance with the generic driver, this host will connect to SSH, then say it is provisioning and installing Docker<sup>[1](#footnote)</sup>, does the cert thing, then says it errors out and asks me to verify that the daemon is listening.

Here's the full output:

```
Running pre-create checks...
Creating machine...
(goomba) Importing SSH key...
Waiting for machine to be running, this may take a few minutes...
Machine is running, waiting for SSH to be available...
Detecting operating system of created instance...
Detecting the provisioner...
Provisioning with ubuntu(systemd)...
Installing Docker...
Copying certs to the local machine directory...
Copying certs to the remote machine...
Setting Docker configuration on the remote daemon...
Error creating machine: Error running provisioning: Unable to verify the Docker daemon is listening: Maximum number of retries (10) exceeded
```

Then if I try to do something like `docker-machine env goomba`, it has this output:

```
Error checking TLS connection: Error checking and/or regenerating the certs: There was an error validating certificates for host "192.168.1.23:2376": dial tcp 192.168.1.23:2376: getsockopt: connection refused
You can attempt to regenerate them using 'docker-machine regenerate-certs [name]'.
Be advised that this will trigger a Docker daemon restart which will stop running containers.
```

You'll note that it's trying to connect to port `2376`, but the daemon is on port `4243`, so it fails.

I couldn't find a way change the port it tries to use. Am I missing something? Or if there's not a way, I would like to propose that we add a way to do that (like perhaps a `--generic-host=tcp://0.0.0.0:4243` flag or something?).

--

<a name="footnote">**[Footnote 1]**</a> Despite saying that it's installing Docker, it doesn't actually install it, does it? The docs say: "If docker is not running on the host, it will be installed automatically." Is this an error in docs, or an error in output, or some other misunderstanding?

**Comment by CWSpear** [comment]
This info may be helpful:

```
$ docker-machine version
docker-machine version 0.5.6, build 61388e9

$ docker version
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.5.3
 Git commit:   a34a1d5
 Built:        Sun Jan 17 16:14:45 UTC 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:20:08 UTC 2015
 OS/Arch:      linux/amd64
```

**Comment by jeanlaurent** [comment]
yes a `docker-machine create` will try to provision aka install docker on the remote host.

What do you want to achieve here ? Since you already has docker installed, Do you want to register your hand installed/started docker so it appears in docker-machine ? something else?

What is your distro/os ?

**Comment by CWSpear** [comment]
Yes, I want to bring this machine under `docker-machine` so I can switch between it and such.

Client is Mac 10.11, Server is Ubuntu 15.10.

So it looks like `docker-machine` put a config in `/etc/systemd/system/docker.service`, with an `ExecStart` directive that used the standard port, but I had an override at `/etc/systemd/system/docker.service.d/override.conf`with an `ExecStart` that was using the nonstandard port.

So in this specific case, I had originally needed to use a port in the 4000 range, which is why I had used `4243`.

So my original issue was actually slightly different than I had stated, and in this case, I was able to delete the override and then change stuff around to be able to use the default `2376`.

But in general, if for some reason I couldn't change to use port 2376 (i.e. like in `docker daemon -H tcp://0.0.0.0:2376`), I feel like there should be a way to specify a different port for `docker-machine` to use.

**Comment by jeanlaurent** [comment]
> So my original issue was actually slightly different than I had stated, and in this case, I was able to delete the override and then change stuff around to be able to use the default 2376.

Is your issue covered by #2820 then ?

byw, trying to register (aka put in docker-machine land) an existing docker daemon by sharing the socket is not really supported at the moment. This is something that is on the roadmap for 0.7 though.

**Comment by CWSpear** [comment]
> Is your issue covered by #2820 then ?

@jeanlaurent yeah, I think it is! I looked all over before posting the ticket. Sorry about the dupe.

So the main issue here could probably be closed as a duplicate of that one.

I guess the one thing I'm still a bit confused on is why the docs imply (by stating "If docker is not running on the host, it will be installed automatically.") that it won't install Docker, but it appears that it does no matter what.

**Comment by jeanlaurent** [comment]
> Sorry about the dupe.

No worries, we have quite a bunch of issues, we are down to less than 20 PRs, but we have still a looong way to triage and answer properly to all those issues.

> I guess the one thing I'm still a bit confused on is why the docs imply (by stating "If docker is not running on the host, it will be installed automatically.") that it won't install Docker, but it appears that it does no matter what.

Well we probably didn't detect custom installed docker properly. That why we would like to use docker-machine create for standard install, and have a way to register custom machine into docker-machine. But that's not ready yet.

**Comment by jeanlaurent** [comment]
>So the main issue here could probably be closed as a duplicate of that one.

Closing, feel free to open a new one to discuss the install thing.
