### ISSUE TITLE
Azure driver default location "West US" returned an error

### ISSUE THREAD

**Issue by anthonydahanne** [docker/machine#2886]
Hello,
trying out the Azure driver, and using the default location, I got the following error : 
````
$ docker-machine create -d azure --azure-subscription-id="XXXX" --azure-subscription-
cert="mycert.pem" machine-name
Running pre-create checks...
Creating machine...
(machine-name) Creating Azure machine...
Error creating machine: Error in driver during machine creation: Invalid location: West US. Available locations: East US, Central US, North Europe, West Europe, Southeast Asia, Japan West, Japan East
````

If this location "West US" does not exist anymore (maybe it's just temporary), I'd suggest we choose another default location

**Comment by ahmetalpbalkan** [comment]
@anthonydahanne Hello, this is about your subscription. Internally in Azure, we have various labels associated to each subscription.

For instance a subscription that's in the 30-day trial mode, or a subscription that belongs to Enterprise Agreement (EA) or BizSpark or some other program and a subscription that is just regular are all associated with a different tag.

For some reason (read: I don't know why) we don't allow all subscriptions to deploy to all locations. You can think this being used for capacity planning or flighting of new features on various types of customer groups.

For example my personal subscription (regular subscription opened with a credit card) has access to "West US", yours doesn't. In addition to this particular region, I also have access to "Brazil South", "East US 2", "South Central US" and "North Central US"; you don't. Just to illustrate the point better, I have another subscription that is opened with a 30-day free coupon I got at a conference. That has access to only 5 regions –so it's pretty limited.

On the contrary to most other cloud providers, we don't choose a default region for users in our portal/CLI. "westus" was just a choice probably was made early on during the development of this driver and we can probably change it in the rewrite (read: breaking change) I am currently doing.

However I'm not sure if we have one region that is enabled on all subscriptions. Therefore our options are very limited here. If you can email your subscription ID to me I can take a look and see what offer type your subscription is associated to and determine if it is a common one.

**Comment by anthonydahanne** [comment]
Hi there @ahmetalpbalkan ,
thanks for your answer, yeah I guess setting the default location to a location common to all subscriptions would make sense.
My subscription is a 30 day trial mode; I don't know your email address, here's a screenshot (not showing my subscription id though)

![screen shot 2016-01-22 at 11 13 48](https://cloud.githubusercontent.com/assets/60938/12516054/6d4cad06-c0f9-11e5-96a0-ec3caa2e3076.png)

If you really need my subscription id, please give me your azure email address.
Thanks

**Comment by ahmetalpbalkan** [comment]
@anthonydahanne from what I learned from the capacity planning team is, they assign different locations to different Free Trial subscriptions and there is no common region available to all Free Trial subscriptions. Even if there were one, it would change based on conditions. So nothing we can do here. I think the failure would be user-friendly in the new docker-machine azure driver, so users can fix that easily.
