### ISSUE TITLE
openstack driver with two controllers and two endpoints 

### ISSUE THREAD

**Issue by thbranch** [docker/machine#2887]
Hi i am getting a error when trying to use docker-machine with a openstack HA setup 

$ ./docker-machine create --driver openstack \

> --openstack-username user \
> --openstack-password password \
> --openstack-tenant-name project \
> --openstack-domain-name domain \
> --openstack-auth-url http://10.168.100.100:5000/v3 \
> --openstack-flavor-id 3 \
> --openstack-image-id 9b8d3106-9921-449c-b895-137c4e8d9ea8 \
> --openstack-net-name pxe-tst \
> --openstack-floatingip-pool ext-net \
> --openstack-ssh-user ubuntu \
> --openstack-sec-groups default \
>  sevstack-dev
> Running pre-create checks...
> Creating machine...
> Error creating machine: Error in driver during machine creation: Discovered 2 matching endpoints: []tokens.Endpoint{tokens.Endpoint{ID:"70bdd9d8ca7e4bd0bc6e42d2a0771f00", Region:"region1", Interface:"public", URL:"http://10.168.102.101:9696"}, tokens.Endpoint{ID:"81dbe77263d14fc0ad1d3522795596e2", Region:"region1", Interface:"public", URL:"http://10.168.102.100:9696"}}

**Comment by fsoppelsa** [comment]
`auth-url` is definitely wrong. In a HA (2 controllers is bad though, for quorum reasons, but that is), you should use as `auth-url` the VIP.

**Comment by fsoppelsa** [comment]
@thbranch did you try to point `OS_AUTH_URL` to your VIP?

**Comment by referup-tarantegui** [comment]
Hi, I'm having the same issue.
```
docker-machine create -d openstack \
>   --openstack-auth-url https://auth.cloud.ovh.net/v2.0/ \
>   --openstack-username $USERNAME \
>   --openstack-password $PASSWORD \
>   --openstack-tenant-name $NAME \
>   --openstack-flavor-id vps-ssd-1 \
>   --openstack-image-id Ubuntu14.04 \
>   consul
Running pre-create checks...
Creating machine...
Error creating machine: Error in driver during machine creation: Discovered 3 matching endpoints: []tokens.Endpoint{tokens.Endpoint{TenantID:"", PublicURL:"https://compute.gra1.cloud.ovh.net/v2/8c4c3c4e62794af6a82cab6db96768fb", InternalURL:"https://compute.gra1.cloud.ovh.net/v2/8c4c3c4e62794af6a82cab6db96768fb", AdminURL:"https://compute.gra1.cloud.ovh.net/v2/8c4c3c4e62794af6a82cab6db96768fb", Region:"GRA1", VersionID:"", VersionInfo:"", VersionList:""}, tokens.Endpoint{TenantID:"", PublicURL:"https://compute.bhs1.cloud.ovh.net/v2/8c4c3c4e62794af6a82cab6db96768fb", InternalURL:"https://compute.bhs1.cloud.ovh.net/v2/8c4c3c4e62794af6a82cab6db96768fb", AdminURL:"https://compute.bhs1.cloud.ovh.net/v2/8c4c3c4e62794af6a82cab6db96768fb", Region:"BHS1", VersionID:"", VersionInfo:"", VersionList:""}, tokens.Endpoint{TenantID:"", PublicURL:"https://compute.sbg1.cloud.ovh.net/v2/8c4c3c4e62794af6a82cab6db96768fb", InternalURL:"https://compute.sbg1.cloud.ovh.net/v2/8c4c3c4e62794af6a82cab6db96768fb", AdminURL:"https://compute.sbg1.cloud.ovh.net/v2/8c4c3c4e62794af6a82cab6db96768fb", Region:"SBG1", VersionID:"", VersionInfo:"", VersionList:""}}
```
I've noticed that shows different regions, but if I select a region this is the output.
```
docker-machine create -d openstack \
>   --openstack-auth-url https://auth.cloud.ovh.net/v2.0/ \
>   --openstack-username $USERNAME \
>   --openstack-password $PASSWORD \
>   --openstack-tenant-name $NAME \
>   --openstack-flavor-id vps-ssd-1 \
>   --openstack-image-id Ubuntu14.04 \
>   --openstack-region sbg1 \
>   consul
Running pre-create checks...
Creating machine...
Error creating machine: Error in driver during machine creation: No suitable endpoint could be found in the service catalog.
```

**Comment by thbranch** [comment]
@fsoppelsa endpoint in the example is my vip

**Comment by sloppylopez** [comment]
I am facing the same issue here did you overcame the problem?
@referup-tarantegui

**Comment by referup-tarantegui** [comment]
Sorry @sloppylopez but no. I've dropped this provider because this issue. Good luck!

**Comment by thbranch** [comment]
From what i gather is they are useing the RPC clients which only support one end point.

**Comment by thbranch** [comment]
https://github.com/hashicorp/terraform/issues/3293

https://github.com/rackspace/gophercloud/blob/master/openstack/endpoint_location.go#L31-31
https://github.com/rackspace/gophercloud/blob/master/openstack/endpoint_location.go#L11-11
