### ISSUE TITLE
Rackspace driver fails with 'internalURL' as endpoint type

### ISSUE THREAD

**Issue by wouterla** [docker/machine#2892]
Using current master/0.6.0-rc1, I can use the rackspace driver to create new machines on rackspace.

I want to use it from another rackspace instance, though, and use the internal IP to talk to docker, so as not to expose that to the outside.

When I try to run docker-machine with `--rackspace-endpoint-type internalURL`, though it always fails with:

    (consul-box) DBG | Authenticating to Rackspace. map[Username:<username>]
    Error creating machine: Error in driver during machine creation: Post /os-keypairs: unsupported protocol scheme ""
    open : no such file or directory
    notifying bugsnag: [Error creating machine: Error in driver during machine creation: Post /os-keypairs: unsupported protocol scheme ""]

My environment has the following variables set that have influence on rackspace:

    $> set | grep OS_
    OS_API_KEY=<something>
    OS_AUTH_URL=https://identity.api.rackspacecloud.com/v2.0/
    OS_PASSWORD=<something>
    OS_REGION_NAME=LON
    OS_TENANT_ID=<something>
    OS_USERNAME=<something>

This command works (using publicURL):
`docker-machine -D create --driver rackspace --rackspace-flavor-id 5 boxname`

This one doesn't (using internalURL):
`docker-machine -D create --driver rackspace --rackspace-flavor-id 5 --rackspace-endpoint-type internalURL boxname`

The error seems to have something to do with the gopherclient code not having the protocol (https) in this case. I'm not sure why this would be different for internal and public URLs...

**Comment by jeanlaurent** [comment]
What is the OS from which you're creating the machine ?

**Comment by wouterla** [comment]
I'm running on OSX latest version (El Capitan):

    sw_vers
    ProductName:	Mac OS X
    ProductVersion:	10.11.2
    BuildVersion:	15C50

I compiled docker-machine from master for this run (trying to get some more debug info).

**Comment by nathanleclaire** [comment]
@ggiamarchi

**Comment by nathanleclaire** [comment]
Please re-open a ticket if the issue is still present with 0.7.0.  Thanks
