### ISSUE TITLE
DigitalOcean SSH 255 error, CoreOS

### ISSUE THREAD

**Issue by leeDav** [docker/machine#2894]
`OS X version: 10.11.1`
`docker-machine version 0.5.6, build 61388e9`
`Docker version 1.9.1, build a34a1d5`

I used `docker-machine` to create a new droplet using CoreOS and I can't seem to get it to work. Here is the command I'm using:

`docker-machine --debug create --driver digitalocean --digitalocean-access-token $TOKEN --digitalocean-image coreos-alpha --digitalocean-region lon1 websites`

And here's the (verbose/debug) errors I'm getting. It keeps retrying until a timeout.

```
Getting to WaitForSSH function...
(websites1) Calling .GetSSHHostname
(websites1) Calling .GetSSHPort
(websites1) Calling .GetSSHKeyPath
(websites1) Calling .GetSSHKeyPath
(websites1) Calling .GetSSHUsername
Using SSH client type: external
{[-o BatchMode=yes -o PasswordAuthentication=no -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=quiet -o ConnectionAttempts=3 -o ConnectTimeout=10 -o ControlMaster=no -o ControlPath=none root@188.166.156.26 -o IdentitiesOnly=yes -i /Users/lee/.docker/machine/machines/websites1/id_rsa -p 22] /usr/bin/ssh}
About to run SSH command:
exit 0
SSH cmd err, output: exit status 255: 
Error getting ssh command 'exit 0' : Something went wrong running an SSH command!
command : exit 0
err : exit status 255
output :
 ```

The image itself does boot and I can see it in my Digital Ocean account and I can SSH in directly via IP but not via `docker-machine ssh website` as I simply get a `exit status 255`.

I have changed the image to Ubuntu and it works fine so I'm left wondering if there's something going on with the Digital Ocean API or whether there's something wrong with the CoreOS build (though I have tried all three; alpha, beta, and stable).

Any help would be much appreciated!

**Comment by bamarni** [comment]
I think it's trying to connect as root, but with coreos you have to do : `--digitalocean-ssh-user core`, and it should work :)

**Comment by leeDav** [comment]
Haha you're right! Boy do I feel silly. Thanks!
