### ISSUE TITLE
Release Candidate is provisioning non-rc version of docker-engine to cloud

### ISSUE THREAD

**Issue by BrianAdams** [docker/machine#2895]
The (0.6.0-rc1, build 174e390) `docker-machine create` with the digital ocean provider appears to be deploying the non-rc version of docker-engine.

While I can find the work arounds to specify the matching release candidate version for virtual box, I don't see any levers to pull to force the release candidate image of docker engine to be deployed by docker-machine.  Is docker-machine RC suppose to deploy docker-engine RC to cloud provisioners by default?  Is testing the RC against cloud provisioners supported right now, and if so, where can I find the correct steps to set it up?  Thanks!

`docker-machine version`
>docker-machine version 0.6.0-rc1, build 174e390

`docker-machine create   -d digitalocean   --digitalocean-access-token=${DO_TOKEN} test3`
>Running pre-create checks...
Creating machine...
(test3) Creating SSH key...
(test3) Creating Digital Ocean droplet...
(test3) Waiting for IP address to be assigned to the Droplet...
Waiting for machine to be running, this may take a few minutes...
Machine is running, waiting for SSH to be available...
Detecting operating system of created instance...
Detecting the provisioner...
Provisioning with debian...
Copying certs to the local machine directory...
Copying certs to the remote machine...
Setting Docker configuration on the remote daemon...
Checking connection to Docker...
Docker is up and running!
To see how to connect Docker to this machine, run: docker-machine env test3

```
eval $(docker-machine env test3)
docker info
```
>Error response from daemon: client is newer than server (client API version: 1.22, server API version: 1.21)

**Comment by BrianAdams** [comment]
Okay. That one line in the release notes about engine-install-url was key.  The command below works for anyone else that was scratching their head

```
docker-machine create -d digitalocean --digitalocean-access-token=${DO_TOKEN} --engine-install-url="https://test.docker.com" test5
```

**Comment by nathanleclaire** [comment]
Yep -- thanks for following up to close -- we don't hardcode Docker versions in Machine so it's always pulling the latest non-RC version, as you noted there are ways to try out the RCs for `virtualbox` (using `--virtualbox-boot2docker-url`) and other providers (using `--engine-install-url test.docker.com`).
