### ISSUE TITLE
Logs from driver are displayed out of order

### ISSUE THREAD

**Issue by ahmetalpbalkan** [docker/machine#2899]
Hi, I observed that if a docker-machine driver does a lot of `log.Debugf`, the messages are displayed in the wrong order sometimes. I'm not sure if it's about the rpc protocol or the processing on the client side. I can reproduce this easily.

It's probably not a big deal, however log statements don't have a date/time prefix, so it sometimes makes it harder to correlate log messages (for instance when correlating HTTP requests/responses to an external service from debug messages).

**Comment by jeanlaurent** [comment]
Yes, this occurs. You can even loose some of them in some corner case where the server panics.

The client/server communication can definitely be improved

**Comment by ahmetalpbalkan** [comment]
ah okay, I was just trying to confirm if it's a known issue/by design. thanks @jeanlaurent
