### ISSUE TITLE
Inconsistent UI in remove command

### ISSUE THREAD

**Issue by jeanlaurent** [docker/machine#2901]
UI sounds strange with the `(default)` coming out of nowhere.
```
$ dm rm -f default
About to remove default
(default) machine does not exist, assuming it has been removed already
Successfully removed default
```
I would believe this could be better :
```
About to remove default
machine default does not exist, assuming it has been removed already
Successfully removed default
```

**Comment by nathanleclaire** [comment]
It's because the "machine does not exist, assuming it has been removed already" message is printed from within the plugin.  I don't know that it will be very easy to change.  We would have to somehow do the existence check outside of the plugin, maybe we could use `GetState` and add a `state.Terminated`, but that's definitely a decent chunk of work.

**Comment by jeanlaurent** [comment]
Yes, I know it comes from within the plugin itself. The thing is, some time, especially in debug log on a `docker-machine ls` it's rather convenient to know which plugin is actually writing logs.

During a create for instance, this information is really not usefull also.
```
Running pre-create checks...
Creating machine...
(default) Copying /Users/jlm/.docker/machine/cache/boot2docker.iso to /Users/jlm/.docker/machine/machines/default/boot2docker.iso...
(default) Creating VirtualBox VM...
(default) Creating SSH key...
(default) Starting the VM...
(default) Waiting for an IP...
Waiting for machine to be running, this may take a few minutes...
Machine is running, waiting for SSH to be available...
Detecting operating system of created instance...
Detecting the provisioner...
Provisioning with boot2docker...
Copying certs to the local machine directory...
Copying certs to the remote machine...
Setting Docker configuration on the remote daemon...
Checking connection to Docker...
Docker is up and running!
To see how to connect Docker to this machine, run: /Users/jlm/go/src/github.com/docker/machine/bin/docker-machine env default
```
So maybe we should have a dedicated command to write something to the user which filter out the machine name. Sounds less complex than what you suggested  and convey more the intention than a `fmt.Println`

**Comment by nathanleclaire** [comment]
I think the information (output from plugin vs. main process) is useful although perhaps we could reduce the amount of screen space used in the future.
