### ISSUE TITLE
Driver for baremetal installation

### ISSUE THREAD

**Issue by Tagnard** [docker/machine#291]
What is needed is drivers to make baremetal install easier with for example, IPMI, DRAC and ILO and others.

This would be a killer feature for ease of installation.

**Comment by ehazlett** [comment]
Interesting.  Perhaps a `baremetal` driver :)  I guess it depends on where you wanted to start as far as automation.  I happen to have access to a 2950 so maybe I can take a look at potentially using something like the DRAC remote services API.  Would be awesome :)

**Comment by Tebro** [comment]
a PXE solution could also work, but that would require changes in a DHCP server. 

iDRAC and similar systems should not be impossible to implement, but that limits what kind of hardware can be supported.

**Comment by sebicas** [comment]
What about http://rancher.com/rancher-os/ ?

**Comment by dgageot** [comment]
@docker/machine-maintainers With the introduction of driver plugins, we should close this ticket, shouldn't we?

**Comment by nathanleclaire** [comment]
@dgageot Yes

**Comment by navinSing** [comment]
i still cannot find docker-machine for bare metal 
is it ever going to happen ??

**Comment by pandrew** [comment]
It´s a lot of work supporting all platforms. Start by looking if theres a go package for IPMI supporting these or take a look at https://www.dmtf.org/standards/redfish. It´s more or less ipmi with an api.

**Comment by navinSing** [comment]
It´s a lot of work supporting all platforms. 
>> atleast wee can support the ubuntu (since it has most server installations)
also not sure how would ipmi / redfish would help to simulate a docker machine for a swarm
