### ISSUE TITLE
undocumented flag: --vmwarevsphere-hostsystem/VSPHERE_HOSTSYSTEM for vmwarevsphere driver

### ISSUE THREAD

**Issue by dayglojesus** [docker/machine#2918]
Ran into an issue using the vSphere driver.

```Error creating machine: Error with pre-create check: default host resolves to multiple instances, please specify```

After some lengthy searching, I finally discovered there was a flag I could pass to specify which hypervisor to connect to, but this info was not documented on the driver info page...

https://docs.docker.com/machine/drivers/vsphere/

**Comment by jeanlaurent** [comment]
Thanks for pointing that out, sounds like the vsphere doc was really outdated.

Should be fixed in #2925
