### ISSUE TITLE
hyper-v & ssh -- vi not recognizing ESC

### ISSUE THREAD

**Issue by JeNeSuisPasDave** [docker/machine#2934]
On my Windows 10 machine, I used docker-machine to create a Hyper-V VM using the boot2docker image.

When I ssh into the running VM and launch 'vi' to edit a script, I find that **I can't use the escape (ESC) key to get out of vi's insert mode**. I'm guessing that terminal emulation isn't working correctly, or there is some kind of keyboard mismatch.

`echo $TERM` yields `xterm`.

I ssh'd from a Windows command window using a command like "docker-machine ssh mydockervm".

(also reported here: https://github.com/boot2docker/boot2docker/issues/1127)

**Comment by nathanleclaire** [comment]
It works for me with VirtualBox + git bash.

Some questions:

1. Which shell are you using to run the SSH command?  Powershell?  cmd.exe?
2. Are you using OpenSSH or the Golang SSH implementation?  If you print the output of something like `docker-machine --debug ssh default df` here we can tell you which.  If it's not OpenSSH I suspect there might be some terminal issues.

**Comment by JeNeSuisPasDave** [comment]
@nathanleclaire answers to your questions ...

1. I'm using cmd.exe
2. It must be the Golang SSH implementation. Here's the output you asked for:

```
C:\Program Files\Docker Toolbox>docker-machine --debug ssh heind-dkr df
Docker Machine Version:  0.5.6, build 61388e9
Found binary path at .\docker-machine.exe
Launching plugin server for driver hyperv
Plugin server listening at address 127.0.0.1:50675
() Calling .GetVersion
Using API Version  1
() Calling .SetConfigRaw
() Calling .GetMachineName
(heind-dkr) Calling .GetState
(heind-dkr) DBG | [executing ==>] : C:\WINDOWS\System32\WindowsPowerShell\v1.0\\powershell.exe -NoProfile -NonInteractive ( Get-VM heind-dkr ).state (heind-dkr) DBG | [stdout =====>] : Running
(heind-dkr) DBG |
(heind-dkr) DBG | [stderr =====>] :
(heind-dkr) Calling .GetSSHHostname
(heind-dkr) DBG | [executing ==>] : C:\WINDOWS\System32\WindowsPowerShell\v1.0\\powershell.exe -NoProfile -NonInteractive ( Get-VM heind-dkr ).state (heind-dkr) DBG | [stdout =====>] : Running
(heind-dkr) DBG |
(heind-dkr) DBG | [stderr =====>] :
(heind-dkr) DBG | [executing ==>] : C:\WINDOWS\System32\WindowsPowerShell\v1.0\\powershell.exe -NoProfile -NonInteractive (( Get-VM heind-dkr ).networkadapte rs[0]).ipaddresses[0]
(heind-dkr) DBG | [stdout =====>] : 10.32.150.155
(heind-dkr) DBG |
(heind-dkr) DBG | [stderr =====>] :
(heind-dkr) Calling .GetSSHPort
(heind-dkr) Calling .GetSSHKeyPath
(heind-dkr) Calling .GetSSHKeyPath
(heind-dkr) Calling .GetSSHUsername
SSH binary not found, using native Go implementation
{{{<nil> 0 [] [] []} docker [0xdaff60] <nil>  []} 10.32.150.155 22}
Filesystem           1K-blocks      Used Available Use% Mounted on
tmpfs                  3640572    126812   3513760   3% /
tmpfs                  2022536         0   2022536   0% /dev/shm
/dev/sda1             19049892    413668  17645500   2% /mnt/sda1
cgroup                 2022536         0   2022536   0% /sys/fs/cgroup
/dev/sda1             19049892    413668  17645500   2% /mnt/sda1/var/lib/docker/aufs
Making call to close driver server
(heind-dkr) Calling .Close
Successfully made call to close driver server
Making call to close connection to plugin binary
(heind-dkr) DBG | Closing plugin on server side

C:\Program Files\Docker Toolbox>
```

I installed PuTTY and that works fine, I can use vi without any terminal/keyboard issues. However, PuTTY is a separate GUI tool, not a CLI SSH, so not usable via `docker-machine`, AFAIK. Regardless, that means the problem must be in the client side of the SSH session, the Golang SSH implementation ... as you suspected.

**Comment by nathanleclaire** [comment]
Yep -- we can look into that and if you'd like a workaround for now you can install "git bash" and that should include `ssh`.

**Comment by JeNeSuisPasDave** [comment]
Thanks.

And I'll try Git Bash ... I have Git installed a different way so I can use it from Powershell scripts, but I can try Git Bash as an experiment.

**Comment by nathanleclaire** [comment]
Please re-file a ticket if you continue to experience issues.  Thanks

**Comment by xuwind** [comment]
Ctr + C will bring you out there...
