### ISSUE TITLE
ls command returning wrong header names, 0.6.0-rc2-dev

### ISSUE THREAD

**Issue by drish** [docker/machine#2937]
Hey guys,

Just noticed the `docker-machine ls` command is returning a wrong header value,

<img width="892" alt="captura de tela 2016-01-27 as 00 26 54" src="https://cloud.githubusercontent.com/assets/1730156/12602967/b930acc2-c48c-11e5-8760-84747c7a46db.png">

It should be `DRIVER` , instead of the first `URL` occurence.

in the `commands/ls.go` file, we have:

```go
	headers = map[string]string{
		"Name":          "NAME",
		"Active":        "ACTIVE",
		"ActiveHost":    "DRIVER", // should be ACTIVE_HOST ?
		"ActiveSwarm":   "STATE", // should be ACTIVE_SWARM ?
		"DriverName":    "URL", // should be DRIVER_NAME ?
		"State":         "STATE",
		"URL":           "URL",
		"SwarmOptions":  "SWARM_OPTIONS",
		"Swarm":         "SWARM",
		"EngineOptions": "ENGINE_OPTIONS",
		"Error":         "ERRORS",
		"DockerVersion": "DOCKER",
		"ResponseTime":  "RESPONSE",
	}
```

If so, should I submit a PR ?

Thank you !

**Comment by nathanleclaire** [comment]
Heh.  Yes, that is a bug.  Good catch!  Please do submit a PR.

**Comment by drish** [comment]
Ok ! working on this.
