### ISSUE TITLE
env --shell no longer defaults to sh/bash

### ISSUE THREAD

**Issue by gimoh** [docker/machine#2947]
Even though --help still says default for shell is sh/bash it is no longer the case, instead (if $SHELL isn't set) the command exits with error "Unknown shell".  This seems to have changed around e13e2b61c6e9a80c3e04815570b48be06ea0b344

**Comment by jeanlaurent** [comment]
Just for reference what shell/so are you using ?

**Comment by nathanleclaire** [comment]
Will look into it -- thanks for the report.
