### ISSUE TITLE
log.Debug arguments appear on the next log message

### ISSUE THREAD

**Issue by ahmetalpbalkan** [docker/machine#2948]
I am passing some object to my `log.Debug` call and it appears like this (see the first two lines):

```sh
(vm0) DBG | Querying public IP address.
(vm0) DBG | %!(EXTRA logutil.Fields= name="vm0-ip")Azure request  method="GET" request="https://management.azure.com/subscriptions/8ba6527b-a16d-4377-a91d-1072decc2aac/resourceGroups/docker-machine/providers/Microsoft.Network/publicIPAddresses/vm0-ip/?api-version=2015-06-15"
(vm0) DBG | Azure response  status="200 OK" method="GET" request="https://management.azure.com/subscriptions/8ba6527b-a16d-4377-a91d-1072decc2aac/resourceGroups/docker-machine/providers/Microsoft.Network/publicIPAddresses/vm0-ip/?api-version=2015-06-15" x-ms-request-id="7d2b9d30-9570-453d-93b8-bdb10627d15b"
```

what I was expecting is:

```sh
(vm0) DBG | Querying public IP address. name="vm0-ip"
(vm0) DBG | Azure request  method="GET" request="https://management.azure.com/subscriptions/8ba6527b-a16d-4377-a91d-1072decc2aac/resourceGroups/docker-machine/providers/Microsoft.Network/publicIPAddresses/vm0-ip/?api-version=2015-06-15"
(vm0) DBG | Azure response  status="200 OK" method="GET" request="https://management.azure.com/subscriptions/8ba6527b-a16d-4377-a91d-1072decc2aac/resourceGroups/docker-machine/providers/Microsoft.Network/publicIPAddresses/vm0-ip/?api-version=2015-06-15" x-ms-request-id="7d2b9d30-9570-453d-93b8-bdb10627d15b"
```

I tend to think there's some race in the libmachine/log package causing this.

**Comment by dgageot** [comment]
Hi @ahmetalpbalkan Can you share the code you used to log?

**Comment by ahmetalpbalkan** [comment]
@dgageot 

It's basically

log.debug("msg1", map1)
Log.Debug("msg2, map2)

And it prints:

DBG | msg1
DBG | %!(EXTRA map1) msg2 map2

I'm mobile right now but that's the basic idea. For maps I defined my own type amd overriden String() for better map printing.

**Comment by ahmetalpbalkan** [comment]
I must say I'm running on top of master. This was not happening with the old logging model back in late November.

**Comment by dgageot** [comment]
@ahmetalpbalkan Could you share the current version of this new driver? That'd great!

**Comment by ahmetalpbalkan** [comment]
@dgageot you can find it here but because I haven't set up auth you can't use it I guess. :) https://github.com/ahmetalpbalkan/machine/tree/azure-new oh you can't compile it either, I hotfixed many things in azure-sdk-for-go until the next code-generation for that happens and I haven't updated godeps yet.

Anyways the log line is here: https://github.com/ahmetalpbalkan/machine/blob/920500474f16ae8023fdc29d2014f13099cdb3bb/drivers/azure/azureutil/azureutil.go#L516

I just realized I was using Debugf instead of Debug, that is probably causing %!(EXTRA)... I'll close this once I confirm that. Thanks for now!

**Comment by ahmetalpbalkan** [comment]
ok this was totally a debug vs debugf mistake on my end.
