### ISSUE TITLE
Release script uploads binaries with OS capitalized

### ISSUE THREAD

**Issue by nathanleclaire** [docker/machine#2959]
@dgageot @jeanlaurent FYI

I haven't been able to debug it yet but the uploaded binaries (and in the template) for this RC, the names look like `docker-machine_Darwin-amd64` (note that the OS is capitalized).  This is violating our previous convention of all lowercase, so we probably should fix it.

**Comment by dgageot** [comment]
This is to mimic the other projects like compose. So not a bug to me

**Comment by jeanlaurent** [comment]
This was requested in #494, implemented in #2915.

If you look at [docker/docker](https://github.com/docker/docker/releases) and [docker/compose](https://github.com/docker/compose/releases) binary names, they have the same.

I don't like the fact that we have a capital in the middle of nowhere like this, but hey, everyone else @ Docker is doing that, so...

**Comment by nathanleclaire** [comment]
Hm OK, I hadn't realized it was intentional.  Thanks!

**Comment by nathanleclaire** [comment]
I'll update the binary names to be the correct format
