### ISSUE TITLE
Machine 0.6.0-rc2 doesn't work with boot2docker 1.10-rc2

### ISSUE THREAD

**Issue by nathanleclaire** [docker/machine#2966]
cc @docker/machine-maintainers 

e.g.

```console
$ docker-machine create -d virtualbox --virtualbox-boot2docker-url https://github.com/tianon/boot2docker-legacy/releases/download/v1.10.0-rc2/boot2docker.iso rc2
```
It seems to timeout on the daemon listening step, because the netstat shows `2375` instead of `2376`.  I'm not sure where the change happened that causes this issue but it needs to be fixed before release.

Note this (healthy -- from 1.9.1 ISO) output which is where DM 0.6.0-rc2 is failing due to not having `2376` in the output:

```
Using SSH client type: external
{[-o BatchMode=yes -o PasswordAuthentication=no -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=quiet -o ConnectionAttempts=3 -o ConnectTimeout=10 -o ControlMaster=no -o ControlPath=none docker@127.0.0.1 -o IdentitiesOnly=yes -i /Users/nathanleclaire/.docker/machine/machines/dtr-local2/id_rsa -p 65115] /usr/local/bin/ssh}
About to run SSH command:
netstat -an
SSH cmd err, output: <nil>: Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN
tcp        0      0 10.0.2.15:22            10.0.2.2:65155          ESTABLISHED
tcp        0      0 :::22                   :::*                    LISTEN
Active UNIX domain sockets (servers and established)
Proto RefCnt Flags       Type       State         I-Node Path
unix  2      [ ACC ]     STREAM     LISTENING      17941 /var/run/acpid.socket
unix  2      [ ACC ]     SEQPACKET  LISTENING      14970 /run/udev/control
unix  3      [ ]         DGRAM                     11613
unix  3      [ ]         STREAM     CONNECTED      18208
unix  3      [ ]         STREAM     CONNECTED      18209
unix  3      [ ]         DGRAM                     11614

(dtr-local2) Calling .GetSSHHostname
(dtr-local2) Calling .GetSSHPort
(dtr-local2) Calling .GetSSHKeyPath
(dtr-local2) Calling .GetSSHKeyPath
(dtr-local2) Calling .GetSSHUsername
Using SSH client type: external
{[-o BatchMode=yes -o PasswordAuthentication=no -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=quiet -o ConnectionAttempts=3 -o ConnectTimeout=10 -o ControlMaster=no -o ControlPath=none docker@127.0.0.1 -o IdentitiesOnly=yes -i /Users/nathanleclaire/.docker/machine/machines/dtr-local2/id_rsa -p 65115] /usr/local/bin/ssh}
About to run SSH command:
netstat -an
SSH cmd err, output: <nil>: Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN
tcp        0      0 10.0.2.15:22            10.0.2.2:65156          ESTABLISHED
tcp        0      0 :::22                   :::*                    LISTEN
tcp        0      0 :::2376                 :::*                    LISTEN
Active UNIX domain sockets (servers and established)
Proto RefCnt Flags       Type       State         I-Node Path
unix  2      [ ACC ]     STREAM     LISTENING      17941 /var/run/acpid.socket
unix  2      [ ACC ]     STREAM     LISTENING      18212 /var/run/docker.sock
unix  2      [ ACC ]     STREAM     LISTENING      18615 /var/lib/docker/network/files/a2bda3e325bfd6a77e407051ba9fe90331c3f9e34ef40866e72e1f2ae21e6d7f.sock
unix  2      [ ACC ]     SEQPACKET  LISTENING      14970 /run/udev/control
unix  3      [ ]         DGRAM                     11613
unix  3      [ ]         STREAM     CONNECTED      18742
unix  3      [ ]         DGRAM                     11614
unix  3      [ ]         STREAM     CONNECTED      18741
```

Will post more information / fix as I keep digging in.

**Comment by nathanleclaire** [comment]
Yeah so basically this is blocking me from releasing a new Toolbox RC.

Currently I'm compiling `boot2docker.iso` to try and see which patch introduced the breaking change.  My guess is that either https://github.com/boot2docker/boot2docker/commit/088c11aec2dd1f935ed43903a947af562d87a536 or https://github.com/boot2docker/boot2docker/commit/d893bae17c4bde29ea2b4d92db9d77a3cf5b6f2b is responsible.

**Comment by nathanleclaire** [comment]
OK, getting some confusing results here.  Building `boot2docker/boot2docker` master I have not duped this bug so far, I can only dupe it with @tianon's ISO from boot2docker-legacy.

**Comment by nathanleclaire** [comment]
OK @tianon I'm going to need you to help with taking a look at this since I'm pretty confused.  Compiling from master on boot2docker/boot2docker and tianon/boot2docker-legacy gives me `boot2docker.iso` files that don't reproduce the bug (unless I'm mistaken, which is definitely possible).  

The SHA256 of the RC2 iso is `1205837b9abba85530391b35864023ccc040e56993e92c08fb00cc6177ce3955`, but the compiles from master on both repos mentioned above result in an ISO with checksum of `b9ad694c120ce998968de816eec109e47cf5eb1f4715ff98d76941e6250cd800` (boot2docker/boot2docker) and `641fbf70a3d8292e845a83e44bb5ad89cf37121ffb843d28388b2eddbe4998bf` (tianon/boot2docker-legacy) for me.  I wonder if there might be some slight inconsistency in your environment?  At any rate I would appreciate it if you could try to dupe the bug from both master and the uploaded RC2 release ISO (using Machine 0.6.0-rc2), to at least confirm what I'm seeing.

**Comment by tianon** [comment]
I can't test further right away, but I can tell you that my ISO was built with the following _after_ building the main b2d `Dockerfile`:
```dockerfile
FROM boot2docker/boot2docker

ENV TEST_DOCKER_VERSION 1.10.0-rc2

RUN curl -fsSL https://test.docker.com/builds/Linux/x86_64/docker-$TEST_DOCKER_VERSION -o $ROOTFS/usr/local/bin/docker \
	&& chmod +x $ROOTFS/usr/local/bin/docker \
	&& $ROOTFS/usr/local/bin/docker -v

RUN $ROOTFS/usr/local/bin/docker -v | sed -r 's/.* version ([^ ,]+).*/\1/' > $ROOTFS/etc/version \
	&& cp -v $ROOTFS/etc/version /tmp/iso/version

RUN { echo; echo "  WARNING: this is a test.docker.com build, not a release."; echo; } >> $ROOTFS/etc/motd

RUN /make_iso.sh
```

**Comment by tianon** [comment]
Using:
```bash
docker build -t boot2docker/boot2docker --pull .
docker build -t boot2docker/boot2docker:test -f Dockerfile.test .
docker run --rm boot2docker/boot2docker:test > boot2docker.iso
```

**Comment by dgageot** [comment]
I've tested with docker machine 0.6.0-rc2, 0.6.0-rc2 and 0.5.6. Same failure

**Comment by moxiegirl** [comment]
Just saw the same thing. I deleted everything `.docker` executables, Everything. Reinstalled from the rc1.  I ran in debug.   Trapped all the output:

[machine-fails.txt](https://github.com/docker/machine/files/111131/machine-fails.txt)

**Comment by patrikerdes** [comment]
When trying to find the difference between the rc1 iso and the rc2 iso I found this:

When SSH:ing into a machine and looking at the file `/etc/init.d/docker` line 9 is `: ${DOCKER_TLS:=auto}` in the rc1 release iso and `${DOCKER_TLS:=no}` in the rc2 iso. Having TLS disabled would explain why the port is 2375.

```
# docker-machine create -d virtualbox --virtualbox-boot2docker-url https://github.com/tianon/boot2docker-legacy/releases/download/v1.10.0-rc1/boot2docker.iso rc1
[...]
# docker-machine create -d virtualbox --virtualbox-boot2docker-url https://github.com/tianon/boot2docker-legacy/releases/download/v1.10.0-rc2/boot2docker.iso rc2
[...]
# docker-machine scp rc1:/etc/init.d/docker docker-rc1
# docker-machine scp rc2:/etc/init.d/docker docker-rc2
# diff docker-rc1 docker-rc2
9c9
< : ${DOCKER_TLS:=auto}
---
> : ${DOCKER_TLS:=no}
30a31,35
>     if [ ! -e "/etc/docker" ]; then
>         echo "Linking /etc/docker to /var/lib/boot2docker for persistence"
>         mkdir -p "/var/lib/boot2docker/etc/docker"
>         ln -sf "/var/lib/boot2docker/etc/docker" "/etc/docker"
>     fi
```

This change can not be seen when looking in the git repo. There the line is `: ${DOCKER_TLS:=auto}` for both rc1 and rc2.

```
# git remote -v
origin	https://github.com/tianon/boot2docker-legacy.git (fetch)
origin	https://github.com/tianon/boot2docker-legacy.git (push)
# git diff v1.10.0-rc1 v1.10.0-rc2 rootfs/rootfs/usr/local/etc/init.d/docker
diff --git a/rootfs/rootfs/usr/local/etc/init.d/docker b/rootfs/rootfs/usr/local/etc/init.d/docker
index 65a287e..9994f5f 100644
--- a/rootfs/rootfs/usr/local/etc/init.d/docker
+++ b/rootfs/rootfs/usr/local/etc/init.d/docker
@@ -28,6 +28,11 @@ test -f '/var/lib/boot2docker/profile' && . '/var/lib/boot2docker/profile'
 export PATH=${PATH}:/usr/local/sbin

 start() {
+    if [ ! -e "/etc/docker" ]; then
+        echo "Linking /etc/docker to /var/lib/boot2docker for persistence"
+        mkdir -p "/var/lib/boot2docker/etc/docker"
+        ln -sf "/var/lib/boot2docker/etc/docker" "/etc/docker"
+    fi
     # Not enabling Docker daemon TLS by default.
     if [ "$DOCKER_TLS" != "no" ]; then
         CERTHOSTNAMES="$(hostname -s),$(hostname -i)"
```

`/etc/init.d/docker` is symlinked to `/usr/local/etc/init.d/docker` in both the rc1 and rc2 machine.
I though `/usr/local/etc/init.d/docker` would reflect the contents of the file `rootfs/rootfs/usr/local/etc/init.d/docker` in the git repository, but that does not seem to happen in this case. I have no idea why.

**Comment by tianon** [comment]
@patrikerdes oh bollocks, you're dead on -- this is my fault

@nathanleclaire if I build a fixed rc2, do you think I should just remove the broken one and replace it, or should I do some screwery with the version number?

**Comment by tianon** [comment]
Oh, there's a 4.1.17 too -- I'll bundle that in and probably just throw a `-1` on the version number since that's a bigger change than just a rebuild.

**Comment by tianon** [comment]
Ok, give https://github.com/boot2docker/boot2docker/releases/tag/v1.10.0-rc2-b a go.

**Comment by nathanleclaire** [comment]
The new version is fixed for me.
