### ISSUE TITLE
support aliyun cloud driver ecs.console.aliyun.com

### ISSUE THREAD

**Issue by popsuper1982** [docker/machine#2973]
aliyun cloud is a famous cloud provider that is widely used in China, but now there is no driver for it.

I plan to develop a aliyun cloud driver for docker-machine

**Comment by nathanleclaire** [comment]
Thanks, we recommend making a plugin for it and submitting a pull request to link to it in https://github.com/docker/machine/blob/master/docs/AVAILABLE_DRIVER_PLUGINS.md !

**Comment by denverdino** [comment]
There is one driver in https://develop.aliyun.com/command/docker
The Git project is in https://github.com/denverdino/docker-machine-driver-aliyunecs
The PR for submit available driver plugins is in #3128
