### ISSUE TITLE
specifying multiple --engine-opt fails

### ISSUE THREAD

**Issue by rhim** [docker/machine#2975]
Hi Folks,

I am trying to specify both cluster-store and cluster-advertise as follows:

--engine-opt "cluster-store=consul://X.X.X.X:8500" –-engine-opt "cluster-advertise=eth0:2376"

However, this results in 

Invalid command line. Found extra arguments [cluster-advertise=eth0:2376 vmfoo]

According to documentation, this should be allowed (also see an example in documentation):
--engine-opt [--engine-opt option --engine-opt option] 

Any ideas?

Thanks,
Himanshu

**Comment by nathanleclaire** [comment]
Are you passing them after the machine name maybe?

Something like this:

```console
$ docker-machine create -d amazonec2 foo --engine-opt dns=8.8.8.8
```

Is invalid syntax today.  `foo` (the machine name) has to come last.

**Comment by nathanleclaire** [comment]
Yeah, this works for me with the latest RC, so let me know if you continue to encounter issues (include the `create` command please).

**Comment by rhim** [comment]
No, I am putting machine name last. 
Can you give me your version and OS version pls?
Thanks,

-Himanshu




On Wed, Feb 3, 2016 at 10:19 AM -0800, "Nathan LeClaire" <notifications@github.com> wrote:












Yeah, this works for me with the latest RC, so let me know if you continue to encounter issues (include the create command please).

**Comment by nathanleclaire** [comment]
I'm on OSX El Cap, Machine 0.6.0-rc4.

How about you?

**Comment by rhim** [comment]
Same here.

Here is the failing command:

/usr/local/bin/docker-machine -D create --driver amazonec2 --amazonec2-access-key XXX --amazonec2-secret-key XXXX --amazonec2-region us-west-1 --amazonec2-vpc-id vpc-838804e6 --amazonec2-subnet-id subnet-7041f729 --amazonec2-zone b --amazonec2-instance-type t2.micro --amazonec2-ami ami-3f50245f --engine-install-url http://X.X.X.X:8081/pkgs/install.sh --engine-opt cluster-store=consul://54.183.105.176:8500 –-engine-opt cluster-advertise=eth0:2376 vhost-rhim839

A similar command succeeds with generic driver.

**Comment by nathanleclaire** [comment]
I notice that the last flag you posted (`--engine-opt cluster-advertise=eth0:2376`) has an "em dash" (`–` - sometimes automatically inserted by Mac editors) instead of a normal hyphen (`-`) -- maybe that's it?  If you replace that argument with a real dash does it work?

**Comment by rhim** [comment]
OMG, that indeed was the case.

Thanks for pointing it out.

**Comment by nathanleclaire** [comment]
:+1: I hate that Mac behavior of replacing with the fancy dashes.  Glad to hear it worked out.

**Comment by LaurentGoderre** [comment]
OMG!!! You guys saved me a lot of trouble. I was pulling my hair out
