### ISSUE TITLE
hyper-v machine creation on remote host

### ISSUE THREAD

**Issue by sipicsg** [docker/machine#2985]
It would be nice it docker-machine could create a new machine on remote host.

New-VM -ComputerName<String[]>

[Info](https://technet.microsoft.com/en-us/library/hh848537.aspx)

I don't know if remote vhd creation for the new vm is possible in this way or not.

**Comment by jeanlaurent** [comment]
We have no plan on working on this as of now, as current `hyperv` driver support only local vm. But we gladly accept contribution.

Indeed we don't really know how to setup/transfer the vhd on the target machine, do you feel investigating it or even better contributing to it ?

**Comment by nathanleclaire** [comment]
No update on this issue in over 2 months -- please submit a PR if you'd like to add this feature.
