### ISSUE TITLE
Hanging on deploying CoreOS images on DigitalOcean

### ISSUE THREAD

**Issue by lavalamp-** [docker/machine#2987]
Greetings,

I recently ran into an issue where I could not properly create CoreOS-based droplets on DigitalOcean through the docker-machine digitalocean driver. Specifically, the process fails when attempting to SSH in and invoke commands:

**Using SSH client type: external
{[-o PasswordAuthentication=no -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=quiet -o ConnectionAttempts=3 -o ConnectTimeout=10 -o ControlMaster=no -o ControlPath=none root@162.243.80.49 -o IdentitiesOnly=yes -i /Users/lavalamp/.docker/machine/machines/swarm-master/id_rsa -p 22] /usr/bin/ssh}
About to run SSH command:
exit 0
SSH cmd err, output: exit status 255:
Error getting ssh command 'exit 0' : Something went wrong running an SSH command!
command : exit 0
err     : exit status 255
output  :**

Further investigation hinted that the private key was not properly installed to the CoreOS droplet. I could not SSH to the droplet using the private key that docker-machine had generated:

**lavalamp@molten ~/D/P/IoT>
ssh -i /Users/lavalamp/.docker/machine/machines/swarm-master/id_rsa root@<redacted>
The authenticity of host '<redacted> (<redacted>)' can't be established.
RSA key fingerprint is <redacted>.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added '<redacted>' (RSA) to the list of known hosts.
root@<redacted>'s password:**

I was able to create an Ubuntu-based droplet using docker-machine's digitalocean API immediately afterwards, hinting that the issue is specific to deploying to CoreOS.

**Comment by nathanleclaire** [comment]
Did you set the SSH user?

**Comment by nathanleclaire** [comment]
I think `core` is the default, so you need something like `--digitalocean-ssh-user core`

**Comment by lavalamp-** [comment]
Aha - I did not. It looks like that was the problem as well.

I double checked the documentation here:

https://docs.docker.com/machine/drivers/digital-ocean/

And I don't believe there is any mention of this command line flag.

Thanks for your help!
