### ISSUE TITLE
Swarm does not resolve machine nodes on external machines correctly

### ISSUE THREAD

**Issue by mlovci** [docker/machine#2988]
I have two (physical) machines that I'd like to join into the same docker swarm. I have a consul keystore running on machine 1 and a swarm master connected to that keystore on machine 1. I can start a worker node on machine 1, but attempts to join the swarm from machine 2 have failed.

## on machine1:

 - Create Swarm master

`machine1 $> docker-machine create -d virtualbox --swarm --swarm-master --swarm-discovery="consul://<MACHINE1 IP>:8500" --engine-opt="cluster-store=consul://<MACHINE1>:8500" --engine-opt="cluster-advertise=eth0:2376" mhs-demo0`

> Running pre-create checks...
> Creating machine...
> Waiting for machine to be running, this may take a few minutes...
> Machine is running, waiting for SSH to be available...
> Detecting operating system of created instance...
> Provisioning created instance...
> Copying certs to the local machine directory...
> Copying certs to the remote machine...
> Setting Docker configuration on the remote daemon...
> Configuring swarm...
> To see how to connect Docker to this machine, run: docker-machine env mhs-demo0
> 

 - Create a worker node

`machine1 $> docker-machine create -d virtualbox --swarm --swarm-discovery="consul://<MACHINE1 IP>:8500" --engine-opt="cluster-store=consul://<MACHINE1>:8500" --engine-opt="cluster-advertise=eth0:2376" worker1`

> Running pre-create checks...
> Creating machine...
> Waiting for machine to be running, this may take a few minutes...
> Machine is running, waiting for SSH to be available...
> Detecting operating system of created instance...
> Provisioning created instance...
> Copying certs to the local machine directory...
> Copying certs to the remote machine...
> Setting Docker configuration on the remote daemon...
> Configuring swarm...
> To see how to connect Docker to this machine, run: docker-machine env worker1
> 

 - Check the state of the swarm
    
```
machine1 $> eval $(docker-machine env --swarm mhs-demo0)
machine1 $> docker info
```
> Containers: 3
> Images: 2
> Role: primary
> Strategy: spread
> Filters: health, port, dependency, affinity, constraint
> Nodes: 2
>  mhs-demo0: 192.168.99.108:2376
>   └ Status: Healthy
>   └ Containers: 2
>   └ Reserved CPUs: 0 / 1
>   └ Reserved Memory: 0 B / 1.021 GiB
>   └ Labels: executiondriver=native-0.2, kernelversion=4.1.13-boot2docker, operatingsystem=Boot2Docker 1.9.1 (TCL 6.4.1); master : cef800b - Fri Nov 20 19:33:59 UTC 2015, provider=virtualbox, storagedriver=aufs
>  worker1: 192.168.99.109:2376
>   └ Status: Healthy
>   └ Containers: 1
>   └ Reserved CPUs: 0 / 1
>   └ Reserved Memory: 0 B / 1.021 GiB
>   └ Labels: executiondriver=native-0.2, kernelversion=4.1.13-boot2docker, operatingsystem=Boot2Docker 1.9.1 (TCL 6.4.1); master : cef800b - Fri Nov 20 19:33:59 UTC 2015, provider=virtualbox, storagedriver=aufs
> CPUs: 2
> Total Memory: 2.043 GiB
> Name: 163ab9debf50

## on machine 2:

    machine2 $> docker-machine create -d virtualbox --swarm --swarm-discovery="consul://<MACHINE1 IP>:8500" --engine-opt="cluster-store=consul://<MACHINE1 IP>:8500" --engine-opt="cluster-advertise=eth0:2376" worker2

> Running pre-create checks...
> Creating machine...
> (worker2) Creating VirtualBox VM...
> (worker2) Creating SSH key...
> (worker2) Starting VM...
> Waiting for machine to be running, this may take a few minutes...
> Machine is running, waiting for SSH to be available...
> Detecting operating system of created instance...
> Detecting the provisioner...
> Provisioning with boot2docker...
> Copying certs to the local machine directory...
> Copying certs to the remote machine...
> Setting Docker configuration on the remote daemon...
> Configuring swarm...
> Checking connection to Docker...
> Docker is up and running!
> To see how to connect Docker to this machine, run: docker-machine env worker2

## Then, back to machine1:

    machine1 $> eval $(docker-machine env --swarm mhs-demo0)
    machine1 $> docker info

> Containers: 5
> Images: 5
> Role: primary
> Strategy: spread
> Filters: health, port, dependency, affinity, constraint
> Nodes: 3
>  mhs-demo0: 192.168.99.108:2376
>   └ Status: Healthy
>   └ Containers: 2
>   └ Reserved CPUs: 0 / 1
>   └ Reserved Memory: 0 B / 1.021 GiB
>   └ Labels: executiondriver=native-0.2, kernelversion=4.1.13-boot2docker, operatingsystem=Boot2Docker 1.9.1 (TCL 6.4.1); master : cef800b - Fri Nov 20 19:33:59 UTC 2015, provider=virtualbox, storagedriver=aufs
>  mlovci: 192.168.99.100:2376
>   └ Status: Healthy
>   └ Containers: 2
>   └ Reserved CPUs: 0 / 4
>   └ Reserved Memory: 0 B / 9.99 GiB
>   └ Labels: executiondriver=native-0.2, kernelversion=4.1.13-boot2docker,  operatingsystem=Boot2Docker 1.9.1 (TCL 6.4.1); master : cef800b - Fri Nov 20 19:33:59 UTC 2015, provider=virtualbox, storagedriver=aufs
>  worker1: 192.168.99.109:2376
>   └ Status: Healthy
>   └ Containers: 1
>   └ Reserved CPUs: 0 / 1
>   └ Reserved Memory: 0 B / 1.021 GiB
>   └ Labels: executiondriver=native-0.2, kernelversion=4.1.13-boot2docker, operatingsystem=Boot2Docker 1.9.1 (TCL 6.4.1); master : cef800b - Fri Nov 20 19:33:59 UTC 2015, provider=virtualbox, storagedriver=aufs
> CPUs: 6
> Total Memory: 12.03 GiB
> Name: 163ab9debf50

The trouble is that 192.168.99.100:2376 refers to another VM running on machine1 that I never added to the swarm. I suspect this is because worker2 has the IP 192.168.99.100:2376 on machine2 and reports this to consul. 

How do I connect a worker VM running on machine2 to the master VM running on machine1?

**Comment by nathanleclaire** [comment]
I don't actually understand the expected vs. actual result here.  Please point this out and re-open if still interested.  Thanks!
