### ISSUE TITLE
hyperv driver should be more explicit when the vswitch is not created

### ISSUE THREAD

**Issue by jeanlaurent** [docker/machine#2995]
We should output a link to the documentation explaning how it works.

**Comment by Oliboy50** [comment]
You mean, when the user haven't create any Virtual Switch / or / when the Virtual Switch used does not have access to Internet ?

I didn't try the first case.

But in the second case, the `docker-machine` provisioning get stuck at 

```
Waiting for host to start
```

So yes, it should be more explicit :+1:

**Comment by jeanlaurent** [comment]
I meant the first case. 

I suggest you submit a specific issue for your case, so we can track it more efficiently.
