### ISSUE TITLE
--engine-install-url not support with vmwarefusion

### ISSUE THREAD

**Issue by alvinr** [docker/machine#2996]
# Problem

I want to use a specific Boot2Docker ISO and a specific Docker Engine, so I would do the following

```
docker-machine create -d vmwarefusion --engine-install-url=https://get.docker.com/builds/Linux/x86_64/docker-1.10.0-rc1 --vmwarefusion-boot2docker-url=https://github.com/tianon/boot2docker-legacy/releases/download/v1.10.0-rc1/boot2docker.iso dev
```

in 1.10.0-rc1 (and prior) this works fine.
```
docker-machine version 0.6.0-rc1, build 174e390
```

However, in 1.10.0 you get the following

```
Error setting machine configuration from flags provided: --engine-install-url cannot be used with the vmwarefusion driver, use --vmwarefusion-boot2docker-url instead

docker-machine version 0.6.0, build e27fb87
```

It appears that this is a regression since 1.10.0-rc1

# Environment
```
uname -a
Darwin vero-3.citrusleaf.local 15.3.0 Darwin Kernel Version 15.3.0: Thu Dec 10 18:40:58 PST 2015; root:xnu-3248.30.4~1/RELEASE_X86_64 x86_64
```

**Comment by nathanleclaire** [comment]
I think you want `--vmwarefusion-boot2docker-url`.  In local VMs so far we have mostly just provided capability for specifying custom ISOs (usually boot2docker).

**Comment by alvinr** [comment]
So my intent is to
- pull a specific boot2docker iso
- pull a specific docker machine version

In 1.10.0-rc1 and prior this seemed possible - but not now

-Alvin

**Comment by nathanleclaire** [comment]
Yes, we added a check to bail if `--engine-install-url` was used with boot2docker-based VMs.  So, you can simply drop the `--engine-install-url`, and it should work.

**Comment by nathanleclaire** [comment]
LMK if we can close -- thanks Alvin

**Comment by jeanlaurent** [comment]
Closing for now, feel free to re-open if needed.
