### ISSUE TITLE
hyperv driver should be more explicit when the vswitch used can't reach Internet

### ISSUE THREAD

**Issue by Oliboy50** [docker/machine#2997]
As said in #2995, the docker-machine provisioning get stuck at

```
Waiting for host to start...
```

When the Virtual Switch used with the Hyper-V machine does not have a proper Internet connection.

And the machine IP cannot be found, if we try to do `docker-machine ls`.

We should output a link to the documentation explaining how it works. 
Personnally, this link (from the docker documentation) https://www.packet6.com/allowing-windows-8-1-hyper-v-vm-to-work-with-wifi/ helped me, because I'm always using WiFi not Ethernet.

**Comment by nathanleclaire** [comment]
Thanks @Oliboy50, please submit a followup PR to add this information if desired.
