### ISSUE TITLE
Ubuntu(upstart) provisioner does not use Docker apt repos?

### ISSUE THREAD

**Issue by ahmetalpbalkan** [docker/machine#2999]
After Docker 1.10 is released I went into my docker-machine VM running Ubuntu 14.04.3 I created the other day and I did an `apt-get update && apt-get upgrade` and I was still on Docker 1.9.

Then I realized machine was not configured to use the `apt.dockerproject.org` repos at all.  Is this normal? I'm running from tip of master.

**Comment by nathanleclaire** [comment]
How old is it?  If it was created with a slightly older version of Docker, the package names may have changed.  If that's the case, I suggest upgrading using `docker-machine upgrade`, or nuking the packages and re-installing yourself.

**Comment by nathanleclaire** [comment]
> Then I realized machine was not configured to use the apt.dockerproject.org repos at all. Is this normal? I'm running from tip of master.

We use the `get.docker.com` script, so if it's not set that way, it's the result of something funny that script did at the time of `create`.

**Comment by ahmetalpbalkan** [comment]
Hmm I was bascially at commit 36aed62 (9 days ago). I forgot to mention, `docker-machine upgrade` from outside did not work either. I was still seeing the same version. Therefore I had to add the apt repo manually.

Now I can't repro this, weird.

**Comment by nathanleclaire** [comment]
Thanks for following up to close Ahmet.  Let us know if any issues persist.
