### ISSUE TITLE
0.6.0 upgrade issue - Error with pre-create check

### ISSUE THREAD

**Issue by jmreicha** [docker/machine#3008]
Here is the full output of the error.

```
Running pre-create checks...
Error with pre-create check: "VirtualBox is configured with multiple host-only adapters with the same IP \"192.168.99.1\". Please remove one."
```

Here is the command I am using to create the VM.

`docker-machine create -d virtualbox --virtualbox-cpu-count 2 dev`

I was playing around around with network interfaces prior to this to test network performance but a) I disabled the interfaces after I was done testing and b) this is attempting to bring up a new VM.

Any ideas?

**Comment by nathanleclaire** [comment]
Did you remove one of the host only interfaces with duplicate IPs?  It should be fairly straightforward to do so through the VirtualBox GUI.

**Comment by jmreicha** [comment]
@nathanleclaire Yeah, I got tripped up a little bit but I was able to use [this post](http://superuser.com/questions/854369/how-do-i-remove-a-virtualbox-host-only-network-adapter) to remove stale hostonly nics.  After I removed the old nics everything started working again.

Thanks.

**Comment by nathanleclaire** [comment]
Awesome glad it worked out.  Thanks for the isuse.

**Comment by luebken** [comment]
I'm getting the same error. Even after deleting all Virtualbox VMs: 
```
$ VBoxManage list vms

$ docker-machine create --driver virtualbox default
Running pre-create checks...
Error with pre-create check: "VirtualBox is configured with multiple host-only adapters with the same IP \"192.168.59.3\". Please remove one."
```
Any pointers?

**Comment by jmreicha** [comment]
@luebken Did you try the link in my post above?   I also needed to remove the vboxnet NIC.

**Comment by luebken** [comment]
Yes.`VBoxManage hostonlyif remove vboxnetX` worked. Thanks. I thought removing the VMs would do the trick.

**Comment by gianpaj** [comment]
For anybody in a similar situation. I upgraded docker toolbox on Mac (`DockerToolbox-1.11.1b`) and I had the same issue starting the VM with Kitematic. I had to remove 5 host-only interfaces:
```
VBoxManage hostonlyif remove vboxnet9
VBoxManage hostonlyif remove vboxnet8
VBoxManage hostonlyif remove vboxnet7
VBoxManage hostonlyif remove vboxnet6
VBoxManage hostonlyif remove vboxnet5
```
