### ISSUE TITLE
PSA: Upgrade from docker-machine 0.5.3 to 0.6.0 broke vmwarevsphere plugin for existing machines

### ISSUE THREAD

**Issue by ljrittle** [docker/machine#3024]
$ docker-machine version
    docker-machine version 0.5.3, build 4d39a66
    $ docker-machine ls
    NAME                    ACTIVE   DRIVER          STATE     URL                       SWARM                DOCKER    ERRORS
    arc-dev-00              *        vmwarevsphere   Running   tcp://10.26.67.187:2376                        v1.9.0    
    [...]

Upgrade to docker-machine-0.6.0.

    $ docker-machine version
    docker-machine version 0.6.0, build e27fb87
    $ NAME                    ACTIVE   DRIVER          STATE     URL                         SWARM                DOCKER    ERRORS
    arc-dev-00              -        vmwarevsphere   Error                                                      Unknown   
    [...]

Here is what I see with `status` post upgrade:

    $ docker-machine status arc-dev-00
    error getting state for host arc-dev-00: Post https://10.26.66.118:0/sdk: dial tcp 10.26.66.118:0: connect: can't assign requested address
    Error

I am looking into how to manually touch the existing e.g. `.docker/machine/machines/arc-dev-00/config.json` to fix this without manually removing and recreating the machine.  I will report the workaround if/when I find it.

**Comment by nathanleclaire** [comment]
cc @frapposelli

**Comment by frapposelli** [comment]
@ljrittle your problem seems to be related to the vCenter port (shown as `0` in the failed command).

@nathanleclaire was there any particular change in `v0.6.0` related to provider configuration?

**Comment by nathanleclaire** [comment]
> @nathanleclaire was there any particular change in v0.6.0 related to provider configuration?

Hm, I'm not sure exactly what you mean.  There were no config migrations and the host loading => plugin mechanic has been largely unchanged since the 0.5.* series of releases.

**Comment by frapposelli** [comment]
@nathanleclaire that's what I've thought, I've tried to reproduce this issue to no avail.

@ljrittle do you have repro steps for this?

**Comment by nathanleclaire** [comment]
Please post a minimally reproducible example on a new ticket if this problem is still occurring.  Thanks!
