### ISSUE TITLE
$ENGINE_REGISTRY_MIRROR environment variable?

### ISSUE THREAD

**Issue by davemkirk** [docker/machine#3025]
`docker-machine create` currently accepts the option flag `--engine-registry-mirror` to specify the registry mirrors to use.

I'd like to be able to use an environment variable to set this flag's default value in the same way that `$MACHINE_DOCKER_INSTALL_URL` sets `--engine-install-url` 

Thoughts?

**Comment by jeanlaurent** [comment]
Thats definitely something we could do. Can you tell us a bit more about your use case, for wanting a env variable for that. Are those registry mirrors permanent ?

**Comment by davemkirk** [comment]
I run a local registry mirror to minimize downloading the same images over and over. The flag works for me but became a hassle when trying to share some simple scripts with others who don't have the same mirror setup. I guess I could just change my scripts to take mirrors as an option but it sure would be convenient if docker-machine just picked up the environment variable :-)

**Comment by dweomer** [comment]
It would be nice if the two different --engine-* with envvar defaults were named similarly. The `ENGINE_` pattern seems more consistent with other envvars than the `MACHINE_DOCKER_` pattern.
