### ISSUE TITLE
Machine Overview has a bad link on the page

### ISSUE THREAD

**Issue by moxiegirl** [docker/machine#3028]
https://docs.docker.com/machine/overview/

Provision a Docker Swarm cluster with Docker Machine
Goes to: https://docs.docker.com/swarm/machine-provisioning/provision-w-machine/  -> 404

**Comment by nathanleclaire** [comment]
Oof, turned in https://github.com/docker/machine/pull/3030 to fix it -- looks like @londoncalling's is a bit more comprehensive in terms of fixing links so we can use that instead

**Comment by nathanleclaire** [comment]
Should be fixed by #2998
