### ISSUE TITLE
certs after create in wrong path

### ISSUE THREAD

**Issue by jseaidou** [docker/machine#3031]
after running
```
docker-machine create --driver virtualbox default
```
I see in my local machine (OSX) the certs in $HOME/.docker/machine/machines/certs
however according to this issue: https://github.com/docker/machine/issues/705 it should be in 
```
$HOME/.docker/machine/<machine>/
```
but I find them in 
```
$HOME/.docker/
```

**Comment by jeanlaurent** [comment]
What's your `docker-machine version` ?

**Comment by jseaidou** [comment]
``docker-machine version
docker-machine version 0.5.6, build 61388e9```

**Comment by jeanlaurent** [comment]
Some certs directory should be in `~/.docker/machine/certs`  and the other specific to your default machine in `~/.docker/machine/certs/default`

Do you have these directory and some .pem inside them ?

What are the certs file you see at the root of `~/.docker/` ?

**Comment by jseaidou** [comment]
docker@default:~$ ll .docker/
total 12
-rw-r--r--    1 docker   staff         1038 Feb 11 05:24 ca.pem
-rw-r--r--    1 docker   staff         1070 Feb 11 05:24 cert.pem
-rw-------    1 docker   staff         1675 Feb 11 05:24 key.pem

**Comment by jeanlaurent** [comment]
That's the expected behavior.

On the host pem files are in `~/.docker/machine/certs/default`
On the 'remote' machine there are indeed in `~/.docker/`

**Comment by jseaidou** [comment]
Perfect, thanks for clarifiying!
