### ISSUE TITLE
Understanding disk size 

### ISSUE THREAD

**Issue by AlexZeitler** [docker/machine#3036]
I'm running Docker Machine 0.6.0 on Ubuntu 14.04 LTS.

I created a machine ```default``` with no changes to settings like disk size.

Thus, ```docker-machine inspect default | grep DiskSize``` returns: ``` "DiskSize": 20000```.

If I ssh into the machine using ```docker-machine ssh default```, I do a ```df -h``` which results in:

```
Filesystem                Size      Used Available Use% Mounted on
tmpfs                   896.6M    129.4M    767.2M  14% /
tmpfs                   498.1M         0    498.1M   0% /dev/shm
/dev/sda1                18.2G     16.9G    339.2M  98% /mnt/sda1
cgroup                  498.1M         0    498.1M   0% /sys/fs/cgroup
/dev/sda1                18.2G     16.9G    339.2M  98% /mnt/sda1/var/lib/docker/aufs
```

Back an the host, when I goto ```~/.docker/machine/machines/default```, ```ls disk.vmdk```, I get back this:

```
-rw------- 1 alexzeitler alexzeitler 2.8G Feb 11 13:52 disk.vmdk
```

The problem here is as follows:
Even if I try to run a MongoDb container with the ```--smallfiles``` flag like this ```docker run -d --name mongo -p 27017:27017 mongo:2.6.11 --smallfiles```, I get this error:

```
2016-02-11T12:53:56.339+0000 [initandlisten] options: { storage: { smallFiles: true } }
2016-02-11T12:53:56.343+0000 [initandlisten] journal dir=/data/db/journal
2016-02-11T12:53:56.343+0000 [initandlisten] recover : no journal files present, no recovery needed
2016-02-11T12:53:56.343+0000 [initandlisten] 
2016-02-11T12:53:56.343+0000 [initandlisten] ERROR: Insufficient free space for journal files
2016-02-11T12:53:56.343+0000 [initandlisten] Please make at least 422MB available in /data/db/journal or use --smallfiles
2016-02-11T12:53:56.343+0000 [initandlisten] 
2016-02-11T12:53:56.347+0000 [initandlisten] exception in initAndListen: 15926 Insufficient free space for journals, terminating
```

My question now is: Why is ```disk.vmdk``` showing only a size of ```2.8G``` and ```df -h``` inside the machine shows ```16.9G``` used?

**Comment by jeanlaurent** [comment]
You're running docker-machine host inside virtualbox on a Ubuntu host ?

**Comment by jeanlaurent** [comment]
vmdk files are compressed anyway so this will not reflect the size of the actual disk space from within the container. One reason could be that you imported a lot of data inside your mongo container.

Anyway you would probably want to increase the default size of your machine with the `--virtualbox-disk-size` in mb.

**Comment by AlexZeitler** [comment]
@jeanlaurent Yes, the host is Ubuntu (which runs inside VMware Workstation on Windows), the machine is a Virtualbox machine.

The MongoDb container did not contain any data and has been created right before the error occurred.

But if disks get compressed, the disk of the machine might have full indeed.

Thanks for explanation.
