### ISSUE TITLE
Docker-machine rm cannot remove a VM in state:saved

### ISSUE THREAD

**Issue by chrisdopuch** [docker/machine#3043]
Docker-machine rm subcommand cannot remove a container that is in a saved state. The container must be started using `docker-machine start` before you can delete it. 
Using:
`OSX Yosemite 10.10.5`
`docker-machine version 0.5.6, build 61388e9`
`Docker version 1.9.1, build a34a1d5`

Example:
```
$ docker-machine ls
NAME    ACTIVE   URL          STATE   URL   SWARM   DOCKER    ERRORS
an-vm   -        virtualbox   Saved                 Unknown

$ docker-machine rm an-vm
About to remove an-vm
Are you sure? (y/n): y
Error removing host "an-vm": /usr/local/bin/VBoxManage controlvm an-vm poweroff failed:
VBoxManage: error: Machine 'an-vm' is not currently running

### Have to start the machine to rm it
$ docker-machine start an-vm
Starting "an-vm"...
(an-vm) Waiting for an IP...
Machine "an-vm" was started.
Started machines may have new IP addresses. You may need to re-run the `docker-machine env` command.

$ docker-machine rm an-vm
About to remove an-vm
Are you sure? (y/n): y
Successfully removed an-vm
```

I'm fairly sure it is possible to delete a virtualbox VM that has been suspended and is in a saved state, so `docker-machine rm` should be able to do this. 

If that's not the desired behavior for `docker-machine rm`, then I would instead propose that the documentation be updated to reflect that machines must be in a running state in order to be deleted with `docker-machine rm`
(I know the examples have running vms, but they do not make it explicit that the machines _must_ be running)
https://docs.docker.com/machine/reference/rm/

**Comment by dgageot** [comment]
This is fixed in 0.6.0
