### ISSUE TITLE
Docker-machine env in Powershell includes the full path to docker-machine.exe

### ISSUE THREAD

**Issue by SteveLasker** [docker/machine#3044]
On Mac, and on Windows in cmd, docker-machine isn't specified by it's full path.
However, using 1.10, when calling docker-machine from a powershell prompt, the fully qualified path is included

```
PS C:\Users\SteveLas> docker-machine env default
$Env:DOCKER_TLS_VERIFY = "1"
$Env:DOCKER_HOST = "tcp://192.168.99.100:2376"
$Env:DOCKER_CERT_PATH = "C:\Users\SteveLas\.docker\machine\machines\default"
$Env:DOCKER_MACHINE_NAME = "default"
# Run this command to configure your shell:
# & "C:\Program Files\Docker Toolbox\docker-machine.exe" env default | Invoke-Expression
PS C:\Users\SteveLas>

```

**Comment by dgageot** [comment]
@SteveLasker we use the name of the binary as it is on the command line. I guess Powershell always expands the binary to its full path.

We could keep only the base name but then it would break for people having multiple docker-machine` binaries in their path.

**Comment by jeanlaurent** [comment]
On MacOSX, if the binary is in the `$PATH` only the binary name is passed along.

If the binary is not in the `$PATH`, we get the full path to the binary.
On Windows we always get the full path to the binary on this is a powershell or cmd.exe.

There is no reliable way of determining wether the full path of the binary is available in the `%PATH%`.

One thing we can do, is always return the full path to the binary, but it's actually a bit less intuitive than the current behavior.

Closing for now, feel free to re-open with a solution to determine on windows if a binary is the 1st in the `%PATH%`.
