### ISSUE TITLE
the makefile is very strict about where godep has to be

### ISSUE THREAD

**Issue by vikstrous** [docker/machine#3049]
The AUR package for docker machine is failing to install for me because the docker machine makefile looks for godep at `GODEP_BIN := $(GOPATH)/bin/godep` but I have it installed elsewhere, still in my path. This happens at https://github.com/docker/machine/blob/7f2e3c1d19ceabaa369ab149882985b2488143f4/mk/main.mk#L15

The makefile should be okay with any godep found in $PATH regardless of where it is.

**Comment by dmp42** [comment]
The AUR package is bonkers.
There is no need for godep when building.

Removing lines 31 & 32 of that should fix it.

https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=docker-machine

Agreed the makefile *may* be more tolerant with godep location though.

Once we move to go 1.6 this will no longer be a concern though.

**Comment by dgageot** [comment]
@vikstrous Clearly, the AUR package is wrong. `godep` is not used by `make build`
@dmp42 a vendoring tool is still needed with go 1.6. So `godep` is here to stay. Right?
I'd rather leave the Makefile as is and close the ticket. @vikstrous wdyt?

**Comment by dmp42** [comment]
@dgageot godep is here to stay, but there will no longer be a need for godep specific tasks in the makefile itself (exit GO15VENDOREXPERIMENT)

**Comment by nathanleclaire** [comment]
Downstream packaging problem, nothing that we can do about it at the moment.
