### ISSUE TITLE
docker-machine ls: Timeout error when instance has been stopped

### ISSUE THREAD

**Issue by janeczku** [docker/machine#3056]
> $ docker-machine ls

```
NAME              ACTIVE   DRIVER       STATE     URL                        SWARM   DOCKER    ERRORS
node01            -        openstack    Running   tcp://92.XXX.XXX.204:2376           v1.9.1
```

> $ docker-machine stop node01

```
Stopping "node01"...
Machine "node01" was stopped.
```

> $ docker-machine ls

```
NAME              ACTIVE   DRIVER       STATE     URL                        SWARM   DOCKER    ERRORS
node01            -        openstack    Timeout  
```

This is obviously doomed to fail, with commit 670c4808ed8abdc80d4a71444b10df5360bed62b assuming incorrectly that when the driver returns the URL it means that the machine is running.

https://github.com/docker/machine/blob/master/commands/ls.go#L343-L347

/cc @dgageot 

**Version Info:**
docker-machine version 0.6.0, build e27fb87

**Comment by dgageot** [comment]
@janeczku The (implicit?) contract with `GetUrl()` is that it should return the url only if the machine is running. I'll take a look at fixing `GetUrl()` in the openstack driver.

**Comment by janeczku** [comment]
Hi @dgageot, are you sure? I haven't seen any driver that behaves the way you described it. They all construct the URL from the IP address, so the only implicit requirement to return an URL is that the machine has an IP address.  E.g.: https://github.com/docker/machine/blob/master/drivers/digitalocean/digitalocean.go#L257-L258

**Comment by dgageot** [comment]
@janeczku Yes, I'm sure ;-) `GetIP` often checks for the VM state or implicitly fails if the VM is not running since it gets an IP only if it's running

**Comment by janeczku** [comment]
I beg to differ:
https://github.com/docker/machine/blob/master/libmachine/drivers/base.go#L38-L44

Nothing being checked here. It just returns the IP from the JSON store.

**Comment by dgageot** [comment]
@janeczku Let me be clearer: every driver that relies on the default implementation of `GetIP` and/or returns an IP without checking that the VM is running is flawed. If it needs to be fixed then it needs to fixed. All local VM drivers behave OK. Some cloud drivers are OK. Some are not OK.

**Comment by janeczku** [comment]
> Let me be clearer: every driver that relies on the default implementation of GetIP and/or returns an IP without checking that the VM is running is flawed.

Thanks. Now we are talking :smile:

**Comment by janeczku** [comment]
Here is the list of drivers that according to @dgageot are flawed in that they return the machine IP and/or URL without checking that the machine is actually running (Hint: All the the cloud drivers):

https://github.com/docker/machine/blob/master/drivers/vmwarevcloudair/vcloudair.go
https://github.com/docker/machine/blob/master/drivers/azure/azure.go
https://github.com/docker/machine/blob/master/drivers/amazonec2/amazonec2.go
https://github.com/docker/machine/blob/master/drivers/digitalocean/digitalocean.go
https://github.com/docker/machine/blob/master/drivers/exoscale/exoscale.go
https://github.com/docker/machine/blob/master/drivers/google/google.go
https://github.com/docker/machine/blob/master/drivers/hyperv/hyperv.go
https://github.com/docker/machine/blob/master/drivers/openstack/openstack.go
https://github.com/docker/machine/blob/master/drivers/rackspace/rackspace.go
https://github.com/docker/machine/blob/master/drivers/softlayer/driver.go

Stopped machines using these drivers will cause  `docker-machine ls` to take around 10 seconds to complete and display a timeout error.

**Comment by dgageot** [comment]
@janeczku Thanks for the inventory. I worked on it yesterday and will create a PR soon. Some of the drivers you listed are not flawed. Here's the list of drivers that have to be fixed:

https://github.com/docker/machine/blob/master/drivers/amazonec2/amazonec2.go
https://github.com/docker/machine/blob/master/drivers/azure/azure.go
https://github.com/docker/machine/blob/master/drivers/digitalocean/digitalocean.go
https://github.com/docker/machine/blob/master/drivers/exoscale/exoscale.go
https://github.com/docker/machine/blob/master/drivers/openstack/openstack.go
https://github.com/docker/machine/blob/master/drivers/softlayer/driver.go
https://github.com/docker/machine/blob/master/drivers/vmwarevcloudair/vcloudair.go

**Comment by dgageot** [comment]
Related to https://github.com/docker/machine/pull/1296

**Comment by janeczku** [comment]
:+1: Great
