### ISSUE TITLE
MissingRegion: could not find region configuration on EC2 instances.

### ISSUE THREAD

**Issue by sjwhyte** [docker/machine#3061]
Upgraded to docker toolbox 1.10.1 (machine 0.6.0) and when listing machines on aws get MissingRegion: could not find region configuration

**Comment by jeanlaurent** [comment]
Hi @sjwhyte, could you paste the full logs ? eventually in debug mode.

**Comment by sjwhyte** [comment]
@jeanlaurent I have fixed this on my machine, I will have to do the upgrade to 0.6.0 on another machine to see if the upgrade caused the issue. What happened was the config.json for my aws instances were changed and the aws keys, region and other aws attributes were empty, I was not sure if the upgrade sis this or something else. I copied the config.json.bak that were there back to config.json and it started working.

**Comment by nathanleclaire** [comment]
@sjwhyte Please re-try with 0.7.0 and re-open if the issue persists.  Thanks
