### ISSUE TITLE
Attach Websocket via Remote API into Container: Error during WebSocket handshake: net::ERR_CONNECTION_CLOSED

### ISSUE THREAD

**Issue by rteusner** [docker/machine#3071]
When trying to open a Websocket connection into one of my running docker containers being on a docker-machine based docker-daemon (running on 192.168.99.100:2376), I always get the following error:

`WebSocket connection to 'ws://192.168.99.100:2376/containers/2ad4e2e42345/attach/ws?logs=1&stderr=1&stdout=1&stream=1&stdin=1' failed: Error during WebSocket handshake: net::ERR_CONNECTION_CLOSED`

I open the connection using the remote API via Javascript:

websocket = new WebSocket("ws://192.168.99.100:2376/containers/2ad4e2e42345/attach/ws?logs=1&stderr=1&stdout=1&stream=1&stdin=1");

When trying to connect to a container running on a daemon in my own ubuntu virtualbox (for example on another ip, 192.168.59.104), the connection succeeds.

My environment infos for the VM running the containers are:
```
user@rteusner ~: docker-machine env default
export DOCKER_TLS_VERIFY="1"
export DOCKER_HOST="tcp://192.168.99.100:2376"
export DOCKER_CERT_PATH="/Users/user/.docker/machine/machines/default"
export DOCKER_MACHINE_NAME="default"

```

I already had a look at (possible) CORS options inside the boot2docker image used by docker-machine, but did not yet find the cause of this.

Any help or additional directions are greatly appreciated, since I am helplessly trying out things since 3 days by now.

__

docker version:
Client:
 Version:      1.8.1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   d12ea79
 Built:        Thu Aug 13 02:49:29 UTC 2015
 OS/Arch:      darwin/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   a34a1d5
 Built:        Fri Nov 20 17:56:04 UTC 2015
 OS/Arch:      linux/amd64

docker info:

Containers: 20
Images: 33
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 73
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.1.13-boot2docker
Operating System: Boot2Docker 1.9.1 (TCL 6.4.1); master : cef800b - Fri Nov 20 19:33:59 UTC 2015
CPUs: 1
Total Memory: 996.2 MiB
Name: default
ID: QC3Z:U7B7:CQZO:LVYJ:BKPL:5NX5:P47V:A7NG:LN6C:RITX:4CFM:UI4U
Debug mode (server): true
File Descriptors: 13
Goroutines: 18
System Time: 2016-02-17T14:40:37.1379515Z
EventsListeners: 0
Init SHA1: 
Init Path: /usr/local/bin/docker
Docker Root Dir: /mnt/sda1/var/lib/docker
Labels:
 provider=virtualbox

uname -a:
Darwin rteusner.local 15.3.0 Darwin Kernel Version 15.3.0: Thu Dec 10 18:40:58 PST 2015; root:xnu-3248.30.4~1/RELEASE_X86_64 x86_64

Environment details (AWS, VirtualBox, physical, etc.):
via docker-machine on OSX.

How reproducible:
Always.

Steps to Reproduce:
See above. Run the code, see the described error.

**Comment by nathanleclaire** [comment]
Unless I'm missing someting, you can't get a Websocket connection to the Docker daemon.  It's a HTTP API exposed over TCP that sometimes hijacks the connection and drops down to a lower level.
