### ISSUE TITLE
Docker Machine does not preserve manual DHCP settings in VirtualBox

### ISSUE THREAD

**Issue by oiavorskyi** [docker/machine#3077]
When `docker-machine` creates new VM using VirtualBox or starts existing one it validates that there is VirtualBox DHCP server with precise parameters on the target interface. When it cannot find it or identifies discrepancy in the parameters it forces creation/modification of the DHCP server. Thus manual changes to the DHCP settings get overwritten every time.

While in many scenarios this is a proper behavior that helps to ensure that the VM will get its IP address it could be very limiting. In my use case I want to use dedicated DHCP server on my Mac host (`dnsmasq`) to ensure that all new or existing VMs register in the local DNS. I'm creating and removing bunch of VMs often as part of a testing of the docker cluster on my local machine and being able to refer to the VM's by their DNS name is important. There is, of course, workaround. I could manually add entries in my hosts file every time I setup a cluster but this quickly becomes a maintenance issue.

In my opinion there should be ability to specify to the docker machine that it should bypass validation/creation of the DHCP server. I don't say that it should change the default behavior but having an option to change it in case-by-case basis is very beneficial. Preferably this should be based on the environment variable rather than switch to the `docker-machine` command as adding it to every `start` command will become a burden.

**Comment by nathanleclaire** [comment]
Please submit a detailed proposal for the flags / options you'd like to see if you want to pursue this further.  Thanks!
