### ISSUE TITLE
'docker-machine upgrade <env-name>' not upgrdaing amazonec2 v1.9.1 to  v1.10.1

### ISSUE THREAD

**Issue by nicklucking** [docker/machine#3079]
I upgrade docker-machine to 6.0 and now I can't connect to some remote docker-machine instances that are on Ubuntu 14 hosted on amazonec2. I can't run docker commands on them because they are  v1.9.1. and i get an error that says: 

Error response from daemon: client is newer than server (client API version: 1.22, server API version: 1.21)

Running 'docker-machine upgrade <env-name>' goes through upgrade process, but docker versions remains  v1.9.1. It should upgrade to v1.10.1.

**Comment by theotheo** [comment]
I've faced with same problem. I would  appreciate any ideas.

**Comment by sebmoule** [comment]
same problem with openstack driver.. any idea to solve the problem ?

**Comment by mateeyow** [comment]
Facing same problem with digitalocean driver

**Comment by nathanleclaire** [comment]
Hi all, thanks for reporting, please see https://github.com/docker/machine/issues/3308#issuecomment-210181219
