### ISSUE TITLE
boot2docker.iso auto upgrade should be constrained to same docker major version

### ISSUE THREAD

**Issue by batsatt** [docker/machine#3084]
The recent https://github.com/docker/machine/pull/2298 change causes a Docker version upgrade if you have an older version, e.g. 1.9.x to 1.10.x. 

Setting aside the fact that this changes only _one_ part of the toolbox, it caused breakage: Docker 1.10.x requires an upgrade of Artifactory to version 4.4.3. In our case, that upgrade is out of our control, so we've been forced to hack around this auto upgrade behavior:

```
docker-machine create --driver virtualbox --virtualbox-boot2docker-url=file://${HOME}/.docker/machine/cache/boot2docker.iso
```

Auto upgrade of the iso should be done only if the newer iso uses the same major version of Docker.

**Comment by nathanleclaire** [comment]
Hi @batsatt, thanks for the issue.  I feel strongly that the upgrade should always upgrade to the latest released version of Docker.  For instance, 1.10.1 contains some fixes which are critical for Docker networking.  As you noted, it's possible to workaround if you need a different version, so I feel we are good with the current behavior.

**Comment by batsatt** [comment]
I understand the idea, but... does it strike you as correct that executing `docker --version` from outside vs. inside the VM will return  _different_ results?

It is not only odd to have the toolbox partially upgraded, it has caused significant disruption on my team in this case. Yes, I found the workaround, but reverting everywhere was a royal pain.

Maybe there is a better solution than the one I proposed, but **silently** changing one part of an install just seems wrong.

**Comment by hminaya** [comment]
Outside the VM is the docker version for you local machine. Inside the VM is the docker version for the host which contains all of the containers.

Those two versions are independent of one another. You can have multiple developers connecting to the same docker host, and all of them are using different versions.

**Comment by nathanleclaire** [comment]
As @hminaya said, it's not unexpected behavior in terms of the current client / server model.  I agree it's definitely a Docker "gotcha", but something the Machine team can't really do anything about today.

>Maybe there is a better solution than the one I proposed, but silently changing one part of an install just seems wrong.

Both will be upgraded if Toolbox is used to do the upgrade, which is the recommended method.

**Comment by politician** [comment]
CoreOS stable is shipping docker v1.9.1.  We need to be able to develop locally against v1.9.1.  Is there an option to prevent `docker-machine create` from checking for an update?

**Comment by nathanleclaire** [comment]
@politician My suggestion in that case is to use `--virtualbox-boot2docker-url`.

```console
$ docker-machine create -d virtualbox \
    --virtualbox-boot2docker-url https://github.com/boot2docker/boot2docker/releases/download/v1.9.1/boot2docker.iso \
    oldversion
```

**Comment by politician** [comment]
Thanks @nathanleclaire, I'll update our docs. We ended up doing something significantly less elegant.
