### ISSUE TITLE
Create fails on digitalocean with custom image

### ISSUE THREAD

**Issue by jalleyne** [docker/machine#3086]
Description of problem:
Cannot create machine with custom digitalocean image/ snapshot.

`docker version`: Docker version 1.10.1, build 9e83765

`docker info`: cannot output, no machine created.

`uname -a`: Darwin shadow 15.3.0 Darwin Kernel Version 15.3.0: Thu Dec 10 18:40:58 PST 2015; root:xnu-3248.30.4~1/RELEASE_X86_64 x86_64

Environment details (AWS, VirtualBox, physical, etc.): DigitalOcean

How reproducible:
Consistent.

Steps to Reproduce:
1. Create a custom image with packer. `packer build do-image.json`
2. Attempt to use the image name as slug 
```
docker-machine create \
  --driver digitalocean \
  --digitalocean-image "ubuntu-14-04-x64_docker_host-19-Feb-16_04-13" \
  --digitalocean-region "nyc2" \
  --digitalocean-size "1gb" \
  --digitalocean-private-networking \
  --digitalocean-ssh-user "root" \
  --digitalocean-ssh-port "22" \
  swarm-node-001
```

Actual Results:
Error creating machine: Error in driver during machine creation: POST https://api.digitalocean.com/v2/droplets: 422 You specified an invalid image for Droplet creation.

Expected Results:
Launch a machine droplet based on my custom image in digitalocean.

Additional info:
Looking into the docker-machine provider, at this line https://github.com/docker/machine/blob/master/drivers/digitalocean/digitalocean.go#L190 there would need to be accomodations for the slug or the id. Internalls `godo` already falls back to `id` if slug is empty. https://github.com/digitalocean/godo/blob/0293606a28f87fbe772c539620672f3d0ac707a2/droplets.go#L149

any other info i can pass along let me know.

**Comment by nathanleclaire** [comment]
> https://api.digitalocean.com/v2/droplets: 422 The image you specified is not available in the selected region, you can transfer it to this region from the images pages.

Just to be clear, you're 100% sure that the image actually _is_ in the region `nyc-3`?  Verified at the API level?

**Comment by jalleyne** [comment]
@nathanleclaire you were correct actually, the region was wrong. But the issue still exists! 

I've updated the initial comment with the correct details.

**Comment by jalleyne** [comment]
Closing this as more related to either packer or digital ocean api. Being able to use the "id" in --digitalocean-image is good enough.
