### ISSUE TITLE
Drop hardcoded port tcp/2376 from OpenStack driver

### ISSUE THREAD

**Issue by fsoppelsa** [docker/machine#3087]
I was reading https://github.com/docker/machine/issues/2820 and definitely this hardcode must be removed from **driver/openstack**:

https://github.com/docker/machine/blob/master/drivers/openstack/openstack.go#L291

Though, not clear yet from where to load the variable. It depends on Machine's roadmap.

**Comment by fsoppelsa** [comment]
@dgageot can you please add label OpenStack

**Comment by jeanlaurent** [comment]
Done

**Comment by nathanleclaire** [comment]
https://github.com/docker/machine/issues/3361
