### ISSUE TITLE
Multiple machines IP tossing that lead to certificate check errors

### ISSUE THREAD

**Issue by aleksandr-vin** [docker/machine#3093]
I have `default` and `jay` machines created in order.

After reboot I've tried to start the second one first. Felt on env set:

```
$ eval $(docker-machine env jay)
Error checking TLS connection: Error checking and/or regenerating the certs: There was an error validating certificates for host "192.168.99.100:2376": x509: certificate is valid for 192.168.99.101, not 192.168.99.100
You can attempt to regenerate them using 'docker-machine regenerate-certs [name]'.
Be advised that this will trigger a Docker daemon restart which will stop running containers.
```

Regeneration helps but it seems to be fixed other way.

**Comment by jeanlaurent** [comment]
Which driver are you using @aleksandr-vin ?

**Comment by nathanleclaire** [comment]
Current recommendation is to `regenerate-certs` as suggested when the IP address changes.  Please re-open if this does not fix the problem.
