### ISSUE TITLE
Machine can grab wrong IP for host-only network in VirtualBox

### ISSUE THREAD

**Issue by thieman** [docker/machine#3108]
We run Machine with VirtualBox to support our local development environments. Recently, we've been seeing a lot of networking failures with Machine 0.6.0 and VirtualBox 5.14. Basically, operations like `docker-machine regenerate-certs` will periodically be unable to connect to the VM and will time out. This problem has sometimes been solved by VM restarts, though it does not always fix itself on the first restart.

I believe I've tracked the bug down to this line in the VirtualBox driver:

https://github.com/docker/machine/blob/c40f9f7a215dd2cbc1bc31b0ace861a0e22b82f4/drivers/virtualbox/virtualbox.go#L666

This line is making an assumption that the host-only network will always be mounted as `eth1` inside the VM. It appears that this assumption does not (edit: always) hold. The NAT and host-only networks seem to get mounted semi-randomly as `eth0` and `eth1` inside our VMs. When the NAT network gets mounted on `eth1` instead of the host-only network, we see `docker-machine ip` returning the wrong IP (the 10.x NAT IP instead of the 192.x host-only IP) and commands reliant on that IP, such as `docker-machine regenerate-certs`, experience timeouts and failures. Restarting seems to sometimes re-assign the interfaces and allow subsequent commands to succeed.

I'm trying to get up to speed on how these interfaces get assigned and hopefully contribute a fix. I wanted to post this issue here in case anyone else is having this problem or could shed some light on the assumptions being made.

**Comment by thieman** [comment]
I think I know a bit more about why our users specifically are hitting the bug. If the user creates a machine and then never modifies any of its settings, I don't think the host-only interface should ever be anything other than `eth1`. However, we are changing settings.

After our Machines are originally created, we change the NAT network to use the PC-net FAST III adapter. `udev` seems to be reassigning the interfaces inside the VM on boot once this change is applied. This can cause our interfaces to shuffle around and that's how we're ending up with the host-only network on `eth0`.

This appears to be a bug that most people would not hit if they only run with the defaults and never tweak their VMs, but it's a bug nonetheless.

**Comment by thieman** [comment]
I couldn't find a way to reliably produce the failure condition, e.g. get the host-only interface on an adapter other than `eth1`. The ephemeral nature of TCL makes it so even editing the udev config isn't sufficient. It seems likely that there might be some sort of rare race condition that can cause the interfaces to get mounted in the wrong order.

**Comment by nathanleclaire** [comment]
Weird issue... @tianon FYI this funny business is going on inside of boot2docker... I'm not 100% sure why, but I'm game to workaround with the submitted patch in the interim.

**Comment by tianon** [comment]
Yuck, sounds like standard non-determinism (the kind of stuff those really annoying "deterministic interface names" was supposed to fix and actually just ended up making worse).  Doing some kind of dynamic detection makes sense here IMO. :+1:
