### ISSUE TITLE
Proposal: DRIVER environment variable

### ISSUE THREAD

**Issue by ahmetalpbalkan** [docker/machine#3113]
(Apologies if this has been discussed before.) What do folks think of having a `DRIVER` environment variable that serves as an alternative to `create -d/--driver` option?

**Comment by nathanleclaire** [comment]
I don't mind although arguably it should be called something like `MACHINE_DRIVER`.  In fact a lot of our integration tests right now have lines like `docker-machine create -d $DRIVER foo` (where `DRIVER` is specified at invocation) which could probably be simplified by this addition.

**Comment by ahmetalpbalkan** [comment]
Yeah that's where I saw it. I'll just leave this here until somebody picks up or I find some time to do it.

**Comment by daehyeok** [comment]
If nobody interesting in this. I want pick up.

**Comment by nathanleclaire** [comment]
Go for it @daehyeok
