### ISSUE TITLE
Operations on multiple machines should fork processes

### ISSUE THREAD

**Issue by Yajo** [docker/machine#3119]
See this output:

```
> docker-machine start agen2 manager
Starting "manager"...
Starting "agen2"...
(manager) Check network to re-create if needed...
(manager) Waiting for an IP...
Machine "manager" was started.
Waiting for SSH to be available...
Detecting the provisioner...
(agen2) Check network to re-create if needed...
(agen2) Waiting for an IP...
Machine "agen2" was started.
Waiting for SSH to be available...
Detecting the provisioner...
Started machines may have new IP addresses. You may need to re-run the `docker-machine env` command.
```

The `agen2` machine did not start until `manager` finished. Why? They are independent machines, so IMHO they should start working simultaneously, no need to wait.

**Comment by nathanleclaire** [comment]
Thanks for the issue -- That _is_ how it works today (well, not through `fork`, but through goroutines): https://github.com/docker/machine/blob/master/commands/commands.go#L438

That said, if this behavior is not working as intended, it'd be a bug -- but I'd need more concrete proof that one was blocking waiting on the other's operation(s).  This order looks simply arbitrary to me but if you can provide more definitive proof feel free to re-open.

**Comment by Yajo** [comment]
Maybe it's just my perception, but here with 2 CPUs, it seems like it's not being async.

[![asciicast](https://asciinema.org/a/37757.png)](https://asciinema.org/a/37757)

Maybe a good option would be to set an async wait when waiting for an IP, which seems the slowest point where a new process could start without problem.

**Comment by nathanleclaire** [comment]
What's the driver you're using here?  If it's `virtualbox`, we deliberately do the operations one at a time because VirtualBox does not handle concurrent requests for operations well.  https://github.com/docker/machine/blob/7a7dfd74440a607ca9b6bc0e002884529e7d445d/libmachine/libmachine.go#L108

**Comment by Yajo** [comment]
Oh yes it is. Then all should be OK, thanks for the info!
