### ISSUE TITLE
No active hosts found

### ISSUE THREAD

**Issue by dvohra** [docker/machine#3126]
With 3 docker machines "running" the `docker-machine ls` command does not list any of the docker machines as active. Also ran the following command:

`eval $(sudo docker-machine env default)`

The machine name is used instead of 'default'.

The following command outputs "No active hosts found"
`docker-machine active`

**Comment by nathanleclaire** [comment]
Thanks for the issue.  Please don't `sudo docker-machine`.  Machine is not meant to be invoked as a superuser.  Environment variables, path, etc. change between users and that may explain some of the issues you're seeing.

**Comment by dvohra** [comment]
But even without "sudo" same issue.

**Comment by nathanleclaire** [comment]
So, even if you run:

```console
$ eval $(docker-machine env)
$ docker-machine ls
```

No hosts show up as active?  What's the output of `env | grep DOCKER` in this case?

**Comment by dvohra** [comment]
Thanks. Running the docker-machine commands without 'sudo' fixed the error and active host gets listed.
But, had to run  docker-machine as 'root' user with sudo -i
Not documented, docker-machine is to be run as 'root'
--------------------------------------------
On Tue, 3/1/16, Nathan LeClaire <notifications@github.com> wrote:

 Subject: Re: [machine] No active hosts found (#3126)
 To: "docker/machine" <machine@noreply.github.com>
 Cc: "dvohra" <dvohra10@yahoo.com>
 Received: Tuesday, March 1, 2016, 11:38 AM
 
 So, even if you run:
 
 $ eval $(docker-machine env)
 $ docker-machine
 ls
 
 No hosts show up as active?  What's the output of
 env | grep DOCKER in this case?
 
 —
 Reply to this email directly or view
 it on GitHub.

**Comment by dvohra** [comment]
Thanks. Running the `docker-machine` commands without 'sudo' fixed the error and active host gets listed.

But, had to run  `docker-machine` as 'root' user with `sudo -i`
Not documented, `docker-machine` is to be run as 'root'

**Comment by jedwards1211** [comment]
I can confirm that with `Docker version 1.11.2, build b9f10c9`, no hosts show up as active and `env | grep DOCKER` outputs nothing.  I never ran `docker-machine` with `sudo`, always as my own user.

**Comment by dvohra** [comment]
As suggested, run as sudo.

**Comment by jedwards1211** [comment]
@dvohra I was confused by the documentation and cli output, I hadn't run `eval $(sudo docker-machine env default)`.  When I ran that (without `sudo`), `docker-machine active` worked.

**Comment by jedwards1211** [comment]
@dvohra I'm guessing the problem is that your actual machine was still running as root?  I would assume if you blow it away and run all the commands again with `sudo` then everything should work...

**Comment by dvohra** [comment]
Either as _root_ user or with _sudo_ is fine.
