### ISSUE TITLE
Default images are non-LTS Ubuntu

### ISSUE THREAD

**Issue by mbentley** [docker/machine#3135]
From the `v0.5.3` release notes (https://github.com/docker/machine/releases/tag/v0.5.3), it mentions that "Most base images are now set to Ubuntu 15.10".  Is there a reason why we have a non-LTS Ubuntu as the default?  I'd expect to receive the latest LTS release when creating instances.  If it was to support overlay networks, that is not an issue anymore because 1.10 has support for kernel 3.10+ when using overlay networks.

**Comment by nathanleclaire** [comment]
We use the latest available.  It's fairly easy to get a custom version of Ubuntu (e.g. 15.04 or 14.04) through `--amazonec2-ami-id` or similar flags.
