### ISSUE TITLE
Better way to detect if docker host is running

### ISSUE THREAD

**Issue by paulovictorv** [docker/machine#3141]
Hello

I'm running into a problem using the generic driver (I believe this applies to other drivers too). docker-machine fails to detect that my docker host is running because it checks the output of ``netstat -an``, which is locale dependent. I'm currently writing from Brazil, and sometimes the default linux distro language pack is downloaded according to the Locale.

I know that this is an easy fix on my part (just re-install ubuntu using english language pack), but I believe that docker-machine can use a more robust way to tell if the docker host is running or not.

I've located the piece of code which is responsible for this error, it happens that the "LISTEN" parameter is hardcoded on the regex match:

https://github.com/docker/machine/blob/8046e13683f6c40cfa55ae106bba5f4f4d87f7ea/libmachine/provision/utils.go#L253

Since the docker host port is until now hardcoded, can we run the regex based on the port it's listening on, instead of the status?

Thanks

**Comment by nathanleclaire** [comment]
I'm open to suggestions. I agree that using `netstat` is not really ideal, but any solution needs to account for the situation where SSH access is available, but direct access to `<ip>:2376` isn't (in which case machine can detect docker is running and finish provisioning anyway, alerting the user to the fact that the port is blocked).  This kind of IP range blockage is common with users running Docker Machine alongside VPN or other aggressively controlling network environments.

**Comment by paulovictorv** [comment]
I'm really not an expert with this, but would not a ´´telnet´´ (or anything similar) suffice to determine if docker is running? This can be run inside the machine being provisioned and also on the client machine. It could determine, as you say, that the port is blocked and therefore generating more robust information to the user.

**Comment by tpires** [comment]
@paulovictorv `telnet` isn't installed by default on all OS like `netstat`. IMHO `netstat` is the best choice but it could be improved to avoid OS with default language different from english.

There is one case in which checkDaemonUp will fail:
- If `dockerPort`is 2376 and machine has port 23760 listening, matchNetstatOut will return true.

I'm currently testing a fix and will push a PR soon.

**Comment by paulovictorv** [comment]
Yep, I'm aware of that, I was trying to come up with ideas similar to using ``telnet`` to check if the port is open. I've used a dummy code in some of my unit tests that tries to open a socket to a specified port and keeps trying until a connection is accepted or a timeout is reached.

But I guess that checking the output of ``netstat`` for the port works.
