### ISSUE TITLE
Machine creation fails due to pool keyservers

### ISSUE THREAD

**Issue by ahmetalpbalkan** [docker/machine#3148]
I get this failure a lot during machine provisioning (like 10% of the time).

I know that provisioner executes `if ! type docker; then curl -sSL https://get.docker.com | sh -; fi` and it's the get.docker.com script handles it, but could there be anything we can do in machine to prevent it (maybe add retries around this ssh command)? (Sorry if this is not the right repo to open the issue.)

```
+ sudo -E sh -c apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
Executing: gpg --ignore-time-conflict --no-options --no-default-keyring --homedir /tmp/tmp.vrqNYDUeXK --no-auto-check-trustdb --trust-model always --keyring /etc/apt/trusted.gpg --primary-keyring /etc/apt/trusted.gpg --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
gpg: requesting key 2C52609D from hkp server p80.pool.sks-keyservers.net
gpgkeys: key 58118E89F3A912897C070ADBF76221572C52609D can't be retrieved
gpg: no valid OpenPGP data found.
gpg: Total number processed: 0

Error creating machine: Error running provisioning: error installing docker:
[bugsnag output redacted]
```

**Comment by thaJeztah** [comment]
There's some improvements made to the install script, but they may not be live yet; https://github.com/docker/docker/pull/20737

**Comment by ahmetalpbalkan** [comment]
@thaJeztah nice,thanks!

**Comment by nathanleclaire** [comment]
Going to go ahead and close this issue -- we can re-open if those improvements don't seem to help with this type of issue (I've definitely seen it before)
