### ISSUE TITLE
Machine made prior to 0.5.5 missing vSphere Port Driver config

### ISSUE THREAD

**Issue by tyrken** [docker/machine#3150]
If you try to manage (e.g. docker-machine ls) vSphere machines made before 0.5.5, with that or newer releases, you'll encounter an error like the below:

> Post https://XXXXXXX:0/sdk: dial tcp XXXXXXX:0: connectex: The requested address is not valid in its context.

The issue is the 0.5.5 govmomi code added a "Port" config to the "Driver" section of the machine's config.json, defaulting to 443 at build time, 0 upon other uses such as above.  The simplest fix is to add this numeric value to your json manually.

Alternatively, initialising Port to 443 in NewDriver (drivers/vmwarevsphere/vsphere.go) will do the same for all.  Would a PR be appropriate?

**Comment by nathanleclaire** [comment]
cc @frapposelli

**Comment by frapposelli** [comment]
This was reported already and your fix suggestion makes perfect sense.

I'm swamped right now, if you could submit a quick PR it would be great.
