### ISSUE TITLE
Making sharing configuration easier

### ISSUE THREAD

**Issue by snyff** [docker/machine#3156]
Hi all,

Currently, the configuration file contains the full path to most files required:
{
    "ConfigVersion": 3,
    "Driver": {
        "AccessToken": "...",
        "Backups": false,
        "CaCertPath": "/Users/snyff/.docker/machine/certs/ca.pem",

This makes it difficult to move/share the config across systems. For example, you need to edit all your machines configuration to access them from a linux using :%s /Users/home/ ).

I'm not sure what the best way to do it. Maybe all paths should be relative to the repository used to store the machines configuration.

Keep up the awesome work.

**Comment by nathanleclaire** [comment]
Going to roll this into: https://github.com/docker/machine/issues/2516

Thanks!
