### ISSUE TITLE
Error OS type not recognized -- Docker-machine create Redhat with generic driver

### ISSUE THREAD

**Issue by ptaillard** [docker/machine#3164]
Hi,

I want to manage with docker-machine two existing docker-engine server.
Docker-machine run on Redhat (**Oracle Linux Server 7.2**) and the two existing docker-engine also.

**_But when I execute the command:_**
 docker-machine -D create --driver generic --generic-ip-address myserver myserver

**_The result is:_**
cat /etc/os-release
SSH cmd err, output: <nil>: NAME="Oracle Linux Server"
VERSION="7.2"
ID="ol"
VERSION_ID="7.2"
PRETTY_NAME="Oracle Linux Server 7.2"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:oracle:linux:7:2:server"
HOME_URL="https://linux.oracle.com/"
BUG_REPORT_URL="https://bugzilla.oracle.com/"

ORACLE_BUGZILLA_PRODUCT="Oracle Linux 7"
ORACLE_BUGZILLA_PRODUCT_VERSION=7.2
ORACLE_SUPPORT_PRODUCT="Oracle Linux"
ORACLE_SUPPORT_PRODUCT_VERSION=7.2

Couldn't set key CPE_NAME, no corresponding struct field found
Couldn't set key , no corresponding struct field found
Couldn't set key ORACLE_BUGZILLA_PRODUCT, no corresponding struct field found
Couldn't set key ORACLE_BUGZILLA_PRODUCT_VERSION, no corresponding struct field found
Couldn't set key ORACLE_SUPPORT_PRODUCT, no corresponding struct field found
Couldn't set key ORACLE_SUPPORT_PRODUCT_VERSION, no corresponding struct field found
Error creating machine: Error detecting OS: OS type not recognized
open : no such file or directory
notifying bugsnag: [Error creating machine: Error detecting OS: OS type not recognized]

**Can anyone help me to go forward with this issue?
Did anyone already have this issue?**

Thanks,

**Comment by ptaillard** [comment]
Hi,

It seems to be a complex issue due to no answer received ;-)
**Can anyone help me to go forward with this issue?
Did anyone already have this issue?
**
Thanks

**Comment by cdrage** [comment]
@ptaillard Hiya, I filed issue #3217 which will hopefully go forward in fixing your issue :)

**Comment by nathanleclaire** [comment]
@ptaillard It just needs to check for the CentOS-specific file in addition to `/etc/os-release` [here](https://github.com/docker/machine/blob/master/libmachine/provision/provisioner.go#L104)
