### ISSUE TITLE
Azure UI changed, consequently Machine docs are out of date

### ISSUE THREAD

**Issue by Nils-Magnus** [docker/machine#3173]
While investigating the Azure IaaS platform, we made some experiments to provision Docker hosts with docker-machine in order to set up a swarm cluster on Azure. When following the instructions on

    https://docs.docker.com/machine/drivers/azure/
    machine/docs/drivers/azure.md

we figured that Microsoft changed Azure's web portal UI recently so that some of the described steps to use the docker-machine driver are not (or not easily) possible any more. More specifically there is no longer an option to upload the "Management Certificates".

Is there a suggested workaround for that issue?

**Comment by ahmetalpbalkan** [comment]
@Nils-Magnus you can still use https://manage.windowsazure.com portal to upload certificates but as Nathan said we will have a brand new Azure driver soon, I suggest switching to that when it comes out (or you can build from source on my PR branch).

**Comment by ahmetalpbalkan** [comment]
@Nils-Magnus  @nathanleclaire no longer valid issue, please close.
