### ISSUE TITLE
Can't run docker-machine create with existing VirtualBox installation

### ISSUE THREAD

**Issue by wheelerlaw** [docker/machine#3174]
I already have VirtualBox 5.0.16 installed, so I unchecked it during the docker for windows installation. When I run docker `docker-machine create --driver virtualbox docker`, it gives me the following error:

`Error with pre-create check: "We support Virtualbox starting with version 5. Your VirtualBox install is \"\". Please upgrade at https://www.virtualbox.org"`

I tried adding `C:\Program Files\Oracle\VirtualBox` to the path system variable but that didn't change anything.

**Comment by wheelerlaw** [comment]
Update: So when I run Kitematic, it is able to create a VM perfectly fine, just not in the command line with `docker-create`

**Comment by wheelerlaw** [comment]
```
docker-machine create --driver virtualbox docker --debug
Docker Machine Version:  0.6.0, build e27fb87
Found binary path at C:\Program Files\Docker Toolbox\docker-machine.exe
Launching plugin server for driver virtualbox
Plugin server listening at address 127.0.0.1:40435
() Calling .GetVersion
Using API Version  1
() Calling .SetConfigRaw
() Calling .GetMachineName
(flag-lookup) Calling .GetMachineName
(flag-lookup) Calling .DriverName
(flag-lookup) Calling .GetCreateFlags
Invalid command line. Found extra arguments [--debug]
```

**Comment by wheelerlaw** [comment]
Interesting, so I am using Cmder as my shell. which is basically just a wrapper around ConEmu, but when I use ConEmu directly, it works fine, and when I just use plain old cmd, it works fine as well. Why would the way docker-machine gets the driver version number be dependent on the shell I am using?

**Comment by nathanleclaire** [comment]
> Why would the way docker-machine gets the driver version number be dependent on the shell I am using?

Not driver version number, but rather the way Docker Machine finds and execs the `VBoxManage` executable.  I'm referring to your original post, since there seems to be an issue finding the proper `VBoxManage`.  What does `C:\Program Files\Oracle\VirtualBox\VBoxManage.exe --version` command output say in the same shell where you're running machine?

In the pasted output, you need to put `--debug` immediately following the `docker-machine` invocation (i.e. `docker-machine --debug ...`).  It's a quirk of our CLI processor.

**Comment by wheelerlaw** [comment]
```
docker-machine --debug create --driver virtualbox docker4
Docker Machine Version:  0.6.0, build e27fb87
Found binary path at C:\Program Files\Docker Toolbox\docker-machine.exe
Launching plugin server for driver virtualbox
Plugin server listening at address 127.0.0.1:8906
() Calling .GetVersion
Using API Version  1
() Calling .SetConfigRaw
() Calling .GetMachineName
(flag-lookup) Calling .GetMachineName
(flag-lookup) Calling .DriverName
(flag-lookup) Calling .GetCreateFlags
Found binary path at C:\Program Files\Docker Toolbox\docker-machine.exe
Launching plugin server for driver virtualbox
Plugin server listening at address 127.0.0.1:8910
() Calling .GetVersion
Using API Version  1
() Calling .SetConfigRaw
() Calling .GetMachineName
(docker4) Calling .GetMachineName
(docker4) Calling .DriverName
(docker4) Calling .GetCreateFlags
(docker4) Calling .SetConfigFromFlags
Running pre-create checks...
(docker4) Calling .PreCreateCheck
(docker4) DBG | COMMAND: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe --version
(docker4) DBG | STDOUT:
(docker4) DBG | {
(docker4) DBG | }
(docker4) DBG | STDERR:
(docker4) DBG | {
(docker4) DBG | }
Error with pre-create check: "We support Virtualbox starting with version 5. Your VirtualBox install is \"\". Please upgrade at https://www.virtualbox.org"
open C:\Users\Wheeler\.docker\machine\machines\docker4\docker4\Logs\VBox.log: The system cannot find the path specified.
notifying bugsnag: [Error with pre-create check: "We support Virtualbox starting with version 5. Your VirtualBox install is \"\". Please upgrade at https://www.virtualbox.org"]
```

**Comment by wheelerlaw** [comment]
And the virtualbox version: 
```
"C:\Program Files\Oracle\VirtualBox\VBoxManage.exe" --version
5.0.16r105871
```

**Comment by wheelerlaw** [comment]
Running the debug command in ConEmu:
```
"C:\Program Files\Oracle\VirtualBox\VBoxManage.exe" --version
5.0.16r105871

C:\Users\Wheeler>docker-machine --debug create --driver virtualbox docker4
Docker Machine Version:  0.6.0, build e27fb87
Found binary path at C:\Program Files\Docker Toolbox\docker-machine.exe
Launching plugin server for driver virtualbox
Plugin server listening at address 127.0.0.1:8941
() Calling .GetVersion
Using API Version  1
() Calling .SetConfigRaw
() Calling .GetMachineName
(flag-lookup) Calling .GetMachineName
(flag-lookup) Calling .DriverName
(flag-lookup) Calling .GetCreateFlags
Found binary path at C:\Program Files\Docker Toolbox\docker-machine.exe
Launching plugin server for driver virtualbox
Plugin server listening at address 127.0.0.1:8945
() Calling .GetVersion
Using API Version  1
() Calling .SetConfigRaw
() Calling .GetMachineName
(docker4) Calling .GetMachineName
(docker4) Calling .DriverName
(docker4) Calling .GetCreateFlags
(docker4) Calling .SetConfigFromFlags
Running pre-create checks...
(docker4) Calling .PreCreateCheck
(docker4) DBG | COMMAND: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe --version
(docker4) DBG | STDOUT:
(docker4) DBG | {
(docker4) DBG | 5.0.16r105871
(docker4) DBG | }
(docker4) DBG | STDERR:
(docker4) DBG | {
(docker4) DBG | }
(docker4) DBG | COMMAND: wmic cpu get VirtualizationFirmwareEnabled
(docker4) DBG | Couldn't check that VT-X/AMD-v is enabled. Will check that the vm is properly created: exit status 2147749911
...
```

It appears STDOUT is not being captured for some reason on Cmder

**Comment by nathanleclaire** [comment]
Sounds like an issue outside of Machine.  If we can't invoke commands correctly using `os/exec`, Machine won't really work.  OK with you if we close this issue?

**Comment by maxwedwards** [comment]
@wheelerlaw I have the exact same issue, did you figure it out or just switch to ConEmu from Cmder?

**Comment by jchanth** [comment]
I have the same issue and trying to search online for solution now.

**Comment by jchanth** [comment]
C:\Users\jchanth>docker-machine --debug create --driver virtualbox docker4
Docker Machine Version:  0.12.2, build 9371605
Found binary path at C:\Program Files\Docker Toolbox\docker-machine.exe
Launching plugin server for driver virtualbox
Plugin server listening at address 127.0.0.1:57402
() Calling .GetVersion
Using API Version  1
() Calling .SetConfigRaw
() Calling .GetMachineName
(flag-lookup) Calling .GetMachineName
(flag-lookup) Calling .DriverName
(flag-lookup) Calling .GetCreateFlags
Found binary path at C:\Program Files\Docker Toolbox\docker-machine.exe
Launching plugin server for driver virtualbox
Plugin server listening at address 127.0.0.1:57408
() Calling .GetVersion
Using API Version  1
() Calling .SetConfigRaw
() Calling .GetMachineName
(docker4) Calling .GetMachineName
(docker4) Calling .DriverName
(docker4) Calling .GetCreateFlags
(docker4) Calling .SetConfigFromFlags
Running pre-create checks...
(docker4) Calling .PreCreateCheck
(docker4) DBG | COMMAND: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe --version
(docker4) DBG | STDOUT:
(docker4) DBG | {
(docker4) DBG | }
(docker4) DBG | STDERR:
(docker4) DBG | {
(docker4) DBG | }
Error with pre-create check: "We support Virtualbox starting with version 5. Your VirtualBox install
 is \"\". Please upgrade at https://www.virtualbox.org"
open C:\Users\jchanth\.docker\machine\machines\docker4\docker4\Logs\VBox.log: The system cannot find
 the path specified.
notifying bugsnag: [Error with pre-create check: "We support Virtualbox starting with version 5. You
r VirtualBox install is \"\". Please upgrade at https://www.virtualbox.org"]

**Comment by ekul1988** [comment]
I have same problem. Did you guys figure it out?
