### ISSUE TITLE
docker-machine create fails for ubuntu-xenial (16.04) host

### ISSUE THREAD

**Issue by FireballDWF** [docker/machine#3184]
docker-machine create fails on attempt install to a ubuntu-xenial (Beta 1) host due to http status 403 from https://apt.dockerproject.org/repo/dists/ubuntu-xenial/main/binary-amd64/Packages  403  Forbidden
which can also be observed via this release (acknowledged still in Beta) not available at https://apt.dockerproject.org/repo/dists/

Release date is 4/21/16 per https://wiki.ubuntu.com/XenialXerus/ReleaseSchedule thus is less than 6 weeks away, so please start have a repo for this upcoming release

**Comment by MrSpock** [comment]
Same here HTTP 403:
`Reading package lists... Done
W: The repository 'https://apt.dockerproject.org/repo ubuntu-xenial Release' does not have a Release file.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
W: Failed to fetch https://apt.dockerproject.org/repo/dists/ubuntu-xenial/main/binary-amd64/Packages  403  Forbidden
E: Some index files failed to download. They have been ignored, or old ones used instead.
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package docker-engine`

**Comment by hensodon** [comment]
Same issue here. I'm running 16.04 on bare metal, but can't get the xenial or wily repos to pull down a package file.

**Comment by nathanleclaire** [comment]
@FireballDWF Thanks for reporting the issue.  Does using the `get.docker.com` script directly work?  We rely on this, so if it doesn't work for 16.04, there's not much we can do in Machineland in the near future to support it.

However, the good news is that even if it's not today, it's very likely to be modified by upstream to start working soon.  And, naturally, both Machine and https://github.com/docker/docker will happily accept pull requests to enable this.

**Comment by FireballDWF** [comment]
No, it's still failing, but failure has changed.  Someone in control of https://apt.dockerproject.org/repo/dists/ubuntu-xenial/ created that last subdir within past few hours, but has not yet published the actual docker-engine package to that subdir of your website, as of 19:17 ET.

**Comment by ericoporto** [comment]
Hi, I need to install docker in Ubuntu 16.04, but I keep getting: `Unable to locate package docker-engine` .

**Comment by cablespaghetti** [comment]
If you change the repository from main to testing it'll work for now until
a tested package is released.

**Comment by nicornk** [comment]
+1 not able to install docker on ubuntu 16.04 bare metal.
@geekflyer

**Comment by nathanleclaire** [comment]
I thought that upstream supported this, I will try and see if I can get it to work and whinge at @tiborvass if it doesn't ;)

**Comment by nathanleclaire** [comment]
Ah, OK, looking around there seems to be an existing issue and I'm sure they're working on it.

**Comment by tiborvass** [comment]
@FireballDWF @nathanleclaire fixed

**Comment by tiborvass** [comment]
Ref: https://github.com/docker/docker/issues/22182

**Comment by nathanleclaire** [comment]
MRW @tiborvass is on the case 

![image](https://cloud.githubusercontent.com/assets/1476820/14726730/658b9dda-07d9-11e6-9ed0-29887a25ebf2.png)

**Comment by hans-permana** [comment]
I know this issue has been closed, but unfortunately I still got 403 Error message: 
```
W: The repository 'https://apt.dockerproject.org/repo ubuntu-xenial Release' does not have a Release file.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: Failed to fetch https://apt.dockerproject.org/repo/dists/ubuntu-xenial/main/binary-amd64/Packages  Received HTTP code 403 from proxy after CONNECT
E: Failed to fetch https://apt.dockerproject.org/repo/dists/ubuntu-xenial/main/binary-i386/Packages  Received HTTP code 403 from proxy after CONNECT
E: Some index files failed to download. They have been ignored, or old ones used instead.
```

and this is what I have in my docker.list file:
```
deb https://apt.dockerproject.org/repo ubuntu-xenial main
```

Do I miss anything?

**Comment by hans-permana** [comment]
Just an additional to the previous comment, the http version of the repository link works fine for me.

**Comment by chinaares** [comment]
I have the same error on ubuntu 16.04.

**Comment by eric-lopez** [comment]
I have the same error on Ubuntu 16.04.01

Err:5 https://apt.dockerproject.org/repo ubuntu-xenial InRelease
  Operation timed out after 0 milliseconds with 0 out of 0 bytes received
Fetched 94.5 kB in 2min 0s (786 B/s)
Reading package lists... Done
W: Failed to fetch https://apt.dockerproject.org/repo/dists/ubuntu-xenial/InRelease  Operation timed out after 0 milliseconds with 0 out of 0 bytes received
W: Some index files failed to download. They have been ignored, or old ones used instead.

**Comment by jonathanjbbr** [comment]
I have the same problem too.

**Comment by caneraydinbey** [comment]
+1

**Comment by ferOnti** [comment]
I had issue with  yakkety 
but I modified the sources.list and use the xenial dist

`vi /etc/apt/sources.list`

In order to check which dists are available, check this link:
[](https://apt.dockerproject.org/repo/dists/)

**Comment by faddat** [comment]
Yeah,what gives Docker, why not just keep pace with Ubuntu?

Having this issue w/ yakkety.

**Comment by nagavenkatab** [comment]
Acquire::https::apt.dockerproject.org::Verify-Peer "false";

try adding the above line to /etc/apt/apt.conf.d/01docker and do apt update

**Comment by code0100fun** [comment]
For anyone else running 16.10 (yakkety) you can install the release candidate instead: 

`curl -fsSL https://test.docker.com | sh`

Refer to this issue: https://github.com/docker/docker/issues/27521

**Comment by bdmorin** [comment]
New DO droplet, 16.04.1, official install instructions failing, fixed with:

/etc/apt/sources.list: deb https://apt.dockerproject.org/repo/ ubuntu-xenial main

**Comment by digitalica** [comment]
@bdmorin the change you suggested had exactly same result for me as without change...


last part of apt-get update output:
```
Ign:19 https://apt.dockerproject.org/repo/pool ubuntu-xenial/main DEP-11 64x64 Icons
Err:13 https://apt.dockerproject.org/repo/pool ubuntu-xenial/main amd64 Packages
  403  Forbidden
Ign:14 https://apt.dockerproject.org/repo/pool ubuntu-xenial/main i386 Packages
Ign:15 https://apt.dockerproject.org/repo/pool ubuntu-xenial/main all Packages
Ign:16 https://apt.dockerproject.org/repo/pool ubuntu-xenial/main Translation-en_US
Ign:17 https://apt.dockerproject.org/repo/pool ubuntu-xenial/main Translation-en
Ign:18 https://apt.dockerproject.org/repo/pool ubuntu-xenial/main amd64 DEP-11 Metadata
Ign:19 https://apt.dockerproject.org/repo/pool ubuntu-xenial/main DEP-11 64x64 Icons
Fetched 102 kB in 36s (2783 B/s)
Reading package lists... Done
W: The repository 'https://apt.dockerproject.org/repo/pool ubuntu-xenial Release' does not have a Release file.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: Failed to fetch https://apt.dockerproject.org/repo/pool/dists/ubuntu-xenial/main/binary-amd64/Packages  403  Forbidden
E: Some index files failed to download. They have been ignored, or old ones used instead.
```

**Comment by MarcosBermudez** [comment]
@digitalica I think you dident change correctly the sources.list you must also remove "pool" from url

Not work
#deb https://apt.dockerproject.org/repo/pool/ xenial main

Working
deb https://apt.dockerproject.org/repo/ ubuntu-xenial main

**Comment by mevatron** [comment]
I can definitely second @MarcosBermudez  findings. Either the guide is wrong or the repo is wrong. One should be fixed :P

**Comment by digitalica** [comment]
@MarcosBermudez was right. I removed 'pool' and now apt-get update works fine. So I agree with @mevatron. Fix in guide is already done in pullrequest by @stevenh

**Comment by durandaltheta** [comment]
I third MarcosBermudez findings. The [instructions](https://docs.docker.com/engine/installation/linux/ubuntu/) 
are wrong, instead of
`$ sudo add-apt-repository \
       "deb https://apt.dockerproject.org/repo/pool/ \
       $(lsb_release -cs) \
       main"`
It should be:
`$ sudo add-apt-repository \
       "deb https://apt.dockerproject.org/repo/ \
       $(cat /etc/issue | awk '{print $1}' | tr '[:upper:]' '[:lower:]')-$(lsb_release -cs) \
       main"`

**Comment by durandaltheta** [comment]
The "$(cat /etc/issue | awk '{print $1}' | tr '[:upper:]' '[:lower:]')-$(lsb_release -cs)" is to produce "ubuntu-xenial"

**Comment by gaboesquivel** [comment]
`deb https://apt.dockerproject.org/repo/ ubuntu-xenial main` works

**Comment by berny9015** [comment]
It seems it is the problem with aliyun mirror, and I solved this problem by removing Acquire::http::Proxy "http://mirrors.aliyun.com/"; in /etc/apt/apt.conf

Reference: https://gist.github.com/llgxvi/19d1666a7f0b5d8d9237707daf479120

**Comment by aitorbk** [comment]
One year on, still doesnt work....

**Comment by thaJeztah** [comment]
@aitorbk I know there have been people that were able to install docker over the last year. Can you open a new issue if you are running into issues, with more details?

**Comment by aitorbk** [comment]
Absolutely my fault, will edit the comment.

**Comment by dikirill** [comment]
Yes, using latest Linux Mint 18.3 you just need to run:
`sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable"`

**Comment by caroso1222** [comment]
Not sure if this is relevant but I landed here looking for this error

```
W: The repository 'https://apt.dockerproject.org/repo ubuntu-xenial Release' does not have a Release file.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: Failed to fetch https://apt.dockerproject.org/repo/dists/ubuntu-xenial/main/binary-amd64/Packages  404  Not Found
E: Some index files failed to download. They have been ignored, or old ones used instead.
```

Fixed it by running this command, as proposed [here](https://stackoverflow.com/questions/41133455/docker-repository-does-not-have-a-release-file-on-running-apt-get-update-on-ubun#comment99414198_43639310).

```
sudo rm /etc/apt/sources.list.d/docker*
```

That file contained the entry `deb [arch=amd64] ...` which is the conflicting one.
