### ISSUE TITLE
Can we add a --engine-opt to existing docker machine?

### ISSUE THREAD

**Issue by llitfkitfk** [docker/machine#3187]

**Comment by nathanleclaire** [comment]
It's not possible first class today unfortunately :( They must be specified at create time.

One way to possibly workaround (although I have to give the disclaimer that this is a total hack and absolutely not a supported Machine workflow), is that you could actually edit the `config.json` to add the parameters you desire yourself, and then invoke `docker-machine provision machine`.  Say you wanted to add some labels.  In that case, `HostOptions > EngineOptions > ArbitraryFlags` becomes:

```
"ArbitraryFlags": [
    "label=hdd=ssd",
    "label=os=debian",
    "label=region=us-west-1"
]
```

**Comment by llitfkitfk** [comment]
@nathanleclaire Thanks!
