### ISSUE TITLE
Bug with SSH command within provisions/utils.go generic driver.

### ISSUE THREAD

**Issue by cdrage** [docker/machine#3197]
Line 125 of `provision/utils.go`:

```go
if _, err := p.SSHCommand(`if [ ! -z "$(ip link show docker0)" ]; then sudo ip link delete docker0; fi`); err != nil {
 return err
}
```

If docker0 has already been removed this command will fail and docker-machine will not proceed.

For example: 
If the docker generic driver timed out the first time and `docker-machine create` is reran with docker0 already removed by `ip link delete docker0`
or
Docker has been installed on the system for the first time but not initiated / start yet.

Incoming PR once I test this a bittttt :dancers:

**Comment by nathanleclaire** [comment]
Hi @cdrage, thanks for the issue.

Looks like the first part of the `if` is meant to check for the presence of that bridge, no? Why is it failing?

Looking forward to PR.

**Comment by cdrage** [comment]
@nathanleclaire Seems to fail when there is actually no bridge, as in, docker0 isn't even initialized / not there. So when `if [ ! -z "$(ip link show docker0)" ];` is executed it get's "Device "docker0" does not exist." so the bash script thinks there is a docker0 due to the output and executes `sudo ip link delete docker0` but fails because docker0 isn't there in the first place.

**Comment by nathanleclaire** [comment]
Mm, that error text should go to STDERR though, rendering the output of the subshell blank.  At least that's the way it seems intended to work.

**Comment by cdrage** [comment]
@nathanleclaire yeah... seems that centos/fedora screws up in this regards but debian/ubuntu appear fine.

let me check a few more things, see if there is alternative fix

**Comment by cdrage** [comment]
Seems like it was an issue with `ip show` on Fedora 22. Updating it and there's no more problems. That or it was something in .bashrc that was screwy.

Closin'!

**Comment by nathanleclaire** [comment]
Thanks for following up to close @cdrage

**Comment by flybyray** [comment]
i would like to reopen that issue because of an error in debug output, while `docker-machine create` with `generic` driver.
executed on supported operating systems provided by vagrant boxes [ubuntu/xenial64](https://app.vagrantup.com/ubuntu/boxes/xenial64) and [centos/7](https://app.vagrantup.com/centos/boxes/7)
`SSH cmd err, output: <nil>: bash: ip: command not found`
is related to this issue because the command executed was
`if [ ! -z "$(ip link show docker0)" ]; then sudo ip link delete docker0; fi`

**Comment by flybyray** [comment]
ok checked it and debugged it in shell.
the `ip` command is excuted on the ssh client side. therefore the bash error "ip: command not found".
it is an escaping sequence problem. with this esacping the command worked on the remote side 
 `		command="if [ ! -z '"'$(ip link show docker0)'"' ]; then sudo ip link delete docker0; fi"
		echo "$command"
		ssh -v -i "$identity_file" -l "$login_name" -p "$port" "$hostname_fqn" "$command"
`
