### ISSUE TITLE
azure driver unresolvable authentication refresh requests

### ISSUE THREAD

**Issue by nathanleclaire** [docker/machine#3201]
Originally reported to me by @dgageot I have now successfully duped this issue.

Steps to reproduce:

```console
$ docker-machine create --driver azure --azure-subscription-id ... azurevm0
... 
$ docker-machine create --driver azure --azure-subscription-id ... azurevm1
...
```

Wait for a little while

```console
$ docker machine ls
(azurevm0) Microsoft Azure: To sign in, use a web browser to open the page https://aka.ms/devicelogin. Enter the code BFXVD92QU to authenticate.
(azurevm1) Microsoft Azure: To sign in, use a web browser to open the page https://aka.ms/devicelogin. Enter the code BMAYXBEHG to authenticate.
NAME       ACTIVE   DRIVER       STATE     URL                         SWARM   DOCKER    ERRORS
azurevm0            azure        Timeout
azurevm1            azure        Timeout
```

Neither authentication seems to work for me.  Race condition (or maybe caused by the `ls` timeout)?

As discussed in https://github.com/docker/machine/issues/3199, it would be preferable to not have to re-prompt users for this (frequently at least).  We definitely need to make sure that they are able to resolve them when they do come up though.

@ahmetalpbalkan @ppadala Please take a look.  Thanks!

**Comment by ahmetalpbalkan** [comment]
@nathanleclaire Normally this prompt should appear every 2 weeks, but it looks like there’s a problem going on that we are not able to reproduce at Microsoft-side. 

So I crafted a binary (at #3199) that spits out HTTP body of the failing request (that’s causing stored token to be deleted so that user can re-auth cleanly). Please try with that and when it asks you to prompt, send the output my way.

The timeouts are because of `ls` cmd. Other commands (i.e. `ip`, `ssh`, `create`, `rm`)  will block until you authenticate.

**Comment by ppadala** [comment]
Pasting the output with the new binary that @ahmetalpbalkan provided in the other post. This output has the response body.

Pradeeps-MacBook-Air-2:machine ppadala$ ~/Downloads/bin/docker-machine-Darwin-x86_64 -D create -d azure --azure-subscription-id $(cat ~/azure/subid)  ppadala-test
Docker Machine Version:  0.7.0-dev, build 2567201
Found binary path at /Users/ppadala/Downloads/bin/docker-machine-Darwin-x86_64
Launching plugin server for driver azure
Plugin server listening at address 127.0.0.1:59911
() Calling .GetVersion
Using API Version  1
() Calling .SetConfigRaw
() Calling .GetMachineName
(flag-lookup) Calling .GetMachineName
(flag-lookup) Calling .DriverName
(flag-lookup) Calling .GetCreateFlags
Found binary path at /Users/ppadala/Downloads/bin/docker-machine-Darwin-x86_64
Launching plugin server for driver azure
Plugin server listening at address 127.0.0.1:59915
() Calling .GetVersion
Using API Version  1
() Calling .SetConfigRaw
() Calling .GetMachineName
(ppadala-test) Calling .GetMachineName
(ppadala-test) Calling .DriverName
(ppadala-test) Calling .GetCreateFlags
(ppadala-test) Calling .SetConfigFromFlags
Running pre-create checks...
(ppadala-test) Calling .PreCreateCheck
(ppadala-test) DBG | Set configuration from flags.
(ppadala-test) DBG | Looking up AAD Tenant ID.  subs="9533c62a-37de-4616-93d0-2ecc89f9ec38"
(ppadala-test) DBG | Azure request  method="GET" request="https://management.azure.com/subscriptions/9533c62a-37de-4616-93d0-2ecc89f9ec38?api-version=2015-11-01"
(ppadala-test) DBG | Azure response  method="GET" request="https://management.azure.com/subscriptions/9533c62a-37de-4616-93d0-2ecc89f9ec38?api-version=2015-11-01" x-ms-request-id="3426e310-471a-4192-9c96-f13322482cb6" status="401 Unauthorized"
(ppadala-test) DBG | Azure response  status="401 Unauthorized" method="GET" request="https://management.azure.com/subscriptions/9533c62a-37de-4616-93d0-2ecc89f9ec38?api-version=2015-11-01" x-ms-request-id="3426e310-471a-4192-9c96-f13322482cb6"
(ppadala-test) DBG | Found AAD Tenant ID.  tenant="ac9085bc-c03c-4ac2-962f-4e0998d24767" subs="9533c62a-37de-4616-93d0-2ecc89f9ec38"
(ppadala-test) DBG | Loading auth token from file  path="/Users/ppadala/.docker/machine/credentials/azure/ac9085bc-c03c-4ac2-962f-4e0998d24767.json"
(ppadala-test) DBG | Auth token found in file.  path="/Users/ppadala/.docker/machine/credentials/azure/ac9085bc-c03c-4ac2-962f-4e0998d24767.json"
(ppadala-test) DBG | Validating the token.
(ppadala-test) RESPONSE BODY = {"error":"invalid_grant","error_description":"AADSTS70002: Error validating credentials. AADSTS70008: The provided authorization code or refresh token is expired. Send a new interactive authorization request for this user and resource.\r\nTrace ID: a29de696-5658-446f-ad02-b91b8a2fb721\r\nCorrelation ID: 3d029e2e-d20a-4fba-ac97-e9ef40c0b00b\r\nTimestamp: 2016-03-17 17:30:13Z","error_codes":[70002,70008],"timestamp":"2016-03-17 17:30:13Z","trace_id":"a29de696-5658-446f-ad02-b91b8a2fb721","correlation_id":"3d029e2e-d20a-4fba-ac97-e9ef40c0b00b"}
(ppadala-test) DBG | Error: Token validity check failed: autorest:WithErrorUnlessStatusCode 400 POST https://login.microsoftonline.com/ac9085bc-c03c-4ac2-962f-4e0998d24767/oauth2/token?api-version=1.0 failed with 400 Bad Request
(ppadala-test) Stored Azure credentials expired. Please reauthenticate.

**Comment by nathanleclaire** [comment]
> The timeouts are because of ls cmd. Other commands (i.e. ip, ssh, create, rm) will block until you authenticate. I believe there’s no race condition going on.

OK.  I think we should add a section in the Azure documentation reviewing the authentication renewal process.  Perhaps we can recommend that users run something like `docker-machine ip <instance>` for each instance to block and refresh.

**Comment by ahmetalpbalkan** [comment]
@nathanleclaire sounds good. 

@ppadala the following output indeed confirms our suspicions, there is something wrong with Active Directory. My guess is it’s a bug. Normally, the `refresh token` issued should be good for 15 days, however apparently that’s not the case. 

I will follow up with Azure Active Directory team about this. There is nothing further we can do in the code to fix or workaround this as far as I can foresee. cc: @colemickens

> `(ppadala-test) RESPONSE BODY = {"error":"invalid_grant","error_description":"AADSTS70002: Error validating credentials. AADSTS70008: The provided authorization code or refresh token is expired. Send a new interactive authorization request for this user and resource.\r\nTrace ID: a29de696-5658-446f-ad02-b91b8a2fb721\r\nCorrelation ID: 3d029e2e-d20a-4fba-ac97-e9ef40c0b00b\r\nTimestamp: 2016-03-17 17:30:13Z","error_codes":[70002,70008],"timestamp":"2016-03-17 17:30:13Z","trace_id":"a29de696-5658-446f-ad02-b91b8a2fb721","correlation_id":"3d029e2e-d20a-4fba-ac97-e9ef40c0b00b"}`

**Comment by ahmetalpbalkan** [comment]
@nathanleclaire @ppadala 

I confirmed with the ActiveDirectory team that this is indeed a bug with the auth flow using Microsoft accounts. The `refresh_token`s that are supposed to be good for 14 days are only good for 12 hours and this will be prompting almost all docker-machine users to reauthenticate probably several times a day.

There's currently no ETA for resolution as far as I can tell (I know, I know... :disappointed:) but I will be pushing the product team to take the fix ASAP. Unfortunately I believe there is nothing we can do in docker-machine driver to fix that –it is a server bug. 

That said, I am entirely O.K. with _not shipping_ the new azure driver (and bringing the old azure driver back) for as long as it takes. I am happy to discuss the matter with the maintainers (preferably over a conf call) and give the background about what is the deal with Azure auth and even though if this were to be fixed, what auth problems will remain.

So, why didn't we catch this bug earlier? I was using my ActiveDirectory user (ahmetb@microsoft˙com) and not my personal Hotmail/Outlook account (now called Microsoft Account). When I tested with my AD account, everything seemed fine. I switched to my MSA and it worked fine too, but I did not wait long enough to see if its expiration is indeed 14 days or so.

**Comment by nathanleclaire** [comment]
OK, thanks for the info @ahmetalpbalkan.  I think that probably what we should do is:

1. Keep going with this new driver
2. Add a note to the Azure documentation page and release notes about this as a known issue
3. Wait for the bug to be fixed in the upstream API, and supplement with a patch release of Machine if needed once it's fixed.

If that sounds good to you @ahmetalpbalkan, I'd ask that you take the initiative on (2) above please.

**Comment by ahmetalpbalkan** [comment]
@nathanleclaire makes sense, in the meanwhile, users can actually create an Azure ActiveDirectory user ([documentation](https://azure.microsoft.com/en-us/documentation/articles/resource-group-create-work-id-from-personal/)) from their personal Microsoft accounts and login with the AAD user, that actually is a workaround to the early expiration problem.

I will send a PR mentioning the known issue and this particular workaround. There should be no code change required in driver in the long term about this, once the AAD fixes its problem we should be working just fine. However currently there is no ETA for resolution, which makes me sad as well.

In the long term, we already started initiatives such as:
- refresh_tokens that don't expire and
- azure credentials file in a well-known location that is shared between tools like Azure CLI, Azure SDKs and utils such as machine, terraform, packer etc. This will be like Google's default_credentials file.

Once these work is done by the ActiveDirectory team, we should have a thousand times better authentication experience for Azure, and possibly no authentication at all if the user already has Azure CLI installed on their machine as they would share credentials.

**Comment by nathanleclaire** [comment]
All of that sounds great.  Thanks Ahmet.

**Comment by ppadala** [comment]
That's great @ahmetalpbalkan. If there are tokens that don't expire, I am guessing that will solve the automation problems as well.

On a side note, I am going to assume that we are not rolling back to old driver and continue with my Windows patch.

**Comment by ahmetalpbalkan** [comment]
@ppadala :+1:, though as I said, there's no ETA for any of those. :)

**Comment by edevil** [comment]
@ahmetalpbalkan It's been more than a month and I still have the AD issues with the auth token validity. Any ETA at this time? Or is there some other forum I should be taking this matter to?

**Comment by ahmetalpbalkan** [comment]
@edevil we are internally following up internally with Azure Active Directory team, and they are aware of the issue. It looks like their ETA is something like 6 months, in the meanwhile if you create an AAD work ID as described in the “known issue” section here: https://docs.docker.com/machine/drivers/azure/ and sign in with that when prompted for authentication, the retrieved token should last 2 weeks. Please let me know if this workaround works for you.
