### ISSUE TITLE
docker-machine rm -f doesn't work with new Azure driver

### ISSUE THREAD

**Issue by nathanleclaire** [docker/machine#3206]
cc @ahmetalpbalkan @ppadala @dgageot 

I had a couple of Azure VMs created using the driver which I removed by hand.

I ran into https://github.com/docker/machine/issues/3201 attempting to `docker-machine rm -f` these hosts.  `docker-machine rm -f` should _always_ be possible to remove the local references if desired.

So, we most likely need to add some max retries logic (so that if authentication is not successful after, say, 5 attempts, `Driver.Remove` will actually return).  If we don't get an error back https://github.com/docker/machine/blob/master/commands/rm.go#L31 will block forever.

**Comment by ahmetalpbalkan** [comment]
What's the error you ran into while rm? Or did it simply block at the authentication prompt?

**Comment by nathanleclaire** [comment]
@ahmetalpbalkan It blocks at the authentication prompt.

**Comment by ahmetalpbalkan** [comment]
@nathanleclaire then "doesn't work" probably isn't entirely accurate. The same situation could occur if any other driver blocks on some HTTP request as well? What do you suggest in this case?

**Comment by nathanleclaire** [comment]
> then "doesn't work" probably isn't entirely accurate.

If the authentication prompt won't let me through, or error out at some reasonable point, it doesn't work :stuck_out_tongue: Today it's easy to get stuck in an impossible situation where you can't authenticate with the driver, and you can't remove the machines through `docker-machine rm`. Ideally, users should be able to recover from every kind of failure using only the porcelain.

> The same situation could occur if any other driver blocks on some HTTP request as well? What do you suggest in this case?

They just shouldn't (usually if there's an authentication failure in a driver it directly returns an error instead of blocking).  If another driver does that, it's a bug.  

Drivers should have their own timeout / failure handling logic to ensure that situations like that can be recovered from.  In this case it looks like the actual blocking bit might be inside of the vendored Azure code itself -- is that correct?

**Comment by ahmetalpbalkan** [comment]
We can probably refactor driver to not to prompt for auth (and just fail) for cmds such as `ls`, `rm`, `ip`, `env` that either timeout or people use with eval directly or indirectly.

**Comment by nathanleclaire** [comment]
Yep, that would be my preference.  Maybe we could make only one of them the "authentication" method, although I dislike the magic nature of that.

In the meanwhile, this (cred management) is one of many issues that I'd like to solve with libmachine v2.  So maybe I should start jotting some notes down about what I'd like v2 to look like to get the conversation moving.

**Comment by ahmetalpbalkan** [comment]
@nathanleclaire that'd be great, I'd love to explain what's the deal with this Azure ActiveDirectory's unusual auth flow some time and why we require users to prompt every 2 weeks etc. and brainstorm about what we can do. I was hoping to propose a cmd like `docker-machine auth`.

**Comment by ahmetalpbalkan** [comment]
@nathanleclaire the new azure auth mode in #3665 solves this problem, feel free to close.
