### ISSUE TITLE
Docker-machine install without sudo permissions

### ISSUE THREAD

**Issue by kovacsa91** [docker/machine#3213]
How can I install docker-machine without sudo permissions in user's home folder?

**Comment by zhangbbo** [comment]
You can download the binary files to your home folder, set their execution permission, and add your home folder to $PATH.
That's all.
:)

**Comment by nathanleclaire** [comment]
Yes, as @zhangbbo noted, you can simply copy the binaries to somewhere on your `PATH`, root is not needed.
