### ISSUE TITLE
Virtualbox shared volumes not picking up changes

### ISSUE THREAD

**Issue by cmheisel** [docker/machine#3222]
With docker-machine 0.6 and Virtualbox 5.0.16 with OS X I've encountered situations where changes to files on my Mac filesystem that are shared via docker-compose volumes aren't picked up by the running docker container.

I've got more details and a test script here: https://github.com/cmheisel/docker-machine-fstest

It seems like installing [docker-machine-nfs](https://github.com/adlogix/docker-machine-nfs) resolves the issue

Interestingly, it seems like using Alpine base images exposes the issue, at least with Python apps.

**Comment by thaJeztah** [comment]
I think this may be because VirtualBox shared folders don't support inotify (and they won't be supporting that, see: https://www.virtualbox.org/ticket/10660)

Also see https://github.com/docker/docker/issues/18246, which has some more related issues linked

**Comment by cmheisel** [comment]
@thaJeztah I didn't think about inotify support. That would explain the live-reloading.

I'm seeing the same behavior if you docker-compose stop and docker-compose up to restart the containers, the change you made doesn't show.  I [updated my test script to verify](https://github.com/cmheisel/docker-machine-fstest/commit/b2f17c7439dc5d958bdb851f932240cc9fd3ed73). That seems like something larger than inotify support.

**Comment by thaJeztah** [comment]
A colleague just mentioned that this could be due to sendfile not working on vboxsf. Don't know if there's an option to disable that in your python app?

**Comment by cmheisel** [comment]
@thaJeztah What's weird is the python app reloads on change with Debian-based distros, but not Alpine-based. And that Nginx isn't picking up changes either live or **after a container restart**

What I've found is below, with the really weird stuff in bold:

| Distro/App   	| Changes appear on file change 	| Changes appear on container restart 	|
|--------------	|-------------------------------	|-------------------------------------	|
| Alpine/Flask 	| NO                            	| **NO**                              	|
| Alpine/Nginx 	| NO                            	| **NO**                              	|
| Debian/Flask 	| Yes                           	| Yes                                 	|
| Debian/Nginx 	| **NO**                        	| **NO**                              	|

**Comment by thaJeztah** [comment]
Nginx may be partly related to sendfile (also see http://serverfault.com/questions/269420/disable-caching-when-serving-static-files-with-nginx-for-development), although it surprises me that it doesn't pick up those changes even after a container restart. Perhaps @ncopa has an idea what difference Alpine makes in this situation.

You may be interested in https://blog.docker.com/2016/03/docker-for-mac-windows-beta/, which solves a lot of issues in this area

**Comment by cmheisel** [comment]
@thaJeztah I got access to the beta and all the tests passed with that, so it must be virtualbox/vboxfs related.

**Comment by thaJeztah** [comment]
@cmheisel excellent! Enjoy the beta, I hope you like it!

**Comment by nathanleclaire** [comment]
Closing this as nothing seems actionable on our end
