### ISSUE TITLE
Generic provisioning with Debian 8 creates invalid APT source file

### ISSUE THREAD

**Issue by kaptajnen** [docker/machine#3225]
When you try to create a docker machine using the generic driver for a remote Debian 8 machine, the following invalid apt source file is created:

`deb c https://apt.dockerproject.org/repo debian-jessie main`

That c character after deb should not be there. I tried to fix it manually, but as soon as I run the command again, the file is overwritten with the invalid content.

Version is 0.6.0, build e27fb87

As a sidenote, when creation fails, the machine is still added to the local machine list, so when you re-run the command you get an error saying the machine already exists. Shouldn't it wait until the creation succeeds until it is added?

**Comment by kaptajnen** [comment]
After running it with the debug option it seems the issue is in the install script at get.docker.com. In the following line, it seems the brackets needs to be escaped

`$sh_c "echo deb [arch=$(dpkg --print-architecture)] https://apt.dockerproject.org/repo ${lsb_dist}-${dist_version} ${repo} > /etc/apt/sources.list.d/docker.list"`

**Comment by nathanleclaire** [comment]
Might want to file an issue on https://github.com/docker/docker/issues/new; thanks!

**Comment by kaptajnen** [comment]
Thanks, submitted here instead: https://github.com/docker/docker/issues/21459
