### ISSUE TITLE
Docker Machine stuck while downloading `boot2docker.iso`

### ISSUE THREAD

**Issue by Mahmoudz** [docker/machine#3229]
I run this command 3 times and every time I wait about 30 min with no success!! could it be that the newtok I'm using is blocking me?!

```sh
❯ docker-machine -D create --driver virtualbox default
Docker Machine Version:  0.6.0, build e27fb87
Found binary path at /usr/local/bin/docker-machine
Launching plugin server for driver virtualbox
Plugin server listening at address 127.0.0.1:62689
() Calling .GetVersion
Using API Version  1
() Calling .SetConfigRaw
() Calling .GetMachineName
(flag-lookup) Calling .GetMachineName
(flag-lookup) Calling .DriverName
(flag-lookup) Calling .GetCreateFlags
Found binary path at /usr/local/bin/docker-machine
Launching plugin server for driver virtualbox
Plugin server listening at address 127.0.0.1:62693
() Calling .GetVersion
Using API Version  1
() Calling .SetConfigRaw
() Calling .GetMachineName
(default) Calling .GetMachineName
(default) Calling .DriverName
(default) Calling .GetCreateFlags
(default) Calling .SetConfigFromFlags
Running pre-create checks...
(default) Calling .PreCreateCheck
(default) DBG | COMMAND: /usr/local/bin/VBoxManage --version
(default) DBG | STDOUT:
(default) DBG | {
(default) DBG | 5.0.16r105871
(default) DBG | }
(default) DBG | STDERR:
(default) DBG | {
(default) DBG | }
(default) No default Boot2Docker ISO found locally, downloading the latest release...
(default) Latest release for github.com/boot2docker/boot2docker is v1.10.3
(default) Downloading /Users/mz/.docker/machine/cache/boot2docker.iso from https://github.com/boot2docker/boot2docker/releases/download/v1.10.3/boot2docker.iso...1
```

**Comment by Mahmoudz** [comment]
Well after opening this issue I tried to download `https://github.com/boot2docker/boot2docker/releases/download/v1.10.3/boot2docker.iso` manually to place it in the `/Users/mz/.docker/machine/cache/` and seems that the connection is very slow when attempting to download a file.

I'm gonna switch to other network and if that solves it I will close this issue :)

**Comment by nathanleclaire** [comment]
Sounds good -- yes slow network sounds like the culprit here

**Comment by Mahmoudz** [comment]
I'm very sure that's something caused by the Internet Service Provider in my country!!

However here's the workaround solution:

Download the boot2docker.iso file manually by going to https://api.github.com/repos/boot2docker/boot2docker/releases/latest then clicking on the `html_url` and finally choosing to download the file.

Once you get the file go and place it manually in `/Users/{user}/.docker/machine/cache/`

Finally re-run this command `docker-machine create --driver virtualbox default`

**Comment by Mahmoudz** [comment]
Well after solving this I got stucked in the same error (as expected) while pulling the images.

It took me few days to figure it out but it works like a sharm now:

All you have to do is to set your DNS to `8.8.8.8` _(mine was 192.168.0.1)_ 
If you're wondering how just edit the `/etc/resolv.conf` and set the nameserver to 8.8.8.8

Now restart your machine :)

If you faced anything related to certificate or whatever just run this `docker-machine regenerate-certs default` and try again, you should be fine.

**Comment by nathanleclaire** [comment]
Did simply restarting the machine not help?

**Comment by nathanleclaire** [comment]
BTW, just to be clear, it's not the same error.  One is related to downloading the `boot2docker.iso` (OS for the VM) and one is _inside_ of the created VM pulling Docker images.

**Comment by Mahmoudz** [comment]
I've restarted everything and nothing worked I've uninstalled and reinstalled everything and still nothing worked. Yes it's 2 different messages each on an area but both are caused by the same root error. It even cause many other errors, all related to not being able to access the internet.

**Comment by nathanleclaire** [comment]
I thought accessing the Internet was fine and DNS seemed to be the issue though.  If it's DNS issues in both cases, there's likely something up with your system's native resolver.  For what it's worth we're taking into considering DNS issues in Docker for Mac and it selects a resolver for the VM a bit more robustly.

**Comment by zored** [comment]
When it shows `Downloading A from B...` I just do `wget B -O A` to download ISO manually to required destination.

**Comment by sdiachenko** [comment]
my steps that solved it: 
`brew uninstall docker docker-machine`
`rm '/usr/local/bin/docker'`
`rm '/usr/local/bin/docker-machine'`

and then  
`brew uninstall docker docker-machine`
run 
`dinghy create --provider virtualbox`

solved issue with downloading

**Comment by dubuqug** [comment]
killing the process and restarting my machine worked for me

**Comment by SkippingAdi** [comment]
Hi all
I have the same Problem and am still stuck in how to download this iso image?
This bad download performance disturbs the whole docker experience for me.

**Comment by BroniusJanonis** [comment]
I had similar problem with slow speed and I switched `External network` from (in my case) `dual band wireless` to `Ethernet connection`
Then `boot2docker.iso` downloaded almost instantly

**Comment by yinfredyue** [comment]
> I had similar problem with slow speed and I switched `External network` from (in my case) `dual band wireless` to `Ethernet connection`
> Then `boot2docker.iso` downloaded almost instantly

Can you indicate how to do that?

**Comment by smittal363** [comment]
> > I had similar problem with slow speed and I switched `External network` from (in my case) `dual band wireless` to `Ethernet connection`
> > Then `boot2docker.iso` downloaded almost instantly
> 
> Can you indicate how to do that? v18.09.3 download still never succeed.

it works thanks

**Comment by alexisrolland** [comment]
> Here's the workaround solution:
> 
> Download the boot2docker.iso file manually by going to https://api.github.com/repos/boot2docker/boot2docker/releases/latest then clicking on the `html_url` and finally choosing to download the file.
> 
> Once you get the file go and place it manually in `/Users/{user}/.docker/machine/cache/`
> 
> Finally re-run this command `docker-machine create --driver virtualbox default`

For those who are on Windows, the file `boot2docker.iso` should be placed in `C:\Users\{user}\.docker\machine\cache`

**Comment by Destinyr4zr** [comment]
Can anyone just put this file on another service? I can't download it even now. May be that's because of drivers docker installs in system
