### ISSUE TITLE
Openstack Driver: Add option for config drive

### ISSUE THREAD

**Issue by Slamper** [docker/machine#3246]
Please add the option to activate the ConfigDrive.
This feature exists in the gophercloud library but isn't exposed in the openstack machine driver.

**Comment by nathanleclaire** [comment]
cc @ggiamarchi @fsoppelsa

**Comment by fsoppelsa** [comment]
Yes, this is a good idea, I can add this. @nathanleclaire

**Comment by Slamper** [comment]
@fsoppelsa Great to hear this. Thanks

**Comment by k3nny0ne** [comment]
+1
It would be great to have ConfigDrive activation option.

**Comment by Mike-Phelps** [comment]
I am looking for this functionality as well.

**Comment by andrei4ka** [comment]
+1

**Comment by sagar-chandarana** [comment]
+1. updates? It's been a year

**Comment by davidarcher** [comment]
I need this for RancherOS launches on OpenStack. Shouldn't be too hard. I'll take a stab at it.
