### ISSUE TITLE
Creating machine using new azure driver gets stuck when specifying azure-no-public-ip

### ISSUE THREAD

**Issue by tmds** [docker/machine#3249]
I am using the 0.7.0-rc1 to create machines in azure. When I specify the azure-no-public-ip option, the command output stops for a very long time on the "Waiting for SSH to be available..." message.

It is possible the command cannot continue because there is no public IP.

In the documentation I also noticed the azure-use-private-ip option. It is not clear what the option does, but adding it does not solve the issue.

**Comment by tmds** [comment]
After a while the command then outputs: "Detecting the provisioner..."
And then some time later it fails with the message: "Error creating machine: Error detecting OS: OS type not recognized"

    Detecting operating system of created instance...
    Waiting for SSH to be available...
    Detecting the provisioner...
    Error creating machine: Error detecting OS: OS type not recognized

**Comment by nathanleclaire** [comment]
cc @ahmetalpbalkan

**Comment by ahmetalpbalkan** [comment]
@tmds the "no public ip" command is for running machine when you're in Azure already and trying to create a VM within the subnet your machine is running on. 

So from your laptop, you can't use this option, it's meant to be used for creating machines with no public IP (only local private IP) from another machine in Azure.

**Comment by tmds** [comment]
After creating the issue, I figured as much. Perhaps the documentation can improve a little.

Does azure-no-public-ip imply azure-use-private-ip?

Are there some tools out there already that use this command to setup machines on azure? or is this a command to execute manually on machine in Azure?

**Comment by ahmetalpbalkan** [comment]
@tmds I agree it's not entirely documented. amazonec2 has the same flags (although they're not documented in detail either).

> Does azure-no-public-ip imply azure-use-private-ip?

Yes, it does.

> Are there some tools out there already that use this command to setup machines on azure? or is this a command to execute manually on machine in Azure?

I personally designed this to be executed manually from a bootstrap machine in Azure. Using this you can create a bootstrap VM (with a public IP) on Azure, then let's say:

- you want to create a Swarm cluster
- nodes communicate each other over private IP addresses
- manager nodes are accessible over public IP (coz you wanna manage them from your laptop)

then in that case, you create VM `bootstrap` with a public IP, ssh in there and create other VMs:

- swarm managers: `--azure-use-private-ip`
- swarm nodes: `--azure-use-private-ip  --azure-no-public-ip`

Later on you can delete the `bootstrap` machine and directly use public swarm manager endpoint. I hope it is clearer?

**Comment by tmds** [comment]
Makes sense. Should I leave this issue open as a reminder to improve the documentation?

**Comment by ahmetalpbalkan** [comment]
@tmds I doubt if we need extra docs for those, these are somewhat advanced features.

I may write a blog article about creating a swarm cluster with machine and perhaps explain these arguments there but other drivers don’t go into any more detail either about such arguments. So I think it’s fine for now, I'll let the docs maintainers make the decision.

**Comment by nathanleclaire** [comment]
What is the specific action item for updating the docs in this case?

**Comment by tmds** [comment]
Some suggestions:

Current:
--azure-subnet-prefix: Private CIDR block to be used for the new subnet.
--azure-private-ip-address: Specify a static private IP address for the machine.
--azure-use-private-ip: Use private IP address of the machine to connect.

Proposed:
--azure-subnet-prefix: Private CIDR block. **Used to create subnet if it does not exist. Must match in case subnet exists.**
--azure-use-private-ip: Use private IP address of the machine to connect. **It's useful for managing docker machines from another machine on the same network e.g. while deploying swarm.**
--azure-no-public-ip: Do not create a public IP address for the machine **(implies azure-use-private-ip).**

(Suggestion for azure-use-private-ip comes from the gce driver.)

**Comment by ahmetalpbalkan** [comment]
@tmds I'm open to it. I think these should go to `azure.md`, not `azure.go`, they're too long to be shown in the CLI.

**Comment by tmds** [comment]
@ahmetalpbalkan I am now experimenting with the azure-private-ip-address option. I specify a value which is in the subnet range, but this results in an error message:

```
Error creating machine: Error in driver during machine creation: network/InterfacesClient:CreateOrUpdate 400 Failure responding to request -- Original Error: azure: Service returned an error. Code="P
rivateIPAddressInReservedRange" Message="Private static IP address 10.10.2.1 falls within reserved IP range of subnet prefix 10.10.2.0/24." Status=400
```

Shouldn't the address be in the range of the subnet?

**Comment by ahmetalpbalkan** [comment]
@tmds ah, that's a bit confusing! I think the 3 or 4 lowest IP addresses in each subnet are reserved by Azure Networking for internal purposes, such as gateways etc. Can you please try 10.0.2.5 and above? Here's the doc:  https://azure.microsoft.com/en-us/documentation/articles/virtual-networks-faq/

Relevant documentation:
> ![image](https://cloud.githubusercontent.com/assets/159209/14290765/445dd842-fb15-11e5-8071-71e438b8a1d9.png)

**Comment by tmds** [comment]
@ahmetalpbalkan That could be the issue I have. In the meanwhile I am trying to use an ARM template to configure my azure setup. Thanks for your help.

**Comment by tmds** [comment]
Close per https://github.com/docker/machine/pull/3276
