### ISSUE TITLE
Digital Ocean docker machine image missing kernel flags "cgroup_enable=memory swapaccount=1"

### ISSUE THREAD

**Issue by smithclay** [docker/machine#3254]
According to [Digital Ocean's official twitter account](https://twitter.com/digitalocean/status/537292676740415490), the default Digital Ocean Docker one-click image boots with the kernel flags "cgroup_enable=memory swapaccount=1" to enable container memory profiling.

The docker image used for Digital Ocean and Docker machine should use these flags as well—either a different image should be used or they should be set as part of the configuration of the ubuntu 15.10 image.

**Comment by nathanleclaire** [comment]
Hm, yeah, that would definitely be nice.

**Comment by nathanleclaire** [comment]
Since we use the default DigitalOcean images, this one isn't directly actionable today, but we'll keep it in mind for the future.
