### ISSUE TITLE
Typo in Digital Ocean example

### ISSUE THREAD

**Issue by moxiegirl** [docker/machine#3257]
User reports typo in Digital Ocean:

Hello, unless I am mistaking myself, there's a typo on the following page:
https://docs.docker.com/machine/examples/ocean/

The new docker-sandbox machine is running, and it is the active host as indicated by the asterisk (*). When you create a new machine, your command shell automatically connects it. If for some reason your new machine is not the active host, you’ll need to run docker-machine env aws-sandbox <- (we aren't talking about aws-sandbox here, are we..?) , followed by eval $(docker-machine env docker-sandbox) to connect to it.

**Comment by londoncalling** [comment]
@moxiegirl thanks, this is fixed by PR #3259

**Comment by moxiegirl** [comment]
Thanks.
