### ISSUE TITLE
SSH keys already existing at create time should not be removed by 'rm'

### ISSUE THREAD

**Issue by nathanleclaire** [docker/machine#3261]
See Scott's article for an explanation: http://blog.scottlowe.org//2016/03/31/docker-machine-openstack-ssh-keys/

Essentially, drivers should not remove SSH keys which were not created as part of the `docker-machine create` process.

Ideally, we should vet all existing drivers with this functionality to ensure that they don't have such destructive operations.

OpenStack driver is known to have this bug -- cc @ggiamarchi

**Comment by lowescott** [comment]
Thanks, @nathanleclaire. I searched the GitHub issues before posting that article and _thought_ I found at least one thread where this behavior was acknowledged as "expected" behavior, though it certainly wasn't how I expected it to work.

**Comment by nathanleclaire** [comment]
Yeah, I think I remember the issue you mention, it's possible I may have misunderstood the problem.

**Comment by jmyounker** [comment]
It's surprising behavior.  Horrifyingly surprising behavior.

**Comment by nathanleclaire** [comment]
Thanks for your input @jmyounker.  I'm happy to accept a PR if you'd like to submit a fix.

**Comment by adaikal** [comment]
@nathanleclaire This issue of docker machine deleting the key we pass to it, has really hurt our automation process. We prefer to have one keypair for all the hosts that we provision on openstack.

May I know whether this will be fixed at any point.

I'm a newbie to docker machine, could you please direct me to right path, so that I can give a try of fixing it, if any other is not working on it.

Thank you.

**Comment by nathanleclaire** [comment]
Hi @adaikal, the code for the Openstack driver is here: https://github.com/docker/machine/tree/master/drivers/openstack

You most likely want to implement some kind of check that will not clean up the key if the user specified it explicitly.  (Implementation is up to you -- may need to add some sort of additional parameter to the `Driver` struct to track this information post-create)

@fsoppelsa Might have input on the Openstack-specific bits

**Comment by fsoppelsa** [comment]
@adaikal removing the instance key when a machine is deleted is triggered automatically now, so to keep things in order, I couldn't even find a reason to save it: You can share the same Nova key since Machine 0.6.

**Comment by adaikal** [comment]
@fsoppelsa  The plan was to setup a CaaS cloud and to have all the instances to share same SSH keypair so that sysadmin could use one key for all the instances that get launched.

Now because of machine deleting the keypair on instance creation failure, we have fall back to use machine's default behavior of  having different key for each instance.

**Comment by fsoppelsa** [comment]
@adaikal yes unfortunately I am aware of this... https://github.com/docker/machine/blob/master/drivers/openstack/openstack.go#L445

Adding a flag to `dm rm` so to save keys is a bit out of discussion, cause that is not driver-dependent, like for `dm create -d`. 

Possible:

1. Scan `config.json` of all openstack machines and save if there are identical `KeyPairName` (but if machines are created or removed from different hosts, that's a problem, ohi ohi)
2. DO NOT remove keys by default
3. Add a boolean field in `config.json` in `Driver`, specifying not to remove the key

**Comment by jrandall** [comment]
The fix in #3969 seems reasonable - as it is now even having the `--openstack-keypair-name` is dangerous - the documentation leads one to think that it is supported to have docker-machine use an existing keypair, but then - SURPRISE! - when you remove a docker-machine, it removes the keypair making all future instance creations that need that keypair (whether in docker-machine or not) fail. 

Is there something standing in the way of getting #3969 merged so we can (at least) explicitly disable that behaviour?

**Comment by dtitov** [comment]
Hi! What about this issue? I have just the same and it's reeeeeeeally annoying :(

**Comment by davidarcher** [comment]
I've opened a new PR to fix this behavior in the openstack driver.
https://github.com/docker/machine/pull/4358
