### ISSUE TITLE
Unable to create machine at digitalocean using existing key

### ISSUE THREAD

**Issue by michaelkrog** [docker/machine#3262]
I am having issues using this digitalocean-ssh-key-fingerprint. I am uncertain if I am doing something wrong.

Related to #1445 

I create a machine like this:
```bash
docker-machine --debug create --driver digitalocean --digitalocean-access-token xxxxx --digitalocean-size 1gb --digitalocean-region ams2 --digitalocean-image 2321312 --digitalocean-ssh-user devops --digitalocean-ssh-key-fingerprint "04:1e:b1:c4:96:40:14:26:cf:cb:13:df:68:f2:af:13" docker-test
```

It creates the machine, but fails when it comes to establishing the SSH connection. Full debug output:

> Docker Machine Version:  0.7.0-rc1, build 0fb68ca
> Found binary path at /usr/local/bin/docker-machine
> Launching plugin server for driver digitalocean
> Plugin server listening at address 127.0.0.1:33228
> () Calling .GetVersion
> Using API Version  1
> () Calling .SetConfigRaw
> () Calling .GetMachineName
> (flag-lookup) Calling .GetMachineName
> (flag-lookup) Calling .DriverName
> (flag-lookup) Calling .GetCreateFlags
> Found binary path at /usr/local/bin/docker-machine
> Launching plugin server for driver digitalocean
> Plugin server listening at address 127.0.0.1:36842
> () Calling .GetVersion
> Using API Version  1
> () Calling .SetConfigRaw
> () Calling .GetMachineName
> (previsto-test) Calling .GetMachineName
> (previsto-test) Calling .DriverName
> (previsto-test) Calling .GetCreateFlags
> (previsto-test) Calling .SetConfigFromFlags
> Running pre-create checks...
> (previsto-test) Calling .PreCreateCheck
> (previsto-test) Calling .GetConfigRaw
> Creating machine...
> (previsto-test) Calling .Create
> (previsto-test) Creating SSH key...
> (previsto-test) Creating Digital Ocean droplet...
> (previsto-test) Waiting for IP address to be assigned to the Droplet...
> (previsto-test) Calling .GetConfigRaw
> (previsto-test) DBG | Created droplet ID 12642079, IP address 82.196.14.245
> (previsto-test) Calling .DriverName
> (previsto-test) Calling .DriverName
> Waiting for machine to be running, this may take a few minutes...
> (previsto-test) Calling .GetState
> (previsto-test) Calling .GetState
> (previsto-test) Calling .GetState
> (previsto-test) Calling .GetState
> (previsto-test) Calling .GetState
> (previsto-test) Calling .GetState
> (previsto-test) Calling .GetState
> (previsto-test) Calling .GetState
> (previsto-test) Calling .GetState
> (previsto-test) Calling .GetState
> (previsto-test) Calling .GetState
> (previsto-test) Calling .GetState
> Detecting operating system of created instance...
> Waiting for SSH to be available...
> Getting to WaitForSSH function...
> (previsto-test) Calling .GetSSHHostname
> (previsto-test) Calling .GetSSHPort
> (previsto-test) Calling .GetSSHKeyPath
> (previsto-test) Calling .GetSSHKeyPath
> (previsto-test) Calling .GetSSHUsername
> Using SSH client type: external
> &{[-o BatchMode=yes -o PasswordAuthentication=no -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=quiet -o ConnectionAttempts=3 -o ConnectTimeout=10 -o ControlMaster=no -o ControlPath=none devops@82.196.14.245 -o IdentitiesOnly=yes -i /var/lib/jenkins/.docker/machine/machines/docker-test/id_rsa -p 22] /usr/bin/ssh <nil>}
> About to run SSH command:
> exit 0
> SSH cmd err, output: exit status 255: Warning: Identity file /var/lib/jenkins/.docker/machine/machines/docker-test/id_rsa not accessible: No such file or directory.
> 
> Error getting ssh command 'exit 0' : Something went wrong running an SSH command!
> command : exit 0
> err     : exit status 255
> output  : Warning: Identity file /var/lib/jenkins/.docker/machine/machines/docker-test/id_rsa not accessible: No such file or directory.
>

**Comment by nathanleclaire** [comment]
cc @bamarni

**Comment by bamarni** [comment]
I could reproduce, it seems to be failing now that we have better validation for the private key (#3235). We probably shouldn't set this path in the driver config when using `--digitalocean-ssh-key-fingerprint`, as it's irrelevant. I've just submitted a patch (#3265) and tested it with this command :

    docker-machine --debug create --driver digitalocean --digitalocean-access-token XxX --digitalocean-size 512mb --digitalocean-region fra1 --digitalocean-image ubuntu-14-04-x64 --digitalocean-ssh-key-fingerprint "64:51:2b:9b:8b:f0:95:3c:f9:36:4d:8b:80:a8:8f:1e" docker-test

@michaelkrog : I can see a custom "devops" user, are you creating this droplet from a snapshot you made? If it's the case I think you'd also have to authorize the key for that user in the snapshot itself.

**Comment by michaelkrog** [comment]
@bamarni : Yes, it is from a custom 14.04 image which we have secured like this:

1. No root login via SSH
2. Only port 80, 443, 2376 and 3376 is allowed in firewall
3. A devops user has been created with an authorized key, but not password-less sudo.

We then registered the public key for devops in digitalocean and used its fingerprint with `--digitalocean-ssh-key-fingerprint`

**Comment by bamarni** [comment]
> A devops user has been created with an authorized key, but not password-less sudo.

This might be problematic as docker-machine requires root privileges for the provisioning part. An alternative could be to allow password-less sudo for `devops` in your snapshot, and once your create command is finished to revoke it.

**Comment by michaelkrog** [comment]
Ahh, yes of course. I better fix that. (y)  

Thx @bamarni

**Comment by nathanleclaire** [comment]
Are we good to close this issue?

**Comment by michaelkrog** [comment]
@nathanleclaire I'll try it out today and post my result here.

**Comment by michaelkrog** [comment]
Woops. Wrong button 😐

**Comment by michaelkrog** [comment]
@nathanleclaire I am too inexperienced with Golang. I didnt manage to build it locally and were therefore unable to test it. Sorry.

**Comment by bamarni** [comment]
@michaelkrog: There are instructions here https://github.com/docker/machine/blob/master/CONTRIBUTING.md

But actually looking at your output again it seems to be more of a ssh misconfiguration. Your path is not the default one (/var/lib/jenkins), are you running your command in a CI or something? If you put your private key in the default location (~/.ssh/id_rsa) for that user it should work, not sure if it's "jenkins" or another one.

**Comment by michaelkrog** [comment]
@bamarni Sorry for taking so long to get back on this.

You were absolutely correct. I still get a lot of warnings like this:
> Warning: Identity file /var/lib/jenkins/.docker/machine/machines/docker-test/id_rsa not accessible: No such file or directory.

...but it seems to work fine after I fixed my private key! :-)

**Comment by bamarni** [comment]
Cool, and warnings should be gone in 0.7.0 stable ;)
