### ISSUE TITLE
Unable to create machines - getsockopt: connection refused

### ISSUE THREAD

**Issue by mabn** [docker/machine#3267]
I can't get machine creation to work - every time try I get: "getsockopt: connection refused".
I tried reinstalling whole docker toolbox, virtualbox, tried docker-machine 0.7.0-rc1, 0.6.0, 0.5.6 - same results. There are no logs under ~/.docker/machine, the only file there is boot2docker.iso

```
mabn@Marcins-MacBook-Pro:/Applications/Docker$ docker-machine --debug create -d virtualbox
Docker Machine Version:  0.7.0-rc1, build 0fb68ca
Found binary path at /usr/local/bin/docker-machine
Launching plugin server for driver virtualbox
Plugin server listening at address 127.0.0.1:51114
dial tcp 127.0.0.1:51114: getsockopt: connection refused
mabn@Marcins-MacBook-Pro:/Applications/Docker$
```

Kitematic displays similar error message:

> Command failed: /usr/local/bin/docker-machine -D create -d virtualbox --virtualbox-memory 2048 default,Docker Machine Version: 0.7.0-rc1, build 0fb68ca,Found binary path at /usr/local/bin/docker-machine,Launching plugin server for driver virtualbox,Plugin server listening at address 127.0.0.1:51184,dial tcp 127.0.0.1:51184: getsockopt: connection refused,

There is something listening on the port because:
```
docker-ma 3291 mabn    4u  IPv4 0x7496dcc7ff4e7e1      0t0  TCP 127.0.0.1:50680->127.0.0.1:50679 (SYN_SENT)
docker-ma 3292 mabn    3u  IPv4 0x7496dcc84ac27e1      0t0  TCP 127.0.0.1:50679 (LISTEN)
```

I also tried to manually create a vm and add it using generic driver - it fails as well:
```
mabn@Marcins-MacBook-Pro:~/.ssh$ docker-machine create --driver generic --generic-ip-address=192.168.59.100 --generic-ssh-key=~/.ssh/id_rsa --generic-ssh-user=ubuntu vm
dial tcp 127.0.0.1:54731: getsockopt: connection refused
mabn@Marcins-MacBook-Pro:~/.ssh$ ssh ubuntu@192.168.59.100 hostname
ubuntu-amd64
mabn@Marcins-MacBook-Pro:~/.ssh$
```

What am I doing wrong?

(I'm on OS X Yosemite 10.10.5)

**Comment by nathanleclaire** [comment]
What's listening on the port is the Machine plugin server (Machine invokes a plugin server and runs commands from that, it's how we support 3rd party drivers).  But, I'm not sure why it's refusing to connect in your case.

**Comment by nathanleclaire** [comment]
Any restrictive, or oddball network configuration on your machine?

**Comment by mabn** [comment]
I see nothing odd - no VPN, I turned off firewall during testing. Besides docker-machine everything seems to be ok.

**Comment by mabn** [comment]
After some investigation it seems that in general Go has some issues on my machine (see: http://stackoverflow.com/questions/36532359/go-http-server-does-not-work-on-osx) so this issue can be closed.
