### ISSUE TITLE
generic ssh key 'Too many retries waiting for SSH to be available.'

### ISSUE THREAD

**Issue by BraunreutherA** [docker/machine#3268]
Hi, when I use docker-machine for provisioning a remote host and set a ssh key with `--generic-ssh-key ~/.ssh/id_rsa` I get the following error `Error creating machine: Error detecting OS: Too many retries waiting for SSH to be available.  Last error: Maximum number of retries (60) exceeded`. When I don't set the --generic-ssh-key flag it works. I even tried to place the ssh key on another path which didn't work aswell.

**Comment by bamarni** [comment]
Hi,

Does your key has a passphrase? I suspect this to be partly related to #3306. The rest should be fixed with #3330.

But as you noticed, the `--generic-ssh-key` flag is not necessary in your case because it's the default location anyway.

**Comment by BraunreutherA** [comment]
Ah that's the error. My key is password protected.

**Comment by nathanleclaire** [comment]
@BraunreutherA If you're feeling ambitious, would be good to get you to try a master build (now containing @bamarni's fix) and see if it fixes your issue.

**Comment by bamarni** [comment]
@nathanleclaire did you already consider having nightly builds available? That could help in such situations.

**Comment by nathanleclaire** [comment]
@bamarni We've considered it at various times and even had unofficial ones available but so far haven't set up the infrastructure to support it.  In the future the Docker projects are intended to share more infrastructure to (hopefully) have a common set of interfaces to things like nightlies, but we aren't sure when that will shape up.

**Comment by bamarni** [comment]
cool 👍

**Comment by npcode** [comment]
I have the same problem with latest master.

```
$ ~/bin/docker-machine version
docker-machine version 0.7.0, build ae9f392
$ ~/bin/docker-machine create --driver generic --generic-ip-address=11.111.111.16  node1                                                                                                                        
Running pre-create checks...
Creating machine...
(node1) No SSH key specified. Assuming an existing key at the default location.
Waiting for machine to be running, this may take a few minutes...
Detecting operating system of created instance...
Waiting for SSH to be available...
Error creating machine: Error detecting OS: Too many retries waiting for SSH to be available.  Last error: Maximum number of retries (60) exceeded
```

It does not work even if I give ssh key explicitly:
```
$ ~/bin/docker-machine create --driver generic --generic-ip-address=11.111.111.16 --generic-ssh-key=$HOME/.ssh/id_rsa  node3
Running pre-create checks...
Creating machine...
(node3) Importing SSH key...
Waiting for machine to be running, this may take a few minutes...
Detecting operating system of created instance...
Waiting for SSH to be available...
Error creating machine: Error detecting OS: Too many retries waiting for SSH to be available.  Last error: Maximum number of retries (60) exceeded
```

**Comment by npcode** [comment]
Okay, now I know what's the problem. docker-machine tried to connect the host with `root` user but my ssh key has no permission to do that.

It would be nice if docker-machine supports nonroot sudoer.

**Comment by bamarni** [comment]
It already does : `--generic-ssh-user` :)

**Comment by npcode** [comment]
@bamarni Thank you for letting me know!

**Comment by holms** [comment]
I have no idea why this been solved like this, but I've removed --generic-ssh-user parameter and it started to work )

**Comment by Dayjo** [comment]
@holms I solved this by ADDING the `--generic-ssh-user` parameter 😆

**Comment by rcadhikari** [comment]
Refer https://github.com/boot2docker/boot2docker/issues/1362#issuecomment-442842774

**Comment by rcadhikari** [comment]
Refer https://github.com/boot2docker/boot2docker/issues/1362#issuecomment-442842774
