### ISSUE TITLE
Error creating and then host already exists issue

### ISSUE THREAD

**Issue by MaerF0x0** [docker/machine#3271]
I was using the amazon driver to create machines and then hit my instance cap, the return message was 
```
Error creating machine: Error in driver during machine creation: Error launching instance: InstanceLimitExceeded: Your quota allows for 0 more running instance(s). You requested at least 1
	status code: 400, request id:
```

however docker machine now thinks those nodes (with name eg node0, node1 ) are created and refuses to make them again.  I am able to `dockermachine rm -f ` them though, so kinda nbd, maybe we should allow recreation of failed nodes though?

**Comment by nathanleclaire** [comment]
Ideally I'd like to be able to "apply" from scratch but it's not possible to do safely today.  We'll keep it in mind for the future, though.
