### ISSUE TITLE
While creating a docker-machine hangs at Waiting for an IP 

### ISSUE THREAD

**Issue by DruvaRam** [docker/machine#3279]
Hello, I am getting the following error when i try to create a docker-machine
 `root@vagrant-ubuntu-trusty-64:/home/vagrant# docker-machine create --driver virtualbox --virtualbox-no-vtx-check true`
`Running pre-create checks...`
`(true) You are using version 4.3.36_Ubuntur105129 of VirtualBox. If you encounter issues, you might want to upgrade to version 5 at https://www.virtualbox.org`
`(true) Image cache directory does not exist, creating it at /root/.docker/machine/cache...`
`(true) No default Boot2Docker ISO found locally, downloading the latest release...`
`(true) Latest release for github.com/boot2docker/boot2docker is v1.11.0-rc3`
`(true) Downloading /root/.docker/machine/cache/boot2docker.iso from https://github.com/boot2docker/boot2docker/releases/download/v1.11.0-rc3/boot2docker.iso...`
`(true) 0%....10%....20%....30%....40%....50%....60%....70%....80%....90%....100%`
`Creating machine...`
`(true) Default Boot2Docker ISO is out-of-date, downloading the latest release...`
`(true) Latest release for github.com/boot2docker/boot2docker is v1.11.0-rc3`
`(true) Downloading /root/.docker/machine/cache/boot2docker.iso from https://github.com/boot2docker/boot2docker/releases/download/v1.11.0-rc3/boot2docker.iso...`
`(true) 0%....10%....20%....30%....40%....50%....60%....70%....80%....90%....100%`
`(true) Copying /root/.docker/machine/cache/boot2docker.iso to /root/.docker/machine/machines/true/boot2docker.iso...`
`(true) Creating VirtualBox VM...`
`(true) Creating SSH key...`
(true) Starting the VM...
`(true) Check network to re-create if needed...`
(`true) Found a new host-only adapter: "vboxnet0"`
`(true) Waiting for an IP...`
`Error creating machine: Error in driver during machine creation: Too many retries waiting for SSH to be available.  Last error: Maximum number of retries (60) exceeded`

**I am trying to run this on ubuntu 14.04 LTS.**

When i run the command `docker-machine ls`, the output is

NAME   ACTIVE   DRIVER       STATE     URL   SWARM   DOCKER    ERRORS
true         *           virtualbox       Running             Unknown   Something went wrong running an SSH command!
command : ip addr show
err     : exit status 255
output  :

Anyone faced this problem before??

docker-machine version 0.7.0-rc2, build 60dbecb

**Comment by nathanleclaire** [comment]
Generally, nested virtualization does not work in VirtualBox.  Also, Machine is largely targeted at VirtualBox latest (currently, 5.0.16), so you might want to try upgrading to that.

**Comment by DruvaRam** [comment]
@nathanleclaire 
I have updated VirtualBox to latest version. Even then am not able to create one. When i remove `--virtualbox-no-vtx-check` flag it gives me the following error - 

`Running pre-create checks...
Error with pre-create check: "This computer doesn't have VT-X/AMD-v enabled. Enabling it in the BIOS is mandatory"`

When i include the flag `--virtualbox-no-vtx-check` it hangs at the same point saying "Waiting for an IP".

**Comment by nathanleclaire** [comment]
As the error message says, virtualization is not enabled, so it is impossible for the VirtualBox driver to work properly.  As I said already, [nested virtualization is really just not a feature supported by VirtualBox](https://www.virtualbox.org/ticket/4032).  I don't think what you're trying to do is possible, and even if it was it'd be incredibly slow.  Why not just run Docker directly on the existing VM, or use Docker Machine on your original host computer?
