### ISSUE TITLE
Docker container volume doesn't write to Ubuntu host

### ISSUE THREAD

**Issue by zavalit** [docker/machine#3280]
Hi guys,  i try to generate some assets within a docker container and put it to a host. All that is running within a docker-machine environment initialised with virtualbox driver.

for example i run:
    
    docker run -it -v $PWD/testfolder:/var/www:rw ubuntu /bin/bash

and then 

    root@b9e73827bc3c:/var/www touch dummy.txt

from that point i actually have to see ```dummy.txt``` in my host's ```$PWD/testfolder``` folder, but there is neither a folder **testfolder** nor ***dummy.txt*** in it(logicly). 

The weired thing, the same setup works correct on MacOSX and creates files on a host end, but when i tried it Ubuntu:14.04 it stopped working.
here are both container ```inspect``` on

-  MacOSX host: https://gist.github.com/zavalit/65e8a260866f834223616c1b59e4ce7d
-  Ubuntu:14.04 host: 
https://gist.github.com/zavalit/40bd3ce8629ad81fcd6793ca63f99491

as far as i can see, they are both quite identical.

it tried it with both docker-machine version 0.7.0-rc2 and 0.6.0, docker version is 1.10.3

**Comment by zavalit** [comment]
another thing. 
also, when i run container with ```--rm```
like:
     docker run --rm -it -v $PWD/testfolder:/var/www:rw ubuntu /bin/bash

and exit it, then run a new again with the same command, i see all created files in container's ***/var/www*** folder.

**Comment by nathanleclaire** [comment]
So on Ubuntu, you see nothing in `/opt/projects/phping.me/test` after you write to the volume in the container?

**Comment by nathanleclaire** [comment]
This isn't a Machine issue, but is your problem that you are expecting the host mount to be a different directory than it actually is?

**Comment by zavalit** [comment]
i run absolutely the same commands for the same images on both MacOSx and Ubuntu hosts, on MacOSx it works, on Ubuntu not.

to your questions:
> *you see nothing in /opt/projects/phping.me/test after you write to the volume in the container*

yes, there is nothing on a host side?

> *is your problem that you are expecting the host mount to be a different directory than it actually is?*

the directory path on a host is ***/opt/projects/phping.me/test*** and on a container is ***/var/www***, in that way, yes, they are different. but how that could be a problem, i just mount my host directory to container's one and expect, that if i create a file in container's ***/var/www*** then it have to be found also under  ***/opt/projects/phping.me/test*** on a host side.

**Comment by nathanleclaire** [comment]
> the directory path on a host is /opt/projects/phping.me/test and on a container is /var/www, in that way, yes, they are different. but how that could be a problem, i just mount my host directory to container's one and expect, that if i create a file in container's /var/www then it have to be found also under /opt/projects/phping.me/test on a host side.

Yes, that's how bind mounts are intended to work.  What I meant was, due to your use of `$PWD`, have you verified with 100% that `/opt/projects/phping.me/test` is the directory you are actually checking on the host that you are checking for file persistence?

Can you verify that the following does not work on your Ubuntu instance?  This should quickly verify that bind mounts are working as intended.

```console
$ docker run -v /opt/projects/phping.me:/var/www -ti alpine sh -c 'echo hello >/var/www/hello'
$ cat /opt/projects/phping.me/hello
hello
```

If that works OK, can you please provide the exact set of steps to reproduce this issue?

**Comment by zavalit** [comment]
hi nathanleclaire, first of all thx for getting back to it.

i runed 

    $ docker run -v /opt/projects/phping.me:/var/www -ti alpine sh -c 'echo hello >/var/www/hello'

and it's still empty

    cat: /opt/projects/phping.me/hello: No such file or directory


also ```chmod a+w /opt/projects/phping.me``` didn't bring much.


and weird is,  when i run:

    $ docker run -v /opt/projects/phping.me/test:/var/www -ti alpine sh -c 'ls -la /var/www'

i get:

    total 8
    drwxr-sr-x    2 root     50              60 Apr 13 12:19 .
    drwxr-xr-x   11 root     root          4096 Apr 13 12:26 ..
    -rw-r--r--    1 root     50               6 Apr 13 12:20 hello

container's volume is still alive and just for the sake of double checking there is no ```/var/www```directory neither on ubuntu host nor on boot2docker VM.

**Comment by nathanleclaire** [comment]
That is quite surprising.  You're running all of these commands in the same shell?  What's the output of `docker inspect`-ing the container with the bind mount?

**Comment by nathanleclaire** [comment]
Hm, I just realized that I may have been assuming (incorrectly) that you were running Docker natively on Linux, not through Docker Machine.  Are you aware that shared folders are not currently supported for Docker Machine on Linux?

**Comment by zavalit** [comment]
jo, i didn't knew it( that shared folders are not currently supported),
is there a plan to provide it also for Linux, it is quite handy to organize projects on a VM base within a single server, especially when your are dealing with a range of MVP like me, and want to stay as lean as possible.

anyway, thank you for getting into it.
