### ISSUE TITLE
Docker won't mount my host directory

### ISSUE THREAD

**Issue by GGross5213** [docker/machine#3283]
It has been several months since I have used docker but I used to be able to run my container and mount my local directory to the container like ```docker run -itp 8080:5000 --name web -v /c/Users/<path to app>:/src <docker image name>``` Where /c/Users/<path to app> is the absolute path to where my application lives on my machine. I don't know if something has changed or if I didn't remember how to do it correctly, but I keep getting an error message : ```invalid value "C:\\Users\\<path to app>;C:\\Program Files\\Git\\src" for flag -v: bad mode specified: \Program Files\Git\src```. I am running on windows 10. I have no idea what I am doing wrong

**Comment by nathanleclaire** [comment]
It seems to be git bash path translation gone wrong unfortunately.  If you wrap the `-v` argument in single or double quotes does it work?

**Comment by GGross5213** [comment]
Yeah I have tried putting quotes around ```"-v  /c/Users/<path to app>:/src"``` as well as ```-v "/c/Users/<path to app>:/src"``` and I am still getting the same error.

**Comment by nathanleclaire** [comment]
Setting `MSYS_NO_PATHCONV` environment variable to `1` should do the trick.

[The Quickstart Terminal does this for you automatically](https://github.com/docker/toolbox/blob/7a62610b878fc3920288de3059dd06560cb276a9/windows/start.sh#L83), but it had slipped my mind until now.

Thanks

**Comment by GGross5213** [comment]
So this worked, but what I am curious about is that I was using the Docker Quickstart Terminal. So, why did I have to manually set the environment variable to 1?

**Comment by nathanleclaire** [comment]
@GGross5213 You're using the latest version?

**Comment by GGross5213** [comment]
Ahh, I am not. I am on 1.9.1.
