### ISSUE TITLE
docker-machine ignores --swarm-opt for swarm agent

### ISSUE THREAD

**Issue by LBaali** [docker/machine#3285]
docker-machine seems to take into account the `--swarm-opt` arbitrary options only if `--swarm-master` is specified.

This blocks me when trying to configure a swarm agent with TLS discovery.

Full command line :
```
docker-machine create --driver generic --swarm \
--swarm-opt="discovery-opt=\"kv.keyfile=/etc/docker/server-key.pem\"" \
--swarm-opt="discovery-opt=\"kv.certfile=/etc/docker/server.pem\"" \
--swarm-opt="discovery-opt=\"kv.cacertfile=/etc/docker/ca.pem\"" \
--swarm-discovery consul://discovery:8500  \
--engine-opt="cluster-store=consul://discovery:8500" \
--engine-opt="cluster-advertise=myip:2376" \
--engine-opt="cluster-store-opt=\"kv.keyfile=/etc/docker/server-key.pem\"" \
--engine-opt="cluster-store-opt=\"kv.certfile=/etc/docker/server.pem\"" \
--engine-opt="cluster-store-opt=\"kv.cacertfile=/etc/docker/ca.pem\"" \
--engine-label "type=node" \
--generic-ip-address  myip   mymachine
```

With this configuration, the engine manages to connect to the consul through TLS but the swarm agent tries to connect without TLS.
Result of `docker inspect swarm-agent` :

```
"Args": [
            "join",
            "--advertise",
            "195.154.47.76:2376",
            "consul://discovery:8500"
        ]
```

`docker-machine --version `
`docker-machine version 0.6.0, build e27fb87`

**Comment by nathanleclaire** [comment]
It's intentional (historically there wasn't as much reason to want such a feature), but should be relatively simple to remedy by modifying the Swarm provisioning code.

**Comment by LBaali** [comment]
Thanks for the reply,
I tried a small modification in the provisioning code but now I realized I also need to mount the /etc/docker volume for swarm-node. This seems like a much bigger change with more implications.

Is there another way for me to work with docker-machine for this particular use-case ? I can set it up myself over ssh but docker-machine seems like a better way to do it.
