### ISSUE TITLE
AWS driver has wrong --amazonec2-device-name default for some AMI/instances

### ISSUE THREAD

**Issue by avuserow** [docker/machine#3293]
When running a m3.medium machine and AMI ami-818eb7b1 (Debian 8 on us-west-2), I must manually override `--amazonec2-device-name` or it won't boot. Full command line which works: `docker-machine --debug create -d amazonec2 --amazonec2-instance-type m3.medium --amazonec2-ami ami-818eb7b1 --amazonec2-device-name /dev/xvda --amazonec2-ssh-user admin ak-aws1` . Removing the device-name option causes it to boot up, then shut itself down at some point, and AWS provides no console output at all.

I've seen this on 0.7.0 RC1.

**Comment by nathanleclaire** [comment]
How would Machine know the proper device name to use ahead of time?  Parameters such as `--amazonec2-ami` usually expect that the user also sets things like `--amazonec2-ssh-user` correctly, e.g. to `admin` if using a Debian AMI instead of Ubuntu.

**Comment by nathanleclaire** [comment]
I'm going to go ahead and close the issue, since I don't think there's anything we can do Machine-side to detect this automatically. However, we're open to suggestions if you have them.

**Comment by avuserow** [comment]
Yeah I was hoping that we could key this off of something like the instance generation but it looks like it's not that simple. Thanks for taking a look.

**Comment by nathanleclaire** [comment]
I think we might be able to make a call equivalent to http://docs.aws.amazon.com/cli/latest/reference/ec2/describe-images.html (`describe-images`) before creating, however I think that should be filed as an enhancement request since that's more where it falls into (additional `create` magic).
