### ISSUE TITLE
Can't resolve mDNS address with Machine

### ISSUE THREAD

**Issue by sneak** [docker/machine#3297]
I am using multicast dns `.local` hostnames via `avahi-daemon` and docker-machine doesn't seem to find them when trying to make TLS connections.  Replacing the `build.local` hostname with the IP address connects, but then fails TLS validation because of the lack of an IP-based SAN in the cert.

I have `libnss-mdns` installed and other tools like `ping` and such work fine for reaching the host.

**Comment by nathanleclaire** [comment]
This smells a lot like a likely Go vs. cgo problem to me.

**Comment by nathanleclaire** [comment]
i.e. non-cgo won't do mdns lookups.

**Comment by sneak** [comment]
Do non-cgo apps have no way of calling into libnss?

**Comment by nathanleclaire** [comment]
No, unfortunately.  The pure Go resolver doesn't use any system libraries.

**Comment by sneak** [comment]
This issue might not be the right place to discuss this, but is it (the pure Go resolver) *unable* to do so, or does it just choose not to?  I'm not sure how pure Go->c lib calling works.  I personally would consider this a Go stdlib bug if pure-Go apps *can* call into libnss to find out how local resolution works and simply aren't.

**Comment by nathanleclaire** [comment]
That's the exact problem, unfortunately.  In order to access native C libraries, you _have to_ use cgo, which we don't (it makes cross-compilation much more difficult and has a variety of other tradeoffs).

**Comment by sneak** [comment]
There's no ffi for non-cgo?!

**Comment by nathanleclaire** [comment]
That's correct.

**Comment by sneak** [comment]
Ok, wow.  Thanks for the educational detour, I'll stop spamming the thread now. 🙇

**Comment by nathanleclaire** [comment]
Heh... No problem.

**Comment by sneak** [comment]
Ok, I lied about spamming the thread anymore with questions. :)

If you have the time, could you link me or give me googleable terms for the "variety of other tradeoffs"?  Other than complicating the build process (which, imho, if you're doing name resolution on unix, is unavoidable as nsswitch.conf is really part of the system's security configuration) I'm trying to better understand the design.

**Comment by nathanleclaire** [comment]
> Ok, I lied about spamming the thread anymore with questions. :)

;P

Dave Cheney summarizes the main points very well here: http://dave.cheney.net/2016/01/18/cgo-is-not-go

**Comment by nathanleclaire** [comment]
BTW, if on a Mac I think if you install Docker Machine with Homebrew you get a version that uses the native system resolver (cgo).  You might want to try that -- usually I recommend the official install but if you really want mDNS resolution that might fix it.

**Comment by sneak** [comment]
Considering that machine disables SSH key fingerprint checking, you don't consider "ignoring local system resolver settings" to be a security-related bug?

**Comment by nathanleclaire** [comment]
> Considering that machine disables SSH key fingerprint checking, you don't consider "ignoring local system resolver settings" to be a security-related bug?
> Someone on the LAN able to spoof DNS replies could send you an IP of a proxy for <whatever>.local and intercept/modify your SSH session.

I'm confused by this.  I thought the issue was that `*.local` wouldn't resolve at all.

**Comment by sneak** [comment]
It is my assumption that it is ignoring the system nsswitch.conf file, defaulting to the go resolver, which of course does not resolve .local as it is not a valid TLD.

If necessary, I can capture traffic on the machine to verify that it's trying to look up .local hostnames in traditional DNS to verify the security implication.  Shall I?

**Comment by sneak** [comment]
This may be relevant: https://github.com/golang/go/issues/14354

**Comment by nathanleclaire** [comment]
Interesting, thanks for the info.  At any rate, personally I'm not happy with the current insecure SSH behavior, so I was hoping to introduce some fixes soon.

**Comment by sneak** [comment]
Well, for new host setup, it's still TOFU (trust on first use) so there's really no good way to authenticate it.

**Comment by nathanleclaire** [comment]
Yeah, but TOFU would be better than TOEU
