### ISSUE TITLE
How to open port 4000 for swarm manager via docker-machine create

### ISSUE THREAD

**Issue by phlegx** [docker/machine#3303]
In the tutorial "[Build a Swarm cluster for production](https://docs.docker.com/swarm/install-manual/)" The first/primary Swarm manager is started with port 4000 open:

``` $ docker run -d -p 4000:4000 swarm manage -H :4000 --replication --advertise <manager0_ip>:4000 consul://<consul_ip>```

Now I'm wondering if I can also do that via ```docker-machine create```. I'm currently using version ```0.7.0-rc2``` But I didn't really find a flag that can open the 4000 port for the swarm manager.

Can someone tell me if and how this is possible?

**Comment by nathanleclaire** [comment]
I think it might be possible with `--swarm-address` flag.  Did you try setting that to `tcp://0.0.0.0:4000`?  (note: some code might go kinda wacky in machine due to hardcoding of port 3376)

**Comment by nathanleclaire** [comment]
But at any rate, why not just use the default of `:3376`?

**Comment by phlegx** [comment]
Hi @nathanleclaire thanks for the hints.

I've tried to use ```--swarm-address``` but I haven't had success with that. I will try it again with my new setup and report you back.

Hmm. I have to admit that this port stuff confuses me a lot... As stated in the tutorial  "[Build a Swarm cluster for production](https://docs.docker.com/swarm/install-manual/)" it is two Swarm managers in a **high-availability configuration** and the first manager the primary one has 4000 open therefore.  So I assume this is a port that is required by the management nodes, and not by the swarm itself. Is Port :3376 really just the default one or is this 4000 port they open something else? And if it is the default one, why did they use the 4000 port in first place?^^

In any case also if I would use the "default port", I still would need to open it, according to the tutorial. So wouldn't the question still remain on how to do that via machine?

**Comment by phlegx** [comment]
What I can say now is that via ```--swarm-host "tcp://0.0.0.0:3376"``` the port is not opened for the swarm manager. I just tried it out.

**Comment by phlegx** [comment]
When I try to connect to the secondary master via machine via 

```eval $(docker-machine env --swarm swarm-manager1)```

and the then try a ```docker ps``` I experience this error:

```Error response from daemon: Unable to reach primary cluster manager (dial tcp 192.168.122.149:4000: getsockopt: connection refused): 192.168.122.149:4000```

This is of course because the Port is not open.  A ```docker info``` however works just fine also on the secondary swarm master. 

On the primary swarm master a ```docker ps``` just works as expected.

**Comment by phlegx** [comment]
Oh I just saw that you meant to use the ```--swarm-address``` aka ```--swarm-addr``` and not the the ```--swarm-host``` parameter. I mistakenly used the latter one first.

I now tried with ```--swarm-addr "tcp://0.0.0.0:3376"``` and ```--swarm-addr "tcp://0.0.0.0:4000"```, however both are unfortunately not opening a port.

**Comment by nathanleclaire** [comment]
Oh yes, sorry about that, I meant `--swarm-host`.  (Unrelated whimsical sidenote:  It always makes me think of [this Starcraft 2 unit](http://wiki.teamliquid.net/starcraft2/Swarm_Host_(Legacy_of_the_Void))).

Unfortunately using Swarm master on non-standard ports is not well supported today, but I would like to enable it.  The pretty difficult bit is that any provider-specific firewall, e.g. Amazon Security Groups, have to be configured to allow inbound access on that port.  This has to be handled by every driver individually :(

**Comment by phlegx** [comment]
Hehe! OK now I also know how ```--swarm-host``` looks like :-) :-) That surely helps me remembering it^^

So currently there can be no port opened via ```docker-machine``` just like the 4000 or 3376  one for swarm? Did I understand that correctly @nathanleclaire ?

That the firewall needs to allow that access is pretty much clear. But I was thinking this is something that should be done manually, or not?
