### ISSUE TITLE
updating installation using toolbox installer is _not_ possible

### ISSUE THREAD

**Issue by pmario** [docker/machine#3304]
Every release note since 0.6.0 shows this message:

>If you're a Mac or Windows user, the Docker Toolbox will install Docker Machine v0.7.0 for you, alongside the latest versions of the Docker Engine, Compose and Kitematic.

which is actually not true, as long as the [toolbox installer isn't fixed](https://github.com/docker/toolbox/issues/349)!

The installer just doesn't let you select, the elements, that need to be installed!

**Comment by nathanleclaire** [comment]
Thanks for the issue.  Please open an issue on Toolbox or comment there.  The installer _will_ install those components, even if there is an issue installing them a la carte.
