### ISSUE TITLE
New Release ......updating (Docker-Machine / Engine)

### ISSUE THREAD

**Issue by Delpedro** [docker/machine#3305]
Hi,

I have 3/4 exiting VMs - all created via Virtualbox. They will not update after the user has downloaded the latest version of Docker Toolbox, still showing version as v1.10.3

When I create a new node, which works fine and is version v1.11.0

VMs / Nodes created using Virtualbox do not have access to apt-get, therefore they cannot be updated and other packages cannot be installed on the node. Is this correct? Is there a way around this? Or am I incorrect in my statement?

Thanks.
Del.

**Comment by nathanleclaire** [comment]
@Delpedro, `docker-machine upgrade vmname` does not work?

**Comment by nathanleclaire** [comment]
To upgrade a boot2docker VM, the process is to download a new ISO, then powercycle the machine, which is what `upgrade` does.  Please re-open if this does not work.
