### ISSUE TITLE
"exit status 255" on docker-machine ssh (when ssh key not yet in ssh-agent)

### ISSUE THREAD

**Issue by brettdh** [docker/machine#3306]
Description of problem:

`docker-machine ssh` run after mac startup fails, seemingly because my passphrase-protected SSH key hasn't been added to the auth agent. After the first manual SSH with this key, `docker-machine ssh` succeeds again.

`uname -a`:

`Darwin hobbes.local 15.3.0 Darwin Kernel Version 15.3.0: Thu Dec 10 18:40:58 PST 2015; root:xnu-3248.30.4~1/RELEASE_X86_64 x86_64`

Environment details (AWS, VirtualBox, physical, etc.):

`remote-machine` below uses the `generic` driver.

Steps to Reproduce:
```
# after first login to mac
$ docker-machine ssh remote-machine
exit status 255
$ ssh remote-machine
<dialog pops up, prompts for passphrase for SSH key>
remote-machine $ exit
$ docker-machine ssh remote-machine
remote-machine $
```

Actual Results: above.

Expected Results: the first command should succeed, or at least print a more helpful error message. about the underlying ssh failure.

**Comment by nathanleclaire** [comment]
Hm... I wonder what we could do to help this (ideally support it directly), since password-protected SSH keys should definitely be supported.

**Comment by Delpedro** [comment]
Nathan, im getting this error after approx 5mins 9f non using the cli within a container, its like its booting me out of the container back to thw master cli of Quickstart Terminal

**Comment by bamarni** [comment]
see #3328 :)
