### ISSUE TITLE
[Azure] error installing docker 1.11.0 & machine 0.7.0 & Ubuntu 16.04

### ISSUE THREAD

**Issue by imton** [docker/machine#3311]
For docker 1.11.0 and docker-machine 0.7.0

Azure creation failed.

log
```
Installing Docker...
error installing docker:
```

WorkAround

1. ssh the machine 

2 .edit ```/etc/apt/sources.list.d/docker.list```
with
```deb https://apt.dockerproject.org/repo ubuntu-xenial experimental```

3. instal docker-engine
```apt-get update```
```apt-get install docker-engine```

4. logout ssh

5. docker-machine provision [machine-name]

**Comment by nathanleclaire** [comment]
Please try #3308 (comment), and open a new issue if that does not help you upgrade.

**Comment by nathanleclaire** [comment]
Hm, actually, I seem to have gotten this mixed up with another issue.  This seems to be a dupe of https://github.com/docker/machine/issues/3184 actually.
