### ISSUE TITLE
Azure driver: cannot login on ubuntu 14.04

### ISSUE THREAD

**Issue by iggycoloma** [docker/machine#3313]
I appear to be running into a couple of problems trying to do a "docker-machine create -d azure ..." from my Ubuntu 14.04 box with the new 0.7.0 driver:

- `Error creating Azure client: Failed to save tenant ID: Failed to rename file: rename /tmp/tenantidxxxxxxxxxx /home/<username>/.docker/machine/credentials/azure/<GUID>.tenantid: invalid cross-device link` (cp'ing appears to work, but rename runs into script errors if I run it manually)
- Even if I copy the tenantid file over manually, the token retrieval process that follows times out before I can go back and forth to the web browser to finish it.

I have the azure-cli installed on this box and it logs in just fine. This appears to be specific to the docker-machine azure driver.

**Comment by ahmetalpbalkan** [comment]
@iggycoloma It looks like your `/home` and `/tmp` are on different filesystems. Could you please send the `mount` command output? We've seen this coming, so a fix will be on your way shortly.

**Comment by iggycoloma** [comment]
`/dev/sdc1 on / type ext4 (rw,errors=remount-ro)
proc on /proc type proc (rw,noexec,nosuid,nodev)
sysfs on /sys type sysfs (rw,noexec,nosuid,nodev)
none on /sys/fs/cgroup type tmpfs (rw)
none on /sys/fs/fuse/connections type fusectl (rw)
none on /sys/kernel/debug type debugfs (rw)
none on /sys/kernel/security type securityfs (rw)
udev on /dev type devtmpfs (rw,mode=0755)
devpts on /dev/pts type devpts (rw,noexec,nosuid,gid=5,mode=0620)
tmpfs on /run type tmpfs (rw,noexec,nosuid,size=10%,mode=0755)
none on /run/lock type tmpfs (rw,noexec,nosuid,nodev,size=5242880)
none on /run/shm type tmpfs (rw,nosuid,nodev)
none on /run/user type tmpfs (rw,noexec,nosuid,nodev,size=104857600,mode=0755)
none on /sys/fs/pstore type pstore (rw)
cgroup on /sys/fs/cgroup/cpuset type cgroup (rw,relatime,cpuset)
systemd on /sys/fs/cgroup/systemd type cgroup (rw,noexec,nosuid,nodev,none,name=systemd)
/home/<username>/.Private on /home/<username> type ecryptfs (ecryptfs_check_dev_ruid,ecryptfs_cipher=aes,ecryptfs_key_bytes=16,ecryptfs_unlink_sigs,ecryptfs_sig=<sig>,ecryptfs_fnek_sig=<sig>)
gvfsd-fuse on /run/user/1000/gvfs type fuse.gvfsd-fuse (rw,nosuid,nodev,user=<username>)`

**Comment by ahmetalpbalkan** [comment]
@iggycoloma okay it looks like your home dir is `ecryptfs`, we'll take a look. thanks!

**Comment by RomanSaveljev** [comment]
I have run into the same bug on ArchLinux, where `/tmp` (rightfully) sits on `tmpfs`. As a workaround I pass `TMPDIR=/var/tmp` to `docker-machine`

**Comment by ahmetalpbalkan** [comment]
cc:@colemickens

**Comment by ahmetalpbalkan** [comment]
@iggycoloma fix is in #3378 feel free to give it a try.

**Comment by mpatrone** [comment]
Ahmet, same happens on Windows. If you have TEMP on one drive and your home path on another:
Error with pre-create check: "Error creating Azure client: Failed to save tenant ID: Failed to rename file: rename d:\\temp\\tenantid376625603 C:\\Users\\po755\\.docker\\machine\\credentials\\azure\\65e754be-29ee-4bac-89b7-97b61412f028.tenantid: The system cannot move the file to a different disk drive."

**Comment by ahmetalpbalkan** [comment]
@mpatrone fair point. We fixed this in #3378, if you build from master branch you should be getting the fix or wait until the next release.

**Comment by manuelm3z** [comment]
@ahmetalpbalkan i have the same problem. i'm using the last release candidate, but the distro is Elementary OS, a variation of Ubuntu 14.04.

**Comment by iboware** [comment]
@ahmetalpbalkan It doesn't work with docker-machine version 0.8.0-rc2, build 4ca1b85

`Running pre-create checks...
Error with pre-create check: "Error creating Azure client: Failed to save tenant ID: Failed to rename file: rename /tmp/tenantid123123123 /home/blabla/.docker/machine/credentials/azure/123123123123123123.tenantid: invalid cross-device link"
`

**Comment by ahmetalpbalkan** [comment]
@manuelm3z @iboware it appears like we took the fix with the `.token` file and not the `.tenantid` file. @nathanleclaire when is 0.8.2 going out, I feel like I can come up with a fix today.

**Comment by ahmetalpbalkan** [comment]
this time it should be fixed completely. The fix is in `master`. In a nutshell, there are two files we write to disk: (1) `{subscription-id}.tenantid` and (2) `{tenantid}.json` containing access_token.

Initially I interpreted this issue as it's about (2) and fixed only that. Now we fixed (1) but both of them had to be fixed anyway for this to work on your machines.
