### ISSUE TITLE
docker-machine openstack driver - deletes keypair incorrectly

### ISSUE THREAD

**Issue by adityavajjha** [docker/machine#3315]
The docker-machine driver for Openstack is deleting manually created key pairs when the docker host is deleted. Here are the versions that I am using: 

**docker-machine version 0.6.0, build e27fb87
Openstack Mitaka installed using devstack on Ubuntu 15.10**

Steps to reproduce: 
1. Create a new nova keypair using the command: **nova keypair-add test-kp**. 
2. Save the private key pair to a new file called test-kp.pem
3. Create a new docker host using the command: 
```
docker-machine -D create -d openstack \
--openstack-flavor-id d3 \
--openstack-image-id 4586a537-0710-494b-9691-fef1962885b1 \
--openstack-net-name private \
--openstack-floatingip-pool public \
--openstack-ssh-user ubuntu \
--openstack-sec-groups default \
--openstack-private-key-file test-kp.pem \
--openstack-keypair-name test-kp \
--openstack-ssh-user ubuntu \
docker-01
```

1. After the host is created successfully, delete it using the command: **docker-machine rm docker-01**
2. Login to Openstack and run the command: **nova keypair-list**
3. The keypair will be deleted.

**Comment by adityavajjha** [comment]
Possible duplicate - as Scott Lowe has already filed in another thred.

**Comment by nathanleclaire** [comment]
I see -- yes that sounds like a dupe, thanks!

**Comment by dgliwa** [comment]
Why is this closed?  I am having this exact issue, and don't see it referenced elsewhere.

**Comment by nathanleclaire** [comment]
It's a dupe of https://github.com/docker/machine/issues/3261

**Comment by dgliwa** [comment]
@nathanleclaire thank you
