### ISSUE TITLE
Documentation for dev features

### ISSUE THREAD

**Issue by bamarni** [docker/machine#3316]
Currently, documentation at https://docs.docker.com/machine/ seems to be built periodically from the master branch. This can be misleading as it references features which might not be released yet and most people don't run docker machine from source.

What about doing something similar to the docker engine documentation? Docker machine docs could be built from a "docs" branch, where typos / rephrasing are pushed directly, and documentation for new features would be pushed when releasing (by merging "master" into "docs").

**Comment by nathanleclaire** [comment]
> What about doing something similar to the docker engine documentation? Docker machine docs could be built from a "docs" branch, where typos / rephrasing are pushed directly, and documentation for new features would be pushed when releasing (by merging "master" into "docs").

This is how it's intended to work.  Every release I update the `docs` branch to be the same as the tag compiled for the release.  @londoncalling @moxiegirl we should circle the wagons and make sure we're on the same page here.

**Comment by moxiegirl** [comment]
@nathanleclaire I checked on Wednesday. That was built from `docs` and the branch had been updated.    We should always build from the `docs` in the past, sometime for the big releases we built from master and built `docs` day after.

**Comment by bamarni** [comment]
> This is how it's intended to work.

Indeed, I had miss that branch already exist. Actually I've opened this one after reading #3284, which was reported 8 days ago while 0.7.0 has been relased later. I thought this was unexpected, but maybe the docs branch is also updated for RC releases to encourage people giving early feedback for new features?

**Comment by nathanleclaire** [comment]
I'm not sure.  @moxiegirl what's our policy on RCs?  I did bump the `docs` branch during RCs this release so maybe that was a mistake.  I had assumed they might be deployed to staging.

**Comment by moxiegirl** [comment]
@nathanleclaire for the docs, during the RC, you need to cherry-pick relevant doc changes into the RC branch.  Then, when the RC is final, update the `docs` branch --- if you've just followed along with the cp's you can create `docs` from the RC.

**Comment by nathanleclaire** [comment]
@moxiegirl So, if I cut the first RC from `master`, and update `docs` to `master` branch immediately after, that should be good, right? i.e. The docs for the RC will then be deployed to a staging site, but not to actual production.

**Comment by nathanleclaire** [comment]
Going to close this issue since it seems the action item is just better coordination between myself and the docs team.
