### ISSUE TITLE
enhancement: add flag to provide SSH config file for generic driver

### ISSUE THREAD

**Issue by brettdh** [docker/machine#3318]
Follow-on from #3310

> @nathanleclaire 
> Machine ignores ~/.ssh/config. This is deliberate, as existing users' SSH configs were causing all sorts of mysterious and unintended side effects in Machineland.

> I'd be happy to consider proposals or PRs to specify an SSH config file to use (via flag), though. Seems perfectly fine to make configurable for those who know what they're doing.

This was pretty easy to implement, so I just did it. :-) Posting a PR shortly, after I test it out a bit in my environment.

**Comment by nathanleclaire** [comment]
Hey @brettdh, thanks for the issue!  Since the PR is already out, I think we're good to go ahead and close this.  A PR in my mind is also a "feature request" (and the best kind too!).
