### ISSUE TITLE
Cannot pull from HTTP registry with boot2docker

### ISSUE THREAD

**Issue by jehrhardt** [docker/machine#3320]
I have created my machine via

```sh
docker-machine create --driver xhyve --engine-insecure-registry http://example.com dev
```

When I login via ssh and look into the profile

```sh
docker-machine ssh dev
cat /var/lib/boot2docker/profile 
```

it wil print

```
EXTRA_ARGS='
--label provider=xhyve
--insecure-registry http://example.com

…
```

But when I try to pull an image from the registry it fails, because it tries to call the URL `https://example.com/v1/_ping` instead of `http://example.com/v1/_ping`. Why is Docker ignoring the `--insecure-registry` property?

I am using:

* Mac OS X 10.11.4
* docker-machine 0.7.0
* docker 1.11.0

The problem appears with xhyve and virtualbox driver.

**Comment by nathanleclaire** [comment]
Hm, yeah, that should work.  Let me see if I can dupe.

**Comment by afaludi** [comment]
it works when using:
`--insecure-registry example.com`
instead of:
`--insecure-registry http://example.com`

just skip the protocol and specify only the hostname

**Comment by nathanleclaire** [comment]
I'm going to go ahead and close the ticket as it seems not to be a Machine issue, but `http://` notation should work, no?

@aaronlehmann @dmp42 @RichardScothern Do you know if this is intended to work?

**Comment by aaronlehmann** [comment]
`--insecure-registry` doesn't accept a URL scheme.

**Comment by nathanleclaire** [comment]
Nice -- thanks @aaronlehmann @afaludi
