### ISSUE TITLE
Connect to multiple consul server

### ISSUE THREAD

**Issue by phlegx** [docker/machine#3321]
With ```consul``` it is very easy to create a cluster see for example here: https://hub.docker.com/r/progrium/consul/

A far as I have seen, with docker-machine it is only possible to pass along one consul server for ```--swarm-discovery``` and ```--engine-options``` (one IP) like i.e.

```
docker-machine create \
  -d digitalocean \
  --swarm \
  --swarm-master \
  --swarm-discovery="consul://${KV_IP}:8500" \
  --engine-opt="cluster-store=consul://${KV_IP}:8500" \
  --engine-opt="cluster-advertise=eth1:2376" \
  master
```

wouldn't it make perfect sense to able to pass multiple ```consul``` IP addresses, so in the case one ```consul``` fails, all can continue without problems? 

Not sure If ```swarm``` itself cannot take more then one IP. Could be the case of course.

**Comment by nathanleclaire** [comment]
I'm not 100% positive, but I think that after bootstrapping a Consul cluster you would just point Swarm at any node you are exposing the [HTTP API](https://www.consul.io/docs/agent/http/agent.html) from.  Consul handles the coordination and consensus "behind the scenes" and each agent exposes a unified interface, so it wouldn't do you any good to connect to multiple endpoints.

Maybe @vieux @abronan @al can chime in with additional commentary.

From the referenced page:

> The Agent endpoints are used to interact with the local Consul agent. Usually, services and checks are registered with an agent which then takes on the burden of keeping that data synchronized with the cluster.

**Comment by nathanleclaire** [comment]
If concerned about high availability of the Consul node you're connecting to, you might be able to put several nodes behind one elastic IP or DNS record.  Not sure what Hashicorp's "best practice" architecture is here.

**Comment by phlegx** [comment]
@nathanleclaire Thanks!

I played a bit around with this and it seems you are right:: ```consul``` does this behind the scenes and therefore there is no (absolute) need to give more the one consul IP/DNS. 

Of course this does not work  if the primary node  is permanently down for some reason. Then, if one restarts the whole cluster (which should not happen anyway), the primary node needs to be set to another host probably manually. So for this use-case it might come in handy to have more then one node.

Nathan, there is still the other issue namely #3303 which is kind of a blocker to me and is somehow minor related to this, since I cannot fully test the consul cluster. I'm not sure if I do it correctly but in #3303  with my last post, I explain what happens when Port 4000 is closed. Would be very nice if you could have a look again at #3303!

thanks!!
