### ISSUE TITLE
"docker-machine create" on OSX / VirtualBox fails to start docker w/ devicemapper as storage driver

### ISSUE THREAD

**Issue by dieswaytoofast** [docker/machine#3322]
(docker-machine version: 0.7.0;   VirtualBox version: 5.0.16 r105871;  OSX version: 10.11.4 (15E65))
I've been merrily creating / wiping-out images for a while now, but sometime in the last two weeks, _something_ broke.
I can no longer get a functioning VM w/ the *devicemapper* storage engine. (**Note** : *aufs* works just fine!)

`docker-machine -D create -d virtualbox  --engine-storage-driver=devicemapper dev` errors out with 
```
Error creating machine: Error checking the host: Error checking and/or regenerating the certs: There was an error validating certificates for host "192.168.99.101:2376": dial tcp 192.168.99.101:2376: getsockopt: connection refused
You can attempt to regenerate them using 'docker-machine regenerate-certs [name]'.
Be advised that this will trigger a Docker daemon restart which will stop running containers.
```

On connecting to the newly created vm, i see that docker has not started
```
root@dev:/mnt/sda1/var/lib/boot2docker# /etc/init.d/docker status
Docker daemon is not running
```

Running `/etc/init.d/docker start` fails, with the following in `/mnt/sda1/var/lib/boot2docker/docker.log`
```
time="2016-04-15T20:55:40.547380117Z" level=debug msg="[graphdriver] trying provided driver \"devicemapper\"" 
time="2016-04-15T20:55:40.547475500Z" level=debug msg="containerd connection state change: READY" 
time="2016-04-15T20:55:40.547888243Z" level=debug msg="devicemapper: driver version is 4.31.0" 
time="2016-04-15T20:55:40.549580492Z" level=debug msg="received past containerd event: &types.Event{Type:\"live\", Id:\"\", Status:0x0, P
id:\"\", Timestamp:0x5711554c}" 
time="2016-04-15T20:55:40.547905237Z" level=error msg="devmapper: Udev sync is not supported. This will lead to data loss and unexpected 
behavior. Install a dynamic binary to use devicemapper or select a different storage driver. For more information, see https://docs.docke
r.com/engine/reference/commandline/daemon/#daemon-storage-driver-option" 
time="2016-04-15T20:55:40.549636885Z" level=debug msg="Cleaning up old mountid : start." 
time="2016-04-15T20:55:40.549667567Z" level=fatal msg="Error starting daemon: error initializing graphdriver: driver not supported" 
```

These are happing with a _clean_ install of VirtualBox and Docker-Toolbox.
Perhaps something to do with static vs dynamic linking of devicemapper? Something else that changed recently?

**Comment by nathanleclaire** [comment]
I think that it's just not really supported in upstream Docker anymore.

Why use `devicemapper`?

**Comment by dieswaytoofast** [comment]
Thats what I thought, just wanted to make sure that it wasn't something _I_ was doing :-)

**Comment by nathanleclaire** [comment]
You're OK !  Give `overlay` a whirl if you're curious.  It's pretty good.

**Comment by dieswaytoofast** [comment]
might as well - intertia had kept me on devicemapper lo all this while...

**Comment by frontrunner4000** [comment]
It's worth mentioning, there's certain things you can't do with overlay that you can do with devicemapper- notably install a JDK on an Ubuntu/Debian system.

**Comment by nathanleclaire** [comment]
> notably install a JDK on an Ubuntu/Debian system.

Can you link the relevant issue? Why would using `overlay` prevent this?

**Comment by menzow** [comment]
Hello @dieswaytoofast ,

The default base os docker-machine uses for virtualbox ( [boot2docker](http://boot2docker.io) ) doesn't support the devicemapper file system.

I wrote a article how to fix this issue here: https://medium.com/@menzo/using-the-device-mapper-storage-driver-on-mac-osx-6327dbee3250
