### ISSUE TITLE
Uninstalling docker machine

### ISSUE THREAD

**Issue by psychok7** [docker/machine#3324]
Hi couldn't find any documentation about uninstalling docker-machine. I am using Ubuntu 14.04 and i have been getting this error sometimes `ERROR: Couldn't connect to Docker daemon - you might need to run docker-machine start default.`

I have no idea why but since i am not using docker-machine (only compose) i thought removing it might solve my issue.

How can i achieve that?

**Comment by bamarni** [comment]
This error is triggered from docker-compose (https://github.com/docker/compose/blob/e2cb7b0237085415ce48900309a61c73b5938520/compose/cli/errors.py#L122). Apparently it is only shown in case it cannot connect to the docker daemon and "docker-machine" is present, I don't think it's directly related to docker machine though as you don't use it.

Maybe it's a permission issue for the daemon socket (https://docs.docker.com/engine/installation/linux/ubuntulinux/#create-a-docker-group)?

**Comment by psychok7** [comment]
@bamarni my user was already in the docker group but i added it again just to make sure. How do i uninstall docker-machine? maybe like that i can get another error and see what the problem could be.

when i run `docker-machine ls` i get:

```
NAME   ACTIVE   DRIVER       STATE   URL   SWARM   DOCKER    ERRORS
yyy   -        virtualbox   Error                 Unknown   machine does not exist

```

But i am not using `yyy` but if someone this is related i think uninstalling docker-machine could help

**Comment by bamarni** [comment]
So you already used docker-machine previously. Then it's probably environment variable leftovers, do you see some output when running `env | grep DOCKER_`? If so, unsetting them should fix your issue.

As per uninstalling docker machine, it depends on how you installed it in the first place, but this should be enough : `rm -rf $(which docker-machine) ~/.docker/machine`

**Comment by psychok7** [comment]
@bamarni I installed docker-machine by:

```
curl -L https://github.com/docker/machine/releases/download/v0.7.0/docker-machine-`uname -s`-`uname -m` > /usr/local/bin/docker-machine && \
chmod +x /usr/local/bin/docker-machine
```

When i run `env | grep DOCKER_` on my host machine nothing appears.. 

Can i remove docker-machine with `sudo rm -rf $(which docker-machine) ~/.docker/machine` then?

**Comment by bamarni** [comment]
Well you can but I don't see how it could help, it seems to be an issue
with your docker setup itself, not machine or compose.

Is docker even running (sudo service docker status)? And are you able to
run containers just with the docker client (docker run hello-world)?

**Comment by psychok7** [comment]
@bamarni yes, i am able to run compose, and docker but sometimes when i am running a crawler inside a container it kills that container and the others, but when i do `sudo service docker status` it is still running.

I only started having this issue recently (after i updated compose i think)

**Comment by bamarni** [comment]
I'd suggest to continue the discussion in docker/compose, as the error message comes from there and it happens since you upgraded compose, docker-compose folks might have more clue about what is going on here. Please also include the output of `docker version` and `docker-compose version` in your report, if possible a `docker-compose.yml` to reproduce the issue.

**Comment by nathanleclaire** [comment]
It won't solve your issue to remove Docker Machine.  Compose is complaining because it can't connect to a Docker daemon, it's only trying to be helpful by suggesting to start the `docker-machine` VM.  You need to figure out why your Compose is not connecting to an active Docker daemon.

**Comment by nathanleclaire** [comment]
If Docker service is running then `docker ps` should just work.  Sounds like permissions issues.  Did you log out and log back in after adding yourself to the `docker` group?  Does `sudo docker ps` work?  Does `docker -H unix:///var/run/docker.sock ps` work?

**Comment by psychok7** [comment]
@nathanleclaire yes to all your questions, they all work. anyways since i removed the docker machine vm i hadn't had this problem (its been a day so far)

**Comment by psychok7** [comment]
@nathanleclaire i am still getting this issue after all.. i `docker ps` right after it crashed and although the comand works there are no running containers right after it crashes.

**Comment by nathanleclaire** [comment]
What do the Docker logs say?  I think in this case they are in somewhere like `/var/log/upstart/docker.log`
