### ISSUE TITLE
"docker-machine ssh" should use active machine, not 'default'

### ISSUE THREAD

**Issue by scarlac** [docker/machine#3326]
**Output of `docker version`:**

```
➜  ~  docker version
Client:
 Version:      1.11.0
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   4dc5990
 Built:        Wed Apr 13 18:13:28 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.11.0
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   4dc5990
 Built:        Wed Apr 13 18:38:59 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
➜  ~  docker info
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 1
Server Version: 1.11.0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 12
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: host bridge null
Kernel Version: 4.2.0-27-generic
Operating System: Ubuntu 15.10
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 488.9 MiB
Name: docker-sandbox
ID: OR4N:XLTM:QDDK:TJBI:D4IB:GYVA:2YB2:I5XN:2G3V:KOST:7JQR:DBMX
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Username: scarlac
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Labels:
 provider=digitalocean
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
```
➜  ~  docker-machine ls
NAME             ACTIVE   DRIVER         STATE     URL                         SWARM   DOCKER    ERRORS
default          -        virtualbox     Running   tcp://192.168.99.100:2376           v1.11.0   
docker-sandbox   *        digitalocean   Running   tcp://***.***.***.***:2376           v1.11.0   
```
(note that docker-sandbox is active, which was done by setting env with `docker-machine env docker-sandbox`)

**Steps to reproduce the issue:**
1. Add a docker-machine other than your default machine using `docker-machine create (...) docker-sandbox`
2. Set the newly created machine as 'active' by using `eval $(docker-machine env docker-sandbox)`
3. Check that it's active by calling `docker-machine ls`. You should see an asterisk in the "ACTIVE" column of the newly created row, similar to my example output.
4. Run `docker-machine ssh` to enter your machine

While it's not directly documented in docker-machine ssh, the 'active' flag should naturally be an indication of what machine should be used as the default target for commands, if relevant.

**Describe the results you received:**
In my case I'm connected to my virtualbox (name 'default') machine instead of the active digitalocean machine (name 'docker-sandbox').

**Describe the results you expected:**
I should be connected to the 'active' machine, not the machine with the 'default' name.

**Additional information you deem important (e.g. issue happens only occasionally):**
This could be considered a feature addition, but given that the environment is already set according to the standard, I'd be so bold to call this a bug/unexpected behaviour.

**Comment by bamarni** [comment]
Here the "active" column is from the docker client perspective. For docker-machine, falling back to "default" is unrelated and was introduced later (https://github.com/docker/machine/commit/5000139c8e5ffdaccec1a16d254871cfa89d899a).

Your assumption makes sense, I'm not sure if it's fine to switch the behaviour at this point though, as it could make some people SSHing / removing the wrong machine if they rely on the current default.

**Comment by scarlac** [comment]
I agree somewhat, @bamarni. It is technically an backwards incompatible change for those who have their active env set to something else than default, yet are expecting docker-machine to still work on default. I can't say if it's normal to work with your default machine while having been set up for another. I suspect not.

Using semver, given that docker-machine is v0.7 right now, would you say v0.8 is a valid target version for this bug?

**Comment by nathanleclaire** [comment]
Hi @scarlac, thanks for the issue.  Once upon a time this was actually how things worked (sort of), but we found it was just too confusing in several senses.  For one, it made it that much more difficult to know as a user what was going to happen when you typed `docker-machine start` etc. at a terminal, because it could be pointed at any arbitrary machine ("Wait, which one is active again?").  It also made trying to remotely debug problems very difficult for the Machine team because any pasted output / sequence of commands could have much more arbitrary behavior based on the environment (or, as was originally the case, the stateful file tracking which machine was "active").

The current behavior is simple and easy to reason about.  `default` is the machine that gets operated on by default.  I'm wary of introducing too much additional magic, so far we've found that erring on the side of explicitness pays off.

**Comment by scarlac** [comment]
@nathanleclaire, please re-open.

The "Wait, which one is active again?" argument doesn't make sense to me. That's either _always_ a problem (and should be addressed in all tools) or not at all. Even `docker-machine active` will tell you which one is active.

The argument about remote debugging seems a bit outdated since the docker issue template shows reporters to issue a `docker-machine ls` which clearly displays which machine is active. In either case, designing a tool to work against the user, for the purpose of debugging, isn't sustainable model for a popular tool.

I can perhaps relate to not remembering which machine I am currently working on if I have several terminals open, a problem made worse by this issue.
If I'm ever in doubt I answer the 'what is active'  question by calling `docker-machine ls`. Ironically docker-machine knows what's active, yet will force me to use re-specify what machine I may mean.

Are you looking for a PR? Please don't just close the issue unless you really mean it is intended to work half/half.

**Comment by nathanleclaire** [comment]
"Active" in the present Docker Machine context refers to which Machine the _Docker client_ is configured to point to, and that's all.  Keeping the model simple (always default to `default`) makes "active" machine and behavior of all commands very straightforward and easy to reason about.  I'm wary of introducing additional meaning to the term "active machine".  Why not stay away from "You Just Have To Know" situations when possible?

Active host checking today verifies a Machine as "active" by checking the value of `DOCKER_HOST` against the machine's IP address.  What happens in the situation where a machine is stopped and therefore has no IP address, causing it to not register as "active"?  `docker-machine start` will have no idea that it's supposed to go start up that machine.  What if the machine is unreachable by firewall etc.?  You won't be able to verify it as `active`, so won't the automatic behavior you're hoping for be impossible to attain?

What to do with `config` and `env`, which today _do_ have a default argument of `default`?  Don't you think it's potentially confusing to have a behavior which applies to `start`, `stop`, etc., but not to `config` and `env`?  After all, those are how you set the "active" machine in the first place.

If you'd like access to such behavior, why not create a shell function and add it to your `~/.bashrc`? e.g.:

```bash
function dmactive () {
    docker-machine "$@" $(docker-machine active)
}
```

used from console like:

```console
$ eval $(docker-machine env nathanleclaire-swarm-playground)
$ dmactive stop
```

**Comment by scarlac** [comment]
If it was up to me all relevant commands including `start`, `stop`, `config`, etc. and even `env` would work by using the active machine. If there was no active machine it could fall back to a machine named 'default'.

Maybe I should have made this clear from the get go instead of focusing on `ssh`. My bad. I don't have enough experience with the other commands so I didn't want to assume anything about the other commands.

Anyway - I think that'd give a great experience - It would be fully consistent and you'd have a clear concept of what is active. New users wouldn't have to think about it, and existing users would have a clear sense of what machine they are working with regardless of command.

I can re-create another issue with a more complete proposal so there's no doubt if you'd like? Complete with examples for all machine commands.
