### ISSUE TITLE
Issue in docker while running this command

### ISSUE THREAD

**Issue by kaushal9808** [docker/machine#3332]
I have install the docker and its gives error while running simple command
** docker pull hello-world**

Using default tag: latest
Pulling repository docker.io/library/hello-world
Error while pulling image: Get https://index.docker.io/v1/repositories/library/hello-world/images: dial tcp: lookup index.docker.io on 10.19.212.200:53: no such host

**After this i have added the proxy 
export HTTP_PROXY=http://{host}:{port}**

after this i run the command again still getting error but different.
_$_ docker pull hello-world
Using default tag: latest
Warning: failed to get default registry endpoint from daemon (An error occurred trying to connect: Get https://192.168.99.100:2376/v1.22/info: Tunnel or SSL Forbidden). Using system default: https://registry-win-tp3.docker.io/v1/
An error occurred trying to connect: Post https://192.168.99.100:2376/v1.22/images/create?fromImage=hello-world%3Alatest: Tunnel or SSL Forbidden

**how i can remove the last error or any guideline for running the simple command on windows 7 
i am new in docker**

**Comment by nathanleclaire** [comment]
Where did you add the `HTTP_PROXY`?  Did you set it on the daemon?

Consider using `--engine-env` to set `HTTP_PROXY` in the created VM.

**Comment by kaushal9808** [comment]
Hi nathanleclaire,

I have set the HTTP_PROXY in config.json or command prompt itself
**can you please explore what is it means 
An error occurred trying to connect: Post https://192.168.99.100:2376/v1.22/images/create?fromImage=hello-world%3Alatest: Tunnel or SSL Forbidden**

**Comment by nathanleclaire** [comment]
It means the machine is not allowed to access the route it is trying to access, most likely due to firewall.

Try setting `--engine-env HTTP_PROXY=http://${host}:${port}` when you `create` the machine.

**Comment by igitur** [comment]
I'm experiencing the same behind a corporate firewall. I'm unsure whether there are restrictions on the routes. I have created my machine with the `--engine-env` parameters as you suggested. I still get this output when I try to pull the `hello-world` image.

```
Using default tag: latest
Warning: failed to get default registry endpoint from daemon (An error occurred
trying to connect: Get https://192.168.99.104:2376/v1.24/info: Tunnel or SSL For
bidden). Using system default: https://index.docker.io/v1/
An error occurred trying to connect: Post https://192.168.99.104:2376/v1.24/imag
es/create?fromImage=hello-world&tag=latest: Tunnel or SSL Forbidden
```

**Comment by tsl143** [comment]
It may have something to do with permissions, as using `SUDO` helped me to resolve `Warning: failed to get default registry endpoint from daemon (Error response from daemon: Bad response from Docker engine). Using system default: https://index.docker.io/v1/`

**Comment by lmyzzu** [comment]
It's need sudo

**Comment by sesong11** [comment]
If on windows you need to run cmd as administrator.

**Comment by mbsaerens** [comment]
> If on windows you need to run cmd as administrator.

You need to add your user to the docker-users group
