### ISSUE TITLE
docker-machine with azure driver Error setting machine configuration from flags provided

### ISSUE THREAD

**Issue by machzqcq** [docker/machine#3333]
I am getting this error on yosemite mac. However the same seems to move forward on Windows 7. Freshly installed Docker toolbox in both cases as of 4/17/2016. (Ultimately the windows 7 also got stuck on "waiting for SSH to be available",but that's a different issue). Some background is  #[here](https://github.com/docker/machine/issues/2180)

**On Mac**
```
Anyones-Mac-mini:~ pmacharl$ docker version
Client:
 Version:      1.10.0
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   590d5108
 Built:        Thu Feb  4 18:18:11 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.11.0
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   4dc5990
 Built:        Wed Apr 13 19:36:04 2016
 OS/Arch:      linux/amd64
Anyones-Mac-mini:~ pmacharl$ docker-machine create --driver azure --azure-subscription-id 48abda7f-a0b5-4308-ba66-02aa66cc0ca8 azure-mac-sandbox
Error setting machine configuration from flags provided: Please specify azure subscription params using options: --azure-subscription-id and --azure-subscription-cert or --azure-publish-settings-file
Anyones-Mac-mini:~ pmacharl$ docker-machine ls
NAME               ACTIVE   DRIVER       STATE     URL                         SWARM   DOCKER    ERRORS
aws-sandbox        -        amazonec2    Stopped                                       Unknown   No IP for instance i-272533e0
default            -        virtualbox   Stopped                                       Unknown
docker-developer   *        virtualbox   Running   tcp://192.168.99.100:2376           v1.11.0
```

**On Windows 7**  
```
$ docker-machine create --driver azure --azure-subscription-id 48abda7f-a0b5-43
08-ba66-02aa66cc0ca8 azure-sandbox
Running pre-create checks...
(azure-sandbox) Microsoft Azure: To sign in, use a web browser to open the page
https://aka.ms/devicelogin. Enter the code ARBVWKQ9G to authenticate.
(azure-sandbox) Completed machine pre-create checks.
Creating machine...
(azure-sandbox) Querying existing resource group.  name="docker-machine"
(azure-sandbox) Creating resource group.  name="docker-machine" location="westus
"
(azure-sandbox) Configuring availability set.  name="docker-machine"
(azure-sandbox) Configuring network security group.  name="azure-sandbox-firewal
l" location="westus"
(azure-sandbox) Querying if virtual network already exists.  name="docker-machin
e-vnet" location="westus"
(azure-sandbox) Configuring subnet.  name="docker-machine" vnet="docker-machine-
vnet" cidr="192.168.0.0/16"
(azure-sandbox) Creating public IP address.  static=false name="azure-sandbox-ip
"
(azure-sandbox) Creating network interface.  name="azure-sandbox-nic"
(azure-sandbox) Creating storage account.  name="vhds93ac0oknz5xngnsj6fsf" locat
ion="westus"
(azure-sandbox) Creating virtual machine.  location="westus" size="Standard_A2"
username="docker-user" osImage="canonical:UbuntuServer:15.10:latest" name="azure
-sandbox"
Waiting for machine to be running, this may take a few minutes...
Detecting operating system of created instance...
Waiting for SSH to be available...
```  

![docker-machine-azure](https://cloud.githubusercontent.com/assets/6425159/14608007/079f97e6-0552-11e6-9164-be0abb76e0b9.png)  

**docker-machine debug**  

Anyones-Mac-mini:~ pmacharl$ docker-machine --debug create --driver azure --azure-subscription-id 48abda7f-a0b5-4308-ba66-02aa66cc0ca8 azure-sandbox
Docker Machine Version:  0.6.0, build e27fb87
Found binary path at /usr/local/bin/docker-machine
Launching plugin server for driver azure
Plugin server listening at address 127.0.0.1:51412
() Calling .GetVersion
Using API Version  1
() Calling .SetConfigRaw
() Calling .GetMachineName
(flag-lookup) Calling .GetMachineName
(flag-lookup) Calling .DriverName
(flag-lookup) Calling .GetCreateFlags
Found binary path at /usr/local/bin/docker-machine
Launching plugin server for driver azure
Plugin server listening at address 127.0.0.1:51416
() Calling .GetVersion
Using API Version  1
() Calling .SetConfigRaw
() Calling .GetMachineName
(azure-sandbox) Calling .GetMachineName
(azure-sandbox) Calling .DriverName
(azure-sandbox) Calling .GetCreateFlags
(azure-sandbox) Calling .SetConfigFromFlags
Error setting machine configuration from flags provided: Please specify azure subscription params using options: --azure-subscription-id and --azure-subscription-cert or --azure-publish-settings-file

**Comment by ahmetalpbalkan** [comment]
> Please specify azure subscription params using options: --azure-subscription-id and --azure-subscription-cert or --azure-publish-settings-file

this means you have docker-machine older than v0.7.0. Please install the latest..

For the error you sent in cmd.exe, can you please run `docker-machine --debug [...]` and send the output. It's hard to tell what's going on except it looks like the machine did not come up...

**Comment by nathanleclaire** [comment]
Thanks the issue @machzqcq.  Please follow Ahmet's instructions and re-open if you have additional issues.
