### ISSUE TITLE
docker machine azure portal Bad Request

### ISSUE THREAD

**Issue by machzqcq** [docker/machine#3334]
Trying to create docker environment using docker-machine + Azure driver  
```
Anyones-Mac-mini:~ pmacharl$ docker-machine create --driver azure --azure-subscription-id 48abda7f-a0b5-4308-ba66-02aa66cc0ca8 docker-azure-sandbox
```  
After this, I login to the [url](https://aka.ms/devicelogin) as specified , enter the token, then I get redirected to login page. Once I enter my Azure credentials, end up with this bad page error (I am able to otherwise login fine to portal.azure.com without any issues)  

**ERROR**
Sign In
Sorry, but we’re having trouble signing you in.
We received a bad request.

Additional technical information:
Correlation ID: fb1c0f60-c2f9-40da-b4b3-089cd0bc23aa
Timestamp: 2016-04-18 19:23:25Z
AADSTS90011: Error when processing DeviceAuthRedirect request.  

![docker-machine-azure-error](https://cloud.githubusercontent.com/assets/6425159/14617180/4113afca-057b-11e6-940a-17dde656d1dc.png)

**Here is the debug information ** (The azure request, response keeps going on without returning )

```
Anyones-Mac-mini:~ pmacharl$ docker-machine --debug create --driver azure --azure-subscription-id 48abda7f-a0b5-4308-ba66-02aa66cc0ca8 docker-azure-sandbox
Docker Machine Version:  0.7.0, build a650a40
Found binary path at /usr/local/bin/docker-machine
Launching plugin server for driver azure
Plugin server listening at address 127.0.0.1:51744
() Calling .GetVersion
Using API Version  1
() Calling .SetConfigRaw
() Calling .GetMachineName
(flag-lookup) Calling .GetMachineName
(flag-lookup) Calling .DriverName
(flag-lookup) Calling .GetCreateFlags
Found binary path at /usr/local/bin/docker-machine
Launching plugin server for driver azure
Plugin server listening at address 127.0.0.1:51748
() Calling .GetVersion
Using API Version  1
() Calling .SetConfigRaw
() Calling .GetMachineName
(docker-azure-sandbox) Calling .GetMachineName
(docker-azure-sandbox) Calling .DriverName
(docker-azure-sandbox) Calling .GetCreateFlags
(docker-azure-sandbox) Calling .SetConfigFromFlags
Running pre-create checks...
(docker-azure-sandbox) Calling .PreCreateCheck
(docker-azure-sandbox) DBG | Set configuration from flags.
(docker-azure-sandbox) DBG | Looking up AAD Tenant ID.  subs="48abda7f-a0b5-4308-ba66-02aa66cc0ca8"
(docker-azure-sandbox) DBG | Tenant ID loaded from file: /Users/pmacharl/.docker/machine/credentials/azure/48abda7f-a0b5-4308-ba66-02aa66cc0ca8.tenantid
(docker-azure-sandbox) DBG | Found AAD Tenant ID.  subs="48abda7f-a0b5-4308-ba66-02aa66cc0ca8" tenant="023bd3bd-20b9-4e5d-a7e5-f08c033768d3"
(docker-azure-sandbox) DBG | Loading auth token from file  path="/Users/pmacharl/.docker/machine/credentials/azure/023bd3bd-20b9-4e5d-a7e5-f08c033768d3.json"
(docker-azure-sandbox) DBG | Initiating device flow.  path="/Users/pmacharl/.docker/machine/credentials/azure/023bd3bd-20b9-4e5d-a7e5-f08c033768d3.json"
(docker-azure-sandbox) DBG | Azure request  request="https://login.microsoftonline.com/023bd3bd-20b9-4e5d-a7e5-f08c033768d3/oauth2/devicecode?api-version=1.0" method="POST"
(docker-azure-sandbox) DBG | Azure response  method="POST" request="https://login.microsoftonline.com/023bd3bd-20b9-4e5d-a7e5-f08c033768d3/oauth2/devicecode?api-version=1.0" x-ms-request-id="8a6f4aa5-8fbd-4c6b-827e-cafb4573a3ea" status="200 OK"
(docker-azure-sandbox) DBG | Retrieved device code.  expires_in=900 interval=5
(docker-azure-sandbox) Microsoft Azure: To sign in, use a web browser to open the page https://aka.ms/devicelogin. Enter the code EQNUK3Q6N to authenticate.
(docker-azure-sandbox) DBG | Azure request  method="POST" request="https://login.microsoftonline.com/023bd3bd-20b9-4e5d-a7e5-f08c033768d3/oauth2/token?api-version=1.0"
(docker-azure-sandbox) DBG | Azure response  status="400 Bad Request" method="POST" request="https://login.microsoftonline.com/023bd3bd-20b9-4e5d-a7e5-f08c033768d3/oauth2/token?api-version=1.0" x-ms-request-id="9f7dc34b-03fc-4bec-9618-b1a8a8e2ed38"
(docker-azure-sandbox) DBG | Azure request  method="POST" request="https://login.microsoftonline.com/023bd3bd-20b9-4e5d-a7e5-f08c033768d3/oauth2/token?api-version=1.0"
(docker-azure-sandbox) DBG | Azure response  status="400 Bad Request" method="POST" request="https://login.microsoftonline.com/023bd3bd-20b9-4e5d-a7e5-f08c033768d3/oauth2/token?api-version=1.0" x-ms-request-id="d28066fc-86dc-4e66-b261-cb888b9d5e73"
(docker-azure-sandbox) DBG | Azure request  method="POST" request="https://login.microsoftonline.com/023bd3bd-20b9-4e5d-a7e5-f08c033768d3/oauth2/token?api-version=1.0"
(docker-azure-sandbox) DBG | Azure response  status="400 Bad Request" method="POST" request="https://login.microsoftonline.com/023bd3bd-20b9-4e5d-a7e5-f08c033768d3/oauth2/token?api-version=1.0" x-ms-request-id="80d50384-5288-4864-9a1b-33cd3706bcff"
(docker-azure-sandbox) DBG | Azure request  request="https://login.microsoftonline.com/023bd3bd-20b9-4e5d-a7e5-f08c033768d3/oauth2/token?api-version=1.0" method="POST"
....... and so on
```

**Comment by nathanleclaire** [comment]
cc @ahmetalpbalkan

**Comment by ahmetalpbalkan** [comment]
@machzqcq are you able to repro this consistently? The AD error page does not reveal much. Cc: @colemickens

**Comment by machzqcq** [comment]
@ahmetalpbalkan yes consistently, in fact rm'd all docker-machines (maybe caching issue) and then redid. Same behavior !

**Comment by ahmetalpbalkan** [comment]
@machzqcq I forwarded the error trace for investigation in Active Directory.  In the meanwhile deleting your browser's cookies for `microsoftonline.com` and `login.windows.net` domains may help.

**Comment by machzqcq** [comment]
@ahmetalpbalkan : I opened an incognito window and tried the steps. And it actually went through ! That means the cookies were the problem. Thanks much. We can close this ticket please, unless we think cookies shouldn't interfere with the handshake(s)

**Comment by nathanleclaire** [comment]
thanks @machzqcq @ahmetalpbalkan

**Comment by ahmetalpbalkan** [comment]
@machzqcq I'm not surprised. 😄  The ActiveDirectory's motto should be “when in doubt, clear cookies”. Sorry for the inconvenience, let us know if you run into any more problems.

**Comment by adewes** [comment]
Having the same problem

**Comment by josh-swank** [comment]
I'm having the same problem. I can't get it to work in any browser, even after clearing cookies.

**Comment by ahmetalpbalkan** [comment]
We're sorry folks are having this issue. AAD is just being unstable and we've heard other issues with this in other projects using this auth flow (called _device auth_) as well. We're working with AAD team to get them to fix this.

@josh-swank can you please paste a correlationId/Timestamp (shown in the screen above) when you get an error and I will file an incident to get this investigated.

**Comment by adrian-drumea** [comment]
@josh-swank, @adewes  
If you can provide a correlation id or a screenshot of the error page that would be very helpful to investigate the issue

**Comment by orekdm** [comment]
I'm getting the same error when trying to do interactive login's via the xplat-cli.   Here is a fresh example (from today) of the failure message:

Additional technical information:
Correlation ID: b9a1f6e9-b7d8-4a83-9174-2923fcd06d51
Timestamp: 2016-09-27 18:45:22Z
AADSTS90011: Error when processing DeviceAuthRedirect request.

I suspect that these problems with xplat-cli and docker auth are the same.

**Comment by ahmetalpbalkan** [comment]
@orekdm thanks this is very valuable. I am forwarding this to the product team for investigation.

**Comment by arroyc** [comment]
another incident 
Correlation ID: 940fbbd0-16e9-4e5d-95c0-42bf6829a79b
Timestamp: 2016-10-10 21:48:34Z
AADSTS90011: Error when processing DeviceAuthRedirect request.

**Comment by ahmetalpbalkan** [comment]
@arroyc @orekdm I'm told that AAD team deployed a mitigation fixing this issue today (Oct 11) 3PM PST.

I can't verify if it fixes the problem as (1) it doesn't reproduce on my account (2) it's an intermittent problem. If you ever hit this issue again, please let me know, I will have them investigate.

**Comment by arroyc** [comment]
I have 3 times so far and it works for me, but I have some co-workers abroad who were also facing this issue, will confirm as soon as I get to hear from them .. Thanks :)

**Comment by lzachmann** [comment]
Unfortunately seeing the same error. Followed the recommendations above (clearing cookies, etc.), but nothing seems to have worked. Any advice?

![screen shot 2017-04-11 at 4 17 57 pm](https://cloud.githubusercontent.com/assets/7574887/24934783/9bb6c932-1ed2-11e7-9a92-0b8058106e41.png)

**Comment by colemickens** [comment]
@lzachmann that looks like a different error - see the error message is different. Did you specify a valid Azure Tenant ID anywhere? And was it valid?

**Comment by billpratt** [comment]
@colemickens I'm getting the same error that @ lzachmann is getting when trying to run

```
docker-machine create --driver azure --azure-subscription-id <SUB ID> --azure-location westus --azure-size Standard_A1 --azure-resource-group ContainersSwarmMode --azure-open-port 8080 --azure-ssh-user sysadmin swarm-leader
```



> Did you specify a valid Azure Tenant ID anywhere? And was it valid?

Where do you do that?

**Comment by billpratt** [comment]
@colemickens I have two Azure accounts. One account returns a Bad Request. The other account successfully authenticates.

**Comment by colemickens** [comment]
@billpratt Can you tell me more details about the difference between the accounts?

**Comment by billpratt** [comment]
@colemickens the account that didn't work is a Visual Studio Professional MSDN subscription. The account that works is a Pay as You Go subscription.

**Comment by lzachmann** [comment]
Followed up with Microsoft tech support yesterday. He had the impression that the error might be associated with some limitation tied to our Azure subscription -- a 'Microsoft Azure Sponsorship' -- but couldn't resolve the issue. Perhaps there some additional configuration that needs to happen via Portal or Azure CLI prior to running `docker-machine`?

**Comment by ivanpaulovich** [comment]
The same problem here:

Additional technical information:
Correlation ID: 54e36a52-8db7-4195-9115-fd98da0d2211
Timestamp: 2017-04-18 00:36:50Z
AADSTS90002: Requested tenant identifier '00000000-0000-0000-0000-000000000000' is not valid. Tenant identifiers may not be an empty GUID.

**Comment by colemickens** [comment]
I'm getting different errors (that I need to report as well) but I haven't been able reproduce the zero GUIDs problem.

Can you please run `docker-machine` in verbose mode? `docker-machine` auto-infers the AZURE_TENANT_ID from a response header. I'm wondering if that is incorrectly returning `00000000-0000-0000-0000-000000000000`.

Also, please let me know if it is a 100% repro, and if this is public cloud.

@lzachmann Wouldn't shock me if it was sub/tenant specific, but the way that the tenant ID is derived in `docker-machine` is what AAD/Azure recommend for determining the OAuth authority URL.

**Comment by lzachmann** [comment]
I've reproduced the same error on two accounts now (the first the original 'sponsored' subscription, and the second a free trial). If I understand you, neither of these accounts would be considered public. (Possibly I misinterpreted your request, however.)

I get the same response as @machzqcq (at the top of this issue). Here's the response using the second -- my own personal -- subscription (with subscription id struck out).
```
Docker Machine Version:  0.10.0, build 76ed2a6
Found binary path at /usr/local/bin/docker-machine
Launching plugin server for driver azure
Plugin server listening at address 127.0.0.1:53090
() Calling .GetVersion
Using API Version  1
() Calling .SetConfigRaw
() Calling .GetMachineName
(flag-lookup) Calling .GetMachineName
(flag-lookup) Calling .DriverName
(flag-lookup) Calling .GetCreateFlags
Found binary path at /usr/local/bin/docker-machine
Launching plugin server for driver azure
Plugin server listening at address 127.0.0.1:53094
() Calling .GetVersion
Using API Version  1
() Calling .SetConfigRaw
() Calling .GetMachineName
(machine) Calling .GetMachineName
(machine) Calling .DriverName
(machine) Calling .GetCreateFlags
(machine) Calling .SetConfigFromFlags
(machine) DBG | Set configuration from flags.
Running pre-create checks...
(machine) Calling .PreCreateCheck
(machine) DBG | Using Azure device flow authentication.
(machine) DBG | Looking up AAD Tenant ID.  subs="********-****-****-****-************"
(machine) DBG | Tenant ID loaded from file: /Users/lukezachmann/.docker/machine/credentials/azure/********-****-****-****-************.tenantid
(machine) DBG | Found AAD Tenant ID.  tenant="f94b4e2b-164f-419a-99c7-8569964c9c06" subs="********-****-****-****-************"
(machine) DBG | Loading auth token from file  path="/Users/lukezachmann/.docker/machine/credentials/azure/f94b4e2b-164f-419a-99c7-8569964c9c06.json"
(machine) DBG | Obtaining a token.  path="/Users/lukezachmann/.docker/machine/credentials/azure/f94b4e2b-164f-419a-99c7-8569964c9c06.json"
(machine) DBG | Azure request  method="POST" request="https://login.microsoftonline.com/f94b4e2b-164f-419a-99c7-8569964c9c06/oauth2/devicecode?api-version=1.0"
(machine) DBG | Azure response  status="200 OK" method="POST" request="https://login.microsoftonline.com/f94b4e2b-164f-419a-99c7-8569964c9c06/oauth2/devicecode?api-version=1.0" x-ms-request-id="cb75d148-d06c-4d1b-b2f5-8b6c0aeb0600"
(machine) DBG | Retrieved device code.  expires_in=900 interval=5
(machine) Microsoft Azure: To sign in, use a web browser to open the page https://aka.ms/devicelogin and enter the code BRJTST7MM to authenticate.
(machine) DBG | Azure request  method="POST" request="https://login.microsoftonline.com/f94b4e2b-164f-419a-99c7-8569964c9c06/oauth2/token?api-version=1.0"
(machine) DBG | Azure response  status="400 Bad Request" method="POST" request="https://login.microsoftonline.com/f94b4e2b-164f-419a-99c7-8569964c9c06/oauth2/token?api-version=1.0" x-ms-request-id="1433ec41-4d96-477d-acc1-996d02620000"
(machine) DBG | Azure request  request="https://login.microsoftonline.com/f94b4e2b-164f-419a-99c7-8569964c9c06/oauth2/token?api-version=1.0" method="POST"
(machine) DBG | Azure response  request="https://login.microsoftonline.com/f94b4e2b-164f-419a-99c7-8569964c9c06/oauth2/token?api-version=1.0" x-ms-request-id="811f4b60-d60f-4496-ad54-a90f92770600" status="400 Bad Request" method="POST"
(machine) DBG | Azure request  method="POST" request="https://login.microsoftonline.com/f94b4e2b-164f-419a-99c7-8569964c9c06/oauth2/token?api-version=1.0"
(machine) DBG | Azure response  status="400 Bad Request" method="POST" request="https://login.microsoftonline.com/f94b4e2b-164f-419a-99c7-8569964c9c06/oauth2/token?api-version=1.0" x-ms-request-id="56738f96-1377-449e-9313-ab9d2b850a00"
```
Etc. It fails to return until the code expires, even if I point my browser to `https://aka.ms/devicelogin` and enter the code. Here's the final message.

```
Error with pre-create check: "Error creating Azure client: Failed to complete device auth: autorest/azure/devicetoken: Error while retrieving OAuth token: Code Expired"
notifying bugsnag: [Error with pre-create check: "Error creating Azure client: Failed to complete device auth: autorest/azure/devicetoken: Error while retrieving OAuth token: Code Expired"]
```

**Comment by colemickens** [comment]
@billpratt @ivanpaulovich we need a separate bug for the issue you're seeing.

@lzachmann thanks for the information

**Comment by ivanpaulovich** [comment]
@lzachmann the problem I am facing is the same as yours. I have two subscriptions, for one subscription it works and for the other the create-machine command fails at login. I think the create-machine is using a fixed subscription id.

**Comment by colemickens** [comment]
@ivanpaulovich The error you got is *not* the same. `Requested tenant identifier '00000000-0000-0000-0000-000000000000' is not valid. Tenant identifiers may not be an empty GUID.` is a new issue. It is NOT the same as what @lzachmann  is reporting, which is the error which terminates with `Error when processing DeviceAuthRedirect request`. Please file a new issue so we can triage there. This issue is already pretty muddled.

**Comment by billpratt** [comment]
@colemickens I think I found the issue. According to the Azure documentation on Docker, an Azure Active Directory account is needed. After creating an AAD account by running the steps from [here](https://docs.microsoft.com/en-us/azure/virtual-machines/windows/create-aad-work-id) I was able to login and create a VM using docker-machine.

More info
https://docs.docker.com/machine/drivers/azure/#authentication

**Comment by colemickens** [comment]
@billpratt I'm not seeing anywhere on that page that says you have to use an Organizational Account. Microsoft (Service) Accounts **should** also be able to authenticate to AAD and use this application. But, as mentioned, if you see this again (with the all zero's GUID), please, please, please run docker-machine in verbose mode and then open a new Issue so we can get to the bottom of it without diluting this thread which is about the `Error when processing DeviceAuthRedirect request`.

**Comment by billpratt** [comment]
@colemickens Please see https://github.com/docker/machine/issues/4062
