### ISSUE TITLE
--amazonec2-retries "120" still results in only waiting for 60 retries

### ISSUE THREAD

**Issue by FireballDWF** [docker/machine#3341]
Even when 
--amazonec2-retries "120" 
is specified on the command line, still getting error that the default max of 60 is exceeded.

Waiting for SSH to be available...
Error creating machine: Error detecting OS: Too many retries waiting for SSH to be available.  Last error: Maximum number of retries (60) exceeded

**Comment by nathanleclaire** [comment]
It's different specification for retries.  Those 60 retries are for when the machine waits for ssh to be available.  I know it's a bit confusing but not sure what to do about it.
