### ISSUE TITLE
How to create docker machine from a specific version of boot2docker?

### ISSUE THREAD

**Issue by f-w** [docker/machine#3346]
Due to downstream software version dependency I would like to install an older version of docker (1.10.3 instead of latest 1.11.0). I replaced ~/.docker/machine/cache/boot2docker.iso to the old version but  `docker-machine create` seems always pulling latest version:

```
$docker-machine create --driver virtualbox xxx
Running pre-create checks...
(xxx) Unable to get the local Boot2Docker ISO version:  EOF
(xxx) Default Boot2Docker ISO is out-of-date, downloading the latest release...
(xxx) Latest release for github.com/boot2docker/boot2docker is v1.11.0

```

**Comment by f-w** [comment]
`--virtualbox-boot2docker-url`

**Comment by hekaldama** [comment]
@f-w dumb question, where do we get a list of url's for old images?

**Comment by hekaldama** [comment]
I am using: https://github.com/boot2docker/boot2docker/releases, seems like it works although I don't like that it only uses one image in its cache :/.

**Comment by f-w** [comment]
That's what I use.

**Comment by drozzy** [comment]
For the sake of completeness, could some post a complete command example?

I'm not sure which url to paste... is it this one? https://github.com/boot2docker/boot2docker/releases/tag/v18.06.0-ce-rc1

**Comment by f-w** [comment]
Going from memory it's the iso url e.g. https://github.com/boot2docker/boot2docker/releases/download/v18.06.0-ce/boot2docker.iso

**Comment by rcadhikari** [comment]
Hope this might be helpful.

**Comment by flacoman91** [comment]
> For the sake of completeness, could some post a complete command example?
> 
> I'm not sure which url to paste... is it this one? https://github.com/boot2docker/boot2docker/releases/tag/v18.06.0-ce-rc1

Just posting this as it took me some time to figure out.

`docker-machine create  yourmachinename  --virtualbox-boot2docker-url https://github.com/boot2docker/boot2docker/releases/download/v18.09.3/boot2docker.iso
`
