### ISSUE TITLE
docker containers can not talk with localhost:port

### ISSUE THREAD

**Issue by st9x3st9** [docker/machine#3348]
I have a docker vm running inside docker-machine that has a container that needs to reach the address `localhost:28281` I am not able to reach the address. How do I give the vm/container permissions to speak with `localhost:28281`? Also I am using virtualbox, is there a way that I can add these settings through the command line.

**Comment by nathanleclaire** [comment]
```console
docker run -d -p 28281:28281 mycontainer
curl $(docker-machine ip):28281
```
