### ISSUE TITLE
Docker-Machine DNS pointing multiple VMs

### ISSUE THREAD

**Issue by psychok7** [docker/machine#3352]
I have a doubt regarding docker-machine.

So we have a staging machine with multiple services running and we usually just launch each service on a diferent port and then point the dns to to host ip to that specific port.

We want to migrate to docker-machine, but since the vm has it's own internal ip i am not sure how to configure this now.

Can i still point the dns of each service/site to my host ip and then to its specific port or i have to point it directly to the vm ip? Since i do not have permissions with the dns pointing it would be awesome if i could keep the dns the way it is and just change docker-machine to pickup the port or something like that.

thanks

**Comment by nathanleclaire** [comment]
What exactly what you are referring to by "pointing DNS" here?  IIRC DNS can't map directly to ports, only IP addresses (unless it's a [SRV record](https://en.wikipedia.org/wiki/SRV_record) I guess?)

**Comment by nathanleclaire** [comment]
Closing unless I hear back.
