### ISSUE TITLE
Unable to create a docker-machine with devicemapper on VirtualBox (1.11.0)

### ISSUE THREAD

**Issue by schmunk42** [docker/machine#3354]
I've recently upgraded our bare-metal machine to `Linux fujitsu 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt25-2 (2016-04-08) x86_64 GNU/Linux` and VirtualBox to `5.0.18r106667`.

I can no longer create machines with storage driver devicemapper, `docker.log` says:

    devmapper: Udev sync is not supported. This will lead to data loss and unexpected behavior

See [gist](https://gist.github.com/schmunk42/efda3db21fadec512c2ebb605573c954) for full debug log output (IPs in both logs are different, since I tried this multiple times).

```
root@fujitsu:~# docker-machine version
docker-machine version 0.7.0, build a650a40
```

**Comment by schmunk42** [comment]
Related: https://github.com/docker/docker/issues/14224

AFAIR I was able to use `devicemapper` with 1.10.x and VirtualBox 4.x - I needed that, because I had issues with `aufs` on large git clones.

**Comment by nathanleclaire** [comment]
It's not supported anymore, sorry.  Try `overlay`, it's pretty good.
