### ISSUE TITLE
docker-machine ssh in v1.11.0 broken when talking to 1.10.3 instances

### ISSUE THREAD

**Issue by FireballDWF** [docker/machine#3359]
1. docker-machine ssh in v1.11.0 broken when talking to 1.10.3 engines 
2. However it works with --native-ssh flag.  
3. Not broken when talking to 1.11.0 engines
4. In the first example below, notice how it complains about permissions, but the permissions are what they should be

$ docker-machine ssh aws-demo2
Permissions 0400 for '/Users/olddfiliatrault/.docker/machine/machines/aws-demo2/id_rsa' are too open.

$ ls -al /Users/olddfiliatrault/.docker/machine/machines/aws-demo2/id_rsa
-r--------  1 olddfiliatrault  staff  1696 Mar  6 15:16 /Users/olddfiliatrault/.docker/machine/machines/aws-demo2/id_rsa

$ docker-machine --native-ssh ssh aws-demo2
Welcome to Ubuntu 15.10 (GNU/Linux 4.2.0-18-generic x86_64)
Last login: Fri Apr 22 14:29:16 2016 from 10.0.0.144
ubuntu@aws-demo2:~$ 

$ docker-machine ls
NAME        ACTIVE   DRIVER       STATE     URL                     SWARM   DOCKER    ERRORS
aws-demo2   *        amazonec2    Running   tcp://10.0.6.20:2376            v1.10.3   
default     -        virtualbox   Stopped                                   Unknown   
qa3         -        amazonec2    Running   tcp://10.0.4.222:2376           v1.10.3   
uat         -        amazonec2    Running   tcp://10.0.4.23:2376            v1.11.0   
$ docker-machine --version
docker-machine version 0.7.0, build a650a40
$ docker-machine ssh uat
Welcome to Ubuntu 15.10 (GNU/Linux 4.2.0-35-generic x86_64)
ubuntu@uat:~$

**Comment by FireballDWF** [comment]
I think the issue I report above should be easier to debug, and the fix will likely fix the following issue, which I also used the --native-ssh to workaround.  A script calling the create command with the amazonec2 driver worked fine with the 1.10.3 release, but after upgrading to 1.11.0 release, received the same error as the issue reported above, and was worked around by adding the --native-ssh flag.  End of the error output:
(uat) DBG | -----------------------------------------------------
(uat) Calling .GetSSHKeyPath
(uat) Calling .GetSSHUsername
Using SSH client type: external
Using SSH private key: /Users/olddfiliatrault/.docker/machine/machines/uat/id_rsa (-r--------)
<nil>
Error getting ssh command 'exit 0' : Permissions 0400 for '/Users/olddfiliatrault/.docker/machine/machines/uat/id_rsa' are too open.
Error creating machine: Error detecting OS: Too many retries waiting for SSH to be available.  Last error: Maximum number of retries (60) exceeded
Opting out of crash reporting.
Create uat failed

**Comment by FireballDWF** [comment]
One of the options I'm using is "--amazonec2-ssh-keypath" so may be related to #3268

**Comment by bamarni** [comment]
@FireballDWF : it seems to be introduced in https://github.com/docker/machine/commit/be8f469a828ffd6ad8ca0baaef017c49e3bab713 and should be fixed with #3381.

As a quick & dirty workaround until the next release you could manually chmod this key to 600.

**Comment by bamarni** [comment]
@nathanleclaire I'm wondering if https://github.com/docker/machine/commit/be8f469a828ffd6ad8ca0baaef017c49e3bab713 shouldn't be reverted instead of merging my PR. It caused a few false positives and kind of "duplicates" the ssh binary behaviour. If the original intention was to have more helpful error messages, maybe the default could be to print the output when a SSH command is failing?
