### ISSUE TITLE
Machine startup order not preserved

### ISSUE THREAD

**Issue by arun-gupta** [docker/machine#3372]
Trying to start two machines as `docker-machine start default test` shows the output as:

```
docker-machine start default test
Starting "test"...
Starting "default"...
```

This is also reported at https://github.com/docker/community/issues/56.

Can the order be defined? Or may be the machines should start in the order specified?

**Comment by nathanleclaire** [comment]
Why would you need startup order to be deterministic?

**Comment by arun-gupta** [comment]
This is required if a Docker Swarm cluster is coming up. For example Consul machine need to come up first, then Master and then other workers.

**Comment by nathanleclaire** [comment]
Why not `docker-machine start kvstore; docker-machine start foo bar`?  It's equally easy and doesn't hardcode implicit behavior based on argument ordering into Machine.

**Comment by nathanleclaire** [comment]
Also, when you invoke `docker-machine start foo quux bar`, `foo`, `quux`, and `bar` (in most drivers' case, `virtualbox` is a special exception) are all sent requests to stop concurrently.  This is a deliberate design to make stopping instances concurrently possible.

**Comment by arun-gupta** [comment]
This makes sense!

**Comment by nathanleclaire** [comment]
👍
