### ISSUE TITLE
docker-machine create ignore options engine-opt and engine-env

### ISSUE THREAD

**Issue by rodrigozc** [docker/machine#3377]
I'm trying to create a machine with some proxy env variables and another DNS, but these options is not working.

First Try:
`docker-machine create --driver virtualbox --engine-opt="dns=8.8.8.8" --engine-env="HTTP_PROXY=http://proxy.enterprise.br:8080/" --engine-env="HTTPS_PROXY=http://proxy.enterprise.br:8080/" dev`

Second Try:
`docker-machine create --driver virtualbox --engine-opt  dns=8.8.8.8 --engine-env HTTP_PROXY=http://proxy.enterprise.br:8080/ --engine-env HTTPS_PROXY=http://proxy.enterprise.br:8080/ dev`

On machine, env command does not show proxy env variables and dns is not set at /etc/resolv.conf.

**Comment by mdeggers** [comment]
The following environment:

Windows 10 Professional 1903 64 bit
Docker Desktop 18.09.02

From an administrative level PowerShell window, both will fail to edit /etc/resolv.conf on the virtual machine.

```
docker-machine create -d hyperv --hyperv-virtual-switch "myswitch" --engine-opt 'dns=192.168.0.202' myvm1

docker-machine create -d hyperv --hyperv-virtual-switch "myswitch" --engine-opt dns=192.168.0.202 myvm1
```
/etc/resolv.conf can be changed by the following:

```
docker-machine ssh virtual_machine_name
$ sudo -i
# cd /etc
# echo "search home" > resolv.conf
# echo "nameserver nameserver_ip_address" >> resolv.conf
# /etc/init.d/docker restart
```

This will not survive a virtual machine restart.

I could find no setting in either the Hyper-V switch or the network interface that would supply the proper DNS when creating a virtual machine. I suspect that the only way this works is to make sure that the DHCP provider sends the appropriate DNS server information.
