### ISSUE TITLE
Azure Driver https://aka.ms/devicelogin timeout too short

### ISSUE THREAD

**Issue by flomader** [docker/machine#3380]
When I do a docker-machine ls I have to do an Azure device login:

Microsoft Azure: To sign in, use a web browser to open the page https://aka.ms/devicelogin. Enter the code CH6Z7YUDJ to authenticate.

The login times out after only 10sec. This is not enough time to finish the device login.
Unfortunately I cannot access my machines because of the failed login.

This happens on Windows and OSX.
docker-machine version 0.7.0, build a650a40

**Comment by ahmetalpbalkan** [comment]
@flomader can you please run `docker-machine --debug ...` and send output (or better a screencast)? I wonder what the error is, it should be running for at least 5 minutes. (or at least nobody else reported this issue so far)

**Comment by flomader** [comment]
Thanks for looking into this.
Since I don't want to expose my subscription id and tenant id, here's a screencast without debug flag to show the timing: http://bit.ly/1TxllvP
and here the text output of docker-machine --debug ls: http://bit.ly/237njWs

**Comment by ahmetalpbalkan** [comment]
@flomader ah that timeout is `docker-machine`s timeout to hear back from drivers. Unfortunately azure authentication is far from ideal right now but this is the only thing we got. When Azure credentials expire and you see that message, try running `docker-machine ip` or `docker-machine ssh`, those commands wait a lot longer.

**Comment by flomader** [comment]
@ahmetalpbalkan thanks for the workaround!

**Comment by curry684** [comment]
18 months later this issue is still around. Is there any known workaround for getting rid of the expiring logins altogether? This makes our autoscaling CI setup nearly useless as it crashes and burns about twice a month.

**Comment by stedwick** [comment]
+1
