### ISSUE TITLE
How to ssh to boot2docker without virtualbox NAT network

### ISSUE THREAD

**Issue by bobzhangyong** [docker/machine#3382]
Hi all

I found if I remove NAT network from virtualbox, I can't ssh to boot2docker by command : docker-machine ssh default 

After run docker-machine  -D ssh default, I found it ssh to 127.0.0.1 and port 56383 (I think it's a rand port). And virtualbox use a NAT network to forward 56383 to boot2docker 22  port.

How can I ssh to boot2docker by 192.168.99.100(boot2docker ip address) and port 22.

Thank you

**Comment by nathanleclaire** [comment]
Does SSHing to 192.168.99.100:22 not work?

**Comment by nathanleclaire** [comment]
Take a look at the SSH command invoked if you run with `--debug` and you can probably get it working by swapping out the host and port for the host only versions instead.

**Comment by bobzhangyong** [comment]
If sshing to 192.168.99.100:22 it work, but ` docker-machine ssh default` not work, also run `docker-machine ls` will get an error.

The result like this 

> PS E:\ProjectDir> docker-machine.exe ls
> NAME      ACTIVE   DRIVER       STATE     URL   SWARM   DOCKER    ERRORS
> default   *        virtualbox   Running                 Unknown   Something went wrong running an SSH command!
> command : ip addr show
> err     : exit status 255
> output  :

**Comment by nathanleclaire** [comment]
Removing the NAT network is considered "voiding the warranty".  We can't account every single possible state that manual intervention can introduce.  If you'd like to use `docker-machine ssh`, please don't disable the NAT network.  Thanks
