### ISSUE TITLE
Use SSH Username/Password with Native Client

### ISSUE THREAD

**Issue by blackms** [docker/machine#3385]
Hello,

I'm trying to develop a new driver for docker machine, but I can't push a public key inside the VM before the creation, so I need to use ssh username and password, and I see that it's possible via Native Client, someone could explain to me how to pass to `GetSSHClientFromDriver` inside `drivers/utils.go` the object ssh.Auth with the password? 

Thank you.

**Comment by nathanleclaire** [comment]
I don't think we want to support password-based auth at all if possible.  Why can't you drop a key onto the machine?

**Comment by blackms** [comment]
Because I don't have API capabilities to do it. Maybe I'm missing something, but I didn't find any way to push the key, I still need a first connection with user/pass. Is there some other way to do it?

**Comment by nathanleclaire** [comment]
We have to limit the scope of what type of access points we're willing to support, so I am not in favor of this change at this time.  The vast majority of cloud providers and/or systems where you might want to use Machine support key-based authentication and it is far superior to password-based auth.
