### ISSUE TITLE
vmwarevsphere: exit status 255 when try to docker-machine ssh

### ISSUE THREAD

**Issue by marcuslinke** [docker/machine#3388]
Docker Machine Version:  0.7.0, build a650a40

@frapposelli I've stumbled upon a problem when trying to do a `docker-machine ssh` into a machine created via `vmwarevsphere` driver. The problem is that it tries to connect to the wrong ip address. In the example below `docker-dev-2` has an external routable ip address 10.32.23.180 but it tries to connect to 172.18.0.1 which is a bridge interface.  I've created several machines exactly the same way but only some of them are affected by the issue. It seems this is related to the order of the reported ip addresses in vsphere somehow (see attached screenshot).

```
$ docker-machine -D ssh docker-dev-2
Docker Machine Version:  0.7.0, build a650a40
Found binary path at /usr/local/bin/docker-machine
Launching plugin server for driver vmwarevsphere
Plugin server listening at address 127.0.0.1:58422
() Calling .GetVersion
Using API Version  1
() Calling .SetConfigRaw
() Calling .GetMachineName
(docker-dev-2) Calling .GetState
(docker-dev-2) Calling .GetSSHHostname
(docker-dev-2) Calling .GetSSHPort
(docker-dev-2) Calling .GetSSHKeyPath
(docker-dev-2) Calling .GetSSHKeyPath
(docker-dev-2) Calling .GetSSHUsername
Using SSH client type: external
Using SSH private key: /Users/marcus/.docker/machine/machines/docker-dev-2/id_rsa (-rw-------)
&{[-F /dev/null -o BatchMode=yes -o PasswordAuthentication=no -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=quiet -o ConnectionAttempts=3 -o ConnectTimeout=10 -o ControlMaster=no -o ControlPath=none docker@172.18.0.1 -o IdentitiesOnly=yes -i /Users/marcus/.docker/machine/machines/docker-dev-2/id_rsa -p 22] /usr/bin/ssh <nil>}
&{/usr/bin/ssh [/usr/bin/ssh -F /dev/null -o BatchMode=yes -o PasswordAuthentication=no -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=quiet -o ConnectionAttempts=3 -o ConnectTimeout=10 -o ControlMaster=no -o ControlPath=none docker@172.18.0.1 -o IdentitiesOnly=yes -i /Users/marcus/.docker/machine/machines/docker-dev-2/id_rsa -p 22] []  <nil> <nil> <nil> [] <nil> <nil> <nil> <nil> false [] [] [] [] <nil>}
exit status 255
```
![bildschirmfoto 2016-04-28 um 10 15 03](https://cloud.githubusercontent.com/assets/2578608/14879562/3dcf51dc-0d2a-11e6-8dab-17e554496eaf.png)

**Comment by marcuslinke** [comment]
The problem seems to be that `vm.WaitForIP` which is called here https://github.com/docker/machine/blob/v0.7.0/drivers/vmwarevsphere/vsphere.go#L242 returns only the first ip address: https://github.com/vmware/govmomi/blob/master/object/virtual_machine.go#L218

**Comment by nathanleclaire** [comment]
@frapposelli

**Comment by tyrken** [comment]
Getting a similar issue here - "docker-machine ls" is reporting the instance as timeout as it tries to use the first IP, 172.x, rather than the external IP, 10.x.  Not sure if govmomi should be extended to report all addresses, or whether docker-machine can get this already & so try all of them.

**Comment by RealKanashii** [comment]
I still getting this error and I dont know why if it's fixed. More info on #3538


```
$ docker-machine -v
docker-machine.exe version 0.7.0, build a650a40

$ docker -v
Docker version 1.11.1, build 5604cbe
```
