### ISSUE TITLE
docker on azure cloud

### ISSUE THREAD

**Issue by sachinvgaikwad** [docker/machine#3390]
Hi have a 2016 server on azure I install docker on it but I am getting error when starts asks me for vt-x enable , it a cloud server I cannot enable it on bios so i tried [ wmic cpu get VirtualizationFirmwareEnabled] but it false so what more can i do plz help

**Comment by nathanleclaire** [comment]
Assuming that's what you're attempting here, you shouldn't use `virtualbox` driver nested inside other types of virtualization.

You can install Docker directly on Linux using `curl get.docker.com | sh`.
