### ISSUE TITLE
inconsistent output between `docker ps`   vs   `api /containers/json?all=1` on Mac

### ISSUE THREAD

**Issue by denisbetsi** [docker/machine#3398]
`docker ps`

Output:
```
CONTAINER ID        IMAGE                                    COMMAND                  CREATED             STATUS              PORTS               NAMES
ec55381f70e1        docker.marathon.mesos:5000/docker-grad   "bin/herimports-grad-"   2 hours ago         Up 2 hours                              clever_yonath

```

Running a remote API query to see containers
`
curl      --cacert ~/.boot2docker/certs/boot2docker-vm/ca.pem      --cert ~/.boot2docker/certs/boot2docker-vm/b2d-client-side.p12:tcuser       https://$(boot2docker ip):2376/v1.23/containers/json?all=1`

Output:
`[{"Id":"1b02748c3b314a5e4a78c1a057d85c014b3c33f3c77248356c529342d82d9921","Names":["/grave_saha"],"Image":"hello-world","ImageID":"sha256:94df4f0ce8a4d4d4c030b9bdfe91fc9cf6a4b7be914542315ef93a046d520614","Command":"/hello","Created":1461952280,"Ports":[],"Labels":{},"State":"exited","Status":"Exited (0) 2 hours ago","HostConfig":{"NetworkMode":"default"},"NetworkSettings":{"Networks":{"bridge":{"IPAMConfig":null,"Links":null,"Aliases":null,"NetworkID":"","EndpointID":"","Gateway":"","IPAddress":"","IPPrefixLen":0,"IPv6Gateway":"","GlobalIPv6Address":"","GlobalIPv6PrefixLen":0,"MacAddress":""}}},"Mounts":[]}]`

Attempts to get stats on containerID available in docker ps results in Container Not found.

I am on a mac `El Capitan 10.11.3`

Docker version
```
Client:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Tue Apr 26 23:44:17 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Wed Apr 27 00:34:20 2016
 OS/Arch:      linux/amd64
```

Why is docker ps reporting different then remote API, are these not related?

**Comment by nathanleclaire** [comment]
It's `boot2docker` CLI you're using here?

I can't answer tickets for it -- please re-open if you have an issue with Machine.  Thanks
