### ISSUE TITLE
Dead link on the document: "Get started with Docker Machine and a local VM"

### ISSUE THREAD

**Issue by shigemk2** [docker/machine#3400]
There is a dead link on the bottom of [Get started with Docker Machine and a local VM](https://docs.docker.com/machine/get-started/), [Docker Machine driver reference](https://docs.docker.com/machine/drivers/index.md).

Is this link url not https://docs.docker.com/machine/drivers/index.md but https://docs.docker.com/machine/drivers/ ?

**Comment by shigemk2** [comment]
I want to send a pull-request, but I couldn't find source code for [Get started with Docker Machine and a local VM](https://docs.docker.com/machine/get-started/).

**Comment by thaJeztah** [comment]
Thanks for reporting! Looks like this was already fixed in the repository, but not yet published on the website. See this pull request; https://github.com/docker/machine/pull/3360/files

**Comment by shigemk2** [comment]
Thank you for your replying. 

> See this pull request; https://github.com/docker/machine/pull/3360/files

I see. Okay, I wait for your publishing on the website.

**Comment by nathanleclaire** [comment]
Why re-open?

**Comment by nathanleclaire** [comment]
If fixed, we should close.  The doc will be updated eventually

**Comment by shigemk2** [comment]
Sorry for reopening. I would close this issue if the page [Get started with Docker Machine and a local VM](https://docs.docker.com/machine/get-started/) is updated.

**Comment by nathanleclaire** [comment]
No problem just trying to keep the tracker as clean as possible.
