### ISSUE TITLE
Add tcsh support to env --shell

### ISSUE THREAD

**Issue by eedeebee** [docker/machine#3404]
Some older folks like me still use tcsh (really).  I will send a PR

**Comment by drewish** [comment]
yeah was kind of annoyed to discover this too

**Comment by drewish** [comment]
Got a quick version of this together but I'm not sure how to suggest sourcing it (or what the tests would need to look like):
```
git diff
diff --git a/commands/env.go b/commands/env.go
index d224e33..40eb3ca 100644
--- a/commands/env.go
+++ b/commands/env.go
@@ -138,6 +138,10 @@ func shellCfgSet(c CommandLine, api libmachine.API) (*ShellConfig, error) {
                shellCfg.Prefix = "(setenv \""
                shellCfg.Suffix = "\")\n"
                shellCfg.Delimiter = "\" \""
+       case "tcsh":
+               shellCfg.Prefix = "setenv "
+               shellCfg.Suffix = "\";\n"
+               shellCfg.Delimiter = " \""
        default:
                shellCfg.Prefix = "export "
                shellCfg.Suffix = "\"\n"
@@ -182,6 +186,10 @@ func shellCfgUnset(c CommandLine, api libmachine.API) (*ShellConfig, error) {
                shellCfg.Prefix = "(setenv \""
                shellCfg.Suffix = ")\n"
                shellCfg.Delimiter = "\" nil"
+       case "tcsh":
+               shellCfg.Prefix = "unsetenv "
+               shellCfg.Suffix = ";\n"
+               shellCfg.Delimiter = ""
        default:
                shellCfg.Prefix = "unset "
                shellCfg.Suffix = "\n"
@@ -249,6 +257,8 @@ func (g *EnvUsageHintGenerator) GenerateUsageHint(userShell string, args []strin
        case "emacs":
                cmd = fmt.Sprintf("(with-temp-buffer (shell-command \"%s\" (current-buffer)) (eval-buffer))", commandLine)
                comment = ";;"
+       case "tcsh":
+               cmd = fmt.Sprintf("source `%s`", commandLine)
        default:
                cmd = fmt.Sprintf("eval $(%s)", commandLine)
        }
```
That gives:
```
% ./docker-machine env
setenv DOCKER_TLS_VERIFY "1";
setenv DOCKER_HOST "tcp://192.168.99.100:2376";
setenv DOCKER_CERT_PATH "/Users/andrew/.docker/machine/machines/default";
setenv DOCKER_MACHINE_NAME "default";
# Run this command to configure your shell: 
# source ./docker-machine env
```

Trying it as `source` it seems like it wants to read the file rather than execute it:
```
% set verbose
% source ./docker-machine env
source ./docker-machine env
????^G^A^C^B^O?^G^A^YH__PAGEZERO^P^Y ( ^B__TEXT^P ) ^B ) ^B^G^E^F__text__TEXT G??^P^D^D__rodata__TEXT`?Ϟ??`??^E__typelink__TEXT??^A??^B??^A^C__gosymtab__TEXT???^A???^A__gopclntab__TEXT???^AEx}???^A^E__symbol_stub1__TEXT ^K ) ^B? ? ( ^B^E^H^D?^F^Y?^A__DATA^P ) ^B ?^D ) ^B? ) ^B^C^C^E__nl_symbol_ptr__DATA^P ) ^BP^A ) ^B^B^F'__noptrdata__DATA`^Q)^B?I^A`^A)^B^E__data__DATA[*^B??K*^B^E__bss__DATA?9+^B??^A^E^A__noptrbss__DATA?'-^B?q^E^A^YH__LINKEDIT?-^BTdD0+^BTdD^G^C^E?^D*?"^F^B^X0+^Bδ$~6^B0^V9^KP????^D??*?|6^BQ^N ^L/usr/lib/dyld^L8^X/usr/lib/libSystem.B.dylib^Lh^X/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation^L`^X/System/Library/Frameworks/Security.framework/Versions/A/Security^L8^X/usr/lib/libSystem.B.dylib^L8^X/usr/lib/libSystem.B.dylib^L8^X/usr/lib/libSystem.B.dylib$^P^G
Illegal variable name.
```

Trying it as `eval` gets the variables set, but errors when it gets to the comments:
```
eval `./docker-machine env`
setenv DOCKER_TLS_VERIFY "1" ; setenv DOCKER_HOST "tcp://192.168.99.100:2376" ; setenv DOCKER_CERT_PATH "/Users/andrew/.docker/machine/machines/default" ; setenv DOCKER_MACHINE_NAME "default" ; # Run this command to configure your shell: # source ./docker-machine env
#: Command not found.
% setenv | grep DOCKER
setenv | grep DOCKER
DOCKER_TLS_VERIFY=1
DOCKER_HOST=tcp://192.168.99.100:2376
DOCKER_CERT_PATH=/Users/andrew/.docker/machine/machines/default
DOCKER_MACHINE_NAME=default
```

So perhaps someone that knows tcsh better than I do can explain the correct way to source this.

**Comment by eedeebee** [comment]
I pushed this last night: https://github.com/docker/machine/pull/3405,
including tests and docs.

Eric


On Wed, May 4, 2016 at 12:00 PM, andrew morton <notifications@github.com>
wrote:

> Got a quick version of this together but I'm not sure how to suggest
> sourcing it (or what the tests would need to look like):
>
> git diff
> diff --git a/commands/env.go b/commands/env.go
> index d224e33..40eb3ca 100644
> --- a/commands/env.go
> +++ b/commands/env.go
> @@ -138,6 +138,10 @@ func shellCfgSet(c CommandLine, api libmachine.API) (*ShellConfig, error) {
>                 shellCfg.Prefix = "(setenv \""
>                 shellCfg.Suffix = "\")\n"
>                 shellCfg.Delimiter = "\" \""
> +       case "tcsh":
> +               shellCfg.Prefix = "setenv "
> +               shellCfg.Suffix = "\";\n"
> +               shellCfg.Delimiter = " \""
>         default:
>                 shellCfg.Prefix = "export "
>                 shellCfg.Suffix = "\"\n"
> @@ -182,6 +186,10 @@ func shellCfgUnset(c CommandLine, api libmachine.API) (*ShellConfig, error) {
>                 shellCfg.Prefix = "(setenv \""
>                 shellCfg.Suffix = ")\n"
>                 shellCfg.Delimiter = "\" nil"
> +       case "tcsh":
> +               shellCfg.Prefix = "unsetenv "
> +               shellCfg.Suffix = ";\n"
> +               shellCfg.Delimiter = ""
>         default:
>                 shellCfg.Prefix = "unset "
>                 shellCfg.Suffix = "\n"
> @@ -249,6 +257,8 @@ func (g *EnvUsageHintGenerator) GenerateUsageHint(userShell string, args []strin
>         case "emacs":
>                 cmd = fmt.Sprintf("(with-temp-buffer (shell-command \"%s\" (current-buffer)) (eval-buffer))", commandLine)
>                 comment = ";;"
> +       case "tcsh":
> +               cmd = fmt.Sprintf("source `%s`", commandLine)
>         default:
>                 cmd = fmt.Sprintf("eval $(%s)", commandLine)
>         }
>
> That gives:
>
> % ./docker-machine env
> setenv DOCKER_TLS_VERIFY "1";
> setenv DOCKER_HOST "tcp://192.168.99.100:2376";
> setenv DOCKER_CERT_PATH "/Users/andrew/.docker/machine/machines/default";
> setenv DOCKER_MACHINE_NAME "default";
> # Run this command to configure your shell:
> # source ./docker-machine env
>
> Trying it as source it seems like it wants to read the file rather than
> execute it:
>
> % set verbose
> % source ./docker-machine env
> source ./docker-machine env
> ????^G^A^C^B^O?^G^A^YH__PAGEZERO^P^Y ( ^B__TEXT^P ) ^B ) ^B^G^E^F__text__TEXT G??^P^D^D__rodata__TEXT`?Ϟ??`??^E__typelink__TEXT??^A??^B??^A^C__gosymtab__TEXT???^A???^A__gopclntab__TEXT???^AEx}???^A^E__symbol_stub1__TEXT ^K ) ^B? ? ( ^B^E^H^D?^F^Y?^A__DATA^P ) ^B ?^D ) ^B? ) ^B^C^C^E__nl_symbol_ptr__DATA^P ) ^BP^A ) ^B^B^F'__noptrdata__DATA`^Q)^B?I^A`^A)^B^E__data__DATA[*^B??K*^B^E__bss__DATA?9+^B??^A^E^A__noptrbss__DATA?'-^B?q^E^A^YH__LINKEDIT?-^BTdD0+^BTdD^G^C^E?^D*?"^F^B^X0+^Bδ$~6^B0^V9^KP????^D??*?|6^BQ^N ^L/usr/lib/dyld^L8^X/usr/lib/libSystem.B.dylib^Lh^X/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation^L`^X/System/Library/Frameworks/Security.framework/Versions/A/Security^L8^X/usr/lib/libSystem.B.dylib^L8^X/usr/lib/libSystem.B.dylib^L8^X/usr/lib/libSystem.B.dylib$^P^G
> Illegal variable name.
>
> Trying it as eval gets the variables set, but errors when it gets to the
> comments:
>
> eval `./docker-machine env`
> setenv DOCKER_TLS_VERIFY "1" ; setenv DOCKER_HOST "tcp://192.168.99.100:2376" ; setenv DOCKER_CERT_PATH "/Users/andrew/.docker/machine/machines/default" ; setenv DOCKER_MACHINE_NAME "default" ; # Run this command to configure your shell: # source ./docker-machine env
> #: Command not found.
> % setenv | grep DOCKER
> setenv | grep DOCKER
> DOCKER_TLS_VERIFY=1
> DOCKER_HOST=tcp://192.168.99.100:2376
> DOCKER_CERT_PATH=/Users/andrew/.docker/machine/machines/default
> DOCKER_MACHINE_NAME=default
>
> So perhaps someone that knows tcsh better than I do can explain the
> correct way to source this.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/docker/machine/issues/3404#issuecomment-216967456>
>



-- 
Eric Bloch

  @eedeebee
  15 Miranda Court, Hillsborough CA 94010
  Email: eric.bloch@gmail.com
  Phone: 650-339-0376

**Comment by drewish** [comment]
@eedeebee you should stick a "fixes #3404" in the commit so it'll link up with this issue and close it when that gets merged.

**Comment by drewish** [comment]
Oh nice, using the `:` null command as the comment character makes a ton of sense.

**Comment by eedeebee** [comment]
I tried to follow the contrib doc and didn't see the request for that bit in the commit, but I can easily add it :)

E

**Comment by drewish** [comment]
Oh yeah that's just a github-ism.

**Comment by drewish** [comment]
Just for reference, I was reading through the contributing guidelines and noticed the do mention the "fixes #XXX":
> Include an issue reference like Closes #XXXX or Fixes #XXXX in commits that close an issue. Including references automatically closes the issue on a merge.
https://github.com/docker/docker/blob/master/CONTRIBUTING.md#conventions

**Comment by eedeebee** [comment]
Thanks, I"ll try to take care of that int he next day or so as I don't have
dev handy for the next bit.

On Mon, May 9, 2016 at 8:37 AM, andrew morton <notifications@github.com>
wrote:

> Just for reference, I was reading through the contributing guidelines and
> noticed the do mention the "fixes #XXX":
>
> Include an issue reference like Closes #XXXX or Fixes #XXXX in commits
> that close an issue. Including references automatically closes the issue on
> a merge.
> https://github.com/docker/docker/blob/master/CONTRIBUTING.md#conventions
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/docker/machine/issues/3404#issuecomment-217900830>
>



-- 
Eric Bloch

  @eedeebee
  15 Miranda Court, Hillsborough CA 94010
  Email: eric.bloch@gmail.com
  Phone: 650-339-0376

**Comment by drewish** [comment]
Oh, it looked like you already did that. I was more just calling out that they actively use that GitHub feature. I'm still getting up to speed with how this project operates.

**Comment by eedeebee** [comment]
Thanks I'm guessing there's some IRC channel or somewhere else where I should actually mention or introduce the change and see if I can find somebody who's a committer who is interested in merging it in
