### ISSUE TITLE
Azure & Docker-machine

### ISSUE THREAD

**Issue by Delpedro** [docker/machine#3408]
If a user creates a vm / node using docker-machine (Not in the portal!!!) as follows ;

_docker-machine create -d azure vm1 _
(and forgets to add the (--azure-open-port) or even only adds one port i.e 80)

How does a user add additional ports in order for the containers to be accessible externally? 

using **_azure config mode asm_** c/w with the Azure Cli a user could add endpoints

But how does a user use **_azure config mode arm_**  c/w Azure Cli to add additional endpoints / port numbers so a container can be accessed i.e. 8080 for cAdvisor?

@nathanleclaire @ahmetalpbalkan

**Comment by ahmetalpbalkan** [comment]
@Delpedro your easiest way of opening port 80 will be going to the Azure Portal (portal.azure.com) and seeing what an `--azure-open-port` looks like on a machine that has it. There will be a resource called `{machinename}-firewall`, if you click on it you can see the firewall rule and add it to the missing machine's `-firewall` resource.

If you want to learn how to do it in the CLI, first you need to study this documentation about what Network Security Groups (a construct that carries firewall/network access rules) https://azure.microsoft.com/en-us/documentation/articles/virtual-networks-nsg/ and use the **`azure network nsg rule`** command to create and manage opening of ports.

My suggestion is to go through the Azure Portal route.

**Comment by ahmetalpbalkan** [comment]
@nathanleclaire please close

**Comment by nathanleclaire** [comment]
Sure thanks @ahmetalpbalkan
