### ISSUE TITLE
Please add AzureStack support to the docker machine driver

### ISSUE THREAD

**Issue by nilleb** [docker/machine#3415]
According to the issue 2907, the azure driver for docker machine supports instantiating Windows 2016 virtual machines on the azure cloud (along with the classical Linux VMs). 

It would be nice to have the possibility to instantiate virtual machines on AzureStack, too.

Reference: https://github.com/docker/machine/issues/2907#issuecomment-216905946

**Comment by ahmetalpbalkan** [comment]
@nilleb I'm not entirely sure how would that work. Does AzureStack have Active Directory Device Auth (aka.ms/deviceauth) as well? If not, that would require substantial code change.

I require just creating VMs with azure CLI and using `docker-machine create -d generic` to import the VM to docker-machine and provision accordingly. I don't think we're going to commit to implementing this anytime soon.
