### ISSUE TITLE
docker machine on OSX with multiple CPU cause pull image very slow

### ISSUE THREAD

**Issue by Noodle05** [docker/machine#3420]
Hi Docker Team,

I created few docker machine on my OSX (El Capital) to try out swarm. Since I have 16 CPU cores, I tried to allocate 4 CPUs to this machine. Command line I used to create docker machine:
docker-machine create -d virtualbox --virtualbox-memory=4096 --virtualbox-cpu-count=4 --virtualbox-disk-size=50000 --virtualbox-no-share default

After I create the docker machine, "docker pull <image>" is very slow, hangs on large layers. So I different command line combination, and found CPU counts is the root cause of the problem.

I searched, but didn't see anybody report this.

Version info:
```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 1.11.1
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 52
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: null host bridge
Kernel Version: 4.4.8-boot2docker
Operating System: Boot2Docker 1.11.1 (TCL 7.0); HEAD : 7954f54 - Wed Apr 27 16:36:45 UTC 2016
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 3.858 GiB
Name: default
ID: FGEQ:VYEN:FGSP:IAVK:Z3CG:LKE5:V3GV:V7BH:NN22:6Y33:MEL3:2X4I
Docker Root Dir: /mnt/sda1/var/lib/docker
Debug mode (client): false
Debug mode (server): true
 File Descriptors: 18
 Goroutines: 102
 System Time: 2016-05-09T22:04:31.606950653Z
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
```

uname -a:
```
Darwin wgao-wsm.internal.salesforce.com 15.4.0 Darwin Kernel Version 15.4.0: Fri Feb 26 22:08:05 PST 2016; root:xnu-3248.40.184~3/RELEASE_X86_64 x86_64
```

Thanks

Noodle

**Comment by nathanleclaire** [comment]
There are some cases where giving more CPU cores to the VM actually decreases performance, as you noted.  Since it seems to be a problem at the hypervisor level, there's likely nothing Machine can do, but consider filing a bug with the VirtualBox upstream.  Thanks
