### ISSUE TITLE
ssh command doesn't infer the machine name like other commands

### ISSUE THREAD

**Issue by scottbelden** [docker/machine#3421]
Unlike ```stop```, ```start```, ```restart```, and other commands that use "default" as the machine name if one is not provided, the ```ssh``` command still requires you to type the machine name. Is it there a reason this one doesn't work that way?

```bash
$ docker-machine version
docker-machine version 0.7.0, build a650a40

$ docker-machine ssh "echo hi"
Host does not exist: "echo hi"

$ docker-machine ssh default "echo hi"
hi
```

**Comment by bamarni** [comment]
It is similar to `create` or `stop` here : `docker-machine ssh` would log into `default`. But if you're providing a one-off command, how could it know if the first argument is your machine name or the first arg of your command? In that case the machine name has to be provided explicitly.

**Comment by scottbelden** [comment]
Ah, I see. My first suggestion would have been to just check the arg length, but I didn't realize that ```docker-machine ssh``` would ssh in without any arguments.

I'll close this. Thanks for the reply!
