### ISSUE TITLE
Ability to supply custom provisioner

### ISSUE THREAD

**Issue by wadetandy** [docker/machine#3429]
I work for an enterprise that relies heavily on RHEL within OpenStack.  Due to the heavily customized nature of our environment, the standard redhat provisioner doesn't work for our use case.  I've been able to modify the rhel provisioner class to take care of everything correctly, but this requires me to maintain that subclass in my own fork of docker machine.  What would be great would be the ability to explicitly declare the provisioner in the `docker create` CLI call, with the ability to provide a third party binary or something.  I am happy to work on something like this myself if you all think that would be useful, but I don't want to step on anything you're doing or work on something that would have no chance of being merged upstream.

If this is something that would be useful, I'd love some opinions on API and general implementation architecture.

**Comment by fsoppelsa** [comment]
We already have a plugins mechanism, you maybe can take a look to the KVM one [1] and proceed that way.

I suggest to close @nathanleclaire 

[1] https://github.com/dhiltgen/docker-machine-kvm

**Comment by nathanleclaire** [comment]
Thanks @fsoppelsa .  Yes I think provisioning plugins is something we're not particularly adamant about supporting, we would prefer instead to be opinionated for this piece.

**Comment by wadetandy** [comment]
Thanks guys, I wasn't previously aware of the plugin system.  @nathanleclaire I am a bit confused by your statement though.  Are you saying that this can be accomplished with a plugin, or plugins don't work with provisioners and you don't want to support that?
