### ISSUE TITLE
How can I install additional packages in boot2docker vm?

### ISSUE THREAD

**Issue by ovidiubuligan** [docker/machine#3447]
For example utility `tracert`  is not present.
Installing additional packages would be great  in order to get better tools for debugging configurations.(especially in corporate environments with multiple network connections and vpns)

**Comment by nathanleclaire** [comment]
`docker run` 😉 

(Seriously though, if you want to use the TCL package manager very badly, you can do this with `tce-load` e.g. `tce-load -iw rsync`)

**Comment by jeremyml** [comment]
I needed to install vim, so now I include this line at the end of my `/mnt/sda1/var/lib/boot2docker/bootsync.sh` file.  This will install it every time you restart the docker-machine.   You must install as docker.  The ampersand at the end forks the command into a background process so you can start using the machine immediatly and wait for vim to finish loading in the background.

`sudo su - docker -c 'tce-load -wi vim.tcz &'`

Kind of resource intensive though - it downloads the packages for every restart.  Requires internet too - don't expect it to work on a plane.
