### ISSUE TITLE
Is there any way to pass docker login to the docker-machine instances ?

### ISSUE THREAD

**Issue by dexterddit** [docker/machine#3458]
I am using a docker registry with login . And I would need the docker machines that i`m spawning to be able to login in to t that registry . Is this possible ?

**Comment by nathanleclaire** [comment]
If invoked from a client where you have run `docker login`, the login username and password should be sent over the wire automatically with `docker pull`, `docker run`, etc.  If you need to give the machine certificates for the registry I recommend using `docker-machine ssh` and `docker-machine scp` to set it up and send the certs over.

**Comment by dexterddit** [comment]
I`m running : 
 docker-machine create --driver $DOCKER_MACHINE_DRIVER \
    --engine-insecure-registry docker-hub.int:5002\
    --engine-registry-mirror http://docker-hub.int:5002\

so the docker login should be before this ?

**Comment by dexterddit** [comment]
Yup works fine thanks a lot

**Comment by nathanleclaire** [comment]
:thu
