### ISSUE TITLE
Error creating machine: Error in driver during machine creation Post https://x.x.x.x:5000/v2.0/tokens: x509: cannot validate certificate for x.x.x.x because it doesn’t contain any IP SANs

### ISSUE THREAD

**Issue by mvsimhareddy** [docker/machine#3460]
Error creating machine: Error in driver during machine creation Post https://x.x.x.x:5000/v2.0/tokens: x509: cannot validate certificate for x.x.x.x because it doesn’t contain any IP SANs

how can i resolve this issue.. I am trying it in openstack environment

**Comment by nathanleclaire** [comment]
Please provide more detail or we will be unable to help you reproduce.  Thanks
