### ISSUE TITLE
vSphere Provider gives 'SystemError'

### ISSUE THREAD

**Issue by TheDeadCode** [docker/machine#3462]
docker-machine create --driver vmwarevsphere --vmwarevsphere-username=root --vmwarevsphere-password=... --vmwarevsphere-vcenter=... --vmwarevsphere-network=Public\ VM\ Network vm

There are no generated logs.

Here are the only things I get:
```
Running pre-create checks...
Creating machine...
(vm) Copying /root/.docker/machine/cache/boot2docker.iso to /root/.docker/machine/machines/vm/boot2docker.iso...
(vm) Generating SSH Keypair...
(vm) Creating VM...
(vm) Uploading Boot2docker ISO ...
(vm) Reconfiguring VM...
Error creating machine: Error in driver during machine creation: SystemError
```

The VM is indeed created in the vSphere UI. (Not configured tho)

**Comment by TheDeadCode** [comment]
PS: Running ESXi 6.0

**Comment by TheDeadCode** [comment]
Although it works flawlessly on ESXi 5.5U1. 6.0 really seems to be the issue

**Comment by nathanleclaire** [comment]
@frapposelli

**Comment by frapposelli** [comment]
@TheDeadCode please run it again with `-D` to show debug log.
