### ISSUE TITLE
"tls: DialWithDialer timed out " error during docker-machine create

### ISSUE THREAD

**Issue by wayne0019** [docker/machine#3479]
when I doing docker-machine create, it failed due to the following error for many times:
**[Error creating machine: Error checking the host: Error check
ing and/or regenerating the certs: There was an error validating certificates fo
r host "10.200.39.81:2376": tls: DialWithDialer timed out
You can attempt to regenerate them using 'docker-machine regenerate-certs [name]'.
Be advised that this will trigger a Docker daemon restart which will stop running containers.]**

Actually, the machine has been created successfully, the machine  can be list by 'docker-machine ls' command, and can be managed by docker-machine.
After review the source code, it seems this failure is caused by **Certificate Validation Timeout** , in machine/libmachine/cert/cert.go
// ValidateCertificate validate the certificate installed on the vm.
func (xcg *X509CertGenerator) ValidateCertificate(addr string, authOptions *auth.Options) (bool, error) {
	tlsConfig, err := xcg.ReadTLSConfig(addr, authOptions)
	if err != nil {
		return false, err
	}

	dialer := &net.Dialer{
		Timeout: time.Second * 2,
	}

	_, err = tls.DialWithDialer(dialer, "tcp", addr, tlsConfig)
	if err != nil {
		return false, err
	}

	return true, nil
}

There is a timeout variable, and it's value is 2 second, it's not enough!   in some cases, this operation needs more time than 2 second. 
There should be a recursive check with specific time in above function, at least, the timeout value should be assigned to a bigger value. (10 or 20 seconds )

**Comment by wayne0019** [comment]
this problem will also affect docker-machine config command, as 'config' command will validate cert!

**Comment by callmephilip** [comment]
Seeing this issue in a very inconsistent way in our CI environment:

Ubuntu 16.04
Docker machine 0.8.1
Remote server runs on Digital Ocean

The following command 

```
docker-machine create --driver generic --generic-ip-address=<REMOTE-IP> --generic-ssh-key=<PATH_TO_PRIVATE_KEY> staging-server
```

Occasionally produces the following result:

```
Creating CA: /root/.docker/machine/certs/ca.pem
Creating client certificate: /root/.docker/machine/certs/cert.pem
Running pre-create checks...
Creating machine...
(staging-server) Importing SSH key...
(staging-server) Couldn't copy SSH public key : unable to copy ssh key: open <REMOTE-IP>.pub: no such file or directory
Waiting for machine to be running, this may take a few minutes...
Detecting operating system of created instance...
Waiting for SSH to be available...
Detecting the provisioner...
Provisioning with ubuntu(systemd)...
Installing Docker...
Copying certs to the local machine directory...
Copying certs to the remote machine...
Setting Docker configuration on the remote daemon...
Checking connection to Docker...
The default lines below are for a sh/bash shell, you can specify the shell you're using, with the --shell flag.
Error creating machine: Error checking the host: Error checking and/or regenerating the certs: There was an error validating certificates for host "<REMOTE-IP>:2376": tls: DialWithDialer timed out
You can attempt to regenerate them using 'docker-machine regenerate-certs [name]'.
Be advised that this will trigger a Docker daemon restart which will stop running containers.
```

Rerunning the command immediately produces this error

```
Host already exists: "staging-server"
```

**Comment by sblackstone** [comment]
I think I might be hitting this problem as well, I'm in the USA and the server is in Manila....

**Comment by sblackstone** [comment]
Update - almost sure this was it - I moved to a server in the same cluster I'm trying to build from and everything works like normal..
