### ISSUE TITLE
Why my docker machine is not getting activated?

### ISSUE THREAD

**Issue by Gauravwagh** [docker/machine#3480]
```
NAME       ACTIVE   DRIVER       STATE     URL                         SWARM   DOCKER    ERRORS
machine1   -        virtualbox   Running   tcp://192.168.99.100:2376           v1.11.2  
```

Then i run command

`eval $(sudo docker-machine env machine1)`

ls output is 

```
NAME       ACTIVE   DRIVER       STATE     URL                         SWARM   DOCKER    ERRORS
machine1   -        virtualbox   Running   tcp://192.168.99.100:2376           v1.11.2
``` 

Why my docker machine is not getting activated? I am using Ubuntu 14.01 LTS

**Comment by nathanleclaire** [comment]
probably the `sudo` -- you don't need `sudo` on `docker-machine` commands and probably environment vars set in `sudo`ed commands don't persist in the original shell session
