### ISSUE TITLE
docker-machine with generic-driver sets storage-driver to aufs

### ISSUE THREAD

**Issue by martinheidegger** [docker/machine#3483]
Using docker 1.11.2 build b9f10c9 I tried to create a docker machine with the generic driver. Unfortunately it switched the --storage-driver settings in /etc/default/docker to 'aufs' which doesn't work on my server that I tried to connect. The consequence was that the docker service on the server couldn't start anymore.

**Comment by nathanleclaire** [comment]
You can specify manually the `--engine-storage-driver` with `create`.

BTW, I read your book "Being and Time".  Haha

**Comment by martinheidegger** [comment]
Thank you for pointing me to the --engine-storage-driver option. I still think that docker-machine shouldn't change the driver option by default. It will confuse people and it is very hard to debug

**Comment by nathanleclaire** [comment]
The driver option is always `aufs` by default unless (IIRC) installing to Redhat derivative distributions.  Generally it's just difficult to account for every single possible permutation of distro and cloud provider (especially w/ generic driver).

**Comment by martinheidegger** [comment]
docker-machine installs docker when on the remote server when docker is not given. Why not "ask docker" which storage driver it is using after the installation and use that as default?

**Comment by nathanleclaire** [comment]
Not opposed to it, just hasn't been high priority to implement since `aufs` is extremely common.  Good suggestion IMO.

**Comment by martinheidegger** [comment]
Reopen bug? Note: linode Ubuntu 14.04 servers don't support aufs

**Comment by nathanleclaire** [comment]
I'd favor a new issue of feature request to auto-detect installed version if you don't mind, please.

**Comment by martinheidegger** [comment]
There you go: https://github.com/docker/machine/issues/3484
