### ISSUE TITLE
docker-machine env incorrectly identifies fish shell on master

### ISSUE THREAD

**Issue by vikstrous** [docker/machine#3496]
If you run the following within fish it produces fish syntax instead of bash syntax, which is unexpected and breaks some of our automated scripts:
```
$ bash -c 'docker-machine env name'
set -gx DOCKER_TLS_VERIFY "1";
set -gx DOCKER_HOST "tcp://52.36.94.168:2376";
set -gx DOCKER_CERT_PATH "/home/v/.docker/machine/machines/name";
set -gx DOCKER_MACHINE_NAME "name";
# Run this command to configure your shell: 
# eval (docker-machine env name)
```
I tested this on master.

It's clearly doing the wrong thing. It should at least only check the value of $SHELL. It seems to be checking some random variable in addition to $SHELL: https://github.com/docker/machine/blob/8141874120abdc5c9056b6dbeb09bfb76a3eb290/libmachine/shell/shell.go#L25

Better yet, I would like a flag that lets me control the output format. I would also like to have some more machine readable formats available.

**Comment by thaJeztah** [comment]
Perhaps the `--shell` flag is what you're looking for? https://github.com/docker/machine/blob/master/docs/reference/env.md

```bash
bash -c 'docker machine env --shell=bash'
```

**Comment by vikstrous** [comment]
Ah, makes sense. I was looking at the help from the wrong version of machine. This solves my immediate problem. I still don't think that docker machine should be looking at anything other than $SHELL.

**Comment by sakoht** [comment]
Yeah it seems like these lines should be removed:
https://github.com/docker/machine/blob/master/libmachine/shell/shell.go#L25-L27

If a user uses fish but runs a bash script that runs `docker-machine`, it incorrectly believes it is in fish.

At best they should be moved inside the condition above, where the shell is not set.
