### ISSUE TITLE
AWS docker-machine : use existing keypair instead creating new for every ec2 launched

### ISSUE THREAD

**Issue by somu4git** [docker/machine#3513]
How Can I create ec2 using docker-machine using existing keypair instead of docker-machine creates new one for each ec2 it launched.

currently I dont see any option for this :

**docker-machine create --driver amazonec2** --amazonec2-region us-west-2 --amazonec2-zone "a" --amazonec2-instance-type "t2.medium" --amazonec2-root-size "20" --amazonec2-access-key <xxxxxx> --amazonec2-secret-key <xxxxxx> --amazonec2-ami <ami-xxxx> --amazonec2-ssh-user oracle --amazonec2-security-group <sec group> --amazonec2-vpc-id <vpc-xxxx> <ec2-instance-name>

If there is no way ,how to login to that ec2 which is launched via **docker-machine create --driver amazonec2**

**Comment by nathanleclaire** [comment]
`--amazonec2-ssh-keypath`, basically

**Comment by somu4git** [comment]
Thanks nathan, is there any documentation available for this ? any samples available using --amazonec2-ssh-keypath ?

**Comment by somu4git** [comment]
finally able to make it work, but it is creating key name as machine name, but able to use the key provided as argument --amazonec2-ssh-keypath to login to the instance . 

Hope the key name issue also would be fixed soon.
