### ISSUE TITLE
Authentocation fails using docker machine azure similar #384

### ISSUE THREAD

**Issue by digeler** [docker/machine#3514]
Here is the details:
authenticate to machine driver docker :
 
Correlation ID: 94060a02-0396-4306-8b17-d7a7aa909b7c
Timestamp: 2016-06-14 14:44:58Z
AADSTS90093: Does not have access to consent.
Thanks

**Comment by ahmetalpbalkan** [comment]
@digeler which issue are you referring to in the title? 384 seems like an irrelevant one.

**Comment by ahmetalpbalkan** [comment]
@nathanleclaire please consider closing.
