### ISSUE TITLE
Azure driver: docker-machine active timeout

### ISSUE THREAD

**Issue by pcgeek86** [docker/machine#3525]
# Issue 

1. I created two Azure Docker Hosts using `docker-machine` with the Azure driver
2. I tried to call `docker-machine active`
3. I received the error message below

```
PS C:\Users\TrevorSullivan> docker-machine.exe active
docker-machine.exe : Error getting active host: timeout
At line:1 char:1
+ docker-machine.exe active
+ ~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Error getting active host: timeout:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError

PS C:\Users\TrevorSullivan> docker-machine.exe -v
docker-machine.exe version 0.8.0-rc1, build fffa6c9
```

# Expected Result

The `docker-machine active` command should properly return the active Docker Host.

Cheers,
**Trevor Sullivan**
Microsoft MVP: Cloud & Data Center Management
https://trevorsullivan.net
https://twitter.com/pcgeek86

**Comment by RealKanashii** [comment]
Which value returns `docker-machine ls` and `docker-machine url "name-of-vm"`?

**Comment by ahmetalpbalkan** [comment]
@pcgeek86 can you please run it with `docker-machine --debug`? If your azure auth has expired, that might be the cause. If you could re-auth with `docker-machine ip <name>` or something like that, it may solve your problem.

**Comment by nathanleclaire** [comment]
Please re-open if followup occurs.  Thanks

**Comment by ginjo** [comment]
I am also receiving this error when running ```docker-machine active```

    wbr$ docker-machine active
    Error getting active host: timeout

* If I run the command a few times, it will eventually return a successful response.
* I have no trouble connecting-to or running containers on my dockerized machines.
* All docker-machine commands take almost 10s to complete.
* Macbook Pro 2015, OSX 10.11, Docker 1.13
* amazonec2 driver, debian host, Docker 1.13
* Had the same issues when using Docker 1.12

Happy to provide more info if that will help.

Thanks,
William

**Comment by l15k4** [comment]
There is something non-deterministic going on regardless of cloud provider, if I do something like : 
```
eval $(docker-machine env a) && docker-machine active
eval $(docker-machine env b) && docker-machine active
eval $(docker-machine env c) && docker-machine active
eval $(docker-machine env d) && docker-machine active
eval $(docker-machine env e) && docker-machine active
eval $(docker-machine env f) && docker-machine active
```
It almost always times out on one of the machines. Some kind of racing condition possibly. These machines are fully accessible EC2 instances, I'm starting a cluster using this approach and I have like 50% chance of the whole cluster starting because of that...
