### ISSUE TITLE
Connect to existing docker host

### ISSUE THREAD

**Issue by dcohenb** [docker/machine#3527]
Hello,

I've created a docker host on gcloud using `docker-machine create`.
It works great but I can't figure out how can I access this docker machine from a different computer.

basically i'm trying to do something like `docker-machine add --existing-docker-host-params`

Can anyone give me a hint or a direction of how to do that?

**Comment by nathanleclaire** [comment]
There are several open issues around this and proposals to deal with it but there is no good first class way today.  Thanks

**Comment by jkrumow** [comment]
@nathanleclaire 

> there is no good first class way today

and the past 18 month. When will you solve this issues once and for all?

**Comment by nathanleclaire** [comment]
> and the past 15 months. When will you solve this issues once and for all?

Thanks for your input.  We're always happy to accept PRs.  It's a tricky issue that involves problems around secrets management, state management, ACLs and more.  So, if it does get resolved, it will take quite a long time.
