### ISSUE TITLE
1.12-rc2 "client is newer than server" error

### ISSUE THREAD

**Issue by pcgeek86** [docker/machine#3541]
1. I installed the 1.12.0-rc2 build of the Docker Toolbox
2. I provisioned a new Docker Host (on Microsoft Azure) using `docker-machine`
3. I attempted to run the `docker` command line against the new Docker Host
4. I received the "client is newer than server" error

Any ideas how I can work around that? My `docker -v` output is below.

```
PS C:\Users\TrevorSullivan> docker -v
Docker version 1.12.0-rc2, build 906eacd
PS C:\Users\TrevorSullivan> docker-machine -v
docker-machine.exe version 0.8.0-rc1, build fffa6c9
```

Cheers,
**Trevor Sullivan**
Microsoft MVP: Cloud & Data Center Management
https://trevorsullivan.net
https://twitter.com/pcgeek86

**Comment by yamamoto-febc** [comment]
I also had same issue.
My workaround is to use "--engine-install-url" option.

ex. 
```
docker-machine create -d azure \
                      --azure-subscription-id <subs-id>  \
                      --engine-install-url "https://experimental.docker.com" \
                      <machine-name> 
```

This will install docker v1.12.0-rc2 for target machine.

**Comment by pcgeek86** [comment]
@yamamoto-febc Thanks, I decided to remove all versions of the Docker Toolbox, and install dvm instead. Apparently I can use this to switch between multiple versions of Docker binaries.

https://github.com/getcarina/dvm

**Comment by zhanghan177** [comment]
If you do `docker version` you might be able to see which API versions are running in the client and server, then you can do `export DOCKER_API_VERSION=xxx` to swap between different API versions.

**Comment by pcgeek86** [comment]
@zhanghan177 Thanks -- that's a good solution.
