### ISSUE TITLE
Azure driver doesn't allow provisioning of SSD-backed VMs

### ISSUE THREAD

**Issue by pcgeek86** [docker/machine#3542]
I tried to provision a Microsoft Azure Docker Host using the `Standard_DS1` VM size. The provisioning process failed. I suspect that this is because an Azure Premium Storage Account is required for SSD-backed OS disks. However, this option isn't exposed in the `docker-machine` command. It would be nice if I could use `docker-machine` to provision a SSD-backed Azure Docker Host.

```
PS C:\Users\TrevorSullivan> ### Create a Docker Host with a static public IP address
>> docker-machine create `
>>     --driver azure `
>>     --azure-subscription-id 1c9fd9f5-a2dc-4cc9-a73c-cab0ee4a95a1 `
>>     --azure-static-public-ip `
>>     --azure-size standard_ds1 `
>>     artofshellstat
>>
Running pre-create checks...
(artofshellstat) Completed machine pre-create checks.
Creating machine...
(artofshellstat) Querying existing resource group.  name="docker-machine"
(artofshellstat) Resource group "docker-machine" already exists.
(artofshellstat) Configuring availability set.  name="docker-machine"
(artofshellstat) Configuring network security group.  name="artofshellstat-firewall" location="westu
s"
(artofshellstat) Querying if virtual network already exists.  name="docker-machine-vnet" location="w
estus"
(artofshellstat) Virtual network already exists.  location="westus" name="docker-machine-vnet"
(artofshellstat) Configuring subnet.  name="docker-machine" vnet="docker-machine-vnet" cidr="192.168
.0.0/16"
(artofshellstat) Creating public IP address.  name="artofshellstat-ip" static=true
(artofshellstat) Creating network interface.  name="artofshellstat-nic"
(artofshellstat) Creating virtual machine.  username="docker-user" osImage="canonical:UbuntuServer:1
5.10:latest" name="artofshellstat" location="westus" size="standard_ds1"
Error creating machine: Error in driver during machine creation: compute.VirtualMachinesClient#Creat
eOrUpdate: Failure sending request: StatusCode=409 -- Original Error: Long running operation termina
ted with status 'Failed': Code="OperationNotAllowed" Message="Unable to update the VM. The requested
 VM size 'Standard_DS1' may not be available in the resources supporting the existing allocation. Pl
ease try again later, try with a different VM size or create a VM with a new availability set or no
availability set binding."

PS C:\Users\TrevorSullivan> docker-machine -v
docker-machine.exe version 0.7.0, build a650a40
```

@ahmetalpbalkan 

Cheers,
**Trevor Sullivan**
Microsoft MVP: Cloud & Data Center Management
https://trevorsullivan.net
https://twitter.com/pcgeek86

**Comment by ahmetalpbalkan** [comment]
@pcgeek86 this is not a docker-machine issue. It appears like there is some limitation either on the Azure side (sometimes our datacenters are running low on capacity) or your subscription (maybe your subscription is not enabled to deploy SSD VMs in particular region(s)).

My suggestion is to try doing the same operation on Azure Portal and see if it goes through (most probably won't) and try using another `--azure-location`.

**Comment by pcgeek86** [comment]
@ahmetalpbalkan Thanks -- are you sure it's not a Docker Machine issue though? Since the `*s*` series VMs require a `Premium_LRS` Azure Storage Account, Docker Machine would have to explicitly create this type of Azure Storage Account. I'm not sure if it's doing this or not, according to the command's output. Did you explicitly add support for `Premium_LRS` Storage Accounts?

Cheers,
Trevor Sullivan

**Comment by ahmetalpbalkan** [comment]
@pcgeek86 You're theoretically right, it should be requiring a Premium_LRS account, however in practice it actually works with Standard_LRS account as well.

So while developing the driver I remember this was the case and we don't have an API to tell that gives you `vm size -> storage type` mapping and I did not want to hardcode something into to the driver. Once I realized the Standard_LRS works just fine with DS-series, I stopped right there and did not implement any configuration for storage type...

Here is a case where I created DS series VM with a Standard_LRS storage account just fine:

```
$ dm create -d azure --azure-size Standard_DS1 foo
Running pre-create checks...
(foo) Completed machine pre-create checks.
Creating machine...
(foo) Querying existing resource group.  name="docker-machine"
(foo) Resource group "docker-machine" already exists.
(foo) Configuring availability set.  name="docker-machine"
(foo) Configuring network security group.  name="foo-firewall" location="westus"
(foo) Querying if virtual network already exists.  location="westus" name="docker-machine-vnet"
(foo) Configuring subnet.  name="docker-machine" vnet="docker-machine-vnet" cidr="192.168.0.0/16"
(foo) Creating public IP address.  name="foo-ip" static=false
(foo) Creating network interface.  name="foo-nic"
(foo) Creating virtual machine.  name="foo" location="westus" size="Standard_DS1" username="docker-user" osImage="canonical:UbuntuServer:15.10:latest"
Waiting for machine to be running, this may take a few minutes...
Detecting operating system of created instance...
Waiting for SSH to be available...
Detecting the provisioner...
Provisioning with ubuntu(systemd)...
Installing Docker...
Copying certs to the local machine directory...
Copying certs to the remote machine...
Setting Docker configuration on the remote daemon...
Checking connection to Docker...
Docker is up and running!
To see how to connect your Docker Client to the Docker Engine running on this virtual machine, run: docker-machine env foo
```

**Comment by pcgeek86** [comment]
@ahmetalpbalkan Yes, the VMs that support SSD storage still work with Standard_LRS, but how do you create one using Premium_LRS?

**Comment by ahmetalpbalkan** [comment]
@pcgeek86 well, you can't for now. That would require exposing another configuration flag. If there is no explicit need for it (i.e. performance is the same) I don't think there is no need to introduce a yet another command line flag.

**Comment by pcgeek86** [comment]
@ahmetalpbalkan The reason I asked about it is because performance isn't the same. The disk latency on Azure's standard storage is pretty high, and even the smallest VM running off Premium_LRS SSD storage has a massive. Is there a particular reason you're resistant to adding this capability? I think it would be very useful for Azure customers at large.

**Comment by ahmetalpbalkan** [comment]
@pcgeek86 I was totally not aware of the fact that it gets slower when you use Standard_LRS with DS-series VMs. This is a mistake on my end. I'll do my research and probably introduce an `--azure-storage-type` argument.

**Comment by pcgeek86** [comment]
@ahmetalpbalkan No worries mate, thanks for checking into that. Yeah, as long as you are using the Standard Storage Account type, then you will get high-latency storage. It works okay for very basic workloads, but for interactive use, the Premium Storage Account is highly preferable. I think your customers will appreciate the ability to provision Docker Hosts using this Storage Account Type.

**Comment by ahmetalpbalkan** [comment]
@pcgeek86 I just sent the fix as a pull request. Feel free to download the patch and build if you want to try it out. I believe it'll go out as a binary with the next release.
