### ISSUE TITLE
Provisioning CoreOS on Azure results in old Docker Engine version

### ISSUE THREAD

**Issue by pcgeek86** [docker/machine#3544]
I've been trying to provision a CoreOS Docker Host on Microsoft Azure, using `docker-machine` 1.12.0-rc2 and 1.11.3. The net result is a CoreOS VM running Docker Engine 1.10.3. 

I even tried specifying `--engine-install-url https://test.docker.com`, and it still resulted in 1.10.3.

Any thoughts on how to ensure the latest Docker Engine is installed?

Cheers,
**Trevor Sullivan**
Microsoft MVP: Cloud & Data Center Management
https://trevorsullivan.net
https://twitter.com/pcgeek86

**Comment by ahmetalpbalkan** [comment]
@pcgeek86 You don't install Docker Engine on CoreOS. CoreOS comes with a read-only filesystem where Docker is already installed. Check out https://coreos.com/releases/ to learn more. This is not limited to Azure.

**Comment by pcgeek86** [comment]
@ahmetalpbalkan Thanks -- good info, I'll read up on it.
