### ISSUE TITLE
Please update documentation on --digitalocean-ssh-user parameter

### ISSUE THREAD

**Issue by achekulaev** [docker/machine#3562]
`docker-machine version 0.7.0, build a650a40`
Creating works perfectly without this parameter but whenever I add `--digitalocean-ssh-user` docker-machine will never be able to connect to ssh. 
It just hangs and waits until timeout happens.

```
$ docker-machine create --driver=digitalocean --digitalocean-access-token=<token> --digitalocean-ssh-user=drude --digitalocean-size=1gb do-test
Running pre-create checks...
Creating machine...
(do-test) Creating SSH key...
(do-test) Creating Digital Ocean droplet...
(do-test) Waiting for IP address to be assigned to the Droplet...
Waiting for machine to be running, this may take a few minutes...
Detecting operating system of created instance...
Waiting for SSH to be available...
Error creating machine: Error detecting OS: Too many retries waiting for SSH to be available.  Last error: Maximum number of retries (60) exceeded
```
`docker-machine ssh` afterwards returns 255 code all the time.

```
$ docker-machine ssh do-test
exit status 255
```

Machine `do-test` is there created and running. I see it in droplets. Deleting in with `docker-machine rm` works fine. 
I suppose something went wrong with setting up that user.

**Comment by bamarni** [comment]
This flag is only useful when creating a machine from your own snaphsot or with distros like coreos. Here it's using the default image (ubuntu), where only the root user is available.

**Comment by achekulaev** [comment]
@bamarni oh. I see. Then this ticket should probably be re-designed as a request for documentation update as it's not obvious 
https://docs.docker.com/machine/drivers/digital-ocean/

**Comment by bamarni** [comment]
If you think it's not clear enough why not. Btw if you want to create and connect with this new user automatically you could set the user data flag with a cloud-config. There are tutorials for this on digitalocean.

**Comment by achekulaev** [comment]
@bamarni oh I see. Thanks for that one I will definitely use it. I guess noting that user should already exist in docs would be enough. Because when I met this option I expected that docker-machine will actually create that user for me.

**Comment by nathanleclaire** [comment]
I agree our documentation could be better, please feel free to submit a PR.  Thanks
