### ISSUE TITLE
[Azure] Error when processing DeviceAuthRedirect request

### ISSUE THREAD

**Issue by wangchunyang** [docker/machine#3580]
I'm using docker-machine to provision a VM on Azure. Once I enter the code to authenticate with browser, I got the following error:

> Sorry, but we’re having trouble signing you in.
> We received a bad request.
> 
> Additional technical information:
> Correlation ID: 92f31ce7-412f-48a8-8d62-bc0a413cb1da
> Timestamp: 2016-07-13 08:20:01Z
> AADSTS90011: Error when processing DeviceAuthRedirect request.

Is there any specific requirements on my Azure account? I can create VM on Azure Portal manually.

**Comment by ahmetalpbalkan** [comment]
@wangchunyang can you please try again in an incognito browser window? ActiveDirectory web interface often has issues like this.

**Comment by nathanleclaire** [comment]
Please re-open if desiring to follow up @wangchunyang
