### ISSUE TITLE
Support provisioner for Google's container-vm

### ISSUE THREAD

**Issue by bradrydzewski** [docker/machine#3585]
I'm interested in adding support for Google's container vm
https://cloud.google.com/compute/docs/containers/vm-image/

I wanted to see if there was any interest in supporting this image type before I put any time into working on a pull request.

> Google Container-VM Image is a container-optimized OS image for the Google Cloud Platform (GCP). We built Container-VM Image primarily for running Google services on GCP. Unlike the open preview version of container-vm, Container-VM Image is based on the open source Chromium OS project, allowing us greater control over the build management, security compliance, and customizations for GCP.

> Container-VM Image is not a general purpose operating system for use outside of GCP.

I haven't dug too much into the docker machine code yet but it appears its a matter of creating a provisioner that recognizes the distribution id `gci` in the `/etc/os-release` file. Docker is already installed so I presume it would need to update the `DOCKER_OPTS` with standard machine configuration values and then restart the Docker daemon. Hopefully pretty simple.

**Comment by nathanleclaire** [comment]
Hey Brad! 

We are mostly interested in general purpose OSes but thanks for the suggestion.

- N

**Comment by Adezandee** [comment]
@bradrydzewski, I'm interested too in a provisioner for `gci`. I have done an simple implementation you can see here https://github.com/Adezandee/machine/blob/driver/gci/libmachine/provision/gci.go
