### ISSUE TITLE
Internal network using VirtualBox driver

### ISSUE THREAD

**Issue by arun-gupta** [docker/machine#3590]
There seems to be no obvious way for Docker Machine created using VirtualBox to be configured with internal networking. This would be required for `docker swarm init --listen-addr <ip>` for swarm mode in 1.12 RC4. `<ip>` would be the private IP of the manager.

**Comment by raykrueger** [comment]
I do the following... https://github.com/raykrueger/docker-swarm-mode-scripts

But yeah, not vpc

**Comment by arun-gupta** [comment]
@raykrueger I've been tinkering with a similar script: https://github.com/arun-gupta/docker-scripts/blob/master/swarm-mode-machine.sh

But I think these options would be useful for a seamless experience.

**Comment by nathanleclaire** [comment]
I don't understand -- the VirtualBox host only network that machines are on by default have ip addresses.  Check `eth1` on these VMs for their internal network IP.

```
$ docker-machine ssh default ifconfig
...
eth1      Link encap:Ethernet  HWaddr 08:00:27:D5:AD:17
          inet addr:192.168.99.100  Bcast:192.168.99.255  Mask:255.255.255.0
          inet6 addr: fe80::a00:27ff:fed5:ad17/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:1670 errors:0 dropped:0 overruns:0 frame:0
          TX packets:594 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:237825 (232.2 KiB)  TX bytes:116930 (114.1 KiB)
...
```
