### ISSUE TITLE
inventory script

### ISSUE THREAD

**Issue by sachinvgaikwad** [docker/machine#3601]
Hi
I am new to aws i need help do we have a bash script to get all the information like
1.       all VMs and their properties
2.       all storage and snapshots
3.       all network interfaces and IP addresses – which VM has been given which ones etc
4.       all VPC (AWS) or network security group  configurations
5.       all load balancers
or commands by which i would get the infomations

**Comment by nathanleclaire** [comment]
No, sorry, if you want such a script you must put it together on your own
