### ISSUE TITLE
Bug authenticating using Azure driver

### ISSUE THREAD

**Issue by pcgeek86** [docker/machine#3604]
Here's the workflow I'm following:

1. Provision a Docker Host from Windows 10 using `docker-machine`
2. Share authentication keys with Mac, Linux, and other Windows clients, by copying `$env:UserProfile\.docker\machine\machines\<DockerHost>`
3. Running `docker-machine env >DockerHost>` results in a prompt to authenticate via web browser
4. The following error message appears

We're trying to share a stand-alone Docker Host in a team environment. What's the best way to handle this?

![image](https://cloud.githubusercontent.com/assets/466713/17037153/bb28b92a-4f4c-11e6-97f8-d9db934d27cf.png)

Cheers,
**Trevor Sullivan**
Microsoft MVP: Cloud & Data Center Management
https://trevorsullivan.net
https://twitter.com/pcgeek86

**Comment by ahmetalpbalkan** [comment]
@pcgeek86 seems like a dupe of #3580. AAD team is working on a fix for this bug for a while now. In the meanwhile, can you please try using an incognito browser window (or clearing your microsoft.com, live.com, windows.net etc. cookies)? That should be fixing your problem.

**Comment by ahmetalpbalkan** [comment]
@pcgeek86 are you still running this issue? If you ever get this `AADSTS90011` error again, feel free to contact me here or via email directly. I'd love to get a correlation ID to investigate further but AAD has recently deployed a fix that should be solving this problem.

If your problem went away, please consider closing the issue.

**Comment by pcgeek86** [comment]
@ahmetalpbalkan Haven't had time to set up this scenario again. Closing for now, as it's a known issue.

**Comment by ahmetalpbalkan** [comment]
@pcgeek86 in the meanwhile you can try the patch at #3665 that lets you use Service Principal Accounts with Docker Machine.
