### ISSUE TITLE
Why does upgrade default to unstable version?

### ISSUE THREAD

**Issue by ain** [docker/machine#3621]
Could someone please explain, why is `docker-machine upgrade <machine>` upgrading to a non-stable version, e.g. currently, `v1.12.0-rc5`? It completely broke a stable system, Compose is no more showing output when building images and so on.

It is indeed a rather untraditional way of doing things, esp. considering the experience with the past 10 versions of Docker and their stability in general.

__UPDATE__: Docker Machine version was corrupt due to Docker for Mac installation, despite that it was shut down at the time. Shouldn't there be an alert that warns against such possibility when Docker for Mac is installed?

**Comment by nathanleclaire** [comment]
It does not.  It only upgrades to RCs if the Docker Machine version is also an RC
