### ISSUE TITLE
Documentation issue: AWS Security Group

### ISSUE THREAD

**Issue by royyeah** [docker/machine#3635]
I was following the tutorial on provisioning AWS EC2 on https://docs.docker.com/machine/examples/aws/. 

Everything worked, but I couldn't see anything when navigating to `http://<host_ip>:8000`, the browser just loaded endlessly. 

It took me a while to find out I had to open port 8000 first. I was new to AWS and had no idea about security groups. I think this is good to add in the tutorial.

Cheers

**Comment by nathanleclaire** [comment]
Generally pretty common knowledge I'd hope to users of AWS, but I'd be happy to merge a PR in docs explaining this.  Thanks
