### ISSUE TITLE
Provisioning RHEL 7 AWS via docker-machine - exit 6

### ISSUE THREAD

**Issue by richardkeit** [docker/machine#3636]
docker-machine -D create --driver amazonec2 --amazonec2-access-key <access-key> --amazonec2-secret-key <secret-key> --amazonec2-ami ami-e0c19f83 --amazonec2-ssh-user ec2-user --amazonec2-region ap-southeast-2 --amazonec2-vpc-id vpc-49fadd2c ec2rhel

**Version of software**
docker-machine version 0.7.0, build a650a40
Docker version 1.12.0, build 8eab29e

**Docker-machine ls**
NAME                  ACTIVE   DRIVER      STATE      URL                      SWARM   DOCKER    ERRORS
ec2rhel               -        amazonec2   Running    tcp://52.64.51.68:2376           Unknown   Unable to query docker version: Cannot connect to the docker engine endpoint

Noting that SSH to the box from main host works fine:
[root@ip-172-31-25-229 ~]# docker-machine ssh ec2rhel
Last login: Wed Aug  3 05:07:41 2016 from 52.65.115.139
[ec2-user@ec2rhel ~]$

**Output of docker-machine create on debug**

Using SSH private key: /root/.docker/machine/machines/ec2rhel/id_rsa (-rw-------)
&{[-F /dev/null -o BatchMode=yes -o PasswordAuthentication=no -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=quiet -o ConnectionAttempts=3 -o ConnectTimeout=10 -o ControlMaster=no -o ControlPath=none ec2-user@52.64.51.68 -o IdentitiesOnly=yes -i /root/.docker/machine/machines/ec2rhel/id_rsa -p 22] /bin/ssh <nil>}
Error creating machine: Error running provisioning: exit status 6
open : no such file or directory
notifying bugsnag: [Error creating machine: Error running provisioning: exit status 6]

**Comment by richardkeit** [comment]
When starting service using the config stored in the below file - docker-machine is able to connect to the host successfully:

`/usr/bin/docker daemon -H tcp://0.0.0.0:2376 -H unix:///var/run/docker.sock --storage-driver devicemapper --tlsverify --tlscacert /etc/docker/ca.pem --tlscert /etc/docker/server.pem --tlskey /etc/docker/server-key.pem --label provider=amazonec2`

[root@specialsshuserrhel2 ~]# cat /etc/systemd/system/docker.service
[Unit]
Description=Docker Application Container Engine
After=network.target docker.socket
Requires=docker.socket

[Service]
ExecStart=/usr/bin/docker daemon -H tcp://0.0.0.0:2376 -H unix:///var/run/docker.sock --storage-driver devicemapper --tlsverify --tlscacert /etc/docker/ca.pem --tlscert /etc/docker/server.pem --tlskey /etc/docker/server-key.pem --label provider=amazonec2
MountFlags=slave
LimitNOFILE=1048576
LimitNPROC=1048576
LimitCORE=infinity
Environment=

**Comment by richardkeit** [comment]
Removing the docker,socket from /etc/systemd/system/docker.service, so the file looks like

> [Unit]
> Description=Docker Application Container Engine
> After=network.target docker.socket
> Requires=docker.socket
> 
> [Service]
> ExecStart=/usr/bin/docker daemon -H tcp://0.0.0.0:2376 -H unix:///var/run/docker.sock --storage-driver devicemapper --tlsverify --tlscacert /etc/docker/ca.pem --tlscert /etc/docker/server.pem --tlskey /etc/docker/server-key.pem --label provider=amazonec2
> MountFlags=slave
> LimitNOFILE=1048576
> LimitNPROC=1048576
> LimitCORE=infinity
> Environment=

After reloading the daemon using `systemctl daemon-reload` and starting using what docker-machine had attempted to `systemctl -f start docker` - the service starts fine.

Looking at [https://github.com/docker/docker/pull/25094/files] the required change has been made. 
When will this be available for at the docker-machine default install URL? 

> "InstallURL": "https://get.docker.com"


@ahmetalpbalkan - I've seen you're quite active here and hoping you were able to provide some insight? Would be appreciated

**Comment by richardkeit** [comment]
Confirmed fixed with latest commit from master [https://github.com/docker/machine/commit/641c6930936fe4094c2a244bdcef95306e6b9cac](docker-machine latest commit in master)

Steps to reproduce fix: 
`git clone https://github.com/docker/machine; cd machine; USE_CONTAINER=true make build-x`

Use binary from within "bin" specific to your version, in my example RHEL 7 within AWS:

**Store environment variables**
```
export AWS_ACCESS_KEY_ID=<individual case specific>
export AWS_SECRET_ACCESS_KEY=<individual case specific>
export AWS_AMI=ami-e0c19f83
export AWS_SSH_USER=ec2-user
export AWS_DEFAULT_REGION=<individual case specific>
export AWS_VPC_ID=<individual case specific>

```
**Create EC2 instance on RHEL 7 image (using environment variables)**
`docker-machine-Linux-x86_64 create --driver amazonec2 <node_name>`

Thanks to @nathanleclaire & @jverhoeven for their assistance

**Comment by nathanleclaire** [comment]
👍
