### ISSUE TITLE
Work on a new driver for Scaleway platform

### ISSUE THREAD

**Issue by matm** [docker/machine#3638]
Would a contribution for a new machine driver for [Scaleway](https://www.scaleway.com) be interesting?

Is someone else already working on that feature?

**Comment by StefanScherer** [comment]
@matm There is a docker-machine plugin for
Scaleway https://github.com/scaleway/docker-machine-driver-scaleway
I don't know the current status of that plugin.

**Comment by matm** [comment]
Indeed. Thank you @StefanScherer. Just asked them if they plan to merge this driver upstream.

**Comment by matm** [comment]
@StefanScherer Just wondering: is there a policy preventing the inclusion of this driver's code into Docker Machine's official repository?

**Comment by StefanScherer** [comment]
@matm Maintaining all the drivers makes it difficult for upstream maintainers in docker/machine repo. Accepting new drivers slowed downin the past  and so the driver plugin mechanism was born. That decouples maintaining drivers from the core.

**Comment by StefanScherer** [comment]
For reference https://github.com/docker/machine/pull/1389#issuecomment-126818120

**Comment by matm** [comment]
Yes, I perfectly get it. So current drivers (aws, softlayer etc.) are planned to move out of the core, right? This comment is one year old now. Is it supposed to happen soon?

Anyway, thanks for your time.
