### ISSUE TITLE
Cannot create symlink inside container in a mounted volume - docker for windows

### ISSUE THREAD

**Issue by BarnumD** [docker/machine#3643]
I can't create a symlink on a mounted volume on windows.  How do I fix this?
I'm using docker for windows 1.12.0 5968

Reproduce:
`docker run -v C:\temp\test:/test --name test phusion/baseimage`
`docker exec -it test bash`
`cd /test`
`mkdir 1`
`ln -s 1 2`
`ln: failed to create symbolic link '2': Operation not supported`

**Comment by BarnumD** [comment]
I previously encountered something like this using vagrant.  I was able to fix that by granting the user i'm logged in as the `create symbolic links` right in local group policies.  That doesn't seem to be working here.

**Comment by TheDigitalNinja** [comment]
I believe this is fixed in the latest beta version of Docker for windows.

**Comment by BarnumD** [comment]
Confirmed in 1.12.1-beta24 build 6563.
