### ISSUE TITLE
docker-machine fails to check the host with openstack driver

### ISSUE THREAD

**Issue by zeddicus76** [docker/machine#3644]
I have been trying to get the gitlab-co-multi-runner working with autoscaling. I am using an OpenStack cloud for the VMs.  I have tried running docker-machine from a host outside of the OpenStack cloud as well as from inside the cloud.
Hosts are running OL7 with 4.1.12-37.6.1.el7uek.x86_64

I would really like to get the autoscaling feature to work but I can't get docker-machine to successfully start docker hosts in my cloud. It is failing trying to validate the certificates. I tried to check them by hand, even on the docker host itself, but no luck.

Any help appreciated.

Checking connection to Docker...
(test-runner) Calling .GetURL
(test-runner) DBG | Get status for OpenStack instance... map[MachineId:e8ebdd43-e113-44ef-93cf-ee8acb94c113]
Reading CA certificate from /root/.docker/machine/certs/ca.pem
Reading client certificate from /root/.docker/machine/certs/cert.pem
(test-runner) DBG | State for OpenStack instance map[MachineId:e8ebdd43-e113-44ef-93cf-ee8acb94c113 State:ACTIVE]
Reading client key from /root/.docker/machine/certs/key.pem
Error creating machine: Error checking the host: Error checking and/or regenerating the certs: There was an error validating certificates for host "172.42.0.66:2376": dial tcp 172.42.0.66:2376: getsockopt: no route to host
You can attempt to regenerate them using 'docker-machine regenerate-certs [name]'.
Be advised that this will trigger a Docker daemon restart which will stop running containers.

notifying bugsnag: [Error creating machine: Error checking the host: Error checking and/or regenerating the certs: There was an error validating certificates for host "172.42.0.66:2376": dial tcp 172.42.0.66:2376: getsockopt: no route to host
You can attempt to regenerate them using 'docker-machine regenerate-certs [name]'.
Be advised that this will trigger a Docker daemon restart which will stop running containers.

From a host not he same network
\# docker --debug -H tcp://172.42.0.66:2376 --tlsverify info
DEBU[0000] Trusting 1 certs

From the host itself.
\# docker -H tcp://172.42.0.66:2376 --debug --tlsverify --tlscacert /etc/docker/ca.pem --tlscert /etc/docker/server.pem --tlskey /etc/docker/server-key.pem info
DEBU[0000] Trusting 1 certs

\# docker --version
Docker version 1.12.0, build 8eab29e

\# docker-machine --version
docker-machine version 0.7.0, build f1789ea

\# docker-machine ls
NAME          ACTIVE   DRIVER      STATE     URL                      SWARM   DOCKER    ERRORS
test-runner   -        openstack   Running   tcp://172.42.0.66:2376           Unknown   Unable to query docker version: Get https://172.42.0.66:2376/v1.15/version: dial tcp 172.42.0.66:2376: getsockopt: no route to host

**Comment by zeddicus76** [comment]
It appears docker is not even listening on IPV4 :2376

# netstat -tln
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State
tcp        0      0 0.0.0.0:111             0.0.0.0:*               LISTEN
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN
tcp        0      0 127.0.0.1:25            0.0.0.0:*               LISTEN
tcp6       0      0 :::111                  :::*                    LISTEN
tcp6       0      0 :::22                   :::*                    LISTEN
tcp6       0      0 ::1:25                  :::*                    LISTEN
tcp6       0      0 :::2376                 :::*                    LISTEN

**Comment by nathanleclaire** [comment]
@fsoppelsa

**Comment by zeddicus76** [comment]
It turns out I had an iptables rule on the host VM causing me all the troubles. 

Thank you

**Comment by anglvictor** [comment]
Hi @zeddicus76 , how do you fix this issue?

**Comment by bruno-lopes** [comment]
I have the same problem. Any solution?
