### ISSUE TITLE
Unable to contact boot2docker node after successful deployment in vsphere

### ISSUE THREAD

**Issue by kylegordon** [docker/machine#3646]
Hey,

I was following the suggestion at https://gist.github.com/philipz/6afdb693479f10f91da3 to deploy Docker Machine to our vSphere cluster, and have hit a bit of a stumbling block with the configuration. It would appear that docker-machine doesn't use the correct IP address to communicate with the node.

> └─(11:28:42)──> docker-machine create docker-consul --driver vmwarevsphere --vmwarevsphere-datacenter Datacenter --vmwarevsphere-vcenter vcs0.linn.co.uk --vmwarevsphere-username XXXX --vmwarevsphere-password XXXX --vmwarevsphere-datastore Datastore01 --vmwarevsphere-network "VM Network" --vmwarevsphere-hostsystem 'Production/v4.linn.co.uk'
Creating CA: /home/kyleg/.docker/machine/certs/ca.pem
Creating client certificate: /home/kyleg/.docker/machine/certs/cert.pem
Running pre-create checks...
Creating machine...
(docker-consul) Image cache directory does not exist, creating it at /home/kyleg/.docker/machine/cache...
(docker-consul) No default Boot2Docker ISO found locally, downloading the latest release...
(docker-consul) Latest release for github.com/boot2docker/boot2docker is v1.12.0
(docker-consul) Downloading /home/kyleg/.docker/machine/cache/boot2docker.iso from https://github.com/boot2docker/boot2docker/releases/download/v1.12.0/boot2docker.iso...
(docker-consul) 0%....10%....20%....30%....40%....50%....60%....70%....80%....90%....100%
(docker-consul) Copying /home/kyleg/.docker/machine/cache/boot2docker.iso to /home/kyleg/.docker/machine/machines/docker-consul/boot2docker.iso...
(docker-consul) Generating SSH Keypair...
(docker-consul) Creating VM...
(docker-consul) Uploading Boot2docker ISO ...
(docker-consul) Reconfiguring VM...
(docker-consul) Waiting for VMware Tools to come online...
(docker-consul) Provisioning certs and ssh keys...
Waiting for machine to be running, this may take a few minutes...
Detecting operating system of created instance...
Waiting for SSH to be available...
Detecting the provisioner...
Provisioning with boot2docker...
Copying certs to the local machine directory...
Copying certs to the remote machine...
Setting Docker configuration on the remote daemon...
Checking connection to Docker...
Docker is up and running!
To see how to connect your Docker Client to the Docker Engine running on this virtual machine, run: docker-machine env docker-consul
└─(11:30:49)──> docker-machine inspect docker-consul | grep -C2 IPAddress 
    "ConfigVersion": 3,
    "Driver": {
        "IPAddress": "10.2.10.97",
        "MachineName": "docker-consul",
        "SSHUser": "docker",
└─(11:57:20)──> docker-machine config docker-consul
Error running connection boilerplate: Error checking and/or regenerating the certs: There was an error validating certificates for host "172.17.0.1:2376": dial tcp 172.17.0.1:2376: i/o timeout
You can attempt to regenerate them using 'docker-machine regenerate-certs [name]'.
Be advised that this will trigger a Docker daemon restart which will stop running containers.
└─(12:02:08)──> docker-machine env docker-consul
Error checking TLS connection: Error checking and/or regenerating the certs: There was an error validating certificates for host "172.17.0.1:2376": dial tcp 172.17.0.1:2376: i/o timeout
You can attempt to regenerate them using 'docker-machine regenerate-certs [name]'.
Be advised that this will trigger a Docker daemon restart which will stop running containers.

Understandably I have networking between my host and the node on 10.2.10.97, but all attempts by docker-machine seem to use the non-routed address that's assigned to the bridge on the node. 

Is docker-machine calling on vsphere and asking for an IP address that's unroutable? Am I supposed to arrange for routing? Why are docker-machine config and inspect using different addresses?

For reference, docker-machine version 0.7.0, build a650a40

**Comment by smitp33** [comment]
I too have encountered the same issue as documented above using docker-machine version 0.7.0, build a650a40.

For some more details here it appears that I can get docker-machine to see the correct URL by restarting using docker-machine, but then this breaks the working node as demonstrated here -->

<< Neither machine is contactable as trying to use the docker0 address from each host >>
[root@home SWARM-MASTER]# docker-machine ls
NAME           ACTIVE   DRIVER          STATE     URL                     SWARM   DOCKER    ERRORS
SWARM-AGENT1   -        vmwarevsphere   Running   tcp://172.17.0.1:2376           Unknown   Unable to query                                                              docker version: Cannot connect to the docker engine endpoint
SWARM-MASTER   -        vmwarevsphere   Running   tcp://172.17.0.1:2376           Unknown   Unable to query                                                              docker version: Cannot connect to the docker engine endpoint

<< Restart SWARM-AGENT1 and then it is resolvable, but SWARM-MASTER still not resolvable >>
[root@home SWARM-MASTER]# docker-machine restart SWARM-AGENT1
Restarting "SWARM-AGENT1"...
(SWARM-AGENT1) Waiting for VMware Tools to come online...
Waiting for SSH to be available...
Detecting the provisioner...
Restarted machines may have new IP addresses. You may need to re-run the `docker-machine env` command.
[root@home SWARM-MASTER]# docker-machine ls
NAME           ACTIVE   DRIVER          STATE     URL                        SWARM   DOCKER    ERRORS
SWARM-AGENT1   -        vmwarevsphere   Running   tcp://192.168.1.132:2376           v1.12.0
SWARM-MASTER   -        vmwarevsphere   Running   tcp://172.17.0.1:2376              Unknown   Unable to qu                                                             ery docker version: Cannot connect to the docker engine endpoint

<< Restart SWARM-MASTER and then it is resolvable, but SWARM-AGENT1 now broken again >> 
[root@home SWARM-MASTER]# docker-machine restart SWARM-MASTER
Restarting "SWARM-MASTER"...
(SWARM-MASTER) Waiting for VMware Tools to come online...
Waiting for SSH to be available...
Detecting the provisioner...
Restarted machines may have new IP addresses. You may need to re-run the `docker-machine env` command.
[root@home SWARM-MASTER]# docker-machine ls
NAME           ACTIVE   DRIVER          STATE     URL                        SWARM   DOCKER    ERRORS
SWARM-AGENT1   -        vmwarevsphere   Running   tcp://172.17.0.1:2376              Unknown   Unable to qu                                                             ery docker version: Cannot connect to the docker engine endpoint
SWARM-MASTER   -        vmwarevsphere   Running   tcp://192.168.1.130:2376           v1.12.0

If I then leave it for a few minutes then both revert to trying to be contacted on the 172 address and so become un-resolvable again.

Not sure why its pulling the 172 address as the only address in the machine config is the 192 address - it looks like it is connecting to the node and then the node is returning the 172 address which is then being used by docker-machine. I am tempted to disable the docker0 interface on the image in the bootlocal.sh script but I suspect that will break something else down the line.

**Comment by smitp33** [comment]
I have just tried with docker 0.6 and same issue, but I then also tried with `0.8.0, build b85aac1` and problem does not appear on this version so am going to stick with 0.8 and see how it goes.

**Comment by kylegordon** [comment]
Thanks @smitp33 
I can confirm that updating to docker-machine 0.8.0 seems to fix this issue. Suspect it's the "Fix port binding of Swarm master" portion of the changelog
