### ISSUE TITLE
[Q] Is there a way to use an existing Linux VM?

### ISSUE THREAD

**Issue by steshaw** [docker/machine#3657]
Since I have a pretty old machine on which to run my VMs, I'd like to install "something" onto my existing Linux VM (which I've given 4GB RAM), rather than create a fresh VM with docker-machine. Is this possible?

I'm running Ubuntu 16.04.1 LTS.

**Comment by michelvocks** [comment]
Have a look at the generic driver: https://docs.docker.com/machine/drivers/generic/

**Comment by steshaw** [comment]
Thanks, that worked!
