### ISSUE TITLE
zsh fails but bash works?!

### ISSUE THREAD

**Issue by brtn** [docker/machine#3658]
I am following the tutorial from the digitalocean documents here [1]. The following command works on bash but fails in zsh:

`docker-machine create --driver digitalocean --digitalocean-access-token $DOTOKEN machine-name`

with an error:

`Error: No machine name specified`

I could not get it to work no matter what I tried. Any ideas?

[1] https://www.digitalocean.com/community/tutorials/how-to-provision-and-manage-remote-docker-hosts-with-docker-machine-on-ubuntu-16-04

**Comment by bamarni** [comment]
It seems because `$DOTOKEN` is not defined in your zsh session.

**Comment by brtn** [comment]
And of course you are right, silly me! I am sure to check it with echo from zsh but, I think, I did it on one window and tried to run the command on another :/
Thanks :)
