### ISSUE TITLE
Creating machine fails with bad certificate

### ISSUE THREAD

**Issue by zbyte64** [docker/machine#3660]
When creating a machine on AWS the command fails with `Error creating machine: Error checking the host: Error checking and/or regenerating the certs: There was an error validating certificates for host "54.173.35.170:2376": remote error: bad certificate`. Attached is the debug output of creating a machine.

[docker-machine-create-failure.txt](https://github.com/docker/machine/files/416739/docker-machine-create-failure.txt)

Invoking regenerate-certs ends with the same failure. Running `docker-machine ls` also reports a bad certificate under status.

**Comment by zbyte64** [comment]
Ran this command with v0.8.0-rc1 and it worked, rc2 and the final release both exhibit this failure.

**Comment by nathanleclaire** [comment]
Hey @zbyte64, you have your private keys in there, so I hope this machine is not around any longer (although with this certificate issue it might be OK...).

If you try with a fresh 'store' (i.e. remove `$HOME/.docker/machine` if possible -- be advised this will remove information about existing machines as well) does it work OK?

**Comment by zbyte64** [comment]
That seems to have been the issue, thx.

**Comment by nathanleclaire** [comment]
👍
