### ISSUE TITLE
docker-machine scp passes "-o IdentitiesOnly=yes" with no ssh keys specified

### ISSUE THREAD

**Issue by jylin** [docker/machine#3663]
This causes the scp to always fail since there are no SSH keys specified in the command either.

**Comment by bamarni** [comment]
How did you create the machine? Debug output would also be useful (`docker-machine -debug scp ...`).

**Comment by jylin** [comment]
I created the machine using the "--generic" flags. There are no SSH keys on the machine I initiated this from (just uses SSH agent forwarding). I saw that "-o" flag from the debug output. It's a bit hard for me to reproduce at this point, but I think just having a config where the SSH keys fields aren't set should repro it.

**Comment by bamarni** [comment]
I don't think it's related to the scp command, is `docker-machine ssh yourmachine` also failing?

It looks more like an error which occurred during machine creation. Notably, docker-machine doesn't rely on ssh-agent, so using ssh agent forwarding wouldn't work, it needs to have the private key on the machine itself.

**Comment by jylin** [comment]
No 'docker-machine ssh' works fine. Docker machine doesn't need to care at all about whether there's an ssh agent running or not. If no proviate key was specified, it should not pass "-o IdentitesOnly=yes" for any command.

**Comment by bamarni** [comment]
My bad, your use-case is indeed supported in the ssh command. There could be a similar check than [here](https://github.com/docker/machine/blob/master/libmachine/ssh/client.go#L316-L320) for the scp command. 👍

**Comment by bamarni** [comment]
@jylin I've submitted a patch in #3681, should fix this issue!
