### ISSUE TITLE
swarm mode confusion

### ISSUE THREAD

**Issue by jamshid** [docker/machine#3673]
I'm so confused about how to set up a swarm cluster now. These are the old instructions, right?
https://docs.docker.com/swarm/provision-with-machine/
And this is the new way? Just `docker swarm init` and do *not* use `docker-machine env --swarm`? 
https://docs.docker.com/engine/swarm/swarm-tutorial/create-swarm/

If this stuff is changing so fast that docs can't keep up, it's changing too fast. 

Sorry to vent, but as a longtime user it's frustrating to see everything I learned (was not easy!) is now useless. E.g., I (and I imagine other users) used to do this to run on a specific node. What's the new way? Hopefully this doesn't require switching to an experimental branch.
docker run -i -e "constraint:node==$c" hello-world
It's frustrating that even after a total rewrite, swarm docs are still difficult, incomplete, and contradictory.

**Comment by nathanleclaire** [comment]
Hey @jamshid.  Thanks for the report and really sorry that you ran into this.  It sounds like there's some confusion between the legacy "Docker Swarm" (which you reference with `env --swarm`) and new (introduced with and bundled directly into Docker Engine 1.12.0) "swarm mode" functionality.

The `swarm init` stuff is new to Docker Swarm 1.12.0.  Legacy swarm (which was a separate, reverse-proxy type workflow not included in Docker Engine itself) should still work as well as the new stuff. If you create a few VMs with >=1.12.0, you can call `docker swarm init` on one and use the instructions to `docker swarm join` the others to it over the VM's IPs.  Then, as opposed to the workflow of treating a Swarm endpoint like a giant virtual Docker host, you mostly use the `docker service` (and optionally `docker deploy`, if using an experimental client) command to orchestrate Docker from the master node (where you called `swarm init`).  No special settings are needed of Machine for this to work -- regular old `env` (without `--swarm`) should allow you to connect and run `docker swarm` / `docker service` commands just fine.

`docker service` has a `--constraint` flag so you'd do something like:

```console
$ docker service create --constraint 'node.hostname == foohost' nginx
```

Sorry for the confusion and thanks for your continued support.
