### ISSUE TITLE
swarm mode workflow

### ISSUE THREAD

**Issue by bgokden** [docker/machine#3699]
Currently I am using old way of creating the swarm like (eg.: https://docs.docker.com/swarm/provision-with-machine/ )

It is easy to use but I want new engine swarm mode features like raft leader quorum.

Is there a plan to use new engine swarm mode?

**Comment by andrestc** [comment]
I´m currently provisioning a swarm cluster with docker machine by simply provisioning regular docker 1.12 hosts and then issuing the commands to setup the cluster (`docker swarm init` against the manager and `docker swarm join` agaisnt the rest of the machines).

**Comment by nathanleclaire** [comment]
It's fairly straightforward to use via vbox host only network like @andrestc suggests although some documentation would be nice.

**Comment by bgokden** [comment]
Ok thank you.
