### ISSUE TITLE
cannot access created host

### ISSUE THREAD

**Issue by leon** [docker/machine#371]
The IP I got assigned was `192.168.99.100`
I think the problem is that we use the `10.0.0.0` series for our local network and that my computer doesn't know how to find the 192.168 network.

The code that's the problem is here https://github.com/docker/machine/blob/master/drivers/virtualbox/virtualbox.go#L234-L239

Is there a workaround?

**Comment by sthulb** [comment]
The code you highlighted is meant to be for creating an internal network on your computer. it's not meant for external access.

**Comment by leon** [comment]
@sthulb if i run `machine url` I get `tcp://192.168.99.100:2376`

I've created a simple wordpress docker image in the machine which if I login to machine with `machine ssh dev` and run `docker ps´ it shows that the wordpress is up and running and exposing port 80

shouldn't I be able to reach wordpress via http://192.168.99.100 ?

**Comment by sthulb** [comment]
`machine ssh` will use the 192.168.99.100 IP address. Can you present a docker ps -a?

**Comment by leon** [comment]
```
CONTAINER ID        IMAGE                                         COMMAND                CREATED             STATUS              PORTS               NAMES
14b7c9c409c5        oskarhane/docker-wordpress-nginx-ssh:latest   "/bin/bash /start.sh   41 minutes ago      Up 41 minutes       80/tcp, 22/tcp      website             
6fcf6509d237        mysql:5.6                                     "/entrypoint.sh mysq   50 minutes ago      Up 50 minutes       3306/tcp            mysql      
```

**Comment by leon** [comment]
@sthulb Could it be that the virtualbox interface should be located on the same network as my computer?

Or does my computer automatically have access to all the interfaces of virtualbox even If the main ip of the computer isn't on the same network?

**Comment by md5** [comment]
@leon that `PORTS` list looks like you didn't publish port 80. You need to add `-p 80:80` to your `docker run` or `docker create` command.

**Comment by leon** [comment]
@md5 Ahh that may be the problem...

I thought that if the original docker container had EXPOSE those would be available by default, but that was a faulty assumption.

https://docs.docker.com/reference/builder/#expose

**Comment by sthulb** [comment]
@leon For reference: Virtualbox creates a virtual network adapter on your computer in the 192.168.99.0/24 range. This is only visible to your computer. :)

**Comment by leon** [comment]
@sthulb Thanks for the help!
Sometimes it's a SBK problem (Shit Behind Keyboard) :)

**Comment by sthulb** [comment]
@leon It's fine, you should see the mistakes I make at times :)
