### ISSUE TITLE
Missing ipv4 address of new machine 

### ISSUE THREAD

**Issue by treiboll** [docker/machine#3718]
### Expected behavior

I expect after creating a new machine, that there schould be an ipv4 address available for the eth0 device of that machine of the subnet 10.0.75.0 as it es defined in the docker settings. 
### Actual behavior

After creating new machines there are only ipv6 addresses and e.g. the joining to a swarm fails with errors. See below.
### Information
- Diagnostic ID : 63A029AD-B8F2-434A-B976-407D5DC5A1AB/2016-09-02_08-48-23
- Docker v1.12.0 and docker-machine 0.8.0 on Windows 10 Pro Build 1607.
### Steps to reproduce the behavior
1. `docker-machine create --driver hyperv master`
2. `docker-machine create --driver hyperv worker`
3. `docker-machine ssh master`
4. master: `docker swarm init --advertise-addr eth0` 
5. worker: 
       `docker swarm join \`
             `--token SWMTKN-1-51mnr3nv48rfymobh2wk0cshdjyd66uhqsz9oun5u6zsep8ew0-15901tuo8wvphqravp4u91hsw \`
             `[fe80::215:5dff:fe02:e025]:2377`
6. error on worker: `Error response from daemon: could not find local IP address: dial udp [fe80::215:5dff:fe02:e025]:2377: connect: invalid argument`

**Comment by tompanq** [comment]
I also have the same error. Did you find a workaround to set up a swarm ?

**Comment by treiboll** [comment]
I created a new virtual switsch via the Hyper-V manager tool. This switch was allowed to connect to the external network based on the physical network interface of my laptop.

**Comment by prad9** [comment]
Having same issue with v1.13.1 too. 
Error: Error response from daemon: could not find local IP address: dial udp [fe80::215:5dff:fe2e:c604]:2377: connect: invalid argument

**Comment by treiboll** [comment]
Now the procedure for creating another virtual switch in hyper v is described in the [Docker docs](https://docs.docker.com/machine/drivers/hyper-v/). This solves this issue....
