### ISSUE TITLE
People on #docker irc channel have suggested using libvirt & libcloud

### ISSUE THREAD

**Issue by maximveksler** [docker/machine#372]
Hey guys, this project looks promising. 

I’d to bring to your attention that there was a recent discussion on #docker freenode about docker/machine and it being “garbage” for not using libvirt & libcloud.

You might wish to pay attention to the detail available via https://botbot.me/freenode/docker/2015-01-19/?msg=29964041&page=23

-m

**Comment by ehazlett** [comment]
Thanks for the heads up :)

We are trying to keep machine as light and simple.  libvirt is a C library and does not have an "official" Go library (http://libvirt.org/bindings.html) which is what machine is written in.  libcloud is written in Python and while it does have a lot of provider support, vital operations to Machine (such as key management) are not all supported across providers.

We are not averse to switch to a common cloud provider library but want to be sure it makes the most sense with what Machine is trying to accomplish.

Thanks!
