### ISSUE TITLE
docker machine config double quotes

### ISSUE THREAD

**Issue by Richard-Mathie** [docker/machine#3722]
Anyone know why this is failing in my bash shell? I keep on getting an extra escaped quote in the docker config output, which is preventing me from doing this:
```
$ docker $(docker-machine config master1) ps
Could not read CA certificate "\"/home/xxxxx/.docker/machine/certs/ca.pem\"": open "/home/xxxxx/.docker/machine/certs/ca.pem": no such file or directory
```
note the **\"**

```
$ docker-machine version
docker-machine version 0.8.1, build 41b3b25
$ uname -a
Linux hostname 4.4.0-34-generic #53-Ubuntu SMP Wed Jul 27 16:06:39 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

docker machine config works as expected:
```
$ docker-machine config master1
--tlsverify
--tlscacert="/home/xxxxx/.docker/machine/certs/ca.pem"
--tlscert="/home/xxxxx/.docker/machine/certs/cert.pem"
--tlskey="/home/xxxxx/.docker/machine/certs/key.pem"
-H=tcp://xxx.xxx.xxx.xxx:2376
```

**Comment by Richard-Mathie** [comment]
for now I will just
```
docker $(docker-machine config master1 | tr -d '\"') ps
```
but its a hassle

**Comment by nathanleclaire** [comment]
Just curious, what's the bash version?

Do you potentially have any shell config which might be interfering?

**Comment by Richard-Mathie** [comment]
Humm, I perged and reinstalled docker, seems to work now?

bash version is

    GNU bash, version 4.3.42(1)-release (x86_64-pc-linux-gnu)

I guess you can mark this as closed.

**Comment by nathanleclaire** [comment]
Oh weird -- thanks for following up
