### ISSUE TITLE
docker-machine restart (with generic driver) removes machine access

### ISSUE THREAD

**Issue by schmunk42** [docker/machine#3725]
Or at least `docker-machine ls` says it's in a `Stopped` state and I also can't start it any more...

```
generic driver does not support start
```

I'd say `docker-machine restart` should not work with the generic driver and output an error, like `start`.

```
docker-machine version 0.8.1, build 41b3b25o
```

**Comment by bamarni** [comment]
Are you sure the machine got in a stopped state after `docker-machine restart` and not something else?

With the generic driver restart should work fine (cf. https://github.com/docker/machine/blob/008283733e9be4c89844ce1ccbee0f944bbbde3d/drivers/generic/generic.go#L174).

**Comment by schmunk42** [comment]
Thanks for the link, this might be related to the underlying Vagrant VM in my case.
I just tried a manual reboot from within the VM and ran into similar problems.

I'd expect something like `sudo /etc/init.d/docker restart` here (for the generic driver)
