### ISSUE TITLE
Azure: DNS cloudapp.net is obsolete

### ISSUE THREAD

**Issue by JohannesHoppe** [docker/machine#3730]
I created my first container on azure, everything fine.
Let the machine name be XXX.

But now I’m not any longer able to reconnect to the host.
The driver assumes that the connection has to be made to `XXX.cloudapp.net` (classic resource management). Where can I change that?

The new resource management allows me to change the DNS name at any time, but `cloudapp.net` is not available any longer. The new DNS names are a combination of self-defined prefix and the datacenter. Eg. `XXX.westeurope.cloudapp.azure.com` or `YYY.westeurope.cloudapp.azure.com`

Please see also this blogpost:
http://www.codewrecks.com/blog/index.php/2015/10/11/where-is-my-dns-name-for-azure-vm-with-new-resource-manager/

Any help is appreaciated!

Regards,
Johannes

**Comment by nathanleclaire** [comment]
Check out `/etc/resolv.conf` in the VM to take a look -- I think it's `${hostname}.${dnsserver}` (where dnsserver is the `search` in that file)

**Comment by JohannesHoppe** [comment]
Thanks for stepping in! :smile: 

But I don't use any VM??
This goes directly to azure. I would need to know where the string `cloudapp.net` is added to the connection. (it is a combination of config.json > Driver.MachineName + hardcoded `cloudapp.net)

**Comment by ahmetalpbalkan** [comment]
@JohannesHoppe what version of docker-machine are you using? As of v0.7.0 azure driver is completely rewritten to use Azure Resource Manager stack and it is not backwards compatible with the older versions of the driver.

**Comment by JohannesHoppe** [comment]
I see! I was working with `docker-machine version 0.6.0, build e27fb87`

**Comment by JohannesHoppe** [comment]
So I accidentally used the older docker-machine from PATH.
Now I'm realizing my confusion. I'm executing my commands with `docker-machine version 0.8.1, build 41b3b25` and everything is fine! Thanks! :+1:

**Comment by nathanleclaire** [comment]
thanks for following up to close @JohannesHoppe

**Comment by JohannesHoppe** [comment]
@nathanleclaire ahmetalpbalkan  Many thanks for the help! :smiley:
