### ISSUE TITLE
docker-machine does not work in elevated command window

### ISSUE THREAD

**Issue by zoltan-boros** [docker/machine#3732]
**System:**

Host OS: Windows 7 Enterprise, 64 bit, SP1
Docker Host runs on virtual Linux, that comes out of `<boot2docker.iso>`
Boot2Docker: 1.11.1 (TCL 7.0); HEAD : 7954f54 - Wed Apr 27 16:36:45 UTC 2016
Oracle VirtualBox: 5.0.20 r106931
Docker Toolbox: 1.11.1
Docker-Machine: 0.7.0, build a650a40

**Observed behaviour:**

The virtual Linux, that Docker Host runs on, started and running with normal rights (i.e. does not started with administrative rights).

On the host computer (Windows 7), in a command window (normal, i.e. not elevated):
```
c:\temp>docker-machine.exe ls
NAME         ACTIVE   DRIVER       STATE     URL                         SWARM   DOCKER    ERRORS
DockerHost   -        virtualbox   Running   tcp://192.168.99.100:2376           v1.11.1

c:\temp>docker-machine.exe ip DockerHost
192.168.99.100
```

On the host computer (Windows 7), in an elevated command window (i.e. started using "Run as Administrator"):
```
C:\Windows\system32>docker-machine.exe ls
NAME         ACTIVE   DRIVER       STATE     URL   SWARM   DOCKER   ERRORS
DockerHost            virtualbox   Timeout

C:\Windows\system32>docker-machine.exe ip DockerHost
Error getting IP address: Host is not running
```

Does someone any idea what's the cause?

**Expected behaviour:**

`docker-machine` works the same way and produces the same result even when it runs with administrative rights.

**Comment by nathanleclaire** [comment]
DM is meant to be invoked without administrator rights
