### ISSUE TITLE
azure machine should have azurefile-dockervolumedriver pre-installed

### ISSUE THREAD

**Issue by mrmunch** [docker/machine#3739]
[azurefile-dockervolumedriver](https://github.com/Azure/azurefile-dockervolumedriver) is a great plugin to use Azure File Storage as volume driver. I think this plugin should be pre-installed on the docker-machine when using Azure as a docker-machine driver.
On top: this feature needs a configuration file to work properly, so it also should be possible to give either a path to this config file (locally) or as command line arguments to create this file on the machine.

**Comment by nathanleclaire** [comment]
Hi @mrmunch thanks for the issue, I think it's a bit out of scope for Machine to bootstrap plugins, I'd suggest doing it after the fact with a container run or `ssh` commands.  Thanks!
