### ISSUE TITLE
documentation missing for gce local-ssd `--google-disk-type` driver option

### ISSUE THREAD

**Issue by sneak** [docker/machine#3754]
I can't use docker-machine to create GCE instances with a `local-ssd` disk type.  The error it gives when I try is super-cryptic: 

```
docker-machine -D create \
        --driver google \
        --google-preemptible \
        --engine-install-url experimental.docker.com \
        --google-project docker-machine-dev \
        --google-zone europe-west1-d \
        --google-machine-image https://www.googleapis.com/compute/v1/projects/ubuntu-os-cloud/global/images/ubuntu-1604-xenial-v20160830 \
        --google-machine-type n1-standard-16 \
        --google-disk-type https://www.googleapis.com/compute/v1/projects/docker-machine-dev/zones/europe-west1-d/diskTypes/local-ssd \
        --google-disk-size 375 \
        default
Docker Machine Version:  0.8.1, build 41b3b25
Found binary path at /Users/jp/Library/homebrew/bin/docker-machine
Launching plugin server for driver google
Plugin server listening at address 127.0.0.1:53694
() Calling .GetVersion
Using API Version  1
() Calling .SetConfigRaw
() Calling .GetMachineName
(flag-lookup) Calling .GetMachineName
(flag-lookup) Calling .DriverName
(flag-lookup) Calling .GetCreateFlags
Found binary path at /Users/jp/Library/homebrew/bin/docker-machine
Launching plugin server for driver google
Plugin server listening at address 127.0.0.1:53698
() Calling .GetVersion
Using API Version  1
() Calling .SetConfigRaw
() Calling .GetMachineName
(default) Calling .GetMachineName
(default) Calling .DriverName
(default) Calling .GetCreateFlags
(default) Calling .SetConfigFromFlags
Running pre-create checks...
(default) Calling .PreCreateCheck
(default) Check that the project exists
(default) Check if the instance already exists
(default) Calling .GetConfigRaw
Creating machine...
(default) Calling .Create
(default) Generating SSH Key
(default) Creating host...
(default) Opening firewall ports
(default) Creating instance
Error creating machine: Error in driver during machine creation: googleapi: Error 503: Code: '53C756CC9A9C8.AD5B488.560A99CD', backendError
notifying bugsnag: [Error creating machine: Error in driver during machine creation: googleapi: Error 503: Code: '53C756CC9A9C8.AD5B488.560A99CD', backendError]
bugsnag.Notify: [bugsnag/payload.deliver: Post https://notify.bugsnag.com/: dial tcp 174.129.216.255:443: connect: host is down]
make: *** [docker_start_gce]
```

I also tried with `--google-disk-type local-ssd` in addition to the full URI.  I tried with and without `--google-disk-size` (`local-ssd`s are only available in 375GB chunks.)

I ran out of time to spend digging deeper; hopefully someone who is interested in the GCE driver can pick this one up.

**Comment by lacerdamarcelo** [comment]
Have you tried to use "pd-ssd"?

**Comment by IljaKroonen** [comment]
Any news on this?

An option for mounting local SSDs would be helpful in our case. We use docker machine to run our CI jobs, and would like a very fast local storage option to mount our temporary database.

**Comment by rdoursenaud** [comment]
I was wondering if I could use local SSDs to speed up GitLab CI jobs as well.
Unfortunately local SSDs can't be used as boot disks (See: https://cloud.google.com/compute/docs/disks/local-ssd?hl=fr#create_local_ssd).
That's why the option is not available in docker-machine!

**Comment by hco** [comment]
Well, but you could attach a secondary local SSD to the machine - which is what we're doing now, but using the docker runner + google auto scaling.

**Comment by rdoursenaud** [comment]
@hco Of course, I've been thinking about that but I believe it's out of docker machine scope. How is it working for you?

**Comment by GeertJohan** [comment]
I got my docker-machine based gitlab-ci runner working with:
```
    --machine-machine-options "google-disk-type=pd-ssd"
    --machine-machine-options "google-disk-size=375"
```
I believe that for docker-machine these translate to simply 
```
--google-disk-type=pd-ssd
--google-disk-size=375
```

**Comment by sneak** [comment]
I (OP) stopped keeping track and stopped using docker-machine (and separately I avoid using Google or AWS services whenever possible as well).

Neither Docker Desktop for Mac or Windows is free software:

https://github.com/docker/for-mac

> Docker Desktop for Mac is free to download.

It's time to move away from any non-free ecosystem components.
