### ISSUE TITLE
[Virtualbox Driver] Nat rules on the NAT Interface available ?

### ISSUE THREAD

**Issue by xinity** [docker/machine#3759]
hi all,

been wondering if we can use docker-machine virtualbox driver to create NAT Rules on the NAT interface ?

seen portions of code who should allow that: https://github.com/docker/machine/blob/master/drivers/virtualbox/virtualbox.go#L927

but didn't find a way to use it to create specific NAT Rules on the NAT Interface

am i wrong ?

**Comment by nathanleclaire** [comment]
Best way today is to create them manually in VBox GUI -- it's not really common enough to be supported directly, mostly folks use the host only interface IP
