### ISSUE TITLE
Azure driver azure-open-port option only allows tcp

### ISSUE THREAD

**Issue by fjollberg** [docker/machine#3776]
Creating a machine with --azure-open-port 123 creates a 'Port7946AllowAny' rule that actually only allows tcp. Should allow any.

docker-machine version 0.8.1, build 41b3b25

**Comment by ahmetalpbalkan** [comment]
@fjollberg `--azure-open-port` defaults to TCP protocol if not explicitly specified as `123/udp` or `123/tcp`. As far as I know Azure does not allow creating firewall a single rule that covers both UDP/TCP at the same time.

**Comment by andrestc** [comment]
I think you can use "*" as protocol, but that would allow any protocol, not only tcp or udp

**Comment by ahmetalpbalkan** [comment]
@andrestc You're right. Prior to your recent changes `--azure-open-port` was just creating a `TCP` rule (not `Any`) so the `Any` behavior has never been there in the first place. It looks like we have two options:

1. make `Any` possible by specifying it explicitly: such as `"8080/any"` or `"8080/*"` and omitting protocol defaults to `Tcp`.
    - (preserves current and previous behavior).
    - I am not sure if EC2 supports the `Any` mode on firewall rules, if it does, perhaps we can update it accordingly too.

2. make `Any` the default when protocol is implicit: such as `"8080"` will create an `Any` rule. 
    - This would differ from existing/prior behavior (and users would not notice –but I'm not sure if it is particularly harmful).

From what I gather, @fjollberg needs a way of specifying `Any` and currently there is none. For the sake of backwards compatibility, I am more leaned towards (1), but not sure if the common code would work both on ec2 & azure drivers.

**Comment by andrestc** [comment]
@ahmetalpbalkan I almost sure we currently support option number 1 on the azure by using `8080/*`, here: https://github.com/docker/machine/blob/master/drivers/azure/util.go#L211

**Comment by ahmetalpbalkan** [comment]
@andrestc ah, perfect, I totally forgot about this! In this case @fjollberg just needs to use `--azure-open-port "123/*"`

**Comment by ahmetalpbalkan** [comment]
@fjollberg if that answers your question, please consider closing the issue.

**Comment by fjollberg** [comment]
I guess. However, the naming of the rules is confusing as "Any" also happens to also be the label in the portal for allowing both udp and tcp. But as long as #3777 is fixed so I can add additional rules for both protocols I'm fine.
