### ISSUE TITLE
Azure driver azure-open-port option fails to process protocol

### ISSUE THREAD

**Issue by fjollberg** [docker/machine#3777]
Creating a machine with --azure-open-port 123/udp or --azure-open-port 123/tcp to specify protocol fails due to illegal naming of firewall rule.

E.g:
Error creating machine: Error in driver during machine creation: network.SecurityGroupsClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Long running operation terminated with status 'Failed': Code="InvalidResourceName" Message="Resource name Port7946/tcpAllowAny is invalid. The name can be up to 80 characters long. It must begin with a word character, and it must end with a word character or with '_'. The name may contain word characters or '.', '-', '_'."

docker-machine version 0.8.1, build 41b3b25

**Comment by ahmetalpbalkan** [comment]
@andrestc it appears like the name for the azure firewall rule has `/` character which is not allowed, do you mind sending a fix, perhaps replacing `/` with `-` or removing it?

**Comment by andrestc** [comment]
Hi @ahmetalpbalkan, I created a PR with a test trying to reproduce this issue(but failed to). I'll be happy to fix this once Im able to reproduce it somehow.

**Comment by ahmetalpbalkan** [comment]
@andrestc here's an easy repro, you need to explicitly specify `/proto` part.

Also let's make sure that even when `/proto` is not specified, it's included in the name.

```
~ dm create -d azure --azure-open-port 5000/udp --azure-image 'coreos:coreos:stable:latest'  azure$RANDOM
Running pre-create checks...
(azure15930) Completed machine pre-create checks.
Creating machine...
(azure15930) Querying existing resource group.  name="docker-machine"
(azure15930) Resource group "docker-machine" already exists.
(azure15930) Configuring availability set.  name="docker-machine"
(azure15930) Configuring network security group.  name="azure15930-firewall" location="westus"
Error creating machine: Error in driver during machine creation: network.SecurityGroupsClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Long running operation terminated with status 'Failed': Code="InvalidResourceName" Message="Resource name Port5000/udpAllowAny is invalid. The name can be up to 80 characters long. It must begin with a word character, and it must end with a word character or with '_'. The name may contain word characters or '.', '-', '_'."
```
