### ISSUE TITLE
azure driver options

### ISSUE THREAD

**Issue by Lickkylee** [docker/machine#3792]
https://docs.docker.com/machine/drivers/azure/  This article provides some arguments that this docker-machine version doesn't support. e.g. --azure-dns
May I know who helps to maitain the docker article and where to find the correct reference guide for each version?

**Comment by ahmetalpbalkan** [comment]
@Lickkylee that's me. The feature has just been added yesterday, and unless you're compiling from source code you won't be able to use the feature. 

@nathanleclaire  @londoncalling any ideas why docs went live with `docs-v0.8.2-2016-09-26` which does not have a binary release yet? Please check

* `v0.8.2` https://github.com/docker/machine/commits/v0.8.2
* `docs-v0.8.2-2016-09-26` https://github.com/docker/machine/commits/docs-v0.8.2-2016-09-26

The docs release has azure changes such as

 ![image](https://cloud.githubusercontent.com/assets/159209/18922128/5c71a7c0-855c-11e6-8c3d-dc0908de6ebb.png)
![image](https://cloud.githubusercontent.com/assets/159209/18922130/61928f4e-855c-11e6-97dc-084411ccb30c.png)

but the binary release does not include the changes. This caused @Lickkylee to try to use a documented version that did not ship with the respective binary release.

**Comment by londoncalling** [comment]
@ahmetalpbalkan that's my fault .. there were changes in the docs I wasn't aware of, sorry. How  should we fix this now? I made some changes to docs I want in, but didn't mean to take those other changes.

**Comment by ahmetalpbalkan** [comment]
@londoncalling you can create a branch from `v0.8.2`'s head commit cherry-pick changes you particularly wanted to that branch and tag that branch as the new docs release.

**Comment by londoncalling** [comment]
Hi Ahmet, I've actually already fixed it with Nathan. I am going to ping
you when the new docs are published, hopefully within the hour. Thanks!
Sorry for the inconvenience ... more soon!

Vicky

On Wed, Sep 28, 2016 at 12:08 PM, Ahmet Alp Balkan <notifications@github.com

**Comment by ahmetalpbalkan** [comment]
No need to ping me me at all. :-) Just wanted to let you know about the sync issues btw docs and binaries.

**Comment by londoncalling** [comment]
@ahmetalpbalkan @nathanleclaire well just to close the loop, Machine docs are updated. My new stuff is in: [Getting started w/Machine on a local VM](https://docs.docker.com/machine/get-started/)  and [Hyper-V driver](https://docs.docker.com/machine/drivers/hyper-v/), and those forward-looking changes are out now: e.g., [Azure driver](https://docs.docker.com/machine/drivers/azure/)  

Thank you guys!

**Comment by nathanleclaire** [comment]
Thanks @londoncalling

**Comment by Lickkylee** [comment]
Thanks, all. That does make sense. I have saw the doc changed back. I will close this issue now.
