### ISSUE TITLE
No machine drivers for OVH cloud

### ISSUE THREAD

**Issue by larsmagnusherland** [docker/machine#3793]
Currently there are no machine drivers with native support for OVH, like there is for DigitalOcean and AWS. There are 2 available GIT's for setting it up towards the API, but it's 50/50 in getting them to work.

Since this is a very large provider (France, Canada) which can be used for Docker and other cloud software, it should have a Machine Driver like DigitalOcean. By adding this, it would make more people able to use Docker in a broader setup.

**Comment by nathanleclaire** [comment]
There is a plugin: https://github.com/yadutaf/docker-machine-driver-ovh

You can use that or write your own if desired.
