### ISSUE TITLE
Experimental boot2docker.iso not cached properly

### ISSUE THREAD

**Issue by fsoppelsa** [docker/machine#3797]
DM 0.8.2

How to reproduce:
`for i in `seq 3`; do docker-machine create -d virtualbox --virtualbox-boot2docker-url  https://github.com/boot2docker/boot2docker/releases/download/v1.12.2-rc1/boot2docker-experimental.iso node-$i; done`

This attempts to download the experimental ISO repeatedly to `.docker/machine/cache`, for each new machine.
I expect instead that the ISO is correctly cached at the first run and not pulled again.

```
(node-1) Downloading /Users/user/.docker/machine/cache/boot2docker.iso from https://github.com/boot2docker/boot2docker/releases/download/v1.12.2-rc1/boot2docker-experimental.iso...
...
(node-2) Downloading /Users/user/.docker/machine/cache/boot2docker.iso from https://github.com/boot2docker/boot2docker/releases/download/v1.12.2-rc1/boot2docker-experimental.iso...
```

Probably just pulling it as `boot2docker-experimental-1.12.2-rc1.iso` and checking for its existence could do the trick.

Tags: Virtualbox

**Comment by nathanleclaire** [comment]
`--virtualbox-boot2docker-url` will always go off and pull the image.  think about it -- you can't cache that safely.  `--virtualbox-boot2docker-url myurl.com/latest/boot2docker.iso` might give you back different ISOs on subsequent invocations (unlikely, but possible).
