### ISSUE TITLE
machine rm is not case sensitive?

### ISSUE THREAD

**Issue by nathanleclaire** [docker/machine#382]
Perhaps I'm missing something but it seems that `machine rm DEV` will actually remove the host named `dev`.  I would expect host names to be case sensitive.

**Comment by sthulb** [comment]
I guess it depends on your file system. HFS will be fine with either, ext3-4 would probably complain.

**Comment by ehazlett** [comment]
Closing as this is on the platform side and the user should be aware (just as with other files).
