### ISSUE TITLE
Docs migration, missing recent changes

### ISSUE THREAD

**Issue by ahmetalpbalkan** [docker/machine#3834]
@londoncalling since the `docs/drivers/azure.md` is now moved, I looked at `azure.md` at https://github.com/docker/docker.github.io/ {master,machine-vnext} branches. I can't see the docs I recently added here: https://github.com/docker/machine/pull/3784/files

Any ideas where they're gone?

**Comment by londoncalling** [comment]
@ahmetalpbalkan did you find it? I think what you are looking for is here, right? https://github.com/docker/docker.github.io/blob/vnext-machine/machine/drivers/azure.md
