### ISSUE TITLE
Add experimental boot2docker image support

### ISSUE THREAD

**Issue by mlangry** [docker/machine#3837]
Docker 1.12 contains experimental features. Boot2docker provides image "boot2docker-experimental.iso".
I wish add support for this in order to test experimental features.

**Comment by nathanleclaire** [comment]
you can use `docker-machine create --driver virtualbox --virtualbox-boot2docker-url` for this!

**Comment by mlangry** [comment]
Yes, but the iso image is downloaded each time.
So when I create several VMs is long, especially with my internet connection.

`(vm-1) Boot2Docker URL was explicitly set to "https://github.com/boot2docker/boot2docker/releases/download/v1.12.2/boot2docker-experimental.iso" at create time, so Docker Machine cannot upgrade this machine to the latest version.
Creating machine...
(vm-1) Boot2Docker URL was explicitly set to "https://github.com/boot2docker/boot2docker/releases/download/v1.12.2/boot2docker-experimental.iso" at create time, so Docker Machine cannot upgrade this machine to the latest version.
(vm-1) Downloading /home/martial/.docker/machine/cache/boot2docker.iso from https://github.com/boot2docker/boot2docker/releases/download/v1.12.2/boot2docker-experimental.iso...
(vm-1) 0%....10%....20%....30%....40%....50%....60%....70%....80%....90%....100%`
`...`
`(vm-2) Boot2Docker URL was explicitly set to "https://github.com/boot2docker/boot2docker/releases/download/v1.12.2/boot2docker-experimental.iso" at create time, so Docker Machine cannot upgrade this machine to the latest version.
Creating machine...
(vm-2) Boot2Docker URL was explicitly set to "https://github.com/boot2docker/boot2docker/releases/download/v1.12.2/boot2docker-experimental.iso" at create time, so Docker Machine cannot upgrade this machine to the latest version.
(vm-2) Downloading /home/martial/.docker/machine/cache/boot2docker.iso from https://github.com/boot2docker/boot2docker/releases/download/v1.12.2/boot2docker-experimental.iso...
(vm-2) 0%....10%....20%....30%....40%....50%....60%....70%....80%....90%....100%`
`...`

**Comment by nathanleclaire** [comment]
@mlangry Download it once and set the flag to `file://`.

e.g.,

```
$ docker-machine create -d virtualbox \
    --virtualbox-boot2docker-url file:///Users/mlangry/Downloads/boot2docker-experimental.iso \
    vm-2
````

**Comment by mlangry** [comment]
Thank you for your reply.
I have already implemented this feature ([commit](https://github.com/mlangry/machine/commit/d588aa2e65d1b1cd253a9b1718ca05f0e39adbbd)).
It'll be nice if you could take some minutes to look at my implementation and tell me what you think.
This is my first program in go and my first contribution to an open source project.
It will be instructive to me.
Thank you

**Comment by nathanleclaire** [comment]
Thanks for the contribution @mlangry .  Machine has a pretty large scope already so I try to avoid merging in changes when they are already adequately covered by existing features.  I'm not open to this change in particular.  But please keep coding and contributing, tenacity like yours is what makes projects great.  In the future I'd suggest opening issues for discussion and see if the maintainers are interested first before working on code (unless you just like hacking, which is also perfectly valid).
