### ISSUE TITLE
Override default GCE service account

### ISSUE THREAD

**Issue by christianbundy** [docker/machine#3846]
I'm running Docker Machine on an GCE instance, but I don't want to use the service account that the instance was created with. I've tried logging in with `gcloud auth login` and have the correct service account activated, but when I run commands they error out as "Insufficient Permission" because Machine is using the instance's service account rather than the one set up with gcloud.

This is consistent with the Machine documentation:

> So if `docker-machin`e is used from a GCE host, authentication will happen automatically via the built-in service account. Otherwise, install gcloud and get through the oauth2 process with `gcloud auth login`.

Is there a way to override this default behavior? Thanks!

---

Update: I was able to set the `GOOGLE_APPLICATION_CREDENTIALS` environment variable to point to  a service account keyfile, is that the best way to go about it?

**Comment by nathanleclaire** [comment]
> Update: I was able to set the GOOGLE_APPLICATION_CREDENTIALS environment variable to point to a service account keyfile, is that the best way to go about it?

Seems to be so ... Defining default behavior can be a bit tricky here
