### ISSUE TITLE
run container with host user in macOS

### ISSUE THREAD

**Issue by waynezw0618** [docker/machine#3850]
Dear everyone
I am running on macOS sierra. before I pull the images. I did add a group named docker and add my host user to the docker group. I did this by using system reference->users and groups. but still I cannot run docker images with this user. here is the command I run on my machine and the error messages I get.
`Zhangs-MacBook-Pro-7:~ zhang$ id`
`uid=501(zhang) gid=20(staff) groups=20(staff),503(docker),401(com.apple.sharepoint.group.1),12(everyone),61(localaccounts),79(_appserverusr),80(admin),81(_appserveradm),98(_lpadmin),33(_appstore),100(_lpoperator),204(_developer),395(com.apple.access_ftp),398(com.apple.access_screensharing),399(com.apple.access_ssh)`

`Zhangs-MacBook-Pro-7:~ zhang$ docker run -it -u zhang ubuntu`

`docker: Error response from daemon: linux spec user: unable to find user zhang: no matching entries in passwd file.
`

Thanks!

**Comment by nathanleclaire** [comment]
`-u` needs a  user on the Docker VM, not on your MacBook
