### ISSUE TITLE
swarm opt  "heartbeat" Fails

### ISSUE THREAD

**Issue by viveky4d4v** [docker/machine#3851]
As per the documents  - https://docs.docker.com/machine/reference/create/

While creating docker machine the following option should work , 

     --swarm-opt heartbeat=20 \

Doesn't seems to be working for me , getting below error -

    time="2016-10-27T14:49:19Z" level=fatal msg="invalid --heartbeat: time: missing unit in duration 20" 

Is it saying that i should append "s" or "sec" to "20"  . Please suggest

**Comment by viveky4d4v** [comment]
It worked after adding "s"   - 

 --swarm-opt heartbeat=20s \

Please correct the documentation , we trust whatever is written :)

You can close this issue for now .

**Comment by nathanleclaire** [comment]
Would love to see a PR at https://github.com/docker/docker.github.io for this!  (if merged into master it should be deployed immediately) FYI @londoncalling
