### ISSUE TITLE
Docker-machine fails to upgrade arch host

### ISSUE THREAD

**Issue by zimy** [docker/machine#3853]
When I run command to upgade my host

```
$ docker-machine upgrade archhost
Waiting for SSH to be available...
Detecting the provisioner...
Upgrading docker...
Something went wrong running an SSH command!
command : sudo -E pacman -Uy --noconfirm --noprogressbar docker
err     : exit status 1
output  : error: invalid option '-y'
```

Docker-machine version is 0.8.0-rc2, build 4ca1b85

**Comment by nathanleclaire** [comment]
Looks like a bug :( cc @hairyhenderson

**Comment by zimy** [comment]
Should I provide any extra information to help you?

**Comment by hairyhenderson** [comment]
😲 

@zimy - what version of Arch is that? And have you tried with the latest docker-machine?

**Comment by zimy** [comment]
Arch is fresh, it was installed last month and have updates a week ago.
Now I tested operation with docker-machine 0.8.2 (latest release, version 0.8.2, build e18a919). Exactly same output.

**Comment by zimy** [comment]
As I can see, the comand above containing pacman is constructed here  machine/libmachine/provision/arch.go 
And line 62 adds flag `y`

**Comment by zimy** [comment]
Another problem is that  `$ sudo pacman -U docker` provides no useful output itself because according to 
[archwiki](https://wiki.archlinux.org/index.php/pacman) pacman uses -U to install package from file like 
`pacman -U file:///path/to/package/package_name-version.pkg.tar.xz`

**Comment by hairyhenderson** [comment]
@zimy - ok, looks like I misunderstood `-U`... sorry about that!

After reading the `pacman` man page a bit more closely it looks like `-Sy` will upgrade the package if a newer one is available.

I must apologize - I stopped using Arch Linux probably around a year ago 😞 

PR incoming soon!

**Comment by zimy** [comment]
@hairyhenderson Thank you!

**Comment by zimy** [comment]
@hairyhenderson Just tested own modified build. and now it works as expected!

**Comment by hairyhenderson** [comment]
@zimy - ok, cool!
