### ISSUE TITLE
Unable to provision CoreOS instance with 1192.2.0 or later

### ISSUE THREAD

**Issue by egoldschmidt** [docker/machine#3858]
It looks like later versions of the Docker daemon no longer use the `daemon` subcommand:

`dockerd: "dockerd" requires 0 arguments`

Since the Docker daemon never starts, it's impossible to provision an instance with docker-machine.

This release is currently live on the alpha and beta channels.

**Comment by easybe** [comment]
Check out https://github.com/docker/machine/pull/3392

**Comment by twang2218** [comment]
I ran into the same issue here, as the `/usr/lib/coreos/dockerd daemon` will become `/usr/bin/dockerd daemon` for 1192.0 or later, which caused the problem.

**Comment by nathanleclaire** [comment]
Try this out on 0.10.0 -- there should be a fix ! Thanks all
