### ISSUE TITLE
add something like drivers.ErrAuthInvalid

### ISSUE THREAD

**Issue by nathanleclaire** [docker/machine#386]
This would be nice to return if your API credentials are no good.  That way, the experience of getting back that type of error would always be the same.  Actually in general I am starting to think that any time drivers write text to STDOUT or `log` which is not `log.Debug` it is kind of an anti-pattern.

**Comment by sthulb** [comment]
I agree, it would be helpful if stderr was used more too. Perhaps for all logging that's not info

**Comment by ehazlett** [comment]
I think err types in general would be better all around.

**Comment by ehazlett** [comment]
Closing as this will be handled in #550 / #553.  Noted in #550.
