### ISSUE TITLE
VirtualBox driver 32 cpus limitation

### ISSUE THREAD

**Issue by StateOfTheArt89** [docker/machine#3871]
Hi,

I would like to use Docker Machine on bigger machines (more than 32 cores) to create VirtualBox VMs. But for some reason every machine I create ends up having just 32 cores instead of 80 (in my case).

So I had a look into the VirtualBox driver and found the source for this limitation:  https://github.com/docker/machine/blob/32185d47d2b8ad336a602d8a52645b99d6514796/drivers/virtualbox/virtualbox.go#L362-L364 

Is there any specific reason why this limitation was set to 32?
Best regards
-Malte

**Comment by nathanleclaire** [comment]
https://forums.virtualbox.org/viewtopic.php?f=24&t=41211 suggests that guests are limited to 32 cores, though that is not guaranteed to be the case...

Have you verified in the VirtualBox GUI that it will allow you to use more cores?  I don't have such a large box to test out on :D

**Comment by StateOfTheArt89** [comment]
I don't have a GUI on that server, but a test via the CLI said it all:

```
VBoxManage modifyvm test --cpus 42
VBoxManage: error: Invalid virtual CPU count: 42 (must be in range [1, 32])
```

Didn't realize this VirtualBox limitation exists.
Thank you for your efforts
