### ISSUE TITLE
[Azure Driver] Cannot reference VNET from different resource group

### ISSUE THREAD

**Issue by sebastianvoss** [docker/machine#3900]
Cannot create a new docker host using the Azure driver while referencing a VNET from a different resource group (e.g. docker-machine:docker-machine-vnet).

I'm using docker-machine version 0.8.2, build e18a919

```
docker-machine create --driver azure \
	--azure-resource-group docker2 \
	--azure-vnet docker-machine:docker-machine-vnet \
	--azure-subscription-id b856b9ae-ed6d-4507-96f0-edcd172af335 \
	--azure-location westeurope \
	--azure-open-port 80 \
	--azure-open-port 443 \
	docker2
```

This results in the error below:

> (docker2) Querying if virtual network already exists.  name="docker-machine:docker-machine-vnet" location="westeurope"
> Error creating machine: Error in driver during machine creation: network.VirtualNetworksClient#Get: Failure responding to request: StatusCode=400 -- Original Error: azure: Service returned an error. Code="InvalidDoubleEncodedRequestUri" Message="The request URI 'https://management.azure.com:443/subscriptions/xyz/resourceGroups/docker2/providers/Microsoft.Network/virtualnetworks/docker-machine%253Adocker-machine-vnet?api-version=2015-06-15' is not valid, because it contains double encoding sequence '%25'." Status=400

**Comment by nathanleclaire** [comment]
cc @ahmetalpbalkan

**Comment by ahmetalpbalkan** [comment]
Looks like it'll ship in v0.9.0 according to the tag here. https://github.com/docker/machine/pull/3666 Nathan, can you confirm?

**Comment by nathanleclaire** [comment]
Ah yeah good times -- it should be in 0.9.0-rc2, @sebastianvoss please try that
