### ISSUE TITLE
Cannot create ubuntu-1404-trusty-v20161130 machine on Google Cloud 

### ISSUE THREAD

**Issue by huseyinbabal** [docker/machine#3904]
Hi,
I am trying to create machine on Google Cloud by using following command:

`docker-machine create --driver google --google-machine-image ubuntu-1404-trusty-v20161130 --google-project <project> --google-disk-size 30 --google-machine-type n1-standard-2 google-machine`

And got following error;

**Error creating machine: Error in driver during machine creation: googleapi: Error 400: Invalid value for field 'resource.disks[0].initializeParams.sourceImage': 'ubuntu-1404-trusty-v20161130'. The URL is malformed., invalid
Opting out of crash reporting**

I can see the image in google cloud image list by using following command:

`gcloud compute images list`

Thanks in advance

**Comment by huseyinbabal** [comment]
Sorry, I need to give absolute url https://www.googleapis.com/compute/v1/projects/ubuntu-os-cloud/global/images/family/ubuntu-1404-lts instead of ubuntu-1404-trusty-v20161130 .

**Comment by dminkovsky** [comment]
Wow thanks for posting your follow-up comment. I couldn't find the URL prefix anywhere. How on earth did you Google this?

**Comment by jjhbw** [comment]
I encountered this as well. For the record, run 
`gcloud compute images list --uri`
to get the absolute URIs of the available images.

**Comment by oussemos** [comment]
It works for me with just `ubuntu-os-cloud/global/images/ubuntu-1404-trusty-v20161130`
No need to add all the URL
