### ISSUE TITLE
"Error starting docker-machine: exit status 1

### ISSUE THREAD

**Issue by shyamhd** [docker/machine#3914]

**Comment by tronicum** [comment]
more details please.

**Comment by shyamhd** [comment]
@tronicum this issue has been resolved. This is is related with #3648
I have used gitbash to work with docker-machine to manage /dev/null file.
Regards,
Shyam

**Comment by mwangialfredkiguru** [comment]
On windows 10 PowerShell, docker-machine start returns exit status 1. Funny thing is that it does not display anything on the event viewer.
