### ISSUE TITLE
"Error starting docker-machine: exit status 1" Hyperv

### ISSUE THREAD

**Issue by shyamhd** [docker/machine#3915]
Hi all,
I have created docker-machine using
## `docker-machine create --driver hyperv node-1`.
But when I start docker-machine using 'docker-machine start node-1'
It gives me error:
## **`exit status 1`**
```
Docker Version:
Client:
 Version:      1.13.0-rc3
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   4d92237
 Built:        Tue Dec  6 01:15:44 2016
 OS/Arch:      windows/amd64

Server:
 Version:      1.13.0-rc3
 API version:  1.25 (minimum version 1.12)
 Go version:   go1.7.3
 Git commit:   4d92237
 Built:        Tue Dec  6 01:15:44 2016
 OS/Arch:      linux/amd64
 Experimental: true
Docker Version:
Client:
 Version:      1.13.0-rc3
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   4d92237
 Built:        Tue Dec  6 01:15:44 2016
 OS/Arch:      windows/amd64

Server:
 Version:      1.13.0-rc3
 API version:  1.25 (minimum version 1.12)
 Go version:   go1.7.3
 Git commit:   4d92237
 Built:        Tue Dec  6 01:15:44 2016
 OS/Arch:      linux/amd64
 Experimental: true
```
```
Docker-machine Version:
docker-machine version 0.9.0-rc2, build 7b19591
```
Operating System: 
Windows 10 Pro

I have refer this issue https://github.com/docker/machine/issues/1716
but it is related to Vritualbox and I'm using Hyperv.

**Comment by tronicum** [comment]
use debug (-D)

**Comment by shyamhd** [comment]
@tronicum this issue has been resolved. This is is related with https://github.com/docker/machine/issues/3648
I have used gitbash to work with docker-machine to manage **/dev/null** file.
Regards,
Shyam

**Comment by mdeselincourt** [comment]
"Use debug -D switch" was good advice from tronicum above. In my case the process was being prevented by the policy rules deployed to the PC.

**Comment by alaagalal** [comment]
when trying to start after a monh using 
"docker-machine start worker1"
The output ....error

Starting "worker1"...
(worker1) Check network to re-create if needed...
Unable to start the VM: /usr/bin/VBoxManage startvm worker1 --type headless failed:
VBoxManage: error: Could not open the medium '/machine/machines/worker1/disk.vmdk'.
VBoxManage: error: VMDK: inconsistency between grain table and backup grain table in 'docker/machine/machines/worker1/disk.vmdk' (VERR_VD_VMDK_INVALID_HEADER).
VBoxManage: error: VD: error VERR_VD_VMDK_INVALID_HEADER opening image file '/.docker/machine/machines/worker1/disk.vmdk' (VERR_VD_VMDK_INVALID_HEADER)
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component MediumWrap, interface IMedium


Any Advice to solve this problem

**Comment by adrianiftode** [comment]
It seems if I run the command with from a `cmd` started with administrator privileges, then I don't get this error and the machine is started.

**Comment by Antony12931a0519** [comment]
even though running the commands on the admin privileges ..is not working giving the same error.
Starting "manager1"...
exit status 1

**Comment by Santos-Jefferson** [comment]
> It seems if I run the command with from a `cmd` started with administrator privileges, then I don't get this error and the machine is started.

Yep, the same here. I am using GIt Bash as an Administrator. Working fine!
