### ISSUE TITLE
memory leak of docker toolbox

### ISSUE THREAD

**Issue by waynezw0618** [docker/machine#3921]
Dear everyone.
I installed docker toolbox and on a windows 7 machine, and installed Arch Linux in docker. When I run my application in Docker, memory leak can be observed. It leads to slow down of running application. I supppose that is because the arch is using swap.  I am sure it is not of the application. As the application can run properly in a native arch Linux system. Can you please let me know how to fix it?

/Wei

**Comment by nathanleclaire** [comment]
Thanks Wei, 

Please provide a minimally reproducible example (e.g., `docker run ...` in the boot2docker VM) or we won't be able to help you.  Thanks.

**Comment by waynezw0618** [comment]
Hello Nathan
I run my  image by two script one is to install image, the other is to run image. 
Here is script for run image:
Docket run -it -d --name OpenFOAM --user=501 -e HOME=$myhome -e USER=$myname --workdir =$myhome -v /openfoam:/Users/Wei:rw ${imagename} /bin/bash

To run image
Docker start OpenFOAM
Docker exec -it OpenFOAM /bin/bash

The weird thing is even if I don't run any application the memory cost in windows still keeps increasing. So after 12 hours, you will find almost 20G memory are eaten...
