### ISSUE TITLE
Not able to change machine status to 'Active'

### ISSUE THREAD

**Issue by sathishmanoharan** [docker/machine#3923]
Hi, I am not able to make a machine 'active' in docker-machine. Ran 'eval $(sudo docker-machine env eris)' command. But it does not affect the status. I am using 0.8.2 version. Is there an issue?

![image](https://cloud.githubusercontent.com/assets/18713130/21220831/d00f0986-c2e0-11e6-9d90-5142298d53ee.png)
![image](https://cloud.githubusercontent.com/assets/18713130/21220847/e5de9704-c2e0-11e6-8c0a-82e11274f1fb.png)

**Comment by nathanleclaire** [comment]
Thanks for the issue -- you shouldn't be using `sudo` with `docker-machine`! Execute commands as a normal user, I think this is due to `eval $(sudo docker-machine env)` getting the environment variables set as `sathish`, whereas `ls` is invoked as the superuser.
