### ISSUE TITLE
Graphdriver as a plugin hangs in ApplyDiff

### ISSUE THREAD

**Issue by jjobi** [docker/machine#3924]
I have a developed a graphdriver for docker which works well when used with a modified docker binary which recognizes the new graphdriver (similar to btrsfs/zfs etc).  I tried to make that work with new graphdriver plugins using the go-plugins-helpers, but that does not seem to work when pulling images.  A simple command like "docker pull hello-world" would cause the plugin to hang with following threads.

goroutine 5 [syscall]:
syscall.Syscall6(0xf7, 0x1, 0x18e9a, 0xc420076f80, 0x1000004, 0x0, 0x0, 0x6caec0, 0xc420049738, 0x436c4e)
        /usr/local/go/src/syscall/asm_linux_amd64.s:44 +0x5
os.(*Process).blockUntilWaitable(0xc4200e0600, 0x7463a0, 0xc4200e2c60, 0xc4200c7c00)
        /usr/local/go/src/os/wait_waitid.go:28 +0xbc
os.(*Process).wait(0xc4200e0600, 0x0, 0x4139ae, 0xc4200c7c38)
        /usr/local/go/src/os/exec_unix.go:22 +0xab
os.(*Process).Wait(0xc4200e0600, 0xc420049840, 0x0, 0x0)
        /usr/local/go/src/os/doc.go:49 +0x2b
os/exec.(*Cmd).Wait(0xc4200e2c60, 0x0, 0x0)
        /usr/local/go/src/os/exec/exec.go:434 +0x6d
os/exec.(*Cmd).Run(0xc4200e2c60, 0xc42004d810, 0x0)
        /usr/local/go/src/os/exec/exec.go:279 +0x48
github.com/docker/docker/pkg/chrootarchive.applyLayerHandler(0xc420014cd0, 0x50, 0x7f298364f038, 0xc4200cf2c0, 0xc42007f0e0, 0xc420049a00,
 0x0, 0x0, 0x0)
        /home/jobi/px-graph/pxg/src/github.com/docker/docker/pkg/chrootarchive/diff_unix.go:118 +0x46f
github.com/docker/docker/pkg/chrootarchive.ApplyUncompressedLayer(0xc420014cd0, 0x50, 0x7f298364f038, 0xc4200cf2c0, 0xc42007f0e0, 0xc42001
4cd0, 0x50, 0x0)
        /home/jobi/px-graph/pxg/src/github.com/docker/docker/pkg/chrootarchive/diff.go:22 +0x58
github.com/docker/docker/daemon/graphdriver.(*NaiveDiffDriver).ApplyDiff(0xc4200cee80, 0xc42004d43f, 0x40, 0xc42004d480, 0x0, 0x7f298364f0
38, 0xc4200cf2c0, 0x0, 0x0, 0x0)
        /home/jobi/px-graph/pxg/src/github.com/docker/docker/daemon/graphdriver/fsdiff.go:142 +0x235
main.(*Driver).ApplyDiff(0xc42004ab00, 0xc42004d43f, 0x40, 0xc42004d480, 0x0, 0x7f298364f038, 0xc4200cf2c0, 0x1, 0xc42004d425, 0x1)
        /home/jobi/px-graph/pxg/pxg.go:259 +0x1e2
github.com/docker/go-plugins-helpers/graphdriver.(*Handler).initMux.func13(0xa6b1c0, 0xc4200d48f0, 0xc4200ca5a0)
        /home/jobi/px-graph/pxg/src/github.com/docker/go-plugins-helpers/graphdriver/api.go:394 +0x134
net/http.HandlerFunc.ServeHTTP(0xc42000d9f0, 0xa6b1c0, 0xc4200d48f0, 0xc4200ca5a0)
        /usr/local/go/src/net/http/server.go:1726 +0x44
net/http.(*ServeMux).ServeHTTP(0xc4200173b0, 0xa6b1c0, 0xc4200d48f0, 0xc4200ca5a0)
        /usr/local/go/src/net/http/server.go:2022 +0x7f
net/http.serverHandler.ServeHTTP(0xc420076800, 0xa6b1c0, 0xc4200d48f0, 0xc4200ca5a0)
        /usr/local/go/src/net/http/server.go:2202 +0x7d
net/http.(*conn).serve(0xc420076a80, 0xa6b840, 0xc4200cecc0)
        /usr/local/go/src/net/http/server.go:1579 +0x4b7
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:2293 +0x44d

goroutine 9 [syscall]:
syscall.Syscall(0x0, 0x8, 0xc420086a00, 0x200, 0x0, 0x0, 0x0)
        /usr/local/go/src/syscall/asm_linux_amd64.s:18 +0x5
syscall.read(0x8, 0xc420086a00, 0x200, 0x200, 0x7f298369a000, 0x0, 0x0)
        /usr/local/go/src/syscall/zsyscall_linux_amd64.go:783 +0x55
syscall.Read(0x8, 0xc420086a00, 0x200, 0x200, 0x0, 0xc4200f0000, 0xc4200e6000)
        /usr/local/go/src/syscall/syscall_unix.go:161 +0x49
os.(*File).read(0xc420026248, 0xc420086a00, 0x200, 0x200, 0x4df00b, 0x6b04c0, 0x200)
        /usr/local/go/src/os/file_unix.go:228 +0x4f
os.(*File).Read(0xc420026248, 0xc420086a00, 0x200, 0x200, 0x0, 0x0, 0xc420025620)
        /usr/local/go/src/os/file.go:101 +0x59
bytes.(*Buffer).ReadFrom(0xc42004d7a0, 0xa67700, 0xc420026248, 0xc420025688, 0x1, 0x0)
        /usr/local/go/src/bytes/buffer.go:176 +0x155
io.copyBuffer(0xa668c0, 0xc42004d7a0, 0xa67700, 0xc420026248, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/io/io.go:384 +0x323
io.Copy(0xa668c0, 0xc42004d7a0, 0xa67700, 0xc420026248, 0x0, 0x0, 0x0)
        /usr/local/go/src/io/io.go:360 +0x68
os/exec.(*Cmd).writerDescriptor.func1(0x0, 0x0)
        /usr/local/go/src/os/exec/exec.go:253 +0x4d
os/exec.(*Cmd).Start.func1(0xc4200e2c60, 0xc4200c7ba0)
        /usr/local/go/src/os/exec/exec.go:370 +0x27
created by os/exec.(*Cmd).Start
        /usr/local/go/src/os/exec/exec.go:371 +0x4db

goroutine 10 [syscall]:
syscall.Syscall(0x0, 0xa, 0xc420102050, 0x5b0, 0x23, 0xc420102000, 0x7f29836a12a0)
        /usr/local/go/src/syscall/asm_linux_amd64.s:18 +0x5
syscall.read(0xa, 0xc420102050, 0x5b0, 0x5b0, 0x7f298369a000, 0x0, 0x0)
        /usr/local/go/src/syscall/zsyscall_linux_amd64.go:783 +0x55
syscall.Read(0xa, 0xc420102050, 0x5b0, 0x5b0, 0x0, 0xc420029c00, 0xc4200e61a0)
        /usr/local/go/src/syscall/syscall_unix.go:161 +0x49
os.(*File).read(0xc420026258, 0xc420102050, 0x5b0, 0x5b0, 0x4df00b, 0x6b04c0, 0x600)
        /usr/local/go/src/os/file_unix.go:228 +0x4f
os.(*File).Read(0xc420026258, 0xc420102050, 0x5b0, 0x5b0, 0x50, 0x0, 0x0)
        /usr/local/go/src/os/file.go:101 +0x59
bytes.(*Buffer).ReadFrom(0xc42004d810, 0xa67700, 0xc420026258, 0xc420025e88, 0x1, 0x0)
        /usr/local/go/src/bytes/buffer.go:176 +0x155
io.copyBuffer(0xa668c0, 0xc42004d810, 0xa67700, 0xc420026258, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/io/io.go:384 +0x323
io.Copy(0xa668c0, 0xc42004d810, 0xa67700, 0xc420026258, 0x0, 0x0, 0x0)
        /usr/local/go/src/io/io.go:360 +0x68
os/exec.(*Cmd).writerDescriptor.func1(0x0, 0x0)
        /usr/local/go/src/os/exec/exec.go:253 +0x4d
os/exec.(*Cmd).Start.func1(0xc4200e2c60, 0xc4200c7c00)
        /usr/local/go/src/os/exec/exec.go:370 +0x27
created by os/exec.(*Cmd).Start
        /usr/local/go/src/os/exec/exec.go:371 +0x4db

**Comment by jjobi** [comment]
Invoking `reexec.Init()` in main() fixed the issue.  Thanks to Brian for helping with that.  I did not see any examples or documentation about this though.

**Comment by nathanleclaire** [comment]
Is there a machine issue here or can we close?

**Comment by jjobi** [comment]
It can be closed now.

**Comment by nathanleclaire** [comment]
thanks
