### ISSUE TITLE
Add azure machine without firewall/nsg

### ISSUE THREAD

**Issue by Negashev** [docker/machine#3929]
How I can run docker-machine in azure without network security group?

**Comment by ahmetalpbalkan** [comment]
It is not supported. NSGs are good practice. 👍

**Comment by Negashev** [comment]
If  i use app docker with many open ports? What i wil do?

**Comment by Negashev** [comment]
@ahmetalpbalkan What will i do?

**Comment by ahmetalpbalkan** [comment]
@Negashev you can specify a port range with --open-port and open many ports at once.

**Comment by Negashev** [comment]
@ahmetalpbalkan Thanks!

**Comment by bigredthelogger** [comment]
The best practice from Azure is to leverage NSGs attached to your Virtual Network subnet rather than creating one NSG per Virtual Machine. This would be a required feature for enterprise use of Docker Machine, and currently the reason why Rancher 2.0 is not viable.
