### ISSUE TITLE
[question]change base os

### ISSUE THREAD

**Issue by lmayorga1980** [docker/machine#3932]
Is it possible to use centos or rhel as a base operating system?

**Comment by tronicum** [comment]
yes

**Comment by nathanleclaire** [comment]
Yes, specify it as such with the image flag for the driver (e.g., `--amazonec2-ami`) -- this tends to work better w/ cloud providers etc. than local drivers, since a lot of assumptions about local drivers work towards a read-only ISO-based model (i.e., `boot2docker`)
