### ISSUE TITLE
"docker-machine start default" is failed!!!!!!

### ISSUE THREAD

**Issue by zzchu** [docker/machine#3935]
Hi, experts.

the "default" VM have worked successfully, the issue happen after I changed the NAT adapter to Bridge adapter, and it still exist even I have rolled back the modificaiton.
because I have worked on the VM several days, so recreating the VM will lost my efforts of those days. is there any method to restore the environment again?  is there any method to get the docker images with the docker-machine start failure? many thanks!

docker-machine info:
docker-machine version 0.7.0, build a650a40

the issue detailed info:
 >docker-machine -D start default
Docker Machine Version:  0.7.0, build a650a40
Found binary path at /usr/local/bin/docker-machine
Launching plugin server for driver virtualbox
Plugin server listening at address 127.0.0.1:52527
() Calling .GetVersion
Using API Version  1
() Calling .SetConfigRaw
() Calling .GetMachineName
command=start machine=default
Starting "default"...
(default) Calling .GetState
(default) DBG | COMMAND: /usr/local/bin/VBoxManage showvminfo default --machinereadable
(default) DBG | STDOUT:
(default) DBG | {
(default) DBG | name="default"
(default) DBG | groups="/"
(default) DBG | ostype="Linux 2.6 / 3.x / 4.x (64-bit)"
(default) DBG | UUID="ddcc001e-4b38-4aa1-948d-e1d5d49e7868"
(default) DBG | CfgFile="/Users/zzchu/.docker/machine/machines/default/default/default.vbox"
(default) DBG | SnapFldr="/Users/zzchu/.docker/machine/machines/default/default/Snapshots"
(default) DBG | LogFldr="/Users/zzchu/.docker/machine/machines/default/default/Logs"
(default) DBG | hardwareuuid="ddcc001e-4b38-4aa1-948d-e1d5d49e7868"
(default) DBG | memory=2048
(default) DBG | pagefusion="off"
(default) DBG | vram=8
(default) DBG | cpuexecutioncap=100
(default) DBG | hpet="on"
(default) DBG | chipset="piix3"
(default) DBG | firmware="BIOS"
(default) DBG | cpus=1
(default) DBG | pae="on"
(default) DBG | longmode="on"
(default) DBG | cpuid-portability-level=0
(default) DBG | bootmenu="disabled"
(default) DBG | boot1="disk"
(default) DBG | boot2="none"
(default) DBG | boot3="none"
(default) DBG | boot4="none"
(default) DBG | acpi="on"
(default) DBG | ioapic="on"
(default) DBG | biossystemtimeoffset=0
(default) DBG | rtcuseutc="on"
(default) DBG | hwvirtex="on"
(default) DBG | nestedpaging="on"
(default) DBG | largepages="on"
(default) DBG | vtxvpid="on"
(default) DBG | vtxux="on"
(default) DBG | paravirtprovider="default"
(default) DBG | VMState="poweroff"
(default) DBG | VMStateChangeTime="2016-12-21T08:46:34.848000000"
(default) DBG | monitorcount=1
(default) DBG | accelerate3d="off"
(default) DBG | accelerate2dvideo="off"
(default) DBG | teleporterenabled="off"
(default) DBG | teleporterport=0
(default) DBG | teleporteraddress=""
(default) DBG | teleporterpassword=""
(default) DBG | tracing-enabled="off"
(default) DBG | tracing-allow-vm-access="off"
(default) DBG | tracing-config=""
(default) DBG | autostart-enabled="off"
(default) DBG | autostart-delay=0
(default) DBG | defaultfrontend=""
(default) DBG | storagecontrollername0="SATA"
(default) DBG | storagecontrollertype0="IntelAhci"
(default) DBG | storagecontrollerinstance0="0"
(default) DBG | storagecontrollermaxportcount0="30"
(default) DBG | storagecontrollerportcount0="30"
(default) DBG | storagecontrollerbootable0="on"
(default) DBG | "SATA-0-0"="none"
(default) DBG | "SATA-1-0"="/Users/zzchu/.docker/machine/machines/default/disk.vmdk"
(default) DBG | "SATA-ImageUUID-1-0"="965a90c2-0ed7-421f-be2f-da669c3fb8bb"
(default) DBG | "SATA-2-0"="none"
(default) DBG | "SATA-3-0"="none"
(default) DBG | "SATA-4-0"="none"
(default) DBG | "SATA-5-0"="none"
(default) DBG | "SATA-6-0"="none"
(default) DBG | "SATA-7-0"="none"
(default) DBG | "SATA-8-0"="none"
(default) DBG | "SATA-9-0"="none"
(default) DBG | "SATA-10-0"="none"
(default) Calling .Start
(default) DBG | "SATA-11-0"="none"
(default) DBG | "SATA-12-0"="none"
(default) DBG | "SATA-13-0"="none"
(default) DBG | "SATA-14-0"="none"
(default) DBG | "SATA-15-0"="none"
(default) DBG | "SATA-16-0"="none"
(default) DBG | "SATA-17-0"="none"
(default) DBG | "SATA-18-0"="none"
(default) DBG | "SATA-19-0"="none"
(default) DBG | "SATA-20-0"="none"
(default) DBG | "SATA-21-0"="none"
(default) DBG | "SATA-22-0"="none"
(default) DBG | "SATA-23-0"="none"
(default) DBG | "SATA-24-0"="none"
(default) DBG | "SATA-25-0"="none"
(default) DBG | "SATA-26-0"="none"
(default) DBG | "SATA-27-0"="none"
(default) DBG | "SATA-28-0"="none"
(default) DBG | "SATA-29-0"="none"
(default) DBG | nic1="none"
(default) DBG | hostonlyadapter2="vboxnet1"
(default) DBG | macaddress2="08002721B644"
(default) DBG | cableconnected2="on"
(default) DBG | nic2="hostonly"
(default) DBG | nictype2="82540EM"
(default) DBG | nicspeed2="0"
(default) DBG | nic3="none"
(default) DBG | nic4="none"
(default) DBG | nic5="none"
(default) DBG | nic6="none"
(default) DBG | nic7="none"
(default) DBG | nic8="none"
(default) DBG | hidpointing="ps2mouse"
(default) DBG | hidkeyboard="ps2kbd"
(default) DBG | uart1="off"
(default) DBG | uart2="off"
(default) DBG | uart3="off"
(default) DBG | uart4="off"
(default) DBG | lpt1="off"
(default) DBG | lpt2="off"
(default) DBG | audio="none"
(default) DBG | clipboard="disabled"
(default) DBG | draganddrop="disabled"
(default) DBG | vrde="off"
(default) DBG | usb="off"
(default) DBG | ehci="off"
(default) DBG | xhci="off"
(default) DBG | SharedFolderNameMachineMapping1="Users"
(default) DBG | SharedFolderPathMachineMapping1="/Users"
(default) DBG | vcpenabled="off"
(default) DBG | vcpscreens=0
(default) DBG | vcpfile="/Users/zzchu/.docker/machine/machines/default/default/default.webm"
(default) DBG | vcpwidth=1024
(default) DBG | vcpheight=768
(default) DBG | vcprate=512
(default) DBG | vcpfps=25
(default) DBG | GuestMemoryBalloon=0
(default) DBG | }
(default) DBG | STDERR:
(default) DBG | {
(default) DBG | }
(default) DBG | COMMAND: /usr/local/bin/VBoxManage showvminfo default --machinereadable
(default) DBG | STDOUT:
(default) DBG | {
(default) DBG | name="default"
(default) DBG | groups="/"
(default) DBG | ostype="Linux 2.6 / 3.x / 4.x (64-bit)"
(default) DBG | UUID="ddcc001e-4b38-4aa1-948d-e1d5d49e7868"
(default) DBG | CfgFile="/Users/zzchu/.docker/machine/machines/default/default/default.vbox"
(default) DBG | SnapFldr="/Users/zzchu/.docker/machine/machines/default/default/Snapshots"
(default) DBG | LogFldr="/Users/zzchu/.docker/machine/machines/default/default/Logs"
(default) DBG | hardwareuuid="ddcc001e-4b38-4aa1-948d-e1d5d49e7868"
(default) DBG | memory=2048
(default) DBG | pagefusion="off"
(default) DBG | vram=8
(default) DBG | cpuexecutioncap=100
(default) DBG | hpet="on"
(default) DBG | chipset="piix3"
(default) DBG | firmware="BIOS"
(default) DBG | cpus=1
(default) DBG | pae="on"
(default) DBG | longmode="on"
(default) DBG | cpuid-portability-level=0
(default) DBG | bootmenu="disabled"
(default) DBG | boot1="disk"
(default) DBG | boot2="none"
(default) DBG | boot3="none"
(default) DBG | boot4="none"
(default) DBG | acpi="on"
(default) DBG | ioapic="on"
(default) DBG | biossystemtimeoffset=0
(default) DBG | rtcuseutc="on"
(default) DBG | hwvirtex="on"
(default) DBG | nestedpaging="on"
(default) DBG | largepages="on"
(default) DBG | vtxvpid="on"
(default) DBG | vtxux="on"
(default) DBG | paravirtprovider="default"
(default) DBG | VMState="poweroff"
(default) DBG | VMStateChangeTime="2016-12-21T08:46:34.848000000"
(default) DBG | monitorcount=1
(default) DBG | accelerate3d="off"
(default) DBG | accelerate2dvideo="off"
(default) DBG | teleporterenabled="off"
(default) Check network to re-create if needed...
(default) DBG | teleporterport=0
(default) DBG | teleporteraddress=""
(default) DBG | teleporterpassword=""
(default) DBG | tracing-enabled="off"
(default) DBG | tracing-allow-vm-access="off"
(default) DBG | tracing-config=""
(default) DBG | autostart-enabled="off"
(default) DBG | autostart-delay=0
(default) DBG | defaultfrontend=""
(default) DBG | storagecontrollername0="SATA"
(default) DBG | storagecontrollertype0="IntelAhci"
(default) DBG | storagecontrollerinstance0="0"
(default) DBG | storagecontrollermaxportcount0="30"
(default) DBG | storagecontrollerportcount0="30"
(default) DBG | storagecontrollerbootable0="on"
(default) DBG | "SATA-0-0"="none"
(default) DBG | "SATA-1-0"="/Users/zzchu/.docker/machine/machines/default/disk.vmdk"
(default) DBG | "SATA-ImageUUID-1-0"="965a90c2-0ed7-421f-be2f-da669c3fb8bb"
(default) DBG | "SATA-2-0"="none"
(default) DBG | "SATA-3-0"="none"
(default) DBG | "SATA-4-0"="none"
(default) DBG | "SATA-5-0"="none"
(default) DBG | "SATA-6-0"="none"
(default) DBG | "SATA-7-0"="none"
(default) DBG | "SATA-8-0"="none"
(default) DBG | "SATA-9-0"="none"
(default) DBG | "SATA-10-0"="none"
(default) DBG | "SATA-11-0"="none"
(default) DBG | "SATA-12-0"="none"
(default) DBG | "SATA-13-0"="none"
(default) DBG | "SATA-14-0"="none"
(default) DBG | "SATA-15-0"="none"
(default) DBG | "SATA-16-0"="none"
(default) DBG | "SATA-17-0"="none"
(default) DBG | "SATA-18-0"="none"
(default) DBG | "SATA-19-0"="none"
(default) DBG | "SATA-20-0"="none"
(default) DBG | "SATA-21-0"="none"
(default) DBG | "SATA-22-0"="none"
(default) DBG | "SATA-23-0"="none"
(default) DBG | "SATA-24-0"="none"
(default) DBG | "SATA-25-0"="none"
(default) DBG | "SATA-26-0"="none"
(default) DBG | "SATA-27-0"="none"
(default) DBG | "SATA-28-0"="none"
(default) DBG | "SATA-29-0"="none"
(default) DBG | nic1="none"
(default) DBG | hostonlyadapter2="vboxnet1"
(default) DBG | macaddress2="08002721B644"
(default) DBG | cableconnected2="on"
(default) DBG | nic2="hostonly"
(default) DBG | nictype2="82540EM"
(default) DBG | nicspeed2="0"
(default) DBG | nic3="none"
(default) DBG | nic4="none"
(default) DBG | nic5="none"
(default) DBG | nic6="none"
(default) DBG | nic7="none"
(default) DBG | nic8="none"
(default) DBG | hidpointing="ps2mouse"
(default) DBG | hidkeyboard="ps2kbd"
(default) DBG | uart1="off"
(default) DBG | uart2="off"
(default) DBG | uart3="off"
(default) DBG | uart4="off"
(default) DBG | lpt1="off"
(default) DBG | lpt2="off"
(default) DBG | audio="none"
(default) DBG | clipboard="disabled"
(default) DBG | draganddrop="disabled"
(default) DBG | vrde="off"
(default) DBG | usb="off"
(default) DBG | ehci="off"
(default) DBG | xhci="off"
(default) DBG | SharedFolderNameMachineMapping1="Users"
(default) DBG | SharedFolderPathMachineMapping1="/Users"
(default) DBG | vcpenabled="off"
(default) DBG | vcpscreens=0
(default) DBG | vcpfile="/Users/zzchu/.docker/machine/machines/default/default/default.webm"
(default) DBG | vcpwidth=1024
(default) DBG | vcpheight=768
(default) DBG | vcprate=512
(default) DBG | vcpfps=25
(default) DBG | GuestMemoryBalloon=0
(default) DBG | }
(default) DBG | STDERR:
(default) DBG | {
(default) DBG | }
(default) DBG | COMMAND: /usr/local/bin/VBoxManage list hostonlyifs
(default) DBG | STDOUT:
(default) DBG | {
(default) DBG | Name:            vboxnet1
(default) DBG | GUID:            786f6276-656e-4174-8000-0a0027000001
(default) DBG | DHCP:            Disabled
(default) DBG | IPAddress:       192.168.99.1
(default) DBG | NetworkMask:     255.255.255.0
(default) DBG | IPV6Address:
(default) DBG | IPV6NetworkMaskPrefixLength: 0
(default) DBG | HardwareAddress: 0a:00:27:00:00:01
(default) DBG | MediumType:      Ethernet
(default) DBG | Status:          Up
(default) DBG | VBoxNetworkName: HostInterfaceNetworking-vboxnet1
(default) DBG |
(default) DBG | }
(default) DBG | STDERR:
(default) DBG | {
(default) DBG | }
(default) DBG | Searching for hostonly interface for IPv4: 192.168.99.1 and Mask: ffffff00
(default) DBG | Found: vboxnet1
(default) DBG | COMMAND: /usr/local/bin/VBoxManage list dhcpservers
(default) DBG | STDOUT:
(default) DBG | {
(default) DBG | NetworkName:    HostInterfaceNetworking-vboxnet1
(default) DBG | IP:             192.168.99.1
(default) DBG | NetworkMask:    255.255.255.0
(default) DBG | lowerIPAddress: 192.168.99.100
(default) DBG | upperIPAddress: 192.168.99.254
(default) DBG | Enabled:        Yes
(default) DBG |
(default) DBG | }
(default) DBG | STDERR:
(default) DBG | {
(default) DBG | }
(default) DBG | Removing orphan DHCP servers...
(default) DBG | COMMAND: /usr/local/bin/VBoxManage list hostonlyifs
(default) DBG | STDOUT:
(default) DBG | {
(default) DBG | Name:            vboxnet1
(default) DBG | GUID:            786f6276-656e-4174-8000-0a0027000001
(default) DBG | DHCP:            Disabled
(default) DBG | IPAddress:       192.168.99.1
(default) DBG | NetworkMask:     255.255.255.0
(default) DBG | IPV6Address:
(default) DBG | IPV6NetworkMaskPrefixLength: 0
(default) DBG | HardwareAddress: 0a:00:27:00:00:01
(default) DBG | MediumType:      Ethernet
(default) DBG | Status:          Up
(default) DBG | VBoxNetworkName: HostInterfaceNetworking-vboxnet1
(default) DBG |
(default) DBG | }
(default) DBG | STDERR:
(default) DBG | {
(default) DBG | }
(default) DBG | Adding/Modifying DHCP server "192.168.99.6"...
(default) DBG | COMMAND: /usr/local/bin/VBoxManage list dhcpservers
(default) DBG | STDOUT:
(default) DBG | {
(default) DBG | NetworkName:    HostInterfaceNetworking-vboxnet1
(default) DBG | IP:             192.168.99.1
(default) DBG | NetworkMask:    255.255.255.0
(default) DBG | lowerIPAddress: 192.168.99.100
(default) DBG | upperIPAddress: 192.168.99.254
(default) DBG | Enabled:        Yes
(default) DBG |
(default) DBG | }
(default) DBG | STDERR:
(default) DBG | {
(default) DBG | }
(default) DBG | COMMAND: /usr/local/bin/VBoxManage dhcpserver modify --netname HostInterfaceNetworking-vboxnet1 --ip 192.168.99.6 --netmask 255.255.255.0 --lowerip 192.168.99.100 --upperip 192.168.99.254 --enable
(default) DBG | STDOUT:
(default) DBG | {
(default) DBG | }
(default) DBG | STDERR:
(default) DBG | {
(default) DBG | }
(default) DBG | COMMAND: /usr/local/bin/VBoxManage modifyvm default --nic2 hostonly --nictype2 82540EM --nicpromisc2 deny --hostonlyadapter2 vboxnet1 --cableconnected2 on
(default) DBG | STDOUT:
(default) DBG | {
(default) DBG | }
(default) DBG | STDERR:
(default) DBG | {
(default) DBG | }
(default) DBG | COMMAND: /usr/local/bin/VBoxManage modifyvm default --natpf1 delete ssh
(default) DBG | STDOUT:
(default) DBG | {
(default) DBG | }
(default) DBG | STDERR:
(default) DBG | {
(default) DBG | }
(default) DBG | COMMAND: /usr/local/bin/VBoxManage modifyvm default --natpf1 ssh,tcp,127.0.0.1,50007,,22
(default) DBG | STDOUT:
(default) DBG | {
(default) DBG | }
(default) DBG | STDERR:
(default) DBG | {
(default) DBG | }
(default) DBG | COMMAND: /usr/local/bin/VBoxManage startvm default --type headless
(default) DBG | STDOUT:
(default) DBG | {
(default) DBG | Waiting for VM "default" to power on...
(default) DBG | VM "default" has been successfully started.
(default) DBG | }
(default) DBG | STDERR:
(default) DBG | {
(default) DBG | }
(default) DBG | Checking vm logs: /Users/zzchu/.docker/machine/machines/default/default/Logs/VBox.log
(default) Waiting for an IP...
(default) DBG | Getting to WaitForSSH function...
(default) DBG | Using SSH client type: external
(default) DBG | Using SSH private key: /Users/zzchu/.docker/machine/machines/default/id_rsa (-rw-------)
(default) DBG | &{[-F /dev/null -o BatchMode=yes -o PasswordAuthentication=no -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=quiet -o ConnectionAttempts=3 -o ConnectTimeout=10 -o ControlMaster=no -o ControlPath=none docker@127.0.0.1 -o IdentitiesOnly=yes -i /Users/zzchu/.docker/machine/machines/default/id_rsa -p 50007] /usr/bin/ssh <nil>}
(default) DBG | About to run SSH command:
(default) DBG | exit 0
(default) DBG | SSH cmd err, output: exit status 255:
(default) DBG | Error getting ssh command 'exit 0' : Something went wrong running an SSH command!
(default) DBG | command : exit 0
(default) DBG | err     : exit status 255
(default) DBG | output  :

>docker-machine inspect default
{
    "ConfigVersion": 3,
    "Driver": {
        "IPAddress": "192.168.99.100",
        "MachineName": "default",
        "SSHUser": "docker",
        "SSHPort": 50007,
        "SSHKeyPath": "/Users/zzchu/.docker/machine/machines/default/id_rsa",
        "StorePath": "/Users/zzchu/.docker/machine",
        "SwarmMaster": false,
        "SwarmHost": "tcp://0.0.0.0:3376",
        "SwarmDiscovery": "",
        "VBoxManager": {},
        "HostInterfaces": {},
        "CPU": 1,
        "Memory": 2048,
        "DiskSize": 204800,
        "NatNicType": "82540EM",
        "Boot2DockerURL": "",
        "Boot2DockerImportVM": "",
        "HostDNSResolver": false,
        "HostOnlyCIDR": "192.168.99.1/24",
        "HostOnlyNicType": "82540EM",
        "HostOnlyPromiscMode": "deny",
        "NoShare": false,
        "DNSProxy": false,
        "NoVTXCheck": false
    },
    "DriverName": "virtualbox",
    "HostOptions": {
        "Driver": "",
        "Memory": 0,
        "Disk": 0,
        "EngineOptions": {
            "ArbitraryFlags": [],
            "Dns": null,
            "GraphDir": "",
            "Env": [
                "HTTP_PROXY=",
                "HTTPS_PROXY=",
                "NO_PROXY="
            ],
            "Ipv6": false,
            "InsecureRegistry": [],
            "Labels": [],
            "LogLevel": "",
            "StorageDriver": "",
            "SelinuxEnabled": false,
            "TlsVerify": false,
            "RegistryMirror": [],
            "InstallURL": "https://get.docker.com"
        },
        "SwarmOptions": {
            "IsSwarm": false,
            "Address": "",
            "Discovery": "",
            "Master": false,
            "Host": "tcp://0.0.0.0:3376",
            "Image": "swarm:latest",
            "Strategy": "spread",
            "Heartbeat": 0,
            "Overcommit": 0,
            "ArbitraryFlags": [],
            "Env": null,
            "IsExperimental": false
        },
        "AuthOptions": {
            "CertDir": "/Users/zzchu/.docker/machine/certs",
            "CaCertPath": "/Users/zzchu/.docker/machine/certs/ca.pem",
            "CaPrivateKeyPath": "/Users/zzchu/.docker/machine/certs/ca-key.pem",
            "CaCertRemotePath": "",
            "ServerCertPath": "/Users/zzchu/.docker/machine/machines/default/server.pem",
            "ServerKeyPath": "/Users/zzchu/.docker/machine/machines/default/server-key.pem",
            "ClientKeyPath": "/Users/zzchu/.docker/machine/certs/key.pem",
            "ServerCertRemotePath": "",
            "ServerKeyRemotePath": "",
            "ClientCertPath": "/Users/zzchu/.docker/machine/certs/cert.pem",
            "ServerCertSANs": [],
            "StorePath": "/Users/zzchu/.docker/machine/machines/default"
        }
    },
    "Name": "default"
}

**Comment by zzchu** [comment]
regenerate-certs cannot fix the issue too.

>docker-machine regenerate-certs default
Regenerate TLS machine certs?  Warning: this is irreversible. (y/n): y
Regenerating TLS certificates
Waiting for SSH to be available...
Too many retries waiting for SSH to be available.  Last error: Maximum number of retries (60) exceeded

>docker-machine env default
Error checking TLS connection: Something went wrong running an SSH command!
command : ip addr show
err     : exit status 255
output  :

**Comment by tronicum** [comment]
try reinstalling virtualbox use one single image, remove your virtualbox configurations, emove all old configuration

dont change nat/bridge settings unless needed. it should work even if you change those settings.

**Comment by nathanleclaire** [comment]
try updating to 0.9.0-rc2, 0.7.0 is a bit dated now... and yes, messing with the network configuration gets into "warranty voiding" turf...

**Comment by alaagalal** [comment]
> docker-machine regenerate-certs

The same error 
isn't solved yet?
