### ISSUE TITLE
Cannot create GCE instance: Docker does not start on new instance.

### ISSUE THREAD

**Issue by dminkovsky** [docker/machine#3946]
```
docker-machine -D create --driver google \
    --google-project "$PROJECT_ID" \
    --google-machine-type g1-small \
    vm02
```

After a while

```
Error creating machine: Error running provisioning: Unable to verify the Docker daemon is listening: Maximum number of retries (10) exceeded
notifying bugsnag: [Error creating machine: Error running provisioning: Unable to verify the Docker daemon is listening: Maximum number of retries (10) exceeded]
```

When I SSH into the machine:

```
Jan 06 18:32:53 vm02 systemd[1]: Started docker.service.
Jan 06 18:32:53 vm02 docker[4666]: time="2017-01-06T18:32:53.958618341Z" level=info msg="libcontainerd: new containerd process, pid: 4672"
Jan 06 18:32:54 vm02 docker[4666]: time="2017-01-06T18:32:54.997067891Z" level=fatal msg="Error starting daemon: error initializing graphdriver: driver not supported"
Jan 06 18:32:54 vm02 systemd[1]: docker.service: Main process exited, code=exited, status=1/FAILURE
Jan 06 18:32:54 vm02 systemd[1]: docker.service: Unit entered failed state.
Jan 06 18:32:54 vm02 systemd[1]: docker.service: Failed with result 'exit-code'.
```

**Comment by dminkovsky** [comment]
Oh and by the way:

```
$ docker-machine -v
docker-machine version 0.8.2, build e18a919
```

and on the instance that gets created:

```
$ docker -v
Docker version 1.12.5, build 7392c3b
```

**Comment by dminkovsky** [comment]
Maybe related to #3930, Docker Machine defaults to using Ubuntu 15.10 (GNU/Linux 4.2.0-18-generic x86_64)

**Comment by dminkovsky** [comment]
Updated to 0.9.0-rc2 and remarkably it's still install 15.10. No matter what!

And when I try 

```
 --google-machine-image ubuntu-1604-xenial-v20161221
```

or some other 16-x image, I get

```
`Error in driver during machine creation: googleapi: Error 400: Invalid value for field 'resource.disks[0].initializeParams.sourceImage': 'ubuntu-1604-xenial-v20161221'. The URL 
                  is malformed., invalid`
```

**Comment by nathanleclaire** [comment]
The default images need to be bumped in GCE driver.  I'd be happy to merge such a PR

**Comment by dminkovsky** [comment]
I am sorry but I don't know anything about this codebase.

And I don't get it: I mean, as it stands, 0.8.2 and 0.9.0-rc2 are published
and advertised as working with GCE, but in reality they are broken, right?
I develop in Java and JS, and you're asking me for a PR to bump a version?
And you can't tell me how to manually specify the image I need via the
--google-imagine switch.

I know this is open source and you guys don't owe me anything, but what is
going on here?

**Comment by dminkovsky** [comment]
the point is that this project is literally for nobody except total n00bs
like me who don't feel like deploying a docker instance by hand.

So telling me I need to clone this repo, remember how to build go, find the
version in the code base , bump it, PR it -and then- here's the kicker:
wait for a release or install my local fork myself: lol




пт, 6 янв. 2017 г. в 14:45, Dmitry Minkovsky <dminkovsky@gmail.com>:

**Comment by dminkovsky** [comment]
PS. For posterity of anyone ever finds this issue, regarding the `--google-machine-image` option: https://github.com/docker/machine/issues/3904#issuecomment-264646624

**Comment by nathanleclaire** [comment]
> So telling me I need to clone this repo, remember how to build go, find the
version in the code base , bump it, PR it -and then- here's the kicker:
wait for a release or install my local fork myself: lol

You might make someone else very happy if you did.  I consider that one of the best parts of open source.  Most of the best parts of any project you enjoy are around because someone did exactly that.

**Comment by dminkovsky** [comment]
I love open source dearly. It's amazing. I've spent a lot of time on it [this past month](https://github.com/graphql-java/graphql-java).

But today I was trying to  focus making progress on my product. I was hoping to begin a deploy to GCE. I've been using AWS spot instances during development, but I wanted to use GCE in production.

And then this happened. And I asked myself: how could this be? `docker-machine create` is broken for GCE? Surely GCE must be a top-3 cloud provider and Docker Machine appears to be a strategic component of Docker's onboarding toolkit. Why isn't this a stop-the-world issue (especially if it's just a version bump)? How has it apparently persisted since November? Why is v0.9.0-rc2 26 commits ahead of master and none of them fix this issue (it's a version bump, right?) Are my assumptions about Docker Machine's strategic role in the Docker ecosystem incorrect? Is this product being neglect? Is Docker itself being neglected? Are my assumptions about GCE as a top-3 platform incorrect? I can go on and on but my point is I sincerely have no idea and it's really fascinating. 

If Docker Machine and Docker, Inc. are alive, well and capitalized, I just don't get why you asked me to PR this. It's not a feature request. It's not an issue with some esoteric feature no one ever uses (is it?). It appears to be fundamental element of this project and the fix is a version bump. None of this makes any sense at all to me.

But regardless, I do want to emphasize that I'm not being critical or demanding or anything. In reality nothing ever works and software development appears to be just making it to the finish line with what you've got.

Thank you for Docker Machine!!

Dmitry

**Comment by eyadsibai** [comment]
I am facing same issue ... if you could point me how to solve it I would be happy to help
