### ISSUE TITLE
VMware Workstation driver

### ISSUE THREAD

**Issue by zaps** [docker/machine#395]
I only care about the Windows version of Workstation, but obviously for completeness the driver would also support Linux version as well.

**Comment by Grynn** [comment]
+1 Windows version of VMWare Workstation; can't be that different from VMWare Fusion?

**Comment by sthulb** [comment]
I'd guess the CLI tool has the same API or similar.

**Comment by Grynn** [comment]
vmrun seems to have the same API

Also I think the Fusion driver picks up a MAC address from /var/db/...vmnet8.dhcpd.leases. There's no equivalent on Windows (that I could find ...)

**Comment by sthulb** [comment]
There probably is. But don't quote me on it :)

**Comment by zaps** [comment]
Also, Fusion always puts vmrun in `/Applications/VMware Fusion.app/Contents/Library/` whereas on Windows the user has the option of installing Workstation to a location other than the default of `C:\Program Files`. I'm not familiar with the Linux version but I suspect it's a similar situation.

So I guess there would have to be some kind of logic to figure out where vmrun lives. Either that or allow it to be specified as a command line option.

**Comment by sthulb** [comment]
Is there a way of querying windows for a path?

**Comment by sthulb** [comment]
TIL: You can query the windows registry to get the path of an installed app. We could use that to figure out the path of vmrun :)

**Comment by zaps** [comment]
On my own installation of Workstation (version 10 on Win7 64-bit), the registry entry is:

`HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\VMware, Inc.\VMware Workstation\InstallPath`

Sure enough, the value of that key points to the install location of the product, which includes the vmrun.exe binary.

On 32-bit Windows the registry key would be the same, minus the `Wow6432Node` part. 

I'm not familiar with Go's interaction with Windows registry, but typically for a "generic" Windows executable that needs to access the registry, it will automatically redirect to the appropriate subtree based on whether the binary doing the registry query is 32-bit or 64-bit.

Here is some more info:
https://msdn.microsoft.com/en-us/library/windows/desktop/aa384232

**Comment by zaps** [comment]
I started an extremely rough first stab at a VMware Workstation driver over at http://github.com/zaps/machine. 

Basically I just copied the Fusion driver and replaced the locations of the vmrun and vmware-diskmanager binaries with their Windows equivalents. So the paths are hardcoded and also they assume a 64-bit OS.

It's really quite awful but I figured I had to start somewhere :smile:

**Comment by sthulb** [comment]
:+1:  Great! It would be awesome to detect where Workstation is installed to.

**Comment by AnneTheAgile** [comment]
@zaps , are you planning to submit a PR back to Docker/Machine with the VMWare configs? Or are you thinking we should wait for something 'official' from VMWare? 
From what I read, to get Ubuntu 14.04 to run with Docker, we need a 64-bit machine, so hard-coding that (and erroring out if not present) might be a sane default to start with. 
AnneTheAgile

**Comment by zaps** [comment]
Sorry @AnneTheAgile for the delay, I had to put this on hold for a bit. I plan on getting back to it in the next few days. I haven't seen anything from @vmware w/r/t to an official driver for Workstation so I'll continue this work for now.  
I like your idea of assuming a 64-bit OS as a reasonable default. 
As far as a PR, as yet I've only been doing dev/testing against Workstation for Windows so I'm not sure if it would be acceptable to submit one without support for the Linux version?

**Comment by SvenDowideit** [comment]
@zaps - yes. :) So long as I have time, I'll do some testing on it for both Windows and Linux - If you don't hear from me ping me / email me

**Comment by zaps** [comment]
PR submitted: https://github.com/docker/machine/pull/1831

**Comment by dgageot** [comment]
@docker/machine-maintainers With the introduction of driver plugins, we should close this ticket, shouldn't we?

**Comment by nathanleclaire** [comment]
@dgageot Yes

**Comment by pecigonzalo** [comment]
In case anyone is still looking.
https://github.com/pecigonzalo/docker-machine-vmwareworkstation

**Comment by gtirloni** [comment]
Does this issue being closed indicate Vmware Workstation will not be supported?

I understand #1831 might not be what is desired since the introduction of driver plugins, but I'm wondering about how to use my installation of Vmware Workstation 12 Pro with Docker on Windows 10.

**Comment by nathanleclaire** [comment]
@gtirloni I'd recommend checking out @pecigonzalo's driver.

We won't be implementing it as a first-class driver in Machine.
