### ISSUE TITLE
CLI arguments to create command should be order-independent

### ISSUE THREAD

**Issue by haldean** [docker/machine#396]
Placing arguments after the name of the machine to create causes those arguments to be silently ignored. For example, this:
```
docker_machine create -d vmwarefusion --vmware-memory-size 8192 mymachine
```
Creates a VM with 8G of RAM, but this:
```
docker_machine create -d vmwarefusion mymachine --vmware-memory-size 8192
```
Creates a VM with the default amount of memory (1G), and doesn't display a warning or anything that the memory-size argument is being ignored.

**Comment by sthulb** [comment]
That'll be a bug in the cli lib

**Comment by ehazlett** [comment]
Yes, the usage is docker-machine <action> -d <driver> <driver-opts>
<machine-name>  -- anything after the name will be ignored.  Since the args
can be variable I'm not sure we can catch it -- perhaps we could mention it
better in the docs.

**Comment by ehazlett** [comment]
We state the usage in the docs and as @sthulb said, this is part of an upstream cli lib.  Closing.
