### ISSUE TITLE
[azure driver] docker-machine rm to remove the storage account as well

### ISSUE THREAD

**Issue by patuf** [docker/machine#3976]
Hello,
Since you cannot choose a storage account when creating a docker-machine in Azure, the creation of each machine also creates its own, unique storage account with one blob inside (the virtual disk of the machine in question). This is fine, until you want to remove/recreate your machines - removing a machine deletes the virtual disk, but not the storage account itself. As a result I get an empty, unused and non-reusable storage account each time I `docker-machine rm`.
Issue [#3579](https://github.com/docker/machine/issues/3579) explains why we cannot specify a storage account upon machine creation and I can agree with the reasoning. However, I see no reason for the storage account to remain at all and if possible, `docker-machine rm` should remove the storage account as well.

**Comment by kleinsasserm** [comment]
Hello @patuf!

We are facing the same situation, so I just exhumed your issue. We will try to fix this in a PR, because we are using Gitlab an therefore we are littering our resource group up with garbage storage accounts. You are not alone.

![image](https://user-images.githubusercontent.com/9364572/30175057-8183f076-93fd-11e7-9512-4a3cf254840e.png)

**Comment by kleinsasserm** [comment]
Ok, the PR which I've provided works in our environment, no more dangling storage accounts.

**Comment by patuf** [comment]
Very nice! I'll give it a try. @kleinsasserm are you planning on creating a pull request back to this repo?

**Comment by kleinsasserm** [comment]
Yes, I've already submitted a PR against this project #4249 :smile:

**Comment by patuf** [comment]
Yep, I seem to type faster than I think...
