### ISSUE TITLE
docker-machine spies on me without my consent

### ISSUE THREAD

**Issue by sneak** [docker/machine#3977]
<img width="735" alt="screen shot 2017-02-01 at 20 10 48" src="https://cloud.githubusercontent.com/assets/408977/22533244/c4f0229c-e8ba-11e6-8a8e-c73b9c3310fb.png">

I gave no authorization for docker-machine to contact third-party services with my usage data.  Sending reports like this without my opt-in advance consent makes docker-machine spyware.

Just ask your users if they're ok with your surveillance before you do it.

**Comment by nathanleclaire** [comment]
Thanks for the report -- Toolbox (most common installation method) has such a checkbox and you can also [opt out](https://docs.docker.com/machine/concepts/#/crash-reporting) yourself.

**Comment by sneak** [comment]
Doing so by default without advance consent is unethical.
