### ISSUE TITLE
docker-machine scp not working in windows 10

### ISSUE THREAD

**Issue by DongyueWang** [docker/machine#3988]
>docker-machine scp "c:/docker-stack.yml" manager:/home/docker/.
error : You must have a copy of the scp binary locally to use the scp feature

**Comment by nathanleclaire** [comment]
Do you have copy of `scp` binary?

**Comment by ekim1394** [comment]
I don't have a copy of scp binary. How can I resolve this issue?

**Comment by nathanleclaire** [comment]
You could install Docker Toolbox or http://www.mingw.org/, or git bash

**Comment by GiroudA** [comment]
cp: cannot stat 'C:\Program': No such file or directory
cp: cannot stat 'Files\Git\usr\bin\scp.exe': No such file or directory

There is a problem with the path using Git Bash
