### ISSUE TITLE
Packing an docker-machine installer

### ISSUE THREAD

**Issue by luheeslo** [docker/machine#3989]
I need create an installer for my application by packaging a docker-machine distribution. This setup executable would run the following steps:
* Installs docker machine
* Pulls distribution images from docker hub

My questions are: 
* Can I package a docker-machine installer?
* Can we make a setup executable which installs docker machine and then installs the needed images?

**Comment by nathanleclaire** [comment]
We'd prefer that you don't re-package Docker Machine. If you want to do something like this, my suggestion would be to have users install the Docker Toolbox or Docker for Mac/Windows and then have a bootstrap script your users execute.
