### ISSUE TITLE
Issues in docker while running the command "docker pull ibmcom/datapower:latest"

### ISSUE THREAD

**Issue by sumitpd2002** [docker/machine#3991]
Error : 
"Warning: failed to get default registry endpoint from daemon (An error occurred trying to connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/info: open //./pipe/docker_engine: The system cannot find the file specified.). Using system default: https://index.docker.io/v1/
An error occurred trying to connect: Post http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/images/create?fromImage=ibmcom%2Fdatapower&tag=latest: open //./pipe/docker_engine: The system cannot find the file specified."

I was able to run this command earlier. Not sure what changed. Experts please help.

**Comment by nathanleclaire** [comment]
Try following the instructions / usage hint from `docker-machine env`
