### ISSUE TITLE
no active host found

### ISSUE THREAD

**Issue by Mrfanwei** [docker/machine#3994]
my system is ubuntu16
The problem is i use the command 'sudo docker-machine create --driver virtualbox linux' to creat host on my computer  and then run 'sudo docker-machine active'  the result show no active host found

**Comment by nathanleclaire** [comment]
Please don't `sudo docker-machine`. Just `docker-machine` should be sufficient.

You need to set an "active" host based on environment variables using `eval $(docker-machine env name)`

**Comment by ppolushkin** [comment]
I got same issue when went through https://docs.docker.com/get-started/part4/#deploy-the-app-on-the-swarm-manager tutorial. I tried to run eval $(sudo docker-machine env myvm1). I see nodes but none of them are marked as active. I'm using ubuntu 16.04.

**Comment by ppolushkin** [comment]
I got same issue when went through https://docs.docker.com/get-started/part4/#deploy-the-app-on-the-swarm-manager tutorial. I tried to run eval $(sudo docker-machine env myvm1). I see nodes but none of them are marked as active. I'm using ubuntu 16.04. 

Docker version 17.12.0-ce, build c97c6d6
Docker-machine version 0.13.0

**Comment by ppolushkin** [comment]
Ok, now I see:

sudo -s
eval $(sudo docker-machine env myvm1)
docker-machine ls

works fine.  It would be not bad to mention it in tutorial.

**Comment by ppolushkin** [comment]
It is funny that I have to apply eval $(sudo docker-machine env myvm1) each time after sudo -s.
