### ISSUE TITLE
Race condition with creating CA and client certificates

### ISSUE THREAD

**Issue by rifelpet** [docker/machine#4005]
I'm using the [Gitlab CI Runner](https://docs.gitlab.com/runner/) to run my CI jobs and have it configured to provision worker instances using [Docker Machine](https://docs.gitlab.com/runner/configuration/autoscale.html). With the runner configured to ensure at least X instances are idle, when the runner starts for the first time it kicks off X `docker-machine create` commands at the same time. If the CA cert does not exist at `~/.docker/machine/certs/ca.pem`, a race condition exists in which each docker-machine process may see a lack of the CA cert, create one itself, then save it to that filename. Each process continues to use its own client cert when signing the cert for the machine it is creating, even though it may have been overwritten on the filesystem. This results in any future docker-machine commands failing to verify that machine's certificate and the only option is to remove and recreate the failed machines.

My current workaround for this is to generate the CA cert before the gitlab runner process starts by creating a "no-op" machine with `docker-machine create -d none --url localhost test && docker-machine rm -f test` but it would be great to fix this race condition.

## Repro
To reproduce this, just wipe your `~/.docker/machine/certs/` directory and run a bunch of `docker-machine create`s at the same time, an example is below. You'll see more than one of the processes outputs the "Creating CA: " and "Creating client certificate: " lines. You can adjust the code below to actually provision real machines to verify that they arent able to be reached with the last-created client certificate. 
```
package main

import (
    "os/exec"
    "fmt"
    "math/rand"
    "bytes"
    "strconv"
)

func run() {
    name := rand.Int()
    cmd := exec.Command("/usr/local/bin/docker-machine", "create", "-d", "none", "--url", "localhost", strconv.Itoa(name))
    var out bytes.Buffer
    cmd.Stdout = &out
    cmd.Stderr = &out
    err := cmd.Run()
    if err != nil {
        fmt.Println(err)
    }
    fmt.Print(out.String())
    cmd.Wait()
}

func main() {
    done := make(chan struct{})
    for i := 0; i < 10; i ++ {
		go func() {
			run()
			done <- struct{}{}
		}()
	}
	for i := 0; i < 10; i++ {
		<- done
	}
}
```

**Comment by ayufan** [comment]
Similar: https://github.com/docker/machine/issues/3634.

**Comment by rifelpet** [comment]
Confirmed duplicate, closing.

**Comment by julianalves** [comment]
@rifelpet it works! 

Thanks for sharing it, I was looking for a solution. 

Little remark for those that are not executing the `workaround` from /root/ folder. I was executing the workaround from / the certs were created at /.docker/machine/cer, but the gitlab-runner process was generating new certs in /root/.docker/machine/certs.

```
cd /root/ && \
        docker-machine create -d none --url localhost test && \
        docker-machine rm -f test

gitlab-runner register --non-interactive \ etc...
```
