### ISSUE TITLE
RedHat provisioner not checking whether Docker is installed

### ISSUE THREAD

**Issue by christianbundy** [docker/machine#4013]
We're trying to run `docker-machine create --generic` to a machine that already has Docker installed (v1.12.0), but the Machine provisioner seems to be trying to install Docker anyway here: https://github.com/docker/machine/blob/a7cdecf69c6e5a30ce6dc0ab73d80dafa3aee4f5/libmachine/provision/redhat.go#L180

Usually this would be fine, but we're behind a proxy and isolated to a single version of Docker, so running `sudo -E yum -y update -x docker-*` doesn't work for us. Is this a bug, or something that could be disabled?

Thanks for your work on this project!

**Comment by christianbundy** [comment]
Oops, looks like there was a version mismatch -- we were using a pre-a7cdecf69c6e5a30ce6dc0ab73d80dafa3aee4f5 release. Sorry!

**Comment by nathanleclaire** [comment]
thanks for following up to close 👍
