### ISSUE TITLE
scp host not running

### ISSUE THREAD

**Issue by weet234** [docker/machine#4022]
Trying to use docker-machine scp as detailed here https://docs.docker.com/engine/getstarted-voting-app/deploy-app/#copy-docker-stackyml-to-the-manager to transfer a file from the host to a machine. I have overcome all the 'host does not exist "C"' stuff but I cannot get past "host is not running". The exact command I am running is (docker-machine scp /a/docker-stack.yml manager/home/docker/.), with the file located in the A: drive. I have tried this using multiple drives and both powershell and git bash. I will reinstall docker with the edge build instead of the stable build to see if it is fixed there, but without the ability to copy files to the machines I don't see a way to move forward.

**Comment by nathanleclaire** [comment]
> I cannot get past "host is not running"

Try `docker-machine start machine-name`, the machine must not be started. Can you SSH in?

> without the ability to copy files to the machines I don't see a way to move forward.

I think you could also just connect to the machine with `docker-machine env` method and have the compose file locally on your computer

**Comment by weet234** [comment]
After a reinstall of docker using the docker toolbox this is working.
