### ISSUE TITLE
set: -g: invalid option

### ISSUE THREAD

**Issue by krainboltgreene** [docker/machine#4035]
While attempting to share my docker development environment with a friend we ran into a rather strange issue. I'm running zsh and she's running fish. All scripts I've written work on my machine, but as soon as she tries to use ones with the `eval "$(docker-machine env lacqueristas)"` line things fall apart:

```
=== Building the container(s) ===
bin/build: line 4: set: -g: invalid option
set: usage: set [--abefhkmnptuvxBCHP] [-o option] [arg ...]
bin/build: line 5: set: -g: invalid option
set: usage: set [--abefhkmnptuvxBCHP] [-o option] [arg ...]
bin/build: line 6: set: -g: invalid option
set: usage: set [--abefhkmnptuvxBCHP] [-o option] [arg ...]
bin/build: line 7: set: -g: invalid option
set: usage: set [--abefhkmnptuvxBCHP] [-o option] [arg ...]
```

We investigated and found it started here, with the eval line in this file:

``` bash
#!/usr/bin/env bash

echo "=== Building the container(s) ===" &&
eval "$(docker-machine env lacqueristas)" &&
docker-compose build $1
```

When we made the script fish compatible (`&&` -> `; and` for example) it worked fine.

Finally she tried to push the default shell and it worked! Here's what it looked like:

``` bash
#!/usr/bin/env bash

echo "=== Building the container(s) ===" &&
eval "$(docker-machine env lacqueristas --shell default)" &&
docker-compose build $1
```

Why does this happen and how can we really fix it?

**Comment by nathanleclaire** [comment]
I'm a bit confused by the behavior. `#!/usr/bin/env bash` in the script should indicate to use `bash` to interpret it and the `eval` line should work more or less the same on different computers. You're invoking these scripts using something like `./script.sh` right?

**Comment by nathanleclaire** [comment]
You might want to check that `bash` on her machine is actually `bash` and not `fish` (though that'd be quite odd, I've seen stranger things)

**Comment by krainboltgreene** [comment]
@nathanleclaire The weird thing is that even if we run this script inside a bash shell (aka typing `bash` from inside fish, seeing the bash prompt, and running `bin/build`) we still get the error.

I believe it to be somewhere in the sector of `eval` and maybe the `env` thing.

**Comment by krainboltgreene** [comment]
Oh we also tried `#!/usr/bin/env bash` and `#!/usr/bin/env sh` and `#!/bin/bash`

**Comment by matthewayers** [comment]
fwiw, I'm seeing the same thing on OS X sierra running from "bash --login" shell (w/ fish as the default)

**Comment by nathanleclaire** [comment]
Ah, yeah, I've seen that before @matthewayers - good callout, that is most likely the issue
