### ISSUE TITLE
"x509: certificate has expired or is not yet valid" when creating a new docker machine

### ISSUE THREAD

**Issue by s-m-e** [docker/machine#4046]
I am working my way through this tutorial ...
http://blog.kaggle.com/2016/02/05/how-to-get-started-with-data-science-in-containers/
... trying to set up docker (with docker-machine) on top of openSUSE Leap 42.1 Linux (Kernel 4.1.39-53.1.x86_64, VirtualBox 5.0.36-37.1.x86_64, Docker 1.12.6-30.2.x86_64)

The first step fails:
`docker-machine create -d virtualbox --virtualbox-disk-size "50000" --virtualbox-cpu-count "4" --virtualbox-memory "8092" kaggle0
`

Output looks as follows:

````
(kaggle0) 0%....10%....20%....30%....40%....50%....60%....70%....80%....90%....100%
Creating machine... 
(kaggle0) Copying /home/ernst/.docker/machine/cache/boot2docker.iso to /home/ernst/.docker/machine/machines/kaggle0/boot2docker.iso...
(kaggle0) Creating VirtualBox VM...
(kaggle0) Creating SSH key...
(kaggle0) Starting the VM...
(kaggle0) Check network to re-create if needed...
(kaggle0) Waiting for an IP...
Waiting for machine to be running, this may take a few minutes...
Detecting operating system of created instance...
Waiting for SSH to be available...
Detecting the provisioner...
Provisioning with boot2docker...
Copying certs to the local machine directory...
Copying certs to the remote machine...
Setting Docker configuration on the remote daemon...
Checking connection to Docker...
Error creating machine: Error checking the host: Error checking and/or regenerating the certs: There was an error validating certificates for host "192.168.99.100:2376": x509: certificate has expired or is not yet valid
You can attempt to regenerate them using 'docker-machine regenerate-certs [name]'.
Be advised that this will trigger a Docker daemon restart which might stop running containers.
````

Regenerating the certs works, but it does not change anything - docker-machine env will just fail with `Error checking TLS connection: Error checking and/or regenerating the certs: There was an error validating certificates for host "192.168.99.100:2376": x509: certificate has expired or is not yet valid
`

I ssh-ed into the docker machine checking the date - looks fine, set to UTC. I also configured the host to use UTC (instead of local time), so times match exactly - still no luck. 

Is this a bug or am I doing something wrong here? I'd appreciate any advice.

**Comment by s-m-e** [comment]
Ok, this is really bizarre ... 

```
ernst@e12:~/.docker/machine/certs> ls -lah
insgesamt 24K
drwx------ 2 ernst users 4,0K 25. Mär 2020  .
drwx------ 5 ernst users 4,0K 27. Mär 16:34 ..
-rw------- 1 ernst users 1,7K 25. Mär 2020  ca-key.pem
-rw-r--r-- 1 ernst users 1,1K 25. Mär 2020  ca.pem
-rw-r--r-- 1 ernst users 1,1K 25. Mär 2020  cert.pem
-rw------- 1 ernst users 1,7K 25. Mär 2020  key.pem
```

Looking into them with `openssl x509 -in somefile -text`, I get this (for both cert.pem and ca.pem):

```
        Validity
            Not Before: Mar 25 16:31:00 2020 GMT
            Not After : Mar 10 16:31:00 2023 GMT
```

The date command says something like this on the host ... 

`So 2. Apr 11:33:01 UCT 2017`

... and this on the docker machine ...

`Sun Apr  2 11:34:22 UTC 2017`

**Comment by s-m-e** [comment]
I wiped all docker, docker-machine and virtualbox configuration and started from scratch. Solved the issue. No idea what went wrong in the first place though.

**Comment by yborunov** [comment]
It looks as if your client's certificates has expired. 
From docker-machine v0.14.0 you can supply additional parameter `--client-certs` to regenerate client's certification as well.

```
docker-machine regenerate-certs --client-certs [name]
```

More info here: https://docs.docker.com/machine/reference/regenerate-certs/

**Comment by chrisfosterelli** [comment]
@yborunov Thank you! I looked everywhere and this was very unclear from the error message.

**Comment by craigotis** [comment]
For anyone encountering this and trying to figure out what happened, **for me**, I'm running a dual-boot system w/ Windows and my system clock is often off by 4 hours.

The Docker service was started around 11am "system time", and then my clocks synchronized, becoming 7am. A quick restart of Docker resolved the problem.

**Comment by Siddharth-H** [comment]
In terminal, type:
`docker-machine regenerate-certs --client-certs default`
For me, the machine name was 'default'. If you are using a different machine, then replace the default with your machine-name.

**Comment by knasim** [comment]
yuck !

**Comment by dchersey** [comment]
Suddenly started getting `docker unable to query docker version: x509: certificate has expired or is not yet valid` on ALL of my docker machine instances when doing a `docker-machine ls` and also getting it from my CI runner that uses docker-compose to deploy to my docker server. 

Tried creating a new docker-machine as a test, and was able to access it just fine.  

Tried regenerating certs several times with no change

Finally added the `--client-certs` option and it fixed everything!  Posting here because it was difficult to find this solution via googling `docker unable to query docker version: x509: certificate has expired or is not yet valid` and I want to help others find it. 

I'm still not clear why this happened to all my docker machines at the same time; they were built several months apart and in one case a year later.  And I am not sure when it will happen again ... can anybody shed light on how this works and how to check the certs?
