### ISSUE TITLE
Forward local credentials on docker-machine ssh

### ISSUE THREAD

**Issue by AkhilNairAmey** [docker/machine#4048]
Using normal ssh, I can forward my local credentials with the `-A` flag (i.e. ssh -A user@host will allow my say, local github keys to work remotely).

Can I do this using `docker-machine ssh`? If not, why is this?

Thanks,
Akhil

**Comment by nathanleclaire** [comment]
`docker-machine ssh machine -A` (additional flags / args after the `ssh` are passed to the underlying SSH command if using the "shellout" SSH, which is default)
