### ISSUE TITLE
WIP: Parallels Desktop for Mac driver

### ISSUE THREAD

**Issue by rickard-von-essen** [docker/machine#405]
I have built a driver for [Parallels Desktop for Mac](http://www.parallels.com/products/desktop/). I'll do I PR during this week, as soon as I have done some more testing.

**Comment by ehazlett** [comment]
Sounds good, thanks!

On Sun, Jan 25, 2015 at 3:25 PM, Rickard von Essen <notifications@github.com

**Comment by saratovsource** [comment]
@rickard-von-essen Sounds cool. This is very lacking to me. +1

**Comment by zfogg** [comment]
+1

**Comment by ehazlett** [comment]
Thanks.  Look forward to the PR!

**Comment by rickard-von-essen** [comment]
See #436

**Comment by ehazlett** [comment]
awesome thx -- i thought i remembered seeing a PR come in for that ;)

**Comment by ima0123** [comment]
+1
