### ISSUE TITLE
Azure Driver: Bad Request When Signing In

### ISSUE THREAD

**Issue by billpratt** [docker/machine#4062]
When I run the command below and sign into ```https://aka.ms/devicelogin``` with the Microsoft account (not AAD) I used to create my subscription, I receive a bad request. If I create an Azure Active Directory user following [these instructions](https://docs.microsoft.com/en-us/azure/virtual-machines/windows/create-aad-work-id) and login with that user, it works.

```
docker-machine create --driver azure --azure-subscription-id $SUB_ID --azure-resource-group foo foo3
```

# Login Accept
<img width="395" alt="login_accept" src="https://cloud.githubusercontent.com/assets/2847527/25191437/3db5a500-24f5-11e7-8341-969e3a4295b4.png">

# Login Error after clicking Accept
<img width="420" alt="login_badrequest" src="https://cloud.githubusercontent.com/assets/2847527/25191451/49eefeca-24f5-11e7-987a-88473d6682a4.png">

**Comment by colemickens** [comment]
@billpratt thanks so much for filing this issue.

This is one I need the verbose output from `docker-machine` for, so I can try to start guessing where the problem lies. Would you be able to repeat this scenario and attach the verbose output from `docker-machine`? (I think just include `--debug` when you repro...)

**Comment by billpratt** [comment]
@colemickens When I add --debug it doesnt show any errors. I am currently at DockerCon and showed the error to a few Microsoft and Docker engineers in the Docker Hands-on lab area. The Docker engineer believes in on the Azure side.

What's really strange is I just tried it again and it worked. I didn't do anything different. I'm hoping that means it is fixed?

**Comment by colemickens** [comment]
@billpratt Okay... but I need the output so I can see where the error is. Can you please just post it?

I wouldn't recommend relying on it just working all of the sudden. It's best if I can follow-up on these things or the fall by the way side. But I can't do that without the verbose output.

I don't doubt it's on the Azure side... but like I said, I need more information. The sub ID would be good too, although if you want to send that privately, I understand (colemick@microsoft.com).

**Comment by billpratt** [comment]
@colemickens I sent you an email with the detailed logs. I was able to successfully create a Docker VM with docker-machine using two different Microsoft accounts (non AAD). I will continue to work on this to see if I can reproduce again.

**Comment by colemickens** [comment]
From talking with @billpratt, it sounds like we may be unable to repro with @billpratt 's subscription because of changes to AAD made since the initial repro. As suspected on a succesful case, the tenant ID is discovered correctly:

```
(swarm-leader-bp111) DBG | Looking up AAD Tenant ID.  subs="[SUBID]"
(swarm-leader-bp111) DBG | Tenant ID file not found: /Users/bpratt/.docker/machine/credentials/azure/[SUBID].tenantid
(swarm-leader-bp111) DBG | Making API call to find tenant ID
(swarm-leader-bp111) DBG | Azure request  method="GET" request="https://management.azure.com/subscriptions/[SUBID]?api-version=2015-11-01"
(swarm-leader-bp111) DBG | Azure response  status="401 Unauthorized" method="GET" request="https://management.azure.com/subscriptions/[SUBID]?api-version=2015-11-01" x-ms-request-id="d2b83c4f-dae2-44a2-b228-f6643b95c31b"
(swarm-leader-bp111) DBG | Azure response  status="401 Unauthorized" method="GET" request="https://management.azure.com/subscriptions/[SUBID]?api-version=2015-11-01" x-ms-request-id="d2b83c4f-dae2-44a2-b228-f6643b95c31b"
(swarm-leader-bp111) DBG | Cached tenant ID to file: /Users/bpratt/.docker/machine/credentials/azure/[SUBID].tenantid
(swarm-leader-bp111) DBG | Found AAD Tenant ID.  tenant="[TENATID]" subs="[SUBID]"
```

In this case, TENANTID and SUBID are real, seemingly correct values. I fear when there is an MSA used, and the user hasn't created a Tenant... that they may hit this bug.

For this reason it's **important** that anyone else hitting this **please run in --debug mode and send me the logs**.

Obviously @billpratt if you repro, please send the same details along and post a note here as well for visibility.

**Comment by billpratt** [comment]
@colemickens I will be using the Azure driver during a lab at Azure Global Bootcamp this Saturday. In case one of the attendees runs into this since they will be creating new Azure accounts, what is the quickest way to create a Tenant?

/cc @jsturtevant

**Comment by colemickens** [comment]
@billpratt Good question. How did you do it? I think just going into the legacy portal and going to the AAD blade should prompt for creation of a tenant...

**Comment by billpratt** [comment]
For one account, I didn't do anything different. For the other account to other difference was that I added an AAD user.

**Comment by colemickens** [comment]
@billpratt So the account you added the AAD user to... when you try to repro now... were you using the Org account or the original MSA? Can you try with the MSA again, in case you're trying just with the org account?

**Comment by billpratt** [comment]
I am using the original MSA

**Comment by billpratt** [comment]
@colemickens can you try creating a brand new azure account with a MSA and run docker-machine create. That's how I was able to repro it previously.

**Comment by colemickens** [comment]
It didn't repro.

**Comment by billpratt** [comment]
Interesting. Maybe it's fixed? I did see another weird issue when using commands like "docker-machine ls" at times it would ask me to sign in again. I'll continue to to use the driver and report my findings with --debug turned on.
