### ISSUE TITLE
Test suite messes with real machine dir

### ISSUE THREAD

**Issue by cpuguy83** [docker/machine#409]
Running the test suite seems to remove everything in ~/.docker/machines, but also leaves a "test" machine around.

Would be nice if tests used an alternate in os.Temp() instead of the real thing :)

**Comment by ehazlett** [comment]
It is recommended to run the tests in a container but we will fix in case
you run it local.  Thanks!

**Comment by bfirsh** [comment]
I wonder if we could set `--storage-path` for the tests...

**Comment by dgageot** [comment]
Closing. This is not the case anymore
