### ISSUE TITLE
Bringing KVM upstream to docker/machine

### ISSUE THREAD

**Issue by cdrage** [docker/machine#4101]
VirtualBox is built-in.

However, KVM is not. Usually we have do download https://github.com/dhiltgen/docker-machine-kvm/ and install it in order to use docker/machine with KVM.

Is there any way that we could contribute https://github.com/dhiltgen/docker-machine-kvm/ upstream into Docker Machine so we no longer have to install the plugin?

Ping @dhiltgen @nathanleclaire

**Comment by afbjorklund** [comment]
I think that @nathanleclaire is no longer a maintainer of this project (since June 6, 95666999ac30b260c9014da674e03909e0d2743a)...

The MAINTAINERS file now says @dgageot @ehazlett @jeanlaurent, but #4018 said @shin- ?

**Comment by afbjorklund** [comment]
@cdrage:
It would be great if you had some input on https://github.com/dhiltgen/docker-machine-kvm/issues/49 (user networking) and https://github.com/dhiltgen/docker-machine-kvm/issues/2 (shared folders), when we are comparing KVM and VirtualBox ?

**Comment by afbjorklund** [comment]
I guess it is now unmaintained

**Comment by afbjorklund** [comment]
There are now _two_ KVM drivers, as well. Using two different ways to start the KVM virtual machines:

* one "kvm", which is using libvirt (needs privileges)
* one "qemu" which is using qemu (works as user)

Thanks to @SvenDowideit (and @fventuri) for https://github.com/jigtools/docker-machine-driver-qemu

* It was originally requested as https://github.com/docker/machine/issues/504 (back in 2015)
* It works better when port 2376 is not hard-coded...

**Comment by shin-** [comment]
Hi folks,

This project is still being maintained. However, we are not looking to add features to the software anymore at this point, and that includes bringing in external plugins upstream.

Thank you for your comprehension.

**Comment by afbjorklund** [comment]
@shin- : OK, sorry to hear that - but thanks for replying!

Does this policy extend to `sshfs` and `GetPort()` too ?
