### ISSUE TITLE
Error creating machine: error generating server cert with $MACHINE_TLS_CA_{KEY|CERT} set

### ISSUE THREAD

**Issue by tonyhb** [docker/machine#411]
`Host.ConfigureAuth` doesn't take into consideration `$MACHINE_TLS_CA_KEY` and `$MACHINE_TLS_CA_CERT` env variables when changing CA cert locations.

If the environment variables are set and you have valid client keys, the server is created and machine fails with the following error:

```
ERRO[0236] Error creating machine: error generating server cert: open /home/vagrant/.docker/machines/key.pem: no such file or directory
```

I think the culprit is in line 126 of host.go

The quick fix is to copy these keys into `/.docker/machines/{ca|cert}.pem`.

**Comment by tonyhb** [comment]
Yeah — `main.go` uses this:

```go
caCertPath := c.GlobalString("tls-ca-cert")
caKeyPath := c.GlobalString("tls-ca-key")
```

whereas host.go uses this:

```go
caCertPath := filepath.Join(utils.GetMachineDir(), "ca.pem")
caKeyPath := filepath.Join(utils.GetMachineDir(), "key.pem")
```

Going to replace this and test see if things still pass.

**Comment by ehazlett** [comment]
I think what `host.go` should have is a reference to the Host.CaCertPath etc.

This: https://github.com/docker/machine/blob/master/commands.go#L205 should set the Host vars and then the generation should work.  I'll work on a PR.

Thanks!

**Comment by tonyhb** [comment]
Okay cool! Yeah, I just changed main.go's caCertPath variables to be pretty global. Not a pretty fix! I'll close that PR pretty fast...!

**Comment by ehazlett** [comment]
@tonyhb could you test https://github.com/docker/machine/pull/414 ?

Thanks!

**Comment by sthulb** [comment]
LGTM.
