### ISSUE TITLE
VirtualBox driver wants admin

### ISSUE THREAD

**Issue by davesomebody** [docker/machine#415]
Hi,

I'm trying to use machine in a somewhat restrictive corporate environment.  The issue I have is creation of a VM results in VirtualBox attempting to elevate to admin during the creation process.

Any ideas how to get the create process to successfuly complete without trying to elevate to admin?  By the way, I have the same problem with boot2docker.

edit: this is on windows, just to make it obvious

Thanks!

Dave

**Comment by davesomebody** [comment]
I turned on debug and got this (lightly cleansed)

time="2015-01-27T10:50:54-08:00" level="info" msg="Creating SSH key..."

Generating public/private rsa key pair.

Your identification has been saved in C:\Users\xxxxxx\.docker\machines\dev7\id_rsa.

Your public key has been saved in C:\Users\xxxxxx\.docker\machines\dev7\id_rsa.pub.

The key fingerprint is:

2d:52:6e:15:9d:95:a1:e3:d7:a2:e6:33:80:9d:79:69 xxxx@yyyyyyyyyy

The key's randomart image is:

+--[ RSA 2048]----+

|          .. ooo |

|           .o..  |

|        . . o    |

|       o o . . . |

|      . So.o..o .|

|       o..= Eo . |

|           +o    |

|           oo    |

|            .o   |

+-----------------+

time="2015-01-27T10:50:54-08:00" level="info" msg="Creating VirtualBox VM..."

Converting from raw image file="stdin" to file="C:\Users\xxxxxx\.docker\machines\dev7\disk.vmdk"...

Creating dynamic image with size 20971520000 bytes (20000MB)...

Virtual machine 'dev7' is created and registered.

UUID: 8ac9f743-9dd8-4ac8-8567-05ebbda98082

Settings file: 'C:\Users\xxxxxxxx\.docker\machines\dev7\dev7\dev7.vbox'

0%...

Progress state: E_FAIL

VBoxManage.exe: error: Failed to create the host-only adapter

VBoxManage.exe: error: Operation canceled by the user

VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component VirtualBox, interface IVirtualBox

VBoxManage.exe: error: Context: "int __cdecl handleCreate(struct HandlerArg *,int,int *)" at line 66 of file VBoxManageHostonly.cpp

time="2015-01-27T10:51:35-08:00" level="error" msg="Error creating machine: exit status 1"

time="2015-01-27T10:51:35-08:00" level="warning" msg="You will want to check the provider to make sure the machine and associated resources were properly removed."

time="2015-01-27T10:51:35-08:00" level="fatal" msg="Error creating machine"

**Comment by ehazlett** [comment]
You must have admin privs as machine needs the host only networking in order for b2d to work.  Sorry!
