### ISSUE TITLE
Docker/Docker-Machine Paradox (Windows BSOD)

### ISSUE THREAD

**Issue by NonCreature0714** [docker/machine#4151]
Docker-CE (Windows Edition) on Windows 10 requires that Hyper-V is enabled in BIOS (and again via Control Panel). 

Virtualbox, which Docker-Machine uses, crashes per a [long-time, known bug running VirtualBox with Hyper-V enabled](https://www.virtualbox.org/ticket/16801).

This means if Docker-CE (Windows Edition for Windows 10) is running, then Docker-Machine cannot run; and vice-versa. So if one is running, the other cannot, yet they should be able to run together.

I have not tested Docker-EE.

I believe this issue is related to #4135, #4086, #4044, and #3901 

docker -v: Docker version 17.03.1-ce, build c6d412e
docker-machine -v: docker-machine.exe version 0.10.0, build 76ed2a6

I have filed a separate [Documentation Issue](https://github.com/docker/docker.github.io/issues/3694) to update the Docker Docs.

**Comment by NonCreature0714** [comment]
The best I can tell right now is that there was some conflict with running Vagrant and docker-machine in proximity on the same host. Vagrant absolutely causes BSOD because of a bug in VirtualBox. And it's possible that when I ran docker-machine afterwards there was still some unresolved issue on the host. I'm currently working to reproduce. Either way, this looks very much like an edge case.

**Comment by NonCreature0714** [comment]
I'm closing this ticket as un-reproducible. It appears it has something more to do with Vagrant.

**Comment by CamelCaseMaster** [comment]
I'm having the same issue after installing docker. Now i cannot run an emulator without getting a BSOD. A temporary fix was turning off Hyper-V from the BIOS. I'm not using Vagrant tho
