### ISSUE TITLE
Misleading "to connect" output when creating new machine with "docker-machine"

### ISSUE THREAD

**Issue by amylindburg** [docker/machine#416]
When I'm creating a new machine with docker-machine, I am advised:

`To connect: docker $(machine config my-new-machine) ps`

The name of the machine binary should print in this message (i.e., docker-machine).

**Comment by ehazlett** [comment]
@amylindburg thanks for reporting!  this has been fixed in master.  we will release with an updated RC probably tomorrow.  thanks!
