### ISSUE TITLE
docker-machine create --driver vmwarefusion vm  --- failed

### ISSUE THREAD

**Issue by xxradar** [docker/machine#4178]
Hi,

Seems that --driver vmwarefusion is setting the adapter to NAT instead of Host-Only, preventing docker-machine to initiate the SSH connection.

$ docker-machine version
docker-machine version 0.12.0, build 45c69ad

$ docker-machine create --driver vmwarefusion vm
Running pre-create checks...
Creating machine...
(vm) Copying /Users/xxradar/.docker/machine/cache/boot2docker.iso to /Users/xxradar/.docker/machine/machines/vm/boot2docker.iso...
(vm) Creating SSH key...
(vm) Creating VM...
(vm) Creating disk '/Users/xxradar/.docker/machine/machines/vm/vm.vmdk'
(vm) Virtual disk creation successful.
(vm) Starting vm...
(vm) Waiting for VM to come online...

changing the interface from NAT to Host-Only and reboot of the VM ...
docker-machine ssh vm
                        ##         .
                  ## ## ##        ==
               ## ## ## ## ##    ===
           /"""""""""""""""""\___/ ===
      ~~~ {~~ ~~~~ ~~~ ~~~~ ~~~ ~ /  ===- ~~~
           \______ o           __/
             \    \         __/
              \____\_______/
 _                 _   ____     _            _
| |__   ___   ___ | |_|___ \ __| | ___   ___| | _____ _ __
| '_ \ / _ \ / _ \| __| __) / _` |/ _ \ / __| |/ / _ \ '__|
| |_) | (_) | (_) | |_ / __/ (_| | (_) | (__|   <  __/ |
|_.__/ \___/ \___/ \__|_____\__,_|\___/ \___|_|\_\___|_|
Boot2Docker version 17.06.0-ce, build HEAD : 0672754 - Thu Jun 29 00:06:31 UTC 2017
Docker version 17.06.0-ce, build 02c1d87

**Comment by shin-** [comment]
Please update to 0.12.1 !

**Comment by xxradar** [comment]
Hi ,
tried this after upgrading to 0.12.1.

The machine gets deployed correctly, but cannot be joined via SSH.
I do think the adapter is wrongly set to NAT. see print screen.

r$ docker-machine create --driver vmwarefusion manager2
Running pre-create checks...
Creating machine...
(manager2) Copying /Users/xxradar/.docker/machine/cache/boot2docker.iso to /Users/xxradar/.docker/machine/machines/manager2/boot2docker.iso...
(manager2) Creating SSH key...
(manager2) Creating VM...
(manager2) Creating disk '/Users/xxradar/.docker/machine/machines/manager2/manager2.vmdk'
(manager2) Virtual disk creation successful.
(manager2) Starting manager2...
(manager2) Waiting for VM to come online...
Waiting for machine to be running, this may take a few minutes...
Detecting operating system of created instance...
Waiting for SSH to be available...

.... stops here.

<img width="721" alt="screenshot 2017-07-08 13 20 02" src="https://user-images.githubusercontent.com/6209321/27984841-62beb4c0-63e0-11e7-9408-b7b71bb3847b.png">

$ docker-machine version
docker-machine version 0.12.1, build c8b17e8
$
