### ISSUE TITLE
docker-machine create --driver digitalocean --digitalocean-access-token=$TOKEN  ---- failed

### ISSUE THREAD

**Issue by xxradar** [docker/machine#4179]
Installing docker via docker-machine  and digitaloceans fails .

$ docker-machine version
docker-machine version 0.12.0, build 45c69ad

$ export TOKEN=d68axdxxxxxxxxxxxx714e

$ docker-machine create --driver digitalocean --digitalocean-access-token=$TOKEN vm-do
Running pre-create checks...
Creating machine...
(vm-do) Creating SSH key...
(vm-do) Creating Digital Ocean droplet...
(vm-do) Waiting for IP address to be assigned to the Droplet...
Waiting for machine to be running, this may take a few minutes...
Detecting operating system of created instance...
Waiting for SSH to be available...
Detecting the provisioner...
Provisioning with ubuntu(systemd)...
Installing Docker...
Copying certs to the local machine directory...
Copying certs to the remote machine...
Setting Docker configuration on the remote daemon...
Error creating machine: Error running provisioning: ssh command error:
command : sudo systemctl -f start docker
err     : exit status 1
output  : Job for docker.service failed because the control process exited with error code. See "systemctl status docker.service" and "journalctl -xe" for details.

$ docker-machine ls
NAME        ACTIVE   DRIVER         STATE     URL                         SWARM   DOCKER    ERRORS
....
vm-do       -        digitalocean   Running   tcp://138.197.28.63:2376            Unknown   Unable to query docker version: Cannot connect to the docker engine endpoint

**Comment by febincloudyuga** [comment]
I am facing the same issue.
#4184

**Comment by shin-** [comment]
Please update to 0.12.1 !
