### ISSUE TITLE
Last version of Docker Machine in Docker for Mac

### ISSUE THREAD

**Issue by lucj** [docker/machine#4181]
I run the latest version of Docker for Mac (17.06.0-ce-mac17 (18432) and still have Machine 0.12. Is it possible to update to 0.12.1 as it seems to fix https://github.com/docker/machine/issues/4179 ?

**Comment by debianw** [comment]
Do this:

```
curl -L https://github.com/docker/machine/releases/download/v0.12.1/docker-machine-`uname -s`-`uname -m` >/usr/local/bin/docker-machine && \
  chmod +x /usr/local/bin/docker-machine
```

**Comment by lucj** [comment]
I finally used brew.

```
brew install docker-machine
alias dm=/usr/local/Cellar/docker-machine/0.12.1/bin/docker-machine
```

**Comment by davidbonachera** [comment]
Wow, it was difficult to find this issue, as of today, when you download the last Docker for Mac you still don't have the docker-machine 0.12.1 

Thanks for the answer :)
