### ISSUE TITLE
Error creating machine: Error running provisioning: Unable to verify the Docker daemon is listening: Maximum number of retries (10) exceeded

### ISSUE THREAD

**Issue by Devendrabhat** [docker/machine#4183]
I ran the following command 
`docker-machine create -d digitalocean --digitalocean-access-token=secret staging`
there is a error coming in the end.
Running pre-create checks...
Creating machine...
(staging) Creating SSH key...
(staging) Creating Digital Ocean droplet...
(staging) Waiting for IP address to be assigned to the Droplet...
Waiting for machine to be running, this may take a few minutes...
Detecting operating system of created instance...
Waiting for SSH to be available...
Detecting the provisioner...
Provisioning with ubuntu(systemd)...
Installing Docker...
Copying certs to the local machine directory...
Copying certs to the remote machine...
Setting Docker configuration on the remote daemon...
Error creating machine: Error running provisioning: Unable to verify the Docker daemon is listening: Maximum number of retries (10) exceeded

**Comment by shin-** [comment]
You probably need to upgrade `docker-machine` to 0.12.1 !
