### ISSUE TITLE
generic driver breaks node with docker already installed

### ISSUE THREAD

**Issue by princemaple** [docker/machine#4190]
docker-machine version 0.12.1

Since docker-machine wasn't able to create machines, I was trying to create a node first, then add it to docker-machine with generic driver. docker-machine, however, simply breaks it. It does configures the ssh related stuff correctly, that I can ssh into the node with docker-machine. Only that docker cannot be started on that node anymore.

VPS provider: scaleway

**Comment by brandontamm** [comment]
I've had this issue. When you try to create a new docker-machine, you'll have issues with installation when docker attempts to contact docker-daemon, correct?

**Comment by brandontamm** [comment]
docker-machine create is having issues in general - fails upon creation, leaving you able to ssh to server ... however, users cannot upgrade or provision server and there are issues on the actual server itself. For instance, when attempting to resize a digital ocean machine, the re-size fails and Digitalocean support is blaming the docker-machine create command that left something in a broken state.

**Comment by princemaple** [comment]
Yes. It's been pretty bad.

**Comment by petk** [comment]
For the generic driver adding the `--engine-storage-driver=overlay2` option solves this issue in my case as noted in #4166
