### ISSUE TITLE
Timeout during docker-machine create with Ubuntu 16.04

### ISSUE THREAD

**Issue by diehl** [docker/machine#4191]
When attempting to create a VM on EC2 with an Ubuntu 16.04 AMI `ami-835b4efa`, I see the following:
```
Waiting for machine to be running, this may take a few minutes...
Detecting operating system of created instance...
Waiting for SSH to be available...
Detecting the provisioner...
Provisioning with ubuntu(systemd)...
Installing Docker...
Copying certs to the local machine directory...
Copying certs to the remote machine...
Setting Docker configuration on the remote daemon...
Error creating machine: Error running provisioning: Unable to verify the Docker daemon is listening: Maximum number of retries (10) exceeded
```
This issue goes away if I create a VM using Ubuntu 14.04 with AMI `ami-fc4f5e85`. I've seen this in the past and thought it was just a fluke. It's happened enough times today repeatedly that I'm thinking there's some issue here. Any thoughts on why the above fails with Ubuntu 16.04? I can use 14.04 for now but would like to upgrade in the not too distant future and still use Docker Machine for managing my VMs. 

I downloaded the latest version of Docker Toolbox for OSX today to take that off the table as a possible issue.

**Comment by shin-** [comment]
@diehl Are you able to provision if you provide `--engine-storage-driver=overlay2` in the `create` command?
