### ISSUE TITLE
Machine v 0.12+ vmwarefusion driver fails on create due to certificate error

### ISSUE THREAD

**Issue by waldnzwrld** [docker/machine#4192]
In docker-machine v 0.12+ when creating a vm using the vmwarefusion driver the installation hangs while trying to validate SSH. In debug mode, the error is `x509: certificate signed by unknown authority`

docker-machine version 0.11.0 works without issue. 

Expected behavior: 

`docker-machine create -d vmwarefusion MyAwesomeMachine` should create a docker vm without any issues

Actual behavior:

`docker-machine create -d vmwarefusion MyAwesomeMachine` fails to complete. Afterward SSH commands work, however the machine will not be available in a browser . 

Environment:
MacOs 10.12.5
VMWare Fusion 8.5.8
docker 17.06.0-ce
docker-compose 1.14.0

**Comment by shin-** [comment]
@waldnzwrld We made a few fixed to VMWare drivers in 0.12.2 - can you check that this version works for you?

**Comment by waldnzwrld** [comment]
@shin- Thanks, version 12.2 fixes the issues I had noticed.
