### ISSUE TITLE
Your Release Notes Seem to Have Error...

### ISSUE THREAD

**Issue by brandontamm** [docker/machine#4196]
You state "If you're a Mac or Windows user, the Docker Toolbox will install Docker Machine v0.12.2 for you, alongside the latest versions of the Docker Engine, Compose and Kitematic."

In fact, when I downloaded docker toolbox from the link you provided, the command: 
$ docker-machine -v
docker-machine version 0.11.0, build 5b27455

I'm trying to use the latest version so it's the only reason I caught it :)

I haven't been able to use the digital ocean driver to create a machine with the high-cpu droplets, but the regular droplet and high-memory droplet work. I am referring to the "droplet-size" environment variable. Is there coding that is needed to include this (the high-cpu is a new feature)?

**Comment by shin-** [comment]
Yep, we'll release an updated toolbox soon.
