### ISSUE TITLE
Feature request: TLS common name(s) as an option to docker-machine regenerate-certs 

### ISSUE THREAD

**Issue by basz** [docker/machine#4203]
Hi when trying to follow a tutorial to deploy to a swarm from ci I ran into the following issue. An additional option to regenerate-certs would probably solve it.

setup:

- working swarm to which I can `docker-machine ssh node-1` from my laptop.
- gitlab runs builds and tries to do the following

```
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_IMAGE" "$CI_REGISTRY"
    - docker stack deploy --with-registry-auth --compose-file=docker-stack-compose.yml ${CI_PROJECT_NAMESPACE}-${CI_PROJECT_NAME}-${SERVICE_NAME}
```

- certificates copied from laptop `cat ~/.docker/machine/machines/node-1/*.pem` to secrets in gitlab 

This results in an (expected) error 

```
error during connect: Get https://docker-swarm.bushbaby.nl:2376/v1.30/version: x509: certificate is valid for localhost, not docker-swarm.bushbaby.nl
```

I was able to solve this error by using the ip address of the swarm manager, but (now comes my request) wouldn't it be nice (better) if `docker-machine regenerate-certs` had an option to specify some common names to be backed into the generated certificates?

Then one would not have to go and generate certificates with common names.

thanks

**Comment by shin-** [comment]
Thank you for your suggestion. Unfortunately, we are not planning to add any more features to docker-machine at this point.
