### ISSUE TITLE
Can not download docker-machine-Linux-x86_64 for any release

### ISSUE THREAD

**Issue by doudoufei1980** [docker/machine#4205]
Today I tried to download docker-machine with curl -L https://github.com/docker/machine/releases/download/v0.12.0/docker-machine-Linux-x86_64 and directly download download file by download link, but unfortunately failed. I am not sure if source file is bad or connection have some problems.

**Comment by shin-** [comment]
works for me. Also you should download 0.12.2.

**Comment by doudoufei1980** [comment]
Thanks shin. it works now.
