### ISSUE TITLE
Feature request: provide easier way to SSH with sudo

### ISSUE THREAD

**Issue by marius311** [docker/machine#4211]
Its often useful to SSH into the docker-machine and forward some ports back to localhost. For example, if I'm running a container with a webserver and I want to forward port 80, I might want to do something like,

```
docker-machine ssh -L 80:localhost:80
```

This however fails because 80 is a privileged port so I need admin privileges. However just running the above command with `sudo` doesn't work (at least with Virtualbox) because I get a `machine doesn't exist` error (I think related to problems calling `VBoxManage` from a root account) .

Instead, I've found the following workaround,

```
sudo ssh docker@$(docker-machine ip) -L 80:localhost:80
```

and then manually typing in the `tcuser` password. Of course, it'd be nicer if I didn't have to do this. Would it be possible to have something like

```
docker-machine ssh --sudo -L 80:localhost:80
```

or maybe a generic option that changes the user account from which we SSH? Thanks. 

For reference, I'm using: 
```
docker-machine version 0.8.2, build e18a919
Docker version 17.05.0-ce-rc3, build 90d35ab
VBox 5.1.0r108711
Ubuntu 16.04
```

**Comment by shin-** [comment]
Thank you for your suggestion. Unfortunately, we are not planning to add any more features to docker-machine at this point.
