### ISSUE TITLE
Clarification on "certificate signed by unknown authority"

### ISSUE THREAD

**Issue by jeeftor** [docker/machine#4218]
I'm trying to use docker machine behind my corporate firewall with AWS and i'm running into a  `x509: certificate signed by unknown` error

> Error with pre-create check: "RequestError: send request failed
> caused by: Post https://ec2.us-east-1.amazonaws.com/: x509: certificate signed by unknown authority"

I'm running:
*  OSX
* docker-machine version 0.12.0, build 45c69ad
* Docker version 17.06.0-ce, build 02c1d87

And the command line is:

```
docker-machine create --driver amazonec2 \
        --amazonec2-instance-type t2.small \
        --amazonec2-ssh-keypath ./ssh/frn_rsa \
        --amazonec2-vpc-id  vpc-xxxxxxx \
        test-instance1
```

Any guidance how to diagnose whats going on?  I do know my system doing SSL inspection and re-signing stuff - but i cant tell if thats the issue or if the amazon cert is the issue.  Also i do trust our self-signed cert so i think that shouldn't be a problem.

Any help appreciated.
Thanks!

**Comment by shin-** [comment]
See #4192 - You should upgrade `docker-machine` to 0.12.2
