### ISSUE TITLE
Allow docker-machine to build on Solaris/illumos

### ISSUE THREAD

**Issue by ptribble** [docker/machine#4221]
Docker-machine doesn't currently build on Solaris or illumos. It should be relatively easy to enable it to do so.

The following is (a) a list of changes I had to make to do this, so others don't have to start from scratch, and (b) a query as to how best integrate this.

First, the required changes:

1. Add golang.org/x/sys/unix, needed by vendor/golang.org/x/crypto/ssh/terminal/util_solaris.go and by (a modified) vendor/github.com/bugsnag/panicwrap/monitor.go

2. Replace docker/docker/pkg/term by moby/moby/pkg/term, which is newer and has Solaris support

3. Copy drivers/virtualbox/virtualbox_freebsd.go to drivers/virtualbox/virtualbox_solaris.go (this will allow machine to build, although it still can't actually manage VirtualBox locally on Solaris because a couple of the command line flags that machine uses aren't exposed in the VirtualBox CLI on Solaris)

4. In vendor/github.com/bugsnag/panicwrap/panicwrap.go and vendor/github.com/bugsnag/panicwrap/monitor.go, remove the osext import and replace osext.Executable by os.Executable (requires Go 1.8).

5. In vendor/github.com/bugsnag/panicwrap/monitor.go, import golang.org/x/sys/unix and replace dup2 with unix.Dup2

6. Copy libmachine/crashreport/os_freebsd.go to libmachine/crashreport/os_solaris.go, probably modifiying uname -r with uname -rv to disammbiguate the various Solaris/illumos distributions.

Not all that much here is actually in machine's own code, some requires patching upstream code or updating dependencies, and it does force a dependency on Go 1.8, so advice on how to fold these changes back would be appreciated.

**Comment by shin-** [comment]
Thank you for the detailed write-up. Unfortunately, we are not looking to add any new features to `docker-machine` at this point.
