### ISSUE TITLE
17.06 on OS X: "docker-machine create" with VMware Fusion failed. (x509: certificate signed by unknown authority)

### ISSUE THREAD

**Issue by xinfengliu** [docker/machine#4222]
Brand new installation of Docker for Mac.
OS X 10.12.6
Docker Version 17.06.0-ce-mac19 (18663)
driver: VMware Fusion Professional Version 8.5.8 (5824040)

$ docker-machine create -d vmwarefusion node1
...
Detecting operating system of created instance...
Waiting for SSH to be available...
Error creating machine: Error detecting OS: Too many retries waiting for SSH to be available.  Last error: Maximum number of retries (60) exceeded

$ docker-machine ls
NAME          ACTIVE   DRIVER         STATE     URL                          SWARM   DOCKER    ERRORS
node1         -        vmwarefusion   Running   tcp://192.168.105.128:2376           Unknown   Unable to query docker version: Get https://192.168.105.128:2376/v1.15/version: **x509: certificate signed by unknown authority**

Do I need do any extra configuration to make it work?

(Just tried with VirtualBox, "docker-machine create" succeeded with no error).

**Comment by shin-** [comment]
docker-machine --version ?

**Comment by xinfengliu** [comment]
docker-machine version 0.12.0, build 45c69ad

**Comment by shin-** [comment]
Should be fixed in 0.12.2, please upgrade!
