### ISSUE TITLE
Add monitoring to the Digital Ocean driver

### ISSUE THREAD

**Issue by TheYorkshireDev** [docker/machine#4227]
Digital Ocean now have a monitoring feature that docker-machine does not currently support.

I propose we add this support therefore allowing users of docker-machine to turn on the monitoring flag when provisioning a droplet. The monitoring option is triggered in the same way private networking is, its a boolean passed on the API.

**Comment by shin-** [comment]
Thank you for your suggestion. Unfortunately, we are not planning to add any more features to docker-machine at this point.

**Comment by TheYorkshireDev** [comment]
@shin- I was planning on adding this in myself and asking for someone to just review the PR.

I want to add this functionality in because Rancher uses docker-machine to provision digital ocean droplets and their UI and CLI does not allow for turning on monitoring due to this limitation.

Can this be re-opened?
