### ISSUE TITLE
open stack: do not delete key-pair on rm

### ISSUE THREAD

**Issue by FlorianLudwig** [docker/machine#4239]
When creating a machine it is possible to either provide no ssh-key in which case a key is automatically generated for each machine and registered with open stack or you can provide `--openstack-keypair-name` in which case this keypair is used.

When removing a machine the corresponding key-pair is deleted as well.  This is useful for the first case but when using an existing key-pair it should not automatically delete the key since docker-machine did not create it and doesn't conceptually own it.

**Comment by catalyst-joe-guo** [comment]
Yes, I had the same issue.
Maybe add a boolean option like 'auto-delete-key'.

**Comment by davidarcher** [comment]
There's a pull request out there for it waiting for feedback:
https://github.com/docker/machine/pull/3969
