### ISSUE TITLE
docker-machine - fails on sudo systemctl -f start docker

### ISSUE THREAD

**Issue by GuyJackson** [docker/machine#4248]
Currently unable to provision a remote machine with docker-machine.

 I have `docker-machine version 0.12.2, build 9371605` installed on my Ubuntu Laptop `Ubuntu 16.04.3 LTS`. The remote host I would like to provision is `Ubuntu 16.04.3 LTS` (VMware Virtual Platform).

Running the following command:

```
docker-machine \
    create \
    <testname> \
    --driver generic  \
    --generic-ip-address <ip address> \
    --generic-ssh-user <username>
```

Results in this error:

> About to run SSH command:
sudo systemctl -f start docker
SSH cmd err, output: exit status 255: 
Error creating machine: Error running provisioning: ssh command error:
command : **sudo systemctl -f start docker**
err     : exit status 255
output  : 
notifying bugsnag: [Error creating machine: Error running provisioning: ssh command error:
command : sudo systemctl -f start docker
err     : exit status 255
output  : ]

Strangely, when I run `sudo systemctl -f start docker` on the server itself, docker starts successfully.

I've not been able to track down any obvious errors in log files as yet.

Thanks,

**Comment by msjyoo** [comment]
I also came across this bug today, docker-machine version 0.15.0, build b48dc28d

**Comment by msjyoo** [comment]
Could possibly be related to `Failed to execute operation: Interactive authentication required.` when I run `ssh u@ip systemctl daemon-reload`?
