### ISSUE TITLE
This computer doesn't have VT-X/AMD-v enabled. Enabling it in the BIOS is mandatory

### ISSUE THREAD

**Issue by dagonpal** [docker/machine#4271]
Helo;

I ´m starting with Docker, and I´m following this explample (previously I did the parts 1,2 and 3 without problem):

[](https://docs.docker.com/get-started/part4/#create-a-cluster)

When I run:

`docker-machine create --driver virtualbox myvm1`

I recive:

> [root@localhost tmp]# docker-machine create --driver virtualbox myvm10
> Running pre-create checks...
> Error with pre-create check: "This computer doesn't have VT-X/AMD-v enabled. Enabling it in the BIOS is mandatory"

This is my environment:

[root@localhost tmp]#  docker --version
Docker version 17.10.0-ce-rc1, build d866876

[root@localhost tmp]# docker-machine --version
docker-machine version 0.12.2, build 9371605
[root@localhost tmp]# vboxmanage --version
5.1.28r117968

[root@localhost tmp]# cat /etc/centos-release
CentOS Linux release 7.4.1708 (Core)

This server is running on host with windows 2012 and Hyper-v

Windows Server 2012-R2 (Microsoft Windows [Version 6.3.9600])
Hyper-v Product version: 6.3.6900.18623

**Comment by dagonpal** [comment]
Can someone help me?

**Comment by matt9ucci** [comment]
See this blog post: ["Nested Virtualization"](https://blogs.technet.microsoft.com/virtualization/2015/10/13/windows-insider-preview-nested-virtualization/)

> Hyper-V relies on hardware virtualization support (e.g. **Intel VT-x** and **AMD-V**) to run virtual machines. Typically, once Hyper-V is installed, the hypervisor **hides this capability from guest virtual machines**, preventing guests virtual machines from installing Hyper-V (and many other hypervisors, for that matter).

> Both hypervisors need to be the latest versions of Hyper-V. **Other hypervisors will not work.** Windows Server **2012R2**, or even builds prior to 10565 **will not work**.

**Comment by dagonpal** [comment]
Thank you very much @matt9ucci, in this case I think that my only option is install docker on a physical server over Linux.
Best regards.

**Comment by thaJeztah** [comment]
Looks like the question is answered

**Comment by gmallir** [comment]
I was facing this error, I have VM ware workstation installed and a CENTOS running on it, when i try to create virtualbox setup as part of using docker-machine, i get error

Error with pre-create check: "This computer doesn't have VT-X/AMD-v enabled. Enabling it in the BIOS is mandatory"

FIX: VM-->Settings--->Processor-->Enable "Virtualize Intel VT-x/EPT "...

This has fixed the issue

**Comment by AnirudhMohanKumar** [comment]
my fix...
![6116 hvw8a](https://user-images.githubusercontent.com/25389332/36444114-a79ee434-16a0-11e8-81a7-2e3ef6ad9c03.jpg)

hope this helps!

**Comment by cg1990** [comment]
Thank you very much @AnirudhMohanKumar! This works fine. Perfect

**Comment by nirvikk** [comment]
`docker-machine create default --virtualbox-no-vtx-check` this might help

**Comment by tigerneil** [comment]
thanks. it worked for me. @nirvikk

**Comment by Izalan** [comment]
I have virtualization enabled but still get that error trying to create docker
Tried docker-machine create default --virtualbox-no-vtx-check  - it created a machine but failed to start with " Raw-mode is unavailable courtesy of Hyper-V" error. Any ideas how to move forward?

**Comment by xhchrn** [comment]
@Izalan Try this: https://stackoverflow.com/a/50403200/8585276

**Comment by jefflancaster** [comment]
Thanks @nirvikk !

**Comment by athanasiosem** [comment]
Running **bcdedit /set hypervisorlaunchtype off**
and **disabling Core Isolation on Windows 10 settings** worked for me
and let me install **Docker toolbox on Windows 10 Home**.

**Comment by zestllankesh** [comment]
What about the aws Windows machine?

I am facing this issue on aws Windows ec2 2012 R2.

I installed Docker Toolbox for Windows on aws ec2 Windows 2012 R2 instance (Instance type is t2.medium)

But I am not able to start any docker machines

**Comment by matt9ucci** [comment]
@zestllankesh The original question of this issue is about Windows Server 2012-R2 environment. That should be the same situation as yours. Please see my [answer](https://github.com/docker/machine/issues/4271#issuecomment-335153094).

**Comment by zestllankesh** [comment]
> @zestllankesh The original question of this issue is about Windows Server 2012-R2 environment. That should be the same situation as yours. Please see my [answer](https://github.com/docker/machine/issues/4271#issuecomment-335153094).

Understood. But my problem is not same as mentioned here.

I have **Windows 2012 R2 ec2** running in **AWS enviroment**. I have no control over hardware.
But I want to run docker on top of the Windows 2012 R2 ec2 instance.

**Comment by matt9ucci** [comment]
@zestllankesh Currently, nested virturalization is available only in bare metal instances. Please be careful they are much more expensive than t2.medium  :sweat_smile:
https://www.reddit.com/r/aws/comments/993zbz/nested_virtualization_within_ec2_need_advice/

**Comment by zestllankesh** [comment]
> @zestllankesh Currently, nested virturalization is available only in bare metal instances. Please be careful they are much more expensive than t2.medium 😅
> https://www.reddit.com/r/aws/comments/993zbz/nested_virtualization_within_ec2_need_advice/

Hehe. Guess I'm screwed then ;)
Thank You for taking time for replying

Cheers :)

**Comment by payam1985** [comment]
> `docker-machine create default --virtualbox-no-vtx-check` this might help

tanks so much, i have same issue so with this line resolved

**Comment by RajatKD** [comment]
@nirvikk thanks, your solution worked for me in AWS EC2 instance

**Comment by MrScors** [comment]
> @Izalan Try this: https://stackoverflow.com/a/50403200/8585276

have the same problem but even this didn't help

**Comment by ginaocto** [comment]
> `docker-machine create default --virtualbox-no-vtx-check` this might help

Thanks a lot, ur solution worked for me. when 2 days i really confuse to solve this error and u giving me this solution. i really happy for that.   TERIMAKASIH @nirvikk

**Comment by bhupenkd** [comment]
> > `docker-machine create default --virtualbox-no-vtx-check` this might help
> 
> Thanks a lot, ur solution worked for me. when 2 days i really confuse to solve this error and u giving me this solution. i really happy for that. TERIMAKASIH @nirvikk

This worked for me

**Comment by thequy** [comment]
> I have virtualization enabled but still get that error trying to create docker
> Tried docker-machine create default --virtualbox-no-vtx-check - it created a machine but failed to start with " Raw-mode is unavailable courtesy of Hyper-V" error. Any ideas how to move forward?
> I am on Win 10 if that matters



> `docker-machine create default --virtualbox-no-vtx-check` this might help

This worked for me too, thanks a lot!

**Comment by josepacelli** [comment]
In my Windows 10 only worked when i disabled the Windows Defender Core Virtualization.

![image](https://user-images.githubusercontent.com/19782727/77233404-eaa92f00-6b85-11ea-9169-b4fb9e1050d8.png)

![image](https://user-images.githubusercontent.com/19782727/77233411-f4329700-6b85-11ea-994c-fdbefa41c749.png)

**Comment by sharehe** [comment]
> `docker-machine create default --virtualbox-no-vtx-check` this might help

Solve my problem

**Comment by raisboualem25** [comment]
> > `docker-machine create default --virtualbox-no-vtx-check` this might help
> 
> tanks so much, i have same issue so with this line resolved

**Comment by satyam-github** [comment]
> `docker-machine create default --virtualbox-no-vtx-check` this might help

@nirvikk . Thanks ! Your solution worked .

**Comment by omeryounus** [comment]
Yeah it did work, I need to 
'''creatr docker-machine create default --virtualbox-no-vtx-check '''

with ELK any idea?

**Comment by omeryounus** [comment]
This is how I made it work but still waiting for IP 

```
ubuntu@ip-172-31-11-0:~/elk$ docker-machine create elk --virtualbox-no-vtx-check
Running pre-create checks...
Creating machine...
(elk) Copying /home/ubuntu/.docker/machine/cache/boot2docker.iso to /home/ubuntu/.docker/machine/machines/elk/boot2docker.iso...
(elk) Creating VirtualBox VM...
(elk) Creating SSH key...
(elk) Starting the VM...
(elk) Check network to re-create if needed...
(elk) Waiting for an IP...
```
