### ISSUE TITLE
Use generic driver with debian wheezy

### ISSUE THREAD

**Issue by lukasgarcya** [docker/machine#4273]
Running pre-create checks...                                                                                                                                          
Creating machine...                                                                                                                                                   
(suapdev) Importing SSH key...                                                                                                                                        
Waiting for machine to be running, this may take a few minutes...                                                                                                     
Detecting operating system of created instance...                                                                                                                     
Waiting for SSH to be available...                                                                                                                                    
Detecting the provisioner...                                                                                                                                          
Provisioning with debian...                                                                                                                                           
Copying certs to the local machine directory...                                                                                                                       
Error creating machine: Error running provisioning: ssh command error:                                                                                                
command : sudo systemctl -f stop docker                                                                                                                               
err     : exit status 1                                                                                                                                               
output  : sudo: systemctl: command not found

**Comment by shin-** [comment]
You'll need to have systemd installed.
