### ISSUE TITLE
Auto log rotation

### ISSUE THREAD

**Issue by nmiculinic** [docker/machine#4277]
Can you add ```--log-opt max-size=10m``` or other sane amounts in the systemd service starting docker daemon? Right now I've found 3GB nginx docker container log file I forgot about until it started exhibiting issues.

This is referring to auto docker installation using create option

**Comment by shin-** [comment]
You can use `--engine-opt` at create time to set it yourself, i.e `docker-machine create --driver generic --engine-opt log-opt="max-size=10m" ...`
