### ISSUE TITLE
Docker won't start raspberry pi

### ISSUE THREAD

**Issue by Tombosy** [docker/machine#4298]
Hello,
I use docker for one mounth without problem, but today I start my raspberry pi and my dotnet and mqtt container will not run.
Run : docker run -d -p 1883:1883 -p 9001:9001 ericmick/armhf-mosquitto:latest

Result : Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?

So i test : sudo systemctl start docker.service but the result is : 
Job for docker.service failed because the control process exited with error code.
See "systemctl status docker.service" and "journalctl -xe" for details.

status of docker.service is : 

`● docker.service - Docker Application Container Engine
   Loaded: loaded (/lib/systemd/system/docker.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Mon 2017-10-30 14:41:58 CET; 19s ago
     Docs: https://docs.docker.com
  Process: 4032 ExecStart=/usr/bin/dockerd -H fd:// (code=exited, status=2)
 Main PID: 4032 (code=exited, status=2)
      CPU: 1.838s

oct. 30 14:41:59 raspberrypi dockerd[4032]: r8      0x4676a9ac
oct. 30 14:41:59 raspberrypi dockerd[4032]: r9      0x1000
oct. 30 14:41:59 raspberrypi dockerd[4032]: r10     0x569cc5a0
oct. 30 14:41:59 raspberrypi dockerd[4032]: fp      0x1c21330
oct. 30 14:41:59 raspberrypi dockerd[4032]: ip      0x20
oct. 30 14:41:59 raspberrypi dockerd[4032]: sp      0x4676a898
oct. 30 14:41:59 raspberrypi dockerd[4032]: lr      0xffffffff
oct. 30 14:41:59 raspberrypi dockerd[4032]: pc      0x76cda45c
oct. 30 14:41:59 raspberrypi dockerd[4032]: cpsr    0x10
oct. 30 14:41:59 raspberrypi dockerd[4032]: fault   0x0`

My full journalctl about docker is : 
[https://pastebin.com/cC3sMNfa](url)

Docker version : 
Client:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:30:54 2017
 OS/Arch:      linux/arm
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?

What I need to do ? I can't backup my images i really need it and then maybe reinstall docker or find a solution ...

thanks

**Comment by shin-** [comment]
Sorry, wrong repo. I'd create an issue on https://github.com/docker/for-linux or maybe make a thread on the forums: https://forums.docker.com
