### ISSUE TITLE
'Bad certificate' after stopping and starting vmwarefusion machine

### ISSUE THREAD

**Issue by brianatirise** [docker/machine#430]
VMWare Fusion machines seem not to be functional after stopping and re-starting them.

As of commit 7d6fd1f (midday January 28, 2015) with Docker 1.4.1 and a fresh boot2docker.iso, if I do the following:

docker-machine create -d vmwarefusion foo
docker $(docker-machine config foo) ps     # SUCCESS
docker-machine stop
docker-machine start
docker $(docker-machine config foo) ps     # FAILURE

the second attempt to do 'docker ps' fails with FATA[0000] An error occurred trying to connect: Get https://172.16.65.190:2376/v1.16/containers/json: remote error: bad certificate. Same is true if I replace the stop/start with restart. 'docker-machine ssh' also fails in that I end up being prompted to authenticate via password.

This does not happen for VirtualBox machines. I haven't had trouble stopping/starting them.

If I 'docker-machine rm foo' and start over, I get the same behavior (works fine until I stop the machine).
This isn't too terrible, but it is a hassle in that any of the cached Docker image files must be re-fetched.

**Comment by ehazlett** [comment]
This is a known issue.  Support for detecting the virtual disk in order to store the b2d configs needs to be added.

**Comment by frapposelli** [comment]
I'm putting together a workaround for this short term as the long term solution will take some time to develop.

**Comment by ehazlett** [comment]
@frapposelli awesome!! thanks!

**Comment by ryanwalls** [comment]
I have the same/similar problem with virtualbox.  Start/stop an engine ends up with this error when I try to connect to it again:

```
FATA[0000] An error occurred trying to connect: Get https://192.168.99.100:2376/v1.16/containers/json: x509: certificate is valid for 192.168.99.105, not 192.168.99.100
```

**Comment by ehazlett** [comment]
Yes we are working on this.  There should be a workaround soon.

**Comment by ryanwalls** [comment]
@ehazlett Thanks!

**Comment by ehazlett** [comment]
yw -- i will post here once it's available.

**Comment by ryanwalls** [comment]
@ehazlett What's weird is if I start a new terminal and run `docker $(docker-machine config dev) ps` I can connect.

If I run `$(docker-machine env dev)`, then `docker ps` it fails with the cert error.

**Comment by frapposelli** [comment]
As a reference, this issue depends on boot2docker/boot2docker#747

**Comment by kpettijohn** [comment]
@frapposelli Were you able to come up with a short term solution or does the short term solution also depend on boot2docker/boot2docker#747?

**Comment by frapposelli** [comment]
This PR adds shared folders support for Fusion and should fix this issue https://github.com/docker/machine/pull/1034
