### ISSUE TITLE
Failed to create docker-machine - ssh error 

### ISSUE THREAD

**Issue by violetaDo** [docker/machine#4305]
Hi, 
after installing Docker Toolbox on Windows 7 along with VirtualBox I get an ssh error when trying to execute the following command:

docker-machine --debug create -d virtualbox testmachine

I get the following debug info:

(testmachine) DBG | &{[-F /dev/null -o PasswordAuthentication=no -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=quiet -o ConnectionAttempts=3 -o ConnectTimeout=10 -o ControlMaster=no -o ControlPath=none docker@127.0.0.1 -o IdentitiesOnly=yes -i C:\Users\vavava\.docker\machine\machines\testmachine\id_rsa -p 63700] C:\Program Files\Git\usr\bin\ssh.exe <nil>}]
(testmachine) DBG | About to run SSH command:
(testmachine) DBG | exit 0
(testmachine) DBG | SSH cmd err, output: exit status 255:
(testmachine) DBG | Error getting ssh command 'exit 0' : ssh command error:
(testmachine) DBG | command : exit 0
(testmachine) DBG | err     : exit status 255

After several retries the command fails. 
I can ping the VM's IP. I tried to remove and reinstall the machine but it did not work for me.

**Comment by stefanvangastel** [comment]
I am having the same issue. Ubuntu linux machine. If I connect to the machine with `ssh -i C:\Users\vavava.docker\machine\machines\testmachine\id_rsaxx user@machine` it works. The `id_rsa` name is messing with ssh somehow..
