### ISSUE TITLE
vcloud air: intermittent connectivity issues

### ISSUE THREAD

**Issue by ehazlett** [docker/machine#431]
This seems to happen the first time with each machine:

```
Error creating machine: error Acquiring Backend Authorization: error processing backend url action: API Error: 401: Unauthorized
```

**Comment by frapposelli** [comment]
Tracking as vmware/govcloudair#4

It's a quirk in the vCloud Air API, there's already a workaround in the bindings code to prevent that but apparently it got worse.

**Comment by ehazlett** [comment]
Thanks for the update!

**Comment by ehazlett** [comment]
This is actually happening about 50% of the time.  Is there anything we can do to help?

**Comment by frapposelli** [comment]
I had back to back meetings this week to figure out the best course of action to solve these problems, will start submitting PRs early next week.

**Comment by ehazlett** [comment]
Thanks!

On Thu, Feb 12, 2015 at 10:04 AM, Fabio Rapposelli <notifications@github.com

**Comment by frapposelli** [comment]
Opened PR #543 that adds exponential backoff.

**Comment by ehazlett** [comment]
Thanks.  This seems to work.  Is there any way we can specify a maximum re-tries and then error?  The ux is a bit odd:

```
INFO[0000] Connecting to vCloud Air...
API Error: 401: Unauthorized retrying... 2015-02-16 06:43:21.312508683 -0500 EST
API Error: 401: Unauthorized retrying... 2015-02-16 06:43:21.895913508 -0500 EST
API Error: 401: Unauthorized retrying... 2015-02-16 06:43:22.627922893 -0500 EST
API Error: 401: Unauthorized retrying... 2015-02-16 06:43:23.669372673 -0500 EST
API Error: 401: Unauthorized retrying... 2015-02-16 06:43:25.673351452 -0500 EST
API Error: 401: Unauthorized retrying... 2015-02-16 06:43:27.110338352 -0500 EST
INFO[0013] Creating a new vApp: test-vca...
```

**Comment by frapposelli** [comment]
The maximum interval is currently fixed to 30 seconds, it will error after that, will probably make it tweakable in the next version but right now it should be enough to make it work flawlessly.

On the UX oddness, I thought this was a good compromise to highlight the retry (not showing anything would've been odd as well :), I still need to add a decent debug structure to `govcloudair` once that is in place I will probably move the retry messages in the debug namespace.

Sounds reasonable?

**Comment by ehazlett** [comment]
Thanks.  This works.  We will most likely be refactoring logging soon too
so the timing should work.

Thanks again for the fix!
