### ISSUE TITLE
Progress logging disparity between "scp" and "scp -d"

### ISSUE THREAD

**Issue by dsifford** [docker/machine#4318]
Hello,

There appears to be a disparity between the outputs of `docker-machine scp` and `docker-machine scp -d` 

The non-rsync version produces the following output when requesting the file `foo.txt` from a cloud machine:

```
$ docker-machine scp foo:/foo.txt /home/dsifford/repos/test/
foo.txt                                                     100%   25     0.7KB/s   00:00
```

However, the rsync version produces no output at all. 

Is this the expected behavior? Having a progress indicator is pretty handy, especially when transferring a large amount of data.

Thanks for the clarification.

**Comment by afbjorklund** [comment]
On most versions of rsync, this could probably be accomplished by adding a `--progress` parameter.

**Comment by dsifford** [comment]
@afbjorklund I believe you're correct. Ideally, `--info=progress2` so that entire transfer progress would be shown rather than individual file progress, but I'm fairly certain that's not totally safe because it's a relatively newer addition to rsync.

Does docker-machine pass flags down through to rsync? If so, whoops! I was not aware of that.

**Comment by afbjorklund** [comment]
While `--info=progress2` does show only the entire transfer, scp does show every individual file...

So might as well use `--progress`. Added a new quiet option, to get the old behaviour back again.

**Comment by dsifford** [comment]
Greatly appreciated 🙏 

Thanks so much!
