### ISSUE TITLE
Machine creates CA and certificate when just getting usage

### ISSUE THREAD

**Issue by bfirsh** [docker/machine#432]
```
$ docker-machine                                                                                                                                                               
INFO[0000] Creating CA: /Users/ben/.docker/machines/ca.pem
INFO[0000] Creating client certificate: /Users/ben/.docker/machines/.client/cert.pem
NAME:
   docker-machine - Create and manage machines running Docker.

USAGE:
   docker-machine [global options] command [command options] [arguments...]

...
```

This seemed a bit odd. I was thinking "what's it doing? I didn't ask it to do anything!"

**Comment by ehazlett** [comment]
Instead of tying this to a specific command, I set it as a "before" to the CLI app.  We could move it out but then would have to make sure to call it from each command in case the user specifies different keys.  Perhaps we just take off the info logging?

**Comment by nathanleclaire** [comment]
@ehazlett We won't need the CA and certificate until a machine actually gets created, right?  So why not tie it to `Create`?

**Comment by ehazlett** [comment]
Yeah we shouldn't.  I'll update.  Thanks.

**Comment by ehazlett** [comment]
Closing - #460 merged
