### ISSUE TITLE
SSH command should be arguments, not an option

### ISSUE THREAD

**Issue by bfirsh** [docker/machine#434]
I should be able to do something like `machine ssh name df -h`. If we want to make the name optional, perhaps we could make a `-n` (name) or `-m` (machine) option for the name.

Also see confusion in #247.

**Comment by ehazlett** [comment]
I think if we are going to do this then we should force the name to be present.  I personally don't like how we have the inconsistency in the commands where some work on the "active" machine as well as specified and then we have this where it gets more tangled.

I would say we keep it simple and just make the command `machine ssh <name> <command>` like you said first.

**Comment by ehazlett** [comment]
@bfirsh the reason we use the `-c` is the cli package validates the flags.  For example, `machine ssh test-machine free` works but `machine ssh test-machine free -m` fails with `Incorrect usage`.  I'm digging into the cli package to see what we can do.

**Comment by sthulb** [comment]
There isn't much if I recall. We can't tell if the first arg is a machine name or a command or perhaps both (machine named ls for example).

A potential solution is:
If arg[0] is a machine name, run arg[1:] on arg[0], if arg[0] isn't a machine, run all args on the active machine.

**Comment by nathanleclaire** [comment]
I am +1 on args over `-c`- I think support for the flag parsing terminator (`--`) got merged into codegangsta/cli lately, so another solution available is that we might be able to bump the version and use that.  Then commands would look like `machine ssh dev -- df -h`.

**Comment by ehazlett** [comment]
Oooh nice!

**Comment by sthulb** [comment]
@nathanleclaire @ehazlett This doesn't really help... in @codegangsta/cli, all the -- option does is stop anything after -- being picked up and parsed as a flag :/

**Comment by ehazlett** [comment]
Closing as #446 is merged.
