### ISSUE TITLE
File is mounted as empty directory

### ISSUE THREAD

**Issue by yuppie-flu** [docker/machine#4349]
Mounting file via `-v` option does not work with `docker-machine`. The file is mounted as empty directory. However with plain docker (without `docker-machine`) the same test case works as expected.

### Environment
```
[kozlov@glenovo ~]$ uname -a
Linux glenovo 4.14.8-1-ARCH #1 SMP PREEMPT Wed Dec 20 21:27:44 UTC 2017 x86_64 GNU/Linux
[kozlov@glenovo ~]$ docker-machine -v
docker-machine version 0.13.0, build HEAD
```

### Steps to reproduce
1. Create new docker-machine with virtualbox driver and start it
```
[kozlov@glenovo ~]$ docker-machine ls
NAME   ACTIVE   DRIVER       STATE     URL                         SWARM   DOCKER        ERRORS
test   *        virtualbox   Running   tcp://192.168.99.100:2376           v17.12.0-ce   
```
2. Configure environment to use docker-machine
```
eval "$(docker-machine env test)"
```
3. Start `alpine` container with mounting some existing file using absolute path
```
[kozlov@glenovo ~]$ cat /tmp/file.txt 
Docker-machine BUG!!!
[kozlov@glenovo ~]$ docker run -v /tmp/file.txt:/tmp/file.txt alpine cat /tmp/file.txt
cat: read error: Is a directory
```

### Expected results
File was successfully mounted

### Actual results
File was mounted as empty directory

**Comment by afbjorklund** [comment]
@yuppie-flu : You need to make sure to use a location that is mapped from the host into the machine VM.
The virtualbox driver will share the `/home` directory, for other drivers you can use something like `sshfs`...

For one-offs, you can use `scp`:

``` shell
docker-machine scp /tmp/file.txt test:/tmp/file.txt
```

**Comment by yuppie-flu** [comment]
@afbjorklund Thank you for the explanation. It's clear now. Test case works with shared folder, not a bug.
