### ISSUE TITLE
docker-machine create --driver digitalocean errors

### ISSUE THREAD

**Issue by cpjolly** [docker/machine#4379]
Digital Ocean recently changed their Droplet plans and I think docker-machine create may need to be updated. There are two issues.

1. docker-machine create still generates Droplets from the old Digital Ocean plans
2. docker-machine throws an ssh error when attempting to install docker on the new Droplet

I reached out to Digital Ocean support and they said this needs to be fixed in the "caller of the API", i.e. docker-machine create...

Apologies if this is not a Docker problem but a Digital Ocean issue... 

For example, I tried to create a new 2GByte/50GByte/1VCPU Droplet but docker-machine created one of the old 2GByte/40GByte/2VCPU Droplet.

```
docker-machine -v
docker-machine version 0.13.0, build 9ba6da9

docker-machine create --driver digitalocean --digitalocean-image debian-9-x64 --digitalocean-size 2gb --digitalocean-region fra1 --digitalocean-access-token $DIGITALOCEANTOKEN d-o-host1
Running pre-create checks...
Creating machine...
(d-o-host1) Creating SSH key...
(d-o-host1) Creating Digital Ocean droplet...
(d-o-host1) Waiting for IP address to be assigned to the Droplet...
Waiting for machine to be running, this may take a few minutes...
Detecting operating system of created instance...
Waiting for SSH to be available...
Detecting the provisioner...
Provisioning with debian...
Copying certs to the local machine directory...
Copying certs to the remote machine...
Setting Docker configuration on the remote daemon...
Error creating machine: Error running provisioning: ssh command error:
command : sudo systemctl -f start docker
err : exit status 1
output : Job for docker.service failed because the control process exited with error code.
See "systemctl status docker.service" and "journalctl -xe" for details.
```

**Comment by pvlg** [comment]
I solved this problem as follows

edit
`
/etc/systemd/system/docker.service.d/10-machine.conf
`
remove this parameter
`
--storage-driver aufs
`
and
`
systemctl daemon-reload
systemctl start docker
`

Debian Stretch support only overlay, vfs volume driver

https://docs.docker.com/engine/userguide/storagedriver/selectadriver/#supported-storage-drivers-per-linux-distribution

**Comment by cpjolly** [comment]
Thanks for the storage driver info @pvlg. I also worked out how to access the new Droplet sizes.

For those of you who face similar issues:

1. You can see all the available sizes at the different Digital Ocean data centres  as follows:
```
$ curl -X GET -H "Content-Type: application/json" \
    -H "Authorization: Bearer $DIGITALOCEANTOKEN" \
    "https://api.digitalocean.com/v2/regions"
```
2. Overlay2 is the preferred storage driver for linux 4 based kernels, including Debian 9.
3. For Digital Ocean, use the following to specify a 2GB/60GB/1VCPU Droplet, using overlay2:
```
docker-machine create \
    --driver digitalocean \
    --engine-storage-driver overlay2 \
    --digitalocean-size s-2vcpu-2gb \
    --digitalocean-image debian-9-x64 \
    --digitalocean-region fra1 \
    --digitalocean-access-token $DIGITALOCEANTOKEN \
    d-o-host1
```
