### ISSUE TITLE
Different timezone settings between vm and host

### ISSUE THREAD

**Issue by benedictdudel** [docker/machine#4402]
If have noticed that I've got 2 different timezones. When I run `docker-machine ssh default` and run the command `date` I have a different timezone than on my host system.

```
$ date 
Sat Feb 17 14:25:47 UTC 2018
```

On my hosts it is:

```
$ date
Sat 17 Feb 2018 15:25:47 CET
```

Is this an expected behaviour? How can I sync the timezone between both?

**Comment by shin-** [comment]
https://unix.stackexchange.com/questions/110522/timezone-setting-in-linux
