### ISSUE TITLE
docker-machine create freezing the OS

### ISSUE THREAD

**Issue by ctur** [docker/machine#4405]
docker-machine create --driver virtualbox node1

Creating the virtual machines with the command above and every time the OS freezes on ubuntu 16.04 (it does not respond neither with the mouse nor with the keyboard).

**Comment by krotowsky** [comment]
try Virtualbox 5.2 - i had same issue with virtualbox 5

**Comment by ctur** [comment]
Thanks for reply. I have googled and tried lots of different things but nothing worked for me. Then i have found KVM and removed everything about Virtualbox and switch to it. Everything works like a charm now. @krotowsky
