### ISSUE TITLE
Manually installed docker-machine

### ISSUE THREAD

**Issue by IdrisDose** [docker/machine#4489]
Hi, I manually installed docker machine on my ubuntu 16.04 laptop using ` base=https://github.com/docker/machine/releases/download/v0.14.0 &&
  curl -L $base/docker-machine-$(uname -s)-$(uname -m) >/tmp/docker-machine &&
  sudo install /tmp/docker-machine /usr/local/bin/docker-machine`. How do I remove docker-machine, my laptop does not have virtualization enabled so I can't use docker-machine.

**Comment by kmmiles** [comment]
`sudo rm -f /usr/local/bin/docker-machine`

**Comment by IdrisDose** [comment]
Thanks heaps :)
