### ISSUE TITLE
Allow physical host install for Linux hosts

### ISSUE THREAD

**Issue by rothgar** [docker/machine#451]
This may be similar to #291 but that seems to want out of band installation/provisioning for OS and docker.

I want to configure already existing physical Linux hosts, either localhost or remote hosts via SSH, without needing a virtual machine.

I assume something like

`docker-machine create localhost` would be good enough for local setup

`docker-machine create --driver ssh remotehost` for remote hosts

This should be replaced with a config management/provisioning system if you're managing more than a dozen or so hosts but for a smaller lab or at home this would be very helpful.

**Comment by ehazlett** [comment]
Something like https://github.com/docker/machine/pull/406?

**Comment by rothgar** [comment]
Does that also work for localhost? Sorry I didn't see it before, was only looking at issues and not PR

**Comment by ehazlett** [comment]
It will if the host is ubuntu and has ssh. Currently machine is coupled to
ubuntu. There is a PR to add cloudinit to allow for more customization.

**Comment by rothgar** [comment]
Alright, thanks for letting me know. I'm specifically looking for RHEL/CentOS hosts but I'll just keep an eye on commits for future compatibility.
