### ISSUE TITLE
docker-machine config chokes when run against non-running machine

### ISSUE THREAD

**Issue by nathanleclaire** [docker/machine#452]
When the machine is running everything is cool:

```console
$ docker-machine config dev
--tls --tlscacert=/Users/nathanleclaire/.docker/machines/.client/ca.pem --tlscert=/Users/nathanleclaire/.docker/machines/.client/cert.pem --tlskey=/Users/nathanleclaire/.docker/machines/.client/key.pem -H tcp://192.168.99.132:2376%
```

But with non-running machines, everything goes haywire:

```console
$ docker-machine stop dev

$ docker-machine config dev
FATA[0000] Error getting machine url: host is not running
```

Yikes!  That shouldn't ever get thrown into a subshell.

**Comment by sthulb** [comment]
What would we expect the behaviour to be? Nothing? Something to stderr?

**Comment by ehazlett** [comment]
Hmm that's a good question.  I guess nothing?  Technically this behavior is the same for any command that throws an error when you run as a subshell.

Personally I think that's the right error.  You are asking for a config of something that is not running.

@nathanleclaire thoughts?

**Comment by nathanleclaire** [comment]
> What would we expect the behaviour to be? Nothing? Something to stderr?

It should be the same output as when the machine is running.  Now, this might be a little tricky, since in our current implementation a machine's IP address disappears when a machine is stopped due to the way that the store save mechanics work.  I'd argue that this shouldn't be the case; instead each machine should get a statically assigned IP address at create time which isn't freed up until the machine is destroyed.  That would make stuff like this possible.

> Personally I think that's the right error. You are asking for a config of something that is not running.

It's the wrong error if we want users to know what's actually happening with the way the current workflow is set up.  Otherwise, `docker` just barfs because the user is passing invalid input to the CLI and leaves them with no idea what might have gone wrong (it will spit out help text and `Error: Command not found: time="2015-02-02T11:00:16-08:00"`).

A machine doesn't need to be running for clients to attempt to connect to it.  A hanging `docker version` is something which is universally accepted as an idiom for "the daemon is not responding".  That's what should happen in this case.  "Oh, my `docker version` is hanging, so the daemon must not be running".

Curious what @bfirsh thinks as well.

**Comment by ehazlett** [comment]
If we want to leave the user without knowing there is an error and just rely on the Docker CLI to tell us, fine.  @bfirsh ?

**Comment by sthulb** [comment]
> My crazy idea: It should be the same output as when the machine is running. Now, this might be a little tricky, since in our current implementation a machine's IP address disappears when a machine is stopped due to the way that the store save mechanics work. Perhaps each machine could get a statically assigned IP address at create time which isn't freed up until the machine is destroyed. That would make stuff like this possible.

@nathanleclaire we can only assign local machines static IPs, for remote drivers that can't have static IPs or there is a charge, this would be difficult. Also, a stopped instance on some providers will have different IPs when they come back up.


I think leaving Docker CLI to tell us there's an error is fine.

**Comment by nathanleclaire** [comment]
@sthulb Right on, that might be more trouble than it's worth and I think I have a decent idea for a compromise.

**Comment by nathanleclaire** [comment]
Another idea for this issue: https://github.com/docker/machine/pull/482

**Comment by ehazlett** [comment]
Closing as #482 is merged.
