### ISSUE TITLE
docker-machine activate <env>

### ISSUE THREAD

**Issue by djchou** [docker/machine#4570]
The current syntax for activating a docker-machine is not very intuitive.  Could we add a shortcut to be more in line with the other docker commands or other type of virtual environment commands?

currently, the way to activate a docker-machine is:
eval $(docker-machine env [machine-name])

Could we change this to something more like
docker-machine activate env

?

**Comment by shin-** [comment]
A child process can't modify the parent's environment, so any such command simply wouldn't work.
