### ISSUE TITLE
[Feature Request] ls should report daemon availability

### ISSUE THREAD

**Issue by nathanleclaire** [docker/machine#46]
Currently the `ls` command reports whether a host is active, but it does not report daemon availability.  `machine ls` should check using something like `net.DialTimeout` to see if the daemon is responding to requests as well as if the host is up.

**Comment by ehazlett** [comment]
+1 to @johngossman -- maybe something like `machine health staging` that would report all of those -- daemon status, cloud service, etc.

**Comment by nathanleclaire** [comment]
+1 @ehazlett like the sound of it

**Comment by dgageot** [comment]
This is fixed with https://github.com/docker/machine/pull/2442
`docker-machine ls` now displays the docker daemon version or an error if the daemon is not responding.

**Comment by nathanleclaire** [comment]
:+1: :+1: :+1:
