### ISSUE TITLE
docker-machine create is never using cache

### ISSUE THREAD

**Issue by LogX7** [docker/machine#4606]
here's waht i am running `docker-machine create test` or `docker-machine create -d virtualbox test`

here's the output 

```
Running pre-create checks...
(test2) Unable to get the local Boot2Docker ISO version:  Did not find prefix "-v" in version string
(test2) Default Boot2Docker ISO is out-of-date, downloading the latest release...
(test2) Latest release for github.com/boot2docker/boot2docker is v18.09.0
(test2) Downloading /home/hammi/.docker/machine/cache/boot2docker.iso from https://github.com/boot2docker/boot2docker/releases/download/v18.09.0/boot2docker.iso...
(test2) 0%....10%....20%....30%....40%....50%....60%....70%....80%....90%....100%
Creating machine...
(test2) Unable to get the local Boot2Docker ISO version:  Did not find prefix "-v" in version string
(test2) Default Boot2Docker ISO is out-of-date, downloading the latest release...
(test2) Latest release for github.com/boot2docker/boot2docker is v18.09.0
(test2) Downloading /home/hammi/.docker/machine/cache/boot2docker.iso from https://github.com/boot2docker/boot2docker/releases/download/v18.09.0/boot2docker.iso...
```

as you can see, it is not using the cached previously downloaded image

**EDIT**
i'm on Linux Mint 19
docker-machine version 0.14.0, build 89b8332

**Comment by LogX7** [comment]
@BretFisher  .. i learned docker from you tutorial by the way

**Comment by elavaud** [comment]
Same here with:
Ubuntu 18.04 (eOS Juno)
Docker 18.09.0
docker-machine 0.16

**Comment by cryptoentity** [comment]
`~ docker-machine version

docker-machine version 0.16.0, build 702c267f
~ sw_vers

ProductName:	Mac OS X
ProductVersion:	10.14
BuildVersion:	18A391`

Same issue here

**Comment by stefanjacobs123** [comment]
Having the same issue on Windows 10.

From a fresh install: https://docs.docker.com/toolbox/toolbox_install_windows/ (choosing defaults)

`docker-machine version` = 0.14.0, build 89b8332

Windows Version: 10.0.17134.345

**Comment by YoungSharp** [comment]
any answer for this issue?

**Comment by izaakdehullu** [comment]
Also having this problem. Docker for windows, docker-machine version 0.15.0, build b48dc28d. Creating Nodes now takes ages. Please fix this I need it working smoothly for a demo soon....

**Comment by afbjorklund** [comment]
As a workaround, you can give a local ISO URL explicitly... The parameter varies slightly, based on driver.
`--virtualbox-boot2docker-url 									The URL of the boot2docker image. Defaults to the latest available version [$VIRTUALBOX_BOOT2DOCKER_URL]`

**Comment by puppylpg** [comment]
Thanks @afbjorklund . That solved the problem. Waiting for the new release of boot2docker.iso!

**Comment by aleroise** [comment]
Manual download to ~/.docker/machine/cache/boot2docker.iso , then :
`export VIRTUALBOX_BOOT2DOCKER_URL=file://$HOME/.docker/machine/cache/boot2docker.iso`
`docker-machine create --driver virtualbox myvm` : it will auto detect your file in cache

**Comment by midosh** [comment]
> 
> 
> Manual download to ~/.docker/machine/cache/boot2docker.iso , then :
> `export VIRTUALBOX_BOOT2DOCKER_URL=file://$HOME/.docker/machine/cache/boot2docker.iso`
> `docker-machine create --driver virtualbox myvm` : it will auto detect your file in cache

it works thanks .

**Comment by AdamWillz** [comment]
> > Manual download to ~/.docker/machine/cache/boot2docker.iso , then :
> > `export VIRTUALBOX_BOOT2DOCKER_URL=file://$HOME/.docker/machine/cache/boot2docker.iso`
> > `docker-machine create --driver virtualbox myvm` : it will auto detect your file in cache
> 
> Is there any solution for Windows System？

I had tried in vain to set a local file path in Windows. Building off the solution from @afbjorklund I added the following line to `start.sh` after `export PATH=...`
```
export VIRTUALBOX_BOOT2DOCKER_URL=https://github.com/boot2docker/boot2docker/releases/download/v18.06.1-ce/boot2docker.iso
```

Works on Windows as a temporary workaround. You can set the release you want.

**Comment by Wiezzel** [comment]
@erhu1999 @AdamWillz 
I found a working solution for Windows that uses a local file.
1. Download the .iso to some directory (but **not** `.docker/machine/cache/boot2docker.iso`) e.g. `C:\Users\<my_user>\Downloads\boot2docker.iso`.
2. Then set the boot2docker URL variable to `file://C:/Users/<my_user>/Downloads/boot2docker.iso`.

Please notice that there are two slashes after `file:` (not three as there should be in a proper local file URI).
I tested it on Hyper-V but I hope it will work for VirtualBox as well.

**Comment by afbjorklund** [comment]
I think this bug will continue to be open, until boot2docker `v18.09.1` has been released...

@tianon Seems like this isn't really the "maintenance mode" that is mentioned in #4537 ?

**Comment by tianon** [comment]
This is how b2d releases have always been; hard-locked to Docker releases (so fixes get similarly delayed).

Of the things wrong with 18.09.0, this is honestly one of the most benign 😅.

I'm told 18.09.1 will officially be released sometime soon, although I don't know exactly how soon (@thaJeztah? :pray: :heart:).

**Comment by thaJeztah** [comment]
Hopefully next week

**Comment by afbjorklund** [comment]
The new release (`v18.09.1`) is out now, which fixes this issue.
https://github.com/boot2docker/boot2docker/releases/tag/v18.09.1

https://github.com/boot2docker/boot2docker/releases/download/v18.09.1/boot2docker.iso

**Comment by thaJeztah** [comment]
👍 let's close this one, thanks everyone!
