### ISSUE TITLE
vsphere: pool not found error after first run

### ISSUE THREAD

**Issue by ehazlett** [docker/machine#461]
After running the first time (which did not succeed, the machine was never started and an error of "Invalid state" was thrown) `govc` errors out with "cannot find pool <poolname>".  The pool indeed exists and the user has administrator privileges.

**Comment by frapposelli** [comment]
There are two concatenated issues here:

- There is a problem in the code that was introduced in docker/machine@861b16dba9020ae6cb3c62e699683db9554300cc (see my [comment in the code](https://github.com/docker/machine/commit/861b16dba9020ae6cb3c62e699683db9554300cc#commitcomment-9579065)), I'm sending a PR for that shortly.

- The B2D iso that is being pulled doesn't contain `vmtoolsd`, hence vSphere cannot figure out the IP of the VM and communicate it back, this is related to the unmerged PR boot2docker/boot2docker#638. 

The B2D issue can be fixed either by merging OVT in Boot2Docker or by pulling a custom ISO (I rebased my custom ISO to v1.4.1 and works). Let me know what works best for you.

**Comment by ehazlett** [comment]
@frapposelli i have a PR open to fix the first: #485 

Let me discuss the `vmtools` issue.  Thanks!

**Comment by frapposelli** [comment]
Cool :+1: the `vmtoolsd` PR is definitely a must have for vSphere.

**Comment by ehazlett** [comment]
@frapposelli could you give a link of the updated b2d custom ISO so I can test?

**Comment by frapposelli** [comment]
Here it is: https://github.com/cloudnativeapps/boot2docker/releases/tag/v1.4.1-vmw

**Comment by ehazlett** [comment]
@frapposelli thx!

**Comment by frapposelli** [comment]
I guess this is done given docker/machine@6feb419

**Comment by ehazlett** [comment]
Cool. Would you be willing to test it as well to make sure?  Thanks!

**Comment by frapposelli** [comment]
Tested current `master` and works great :+1:

**Comment by ehazlett** [comment]
Awesome.  Thanks!
