### ISSUE TITLE
transport stream analysis report 

### ISSUE THREAD

**Issue by fredino** [docker/machine#4619]
Hallo everybody,

first of all I'm a new user for docker and I have a couple of questions  

I'm using now docker since one month, the goal for using docker for me is to run a tsduck toolkit app ( The MPEG Transport Stream Toolkit ) in a container then getting the transport stream analysis report and import it in grafana dashboard 

I already ececuted the source code in a container and got the transport stream analysis report, next step is to import that report in grafana dashboard .

first question is , how can I know if my tsduck toolkit app is running inside a container or not ? 
second question is, is there any command trigger another command in docker which export that txt file report analysis automatically to grafana dashboard, since I have already the ip address and the port of my stream  tsp -P analyze -I ip 10.15.97.125@232.100.142.1:5000 --ts-analysis and how to connect both of them my app and grafana dashboard together  ?

I will be really thankful for your help :)

**Comment by shin-** [comment]
This is an issue tracker for Docker Machine. Please use https://forums.docker.com instead.
