### ISSUE TITLE
Install Docker Machine Fails on MacOS 10.14.2 (18C54)

### ISSUE THREAD

**Issue by ScottyVG** [docker/machine#4635]
When running the following command from [the docs](https://docs.docker.com/machine/install-machine/) `$ base=https://github.com/docker/machine/releases/tag/v0.16.0 &&
  curl -L $base/docker-machine-$(uname -s)-$(uname -m) >/usr/local/bin/docker-machine &&
  chmod +x /usr/local/bin/docker-machine`

I get the following error when running `$ docker-machine version`

`/usr/local/bin/docker-machine: line 7: syntax error near unexpected token `newline'
/usr/local/bin/docker-machine: line 7: `<!DOCTYPE html>'`

It looks like the curl command is grabbing an html file for the docker-machine.

**Comment by bypotatoes** [comment]
same for ubuntu, it seems that github url has changed and base should be `https://github.com/docker/machine/releases/download/v0.16.0`

**Comment by ScottyVG** [comment]
Thank you @bypotatoes 

running:
`base=https://github.com/docker/machine/releases/download/v0.16.0 &&
  curl -L $base/docker-machine-$(uname -s)-$(uname -m) >/usr/local/bin/docker-machine &&
  chmod +x /usr/local/bin/docker-machine`
worked for me.
