### ISSUE TITLE
docker-machine for windows on  AMD FX-8300 cannot create virtualbox machine

### ISSUE THREAD

**Issue by hilbertxia** [docker/machine#4669]
I run docker toolbox v18.09.2 (include docker-machine v0.16.1) in my Windows 10 ( Gigabyte 970A-DS3P + AMD FX-8300) computer, get the fowllowing error info: Error with pre-create check: "This computer doesn't have VT-X/AMD-v enabled. Enabling it in the BIOS is mandatory". After tracingthe docker-machine source code, I find the problem exist in drivers\virtualbox\vtx_intel.go Line 9:
 if cpuid.HasFeature(cpuid.VMX) || cpuid.HasFeature(cpuid.SVM) {
must be
 if cpuid.HasFeature(cpuid.VMX) || cpuid.HasExtraFeature(cpuid.SVM) {
. Simply fix, build docker-machine v0.16.1 in Ubuntu 18.04.02 by myself, it is working. This problem affect latest minikube version (v0.34.0) in windows 10.
I don't how to report bug, so issue.

**Comment by afbjorklund** [comment]
Good catch! See the same issue in `minikube`.

Can you make a commit and open a Pull Request ?
