### ISSUE TITLE
machine vendors a revision of docker which doesn't exist

### ISSUE THREAD

**Issue by nathanleclaire** [docker/machine#472]
cc @bfirsh @ehazlett @sthulb 

Not sure how this happened, but see for yourself:

```console
$ cd /tmp && git clone https://github.com/docker/docker && cd docker && git checkout 831d09f8b535a1e2939bdacb02032d238e8dd249
Cloning into 'docker'...
remote: Counting objects: 70905, done.
remote: Compressing objects: 100% (41/41), done.
remote: Total 70905 (delta 11), reused 44 (delta 9)
Receiving objects: 100% (70905/70905), 39.38 MiB | 4.72 MiB/s, done.
Resolving deltas: 100% (46278/46278), done.
Checking connectivity... done.
fatal: reference is not a tree: 831d09f8b535a1e2939bdacb02032d238e8dd249
```

After wrangling with Godeps a bit this afternoon I'm starting to think we should rip it out and replace it with something else (probably custom - we could either steal `vendor.sh` as a base or make our own thing).

It's not very actively maintained (last commit is from two weeks ago), [seems to have issues supporting Go 1.4](https://github.com/tools/godep/issues/168) (which we should move to anyway ASAP), and so on.

At any rate I will look into vendoring `docker/docker` properly.

**Comment by ehazlett** [comment]
This probably happened from the beginning when we were using a custom
identity version from Ben's fork.  We should just be able to godep update.
I would rather use something that is half way supported then some home
grown thing ourselves.

**Comment by ehazlett** [comment]
#474 should fix this.
