### ISSUE TITLE
Question: How is the value of the SWARM column determined?

### ISSUE THREAD

**Issue by schmunk42** [docker/machine#4730]
I am about to replace a `docker/swarm` manager. At the moment I have two manager in the swarm (no replicas). 
Currently the swarm name in `docker-machine ls` is the same as the *old swarm-manager name*, but I am connected (`docker-machine env --swarm`) to the *new swarm-manager*.

So, how is the value for `SWARM` determined? 
I found nothing helpful to me while looking into the code, did a `docker-machine inspect`, it's also different from the one in the discovery.

CC: @handcode

**Comment by handcode** [comment]
This is the "directory name" of the last machine that `docker-machine ls` finds in its machines directory which has a master flag.

see: https://github.com/docker/machine/blob/master/commands/ls.go#L123
