### ISSUE TITLE
One Simple Question.

### ISSUE THREAD

**Issue by TrumanLing** [docker/machine#476]
From information over internet, the final target of docker is to run on physical machine, but docker machine makes docker work on virtual machine. Is it docker machine a temporary tool to enforce docker's security and isolation?

**Comment by ehazlett** [comment]
I'm not sure what you are reading from but Docker runs on both physical and virtual machines well.  It really depends on your environment and what works best for you.  There are many benefits to running in a cloud provider or VMs.

Docker Machine is intended to assist in getting Docker Engine(s) / Swarm cluster up and running in a secure setup with minimal effort.

Does this answer your question?

**Comment by TrumanLing** [comment]
@ehazlett thx for your info, I understand your explanation, docker can run physical and virtual machines, and docker machine is a tool cooperating with swarm for cluster. And I think, currently docker's security and isolation is not better than VM, and the docker running environment setup via docker machine can potentially enforce docker's weakness, moreover I want to know the trend of container tech, will docker or other container tech substitute VM, does docker have that road map.

**Comment by ehazlett** [comment]
@TrumanLing Thanks for your interest.  If you have concerns about security, please send to support@docker.com.  I'm also not the one to give an official opinion on the trend of container tech - I just want to build the best things we can and hopefully people find them useful :)
