### ISSUE TITLE
docker-machine works in git bash but not in powershell

### ISSUE THREAD

**Issue by oke-aditya** [docker/machine#4791]
OS used:- Windows 10 Pro
Hypervisor:- Hyper-V (Not virtual box)
Docker installation: - Docker for Windows (not Docker Desktop)

- I installed the docker-machine using the below commands as given on GitHub releases page and in the docker docs.

- I ran the below code in my git bash. ( As suggested in [https://github.com/docker/machine/releases/](https://github.com/docker/machine/releases/))

` $ if [[ ! -d "$HOME/bin" ]]; then mkdir -p "$HOME/bin"; fi && \
curl -L https://github.com/docker/machine/releases/download/v0.16.2/docker-machine-Windows-x86_64.exe > "$HOME/bin/docker-machine.exe" && \
chmod +x "$HOME/bin/docker-machine.exe" `

- Now docker machine seems to be running fine in git bash 

![image](https://user-images.githubusercontent.com/47158509/78986006-e00c0500-7b47-11ea-9cbb-7456076d942b.png)

- But it fails to run on powershell. This is original powershell in windows 10
![image](https://user-images.githubusercontent.com/47158509/78986070-00d45a80-7b48-11ea-8c2a-79d5a638f226.png)

- Also fails on powershell v7
![image](https://user-images.githubusercontent.com/47158509/78986120-219cb000-7b48-11ea-88ea-9f28b3243eed.png)

- Similar issues #4464 #3152 and #4789 They are open currently.

- Is this PR the solution ? #4788 Open PR currently.

**Comment by oke-aditya** [comment]
- This fixed for me.
https://github.com/docker/machine/issues/4424#issuecomment-377727985

Now docker-machine runs in the powershell (both versions).
The problem might be because.
- I had no docker-machine.exe file created after the above process.
- I still wonder how git bash picked it up.

**Comment by yureplacido** [comment]
The best way in to use chocolatey.org, choco install docker-machine. It will insltall all you need.
