### ISSUE TITLE
[Feature Request] Configure Docker client inside machine

### ISSUE THREAD

**Issue by thaJeztah** [docker/machine#48]
After creating a new machine, the Docker client on the created machine itself is not configured to connect to the daemon. It would be nice if the client *on* the machine is also automatically configured.

    # Local client is able to connect to the remote daemon;
    ./docker-1.3.1-dev-identity-auth info
    [outputs docker info of "machine"]

    # But SSH-ing into the remote machine, that client is not configured

    ./machine ssh dev

    ~# docker info
    FATA[0000] Cannot connect to the Docker daemon. Is 'docker -d' running on this host? 

    ~#docker --host=tcp://127.0.0.1:2376 --auth=identity info
    FATA[0000] TLS Handshake error: remote error: bad certificate

**Comment by ehazlett** [comment]
This is fixed with the new `env` command.  For example, `$(docker-machine env dev)`
