### ISSUE TITLE
SSH password for a new driver

### ISSUE THREAD

**Issue by nlamirault** [docker/machine#480]
hi,
hi try to add a new driver OnlineLabs to Docker machine.
VM creation is working and upload SSH keys too.
I try to connect to VM using ssh package : 

```bash
DEBU[0051] [OnlineLabs] Waiting server ready. Currently : Running 
DEBU[0051] [OnlineLabs] Server 7d01e8a1-b843-437b-afaa-dfa8ac607182 is running. Set IP address 
DEBU[0057] [OnlineLabs] Setting hostname: docker-lam    
DEBU[0057] executing: ssh -o IdentitiesOnly=yes -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=quiet -p 22 -i /home/nlamirault/.docker/machines/docker-lam/id_rsa root@xx.xx.xx.xx echo "127.0.0.1 docker-lam" | sudo tee -a /etc/hosts && sudo hostname docker-lam && echo "docker-lam" | sudo tee /etc/hostname 
root@212.47.237.14's password: 
```

If i try to execute command in a bash it works : 

```
$ ssh -o IdentitiesOnly=yes -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=quiet -p 22 -i /home/nlamirault/.docker/machines/docker-lam/id_rsa root@xx.xx.xx.xx
$ root@docker-lam:~# 
```

Any idea about this difference ?
Thanks

**Comment by ehazlett** [comment]
Is the instance up and ssh available?  Sometimes this can happen if you try to ssh too quickly.

**Comment by nlamirault** [comment]
hi think. According to  the code and the previous logs : 

``̀`go
if err := ssh.WaitForTCP(fmt.Sprintf("%s:%d", d.IPAddress, 22)); err != nil {
	return err
}
log.Debugf("[OnlineLabs] Setting hostname: %s", d.MachineName)

log.Debugf("[OnlineLabs] Setting hostname: %s", d.MachineName)
cmd, err := d.GetSSHCommand(
	fmt.Sprintf(
		"echo \"127.0.0.1 %s\" | sudo tee -a /etc/hosts && sudo hostname %s && echo \"%s\" | sudo tee /etc/hostname",
		d.MachineName,
		d.MachineName,
		d.MachineName,
	))
if err != nil {
	return err
}
if err := cmd.Run(); err != nil {
	return err
}

```

**Comment by ehazlett** [comment]
hmm yeah it should work -- we currently shell out so it should be the same as your manual command.  the only thing i could think of is perhaps the provisioning service is doing something with the key on the server side causing some sort of race condition.  You might try a manual sleep just to see if that works.  I'm not sure what else it would be.

**Comment by nlamirault** [comment]
Using a sleep it works. Thanks

**Comment by ehazlett** [comment]
fyi there is also https://github.com/docker/machine/blob/master/ssh/ssh.go#L64 that you can use to wait until it is available -- i would recommend that against sleep.
