### ISSUE TITLE
Windows USERPROFILE or HOME env variables are ignored

### ISSUE THREAD

**Issue by atomi** [docker/machine#483]
On Windows boot2docker uses the HOME env variable to translate .boot2docker config path. Docker-machine should do that.

**Comment by ehazlett** [comment]
Everything appears to be working on Windows as far as I can tell.  Are you experiencing a problem or issue?

**Comment by atomi** [comment]
Yeah docker-machine is ignoring the both the HOME and USERPROFILE environment variables.

**Comment by ehazlett** [comment]
Can you be more specific?  What are you doing where it's ignoring?  It
shouldn't be:
https://github.com/docker/machine/blob/master/utils/utils.go#L12

**Comment by jeffmendoza** [comment]
HOME is not appropriate for Windows. It is not set automatically.

**Comment by ehazlett** [comment]
@jeffmendoza can you confirm `USERPROFILE` is correct or do we need to update that?

**Comment by jeffmendoza** [comment]
Yes, `USERPROFILE` is correct. Also, we'll do #499 after docker 1.5 release.

**Comment by ehazlett** [comment]
Yes indeed.  Thanks for confirming.
