### ISSUE TITLE
docker registry test failed

### ISSUE THREAD

**Issue by TrumanLing** [docker/machine#484]
run "sudo ./script/test", error info:
......
Successfully built 1afb7fe6e80b
go build launchpad.net/gocheck: no buildable Go source files in 
=== RUN TestGetHostState
--- PASS: TestGetHostState (0.00 seconds)
=== RUN TestLoadHostDoesNotExist
--- PASS: TestLoadHostDoesNotExist (0.00 seconds)
=== RUN TestLoadHostExists
--- PASS: TestLoadHostExists (0.00 seconds)
=== RUN TestValidateHostnameValid
--- PASS: TestValidateHostnameValid (0.00 seconds)
=== RUN TestValidateHostnameInvalid
--- PASS: TestValidateHostnameInvalid (0.00 seconds)
=== RUN TestGenerateClientCertificate
--- PASS: TestGenerateClientCertificate (1.30 seconds)
=== RUN TestGenerateDockerConfigNonLocal
--- PASS: TestGenerateDockerConfigNonLocal (0.00 seconds)
=== RUN TestMachinePort
--- PASS: TestMachinePort (0.00 seconds)
=== RUN TestMachineCustomPort
--- PASS: TestMachineCustomPort (0.00 seconds)
=== RUN TestHostConfig
--- PASS: TestHostConfig (0.00 seconds)
=== RUN TestStoreCreate
--- PASS: TestStoreCreate (0.00 seconds)
=== RUN TestStoreRemove
--- PASS: TestStoreRemove (0.00 seconds)
=== RUN TestStoreList
--- PASS: TestStoreList (0.00 seconds)
=== RUN TestStoreExists
--- PASS: TestStoreExists (0.00 seconds)
=== RUN TestStoreLoad
--- PASS: TestStoreLoad (0.00 seconds)
=== RUN TestStoreGetSetActive
--- PASS: TestStoreGetSetActive (0.00 seconds)
PASS
ok  	github.com/docker/machine	1.313s
FAIL	github.com/docker/machine/docker-registry/contrib/golang_impl [build failed]
=== RUN TestGetCreateFlags
--- PASS: TestGetCreateFlags (0.00 seconds)
PASS
ok 
......
************************************************************************************************
************************************************************************************************
in container, run "go test", error info:
root@b8e3964dc65d:/go/src/github.com/docker/machine/docker-registry/contrib/golang_impl# go test
go build launchpad.net/gocheck: no buildable Go source files in 
FAIL	github.com/docker/machine/docker-registry/contrib/golang_impl [build failed]

**Comment by ehazlett** [comment]
It looks like you are running tests from multiple projects or something.  I just ran the tests and all are passing.  Travis CI is passing as well.  Try to clear your clone and re-run the tests.
