### ISSUE TITLE
This computer doesn't have VT-X/AMD-v enabled. Enabling it in the BIOS is mandatory

### ISSUE THREAD

**Issue by hoangthedo** [docker/machine#4875]
- [x] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
I can create virtual machine
### Actual behavior
There is a error: 
`This computer doesn't have VT-X/AMD-v enabled. Enabling it in the BIOS is mandatory`
Command:
`docker-machine create -d virtualbox --virtualbox-memory 8192 --virtualbox-cpu-count 4 --virtualbox-disk-size 150000 --virtualbox-no-share dinghy`
### Information

  - Is it reproducible? Yes, in my machine
  - macOS Version: 11.2.2 (20D80) chip M1
  - Docker Desktop Version: 3.1.0 (60984) Apple M1 Tech Preview

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by justincormack** [comment]
Virtualbox does not work on M1, and it does not appear that there will ever be a port see https://forums.virtualbox.org/viewtopic.php?f=8&t=98742
