### ISSUE TITLE
Azure driver, how to specify --virtual-network-name --subnet-names

### ISSUE THREAD

**Issue by roldancer** [docker/machine#496]
Hi, I don't know if this place is the right place for "How to" questions ... 

I would like to create my VM on Azure but on a specific network, I use the following parameters in the Azure cli for linux  "azure vm create --virtual-network-name ... --subnet-names  ...."

Is there any way to specify those parameters using the Azure driver ?

Thanks and sorry if  I posted this question in the wrong place...

**Comment by sthulb** [comment]
Right place I guess, but we don't allow users to specify them yet.

**Comment by roldancer** [comment]
Is there any plan to add those parameters ?, I'm asking this because wihtout those parameters is not possible to deploy a docker runtime on a private network

**Comment by ehazlett** [comment]
Thanks for reporting.  I would imagine this would be a good thing.  /cc
@jeffmendoza

**Comment by jeffmendoza** [comment]
Agreed, these would be good. I'll see what we can do.

**Comment by cascadian** [comment]
+1

**Comment by ahmetalpbalkan** [comment]
@ehazlett duly noted. I was expecting this request to come. Let's keep in the backlog. Thanks for labeling.

**Comment by ehazlett** [comment]
@ahmetalpbalkan thanks!

**Comment by otaviocarvalho** [comment]
+1

**Comment by nashasha1** [comment]
+1

**Comment by dmp42** [comment]
@ahmetalpbalkan @jeffmendoza bump :)

**Comment by ahmetalpbalkan** [comment]
@dmp42 I'll be rewriting docker-machine with the newly released Azure REST APIs soon. Taking that as a feature request for that. :)

**Comment by dmp42** [comment]
@ahmetalpbalkan \o/

**Comment by bitsofinfo** [comment]
bump!!!!

**Comment by jamesmeen** [comment]
Bump :D

**Comment by jensbruggeman** [comment]
Any news on this?  I'd like to setup a Consul cluster on Azure and connect with private IP addresses.  Therefore it should be great to have this enhancement :+1: :)

Best regards,
Jens

**Comment by ahmetalpbalkan** [comment]
@bitsofinfo @jamesmeen @jensbruggeman Hi folks (and those who are planning to +1 afterwards), I recently got busy with some other projects but rewriting the Azure driver is definitely on my list and I'd like to take a look at that in the next month or so.

**Comment by rafabene** [comment]
+1 At this moment I couldn't setup a docker-swarm cluster with docker-machine because the hosts seems to not be able to talk to each other. This proposal should fix it

**Comment by jotunskij** [comment]
+1

I would like some way to send arbitrary flags to the azure vm create-command (I assume) is run by the azure-driver of docker-machine create. In my case I want to be able to specify a static private IP (the -S/--static-ip flag) to the machines I'm creating for the swarm managers and the consul instances.

**Comment by ahmetalpbalkan** [comment]
@jotunskij are you aware of any other machine driver for cloud provider that lets you specify a static private IP address?

**Comment by dgageot** [comment]
@ahmetalpbalkan @jotunskij the google driver with the `google-address` flag.

**Comment by ahmetalpbalkan** [comment]
@dgageot hmm `google-address` appears to be for external IP addr. Internal IP is way easier to do for Azure case. External IP will be harder for users to actually specify the argument (it'll be a long argument to the IP resource). @jotunskij do you only need specifying an internal IP address or do you need static public IP addresses, too?

**Comment by jotunskij** [comment]
@ahmetalpbalkan Since machine is the only one I've tried, no. The static ip configuration can in fact be done after docker-machine create by using the azure cli. Since machine is using the azure sdk and this let's you specify a static ip flag I'm not sure why this couldn't be done though? The more important aspect is (as many before me have mentioned) the possibility to add the machine to a virtual network upon creation.
I only need to specify an internal IP right now. I'm using is to advertise the swarm masters and consuls on their own IP when I fire them up. This method seems to be the same that is used in the swarm quickstart template provided by Azure themselves: https://github.com/Azure/azure-quickstart-templates/tree/master/docker-swarm-cluster

Is there any specific reason why a --driver-opt="--static-ip=x.y.z" couldn't be added that I'm not aware of?

**Comment by dgageot** [comment]
@ahmetalpbalkan You are right. It's not for a private IP. I misread your question!

**Comment by ahmetalpbalkan** [comment]
@jotunskij I see. I just implemented `--azure-private-ip-address`  for the new version of azure driver that we'll release soon. Virtual networks and many such problems are already addressed there. Stay tuned.

**Comment by jotunskij** [comment]
@ahmetalpbalkan Alright, thanks and great work!

**Comment by ahmetalpbalkan** [comment]
@jotunskij @roldancer  This issue is now fixed with the brand new `azure` driver in `master` branch. Please try it out and close the issue as you see fit (I forgot include this issue number in PR #3159).

**Comment by ahmetalpbalkan** [comment]
@nathanleclaire please close as it is resolved.
