### ISSUE TITLE
utils.GetHomeDir should use github.com/docker/docker/pkg/homedir

### ISSUE THREAD

**Issue by ahmetalpbalkan** [docker/machine#499]
The logic was historically copy/pasted from docker code. We now have a separate pkg for that: `github.com/docker/docker/pkg/homedir` (https://github.com/docker/docker/pull/10602)

I couldn't manage to vendor that change from docker/docker (I guess we keep Godeps at docker-1.4.1 at this point). But at some point this codebase should make use of the new package (especially at utils/utils.go).
cc: @jeffmendoza @ehazlett

**Comment by nathanleclaire** [comment]
+1

**Comment by ehazlett** [comment]
Yes, +1 also.  Once 1.5 is released we can update the deps.

**Comment by ehazlett** [comment]
This does not appear to be in v1.5.0. https://github.com/docker/docker/tree/v1.5.0/pkg

**Comment by ahmetalpbalkan** [comment]
@ehazlett I guess it didn't make it. Feel free to specify a commit number if you like or it can wait 1.5.1?

**Comment by atomi** [comment]
In the meantime, how will users be able to specify where the .docker/machine/* files are stored?

**Comment by ehazlett** [comment]
@atomi you can by specifying `--storage-path` on the command line or using the environment variable `MACHINE_STORAGE_PATH`.

**Comment by ehazlett** [comment]
This should be fixed.
