### ISSUE TITLE
restart fails after stop

### ISSUE THREAD

**Issue by razic** [docker/machine#502]
```bash
machine create dev -d virtualbox
machine stop dev
machine restart dev
FATA[0000] VBoxManage controlvm dev acpipowerbutton failed: exit status 1
```

**Comment by sthulb** [comment]
We should handle this a bit better.

**Comment by ehazlett** [comment]
I think we need a little more information.

@razic can you tell me what the host OS and VirtualBox versions are?

**Comment by ehazlett** [comment]
Ok I can confirm this.  Thanks for reporting.  Working on a fix.
