### ISSUE TITLE
Proposal: KVM/Qemu driver

### ISSUE THREAD

**Issue by Tebro** [docker/machine#504]
The title says it all. A driver for KVM/Qemu could be quite useful since it is so easy to set up a host for it and using SSH to auth.

**Comment by ehazlett** [comment]
+1

**Comment by gnoymmij** [comment]
+1

**Comment by grigio** [comment]
+1

**Comment by thomgit** [comment]
+1

**Comment by torvitas** [comment]
+2

**Comment by fventuri** [comment]
Sven, I worked on your initial KVM/Qemu driver and I finished a few parts that were missing.
The code is here: https://github.com/fventuri/machine/tree/504-kvm-qemu-driver
This version should be able to create/start/stop/remove a docker machine locally with the KVM/Qemu driver.
It still needs some cleaning and can definitely be improved, but it at least somewhat functional.

Please give it a try and let me know what you think and if you had any problems with it.

Franco

**Comment by clnperez** [comment]
@fventuri Do you have a PR for this that I should be commenting on? I tried it out and it worked pretty great, except that I'm getting a connection refused error when connecting during a `docker-machine ls`.

**Comment by shuron** [comment]
+1

**Comment by fventuri** [comment]
@clnperez - I see @SvenDowideit has already a pull request (https://github.com/docker/machine/pull/650) that he is working on for the same thing.
Not sure if I should create another one, or what is the best way to work on this driver, since I am new here.

**Comment by mmarzantowicz** [comment]
What is the current status of KVM/Qemu driver for Docker Machine? Are there any more or less finished and working implementation? Is is going to be included in Machine any time soon?

Maybe it's to much questions but I'm interested in such driver, I've seen a lot of other drivers come recently to Machine but not this one.

**Comment by lazyval** [comment]
Having such driver will enable running ARM based docker images on x86 host system, e.g. developing for raspberry pi using your macbook laptop. Unfortunately, it's not possible right now since virtualbox does not support hardware emulation.

**Comment by JurrianFahner** [comment]
+1

**Comment by torvitas** [comment]
+1

**Comment by nathanleclaire** [comment]
We are introducing a driver plugin model with 0.5.0 and any user who wants to build and distribute such a driver is free to rock and roll!

**Comment by SvenDowideit** [comment]
@fventuri 2 years later, so I'm guessing you're not interested in this anymore, but I'm using your work in https://github.com/jigtools/docker-machine-driver-qemu

**Comment by fventuri** [comment]
@SvenDowideit Wow! Time flies! I hadn't realized that I wrote that stuff two years ago already.
Anyway, I moved on to other projects, so feel free to use all that code and documentation for your projects.

Good luck,
Franco
