### ISSUE TITLE
vmwareFusion 'stop' too harsh

### ISSUE THREAD

**Issue by leth** [docker/machine#507]
After a stop/start the Docker daemon fails to start due to empty trust file.

The process I followed is roughly this:

- docker-machine create -d vmwarefusion  --vmwarefusion-boot2docker-url https://github.com/cloudnativeapps/boot2docker/releases/download/v1.4.1-vmw/boot2docker-1.4.1-vmw.iso boot2docker
- docker pull busybox
- docker-machine stop
- docker-machine start
- docker ps (fails, VM daemon never starts)

Looking into the logs, the file at `/var/lib/docker/trust/official.json` was empty, and docker failed when parsing it.

Manually running `sync` in the VM after pulling busybox allowed the daemon to start okay later, so it looks like what is needed is a more graceful `stop` implementation.

**Comment by frapposelli** [comment]
Good call, putting boot2docker/boot2docker#638 to reference the need to appropriately run shutdown through OVT.

**Comment by ehazlett** [comment]
I have a PR to use your custom ISO for the time being.  Once that is merged
we should have everything in the custom ISO to do this correct?

**Comment by frapposelli** [comment]
@ehazlett I need to double check that, I'm not 100% sure.

**Comment by ehazlett** [comment]
Thanks

**Comment by leth** [comment]
Are you certain you need the guest tools for this? Perhaps there is an API call to simulate the power button being pressed?

**Comment by frapposelli** [comment]
As a reference, this issue depends on boot2docker/boot2docker#747
