### ISSUE TITLE
creating a new hyper-v machine changes the conf on my cmd

### ISSUE THREAD

**Issue by SvenDowideit** [docker/machine#509]
I don't use the default fonts in my win8.1 terminal, and when I run `docker-machine.exe create --driver hyper-v test` in either msys-bash, or cmd, it changes the window to use a bigger heavier font.

**Comment by SvenDowideit** [comment]
@jeffmendoza

**Comment by rgardler** [comment]
I can't reproduce this. Can you please confirm you are still seeing this behavior with the current release. If it does happen can you provide steps to reproduce?

**Comment by nathanleclaire** [comment]
We've cleaned up the output a bit so please re-open if you run into any more issues
