### ISSUE TITLE
Hyper-v gets in a confused state if it fails to create a machine.

### ISSUE THREAD

**Issue by SvenDowideit** [docker/machine#511]
I ran `docker-machine create --driver=hyper-v msys` and it failed, as i did not create a hyper-v vswitch first.

I then created one, and re-ran that create, it failed with msys already exists - though the hyper-v manager shows that its not created. So I tried killing it (which really is not a good name, as I'm trying to delete it - generally, road kill leaves mess lying around, and users want to be able to clean up)

killing it failed too.

```
svend_000@BIG ~/Downloads
$ docker-machine_windows_amd64-nightly.exe create --driver hyper-v msys
←[31mERRO←[0m[0000] Error creating machine: Machine msys already exists
←[33mWARN←[0m[0000] You will want to check the provider to make sure the machine
 and associated resources were properly removed.
←[31mFATA←[0m[0000] Error creating machine

svend_000@BIG ~/Downloads
$ docker-machine_windows_amd64-nightly.exe  kill msys
←[31mFATA←[0m[0000] exit status 1

svend_000@BIG ~/Downloads
$ docker-machine_windows_amd64-nightly.exe create --driver hyper-v msys
←[31mERRO←[0m[0000] Error creating machine: Machine msys already exists
←[33mWARN←[0m[0000] You will want to check the provider to make sure the machine
 and associated resources were properly removed.
←[31mFATA←[0m[0000] Error creating machine
```

**Comment by SvenDowideit** [comment]
@jeffmendoza

**Comment by ehazlett** [comment]
As the docs state, an existing vswitch must be created.  This is the same behavior on all providers that create partial resources (i.e. ec2 keys, security groups, azure cloud deployments, etc).  We chose not to auto-remove these as it was potentially dangerous and we didn't want to make assumptions by removing something that could be debugged.

**Comment by jeffmendoza** [comment]
Yes, expected behavior. `machine rm -f <name>` should clean everything up. If that doesn't work, there is a bug.

**Comment by SvenDowideit** [comment]
there is a bug.

**Comment by SvenDowideit** [comment]
closing, though the errors make it feel really brittle atm

**Comment by jeffmendoza** [comment]
kill is force shutdown
