### ISSUE TITLE
Azure - connect to existing docker instance

### ISSUE THREAD

**Issue by leon** [docker/machine#515]
I created a docker instance via azures portal, only to have a hard time getting it going from my local machine.

it would be great if you could connect to your already up and running docker instances.

**Comment by sthulb** [comment]
This is something that would be nice for all drivers if possible.

**Comment by cartolari** [comment]
This is also required for deployments, if docker-machine can create and run commands on a bunch of drivers, it could be used for deploy to, so it needs some way to share the machines it creates and add existing ones.

**Comment by jeffmendoza** [comment]
#406 is the answer IMO

**Comment by ehazlett** [comment]
I agree with @jeffmendoza.  I think this would be what the generic driver provides.  Maybe in the future we could add a discovery mechanism to help import.
