### ISSUE TITLE
Configuring the DNS server that is used by docker builds

### ISSUE THREAD

**Issue by jamshid** [docker/machine#521]
Hi, will there be a standard way to set and change the docker machine's DNS server, or at least add /etc/hosts entries?

Currently my Dockerfile's reference a package manager cache and http proxy cache by hostname (`apt-cacher-ng1` and `polipo1`). The first container I build and run is a DNS server (`dnsmasq`), then I set `EXTRA_ARGS="--dns 172.17.42.1 --dns-search=."` in  `/var/lib/boot2docker/profile` and restart my docker server.

Btw my dnsmasq container actually watches docker events and updates a hosts file, so that containers can access each other by name without being explicitly linked. But I guess I should be using links or a real docker networking/orchestration service.

**Comment by ehazlett** [comment]
We are hoping to move to cloudinit soon.  This will allow almost full customization of the instance.  Thanks!

**Comment by mgasner** [comment]
is this still in pipeline?

**Comment by mgasner** [comment]
@ehazlett looks like cloudinit might be a dead letter? https://github.com/docker/machine/issues/124 and https://github.com/docker/machine/issues/1185?

**Comment by mikeatlas** [comment]
+1 I'd like this re-opened...

**Comment by jamshid** [comment]
I think the desire to configure the DNS server used by the docker server itself lives on in https://github.com/docker/machine/issues/2234.
