### ISSUE TITLE
Creating VirtualBox VMs in OVF format.

### ISSUE THREAD

**Issue by gozes** [docker/machine#522]
Here is an example of why OVF support would be great. Assuming that company/client X is not using docker, if they did I could just give them the container(s) with the app, but they are using a virtualization product(VMware, Xen, Hyper-V etc..). I, as the developer, can crate, setup and configure the VM(s) in OVF on my system and hand them off to IT at campany/client X to be deployed without worry that what I give them wouldn't work on there infrastructure.

**Comment by ehazlett** [comment]
We currently do not package any of the VMs up.  Perhaps this would be related to #260

**Comment by sthulb** [comment]
I looked into creating OVA VMs in #260. It's a bit of a pain with virtualbox. The import doesn't give you complete control over your FS. Also, virtualbox likes to copy them instead of using the OVA directly.

**Comment by ehazlett** [comment]
We have no current plans of exporting local machines besides configuration.

**Comment by thalesfc** [comment]
+1 on this feature.
