### ISSUE TITLE
virtualbox driver fails when vbox is not in PATH

### ISSUE THREAD

**Issue by SvenDowideit** [docker/machine#525]
testing on my boot2docker installer based windows setup, and it seems the reason we added a default path for VBoxManage.exe is that its not always in the PATH.

(this is in an MSYS-git bash shell)

```
svend_000@BIG ~/Downloads
$ docker-machine_windows-amd64.exe create --driver=virtualbox vbox2
←[31mERRO←[0m[0000] Error creating machine: VBoxManage  failed: exec: "VBoxManag
e": executable file not found in %PATH%
←[33mWARN←[0m[0000] You will want to check the provider to make sure the machine
 and associated resources were properly removed.
←[31mFATA←[0m[0000] Error creating machine
```

**Comment by SvenDowideit** [comment]
the code we use to cater for different versions of vbox, as they don't all set the same env:

```
        cfg.VBM = "VBoxManage"
        if runtime.GOOS == "windows" {
                p := "C:\\Program Files\\Oracle\\VirtualBox"
                if t := os.Getenv("VBOX_INSTALL_PATH"); t != "" {
                        p = t
                } else if t = os.Getenv("VBOX_MSI_INSTALL_PATH"); t != "" {
                        p = t
                }
                cfg.VBM = filepath.Join(p, "VBoxManage.exe")
        }
        flags.StringVar(&cfg.VBM, "vbm", cfg.VBM, "path to VirtualBox management utility.")
```

**Comment by sthulb** [comment]
We should pull it out of the registry but still have the ability to override it with an ENV var.

**Comment by SvenDowideit** [comment]
ok, I'll add some code to use the registry - though that too does not persist over different versions of virtualbox.

**Comment by SvenDowideit** [comment]
btw - these ENV's are the ones set by the VirtualBox installer, not by users.

**Comment by SvenDowideit** [comment]
@sthulb @ehazlett can we consider using something like https://github.com/luisiturrios/gowin to query the registry? seeing https://golang.org/src/mime/type_windows.go does not make me eager to write our own (as the VMWare driver seems to need something too)

**Comment by sthulb** [comment]
Someyhing like that lib would be great. We can't use that one though since its under GPL

**Comment by ehazlett** [comment]
yeah as @sthulb said it's GPL -- we need a different one.
