### ISSUE TITLE
virtualbox driver on windows doesn't mount to the local file system yet 

### ISSUE THREAD

**Issue by cvuijst** [docker/machine#529]
As discussed on IRC, after running a "docker-machine create" on Windows, the local file system is not mounted in the created docker environment. It works out of the box gracefully on OSX.
This leads possibly to a non implemented feature on Windows: See: https://github.com/docker/machine/blob/master/drivers/virtualbox/virtualbox.go#L289
Currently as a workaround, you can do this manually on the windows CLI having VBoxManage in your path through e.g.:
     $/> VBoxManage controlvm dummy_env acpipowerbutton
     $/> VBoxManage sharedfolder add dummy_env --name Users --hostpath c:/Users --automount
     $/> VBoxManage startvm dummy_env --type headless
Where "dummy_env" is the name of the created environment.
It would be nice to have this on Windows as well.

**Comment by ehazlett** [comment]
@SvenDowideit @jeffmendoza what would be the best path to mount?  is there an env var for the user home dir on windows?  i would think so.

@SvenDowideit perhaps b2d already has this solved and i could reference it from somewhere?

**Comment by cvuijst** [comment]
I took a look at the VMs created in the VBox management UI on OSX and Windows, it looks like for boot2docker:
* Windows: "c/Users" folder gets mounted to "c:\Users" 
* OSX: "Users" folder gets mounted to "/Users"
There is a platform difference there. I'm not sure that was the original intention though.
Currently, for docker-machine on OSX:
* "Users" gets mounted to "/Users"

**Comment by jeffmendoza** [comment]
C:\Users would be fine

**Comment by dsebastien** [comment]
There's actually a variable for the user's home folder: %USERPROFILE%.

**Comment by atomi** [comment]
Is it safe to assume that volume mounting will never work on Windows using docker proxy to boot2docker and virtual box? It seems the best solution right now is to use an ubuntu vagrant box, mount your preferred folders and run all commands via a putty terminal. We may as well run docker machine on virtual box as well. Or wait for docker daemon to get ported to Windows which will be extremely surprising to see.

**Comment by ehazlett** [comment]
@atomi that's the goal.  the shared folder support should work we just need to map it.

**Comment by carletes** [comment]
Any plans to have this working also for Linux VirtualBox hosts (not just Windows and OS X) for 0.2.0?

**Comment by sthulb** [comment]
@carletes Yes, there should be universal support for all of our supported OSs

**Comment by atomi** [comment]
Yeah so this won't be on 0.2.0?

**Comment by ehazlett** [comment]
@atomi this is pushed to 0.3.0

**Comment by atomi** [comment]
Wow yeah.. Great work! I'm really excited to try it. Thanks!

**Comment by ehazlett** [comment]
@atomi thanks!  and i would love to be able to test -- right now it looks like there is no way to actually get the container to run but that fix will be coming as part of the "better Windows experience" task for this sprint :)

**Comment by ehazlett** [comment]
Closing as #993 is merged.
