### ISSUE TITLE
vmware fusion machine loses keys when stopped/restarted

### ISSUE THREAD

**Issue by ehazlett** [docker/machine#532]
When stopping a VMware fusion machine the docker daemon is no longer accessible nor is ssh etc.

**Comment by ehazlett** [comment]
@frapposelli ^

**Comment by frapposelli** [comment]
Yes, I'm aware of this, it's part of the whole "seeding disk" problem, directly related to #430 

Working hard on these this week :smile:

**Comment by ehazlett** [comment]
awesome, thanks!

**Comment by frapposelli** [comment]
As a reference, this issue depends on boot2docker/boot2docker#747

**Comment by pdevine** [comment]
I run in to the same problem.  If a vm gets powered off (either through machine, a reboot, etc.), it's no longer possible to ssh into the machine and things like "docker ps" start failing.  I'm using the 0.1.0 release.
