### ISSUE TITLE
support github enterprise urls for b2d

### ISSUE THREAD

**Issue by ehazlett** [docker/machine#537]
We should support Github enterprise URLs for b2d.  See https://github.com/boot2docker/boot2docker-cli/pull/339

**Comment by sthulb** [comment]
We should start putting these in a 0.2 milestone.

**Comment by ehazlett** [comment]
Once we have it scoped we will.

**Comment by razic** [comment]
@ehazlett does this have to do with the `--url` provisioner? if so, can you explain what the `--url` provisioner is?

**Comment by ehazlett** [comment]
@razic the `--url` simply adds an existing host to the machine store.  however, i don't particular like it because it doesn't do anything with creds, certs, etc.  I would rather use the Generic Driver (#406) which imports the ssh key and could setup the auth.

**Comment by databus23** [comment]
@ehazlett  @sthulb I started working on this and then discovered #603. Whats the status on this? Is this still being worked on. Is it worth looking into this or should I jus be patient. :)

**Comment by sthulb** [comment]
@darabus23 go ahead. I closed my PR

**Comment by nathanleclaire** [comment]
@databus23 Do you still have interest in working on this?

**Comment by databus23** [comment]
@nathanleclaire I do. i got distracted by other tasks and this fell off the desk. That's being said I'm one week away from a two week vacation and won't be able to attend to this before the vacation. So this will linger for at least three more weeks.

**Comment by nathanleclaire** [comment]
@databus23 No problem, just checking in.

**Comment by dmp42** [comment]
Hey @databus23 - do you still have plans to work on this?

**Comment by databus23** [comment]
@dmp42 Yes, looking into it now.

**Comment by jeanlaurent** [comment]
Closing since this is fixed by #1856
