### ISSUE TITLE
machine change ip addresses after reboot the host.

### ISSUE THREAD

**Issue by rossbachp** [docker/machine#540]
I create and remove some machines. After reboot my Mac the ip address are don't  stable.  The DHCP virtualbox daemon use the first one...

```
$ docker-machine ls
NAME     ACTIVE   DRIVER       STATE     URL
dev2              virtualbox   Stopped   
dev3              virtualbox   Stopped   
tomcat   *        virtualbox   Stopped   
$ docker-machine start tomcat
INFO[0000] Waiting for VM to start...                   
$ docker $(docker-machine config tomcat) ps
FATA[0000] An error occurred trying to connect: Get https://192.168.99.100:2376/v1.16/containers/json: x509: certificate is valid for 192.168.99.103, not 192.168.99.100 
```

How I can regenerate the certs and upload it to the box?
The original boot2docker regenerate the certs after an ip address change...

**Comment by md5** [comment]
This looks like a duplicate of #531

**Comment by rossbachp** [comment]
Many thanks! The problem is that the current docker-machine implementation generate there own certs! See /var/lib/boot2docker/profile but virtualbox change the ip addresses after reboot my MAC host. The boot2docker regeneration stuffs only works at the original certs path. We need a regen certs command at docker-machine to upload the correct one...
