### ISSUE TITLE
machine should tell the user if a drivers functionality is not implemented

### ISSUE THREAD

**Issue by metcalfc** [docker/machine#542]
For example, docker-machine upgrade on VMware Fusion. The command just returns. We should tell the user that its not implemented so they don't have to come here and read the code.

**Comment by sthulb** [comment]
+1

**Comment by ehazlett** [comment]
Thanks for reporting.  The fusion driver needs to implement something like https://github.com/docker/machine/blob/master/drivers/rackspace/client.go#L50.

We should include this behavior in the core refactor as well.  Let drivers specify what is supported and what isn't.

**Comment by nathanleclaire** [comment]
`upgrade` now works in `vmwarefusion`, so I'm closing this.  Agree we need to be clearer about what's supported and not in general though.
