### ISSUE TITLE
x509 and openstack

### ISSUE THREAD

**Issue by razic** [docker/machine#549]
trying to run `machine-create` with `openstack` driver but keep getting this: 

```bash
ERRO[0000] Error creating machine: Get https://horizon.corp.foo.com/: x509: certificate signed by unknown authority
```

**Comment by ehazlett** [comment]
This is probably in the gophercloud lib not allowing self-signed certs.

/cc @smashwilson @ggiamarchi

**Comment by smashwilson** [comment]
Yes, that's exactly it. Fortunately, with rackspace/gophercloud#365 and rackspace/gophercloud#367 merged, Gophercloud master will allow us to override the `http.Client` used for requests throughout the library, which will let us customize the TLS configuration, among other things.

I'm thinking of adding an `--openstack-untrusted` option to the OpenStack driver. Is that reasonable, or is there a more global option I can hook? It seems to me that we would ultimately want the ability to set custom TLS credentials (CA, cert, key) as well, which adds quite a few options to a driver that already has quite a few.

**Comment by ehazlett** [comment]
Let's start with the option to get it working (perhaps `--openstack-insecure` to match golang).  We will probably want to have a global option eventually as I'm sure this won't be the only driver that will need custom TLS settings.

**Comment by smashwilson** [comment]
:+1: Sounds good to me. I'll start a PR later today.

**Comment by smashwilson** [comment]
Nuts, a few other things came up - I doubt I'll get to this. I should have a fix in soon.

**Comment by ehazlett** [comment]
Ok thanks!

**Comment by razic** [comment]
@ehazlett @smashwilson I don't actually think the cert is self-signed in my case. Look here:

Got any ideas?

![screen shot 2015-02-19 at 11 09 29 am](https://cloud.githubusercontent.com/assets/225005/6273876/d6bd12fc-b827-11e4-9f30-b85932397e7b.png)

**Comment by smashwilson** [comment]
@razic: Interesting. I wonder if they aren't including intermediate CA certificates? Sometimes, you can hunt those down and trust them yourself to validate the connection...

**Comment by razic** [comment]
Do you have to place the intermediary certificates in the same directory as the main one?

**Comment by smashwilson** [comment]
@razic: You'd need to install it as a trusted certificate in your operating system. From the screenshot I'm guessing that you're on a Mac, so [these instructions](http://support.apple.com/kb/PH18677) might be what you need.

> Also do you have a slack channel (preferably) or IRC?

I do hang out on Freenode very occasionally, and we have an internal Slack for my team at Rackspace, but I don't believe we have a public one. Also I'm personally about to be mostly unavailable until next week, so I'm probably not the best person to contact in any case. Did you just need help with SSL?

**Comment by razic** [comment]
@smashwilson i added the cert and gave it all permessions but now i'm getting this:

```
ERRO[0000] Error creating machine: Post https://[OMITTED]:5000/v2.0/tokens: x509: cannot validate certificate for [OMITTED] because it doesn't contain any IP SANs
```

**Comment by ehazlett** [comment]
make sure you are using the hostname and not IP.

**Comment by razic** [comment]
I tried both.

**Comment by ehazlett** [comment]
@razic and you got the IP SANs error with the hostname?
