### ISSUE TITLE
Proposal: Add Driver for Linode

### ISSUE THREAD

**Issue by stevesmename** [docker/machine#552]
Add driver for creating docker machines in Linode through the Linode APIs..

Resources:
https://www.linode.com/api

**Comment by stevesmename** [comment]
Just a note, I am working on this initiative and will reference this ticket (closed or open) when I have a PR ready.

**Comment by stevesmename** [comment]
Clone of #268

**Comment by ehazlett** [comment]
FYI there is a proposed Linode driver here: https://github.com/docker/machine/pull/268

**Comment by ehazlett** [comment]
Sorry -- i didnt' see the above comment :)
