### ISSUE TITLE
Create an internal API so Machine can be used as a library

### ISSUE THREAD

**Issue by ehazlett** [docker/machine#553]
This will enable machine to be used as a lib and lay the groundwork for machine server.

This will provide a more manageable way to interact with machine instead of working directly with the store and host individually.  For example, right now we use `store.Create` which calls `host.Driver.Create` etc.  This will split up those operations so that the store does not handle provisioning, simply storing machine configuration data.

- [x] Utilize new Driver architecture (#554)
- [x] Move store into package
- [x] Provide abstraction around common operations (see https://github.com/docker/machine/pull/550/files#diff-604f4192deea5adf9c159e5f88f64630)
- [x] #767 

Refs: #550

**Comment by nathanleclaire** [comment]
Before we jump headlong into implementing a server, perhaps a good intermediate step would be to create (and dogfood) some good Go bindings / library?  @ibuildthecloud expressed an interest in that for their use case and I think it would be good to get people going / using it right away until the API fully takes shape.

**Comment by ehazlett** [comment]
That is what this is.

**Comment by ehazlett** [comment]
Sorry I was responding to your email which had a different comment.

Yes, this is the placeholder for an internal, non-http API to be used as a lib.

**Comment by sthulb** [comment]
- [ ] Share flags
- [ ] Driver structure
- [ ] Metadata
- [ ] Error handling
- [ ] Logging

**Comment by ehazlett** [comment]
@sthulb added your checklist to the description -- thx!

**Comment by nathanleclaire** [comment]
Yep, I realized that after my first comment so I updated it to just say we should loop potential consumers of the API / bindings in on it.

**Comment by ehazlett** [comment]
Updated scope to be more manageable for this first pass.  We can iterate after feedback.

**Comment by ehazlett** [comment]
This is pending #699 as they both affect the backend provisioning.
