### ISSUE TITLE
move ssh operations to crypto/ssh

### ISSUE THREAD

**Issue by ehazlett** [docker/machine#555]
Remove the shell out to `ssh` and use `crypto/ssh` instead.

This should do the following:
- refactor the key generation from the `ssh` command into `crypto/ssh`
- refactor the functionality from GetSSHCommand from `ssh` into `crypto/ssh`

**Comment by andrewwatson** [comment]
+1

**Comment by bfirsh** [comment]
Work in progress here: https://github.com/docker/machine/pull/730

**Comment by ahmetalpbalkan** [comment]
+1 this would improve windows command line prompt (cmd.exe) & PowerShell experience a great deal as Windows by default doesn't have ssh.exe in PATH.

**Comment by ahmetalpbalkan** [comment]
A big +1 for this! This would improve windows command line prompt (cmd.exe) & PowerShell experience a great deal for users as Windows by default doesn't have ssh.exe in PATH.

**Comment by hairyhenderson** [comment]
I think this was resolved by #909 - right? /cc @ehazlett

**Comment by ehazlett** [comment]
@hairyhenderson yes should be.  @sthulb #909 replaced all of the ssh shell-out correct?

**Comment by sthulb** [comment]
Ja!

**Comment by ehazlett** [comment]
sweet.  closing.  thx!
