### ISSUE TITLE
Running machine commands with multiple machine names silently fails

### ISSUE THREAD

**Issue by bfirsh** [docker/machine#563]
```
$ docker-machine start machine1 machine2
```

Only starts machine1. If commands don't support >1 arguments, I would expect it to complain instead of silently not start machine2.

**Comment by ehazlett** [comment]
@nathanleclaire feel free to use (or not) my branch https://github.com/ehazlett/machine/tree/commands-with-multiple-machine-names where i started this.

thx

**Comment by nathanleclaire** [comment]
I'm going to use that branch :+1:
