### ISSUE TITLE
VSphere Driver doesn't detect absence of "govc" utility

### ISSUE THREAD

**Issue by andrewwatson** [docker/machine#564]
If you don't have 'govc' installed, the error you get is on the mkdir command but it doesn't tell you anything useful at all because the error in vc_conn.go gets squashed.

The error you get is 
```
ERRO[0001] Error creating machine: Unable to mkdir on datastore qts-vnxe-t2-prod-vms02 due to  
```

i'm working on some fixes to bubbles errors up to the user correctly

**Comment by ehazlett** [comment]
It is listed in the docs (https://github.com/docker/machine#vmware-vsphere) but I agree we should notify the user more gracefully.

**Comment by andrewwatson** [comment]
Well, the way it is right now it loses any error from exec.Command() no matter what it is....

**Comment by ehazlett** [comment]
Ah gotcha -- thx for the PR to fix :)
