### ISSUE TITLE
Proposal: use the govmomi library for vsphere instead of exec.Command to run the govc binary

### ISSUE THREAD

**Issue by andrewwatson** [docker/machine#572]
By shelling out with exec.Command() to run the govc binary it's harder to handle errors that are generated and deal with them effectively.  It also seems problematic that you have to have this other binary installed in your $GOPATH in order to use this library.

Using the govmomi library directly should be very straightforward and allow machine to get more detailed information about an instance after it's created.  It would also make it easier to support more options going forward.  

Also, most of the code in the existing driver deals with formatting command line arguments and ssh commands and we could do away with all of that.

**Comment by ehazlett** [comment]
I like the idea of this.  Thoughts @frapposelli ?

**Comment by frapposelli** [comment]
Completely agree, the move was in the cards already.

**Comment by andrewwatson** [comment]
The only part that I don't have a good grasp on is the conversion of iso to template.  The rest I have code to look at for inspiration...

**Comment by dgageot** [comment]
Fixed with https://github.com/docker/machine/pull/1522
