### ISSUE TITLE
Machine puts boot2docker images in ~/.docker/images

### ISSUE THREAD

**Issue by bfirsh** [docker/machine#580]
We shouldn't be polluting to top-level `~/.docker` namespace.

Perhaps `~/.docker/machine/boot2docker-cache`?

**Comment by bfirsh** [comment]
Maybe it's a bit weird then that we have `~/.docker/machines` and `~/.docker/machine`?

**Comment by bfirsh** [comment]
Oh – I see that the cert path is `~/.docker/machines/.client`.

I don't think I like this - paths with dots in them make them very hard to find. The only reason `.active` exists is because it is a piece of metadata for that directory.

Perhaps we could start `~/.docker/machine/...` and have:

 - `~/.docker/machine/machines`
 - `~/.docker/machine/boot2docker-cache`
 - `~/.docker/machine/certs`

... etc

**Comment by sthulb** [comment]
Seems a little clearer, but we should include .active too (if we want keep it around)

**Comment by ehazlett** [comment]
This will need a refactor to store as it just looks for the non-hidden directory names.  I chose the `.client` so I can just not include hidden dirs but I'm more than happy to change it.

**Comment by ehazlett** [comment]
@sthulb is working on this one (and the issues in #217) (i can't manage teams)

**Comment by bfirsh** [comment]
@sthulb @ehazlett Are we going to land this before tomorrow? At this late stage, a quick fix might be more suitable.

**Comment by sthulb** [comment]
I'll submit a quick fix with the ISOs being stored in ~/.docker/machines/.images for now.

My next PR with the versioning, will correct it later.
