### ISSUE TITLE
Command usage should explain what arguments mean

### ISSUE THREAD

**Issue by bfirsh** [docker/machine#583]
```
$ docker-machine start --help                                                                                                                                                
NAME:
   start - Start a machine

USAGE:
   command start [arguments...]
```

This should explain that the arguments are machine names, and that if no machine is provided the active one will be used.

**Comment by sthulb** [comment]
This is a problem with codegangsta/cli. It doesn't actually offer this. We should either use our own CLI lib or perhaps alter codegangsta/cli.

I'd also like to see descriptions of flags be a little clearer and offer flag types similar to curl (`--flag <hint> <description>`)

**Comment by bfirsh** [comment]
@sthulb Can't we add it to the description for the command?

**Comment by ehazlett** [comment]
we can add it to the `Usage` as a long description.

**Comment by ehazlett** [comment]
@bfirsh is #585 what you were looking for?
