### ISSUE TITLE
Digital Ocean driver prints out a bunch of debugging output

### ISSUE THREAD

**Issue by bfirsh** [docker/machine#587]
```
$ docker-machine create -d digitalocean --digitalocean-access-token=$DIGITALOCEAN_ACCESS_TOKEN --swarm --swarm-master --swarm-discovery=token://... swarm-master
INFO[0000] Creating SSH key...
INFO[0000] Creating Digital Ocean droplet...
INFO[0004] Waiting for SSH...
INFO[0073] Configuring Machine...
+ [ https://get.docker.com/ = https://get.docker.com/ ]
+ sh -c apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 36A1D7869245C8950F966E92D8576A8BA88D21E9
gpg: requesting key A88D21E9 from hkp server keyserver.ubuntu.com
gpg: key A88D21E9: public key "Docker Release Tool (releasedocker) <docker@dotcloud.com>" imported
gpg: Total number processed: 1
gpg:               imported: 1  (RSA: 1)
+ sh -c echo deb https://get.docker.com/ubuntu docker main > /etc/apt/sources.list.d/docker.list
+ sh -c sleep 3; apt-get update; apt-get install -y -q lxc-docker
+ sh -c docker version
INFO[0135] Configuring Swarm...
INFO[0142] "swarm-master" has been created and is now the active machine.
INFO[0142] To point your Docker client at it, run this in your shell: $(docker-machine env swarm-master)
```

**Comment by ehazlett** [comment]
When we moved to using the script to install this happened.  Looking.

**Comment by ehazlett** [comment]
@bfirsh so here's why: when we moved to the `curl -sL get.docker.com ...` install process, apparently it outputs all of that to `stderr`.  I've tested this by using `cmd.Stderr = ioutil.Discard` and the debug is gone.  However, I'm not sure we want to toss out stderr.

The other way around would be to refactor the install to split out and do the same thing the script does only without using it (import apt gpg key, add the sources, update, install).

**Comment by andrewwatson** [comment]
is it just a matter of adding curl options?

**Comment by ehazlett** [comment]
@andrewwatson i don't think so.  we already use `-s` (silent) and the output isn't coming from `curl` it's coming from the script that is passed.

**Comment by sthulb** [comment]
@ehazlett: the only thing that makes sense to me is to save the stderr contents to a buffer and then do a check for the docker bin afterwards, if it fails output the stderr buffer.
