### ISSUE TITLE
Set the hostname of created machines to match the machine name

### ISSUE THREAD

**Issue by robhaswell** [docker/machine#59]
When creating and managing multiple machines, it is confusing to identify which machine you have logged into after using `machine ssh`. Setting the hostname to match the machine name would be useful in this scenario.

(woops I initially raised this against swarm by accident)

**Comment by sthulb** [comment]
If I've read this issue correctly, the implementation should be:
  
  1. Set a hostname on creation
  1. add `machine move/rename` which will change a machine's name in the internal data store and change the hostname
  1. For move/rename: Error if the name is taken in the internal data store.

**Comment by bfirsh** [comment]
I don't think renaming is necessary to start with - that's already being worked on here https://github.com/docker/machine/issues/59

At the moment we give hostnames long random names. I think we should set the name on the provider to be the name given by the user, which normally is also the hostname given to the machine. For example – when you create a droplet on digital ocean, you give it a name, which is also used by the hostname.

**Comment by bfirsh** [comment]
Another thing to be aware of: the name given by the user might already exist on the provider. We should display useful error messages about this.

**Comment by sthulb** [comment]
I absolutely agree with setting the name on the provider too. Things like EC2 won't care since the unique criteria will be the instance id.

As per: 

> I don't think renaming is necessary to start with - that's already being worked on here #59
That's this issue :)

**Comment by ehazlett** [comment]
+1 for setting the name / hostname on the provider if supported.  I agree to leave renaming / moving out of this one -- I believe bfirsh meant #30 is being worked on for that.

**Comment by sthulb** [comment]
I'll give it a go :)

**Comment by bfirsh** [comment]
Oh whoops, yes, wrong issue. Sorry.

**Comment by ehazlett** [comment]
Closing as #219 has been merged.

**Comment by tlaguz** [comment]
How can I disable host renaming?
