### ISSUE TITLE
[DigitalOcean driver] Fails to remove created droplets after CTRL+C on create

### ISSUE THREAD

**Issue by nathanleclaire** [docker/machine#592]
I was creating some DO instances and the "Wait for SSH" bit was taking really long (possibly just straight-up freezing), so I hit `CTRL+C`.  I could see that they got created in the DO admin panel, so I'm not sure what the hangup was, but when I went to `docker-machine rm` the hosts they were still around and I just got a message saying:

```console
$ ./docker-machine_darwin-amd64 rm prod1 prod3
INFO[0000] Digital Ocean SSH key doesn't exist, assuming it is already deleted
INFO[0000] Digital Ocean droplet doesn't exist, assuming it is already deleted
INFO[0000] Digital Ocean SSH key doesn't exist, assuming it is already deleted
INFO[0000] Digital Ocean droplet doesn't exist, assuming it is already deleted
```

The assumption is bad!  They were _not_ deleted already.  Seems that the detection of their existence is off too.

Having the "broken" refs around in an error state is cool and expected but I think this seems a bug to me - `rm` should clean up instances that exist whether they're in a happy state or not.

**Comment by ehazlett** [comment]
Perhaps we need to `SaveConfig` earlier to get the creds, etc.

**Comment by knarz** [comment]
This seems to be an issue with other drivers as well. The instance gets created and if you `ctrl-c` while machine is waiting for ssh then the config ends up without the correct or any data.

So how about the `Create()` gets refactored to just do creation, then a `SaveConfig()` to end up in a defined state and use that to wait for ssh to get available?

**Comment by ehazlett** [comment]
@knarz We should be really close to that after this latest refactor.  We now have the drivers just creating the instance and then call "Provision" after that.  I will do some testing to see if this works with various drivers.

**Comment by nathanleclaire** [comment]
We need to revisit this in a different light given recent realizations
