### ISSUE TITLE
[VirtualBox] Trying to start an already started machine message isn't helpful

### ISSUE THREAD

**Issue by nathanleclaire** [docker/machine#593]
```console
$ ./docker-machine_darwin-amd64 start dev
ERRO[0000] exit status 1
```

Let's be sure to at least tell the user "what went wrong" (the machine is already started).

**Comment by ehazlett** [comment]
submitted #597 for the fix -- ideally we will have a better logging solution for the providers so we can get more detailed logs around these types of errors but at least this will prevent the error when trying to start a running machine.
