### ISSUE TITLE
Proposal: machine metadata

### ISSUE THREAD

**Issue by ehazlett** [docker/machine#598]
This will enable common metadata to be used with machines and not require the driver to implement them.  Example, is `swarm` support.  Each driver must implement `SwarmXX` due to the way the driver architecture is today.  This will enable new functionality without requiring the driver to be updated.

Sample Metadata:
- Name
- Provider
- Region (`us-east-1a`, `us-central-1a`, `nyc3`)
- MachineType (i.e. `t1.micro`, `f1.micro`, etc)
- Memory

These also might need data from the driver so we will want to keep that in mind when refactoring the driver architecture.  For example, instead of binding `t1.micro` in the metadata, we would do a lookup from the driver for something like `driver.GetMachineType` to account for resizes, etc.

Refs #553

**Comment by nathanleclaire** [comment]
I'm having a hard time wrapping my head around what this is exactly, although I think I might understand.  Essentially there would be some kind of common base that the drivers use, e.g.:

```go
type SomeDriver struct {
    metadata *drivers.Metadata
}

// ... now implement the rest of the methods
```

?

**Comment by ehazlett** [comment]
Correct.  If we refactor the internal api / store this might not be necessary.  But for now, the idea was that instead of having to add something like `SwarmHost` etc. for each driver, the metadata would be able to hold that.

**Comment by nathanleclaire** [comment]
I think this is covered by @hairyhenderson `BaseDriver` PR
