### ISSUE TITLE
azure: cert error when creating machine

### ISSUE THREAD

**Issue by ehazlett** [docker/machine#600]
Receive this:

```
An error occurred trying to connect: Get https://machine-demo-azure-0.cloudapp.net:2376/v1.17/containers/json: x509: certificate is valid for , not machine-demo-azure-0.cloudapp.net
```

**Comment by ehazlett** [comment]
Perhaps a race condition on `GetIP`?

/cc @jeffmendoza

**Comment by ehazlett** [comment]
Yeah looks like it -- a second create works fine.

**Comment by SvenDowideit** [comment]
I still get this issue - and when I create a second azure vm too.

**Comment by SvenDowideit** [comment]
@ehazlett @jeffmendoza can we please re-open this?

**Comment by jeffmendoza** [comment]
Let me get the error straight:

1. Machine creates the VM in Azure.
2. Machine queries Azure for the hostname, example: my-vm.cloudapp.net, however Machine is getting an empty string from the Azure driver.
3. Machine uses the hostname in the Common Name field to create the TLS certificates that are used for secure docker communication.
4. Machine sets up the certificates on the created host
5. Docker is run with the certificates
6. The Docker client is doing server verification.
7. The server's certificate's CN field is ''
8. The Docker client is seeing the server as "my-vm.cloudapp.net" and is then failing to verifty the server's identity.

???

If so, @SvenDowideit can you run the docker client with only --tls, not --tlsverify to confirm that this works?

Sounds like we need better error checking when getting the Azure VM's name before creating the TLS certificates.

**Comment by squillace** [comment]
confirmed repro here on ubuntu and mac. Same precise string.

**Comment by jeffmendoza** [comment]
> Sounds like we need better error checking when getting the Azure VM's name before creating the TLS certificates.

I'm slow, looks like it's already fixed.

**Comment by ehazlett** [comment]
@jeffmendoza no actually it's not.  my fix didn't work for @SvenDowideit

**Comment by ehazlett** [comment]
@jeffmendoza fwiw that sounds like what's happening

**Comment by squillace** [comment]
i'm redoing right now, just to see, with rc5

**Comment by ehazlett** [comment]
@jeffmendoza actually it should always have a name right?  after the PreCreate check we are simply prepending the MachineName to cloudapp.net, right?

**Comment by jeffmendoza** [comment]
Yep: https://github.com/docker/machine/blob/master/drivers/azure/azure.go#L594
No actual call, the name is set on driver creation. I wonder how this could end up blank?

**Comment by squillace** [comment]
This worked fine last week, but since I can't see the backward releases, I can't tell you which of the rcs worked, but I think it was rc3...

**Comment by squillace** [comment]
sorry for the delay: fix worked nicely, thank you. Both on mac and ubuntu, in West US and West Europe, and propped apps happily. Nice work.

**Comment by ehazlett** [comment]
@squillace awesome -- thx for the help!
