### ISSUE TITLE
[amazonec2] Race causes machine to think instance doesn't exist and bail in create

### ISSUE THREAD

**Issue by nathanleclaire** [docker/machine#606]
I attempted a `docker-machine create -d amazonec2 foo` and got back an error:

```console
INFO[0000] Launching instance...
INFO[0005] Waiting for SSH on :22
INFO[0005] Configuring Machine...
ERRO[0005] Error creating machine: Non-200 API response: code=400 message=The instance ID 'i-b28ce948' does not exist
WARN[0005] You will want to check the provider to make sure the machine and associated resources were properly removed.
FATA[0005] Error creating machine
```

OK... this seems to be a bug in machine, since the instance most assuredly _does_ exist (I can see that it got created in the admin panel).  `docker-machine rm -f` cleaned up my local instance but the cloud resources (key, instance) still exist.

Second (somewhat related) problem:  Lingering keys (like we got with the previous step) can cause issues like:

```console
$ docker-machine create -d amazonec2 jungle
ERRO[0000] Error creating machine: There is already a keypair with the name jungle.  Please either remove that keypair or use a different machine name.
WARN[0000] You will want to check the provider to make sure the machine and associated resources were properly removed.
FATA[0000] Error creating machine
```

I don't know what to do about this.  It keeps making me think that we need some kind of a naming-scheme and automatic import as discussed in #248.  It would probably be more robust than saving the `config.json` at every possible turn.

**Comment by ehazlett** [comment]
Yeah I would love auto-cleanup but it's a delicate operation.  I was bit by the existing keypair today as well.

**Comment by sthulb** [comment]
I think if we interpret the errors from the API, we could clean up easier.

**Comment by jpetazzo** [comment]
The original error *might* be caused by the fact that the EC2 API is eventually consistent. When I wrote the dotCloud deployment scripts, each time I would create a resource (instance or volume) I would wait for the API to tell me that the resource actually exists before continuing (even though it's supposed to exist since it gave me its ID!).

Regarding cleanup: I'd love a cleanup command within machine itself, since the whole idea is to help people to not get dirty with the EC2 APIs and consoles :innocent:

**Comment by ehazlett** [comment]
@jpetazzo great point.  i think a cleanup function would be great.

**Comment by nathanleclaire** [comment]
Closing this -- `docker-machine rm jungle` tends to work pretty well now unless something went wacky

**Comment by cboettig** [comment]
Just a comment that I often get the same error:

```
Error with pre-create check: There is already a keypair with the name dev.  Please either remove that keypair or use a different machine name.
```

even when `docker-machine ls` shows no machines (and thus `docker-machine rm -f ` doesn't do anything), and sometimes even after deleting the `~/.docker/machine/certs` directory where those certifications exist.  I'm seeing this using the amazonec2 driver, and still experiencing this on docker-machine v0.5.0.  I'd love guidance on how to recover from this condition and if there's anything I can report that might help others better replicate and debug the issue.

**Comment by nathanleclaire** [comment]
@cboettig Sometimes there can be a situation where there is a keypair created in AWS, but Machine did not clean it up properly.  If you remove it in their admin panel, it should work fine.

**Comment by cboettig** [comment]
@nathanleclaire yup, that was it.  Thanks much!
