### ISSUE TITLE
[VirtualBox] Cannot re-create machine after deleting VM manually

### ISSUE THREAD

**Issue by jeffdm** [docker/machine#609]
If you delete a VM manually in virtualbox machine can't create anymore VMs with the same name.

To reproduce:

**Step 1: Create VM**
```
~/w/machine (master) $ machine create -d virtualbox dev
INFO[0000] Creating SSH key...                          
INFO[0000] Creating VirtualBox VM...                    
INFO[0006] Starting VirtualBox VM...                    
INFO[0006] Waiting for VM to start...                   
INFO[0040] "dev" has been created and is now the active machine. 
INFO[0040] To point your Docker client at it, run this in your shell: $(machine env dev)
```

**Step 2: Delete VM Manually via VirtualBox GUI**
Note that it doesn't matter whether you choose _Delete All Files_ or _Remove Only_ in the remove dialog.

![screen shot 2015-02-25 at 12 08 51 pm](https://cloud.githubusercontent.com/assets/251292/6375760/2b554fc8-bce7-11e4-9720-086b6a759291.png)

**Step 3: 2nd create fails**
```
~/w/machine (master) $ machine create -d virtualbox dev
ERRO[0000] Error creating machine: Machine dev already exists 
WARN[0000] You will want to check the provider to make sure the machine and associated resources were properly removed. 
FATA[0000] Error creating machine
```

I assume this is because machine keeps the `~/.docker/machine/dev directory.` It should detect that the VM is gone, but the files are there and delete them on the next call to `machine create`.

**Comment by ehazlett** [comment]
You can remove the directory by forcing it -- i.e. `docker-machine rm -f dev`.

**Comment by meticulo3366** [comment]
docker-machine rm -f does not work on creating a new docker machine on aws!
