### ISSUE TITLE
Proposal: eliminate "active host"

### ISSUE THREAD

**Issue by nathanleclaire** [docker/machine#616]
In the original `docker hosts` implementation that eventually became Machine in its present state, the notion of "active host" was useful and easy to control, since all of the code was inside of Docker and hijacking the value of `-H`/`DOCKER_HOST` was quite easy to do.  Now that Machine's been split into a separate tool, however, what was once a useful abstraction has become a huge source of headaches.  The "active" host doesn't really have much meaning anymore, as noted in discussion on #443 and elsewhere.  The user could easily "drift" their ostensible active host with `$(docker-machine env foo)` etc.

Additionally, consider this situation, which is still one of several outstanding issues today:

```console
$ ./docker-machine_darwin-amd64 create -d virtualbox dev
INFO[0000] Creating SSH key...
INFO[0001] Creating VirtualBox VM...
INFO[0008] Starting VirtualBox VM...
INFO[0008] Waiting for VM to start...
INFO[0041] "dev" has been created and is now the active machine.
INFO[0041] To point your Docker client at it, run this in your shell: $(docker-machine_darwin-amd64 env dev)
$ ./docker-machine_darwin-amd64 ls
NAME   ACTIVE   DRIVER       STATE     URL                         SWARM
dev    *        virtualbox   Running   tcp://192.168.99.123:2376
$ ./docker-machine_darwin-amd64 rm dev
$ ./docker-machine_darwin-amd64 ssh
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x6e61]

goroutine 16 [running]:
runtime.panic(0x6ac500, 0xae9c04)
        /usr/src/go/src/pkg/runtime/panic.c:279 +0xf5
main.cmdSsh(0x208c2c3c0)
        /go/src/github.com/docker/machine/commands.go:535 +0x791
github.com/codegangsta/cli.Command.Run(0x755390, 0x3, 0x0, 0x0, 0x815fd0, 0x2f, 0x8561b0, 0x57, 0x0, 0x0, ...)
        /go/src/github.com/docker/machine/Godeps/_workspace/src/github.com/codegangsta/cli/command.go:113 +0xeb2
github.com/codegangsta/cli.(*App).Run(0x208c020d0, 0x208be6000, 0x2, 0x2, 0x0, 0x0)
        /go/src/github.com/docker/machine/Godeps/_workspace/src/github.com/codegangsta/cli/app.go:156 +0xaea
main.main()
        /go/src/github.com/docker/machine/main.go:67 +0x7cd

goroutine 17 [runnable]:
runtime.MHeap_Scavenger()
        /usr/src/go/src/pkg/runtime/mheap.c:507
runtime.goexit()
        /usr/src/go/src/pkg/runtime/proc.c:1445

goroutine 18 [runnable]:
bgsweep()
        /usr/src/go/src/pkg/runtime/mgc0.c:1976
runtime.goexit()
        /usr/src/go/src/pkg/runtime/proc.c:1445

goroutine 19 [runnable]:
runfinq()
        /usr/src/go/src/pkg/runtime/mgc0.c:2606
runtime.goexit()
        /usr/src/go/src/pkg/runtime/proc.c:1445

goroutine 20 [runnable]:
os/signal.loop()
        /usr/src/go/src/pkg/os/signal/signal_unix.go:19
created by os/signal.init·1
        /usr/src/go/src/pkg/os/signal/signal_unix.go:27 +0x32
```

(If I'm a user new to machine, I don't have a clue how to even begin debugging this)

We could keep fixing and working around these issues (for instance, by automatically selecting another machine if it exists in the scenario of removing the active host), but I'd rather just remove active and be done with it.  Moving forwards to be able to do e.g. creation of multiple machines concurrently, automatically switching to an active machine on creation confuses things and complicates the logic that we need to maintain.

I think the `$(docker-machine env dev)` method is a pretty reasonable solution for now, and maybe we can revisit if/when true config lands in Docker, but for now I have a feeling that active will just confuse users a lot.

Also (somewhat embarrassingly), I didn't realize it until writing up this proposal, but adding support for multiple machine arguments for `stop`, `start`, `kill`, etc. accidentally caused a regression which stopped the "short form" (active host) versions from working, since they will just iterate through the args they have been given and run the command on each specified machine.  Rather than continue handling this special case, I'd rather just move forward with specifying machines explicitly. (_Side note for myself_: We should spit out help text instead of silently doing nothing like we are now there).

cc @ehazlett @bfirsh @sthulb

**Comment by ehazlett** [comment]
yes, +1 :)

**Comment by sthulb** [comment]
+1. I've always disliked it.

**Comment by bfirsh** [comment]
I would like us to consider https://github.com/docker/machine/issues/16 before we remove active hosts. `$(docker-machine env)` is a hack, not a permanent solution.

**Comment by nathanleclaire** [comment]
@bfirsh I'd say #16 has been considered thoroughly and I don't think anyone is against that UI, but it depends on (as yet unwritten) upstream dependencies which are tangled up in a bigger search for a config file: https://github.com/docker/docker/pull/10151  That's a _really_ non-trivial change and effectively contributing that back upstream will be difficult and time-consuming.  

In the interim, it would be better for Machine usability to remove "active" altogether.  It's one less thing for users to keep in their heads, and less surface area for things to go awry.

I don't think providing users with a way to set these via environment variables is a hack.  Environment variables are extremely common and supported on almost all platforms, they're not fragile and the subshell method makes no attempt to conceal what's happening behind the scenes, making it (relatively) easy to debug if something odd happens.

**Comment by jeffdm** [comment]
+1 to removal. As a consumer of machine, we will probably need the `active` concept. That said, we can keep track of the active VM ourselves via the unique name.

**Comment by nathanleclaire** [comment]
This is pretty well covered by the new active tracking stuff
