### ISSUE TITLE
docker machine command create vmwarefusion broken

### ISSUE THREAD

**Issue by stonevil** [docker/machine#630]
VMware Fusion 7.1.1

After command create -d vmwarefusion dev -D
VMware VM created and started.
But cannot boot. Boot2Docker image downloaded and attached to the VMware VM configuration but not enabled.

Check attached screenshot

![1](https://cloud.githubusercontent.com/assets/129196/6395891/d933d8f6-bde3-11e4-8565-780e2f448c8d.png)

**DEBUG LOG**
INFO[0126] Creating VM...
VixDiskLib: Invalid configuration file parameter. Failed to read configuration file.
Creating disk '~/.docker/storage/dev/dev.vmdk'
Virtual disk creation successful.
DEBU[0126] executing: /Applications/VMware Fusion.app/Contents/Library/vmrun start ~/.docker/storage/dev/dev.vmx nogui
…

**VMX FILE**
.encoding = "UTF-8"

config.version = "8"
displayName = "dev"
ethernet0.addressType = "generated"
ethernet0.connectionType = "nat"
ethernet0.linkStatePropagation.enable = "TRUE"
ethernet0.present = "TRUE"
ethernet0.virtualDev = "e1000"
ethernet0.wakeOnPcktRcv = "FALSE"
floppy0.present = "FALSE"
guestOS = "other26xlinux-64"
hpet0.present = "TRUE"
ide1:0.deviceType = "cdrom-image"
ide1:0.fileName = "~/.docker/storage/dev/boot2docker-vmw.iso"
ide1:0.present = "TRUE"
mem.hotadd = "TRUE"
memsize = "512"
powerType.powerOff = "hard"
powerType.powerOn = "hard"
powerType.reset = "hard"
powerType.suspend = "hard"
scsi0.present = "TRUE"
scsi0.virtualDev = "lsilogic"
scsi0:0.fileName = "dev.vmdk"
scsi0:0.present = "TRUE"
virtualHW.productCompatibility = "hosted"
virtualHW.version = "10"
msg.autoanswer = "TRUE"
uuid.action = "create"
extendedConfigFile = "dev.vmxf"
uuid.bios = "56 4d 2c d8 62 f1 d0 d9-1a 39 5e cb d4 21 df bb"
uuid.location = "56 4d 2c d8 62 f1 d0 d9-1a 39 5e cb d4 21 df bb"
replay.supported = "FALSE"
replay.filename = ""
migrate.hostlog = "./dev-8f1bbb52.hlog"
scsi0:0.redo = ""
scsi0.pciSlotNumber = "16"
ethernet0.pciSlotNumber = "17"
ethernet0.generatedAddress = "00:0c:29:21:df:bb"
ethernet0.generatedAddressOffset = "0"
monitor.phys_bits_used = "40"
vmotion.checkpointFBSize = "67108864"
cleanShutdown = "FALSE"
softPowerOff = "FALSE"
ide1:0.startConnected = "FALSE"
tools.syncTime = "FALSE"

**Comment by ehazlett** [comment]
Can you re-run with `docker-machine -D create -d vmwarefusion dev` and post the output?

**Comment by stonevil** [comment]
~ ❯ docker-machine -D create -d vmwarefusion dev
INFO[0000] Creating SSH key...
DEBU[0000] executing: /usr/bin/ssh-keygen ssh-keygen -t rsa -N  -f ~/.docker/storage/dev/id_rsa

Generating public/private rsa key pair.
Your identification has been saved in ~/.docker/storage/dev/id_rsa.
Your public key has been saved in ~/.docker/storage/dev/id_rsa.pub.
The key fingerprint is:
...:11:54 stone@stoned-rMBP.local
The key's randomart image is:
+--[ RSA 2048]——+
...
INFO[0001] Creating VM...
VixDiskLib: Invalid configuration file parameter. Failed to read configuration file.
Creating disk '~/.docker/storage/dev/dev.vmdk'
Virtual disk creation successful.
DEBU[0001] executing: /Applications/VMware Fusion.app/Contents/Library/vmrun start ~/.docker/storage/dev/dev.vmx nogui
INFO[0004] Waiting for VM to come online...
DEBU[0004] MAC address in VMX: 00:0c:29:21:df:bb
DEBU[0004] Not there yet 1/60, error: IP not found for MAC 00:0c:29:21:df:bb in DHCP leases
...
DEBU[0124] MAC address in VMX: 00:0c:29:21:df:bb
DEBU[0124] Not there yet 60/60, error: IP not found for MAC 00:0c:29:21:df:bb in DHCP leases
ERRO[0126] Error creating machine: Machine didn't return an IP after 120 seconds, aborting
WARN[0126] You will want to check the provider to make sure the machine and associated resources were properly removed.
FATA[0126] Error creating machine

**Comment by ehazlett** [comment]
Hmm looks like it never gets an IP.  Could you try the following to restart the Fusion networking and see if that helps?

```
sudo /Applications/VMware\ Fusion.app/Contents/Library/vmnet-cli --configure
sudo /Applications/VMware\ Fusion.app/Contents/Library/vmnet-cli --stop
sudo /Applications/VMware\ Fusion.app/Contents/Library/vmnet-cli --start
```

**Comment by stonevil** [comment]
VM do not get any IP because never started!
ISO image not enabled in VMware Fusion configuration. No boot device.

![screen shot 2015-02-26 at 19 31 36](https://cloud.githubusercontent.com/assets/129196/6397548/20bb5514-bdee-11e4-8104-e3fdccfd2779.png)

**Comment by ehazlett** [comment]
What version of machine are you using?  The latest (released today)?

**Comment by ehazlett** [comment]
Confirmed.  Working on a fix.

**Comment by ehazlett** [comment]
actually mine was a different error -- still digging

**Comment by ehazlett** [comment]
Mine is working fine (my issue was a memory issue -- didn't have enough free mem to start the VM).

Could you try clearing `~/.docker/machine` or if you don't want to remove that, run:

```
export MACHINE_STORAGE_PATH=/tmp/test
docker-machine create -d vmwarefusion test-fusion
```
To create that using a different store directory.  Note that you will not be able to use machine with the other directory as it will have different certs but this should at least show if there is a different issue.

**Comment by olibob** [comment]
I just tested and the VM was created: I could `docker-machine ssh` into it.
Here are [the creation logs](http://pastebin.com/ux4wT8mF).

**Comment by olibob** [comment]
BTW, the created VMs don't show up in VMware Fusion's Library window.

**Comment by frapposelli** [comment]
> BTW, the created VMs don't show up in VMware Fusion's Library window.

@olibob that is by design.

**Comment by frapposelli** [comment]
> ide1:0.deviceType = "cdrom-image"
> ide1:0.fileName = "~/.docker/storage/dev/boot2docker-vmw.iso"
> ide1:0.present = "TRUE"

@stonevil those options are consistent with a correctly mounted iso file, can you test clearing `~/.docker/machine` as @ehazlett asked?

**Comment by stonevil** [comment]
Short summary of my research.

Looks like VMware Fusion have problem with special symbols just like ~ in for MACHINE_STORAGE_PATH.

Problem solved.

**Comment by ehazlett** [comment]
Thanks @stonevil
