### ISSUE TITLE
Minor: TODO note exposed in docs

### ISSUE THREAD

**Issue by moxiegirl** [docker/machine#638]
http://docs.docker.com/machine/#drivers

**Comment by ChrisChinchilla** [comment]
#dibs

**Comment by sthulb** [comment]
I'm not sure machine has a "#dibs" bot :)

**Comment by ChrisChinchilla** [comment]
As far as I can see, this has already been removed but maybe it's not deployed? See commit here - https://github.com/docker/machine/commit/3b622cdde10946147c8694e47b2ac427096325b3

**Comment by ehazlett** [comment]
@sthulb this is part of the birthday tagging.

@ChrisChinchilla yep looks like it was fixed in that and didn't get mentioned.  thanks for checking it!
