### ISSUE TITLE
Error creating machine, can't find powershell.exe

### ISSUE THREAD

**Issue by pbering** [docker/machine#639]
Hi,

I get this error when trying to create a new host:

D:\> docker-machine create --driver hyper-v dev                                                                                       
INFO[0000] Creating CA: C:\Users\pmb\.docker\machine\certs\ca.pem                                                                  
INFO[0001] Creating client certificate: C:\Users\pmb\.docker\machine\certs\cert.pem                                                   
**ERRO[0001] Error creating machine: exec: "E:\\Users\\pmb\\Documents\\WindowsPowerShell\\Scripts\\powershell.exe": file does not exist** 
WARN[0001] You will want to check the provider to make sure the machine and associated resources were properly removed.               
FATA[0001] Error creating machine                                                                                                     

Notes:

1. The directory "E:\\Users\\pmb\\Documents\\WindowsPowerShell\\Scripts" seems kind of odd, this is where my profile.ps1 is placed.
2. "E:\\Users\\pmb\\Documents\\WindowsPowerShell" is actually a junction point to another directory.
3. **Trying on another machine without junction points works**

**Comment by nathanleclaire** [comment]
cc @jeffmendoza for input

**Comment by jeffmendoza** [comment]
Looks like our logic is pretty crappy, sorry:
https://github.com/docker/machine/blob/master/drivers/hyperv/powershell_windows.go#L17

It looks for any directory in your path that contains "WindowsPowerShell" anywhere in it, then adds "/powershell.exe" to the end. Definitely needs a refactor.

**Comment by nathanleclaire** [comment]
Hey @jeffmendoza, if you are just needing to track down an executable, [exec.LookPath](http://golang.org/pkg/os/exec/#example_LookPath) will do the trick.

**Comment by JonathanDaSilva** [comment]
#1800 same here sorry for duplicate don't see this issue in the first place
