### ISSUE TITLE
docker-machine -d azure --swarm should create an endpoint on port 3376

### ISSUE THREAD

**Issue by chanezon** [docker/machine#640]
Right now it creates an Azure endpoint on port 2276, it should create one also on port 3376
docker-machine create -d azure \
--azure-subscription-id="9b5910a1-...79d5ea2841" \
--azure-subscription-cert="/Users/pat/.azure/9b5910a1-...d5ea2841.pem" \
--azure-location="West US" \
--azure-username="pat" \
--swarm --swarm-master \
--swarm-discovery token://4d6b2c18727...d5a0b2e52d978 \
pat-swarm-master-3

on the created machine
ps -efww
root     12593     1  0 18:30 ?        00:00:07 /usr/bin/docker -d --tlsverify --tlscacert=/etc/docker/ca.pem --tlskey=/etc/docker/server-key.pem --tlscert=/etc/docker/server.pem --label=provider=azure --host=unix:///var/run/docker.sock --host=tcp://0.0.0.0:2376
root     12789 12593  0 18:31 ?        00:00:00 docker-proxy -proto tcp -host-ip 0.0.0.0 -host-port 3376 -container-ip 172.17.0.2 -container-port 3376
root     12794 12593  0 18:31 ?        00:00:06 /swarm manage --tlsverify --tlscacert=/etc/docker/ca.pem --tlscert=/etc/docker/server.pem --tlskey=/etc/docker/server-key.pem -H tcp://0.0.0.0:3376 --strategy random token://ef400dd128546b6b559851b948fa51ac

Creating the endpoint manually works:
$(docker-machine env --swarm pat-swarm-master-3)
docker info
Containers: 2
Nodes: 1
 pat-swarm-master-4: pat-swarm-master-4.cloudapp.net:2376
  └ Containers: 2
  └ Reserved CPUs: 0 / 1

**Comment by yunspace** [comment]
+1 got the same issue using 0.2.0-rc3 

needed to manually create the 3376 endpoint on master machine as pointed out by @chanezon

**Comment by nathanleclaire** [comment]
@chanezon Is this still happening as far as you know?

**Comment by gotascii** [comment]
I think this is still happening. If you look at [where the endpoint creation method is called](https://github.com/docker/machine/blob/master/drivers/azure/azure.go#L245) and [the method that handles endpoint creation](https://github.com/docker/machine/blob/master/drivers/azure/azure.go#L408-L426) it appears that the only endpoint port that is ever created is for `d.DockerPort`. Something along the lines of an `addSwarmMasterEndpoint` that gets called after `addDockerEndpoint` when `d.SwamMaster` is true might work?

**Comment by agup006** [comment]
+1 got the same issue using 0.3.0

**Comment by ehazlett** [comment]
Closing as #1640 is merged.
