### ISSUE TITLE
docker-machine stop not working

### ISSUE THREAD

**Issue by leitu** [docker/machine#645]
According to the documents:
>$ docker-machine stop
  $ docker-machine start
  If they aren't passed any arguments, commands such as docker-machine stop will run against the active host (in this case, the VirtualBox VM). You can also specify a host to run a command against as an argument. For instance, you could also have written:
  $ docker-machine stop dev
  $ docker-machine start dev

But I had tried several times, docker-machine stop doesn't work. only can stop dev machine with docker-machine stop dev.

Virutalbox: 4.3.22
docker-machine version 0.1.0
ocker version
Client version: 1.3.2
Client API version: 1.15
Go version (client): go1.3.3
Git commit (client): 39fa2fa
OS/Arch (client): darwin/amd64
Server version: 1.5.0
Server API version: 1.17
Go version (server): go1.4.1
Git commit (server): a8a31ef

I have boot2docker installed as well

**Comment by nathanleclaire** [comment]
This is a bug introduced by supporting multi-name arguments.  Sorry about that.  If you specify the host directly it will work e.g. `docker-machine stop dev` and we will fix it in master soon.

**Comment by therealprologic** [comment]
Btw - just a thought... How would this work for the ``none`` driver?

**Comment by sthulb** [comment]
@therealprologic they won't. We can only create and remove the none driver.

**Comment by therealprologic** [comment]
No problems :)
