### ISSUE TITLE
hyper-v: host.go want's to provision docker again

### ISSUE THREAD

**Issue by pmario** [docker/machine#647]
using docker-machine V 0.1.0

TLDR
IMO https://github.com/docker/machine/blob/master/host.go#L406 needs to check for hyper-v as a boot to docker driver. 

-----------

I get the info: 

```
←[34mDEBU←[0m[0047] executing: ssh -o IdentitiesOnly=yes -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o
LogLevel=quiet -p 22 -i C:\Users\xxxxx\.docker\machine\machines\hugo\id_rsa docker@10.0.0.11 if [ ! -e /usr/bin/docker ]
; then curl -sSL https://get.docker.com | sh -; fi
←[31mERRO←[0m[0068] Error creating machine: error installing docker: exit status 1
Warning: "docker" or "lxc-docker" command appears to already exist.
Please ensure that you do not already have docker installed.
```

which points out, that the docker command already exists. Which is true since the hyper-v driver uses the boot2docker iso image.

**Comment by agocke** [comment]
There are probably two problems here:

1. The check in docker-machine is a simple `if [ ! -e /usr/bin/docker ]`, when it should probably be something like `if command -v docker`.
2. The get-docker script doesn't recognize boot2docker.

I'll try to fix this since it is blocking me and send a PR.

**Comment by pmario** [comment]
@agocke 
Imo your PR comment should have closed this issue too but it didn't. So I'll close it.

**Comment by pmario** [comment]
Due to this revert: https://github.com/docker/machine/commit/8b6ccddd801e2f2397ea116ed82f6c936485931f it needs to be opened again. 

cc: @agocke

**Comment by pmario** [comment]
@agocke imo you should open your PR #672 again.

**Comment by ehazlett** [comment]
Yes, I think we should use `command` as it is much better.  I had to revert 8b6ccdd because it removed the check for local drivers.  I think the rest is ok.

**Comment by pmario** [comment]
@ehazlett 
Just did a test with v0.2.0-rc2 -> problem seems to be fixed. So I'll close this issue again.
