### ISSUE TITLE
Question: should I execute docker run swarm inside the vm created by docker-machine?

### ISSUE THREAD

**Issue by joeyhipolito** [docker/machine#651]
I am on windows a I was fiddling around this docker-machine, as I go along the writeups and instructions on getting started with docker machine swarm and compose.

So I created a machine like so

    docker-machine create --drive virtualbox dev

Now I wanted to create a swarm-master, in the instructions, was the following instructions is inside the dev container? or was for the host machine

    docker pull swarm

Or should we 

    docker-machine ssh dev
    docker pull swarm
    docker run --rm swarm create

**Comment by killerwolf** [comment]
I am also misunderstanding what swarm is ? is it a container ? it it a cli tool ? or cli tol within a container ?
I am on OSX and download docker-swarm from brew ?
Thanks for help setting up a docker host cluster with swarm

**Comment by ehazlett** [comment]
Thanks for the feedback.  Docker Swarm is a separate project (https://github.com/docker/swarm) and available via either docker image (`swarm` and recommended) or standalone binary.

Docker Machine uses the Swarm Docker image to create the cluster.  These are the steps to create a Swarm cluster with machine:

`docker-machine create -d virtualbox local`

This creates a Machine using virtualbox that will be used to create the token needed for the cluster.

`$(docker-machine env local)`

This loads in the environment settings needed for the Docker cli.  The `local` docker instance will be used.

`docker run swarm create`

This will return a token to be used when creating the Swarm cluster.

```
docker-machine create \
    -d virtualbox \
    --swarm \
    --swarm-master \
    --swarm-discovery token://<TOKEN-FROM-ABOVE> \
    swarm-master
```

This creates a new Machine instance using virtualbox that will be the Swarm master.  See full docs here: http://docs.docker.com/machine/#using-docker-machine-with-docker-swarm

**Comment by atomi** [comment]
docker-machine is creating -d virtualbox with tcp docker port 2375 in the boot2docker vm but listing it in docker-machine ls and /swarm join --addr as 2376

**Comment by kevinsimper** [comment]
I get `Incorrect usage.` when running:

```
docker-machine create \
    -d virtualbox \
    --swarm \
    --swarm-master \
    --swarm-discovery token://MYTOKEN \
    swarm-master
```

**Comment by kevinsimper** [comment]
Got it working by using @ehazlett latest build https://docker-machine-builds.evanhazlett.com/latest/

The version that i had, even through it was version 0.1.0, not the swarm deploying

**Comment by ehazlett** [comment]
Thanks for reporting.  I'll add a test for this.
