### ISSUE TITLE
Question: Permission Denied on curl and save for docker compose

### ISSUE THREAD

**Issue by joeyhipolito** [docker/machine#652]
In the instructions for installing docker-compose, you can do : 

    curl -L https://github.com/docker/compose/releases/download/1.1.0/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
    chmod +x /usr/local/bin/docker-compose

But you cannot intall it because:

    zsh: permission denied: /usr/local/bin/docker-compose

I don't want to do sudo, because I wanted it to be like my previous installs and usage of docker

    docker <command>

No sudo...

What is the proper way of setting it up?

**Comment by ehazlett** [comment]
I believe you meant https://github.com/docker/compose.  @aanand ?

**Comment by aanand** [comment]
Most likely your `/usr/local/bin` directory isn't writable by you. Either `chmod`/`chown` it, or download `docker-compose` somewhere writable and `sudo cp` it in.

You won't need `sudo` to run it, just to install it.

**Comment by luisrudge** [comment]
I'm having this problem too and I'm kinda linux newbie :) Can someone help me?

**Comment by ehazlett** [comment]
@luisrudge for compose or machine?

**Comment by luisrudge** [comment]
Oh, sorry! It's for compose!

**Comment by ehazlett** [comment]
@luisrudge ok np :)  Mind if I close this one?

**Comment by luisrudge** [comment]
Yes! Thanks!

**Comment by tarun6006** [comment]
i'm facing same issue for docker machine, please redirect to the solution @ehazlett

**Comment by tarun6006** [comment]
@joeyhipolito @aanand  kindly help

**Comment by aanand** [comment]
@tarun6006 The problem/solution is likely the same:

> Most likely your `/usr/local/bin` directory isn't writable by you. Either `chmod`/`chown` it, or download `docker-machine` somewhere writable and `sudo cp` it in.

> You won't need `sudo` to run it, just to install it.

**Comment by zhangqinghe** [comment]
in terminate input  `sudo chown -R $(whoami) /usr/local/bin`

**Comment by imad-bouhamidi** [comment]
Oh thanks @zhangqinghe it fixed the problem for me

**Comment by slawa85** [comment]
I found [this](https://github.com/docker/compose/pull/1249/files) approach easier.

**Comment by vabnirvana** [comment]
@zhangqinghe this solves the problem. thanks.

**Comment by fernandoGN** [comment]
To me sudo -i before, solved the problem.

**Comment by tanchao90** [comment]
@zhangqinghe thanks .  this solves my problem.

**Comment by Jihar** [comment]
please type 

sudo chmod -Rf 777 /usr/local/bin

it's work

**Comment by nathanleclaire** [comment]
> please type
> sudo chmod -Rf 777 /usr/local/bin
> it's work

Please DO NOT do this.  This will have far-reaching permission changes which are likely beyond the scope of what you'd actually like to accomplish.

**Comment by nathanleclaire** [comment]
> sudo chown -R $(whoami) /usr/local/bin

Please DO NOT do this either (it will change the owner of every single file recursively in `/usr/local/bin` to the user you are currently running as).  It's WAY overkill.  I can't emphasize this enough.

Doing something like this is very likely to blow up in your face eventually.  In `/usr/local/bin` on my Mac some files are owned by `nathanleclaire` and some are owned by `root`.  The programs that put them there and rely on them probably expect it to stay this way.  The suggested command above will totally decimate these carefully layed out file permissions.

Instead, if needed, consider this type of operation instead.  Save the file to a directory you own and then `cp` / `mv` it.

```console
$ curl -L https://github.com/docker/compose/releases/download/1.8.0/docker-compose-`uname -s`-`uname -m` \
    >~/docker-compose
$ chmod +x ~/docker-compose
$ sudo mv ~/docker-compose /usr/local/bin/docker-compose
```

Much safer with much less far-reaching consequences.

**Comment by AhmadAbdelghany** [comment]
From Docker [documentation:](https://docs.docker.com/compose/install/)

> Note: If you get a “Permission denied” error, your /usr/local/bin directory probably isn’t writable and you’ll need to install Compose as the superuser. Run sudo -i, then the two commands below, then exit

**Comment by PrabhuGithub** [comment]
nathanleclaire  suggestion worked for me.  Thanks

**Comment by agusgr** [comment]
Google brings me here....

Please, please PLEASE... use the @nathanleclaire solution

**Comment by zhaynoth** [comment]
What about this:
If you would like to use Docker as a non-root user, you should now consider
adding your user to the "docker" group with something like:

  sudo usermod -aG docker your-user
Is this a good idea?

**Comment by amarouane-ABDLHAK** [comment]
make sure docker-compose is executable (chmod +x /usr/local/bin/docker-compose)

**Comment by binodluitel** [comment]
No need to mess with permissions on all files inside `/usr/local/bin`
Do not do 
> sudo chown -R $(whoami) /usr/local/bin

Do this instead

```
sudo -i
curl -L https://github.com/docker/compose/releases/download/1.18.0/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose
chmod 755 /usr/local/bin/docker-compose
exit
```

**Comment by jimmylin212** [comment]
Please use @nathanleclaire 's solution, it works very well for me.

**Comment by milos-djokic** [comment]
> make sure docker-compose is executable (chmod +x /usr/local/bin/docker-compose)

this worked on Ubuntu 18.04

**Comment by KingAlawaka** [comment]
> I found [this](https://github.com/docker/compose/pull/1249/files) approach easier.

this worked for me :D

**Comment by polaroidkidd** [comment]
> To me sudo -i before, solved the problem.

This (or any of the others mentioning `sudo -i` ) should be the accepted answer and not the just chown the entire /usr/local/bin

**Comment by mmzoo** [comment]
For what it's worth: the `permission denied: docker-compose` error occurred to me after an upgrade of Docker. A minute earlier everything was still working fine, so my permissions were all in order.

After I started the (now upgraded) Docker desktop application and authorized it when asked for my administrator password, the error was gone. So Docker fixed the permissions itself.

**Comment by sriramgroot** [comment]
This code alone can solve this problem
`sudo chmod +x /usr/local/bin/docker-compose`
