### ISSUE TITLE
virtualbox network/routing issue

### ISSUE THREAD

**Issue by therealprologic** [docker/machine#657]
I just tried:

```#!bash
docker-machine create -d virtualbox dev
...
$(docker-machine env dev)
docker ps
```

And this fails with "No route to host".

The IP assigned to the VM seems to be ``192.168.99.100`` however there doesn't seem to be a matching interface on the Host that matches this network so ``/sbin/ss ip route get 192.168.99.100`` shows it going out via the local LAN.

How is docker-machine setting up the networking?

**Comment by therealprologic** [comment]
I'm closing this as I don't think this is a ``docker-machine`` issue.
After some investigating I had to do the following:

```#!bash
/sbin/ip set link vboxnet1 up
/sbin/ip addr add 192.168.99.1/24 dev vboxnet1
``

I *thought* this was something that VirtualBox did automatically? (*Apparently not*).

**Comment by dnvriend** [comment]
Maybe someone else has or will have the same problem, so I'm gonna tell my story here. On OSX I had the following; installed boot2docker and VirtualBox and after some months I had three vboxnet interfaces so vboxnet0, vboxnet1 and vboxnet2. I want to use docker-machine so I installed it using brew. When I added a new virtualbox docker machine, (I set the environment using the docker-machine env dev command), it could not connect to the docker instance running on the docker machine. The boot2docker one worked good though. I wanted to switch to docker-machine, and after I tried to add routes to the routing table and failing I removed the docker-machines and boot2docker vm. Basically a cleanup of everything. Next creating a new docker-machine with the virtualbox driver and setting the correct environment, docker could connect to the docker-machine. 

Commands I used
```
Install docker-machine
brew cask install docker-machine

Create new docker machine using the VirtualBox driver:
docker-machine create -d virtualbox dev
docker-machine ip
$(docker-machine env dev)
docker ps

show routing table:
netstat -nr

VirtualBox show interfaces:
VBoxManage list hostonlyifs --long

Remove virtualbox hostonly network adapters:
VBoxManage hostonlyif remove vboxnet0
VBoxManage hostonlyif remove vboxnet1
VBoxManage hostonlyif remove vboxnet2

Add route to the routing table (did not work though):
sudo route -nv add -net 192.168.56 -interface vboxnet0
sudo route -nv delete -net 192.168.56 -interface vboxnet0
```
