### ISSUE TITLE
New Driver: libvirt / KVM

### ISSUE THREAD

**Issue by dhiltgen** [docker/machine#659]
This driver support libvirt, and at present the KVM back-end.  The current implementation requires a NAT'd network with libvirt managed DHCP (via dnsmasq) to establish connectivity to the VM.

Initial Implementation: [https://github.com/dhiltgen/machine/commit/e5d159c17fc9ef497a1933c83b69d2b8d1e6f168]

**Comment by ehazlett** [comment]
@SvenDowideit want to sync with @dhiltgen on this?  Perhaps we can combine the implementations?

**Comment by SvenDowideit** [comment]
we've synced a little  when I get back to australia, I'll look at my code a bit further, I'm not sure if we should just combine these 2 drivers, or make a more shared abstraction.

**Comment by sthulb** [comment]
Are we still avoiding libvirt due to it's C bindings?

**Comment by ehazlett** [comment]
@sthulb no we were just avoiding using libvirt as the layer between all drivers.

@SvenDowideit sounds good.  I'm not sure either.  @dhiltgen what do you think?

**Comment by sthulb** [comment]
OK! I was just making sure :smile:

**Comment by Brandl** [comment]
Any progress on this? (+1 for libvirt support)

**Comment by ehazlett** [comment]
I would like to see `libvirt` as well however I would really like to see the two implementations come together to have a single driver.

**Comment by efrecon** [comment]
Any progress or decision on this?

**Comment by ehazlett** [comment]
@efrecon see https://github.com/docker/machine/pull/692#issuecomment-105925355
