### ISSUE TITLE
keypair prevents creation of machine with same name as the one just removed

### ISSUE THREAD

**Issue by DanLipsitt** [docker/machine#661]
If the create command fails (in this case because I forgot the vpc-id flag) and I remove the failed image, I can't create a new one with the same name because the keypair doesn't get deleted:

```console
$ docker-machine rm -f demo
$ docker-machine create --driver=amazonec2 --amazonec2-vpc-id=vpc-foo demo
INFO[0000] Creating CA: /Users/dan/.docker/machine/certs/ca.pem 
INFO[0001] Creating client certificate: /Users/dan/.docker/machine/certs/cert.pem 
ERRO[0003] Error creating machine: There is already a keypair with the name demo.  Please either remove that keypair or use a different machine name.
```

It seems that `rm -f` should remove associated keypairs.

Related: #119.

**Comment by cboettig** [comment]
+1 

it would also/meanwhile be useful for the error message to point to how to remove such a keypair -- I get this error even when `docker-machine ls` does not show any machines, and `docker -h` doesn't suggest any other way of removing this keypair record.

**Comment by dougborg** [comment]
I have run into this as well. Does anyone know where these keys are being created? I have looked around in the machine storage path and in my home directory and come up empty.

**Comment by dougborg** [comment]
Ok, so now I get it. This is the "Key Pair" in EC2, not anything stored locally. I was able to remove them in the EC2 management console and now all is well.

**Comment by jolestar** [comment]
+1 @dougborg

**Comment by raykrueger** [comment]
It would also be helpful to be able to pass --amazonec2-keypair-name=whatever to re-use existing keypairs.

**Comment by chiefy** [comment]
:+1: just ran into this - working within a group - we have a keypair we're sharing.

**Comment by ruffsl** [comment]
+1 I ran into this today too.

**Comment by saada** [comment]
:+1:

**Comment by therealbill** [comment]
+1 as well. In my case it is telling me this even though when doing an `aws describe-keypairs` and looking in the AWS console the keeper doesn't exists. Some more verbosity in debug mode would help here as well.

**Comment by voltecrus** [comment]
+1

**Comment by dustinblackman** [comment]
:1 for `--amazonec2-keypair-name`

**Comment by PurrBiscuit** [comment]
+1

**Comment by bobby** [comment]
+1 for --amazonec2-keypair-name

**Comment by java4africa** [comment]
You can delete the keypair in the AWS console. "Network & Security" -> "Key Pairs" -> "Delete"

**Comment by baljanak** [comment]
+1 for keypair-name option

**Comment by igorescobar** [comment]
`--amazonec2-keypair-name` 👍

**Comment by vikstrous** [comment]
I keep running into this issue as well. Our automated docker machine creation scripts often fail and leave behind existing key pairs and then cause even more failures which require manual intervention to fix.

**Comment by alexanderkjeldaas** [comment]
This bug is not fully fixed.  The unhelpful error message is still there.

It should read:

`Use aws ec2 delete-key-pair --key-name {{.Hoast}}` to delete.

**Comment by Matt-Byrne** [comment]
I've just seen this issue too, on 1.5.3. In my case, the console showed no key pair with the relevant name, and neither did `aws ec2 describe-key-pairs`. That said, `aws ec2 delete-key-pair --key-name xyz` DID work, despite them not being visible...

**Comment by m-dunbar** [comment]
Creating a keypair for every new instance is an ugly kludge, and it's what's causing the underlying problem.  True use of an existing key pair _without_ duplication is the real solution.  When with _that_ be implemented.

Simply saying 'delete the keypair manually from aws' is NOT a solution.  How is clustering supposed to work with that?

**Comment by vikstrous** [comment]
@m-dunbar `--amazonec2-keypair-name` is what you are looking for.
