### ISSUE TITLE
Setting and elastic ip address on AWS EC2 will make existing TLS invalid

### ISSUE THREAD

**Issue by kretz** [docker/machine#662]
I set up an instance using the amazonec2 driver successfully. Then I associated an Elastic IP address with the instance, and thus removing the old ip address. Now communicating with the instance does not work since the TLS is not valid for the new (Elastic) ip address.
```
FATA[0000] An error occurred trying to connect: Get https://x.x.x.x:2376/v1.17/containers/kibana/json: x509: certificate is valid for y.y.y.y, not x.x.x.x
```

**Comment by kmadel** [comment]
Did you `docker-machine regenerate-certs {machine-name}` after you udpated the new IP in the config.json for said {machine-name}?

**Comment by kretz** [comment]
Can't remember, but probably not. Thanks for the comment, perhaps it helps someone.

**Comment by ehazlett** [comment]
Yes this is exactly what the `regenerate-certs` command is for.  If you use `config` or `env` they should be regenerated automatically.  Please re-open if the issue persists.

**Comment by ebanner** [comment]
I still see the old IP address even after changing the IP in `/home/user/.docker/machine/machines/{machine_name}/config.json` and running `regenerate-certs`. I've grepped for the old IP address in `.docker/` and I can't find it anywhere. Where is it coming from??
