### ISSUE TITLE
Machine is trying to provision docker on top of Hyper-V's boot2docker iso

### ISSUE THREAD

**Issue by jeffmendoza** [docker/machine#666]
see:
54f36078f4c7516d717987f94c4787c0566798c0

https://github.com/docker/machine/blob/master/host.go#L406

Hyper-V is missing from this line.

**Comment by nathanleclaire** [comment]
Argh, this is why I would really like a `IsLocal` method or equivalent on drivers, it would definitely be more robust.

**Comment by sthulb** [comment]
@nathanleclaire in the long run, we don't need that, I need to finish #546. So we can detect the distro family.
