### ISSUE TITLE
Openstack Identity v3 support

### ISSUE THREAD

**Issue by stenstad** [docker/machine#679]
Gophercloud supports the Openstack Identity v3 API, wich brings in a lot of new features. It has been the preferred API since Openstack Havana (2013), and the v2 API is somewhat deprecated.

http://gophercloud.io/docs/identity/v3/

Could you look into supporting the new auth mechanisms?

If you need access to an Openstack cloud with V3 API for testing I can arrange that.

We only support the v3 API since we are using domains and other related features.

For the Docker Machine use case, the v3 API is mostly used for acquiring a project scoped authtoken to talk to the nova, neutron etc. APIs.

**Comment by ggiamarchi** [comment]
+1

I can work on this one. I'll do a PR in a few days.

**Comment by stenstad** [comment]
@ggiamarchi That's awesome, it's hard for us that use V3 domains. :-)

**Comment by ggiamarchi** [comment]
In order to implement it correctly, there were some work to do in gophercloud to fix things in keystone v3 implementation. I have just submit this pull request https://github.com/rackspace/gophercloud/pull/408

Then, the work in docker-machine is pretty easy, i'm on it.

**Comment by ggiamarchi** [comment]
@stenstad Can you test the PR https://github.com/docker/machine/pull/955 against your OpenStack domains ? It would be great in order to validate this work. From my part, i have tested it against a devstack installation.

**Comment by stenstad** [comment]
@ggiamarchi Hi, sorry for answering so late. Identity seems to work now! I am still not able to actually launch a working VM yet, but I assume that is not related to the identity part.

A few things I have noticed:

There should be a check for more environment variables. Some of them are new and/or have changed names.

OS_TENANT_ID is now OS_PROJECT_ID.
OS_TENANT_NAME is now OS_PROJECT_NAME
OS_DOMAIN_NAME is not necesarily set, OS_PROJECT_DOMAIN_NAME and/or  OS_USER_DOMAIN_NAME might be set instead.

**Comment by stenstad** [comment]
@ggiamarchi It works now! Awesome.

**Comment by stenstad** [comment]
@ggiamarchi Actually, OS_DOMAIN_NAME is used for scoping to a domain and not a project/tenant. If it is defined python-openstackclient complains.

**Comment by stenstad** [comment]
@ggiamarchi Seems like Openstack Client has upgraded their docs regarding auth, explaining what is needed and used for v3 auth with regards to scoping:

https://github.com/openstack/python-openstackclient/blob/master/doc/source/authentication.rst

**Comment by zhoutiekui** [comment]
@stenstad  the current authentication method only supports domain scope authentication rather than project scope authentication. Is there a workaround about this, cause our platform only supports project scope authentication. thanks

**Comment by stenstad** [comment]
@zhoutiekui Hi, I don't understand your problem. You scope to a project, not a domain. If you have not implemented domains in your Keystone setup, i.e. you basically use a Keystone v2 setup, just use the domain "default". Read the original blueprint here: https://blueprints.launchpad.net/keystone/+spec/default-domain
