### ISSUE TITLE
Cannot use docker-machine from behind a corporate proxy

### ISSUE THREAD

**Issue by sirlatrom** [docker/machine#681]
I know this will amuse most users of docker-machine, but it bothers me.

I am behind a corporate authenticated proxy with MITM (modified certificate path) for HTTPS connections. I cannot use `docker-machine` as it is, apparently because it does not support proxy settings. I have tried setting `https_proxy`, `http_proxy` and their uppercase counterparts, as well as ensured that `no_proxy` is set correctly.

I have removed ASCII escape codes for readability in the following example.

    C:\docker\bin>docker-machine create --driver virtualbox dev
    ←[WARN] Unable to check for the latest release: Get https://api.github.com/repos/boot2docker/boot2docker/releases: dial tcp 192.30.252.137:443: ConnectEx tcp: i/o timeout
    ←[INFO] Downloading boot2docker.iso to C:\Users\absukl\.docker\machine\cache\boot2docker.iso...
    ←[ERRO] Error creating machine: Get : unsupported protocol scheme ""
    ←[WARN] You will want to check the provider to make sure the machine and associated resources were properly removed.
    ←[FATA] Error creating machine

**Comment by jampy** [comment]
I have the exact same problem, except that I do not need/have a proxy to access Internet.
I guess the problem is not related to the Proxy.

In my case I tried to run docker-machine under Windows 7 64bit (VirtualBox is installed).

**Comment by sandywater** [comment]
:+1:

**Comment by jus101** [comment]
+1 - I get this error when trying to create a machine on OS X 10.10.2.

**Comment by shawnzhu** [comment]
fix from #625 works for me

**Comment by sirlatrom** [comment]
Closing this as duplicate of #625.
