### ISSUE TITLE
Proposal: error types

### ISSUE THREAD

**Issue by ehazlett** [docker/machine#682]
This would add support for error types instead of return `fmt.Errorf` everywhere.

Refs #553

**Comment by nathanleclaire** [comment]
I think this is more of a "We need a coding style guide" than a specific issue which we can point at as definitively solved.  I do agree strongly though.

**Comment by thaJeztah** [comment]
@ehazlett @nathanleclaire not sure if this is the same thing, but you might be interested in the work @duglin and @stevvooe did here; https://github.com/docker/distribution/pull/548

**Comment by nathanleclaire** [comment]
Nice callout @thaJeztah ; noted

**Comment by stevvooe** [comment]
@thaJeztah The `errcode` package is targeted at API-level errors. We should start using it for any errors that may cross an http/rpc (and maybe cli) boundary. 

@nathanleclaire @ehazlett We're still experimenting with the API, but Machine might want to explore use of the package.

**Comment by thaJeztah** [comment]
@stevvooe yup, I was aware of that (API / http); I thought it might be interesting (for inspiration). Thanks for adding your thoughts :+1:
