### ISSUE TITLE
Create an MVP HTTP API

### ISSUE THREAD

**Issue by bfirsh** [docker/machine#683]
Machine currently relies on storing configuration locally on the computer that the command-line client is run which makes it difficult to use in teams and for large deployments.

Machines could instead be managed by a central server with a REST API. The command-line client could be a client for this server.

We should create an MVP of this HTTP API to see how it's going to work. It could map directly to the current behaviour of Machine, then we can start to figure out:

- the bits which don't make sense in an API server
- how a client would interact with the server

etc.

## Dependencies

 - This will be built on the internal API https://github.com/docker/machine/issues/553

**Comment by tiagoalves83** [comment]
Do you have any updates on this ?
How can I help ?

**Comment by nathanleclaire** [comment]
It's unlikely to be implemented first-class although you might be able to roll your own with `libmachine` if interested

**Comment by tiagoalves83** [comment]
Thank you @nathanleclaire, I have just looked to libmachine. Is there any documentation? Does docker-machine CLI use it?

**Comment by nathanleclaire** [comment]
No, and Yes.  Going to close this issue as I think we're not really interested in this any longer
