### ISSUE TITLE
Pass additional arguments to ssh

### ISSUE THREAD

**Issue by kraney** [docker/machine#691]
It would be very useful if I could pass extra arguments to docker-machine ssh. In particular I'd like to use -L and -R.

Here are a couple of examples why (glossing over a few details.) These examples assume the client machine I'm using to run docker is behind a NAT, so the docker machine can't make outgoing connections back to me.

# Make home directory accessible as a volume, similar to boot2docker
docker-machine ssh -R 2222:localhost:22 sshfs mount localhost:/Users /Users
docker run -v /Users/me:/Users/me -it busybox

# Push to a private registry not accessible from ec2
docker-machine ssh -R 5000:docker-registry.localdomain:5000 &
docker tag my-image localhost:5000:my-image
docker push localhost:5000:my-image

**Comment by nathanleclaire** [comment]
So to be clear on this, you want to be able to specify extra flags that the underlying `ssh` command uses?

**Comment by sthulb** [comment]
Unsure if we should do that... instead port forwarding on the hypervisor layer seems nicer (via a plugin)

**Comment by kraney** [comment]
Yes, extra flags on the ssh that docker-machine executes - similar to what boot2docker allows. The two use cases I mention are examples, it would be useful for anything from binding to a particular address on my machine (docker-machine ssh -b particular_ip_address) to turning on compression (docker-machine ssh -C)

Why hide the functionality that ssh provides?

**Comment by frankh** [comment]
I would like this too... It's not possible to use docker-enter directly now as you can't pass the -t flag to ssh

(you used to be able to do) ```boot2docker ssh -t sudo /var/lib/boot2docker/docker-enter "$@"```

**Comment by nathanleclaire** [comment]
@frankh As an aside from the main thread:  I would highly recommend using `docker-exec` if you want to spawn a shell inside a container.  It's built into Docker so it's a lot more convenient.

**Comment by mback2k** [comment]
@nathanleclaire Actually it would be great if the functionality of docker-enter / nsenter could be included into docker-machine.

**Comment by nathanleclaire** [comment]
@mback2k What would you be interested that `docker exec` doesn't provide?

**Comment by frankh** [comment]
Would be nice to add
    docker enter <name>

Instead of
    docker exec -it <name> /bin/bash

(I'm not even sure if -it are the right switches)

I know it seems like a trivial change but I think it would really make a
difference

**Comment by stevesmename** [comment]
@frankh think that aliases will do help you achieve this. 
```
function docker_enter() { sudo docker exec -it "$@" /bin/bash; }
```
Then you should have the following available:
```
docker_enter <name>
```
Side note, not sure why we are talking about this in this ticket (unrelated?) or in the Machine repo. Further convo should likely move into the docker/docker project.

**Comment by mback2k** [comment]
@stevesmename You are probably right, but in order to answer @nathanleclaire question, I would like to add the following statement from the nsenter project:

> There are differences between nsenter and docker exec; namely, nsenter doesn't enter the cgroups, and therefore evades resource limitations. The potential benefit of this would be debugging and external audit, but  for remote access, **docker exec is the current reccomended approach**.

**Comment by anentropic** [comment]
I have also been using `boot2docker ssh -L 5432:127.0.0.1:5432` to open a port forwarding session... my predecessor set this up in our project. It's a bit annoying having to have this shell window open... but it doesn't seem to work without it, eg I have:

```
postgres:
  build: ./infrastructure/docker/postgres/
  ports:
    - "5432:5432"
  expose:
    - "5432"
```

But I can't connect to the db from `psql` on my host machine until I start the boot2docker ssh session. I'd love to know why because I thought this is what exposing the ports from docker-compose was supposed to achieve.

Anyway... can't do the same under docker-machine so am stuck with boot2docker for now in order to get work done

**Comment by nathanleclaire** [comment]
@anentropic Does the IP assigned on the host-only network not work?  i.e. `psql -U postgres -h $(docker-machine ip default)`?

**Comment by anentropic** [comment]
yes, that works... and I should have thought of that sooner

what I don't understand though is why I can browse to my nginx container from the host using 127.0.0.1 ...but I can't connect to postgres container from the host using that ip?

**Comment by nathanleclaire** [comment]
> what I don't understand though is why I can browse to my nginx container from the host using 127.0.0.1 ...but I can't connect to postgres container from the host using that ip?

Mm, you shouldn't be able to (access the container on `localhost`).  Are you 100% certain that you're actually hitting a container running inside of that VM and/or that you haven't forwarded the port via some other method?  The only port that gets NAT-ed to localhost from the VM is for SSH.

> is port 80 already forwarded by default in boot2docker?

Definitely not.

**Comment by anentropic** [comment]
I confused myself, never mind, you are correct I can't reach the container webserver on localhost, I have to use the boot2docker ip

**Comment by rdsubhas** [comment]
A temporary workaround in VirtualBox is to add a "Bridged" adapter to the VM (by manually going to the VM settings). Now everybody on the network can access the VM directly. Useful for testing Android apps, etc.

**Comment by nathanleclaire** [comment]
The original issue mentioned should work now with some recent SSH changes, although you do need to specify the machine name:

```console
$ docker-machine ssh default -R 2222:localhost:22 sshfs mount localhost:/Users /Users
$ docker run -v /Users/me:/Users/me -it busybox
```

**Comment by clakech** [comment]
Hi, thanks for this interesting thread

I have the same need: forward a few port to my localhost (I am using docker-machin on a mac, other devs are unix linux to forwarding port is not needed)

Does -L option works? docker-machine ssh default -L 9200:localhost:9200
Is there any pointer to code or documentation to understand the way this should/will works.

using 1.8.2:
```
docker-machine ssh default -L 9200:localhost:9200
Incorrect Usage.

Usage: docker-machine ssh [arg...]

Log into or run a command on a machine with SSH.

Description:
   Arguments are [machine-name] [command]
```

Thanks

**Comment by dgageot** [comment]
Hello @clakech :-)
Have you tried docker-machine 0.5-rc3? I think it should work.

**Comment by clakech** [comment]
thx @dgageot ;)

**Comment by aertoria** [comment]
follow up

**Comment by nathanleclaire** [comment]
@aertoria It should work as outlined above
