### ISSUE TITLE
Proposal: OS Detection

### ISSUE THREAD

**Issue by sthulb** [docker/machine#693]
## Abstract
In an attempt to support any flavour of linux, we should build a profile of distributions to allow us to do certain things easily.

## Background
At the moment, we have no ability to run any distribution that isn't TinyCore (boot2docker) or Ubuntu, not everyone uses those distributions. We currently don't have any way of determining the distribution, we blindly assume that they're all one of the previously mentioned distributions.

The main area to focus on is the package manager and services, since everything else should be easy to do.

## Proposal
The proposal is a way of detecting the distribution we're trying to provision and allow machine to then have a generic runtime to perform commands against.

### Runtime
A runtime would be a simple interface offering three options:
 - detection function
 - package state
 - service state

#### Detection function
Often this would be as simple as a pattern match on all or some part of `lsb_release`

#### Package state
To allow machine to ensure a package is in one of a few states (`Installed`, `Missing`)

#### Service state
To allow machine to perform an action on a service based on `Start`, `Stop`, `Restart`.

An example situation for proposal would be to allow machine to install cloud-init should it be missing on an distribution.

**Comment by sthulb** [comment]
cc: @bfirsh @nathanleclaire @ehazlett

**Comment by ehazlett** [comment]
This sounds good to me.  I want to re-state that I think this should be clearly bounded and not stray into the config management space.  I think what's defined above is good.  It gives us the ability to get a base system ready for provisioning via cloudinit and provide a fallback if needed.  It also gives us the needed ability to restart services (such as Docker) across platforms.  Anything outside of that I think we should push to try to do with cloudinit.

Thanks!

**Comment by sthulb** [comment]
Absolutely. I have no intention of allowing this to become a provisioning system. I just wanted the bare minimum for what machine needs. 99% of provisioning should be done via cloud-init.

**Comment by nathanleclaire** [comment]
+1 on this

My basic vision is a `Provisioner` interface with methods for the common operations, e.g. `InstallDocker`, `ConfigureDaemon`, `ConfigureAuth`, `SetHostname`, `StartDaemon` etc.  Then there would be a `DebianProvisioner`, `CentosProvisioner`, etc. as we see fit.  Like you mentioned, it would be limited in scope, and accessible using `package provision` or something like that.

**Comment by sthulb** [comment]
@nathanleclaire this is deliberately lacking in functionality since we're opting for cloudinit which should do everything you mentioned.

**Comment by ehazlett** [comment]
@sthulb I think @nathanleclaire was referring to the Provisioner (#699) which would work with this package to handle things like `StartDocker`, `StopDocker` etc as we will need some way to identify what OS it is to do the right operation.  The provisioner would still be limited with the end goal of just provisioning a Docker engine.  Ideally this would be with cloudinit, but I think we need something as a fallback most likely using something like you have to pull a correct package etc.

**Comment by ehazlett** [comment]
Perhaps "Provisioner" is a bad term -- basically something that sets up and configures the system (that are common operations such as setting the hostname, running cloudinit, configuring TLS, etc) that is not tied to the driver.

**Comment by sthulb** [comment]
Ah. Sorry @nathanleclaire. In that case, we won't need OS specific provisioners, instead they can opt to use the the runtime to manage services and packages. It should make for a nice generic layer.

**Comment by TrumanLing** [comment]
+1

My PR#670 just covers virtualbox drive, not a total solution for docker machine.

 @sthulb if you need more man power, I will join to take some things.

**Comment by sthulb** [comment]
@trumanling it's fine. I paused this task since I wanted the SSH work done.

**Comment by nathanleclaire** [comment]
The first draft of this is well implemented at this point
