### ISSUE TITLE
TTY required to run sudo

### ISSUE THREAD

**Issue by superbeeny** [docker/machine#698]
Docker-machine is failing the remote ssh and sudo commands to stop docker.

Image: Centos 7
Driver: Openstack

Debug Log
```
DEBU[0077] Stopping Docker...                           
DEBU[0077] Command: %s[sudo sh -c 'sudo service docker stop']  MachineId=2bea2d0b-4884-43ba-a397-a05db104a640
DEBU[0077] executing: ssh -o IdentitiesOnly=yes -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=quiet -p 22 -i /home/nick/.docker/machine/machines/testDockerMachine/id_rsa centos@XX.XX.XX.XX sudo sh -c 'sudo service docker stop' 
sudo: sorry, you must have a tty to run sudo
ERRO[0077] Error creating machine: exit status 1        
WARN[0077] You will want to check the provider to make sure the machine and associated resources were properly removed. 
FATA[0077] Error creating machine     
```

The instance is generated on openstack and when adding -tt to the ssh command it appears to work as intended.

```sh
ssh -tt -o IdentitiesOnly=yes -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=quiet -p 22 -i /home/nick/.docker/machine/machines/testDockerMachine/id_rsa centos@XX.XX.XX.XX "sudo service docker stop"
Redirecting to /bin/systemctl stop  docker.service
```

**Comment by nathanleclaire** [comment]
cc @ggiamarchi

**Comment by nathanleclaire** [comment]
Thanks for the report @superbeeny.  A quick Google reveals http://unix.stackexchange.com/questions/122616/why-do-i-need-a-tty-to-run-sudo-if-i-can-sudo-without-a-password, so I think we might have to check for that as part of the provisioning.  Are you able to run `sudo service docker restart` when manually SSHed in to the box?

**Comment by superbeeny** [comment]
yes i can do it manually, and if i update sudoers to remove the "require tty" as described in the article I can get it to run without error. The default centos 7 cloud image does not contain that edit and so will not work "out of the box"

**Comment by ehazlett** [comment]
@superbeeny thanks for reporting.  right now, only Ubuntu is supported as a base OS but we are wanting to add more options via cloudinit. See #699 for details.  Thanks!

**Comment by nathanleclaire** [comment]
This _should_ work now, please re-open if you have any issues.  Thanks!

**Comment by kadishmal** [comment]
I still have the same issue with docker-machine v0.3.0 on CentOS 6.6.

If I ssh manually I can start docker and use docker normally. However when adding the host to docker machine it exist with an error:

    ....
    Using SSH client type: external
    &{/usr/bin/ssh [/usr/bin/ssh -o PasswordAuthentication=no -o IdentitiesOnly=yes -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=quiet -o ConnectionAttempts=3 -o ConnectTimeout=10 -i /home1/user/.docker/machine/machines/host1/id_rsa -p 22 user@11.11.116.100 -t sudo yum -y update] []  <nil> <nil> <nil> [] <nil> <nil> <nil> ?reflect.Value? false [] [] [] [] <nil>}
    Error creating machine: exit status 1
    You will want to check the provider to make sure the machine and associated resources were properly removed.

**Comment by nathanleclaire** [comment]
@kadishmal Hm, as far as I know the CentOS support in Docker Machine is for versions >=7.

**Comment by cusspvz** [comment]
Same here with a CentOS based distro.

```bash
INFO[0001] Creating Azure machine...
INFO[0062] Waiting for SSH...
ERRO[0519] Error creating machine: error installing docker: exit status 1
sudo: sorry, you must have a tty to run sudo


WARN[0519] You will want to check the provider to make sure the machine and associated resources were properly removed.
FATA[0519] Error creating machine
```

**Comment by nrvale0** [comment]
I'm able to repro this with latest docker-machine and latest CentOS7 AMI.

```ShellSession
➜  docker-tag docker-machine --version                          
docker-machine version 0.8.2, build e18a919
➜  docker-tag docker-machine ssh centos-test -- 'uname -a'      
Linux centos-test 3.10.0-327.10.1.el7.x86_64 #1 SMP Tue Feb 16 17:03:50 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
➜  docker-tag docker-machine ssh centos-test -- sudo sh -c 'sudo service docker stop'
sudo: sorry, you must have a tty to run sudo
exit status 1
```

**Comment by nrvale0** [comment]
Interestingly enough, 

```ShellSession
$ docker-machine --native-ssh centos-test sudo id
```

works fine. The key seems to be specifying the option: --native-ssh
