### ISSUE TITLE
Add option to pass daemon config flags to docker machine on create

### ISSUE THREAD

**Issue by justinclayton** [docker/machine#701]
Like --insecure-registry. It eliminates the extra step of sshing into every docker-machine box and manually adding these options and restarting the daemon.

Or, just merge docker/docker#8887. ;-)

**Comment by florentvaldelievre** [comment]
+1

**Comment by ehazlett** [comment]
Thanks for reporting.  We are wanting to add daemon configuration in the upcoming cloudinit support.  You can follow the development in #699.  Thanks!
