### ISSUE TITLE
Coreos in azure and aws

### ISSUE THREAD

**Issue by freeman1988** [docker/machine#703]
I tried to create coreos instance in azure with following command:
```
docker-machine_linux-386 create -d azure --azure-image "2b171e93f07c4903bcad35bda10acf22__CoreOS-Stable-557.2.0" --azure-publish-settings-file "azure-credentials.publishsettings" --azure-size "Small" --azure-username "core" --azure-password "123456Test!" coreos-test-machine
```
The output was: `bash: !": event not found`

Then I deleted `--azure-password "123456Test!"` option and docker-machine created instance! But when docker-machine tried to exec `sudo service stop docker` it failed with error:

```
DEBU[0215] executing: ssh -o IdentitiesOnly=yes -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=quiet -p 22 -i /home/user/.docker/machine/machines/coreos-test-machine/id_rsa core@coreos-test-machine.cloudapp.net sudo service docker stop 

We trust you have received the usual lecture from the local System
Administrator. It usually boils down to these three things:

    #1) Respect the privacy of others.
    #2) Think before you type.
    #3) With great power comes great responsibility.

sudo: no tty present and no askpass program specified
ERRO[0219] Error creating machine: exit status 1        
WARN[0219] You will want to check the provider to make sure the machine and associated resources were properly removed. 
FATA[0219] Error creating machine     
```

So then I tried to launch coreos with docker-machine in aws:
```
docker-machine_linux-386 -D create -d amazonec2 --amazonec2-access-key "xxx" --amazonec2-secret-key "xxx" --amazonec2-ami "ami-3415525c" --amazonec2-instance-type "t2.micro" --amazonec2-region "us-east-1" --amazonec2-zone "a" --amazonec2-subnet-id "subnet-xxx"  --amazonec2-vpc-id "vpc-xxx" "coreos-mq-test"
```

Docker-machine created instance and waiting for ssh
```
DEBU[0031] created instance ID i-xxxxx, IP address 54.152.xx.xx
INFO[0031] Waiting for SSH on 54.152.161.xx.xx
```
Meanwhile in aws console the status of this instance was `running` and then status changed to `stopped`. AWS logs says nothing :(  and docker-machine still waiting for ssh :(

BTW docker-machine creates ubuntu instance without any problems.

**Comment by ehazlett** [comment]
Right now, Ubuntu is the only supported base OS.  We are working to integrate cloudinit support soon to offer more options.  Thanks for the feedback!

**Comment by ezeeetm** [comment]
@ehazlett I came here researching this also.  While cloudinit support might be a good idea, looking at the code I think there might be a painless way to achieve this in the near term.  the ami mappings appear to be handled by machine/drivers/amazonec2/utils.go.  As you say, they are all currently statically mapped to whatever ubuntu 12.04.2 image for a given region.  Is there any interest in being able to pass the ami id as a parameter?  If no param, use the defualt values in utils.go.  If param, use the ami-id passed in?

In this way, we should be able to use machine to spin up CoreOS/Snappy docker hosts without too much work.

I'm a python dev, but I'd be willing to figure this out in go if you think you'd pull it in?

**Comment by ehazlett** [comment]
@ezeeetm You can already pass any AMI ID you want, however, it must be based on Ubuntu currently as that is all our provisioner can use in 0.2.0.  We are adding more base OS support in 0.3.0 but CoreOS isn't yet supported.

**Comment by ezeeetm** [comment]
ah, i did not notice you can pass amis already.  Ill go RTFM a bit.  Snappy is ubuntu so there is a minimalist docker image we can use now....

**Comment by sylus** [comment]
Given a provisioner has been added for CoreOS now can this be reopened?
