### ISSUE TITLE
docker machine create and certs

### ISSUE THREAD

**Issue by florentvaldelievre** [docker/machine#705]
Hello,

Is it possible to create a docker machine without any TLS certificate for the docker daemon without hacking /var/lib/boot2docker/profile in ssh?
````
docker-machine create --driver virtualbox dev
````

on boot2docker:
````
ps aux
 /usr/local/bin/docker -d -D -g /var/lib/docker -H unix:// -H tcp://0.0.0.0:2375 --tlsverify --tlscacert=/var/lib/boot2docker/ca.pe
````

/var/lib/boot2docker/profile
````
EXTRA_ARGS='--tlsverify --tlscacert=/var/lib/boot2docker/ca.pem --tlskey=/var/lib/boot2docker/server-key.pem --tlscert=/var/lib/boot2docker/server
CACERT=/var/lib/boot2docker/ca.pem
SERVERCERT=/var/lib/boot2docker/server-key.pem
SERVERKEY=/var/lib/boot2docker/server.pem
DOCKER_TLS=no
````

Thanks

**Comment by sthulb** [comment]
In short, not at the moment. 

I wouldn't expect machine to offer this to be honest. Machine wants to focus on being secure, so to do that, we use TLS.

**Comment by florentvaldelievre** [comment]
Ok Thank you.

We would like to create dev vms running a boot2docker and a docker daemon ready to use.
A rest client targets the remote docker API. We wanted to avoid talking with the remote API through secure channel as the communication is on the same machine PC dev => Boot2docker.

Tell me if i am wrong, but adding this secured layer involve each developer to copy manually certificates from boot2docker to their machine. This step has to be done each time a VM is created.

**Comment by sthulb** [comment]
If you're using machine, the certificates are automatically created for you and placed in a directory similar to: $HOME/.docker/machine/<machine>/

**Comment by florentvaldelievre** [comment]
I see, thank you, issue can be closed

**Comment by sthulb** [comment]
I can't, do you mind? :)

**Comment by florentvaldelievre** [comment]
Sure :)
