### ISSUE TITLE
--storage-path isn't used anymore

### ISSUE THREAD

**Issue by nathanleclaire** [docker/machine#708]
In the changes to the machine internal directory, `--storage-path` lost its ability to do anything.  `GetBaseDir` in `utils/utils.go` still checks `MACHINE_STORAGE_PATH`, but not the flag.

**Comment by ehazlett** [comment]
Thanks for pointing this out.  I will work on this to get it fixed asap.

**Comment by nathanleclaire** [comment]
:+1:
