### ISSUE TITLE
Question: How do you forward ports with Virtualbox to boot2docker?

### ISSUE THREAD

**Issue by florentvaldelievre** [docker/machine#710]
Hello,

I have created a VM using ```` docker-machine create --driver virtualbox dev ````
I have a container running on 8500:8500 on this dev vm and boot2docker

I would like to forward my port from the Host -> virtualbox -> boot2docker so i can target my container from my host : ````curl localhost:8500````
Can anyone point me to the right direction ?

Thank you

**Comment by UserTaken** [comment]
You can run
```
VBoxManage controlvm dev natpf1 "8050,tcp,127.0.0.1,8050,,8050"
```

**Comment by SvenDowideit** [comment]
the best thing to do is _not_ port forward. instead, use the second network attached to your machine

get it using `docker-machine ip` - the mapped container ports will be there already.

**Comment by florentvaldelievre** [comment]
Thank you very much for the answers, appreciated !
