### ISSUE TITLE
vsphere driver can't create

### ISSUE THREAD

**Issue by kraney** [docker/machine#716]
Using the vsphere driver, the IP address that's detected for the docker VM is the IP of eth0 - which is the docker private IP address. The outgoing interface is eth1. So then docker-machine can't connect to the VM it just created.

INFO[0283] Configuring virtual machine vsphere-docker...
ERRO[0374] Error creating machine: dial tcp 172.17.42.1:22: operation timed out

The vSphere summary panel also shows the private IP. It would probably simplify things if eth0 were the public IP, and eth1 was the private one.

**Comment by frapposelli** [comment]
Can't reproduce, are you using a custom b2d iso?

**Comment by kraney** [comment]
I'm no longer able to reproduce it, either.

I was not using a custom boot2docker, but at the time I reported the issue the iso that was downloaded by docker-machine was named boot2docker-vmw.iso (on Feb 26.) Now it's boot2docker-1.5.0-GH747.iso.

It seems likely that the current boot2docker iso resolves the issue. In any case, something has resolved it.
