### ISSUE TITLE
create fails due to: No IP address found

### ISSUE THREAD

**Issue by schmunk42** [docker/machine#721]
Tried 0.1.0 and dev-master

```
Kraftbuch:machine tobias$ ./docker-machine_darwin-amd64 create -d virtualbox ved2
INFO[0000] Creating SSH key...                          
INFO[0000] Creating VirtualBox VM...                    
INFO[0011] Starting VirtualBox VM...                    
INFO[0012] Waiting for VM to start...                   
ERRO[0065] Error creating machine: No IP address found 4: eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP qlen 1000
    link/ether 08:00:27:26:c2:13 brd ff:ff:ff:ff:ff:ff
    inet6 fe80::a00:27ff:fe26:c213/64 scope link 
       valid_lft forever preferred_lft forever
 
WARN[0065] You will want to check the provider to make sure the machine and associated resources were properly removed. 
FATA[0065] Error creating machine                       
```

The problem is somewhere around here:
https://github.com/docker/machine/blob/master/drivers/virtualbox/virtualbox.go#L479

Looks like Docker `eth1`(?) is not coming up in my host?

**Comment by jeffdm** [comment]
This output may or may not help:

```
~/w/updateserver (master) $ docker-machine ls
NAME   ACTIVE   DRIVER       STATE     URL                         SWARM
bob    *        virtualbox   Stopped                               
dev             virtualbox   Running   tcp://192.168.99.100:2376   
dev2            virtualbox   Stopped                               
test            virtualbox   Stopped                               
~/w/updateserver (master) $ pkill VBox
~/w/updateserver (master) $ docker-machine create -d virtualbox teshads
INFO[0000] Creating SSH key...                          
INFO[0000] Creating VirtualBox VM...                    
ERRO[0006] Error creating machine: exit status 1        
WARN[0006] You will want to check the provider to make sure the machine and associated resources were properly removed. 
FATA[0006] Error creating machine                       
~/w/updateserver (master) $ docker-machine ls
^C⏎                                                                                                                                                                                               ~/w/updateserver (master) $ docker-machine ls
ERRO[0000] error getting URL for host dev: No IP address found 4: eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP qlen 1000
    link/ether 08:00:27:a0:17:bd brd ff:ff:ff:ff:ff:ff
    inet6 fe80::a00:27ff:fea0:17bd/64 scope link tentative 
       valid_lft forever preferred_lft forever
 
NAME      ACTIVE   DRIVER       STATE     URL   SWARM
bob                virtualbox   Stopped         
dev       *        virtualbox   Running         
dev2               virtualbox   Stopped         
teshads            virtualbox   Stopped         
test               virtualbox   Stopped         
~/w/updateserver (master) $ docker-machine ls
NAME      ACTIVE   DRIVER       STATE     URL                         SWARM
bob                virtualbox   Stopped                               
dev       *        virtualbox   Running   tcp://192.168.99.100:2376   
dev2               virtualbox   Stopped                               
teshads            virtualbox   Stopped                               
test               virtualbox   Stopped       
```

It seems like terminating VirtualBox with `pkill VBox` can cause some errors that span a couple issues. Will post more info if I learn more

**Comment by schmunk42** [comment]
Turns out that my docker machine did not get an IPv4 assigned.
Therefore the error and the problem that is *was* not accessible from outside.

My workaround was to stop the machine and manually set the secondary (eth1) network interface to NAT  in the VirtualBox Manager. So I gets an IPv4 address and Kitematic can at least connect.

 Host: OS X, probably related http://serverfault.com/q/217256/96303

**Comment by ehazlett** [comment]
Thanks for reporting.  We will probably need more checks around the IP allocation and possibly a timeout with an error in case it doesn't get one.

**Comment by motin** [comment]
Having the exact same issue. Latest OS X Yosemite and VirtualBox (4.3.24)

**Comment by ehazlett** [comment]
thanks @motin.  we are working on a provisioner and driver refactor that will address these issues.  we will have something for you to test soon.  thanks for reporting!

**Comment by petersellars** [comment]
I also hit this issue on Windows 8.1/Virtualbox 4.3.20 - using 0.1.0 (latest from the Docker documentation page).

I noticed the docker-machine VM was using a different VirtualBox Host-Only Adapter compared to a working 'boot2docker' instance. I manually updated this to the same adapter (which has a DHCP Server) and restarted the machine. The docker-machine then picked up an ip address and I was able to make it active.

@ehazlett - is this likely to be fixed by your work - or a different aspect of the issue? Can provide more information if it helps.

**Comment by rajurs** [comment]
I am seeing somewhat similar results, on Windows 8.1 update 1. docker-machine create says the dev VM was created, but I don't see it in VirtualBox. Then I create a second machine dev2 and get the same result (cannot see the VM). A few more machines later, I get the IP address error. How do I activate the dev or dev2 VMs so that I can see it? Is this behavior expected if I already have Boot2Docker running on VirtualBox?

**Comment by ehazlett** [comment]
@petersellars yes we have added checks for waiting for state.  The driver refactor has been merged as well so there should be better stability there.  Windows support is unfortunately lacking a bit at the moment and we are working to get that better.

@petersellars your comment about the b2d host-only adapter is interesting.  I will check to see if I can re-create.  That may have been part of the issue and we will definitely want to get that fixed to help migrate users from b2d.

@rajurs you should see the VM in virtualbox after create.  you may need to close the interface and re-open it.  note: you will not see the VM launch as machine launches them using the `headless` mode.

**Comment by rajurs** [comment]
I still don't see the VM. I am running Version 4.3.24 of VB and V1.5 of Docker Do I need to go down to the older version of VirtualBox and Docker and Boot2Docker?

**Comment by ehazlett** [comment]
Hmm.  I've tested on Win8.1 Pro with vbox 4.3.20 and the latest machine build from master.  Everything is fine:

![2015-03-18-112639_1413x573_scrot](https://cloud.githubusercontent.com/assets/260642/6712219/cadb6e4e-cd61-11e4-8d07-b390523f3a45.png)

**Comment by rajurs** [comment]
Hmm that is very odd. See screen shot below. I start two machines successfully and they are running (test-dev is he active one).  VirtualBox does not list either one!


 





raj


Sent from Windows Mail





From: Evan Hazlett
Sent: ‎Wednesday‎, ‎March‎ ‎18‎, ‎2015 ‎8‎:‎28‎ ‎AM
To: docker/machine
Cc: 'Pradeep Rajurs'





Hmm. I've tested on Win8.1 Pro with vbox 4.3.20 and the latest machine build from master. Everything is fine:

 2015-03-18-112639_1413x573_scrot

**Comment by rajurs** [comment]
Odd part is, I can docker-machine ssh into the host and run containers!






Sent from Windows Mail





From: 'Pradeep Rajurs'
Sent: ‎Wednesday‎, ‎March‎ ‎18‎, ‎2015 ‎9‎:‎18‎ ‎AM
To: docker/machine, docker/machine





Hmm that is very odd. See screen shot below. I start two machines successfully and they are running (test-dev is he active one).  VirtualBox does not list either one!




 









raj


Sent from Windows Mail





From: Evan Hazlett
Sent: ‎Wednesday‎, ‎March‎ ‎18‎, ‎2015 ‎8‎:‎28‎ ‎AM
To: docker/machine
Cc: 'Pradeep Rajurs'





Hmm. I've tested on Win8.1 Pro with vbox 4.3.20 and the latest machine build from master. Everything is fine:

 2015-03-18-112639_1413x573_scrot

**Comment by ehazlett** [comment]
I can't see the screenshots but that is odd.  Are you sure you aren't running as a different user or something?

**Comment by rajurs** [comment]
Not sure what you mean by different user. 


Its a Windows 8.1 machine with just one user account, running VirtualBox, Docker-Machine Binary and that's pretty much it. 


Raj




Sent from Windows Mail

 



From: Evan Hazlett
Sent: ‎Wednesday‎, ‎March‎ ‎18‎, ‎2015 ‎3‎:‎29‎ ‎PM
To: docker/machine
Cc: Pradeep Rajurs





I can't see the screenshots but that is odd. Are you sure you aren't running as a different user or something?

**Comment by atomi** [comment]
HIt this too. And docker-machine ssh works fine.
Was the boot2docker.iso recently updated? I don't think I've changed anything else.

**Comment by rajurs** [comment]
I tried older versions of Boot2Docker, VirtualBox and still see the same issue. 






Sent from Surface





From: atomi
Sent: ‎Thursday‎, ‎March‎ ‎19‎, ‎2015 ‎1‎:‎03‎ ‎PM
To: docker/machine
Cc: 'Pradeep Rajurs'





HIt this too. And docker-machine ssh works fine.
Was the boot2docker.iso recently updated? I don't think I've changed anything else.

**Comment by petersellars** [comment]
@rajurs if you don't see the VM in Virtualbox check that you are not running either your command window or Virtualbox as Administrator and the other as your user. If I run either as the Administrator and the other as a user I can't see the box in Virtualbox. Believe this is what was meant by running as different users.

**Comment by petersellars** [comment]
@ehazlett thanks for the update. Will do some more testing in this space and provide any feedback that would be useful. I use a Windows machine at work and Debian instance at home so happy to help test in this space. Will look to contribute fixes when I can too.

Host-Only Adapter issue looks like it is specific to my environment based on your successful screenshots so will have to investigate that further myself.

**Comment by ehazlett** [comment]
@petersellars ok thanks!  i will keep testing as well to see if i can re-create.

**Comment by rajurs** [comment]
Thanks Much. Looks like its working now. The Cmd prompt was being started as admin…duh!

Since I am a Linux newbie, every step takes a while to get working on Windows 😊

 

Now I have the issue of running docker-machine on Windows alongside the Docker CLI for Windows. I compiled the github Windows Docker Client files to build the Docker CLI for Windows. 


Question is: What is the “eval” equivalent on Windows so that I can do this. eval "$(docker-machine env dev)"

Thanks

raj






Sent from Windows Mail





From: Peter Sellars
Sent: ‎Thursday‎, ‎March‎ ‎19‎, ‎2015 ‎2‎:‎48‎ ‎PM
To: docker/machine
Cc: Pradeep Rajurs





@rajurs if you don't see the VM in Virtualbox check that you are not running either your command window or Virtualbox as Administrator and the other as your user. If I run either as the Administrator and the other as a user I can't see the box in Virtualbox. Believe this is what was meant by running as different users.

**Comment by umegaya** [comment]
hi, I hit same issue today and at least in my environment, the reason caused "No IP address found", seems to be my host interface setting. 
it was like following. that is, IP address was in the range which docker-machine want to assign to its eth1
```
Name:            vboxnet1
GUID:            786f6276-656e-4174-8000-0a0027000001
DHCP:            Disabled
IPAddress:       192.168.99.1
NetworkMask:     255.255.255.0
IPV6Address:     
IPV6NetworkMaskPrefixLength: 0
HardwareAddress: 0a:00:27:00:00:01
MediumType:      Ethernet
Status:          Up
VBoxNetworkName: HostInterfaceNetworking-vboxnet1
```

so I changed this to below setting and re-create docker machine again, this problem did not occur.
```
Name:            vboxnet1
GUID:            786f6276-656e-4174-8000-0a0027000001
DHCP:            Disabled
IPAddress:       192.168.59.103
NetworkMask:     255.255.255.0
IPV6Address:     
IPV6NetworkMaskPrefixLength: 0
HardwareAddress: 0a:00:27:00:00:01
MediumType:      Ethernet
Status:          Up
VBoxNetworkName: HostInterfaceNetworking-vboxnet1
```

hope this would help you guys in trouble.

**Comment by rajurs** [comment]
Thanks. 

My setup is throwing a weird error on a Windows 8.1 setup. (Docker Client compiled and installed on the machine with VirtualBox (4.3.26) 




I keep getting the error message stating that the client and server versions are different. Boot2Docker says I have version 1.5 and I can SSH into the machine. I just can’t issue Docker commands from the cmd prompt.





Rajurs


Sent from Windows Mail






From: iyatomi takehiro
Sent: ‎Tuesday‎, ‎March‎ ‎31‎, ‎2015 ‎8‎:‎42‎ ‎PM
To: docker/machine
Cc: rajurs





hi, I hit same issue today and at least in my environment, the reason caused "No IP address found", seems to be my host interface setting. 
it was like following. that is, IP address was in the range which docker-machine want to assign to its eth1
Name:            vboxnet1
GUID:            786f6276-656e-4174-8000-0a0027000001
DHCP:            Disabled
IPAddress:       192.168.99.1
NetworkMask:     255.255.255.0
IPV6Address:     
IPV6NetworkMaskPrefixLength: 0
HardwareAddress: 0a:00:27:00:00:01
MediumType:      Ethernet
Status:          Up
VBoxNetworkName: HostInterfaceNetworking-vboxnet1


so I changed this to below setting and re-create docker machine again, this problem did not occur.
Name:            vboxnet1
GUID:            786f6276-656e-4174-8000-0a0027000001
DHCP:            Disabled
IPAddress:       192.168.59.103
NetworkMask:     255.255.255.0
IPV6Address:     
IPV6NetworkMaskPrefixLength: 0
HardwareAddress: 0a:00:27:00:00:01
MediumType:      Ethernet
Status:          Up
VBoxNetworkName: HostInterfaceNetworking-vboxnet1


hope this would help you guys in trouble.

**Comment by ehazlett** [comment]
@umegaya ah ok -- perhaps we need to check the subnet when creating.  most of the time it shouldn't overlap but we should check it to make sure.

@rajurs that is because you are using a newer client than server.  you will need to build the windows docker client for v1.5.0 (you can use the tag).

**Comment by stevengssns** [comment]
@umegaya Thanks a lot! This workaround finally worked for me.

Some details about my environment should anyone be interested..

I was having this issue on my most recent laptop:

MacBook Pro with Yosemite
VirtualBox v4.3.26
docker client v1.5.0

On an older MacBook Pro (same setup) everything was working without a problem.

**Comment by j0hnsmith** [comment]
I'm getting this problem too, where do I find the settings shown in https://github.com/docker/machine/issues/721#issuecomment-88340886

**Comment by ehazlett** [comment]
@j0hnsmith you can view that with `VBoxManage list hostonlyifs` -- would you mind posting that here too?  thanks!

**Comment by j0hnsmith** [comment]
@ehazlett, thanks, here's the pertinent output

    ...
    Name:            vboxnet5
    GUID:            786f6276-656e-4574-8000-0a0027000005
    DHCP:            Disabled
    IPAddress:       192.168.99.1
    NetworkMask:     255.255.255.0
    IPV6Address:     
    IPV6NetworkMaskPrefixLength: 0
    HardwareAddress: 0a:00:27:00:00:05
    MediumType:      Ethernet
    Status:          Up
    VBoxNetworkName: HostInterfaceNetworking-vboxnet5
    ...

So I changed `IPAddress:       192.168.99.1` to `IPAddress:       192.168.100.1` (via Virtualbox > Preferences > Network > Host-only Networks > vboxnet5) and docker-machine is now happy. I think that IP address came from a Vagrantfile supplied by a colleague, there's nothing special about it to me, but it would be good if docker-machine found an unused range.

**Comment by ehazlett** [comment]
Hmm that's odd.  Mine is `192.168.99.1` as well and everything works.  I wonder if it's a race in vbox to grab a default or something.

**Comment by j0hnsmith** [comment]
I had an _existing_ host only network configured to use `192.168.99.1` (vboxnet5) that wasn't created by `docker-machine`, once I changed the IP to `192.168.100.1` `docker-machine` created a new network on `192.168.99.1` (vboxnet8) and all is good.

**Comment by ehazlett** [comment]
@j0hnsmith ah ok that could be it -- would you mind posting all of your interface output so I can compare to see what we do different?

**Comment by j0hnsmith** [comment]
@ehazlett Here's the output from when I was getting the error

    $ VBoxManage list hostonlyifs
    Name:            vboxnet0
    GUID:            786f6276-656e-4074-8000-0a0027000000
    DHCP:            Disabled
    IPAddress:       192.168.56.1
    NetworkMask:     255.255.255.0
    IPV6Address:     
    IPV6NetworkMaskPrefixLength: 0
    HardwareAddress: 0a:00:27:00:00:00
    MediumType:      Ethernet
    Status:          Down
    VBoxNetworkName: HostInterfaceNetworking-vboxnet0

    Name:            vboxnet1
    GUID:            786f6276-656e-4174-8000-0a0027000001
    DHCP:            Disabled
    IPAddress:       192.168.50.1
    NetworkMask:     255.255.255.0
    IPV6Address:     
    IPV6NetworkMaskPrefixLength: 0
    HardwareAddress: 0a:00:27:00:00:01
    MediumType:      Ethernet
    Status:          Down
    VBoxNetworkName: HostInterfaceNetworking-vboxnet1

    Name:            vboxnet2
    GUID:            786f6276-656e-4274-8000-0a0027000002
    DHCP:            Disabled
    IPAddress:       10.10.10.1
    NetworkMask:     255.255.255.0
    IPV6Address:     
    IPV6NetworkMaskPrefixLength: 0
    HardwareAddress: 0a:00:27:00:00:02
    MediumType:      Ethernet
    Status:          Down
    VBoxNetworkName: HostInterfaceNetworking-vboxnet2

    Name:            vboxnet3
    GUID:            786f6276-656e-4374-8000-0a0027000003
    DHCP:            Disabled
    IPAddress:       172.16.42.1
    NetworkMask:     255.255.255.0
    IPV6Address:     
    IPV6NetworkMaskPrefixLength: 0
    HardwareAddress: 0a:00:27:00:00:03
    MediumType:      Ethernet
    Status:          Down
    VBoxNetworkName: HostInterfaceNetworking-vboxnet3

    Name:            vboxnet4
    GUID:            786f6276-656e-4474-8000-0a0027000004
    DHCP:            Disabled
    IPAddress:       172.17.8.1
    NetworkMask:     255.255.255.0
    IPV6Address:     
    IPV6NetworkMaskPrefixLength: 0
    HardwareAddress: 0a:00:27:00:00:04
    MediumType:      Ethernet
    Status:          Down
    VBoxNetworkName: HostInterfaceNetworking-vboxnet4

    Name:            vboxnet5
    GUID:            786f6276-656e-4574-8000-0a0027000005
    DHCP:            Disabled
    IPAddress:       192.168.99.1
    NetworkMask:     255.255.255.0
    IPV6Address:     
    IPV6NetworkMaskPrefixLength: 0
    HardwareAddress: 0a:00:27:00:00:05
    MediumType:      Ethernet
    Status:          Up
    VBoxNetworkName: HostInterfaceNetworking-vboxnet5

    Name:            vboxnet6
    GUID:            786f6276-656e-4674-8000-0a0027000006
    DHCP:            Disabled
    IPAddress:       10.0.0.1
    NetworkMask:     255.255.255.0
    IPV6Address:     
    IPV6NetworkMaskPrefixLength: 0
    HardwareAddress: 0a:00:27:00:00:06
    MediumType:      Ethernet
    Status:          Down
    VBoxNetworkName: HostInterfaceNetworking-vboxnet6

    Name:            vboxnet7
    GUID:            786f6276-656e-4774-8000-0a0027000007
    DHCP:            Disabled
    IPAddress:       192.168.59.3
    NetworkMask:     255.255.255.0
    IPV6Address:     
    IPV6NetworkMaskPrefixLength: 0
    HardwareAddress: 0a:00:27:00:00:07
    MediumType:      Ethernet
    Status:          Down
    VBoxNetworkName: HostInterfaceNetworking-vboxnet7

**Comment by ehazlett** [comment]
hmm yeah nothing is sticking out.  perhaps we should have a "reset" command that would tear these down and rebuild?  /cc @nathanleclaire

**Comment by guiwork** [comment]
I got around this error

No IP address found 4: eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 08:00:27:2a:ed:4d brd ff:ff:ff:ff:ff:ff
    inet6 fe80::a00:27ff:fe2a:ed4d/64 scope link 
       valid_lft forever preferred_lft forever

By removing all my Host-only network in VirtualBox (I did not need my existing VMs), then recreated the VM for docker-machine and it all works fine now. 

I had 7 host-only networks in VirtualBox similar to @j0hnsmith , I removed them via the UI (Preferences -> Network -> Host-only Networks). I'm sure there is a VBoxManage equivalent. This is just a workaround and assumes you can delete these on VirtualBox.

**Comment by schmunk42** [comment]
@guiwork Great! That worked for me too, I had 20 vboxnet adapters.

Note: In my setup the newly created VMs from docker-machine got assigned the same vboxnet adapter as boot2docker. It looks like there is a conflict for that interface then.

**Comment by nathanleclaire** [comment]
@ehazlett I wonder if we should clear out existing host only adapters on create if there are no VMs using them.

**Comment by rcsenkbeil** [comment]
@guiwork, thanks! Fixed my issue, too!

**Comment by gdm85** [comment]
I am also affected by this issue; I am going to try re-creating the docker-machine VM, although I'd have preferred to not need to :(

**Comment by motin** [comment]
I wonder if this same issue is causing migrations to fail: https://github.com/docker/toolbox/issues/216 https://github.com/docker/toolbox/issues/219

**Comment by Rykka** [comment]
+1 fixed my issue too

**Comment by nathanleclaire** [comment]
This issue is very long and contains a lot of digressions.  If someone continues to encounter similar ones please open a new one at https://github.com/docker/machine/issues/new with detailed information including:

- Which OS you are on
- Anything atypical in networking configuration (VPN, proxy, SSH configuration settings, etc.),
- Output of the misbehaving commands with the `--debug` flag
- the VirtualBox logs from `~/.docker/machine/machines/name/name`.  

Thanks!

- N
