### ISSUE TITLE
syntax for "softlayer-private-net-only" flag

### ISSUE THREAD

**Issue by crosen188** [docker/machine#724]
The command works without the --softlayer-private-net-only flag, but I cannot determine what to use as the value for this flag.

docker-machine create --driver softlayer  --softlayer-api-endpoint "https://api.softlayer.com/rest/v3" --softlayer-api-key <id> --solayer-user "username" --softlayer-cpu "1" --softlayer-disk-size "0" --softlayer-domain "domain.softlayer.com" --softlayer-hostname "crsrv001" --softlayer-image "UBUNTU_LATEST" --softlayer-memory "4096" --softlayer-private-net-only "1773" --softlayer-region "dal09" sltest001

**Comment by cpuguy83** [comment]
This is just a bool, so just passing the flag in with no arguments enables private-only networking.

**Comment by crosen188** [comment]
docker-machine create --driver softlayer  --softlayer-api-endpoint "https://api.softlayer.com/rest/v3" --softlayer-api-key <id> --solayer-user "username" --softlayer-cpu "1" --softlayer-disk-size "0" --softlayer-domain "domain.softlayer.com" --softlayer-hostname "crsrv001" --softlayer-image "UBUNTU_LATEST" --softlayer-memory "4096" --softlayer-private-net-only --softlayer-region "dal09" sltest003

Results in --> Incorrect Usage.

**Comment by cpuguy83** [comment]
@crosen188 you have `solayer-user` instead of `softlayer-user`.
It also looks like you are setting all the options to their default values... no need for this.
The only required flags are domain, user, and apikey

**Comment by crosen188** [comment]
Thanks @cpuguy83, the copy/paste got me because I had deployed successfully before trying to add the --softlayer-private-net-only flag.  Is there or any plans to add support for specifying the VLAN for deployment?

**Comment by ehazlett** [comment]
@cpuguy83 thanks.  @crosen188 right now there are not plans to add VLAN support but feel free to open a separate issue.  thanks for reporting!
