### ISSUE TITLE
softlayer "waiting for host to become available"

### ISSUE THREAD

**Issue by crosen188** [docker/machine#725]
I am able to deploy a VM and can ping the IP after obtaining from the Softlayer console, but my Docker Machine command continues to sit here...

INFO[0000] Creating SSH key...
INFO[0004] Getting Host IP
INFO[0027] Waiting for host to become available

docker-machine create --driver softlayer  --softlayer-api-endpoint "https://api.softlayer.com/rest/v3" --softlayer-api-key <id> --solayer-user "username" --softlayer-cpu "1" --softlayer-disk-size "0" --softlayer-domain "domain.softlayer.com" --softlayer-hostname "crsrv001" --softlayer-image "UBUNTU_LATEST" --softlayer-memory "4096" --softlayer-region "dal09" sltest003

**Comment by cpuguy83** [comment]
Hmmm... maybe here: https://github.com/docker/machine/blob/master/drivers/softlayer/driver.go#L299-L301
Maybe we can throw those errors into debug logs to see why it could be erroring.

**Comment by wzymaster** [comment]
for me,  it sits there for ever like below  :  

[0000] Creating SSH key...
INFO[0005] Getting Host IP
INFO[0028] Waiting for host to become available
INFO[0191] Configuring host OS
...

**Comment by ehazlett** [comment]
This was fixed in #760
