### ISSUE TITLE
UX: machine saves failed creation

### ISSUE THREAD

**Issue by ahmetalpbalkan** [docker/machine#731]
I see that machine is saving the machine info even though `machine create` fails. If that's the by design behavior, please close this. IMO, this should be transactional (and should attempt cleaning created artifacts after "error creating the machine") because if it fails user most probably will try to create it again with the same name.

```
C:\Users\ahmetb>docker-machine create -d virtualbox docker-vb
←[34mINFO←[0m[0000] Creating SSH key...
←[31mERRO←[0m[0000] Error creating machine: ssh-keygen not found in the path, please install ssh-keygen
←[33mWARN←[0m[0000] You will want to check the provider to make sure the machine and associated resources were properly removed.
←[31mFATA←[0m[0000] Error creating machine

C:\Users\ahmetb>docker-machine create -d virtualbox docker-vb
←[31mERRO←[0m[0000] Error creating machine: Machine docker-vb already exists
←[33mWARN←[0m[0000] You will want to check the provider to make sure the machine and associated resources were properly removed.
←[31mFATA←[0m[0000] Error creating machine
```

**Comment by ehazlett** [comment]
Thanks for the feedback.  We've gone round and round on this one.  We chose not to automatically cleanup as we don't want to do uncertain destructive operations.  We are working on getting the proper creation and removal behavior (including possibly using discovery instead of explicit stores).

**Comment by ahmetalpbalkan** [comment]
Sounds good then, I'm closing in favor of other discussions.

**Comment by ehazlett** [comment]
Ok thanks!

**Comment by bytepoet** [comment]
Was hoping there would be an easier way to make docker-machine ls reflect the truth as stated by api return from the provider.

Right now if I remove a host from the provider web page manually, it still shows up in docker-machine ls, in which I remove with cli-fu. And put it on the expire list.  After 24 hours of "error" it executes a small cleanup script.

**Comment by ahmetalpbalkan** [comment]
In this example above, a check for `ssh-keygen` with exec.LookPath just after we start "create" can help a great deal avoiding this problem most of the time –at least on windows.

**Comment by ahmetalpbalkan** [comment]
sorry, mistakenly reopened.

**Comment by ehazlett** [comment]
@bytepoet i think this is something that a discovery type of service instead of an inventory would be really nice.
