### ISSUE TITLE
env output is not compatible with windows

### ISSUE THREAD

**Issue by ahmetalpbalkan** [docker/machine#732]
```
C:\Users\ahmetb>docker-machine env docker-vb
export DOCKER_TLS_VERIFY=yes
export DOCKER_CERT_PATH=C:\Users\ahmetb\.docker\machine\machines\docker-vb
export DOCKER_HOST=tcp://192.168.99.100:2376
```

export wouldn't work on windows cmd.exe/powershell. We must generate the correct output for cmd/ps and must also keep in mind that user might be running on mingw(msys)/cygwin and in that case this output is already valid (except the cert path though). I may fix this some time, not top priority.

**Comment by ehazlett** [comment]
See https://github.com/docker/machine/issues/733#issuecomment-77602371 (we currently recommend to install msysgit which has bash).

**Comment by sthulb** [comment]
I think in the future, we should support at least powershell

**Comment by ehazlett** [comment]
I agree -- but I defer to @ahmetalpbalkan as he has better domain knowledge than I do.

**Comment by StefanScherer** [comment]
I've played with `docker-machine.exe` on Windows last week. I additionally downloaded `docker.exe` CLI that is also pre-built on dockerproject.com.

Assuming [Chocolatey](https://chocolatey.org) we can install VirtualBox and curl with two little steps. I have made all these steps in a good old cmd.exe shell:

```cmd
λ cinst virtualbox
λ cinst curl
```

Then download docker-machine.exe and docker.exe

```cmd
λ curl -L -o docker-machine.exe https://github.com/docker/machine/releases/download/v0.1.0/docker-machine_windows-amd64.exe
λ curl -L -o docker.exe https://master.dockerproject.com/windows/amd64/docker.exe
```

Now create a VirtualBox dev machine:

```cmd
λ docker-machine create -d virtualbox dev
```

And here comes my favorite for `cmd.exe` shells: Translate the unix'ish environments printed by docker-machine and set it as environment variables in a plain Windows shell:

```cmd
λ for /f "tokens=2" %i in ('docker-machine env dev') do set %i
```

We are almost up and running. But the `docker.exe` (nightly build ?) already uses protocol version 1.18, but talking to a docker host we need version 1.17 for docker 1.5.0 hosts.

This could be done with a little trick:

```cmd
λ sed -ibak -b docker.exe -e 's/1.18/1.17/g'
```

And now you can do something like

```cmd
λ docker logs
λ docker images
```

Maybe this helps.

**Comment by ehazlett** [comment]
@StefanScherer thanks for the info!  i hope to have a "recommended" guide soon so you don't have to jump through all of those hoops!

**Comment by tknerr** [comment]
I'm hopefully waiting for docker 1.6.0 release to support this out of the box.

@StefanScherer awesome info! I got stuck with the different protocol versions, using `sed` to *fix* that is nice ;-) 

Is it usable like that or do you actually run into protocol incompatibilies quite early for the basic commands?

**Comment by ahmetalpbalkan** [comment]
@tknerr @StefanScherer about the overriding API version, you can +1 the proposal here: https://github.com/docker/docker/issues/11486

**Comment by StefanScherer** [comment]
@ahmetalpbalkan I'll have a look at your proposal.
I've tested the output of the current `docker-machine.exe` v0.2.0-rc3 and found some other issues:

```
C:\Users\vagrant>for /f "tokens=2" %i in ('docker-machine env dev') do set %i

C:\Users\vagrant>set DOCKER_TLS_VERIFY=1

C:\Users\vagrant>set DOCKER_CERT_PATH="C:\\Users\\vagrant\\.docker\\machine\\machines\\dev"

C:\Users\vagrant>set DOCKER_HOST=tcp://192.168.99.100:2376

C:\Users\vagrant>set Run
Environment variable Run not defined

C:\Users\vagrant>docker-machine env dev
export DOCKER_TLS_VERIFY=1
export DOCKER_CERT_PATH="C:\\Users\\vagrant\\.docker\\machine\\machines\\dev"
export DOCKER_HOST=tcp://192.168.99.100:2376

# Run this command to configure your shell: eval $(docker-machine env dev)


C:\Users\vagrant>docker info
FATA[0000] Couldn't read ca cert "C:\Users\vagrant\.docker\machine\machines\dev"\ca.pem:
open "C:\Users\vagrant\.docker\machine\machines\dev"\ca.pem: The filename, directory name,
or volume label syntax is incorrect.
```

1. The "bash" comment `# Run this command ...` has to be ignored on Windows.
2. The quotes in the envionment variable seems to make trouble.

After correcting the `DOCKER_CERT_PATH` environment the docker client can find the cert:

```
C:\Users\vagrant>set DOCKER_CERT_PATH=C:\Users\vagrant\.docker\machine\machines\dev

C:\Users\vagrant>docker info
FATA[0000] Error response from daemon: client and server don't have same version (client : 1.19, server: 1.17)
```

So IMHO the `docker-machine.exe` should be more polite on windows and make it easier to set the environments.

**Comment by ahmetalpbalkan** [comment]
@StefanScherer sorry I didn't get your point.

     set DOCKER_CERT_PATH="C:\\Users\\vagrant\\.docker\\machine\\machines\\dev"

this is not a valid usage for cmd.exe. you should not use backslashes or double quotes.

I recently fixed the same issue b2d-cli for windows: https://github.com/boot2docker/boot2docker-cli/pull/356 I'm hoping to port that here soon.

**Comment by StefanScherer** [comment]
@ahmetalpbalkan I've just retried my `for` loop from three weeks ago. Parsing the current output of `docker-machine.exe` results in the two errors above. So it gets more complicated for Windows users to use these envs.

I know the output of `docker-machine` is for unix shells at the moment. It would be fine if `docker-machine` outputs the correct values without the double quotes and without quotes.

**Comment by ahmetalpbalkan** [comment]
@StefanScherer umm, yes this issue is about that precisely :)

**Comment by StefanScherer** [comment]
@ahmetalpbalkan your PR in boot2docker-cli looks promising!

**Comment by ehazlett** [comment]
@StefanScherer this is a goal for 0.3.0 -- better windows experience.  we want to be able to support cmd.exe / powershell out of the box.

**Comment by dgageot** [comment]
Closing. this had been fixed
