### ISSUE TITLE
Be consistent with docker in DOCKER_TLS_VERIFY usage

### ISSUE THREAD

**Issue by ahmetalpbalkan** [docker/machine#734]
docker-machine env output shows 

    export DOCKER_TLS_VERIFY=yes

although that might be working, that's not the value generally used in docker docs in general (`1` is the one in the docker docs) and when I first saw it I was confused. In fact this usage appears only in machine-related repos/discussion according to google. 

We should probably speak the same language with docker/docker repo. Treat as low-priority UX feedback.

**Comment by shawnzhu** [comment]
According to the [docker CLI doc](https://docs.docker.com/reference/commandline/cli/):
> Setting the `DOCKER_TLS_VERIFY` environment variable to any value other than the empty string is equivalent to setting the `--tlsverify` flag.

Yes, `1` is what is showed in the code example of doc, but *any value other than the empty string* works as that in the doc :)

**Comment by ahmetalpbalkan** [comment]
@shawnzhu :smile:  we should make it 

     export DOCKER_TLS_VERIFY=damn straight yeah

**Comment by shawnzhu** [comment]
@ahmetalpbalkan I would prefer to clarify this in docker first because the semantic `any value other than the empty string` was introduced in docker/docker#8503

**Comment by shawnzhu** [comment]
This reminds me that it should use `--tlsverify` instead of `--tls` when performing command `docker-machine config`. see #736

**Comment by ahmetalpbalkan** [comment]
@shawnzhu that's just a comprehensive feature. my point was being consistent with usage examples across repos.

**Comment by ehazlett** [comment]
I think you both are correct ;)  I'll get a fix :)
