### ISSUE TITLE
support openstack-floatingip-pool without neutron

### ISSUE THREAD

**Issue by dudymas** [docker/machine#737]
## Summary
I expect docker-machine's openstack driver to support floating ip arguments even if I don't have a neutron service running.
This is likely a feature request... definitely a documentation bug ( documentation should specify that neutron is required for floating-ip at this point)... and maybe a bug too.

## Analysis
Given an openstack cluster with purely nova-based networking.

I expect that I can use docker-machine create to support floating ip pools.

Instead, the client fails with:
```
ERRO[0000] Error creating machine: No suitable endpoint could be found in the service catalog.
WARN[0000] You will want to check the provider to make sure the machine and associated resources were properly removed.
FATA[0000] Error creating machine
```

Omitting all floating ip arguments and flags allows the create command to continue merrily.

## Next steps

Per discussion below, gophercloud already supports this. A PR will be made to add a service check, and if neutron is not found, the openstack client will just use the nova api to nab an ip address.

**Comment by hairyhenderson** [comment]
+1

I've run into this before - except in my case we _are_ using neutron, but it was just blocked by default. I know my IT folks would rather lock down that port again.

**Comment by ggiamarchi** [comment]
Yes, the current implements only works with neutron. We should definitely support both neutron and nova-nework.

The reason why only neutron is supported is because when the driver had been developed Gophercloud did not provide implementation for nova-network floating IPs (maybe not a good reason). Now it does.

To deal with that in the driver we should check if neutron service is available in the keystone catalog and use it if it does. If not, we should fallback on nova.

**Comment by dudymas** [comment]
@ggiamarchi good to know I won't have to make a PR to Gophercloud too.

You think I should make the PR? or would is someone already planning to mess with the openstack driver? I don't mind being assigned to this... just don't expect it instantly... more like by the end of next week.

**Comment by ggiamarchi** [comment]
@dudymas Yes, of course, feel free to submit a PR. As far as i know, nobody is currently working on this one.

**Comment by ehazlett** [comment]
@dudymas that would be awesome!  like @ggiamarchi said, I don't know of anyone working on this so that would be great! thanks!

**Comment by hairyhenderson** [comment]
@dudymas - just curious - did you get anywhere with a PR for this yet?

**Comment by dudymas** [comment]
I've finally got it working. It was tricky to do... you'll see it in the first commit.

I'm heavily considering refactoring later
