### ISSUE TITLE
OSX binary corrupted

### ISSUE THREAD

**Issue by arun-gupta** [docker/machine#745]
Download instructions from https://docs.docker.com/machine/ for OSX_64 refer to https://github.com/docker/machine/releases/download/v0.1.0/docker-machine_darwin-amd64. Clicking on this link downloads the file, and that too without a .dmg extension.

Adding .dmg extension, and opening it, reports the download is corrupted.

**Comment by arun-gupta** [comment]
Never mind, false alarm! :)

Didn't realize its the script itself, not a .dmg.

**Comment by hairyhenderson** [comment]
It's not a .dmg, it's a binary. Just copy it somewhere and execute it in Terminal :)

**Comment by arun-gupta** [comment]
I had chmod +x it, so will file a separate bug for that.
