### ISSUE TITLE
Rename download scripts to be compatible with Compose

### ISSUE THREAD

**Issue by arun-gupta** [docker/machine#747]
I love the ability to download Compose as:

```
curl -L https://github.com/docker/compose/releases/download/1.1.0/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
```

It would be great if Machine downloads are named accordingly as well.

**Comment by ehazlett** [comment]
Thanks for reporting.  Duplicate of #494.

**Comment by ehazlett** [comment]
We will get this updated -- it bugs me too ;)
