### ISSUE TITLE
"ForbiddenError, Message: The server failed to authenticate the request" on Windows using Azure Driver

### ISSUE THREAD

**Issue by jangelfdez** [docker/machine#749]
Hi!

I was trying to create a virtual machine using Azure driver from my Windows machine but following the documentation steps is not fruitful.

First, using a Linux VM with Ubuntu installed I run the following commands to get my certificate:
```
$ openssl req -x509 -days 365 -newkey rsa:1024 -keyout AzureManagement.pem -out AzureManagement.pem
$ openssl pkcs12 -export -out AzureManagement.pfx -in AzureManagement.pem -name "Azure Management"
$ openssl x509 -inform pem -in AzureManagement.pem -outform der -out AzureManagement.cer
```
Second, using WinSCP I copy the files to my local Windows machine in the same directory running docker machine. I upload the .cer file to Azure and  I execute the following command
```
docker-machine_windows-amd64.exe create -d azure --azure-subscription-id="b124xxxx-xxxx-xxxx-xxxx-xxxx20b68a6" --azure-subscription-cert="AzureManagement.cer" UniqueNameHere
```
The result is the following error:
```
[34mINFO[0m[0000] Creating Azure machine...
[31mERRO[0m[0003] Error creating machine: Code: ForbiddenError, Message: The server failed to authenticate the request. Verify that the certificate is valid and is associated with this subscription.
[33mWARN[0m[0003] You will want to check the provider to make sure the machine and associated resources were properly removed.
[31mFATA[0m[0003] Error creating machine
```

Using the recommendation from Microsoft Azure documentation produces the same error message (https://msdn.microsoft.com/en-us/library/azure/gg551722.aspx)

**Comment by jangelfdez** [comment]
It was an ID10T Error Code, I will close the Issue ;)

**Comment by ehazlett** [comment]
Thanks for the update!  I have plenty of those :)

**Comment by jangelfdez** [comment]
Yes, however, I have not been able to deploy something from Windows to Azure. I get always an error creating the machine, something like this: https://github.com/docker/machine/issues/774

**Comment by cusspvz** [comment]
> It was an ID10T Error Code, I will close the Issue ;)

@jangelfdez seems that I'm getting the same error hahaha
Could you please specify what you did wrong?

**Comment by cusspvz** [comment]
Well, really an ID10T error!!

For those with the same problem, check that you are `azure-subscription-cert` pointing to `.pem` instead of `.cer` file.

**Comment by ehazlett** [comment]
@cusspvz ah haha thanks for the feedback!

**Comment by jangelfdez** [comment]
Same here ;)
