### ISSUE TITLE
virtualbox provider cannot start paused or saved VMs

### ISSUE THREAD

**Issue by slashk** [docker/machine#750]
The virtualbox driver cannot start VMs in the `paused` or `saved` states. The current logic only will start VMs in the `stopped` state. VMs will get into these states often on laptop due to power settings. 

The driver should be able to start or resume VMs in these states.

**Comment by rrarunan** [comment]
+1 @slashk .. I had the same issue today. Couldn't start a  VM which went into a `saved` state.
