### ISSUE TITLE
Custom args in boot2docker profile?

### ISSUE THREAD

**Issue by tyrbo** [docker/machine#755]
I'm needing to override the bridge IP address (--bip) as the default address clobbers VPN usage. Originally, with boot2docker, I built an ISO with the changed address included. It seems that docker-machine overwrites the /var/lib/boot2docker/profile file, killing my change along with it.

Adding it after the fact is an option, but is not ideal for my use case.

I didn't see anything in the docs about passing through any EXTRA_ARGS. Are there any options available to accomplish that, or are there any options that might be in the works for passing in our own args?

**Comment by LaynePeng** [comment]
I proposed this before, but machine is integrating Cloud-init, and will release in 0.2.0. So, just pay patient.

**Comment by LaynePeng** [comment]
refer to:  #701

**Comment by tyrbo** [comment]
Thanks, didn't catch that one. :)
