### ISSUE TITLE
OS image doesn't work for SoftLayer driver

### ISSUE THREAD

**Issue by wzymaster** [docker/machine#759]
I have tried the below command to create a VM(CentOS) on SoftLayer  but it still brings me UBUNTU :+1: 

./docker-machine create --driver softlayer \
     --softlayer-user xxxx \
     --softlayer-api-key yyyy \
      --softlayer-cpu 2 \
     --softlayer-memory 4096 \
     --softlayer-disk-size  0 \
     --softlayer-domain imdemocloud.com \
     --softlayer-hostname  DBServer2  \
     --softlayer-image CENTOS_LATEST_64 \
     --softlayer-region tor01  \
     DBServer2

Also,  this command is hanging there for ever and can't proceed.

**Comment by hairyhenderson** [comment]
I wonder if the "hanging there forever" thing is the same issue that's come up in #725...

**Comment by hairyhenderson** [comment]
And... yeah, currently the driver is [hard-coded to UBUNTU](https://github.com/docker/machine/blob/master/drivers/softlayer/driver.go#L205). I'm not sure if this is on purpose, though I do know that docker-machine currently only properly supports Ubuntu.

**Comment by hairyhenderson** [comment]
I'll have a PR ready hopefully tomorrow for this.

**Comment by ehazlett** [comment]
So this will not work as it is because we currently only support Ubuntu.  This is due to the Docker daemon config path and how we currently setup the TLS certs.  We are adding support for cloudinit which will help in customizing and using other base OSs.

**Comment by wzymaster** [comment]
Do you have ETA for cloudinit so that I can provision other than Ubuntu OS on IBM SoftLayer ?
