### ISSUE TITLE
Use $(docker-machine env) in getting started guide

### ISSUE THREAD

**Issue by bfirsh** [docker/machine#762]
It's confusing that the getting started guide switches between `$(docker-machine config)` and `$(docker-machine env)`. We should show you just one way to do it in the getting started guide. My vote is for `$(docker-machine env)` because that's how you're more likely going to do it when working normally.

**Comment by nathanleclaire** [comment]
+1 I think it's just that no one updated the docs since `config` was in vogue

**Comment by ehazlett** [comment]
SGTM
