### ISSUE TITLE
SoftLayer driver should support specifying VLAN for public and private interfaces

### ISSUE THREAD

**Issue by hairyhenderson** [docker/machine#766]
This is important for the use case where there are isolated VLANs for pre-production and production environments in a given SoftLayer account. If a VLAN isn't specified, the created host can end up in the wrong environment.

I'm suggesting some new flags:
- `--softlayer-public-vlan-id` - the ID of the VLAN for the public interface
  - would refuse to run if `--softlayer-private-net-only` is set
- `--softlayer-private-vlan-id` - the ID of the VLAN for the private interface

And maybe some additional more user-friendly flags (though these would require additional API calls to resolve):
- `--softlayer-public-vlan-name` - the name of the VLAN for the public interface
- `--softlayer-private-vlan-name` - the name of the VLAN for the private interface

**Comment by hairyhenderson** [comment]
Just for posterity - I implemented the `id` flags, but not the `name` ones. It's probably too much trouble for too little benefit.

**Comment by ehazlett** [comment]
@hairyhenderson :+1: -- if there is need we can implement in the future.  Also, fwiw we use the VPC ID for EC2 as well.
