### ISSUE TITLE
[OS X] Docker not able to pick the right path to ca cert

### ISSUE THREAD

**Issue by smace** [docker/machine#781]
At the root of /Volumes I have 2 directories belonging to the 2 hard drives in my macbook pro, it seems that docker and/or docker-machine isn't able to handle directories with white-spaces in their names: 

![capture d ecran 2015-03-14 a 15 17 33](https://cloud.githubusercontent.com/assets/1382456/6651962/5f7184ce-ca5d-11e4-863f-63facece4513.png)

**Comment by hairyhenderson** [comment]
Does `$(docker-machine env dev)` work?

Looks like the cert path needs to be surrounded by double-quotes

**Comment by smace** [comment]
How can I check if $(docker-machine env dev) works properly?

**Comment by hairyhenderson** [comment]
@smace - sorry - I meant to run the command in the terminal, then try running docker commands. I checked it myself though, and it doesn't work.

The PR I issued fixes the problem, though.

Until the PR is merged and you have a build with the fix, you can work around it by running `docker-machine env dev`, and copy-pasting the `export` commands, except for `DOCKER_CERT_PATH`, which you should change to something like:

```
export DOCKER_CERT_PATH="/Volumes/Macintosh HD/swann/.docker/machine/machines/dev"
```

Then, you can run `docker ps` and it'll pick up the environment variables for its configuration.

**Comment by smace** [comment]
Thank you very much this quick fix!

**Comment by hairyhenderson** [comment]
@smace - just FYI, this _was_ fixed, but @nathanleclaire and @ehazlett found a bug in my PR, so the fix had to be reverted... I'm working on a better fix now ;)

**Comment by hairyhenderson** [comment]
Ok, it _actually_ was fixed, and the revert is being reverted in #814.

@smace you will need to do `eval "$(docker-machine env dev)"` to set the variables in future (though the `$(docker-machine config dev)` usage will also work).

**Comment by hairyhenderson** [comment]
@ehazlett can you close this again? :)

**Comment by ehazlett** [comment]
@hairyhenderson yes.  thanks for the clarification!
