### ISSUE TITLE
docker-machine can be created without a name

### ISSUE THREAD

**Issue by blijblijblij** [docker/machine#785]
After running a incomplete docker-machine create, it did register something via virtualbox / localhost, but without a name. This should not happen.

Check the attached image

**Comment by blijblijblij** [comment]
![screenshot from 2015-03-15 10 02 03](https://cloud.githubusercontent.com/assets/1648248/6655315/60b86fa8-cafa-11e4-95ee-717bf5259bd3.png)

**Comment by hairyhenderson** [comment]
@blijblijblij - what command did you run? was it something like `docker machine create -d virtualbox  `?

Based on the spacing in the error message, it seems that the issue isn't so much that a machine was created _without_ a name, as a machine was created with a name consisting of a single space character.

**Comment by crunchywelch** [comment]
I just issued this patch https://github.com/docker/machine/pull/807 which validates hostname prior to storing the host entry, which would prevent this (and storing other hosts with invalid hostnames). Without seeing the create command though, I can't be sure it would prevent this exact state however.

**Comment by blijblijblij** [comment]
Grepped my bash_history, I pasted a multi line docker-machine create statement which started with:

docker-machine create --driver virtualbox \

which in the current version results in a FATA[0000] You must specify a machine name, and the reported issue cannot be recreated. Thx for that.
