### ISSUE TITLE
Parallels option

### ISSUE THREAD

**Issue by josh-devops-center** [docker/machine#786]
It would be nice to set up docker machine using a Parallels provider in addition to the virtualbox provider.

**Comment by posita** [comment]
See PR #939.

**Comment by dgageot** [comment]
@docker/machine-maintainers With the introduction of driver plugins, we should close this ticket, shouldn't we?

**Comment by posita** [comment]
I'm not a stakeholder (just an interested party), but I think there's enough history and interaction with this particular case to warrant keeping this open until [Parallels/docker-machine-parallels](/Parallels/docker-machine-parallels) is production ready?

**Comment by nathanleclaire** [comment]
Given the introduction of plugins and existence of that repo, I think it's pretty safe to close the ticket.  Thanks all
