### ISSUE TITLE
Fusion boot2docker VM aren't headless.

### ISSUE THREAD

**Issue by loic** [docker/machine#788]
From my understanding `docker-machine create` is supposed to create a headless VM, but somehow I can see the running instance when I open the Fusion application (7.1.1).

Quitting the Fusion GUI suspends the boot2docker VM which is obviously not the expected behaviour.

**Comment by sthulb** [comment]
We can't actually fix this, it's a problem with VMware Fusion. The problem exists with the Library application taking over responsibility of the VMs. 

This is the sam behaviour as Vagrant.

**Comment by ehazlett** [comment]
ping @frapposelli

**Comment by frapposelli** [comment]
There is no workaround/fix at the moment, the only way to keep the VM headless is to avoid opening the Fusion GUI, I'm raising this with the Fusion team internally as this doesn't happen with VMware Workstation on Windows/Linux.

**Comment by ehazlett** [comment]
@frapposelli thanks!

**Comment by yyyc514** [comment]
Any news on this?  Just tried with VMWare Fusion 8 and this behavior is super annoying.

**Comment by yyyc514** [comment]
vmrun:

```
/Applications/VMware\ Fusion.app/Contents/Library/vmrun start ~/.docker/machine/machines/warm/warm.vmx nogui 
```

I was just about to suggest looking into this, but it only seems to work short-term... so perhaps that's what docker-machine is using already... you can fire up a machine WHILE VmWare is running and it's hidden but if you re-launch VmWare then it becomes visible and the GUI is prone to mess with it.

**Comment by frapposelli** [comment]
@yyyc514 the `nogui` option is what the driver uses to spin up the VM, but if you launch the Fusion app you'll see the VM console regardless, there is currently no workaround for this on the `docker-machine` side.

**Comment by yyyc514** [comment]
Is there any great place to file an issue with VMWare on the subject?

**Comment by dgageot** [comment]
Closing. The driver uses `nogui` option

**Comment by yyyc514** [comment]
I don't think nogui actually fully addresses this issue... perhaps more useful to say this was closed because it's unsolvable.  Either that or leave this open in the hope of a better solution.  My 0.02.

**Comment by frapposelli** [comment]
@yyyc514 `nogui` is the `vmrun` flag that disable automatic opening of the console upon VM start, if you open the Fusion App that will automatically connect to all the `vmware-vmx` processes that are currently running, showing console for VMs that were started with the `nogui` option.

This is the default behavior of Fusion and currently the `docker-machine` driver can do nothing to prevent you from opening the UI and stopping the console to show up. If you think this Fusion behavior should change, please raise a feature request (https://www.vmware.com/company/contact/contactus.html?department=prod_request) or a service request (https://my.vmware.com/group/vmware/get-help).
