### ISSUE TITLE
Offline version of Docker Machine

### ISSUE THREAD

**Issue by arun-gupta** [docker/machine#791]
Would like the capability to run Docker Machine in an offline mode. This should allow to download boot2docker ISO from a local network, and perform all settings without relying upon Internet.

This setup would be very relevant for lab setups in a conference setting.

**Comment by hairyhenderson** [comment]
@arun-gupta - wouldn't the `--virtualbox-boot2docker-url` argument support this? Or alternately, the `VIRTUALBOX_BOOT2DOCKER_URL` environment variable?

Or is there something else that relies on Internet access?

**Comment by arun-gupta** [comment]
Seems like file scheme is not supported:

```
~> docker-machine create --driver=virtualbox --virtualbox-boot2docker-url=file:///Users/arungupta/Downloads/boot2docker.iso mydocker 
INFO[0000] Creating CA: /Users/arungupta/.docker/machine/certs/ca.pem 
INFO[0000] Creating client certificate: /Users/arungupta/.docker/machine/certs/cert.pem 
INFO[0000] Downloading boot2docker.iso from file:///Users/arungupta/Downloads/boot2docker.iso... 
ERRO[0000] Error creating machine: Get file:///Users/arungupta/Downloads/boot2docker.iso: unsupported protocol scheme "file" 
WARN[0000] You will want to check the provider to make sure the machine and associated resources were properly removed. 
FATA[0000] Error creating machine 
```

I switched off Internet access before trying this command.

**Comment by hairyhenderson** [comment]
Ah - I misunderstood. when you said "local network" I assumed you were talking about HTTP to a local server.

I think this is related to #539

**Comment by arun-gupta** [comment]
Yep, thanks, will close this one then!
