### ISSUE TITLE
Make boot2docker compatible with Machine

### ISSUE THREAD

**Issue by bfirsh** [docker/machine#80]
I'm using this issue as a way of tracking our boot2docker dependencies for a Machine 1.0 release.

 - [Docker with identity auth](https://github.com/docker/docker/pull/8265) should be included in boot2docker
 - [This patch](https://github.com/boot2docker/boot2docker/pull/659) is required for VMware Fusion

**Comment by ehazlett** [comment]
Closing as we no longer use identity and have separate issues for the b2d compatibility for vmw.
