### ISSUE TITLE
using drivers to manually pull data from api

### ISSUE THREAD

**Issue by bytepoet** [docker/machine#801]
seeing that docker-machine uses the api drivers to get states of hosts, (running, stopped,  etc)  is there a way to use the binary to pull other specific information about the servers/account? 

example.   I can see how many hosts I've created on my cloud account using docker-machine but I can't see all servers created.  any simple way to do this?

**Comment by hairyhenderson** [comment]
@bytepoet seems to me this is outside the scope of what docker-machine is trying to be... Most providers have their own command line clients that you could use for this. I think it would be a bad idea for docker-machine to try to be a general-purpose client for all cloud providers. There are a number of other projects for that already.

**Comment by bytepoet** [comment]
yeah, jumped back to libcloud for the rest.  (for those of you who might have been heading down the same path as me.

**Comment by nathanleclaire** [comment]
Yep, out of scope.  Thanks!
