### ISSUE TITLE
VirtualBox VM in the "Saved" State Cannot be Started

### ISSUE THREAD

**Issue by razic** [docker/machine#809]
So somehow my VM was in the "Saved" state. Maybe my computer went to sleep and VirtualBox put it to sleep? In any case, the `docker-machine stop|start|restart <name>` commands would just hang. I managed to get the `docker-machine` CLI working again by manually opening the VirtualBox GUI and "Restoring" the "Saved" state of the VM, and then stopping it.

**Comment by yamii** [comment]
I have a similar issue. My work around for this is:
- Opened my Virtual Box Manager
- I can see the list of my Machines in diff state
- Started my 'SAVED' machine (right clicking on the machine and click save)
Maybe this will help in your end.

**Comment by yamii** [comment]
I experienced the same issue. I'm also using virtual box as my driver. Same workaround using Virtual Box and started the machine in `Saved` state.

**Comment by UserTaken** [comment]
This is a known issue and a fix has already been created. See [#750](https://github.com/docker/machine/issues/750)

**Comment by nathanleclaire** [comment]
This should be fixed by https://github.com/docker/machine/pull/751 cc @ehazlett to close

**Comment by yamii** [comment]
nice!

**Comment by holic** [comment]
Just ran into this issue. I'm on OSX 10.10.3 using the latest Docker Engine stable release and the latest Docker Machine (installed both yesterday).

I created a Virtualbox VM, used it a bit yesterday, left it running and closed my MacBook.

Today when I opened it up, Docker Machine reported the VM in "Saved" state:

```
$ docker-machine ls
NAME   ACTIVE   DRIVER       STATE   URL   SWARM
dev             virtualbox   Saved
```

I tried to start, stop, restart, and kill the VM, to no avail:

```
$ docker-machine start dev
exit status 1

$ docker-machine ls
NAME   ACTIVE   DRIVER       STATE   URL   SWARM
dev             virtualbox   Saved

$ docker-machine stop dev
exit status 1

$ docker-machine ls
NAME   ACTIVE   DRIVER       STATE   URL   SWARM
dev             virtualbox   Saved

$ docker-machine restart dev
exit status 1

$ docker-machine kill dev
exit status 1
```

I was able to `rm` the VM and re-create it. If I run into this issue again, is there anything I can do to help you guys to reproduce this issue?

**Comment by nathanleclaire** [comment]
Argh, this should work.  I'll try and see if I can reproduce and/or fix.

**Comment by Elido** [comment]
same issue here. Just happened today.

**Comment by nathanleclaire** [comment]
I can duplicate this and want to get a fix in ASAP.

**Comment by nathanleclaire** [comment]
https://github.com/docker/machine/pull/1487
