### ISSUE TITLE
Compile Error on Red Hat Server 7.0

### ISSUE THREAD

**Issue by TrumanLing** [docker/machine#812]
Environmental info:
```console
[root@localhost ~]# cat /etc/redhat-release
Red Hat Enterprise Linux Server release 7.0 (Maipo)
```
Compile message:
```console
[root@localhost machine]# script/build 
Sending build context to Docker daemon 6.501 MB
Sending build context to Docker daemon 
Step 0 : FROM golang:1.3-cross
 ---> c9b4f7f2a976
Step 1 : ENV http_proxy http://s00318865:*uhb9ijn@proxyus-rd.huawei.com:8080
 ---> Using cache
 ---> e077be9980cd
Step 2 : ENV https_proxy https://s00318865:*uhb9ijn@proxyus-rd.huawei.com:8080
 ---> Using cache
 ---> c82427052e70
Step 3 : ENV no_proxy rnd-isourceb.huawei.com,/var/run/docker.sock,localhost,docker01.thstack.com
 ---> Using cache
 ---> 8bc2a0c75c97
Step 4 : RUN apt-get update && apt-get install -y --no-install-recommends openssh-client
 ---> Using cache
 ---> 6dd73a624882
Step 5 : RUN go get github.com/mitchellh/gox
 ---> Using cache
 ---> 8341b65f64cb
Step 6 : RUN go get github.com/aktau/github-release
 ---> Using cache
 ---> aed11abed523
Step 7 : ENV GIT_SSL_NO_VERIFY 1
 ---> Using cache
 ---> 3455ae41e461
Step 8 : RUN go get github.com/tools/godep
 ---> Using cache
 ---> f97fb52d21f0
Step 9 : RUN go get code.google.com/p/go.tools/cmd/cover
 ---> Using cache
 ---> 6f1f38bf410b
Step 10 : ENV GOPATH /go/src/github.com/docker/machine/Godeps/_workspace:/go
 ---> Using cache
 ---> 1aab22a50dd3
Step 11 : ENV MACHINE_BINARY /go/src/github.com/docker/machine/docker-machine
 ---> Using cache
 ---> 296bbe828d8b
Step 12 : ENV USER root
 ---> Using cache
 ---> 62d298819dff
Step 13 : WORKDIR /go/src/github.com/docker/machine
 ---> Using cache
 ---> c1038eef89d0
Step 14 : ADD . /go/src/github.com/docker/machine
 ---> Using cache
 ---> 7208dcff09c8
Successfully built 7208dcff09c8
Error reading packages: exit status 1
Stderr: can't load package: package github.com/docker/machine: open /go/src/github.com/docker/machine: permission denied
```

**Comment by clnperez** [comment]
I'm hitting this on Fedora 21 as well. I see in PR #813 that @ehazlett suggested using a cap. I tried DAC_READ_SEARCH, then DAC_OVERRIDE, then and FOWNER along with DAC_READ_SEARCH, but no love. I also tried using 'all,' which didn't work either. That alone leads me to wonder if caps is what we need. 

It's definitely an selinux issue. setenforce 0 will get it to work, but that's not the solution for sure. 

I did some poking around and it looks like I'm getting noatsecure, signh, and rlimitinh denials. Maybe a policy update is already in the works for these?

**Comment by clnperez** [comment]
I'm seeing this too, on Fedora 21 (which is just upstream RHEL). I saw in PR #813 that @ehazlett mentioned adding a CAP for RH.

**Comment by clnperez** [comment]
I google'd some more, and found a great video by Dan Walsh at last year's Docker Con, and at 36:11, appeared the answer: selinux doesn't work with volume mounts. The workaround is to relabel your local directory: 
$ sudo chcon -Rt svirt_sandbox_file_t ../machine

That worked.

Then Dan mentioned they had a PR to relabel FS, which, I think is  the noatsecure denial I saw. So, IIUC, we (selinux users) need a policy to allow Docker to do those things it was trying?

**Comment by nathanleclaire** [comment]
Yep, SELinux issues.  There's not much we can do here because it is largely dependent on how the user's system is set up, but thanks for filing- it will probably help others who run into the issue in the future.

**Comment by nathanleclaire** [comment]
Hey @clnperez , any chance I could persuade you to make a PR for the CONTRIBUTING.md file detailing the steps that you took to set SELinux correctly in a general way?

**Comment by clnperez** [comment]
Sure, @nathanleclaire. IIUC, it might not be an issue with Docker later than 1.7 (see https://github.com/docker/docker/pull/5910 and https://github.com/docker/docker/pull/12572). However, after a super quick scan of 12527 -- a change to a Dockerfile somewhere in machine might need to add [z,Z] to use that new feature. I can look into it this week and see what we need to do for this.

**Comment by clnperez** [comment]
I just put the original selinux label  (user_home_t) back and the build failed with Docker 1.6. It worked with 1.7, though. I can still add a note in CONTRIBUTING.md and state that the workaround is only needed for versions < 1.7. WDYT, @nathanleclaire?

**Comment by clnperez** [comment]
I'm running into a flavor of this now:
christy@christy-toshiba machine> make build
script/build
Sending build context to Docker daemon 24.67 MB
Sending build context to Docker daemon 
Step 0 : FROM golang:1.4.2-cross
 ---> bbc500088baa
Step 1 : RUN go get github.com/mitchellh/gox
 ---> Running in b1fc79e9b7d6
package github.com/mitchellh/gox: mkdir /go/src/github.com: permission denied
The command '/bin/sh -c go get github.com/mitchellh/gox' returned a non-zero code: 1
Makefile:17: recipe for

turning off selinunx (setenforce 0) lets it continue -- but that's bad. The relabel workaround I had earlier doesn't help, so I'll look into it and submit something for the Readme. I see it's also mentioned in Issue #940.

**Comment by nathanleclaire** [comment]
>  I'll look into it and submit something for the Readme

Nice, thanks.  Probably should go in : https://github.com/docker/machine/blob/master/CONTRIBUTING.md
