### ISSUE TITLE
quoted DOCKER_CERT_PATH breaks docker client commands

### ISSUE THREAD

**Issue by greentg** [docker/machine#817]
Run '$(docker-machine env <machine>)' against existing machine, followed by any command that opens a connection to the engine (e.g. docker ps) and you'll get the following error:

FATA[0000] Couldn't read ca cert "/Users/username/.docker/machine/machines/docker01"/ca.pem: open "/Users/username/.docker/machine/machines/docker01"/ca.pem: no such file or directory

This can be fixed if the quotes are placed after the cert filename, or if quotes are removed.  The former would be the better solution, though, so pathnames with spaces are handled properly.

Commit 3dfc436e0717c94c647ef32f498a312e8aeaf4b9 seems to be the culprit.

**Comment by hairyhenderson** [comment]
Use `eval "$(docker-machine env docker01)"` instead. We're no longer recommending using `$(docker-machine env foo)` on its own (see #795)

**Comment by greentg** [comment]
Ok thanks @hairyhenderson .  This needs to be reflected in the docs also I believe.   Do you know if docs.docker.com is also under version control here?

**Comment by hairyhenderson** [comment]
@greentg - I believe they were already updated in git, and I think docs.docker.com will reflect this when docker-machine 0.2.0 is released. Am I right, @ehazlett?

**Comment by ehazlett** [comment]
@hairyhenderson correct -- once we do the release it will update the official docs.  You can also checkout master at http://docs.master.dockerproject.com/machine/#config

Thanks!

**Comment by ehazlett** [comment]
@hairyhenderson correct -- once we do the release it will update the official docs.  You can also checkout master at http://docs.master.dockerproject.com/machine/#config

Thanks!
