### ISSUE TITLE
Question: I have installed docker, what will happen if I use docker-machine to create my instances

### ISSUE THREAD

**Issue by joeyhipolito** [docker/machine#818]
I have been fiddling with docker in my ubuntu machine for quite some time now and it works great, however, docker-machine came, will this change the way I create my containers in my own local machine?

Running `docker-machine create --driver virtualbox dev`

> This will download a lightweight Linux distribution (boot2docker) with the Docker daemon installed, and will create and start a VirtualBox VM with Docker running.

That means it'll be like me running boot2docker on windows right?

**Comment by hairyhenderson** [comment]
Yep. docker-machine with the virtualbox driver is very similar to running boot2docker.

**Comment by joeyhipolito** [comment]
Alright got that, so I can have both docker in my laptop and docker-machine so I can launch droplets / vps / ec2 instances with docker instance running? Am I right?

**Comment by hairyhenderson** [comment]
Yep, absolutely

**Comment by joeyhipolito** [comment]
Okay then, I think that confirmed my understanding.
