### ISSUE TITLE
Virtualbox CPU Support

### ISSUE THREAD

**Issue by stephenlawrence** [docker/machine#819]
Add an option to docker-machine Virtualbox integration to allow for the number of cpu's to be adjusted during create.

**Comment by hairyhenderson** [comment]
Currently the behaviour is to use the same number of CPUs as the host has. Any reason you would want or need to adjust this?

**Comment by greentg** [comment]
It's already an option for some of the other providers, so there should at least be some kind of consistency.  Thoughts?

**Comment by dnvriend** [comment]
Reason: on my machine, MacBook Pro i7 end 2011 and Akka/play packaged with Docker, performance is best using 1 cpu per real core, and not the virtual cores (HyperThreading). I must manually change this setting. Not a real big issue, but it would be nice.

**Comment by hairyhenderson** [comment]
@dnvriend - ah. Makes sense.

**Comment by pbiggar** [comment]
Trying to do this during the open-source-a-thon

**Comment by hairyhenderson** [comment]
I think this was a duplicate of #822
