### ISSUE TITLE
driver-libvirt: Verify at least one NIC has local DHCP for discovery

### ISSUE THREAD

**Issue by crosbymichael** [docker/machine#835]
**Problem**

driver-libvirt: Verify at least one NIC has local DHCP for discovery

**Solution**

The (soon to be merged) libvirt driver should detect if the user specified
 network is managed by libvirt and has DHCP running (allowing us to look up
 the IP of the resulting VM) or is an externally routed and managed network.
  If no libvirt/DHCP network is specified, we should add an additional NIC
 to the VM using private networking so we have a communication channel to
 the VM after it starts up.

**Comment by nathanleclaire** [comment]
It's not clear if we will merge `libvirt` support in, so this jumps the gun a little.
