### ISSUE TITLE
Validate instance creation for openstack using driver flags

### ISSUE THREAD

**Issue by crosbymichael** [docker/machine#840]
**Problem**

Test the flags for Openstack

**Solution**

Validate instance creation using various flags for Openstack

There are several flags available for each driver.  Test each flag to ensure it does the intended behavior.

For example,

`docker-machine create -d openstack --openstack-flavor-id fl-12345 test-os`

This should create a machine with a different flavor ID.

**Comment by jjacobso** [comment]
#dibs

**Comment by slashk** [comment]
#dibs
