### ISSUE TITLE
Integration tests are not run on Windows based systems

### ISSUE THREAD

**Issue by crosbymichael** [docker/machine#848]
**Problem**

Enable running integration tests on Windows

**Solution**

The integration tests currently only work on Linux/OS X.  We should support running tests on Windows to integrate with CI.

We currently use [bats](https://github.com/sstephenson/bats) for integration testing.  It would be great to get this to run on Windows.

On Linux/OS X, the way to run the integration tests are as follows:

- Setup the environment variables for the driver you want to test
- Run `bats test/integration/driver-<name>.bats` to start the tests

It will show a series of tests and outputs.  This would be great to re-use on Windows.

**Comment by nathanleclaire** [comment]
This should work if using msysgit or anywhere that `bash` is available, although I'm not sure if `bats` is directly supported on windows so I'm not sure if it's a lost cause or not.
