### ISSUE TITLE
docker-machine env seems to be broken

### ISSUE THREAD

**Issue by rschmukler** [docker/machine#851]
Running the `docker-machine env` gives the following:

```
export DOCKER_TLS_VERIFY=1
export DOCKER_CERT_PATH="/Users/ryan/.docker/machine/machines/om-6"
export DOCKER_HOST=x.x.x.x
```

If this is copy pasted, bash works fine. However,  running `$(docker-machine env)` results in the following when running any `docker` command.

```
FATA[0000] Couldn't read ca cert "/Users/ryan/.docker/machine/machines/om-6"/ca.pem: open
"/Users/ryan/.docker/machine/machines/om-6"/ca.pem: no such file or directory
```

The quotes seem to be preserved literally.

**Comment by hairyhenderson** [comment]
This is my fault ;)

This isn't a bug, however it is a change in behaviour. You need to do `eval "$(docker-machine env)"` now. See #795 for the reasoning, and also #781 for the original bug that drove the PR (#783).

**Comment by rschmukler** [comment]
@hairyhenderson I figured there was good reason behind it. Thanks for the clarification! Feel free to close this (or keep it open if you expect others might need further clarification)

**Comment by hairyhenderson** [comment]
@rschmukler - I can't close it (I'm not an owner) - can you close it? This is covered in the changelog, and it's been explained a few times in IRC, so hopefully not too many more issues get logged about it :)

**Comment by rschmukler** [comment]
Oh, well then very sorry I didn't see it haha. Closing!
