### ISSUE TITLE
For windows, add dependency to ssh-keygen

### ISSUE THREAD

**Issue by MaitreDede** [docker/machine#852]
Hi,

In the documentation https://docs.docker.com/machine/#vmware-vsphere there is an info that should be mentionned : requirement to ssh-keygen tool.
I have tried to run docker-machine on local windows :
- downloaded docker-machine for windows amd64
- downloaded govc windows amd64
- tried to create a VM, error about missing ssh-keygen.

My workaround : ssh-keygen is included with msysgit (git for windows).

**Comment by nathanleclaire** [comment]
This is a good point.  I'd been using Cygwin for my Windows testing so I hadn't noticed, but we need to define a supported Windows "stack" ASAP.

**Comment by StefanScherer** [comment]
I first thought using Windows Vagrant boxes, but even the packer-windows boxes normally have OpenSSH installed and therefore some SSH tools.

I remember there are some Modern.IE Vagrant boxes here: http://blogs.msdn.com/b/ie/archive/2014/09/16/expanding-offers-and-vm-delivery-choices-on-modern-ie.aspx

```bash
vagrant box add win81-ie11 http://aka.ms/vagrant-win81-ie11
```

But Vagrant can't provision these boxes as WinRM is not configured out-of-the-box.

**Comment by nathanleclaire** [comment]
msysgit is currently the recommended way to run `docker-machine`, and I think we use the native SSH key generation in every case so this should be taken care of.  Thanks!
