### ISSUE TITLE
Replace AWS driver

### ISSUE THREAD

**Issue by sthulb** [docker/machine#858]
With the release of an AWS (alpha) SDK for Go, https://github.com/awslabs/aws-go

Using the official SDK has advantages over our current implementation since we wouldn't have to maintain lower level code.

**Comment by awsmsrc** [comment]
#dibs

**Comment by teng-lin** [comment]
I have initial successful to replace the driver with aws-sdk-go. Not sure if the API is stable or not though.
@ehazlett, do you plan to do some kind of integration testing for various driver?

**Comment by ehazlett** [comment]
@teng-lin we have (a few) unit tests for the existing AWS driver and integration tests with bats (check the test/integration dir).

/cc @sthulb as he has worked on this in the past

**Comment by rhunter** [comment]
Do @teng-lin 's changes make use of the AWS SDK credential handling (reading `~/.aws/credentials`, profiles, etc)? If they do, then they'll address #1366 as well :-)

**Comment by sthulb** [comment]
AWS claimed that the go-sdk is usable now. They had a blog post about a month ago?

**Comment by nathanleclaire** [comment]
I'm +1 on this long-term

**Comment by teng-lin** [comment]
Will take a close look to see if the API is stable enough to pursue this.

**Comment by euank** [comment]
The Go AWS SDK is fairly stable at this point.

Since it looked like this issue hadn't had any activity in a while, I took a shot at this in #1850. Any feedback or comments there would be appreciated.
