### ISSUE TITLE
Docker machine create on Softlayer stuck in "Configuring host OS"

### ISSUE THREAD

**Issue by gauthamacharya** [docker/machine#863]
docker-machine create slm0 --driver=softlayer --softlayer-user=sl_user_id --softlayer-api-key=sl_api_key --softlayer-cpu=1 --softlayer-disk-size=0 --softlayer-domain=sl_domain --softlayer-hostname=m0 --softlayer-image=UBUNTU_LATEST --softlayer-hourly-billing --softlayer-memory=1024 --softlayer-region=dal09
←[34mINFO←[0m[0000] Creating SSH key...
←[34mINFO←[0m[0004] Getting Host IP
←[34mINFO←[0m[0022] Waiting for host to become available
←[34mINFO←[0m[0208] Configuring host OS

the commands waits here indefinitely. The softlayer instance gets provisioned with the settings, however there is docker provisioning does not happen. I have checked both running this from local and from another softlayer instance both yielding similar results.

**Comment by hairyhenderson** [comment]
@gauthamacharya - is this with a recently-compiled docker-machine, or is with the 0.1.0 release? There was a similar issue (#725) fixed a little while ago.

**Comment by rhodgin** [comment]
@hairyhenderson - I'm able to consistently reproduce this issue with the 0.1.0 release but it doesn't happen after compiling 0.2.0. 0.2.0 doesn't include the "Configuring host OS step" in its output but displays "Waiting for host setup transactions to complete". This step completes quickly and finishes creation as expected.

**Comment by gauthamacharya** [comment]
Confirming that the issue is closed with 0.2.0 builds ! The issues was consistent with 0.1.0 version

**Comment by wzymaster** [comment]
where to download 0.2.0 version ? or I have to build it myself ?

**Comment by hairyhenderson** [comment]
@wzymaster - 0.2.0 isn't quite out yet, but you can get a release candidate here: https://github.com/docker/machine/releases

**Comment by wzymaster** [comment]
thx very much and I will give it a try.

**Comment by wzymaster** [comment]
Sorry, I just download the pre-release of 0.2.0 and run docker-machine like below :  
./docker-machine create --driver softlayer      --softlayer-user leow      --softlayer-api-key 0a7e316ab1004f761672ab1a890f906cb3a90ba978c5c217c2ca500fd42b820d       --softlayer-cpu 4      --softlayer-memory 8192      --softlayer-disk-size  0      --softlayer-domain imdemocloud.com      --softlayer-hostname "leo-demo1"       --softlayer-image CENTOS_LATEST_64      --softlayer-region hkg02      leo-demo1
INFO[0000] Creating SSH key...
INFO[0007] Getting Host IP
INFO[0032] Waiting for host to become available
INFO[0154] Waiting for host setup transactions to complete


Unfortunatley, it still get stuck at 'Waiting for host setup transaction to complete" step .  

However, I do see this VM machine provisioned on SoftLayer and I can log in.  It looks like a clean machine without docker. 

Do I run something wrong here ? @hairyhenderson 

The below is the build of docker-machine which I am using :   

Zhongs-MacBook-Pro:Leo_Demo wzymaster$ ./docker-machine -v
docker-machine version 0.2.0 (45f08d9)

**Comment by wzymaster** [comment]
btw, I am running docker-machine on the macBook with OS X v10.9.5

**Comment by hairyhenderson** [comment]
@wzymaster - can you run docker-machine with debug enabled?

Something like:

```
./docker-machine --debug create --driver softlayer --softlayer-user leow --softlayer-api-key xxx --softlayer-cpu 4 --softlayer-memory 8192 --softlayer-disk-size 0 --softlayer-domain imdemocloud.com --softlayer-hostname "leo-demo1" --softlayer-image CENTOS_LATEST_64 --softlayer-region hkg02 leo-demo1
```

**Comment by hairyhenderson** [comment]
@wzymaster also, you're probably going to want to change your API key, because you pasted it in your earlier comment :)

**Comment by hairyhenderson** [comment]
@wzymaster also - would you mind logging a new issue for what you're seeing? This is different than what @gauthamacharya originally logged, and this issue is closed...

**Comment by wzymaster** [comment]
Thanks for the reminder of my API key and just updated.
