### ISSUE TITLE
exit status 255 or hang on Google CE

### ISSUE THREAD

**Issue by robwithhair** [docker/machine#865]
When running following command...
```
docker-machine create --driver google --google-project app-inst-ae --google-zone europe-west1-c --google-username rob@appinstitute.co.uk staging-test4
```
On version 0.1.0 I get the following error
```
INFO[0009] Saving token in /Users/robwithhair/.docker/machine/machines/staging-test2/gce_token 
INFO[0009] Creating host...                             
INFO[0010] Generating SSH Key                           
INFO[0010] Creating instance.                           
INFO[0011] Waiting for Instance...                      
INFO[0027] Waiting for SSH...                           
INFO[0075] Uploading SSH Key                            
INFO[0076] Waiting for SSH Key                          
INFO[0079] Configuring Machine...                       
ERRO[0079] Error creating machine: exit status 255      
WARN[0079] You will want to check the provider to make sure the machine and associated resources were properly removed. 
FATA[0079] Error creating machine 
```
On version v0.2.0-rc1 it just hangs waiting for SSH key like the following
```
INFO[0009] Saving token in /Users/robwithhair/.docker/machine/machines/staging-test4/gce_token 
INFO[0009] Creating host...                             
INFO[0010] Generating SSH Key                           
INFO[0011] Creating instance.                           
INFO[0012] Waiting for Instance...                      
INFO[0029] Waiting for SSH...                           
INFO[0076] Uploading SSH Key                            
INFO[0076] Waiting for SSH Key
```
When looking on GCE it looks like the key has been created as expected though.  I'm not sure where to go from here so any info or help of how to debug further would be much appreciated.

**Comment by robwithhair** [comment]
Doesn't look like it can communicate with the instance for some reason

**Comment by robwithhair** [comment]
OK, all of these issues was because I set `--google-username rob@appinstitute.co.uk` when it should have been `--google-username rob`, if required at all.  It isn't the username you log in with to google it is the username for the machine.  Better documentation perhaps on this particular option.  I thought this was required too.

Not closing as documentation could use improvement but not a bug.

**Comment by ehazlett** [comment]
@robwithhair thanks for reporting and digging through the issue!  we'll get the Google docs updated for the proper usage.

**Comment by robwithhair** [comment]
Thanks!  Machine really is great.

**Comment by ehazlett** [comment]
@robwithhair thanks!

**Comment by thebaron93** [comment]
If i want to pass the boot disk as something else instead of Default (ubuntu-1404-trusty-v20150128) as well then?

**Comment by ehazlett** [comment]
@thebaron93 there needs to be a flag added (https://github.com/docker/machine/issues/1243)

**Comment by ehazlett** [comment]
Closing.  Please open a new issue if you continue to have trouble.  Thanks!
