### ISSUE TITLE
How to authenticate with amazonec2 driver with IAM-based security credentials?

### ISSUE THREAD

**Issue by cboettig** [docker/machine#871]
Hi,

I'm looking for advice on how to use docker machine without using a root-level key and secret key, as Amazon recommends.

First, I noticed a minor inconsistency in the [docker machine documentation](https://docs.docker.com/machine/), which appears to be for version `0.1.0` (which is what is available for download on that site right now), but still documents the argument `--amazonec2-iam-instance-profile` which appears to only be available on `0.2.0`, which it seems I need to build from source. (Lucky for me that this was included in the docs all the same, since it suggested to me such an option might exist).

Anyway, running `docker-machine 0.2.0` I'm able to successfully set the `--amazonec2-iam-instance-profile` to a "role" I create under my IAM panel to which I give full EC2 access (I assume that's the appropriate setting).  Nevertheless, when I try to run docker machine with this argument, along with the key and secret key of my IAM user, I only get a 403 error that my authentication failed.  If I create and use root keys, everything works fine (and of course then I don't need the `iam-instance-profile` argument at all.  

I'm probably just getting lost in the AWS complexity here, but I would greatly appreciate clearer documentation on how to go about authenticating an AWS instance without root keys (or if/where that is not possible, at least a note to the effect that a root key and not an IAM key is required).  

Thanks for considering, and keep making docker more awesome!  I've been blown away by convenience of `docker-machine` on each of the other platforms where authentication is less opaque!

**Comment by ehazlett** [comment]
@cboettig thanks for the feedback and kind words! I cc'd simon as I think he can give some guidance.

**Comment by sthulb** [comment]
That particular flag is to attach a role to an instance. By any chance are you trying to run machine using the credentials from the instance? If so are you specifying the session token via --amazonec2-session-token?

**Comment by andrewwatson** [comment]
FWIW I am using an AWS access and secret key that is **not** a root key and not specifying iam-instance-profile and I am able to create instances just fine...

**Comment by ehazlett** [comment]
thanks @andrewwatson 

all: is there anything we can document more to help get this setup?

**Comment by cboettig** [comment]
Thanks for the replies. @sthulb I couldn't actually figure out what an `--amazonec2-session-token` is -- do I need that for authentication to work when using IAM keys instead of root keys?  (Also not sure I follow what you mean by 'credentials from the instance', but I'm trying to create an instance via docker machine, so there isn't an existing instance that possesses certain credentials, just an instance profile.  

Authenticating with root keys, or authenticating with any of the other services I've tried, is pretty self explanatory.  But AWS recommends not using root keys, and then it's no longer clear what steps need to be done on both the AWS console end and in the `docker-machine` run command to authenticate successfully.  Of course amazon has extensive [documentation of IAM](http://docs.aws.amazon.com/IAM/latest/UserGuide/IAM_Introduction.html) but because it covers just about every use case under the sun it's kinda impenetrable. 

A guide that simply said what things needed to be created in the console (IAM key+private key, user? group? role, role assigned to ec2) and what arguments needed to be provided to `docker-machine` (session-token? iam-instance-profile) would be a helpful to users.  But feel free to just close this if that just sounds more like a RTFM for the AWS API than a `docker-machine` issue.  Thanks for considering.

**Comment by sthulb** [comment]
I guess firstly: 
 - Where are you getting the 403? from machine or a service on your instance?
 - Where are you running machine, on a local computer or on an instance? 
 - Does the IAM user have access to `ec2:*`?

**Comment by cboettig** [comment]
- Where are you getting the 403? from machine or a service on your
   instance?

from docker-machine

   - Where are you running machine, on a local computer or on an instance?

running locally on my laptop.

   - Does the IAM user have access to ec2:*?

Yes, the IAM user has access to EC2, as does the IAM "role" (although that
seems redundant).

Not sure why the auth issue persists in the IAM instance or how to get
around this.  Thanks again for your suggestions and apologies for the slow
reply.

**Comment by ipedrazas** [comment]
There are 2 scenarios.

* Running locally in your machine: you use AWS credentials (KEY & SECRET). This is to create containers in EC2 from your laptop using your credentials.
* Running in an EC2 instance: you use your IAM role from an EC2 instance. You cannot use IAM roles in your laptop, it doesn't work.

IAM roles provide a temporary token in the instance where the role is applied.

**Comment by cboettig** [comment]
Ivan, thanks for clarification!  So when running docker-machine from a
laptop it is impossible to avoid the use of root keys, even though their
use is not recommended by AWS.  Is that correct?

**Comment by ipedrazas** [comment]
You don't need the root keys, any user with the right permissions can use docker-machine.

I guess that your problem is that the key/secret pair you were trying did not have the rights to create EC2 instances.

But the principle is the same. Machines that are not in AWS, credentials, machines inside AWS, roles :smile:

**Comment by cboettig** [comment]
Ah, of course, works like a charm. Sorry for my confusion and thanks for
your patience and explanations!
