### ISSUE TITLE
Can't communicate through unix socket on b2d machines

### ISSUE THREAD

**Issue by ChristopherBiscardi** [docker/machine#875]
when ssh'd in to b2d instance, you should be able to use docker. Currently you can't because it doesn't accept connections on the socket.

(Using master build)

cc @nathanleclaire

**Comment by nathanleclaire** [comment]
I'm on this

**Comment by ehazlett** [comment]
This appears to be in our provisioner (https://github.com/docker/machine/blob/master/libmachine/provision/boot2docker.go#L91) doesn't have the socket option for b2d whereas the Ubuntu one does (https://github.com/docker/machine/blob/master/libmachine/provision/ubuntu.go#L150)

I'll let @nathanleclaire get this :)

Thanks for reporting!

**Comment by ehazlett** [comment]
Closing as #887 was merged.
