### ISSUE TITLE
Strip out dependencies 

### ISSUE THREAD

**Issue by sthulb** [docker/machine#883]
We should remove some of our dependencies, a good example is: `github.com/docker/docker/api`, it's only used by the `none` driver for validating a host.

**Comment by sthulb** [comment]
Q: Are a lot of the things in our `Godeps.json` file there because they're dependencies of dependencies?

cc @ehazlett @nathanleclaire

**Comment by ehazlett** [comment]
@sthulb yes i believe so

**Comment by nathanleclaire** [comment]
Unfortunately, at the moment we don't have a great way to audit dependencies, although I do think a sweep to clean up would be good at some point.  Let's revisit this when we get some direction from Go upstream about their vendoring solution.
