### ISSUE TITLE
DOC: not everyone is familiar with the concept of PATH, link or add more information about it

### ISSUE THREAD

**Issue by mattetti** [docker/machine#889]
> Docker Machine is supported on Windows, OSX, and Linux. To install Docker Machine, download the appropriate binary for your OS and architecture to the correct place in your PATH:

The documentation asks users to download the binary to their `PATH`, however, lots of users won't be familiar with their path. I would strongly suggest to link to some documentation about path, especially for Windows users out there. Another option is to suggest some common paths based on the os, `/usr/local/bin` for instance for Mac and Linux.

**Comment by mattetti** [comment]
https://docs.docker.com/machine/

**Comment by nathanleclaire** [comment]
Yeah I definitely want curl + chmod example(s) to copy-paste for OSX/Linux install.  Windows is a little trickier but I'm sure we can figure something out.

**Comment by ipedrazas** [comment]
Guess I should have started with #dibs

**Comment by znmeb** [comment]
There definitely needs to be more documentation for Windows. 
1. The executable download isn't an installer - it's an executable. Windows users are used to installers, which put things where they need to be with the right names and adjust PATHs accordingly so things "just work".
2. The executable has the name `docker-machine_windows-amd64.exe` but the documentation shows people just typing `docker-machine` at the command prompt.
3. It should be noted that `docker-machine` stores stuff in your user directory in a folder called `.docker`. For example, my user folder is `C:\Users\Ed` and docker-machine's stuff lands in `C:\Users\Ed\.docker`.

Really, though, step one is to build an installer. ;-)

**Comment by nathanleclaire** [comment]
Nice points @znmeb @mattetti .  I am working on some slightly better documentation on the Windows side in particular for this next release.

**Comment by znmeb** [comment]
@nathanleclaire any chance of either a Windows installer for docker-machine or boot2docker supporting Hyper-V instead of VirtualBox? Either one would work for me.

**Comment by ipedrazas** [comment]
Unfortunately I don't have a windows machine to test all the cases but splitting the installation docs by OS makes a lot of sense to me.

**Comment by znmeb** [comment]
@ipedrazas I have a dual-booted laptop (Windows 8.1 and Fedora Linux 22 Alpha). I'm testing heavily all ways of running Docker containers with Windows Client Hyper-V. So far I have Docker Machine and Fedora Project Atomic running and hope to have Vagrant running in the near future.

This is a bake-off - most convenient to an end user wins. ;-) That means working documentation and as few stop-points / places a beginner can screw up and get confused as possible.

**Comment by znmeb** [comment]
P.S.: Vagrant is a long shot in this race because its config file is Ruby code! That's about as end-user-unfriendly as it gets! ;-)

**Comment by nathanleclaire** [comment]
>  any chance of either a Windows installer for docker-machine or boot2docker supporting Hyper-V instead of VirtualBox? Either one would work for me.

Tentatively I think the plan here is to offer a Windows installer for `docker-machine`, but I'm not sure when that would come down the pipe.  Until then I intend to provide some instructions to make installing easier via msysgit.

> P.S.: Vagrant is a long shot in this race because its config file is Ruby code! That's about as end-user-unfriendly as it gets! ;-)

Lol - Vagrant has very good docs and is a pretty mature tool though - at any rate I'd like to hear your thoughts when you're finished so we can improve :)

**Comment by znmeb** [comment]
@nathanleclaire Vagrant is a tool for developers, not end-users. It depends heavily on Ruby devops tools like Puppet, Chef, etc. And it is heavily VirtualBox-centric. If you don't know Ruby well enough to read a Vagrantfile you're going to flounder trying to do anything except read instructions from a blog post and follow them. Then again, so is Docker. ;-)

**Comment by nathanleclaire** [comment]
In general I think a working understanding of `PATH` is pretty essential to running on the command line so I think it's a little out of scope for Machine docs to cover.  We should be offering Mac and Windows installers soon, too.
