### ISSUE TITLE
amazonec2 login to centos ami

### ISSUE THREAD

**Issue by joshuacalloway** [docker/machine#897]
Not obvious to me, but I'm trying to login into a centos based Amazon AMI.   The username is "root" and not "ubuntu"

Maybe add this flag "--amazonec2-username=root"

script example
-------
`docker-machine create --driver amazonec2  --amazonec2-access-key=AXXY --amazonec2-secret-key=Uxdfsc --amazonec2-vpc-id=vpc-123 --amazonec2-subnet-id=subnet-123 --amazonec2-security-group=vpc-wide-open-for-testing-only --amazonec2-ami=ami-centosbased testcentos`

**Comment by sthulb** [comment]
I'd expect `--ssh-user` as a flag I guess.

**Comment by nathanleclaire** [comment]
If we had that flag it _maybe_ would have worked with previous versions of machine, but with the current master branch of `docker-machine` we only support Ubuntu and boot2docker as OSes.  We will gradually be expanding our reach into other OSes, though (just did a big refactor to support this), so stay tuned.

cc @ehazlett probably want to close this.

**Comment by ehazlett** [comment]
@joshuacalloway yeah as @nathanleclaire mentioned we currently only support Ubuntu so this would not have worked even with the login.  We will be expanding support for more base operating systems soon.  Thanks for the feedback!
