### ISSUE TITLE
docker run fails with "malformed HTTP response"

### ISSUE THREAD

**Issue by nicolasff** [docker/machine#90]
On OSX Yosemite with release 0.0.2:

    $ machine -D create -d virtualbox cassandra
    DEBU[0000] executing: VBoxManage
    
    [Skipping VBoxManage output, hundreds of line of help]
    
    INFO[0000] Downloading boot2docker...
    INFO[0037] Creating SSH key...
    DEBU[0037] executing: /usr/bin/ssh-keygen ssh-keygen -t rsa -N  -f /Users/nicolas/.docker/hosts/cassandra/id_rsa
    
    Generating public/private rsa key pair.
    Your identification has been saved in /Users/nicolas/.docker/hosts/cassandra/id_rsa.
    Your public key has been saved in /Users/nicolas/.docker/hosts/cassandra/id_rsa.pub.
    The key fingerprint is:
    db:51:27:90:d7:8e:f4:68:35:80:94:cd:96:6c:ca:60 nicolas@Nicolass-iMac.local
    The key's randomart image is:
    +--[ RSA 2048]----+
    |         .oB.+   |
    |        E +.X +  |
    |       . o *o*.. |
    |          o.+oo  |
    |        S ..     |
    |         o .     |
    |        . .      |
    |                 |
    |                 |
    +-----------------+
    INFO[0037] Creating VirtualBox VM...
    DEBU[0037] Creating 20000 MB hard disk image...
    Converting from raw image file="stdin" to file="/Users/nicolas/.docker/hosts/cassandra/disk.vmdk"...
    Creating dynamic image with size 20971520000 bytes (20000MB)...
    DEBU[0041] executing: VBoxManage createvm --name docker-host-ae75949676e858b3896d54d65588cb4405837113ffe9025e80ffdeee9239aa78 --register
    Virtual machine 'docker-host-ae75949676e858b3896d54d65588cb4405837113ffe9025e80ffdeee9239aa78' is created and registered.
    UUID: c724b220-7164-410c-be40-86a8d08d6fae
    Settings file: '/Users/nicolas/VirtualBox VMs/docker-host-ae75949676e858b3896d54d65588cb4405837113ffe9025e80ffdeee9239aa78/docker-host-ae75949676e858b3896d54d65588cb4405837113ffe9025e80ffdeee9239aa78.vbox'
    DEBU[0041] executing: VBoxManage modifyvm docker-host-ae75949676e858b3896d54d65588cb4405837113ffe9025e80ffdeee9239aa78 --firmware bios --bioslogofadein off --bioslogofadeout off --natdnshostresolver1 on --bioslogodisplaytime 0 --biosbootmenu disabled --ostype Linux26_64 --cpus 8 --memory 1024 --acpi on --ioapic on --rtcuseutc on --cpuhotplug off --pae on --synthcpu off --hpet on --hwvirtex on --nestedpaging on --largepages on --vtxvpid on --accelerate3d off --boot1 dvd
    DEBU[0041] executing: VBoxManage modifyvm docker-host-ae75949676e858b3896d54d65588cb4405837113ffe9025e80ffdeee9239aa78 --nic1 nat --nictype1 virtio --cableconnected1 on
    DEBU[0041] executing: VBoxManage modifyvm docker-host-ae75949676e858b3896d54d65588cb4405837113ffe9025e80ffdeee9239aa78 --natpf1 ssh,tcp,127.0.0.1,49261,,22
    DEBU[0041] executing: VBoxManage list hostonlyifs
    DEBU[0041] executing: VBoxManage hostonlyif create
    0%...10%...20%...30%...40%...50%...60%...70%...80%...90%...100%
    DEBU[0041] executing: VBoxManage hostonlyif ipconfig vboxnet0 --ip 192.168.99.1 --netmask 255.255.255.0
    DEBU[0041] executing: VBoxManage list dhcpservers
    DEBU[0042] executing: VBoxManage dhcpserver modify --netname HostInterfaceNetworking-vboxnet0 --ip 192.168.99.2 --netmask 255.255.255.0 --lowerip 192.168.99.100 --upperip 192.168.99.254 --enable
    DEBU[0042] executing: VBoxManage modifyvm docker-host-ae75949676e858b3896d54d65588cb4405837113ffe9025e80ffdeee9239aa78 --nic2 hostonly --nictype2 virtio --hostonlyadapter2 vboxnet0 --cableconnected2 on
    DEBU[0042] executing: VBoxManage storagectl docker-host-ae75949676e858b3896d54d65588cb4405837113ffe9025e80ffdeee9239aa78 --name SATA --add sata --hostiocache on
    DEBU[0042] executing: VBoxManage storageattach docker-host-ae75949676e858b3896d54d65588cb4405837113ffe9025e80ffdeee9239aa78 --storagectl SATA --port 0 --device 0 --type dvddrive --medium /Users/nicolas/.docker/hosts/cassandra/boot2docker.iso
    DEBU[0042] executing: VBoxManage storageattach docker-host-ae75949676e858b3896d54d65588cb4405837113ffe9025e80ffdeee9239aa78 --storagectl SATA --port 1 --device 0 --type hdd --medium /Users/nicolas/.docker/hosts/cassandra/disk.vmdk
    DEBU[0042] executing: VBoxManage guestproperty set docker-host-ae75949676e858b3896d54d65588cb4405837113ffe9025e80ffdeee9239aa78 /VirtualBox/GuestAdd/SharedFolders/MountPrefix /
    DEBU[0042] executing: VBoxManage guestproperty set docker-host-ae75949676e858b3896d54d65588cb4405837113ffe9025e80ffdeee9239aa78 /VirtualBox/GuestAdd/SharedFolders/MountDir /
    DEBU[0042] executing: VBoxManage sharedfolder add docker-host-ae75949676e858b3896d54d65588cb4405837113ffe9025e80ffdeee9239aa78 --name Users --hostpath /Users --automount
    DEBU[0042] executing: VBoxManage setextradata docker-host-ae75949676e858b3896d54d65588cb4405837113ffe9025e80ffdeee9239aa78 VBoxInternal2/SharedFoldersEnableSymlinksCreate/Users 1
    INFO[0042] Starting VirtualBox VM...
    DEBU[0042] executing: VBoxManage startvm docker-host-ae75949676e858b3896d54d65588cb4405837113ffe9025e80ffdeee9239aa78 --type headless
    Waiting for VM "docker-host-ae75949676e858b3896d54d65588cb4405837113ffe9025e80ffdeee9239aa78" to power on...
    VM "docker-host-ae75949676e858b3896d54d65588cb4405837113ffe9025e80ffdeee9239aa78" has been successfully started.
    INFO[0042] Waiting for VM to start...
    DEBU[0073] Adding key to authorized-keys.d...
    DEBU[0073] executing: ssh -o IdentitiesOnly=yes -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=quiet -p 49261 -i /Users/nicolas/.docker/hosts/cassandra/id_rsa docker@localhost mkdir -p "/root/.docker/authorized-keys.d" && cat > "/root/.docker/authorized-keys.d/docker-host.json"
    DEBU[0074] executing: ssh -o IdentitiesOnly=yes -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=quiet -p 49261 -i /Users/nicolas/.docker/hosts/cassandra/id_rsa docker@localhost sudo /etc/init.d/docker restart
    INFO[0074] "cassandra" has been created and is now the active machine. To point Docker at this machine, run: export DOCKER_HOST=$(machine url) DOCKER_AUTH=identity

    $ export DOCKER_HOST=$(machine url) DOCKER_AUTH=identity

    $ machine ls
    NAME        ACTIVE   DRIVER       STATE     URL
    cassandra   *        virtualbox   Running   tcp://192.168.99.100:2376

    $ docker run busybox bash
    2014/12/11 23:58:54 Post http://192.168.99.100:2376/v1.15/containers/create: malformed HTTP response "\x15\x03\x01\x00\x02\x02\x16"

    $ docker run busybox echo hello world
    2014/12/11 23:59:07 Post http://192.168.99.100:2376/v1.15/containers/create: malformed HTTP response "\x15\x03\x01\x00\x02\x02\x16"

    $ ./docker-1.3.1-dev-identity-auth run busybox echo hello world
    FATA[0000] TLS Handshake error: remote error: bad certificate

    $ machine url
    tcp://192.168.99.100:2376

    $ echo $DOCKER_HOST
    tcp://192.168.99.100:2376

    $ echo $DOCKER_AUTH
    identity

    $ machine -D inspect cassandra
    {
        "DriverName": "virtualbox",
        "Driver": {
            "MachineName": "docker-host-ae75949676e858b3896d54d65588cb4405837113ffe9025e80ffdeee9239aa78",
            "SSHPort": 49261,
            "Memory": 1024,
            "DiskSize": 20000,
            "Boot2DockerURL": ""
        }
    }

    $ curl -s http://192.168.99.100:2376/v1.15/ | xxd
    0000000: 1503 0100 0202 0a                        .......

What am I missing?

**Comment by ehazlett** [comment]
@nicolasff could you try this from master and see if it still exists?

**Comment by rickard-von-essen** [comment]
I had the same problem and it was solved by using **docker-1.4.1-136b351e-identity** instead of **docker-1.3.1-dev-identity-auth**.

**Comment by ehazlett** [comment]
Ok thanks @rickard-von-essen.  I will close this for now as we are using the standard Docker client and server now.  Please re-open if you notice again.
