### ISSUE TITLE
Enable Docker Engine configuration

### ISSUE THREAD

**Issue by ehazlett** [docker/machine#902]
Currently there are only a few things that can be configured in the Docker Engine. This will enable more operations such as Engine labels, storage drivers, etc.

- [x] label
- [x] graph (graph dir)
- [x] storage-driver
- [x] insecure-registry
- [x] registry-mirror

**Comment by nathanleclaire** [comment]
Just a thought on implementation: moving away from our current `Sprintf` method and over to using `text/template` will probably provide us far more flexibility on this in the long run.

**Comment by ehazlett** [comment]
+1

**Comment by ehazlett** [comment]
closing as #1040 is merged.
