### ISSUE TITLE
Expand Provisioning capabilities

### ISSUE THREAD

**Issue by ehazlett** [docker/machine#905]
This will enable the provisioning capabilities for other base distributions besides boot2docker and Ubuntu.  For example, RedHat like distributions.

**Comment by flavio** [comment]
Hi, where is this work being done? I would like to help adding SUSE/openSUSE support.

**Comment by ehazlett** [comment]
@flavio not yet -- i was planning on starting on centos/fedora this week.

**Comment by flavio** [comment]
Any update on this topic?

**Comment by ehazlett** [comment]
@flavio #1090

**Comment by jiangshengwu** [comment]
Looking forward to CentOS support, and maybe `os-release` shouldn't be the only way to detect operating system.

**Comment by ehazlett** [comment]
@jiangshengwu what else would you suggest?

**Comment by jiangshengwu** [comment]
@ehazlett As you've been working on the expanding of provision, maybe you've noticed that some linux release versions don't have `os-release`. Such as CentOS6.x or 7, but `centos-release` instead.

Other ways of release version detection can be useful: `redhat-release` or `lsb_release` command which is more universal.

**Comment by ehazlett** [comment]
@jiangshengwu ah i see -- thanks -- we'll keep it in mind :)

**Comment by Tritlo** [comment]
could we get support for the default AWS Linux? Running the AWS Linux AMIs is cheaper than running the ubuntu ones.
