### ISSUE TITLE
Create a consistent Windows experience

### ISSUE THREAD

**Issue by ehazlett** [docker/machine#906]
The current Windows experience with Machine is sub-par from its Mac/Linux counterpart.  This will bring it up to be consistent.  This includes getting Machine running as well as logging and output formatting consistency.

- [x] Use Powershell for Machine interaction (https://github.com/docker/machine/pull/1033)
- [x] Cleanup logging (ascii chars in output)
- [x] Remove dependency on external apps if possible (i.e. ssh, bash)

**Comment by ahmetalpbalkan** [comment]
:+1: following this

**Comment by znmeb** [comment]
A point and click interface for Client Hyper-V is pretty high on my wishlist for Windows. Maybe that belongs under Boot2Docker?

**Comment by ahmetalpbalkan** [comment]
@znmeb care to explain more? What is that?

**Comment by znmeb** [comment]
@ahmetalpbalkan Boot2Docker is a one-click installer. It installs Git for Windows and VirtualBox, then creates a virtual machine running the Boot2Docker ISO. What I'm looking for is something that does the same thing but creates the virtual machine in Windows 8.1 Professional's Client Hyper-V native virtualizer.

The pieces are there - Docker Machine can create Hyper-V machines running Boot2Docker and the Boot2Docker installer can do the same thing with VirtualBox.

**Comment by garthk** [comment]
Isn't the idea to replace the `boot2docker` command line (not VM) with `docker machine` once the latter hits parity? 

If so: this is the right repo, @znmeb, but you might want your own issue for

* making a separate installer available without VirtualBox and
* using `--driver= hyper-v` by default if it's available

… as neither are a matter of bringing the Windows experience of `docker machine` up to parity with Linux and OS X.

**Comment by ehazlett** [comment]
@garthk yes the idea is to replace the boot2docker CLI tool with machine.

@znmeb there are plans to update the current installer mechanism to include machine etc similar to b2d.  we haven't ironed out exactly what that looks like but will have one when machine enters non-beta.

**Comment by znmeb** [comment]
Sounds good to me - I'm chomping at the bit to test something. ;-) I just wish I knew PowerShell and open source Windows installer tooling well enough to build something myself.

**Comment by ehazlett** [comment]
@znmeb i know almost nothing about the installer :)  however, here is the source in case you want to check it out: https://github.com/boot2docker/windows-installer

**Comment by ehazlett** [comment]
@znmeb and fyi, i'm not sure exactly which direction we will go (we may have a completely different install system altogether) -- however, that should get you what you need for the interim

**Comment by znmeb** [comment]
@ehazlett Thanks - I have no preconceived notions about installers except that there has to be one. ;-) Pretty much all open source installers force the user to page through half a dozen or so option screens and license acceptance pages, which I think reeks.

**Comment by ehazlett** [comment]
Closing as the child tasks are compete.  If you would like to see a specific improvement added please open a new issue.  Thanks!

**Comment by ahmetalpbalkan** [comment]
@ehazlett never had a chance to try the new code, what's the status of ANSI emulation integration of the ssh code for cmd.exe/powershell?

**Comment by ehazlett** [comment]
@ahmetalpbalkan i don't think we've done anything there.  we did refactor the logging so there are no longer color codes sent which solves our specific ansi display issue.  I think long term we want to move to what you did in the CLI.
