### ISSUE TITLE
allow setting storage backend when creating machine

### ISSUE THREAD

**Issue by clkao** [docker/machine#911]
Might require different provision strategy for different provider.

For example for using overlayfs on boot2docker, it's adding `DOCKER_STORAGE=overlay` to `/var/lib/boot2docker/profile`.  for btrfs it's also required to mkfs.btrfs first.

**Comment by ehazlett** [comment]
Thanks!  We are targeting this for the 0.3.0 release (https://github.com/docker/machine/issues/902).  We would love to have you help and test :)
