### ISSUE TITLE
Openstack driver got error

### ISSUE THREAD

**Issue by Fangfenghua** [docker/machine#912]
When i run docker-machine ls i got error like:
ERRO[0000] error getting state for host test: Post https://192.168.1.3:443/identity/v2.0/tokens: x509: certificate signed by unknown authority 

attach:
[root@centos-master ~]# docker-machine ls
ERRO[0000] error getting state for host test: Post https://192.168.1.3:443/identity/v2.0/tokens: x509: certificate signed by unknown authority 
ERRO[0000] error getting URL for host test: Post  https://192.168.1.3:443/identity/v2.0/tokens: x509: certificate signed by unknown authority 
NAME   ACTIVE   DRIVER      STATE   URL   SWARM
test            openstack

**Comment by ggiamarchi** [comment]
@ldpc When you use a self-signed certificate you have to use the flag `--openstack-insecure` to ignore SSL errors.

**Comment by Fangfenghua** [comment]
@ggiamarchi  Where  can i  add the --openstack-insecure  option?

**Comment by ggiamarchi** [comment]
@Fangfenghua You can give this flag when you create the machine using the `docker-machine create` command. Then docker-machine will remember it for all others commands.

**Comment by marcellodesales** [comment]
Is there a similar entry for the `none` driver?
