### ISSUE TITLE
machine url command for virtualbox fails on Windows

### ISSUE THREAD

**Issue by johngossman** [docker/machine#92]
First issue: In virtualbox.go GetState uses a regex to pull the value out of "VMState". The regex is:

	re := regexp.MustCompile(`(?m)^VMState="(\w+)"$`)

My wild guess on the first try was that Windows is different because of \r\n. Whether that was it or not, removing the $ to match end-of-line fixed the problem.

Second issue: driver still can't get the ip address.
This is done in the GetIP func in virtualbox.go. Quick debugging, the stuff that parses the results from "ip addr show dev eht1" can't find "inet". On my machine it looks like there is an ipv6 addr in the result. Haven't compared on a Mac or Linux machine to see what is there.

**Comment by ehazlett** [comment]
First part is fixed in #426.

**Comment by ehazlett** [comment]
This appears to be fixed.  I just tested and `url` returns correctly.  If you continue to see issues, please re-open.  Thanks!
