### ISSUE TITLE
Proposal: add DOCKER_MACHINE_NAME in machine env

### ISSUE THREAD

**Issue by waitingkuo** [docker/machine#925]
Goal: add following line when execute `machine env dev`

    export DOCKER_MACHINE_NAME=dev

Why?
When we want to control more than more machine in the same time, we need to open several terminal tabs, set the different env for each tabs, and switch between these tabs. It's easy to forget where we are. Currently, we can use `export | grep DOCKER_HOST` to see which host we are using. However, sometimes they are only the ipv4/ipv6 addresses and hard to remember.

To release this pain, I propose that we can add a new environment variable `DOCKER_MACHINE_NAME` so that we can get it by `export | grep DOCKER_MACHINE_NAME`.
Moreover, we can set `$PS1` as something like 

    export PS1="(\$DOCKER_MACHINE_NAME) \W \u$ "

Then the machine name will always be displayed in the bash promt. For example:

    (dev) ~ willy $ eval `machine env staging`
    (staging) ~ willy$

**Comment by ehazlett** [comment]
+1 -- I like the idea of having some "metadata" available in the environment.

/cc @nathanleclaire @sthulb thoughts?

**Comment by sthulb** [comment]
fine with me

**Comment by nathanleclaire** [comment]
Why not have something like:

```console
export PS1="($(docker-machine active)) \W \u $ "
```

in your `~/.bashrc`?

I know that sometimes active drifts from `DOCKER_HOST`, but I'd rather fix that issue directly than introducing additional complexity to `env`.

**Comment by waitingkuo** [comment]
Hi @nathanleclaire thank you for the feedback.

In my case, I manipulate more than one docker hosts in different terminal tabs in the same time. But we can only have an active machine. Any thoughts for fixing this issue?

**Comment by philipz** [comment]
I use tmux to switch~~~ :)

**Comment by ehazlett** [comment]
I think without getting hung up on the specific shell configuration, I like the idea of having more info about the active settings in the environment.  I'm not sure it adds too much complexity -- simply another export to `env`.

**Comment by waitingkuo** [comment]
I prefer adding machine name as an env variable because its something like the primary_id in the database. We could use this name to query other information by the `docker-machine` command (maybe a machine restful server in the future)

**Comment by nathanleclaire** [comment]
> In my case, I manipulate more than one docker hosts in different terminal tabs in the same time. But we can only have an active machine. Any thoughts for fixing this issue?

Ah, I see.  I'm in favor of another environment variable in env for this purpose, and if we do something like https://github.com/docker/machine/pull/777 too "active" will be tracked transparently and you will be able to have different "active" hosts in different windows.

**Comment by hairyhenderson** [comment]
I was bored... so I implemented this in #1175 :smile:
