### ISSUE TITLE
OpenStack driver stuck waiting for SSH server on its private IP address

### ISSUE THREAD

**Issue by fdangtran** [docker/machine#926]
Checked with machine 0.2.0 (382f71f)

When I try to create a machine with the OpenStack driver, the client get stuck waiting for the SSH server to be started.  Unless I'm wrong, the client attempts to connect to the VM on its private IP address not its floating IP (which has not been allocated yet).
Currently, the only way to use docker-machine is from a machine within the cloud with access to the private network the VM is connected to.

DEBU[0000] Creating OpenStack instance...                FlavorId=a25dab6d-b2dd-49a8-87a9-64c2c0016e5b ImageId=3236f93d-23ae-4eaf-864f-3cb89b45a1d6
INFO[0000] Creating machine...                          
DEBU[0000] Waiting for the OpenStack instance to be ACTIVE...  MachineId=10eb36b9-4901-4c29-8cfc-fcae33ec72ef
DEBU[0042] Looking for the IP address...                 MachineId=10eb36b9-4901-4c29-8cfc-fcae33ec72ef
DEBU[0042] IP address found                              IP=10.100.0.20 MachineId=10eb36b9-4901-4c29-8cfc-fcae33ec72ef
DEBU[0042] Waiting for the SSH server to be started...   IP=10.100.0.20 MachineId=10eb36b9-4901-4c29-8cfc-fcae33ec72ef

**Comment by ggiamarchi** [comment]
@fdangtran Can you please put here the exact command you ran to create the machine ?

**Comment by fdangtran** [comment]
./docker-machine_darwin-amd64 --debug create -d openstack --openstack-image-id=3236f93d-23ae-4eaf-864f-3cb89b45a1d6 --openstack-flavor-id=a25dab6d-b2dd-49a8-87a9-64c2c0016e5b --openstack-net-id=aa4ffefc-e11b-4197-a334-a15e1649034b test

**Comment by ggiamarchi** [comment]
With this command it's normal your machine does not get a floating IP. You have to use the flag `--openstack-floatingip-pool <<pool name>>`. Then, docker-machine will use your floating IP to SSH the machine.

**Comment by fdangtran** [comment]
OK thanks. It works fine now.
