### ISSUE TITLE
docker-machine create hangs on digitalocean

### ISSUE THREAD

**Issue by coopernurse** [docker/machine#933]
I'm still isolating where the issue is here.  But I'll file this with the symptom in case others see something similar.  This may occur with other ubuntu based providers, but I'm seeing it today with digitalocean.  I did not have this problem yesterday, so perhaps the base image or the get.docker.com script has changed recently?

Summary: `start docker` is hanging during the initial boot/provision sequence.

I ran: 

```bash
docker-machine create --driver digitalocean --digitalocean-access-token $DO_TOKEN do1
```

ssh key is created and droplet boots, as expected.  provisioning hangs here:

```bash
Preparing to unpack .../lxc-docker_1.5.0_amd64.deb ...
Unpacking lxc-docker (1.5.0) ...
Processing triggers for man-db (2.6.7.1-1ubuntu1) ...
Processing triggers for ureadahead (0.100.0-16) ...
Setting up aufs-tools (1:3.2+20130722-1.1) ...
Setting up liberror-perl (0.17-1.1) ...
Setting up git-man (1:1.9.1-1ubuntu0.1) ...
Setting up git (1:1.9.1-1ubuntu0.1) ...
Setting up cgroup-lite (1.9) ...
cgroup-lite start/running
Setting up lxc-docker-1.5.0 (1.5.0) ...
```

I can ssh into the droplet, and `ps aux` shows:

```
root      1192  0.0  0.2  12400  1396 ?        Ss   11:00   0:00 bash -c if [ ! -e /usr/bin/docker ]; then curl -sSL https://get.docker.com | sh -; fi
root      1194  0.0  0.1   4444   724 ?        S    11:00   0:00 sh -
root      1209  0.0  0.1   4444   652 ?        S    11:00   0:00 sh -c sleep 3; apt-get update; apt-get install -y -q lxc-docker
root      1268  3.9 10.4  92344 52236 ?        S    11:00   2:29 apt-get install -y -q lxc-docker
root      2593  0.0  0.5  16600  2860 ?        S    11:00   0:00 /usr/bin/dpkg --status-fd 29 --configure aufs-tools:amd64 liberror-perl:all git-man:all git:amd64 cgroup-lite:all lxc-docker-1.5.0:amd64 lxc-docker
root      2677  0.0  0.1   4444   652 ?        S    11:00   0:00 /bin/sh /var/lib/dpkg/info/lxc-docker-1.5.0.postinst configure 
root      2685  0.0  0.2  18168  1176 ?        S    11:00   0:00 start docker
```

I can confirm that `/usr/bin/docker` exists and is executable.  `start docker` hangs if run from the terminal.

**Comment by ehazlett** [comment]
Hmm I just successfully tested on nyc and sfo.  Could you try again?  Perhaps it was a momentary issue with their service.

**Comment by booyaa** [comment]
digital ocean frequently have scheduling delays. sadly they don't keep their status page up to date. if you email support they'll usually confirm if this is the case.

**Comment by coopernurse** [comment]
@ehazlett Thanks for looking into it.  I just re-tested and it worked.  

@booyaa The Droplet status on the DO webapp was "Active", and I could ssh into it normally.  What was curious was that the hung command appeared to be the upstart "start docker" command.

I'm willing to chalk this up to a transient DO issue, so I'll close this out.  Thanks again for looking into it

**Comment by ehazlett** [comment]
@coopernurse thanks for digging -- we have brainstormed ideas around these "random" (not quite so random ;) failures.  hopefully we can get a solution to them.  thanks for the update!

**Comment by stenstad** [comment]
@ehazlett Hi, I have noticed this running Ubuntu 14.04 on an Openstack installation (Zetta.IO) as well. For some reason the Docker initscript doesn't work randomly. I think there might be a timing-issue somewhere. It worked 1 in 4 times for now.

It seems to hang in the post-installation step:

Setting up lxc-docker-1.5.0 (1.5.0) ...

If I look at /var/log/upstart/docker.log:

Waiting for /var/run/docker.sock
INFO[0000] +job serveapi(unix:///var/run/docker.sock)   
INFO[0000] +job init_networkdriver()                    
INFO[0000] Listening for HTTP on unix (/var/run/docker.sock) 
invalid argument
INFO[0000] -job init_networkdriver() = ERR (1)          
FATA[0000] invalid argument                             
Waiting for /var/run/docker.sock
Waiting for /var/run/docker.sock
Waiting for /var/run/docker.sock

**Comment by ehazlett** [comment]
@stenstad yes we have noticed this in the RCs of 1.6 as well.  There is a fix coming that should fix this.  Basically it's a module not being loaded -- the new installer takes care of it.

**Comment by wmiller848** [comment]
I'm having a similar issue with the driver as of today.

Digital Ocean creates the machine, I can access it via ssh (if I ctrl-c after its hanging for a while).

docker-machine hangs forever

```
$ docker-machine create --driver digitalocean --digitalocean-access-token $DO_TOKEN node1
```

My version info:

`mac os`
```
$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.10.4
BuildVersion:	14E46
```

`docker`
```
$ docker --version
Docker version 1.7.1, build 786b29d
```

`docker-machine`
```
$ docker-machine --version
docker-machine version 0.3.1 (HEAD)
```

`driver info`

```
    "DriverName": "digitalocean",
    "Driver": {
        "IPAddress": "[OMITTED]",
        "SSHUser": "root",
        "SSHPort": 22,
        "MachineName": "node1",
        "CaCertPath": "/Users/user_a/.docker/machine/certs/ca.pem",
        "PrivateKeyPath": "/Users/user_a/.docker/machine/certs/ca-key.pem",
        "SwarmMaster": false,
        "SwarmHost": "tcp://0.0.0.0:3376",
        "SwarmDiscovery": "",
        "AccessToken": "[OMITTED]",
        "DropletID": [OMITTED],
        "DropletName": "",
        "Image": "ubuntu-14-04-x64",
        "Region": "nyc3",
        "SSHKeyID":[OMITTED],
        "Size": "512mb",
        "IPv6": false,
        "Backups": false,
        "PrivateNetworking": false
    }
```
