### ISSUE TITLE
docker-machine env places double quotes around path for DOCKER_CERT_PATH, but around the certificate

### ISSUE THREAD

**Issue by booyaa** [docker/machine#935]
To reproduce:

```
$(docker-machine env dev)
$ docker ps
FATA[0000] Couldn't read ca cert "/Users/booyaa/.docker/machine/machines/dev"/ca.pem: open "/Users/booyaa/.docker/machine/machines/dev"/ca.pem: no such file or directory
```

presumably for this to work, the file path to ca.pem should be: ```"/Users/booyaa/.docker/machine/machines/dev/ca.pem"```

this behaviour appears to be have been introduced in v0.2.0.

version I'm using: docker-machine version 0.2.0 (45f08d9)
os: OSX Yosemite 10.10.2

**Comment by knarz** [comment]
It's `eval $(docker-machine env machine)` to load the settings into the env now.

**Comment by booyaa** [comment]
cheers!
