### ISSUE TITLE
Build machine fail

### ISSUE THREAD

**Issue by Fangfenghua** [docker/machine#940]
[root@ip-172-31-45-134 machine]# uname -a
Linux ip-172-31-45-134.us-west-2.compute.internal 3.10.0-229.el7.x86_64 #1 SMP Thu Jan 29 18:37:38 EST 2015 x86_64 x86_64 x86_64 GNU/Linux

[root@ip-172-31-45-134 machine]# docker -v
Docker version 1.5.0-dev, build fc0329b/1.5.0
[root@ip-172-31-45-134 machine]# 

-->     linux/amd64: github.com/docker/machine
-->     windows/386: github.com/docker/machine
-->   windows/amd64: github.com/docker/machine

6 errors occurred:
--> darwin/386 error: exit status 1
Stderr: go install github.com/docker/machine: open /go/src/github.com/docker/machine/docker-machine_darwin-386: permission denied

--> darwin/amd64 error: exit status 1
Stderr: go install github.com/docker/machine: open /go/src/github.com/docker/machine/docker-machine_darwin-amd64: permission denied

--> linux/386 error: exit status 1
Stderr: go install github.com/docker/machine: open /go/src/github.com/docker/machine/docker-machine_linux-386: permission denied

--> linux/amd64 error: exit status 1
Stderr: go install github.com/docker/machine: open /go/src/github.com/docker/machine/docker-machine_linux-amd64: permission denied

--> windows/386 error: exit status 1
Stderr: go install github.com/docker/machine: open /go/src/github.com/docker/machine/docker-machine_windows-386.exe: permission denied

--> windows/amd64 error: exit status 1
Stderr: go install github.com/docker/machine: open /go/src/github.com/docker/machine/docker-machine_windows-amd64.exe: permission denied

when i add   --privileged=true  build is ok!

**Comment by ehazlett** [comment]
Are you using `script/build` to build the binaries?

**Comment by Fangfenghua** [comment]
@ehazlett  Yes，I use script/build.

[root@ip-172-31-45-134 ec2-user]# ps -ef|grep docker
root      2292     1  0 12:00 ?        00:01:04 /usr/bin/docker -d --selinux-enabled
root      4380  4364  0 19:21 pts/0    00:00:00 grep --color=auto docker
[root@ip-172-31-45-134 ec2-user]#

**Comment by Fangfenghua** [comment]
@ehazlett  May be it's becasue i enable SELinux,  when i disable SELinux it's also work ok. Did you enable the SElinux option?

**Comment by Fangfenghua** [comment]
@ehazlett  Did you run script/buil on ubuntu? In ubuntu the SELinux is disable default.

**Comment by ehazlett** [comment]
@Fangfenghua can you give me the OS version you are using so I can re-produce?  thanks

**Comment by Fangfenghua** [comment]
@ehazlett  A aws instance with ostype   Red Hat Enterprise Linux 7.1 (HVM),

**Comment by Fangfenghua** [comment]
ping  @ehazlett  Did you re-produce that?

**Comment by nathanleclaire** [comment]
This is an issue related to permissions set with SELinux, not Machine, but perhaps we can add a note in the README.

**Comment by clnperez** [comment]
Commenting here since I ran into issues today with build. Can you try deleting all the containers and images that were involved in the machine build? I was running into this yesterday and today and created some policy updates using audit2allow and semodule -i, but those weren't eliminating the permission denied errors. What ended up (I *think*) fixing the issue was deleting the images and starting over. I'd like to know if just deleting the images is enough, though -- so if you can try that it would be helpful.

**Comment by clnperez** [comment]
D'oh. Nevermind on that. I'll keep looking into this.

**Comment by jeanlaurent** [comment]
The build has been tremendously changed since july.

I'm going to close this, and re-open if this happen again with the new `make` build system.
