### ISSUE TITLE
[Proposal] Add centos、rhel support for docker-machine

### ISSUE THREAD

**Issue by Fangfenghua** [docker/machine#944]
@ehazlett 
 When i test openstack-driver with os type centos, i got error “OS type not recognized”. I check the code and found that we just support  ubuntu 14:04 or boot2docker.

 Can we support more ostype?Like centos7 or rhel7.

**Comment by znmeb** [comment]
@Fangfenghua CentOS as a guest or CentOS as a host?

**Comment by Fangfenghua** [comment]
@znmeb  CentOS as a guest!

**Comment by ehazlett** [comment]
This is planned as part of #905. :)

**Comment by Fangfenghua** [comment]
@ehazlett  Did you have any plan  to implement it?

**Comment by ehazlett** [comment]
@Fangfenghua we will most likely use the Provisioner interface as Ubuntu uses.  We haven't discussed specifics beyond that.  Feel free to visit IRC if you want to discuss :)

**Comment by ehazlett** [comment]
Closing.  This is referenced in #905 and will be added there.  Thanks!
