### ISSUE TITLE
Google when swarm should create an endpoint on port 3376

### ISSUE THREAD

**Issue by imton** [docker/machine#948]
Right now I have to enable it manually which kind of limit the usefulness of this amazing tool in first place. 

Thanks

**Comment by ehazlett** [comment]
I'm checking this now but it looks like it should be working: https://github.com/docker/machine/blob/master/drivers/google/compute_util.go#L105

**Comment by imton** [comment]
This didn't create the swarm port

````bash
docker-machine create --driver google --google-project XXXX --google-zone us-central1-a --google-machine-type n1-highmem-2 --swarm --swarm-master --swarm-discovery token://YYYYY swarm-master
````

**Comment by ehazlett** [comment]
ok thanks -- checking

**Comment by imton** [comment]
:+1:

**Comment by ehazlett** [comment]
Everything looks ok to me:

```
ehazlett machine> docker-machine ls
NAME        ACTIVE   DRIVER       STATE     URL                          SWARM  
gce-swarm   *        google       Running   tcp://107.178.215.204:2376   gce-swarm (master)
ehazlett machine> docker $(docker-machine config --swarm gce-swarm) info
Containers: 2
Nodes: 1
 gce-swarm: 107.178.215.204:2376
  └ Containers: 2
  └ Reserved CPUs: 0 / 1
  └ Reserved Memory: 0 B / 3.615 GiB
```

What version of Machine are you using?

**Comment by imton** [comment]
````
➜ audify git:(master) ✗ docker-machine --version
docker-machine version 0.1.0
````

**Comment by ehazlett** [comment]
ah ok -- can you try the latest RC available here: https://github.com/docker/machine/releases/tag/v0.2.0-rc3

**Comment by aperepel** [comment]
Hi, I've download the 0.2.0 version HEAD from https://github.com/docker/machine/releases/download/v0.2.0/docker-machine_darwin-amd64 , and the 3376 port rule wasn't created for me. I still had to manually create a firewall rule in GCE. Wondering if it made it into this release.

**Comment by aperepel** [comment]
Hi, this is still an issue with `docker-machine version 0.3.0-dev (fec8b4a)` and is getting annoying, because GCE will re-arrange node ips and firewall rules won't apply after `docker-machine stop/start`.

See this session transcription:
```
08:11:00::docker-964 ♨ >  docker-machine ls
NAME           ACTIVE   DRIVER       STATE     URL                         SWARM
gce1                    google       Running   tcp://104.154.95.34:2376    gce1 (master)
gce2                    google       Running   tcp://104.154.84.165:2376   gce1
gce3                    google       Running   tcp://130.211.182.1:2376    gce1
swarm-master            virtualbox   Stopped                               swarm-master (master)
swarm-node-1            virtualbox   Stopped                               swarm-master
swarm-node-2            virtualbox   Stopped                               swarm-master
08:11:06::docker-964 ♨ >  echo $DOCKER_HOST
tcp://104.154.95.34:3376
08:11:13::docker-964 ♨ >  docker info
FATA[0032] An error occurred trying to connect: Get https://104.154.95.34:3376/v1.18/info: dial tcp 104.154.95.34:3376: i/o timeout
08:11:54::docker-964 ♨ >
```

**Comment by aperepel** [comment]
This is related to e.g. Azure (same problem) #640
The only mention of port 3376 I found was in the integration tests and AWS driver https://github.com/docker/machine/blob/2efadeaf090cc2c9228678c421c6869c95d21252/drivers/amazonec2/amazonec2.go#L35 - looks like they've implemented it there, but not for any other provider.

**Comment by ehazlett** [comment]
This should work if you specify the host to be a Swarm master.  See https://github.com/docker/machine/blob/master/drivers/google/compute_util.go#L103.

Closing.  Please re-open if you still experience the issue.  Thanks!

**Comment by aperepel** [comment]
@ehazlett this is not the case, hence this issue report. Both the original author and I designate the host to be a swarm master, please see below:

```
02:41:32::docker-964 ♨ >  docker-machine create \
>                --driver google \
>                --google-zone $GOOGLE_ZONE \
>                --google-machine-type $GOOGLE_MACHINE_TYPE \
>                --google-project $GOOGLE_PROJECT \
>                --swarm \
>                --swarm-master \
>                --swarm-discovery "token://xxx" \
>                $GOOGLE_NODENAME
...
Creating host...
Generating SSH Key
Creating instance.
Waiting for Instance...
Uploading SSH Key
Waiting for SSH Key
To see how to connect Docker to this machine, run: docker-machine env gce1
02:43:41::docker-964 ♨ >  docker-machine ls
NAME               ACTIVE   DRIVER   STATE     URL                                        SWARM
gce1               *        google   Running   tcp://104.154.76.147:2376                  gce1 (master)
02:43:52::docker-964 ♨ >  eval $(docker-machine env gce1)
02:44:07::docker-964 ♨ >  docker info
Containers: 2
Images: 7
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 11
 Dirperm1 Supported: true
Execution Driver: native-0.2
Kernel Version: 3.16.0-31-generic
Operating System: Ubuntu 14.04.2 LTS
CPUs: 2
Total Memory: 7.306 GiB
Name: gce1
ID: DPOG:EIOT:ORQK:2SRO:LQYH:DTGN:TKLX:LW76:6LSD:4AEE:S3OT:25OG
Username: aperepel
Registry: [https://index.docker.io/v1/]
WARNING: No swap limit support
Labels:
 provider=google
02:44:26::docker-964 ♨ >  eval $(docker-machine env --swarm gce1)
02:44:36::docker-964 ♨ >  docker info
FATA[0032] An error occurred trying to connect: Get https://104.154.76.147:3376/v1.18/info: dial tcp 104.154.76.147:3376: i/o timeout
02:45:11::docker-964 ♨ >
```

**Comment by ehazlett** [comment]
Ok.  I will take a look.  Thanks!

**Comment by aperepel** [comment]
@ehazlett can you please reopen the issue too? i can see how it can get lost in the swarm of release preparations.

**Comment by aperepel** [comment]
I see what's going on - the code checks for the presence of the `docker-machines` firewall rule, and doesn't dig in (making different assumptions from what I had in mind). The old rule was created by a previous docker-machine version. Once deleted, the rule got re-created with port 3376 open.

However, my approach was to tag a machine as a docker-swam and open the 3376 port **only** to this machine (remove the rule on machine delete as well). Current code just opens 3376 for every node - not ideal, as it increases an attack surface, but I guess ok for now. Thanks!

**Comment by ehazlett** [comment]
@aperepel yw -- i agree it widens the attack surface, however, with changing IPs (office vs. home, etc) I think we would run into connection issues often.  Thus, we choose to use all access (with TLS) by default and allow the user to change if desired.  Thanks for the feedback!
