### ISSUE TITLE
Random problem downloading docker

### ISSUE THREAD

**Issue by cjellick** [docker/machine#950]
We noticed the following problem when trying to launch a DO machine.
Please ignore/forgive the odd formatting. We are calling docker-machine from a golang program via `exec.Cmd`

docker-machin create -d digitalocean --digitalocean-image ubuntu-14-04-x64 --digitalocean-size 1gb --digitalocean-region nyc3 --digitalocean-access-token <redacted> foo1
```
stdout: time=\"2015-04-02T19:51:32Z\" level=\"info\" msg=\"Creating CA: /var/lib/cattle/machine/97e67f5e-ddfa-4675-b9d7-481035fd626d/certs/ca.pem\" "
"stdout: time=\"2015-04-02T19:51:33Z\" level=\"info\" msg=\"Creating client certificate: /var/lib/cattle/machine/97e67f5e-ddfa-4675-b9d7-481035fd626d/certs/cert.pem\" " 
"stdout: time=\"2015-04-02T19:51:34Z\" level=\"info\" msg=\"Creating SSH key...\" "
"stdout: time=\"2015-04-02T19:51:34Z\" level=\"info\" msg=\"Creating Digital Ocean droplet...\" "
"stdout: time=\"2015-04-02T19:51:38Z\" level=\"info\" msg=\"Waiting for SSH...\" "
"stdout: time=\"2015-04-02T20:58:52Z\" level=\"error\" msg=\"Error creating machine: error installing docker: exit status 255\\nbash: line 0: type: docker: not found\\n+ [ https://get.docker.com/ = https://get.docker.com/ ]\\n+ sh -c apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 36A1D7869245C8950F966E92D8576A8BA88D21E9\\ngpg: requesting key A88D21E9 from hkp server keyserver.ubuntu.com\\ngpg: key A88D21E9: public key \\\"Docker Release Tool (releasedocker) <docker@dotcloud.com>\\\" imported\\ngpg: Total number processed: 1\\ngpg:               imported: 1  (RSA: 1)\\n+ sh -c echo deb https://get.docker.com/ubuntu docker main > /etc/apt/sources.list.d/docker.list\\n+ sh -c sleep 3; apt-get update; apt-get install -y -q lxc-docker\\nConnection to 104.131.124.4 closed by remote host.\\r\\n\\n\" "
```

**Comment by ehazlett** [comment]
Yes this happens when the keyserver at ubuntu is having issues.  I think we need to get that key file and store on the cdn instead of requesting it from `keyserver.ubuntu.com` each time.

@tianon thoughts?

**Comment by ehazlett** [comment]
actually that looks like it does get the key now that i look again -- i still think we should keep the file on the cdn though :)

**Comment by ehazlett** [comment]
@cjellick that issue looks like the DO instance closed the connection thus killing the provisioning.

**Comment by tianon** [comment]
Why not switch to use http://pool.sks-keyservers.net/ instead?  It's much more reliable than any single keyserver is going to be, and won't have the MITM problems that fetching the key off our own CDN would.

**Comment by ehazlett** [comment]
@tianon perfect thanks!

**Comment by nathanleclaire** [comment]
> Why not switch to use http://pool.sks-keyservers.net/ instead?

We don't control that usually as we use the script from `get.docker.com` to install.

**Comment by thaJeztah** [comment]
is this still an issue with the new apt/yum repos in place?

**Comment by bmangold** [comment]
I just experienced this with docker-machine v0.2.0

**Comment by thaJeztah** [comment]
The 0.2 release doesn't use the new repos; that's new in 0.4 https://github.com/docker/machine/releases/tag/v0.4.0

@ehazlett does machine 0.4 also use the new repos for Ubuntu? (it isn't mentioned in the release notes)

**Comment by nathanleclaire** [comment]
If the Docker install script does not work, we cannot do much to workaround in our current model so I'm closing this as "NON-ACTIONABLE".

**Comment by thaJeztah** [comment]
@nathanleclaire just a heads-up: we're updating the install docs of docker to prefer manually adding the apt/yum repo's, because using `curl | sh` is not really best practice; https://github.com/docker/docker/pull/16662 (perhaps the provisioning scripts should be update at some point)

**Comment by nathanleclaire** [comment]
Thx @thaJeztah .  Over time I'd like to wean the Machine provisioning process off the script as well.

**Comment by tianon** [comment]
:cake:
