### ISSUE TITLE
DO OS types are not supported 

### ISSUE THREAD

**Issue by deniseschannon** [docker/machine#954]
I am trying to create different images using docker machine on Digital Ocean.

Currently, only ubuntu works and anytime I try the other images, I get a 'OS type not recognized' when trying other images (i.e. fedora, debian, coresos, centos).

Please forgive the odd formatting. We are calling docker-machine from a golang program via ```exec.cmd```.

docker-machine create -d digitalocean --digitalocean-image fedora-21-x64
 --digitalocean-size 1gb --digitalocean-region nyc3 --digitalocean-access-token mytoken

```bash
stdout: time=\"2015-04-03T16:22:24Z\" level=\"info\" msg=\"Creating CA: /var/lib/cattle/machine/16e12da7-70af-4f4f-ba05-df348bfcfef8/certs/ca.pem\" 
stdout: time=\"2015-04-03T16:22:24Z\" level=\"info\" msg=\"Creating client certificate: /var/lib/cattle/machine/16e12da7-70af-4f4f-ba05-df348bfcfef8/certs/cert.pem\"  
stdout: time=\"2015-04-03T16:22:26Z\" level=\"info\" msg=\"Creating SSH key...\"
stdout: time=\"2015-04-03T16:22:26Z\" level=\"info\" msg=\"Creating Digital Ocean droplet...\" 
stdout: time=\"2015-04-03T16:22:33Z\" level=\"info\" msg=\"Waiting for SSH...\" 
stdout: time=\"2015-04-03T16:23:06Z\" level=\"error\" msg=\"Error creating machine: OS type not recognized\" 
```

When can we expect the other OS to be fixed so that it works?

**Comment by UserTaken** [comment]
Expanding provisioning capabilities is in the milestone for v0.3.0 #905.

**Comment by ehazlett** [comment]
Closing as this will be in 0.3.0.
