### ISSUE TITLE
do not register hosts until successful/finished provision

### ISSUE THREAD

**Issue by crunchywelch** [docker/machine#959]
Right now, if you do a docker-machine ls, and a device is in the middle of a provision, or there are host entries that failed mid-provision but you haven't force removed yet, you get timeouts and errors. Same if you attempt other operations on a failed host or host still being provisioned. I'd propose we make an indicator that represents that a host is not ready or available to be operated on.

Most simple would be dropping a .lock file in the hosts config directory at the start of cmdCreate which gets removed at the end of that process, and if present then that host is not sourced in cmdLs(), etc.

More fancy would be a .state file, or attribute in the json, which which would give us more options to reflect the state of a host like "failed", "provisioning", "available" etc.

Thoughts?

**Comment by crunchywelch** [comment]
Also, I should say I'm happy to do this myself if folks think it is a good idea and we agree on an implementation strategy :)

**Comment by janeczku** [comment]
See related #972

**Comment by nathanleclaire** [comment]
It's getting created, so I want to err on the side of showing it.  It is much more common to leave cloud resources lingering than not, I'd prefer a way to detect / salvage them to leaving them unreferenced.
