### ISSUE TITLE
push docker configuration logic into provider files

### ISSUE THREAD

**Issue by crunchywelch** [docker/machine#961]
Right now we just pipe a string into a file location returned by the provider in libmachine/provision/utils.go over ssh like so:

`cmd, err = p.SSHCommand(fmt.Sprintf("echo \"%s\" | sudo tee -a %s", dkrcfg.EngineOptions, dkrcfg.EngineOptionsPath))`

but I think we should let the provider decide how to do this, for example, Centos7 (and presumably fedora, etc) use /etc/sysconfig/docker which should replace the `OPTIONS=` line with sed or something, and not overwrite the whole file.

Since we already are asking the providers for the docker conf file location and options with GenerateDockerOptions(), maybe we can just rename that to GenerateDockerConfig and get back a full command to run on ssh instead of the file path and arguments? Or maybe even more flexible would be to just ask for an error on failure, and let GenerateDockerConfig make the ssh call (or multiple calls if it needs to do more than configure that one file).

Thoughts?

**Comment by ehazlett** [comment]
+1.  In the current implementation, it was aimed at Ubuntu/b2d.  Moving forward, I think this makes sense to put in the provisioner.

/cc @nathanleclaire thoughts?

**Comment by nathanleclaire** [comment]
> but I think we should let the provider decide how to do this, for example, Centos7 (and presumably fedora, etc) use /etc/sysconfig/docker which should replace the OPTIONS= line with sed or something, and not overwrite the whole file.

Why not over-write the whole file?  I basically assume all bets are off about the default setup if we're configuring with Machine.  

I'm not opposed, just curious.  As long as it's the case that there's only one "config" file for the daemon to support, the current method should be fine - but I acknowledge that won't necessarily be the case forever.

**Comment by crunchywelch** [comment]
After thinking about this some more, I think it's ok to write over the
entire file for CentOs, but I haven't thought about how this might work
with rancher or coreos yet, there may be a good reason to let the provider
construct the entire command in those cases...

On Fri, Apr 10, 2015 at 6:51 PM, Nathan LeClaire <notifications@github.com>
wrote:

> but I think we should let the provider decide how to do this, for example,
> Centos7 (and presumably fedora, etc) use /etc/sysconfig/docker which should
> replace the OPTIONS= line with sed or something, and not overwrite the
> whole file.
>
> Why not over-write the whole file? I basically assume all bets are off
> about the default setup if we're configuring with Machine.
>
> I'm not opposed, just curious. As long as it's the case that there's only
> one "config" file for the daemon to support, the current method should be
> fine - but I acknowledge that won't necessarily be the case forever.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/docker/machine/issues/961#issuecomment-91711526>.
>



-- 

Aaron Welch
SVP of Product
---
212.933.9785 x301
welch@packet.net

**Comment by nathanleclaire** [comment]
Cool - I'm totally OK with moving over to doing it in a less prescriptive (from the "general" case) way if the needs of the provisioners demand it, but let's take a specific look at making sure that others need it that way before we implement it.  We can always just move the "current way" to a few helper methods that the current provisioners call if need be.

**Comment by nathanleclaire** [comment]
Each provisioner has the ability to take care of this on their own if need be, so I'm closing until we have some specific instances that we know are problematic.
