### ISSUE TITLE
Error message about host not existing is printed to stdout

### ISSUE THREAD

**Issue by bfirsh** [docker/machine#962]
The error message about the host not existing is printed to stdout, so this fails silently:

```
$ eval $(docker-machine env fdshkjlfsd)
$ 
```

**Comment by dave-tucker** [comment]
+1, it's not just the host not existing, but *any* error message
e.g `FATA[0000] Unexpected error getting machine url: exit status 255`
This happened to me today and I ended up running containers on the wrong docker host as I had assumed that the command had completed successfully :(

**Comment by ehazlett** [comment]
@tianon is there anything we can do here with the `eval`?  If machine exits non-zero would that cause the eval to show something?

**Comment by nathanleclaire** [comment]
@bfirsh @dave-tucker @ehazlett This should now be fixed, and if things that need to "leak" their output from a subshell don't do so it's a bug.  See: https://github.com/docker/machine/pull/1217 which cleans up the remaining thing we missed on this.

This was a huge reason we did the logging refactor: To clean up the granularity of what we print to STDOUT and STDERR.

Today on master I get:

```console
$ eval $(docker-machine env fdshkjlfsd)
Error: Host does not exist: fdshkjlfsd
```

**Comment by tianon** [comment]
@ehazlett yeah, what Nathan said -- exit code for eval isn't used, but stderr is not captured at all so it's definitely the appropriate place for error messages

**Comment by ehazlett** [comment]
@nathanleclaire @tianon perfect.  closing as this looks correct.
