### ISSUE TITLE
docs: documentation shows commands of version 0.2, but download links are 0.1

### ISSUE THREAD

**Issue by drish** [docker/machine#963]
Hey guys,

I'm a new-comer.

I've being going through the official docs, and seems that some driver options are only available for the version 0.2.x, but the download links are for version 0.1, which can be confusing for users.

For example:
>--digitalocean-ipv6: Enable IPv6 support for the droplet. Default: false
--digitalocean-private-networking: Enable private networking support for the droplet. Default: false
--digitalocean-backups: Enable Digital Oceans backups for the droplet. Default: false

Those three options are only available on machine version 0.2.x+, making the `create` commands to fail when providing any these options.

Should the download links be updated to a new machine version ?

Thanks in advance.

**Comment by ehazlett** [comment]
It looks like the docs were pushed a bit prematurely.  I will follow up.  Thanks!
