### ISSUE TITLE
Proposal: Logging cleanup

### ISSUE THREAD

**Issue by nathanleclaire** [docker/machine#967]
The current method of outputting information from Docker Machine commands is a bit of an awkward fit.  The majority of code uses `logrus` to print things to the terminal, and while `logrus` is a great package there are a few issues:

- We'd like finer-grained control over what goes to STDOUT and STDERR
- Current output looks not so great on Windows
- `logrus` is meant more for long-running applications than for the ad-hoc sort of commands invoked using `docker-machine`; while Machine may run as a long-lived daemon or server someday, we aren't quite ready to move to that model yet.

Because we have so much code that uses `logrus` and don't want to chuck this method of outputting information out completely, this proposal is to wrap the existing `log.*` calls with our own package (`github.com/docker/machine/log`?) which will give us more control over the result of these calls.

That way, all of the existing code which uses, say, `log.Warnf` will simply wrap calls to `fmt.Printf`, calls to `log.Errorf` will wrap `fmt.Fprintf(os.Stderr`, etc.

In general, I'm thinking that what I want to do is make an interface with the relevant methods, and have several swappable "backends" e.g. `terminal`, `file`, `logstash` so that we could take advantage of the versatility `logrus` provides at some point down the line here.   Similar to what we do with hosting providers or underlying OSes.  And `terminal` being the simplest, it would be the default.

Sticking points:

- What to do about `log.WithFields`?  The Openstack / Rackspace drivers use this non-trivially and I don't really want to just chuck it out, but it will be difficult to reconcile with this proposal since it seems to mandate including `logrus` directly.  We could wrap that stuff too I guess.
- Might want to consider adding some timing data e.g. "Your machine create took X seconds" since one of the things I like about the existing method is that you can get a feel for how long something's been running or took to run by looking at the second counter.

cc @ehazlett @sthulb @bfirsh

**Comment by sthulb** [comment]
+1 The logging implementation is rather out of place with what I'd expect in a client app.

I guess for now, we should perhaps wrap go's native `log` package with `docker/machine/log`, but this would be a stop-gap for a better solution later.

**Comment by ehazlett** [comment]
+1 for cleaner and "standard" log formats across drivers and platforms.  After glancing into `logrus` I wonder if we should look into the hooks and formatters?  This way we wouldn't have to implement / maintain the various backends ourselves and potentially re-use it if/when a server version happens.  If it doesn't fit then we could roll our own.  Just a thought.

As far as the WithFields, perhaps we could just add that content inline with the appropriate field?  Something like `Creating instance: name=foo type=m1.large` instead of the specific WithFields format?  /cc @ggiamarchi thoughts?

Overall, +1 to the proposal :)

**Comment by nathanleclaire** [comment]
> After glancing into logrus I wonder if we should look into the hooks and formatters? This way we wouldn't have to implement / maintain the various backends ourselves and potentially re-use it if/when a server version happens. If it doesn't fit then we could roll our own. Just a thought.

I'd definitely like to re-use as much as possible.  Maybe we could include as part of the architecture a logrus driver with an "Options" struct that could be used to configure this sort of thing (if we implement logging through a standard interface, logrus-specific features will have to be exposed through that interface somehow).

**Comment by ggiamarchi** [comment]
Actually, i originally widely used `WithFields` in the OpenStack driver just because i like the log output which is very clear but i don't see any problem to replace it by another API. Log format proposed by @ehazlett looks good :+1:
