### ISSUE TITLE
SSH issues and VMware Fusion

### ISSUE THREAD

**Issue by lloeki** [docker/machine#969]
Using docker-machine 0.1 (from homebrew), I can't create a VMware Fusion machine (7.1.1 (2498930)) anymore due to SSH suddenly being stubbornly uncooperative:

```
$ docker-machine create -d vmwarefusion dev1
INFO[0000] Creating CA: /Users/lloeki/.docker/machine/certs/ca.pem 
INFO[0000] Creating client certificate: /Users/lloeki/.docker/machine/certs/cert.pem 
INFO[0001] Downloading boot2docker.iso to /Users/lloeki/.docker/machine/cache/boot2docker-vmw.iso... 
INFO[0033] Creating SSH key...                          
INFO[0034] Creating VM...                               
INFO[0037] Waiting for VM to come online...             
ERRO[0061] Error creating machine: dial tcp 192.168.138.129:22: connection refused 
WARN[0061] You will want to check the provider to make sure the machine and associated resources were properly removed. 
FATA[0061] Error creating machine                       
```

Sometimes, instead of being uncooperative, SSH is just being lazy as I get a timeout error.

Issue confirmed on two distinct machines (one on OS X 10.10.2, the other on 10.10.3 beta). Virtualbox works fine but I'd rather continue using Fusion as it happens to be much more battery-friendly.

**Comment by nathanleclaire** [comment]
Could you try the [RC](https://github.com/docker/machine/releases/tag/v0.2.0-rc3) please to see if it works better for you?

**Comment by lloeki** [comment]
Workie! Here's hoping it's not a fluke. Let me confirm that at work tomorrow.

**Comment by lloeki** [comment]
It seems to be ok on my second machine too.

**Comment by nathanleclaire** [comment]
Great!  Do you feel like we can close this ticket?

**Comment by lloeki** [comment]
Sure, thanks.
