### ISSUE TITLE
Starting VMware Fusion app makes the VM go headful in some cases

### ISSUE THREAD

**Issue by lloeki** [docker/machine#975]
- create and start a VMware Fusion machine via docker-machine
- start the VMware Fusion app
- the VM that should stay headless is displayed in a window
- the VM that should stay ignored from the library is registered into the library
- the VM will be suspended or shut down when quitting the VMware Fusion app

The last two items don't happen if:
- the VM is stopped via docker-machine before starting the VMware Fusion app
- the VMware Fusion app is started before docker-machine starts the VM

Workaround when this happens:
- stop the VM via docker-machine stop
- delete the VM from the library but "keep file" when asked
- now one can either quit the VMware Fusion app or start the VM again (complying with the "don't happen" case)

**Comment by sthulb** [comment]
This is an issue with VMware fusion rather than docker-machine, the same behaviour happens with Vagrant too...

Maybe @frapposelli will be able to shed light on this too.

But this is also a dupe of: #788

**Comment by sthulb** [comment]
> There is no workaround/fix at the moment, the only way to keep the VM headless is to avoid opening the Fusion GUI, I'm raising this with the Fusion team internally as this doesn't happen with VMware Workstation on Windows/Linux. – @frapposelli on #788

**Comment by lloeki** [comment]
OK I suspected so. I will patiently wait, and follow further developments on #788.
