### ISSUE TITLE
Documentation home page should point at GitHub, IRC, etc

### ISSUE THREAD

**Issue by bfirsh** [docker/machine#976]
http://docs.docker.com/machine/ is currently the landing page for Machine. A few cases this page doesn't cater for:

- Somebody wants some help using Machine, in which case we should point them at the mailing list or IRC channel
- Somebody wants to suggest features, report bugs or contribute code, in which case we should point them at GitHub

I think we should have links off to those things somewhere. @ehazlett @nathanleclaire @fredlf - WDYT?

**Comment by ehazlett** [comment]
SGTM

**Comment by nathanleclaire** [comment]
Absolutely.  I'll put in a quick PR for it actually...

**Comment by fredlf** [comment]
Yes, we should have the same boilerplate for all three tools. Good idea. Nathan, you can probably just point people here: https://docs.docker.com/project/get-help/

**Comment by nathanleclaire** [comment]
Nice @fredlf I will definitely include that link; I want a little blurb specific to us too, so we can talk about it in the PR.

**Comment by fredlf** [comment]
Sounds good, @nathanleclaire, go get 'em Tiger.
