### ISSUE TITLE
ssh - can't use commands with args

### ISSUE THREAD

**Issue by cpuguy83** [docker/machine#977]
When using `docker-machine ssh <name> <command>`, you can pass in as manyh args to `<command>` as you like... unless they are traditional cli args that start with a `-`... in that case it's interpreting the args as being passed into docker-machine and not to the ssh command.

**Comment by bclaridge** [comment]
Have you tried wrapping  ```<command>``` in quotes? 

```docker-machine ssh my-machine "docker -v" worked for me

**Comment by cpuguy83** [comment]
Ah yes, of course. This works, silly me.
Closing.

**Comment by jorahn** [comment]
Is there a specific reason, why `docker-machine ssh` takes multi-word commands only in quotes while `docker exec` doesn't allow quotes? I realize these do different things, but in my current workflow I stumbled over this a couple of times and just wanted to let you know.

    docker Client/Server version 1.7.0, API versions 1.19
    docker-machine version 0.3.0

**Comment by cpuguy83** [comment]
They use completely different cli libraries.

**Comment by jorahn** [comment]
thanks for your reply. i'm aware of that, it's just a comment towards api design

**Comment by cpuguy83** [comment]
Really the "right" way is to do a double-dash to split cli args from args to the app that's going to be exec'd
