### ISSUE TITLE
Add support for SoftLayer Local disk on VMs 

### ISSUE THREAD

**Issue by huslage** [docker/machine#982]
The SoftLayer API supports Local disk via the `localDiskFlag` boolean parameter. Please expose this so that we can create VMs with Local disk.

```python
client['Virtual_Guest'].createObject({
    'hostname': 'myhostname',
    'domain': 'example.org',
    'startCpus': 1,
    'maxMemory': 1024,
    'hourlyBillingFlag': 'true',
    'operatingSystemReferenceCode': 'UBUNTU_LATEST',
    'localDiskFlag': 'false'
})
```

**Comment by ehazlett** [comment]
Thanks!  This option is supported via the `--softlayer-local-disk` option.  See https://github.com/docker/machine/blob/master/docs/index.md#ibm-softlayer for details.

**Comment by mbentley** [comment]
Upon further investigation, it looks like the driver doesn't actually sent and pass the localdisk option.  The option is there in machine but it essentially isn't doing anything.
