### ISSUE TITLE
Machine should manage credentials for drivers

### ISSUE THREAD

**Issue by dave-tucker** [docker/machine#987]
I find that managing env variables for the various drivers to be a little clumsy. Not only are there issues related to me accidentally putting these in my `.zshrc` which is hosted on GitHub, but it's tricky to manage multiple accounts with the same provider.

For example, consider DigitalOcean, where I have a "personal" account and a "company" account.
To perform operations on  one, or the other, I'd need to make sure to `source` the correct file first or the API calls would fail.

I'd like to see something along the lines of:
```
docker-machine account create -d digitalocean dave
... prompts for the required credentials...
Account "dave" for DigitalOcean created successfully

docker-machine account create -d digitalocean work
... prompts for the required credentials...
Account "work" for DigitalOcean created successfully 

docker-machine create -d digitalocean --account dave
```
I would expect machine to securely store the minimum amount of information required. Perhaps in `~/.docker/accounts`

**Comment by ehazlett** [comment]
We are looking at adding support for this in #773.  Not sure on timeline though.

**Comment by dave-tucker** [comment]
Cool! Thanks @ehazlett

**Comment by ehazlett** [comment]
yw!  this is ref'd in that issue -- feel free to re-open if you have other ideas or questions.  thanks!
