### ISSUE TITLE
Docker unable to connect to VM after restarting laptop.

### ISSUE THREAD

**Issue by michaelbarton** [docker/machine#99]
Client version: 1.3.1-dev
Client API version: 1.16
Go version (client): go1.3.3
Git commit (client): 831d09f
OS/Arch (client): darwin/amd64

I used docker machine successfully last night and turned of my laptop. This
morning I turned my laptop back on and ran the following commands:

    machine start dev
    machine active dev
    DOCKER_HOST=$(machine url) DOCKER_AUTH=identity docker build --tag=target .

I however get the following error:

    FATA[0000] TLS Handshake error: remote error: bad certificate

I can fix this:

    machine stop dev
    machine rm dev
    machine create -d virtualbox dev

However I lose all the cached layers in my previous VM.

**Comment by michaelbarton** [comment]
I've just tried to download and build the master branch of docker/machine to test this, unfortunately I can't build this as it requires a running version of docker. Could you share a compiled build or newer release for me test? Thank you.

**Comment by ehazlett** [comment]
Closing this as #111 has been merged.  Please re-open if you continue to have issues.  Thanks!
