### ISSUE TITLE
[GCE] Why imgeName do not update?

### ISSUE THREAD

**Issue by zchee** [docker/machine#994]
Hi,

imgeName on google driver is `ubuntu-1404-trusty-v20150128`, but The latest version ubuntu-1404-trusty-v20150316.
Why?

**Comment by zchee** [comment]
And if necessary, I will pr.

**Comment by zchee** [comment]
I think that it may be to flag.
How you do you feel about it?

**Comment by ehazlett** [comment]
Thanks!  It simply hasn't been updated.  Feel free to send a PR.
