### ISSUE TITLE
`machine ip` chained arguments

### ISSUE THREAD

**Issue by frntn** [docker/machine#999]
## What I do

I use the `ip` command to get the ip list of my two servers :

```bash
~$ docker-machine ls
NAME    ACTIVE   DRIVER         STATE     URL                         SWARM
nodeA            digitalocean   Running   tcp://x.x.x.x:2376   
nodeB   *        digitalocean   Running   tcp://y.y.y.y:2376   

~$ 
```

## What I get

I only get the first IP of the list :

```bash
~$ docker-machine ip $(docker-machine ls -q)
x.x.x.x

~$ 
```

## What I expected

I expected to have the same behaviour as the `rm` command.
So I expected to see the following ouput :

```bash
~$ docker-machine ip $(docker-machine ls -q)
x.x.x.x
y.y.y.y

~$ 
```

**Comment by UserTaken** [comment]
In the meanwhile you can run something like `for i in $(docker-machine ls -q); do docker-machine ip $i; done` as a workaround.

**Comment by frntn** [comment]
Hehe yes that's what I do actually
Thanks anyway :)

**Comment by ehazlett** [comment]
Thanks for the feedback.  Yes this looks reasonable to use -- I expect it to show all IPs :)

**Comment by nathanleclaire** [comment]
Yes commands like `docker-machine start foo bar spam` will work on all 3 so we should probably support this.
